= Jenkins Security Advisory 2017-11-08
:kind: core

== Descriptions

=== Unsafe use of usernames as directory names

==== SECURITY-499 / CVE-2017-1000391

==== Severity (CVSS): https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:L/UI:R/S:U/C:N/I:L/A:L[low]

==== Description

Jenkins stores metadata related to _people_, which encompasses actual user accounts, as well as users appearing in SCM, in directories corresponding to the user ID on disk.
These directories used the user ID for their name without additional escaping.
This potentially resulted in a number of problems, such as the following:

. Usernames consisting of a single forward slash would have their user record stored in the parent directory; deleting this user deleted all user records.
. Usernames containing character sequences such as `..` could be used to clobber other configuration files in Jenkins.
. Usernames could consist of reserved names such as `COM` (on Windows).

This is not limited to the _Jenkins user database_ security realm, other security realms such as LDAP may allow users to create usernames that result in problems in Jenkins.

Usernames are now transformed into a filesystem-safe representation that is used as directory name.


=== Persisted XSS vulnerability in autocompletion suggestions

==== SECURITY-641 / CVE-2017-1000392

==== Severity (CVSS): https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:H/UI:R/S:U/C:L/I:L/A:N[low]

==== Description
Autocompletion suggestions for text fields were not escaped, resulting in a persisted cross-site scripting vulnerability if the source for the suggestions allowed specifying text that includes HTML metacharacters like less-than and greater-than characters.

Known previously unsafe sources for these suggestions include the names of loggers in the log recorder condition, and agent labels.

Autocompletion suggestions are now escaped and can no longer contain HTML-based formatting.


== Severity

* *SECURITY-499* - https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:H/UI:R/S:U/C:L/I:L/A:N[low]
* *SECURITY-641* - https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:H/UI:R/S:U/C:L/I:L/A:N[low]


== Affected Versions

* *Jenkins weekly* up to and including 2.88
* *Jenkins LTS* up to and including 2.73.2


== Fix

* *Jenkins weekly* should be updated to version 2.89
* *Jenkins LTS* should be updated to version 2.73.3

These versions include fixes to the vulnerabilities described above. All prior versions are considered to be affected by these vulnerabilities unless otherwise indicated.


== Credits
The Jenkins project would like to thank the reporters for discovering and xref:index.adoc#reporting-vulnerabilities[reporting] these vulnerabilities:

* *Darren Zhao* for SECURITY-499
* *Viktor Gazdag of NCC Group* for SECURITY-641


== Other Resources
* link:https://www.jenkins.io/blog/2017/11/08/security-updates/[Announcement blog post]