= AbsInt a³ Jenkins Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/absint-a3">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'A3Builder'])`: a³ Analysis Run
++++
<ul><li><code>project_file : String</code>
<div><div>
 Absolute path to the a³ <b>project</b> file (.apx) containing the analysis items and configuration.
 <br>
  (Note: a³ workspace files (also .apx) are not supported as input.)
</div></div>

</li>
<li><code>analysis_ids : String</code>
<div><div>
 The following values are allowed: 
 <ul>
  <li>Comma separated list of analysis IDs. Then only the given analysis items will be executed. Note: The ID must be contained in the apx project and must adhere the analysis ID naming conventions (letters, numbers and underscores only).</li>
  <li>No ID at all (i.e. empty field). Then <b>all</b> analysis items specified in the apx project file will be executed.</li>
 </ul>
</div></div>

</li>
<li><code>pedantic_level : String</code>
</li>
<li><code>export_a3apxworkspace : String</code>
<div><div>
 Exports the status of a³ at the end of the a³ analysis build step run as a workspace .apx file. This workspace file can later be opened in an interactive run of a³. The result is that the a³ GUI then shows all messages and all results generated by the batch-mode analyses without the need to run these analyses again.
</div></div>

</li>
<li><code>copy_report_file : boolean</code>
</li>
<li><code>copy_result_file : boolean</code>
</li>
<li><code>skip_a3_analysis : boolean</code>
<div><div>
 This switch can be used to deactivate the a³ analysis build step. This switch provides a more convenient method to temporarily deactivate analysis runs than removing the entire build step and reconfiguring the a³ analysis run from scratch when later adding the build step again.
</div></div>

</li>
</ul>


++++
