= ACCELQ CI-Connect Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/accelq-ci-connect">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'AQPluginBuilderAction'])`: ACCELQ Connect
++++
<ul><li><code>jobId : String</code>
<div><div>
 This ID should come from the CI job you saved in ACCELQ application
</div></div>

</li>
<li><code>apiKey</code>
<div><div>
 API key available in Profile section of ACCELQ
</div></div>

<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>appURL : String</code>
<div><div>
 Your ACCELQ Application URL in the exact following format: 
 <br>
 <pre>https://&lt;hostname&gt;:&lt;port_num&gt;</pre>
</div></div>

</li>
<li><code>runParamStr : String</code>
<div><div>
 Run Params should be JSON string form example: <strong>{"username": "John Todd", "password": "bxW&amp;=UVw"}</strong>
</div></div>

</li>
<li><code>tenantCode : String</code>
<div><div>
 Tenant Code displayed in the Profile section of ACCELQ
</div></div>

</li>
<li><code>userName : String</code>
<div><div>
 Your ACCELQ User ID
</div></div>

</li>
<li><code>proxyHost : String</code>
</li>
<li><code>proxyPort : String</code>
</li>
<li><code>stepFailureThreshold : String</code>
<div><div>
 Percentage ACCELQ test case failure, beyond which this Step in the Pipeline will be marked as a failure. If this is zero, even a single failed test will cause the Step to fail. If you never want to fail the Pipeline Step due to failing Automation tests, input -1. Input a valid integer between 0 and 100 or, -1.
</div></div>

</li>
<li><code>maxWaitTimeInMins : String</code>
<div><div>
 Maximum time to wait for the job to be picked up by an ACCELQ Agent. Default is 15 mins.
</div></div>

</li>
<li><code>disableSSLCheck : boolean</code>
</li>
</ul>


++++
