= Acunetix
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/acunetix">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'BuildScanner'])`: Acunetix
++++
<div><div>
 Trigger automated Acunetix scans as part of your web application's build process
</div></div>
<ul><li><code>profile : String</code>
<div><div>
 The Scan Type used to scan the target
</div></div>

</li>
<li><code>target : String</code>
<div><div>
 The Scan Target on which to run a scan (excludes Targets requiring Manual Intervention)
</div></div>

</li>
<li><code>repTemp : String</code>
<div><div>
 Generate a Report after the scan completes. The report is available for download from Acunetix backend within a time frame of one hour
</div></div>

</li>
<li><code>threat : String</code>
<div><div>
 The Threat Level (High, Medium, Low) to fail the build on
</div></div>

</li>
<li><code>stopScan : boolean</code>
<div><div>
 If selected, the scan will be stopped if the build fails (Threat Level is reached)
</div></div>

</li>
<li><code>svRep : boolean</code>
<div><div>
 Option to download the report in the project workspace from where it can be used for other operations like attaching to an email or archiving.
 <br>
  Note: Archiving can be done with "Archive the artifacts" post-build action
</div></div>

</li>
<li><code>incScan : boolean</code>
<div><div>
 This will create an Incremental scan. The first scan will scan all the site. Subsequent scans will only scan the changes in the site, resulting in smaller scans.
</div></div>

</li>
<li><code>incScanId : String</code>
</li>
<li><code>stopTargetScans : boolean</code>
<div><div>
 This is useful when older versions of the web application are discarded by the CI/CD when an updated version is created.
</div></div>

</li>
</ul>


++++
