= Alauda DevOps Pipeline Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/alauda-devops-pipeline">Visit the Jenkins Plugins site</a>
++++


=== `base64Decode`: Decode Base64 string
++++
<ul><li><code>encodedString : String</code>
</li>
</ul>


++++
=== `_AcpAction`: Internal utility function for DevOps DSL
++++
<ul><li><code>server : String</code>
</li>
<li><code>project : String</code>
</li>
<li><code>skipTLSVerify : boolean</code>
</li>
<li><code>caPath : String</code>
</li>
<li><code>verb : String</code>
</li>
<li><code>advArgs</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>verbArgs</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>userArgs</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>options</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>token : String</code>
</li>
<li><code>streamStdOutToConsolePrefix : String</code>
</li>
<li><code>reference</code>
<ul><li><b>Type:</b> <code>java.util.HashMap&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>logLevel : int</code>
</li>
</ul>


++++
=== `_AcpContextInit`: Internal utility function for Devops DSL
++++
<ul></ul>


++++
=== `_OcWatch`: Internal utility function for Devops DSL
++++
<ul><li><code>server : String</code>
</li>
<li><code>project : String</code>
</li>
<li><code>skipTLSVerify : boolean</code>
</li>
<li><code>caPath : String</code>
</li>
<li><code>verb : String</code>
</li>
<li><code>advArgs</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>verbArgs</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>userArgs</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>options</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>token : String</code>
</li>
<li><code>logLevel : int</code>
</li>
</ul>


++++
