= Alibaba Cloud ECS Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/alibabacloud-ecs">Visit the Jenkins Plugins site</a>
++++


=== `EcsTemplate`: EcsTemplateStep
++++
<ul><li><code>attachPublicIp : boolean</code> (optional)
</li>
<li><code>chargeType : String</code> (optional)
</li>
<li><code>cloudName : String</code> (optional)
</li>
<li><code>connectionStrategy</code> (optional)
<ul><li><b>Values:</b> <code>PUBLIC_IP</code>, <code>PRIVATE_IP</code></li></ul></li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>dataDiskCategory : String</code> (optional)
</li>
<li><code>dataDiskSize : String</code> (optional)
</li>
<li><code>ecsType</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'UnixData'</code><div>
<ul></ul></div></li>
<li><code>$class: 'WindowsData'</code><div>
<ul><li><code>password : String</code>
<div><div>
 Instance login password, 8~30 characters, including three items (uppercase, lowercase, numbers, numbers, ()`~@#$%^&amp;*_=|{}[]:;'&lt;&gt; ,.?/ special symbols in the middle order), cannot be preceded by a slash (/)
</div></div>

</li>
<li><code>useHTTPS : boolean</code>
</li>
<li><code>bootDelay : String</code>
<div><div>
 Indicate here the time in seconds to wait for the machine to be ready once the plugin detects WinRM is available. Unfortunately, on Windows during the boot, the WinRM service might be started, and then several minutes after will be restarted. If this restart happens during the agent provisioning that Jenkins does, Windows will prevent the WinRM client to connect again and the agent will not be correctly provisioned. 
 <br>
  A safe value has been found to be 3 minutes.
</div></div>

</li>
<li><code>specifyPassword : boolean</code>
</li>
<li><code>allowSelfSignedCertificate : boolean</code>
</li>
</ul></div></li>
</ul></li>
<li><code>idleTerminationMinutes : String</code> (optional)
</li>
<li><code>image : String</code> (optional)
</li>
<li><code>initScript : String</code> (optional)
</li>
<li><code>instanceCap : String</code> (optional)
</li>
<li><code>instanceCapStr : String</code> (optional)
</li>
<li><code>instanceType : String</code> (optional)
</li>
<li><code>intranetMaster : boolean</code> (optional)
</li>
<li><code>labels : String</code> (optional)
</li>
<li><code>launchTimeout : String</code> (optional)
</li>
<li><code>maxTotalUses : String</code> (optional)
</li>
<li><code>minimumNumberOfInstances : String</code> (optional)
</li>
<li><code>mountDataDisk : boolean</code> (optional)
</li>
<li><code>mountQuantity : String</code> (optional)
</li>
<li><code>name : String</code> (optional)
</li>
<li><code>noDelayProvisioning : boolean</code> (optional)
</li>
<li><code>numExecutors : String</code> (optional)
</li>
<li><code>region : String</code> (optional)
</li>
<li><code>remoteAdmin : String</code> (optional)
</li>
<li><code>remoteFs : String</code> (optional)
</li>
<li><code>securityGroup : String</code> (optional)
</li>
<li><code>sshKey : String</code> (optional)
</li>
<li><code>systemDiskCategory : String</code> (optional)
</li>
<li><code>systemDiskSize : int</code> (optional)
</li>
<li><code>tags</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>templateName : String</code> (optional)
</li>
<li><code>userData : String</code> (optional)
</li>
<li><code>vpc : String</code> (optional)
</li>
<li><code>vsw : String</code> (optional)
</li>
<li><code>zone : String</code> (optional)
</li>
</ul>


++++
=== `alibabaEcs`: Cloud template provisioning
++++
<div><div>
 Creates an <code>Aliyun ECS Spot Instance</code> object, from an already globally defined cloud name and template without registering it as a Jenkins agent.
</div></div>
<ul><li><code>cloud : String</code>
</li>
<li><code>template : String</code>
</li>
</ul>


++++
