= EDAS Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/alibabacloud-edas">Visit the Jenkins Plugins site</a>
++++


=== `edasClient`: Deploy to EDAS
++++
<ul><li><code>extensions</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>deployEDASApplication</code><div>
<ul><li><code>namespace : String</code>
<div><div>
 The EDAS namespace, please check with ListUserDefineRegion
</div></div>

</li>
<li><code>credentialId : String</code>
</li>
<li><code>group : String</code>
<div><div>
 The deploy group ID of EDAS application. Set this parameter to "all" if you want to deploy the application to all groups
</div></div>

</li>
<li><code>appId : String</code>
<div><div>
 The ID of the EDAS Application that you want to deploy
</div></div>

</li>
<li><code>targetObject : String</code>
<div><div>
 The path of file to deploy
</div></div>

</li>
<li><code>batch : String</code> (optional)
<div><div>
 The batch of this deployment
</div></div>

</li>
<li><code>batchWaitTime : String</code> (optional)
<div><div>
 The wait time between batches
</div></div>

</li>
<li><code>endpoint : String</code> (optional)
</li>
<li><code>releaseType : String</code> (optional)
<div><div>
 The release type of batch deployment
</div></div>

</li>
<li><code>versionDescriptionFormat : String</code> (optional)
<div><div>
 Sets the description of the version to be published. Jenkins environment variables are supported such as ${GIT_BRANCH} - ${BUILD_TAG}
</div></div>

</li>
<li><code>versionLabelFormat : String</code> (optional)
<div><div>
 How to set the version label? For instance, for "${GIT_COMMIT}-${BUILD_TAG}", and with "Key Prefix" set to "myapp/builds/myapp-prod-env/", the S3 Object Key is set to myapp/builds/myapp-prod-env/4b5f7669b3376a1ce504bf7ef8bf7aeee9d21746-myjob-41.zip and the version Label will be 4b5f7669b3376a1ce504bf7ef8bf7aeee9d21746-myjob-41
</div></div>

</li>
</ul></div></li>
<li><code>InsertEDASApplication</code><div>
<ul><li><code>namespace : String</code>
<div><div>
 The EDAS namespace, please check with ListUserDefineRegion
</div></div>

</li>
<li><code>credentialId : String</code>
</li>
<li><code>applicationName : String</code>
<div><div>
 The EDAS Application Name to Create
</div></div>

</li>
<li><code>targetObject : String</code>
<div><div>
 The path of file to deploy
</div></div>

</li>
<li><code>clusterId : String</code>
<div><div>
 The ID of cluster to deploy EDAS application
</div></div>

</li>
<li><code>packageType : String</code>
<div><div>
 The package type of application (e.g. : "war")
</div></div>

</li>
<li><code>ecuInfo : String</code>
<div><div>
 The ID of the Elastic Compute Unit (ECU) to deploy the application. Use ListScaleOutEcu to get ecu id
</div></div>

</li>
<li><code>buildPackId : String</code> (optional)
<div><div>
 The package ID of Enterprise Distributed Application Service (EDAS) Container, which can be retrieved by calling container version list interface ListBuildPack or the "Pack ID" column in container version list. When creating High-speed Service Framework (HSF) application, this parameter is required.
</div></div>

</li>
<li><code>endpoint : String</code> (optional)
</li>
<li><code>healthCheckUrl : String</code> (optional)
<div><div>
 The URL for health checking of the application
</div></div>

</li>
<li><code>versionDescriptionFormat : String</code> (optional)
<div><div>
 Sets the description of the version to be published. Jenkins environment variables are supported such as ${GIT_BRANCH} - ${BUILD_TAG}
</div></div>

</li>
<li><code>versionLabelFormat : String</code> (optional)
<div><div>
 How to set the version label? For instance, for "${GIT_COMMIT}-${BUILD_TAG}", and with "Key Prefix" set to "myapp/builds/myapp-prod-env/", the S3 Object Key is set to myapp/builds/myapp-prod-env/4b5f7669b3376a1ce504bf7ef8bf7aeee9d21746-myjob-41.zip and the version Label will be 4b5f7669b3376a1ce504bf7ef8bf7aeee9d21746-myjob-41
</div></div>

</li>
</ul></div></li>
<li><code>deployEDASK8sApplication</code><div>
<ul><li><code>namespace : String</code>
<div><div>
 The EDAS namespace, please check with ListUserDefineRegion
</div></div>

</li>
<li><code>credentialId : String</code>
</li>
<li><code>appId : String</code>
<div><div>
 The ID of the EDAS Application that you want to deploy
</div></div>

</li>
<li><code>targetObject : String</code>
<div><div>
 The path of file to deploy. Local file, remote url and image url permitted
</div></div>

</li>
<li><code>image : boolean</code>
</li>
<li><code>args : String</code> (optional)
<div><div>
 JsonArray of command arguments.(e.g.: [{"argument":"-c"},{"argument":"test"}])
</div></div>

</li>
<li><code>cpuLimit : String</code> (optional)
<div><div>
 CPU limit, unit: millicores
</div></div>

</li>
<li><code>cpuRequest : String</code> (optional)
<div><div>
 CPU request, unit: millicores
</div></div>

</li>
<li><code>edasContainerVersion : String</code> (optional)
<div><div>
 The version of EDAS container. Required when deploy war package
</div></div>

</li>
<li><code>endpoint : String</code> (optional)
</li>
<li><code>envs : String</code> (optional)
<div><div>
 The jsonArray of envs.(e.g.: [{"name":"testkey","value":"testValue"}]) Set [] to clear settings
</div></div>

</li>
<li><code>jdk : String</code> (optional)
<div><div>
 The version of JDK
</div></div>

</li>
<li><code>liveness : String</code> (optional)
<div><div>
 e.g.: {"failureThreshold": 3,"initialDelaySeconds": 5,"successThreshold": 1,"timeoutSeconds": 1,"httpGet": {"path": "/consumer","port": 8080,"scheme": "HTTP","httpHeaders": [{"name": "test","value": "testvalue"}]}}. Set empty of {} to clear, "unchanging" means no changing
</div></div>

</li>
<li><code>memoryLimit : String</code> (optional)
</li>
<li><code>memoryRequest : String</code> (optional)
</li>
<li><code>postStart : String</code> (optional)
<div><div>
 e.g.: {"exec":{"command":"cat","/etc/group"}}. Set empty of {} to clear, "unchanging" means no changing
</div></div>

</li>
<li><code>preStop : String</code> (optional)
<div><div>
 e.g.: {"exec":{"command":"cat","/etc/group"}}. Set empty of {} to clear, "unchanging" means no changing
</div></div>

</li>
<li><code>readiness : String</code> (optional)
<div><div>
 e.g.: {"failureThreshold": 3,"initialDelaySeconds": 5,"successThreshold": 1,"timeoutSeconds": 1,"httpGet": {"path": "/consumer","port": 8080,"scheme": "HTTP","httpHeaders": [{"name": "test","value": "testvalue"}]}}. Set empty of {} to clear, "unchanging" means no changing
</div></div>

</li>
<li><code>replicas : String</code> (optional)
<div><div>
 The number of pods
</div></div>

</li>
<li><code>startupCommand : String</code> (optional)
<div><div>
 The startup command
</div></div>

</li>
<li><code>updateStrategy : String</code> (optional)
<div><div>
 e.g.: {"type":"GrayBatchUpdate","batchUpdate":{"batch":2,"releaseType":"auto","batchWaitTime":1},"grayUpdate":{"gray":1}}. Please check usage from pop api DeployK8sApplication
</div></div>

</li>
<li><code>versionLabelFormat : String</code> (optional)
<div><div>
 How to set the version label? For instance, for "${GIT_COMMIT}-${BUILD_TAG}", and with "Key Prefix" set to "myapp/builds/myapp-prod-env/", the S3 Object Key is set to myapp/builds/myapp-prod-env/4b5f7669b3376a1ce504bf7ef8bf7aeee9d21746-myjob-41.zip and the version Label will be 4b5f7669b3376a1ce504bf7ef8bf7aeee9d21746-myjob-41
</div></div>

</li>
<li><code>webContainer : String</code> (optional)
<div><div>
 The version of tomcat(e.g. "Apache Tomcat 7.0.91"). Required when deploy war package
</div></div>

</li>
</ul></div></li>
<li><code>insertEDASK8sApplication</code><div>
<ul><li><code>credentialId : String</code>
</li>
<li><code>namespace : String</code>
<div><div>
 The EDAS namespace, please check with ListUserDefineRegion
</div></div>

</li>
<li><code>clusterId : String</code>
<div><div>
 The ID of cluster to deploy EDAS application
</div></div>

</li>
<li><code>k8sNamespace : String</code>
<div><div>
 The K8s namespace where application to deploy. (e.g. : "default")
</div></div>

</li>
<li><code>applicationName : String</code>
<div><div>
 The EDAS Application Name to Create
</div></div>

</li>
<li><code>targetObject : String</code>
<div><div>
 The path of file to deploy. Local file, remote url and image url permitted
</div></div>

</li>
<li><code>packageType : String</code>
</li>
<li><code>jdk : String</code>
<div><div>
 The version of JDK
</div></div>

</li>
<li><code>args : String</code> (optional)
<div><div>
 JsonArray of command arguments.(e.g.: [{"argument":"-c"},{"argument":"test"}])
</div></div>

</li>
<li><code>cpuLimit : String</code> (optional)
<div><div>
 CPU limit, unit: millicores
</div></div>

</li>
<li><code>cpuRequest : String</code> (optional)
<div><div>
 CPU request, unit: millicores
</div></div>

</li>
<li><code>descFormat : String</code> (optional)
</li>
<li><code>edasContainerVersion : String</code> (optional)
<div><div>
 The version of EDAS container. Required when deploy war package
</div></div>

</li>
<li><code>endpoint : String</code> (optional)
</li>
<li><code>envs : String</code> (optional)
<div><div>
 The jsonArray of envs.(e.g.: [{"name":"testkey","value":"testValue"}]) Set [] to clear settings
</div></div>

</li>
<li><code>liveness : String</code> (optional)
<div><div>
 e.g.: {"failureThreshold": 3,"initialDelaySeconds": 5,"successThreshold": 1,"timeoutSeconds": 1,"httpGet": {"path": "/consumer","port": 8080,"scheme": "HTTP","httpHeaders": [{"name": "test","value": "testvalue"}]}}. Set empty of {} to clear, "unchanging" means no changing
</div></div>

</li>
<li><code>memoryLimit : String</code> (optional)
</li>
<li><code>memoryRequest : String</code> (optional)
</li>
<li><code>postStart : String</code> (optional)
<div><div>
 e.g.: {"exec":{"command":"cat","/etc/group"}}. Set empty of {} to clear, "unchanging" means no changing
</div></div>

</li>
<li><code>preStop : String</code> (optional)
<div><div>
 e.g.: {"exec":{"command":"cat","/etc/group"}}. Set empty of {} to clear, "unchanging" means no changing
</div></div>

</li>
<li><code>readiness : String</code> (optional)
<div><div>
 e.g.: {"failureThreshold": 3,"initialDelaySeconds": 5,"successThreshold": 1,"timeoutSeconds": 1,"httpGet": {"path": "/consumer","port": 8080,"scheme": "HTTP","httpHeaders": [{"name": "test","value": "testvalue"}]}}. Set empty of {} to clear, "unchanging" means no changing
</div></div>

</li>
<li><code>replicas : String</code> (optional)
<div><div>
 The number of pods
</div></div>

</li>
<li><code>startupCommand : String</code> (optional)
<div><div>
 The startup command
</div></div>

</li>
<li><code>versionLabelFormat : String</code> (optional)
<div><div>
 How to set the version label? For instance, for "${GIT_COMMIT}-${BUILD_TAG}", and with "Key Prefix" set to "myapp/builds/myapp-prod-env/", the S3 Object Key is set to myapp/builds/myapp-prod-env/4b5f7669b3376a1ce504bf7ef8bf7aeee9d21746-myjob-41.zip and the version Label will be 4b5f7669b3376a1ce504bf7ef8bf7aeee9d21746-myjob-41
</div></div>

</li>
<li><code>webContainer : String</code> (optional)
<div><div>
 The version of tomcat(e.g. "Apache Tomcat 7.0.91"). Required when deploy war package
</div></div>

</li>
</ul></div></li>
</ul></li>
</ul>


++++
