= Amazon Elastic Container Service (ECS) / Fargate plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/amazon-ecs">Visit the Jenkins Plugins site</a>
++++


=== `ecsTaskTemplate`: Define a task template to use in the AWS ECS plugin
++++
<ul><li><code>label : String</code>
</li>
<li><code>name : String</code>
</li>
<li><code>agentContainerName : String</code> (optional)
</li>
<li><code>assignPublicIp : boolean</code> (optional)
</li>
<li><code>capacityProviderStrategies</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>provider : String</code>
</li>
<li><code>base : int</code>
</li>
<li><code>weight : int</code>
</li>
</ul></li>
<li><code>cloud : String</code> (optional)
</li>
<li><code>containerUser : String</code> (optional)
</li>
<li><code>cpu : int</code> (optional)
</li>
<li><code>cpuArchitecture : String</code> (optional)
</li>
<li><code>defaultCapacityProvider : boolean</code> (optional)
</li>
<li><code>efsMountPoints</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>containerPath : String</code>
</li>
<li><code>readOnly : boolean</code>
</li>
<li><code>fileSystemId : String</code>
</li>
<li><code>rootDirectory : String</code>
</li>
<li><code>accessPointId : String</code>
</li>
<li><code>transitEncryption : boolean</code>
</li>
<li><code>iam : boolean</code>
</li>
</ul></li>
<li><code>enableExecuteCommand : boolean</code> (optional)
</li>
<li><code>environments</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>ephemeralStorageSizeInGiB : int</code> (optional)
</li>
<li><code>executionRole : String</code> (optional)
</li>
<li><code>extraHosts</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>ipAddress : String</code>
</li>
<li><code>hostname : String</code>
</li>
</ul></li>
<li><code>image : String</code> (optional)
</li>
<li><code>inheritFrom : String</code> (optional)
<div><p>You can pre-configure a task template in the system settings. Configure the label of this template to inherit from here.</p></div>

</li>
<li><code>kernelCapabilities : String</code> (optional)
</li>
<li><code>launchType : String</code> (optional)
</li>
<li><code>logDriver : String</code> (optional)
</li>
<li><code>logDriverOptions</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>memory : int</code> (optional)
</li>
<li><code>memoryReservation : int</code> (optional)
</li>
<li><code>mountPoints</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>sourcePath : String</code>
</li>
<li><code>containerPath : String</code>
</li>
<li><code>readOnly : boolean</code>
</li>
</ul></li>
<li><code>networkMode : String</code> (optional)
</li>
<li><code>operatingSystemFamily : String</code> (optional)
</li>
<li><code>overrides : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>placementStrategies</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>type : String</code>
</li>
<li><code>field : String</code>
</li>
</ul></li>
<li><code>platformVersion : String</code> (optional)
</li>
<li><code>portMappings</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>containerPort : int</code>
<div>The port number on the container to bind to the host port.</div>

</li>
<li><code>hostPort : int</code>
<div><p>The port number on the host instance to map to the container port.</p>
<p>If no host port is provided (or it is set to 0), the container will receive a port in the ephemeral port range.</p>
<p>Reserved ports: 22 (SSH), 2375-2376 (Docker), and 51678 (ECS container agent)</p></div>

</li>
<li><code>protocol : String</code>
<div>The protocol used for the port mapping.</div>

</li>
</ul></li>
<li><code>privileged : boolean</code> (optional)
</li>
<li><code>remoteFSRoot : String</code> (optional)
</li>
<li><code>repositoryCredentials : String</code> (optional)
</li>
<li><code>securityGroups : String</code> (optional)
</li>
<li><code>sharedMemorySize : int</code> (optional)
</li>
<li><code>subnets : String</code> (optional)
</li>
<li><code>tags</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>taskDefinitionOverride : String</code> (optional)
</li>
<li><code>taskrole : String</code> (optional)
</li>
<li><code>ulimits</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>softLimit : int</code>
</li>
<li><code>hardLimit : int</code>
</li>
<li><code>ulimitName : String</code>
</li>
</ul></li>
<li><code>uniqueRemoteFSRoot : boolean</code> (optional)
</li>
</ul>


++++
