= Anka Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/anka-build">Visit the Jenkins Plugins site</a>
++++


=== `ankaGetSaveImageResult`: Wait for previous save image requests results
++++
<ul><li><code>shouldFail : boolean</code>
</li>
<li><code>timeoutMinutes : int</code>
</li>
</ul>


++++
=== `createDynamicAnkaNode`: create dynamic anka node
++++
<ul><li><code>masterVmId : String</code> (optional)
</li>
<li><code>SSHPort : int</code> (optional)
</li>
<li><code>cloudName : String</code> (optional)
</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>deleteLatest : boolean</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>dontAppendTimestamp : boolean</code> (optional)
</li>
<li><code>environments</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>extraArgs : String</code> (optional)
</li>
<li><code>group : String</code> (optional)
</li>
<li><code>javaArgs : String</code> (optional)
</li>
<li><code>jnlpJenkinsOverrideUrl : String</code> (optional)
</li>
<li><code>jnlpTunnel : String</code> (optional)
</li>
<li><code>keepAliveOnError : boolean</code> (optional)
</li>
<li><code>labelString : String</code> (optional)
</li>
<li><code>launchDelay : int</code> (optional)
</li>
<li><code>launchMethod : String</code> (optional)
</li>
<li><code>mode</code> (optional)
<ul><li><b>Values:</b> <code>NORMAL</code>, <code>EXCLUSIVE</code></li></ul></li>
<li><code>nameTemplate : String</code> (optional)
</li>
<li><code>numberOfExecutors : int</code> (optional)
</li>
<li><code>priority : int</code> (optional)
</li>
<li><code>pushTag : String</code> (optional)
</li>
<li><code>remoteFS : String</code> (optional)
</li>
<li><code>retentionStrategy</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>agent-maintenance</code><div>
<div><div>
 Take this agent offline during dedicated time windows, e.g. due to maintenance activities. Outside of an active maintenance window, the "Regular Availability" is applied.
 <br>
  Exact behaviour what to do with running builds can be individually defined for each maintenanance window.
</div></div>
<ul><li><code>regularRetentionStrategy</code>
<ul><li><b>Type:</b> <code>hudson.slaves.RetentionStrategy&lt;hudson.slaves.SlaveComputer&gt;</code></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'AlmostAlways'</code><div>
<ul></ul></div></li>
<li><code>always</code><div>
<ul></ul></div></li>
<li><code>$class: 'AzureVMCloudOnceRetentionStrategy'</code><div>
<ul></ul></div></li>
<li><code>$class: 'AzureVMCloudPoolRetentionStrategy'</code><div>
<ul><li><code>retentionInHours : int</code>
<div><div>
 Retention time define the time of hour before automatically deleting since the agent created. Specify 0 means agents won't be deleted automatically.
</div></div>

</li>
<li><code>poolSize : int</code>
<div><div>
 Pool size define the number of agent you want to maintain.
</div></div>

</li>
<li><code>singleUseAgents : boolean</code> (optional)
<div><div>
 If enabled, agents are deleted after a single job is run. It is suggested to set retention time to 0 if this is enabled.
</div></div>

</li>
</ul></div></li>
<li><code>azureVMCloudRetentionStrategy</code><div>
<ul><li><code>idleTerminationMinutes : int</code>
</li>
</ul></div></li>
<li><code>$class: 'ContainerIdleRetentionStrategy'</code><div>
<ul><li><code>idleMinutes : int</code>
</li>
</ul></div></li>
<li><code>$class: 'ContainerOnceRetentionStrategy'</code><div>
<ul></ul></div></li>
<li><code>demand</code><div>
<ul><li><code>inDemandDelay : long</code>
</li>
<li><code>idleDelay : long</code>
</li>
</ul></div></li>
<li><code>$class: 'DockerCloudRetentionStrategy'</code><div>
<ul><li><code>idleMinutes : int</code>
<div><div>
 Number of minutes of idleness after which to kill the slave; serves a backup in case the strategy fails to detect the end of a task
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DockerSwarmAgentRetentionStrategy'</code><div>
<ul><li><code>timeout : int</code>
</li>
</ul></div></li>
<li><code>$class: 'IdleTimeCloudRetentionStrategy'</code><div>
<ul><li><code>idleMinutes : int</code>
</li>
</ul></div></li>
<li><code>demand</code><div>
<ul><li><code>inDemandDelay : long</code>
</li>
<li><code>idleDelay : long</code>
</li>
<li><code>conflictsWith : String</code> (optional)
<div><div>
 <p>Optional regular expression (or string in trivial case) with name(s) of node(s) whose being online blocks the current node from starting.</p>
 <p>To properly take advantage of this, be sure to set low idleDelay timeout values for those other workers that no longer have work pending.</p>
 <p>Note that conflict is evaluated one way (<i>"should this node start if inDemandDelay has elapsed?"</i>), so all nodes in question should declare each other as conflicting -- e.g. by copying the regular expression, if such node names follow the same pattern. In any case, a node would not conflict with itself even if there is a match.</p>
 <p>As with other regular expressions, "negative look-ahead" can be used to exclude certain results from the following matching pattern, e.g.:</p>
 <pre>^(?!myServer$)(.*erver.*)$</pre>
 <p>This setting allows a Jenkins deployment to co-locate various pre-defined or otherwise provisioned build environments without overwhelming their host -- and instead permits round-robining, one by one.</p>
</div></div>

</li>
</ul></div></li>
<li><code>schedule</code><div>
<ul><li><code>startTimeSpec : String</code>
</li>
<li><code>upTimeMins : int</code>
</li>
<li><code>keepUpWhenActive : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'VSphereCloudRetentionStrategy'</code><div>
<ul><li><code>idleMinutes : int</code>
</li>
</ul></div></li>
<li><code>$class: 'com.github.kostyasha.yad.strategy.DockerOnceRetentionStrategy'</code><div>
<ul><li><code>idleMinutes : int</code>
<div><div>
 Number of minutes of idleness after which to kill the slave; serves a backup in case the strategy fails to detect the end of a task
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy'</code><div>
<ul><li><code>idleMinutes : int</code>
<div><div>
 Number of minutes of idleness after which to kill the agent; serves a backup in case the strategy fails to detect the end of a task
</div></div>

</li>
<li><code>numberOfTasksInProgress : int</code> (optional)
</li>
<li><code>terminateOnceDone : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>ankaRunOnceCloud</code><div>
<ul><li><code>idleMinutes : int</code>
</li>
</ul></div></li>
<li><code>$class: 'io.jenkins.plugins.orka.RunOnceCloudRetentionStrategy'</code><div>
<ul><li><code>idleMinutes : int</code>
</li>
</ul></div></li>
<li><code>$class: 'org.jenkinsci.plugins.vsphere.RunOnceCloudRetentionStrategy'</code><div>
<ul><li><code>idleMinutes : int</code>
</li>
</ul></div></li>
</ul></li>
<li><code>saveImage : boolean</code> (optional)
</li>
<li><code>suspend : boolean</code> (optional)
</li>
<li><code>tag : String</code> (optional)
</li>
<li><code>templateDescription : String</code> (optional)
</li>
<li><code>templateId : String</code> (optional)
</li>
<li><code>timeout : int</code> (optional)
</li>
<li><code>vcpu : int</code> (optional)
</li>
<li><code>vram : int</code> (optional)
</li>
</ul>


++++
