= Ansible Tower Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/ansible-tower">Visit the Jenkins Plugins site</a>
++++


=== `ansibleTower`: Have Ansible Tower run a job template
++++
<ul><li><code>towerServer : String</code> (optional)
</li>
<li><code>towerCredentialsId : String</code> (optional)
</li>
<li><code>jobTemplate : String</code> (optional)
</li>
<li><code>jobType : String</code> (optional)
</li>
<li><code>async : boolean</code> (optional)
</li>
<li><code>credential : String</code> (optional)
</li>
<li><code>extraVars : String</code> (optional)
</li>
<li><code>importTowerLogs : boolean</code> (optional)
</li>
<li><code>importWorkflowChildLogs : boolean</code> (optional)
</li>
<li><code>inventory : String</code> (optional)
</li>
<li><code>jobTags : String</code> (optional)
</li>
<li><code>limit : String</code> (optional)
</li>
<li><code>removeColor : boolean</code> (optional)
</li>
<li><code>scmBranch : String</code> (optional)
</li>
<li><code>skipJobTags : String</code> (optional)
</li>
<li><code>templateType : String</code> (optional)
</li>
<li><code>throwExceptionWhenFail : boolean</code> (optional)
</li>
<li><code>towerLogLevel : String</code> (optional)
</li>
<li><code>verbose : boolean</code> (optional)
</li>
</ul>


++++
=== `ansibleTowerProjectRevision`: Have Ansible Tower update a Tower project's revision
++++
<ul><li><code>towerServer : String</code> (optional)
</li>
<li><code>towerCredentialsId : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>revision : String</code> (optional)
</li>
<li><code>verbose : boolean</code> (optional)
</li>
<li><code>throwExceptionWhenFail : boolean</code> (optional)
</li>
</ul>


++++
=== `ansibleTowerProjectSync`: Have Ansible Tower update a Tower project
++++
<ul><li><code>towerServer : String</code> (optional)
</li>
<li><code>towerCredentialsId : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>verbose : boolean</code> (optional)
</li>
<li><code>importTowerLogs : boolean</code> (optional)
</li>
<li><code>removeColor : boolean</code> (optional)
</li>
<li><code>throwExceptionWhenFail : boolean</code> (optional)
</li>
<li><code>async : boolean</code> (optional)
</li>
</ul>


++++
