= Appdome Build-2secure
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/appdome-build-2secure">Visit the Jenkins Plugins site</a>
++++


=== `AppdomeBuilder`: Appdome Build-2secure
++++
<ul><li><code>token</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>teamId : String</code>
</li>
<li><code>platform</code>
<ul><b>Nested Choice of Objects</b>
<li><code>AndroidPlatform</code><div>
<ul><li><code>certificateMethod</code>
<ul><b>Nested Choice of Objects</b>
<li><code>Android_AutoDevSign</code><div>
<ul><li><code>fingerprint : String</code>
</li>
<li><code>googleSigning : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>Android_AutoSign</code><div>
<ul><li><code>keystorePath : String</code>
</li>
<li><code>keystorePassword</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>keystoreAlias</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>keyPass</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>googleSignFingerPrint</code> (optional)
<ul><b>Nested Object</b>
<li><code>googleSignFingerPrint : String</code> (optional)
</li>
</ul></li>
<li><code>googleSign</code> (optional)
<ul><b>Nested Object</b>
<li><code>googleSignFingerPrint : String</code> (optional)
</li>
</ul></li>
</ul></div></li>
<li><code>Android_PrivateSign</code><div>
<ul><li><code>fingerprint : String</code>
</li>
<li><code>googleSigning : boolean</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>appPath : String</code> (optional)
</li>
<li><code>fusionSetId : String</code> (optional)
</li>
</ul></div></li>
<li><code>IosPlatform</code><div>
<ul><li><code>certificateMethod</code>
<ul><b>Nested Choice of Objects</b>
<li><code>iOS_AutoDevSign</code><div>
<ul><li><code>provisioningProfiles</code>
<ul><b>Array / List of Nested Object</b>
<li><code>item : String</code>
</li>
</ul></li>
<li><code>entitlements</code>
<ul><b>Array / List of Nested Object</b>
<li><code>item : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>iOS_AutoSign</code><div>
<ul><li><code>keystorePath : String</code>
</li>
<li><code>keystorePassword</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>entitlements</code>
<ul><b>Array / List of Nested Object</b>
<li><code>item : String</code>
</li>
</ul></li>
<li><code>provisioningProfiles</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>item : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>iOS_PrivateSign</code><div>
<ul><li><code>provisioningProfiles</code>
<ul><b>Array / List of Nested Object</b>
<li><code>item : String</code>
</li>
</ul></li>
</ul></div></li>
</ul></li>
<li><code>appPath : String</code> (optional)
</li>
<li><code>fusionSetId : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>secondOutput</code> (optional)
<ul><b>Nested Object</b>
<li><code>item : String</code>
</li>
</ul></li>
<li><code>buildToTest</code> (optional)
<ul><b>Nested Object</b>
<li><code>selectedVendor : String</code> (optional)
</li>
</ul></li>
<li><code>buildWithLogs : boolean</code> (optional)
</li>
<li><code>outputLocation : String</code> (optional)
</li>
</ul>


++++
