= Apprenda Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/apprenda">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'ApprendaBuilder'])`: Deploy to Apprenda
++++
<ul><li><code>appAlias : String</code>
<div><div>
 The Applicaton Alias to be used.
</div></div>

</li>
<li><code>appName : String</code>
<div><div>
 The Applicaton Name to be used.
</div></div>

</li>
<li><code>versionAlias : String</code>
<div><div>
 The application Version Alias to target.
</div></div>

</li>
<li><code>stage : String</code>
<div><div>
 The desired Apprenda Application lifecycle Stage.
</div></div>

</li>
<li><code>artifactName : String</code>
<div><div>
 The filename of the Apprenda Application Package. For example myapplication.zip.
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
<li><code>prefix : String</code>
<div><div>
 The Version Alias prefix to be used. Apprenda will append a number to the prefix to complete the Version Alias.
</div></div>

</li>
<li><code>advVersionAliasToBeForced : String</code>
<div><div>
 The complete Version Alias, including the Version prefix and Version number to be used. For example v23.
</div></div>

</li>
<li><code>advancedNewVersionOption : String</code>
</li>
<li><code>customPackageDirectory : String</code>
<div><div>
 The full path to the folder that contains the Apprenda Application Package defined in the Artifact Name.
</div></div>

</li>
<li><code>applicationPackageURL : String</code>
<div><div>
 The complete URL to the Apprenda Application Package, starting with http:// or https://.
</div></div>

</li>
<li><code>archiveUploadMethod : String</code>
</li>
<li><code>buildWithParameters : boolean</code>
<div><div>
 Check this box if you are using a parameterized project and want the Apprenda build step to do the substitution of variables from parameters.
</div></div>

</li>
</ul>


++++
