= App-Ray Security check plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/appray">Visit the Jenkins Plugins site</a>
++++


=== `appray`: App-Ray security check
++++
<ul><li><code>appRayUrl : String</code>
<div><div>
 App-Ray instance URL. Default: https://demo.app-ray.co
</div></div>

</li>
<li><code>outputFilePath : String</code>
<div><div>
 Name of the binary file (apk, ipa) to be scanned relative to the workspace. You can use Jenkins variables to specify the filename.
</div></div>

</li>
<li><code>waitTimeout : int</code>
<div><div>
 Timeout of waiting for ending of a scan. (For big application sometimes it take more than 30 minute!)
</div></div>

</li>
<li><code>riskScoreThreshold : int</code>
<div><div>
 The minimum risk score to check the apk validity. It is the output of then scan. You can check the scores on the app-ray instance.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Use email address as a username and please provide a password. The user must have full-access access right in App-Ray in order to be able to submit applications for scanning.
</div></div>

</li>
</ul>


++++
