= Artifactory Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/artifactory">Visit the Jenkins Plugins site</a>
++++


=== `ArtifactoryGradleBuild`: run Artifactory gradle
++++
<ul><li><code>gradleBuild</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.builds.GradleBuild</code></li>
</ul></li>
<li><code>rootDir : String</code>
</li>
<li><code>buildFile : String</code>
</li>
<li><code>tasks : String</code>
</li>
<li><code>switches : String</code>
</li>
<li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
</ul>


++++
=== `MavenDescriptorStep`: Get Artifactory Maven descriptor
++++
<ul><li><code>pomFile : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>versionPerModule</code>
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>failOnSnapshot : boolean</code>
</li>
<li><code>dryRun : boolean</code>
</li>
</ul>


++++
=== `addInteractivePromotion`: Add interactive promotion
++++
<ul><li><code>promotionConfig</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.PromotionConfig</code></li>
</ul></li>
<li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
<li><code>displayName : String</code>
</li>
</ul>


++++
=== `artifactoryBuildTrigger`: Trigger Artifactory build
++++
<ul><li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
<li><code>paths : String</code>
</li>
<li><code>spec : String</code>
</li>
</ul>


++++
=== `artifactoryDistributeBuild`: Distribute build
++++
<ul><li><code>distributionConfig</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.DistributionConfig</code></li>
</ul></li>
<li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
</ul>


++++
=== `artifactoryDownload`: Download artifacts
++++
<ul><li><code>spec : String</code>
</li>
<li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>failNoOp : boolean</code>
</li>
<li><code>module : String</code>
</li>
<li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
</ul>


++++
=== `artifactoryEditProps`: Edit properties
++++
<ul><li><code>spec : String</code>
</li>
<li><code>props : String</code>
</li>
<li><code>failNoOp : boolean</code>
</li>
<li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
<li><code>editType</code>
<ul><li><b>Values:</b> <code>SET</code>, <code>DELETE</code></li></ul></li>
</ul>


++++
=== `artifactoryGoPublish`: Run Artifactory Go Publish command
++++
<ul><li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>goBuild</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.builds.GoBuild</code></li>
</ul></li>
<li><code>path : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>args : String</code>
</li>
<li><code>module : String</code>
</li>
<li><code>javaArgs : String</code>
</li>
</ul>


++++
=== `artifactoryGoRun`: Run Artifactory Go command
++++
<ul><li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>goBuild</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.builds.GoBuild</code></li>
</ul></li>
<li><code>path : String</code>
</li>
<li><code>goCmdArgs : String</code>
</li>
<li><code>args : String</code>
</li>
<li><code>module : String</code>
</li>
<li><code>javaArgs : String</code>
</li>
</ul>


++++
=== `artifactoryMavenBuild`: run Artifactory maven
++++
<ul><li><code>mavenBuild</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.builds.MavenBuild</code></li>
</ul></li>
<li><code>pom : String</code>
</li>
<li><code>goals : String</code>
</li>
<li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
</ul>


++++
=== `artifactoryNpmCi`: Run Artifactory npm ci
++++
<ul><li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>npmBuild</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.builds.NpmBuild</code></li>
</ul></li>
<li><code>javaArgs : String</code>
</li>
<li><code>path : String</code>
</li>
<li><code>args : String</code>
</li>
<li><code>module : String</code>
</li>
</ul>


++++
=== `artifactoryNpmInstall`: Run Artifactory npm install
++++
<ul><li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>npmBuild</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.builds.NpmBuild</code></li>
</ul></li>
<li><code>javaArgs : String</code>
</li>
<li><code>path : String</code>
</li>
<li><code>args : String</code>
</li>
<li><code>module : String</code>
</li>
</ul>


++++
=== `artifactoryNpmPublish`: Run Artifactory npm publish
++++
<ul><li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>npmBuild</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.builds.NpmBuild</code></li>
</ul></li>
<li><code>path : String</code>
</li>
<li><code>javaArgs : String</code>
</li>
<li><code>args : String</code>
</li>
<li><code>module : String</code>
</li>
</ul>


++++
=== `artifactoryNugetRun`: Run Artifactory NuGet
++++
<ul><li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>nugetBuild</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.builds.NugetBuild</code></li>
</ul></li>
<li><code>javaArgs : String</code>
</li>
<li><code>args : String</code>
</li>
<li><code>module : String</code>
</li>
</ul>


++++
=== `artifactoryPipRun`: Run Artifactory pip install
++++
<ul><li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>pipBuild</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.builds.PipBuild</code></li>
</ul></li>
<li><code>javaArgs : String</code>
</li>
<li><code>args : String</code>
</li>
<li><code>envActivation : String</code>
</li>
<li><code>module : String</code>
</li>
</ul>


++++
=== `artifactoryPromoteBuild`: Promote build
++++
<ul><li><code>promotionConfig</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.PromotionConfig</code></li>
</ul></li>
<li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
</ul>


++++
=== `artifactoryUpload`: Upload artifacts
++++
<ul><li><code>spec : String</code>
</li>
<li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>failNoOp : boolean</code>
</li>
<li><code>module : String</code>
</li>
<li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
</ul>


++++
=== `buildAppend`: Build append
++++
<ul><li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>buildName : String</code>
</li>
<li><code>buildNumber : String</code>
</li>
<li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
</ul>


++++
=== `collectEnv`: Collect environment variables and system properties
++++
<ul><li><code>env</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.Env</code></li>
</ul></li>
</ul>


++++
=== `collectIssues`: Collect issues from git and add them to a build
++++
<ul><li><code>issues</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.Issues</code></li>
</ul></li>
<li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
<li><code>config : String</code>
</li>
</ul>


++++
=== `conanAddRemote`: Add new repo to Conan config
++++
<ul><li><code>serverUrl : String</code>
</li>
<li><code>serverName : String</code>
</li>
<li><code>conanHome : String</code>
</li>
<li><code>force : boolean</code>
</li>
<li><code>verifySSL : boolean</code>
</li>
</ul>


++++
=== `conanAddUser`: Add new user to Conan config
++++
<ul><li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
<li><code>serverName : String</code>
</li>
<li><code>conanHome : String</code>
</li>
</ul>


++++
=== `createDockerBuildStep`: Artifactory create Docker build
++++
<ul><li><code>kanikoImageFile : String</code>
</li>
<li><code>jibImageFiles : String</code>
</li>
<li><code>sourceRepo : String</code>
</li>
<li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
<li><code>javaArgs : String</code>
</li>
</ul>


++++
=== `createReleaseBundle`: Create a release bundle 
++++
<ul><li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.DistributionServer</code></li>
</ul></li>
<li><code>name : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>spec : String</code>
</li>
<li><code>storingRepo : String</code>
</li>
<li><code>signImmediately : boolean</code>
</li>
<li><code>dryRun : boolean</code>
</li>
<li><code>gpgPassphrase : String</code>
</li>
<li><code>releaseNotesPath : String</code>
</li>
<li><code>releaseNotesSyntax : String</code>
</li>
<li><code>description : String</code>
</li>
</ul>


++++
=== `deleteReleaseBundle`: Delete a release bundle
++++
<ul><li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.DistributionServer</code></li>
</ul></li>
<li><code>name : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>dryRun : boolean</code>
</li>
<li><code>sync : boolean</code>
</li>
<li><code>deleteFromDist : boolean</code>
</li>
<li><code>distRules : String</code>
</li>
<li><code>countryCodes : Array / List of String</code>
<ul></ul></li>
<li><code>siteName : String</code>
</li>
<li><code>cityName : String</code>
</li>
</ul>


++++
=== `deployArtifacts`: Deploy artifacts
++++
<ul><li><code>deployer</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
</ul>


++++
=== `distributeReleaseBundle`: Distribute a release bundle
++++
<ul><li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.DistributionServer</code></li>
</ul></li>
<li><code>name : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>dryRun : boolean</code>
</li>
<li><code>sync : boolean</code>
</li>
<li><code>distRules : String</code>
</li>
<li><code>countryCodes : Array / List of String</code>
<ul></ul></li>
<li><code>siteName : String</code>
</li>
<li><code>cityName : String</code>
</li>
</ul>


++++
=== `dockerPullStep`: Artifactory docker pull
++++
<ul><li><code>image : String</code>
</li>
<li><code>host : String</code>
</li>
<li><code>sourceRepo : String</code>
</li>
<li><code>javaArgs : String</code>
</li>
<li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
</ul>


++++
=== `dockerPushStep`: Artifactory docker push
++++
<ul><li><code>image : String</code>
</li>
<li><code>host : String</code>
</li>
<li><code>targetRepo : String</code>
</li>
<li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>com.google.common.collect.ArrayListMultimap&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
<li><code>javaArgs : String</code>
</li>
</ul>


++++
=== `dsCreateReleaseBundle`: Create release bundle
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>name : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>spec : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>dryRun : boolean</code> (optional)
</li>
<li><code>gpgPassphrase : String</code> (optional)
</li>
<li><code>releaseNotesPath : String</code> (optional)
</li>
<li><code>releaseNotesSyntax : String</code> (optional)
</li>
<li><code>signImmediately : boolean</code> (optional)
</li>
<li><code>specPath : String</code> (optional)
</li>
<li><code>storingRepo : String</code> (optional)
</li>
</ul>


++++
=== `dsDeleteReleaseBundle`: Delete a release bundle
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>name : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>cityName : String</code> (optional)
</li>
<li><code>countryCodes : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>deleteFromDist : boolean</code> (optional)
</li>
<li><code>distRules : String</code> (optional)
</li>
<li><code>dryRun : boolean</code> (optional)
</li>
<li><code>siteName : String</code> (optional)
</li>
<li><code>sync : boolean</code> (optional)
</li>
</ul>


++++
=== `dsDistributeReleaseBundle`: Distribute a release bundle
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>name : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>cityName : String</code> (optional)
</li>
<li><code>countryCodes : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>distRules : String</code> (optional)
</li>
<li><code>dryRun : boolean</code> (optional)
</li>
<li><code>siteName : String</code> (optional)
</li>
<li><code>sync : boolean</code> (optional)
</li>
</ul>


++++
=== `dsSignReleaseBundle`: Sign a release bundle
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>name : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>gpgPassphrase : String</code> (optional)
</li>
<li><code>storingRepo : String</code> (optional)
</li>
</ul>


++++
=== `dsUpdateReleaseBundle`: Update a release bundle
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>name : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>spec : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>dryRun : boolean</code> (optional)
</li>
<li><code>gpgPassphrase : String</code> (optional)
</li>
<li><code>releaseNotesPath : String</code> (optional)
</li>
<li><code>releaseNotesSyntax : String</code> (optional)
</li>
<li><code>signImmediately : boolean</code> (optional)
</li>
<li><code>specPath : String</code> (optional)
</li>
<li><code>storingRepo : String</code> (optional)
</li>
</ul>


++++
=== `getArtifactoryServer`: Get Artifactory server from Jenkins config
++++
<ul><li><code>artifactoryServerID : String</code>
</li>
</ul>


++++
=== `getJFrogPlatformInstance`: Get JFrog Platform instance from Jenkins config
++++
<ul><li><code>instanceId : String</code>
</li>
</ul>


++++
=== `initConanClient`: Create Conan Client
++++
<ul><li><code>client</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ConanClient</code></li>
</ul></li>
</ul>


++++
=== `jfPipelines`: Set output resources and report results for JFrog Pipelines
++++
<ul><li><code>outputResources : String</code> (optional)
</li>
<li><code>reportStatus : String</code> (optional)
</li>
</ul>


++++
=== `jfrogInstance`: Creates new JFrog instance
++++
<ul><li><code>id : String</code>
</li>
<li><code>artifactoryUrl : String</code> (optional)
</li>
<li><code>bypassProxy : boolean</code> (optional)
</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>deploymentThreads : int</code> (optional)
</li>
<li><code>distributionUrl : String</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>retry : int</code> (optional)
</li>
<li><code>timeout : int</code> (optional)
</li>
<li><code>url : String</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
</ul>


++++
=== `newArtifactoryServer`: Returns new Artifactory server
++++
<ul><li><code>url : String</code>
</li>
<li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
</ul>


++++
=== `newBuildInfo`: New buildInfo
++++
<ul></ul>


++++
=== `newGoBuild`: New Artifactory Go
++++
<ul></ul>


++++
=== `newGradleBuild`: New Artifactory gradle executor
++++
<ul></ul>


++++
=== `newJFrogPlatformInstance`: Returns new JFrog platform instance
++++
<ul><li><code>url : String</code>
</li>
<li><code>artifactoryUrl : String</code>
</li>
<li><code>distributionUrl : String</code>
</li>
<li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
</ul>


++++
=== `newMavenBuild`: New Artifactory maven
++++
<ul></ul>


++++
=== `newNpmBuild`: New Artifactory npm executor
++++
<ul></ul>


++++
=== `newNugetBuild`: New Artifactory NuGet executor
++++
<ul></ul>


++++
=== `newPipBuild`: New Artifactory pip executor
++++
<ul></ul>


++++
=== `publishBuildInfo`: Publish build Info to Artifactory
++++
<ul><li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
<li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
</ul>


++++
=== `rtAddInteractivePromotion`: Add interactive promotion
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>comment : String</code> (optional)
</li>
<li><code>copy : boolean</code> (optional)
</li>
<li><code>displayName : String</code> (optional)
</li>
<li><code>failFast : boolean</code> (optional)
</li>
<li><code>includeDependencies : boolean</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>sourceRepo : String</code> (optional)
</li>
<li><code>status : String</code> (optional)
</li>
<li><code>targetRepo : String</code> (optional)
</li>
</ul>


++++
=== `rtBuildAppend`: Build append
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>appendBuildName : String</code>
</li>
<li><code>appendBuildNumber : String</code>
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
</ul>


++++
=== `rtBuildInfo`: Create build info
++++
<ul><li><code>asyncBuildRetention : boolean</code> (optional)
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>captureEnv : boolean</code> (optional)
</li>
<li><code>deleteBuildArtifacts : boolean</code> (optional)
</li>
<li><code>doNotDiscardBuilds : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>excludeEnvPatterns : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>includeEnvPatterns : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>maxBuilds : int</code> (optional)
</li>
<li><code>maxDays : int</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>startDate</code> (optional)
<ul><li><b>Type:</b> <code>class java.util.Date</code></li>
</ul></li>
</ul>


++++
=== `rtBuildTrigger`: Trigger Artifactory build
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>paths : String</code>
</li>
<li><code>spec : String</code>
</li>
</ul>


++++
=== `rtCollectIssues`: Collect issues
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>config : String</code> (optional)
</li>
<li><code>configPath : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
</ul>


++++
=== `rtConanClient`: Creates new Conan client
++++
<ul><li><code>id : String</code>
</li>
<li><code>userHome : String</code> (optional)
</li>
</ul>


++++
=== `rtConanRemote`: Add new repo to Conan config
++++
<ul><li><code>clientId : String</code>
</li>
<li><code>name : String</code>
</li>
<li><code>serverId : String</code>
</li>
<li><code>repo : String</code>
</li>
<li><code>force : boolean</code> (optional)
</li>
<li><code>verifySSL : boolean</code> (optional)
</li>
</ul>


++++
=== `rtConanRun`: Run a Conan command
++++
<ul><li><code>clientId : String</code>
</li>
<li><code>command : String</code>
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
</ul>


++++
=== `rtCreateDockerBuild`: run Artifactory create Docker build
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>sourceRepo : String</code>
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>javaArgs : String</code> (optional)
</li>
<li><code>jibImageFiles : String</code> (optional)
</li>
<li><code>kanikoImageFile : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
</ul>


++++
=== `rtDeleteProps`: Delete properties
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>failNoOp : boolean</code> (optional)
</li>
<li><code>props : String</code> (optional)
</li>
<li><code>spec : String</code> (optional)
</li>
<li><code>specPath : String</code> (optional)
</li>
</ul>


++++
=== `rtDockerPull`: run Artifactory docker pull
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>image : String</code>
</li>
<li><code>sourceRepo : String</code>
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>host : String</code> (optional)
</li>
<li><code>javaArgs : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
</ul>


++++
=== `rtDockerPush`: run Artifactory docker push
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>image : String</code>
</li>
<li><code>targetRepo : String</code>
</li>
<li><code>javaArgs : String</code> (optional)
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>host : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>properties : String</code> (optional)
</li>
</ul>


++++
=== `rtDotnetResolver`: set .NET resolver
++++
<ul><li><code>id : String</code>
</li>
<li><code>serverId : String</code>
</li>
<li><code>repo : String</code> (optional)
</li>
</ul>


++++
=== `rtDotnetRun`: run Artifactory .NET
++++
<ul><li><code>apiProtocol : String</code> (optional)
</li>
<li><code>args : String</code> (optional)
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>javaArgs : String</code> (optional)
</li>
<li><code>module : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>resolverId : String</code> (optional)
</li>
</ul>


++++
=== `rtDownload`: Download artifacts
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>failNoOp : boolean</code> (optional)
</li>
<li><code>module : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>spec : String</code> (optional)
</li>
<li><code>specPath : String</code> (optional)
</li>
</ul>


++++
=== `rtGoDeployer`: set go deployer
++++
<ul><li><code>id : String</code>
</li>
<li><code>serverId : String</code>
</li>
<li><code>repo : String</code> (optional)
</li>
<li><code>customBuildName : String</code> (optional)
</li>
<li><code>properties : Array / List of String</code> (optional)
<ul></ul></li>
</ul>


++++
=== `rtGoPublish`: run Artifactory Go publish
++++
<ul><li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>deployerId : String</code> (optional)
</li>
<li><code>javaArgs : String</code> (optional)
</li>
<li><code>module : String</code> (optional)
</li>
<li><code>path : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>version : String</code> (optional)
</li>
</ul>


++++
=== `rtGoResolver`: set Go resolver
++++
<ul><li><code>id : String</code>
</li>
<li><code>serverId : String</code>
</li>
<li><code>repo : String</code> (optional)
</li>
</ul>


++++
=== `rtGoRun`: run Artifactory Go publish
++++
<ul><li><code>args : String</code> (optional)
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>javaArgs : String</code> (optional)
</li>
<li><code>module : String</code> (optional)
</li>
<li><code>path : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>resolverId : String</code> (optional)
</li>
</ul>


++++
=== `rtGradleDeployer`: set gradle deployer
++++
<ul><li><code>id : String</code>
</li>
<li><code>serverId : String</code>
</li>
<li><code>artifactPattern : String</code> (optional)
</li>
<li><code>customBuildName : String</code> (optional)
</li>
<li><code>deployIvyDescriptors : boolean</code> (optional)
</li>
<li><code>deployMavenDescriptors : boolean</code> (optional)
</li>
<li><code>excludePatterns : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>includeEnvVars : boolean</code> (optional)
</li>
<li><code>includePatterns : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>ivyPattern : String</code> (optional)
</li>
<li><code>mavenCompatible : boolean</code> (optional)
</li>
<li><code>properties : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>publications : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>releaseRepo : String</code> (optional)
</li>
<li><code>repo : String</code> (optional)
</li>
<li><code>snapshotRepo : String</code> (optional)
</li>
<li><code>threads : int</code> (optional)
</li>
</ul>


++++
=== `rtGradleResolver`: set gradle resolver
++++
<ul><li><code>id : String</code>
</li>
<li><code>serverId : String</code>
</li>
<li><code>repo : String</code> (optional)
</li>
</ul>


++++
=== `rtGradleRun`: run Artifactory gradle
++++
<ul><li><code>buildFile : String</code> (optional)
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>deployerId : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>resolverId : String</code> (optional)
</li>
<li><code>rootDir : String</code> (optional)
</li>
<li><code>switches : String</code> (optional)
</li>
<li><code>tasks : String</code> (optional)
</li>
<li><code>tool : String</code> (optional)
</li>
<li><code>useWrapper : boolean</code> (optional)
</li>
<li><code>usesPlugin : boolean</code> (optional)
</li>
</ul>


++++
=== `rtMavenDeployer`: set maven deployer
++++
<ul><li><code>id : String</code>
</li>
<li><code>releaseRepo : String</code>
</li>
<li><code>snapshotRepo : String</code>
</li>
<li><code>serverId : String</code>
</li>
<li><code>customBuildName : String</code> (optional)
</li>
<li><code>deployArtifacts : boolean</code> (optional)
</li>
<li><code>deployEvenIfUnstable : boolean</code> (optional)
</li>
<li><code>excludePatterns : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>includeEnvVars : boolean</code> (optional)
</li>
<li><code>includePatterns : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>properties : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>threads : int</code> (optional)
</li>
</ul>


++++
=== `rtMavenResolver`: set maven resolver
++++
<ul><li><code>id : String</code>
</li>
<li><code>releaseRepo : String</code>
</li>
<li><code>snapshotRepo : String</code>
</li>
<li><code>serverId : String</code>
</li>
</ul>


++++
=== `rtMavenRun`: run Artifactory maven
++++
<ul><li><code>pom : String</code>
</li>
<li><code>goals : String</code>
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>deployerId : String</code> (optional)
</li>
<li><code>opts : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>resolverId : String</code> (optional)
</li>
<li><code>tool : String</code> (optional)
</li>
<li><code>useWrapper : boolean</code> (optional)
</li>
</ul>


++++
=== `rtNpmCi`: run Artifactory npm ci
++++
<ul><li><code>args : String</code> (optional)
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>javaArgs : String</code> (optional)
</li>
<li><code>module : String</code> (optional)
</li>
<li><code>path : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>resolverId : String</code> (optional)
</li>
<li><code>tool : String</code> (optional)
</li>
</ul>


++++
=== `rtNpmDeployer`: set npm deployer
++++
<ul><li><code>id : String</code>
</li>
<li><code>serverId : String</code>
</li>
<li><code>repo : String</code> (optional)
</li>
<li><code>customBuildName : String</code> (optional)
</li>
<li><code>properties : Array / List of String</code> (optional)
<ul></ul></li>
</ul>


++++
=== `rtNpmInstall`: run Artifactory npm install
++++
<ul><li><code>args : String</code> (optional)
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>javaArgs : String</code> (optional)
</li>
<li><code>module : String</code> (optional)
</li>
<li><code>path : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>resolverId : String</code> (optional)
</li>
<li><code>tool : String</code> (optional)
</li>
</ul>


++++
=== `rtNpmPublish`: run Artifactory npm publish
++++
<ul><li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>deployerId : String</code> (optional)
</li>
<li><code>javaArgs : String</code> (optional)
</li>
<li><code>module : String</code> (optional)
</li>
<li><code>path : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>tool : String</code> (optional)
</li>
</ul>


++++
=== `rtNpmResolver`: set npm resolver
++++
<ul><li><code>id : String</code>
</li>
<li><code>serverId : String</code>
</li>
<li><code>repo : String</code> (optional)
</li>
</ul>


++++
=== `rtNugetResolver`: set NuGet resolver
++++
<ul><li><code>id : String</code>
</li>
<li><code>serverId : String</code>
</li>
<li><code>repo : String</code> (optional)
</li>
</ul>


++++
=== `rtNugetRun`: run Artifactory NuGet
++++
<ul><li><code>apiProtocol : String</code> (optional)
</li>
<li><code>args : String</code> (optional)
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>javaArgs : String</code> (optional)
</li>
<li><code>module : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>resolverId : String</code> (optional)
</li>
</ul>


++++
=== `rtPipInstall`: run Artifactory pip install
++++
<ul><li><code>args : String</code> (optional)
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>envActivation : String</code> (optional)
</li>
<li><code>javaArgs : String</code> (optional)
</li>
<li><code>module : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>resolverId : String</code> (optional)
</li>
</ul>


++++
=== `rtPipResolver`: set pip resolver
++++
<ul><li><code>id : String</code>
</li>
<li><code>serverId : String</code>
</li>
<li><code>repo : String</code> (optional)
</li>
</ul>


++++
=== `rtPromote`: Promote build
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>targetRepo : String</code>
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>comment : String</code> (optional)
</li>
<li><code>copy : boolean</code> (optional)
</li>
<li><code>failFast : boolean</code> (optional)
</li>
<li><code>includeDependencies : boolean</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>sourceRepo : String</code> (optional)
</li>
<li><code>status : String</code> (optional)
</li>
</ul>


++++
=== `rtPublishBuildInfo`: Publish build info
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
</ul>


++++
=== `rtServer`: Creates new Artifactory server
++++
<ul><li><code>id : String</code>
</li>
<li><code>bypassProxy : boolean</code> (optional)
</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>deploymentThreads : int</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>retry : int</code> (optional)
</li>
<li><code>timeout : int</code> (optional)
</li>
<li><code>url : String</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
</ul>


++++
=== `rtSetProps`: Set properties
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>failNoOp : boolean</code> (optional)
</li>
<li><code>props : String</code> (optional)
</li>
<li><code>spec : String</code> (optional)
</li>
<li><code>specPath : String</code> (optional)
</li>
</ul>


++++
=== `rtUpload`: Upload artifacts
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>failNoOp : boolean</code> (optional)
</li>
<li><code>module : String</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
<li><code>spec : String</code> (optional)
</li>
<li><code>specPath : String</code> (optional)
</li>
</ul>


++++
=== `runConanCommand`: Run a Conan command
++++
<ul><li><code>command : String</code>
</li>
<li><code>conanHome : String</code>
</li>
<li><code>buildInfo</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.buildInfo.BuildInfo</code></li>
</ul></li>
</ul>


++++
=== `signReleaseBundle`: Sign a release bundle
++++
<ul><li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.DistributionServer</code></li>
</ul></li>
<li><code>name : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>spec : String</code>
</li>
<li><code>gpgPassphrase : String</code>
</li>
<li><code>storingRepo : String</code>
</li>
</ul>


++++
=== `updateReleaseBundle`: Update a release bundle
++++
<ul><li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.DistributionServer</code></li>
</ul></li>
<li><code>name : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>spec : String</code>
</li>
<li><code>storingRepo : String</code>
</li>
<li><code>signImmediately : boolean</code>
</li>
<li><code>dryRun : boolean</code>
</li>
<li><code>gpgPassphrase : String</code>
</li>
<li><code>releaseNotesPath : String</code>
</li>
<li><code>releaseNotesSyntax : String</code>
</li>
<li><code>description : String</code>
</li>
</ul>


++++
=== `xrayScan`: run Xray scan
++++
<ul><li><code>serverId : String</code>
</li>
<li><code>buildName : String</code> (optional)
</li>
<li><code>buildNumber : String</code> (optional)
</li>
<li><code>failBuild : boolean</code> (optional)
</li>
<li><code>printTable : boolean</code> (optional)
</li>
<li><code>project : String</code> (optional)
</li>
</ul>


++++
=== `xrayScanBuild`: Xray build scanning
++++
<ul><li><code>xrayScanConfig</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.XrayScanConfig</code></li>
</ul></li>
<li><code>server</code>
<ul><li><b>Type:</b> <code>class org.jfrog.hudson.pipeline.common.types.ArtifactoryServer</code></li>
</ul></li>
</ul>


++++
