= Artifactz.io Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/artifactz">Visit the Jenkins Plugins site</a>
++++


=== `publishArtifact`: Publish Artifact Version
++++
<ul><li><code>token : String</code> (optional)
</li>
<li><code>name : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>type : String</code> (optional)
</li>
<li><code>flow : String</code> (optional)
</li>
<li><code>stage : String</code> (optional)
</li>
<li><code>stageDescription : String</code> (optional)
</li>
<li><code>groupId : String</code> (optional)
</li>
<li><code>artifactId : String</code> (optional)
</li>
<li><code>version : String</code> (optional)
</li>
</ul>


++++
=== `pushArtifact`: Push Artifact Version
++++
<ul><li><code>variable : String</code>
</li>
<li><code>token : String</code> (optional)
</li>
<li><code>stage : String</code> (optional)
</li>
<li><code>name : String</code> (optional)
</li>
<li><code>version : String</code> (optional)
</li>
</ul>


++++
=== `retrieveArtifacts`: Retrieve Artifact Versions
++++
<ul><li><code>token : String</code> (optional)
</li>
<li><code>stage : String</code> (optional)
</li>
<li><code>names : Array / List of String</code> (optional)
<ul></ul></li>
</ul>


++++
=== `artifactVersion`: Send Artifact Version To Artifactor Web Service Deprecated
++++
<ul><li><code>name : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>type : String</code> (optional)
</li>
<li><code>groupId : String</code> (optional)
</li>
<li><code>artifactId : String</code> (optional)
</li>
<li><code>stage : String</code> (optional)
</li>
<li><code>flow : String</code> (optional)
</li>
<li><code>stageDescription : String</code> (optional)
</li>
<li><code>version : String</code> (optional)
</li>
</ul>


++++
=== `artifactVersion`: Push Artifact Version to the next stage in the flow Deprecated
++++
<ul><li><code>variableName : String</code>
</li>
<li><code>name : String</code> (optional)
</li>
<li><code>stage : String</code> (optional)
</li>
<li><code>version : String</code> (optional)
</li>
</ul>


++++
=== `artifactVersion`: Send Artifact Version To Artifactor Web Service
++++
<ul><li><code>token : String</code> (optional)
</li>
<li><code>name : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>type : String</code> (optional)
</li>
<li><code>groupId : String</code> (optional)
</li>
<li><code>artifactId : String</code> (optional)
</li>
<li><code>stage : String</code> (optional)
</li>
<li><code>flow : String</code> (optional)
</li>
<li><code>stageDescription : String</code> (optional)
</li>
<li><code>version : String</code> (optional)
</li>
</ul>


++++
=== `artifactVersion`: Push Artifact Version to the next stage in the flow
++++
<ul><li><code>variableName : String</code>
</li>
<li><code>token : String</code> (optional)
</li>
<li><code>name : String</code> (optional)
</li>
<li><code>stage : String</code> (optional)
</li>
<li><code>version : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'RetrieveArtifactsBuildStep'])`: Retrieve Artifact version for stage
++++
<ul><li><code>token : String</code> (optional)
</li>
<li><code>names</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code> (optional)
</li>
</ul></li>
<li><code>stage : String</code> (optional)
</li>
<li><code>variableName : String</code> (optional)
</li>
</ul>


++++
