= artifact-promotion
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/artifact-promotion">Visit the Jenkins Plugins site</a>
++++


=== `artifactPromotion`: ArtifactPromotionStep
++++
<ul><li><code>groupId : String</code>
</li>
<li><code>artifactId : String</code>
</li>
<li><code>classifier : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>stagingRepository : String</code>
</li>
<li><code>stagingUser : String</code>
</li>
<li><code>stagingPW : String</code>
</li>
<li><code>releaseUser : String</code>
</li>
<li><code>releasePW : String</code>
</li>
<li><code>releaseRepository : String</code>
</li>
<li><code>promoterClass : String</code>
</li>
<li><code>debug : boolean</code>
</li>
<li><code>extension : String</code> (optional)
</li>
<li><code>skipDeletion : boolean</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'ArtifactPromotionBuilder'])`: Single Artifact Promotion
++++
<div><div>
 Here you can configure the artifact promotion plugin for single artifacts. In the first section (<i>Artifact Information</i>) you enter the coordinates of your artifact.
 <br>
  In the <i>Staging Repository Information</i> section you tell there your source repository is, e.g. http://192.168.56.24/nexus/content/repositories/staging/.
 <br>
  In the following section <i>Release Repository Information</i>, you enter the information about the target repository, e.g. http://192.168.56.24/nexus/content/repositories/releases/. In both sections, you can add user credentials. If you do, the connection to the repository servers will be done using these credentials. If you don't suppot credentials, the access will be done without any authentication. 
 <br>
  Both repositorys should be <i>release</i> repositories, not snapshot repos! The password(s) will be saved currently using the standard Jenkins functionality to save those. It's planned to use in the future the credentials plugin.
</div></div>
<ul><li><code>groupId : String</code>
</li>
<li><code>artifactId : String</code>
</li>
<li><code>classifier : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>extension : String</code>
</li>
<li><code>stagingRepository : String</code>
</li>
<li><code>stagingUser : String</code>
</li>
<li><code>stagingPW : String</code>
</li>
<li><code>releaseUser : String</code>
</li>
<li><code>releasePW : String</code>
</li>
<li><code>releaseRepository : String</code>
</li>
<li><code>promoterClass : String</code>
</li>
<li><code>debug : boolean</code>
</li>
<li><code>skipDeletion : boolean</code>
<div><div>
 <p>'Skip deletion' option preserves the files in the staging repository.</p>
 <p>Untick 'Skip deletion' only after you've promoted all the relevant files in previous steps.</p>
</div></div>

</li>
</ul>


++++
