= AssertThat BDD Jira Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/assertthat-bdd-jira">Visit the Jenkins Plugins site</a>
++++


=== `assertthatBddFeatures`: Download AssertThat features
++++
<ul><li><code>projectId : String</code>
<div><div>
 Jira project id.
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
<li><code>outputFolder : String</code>
<div><br>
 Output folder for feature files withing workspace. Default ./features/. 
<br>
 By default features are downloaded to the root of the workspace.</div>

</li>
<li><code>jql : String</code>
</li>
<li><code>tags : String</code>
</li>
<li><code>mode : String</code>
</li>
<li><code>proxyURI : String</code>
</li>
<li><code>proxyUsername : String</code>
</li>
<li><code>proxyPassword : String</code>
</li>
<li><code>jiraServerUrl : String</code>
<div><div>
 Jira Server URL. Populate only if using Jira Server version (e.g. https://mycompanyjira.com). Leave blank for cloud.
</div></div>

</li>
<li><code>numbered : boolean</code>
</li>
<li><code>ignoreCertErrors : boolean</code>
</li>
</ul>


++++
=== `assertthatBddReport`: Upload AssertThat report
++++
<ul><li><code>projectId : String</code>
<div><div>
 Jira project id.
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
<li><code>jsonReportFolder : String</code>
<div><div>
 Cucumber json files folder withing the workspace. The folder where cucumber json is outputted after the tests run. e.g. ./reports/. 
 <br>
  By default searching for json files in the root of the workspace.
</div></div>

</li>
<li><code>jsonReportIncludePattern : String</code>
<div><div>
 Pattern for json file names. Default **/*.json
</div></div>

</li>
<li><code>runName : String</code>
<div><div>
 The name of the run. Default 'Test run dd MMM yyyy HH:mm:ss'
</div></div>

</li>
<li><code>type : String</code>
<div><div>
 Report type: Cucumber or Karate
</div></div>

</li>
<li><code>proxyURI : String</code>
</li>
<li><code>proxyUsername : String</code>
</li>
<li><code>proxyPassword : String</code>
</li>
<li><code>jiraServerUrl : String</code>
<div><div>
 Jira Server URL. Populate only if using Jira Server version (e.g. https://mycompanyjira.com). Leave blank for cloud.
</div></div>

</li>
<li><code>metadata : String</code>
</li>
<li><code>jql : String</code>
</li>
<li><code>ignoreCertErrors : boolean</code>
</li>
</ul>


++++
