= Bitbucket Server Integration
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/atlassian-bitbucket-server-integration">Visit the Jenkins Plugins site</a>
++++


=== `bbs_checkout`: BitbucketSCMStep
++++
<ul><li><code>projectName : String</code>
<div><div>
 <p>Enter the name of the Bitbucket Server project containing the repository you want Jenkins to build from. To find a project, start typing. If it doesn't appear in the search results, the credentials that you've chosen may not have read access to it and you'll need to provide different credentials.</p>
 <p>To get Jenkins to build from a personal repository, enter a tilde (<code>~</code>) followed by repository owner's username. For example, <code>~jsmith.</code></p>
</div></div>

</li>
<li><code>repositoryName : String</code>
<div><div>
 <p>Enter the Bitbucket Server repository you want Jenkins to build from. To find a repository, start typing. If it doesn't appear in the search results, the credentials that you've chosen may not have read access to it and you'll need to provide different credentials.</p>
 <p>To get Jenkins to build from a personal repository, enter its slug. This is the URL-friendly version of the repository name. For example, a repository called my example repo will have the slug <em>my-example-repo</em>, and you can see this in its URL, https://bitbucketserver.mycompany.com/myproject/my-example-repo.</p>
</div></div>

</li>
<li><code>branches</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
<div><div>
 <p>Specify the branches if you'd like to track a specific branch in a repository. If left blank, all branches will be examined for changes and built.</p>
 <p>The safest way is to use the <code>refs/heads/&lt;branchName&gt;</code> syntax. This way the expected branch is unambiguous.</p>
 <p>If your branch name has a <code>/</code> in it make sure to use the full reference above. When not presented with a full path the plugin will only use the part of the string right of the last slash. Meaning <code>foo/bar</code> will actually match <code>bar</code>.</p>
 <p>If you use a wildcard branch specifier, with a slash (e.g. <code>release/</code>), you'll need to specify the origin repository in the branch names to make sure changes are picked up. So e.g. <code>origin/release/</code></p>
 <p>Possible options:</p>
 <ul>
  <li><strong><code>&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch. If ambiguous the first result is taken, which is not necessarily the expected one. Better use <code>refs/heads/&lt;branchName&gt;</code>.<br>
    E.g. <code>master</code>, <code>feature1</code>, ...</li>
  <li><strong><code>refs/heads/&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch.<br>
    E.g. <code>refs/heads/master</code>, <code>refs/heads/feature1/master</code>, ...</li>
  <li><strong><code>&lt;remoteRepoName&gt;/&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch. If ambiguous the first result is taken, which is not necessarily the expected one.<br>
    Better use <code>refs/heads/&lt;branchName&gt;</code>.<br>
    E.g. <code>origin/master</code></li>
  <li><strong><code>remotes/&lt;remoteRepoName&gt;/&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch.<br>
    E.g. <code>remotes/origin/master</code></li>
  <li><strong><code>refs/remotes/&lt;remoteRepoName&gt;/&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch.<br>
    E.g. <code>refs/remotes/origin/master</code></li>
  <li><strong><code>&lt;tagName&gt;</code></strong><br>
    This does not work since the tag will not be recognized as tag.<br>
    Use <code>refs/tags/&lt;tagName&gt;</code> instead.<br>
    E.g. <code>git-2.3.0</code></li>
  <li><strong><code>refs/tags/&lt;tagName&gt;</code></strong><br>
    Tracks/checks out the specified tag.<br>
    E.g. <code>refs/tags/git-2.3.0</code></li>
  <li><strong><code>&lt;commitId&gt;</code></strong><br>
    Checks out the specified commit.<br>
    E.g. <code>5062ac843f2b947733e6a3b105977056821bd352</code>, <code>5062ac84</code>, ...</li>
  <li><strong><code>${ENV_VARIABLE}</code></strong><br>
    It is also possible to use environment variables. In this case the variables are evaluated and the result is used as described above.<br>
    E.g. <code>${TREEISH}</code>, <code>refs/tags/${TAGNAME}</code>, ...</li>
  <li><strong><code>&lt;Wildcards&gt;</code></strong><br>
    The syntax is of the form: <code>REPOSITORYNAME/BRANCH</code>. In addition, <code>BRANCH</code> is recognized as a shorthand of <code>*/BRANCH</code>, '*' is recognized as a wildcard, and '**' is recognized as wildcard that includes the separator '/'. Therefore, <code>origin/branches*</code> would match <code>origin/branches-foo</code> but not <code>origin/branches/foo</code>, while <code>origin/branches**</code> would match both <code>origin/branches-foo</code> and <code>origin/branches/foo</code>.</li>
  <li><strong><code>:&lt;regular expression&gt;</code></strong><br>
    The syntax is of the form: <code>:regexp</code>. Regular expression syntax in branches to build will only build those branches whose names match the regular expression.<br>
    Examples:<br>
   <ul>
    <li><code>:^(?!(origin/prefix)).*</code>
     <ul>
      <li>matches: <code>origin</code> or <code>origin/master</code> or <code>origin/feature</code></li>
      <li>does not match: <code>origin/prefix</code> or <code>origin/prefix_123</code> or <code>origin/prefix-abc</code></li>
     </ul></li>
    <li><code>:origin/release-\d{8}</code>
     <ul>
      <li>matches: <code>origin/release-20150101</code></li>
      <li>does not match: <code>origin/release-2015010</code> or <code>origin/release-201501011</code> or <code>origin/release-20150101-something</code></li>
     </ul></li>
    <li><code>:^(?!origin/master$|origin/develop$).*</code>
     <ul>
      <li>matches: <code>origin/branch1</code> or <code>origin/branch-2</code> or <code>origin/master123</code> or <code>origin/develop-123</code></li>
      <li>does not match: <code>origin/master</code> or <code>origin/develop</code></li>
     </ul></li>
   </ul></li>
 </ul>
 <p></p>
</div></div>

</li>
</ul></li>
<li><code>changelog : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in changelog': 
 <p>If 'Include in changelog' is enabled for an SCM source, then when a build occurs, the changes from that SCM source will be included in the changelog.</p>
 <p>If 'Include in changelog' is disabled, then when a build occurs, the changes from this SCM source will not be included in the changelog.</p>
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 <p>When running a job, Jenkins requires credentials to authenticate with Bitbucket Server. For example, to checkout the source code for builds. To do this, it needs credentials with access to the projects and repositories you want it to build from.</p>
 <p>You can provide Jenkins with credentials here by:</p>
 <ul>
  <li>selecting credentials from the list</li>
  <li>adding credentials as a <strong>Username with password</strong> (for the password, you can enter a Bitbucket Server password or a Bitbucket Server <a href="https://confluence.atlassian.com/x/a97-Nw" rel="nofollow">personal access token</a>)</li>
 </ul>
 <p>In addition, you can provide Jenkins with SSH credentials below. If you do, Jenkins will use them for clone operations instead of the credentials you select here.</p>
</div></div>

</li>
<li><code>id : String</code> (optional)
</li>
<li><code>mirrorName : String</code> (optional)
<div><div>
 <p>Choose the location that Jenkins should clone from when running this build. This can be the primary server or a mirror if one is available. To see available mirrors, first choose a Bitbucket Server project and repository.</p>
</div></div>

</li>
<li><code>poll : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in polling' 
 <p>If 'Include in polling' is enabled or 'Include in changelog' is enabled, then when polling occurs, the job will be started if changes are detected from this SCM source.</p>
 <p>If 'Include in polling' is disabled and 'Include in changelog' is disabled, then when polling occurs, changes that are detected from this repository will be ignored.</p>
</div></div>

</li>
<li><code>serverId : String</code> (optional)
<div><div>
 <p>Choose the Bitbucket Server instance containing the repository you want Jenkins to build from. If you can't find your instance, check this plugin's configuration and try again.</p>
</div></div>

</li>
<li><code>serverName : String</code> (optional)
</li>
<li><code>sshCredentialsId : String</code> (optional)
<div><div>
 <p>If specified, Jenkins will use these credentials to check out the source code for builds. If no SSH credentials are specified, Jenkins will use the basic credentials instead.</p>
 <p>To provide Jenkins with SSH credentials, you can:</p>
 <ul>
  <li>choose credentials from the list</li>
  <li>add credentials as a <strong>SSH Username with private key</strong> (the username must be "git")</li>
 </ul>
</div></div>

</li>
</ul>


++++
=== `bbs_deploy`: Wrapper step to notify Bitbucket Server of the deployment status.
++++
<ul><li><code>environmentName : String</code>
<div><div>
 <p>A human-readable display name for the environment that was deployed to.</p>
</div></div>

</li>
<li><code>environmentKey : String</code> (optional)
<div><div>
 <p>This is a unique identifier for the environment in Bitbucket Server. You can name it something readable like <code>MY-ENV</code>, or you can leave it blank and have it auto-generated by the plugin.</p>
</div></div>

</li>
<li><code>environmentType : String</code> (optional)
<div><div>
 <p>The type of environment that was deployed to, or 'None' if the environment type does not apply.</p>
</div></div>

</li>
<li><code>environmentUrl : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'DeploymentNotifier'])`: Notify Bitbucket Server of deployment
++++
<ul><li><code>environmentName : String</code>
<div><div>
 <p>A human-readable display name for the environment that was deployed to.</p>
</div></div>

</li>
<li><code>environmentKey : String</code> (optional)
<div><div>
 <p>This is a unique identifier for the environment in Bitbucket Server. You can name it something readable like <code>MY-ENV</code>, or you can leave it blank and have it auto-generated by the plugin.</p>
</div></div>

</li>
<li><code>environmentType : String</code> (optional)
<div><div>
 <p>The type of environment that was deployed to, or 'None' if the environment type does not apply.</p>
</div></div>

</li>
<li><code>environmentUrl : String</code> (optional)
</li>
</ul>


++++
