= Autify Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/autify">Visit the Jenkins Plugins site</a>
++++


=== `autifyMobile`: Run test on Autify for Mobile
++++
<ul><li><code>credentialsId : String</code>
<div><div>
 Select the credentials of "Secret Text" storing the Personal Access Token of Autify for Mobile.
</div>
<div>
 See <a href="https://help.autify.com/mobile/docs/api-integration#api-authentication-token-generation-method" rel="nofollow">Autify's document</a> to understand how to generate the Personal Access Token.
</div></div>

</li>
<li><code>autifyUrl : String</code>
<div><div>
 The URL of your test plan you want to run on Autify for Mobile e.g. <code>https://mobile-app.autify.com/projects/&lt;ID&gt;/test_plans/&lt;ID&gt;</code>
</div></div>

</li>
<li><code>autifyPath : String</code> (optional)
</li>
<li><code>buildId : String</code> (optional)
</li>
<li><code>buildPath : String</code> (optional)
<div><div>
 If it's a relative path, it will be relative from the workspace directory.
</div></div>

</li>
<li><code>shellInstallerUrl : String</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
<div><div>
 <b>Only meaningful if you check "Wait".</b>
 <br>
  Timeout seconds when waiting the test finishes. If exceeds, the step will fail.
</div></div>

</li>
<li><code>wait : boolean</code> (optional)
<div><div>
 If checked, the step will wait until the Autify's test plan finishes.
</div></div>

</li>
</ul>


++++
=== `autifyMobileUpload`: Upload build to Autify for Mobile
++++
<ul><li><code>credentialsId : String</code>
<div><div>
 Select the credentials of "Secret Text" storing the Personal Access Token of Autify for Mobile.
</div>
<div>
 See <a href="https://help.autify.com/mobile/docs/api-integration#api-authentication-token-generation-method" rel="nofollow">Autify's document</a> to understand how to generate the Personal Access Token.
</div></div>

</li>
<li><code>workspaceId : String</code>
</li>
<li><code>buildPath : String</code>
<div><div>
 If it's a relative path, it will be relative from the workspace directory.
</div></div>

</li>
<li><code>autifyPath : String</code> (optional)
</li>
<li><code>shellInstallerUrl : String</code> (optional)
</li>
</ul>


++++
=== `autifyWeb`: Run test on Autify for Web
++++
<ul><li><code>credentialsId : String</code>
<div><div>
 Select the credentials of "Secret Text" storing the Personal Access Token of Autify for Web.
</div>
<div>
 See <a href="https://help.autify.com/docs/integrate-with-api#issue-a-personal-access-token" rel="nofollow">Autify's document</a> to understand how to generate the Personal Access Token.
</div></div>

</li>
<li><code>autifyUrl : String</code>
<div><div>
 The URL of your test plan or test scenario you want to run on Autify for Web e.g. <code>https://app.autify.com/projects/&lt;ID&gt;/(scenarios|test_plans)/&lt;ID&gt;</code>
</div></div>

</li>
<li><code>autifyConnect : String</code> (optional)
</li>
<li><code>autifyConnectClient : boolean</code> (optional)
<div><div>
 If checked, the step will start Autify Connect Client locally with an ephemeral Autify Connect Access Point. "Wait" option must be also checked.
</div></div>

</li>
<li><code>autifyConnectClientExtraArguments : String</code> (optional)
</li>
<li><code>autifyPath : String</code> (optional)
</li>
<li><code>browser : String</code> (optional)
</li>
<li><code>device : String</code> (optional)
</li>
<li><code>deviceType : String</code> (optional)
</li>
<li><code>os : String</code> (optional)
</li>
<li><code>osVersion : String</code> (optional)
</li>
<li><code>shellInstallerUrl : String</code> (optional)
</li>
<li><code>testExecutionName : String</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
<div><div>
 <b>Only meaningful if you check "Wait".</b>
 <br>
  Timeout seconds when waiting the test finishes. If exceeds, the step will fail.
</div></div>

</li>
<li><code>urlReplacements</code> (optional)
<div><div>
 List of a pair of URLs to replace the URL when Autify test accesses. This is useful when you want to run the same Autify test in a different stage e.g. running a test recorded in production against staging.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>patternUrl : String</code>
</li>
<li><code>replacementUrl : String</code>
</li>
</ul></li>
<li><code>wait : boolean</code> (optional)
<div><div>
 If checked, the step will wait until the Autify's test plan or scenario finishes.
</div></div>

</li>
</ul>


++++
