= AWS Lambda Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/aws-lambda">Visit the Jenkins Plugins site</a>
++++


=== `eventSourceLambda`: AWS Lambda eventsource mapping
++++
<ul><li><code>lambdaEventSourceBuildStepVariables</code>
<ul><b>Nested Object</b>
<li><code>awsRegion : String</code>
</li>
<li><code>functionName : String</code>
</li>
<li><code>eventSourceArn : String</code>
</li>
<li><code>awsAccessKeyId : String</code> (optional)
</li>
<li><code>awsSecretKey : String</code> (optional)
</li>
<li><code>functionAlias : String</code> (optional)
</li>
<li><code>useInstanceCredentials : boolean</code> (optional)
</li>
</ul></li>
</ul>


++++
=== `invokeLambda`: AWS Lambda invocation
++++
<ul><li><code>lambdaInvokeBuildStepVariables</code>
<ul><b>Nested Object</b>
<li><code>awsRegion : String</code>
</li>
<li><code>functionName : String</code>
</li>
<li><code>synchronous : boolean</code>
</li>
<li><code>awsAccessKeyId : String</code> (optional)
</li>
<li><code>awsSecretKey : String</code> (optional)
</li>
<li><code>jsonParameters</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>envVarName : String</code>
</li>
<li><code>jsonPath : String</code> (optional)
</li>
</ul></li>
<li><code>payload : String</code> (optional)
</li>
<li><code>useInstanceCredentials : boolean</code> (optional)
</li>
</ul></li>
</ul>


++++
=== `publishLambda`: AWS Lambda publish new version and update alias
++++
<ul><li><code>lambdaPublishBuildStepVariables</code>
<ul><b>Nested Object</b>
<li><code>awsRegion : String</code>
</li>
<li><code>functionARN : String</code>
</li>
<li><code>functionAlias : String</code>
</li>
<li><code>versionDescription : String</code>
</li>
<li><code>awsAccessKeyId : String</code> (optional)
</li>
<li><code>awsSecretKey : String</code> (optional)
</li>
<li><code>useInstanceCredentials : boolean</code> (optional)
</li>
</ul></li>
</ul>


++++
=== `deployLambda`: AWS Lambda deployment
++++
<ul><li><code>lambdaUploadBuildStepVariables</code>
<ul><b>Nested Object</b>
<li><code>awsRegion : String</code>
</li>
<li><code>functionName : String</code>
</li>
<li><code>updateMode : String</code>
</li>
<li><code>alias : String</code> (optional)
</li>
<li><code>artifactLocation : String</code> (optional)
</li>
<li><code>awsAccessKeyId : String</code> (optional)
</li>
<li><code>awsSecretKey : String</code> (optional)
</li>
<li><code>createAlias : boolean</code> (optional)
</li>
<li><code>deadLetterQueueArn : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>enableDeadLetterQueue : boolean</code> (optional)
</li>
<li><code>environmentConfiguration</code> (optional)
<ul><b>Nested Object</b>
<li><code>environment</code>
<ul><b>Array / List of Nested Object</b>
<li><code>key : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>configureEnvironment : boolean</code> (optional)
</li>
<li><code>kmsArn : String</code> (optional)
</li>
</ul></li>
<li><code>handler : String</code> (optional)
</li>
<li><code>memorySize : String</code> (optional)
</li>
<li><code>publish : boolean</code> (optional)
</li>
<li><code>role : String</code> (optional)
</li>
<li><code>runtime : String</code> (optional)
</li>
<li><code>securityGroups : String</code> (optional)
</li>
<li><code>subnets : String</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
</li>
<li><code>useInstanceCredentials : boolean</code> (optional)
</li>
</ul></li>
</ul>


++++
