= AWSEB Deployment Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/awseb-deployment-plugin">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'AWSEBDeploymentBuilder'])`: AWS Elastic Beanstalk
++++
<ul><li><code>config</code>
<ul><li><b>Type:</b> <code>class br.com.ingenieux.jenkins.plugins.awsebdeployment.AWSEBDeploymentConfig</code></li>
</ul></li>
<li><code>applicationName : String</code> (optional)
<div><div>
 AWS EB Application Name (e.g.: "myapp")
</div></div>

</li>
<li><code>awsRegion : String</code> (optional)
<div><div>
 AWS Region (e.g. us-east-1)
</div></div>

</li>
<li><code>bucketName : String</code> (optional)
<div><div>
 <p>S3 Bucket Name to Upload to (e.g. "my-awseb-apps")</p>
 <p>(Optional, will call <code>createStorageLocation</code> if blank)</p>
</div></div>

</li>
<li><code>checkHealth : boolean</code> (optional)
<div><div>
 Uncheck this to disable the Health check on deploy. Some implementations may not care to wait until the environment shows "Green".
</div></div>

</li>
<li><code>credentialId : String</code> (optional)
<div><div>
 Select the credentials to use.
</div></div>

</li>
<li><code>environmentName : String</code> (optional)
<div><div>
 <p>Optional: AWS EB Environment name(s) to deploy to.</p>
 <p>Can accept single or multiple comma-separated values. Examples:</p>
 <ul>
  <li>"my-prod-env" (single environment)</li>
  <li>"my-dev-env,my-staging-env" (multiple environments)</li>
 </ul>
 <p></p>
 <p>When this value is set and each requested environment exists, an UpdateEnvironment call will be triggered as the Application Version is created.</p>
</div></div>

</li>
<li><code>excludes : String</code> (optional)
<div><div>
 Optional (if rootObject points to a directory): Glob for Zip Excludes, comma-separated eg '**/.git/**/*,**/node_modules/**/*'
</div></div>

</li>
<li><code>includes : String</code> (optional)
<div><div>
 Optional (if rootObject points to a directory): Glob for Zip Includes, comma-separated like 'target/file,target/myapp/**/*'
</div></div>

</li>
<li><code>keyPrefix : String</code> (optional)
<div><div>
 Prefix for newly created apps on S3 Bucket. For Example, myapp/builds/myapp-prod-env/
</div></div>

</li>
<li><code>maxAttempts : int</code> (optional)
</li>
<li><code>rootObject : String</code> (optional)
<div><div>
 <p>Workspace-relative path of the artifact file to upload (if it's a file), or if it's a directory, the base directory to build the zip/war against</p>
 <p>Examples:</p>
 <ul>
  <li>File, like <code>target/mywebapp.war</code>: The war file will be uploaded</li>
  <li>A Directory, like '<code>.</code>' or '<code>target/war</code>': A Zip file will be built and uploaded instead (using includes and excludes).</li>
 </ul>
</div></div>

</li>
<li><code>skipEnvironmentUpdates : boolean</code> (optional)
</li>
<li><code>sleepTime : int</code> (optional)
</li>
<li><code>versionDescriptionFormat : String</code> (optional)
<div><div>
 How to set the version description? For instance, for "${GIT_COMMIT}", the version Description will be 4b5f7669b3376a1ce504bf7ef8bf7aeee9d21746 on AWS EB Application Versions
</div></div>

</li>
<li><code>versionLabelFormat : String</code> (optional)
<div><div>
 How to set the version label? For instance, for "${GIT_COMMIT}-${BUILD_TAG}", and with "Key Prefix" set to "myapp/builds/myapp-prod-env/", the S3 Object Key is set to myapp/builds/myapp-prod-env/4b5f7669b3376a1ce504bf7ef8bf7aeee9d21746-myjob-41.zip and the version Label will be 4b5f7669b3376a1ce504bf7ef8bf7aeee9d21746-myjob-41 on AWS EB Application Versions
</div></div>

</li>
<li><code>zeroDowntime : boolean</code> (optional)
</li>
</ul>


++++
