= Azure Virtual Machine Scale Set Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/azure-vmss">Visit the Jenkins Plugins site</a>
++++


=== `azureVMSSUpdateInstances`: Update Azure Virtual Machine Scale Set Instances
++++
<ul><li><code>azureCredentialsId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>resourceGroup : String</code>
<div><div>
 The resource group name that the Virtual Machine Scale Set is associated with.
</div></div>

</li>
<li><code>name : String</code>
<div><div>
 The Azure Virtual Machine Scale Set name.
</div></div>

</li>
<li><code>instanceIds : String</code>
<div><div>
 Instance IDs to be updated, separated by '<code>,</code>'.
</div></div>

</li>
</ul>


++++
=== `azureVMSSUpdate`: Update Azure Virtual Machine Scale Set
++++
<ul><li><code>azureCredentialsId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>resourceGroup : String</code>
<div><div>
 The resource group name that the Virtual Machine Scale Set is associated with.
</div></div>

</li>
<li><code>name : String</code>
<div><div>
 The Azure Virtual Machine Scale Set name.
</div></div>

</li>
<li><code>imageReference</code>
<ul><b>Nested Object</b>
<li><code>id : String</code> (optional)
<div><div>
 <p>Resource ID or VHD URI of the custom image.</p>
 <p>Example Resource ID: <code>/subscriptions/your-subscription-id/resourceGroups/your-resource-group/providers/Microsoft.Compute/images/your-image-name</code></p>
 <p>Example VHD URI: <code>http://your-storage-account.blob.core.windows.net/vhds/your-disk-image.vhd</code></p>
</div></div>

</li>
<li><code>offer : String</code> (optional)
<div><div>
 Offer of the image. For example, UbuntuServer.
</div></div>

</li>
<li><code>publisher : String</code> (optional)
<div><div>
 Publisher of the image. For example, Canonical.
</div></div>

</li>
<li><code>sku : String</code> (optional)
<div><div>
 SKU of the image. For example, 16.04-LTS.
</div></div>

</li>
<li><code>version : String</code> (optional)
<div><div>
 Version of the image. For example, 16.04.201611150.
</div></div>

</li>
</ul></li>
</ul>


++++
