= Azure CLI Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/azure-cli">Visit the Jenkins Plugins site</a>
++++


=== `azureCLI`: azure-cli                         2.59.0
++++
<ul><li><code>principalCredentialId : String</code>
<div><div>
 The Service Principal credentials required to connect to your Azure account. 
 <br>
  More information can be found here: <a href="https://github.com/Azure/azure-devops-utils#user-content-create-service-principal" rel="nofollow">https://github.com/Azure/azure-devops-utils#user-content-create-service-principal</a>
 <br>
  If you want to add an Azure credential click "Add" and select "Microsoft Azure Service Principal" from the Kind drop-down. 
 <br>
  If you want to remove existing Azure credentials you must go to the <a rel="nofollow">Credentials Dashboard</a>.
</div></div>

</li>
<li><code>commands</code>
<ul><b>Array / List of Nested Object</b>
<li><code>script : String</code>
</li>
<li><code>exportVariablesString : String</code>
<div><div>
 Export the output of the command to environment variables 
 <br>
  The format: /"variable from JSON" | "desired environment variable name" 
 <br>
  For example: Output: { "id": "/subscriptions/some-guid/resourceGroups/test", "location": "northeurope", "managedBy": null, "name": "test", "properties": { "provisioningState": "Succeeded" }, "tags": null } Environment Variable String: /location|LOCATION , /name|NAME
</div></div>

</li>
</ul></li>
</ul>


++++
