= Azure App Service Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/azure-app-service">Visit the Jenkins Plugins site</a>
++++


=== `azureWebAppPublish`: Publish an Azure Web App
++++
<ul><li><code>azureCredentialsId : String</code>
</li>
<li><code>appName : String</code>
</li>
<li><code>resourceGroup : String</code>
</li>
<li><code>deleteTempImage : boolean</code> (optional)
<div><div>
 If checked, the intermediate docker image will be removed from your build agent after build succeeds.
</div></div>

</li>
<li><code>deployOnlyIfSuccessful : boolean</code> (optional)
<div><div>
 If checked, application will only be deployed to Azure if the build was successful.
</div></div>

</li>
<li><code>dockerFilePath : String</code> (optional)
</li>
<li><code>dockerImageName : String</code> (optional)
<div><div>
 The docker image name. Leave blank if you want to use the same name as it on Azure. 
 <br>
  Be sure to include the registry and account if any. See examples:
 <br>
  Docker hub format: &lt;username&gt;/&lt;name&gt; eg. bitname/mysql 
 <br>
  Azure registry format: &lt;namePrefix.azurecr.io&gt;/&lt;repo&gt; eg. xxx.azurecr.io/mysql, xxx.azurecr.io/yyy/mysql
</div></div>

</li>
<li><code>dockerImageTag : String</code> (optional)
<div><div>
 Tha tag for your image. It's recommended to use a different tag for every single build otherwise your previous images might be overridden. We suggest you to append the BuildNumber to your tag so you can easily know that with which image your web app is currently running.
</div></div>

</li>
<li><code>dockerRegistryEndpoint</code> (optional)
<ul><b>Nested Object</b>
<li><code>url : String</code>
<div><div>
 URL to the Docker registry you are using. May be left blank to use the public DockerHub registry (currently <code>https://index.docker.io/v1/</code>).
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
</ul></li>
<li><code>filePath : String</code> (optional)
<div><div>
 <p>The file paths that will be deployed.</p>
 <p>You can use wildcards like <code>module/dist/**/*.py</code>. See the includes attribute of <a href="https://ant.apache.org/manual/Types/fileset.html" rel="nofollow">Ant fileset</a> for the exact format. Multiple files can be separated by '<code>,</code>'. The base directory is the workspace. You can only deploy files that are located in your workspace.</p>
 <p>Examples:</p>
 <ul>
  <li>
   <p>Java</p>
   <pre><code>webapps/*.war</code></pre>
   <pre><code>**/*.zip</code></pre>
   <p>Note: For Java application, if you choose WAR deployment, usually you should put your war file under the 'webapps' directory.</p></li>
  <li>
   <p>PHP</p>
   <pre><code>**/*.php,composer.json</code></pre></li>
  <li>
   <p>Python</p>
   <pre><code>**/*.py,requirements.txt</code></pre></li>
  <li>
   <p>Node.js</p>
   <pre><code>**/*.js,package.json,process.json</code></pre></li>
 </ul>
</div></div>

</li>
<li><code>publishType : String</code> (optional)
</li>
<li><code>skipDockerBuild : boolean</code> (optional)
<div><div>
 If checked, will skip building docker image and assume it already exists in the registry.
</div></div>

</li>
<li><code>slotName : String</code> (optional)
<div><div>
 <p>If not blank, will deploy to this deployment slot instead of the default production slot.</p>
 <p>See <a href="https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-staged-publishing" rel="nofollow">this article</a> for more details.</p>
</div></div>

</li>
<li><code>sourceDirectory : String</code> (optional)
<div><div>
 Source directory relative to the workspace.
</div></div>

</li>
<li><code>targetDirectory : String</code> (optional)
<div><div>
 Target directory relative to the site root.
</div></div>

</li>
</ul>


++++
=== `azureWebAppSwapSlots`: Swap slots for an Azure Web App
++++
<ul><li><code>azureCredentialsId : String</code>
</li>
<li><code>resourceGroup : String</code>
</li>
<li><code>appName : String</code>
</li>
<li><code>sourceSlotName : String</code>
<div><div>
 Source slot needs to be swapped.
</div></div>

</li>
<li><code>targetSlotName : String</code>
<div><div>
 Target slot needs to be swapped. It is usually the production slot.
</div></div>

</li>
</ul>


++++
