= Azure Key Vault Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/azure-keyvault">Visit the Jenkins Plugins site</a>
++++


=== `azureKeyVault`: Bind credentials in Azure Key Vault to environment variables
++++
<ul><li><code>secrets</code>
<ul><b>Array / List of Nested Object</b>
<li><code>secretType : String</code>
<div><div>
 Key Vault supports two types of secrets 
 <ul>
  <li><b>Secrets</b> are passwords or any arbitrary text</li>
  <li><b>Certificates</b> are X.509 certificates in PKCS12 format (PFX)</li>
 </ul>
</div></div>

</li>
<li><code>name : String</code>
<div><div>
 Name of the secret to retrieve from Key Vault
</div></div>

</li>
<li><code>envVariable : String</code>
<div><div>
 Environment Variable to which the secret will be assigned 
 <ul>
  <li>For <b>secrets</b>, the variable will contain the value of the secret</li>
  <li>For <b>certificates</b>, the variable will contain the path to the certificate in pkcs12 format</li>
 </ul>
</div></div>

</li>
<li><code>version : String</code> (optional)
<div><div>
 Version of the secret to retrieve from Key Vault
</div></div>

</li>
</ul></li>
<li><code>credentialID : String</code> (optional)
<div><div>
 Specify the Credential ID used for accessing Key Vault. 
 <ul>
  <li>Must be a <b>Azure Service Principal</b> or <b>Azure Managed Identity</b></li>
 </ul>
</div></div>

</li>
<li><code>keyVaultURL : String</code> (optional)
<div><div>
 OPTIONAL: Override the globally configured Key Vault URL (e.g. https://YOURKEYVAULT.vault.azure.net)
</div></div>

</li>
</ul>


++++
=== `withAzureKeyvault`: Bind credentials in Azure Key Vault to environment variables
++++
<ul><li><code>azureKeyVaultSecrets</code>
<ul><b>Array / List of Nested Object</b>
<li><code>secretType : String</code>
<div><div>
 Key Vault supports two types of secrets 
 <ul>
  <li><b>Secrets</b> are passwords or any arbitrary text</li>
  <li><b>Certificates</b> are X.509 certificates in PKCS12 format (PFX)</li>
 </ul>
</div></div>

</li>
<li><code>name : String</code>
<div><div>
 Name of the secret to retrieve from Key Vault
</div></div>

</li>
<li><code>envVariable : String</code>
<div><div>
 Environment Variable to which the secret will be assigned 
 <ul>
  <li>For <b>secrets</b>, the variable will contain the value of the secret</li>
  <li>For <b>certificates</b>, the variable will contain the path to the certificate in pkcs12 format</li>
 </ul>
</div></div>

</li>
<li><code>version : String</code> (optional)
<div><div>
 Version of the secret to retrieve from Key Vault
</div></div>

</li>
</ul></li>
<li><code>applicationIDOverride : String</code> (optional)
<div><div>
 OPTIONAL: Override the configured application ID to access Key Vault.
</div></div>

</li>
<li><code>applicationSecretOverride : String</code> (optional)
<div><div>
 OPTIONAL: Set an Application Secret directly
 <br><b>It is recommended to use the CredentialID field instead.</b>
</div></div>

</li>
<li><code>credentialIDOverride : String</code> (optional)
<div><div>
 Specify the Credential ID used for accessing Key Vault. 
 <ul>
  <li>Must be a <b>Azure Service Principal</b> or <b>Azure Managed Identity</b></li>
 </ul>
</div></div>

</li>
<li><code>keyVaultURLOverride : String</code> (optional)
<div><div>
 OPTIONAL: Override the configured Key Vault URL (e.g. https://YOURKEYVAULT.vault.azure.net)
</div></div>

</li>
<li><code>tenantIdOverride : String</code> (optional)
<div><div>
 Override the tenantId, only used if you're explicitly providing an override client ID and secret.
</div></div>

</li>
</ul>


++++
