= Badge
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/badge">Visit the Jenkins Plugins site</a>
++++


=== `addBadge`: Add Badge
++++
<ul><li><code>icon : String</code>
</li>
<li><code>text : String</code>
</li>
<li><code>id : String</code> (optional)
</li>
<li><code>link : String</code> (optional)
</li>
</ul>


++++
=== `addErrorBadge`: Add Error Badge
++++
<ul><li><code>text : String</code>
</li>
<li><code>id : String</code> (optional)
</li>
<li><code>link : String</code> (optional)
</li>
</ul>


++++
=== `addHtmlBadge`: Add a html badge Text
++++
<ul><li><code>html : String</code>
</li>
<li><code>id : String</code> (optional)
</li>
</ul>


++++
=== `addInfoBadge`: Add Info Badge
++++
<ul><li><code>text : String</code>
</li>
<li><code>id : String</code> (optional)
</li>
<li><code>link : String</code> (optional)
</li>
</ul>


++++
=== `addShortText`: Add Short Text
++++
<ul><li><code>text : String</code>
</li>
<li><code>background : String</code> (optional)
</li>
<li><code>border : int</code> (optional)
</li>
<li><code>borderColor : String</code> (optional)
</li>
<li><code>color : String</code> (optional)
</li>
<li><code>link : String</code> (optional)
</li>
</ul>


++++
=== `addWarningBadge`: Add Warning Badge
++++
<ul><li><code>text : String</code>
</li>
<li><code>id : String</code> (optional)
</li>
<li><code>link : String</code> (optional)
</li>
</ul>


++++
=== `createSummary`: Print Message
++++
<ul><li><code>icon : String</code>
</li>
<li><code>id : String</code> (optional)
</li>
<li><code>text : String</code> (optional)
</li>
</ul>


++++
=== `removeBadges`: Remove Badges
++++
<ul><li><code>id : String</code> (optional)
</li>
</ul>


++++
=== `removeHtmlBadges`: Remove Html Badges
++++
<ul><li><code>id : String</code> (optional)
</li>
</ul>


++++
=== `removeSummaries`: Remove Summaries
++++
<ul><li><code>id : String</code> (optional)
</li>
</ul>


++++
