= BlazeMeter plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/BlazeMeterJenkinsPlugin">Visit the Jenkins Plugins site</a>
++++


=== `blazeMeterTest`: BlazeMeter
++++
<ul><li><code>credentialsId : String</code> (optional)
<div><div>
 Select the BlazeMeter credentials to use.
</div></div>

</li>
<li><code>workspaceId : String</code> (optional)
</li>
<li><code>testId : String</code> (optional)
<div><div>
 BlazeMeter's plugin for Jenkins allows users to automate load tests from the cloud post build. 
 <br>
  Just choose the test you want to run. Let Jenkins start and stop the test and document the results. 
 <br>
  After the run, a test report will be generated directly into Jenkins and <a href="https://a.blazemeter.com/user" rel="nofollow">your BlazeMeter account.</a>
 <br>
  If the test list is empty, you must insert your unique BlazeMeter API key into the <a rel="nofollow">Jenkins settings</a>, or <a href="https://a.blazemeter.com/user/login?destination=cloud/testing/load/home/hello" rel="nofollow">create a test</a> in <a href="https://a.blazemeter.com/user" rel="nofollow">your BlazeMeter account.</a>
</div></div>

</li>
<li><code>abortJob : boolean</code> (optional)
<div><div>
 If checked and BlazeMeter test has fails plugin will throw AbortException
</div></div>

</li>
<li><code>additionalTestFiles : String</code> (optional)
<div><div>
 Before the test runs these files will be pushed to the selected BlazeMeter test. Existing files with the same name will be replaced. Provide a list of files that are locate in job workspace(relative path, each file on a new line).
</div>
<div>
 <i> Limitations: Supported test types: Taurus, FunctionalApi, JMeter </i>
</div></div>

</li>
<li><code>getJtl : boolean</code> (optional)
<div><div>
 Check this box if you need to download JTL report after test will be over.
</div></div>

</li>
<li><code>getJunit : boolean</code> (optional)
<div><div>
 Check this box if you need to download junit report after test will be over.
</div></div>

</li>
<li><code>jobApiKey : String</code> (optional)
</li>
<li><code>jtlPath : String</code> (optional)
<div><div>
 Here you can define desired location for downloading jtl artifact. 
 <br>
  Plugin supports both absolute and relative paths. 
 <br>
  Jenkins environment variables will be resolved.
</div></div>

</li>
<li><code>junitPath : String</code> (optional)
<div><div>
 Here you can define desired location for downloading junit artifact. 
 <br>
  Plugin supports both absolute and relative paths. 
 <br>
  Jenkins environment variables will be resolved.
</div></div>

</li>
<li><code>mainTestFile : String</code> (optional)
<div><div>
 Before the test runs this file will be pushed to the selected BlazeMeter test and select as executable file. Existing file with the same name will be replaced. Provide a file that is locate in job workspace(relative path).
</div>
<div>
 <i> Limitations: For Taurus and FunctionalApi tests will set 'Test type': JMeter if file has '.jmx' extension and Taurus - for '.yml' and '.yaml' files. Other 'Test types', please, set in the BlazeMeter application. Supported test types: Taurus, FunctionalApi, JMeter </i>
</div></div>

</li>
<li><code>notes : String</code> (optional)
<div><div>
 Enter here some notes that you want to attached to test report.
</div></div>

</li>
<li><code>reportLinkName : String</code> (optional)
<div><div>
 Report link name that you will see in your build. By default it'll set: "BlazeMeter report: BLAZEMETER_TEST_NAME", where BLAZEMETER_TEST_NAME is a test name from app. By default max report link name length = 35, but you can increase this value using Java System property or Jenkins environment variable "bzm.reportLinkName.length"
</div></div>

</li>
<li><code>selectWebhook : String</code> (optional)
</li>
<li><code>serverUrl : String</code> (optional)
</li>
<li><code>sessionProperties : String</code> (optional)
<div><div>
 Define jmeter properties for particular session in format key1=value1,key2=value2,key3=value3. 
 <br>
  Properties will be pushed to every separate session of master session.
</div></div>

</li>
<li><code>webhookUrl : String</code> (optional)
</li>
</ul>


++++
