= bootstraped-multi-test-results-report
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/bootstraped-multi-test-results-report">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'CucumberTestReportPublisher'])`: Publish Cucumber reports generated with handlebars
++++
<ul><li><code>reportsDirectory : String</code>
</li>
<li><code>fileIncludePattern : String</code>
</li>
<li><code>fileExcludePattern : String</code>
</li>
<li><code>markAsUnstable : boolean</code>
</li>
<li><code>copyHTMLInWorkspace : boolean</code>
</li>
<li><code>ignoreUndefinedSteps : boolean</code>
</li>
</ul>


++++
=== `step([$class: 'JUnitTestReportPublisher'])`: Publish JUnit reports generated with handlebars
++++
<ul><li><code>reportsDirectory : String</code>
</li>
<li><code>fileIncludePattern : String</code>
</li>
<li><code>fileExcludePattern : String</code>
</li>
<li><code>markAsUnstable : boolean</code>
</li>
<li><code>copyHTMLInWorkspace : boolean</code>
</li>
</ul>


++++
=== `step([$class: 'RSpecTestReportPublisher'])`: Publish RSpec reports generated with handlebars
++++
<ul><li><code>reportsDirectory : String</code>
</li>
<li><code>fileIncludePattern : String</code>
</li>
<li><code>fileExcludePattern : String</code>
</li>
<li><code>markAsUnstable : boolean</code>
</li>
<li><code>copyHTMLInWorkspace : boolean</code>
</li>
</ul>


++++
=== `step([$class: 'TestNGTestReportPublisher'])`: Publish TestNG reports generated with handlebars
++++
<ul><li><code>reportsDirectory : String</code>
</li>
<li><code>fileIncludePattern : String</code>
</li>
<li><code>fileExcludePattern : String</code>
</li>
<li><code>markAsUnstable : boolean</code>
</li>
<li><code>copyHTMLInWorkspace : boolean</code>
</li>
</ul>


++++
