= BrowserStack
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/browserstack-integration">Visit the Jenkins Plugins site</a>
++++


=== `browserStackReportPublisher`: BrowserStack Test Report
++++
<ul><li><code>product : String</code>
<div><div>
 Specify the product for which the report should be generated, i.e. automate or app-automate
</div></div>

</li>
</ul>


++++
=== `browserstack`: BrowserStack
++++
<ul><li><code>credentialsId : String</code>
<div><div>
 Select the BrowserStack credentials (username, access key) to use for this project.
 <br>
  These values will be available as <i>BROWSERSTACK_USERNAME</i> and <i>BROWSERSTACK_ACCESS_KEY</i> environment variables.
</div></div>

</li>
<li><code>localConfig</code> (optional)
<div><div>
 Use BrowserStack Local to securely access internal servers on BrowserStack VMs and Mobile devices.
 <br><strong>Skip this if you are using BrowserStack Local bindings in your code.</strong>
 <br>
 <ul>
  <li><i>BROWSERSTACK_LOCAL</i> environment variable is set with value <i>true</i></li>
  <li><i>BROWSERSTACK_LOCAL_IDENTIFIER</i> environment variable contains the unique identifier set for the local testing connection</li>
 </ul>
</div></div>

<ul><b>Nested Object</b>
<li><code>localPath : String</code>
</li>
<li><code>localOptions : String</code>
</li>
</ul></li>
<li><code>observabilityConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>tests : String</code>
</li>
<li><code>reRun : String</code>
</li>
</ul></li>
</ul>


++++
=== `browserstackAppUploader`: BrowserStack App Uploader
++++
<ul><li><code>appPath : String</code>
<div><div>
 Please specify the absolute path or relative to the app(.apk or .ipa) file to be uploaded. 
 <br>
  The app_url of the uploaded app can be accessed from the environment variable BROWSERSTACK_APP_ID.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'BrowserStackCypressReportPublisher'])`: BrowserStack Cypress Test Report
++++
<ul></ul>


++++
=== `step([$class: 'BrowserStackReportPublisher'])`: BrowserStack Test Report
++++
<ul></ul>


++++
