= Buckminster
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/buckminster">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'TargetPlatformPublisher'])`: Archive and publish an Eclipse Target Platform
++++
<div><div>
 Archives the build artifacts (for example, distribution zip files or jar files) so that they can be downloaded later. Archived files will be accessible from the Jenkins webpage. 
 <br>
  Normally, Jenkins keeps artifacts for a build as long as a build log itself is kept, but if you don't need old artifacts and would rather save disk space, you can do so.
</div>
<br>
<div>
 Note that the Maven job type automatically archives any produced Maven artifacts. Any artifacts configured here will be archived on top of that. Automatic artifact archiving can be disabled under the advanced Maven options.
</div>
<br>
<div>
 The <a href="https://www.jenkins.io/redirect/pipeline-snippet-generator" rel="nofollow"> Pipeline Snippet Generator </a> generates this example when all arguments are set to true (some arguments by default are true): 
 <pre><code>archiveArtifacts artifacts: '**/*.txt',
                   allowEmptyArchive: true,
                   fingerprint: true,
                   onlyIfSuccessful: true

</code></pre>
</div></div>
<ul><li><code>artifacts : String</code>
<div><div>
 You can use wildcards like 'module/dist/**/*.zip'. See <a href="https://ant.apache.org/manual/Types/fileset.html" rel="nofollow"> the includes attribute of Ant fileset </a> for the exact format -- except that <code>","</code> ( <em>comma</em> ) is the only supported separator. The base directory is <a rel="nofollow">the workspace</a> . You can only archive files that are located in your workspace.
</div>
<br>
<div>
 <p>Here are some examples of usage for pipeline:</p>
 <ul>
  <li>How to archive multiple artifacts from a specific folder: 
   <pre><code>archiveArtifacts artifacts: 'target/*.jar'</code></pre></li>
  <br>
  <li>How to archive multiple artifacts with different patterns: 
   <pre><code>archiveArtifacts artifacts: 'target/*.jar, target/*.war'</code></pre></li>
  <br>
  <li>How to archive multiple nested artifacts: 
   <pre><code>archiveArtifacts artifacts: '**/*.jar'</code></pre></li>
  <br>
 </ul>
</div></div>

</li>
<li><code>latestOnly : boolean</code>
</li>
<li><code>targetPlatformName : String</code>
</li>
<li><code>excludes : String</code> (optional)
<div><div>
 Optionally specify the 'excludes' pattern, such as "foo/bar/**/*". Use "," to set a list of patterns. A file that matches this mask will not be archived even if it matches the mask specified in 'files to archive' section.
</div></div>

</li>
<li><code>allowEmptyArchive : boolean</code> (optional)
<div><div>
 Normally, a build fails if archiving returns zero artifacts. This option allows the archiving process to return nothing without failing the build. Instead, the build will simply throw a warning.
</div></div>

</li>
<li><code>caseSensitive : boolean</code> (optional)
<div><div>
 Artifact archiver uses Ant <code>org.apache.tools.ant.DirectoryScanner</code> which by default is case sensitive. For instance, if the job produces *.hpi files, pattern "**/*.HPI" will fail to find them. 
 <br>
 <br>
  This option can be used to disable case sensitivity. When it's unchecked, pattern "**/*.HPI" will match any *.hpi files, or pattern "**/cAsEsEnSiTiVe.jar" will match a file called caseSensitive.jar.
</div></div>

</li>
<li><code>defaultExcludes : boolean</code> (optional)
</li>
<li><code>fingerprint : boolean</code> (optional)
</li>
<li><code>followSymlinks : boolean</code> (optional)
<div><div>
 By disabling this option all symbolic links found in the workspace will be ignored.
</div></div>

</li>
<li><code>onlyIfSuccessful : boolean</code> (optional)
</li>
</ul>


++++
