= Build Token Trigger Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/build-token-trigger">Visit the Jenkins Plugins site</a>
++++


=== `buildTokenTrigger`: Build Token Trigger
++++
<ul><li><code>job : String</code>
<div><div>
 The full name of the job. For example: <code>rootJob</code>, <code>rootFolder/childJob</code>, or <code>rootFolder/childFolder/grandchildJob</code>
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 The credentials to trigger the job with. Only <b>Jenkins Build Token</b> credentials are supported and they must be for the same Jenkins URL that the job is being triggered on.
</div></div>

</li>
<li><code>parameters</code>
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>delay : int</code> (optional)
<div><div>
 Leave blank to use the job's default quiet period, otherwise specify the number of seconds to use as the quiet period when queuing the job.
</div></div>

</li>
<li><code>ignoreMissing : boolean</code> (optional)
<div><div>
 By default, if the target job cannot be found then the step will fail. When this option is selected the step will ignore a <code>HTTP/404</code> response from the remote Jenkins and return <code>about:missing</code>
</div></div>

</li>
<li><code>ignoreUnqueued : boolean</code> (optional)
<div><div>
 By default, if the target job is not queued for execution then the step will fail. When this option is selected the step will ignore a <code>HTTP/302</code> response from the remote Jenkins and return <code>about:unqueued</code>.
</div></div>

</li>
<li><code>jenkinsUrl : String</code> (optional)
<div><div>
 The URL of the remote Jenkins to trigger a job on. If left blank and this Jenkins has had its URL configured then the step will attempt to trigger on this Jenkins.
</div></div>

</li>
</ul>


++++
