= Bumblebee HP ALM Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/bumblebee">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'AddTestToSetStep'])`: Bumblebee: Add Test to Test Set
++++
<ul><li><code>domain : String</code>
<div><div>
 HP ALM Domain
</div></div>

</li>
<li><code>project : String</code>
<div><div>
 HP ALM Project name
</div></div>

</li>
<li><code>testPlanPath : String</code>
<div><div>
 Path to a test or test folder in HP ALM which shall be added to a test set
</div></div>

</li>
<li><code>testSetPath : String</code>
<div><div>
 Path to a test set in HP ALM into which test(s) shall be added
</div></div>

</li>
</ul>


++++
=== `step([$class: 'BumblebeePublisher'])`: Bumblebee  HP  ALM  Uploader
++++
<ul><li><code>configs</code>
<ul><b>Array / List of Nested Object</b>
<li><code>domain : String</code>
</li>
<li><code>projectName : String</code>
</li>
<li><code>testPlan : String</code>
</li>
<li><code>testLab : String</code>
</li>
<li><code>testSet : String</code>
</li>
<li><code>format : String</code>
</li>
<li><code>resultPattern : String</code>
</li>
<li><code>customProperties : String</code>
</li>
<li><code>failIfUploadFailed : boolean</code>
</li>
<li><code>offline : boolean</code>
</li>
<li><code>defectCreatePolicy : String</code>
</li>
<li><code>defectCreateStatus : String</code>
</li>
<li><code>defectSeverity : String</code>
</li>
<li><code>defectReopenStatus : String</code>
</li>
<li><code>defectResolvePolicy : String</code>
</li>
<li><code>defectResolveStatus : String</code>
</li>
<li><code>defectCreateProperties : String</code>
</li>
<li><code>defectReopenProperties : String</code>
</li>
<li><code>defectResolveProperties : String</code>
</li>
</ul></li>
</ul>


++++
=== `step([$class: 'GetTestResults'])`: Bumblebee: Import HP ALM Test Results
++++
<ul><li><code>domain : String</code>
<div><div>
 HP ALM Domain
</div></div>

</li>
<li><code>project : String</code>
<div><div>
 HP ALM Project name
</div></div>

</li>
<li><code>resultsDir : String</code>
<div><div>
 Path to the directory where to put JUnit-like reports containing results of tests in HP ALM.
 <br>
  This path can be used for publishing JUnit reports in subsequent post-build action.
</div></div>

</li>
<li><code>configurations</code>
<ul><b>Array / List of Nested Object</b>
<li><code>testSetPath : String</code>
</li>
</ul></li>
<li><code>user : String</code> (optional)
<div><div>
 HP ALM Login Name. If set, this value overrides value from Bumblebee Global Configuration.
 <br>
 If empty, value from Bumblebee Global Configuration will be used
</div></div>

</li>
<li><code>password : String</code> (optional)
<div><div>
 HP ALM user's password. If set, this value overrides the value from Bumblebee Global Configuration. 
 <br>
 If empty, value from Bumblebee Global Configuration will be used
</div></div>

</li>
</ul>


++++
=== `step([$class: 'RunPcTestBuildStep'])`: Bumblebee HP PC Test Runner
++++
<ul><li><code>almPassword : String</code> (optional)
<div><div>
 HP ALM user's password. If set, this value overrides the value from Bumblebee Global Configuration. 
 <br>
 If empty, value from Bumblebee Global Configuration will be used
</div></div>

</li>
<li><code>almUser : String</code> (optional)
<div><div>
 HP ALM user. If set, this value overrides the value from Bumblebee Global Configuration. 
 <br>
 If empty, value from Bumblebee Global Configuration will be used
</div></div>

</li>
<li><code>domain : String</code> (optional)
<div><div>
 HP ALM Domain.
</div></div>

</li>
<li><code>failIfTaskFails : boolean</code> (optional)
<div><div>
 If task shall fail the build in case it fails.
</div></div>

</li>
<li><code>outputDir : String</code> (optional)
<div><div>
 Directory where Performance Center reports will be placed. Relative to the workspace root. If it does not exist, it will be created.
</div></div>

</li>
<li><code>pollingInterval : int</code> (optional)
<div><div>
 Test status polling interval in seconds.
</div></div>

</li>
<li><code>postRunActionString : String</code> (optional)
<div><div>
 Performance Center Post Run Action.
</div></div>

</li>
<li><code>project : String</code> (optional)
<div><div>
 HP ALM Project name.
</div></div>

</li>
<li><code>retryCollateAndAnalysisAttempts : int</code> (optional)
<div><div>
 Defines how many times it will retry Collate or Analyze phase if they failed, before task completely fails.
</div></div>

</li>
<li><code>retryCollateAndAnalysisFlag : boolean</code> (optional)
</li>
<li><code>retryCollateAndAnalysisInterval : int</code> (optional)
<div><div>
 Number of seconds to wait between retry attempts.
</div></div>

</li>
<li><code>retryCount : int</code> (optional)
<div><div>
 Number of retry attempts, before task completely fails.
</div></div>

</li>
<li><code>retryInterval : int</code> (optional)
<div><div>
 Number of seconds to wait between retry attempts.
</div></div>

</li>
<li><code>retryIntervalMultiplier : double</code> (optional)
<div><div>
 Increase factor for retry interval. E.g. if it is set to 2, then each subsequent wait interval between attempts will be twice bigger than the previous one.
</div></div>

</li>
<li><code>testLabPath : String</code> (optional)
<div><div>
 Path to a test set in HP ALM TestLab. Must start with Root\, e.g. Root\folder1\testSet1, where Root\folder1 is a path to test lab folder and testSet1 is the name of a test set. Test set will be created if it does not exist.
</div></div>

</li>
<li><code>testPlanPath : String</code> (optional)
<div><div>
 Path to a test in HP ALM TestPlan. Must start with Subject\, e.g. Subject\folder1\test1, where Subject\folder1 is a path to test folder and test1 is the name of a test.
</div></div>

</li>
<li><code>timeout : int</code> (optional)
<div><div>
 The number of minutes to wait for the Performance Center test to finish. 0 means wait indefinitely.
</div></div>

</li>
<li><code>timeslotDuration : int</code> (optional)
<div><div>
 Time Slot Duration in minutes.
</div></div>

</li>
<li><code>vudsMode : boolean</code> (optional)
<div><div>
 If true, the test consumes Virtual User Day (VUD) licenses.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'RunTestSetBuildStep'])`: Bumblebee HP ALM Test Set Runner
++++
<ul><li><code>domain : String</code>
<div><div>
 HP ALM Domain
</div></div>

</li>
<li><code>project : String</code>
<div><div>
 HP ALM Project name
</div></div>

</li>
<li><code>runMode : String</code>
<div><div>
 Where to run test sets: locally, on scheduled host or remotely
</div></div>

</li>
<li><code>host : String</code>
<div><div>
 Host on which test sets will be executed
</div></div>

</li>
<li><code>testSets : String</code>
<div><div>
 A list of test set paths to be executed. Each test set starts from a new line. Example: Root\Release\2.0
</div></div>

</li>
<li><code>outputDirPath : String</code>
<div><div>
 Path to the directory where to put JUnit-like execution results. Basedir of the fileset is the workspace root. If directory does not exist, it will be created
</div></div>

</li>
<li><code>timeOut : int</code>
<div><div>
 The number of minutes to wait for test sets execution. 0 means wait indefinitely
</div></div>

</li>
</ul>


++++
=== `step([$class: 'RunUftTestBuildStep'])`: Bumblebee Local UFT Test Runner
++++
<ul><li><code>testPath : String</code>
<div><div>
 Path to a test folder or test batch file (.mtb) which shall be executed
</div></div>

</li>
<li><code>outputDirPath : String</code>
<div><div>
 Path to the directory where to put JUnit-like execution results. Basedir of the fileset is the workspace root. If directory does not exist, it will be created
</div></div>

</li>
</ul>


++++
