= CA Service Virtualization Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/ca-service-virtualization">Visit the Jenkins Plugins site</a>
++++


=== `svCreateAndDeployVirtualService`: CA Service Virtualization - Create And Deploy Virtual Service
++++
<div><div>
 <p>Create and deploy Virtual Service from VSI/VSM, RR Pairs, or the following specifications: Swagger, WSDL, or RAML.</p>
</div></div>
<ul><li><code>useCustomRegistry : boolean</code>
<div><div>
 Set to true to override the default global connection setting to CA DevTest registry for the particular project
</div></div>

</li>
<li><code>host : String</code>
<div><div>
 The correct hostname or registry name needs to be entered
</div></div>

</li>
<li><code>port : String</code>
<div><div>
 Enter the port on which the registry is running. The default port is 1505. If you changed it, you can find the port in the LISA properties file as lisa.webserver.port followed by the port number
</div></div>

</li>
<li><code>vseName : String</code>
<div><div>
 Use the name of the VSE to which you want this build step to apply
</div></div>

</li>
<li><code>config : String</code>
<div><div>
 Configuration JSON 
 <br>
 <p>Example of using a configuration object that includes port and SSL information</p>
 <p>{ "virtualService": { "version": "2", "name": "API_Test_1", "description": "Invoke API V2", "status": "" }, "transportProtocol": { "typeId": "HTTP", "basePath": "/", "useGateway": true, "duptxns": true, "hostHeaderPassThrough": false }, "dataProtocol": { "forRequest": true, "typeId": "RESTDPH" } }</p>
</div></div>

</li>
<li><code>deploy : String</code>
<div><div>
 If true will atomically deploy the newly created virtual service on to the VSE
</div></div>

</li>
<li><code>undeploy : String</code>
<div><div>
 If selected will undeploy virtual service if it exists on Virtual Service Environment.
</div></div>

</li>
<li><code>inputFile1 : String</code>
<div><div>
 Path to input file that will be uploaded to the VSE. The input file can be Request/Response (file or zip), VSM/VSI, Swagger, RAML, or WADL file. 
 <br>
  Possibilities: 
 <p>for files in <strong>job workspace</strong> you can specify:</p>
 <ul>
  <li>relative path to input file in job workspace (<em>example: dir/test-req.txt</em>)</li>
 </ul>
 <p>for files on the <strong>DevTest machine</strong> you can specify:</p>
 <ul>
  <li>absolute path to file (<em>example: file:///C:/something/test-req.txt</em>)</li>
  <li><strong>http</strong> location of input file (<em>example: http://something/test-req.txt</em>)</li>
 </ul>
</div></div>

</li>
<li><code>inputFile2 : String</code>
<div><div>
 Path to input file that will be uploaded to the VSE. The input file can be Request/Response or VSM/VSI file. 
 <br>
  Possibilities: 
 <p>for files in <strong>job workspace</strong> you can specify:</p>
 <ul>
  <li>relative path to input file in job workspace (<em>example: dir/test-rsp.txt</em>)</li>
 </ul>
 <p>for files on the <strong>DevTest machine</strong> you can specify:</p>
 <ul>
  <li>absolute path to file (<em>example: file:///C:/something/test-rsp.txt</em>)</li>
  <li><strong>http</strong> location of input file (<em>example: http://something/test-rsp.txt</em>)</li>
 </ul>
</div></div>

</li>
<li><code>activeConfig : String</code>
<div><div>
 Path to active project config file that will be uploaded to the VSE. 
 <br>
  Possibilities: 
 <p>for files in <strong>job workspace</strong> you can specify:</p>
 <ul>
  <li>relative path to input file in job workspace (<em>example: dir/project.config</em>)</li>
 </ul>
 <p>for files on the <strong>DevTest machine</strong> you can specify:</p>
 <ul>
  <li>absolute path to file (<em>example: file:///C:/something/project.config</em>)</li>
 </ul>
</div></div>

</li>
<li><code>dataFiles : String</code>
<div><div>
 Path to data file that will be uploaded to the VSE. The input should be data file in one of the content type defined in &lt;LISA_HOME&gt;/contenttype.xml, 
 <br>
  Possibilities: 
 <p>for files in <strong>job workspace</strong> you can specify:</p>
 <ul>
  <li>relative path to input file in job workspace (<em>example: dir/data.csv</em>)</li>
 </ul>
 <p>for files on the <strong>DevTest machine</strong> you can specify:</p>
 <ul>
  <li>absolute path to file (<em>example: file:///C:/something/data.csv</em>)</li>
 </ul>
</div></div>

</li>
<li><code>swaggerurl : String</code>
<div><div>
 Swagger (OpenAPI) 2.0 or 3.0 document URL
</div></div>

</li>
<li><code>ramlurl : String</code>
<div><div>
 RAML 0.8 spec URL
</div></div>

</li>
<li><code>wadlurl : String</code>
<div><div>
 WADL URL
</div></div>

</li>
<li><code>tokenCredentialId : String</code>
<div><div>
 <p>The ID for the integration token from the Credentials plugin to be used to connect to Registry endpoint. The "Kind" of the credential must be "Username with password".</p>
</div></div>

</li>
<li><code>secured : boolean</code>
<div><div>
 Set to true if the CA DevTest API are set to accept only https connections
</div></div>

</li>
</ul>


++++
=== `svDeployTest`: CA Service Virtualization - Deploy Test
++++
<div><div>
 <p>Deploys and starts CA DevTest test or test suite provided as a .mar file.</p>
 <p>Throws exception if .mar file is incorrect, authorization to CA DevTest fails or connection to CA DevTest cannot be established.</p>
</div></div>
<ul><li><code>useCustomRegistry : boolean</code>
<div><div>
 Set to true to override the default global connection setting to CA DevTest registry for the particular project
</div></div>

</li>
<li><code>host : String</code>
<div><div>
 The correct hostname or registry name needs to be entered
</div></div>

</li>
<li><code>port : String</code>
<div><div>
 Enter the port on which the registry is running. The default port is 1505. If you changed it, you can find the port in the LISA properties file as lisa.webserver.port followed by the port number
</div></div>

</li>
<li><code>marFilePath : String</code>
<div><div>
 Path to MAR file that will be uploaded to the VSE. Needs to be relative path to MAR file in job workspace.
</div></div>

</li>
<li><code>testType : String</code>
<div><div>
 Choose whether mar file contains test or test suite.
</div></div>

</li>
<li><code>tokenCredentialId : String</code>
<div><div>
 <p>The ID for the integration token from the Credentials plugin to be used to connect to Registry endpoint. The "Kind" of the credential must be "Username with password".</p>
</div></div>

</li>
<li><code>secured : boolean</code>
<div><div>
 Set to true if the CA DevTest API are set to accept only https connections
</div></div>

</li>
</ul>


++++
=== `svDeployVirtualService`: CA Service Virtualization - Deploy Virtual Service
++++
<div><div>
 <p>Deploys and starts virtual service provided as a .mar file to target VSE. More services could be provided using comma or newline separator.</p>
 <p>Throws exception if .mar file is incorrect, virtual service is already deployed, authorization to CA DevTest fails or connection to CA DevTest cannot be established.</p>
</div></div>
<ul><li><code>useCustomRegistry : boolean</code>
<div><div>
 Set to true to override the default global connection setting to CA DevTest registry for the particular project
</div></div>

</li>
<li><code>host : String</code>
<div><div>
 The correct hostname or registry name needs to be entered
</div></div>

</li>
<li><code>port : String</code>
<div><div>
 Enter the port on which the registry is running. The default port is 1505. If you changed it, you can find the port in the LISA properties file as lisa.webserver.port followed by the port number
</div></div>

</li>
<li><code>vseName : String</code>
<div><div>
 Use the name of the VSE to which you want this build step to apply
</div></div>

</li>
<li><code>marFilesPaths : String</code>
<div><div>
 Path to MAR file that will be uploaded to the VSE. The field supports multiple strings delimited by a separate line or comma. 
 <br>
  Possibilities: 
 <p>for files in <strong>job workspace</strong> you can specify:</p>
 <ul>
  <li>relative path to MAR file in job workspace (<em>example: dir/test.mar</em>)</li>
  <li>path to MAR files using ant glob syntax (<em>example: **/*.mar</em>)</li>
 </ul>
 <p>for files on the <strong>DevTest machine</strong> you can specify:</p>
 <ul>
  <li>absolute path to file (<em>example: file:///C:/something/test.mar</em>)</li>
  <li><strong>http</strong> location of MAR file (<em>example: http://something/test.mar</em>)</li>
 </ul>
</div></div>

</li>
<li><code>tokenCredentialId : String</code>
<div><div>
 <p>The ID for the integration token from the Credentials plugin to be used to connect to Registry endpoint. The "Kind" of the credential must be "Username with password".</p>
</div></div>

</li>
<li><code>secured : boolean</code>
<div><div>
 Set to true if the CA DevTest API are set to accept only https connections
</div></div>

</li>
</ul>


++++
=== `svStartVirtualService`: CA Service Virtualization - Start Virtual Service
++++
<div><div>
 <p>Starts virtual service that is already deployed on target VSE. More services could be started using comma or newline separator.</p>
 <p>Throws exception if virtual service does not exist on specified VSE, authorization to CA DevTest fails or connection to CA DevTest cannot be established.</p>
</div></div>
<ul><li><code>useCustomRegistry : boolean</code>
<div><div>
 Set to true to override the default global connection setting to CA DevTest registry for the particular project
</div></div>

</li>
<li><code>host : String</code>
<div><div>
 The correct hostname or registry name needs to be entered
</div></div>

</li>
<li><code>port : String</code>
<div><div>
 Enter the port on which the registry is running. The default port is 1505. If you changed it, you can find the port in the LISA properties file as lisa.webserver.port followed by the port number
</div></div>

</li>
<li><code>vseName : String</code>
<div><div>
 Use the name of the VSE to which you want this build step to apply
</div></div>

</li>
<li><code>vsNames : String</code>
<div><div>
 Names of Virtual Services existing on provided VSE delimited by a separate line or comma.
</div></div>

</li>
<li><code>tokenCredentialId : String</code>
<div><div>
 <p>The ID for the integration token from the Credentials plugin to be used to connect to Registry endpoint. The "Kind" of the credential must be "Username with password".</p>
</div></div>

</li>
<li><code>secured : boolean</code>
<div><div>
 Set to true if the CA DevTest API are set to accept only https connections
</div></div>

</li>
</ul>


++++
=== `svStopVirtualService`: CA Service Virtualization - Stop Virtual Service
++++
<div><div>
 <p>Stops virtual service that is running on target VSE. More services could be stopped using comma or newline separator.</p>
 <p>Throws exception if virtual service is not running on specified VSE, authorization to CA DevTest fails or connection to CA DevTest cannot be established.</p>
</div></div>
<ul><li><code>useCustomRegistry : boolean</code>
<div><div>
 Set to true to override the default global connection setting to CA DevTest registry for the particular project
</div></div>

</li>
<li><code>host : String</code>
<div><div>
 The correct hostname or registry name needs to be entered
</div></div>

</li>
<li><code>port : String</code>
<div><div>
 Enter the port on which the registry is running. The default port is 1505. If you changed it, you can find the port in the LISA properties file as lisa.webserver.port followed by the port number
</div></div>

</li>
<li><code>vseName : String</code>
<div><div>
 Use the name of the VSE to which you want this build step to apply
</div></div>

</li>
<li><code>vsNames : String</code>
<div><div>
 Names of Virtual Services existing on provided VSE delimited by a separate line or comma.
</div></div>

</li>
<li><code>tokenCredentialId : String</code>
<div><div>
 <p>The ID for the integration token from the Credentials plugin to be used to connect to Registry endpoint. The "Kind" of the credential must be "Username with password".</p>
</div></div>

</li>
<li><code>secured : boolean</code>
<div><div>
 Set to true if the CA DevTest API are set to accept only https connections
</div></div>

</li>
</ul>


++++
=== `svPublishTestReport`: CA Service Virtualization Report Publisher
++++
<div><div>
 <p>Generates simple test or test suite report that is available as a part of project run.</p>
</div></div>
<ul></ul>


++++
=== `svUndeployVirtualService`: CA Service Virtualization - Undeploy  Virtual Service
++++
<div><div>
 <p>Undeploys (removes) virtual service from specified VSE. More services could be provided using comma or newline separator.</p>
 <p>Throws exception if virtual service does not exist on specified VSE, authorization to CA DevTest fails or connection to CA DevTest cannot be established</p>
</div></div>
<ul><li><code>useCustomRegistry : boolean</code>
<div><div>
 Set to true to override the default global connection setting to CA DevTest registry for the particular project
</div></div>

</li>
<li><code>host : String</code>
<div><div>
 The correct hostname or registry name needs to be entered
</div></div>

</li>
<li><code>port : String</code>
<div><div>
 Enter the port on which the registry is running. The default port is 1505. If you changed it, you can find the port in the LISA properties file as lisa.webserver.port followed by the port number
</div></div>

</li>
<li><code>vseName : String</code>
<div><div>
 Use the name of the VSE to which you want this build step to apply
</div></div>

</li>
<li><code>vsNames : String</code>
<div><div>
 Names of Virtual Services existing on provided VSE delimited by a separate line or comma.
</div></div>

</li>
<li><code>tokenCredentialId : String</code>
<div><div>
 <p>The ID for the integration token from the Credentials plugin to be used to connect to Registry endpoint. The "Kind" of the credential must be "Username with password".</p>
</div></div>

</li>
<li><code>secured : boolean</code>
<div><div>
 Set to true if the CA DevTest API are set to accept only https connections
</div></div>

</li>
</ul>


++++
