= NS-ND Integration Performance Publisher Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/cavisson-ns-nd-integration">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'CreateVM'])`: Create Virtual Server
++++
<ul><li><code>INSTANCE_NAME : String</code>
</li>
<li><code>GCP_PROJECT_ID : String</code>
</li>
<li><code>IMAGE_NAME : String</code>
</li>
<li><code>scriptType : String</code>
</li>
</ul>


++++
=== `step([$class: 'CreateVirtualService'])`: Cavisson Service Virtualization : Create
++++
<ul><li><code>config : String</code>
</li>
<li><code>rrFilePath : String</code>
</li>
<li><code>host : String</code>
</li>
<li><code>username : String</code>
</li>
<li><code>password</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>isstart : boolean</code>
</li>
<li><code>token</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
</ul>


++++
=== `step([$class: 'DeleteVirtualService'])`: Cavisson Service Virtualization : Delete
++++
<ul><li><code>serviceName : String</code>
</li>
</ul>


++++
=== `step([$class: 'DestroyVM'])`: Destroy VM 
++++
<ul><li><code>INSTANCE_NAME : String</code>
</li>
<li><code>GCP_PROJECT_ID : String</code>
</li>
<li><code>IMAGE_NAME : String</code>
</li>
</ul>


++++
=== `step([$class: 'DisableVirtualService'])`: Cavisson Service Virtualization : Disable
++++
<ul><li><code>serviceName : String</code>
</li>
</ul>


++++
=== `step([$class: 'EditVirtualService'])`: Cavisson Service Virtualization : Edit
++++
<ul><li><code>config : String</code>
</li>
</ul>


++++
=== `step([$class: 'EnableVirtualService'])`: Cavisson Service Virtualization : Enable
++++
<ul><li><code>serviceName : String</code>
</li>
</ul>


++++
=== `step([$class: 'FetchTestAssets'])`: Fetch Test Assets
++++
<ul><li><code>username : String</code>
</li>
<li><code>profile : String</code>
</li>
<li><code>giturl : String</code>
</li>
<li><code>ipAddress : String</code>
</li>
</ul>


++++
=== `step([$class: 'NSNDIntegrationResultsPublisher'])`: NS/NC-ND Integration Performance Publisher
++++
<ul><li><code>nsIntegrationUri : String</code>
</li>
<li><code>nsUsername : String</code>
</li>
<li><code>nsPassword : String</code>
</li>
<li><code>ndIntegrationUri : String</code>
</li>
<li><code>ndUsername : String</code>
</li>
<li><code>ndPassword : String</code>
</li>
<li><code>base1StartTime : String</code>
</li>
<li><code>base1EndTime : String</code>
</li>
<li><code>base2StartTime : String</code>
</li>
<li><code>base2EndTime : String</code>
</li>
<li><code>base3StartTime : String</code>
</li>
<li><code>base3EndTime : String</code>
</li>
<li><code>checkProfilePath : String</code>
</li>
<li><code>criThreshold : String</code>
</li>
<li><code>warThreshold : String</code>
</li>
<li><code>failThreshold : String</code>
</li>
<li><code>timePeriod : String</code>
</li>
<li><code>curStartTimeAbsolute : String</code>
</li>
<li><code>curEndTimeAbsolute : String</code>
</li>
<li><code>curStartTimeElapsed : String</code>
</li>
<li><code>curEndTimeElapsed : String</code>
</li>
<li><code>phase : String</code>
</li>
<li><code>base1MSRName : String</code>
</li>
<li><code>base2MSRName : String</code>
</li>
<li><code>base3MSRName : String</code>
</li>
</ul>


++++
=== `step([$class: 'NetDiagnosticsResultsPublisher'])`: NetDiagnostics Performance Publisher
++++
<ul><li><code>netdiagnosticsUri : String</code>
</li>
<li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
<li><code>base1StartTime : String</code>
</li>
<li><code>base1EndTime : String</code>
</li>
<li><code>base2EndTime : String</code>
</li>
<li><code>base2StartTime : String</code>
</li>
<li><code>base3StartTime : String</code>
</li>
<li><code>base3EndTime : String</code>
</li>
<li><code>checkProfilePath : String</code>
</li>
<li><code>criThreshold : String</code>
</li>
<li><code>warThreshold : String</code>
</li>
<li><code>failThreshold : String</code>
</li>
<li><code>curStartTime : String</code>
</li>
<li><code>curEndTime : String</code>
</li>
<li><code>base1MSRName : String</code>
</li>
<li><code>base2MSRName : String</code>
</li>
<li><code>base3MSRName : String</code>
</li>
<li><code>profile : String</code>
</li>
</ul>


++++
=== `step([$class: 'NetStormBuilder'])`: Execute NetStorm/NetCloud Test
++++
<div><div>
 This build step can be used to invoke Netstorm tasks
</div></div>
<ul><li><code>URLConnectionString : String</code>
</li>
<li><code>username : String</code>
</li>
<li><code>password : <code>Object</code></code>
</li>
<li><code>project : String</code>
</li>
<li><code>subProject : String</code>
</li>
<li><code>scenario : String</code>
</li>
<li><code>testMode : String</code>
</li>
<li><code>baselineType : String</code>
</li>
<li><code>pollInterval : String</code>
</li>
<li><code>profile : String</code>
</li>
<li><code>generateReport : boolean</code>
</li>
<li><code>doNotWaitForTestCompletion : boolean</code>
</li>
<li><code>rampupDuration : String</code>
</li>
<li><code>skipSSLCertCheck : boolean</code>
</li>
<li><code>skipSSLHostCheck : boolean</code>
</li>
<li><code>protocol : String</code> (optional)
</li>
<li><code>repoIp : String</code> (optional)
</li>
<li><code>repoPort : String</code> (optional)
</li>
<li><code>repoPath : String</code> (optional)
</li>
<li><code>repoUsername : String</code> (optional)
</li>
<li><code>repoPassword : String</code> (optional)
</li>
<li><code>script : String</code> (optional)
</li>
<li><code>page : String</code> (optional)
</li>
<li><code>advanceSett : String</code> (optional)
</li>
<li><code>urlHeader : String</code> (optional)
</li>
<li><code>hiddenBox : String</code> (optional)
</li>
<li><code>gitPull : String</code> (optional)
</li>
<li><code>testProfileBox : String</code> (optional)
</li>
<li><code>totalusers : String</code> (optional)
</li>
<li><code>rampUpSec : String</code> (optional)
</li>
<li><code>rampupmin : String</code> (optional)
</li>
<li><code>rampuphour : String</code> (optional)
</li>
<li><code>duration : String</code> (optional)
</li>
<li><code>serverhost : String</code> (optional)
</li>
<li><code>sla : String</code> (optional)
</li>
<li><code>testName : String</code> (optional)
</li>
<li><code>scriptPath : String</code> (optional)
</li>
<li><code>emailid : String</code> (optional)
</li>
<li><code>emailidCC : String</code> (optional)
</li>
<li><code>emailidBcc : String</code> (optional)
</li>
<li><code>testsuite : String</code> (optional)
</li>
<li><code>dataDir : String</code> (optional)
</li>
<li><code>checkRuleFileUpload : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'NetStormResultsPublisher'])`: NetStorm/NetCloud Performance Publisher
++++
<ul><li><code>netstormUri : String</code>
</li>
<li><code>username : String</code>
</li>
<li><code>password : <code>Object</code></code>
</li>
<li><code>htmlTable</code>
<ul><li><b>Type:</b> <code>class net.sf.json.JSONObject</code></li>
</ul></li>
<li><code>project : String</code>
</li>
<li><code>subProject : String</code>
</li>
<li><code>scenario : String</code>
</li>
<li><code>durationReport : boolean</code>
</li>
<li><code>profile : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul>


++++
