= Cerberus Testing Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/cerberus-testing">Visit the Jenkins Plugins site</a>
++++


=== `executeCerberusCampaign`: Execute Cerberus Campaign
++++
<ul><li><code>campaignName : String</code>
<div><div>
 Enter the campaign name.
</div></div>

</li>
<li><code>environment : String</code>
</li>
<li><code>browser : String</code>
<div><div>
 either
 <br>
  - Robot
 <br>
  or
 <br>
  - Robot server ip + Robot server port + browser
 <br>
 <br>
  If you enter a robot, no need to enter Robot server ip + Robot server port + browser
</div></div>

</li>
<li><code>screenshot : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>pageSource : String</code>
</li>
<li><code>seleniumLog : String</code>
</li>
<li><code>timeOut : String</code>
</li>
<li><code>retries : String</code>
</li>
<li><code>priority : String</code>
</li>
<li><code>tag : String</code>
<div><div>
 Tag for the execution of this campaign. Tag is used to group and display all testcases execution of the campaign.
 <br>
  Use <strong>$[current_timestamp]</strong> to put the current timestamp to the job execution.
</div></div>

</li>
<li><code>ss_p : String</code>
<div><div>
 either
 <br>
  - Robot
 <br>
  or
 <br>
  - Robot server ip + Robot server port + browser
 <br>
 <br>
  If you enter a robot, no need to enter Robot server ip + Robot server port + browser
</div></div>

</li>
<li><code>ssIp : String</code>
<div><div>
 either
 <br>
  - Robot
 <br>
  or
 <br>
  - Robot server ip + Robot server port + browser
 <br>
 <br>
  If you enter a robot, no need to enter Robot server ip + Robot server port + browser
</div></div>

</li>
<li><code>robot : String</code>
<div><div>
 either
 <br>
  - Robot
 <br>
  or
 <br>
  - Robot server ip + Robot server port + browser
 <br>
 <br>
  If you enter a robot, no need to enter Robot server ip + Robot server port + browser
</div></div>

</li>
<li><code>manualHost : String</code>
</li>
<li><code>manualContextRoot : String</code>
</li>
<li><code>country : String</code>
<div><div>
 If empty, the countries defined on the campaign will be used.
</div></div>

</li>
<li><code>cerberusUrl : String</code>
</li>
<li><code>timeOutForCampaignExecution : int</code>
</li>
<li><code>executor : String</code>
</li>
</ul>


++++
