= Chatter Notifier Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/chatter-notifier">Visit the Jenkins Plugins site</a>
++++


=== `chatterPost`: Post to Chatter
++++
<div><div>
 Simple step for posting a Chatter buildUrlTitle/body to a specified channel or the user's wall.
 <br>
  Usage Example:
 <br><code> postToChatter "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (&lt;${env.BUILD_URL}|Open&gt;)" </code>
</div></div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Utilizes the <a href="https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Plugin" rel="nofollow">Credentials Plugin's</a> <em>Username with Password</em> credentials storage to communicate with Chatter. 
 <p>If you're connecting from outside of your organizations trusted network, you'll also need to append your API security token to your password.</p>
 <p>See Identity Confirmation in the salesforce.com online help for more information.</p>
</div></div>

</li>
<li><code>body : String</code>
<div><div>
 The body text for your Chatter post
</div></div>

</li>
<li><code>buildUrlTitle : String</code> (optional)
<div><div>
 The buildUrlTitle for your Chatter post. If left blank, the title will be set to your job/pipeline name and number (JOB_NAME BUILD_DISPLAY_NAME)
</div></div>

</li>
<li><code>recordId : String</code> (optional)
<div><div>
 Id of record to chatter to (e.g. a group, or a custom object), leave blank to chatter to user's wall.
</div></div>

</li>
<li><code>server : String</code> (optional)
<div><div>
 If left blank will connect to production, if you want to connect to a sandbox or have the my domains feature enabled, enter URL of alternative login server, e.g. https://test.salesforce.com
</div></div>

</li>
</ul>


++++
