= Checks API plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/checks-api">Visit the Jenkins Plugins site</a>
++++


=== `publishChecks`: Publish customized checks to SCM platforms
++++
<ul><li><code>actions</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>label : String</code>
<div><div>
 The label to be displayed on the checks report for this action.
</div></div>

</li>
<li><code>identifier : String</code>
<div><div>
 The unique identifier for the action. Since for SCM platforms like GitHub, this is the only field that would be sent back to your Jenkins instance when an action is requested, so you may need to use this field to have more information besides the basic type of the action.
</div></div>

</li>
<li><code>description : String</code> (optional)
<div><div>
 Detailed description of the action's purpose, functionality, and so on.
</div></div>

</li>
</ul></li>
<li><code>annotations</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
<div><div>
 Path to the file to be annotated, started from the project root directory.
</div></div>

</li>
<li><code>startLine : int</code>
<div><div>
 Start line of code to be annotated.
</div></div>

</li>
<li><code>endLine : int</code>
<div><div>
 End line of code to be annotated.
</div></div>

</li>
<li><code>message : String</code>
<div><div>
 A digest message of the annotation.
</div></div>

</li>
<li><code>annotationLevel</code> (optional)
<div><div>
 Severity level of the annotation, can be one of can be "NOTICE", "WARNING", or "FAILURE"; by default, "WARNING" will be used.
</div></div>

<ul><li><b>Values:</b> <code>NONE</code>, <code>NOTICE</code>, <code>WARNING</code>, <code>FAILURE</code></li></ul></li>
<li><code>endColumn : int</code> (optional)
<div><div>
 End column of code to be annotated.
</div></div>

</li>
<li><code>rawDetails : String</code> (optional)
<div><div>
 Raw details of the annotation.
</div></div>

</li>
<li><code>startColumn : int</code> (optional)
<div><div>
 Start column of code to be annotated.
</div></div>

</li>
<li><code>title : String</code> (optional)
<div><div>
 Title of the annotation.
</div></div>

</li>
</ul></li>
<li><code>conclusion</code> (optional)
<div><div>
 The conclusion of the check, can be "ACTION_REQUIRED", "SKIPPED", "CANCELED", "TIME_OUT", "FAILURE", "NEUTRAL", "SUCCESS" or "NONE". By default, "SUCCESS" will be used. When providing the conclusion other than "NONE", please make sure the status is "COMPLETED".
</div></div>

<ul><li><b>Values:</b> <code>NONE</code>, <code>ACTION_REQUIRED</code>, <code>SKIPPED</code>, <code>CANCELED</code>, <code>TIME_OUT</code>, <code>FAILURE</code>, <code>NEUTRAL</code>, <code>SUCCESS</code></li></ul></li>
<li><code>detailsURL : String</code> (optional)
<div><div>
 The URL of the site where full details can be found. When providing this parameter, make sure it is http or https scheme.
</div></div>

</li>
<li><code>name : String</code> (optional)
<div><div>
 Name or identifier of the check.
</div></div>

</li>
<li><code>status</code> (optional)
<div><div>
 The status of the check, can be "QUEUED", "IN_PROGRESS", or "COMPLETED". By default, "COMPLETED" will be used.
</div></div>

<ul><li><b>Values:</b> <code>NONE</code>, <code>QUEUED</code>, <code>IN_PROGRESS</code>, <code>COMPLETED</code></li></ul></li>
<li><code>summary : String</code> (optional)
<div><div>
 The summary of the check run. This field supports Markdown.
</div></div>

</li>
<li><code>text : String</code> (optional)
<div><div>
 The details of the check. This parameter supports Markdown.
</div></div>

</li>
<li><code>title : String</code> (optional)
<div><div>
 The title of the check run.
</div></div>

</li>
</ul>


++++
=== `withChecks`: Inject checks properties into its closure
++++
<ul><li><code>name : String</code>
</li>
<li><code>includeStage : boolean</code> (optional)
</li>
</ul>


++++
