= Checkmarx Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/checkmarx">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'CxScanBuilder'])`: Execute Checkmarx Scan
++++
<ul><li><code>credentialsId : String</code>
<div><div>
 This option is for users that may already have Jenkins credentials, as defined in Jenkins, and would like to use them with the CxSAST Jenkins plugin. Select your credentials from the drop-down list. 
 <br>
 NOTE: If your credentials do not exist in the system, you can add them by clicking Add and selecting Jenkins (see Adding Jenkins Credentials to the CxSAST Jenkins Plugin, for more information).
</div></div>

</li>
<li><code>sastCredentialsId : String</code>
</li>
<li><code>buildStep : String</code>
</li>
<li><code>teamPath : String</code>
</li>
<li><code>sastEnabled : boolean</code>
</li>
<li><code>exclusionsSetting : String</code>
</li>
<li><code>failBuildOnNewResults : boolean</code>
<div><div>
 Enables the option to fail the build according to the defined severity (or higher). This option works in addition to the regular thresholds (e.g. if "x" total high vulnerabilities were found OR at least 1 new vulnerability, fail the build). This option is only available if the "Enable vulnerability threshold" parameter is enabled.
</div></div>

</li>
<li><code>failBuildOnNewSeverity : String</code>
</li>
<li><code>useOwnServerCredentials : boolean</code> (optional)
</li>
<li><code>serverUrl : String</code> (optional)
<div><div>
 Checkmarx server url or ip address with or without port. Syntax: http(s)://server-name:port. Example: http://checkmarx-server, https://10.0.0.255:9495
</div></div>

</li>
<li><code>username : String</code> (optional)
<div><div>
 Login username
</div></div>

</li>
<li><code>password : String</code> (optional)
<div><div>
 Login password
</div></div>

</li>
<li><code>isProxy : boolean</code> (optional)
</li>
<li><code>configAsCode : boolean</code> (optional)
<div><div>
 Create cx.config config-as-code input file at the root of the repo in '.checkmarx' folder. For example .checkmarx/cx.config
</div></div>

</li>
<li><code>projectName : String</code> (optional)
<div><div>
 A full absolute name of a project. The full Project name includes the whole path to the project, including Server, service provider, company, and team. Example: "CxServer\SP\Company\Users\bs_java" If project with such a name doesn't exist in the system, new project will be created. May reference build parameters like ${PARAM}.
</div></div>

</li>
<li><code>projectId : long</code> (optional)
</li>
<li><code>projectRetentionRate : int</code> (optional)
</li>
<li><code>groupId : String</code> (optional)
<div><div>
 Fully qualified team name for the project.
</div></div>

</li>
<li><code>preset : String</code> (optional)
<div><div>
 Select the scan preset for this project
</div></div>

</li>
<li><code>jobStatusOnError</code> (optional)
<div><div>
 Determines how to act when a triggered Checkmarx scan in synchronous mode fails and returns an error message (i.e. no scan results, not to be confused with valid scan results that exceed the threshold). 
 <ul>
  <li>FAILURE is equivalent to a Job error that fails the entire build.</li>
  <li>UNSTABLE is equivalent to a Job warning that allows the build to proceed normally but provides an unstable status upon completion.</li>
  <li>Use the global setting implies that this project uses the value either FAILURE or UNSTABLE defined globally by the CxSAST Jenkins plugin.</li>
 </ul>
</div></div>

<ul><li><b>Values:</b> <code>GLOBAL</code>, <code>FAILURE</code>, <code>UNSTABLE</code>, <code>ABORTED</code></li></ul></li>
<li><code>scaReportFormat</code> (optional)
<ul><li><b>Values:</b> <code>PDF</code>, <code>XML</code>, <code>CSV</code>, <code>JSON</code>, <code>cyclonedxjson</code>, <code>cyclonedxxml</code></li></ul></li>
<li><code>presetSpecified : boolean</code> (optional)
</li>
<li><code>excludeFolders : String</code> (optional)
<div><div>
 Comma separated list of folders to exclude from scan. Entries in this list are automatically converted to exclude wildcard patterns and appended to the full pattern list provided in the advanced section. May reference build parameters like ${PARAM}. 
 <p>Conversion is done as follows: <br><code>fold1, fold2 fold3</code><br>
   is converted to: <br><code>!**/fold1/**/*, !**/fold2/**/*, !**/fold3/**/*, </code></p>
</div></div>

</li>
<li><code>filterPattern : String</code> (optional)
<div><div>
 Comma separated list of include or exclude wildcard patterns. Exclude patterns start with exclamation mark "!". 
 <p>Example: <code>**/*.java, <code>**/*.html, !**\test\**\XYZ*</code> </code></p><code>
  <h5>Pattern Syntax</h5>
  <p>A given directory is recursively scanned for all files and directories. Each file/directory is matched against a set of selectors, including special support for matching against filenames with include and exclude patterns. Only files/directories which match at least one pattern of the include pattern list, and don't match any pattern of the exclude pattern list will be placed in the list of files/directories found.</p>
  <p>When no list of include patterns is supplied, "**" will be used, which means that everything will be matched. When no list of exclude patterns is supplied, an empty list is used, such that nothing will be excluded. When no selectors are supplied, none are applied.</p>
  <p>The filename pattern matching is done as follows: The name to be matched is split up in path segments. A path segment is the name of a directory or file, which is bounded by <code>File.separator</code> ('/' under UNIX, '\' under Windows). For example, "abc/def/ghi/xyz.java" is split up in the segments "abc", "def","ghi" and "xyz.java". The same is done for the pattern against which should be matched.</p>
  <p>The segments of the name and the pattern are then matched against each other. When '**' is used for a path segment in the pattern, it matches zero or more path segments of the name.</p>
  <p>There is a special case regarding the use of <code>File.separator</code>s at the beginning of the pattern and the string to match:<br>
    When a pattern starts with a <code>File.separator</code>, the string to match must also start with a <code>File.separator</code>. When a pattern does not start with a <code>File.separator</code>, the string to match may not start with a <code>File.separator</code>. When one of these rules is not obeyed, the string will not match.</p>
  <p>When a name path segment is matched against a pattern path segment, the following special characters can be used:<br>
    '*' matches zero or more characters<br>
    '?' matches one character.</p>
  <p>May reference build parameters like ${PARAM}.</p>
  <p>Examples:</p>
  <p>"**\*.class" matches all .class files/dirs in a directory tree.</p>
  <p>"test\a??.java" matches all files/dirs which start with an 'a', then two more characters and then ".java", in a directory called test.</p>
  <p>"**" matches everything in a directory tree.</p>
  <p>"**\test\**\XYZ*" matches all files/dirs which start with "XYZ" and where there is a parent directory called test (e.g. "abc\test\def\ghi\XYZ123").</p></code>
</div></div>

</li>
<li><code>incremental : boolean</code> (optional)
<div><div>
 Run incremental scan instead of full scan.
</div></div>

</li>
<li><code>fullScansScheduled : boolean</code> (optional)
</li>
<li><code>fullScanCycle : int</code> (optional)
<div><div>
 Incremental scans are faster, but with time they become less accurate.
 <br>
  Therefore, after a number of incremental scans it is recommended to perform a full scan.
 <br>
  Here you can schedule periodic full scans to be executed after a certain number of incremental scans.
 <br>
 <br>
  Alternatively, if you want to run full scans on weekends, you can create 2 separate jobs.
 <br>
  First job - to run incremental scans on weekdays and second job - to run full scans on weekends.
</div></div>

</li>
<li><code>postScanActionId : int</code> (optional)
<div><div>
 Select Post Scan Action name that is to be performed automatically after a scan.(Note that the feature works with 9.3 version SAST onwards.)
</div></div>

</li>
<li><code>sourceEncoding : String</code> (optional)
<div><div>
 Source code character encoding.
</div></div>

</li>
<li><code>comment : String</code> (optional)
<div><div>
 Free text comment. If the comment contains variables like ${GIT_COMMIT}, ${GIT_BRANCH}, ${GIT_URL}, ${GIT_AUTHOR_NAME} or any Jenkins variable. It shall be expanded as long as it is a valid variable available to Jenkins else considers it as plain text.
</div></div>

</li>
<li><code>skipSCMTriggers : boolean</code> (optional)
<div><div>
 Do not perform Checkmarx scan when the build was triggered by SCM Change.
</div></div>

</li>
<li><code>waitForResultsEnabled : boolean</code> (optional)
<div><div>
 In synchronous mode, Checkmarx build step will wait for Checkmarx scan to complete, then retrieve scan results and optionally check vulnerability thresholds. When disabled, the build step finishes after scan job submissions to Checkmarx server.
</div></div>

</li>
<li><code>vulnerabilityThresholdEnabled : boolean</code> (optional)
<div><div>
 Mark the build as unstable if the number of high severity vulnerabilities is above the specified threshold.
</div></div>

</li>
<li><code>highThreshold : int</code> (optional)
<div><div>
 High severity vulnerability threshold. If set, the threshold is crossed if number of high severity vulnerabilities exceeds it.
</div></div>

</li>
<li><code>mediumThreshold : int</code> (optional)
<div><div>
 Medium severity vulnerability threshold. If set, the threshold is crossed if number of medium severity vulnerabilities exceeds it.
</div></div>

</li>
<li><code>lowThreshold : int</code> (optional)
<div><div>
 Low severity vulnerability threshold. If set, the threshold is crossed if number of low severity vulnerabilities exceeds it.
</div></div>

</li>
<li><code>osaHighThreshold : int</code> (optional)
<div><div>
 High severity vulnerabilities threshold for dependency scan. If set, the threshold is crossed if number of high severity vulnerabilities exceeds it.
</div></div>

</li>
<li><code>osaMediumThreshold : int</code> (optional)
<div><div>
 Medium severity vulnerabilities threshold for dependency scan. If set, the threshold is crossed if number of medium severity vulnerabilities exceeds it.
</div></div>

</li>
<li><code>osaLowThreshold : int</code> (optional)
<div><div>
 Low severity vulnerabilities threshold for dependency scan. If set, the threshold is crossed if number of low severity vulnerabilities exceeds it.
</div></div>

</li>
<li><code>generatePdfReport : boolean</code> (optional)
<div><div>
 Downloads a PDF report with scan results from the Checkmarx server. The report is available via a link on "Checkmarx Scan Results" page.
</div></div>

</li>
<li><code>generateScaReport : boolean</code> (optional)
<div><div>
 Downloads a report with scan results from the Checkmarx server. The report is available via a link on "Checkmarx Scan Results" page.
</div></div>

</li>
<li><code>enableProjectPolicyEnforcement : boolean</code> (optional)
<div>Mark the build as failed or unstable if the project's policy is violated.
<br>
 Note:
<br>
 Assigning a policy to a project is done from within CxSAST
<br>
 For SAST scan Mno is required, by default it is not supported in 9.6 SAST server.</div>

</li>
<li><code>enableProjectPolicyEnforcementSCA : boolean</code> (optional)
<div>Mark the build as failed or unstable if the project's policy is violated.
<br>
 Note:
<br>
 Assigning a policy to a project is done from within CxSCA
<br></div>

</li>
<li><code>thresholdSettings : String</code> (optional)
</li>
<li><code>vulnerabilityThresholdResult : String</code> (optional)
</li>
<li><code>exceptionOnThresholdError : boolean</code> (optional)
<div><div>
 Choose if build should throw "Threshold exceeded" exception and stop the scan in case when result of scan vulnerabilities exceeds threshold. Default is False.
</div></div>

</li>
<li><code>avoidDuplicateProjectScans : boolean</code> (optional)
<div><div>
 If there is a scan of this project in the queue in status working or queued do not send a new scan request to Checkmarx
</div></div>

</li>
<li><code>addGlobalCommenToBuildCommet : boolean</code> (optional)
<div><div>
 Allow global sast comment to be added to the build comment.By default the global comment is empty. When both job level comments and global comments are provided and 'Allow Global comment' is selected, then both comments shall be concatenated.
</div></div>

</li>
<li><code>generateXmlReport : boolean</code> (optional)
<div><div>
 Generate full XML and HTML CxSAST scan reports. These reports will contain additional information about the detected vulnerabilities
</div></div>

</li>
<li><code>hideDebugLogs : boolean</code> (optional)
<div><div>
 Enabling this will not generate any debug level logs in the job output.
</div></div>

</li>
<li><code>forceScan : boolean</code> (optional)
<div><div>
 Force Scan - If force scan is enabled, SAST will perform scan even if there are no code changes.
</div></div>

</li>
<li><code>customFields : String</code> (optional)
<div><div>
 Add scan level custom fields and its value. Example: field1:value1,field2:value2.(Note that the feature works with 9.4 version SAST onwards.)
</div></div>

</li>
<li><code>projectLevelCustomFields : String</code> (optional)
<div><div>
 Add project level custom fields and its value. Example: field1:value1,field2:value2.(Note that the feature works with 9.4 version SAST onwards.)
</div></div>

</li>
<li><code>dependencyScanConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>SASTUserName : String</code> (optional)
</li>
<li><code>dependencyScanExcludeFolders : String</code> (optional)
</li>
<li><code>dependencyScanPatterns : String</code> (optional)
</li>
<li><code>dependencyScannerType</code> (optional)
<ul><li><b>Values:</b> <code>OSA</code>, <code>SCA</code></li></ul></li>
<li><code>enableScaResolver</code> (optional)
<ul><li><b>Values:</b> <code>SCA_RESOLVER</code>, <code>MANIFEST</code></li></ul></li>
<li><code>fsaVariables : String</code> (optional)
</li>
<li><code>generateScaReport : boolean</code> (optional)
</li>
<li><code>globalScaResolverAddParameters : String</code> (optional)
</li>
<li><code>isExploitablePath : boolean</code> (optional)
</li>
<li><code>isExploitablePathByScaResolver : boolean</code> (optional)
</li>
<li><code>isGlobalExploitablePathByScaResolver : boolean</code> (optional)
</li>
<li><code>isIncludeSources : boolean</code> (optional)
</li>
<li><code>osaArchiveIncludePatterns : String</code> (optional)
</li>
<li><code>osaInstallBeforeScan : boolean</code> (optional)
</li>
<li><code>overrideGlobalConfig : boolean</code> (optional)
</li>
<li><code>pathToScaResolver : String</code> (optional)
</li>
<li><code>sastCredentialsId : String</code> (optional)
</li>
<li><code>scaAccessControlUrl : String</code> (optional)
</li>
<li><code>scaConfigFile : String</code> (optional)
</li>
<li><code>scaCredentialsId : String</code> (optional)
</li>
<li><code>scaEnvVariables : String</code> (optional)
</li>
<li><code>scaProjectCustomTags : String</code> (optional)
</li>
<li><code>scaResolverAddParameters : String</code> (optional)
</li>
<li><code>scaSASTProjectFullPath : String</code> (optional)
</li>
<li><code>scaSASTProjectID : String</code> (optional)
</li>
<li><code>scaSastServerUrl : String</code> (optional)
</li>
<li><code>scaScanCustomTags : String</code> (optional)
</li>
<li><code>scaServerUrl : String</code> (optional)
</li>
<li><code>scaTeamId : String</code> (optional)
</li>
<li><code>scaTeamPath : String</code> (optional)
</li>
<li><code>scaTenant : String</code> (optional)
</li>
<li><code>scaTimeout : int</code> (optional)
</li>
<li><code>scaWebAppUrl : String</code> (optional)
</li>
<li><code>useJobLevelSastDetails : boolean</code> (optional)
</li>
</ul></li>
<li><code>excludeOpenSourceFolders : String</code> (optional)
</li>
<li><code>includeOpenSourceFolders : String</code> (optional)
</li>
<li><code>osaArchiveIncludePatterns : String</code> (optional)
<div><br>
 Comma separated list of archive wildcard patterns to include their extracted content for the scan. eg. *.zip, *.jar, *.ear
<br>
 Supported archive types are: jar, war, ear, sca, gem, whl, egg, tar, tar.gz, tgz, zip, rar
<br>
 Leave empty to extract all archives</div>

</li>
<li><code>osaEnabled : boolean</code> (optional)
</li>
<li><code>osaInstallBeforeScan : boolean</code> (optional)
<div><div>
 Select this option in order to be able to scan packages from various dependency managers (NPM, Nugget, Python and more.) as part of the CxOSA scan
</div></div>

</li>
<li><code>overrideGlobalRetentionRate : boolean</code> (optional)
</li>
<li><code>overrideProjectSetting : boolean</code> (optional)
<div><div>
 When selected, preset &amp; engine configuration value selected in the pipeline will be saved on the CxSAST project.
</div></div>

</li>
<li><code>thisBuildIncremental : boolean</code> (optional)
</li>
</ul>


++++
