= Checkmarx AST Scanner Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/checkmarx-ast-scanner">Visit the Jenkins Plugins site</a>
++++


=== `checkmarxASTScanner`: Execute Checkmarx AST Scan
++++
<ul><li><code>useOwnServerCredentials : boolean</code> (optional)
</li>
<li><code>serverUrl : String</code> (optional)
<div><div>
 The base URL of your CxAST environment.
</div></div>

</li>
<li><code>useAuthenticationUrl : boolean</code> (optional)
<div><div>
 The base URL of your Checkmarx authentication server (IAM). Required for CxAST cloud platform.
</div></div>

</li>
<li><code>baseAuthUrl : String</code> (optional)
</li>
<li><code>tenantName : String</code> (optional)
</li>
<li><code>projectName : String</code> (optional)
<div><div>
 The name of your Project in CxAST. If you enter the name of an existing Project, then this build step will trigger a scan of that Project. If you enter a new Project name, then, when a scan is triggered it will create a new Project in CxAST with the specified name.
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 Create "Checkmarx Client Id and Client Secret" type credentials in Jenkins and enter your oAuth2 clientId and secret. This will be used to authenticate access to the CxAST platform whenever a scan is triggered.
</div></div>

</li>
<li><code>useOwnAdditionalOptions : boolean</code> (optional)
</li>
<li><code>additionalOptions : String</code> (optional)
<div><div>
 You can customize your scan by adding additional arguments. The Jenkins plugin supports all CxAST CLI arguments. See documentation <a href="https://checkmarx.com/resource/documents/en/34965-68643-scan.html#UUID-a0bb20d5-5182-3fb4-3da0-0e263344ffe7" rel="nofollow">here</a>
 <br>
  e.g- --sast-incremental true
</div></div>

</li>
<li><code>branchName : String</code> (optional)
</li>
<li><code>checkmarxInstallation : String</code> (optional)
<div><div>
 Select the Checkmarx CLI installation in Jenkins that will be used for triggering scans. This should have been configured in the Jenkins Global Tool Configuration section.
</div></div>

</li>
</ul>


++++
