= Cisco Spark Notifier
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/cisco-spark-notifier">Visit the Jenkins Plugins site</a>
++++


=== `sparkSend`: Send spark message
++++
<div><div>
 Spark Notifier Plugin sends messages to spark spaces 
 <br>
 <br>
  Make sure you add the correct bot or user to the space
</div></div>
<ul><li><code>message : String</code>
<div><div>
 Define the message to send to spark space 
 <br>
 <br>
  Environment variable examples: 
 <ul>
  <li>$BUILD_URL</li>
  <li>${BUILD_URL}</li>
  <li>${env.BUILD_URL}</li>
 </ul> Commonly used variables: 
 <ul>
  <li>${JOB_NAME}</li>
  <li>${JOB_URL}</li>
  <li>${BUILD_NUMBER}</li>
  <li>${BUILD_URL}</li>
  <li>${BUILD_DISPLAY_NAME}</li>
  <li>${BUILD_ID}</li>
  <li>${BUILD_TAG}</li>
  <li>${JAVA_HOME}</li>
  <li>${JAVA_VERSION}</li>
  <li>${JENKINS_URL}</li>
  <li>${JENKINS_VERSION}</li>
  <li>${NODE_LABELS}</li>
  <li>${NODE_NAME}</li>
  <li>${PATH}</li>
  <li>${PWD}</li>
  <li>${EXECUTOR_NUMBER}</li>
 </ul> if using SCM or SCM trigger (see the corresponding plugin wiki for additional environment variables): 
 <ul>
  <li>${BRANCH_NAME}</li>
  <li>${CHANGE_ID}</li>
  <li>${CHANGE_URL}</li>
  <li>${CHANGE_TITLE}</li>
  <li>${CHANGE_AUTHOR}</li>
  <li>${CHANGE_AUTHOR_DISPLAY_NAME}</li>
  <li>${CHANGE_AUTHOR_EMAIL}</li>
  <li>${CHANGE_TARGET}</li>
 </ul> Environment variables injected into the step from withEnv and withCredentials can also be used
</div></div>

</li>
<li><code>spaceList</code>
<div><div>
 To get the Space ID, go to web.ciscospark.com, select the space you want to message and get the ID from the URL. 
 <br>
 <br>
  Example: https://web.ciscospark.com/#/rooms/f2fbc1f0-317c-11e6-8308-f3bee39e57c5 
 <br>
  The Space ID would be: f2fbc1f0-317c-11e6-8308-f3bee39e57c5 
 <br>
 <br>
 <br>
  You can also use the room ID representation acquired from GET https://api.ciscospark.com/v1/rooms 
 <br>
 <br>
  See https://developer.ciscospark.com/endpoint-rooms-get.html for more information
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>spaceName : String</code>
</li>
<li><code>spaceId : String</code>
</li>
</ul></li>
<li><code>credentialsId : String</code>
</li>
<li><code>disable : boolean</code> (optional)
</li>
<li><code>failOnError : boolean</code> (optional)
</li>
<li><code>messageType : String</code> (optional)
</li>
</ul>


++++
