= CloudShare Docker-Machine Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/cloudshare-docker">Visit the Jenkins Plugins site</a>
++++


=== `cloudshareDockerMachine`: CloudShare Docker-Machine
++++
<ul><li><code>name : String</code> (optional)
<div><div>
 Override the default docker-machine name for this project. 
 <br>
  You can use environment variables. The default value is jenkins-$JOB_NAME, which means an environment by the name of docker-machine-jenkins-[job name] would be used.
</div></div>

</li>
<li><code>expiryDays : int</code> (optional)
</li>
</ul>


++++
=== `wrap([$class: 'DockerMachineWrapper'])`: Run Docker commands on CloudShare VM
++++
<ul><li><code>name : String</code>
<div><div>
 Override the default docker-machine name for this project. 
 <br>
  You can use environment variables. 
 <br>
  The default value is jenkins-$JOB_NAME, which means a CloudShare environment by the name of docker-machine-jenkins-[job name] would be used (docker-machine- is always prefixed by the docker-machine driver). 
 <br>
  Remember to also in <a rel="nofollow">configure the CloudShare API keys</a>.
</div></div>

</li>
<li><code>expiryDays : String</code>
</li>
</ul>


++++
