= CMake plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/cmakebuilder">Visit the Jenkins Plugins site</a>
++++


=== `cmake`: Run cmake with arbitrary arguments
++++
<div><div>
 Runs the tool and returns the exit code of the process.
</div></div>
<ul><li><code>installation : String</code>
</li>
<li><code>arguments : String</code> (optional)
</li>
<li><code>ignoredExitCodes : String</code> (optional)
</li>
<li><code>label : String</code> (optional)
<div><div>
 Allows to display a more meaningful text in the console output, the pipeline step view and the blue ocean details for this step, like with stages.
 <br>
  If non-empty, the specified text will be displayed instead of the default step type description.
</div></div>

</li>
<li><code>workingDir : String</code> (optional)
</li>
</ul>


++++
=== `cmakeBuild`: Generate build-scripts with cmake and execute them
++++
<div><div>
 Uses CMake to generate build-scripts and can run these.
 <br>
  This invokes <code>cmake</code> with the given options to generate the build scripts.
 <br>
  Any non-zero exit code during build-script generation causes Jenkins to mark the build as a failure. 
 <p>To run the generated build script, you have to add <i>build tool invocation</i> steps.</p> For example, to run the equivalent of the <code>sh</code> shell script 
 <pre><code>
   mkdir build &amp;&amp; cd build
   cmake -G Ninja &lt;workpace-root&gt;/source
   DESTDIR=&lt;workpace-root&gt;/artifacts ninja all install
  </code></pre> you would enter the following pipeline script: 
 <pre><code>
  cmakeBuild
      generator: 'Ninja',
      buildDir: 'build',
      sourceDir: 'source',
      installation: 'InSearchPath',
      steps: [
          [args: 'all install', envVars: 'DESTDIR=${WORKSPACE}/artifacts']
      ]
  </code></pre>
</div></div>
<ul><li><code>installation : String</code>
</li>
<li><code>buildDir : String</code> (optional)
</li>
<li><code>buildType : String</code> (optional)
</li>
<li><code>cleanBuild : boolean</code> (optional)
</li>
<li><code>cmakeArgs : String</code> (optional)
</li>
<li><code>generator : String</code> (optional)
</li>
<li><code>label : String</code> (optional)
<div><div>
 Allows to display a more meaningful text in the console output, the pipeline step view and the blue ocean details for this step, like with stages.
 <br>
  If non-empty, the specified text will be displayed instead of the default step type description.
</div></div>

</li>
<li><code>preloadScript : String</code> (optional)
</li>
<li><code>sourceDir : String</code> (optional)
</li>
<li><code>steps</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>args : String</code> (optional)
<div><div>
 Specify arguments to pass to the build tool or to <code>cmake</code>. Arguments must be separated by spaces but may contain spaces if they are enclosed in double quotes (will be handled like a Unix shell does),
 <br>
  Most of the time, you will want to leave this empty (to call the default build target) or you will specify just some build target names here.
</div></div>

</li>
<li><code>envVars : String</code> (optional)
<div><div>
 Specify extra environment variables to pass to the build tool as key-value pairs here.
 <br>
  Each entry must be on its own line, for example:
 <br><code>DESTDIR=${WORKSPACE}/artifacts/dir<br>
   KEY=VALUE</code>
</div></div>

</li>
<li><code>withCmake : boolean</code> (optional)
<div><div>
 Whether to run the actual build tool directly (by expanding <code>$CMAKE_BUILD_TOOL</code>) or to have <code>cmake</code> run the build tool (by invoking <code>cmake --build &lt;dir&gt;</code>). 
 <ul>
  <li>Leave unchecked for minimal performance overhead.</li>
  <li>Make it checked, if you selected one of the <em>Visual Studio</em> or <em>Xcode</em> generators above <strong>AND</strong> if you run CMake v. 2.8.11 or newer.</li>
 </ul>
</div></div>

</li>
</ul></li>
</ul>


++++
=== `cpack`: Run cpack
++++
<div><div>
 Runs the tool and returns the exit code of the process.
</div></div>
<ul><li><code>installation : String</code>
</li>
<li><code>arguments : String</code> (optional)
</li>
<li><code>ignoredExitCodes : String</code> (optional)
</li>
<li><code>label : String</code> (optional)
<div><div>
 Allows to display a more meaningful text in the console output, the pipeline step view and the blue ocean details for this step, like with stages.
 <br>
  If non-empty, the specified text will be displayed instead of the default step type description.
</div></div>

</li>
<li><code>workingDir : String</code> (optional)
</li>
</ul>


++++
=== `ctest`: Run ctest
++++
<div><div>
 Runs the tool and returns the exit code of the process.
</div></div>
<ul><li><code>installation : String</code>
</li>
<li><code>arguments : String</code> (optional)
</li>
<li><code>ignoredExitCodes : String</code> (optional)
</li>
<li><code>label : String</code> (optional)
<div><div>
 Allows to display a more meaningful text in the console output, the pipeline step view and the blue ocean details for this step, like with stages.
 <br>
  If non-empty, the specified text will be displayed instead of the default step type description.
</div></div>

</li>
<li><code>workingDir : String</code> (optional)
</li>
</ul>


++++
