= CodeSonar Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/codesonar">Visit the Jenkins Plugins site</a>
++++


=== `codesonar`: CodeSonar
++++
<ul><li><code>conditions</code>
<div><div>
 Choose the condition you want CodeSonar to use for build verification
</div></div>

<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>warningCountIncreaseNewOnly</code><div>
<div><p>Condition will trigger the warranted result if the amount of warnings that did not exist until the current analysis is exceeded by more than the designated percentage.</p>
<p>Maximum percentage increase - if the percentage of warnings exceed this amount it will mark build with the desired result [default 5.0]</p>
<p>Mark build as - the desired result if the condition is triggered.</p></div>
<ul><li><code>percentage : String</code> (optional)
</li>
<li><code>warrantedResult : String</code> (optional)
</li>
</ul></div></li>
<li><code>cyclomaticComplexity</code><div>
<div><p>Condition will change the result of the build if the cyclomatic complexity of procedures exceeds the preset value.</p>
<p>Cyclomatic complexity limit - The procedures with cyclomatic complexity that exceeds this value will change the build result. [default 30]</p>
<p>Mark build as - the desired result if the condition is triggered.</p></div>
<ul><li><code>maxCyclomaticComplexity : int</code> (optional)
</li>
<li><code>warrantedResult : String</code> (optional)
</li>
</ul></div></li>
<li><code>redAlerts</code><div>
<div><p>Condition will change the result of the build if the amount of red alerts exceed the predefined value.</p>
<p>Maximum amount of alerts - the maximum allowed amount of red alerts [default 1]</p>
<p>Mark build as - the desired result if the condition is triggered.</p></div>
<ul><li><code>alertLimit : int</code> (optional)
</li>
<li><code>warrantedResult : String</code> (optional)
</li>
</ul></div></li>
<li><code>warningCountAbsoluteSpecifiedScoreAndHigher</code><div>
<div><p>Condition will change the result of the build if the number of warnings above the predefined rank is greater then the maximum allowable.</p>
<p>Rank of warnings - only warnings that are at or above this rank will be checked. [default 56]</p>
<p>Maximum warnings - if the number of warnings at or above the specified score exceed this amount it will mark build with the desired result [default 20]</p>
<p>Mark build as - the desired result if the condition is triggered.</p></div>
<ul><li><code>rankOfWarnings : int</code>
</li>
<li><code>warningCountThreshold : int</code>
</li>
<li><code>warrantedResult : String</code> (optional)
</li>
</ul></div></li>
<li><code>warningCountIncreaseOverall</code><div>
<div><p>Condition will change the result of the build if the amount of warnings the analysis produces is greater than the preset percentage.</p>
<p>Maximum percentage increase - if the percentage of warnings exceed this amount it will mark build with the desired result [default 5.0]</p>
<p>Mark build as - the desired result if the condition is triggered.</p></div>
<ul><li><code>percentage : String</code>
</li>
<li><code>warrantedResult : String</code> (optional)
</li>
</ul></div></li>
<li><code>warningCountIncreaseSpecifiedScoreAndHigher</code><div>
<div><p>Condition will change the result of the build if the percentage of warnings bellow the predefined rank increases above a certain percentage.</p>
<p>Rank of warnings - Only warnings that are bellow this rank will be checked. [default 30]</p>
<p>Maximum percentage increase - if the percentage of warnings exceed this amount it will mark build with the desired result [default 5.0]</p>
<p>Mark build as - the desired result if the condition is triggered.</p></div>
<ul><li><code>rankOfWarnings : int</code>
</li>
<li><code>warningPercentage : String</code>
</li>
<li><code>warrantedResult : String</code> (optional)
</li>
</ul></div></li>
<li><code>yellowAlerts</code><div>
<div><p>Condition will change the result of the build if the amount of yellow alerts exceed the predefined value.</p>
<p>Maximum amount of alerts - the maximum allowed amount of yellow alerts [default 1]</p>
<p>Mark build as - the desired result if the condition is triggered.</p></div>
<ul><li><code>alertLimit : int</code> (optional)
</li>
<li><code>warrantedResult : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>protocol : String</code>
<div><div>
 Choose http or https
</div></div>

</li>
<li><code>hubAddress : String</code>
<div><div>
 Your hub location as <i>host:port</i> without protocol. For example, <code>myhub.example.com:7340</code>
</div></div>

</li>
<li><code>projectName : String</code>
<div><div>
 The CodeSonar project path. 
 <br>
  This is used to identify analysis results for previous, related Jenkins builds. It should be set to the same CodeSonar hub project path used in your <code>codesonar build</code> and <code>codesonar anaylze</code> commands. The project path is determined by the codesonar <code>-project</code> option if present, or the base name of the CodeSonar project file. This field is required.
</div></div>

</li>
<li><code>credentialId : String</code>
<div><div>
 CodeSonar Hub user account credentials. 
 <br>
  Credentials used to authenticate the CodeSonar operations that you will be invoking within Jenkins. 
 <br>
  Provide one of the following. 
 <ul>
  <li>A Credentials parameter of type <b>Username with password</b>, containing the hub user account username and password.</li>
  <li>A Credentials parameter of type <b>Certificate</b>, containing the user certificate and its private key in PKCS#12 format.</li>
 </ul>
 <br>
  This account must have sufficient permissions to: 
 <br>
 <ul>
  <li>Sign into the hub.</li>
  <li>Analyze the project you are interested in.</li>
  <li>Create a launch daemon.</li>
  <li>Browse analysis results.</li>
 </ul>
 <br>
  With factory settings, it is sufficient for the hub user account to have the built-in <code>Enabled</code> and <code>User</code> roles.
</div></div>

</li>
<li><code>visibilityFilter : String</code> (optional)
<div><div>
 <p>A CodeSonar warning visibility filter. <br><b>CodeSonar conditions</b> based on "number of warnings" are evaluated with respect to this filter.</p>
 <ul>
  <li>
   <p>You can specify a warning visibility filter by <em>name</em> or by numeric <em>ID</em>.</p></li>
  <li>
   <p>By default, the <em>active</em> filter is used.</p></li>
  <li>
   <p>To view the list of available warning visibility filters, including their names, IDs, and search definitions, see the <strong>Warnings</strong> tab of the <strong>Saved Searches</strong> page in the CodeSonar GUI.</p>
   <p><strong>MANUAL</strong>: Using CodeSonar &gt; GUI Reference &gt; Searching &gt; GUI: Saved Searches</p></li>
 </ul>
</div></div>

</li>
<li><code>aid : String</code> (optional)
<div><div>
 The analysis ID of the CodeSonar analysis results to use. 
 <br>
  If this field is not specified, the plugin will use the analysis results associated with your CodeSonar Project File. 
 <br>
  NOTE: This attribute is intended to be used in scripted pipeline projects. It is not typically useful for freestyle projects, and should be left blank.
</div></div>

</li>
<li><code>comparisonAnalysis : String</code> (optional)
<div><div>
 ID of a CodeSonar analysis to use as a base of comparison for "Warning Count Increase" conditions. 
 <br>
  If this field is not specified, the plugin will use the analysis results corresponding to the latest successful Jenkins build (if present).
</div></div>

</li>
<li><code>newWarningsFilter : String</code> (optional)
<div><div>
 <p>A CodeSonar warning visibility filter. <br><b>CodeSonar conditions</b> based on "number of new warnings" are evaluated with respect to this filter.</p>
 <ul>
  <li>
   <p>You can specify a warning visibility filter by <em>name</em> or by numeric <em>ID</em>.</p></li>
  <li>
   <p>By default, the <em>new</em> filter is used.</p></li>
  <li>
   <p>To view the list of available warning visibility filters, including their names, IDs, and search definitions, see the <strong>Warnings</strong> tab of the <strong>Saved Searches</strong> page in the CodeSonar GUI.</p>
   <p><strong>MANUAL</strong>: Using CodeSonar &gt; GUI Reference &gt; Searching &gt; GUI: Saved Searches</p></li>
 </ul>
</div></div>

</li>
<li><code>projectFile : String</code> (optional)
<div><div>
 CodeSonar project file path. 
 <br>
  This should match the project file path you specified in your codesonar build and codesonar analyze command lines. 
 <br>
  Relative paths are interpreted with respect to the Jenkins build working directory.
</div></div>

</li>
<li><code>serverCertificateCredentialId : String</code> (optional)
<div><div>
 CodeSonar Hub server certificate. 
 <br>
  [Optional, HTTPS hubs only] 
 <br>
  A Credentials parameter of type secret file, where the file contains the hub server certificate in PEM format (Base-64 encoded ASCII). 
 <br>
  This setting is useful if your hub is not automatically trusted by your Jenkins server, for example, if your hub uses a self-signed certificate.
</div></div>

</li>
<li><code>socketTimeoutMS : int</code> (optional)
<div><div>
 Use this attribute to override default connection timeout.
</div></div>

</li>
</ul>


++++
