= CodeScene Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/codescene">Visit the Jenkins Plugins site</a>
++++


=== `codescene`: Run CodeScene Delta Analysis
++++
<ul><li><code>credentialsId : String</code>
<div>Select username/password credentials defined in Jenkins configuration. This is a safe way to use credentials in Jenkins plugin. See <a href="https://support.cloudbees.com/hc/en-us/articles/203802500-Injecting-Secrets-into-Jenkins-Build-Jobs" rel="nofollow">Injecting Secrets into Jenkins Build Jobs</a> for more details.</div>

</li>
<li><code>deltaAnalysisUrl : String</code>
</li>
<li><code>repository : String</code>
</li>
<li><code>analyzeBranchDiff : boolean</code> (optional)
</li>
<li><code>analyzeLatestIndividually : boolean</code> (optional)
<div><div>
 Commits not seen in previous successful builds will be used for separate delta analyses.
</div></div>

</li>
<li><code>baseRevision : String</code> (optional)
</li>
<li><code>couplingThresholdPercent : int</code> (optional)
</li>
<li><code>failOnDecliningCodeHealth : boolean</code> (optional)
<div><div>
 Check this option to mark the build as unstable if the Code Health of a hotspot declines.
</div></div>

</li>
<li><code>failOnFailedGoal : boolean</code> (optional)
<div><div>
 Check this option to mark the build as unstable if a goal -- as defined by CodeScene's Intelligent Notes -- is violated. This could be a supervised hotspot that suddenly declines in Code Health, or a module indicated as No Problem that starts to accumulate complex code, etc.
</div></div>

</li>
<li><code>letBuildPassOnFailedAnalysis : boolean</code> (optional)
<div><div>
 By default we fail the build if CodeScene couldn't run an analysis (e.g. couldn't update the repository). This behaviour can be overridden here.
</div></div>

</li>
<li><code>markBuildAsUnstable : boolean</code> (optional)
</li>
<li><code>originUrl : String</code> (optional)
</li>
<li><code>riskThreshold : int</code> (optional)
</li>
</ul>


++++
