= BMC AMI DevX Total Test
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/compuware-topaz-for-total-test">Visit the Jenkins Plugins site</a>
++++


=== `totaltestUT`: Total Test - Execute unit tests
++++
<ul><li><code>connectionId : String</code>
<div><div>
 This field specifies the host connection to use to execute on.
 <p></p> Host connections can be configured in the Jenkins system configuration (Manage Jenkins -&gt; Configure System).
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 The available credentials to use for logging onto the host. Alternatively, click <b>Add</b> to add credentials using the Credentials Plugin. Refer to the Jenkins documentation for the Credentials Plugin.
</div></div>

</li>
<li><code>projectFolder : String</code>
<div><div>
 The path to the Total Test project folder containing the test scenario or test suite to run.
</div></div>

</li>
<li><code>testSuite : String</code>
<div><div>
 A comma separated list of Total Test test scenarios/suites names. On Windows the names are case-insensitive. 
 <p>Wild carding of test scenarios/suites names can be done using '*' for any characters and '?' for a single character. 'All_Scenarios' can be used to run all test scenarios or 'All_Suites' can be used to run all test suites.</p>
</div></div>

</li>
<li><code>jcl : String</code>
<div><div>
 The name of the JCL file to run the Total Test test scenario or test suite.
</div></div>

</li>
<li><code>ccClearStats : boolean</code> (optional)
<div><div>
 Indicates if the Code Coverage repository statistics should be cleared before running the test.
</div></div>

</li>
<li><code>ccDB2 : boolean</code> (optional)
</li>
<li><code>ccPgmType : String</code> (optional)
<div><div>
 The type of the program specified on the EXEC statement, in the JCL, for the Total Test step. If PGM=IKJEFT01 was specified, select "Live DB2". When PGM=DFSRRC00 was specified select "Live IMS", otherwise select TotalTest.
</div></div>

</li>
<li><code>ccRepo : String</code> (optional)
<div><div>
 The dataset where Total Test will write coverage information. This dataset will later be fed into the Code Coverage reporting system. Members with like systems, names, and compile date and times will automatically be merged together.
</div></div>

</li>
<li><code>ccSystem : String</code> (optional)
<div><div>
 A system name for this test. Code Coverage keeps statistics by programs separate by system name. This name can be any-specified name. The name must be 16 characters or less and will be converted to upper-case when the test is run.s. If not specified defaults to the test scenario/suite name.
</div></div>

</li>
<li><code>ccTestId : String</code> (optional)
<div><div>
 A test identification to be added to the Code Coverage test. This information can be useful when reviewing test reports from Code Coverage. This test identification can be any-specified string. The test identification must be 16 characters or less and will be converted to upper-case when the test is run. If not specified defaults to the test scenario/suite name.
</div></div>

</li>
<li><code>deleteTemp : boolean</code> (optional)
<div><div>
 Delete temporary files after test run. The default is to delete temporary files.
</div></div>

</li>
<li><code>hlq : String</code> (optional)
<div><div>
 Optional high level qualifier to be used when allocating datasets.
</div></div>

</li>
<li><code>hostPort : String</code> (optional)
</li>
<li><code>recursive : boolean</code> (optional)
<div><div>
 Indicates if the test runner should recursively check for Total Test Unit Test projects. The default is not to recursively check for Total Test Unit Test projects..
</div></div>

</li>
<li><code>useStubs : boolean</code> (optional)
<div><div>
 Indicates if stubs should be used when running the test scenario or test suite. The default is to use stubs.
</div></div>

</li>
</ul>


++++
=== `totaltest`: Total Test - Execute Total Test scenarios
++++
<ul><li><code>environmentId : String</code>
<div><div>
 Environment ID of the environment defined in the Total Test repository server or local TotalTestConfiguration directory where tests are executed.
</div></div>

</li>
<li><code>folderPath : String</code>
<div><div>
 <ul>
  <li>Folder path to the test scenario or context file(s) to execute (.xactx or .xaunit)</li>
  <li>A relative path or an empty string will set the folder path relative to the Jenkins workspace directory</li>
  <li>An absolute path can also be used to specify Test folder path</li>
 </ul>
</div></div>

</li>
<li><code>serverUrl : String</code>
<div><div>
 This field specifies the CES URL where the Total Test repository server is published on.
 <p></p> The CES URL can be configured in Jenkins system configuration (Manage Jenkins -&gt; Configure System -&gt; BMC Configurations -&gt; Host Connections).
</div></div>

</li>
<li><code>serverCredentialsId : String</code>
<div><div>
 The available credentials to use for logging onto CES (used only when using the Total Test repository server). Alternatively, click <b>Add</b> to add credentials using the Credentials Plugin. Refer to the Jenkins documentation for the Credentials Plugin.
</div></div>

</li>
<li><code>connectionId : String</code>
<div><div>
 This field specifies the host connection to use to execute on.
 <p></p> Host connections can be configured in the Jenkins system configuration (Manage Jenkins -&gt; Configure System).
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 The available credentials to use for logging onto the host. Alternatively, click <b>Add</b> to add credentials using the Credentials Plugin. Refer to the Jenkins documentation for the Credentials Plugin.
</div></div>

</li>
<li><code>sonarVersion : String</code> (optional)
<div><div>
 SonarQube version 5 or 6
</div></div>

</li>
<li><code>logLevel : String</code> (optional)
<div><div>
 Set the logging level to be used when executing the test.
</div></div>

</li>
<li><code>accountInfo : String</code> (optional)
<div><div>
 Optional job account information.
 <p>Use the accounting information field to enter an account number and any other accounting information that your installation requires.<br>
   The accounting information must be entered, just as it would be on the job card. Currently only 52 characters are allowed for the accounting information.</p>
</div></div>

</li>
<li><code>ccThreshold : int</code> (optional)
</li>
<li><code>clearCodeCoverage : boolean</code> (optional)
</li>
<li><code>collectCCRepository : String</code> (optional)
</li>
<li><code>collectCCSystem : String</code> (optional)
</li>
<li><code>collectCCTestID : String</code> (optional)
</li>
<li><code>collectCodeCoverage : boolean</code> (optional)
<div><div>
 Select this option to collect Code Coverage information during test execution.
</div></div>

</li>
<li><code>compareJUnits : boolean</code> (optional)
</li>
<li><code>contextVariables : String</code> (optional)
<div><div>
 Execution context variable in the format "field1=value1,field2=value2".
</div></div>

</li>
<li><code>createJUnitReport : boolean</code> (optional)
</li>
<li><code>createReport : boolean</code> (optional)
</li>
<li><code>createResult : boolean</code> (optional)
</li>
<li><code>createSonarReport : boolean</code> (optional)
</li>
<li><code>customerId : String</code> (optional)
<div><div>
 BMC customer id for use on the BMC cloud license server.
 <p></p> This is required for obtaining a license from the BMC license server.
</div></div>

</li>
<li><code>enterpriseDataHostPort : String</code> (optional)
<div><div>
 This field allows you to specify the host and port of the Enterprise Data Communication Manager to connect to. The host and port must be separated by a ':' character.
</div></div>

</li>
<li><code>enterpriseDataWorkspace : String</code> (optional)
<div><div>
 The BMC AMI DevX Data Studio Communication Manager's workspace.
</div></div>

</li>
<li><code>haltAtFailure : boolean</code> (optional)
</li>
<li><code>haltPipelineOnFailure : boolean</code> (optional)
</li>
<li><code>jclPath : String</code> (optional)
<div><div>
 The path to the JCL file to use when executing '.testscenario' files.
</div></div>

</li>
<li><code>jsonFile : String</code> (optional)
<div><div>
 Optional JSON file containing tests to execute.
 <p>Use the JSON file field to enter a JSON file containing the tests to execute.<br><b>Note: This field is only used for Total Test CLI version 20.04.01 and later</b></p>
</div></div>

</li>
<li><code>localConfig : boolean</code> (optional)
<div><div>
 When selected use the defined local TotalTestConfiguration directory. Otherwise use the Total Test repository server running on the CES server.
</div></div>

</li>
<li><code>localConfigLocation : String</code> (optional)
<div><div>
 Optional location of TotalTestConfiguration directory.
 <p></p>
</div></div>

</li>
<li><code>programList : String</code> (optional)
<div><div>
 Optional comma separated list of tests tests to execute.
 <p>Use the Test list field to enter a comma separated list of program names to be tested. Will only include test scenarios that have component under test defined as one of these<br><b>Note: This field is only used for Total Test CLI version 20.04.01 and later</b></p>
</div></div>

</li>
<li><code>recursive : boolean</code> (optional)
<div><div>
 Should test scenarios be found recursively in the folder
</div></div>

</li>
<li><code>reportFolder : String</code> (optional)
<div><div>
 The folder path containing produced test results vary depending on the Total Test CLI version. 
 <ul>
  <li>Total Test CLI version 20.03.01 and later</li>
  <ul>
   <li>The Report Folder field will be ignored.</li>
   <li>The produced test result will be contained in the Output directory relative to the Test folder path.</li>
   <li>Junit and Sonar report files are copied to TTTUnit and TTTSonar folders in the Jenkins workspace.</li>
  </ul>
  <li>Total Test CLI version prior to 20.03.01</li>
  <ul>
   <li>The produced test results will be contained in this folder path.</li>
   <li>Default folder path is TTTReport.</li>
   <li>Relative folder paths are relative to the Jenkins workspace.</li>
   <li>An absolute path can also be used to specify Report folder.</li>
  </ul>
 </ul><b>Note: This field is only used for Total Test CLI version prior to 20.03.01</b>
</div></div>

</li>
<li><code>selectEnvironmentRadio : String</code> (optional)
</li>
<li><code>selectProgramsOption : boolean</code> (optional)
</li>
<li><code>selectProgramsRadio : String</code> (optional)
</li>
<li><code>siteId : String</code> (optional)
<div><div>
 BMC customer's site id for use on the BMC cloud license server.
 <p></p> This is required for obtaining a license from the BMC license server.
</div></div>

</li>
<li><code>sourceFolder : String</code> (optional)
<div><div>
 Optional file path to a folder that contains source code of tested programs.
 <br>
  Default is COBOL. 
 <br>
  It is only used to set the source path.
</div></div>

</li>
<li><code>stopIfTestFailsOrThresholdReached : boolean</code> (optional)
<div><div>
 Stop if test fails or threshold is reached (default is true)
</div></div>

</li>
<li><code>uploadToServer : boolean</code> (optional)
</li>
<li><code>useEnterpriseData : boolean</code> (optional)
</li>
<li><code>useScenarios : boolean</code> (optional)
<div><div>
 Should .scenarios files be used instead of .context files
</div></div>

</li>
</ul>


++++
