= BMC AMI DevX Data Studio
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/compuware-topaz-for-enterprise-data">Visit the Jenkins Plugins site</a>
++++


=== `ted`: BMC AMI DevX Data Studio - Execute Specifications.
++++
<ul><li><code>credentialsID : String</code>
</li>
<li><code>repositoryName : String</code> (optional)
<div><div>
 The name of the File-AID EX repository, which houses the required EX specifications that are to be executed. 
 <p></p>Optional? No 
 <p></p>Can be defined in execution Context? No
</div></div>

</li>
<li><code>resultsRepositoryName : String</code> (optional)
<div><div>
 The repository where Compare Pro execution results will be stored. Only applicable to comparePro specifications. 
 <p></p>Optional? Yes, defaults to the specification repository if not specified. 
 <p></p>Can be defined in execution Context? No
</div></div>

</li>
<li><code>selectExecutionTypeRadio : String</code> (optional)
</li>
<li><code>specificationName : String</code> (optional)
<div><div>
 The name of the specification that is to be executed. Required if single specification execution is selected. 
 <p></p>Optional? No, mandatory if single specification execution is selected. 
 <p></p>Can be defined in execution Context? No
</div></div>

</li>
<li><code>specificationType : String</code> (optional)
<div><div>
 The type of the specification that is to be executed. 
 <p></p>Optional? No, mandatory if single specification execution is selected. 
 <p></p>Can be defined in execution Context? No
</div></div>

</li>
<li><code>specificationList : String</code> (optional)
<div><div>
 If multiple specifications are to be executed within the same pipeline, with the same configuration. Provide a list of Specification Name and Types each separated by space. For example: SPECA extract SPECB convert SPECC compare 
 <p></p>Optional? No, mandatory if multi-specification execution is selected. 
 <p></p>Can be defined in execution Context? No
</div></div>

</li>
<li><code>exitOnFailure : boolean</code> (optional)
<div><div>
 Flag to denote if it is preferred to stop the continued execution of specifications after a execution failure, in case of multi-specification execution. 
 <p></p>Optional? Yes, defaulted to true if not defined. 
 <p></p>Can be defined in execution Context? No
</div></div>

</li>
<li><code>executionContext : String</code> (optional)
<div><div>
 TThe name of the execution context file. If the file is present at /WorkbenchCLI/EnterpriseData, the name of the file would suffice, if at a different location on the machine supply the full path with the file name. If a value for a certain argument is defined in the context file and is also passed as an argument, the value passed with the command will take precedence. To know which all parameters can be specified via the context file, view the template provided at /WorkbenchCLI/EnterpriseData named executioncontext_template.properties. Multiple execution contexts can be created as required by copying the template. 
 <p></p>Optional? Yes, if this is not provided all other mandatory parameters have to be defined on the pipeline definition.
</div></div>

</li>
<li><code>executionTimeout : String</code> (optional)
<div><div>
 The execution timeout in seconds. The default if not defined is 20 seconds. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>defineCES : boolean</code> (optional)
</li>
<li><code>cesURL : String</code> (optional)
<div><div>
 The URL for the CES to be used for license validation. It can either be the URL for the cloud CES or a locally installed CES. 
 <p></p>Optional? No 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>useCloudCES : boolean</code> (optional)
<div><div>
 Flag to denote if cloud CES should be used. 
 <p></p>Optional? No 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>cloudCustomerNo : String</code> (optional)
<div><div>
 The customer number, in case the cloud CES is chosen to be used. Please contact BMC customer support if you need help with this information. 
 <p></p>Optional? Required for cloud CES. 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>cloudSiteID : String</code> (optional)
<div><div>
 The Site ID, in case the cloud CES is chosen to be used. Please contact BMC customer support if you need help with this information. 
 <p></p>Optional? Required for cloud CES. 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>defineManager : boolean</code> (optional)
</li>
<li><code>communicationManager : String</code> (optional)
<div><div>
 The host name or ip of the machine where the communication manager is running. The File-AID Ex repository containing the specifications that needs to be executed should be configured on this communication manager. 
 <p></p>Optional? No 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>communicationManagerPort : String</code> (optional)
<div><div>
 The port on which the communication manager is running. on the specified host. 
 <p></p>Optional? No 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>defineServer : boolean</code> (optional)
</li>
<li><code>executionServer : String</code> (optional)
<div><div>
 The host name or ip of the machine which the execution server where the EX specifications should be executed, is installed. 
 <p></p>Optional? Required for executing EX specifications. 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>executionServerPort : String</code> (optional)
<div><div>
 The port on which the execution server is running, on the specified host. 
 <p></p>Optional? Required for executing EX specifications. 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>defineHost : boolean</code> (optional)
</li>
<li><code>connectionId : String</code> (optional)
<div><div>
 The execution host and port where RDX specifications should be executed. 
 <p></p>Optional? Required for executing RDX specifications. 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>includeCred : boolean</code> (optional)
</li>
<li><code>defineJobcard : boolean</code> (optional)
</li>
<li><code>jclJobcardLine1 : String</code> (optional)
<div><div>
 The JCL Jobcard's line 1, applicable only to RDX execution. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>jclJobcardLine2 : String</code> (optional)
<div><div>
 The JCL Jobcard's line 2, applicable only to RDX execution. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>jclJobcardLine3 : String</code> (optional)
<div><div>
 The JCL Jobcard's line 3, applicable only to RDX execution. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>jclJobcardLine4 : String</code> (optional)
<div><div>
 The JCL Jobcard's line 4, applicable only to RDX execution. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>jclJobcardLine5 : String</code> (optional)
<div><div>
 The JCL Jobcard's line 5, applicable only to RDX execution. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>defineQualifiers : boolean</code> (optional)
</li>
<li><code>datasetHighLevelQualifier : String</code> (optional)
<div><div>
 The dataset high level qualifier to be used. Applicable only for RDX execution. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>temporaryDatasetPrefix : String</code> (optional)
<div><div>
 The prefix to be used for temporary datasets. Applicable only for RDX execution. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>temporaryDatasetSuffix : String</code> (optional)
<div><div>
 The suffix to be used for temporary datasets. Applicable only for RDX execution. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>defineDataprivacyOverride : boolean</code> (optional)
</li>
<li><code>dpOverrideFADEBUG : String</code> (optional)
<div><div>
 The data privacy override FADEBUG, that defines the logging information for the File-AID Rules Engine. Only applicable for RDX Extract executions. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>dpOverrideFAEXPATH : String</code> (optional)
<div><div>
 The data privacy override FAEXPATH, that defines the path for File-AID Rules Engine location. Only applicable for RDX Extract executions. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>dpOverrideFAIPADDR : String</code> (optional)
<div><div>
 The data privacy override FAIPADDR, that provides the File-AID Services IP address and execution port. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>dpOverrideFAJOPTS : String</code> (optional)
<div><div>
 The data privacy override FAJOPTS, that defines the Java options for the File-AID Rules Engine. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>dpOverrideFAJPATH : String</code> (optional)
<div><div>
 The data privacy override FAJAPTH, that defines the z/OS UNIX path for the Java Virtual Machine. 
 <p></p>Optional? Yes 
 <p></p>Can be defined in execution Context? Yes
</div></div>

</li>
<li><code>haltPipelineOnFailure : boolean</code> (optional)
</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 The credentials for the selected execution host. 
 <p></p>Optional? Required for executing RDX specifications. 
 <p></p>Can be defined in execution Context? No 
 <p></p>Note: If keystore or certificate needs to be used, leave this field empty and define the parameters in the execution context. The support for keystore and certificate based authentication via this jenkins plugin will be added in a future version.
</div></div>

</li>
</ul>


++++
