= Concurrent Step
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/concurrent-step">Visit the Jenkins Plugins site</a>
++++


=== `acquireSemaphore`: Wait until the latch has counted down to zero.
++++
<ul><li><code>semaphore</code>
<ul><li><b>Type:</b> <code>class com.github.topikachu.jenkins.concurrent.semaphore.SemaphoreRef</code></li>
</ul></li>
<li><code>permit : int</code> (optional)
</li>
<li><code>timeout : long</code> (optional)
</li>
<li><code>unit</code> (optional)
<ul><li><b>Values:</b> <code>NANOSECONDS</code>, <code>MICROSECONDS</code>, <code>MILLISECONDS</code>, <code>SECONDS</code>, <code>MINUTES</code>, <code>HOURS</code>, <code>DAYS</code></li></ul></li>
</ul>


++++
=== `awaitBarrier`: Waits until all parties have invoked await on this barrier.
++++
<ul><li><code>barrier</code>
<ul><li><b>Type:</b> <code>class com.github.topikachu.jenkins.concurrent.barrier.BarrierRef</code></li>
</ul></li>
<li><code>timeout : long</code> (optional)
</li>
<li><code>unit</code> (optional)
<ul><li><b>Values:</b> <code>NANOSECONDS</code>, <code>MICROSECONDS</code>, <code>MILLISECONDS</code>, <code>SECONDS</code>, <code>MINUTES</code>, <code>HOURS</code>, <code>DAYS</code></li></ul></li>
</ul>


++++
=== `awaitCondition`: Causes the current thread to wait until it is signalled or interrupted.
++++
<ul><li><code>condition</code>
<ul><li><b>Type:</b> <code>class com.github.topikachu.jenkins.concurrent.condition.LockAndCondition</code></li>
</ul></li>
<li><code>timeout : long</code> (optional)
</li>
<li><code>unit</code> (optional)
<ul><li><b>Values:</b> <code>NANOSECONDS</code>, <code>MICROSECONDS</code>, <code>MILLISECONDS</code>, <code>SECONDS</code>, <code>MINUTES</code>, <code>HOURS</code>, <code>DAYS</code></li></ul></li>
</ul>


++++
=== `awaitLatch`: Wait until the latch has counted down to zero.
++++
<ul><li><code>latch</code>
<ul><li><b>Type:</b> <code>class com.github.topikachu.jenkins.concurrent.latch.LatchRef</code></li>
</ul></li>
<li><code>timeout : long</code> (optional)
</li>
<li><code>unit</code> (optional)
<ul><li><b>Values:</b> <code>NANOSECONDS</code>, <code>MICROSECONDS</code>, <code>MILLISECONDS</code>, <code>SECONDS</code>, <code>MINUTES</code>, <code>HOURS</code>, <code>DAYS</code></li></ul></li>
</ul>


++++
=== `countDownLatch`: Decrements the count of the latch.
++++
<ul><li><code>latch</code>
<ul><li><b>Type:</b> <code>class com.github.topikachu.jenkins.concurrent.latch.LatchRef</code></li>
</ul></li>
</ul>


++++
=== `createBarrier`: Create a Cyclic Barrier.
++++
<ul><li><code>count : int</code> (optional)
</li>
</ul>


++++
=== `createCondition`: Create a lock.
++++
<ul></ul>


++++
=== `createLatch`: Create a count down latch.
++++
<ul><li><code>count : int</code> (optional)
</li>
</ul>


++++
=== `createSemaphore`: Create a semaphore.
++++
<ul><li><code>permit : int</code> (optional)
</li>
</ul>


++++
=== `releaseSemaphore`: Release the semaphore.
++++
<ul><li><code>semaphore</code>
<ul><li><b>Type:</b> <code>class com.github.topikachu.jenkins.concurrent.semaphore.SemaphoreRef</code></li>
</ul></li>
</ul>


++++
=== `signalAll`: Notify all wa.
++++
<ul><li><code>condition</code>
<ul><li><b>Type:</b> <code>class com.github.topikachu.jenkins.concurrent.condition.LockAndCondition</code></li>
</ul></li>
</ul>


++++
