= Consul Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/consul">Visit the Jenkins Plugins site</a>
++++


=== `Consul`: ConsulStep
++++
<ul><li><code>installationName : String</code>
</li>
<li><code>consulSettingsProfileName : String</code>
</li>
<li><code>operationList</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'ConsulGetKV'</code><div>
<ul><li><code>valuePath : String</code>
<div><div>
 Consul path for the required value.
 <br>
  e.g. mysql/config/users/admin
</div></div>

</li>
<li><code>environmentVariableName : String</code>
<div><div>
 Environment variable name for the value.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ConsulServiceDiscoveryOperation'</code><div>
<ul><li><code>serviceName : String</code>
<div><div>
 Service name to look in consul
</div></div>

</li>
<li><code>serviceTag : String</code>
<div><div>
 Service tag - leave empty for no tag filtering.
</div></div>

</li>
<li><code>environmentVariableName : String</code>
<div><div>
 Environment variable name for the response.
 <br>
  Leave empty to use the same name of the service.
</div></div>

</li>
<li><code>healthStatus : String</code>
<div><div>
 Service health status.
</div></div>

</li>
<li><code>addPort : boolean</code>
<div><div>
 Add port number to response?
 <br>
  The port will be added for every ip address - {ip}:{port}
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ConsulSetKV'</code><div>
<ul><li><code>valuePath : String</code>
<div><div>
 Consul path to set with your value.
 <br>
  e.g. mysql/config/users/admin
</div></div>

</li>
<li><code>value : String</code>
<div><div>
 Value or ENV var name to use.
</div></div>

</li>
</ul></div></li>
</ul></li>
</ul>


++++
