= Conventional Commits Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/conventional-commits">Visit the Jenkins Plugins site</a>
++++


=== `currentVersion`: determine the current version from the conventional commit history
++++
<div><p>This step can be used to determine the current version of supported projects types. The supported configuration files :</p>
<ul>
 <li>Maven,</li>
 <li>Gradle,</li>
 <li>Helm,</li>
 <li>Make,</li>
 <li>Python,</li>
 <li>Npm.</li>
</ul></div>
<ul></ul>


++++
=== `nextVersion`: Next Version: determine the next version from the conventional commit history
++++
<div><p>Determine the next release version based on previous tags and the commit messages used. It calculates the version number based on the format of the commit message. The commit message format used is <a href="https://www.conventionalcommits.org/en/v1.0.0/" rel="nofollow">conventional commits.</a></p>
<p>This plugin can be used in a pipeline in a stage or the environment block. Some examples of this in use are:<br><strong>In the environment block:</strong><br><code> </code></p>
<pre><code>pipeline {
    agent any

    environment {
        NEXT_VERSION = nextVersion()
    }

    stages {
        stage('Hello') {
            steps {
                echo "next version = ${NEXT_VERSION}"
            }
        }
    }
}
	    </code></pre><code> </code> <strong>In a scripted Pipeline:</strong>
<br><code>
 <pre>def NEXT_VERSION
node {
    stage('Get next version ...') {
      NEXT_VERSION=nextVersion()
      echo "Next version : $NEXT_VERSION"
    }
    stage ('Release') {
        sh "mvn release:prepare -DreleaseVersion=$NEXT_VERSION"
        sh 'mvn release:perform'
    }
}
	    </pre></code>
<p></p></div>
<ul><li><code>buildMetadata : String</code> (optional)
<div><p>An optional parameter can be added as follows: <code> </code></p>
<pre><code>pipeline {
    agent any
    environment {
        NEXT_VERSION = nextVersion(buildMetadata: "$env.BUILD_NUMBER")
    }
    stages {
        stage('Hello') {
            steps {
                echo "next version = ${NEXT_VERSION}"
            }
        }
    }
}
        </code></pre><code> </code> Assuming next version is 1.1.0. The pipeline will output: next version = 1.1.0+001 
<p></p></div>

</li>
<li><code>incrementPreRelease : boolean</code> (optional)
<div><p>There are three options to manipulate the prerelease option:</p>
<ul>
 <li>the name of the prerelease ➡️ <code>preRelease</code></li>
 <li>keep the existing prerelease (default false) ➡️ <code>preservePrelease</code></li>
 <li>increment the existing prerelease (default false) ➡️ <code>incrementPreRelease</code></li>
</ul> The table described in <a href="https://github.com/jenkinsci/conventional-commits-plugin#prerelease-possible-combinations" rel="nofollow">here</a> are the combined use of these options and the result. 
<p></p></div>

</li>
<li><code>nonAnnotatedTag : boolean</code> (optional)
<div><p>If false use only annotated tags, if true use all tags to determine next version</p></div>

</li>
<li><code>outputFormat : String</code> (optional)
<div><p></p></div>

</li>
<li><code>preRelease : String</code> (optional)
<div><p>For a <code>1.0.0</code> existing version the following code: <code> </code></p>
<pre><code>pipeline {
    agent any

    environment {
        NEXT_VERSION = nextVersion(preRelease: 'alpha')
    }

    stages {
        stage('Hello') {
            steps {
                echo "next version = ${NEXT_VERSION}"
            }
        }
    }
}
        </code></pre><code> </code> Will display: next version = 1.1.0-alpha 
<p></p></div>

</li>
<li><code>preservePreRelease : boolean</code> (optional)
<div><p>There are three options to manipulate the prerelease option:</p>
<ul>
 <li>the name of the prerelease ➡️ <code>preRelease</code></li>
 <li>keep the existing prerelease (default false) ➡️ <code>preservePrelease</code></li>
 <li>increment the existing prerelease (default false) ➡️ <code>incrementPreRelease</code></li>
</ul> The table described in <a href="https://github.com/jenkinsci/conventional-commits-plugin#prerelease-possible-combinations" rel="nofollow">here</a> are the combined use of these options and the result. 
<p></p></div>

</li>
<li><code>startTag : String</code> (optional)
<div><p></p></div>

</li>
<li><code>writeVersion : boolean</code> (optional)
<div><p>Allow writing back to the file the next calculated version.</p></div>

</li>
</ul>


++++
