= Copy Artifact Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/copyartifact">Visit the Jenkins Plugins site</a>
++++


=== `copyArtifacts`: Copy artifacts from another project
++++
<ul><li><code>projectName : String</code>
<div><p>The name of the project to copy artifacts from.</p>
<dl>
 <dt>
  <strong>Maven projects:</strong>
 </dt>
 <dd>
  <p>Artifacts from all modules will be copied. Enter JOBNAME/MODULENAME here to copy from a particular module; you may copy/paste this from the URL for that module when browsing Jenkins.<br><strong>Example:</strong> MyMavenJob/my.group$MyModule</p>
 </dd>
 <dt>
  <strong>Matrix projects:</strong>
 </dt>
 <dd>
  <p>Artifacts from all configurations will be copied, each into a subdirectory with the name of the configuration as seen in its URL when browsing Jenkins.<br><strong>Example:</strong> If the target directory is given as fromMatrix then the copy could create $WORKSPACE/fromMatrix/label=agentA/dist/mybuild.jar and $WORKSPACE/fromMatrix/label=agentB/dist/mybuild.jar.</p>
  <p>To copy from a particular configuration, enter JOBNAME/AXIS=VALUE,.. as seen in the URL for that configuration.<br><strong>Example:</strong> MyMatrixJob/jdk=Java6u17</p>
  <p>To copy artifacts from one matrix project to another, use a parameter to select the matching configuration in the source project.<br><strong>Example:</strong> OtherMatrixJob/jdk=$jdk</p>
 </dd>
 <dt>
  <strong>Multibranch Pipeline projects:</strong>
 </dt>
 <dd>
  <p>Use a path consisting of the project name followed by the branch name.<br><strong>Example:</strong> /MyMultibranchProject/MyBranch</p>
  <p>Special letters like '/' in branch names should be escaped. You can see the exact name in "Full project name" in job pages of each branch.<br><strong>Example:</strong> ../MyMultibranchProject/feature%2Fnavigation</p>
 </dd>
</dl>
<p>See <a href="https://www.jenkins.io/doc/book/using/referencing-another-project-by-name/" rel="nofollow">"How to reference another project by name"</a> for more information.</p></div>

</li>
<li><code>excludes : String</code> (optional)
<div><div>
 Specify paths or patterns of artifacts to exclude, even if specified in "Artifacts to copy". Can be blank.
</div></div>

</li>
<li><code>filter : String</code> (optional)
<div><div>
 Relative paths to artifact(s) to copy or leave blank to copy all artifacts. This works just as a filter, and doesn't care whether all specified artifacts really exists. Check the /artifact/ browser of a build to see the relative paths to use here, as the build page typically hides intermediate directories. Can use wildcards like module/dist/**/*.zip, and use comma (followed by optional whitespace) to separate multiple entries. See the @includes of <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">Ant fileset</a> for the exact format. May also contain references to build parameters like $PARAM.
</div></div>

</li>
<li><code>fingerprintArtifacts : boolean</code> (optional)
<div><div>
 Automatically fingerprint all artifacts that are copied as part of this build step.
</div></div>

</li>
<li><code>flatten : boolean</code> (optional)
<div><div>
 Ignore the directory structure of the artifacts in the source project and copy all matching artifacts directly into the specified target directory. By default the artifacts are copied in the same directory structure as the source project.
</div></div>

</li>
<li><code>includeBuildNumberInTargetPath : boolean</code> (optional)
<div><div>
 Include build number in target path. Default is false. 
 <p>When true, the build number of the source project will be included in the target path. This is particularly useful when the selector is specific and the value is a permalink, e.g. lastSuccessfulBuild.</p>
</div></div>

</li>
<li><code>optional : boolean</code> (optional)
<div><div>
 Allow this build to continue even if no build is found that matches the "Which build" condition. By default this build step fails the build if no artifacts are copied.
</div></div>

</li>
<li><code>parameters : String</code> (optional)
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
 <p>You shouldn't use "Build selector for Copy Artifact" parameters here, as it doesn't preserve compatibility when you upgrade plugins, and doesn't work for builds built before upgrading.</p>
</div></div>

</li>
<li><code>resultVariableSuffix : String</code> (optional)
<div><div>
 The build number of the selected build will be recorded into the variable named COPYARTIFACT_BUILD_NUMBER_(SUFFIX) for later build steps to reference. You can specify that suffix part for that variable here. 
 <p>If not specified, the source project name will be used instead (in all uppercase, and sequences of characters other than A-Z replaced by a single underscore).</p>
 <p><strong>Example</strong>:</p>
 <table>
  <tbody>
   <tr>
    <th>Source project name</th>
    <th>Suffix to be used</th>
   </tr>
   <tr>
    <td>Project-ABC</td>
    <td>PROJECT_ABC</td>
   </tr>
   <tr>
    <td>tool1-release1.2</td>
    <td>TOOL_RELEASE_</td>
   </tr>
  </tbody>
 </table>
</div></div>

</li>
<li><code>selector</code> (optional)
<div><div>
 How to select the build to copy artifacts from, such as latest successful or stable build, or latest "keep forever" build. Other plugins may provide additional selections. 
 <br>
  The build number of the selected build will be recorded in the environment for later build steps to reference. For details, see the help of "Result variable suffix" in "Advanced" section.
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>downstream</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggered from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downstream build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>lastWithArtifacts</code><div>
<ul></ul></div></li>
<li><code>lastCompleted</code><div>
<ul></ul></div></li>
<li><code>$class: 'MultiJobBuildSelector'</code><div>
<ul></ul></div></li>
<li><code>buildParameter</code><div>
<ul><li><code>parameterName : String</code>
<div><div>
 Name of the "build selector" parameter. A parameter with this name should be added in the build parameters section above. There is a special parameter type for choosing the build selector. 
 <p>You can pass not only the parameter name, but also the parameter value itself. This is useful especially used with workflow-plugin.</p>
</div></div>

</li>
</ul></div></li>
<li><code>permalink</code><div>
<ul><li><code>id : String</code>
</li>
</ul></div></li>
<li><code>$class: 'PromotedBuildSelector'</code><div>
<ul><li><code>level : int</code>
</li>
</ul></div></li>
<li><code>latestSavedBuild</code><div>
<ul></ul></div></li>
<li><code>specific</code><div>
<ul><li><code>buildNumber : String</code>
<div><div>
 While this selector is for build numbers (e.g. "22" for build #22), you can also resolve build parameters or environment variables (e.g. "${PARAM}"). The display name of a build and permalinks (e.g. "lastSuccessfulBuild", "lastBuild"...) can be used as well.
</div></div>

</li>
</ul></div></li>
<li><code>lastSuccessful</code><div>
<ul><li><code>stable : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>upstream</code><div>
<ul><li><code>allowUpstreamDependencies : boolean</code> (optional)
</li>
<li><code>fallbackToLastSuccessful : boolean</code> (optional)
</li>
<li><code>upstreamFilterStrategy</code> (optional)
<div><div>
 Jenkins launches only one build when multiple upstreams triggered the same project at the same time. This field specifies from which upstream build to copy artifacts in those cases. "Use the oldest" copies artifacts from the upstream build with the smallest build number (that is, oldest). "Use the newest" copies artifacts from the upstream build with the largest build number (that is, newest). The default value is "Use global setting", which behaves as configured in "Manage Jenkins" &gt; "Configure System".
</div></div>

<ul><li><b>Values:</b> <code>UseGlobalSetting</code>, <code>UseOldest</code>, <code>UseNewest</code></li></ul></li>
</ul></div></li>
<li><code>workspace</code><div>
<ul></ul></div></li>
</ul></li>
<li><code>target : String</code> (optional)
<div><div>
 Target base directory for copy, or leave blank to use the <a rel="nofollow">workspace</a>. Directory (and parent directories, if any) will be created if needed. May contain references to build parameters like $PARAM.
</div></div>

</li>
</ul>


++++
