= Cortex Metrics Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/cortex-metrics">Visit the Jenkins Plugins site</a>
++++


=== `publishCortexMetrics`: Publish metrics to Cortex
++++
<div><div>
 <p>Publishes current job metrics to Cortex.</p>
</div></div>
<ul><li><code>bearerToken : String</code> (optional)
<div><div>
 Overrides the value set on the folder or global configuration. The Cortex API bearer token, in the form "123:abcd0123...".
</div></div>

</li>
<li><code>labels</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>namespace : String</code> (optional)
<div><div>
 Overrides the value set on the folder or global configuration. The namespace to use for the Cortex metrics, defaults to "default". This will be the first element in all metrics, such as "default_jenkins_job_...".
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 Overrides the value set on the folder or global configuration. The Cortex write URL for Prometheus pushes. This is used to send metrics directly to Cortex as if it were Prometheus. Example: https://mycortex.com/api/prom/push
</div></div>

</li>
</ul>


++++
