= Credentials Binding Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/credentials-binding">Visit the Jenkins Plugins site</a>
++++


=== `withCredentials`: Bind credentials to variables
++++
<div><p>Allows various kinds of credentials (secrets) to be used in idiosyncratic ways. (Some steps explicitly ask for credentials of a particular kind, usually as a <code>credentialsId</code> parameter, in which case this step is unnecessary.) Each binding will define an environment variable active within the scope of the step. You can then use them directly from any other steps that expect environment variables to be set:</p>
<pre><code>node {
  withCredentials([usernameColonPassword(credentialsId: 'mylogin', variable: 'USERPASS')]) {
    sh '''
      set +x
      curl -u "$USERPASS" https://private.server/ &gt; output
    '''
  }
}</code></pre>
<p>As another example (use <i>Snippet Generator</i> to see all options):</p>
<pre><code>node {
  withCredentials([string(credentialsId: 'mytoken', variable: 'TOKEN')]) {
    sh '''
      set +x
      curl -H "Token: $TOKEN" https://some.api/
    '''
  }
}</code></pre>
<p>Note the use of <em>single</em> quotes to define the <code>script</code> (implicit parameter to <code>sh</code>) in Groovy above. You want the secret to be expanded by the shell as an environment variable. The following idiom is potentially less secure, as the secret is interpolated by Groovy and so (for example) typical operating system process listings will accidentally disclose it:</p>
<pre><code>node {
  withCredentials([string(credentialsId: 'mytoken', variable: 'TOKEN')]) {
    sh /* WRONG! */ """
      set +x
      curl -H 'Token: $TOKEN' https://some.api/
    """
  }
}</code></pre>
<p>At least on Linux, environment variables can be obtained by other processes running in the same account, so you should not run a job which uses secrets on the same node as a job controlled by untrusted parties. In any event, you should always prefer expansion as environment variables to inclusion in the command, since Jenkins visualizations such as Blue Ocean will <em>attempt</em> to detect step parameters containing secrets and refuse to display them.</p>
<p>The secret(s) will be masked (<code>****</code>) in case they are printed to the build log. This prevents you from <em>accidentally</em> disclosing passwords and the like via the log. (Bourne shell <code>set +x</code>, or Windows batch <code>@echo off</code>, blocks secrets from being displayed in echoed commands; but build tools in debug mode might dump all environment variables to standard output/error, or poorly designed network clients might display authentication, etc.) The masking could of course be trivially circumvented; anyone permitted to configure a job or define Pipeline steps is assumed to be trusted to use any credentials in scope however they like.</p>
<p>Beware that certain tools mangle secrets when displaying them. As one example, Bash (as opposed to Ubuntu’s plainer Dash) does so with text containing <code>'</code> in echo mode:</p>
<pre><code>$ export PASS=foo"'"bar
$ env|fgrep PASS
PASS=foo'bar
$ sh -xc 'echo $PASS'
+ echo foo'bar
foo'bar
$ bash -xc 'echo $PASS'
+ echo 'foo'\''bar'
foo'bar
</code></pre>
<p>Mangled secrets can only be detected on a best-effort basis. By default, Jenkins will attempt to mask mangled secrets as they would appear in output of Bourne shell, Bash, Almquist shell and Windows batch. Without these strategies in place, mangled secrets would appear in plain text in log files. In the example above, this would result in:</p>
<pre><code>+ echo 'foo'\''bar'
****</code></pre>
<p>This particular issue can be more safely prevented by turning off echo with <code>set +x</code> or avoiding the use of shell metacharacters in secrets.</p>
<p>For bindings which store a secret file, beware that</p>
<pre><code>node {
  dir('subdir') {
    withCredentials([file(credentialsId: 'secret', variable: 'FILE')]) {
      sh 'use $FILE'
    }
  }
}</code></pre>
<p>is not safe, as <code>$FILE</code> might be inside the workspace (in <code>subdir@tmp/secretFiles/</code>), and thus visible to anyone able to browse the job’s workspace. If you need to run steps in a different directory than the usual workspace, you should instead use</p>
<pre><code>node {
  withCredentials([file(credentialsId: 'secret', variable: 'FILE')]) {
    dir('subdir') {
      sh 'use $FILE'
    }
  }
}</code></pre>
<p>to ensure that the secrets are outside the workspace; or choose a different workspace entirely:</p>
<pre><code>node {
  ws {
    withCredentials([file(credentialsId: 'secret', variable: 'FILE')]) {
      sh 'use $FILE'
    }
  }
}</code></pre>
<p>Also see the <a href="https://jenkins.io/blog/2019/02/21/credentials-masking/" rel="nofollow">Limitations of Credentials Masking</a> blog post for more background.</p></div>
<ul><li><code>bindings</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>aws</code><div>
<div><div>
 Sets one variable to the AWS access key and another one to the secret key given in the credentials.
</div></div>
<ul><li><code>accessKeyVariable : String</code>
<div><div>
 Environment variable name for the AWS Access Key Id. If empty, <code>AWS_ACCESS_KEY_ID</code> will be used.
</div></div>

</li>
<li><code>secretKeyVariable : String</code>
<div><div>
 Environment variable name for the AWS Secret Access Key. If empty, <code>AWS_SECRET_ACCESS_KEY</code> will be used.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
<li><code>roleArn : String</code> (optional)
</li>
<li><code>roleSessionDurationSeconds : int</code> (optional)
</li>
<li><code>roleSessionName : String</code> (optional)
</li>
</ul></div></li>
<li><code>token</code><div>
<ul><li><code>variable : String</code>
<div><div>
 Name of an environment variable to be set during the build. The contents of this location are not masked.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'AwsBucketCredentialsBinding'</code><div>
<div><div>
 Does something.
</div></div>
<ul><li><code>usernameVariable : String</code>
</li>
<li><code>passwordVariable : String</code>
</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>certificate</code><div>
<div><div>
 Sets one variable to the username and one variable to the password given in the credentials.
</div>
<div>
 <strong>Warning</strong>: if the Jenkins controller or agent node has multiple executors, any other build running concurrently on the same node will be able to read the text of the secret, for example on Linux using <code>ps e</code>.
</div></div>
<ul><li><code>keystoreVariable : String</code>
<div><div>
 Name of an environment variable to be set to the temporary keystore location during the build. The contents of this file are not masked.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
<li><code>aliasVariable : String</code> (optional)
<div><div>
 Name of an environment variable to be set to the keystore alias name of the certificate during the build.
</div></div>

</li>
<li><code>passwordVariable : String</code> (optional)
<div><div>
 Name of an environment variable to be set to the password during the build.
</div></div>

</li>
</ul></div></li>
<li><code>ConjurSecretApplianceCredentials</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
<li><code>sPath : String</code> (optional)
</li>
<li><code>variable : String</code> (optional)
</li>
</ul></div></li>
<li><code>conjurSecretCredential</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
<li><code>variable : String</code> (optional)
</li>
</ul></div></li>
<li><code>conjurSecretUsername</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
<li><code>passwordVariable : String</code> (optional)
</li>
<li><code>usernameVariable : String</code> (optional)
</li>
</ul></div></li>
<li><code>conjurSecretUsernameSSHKey</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
<li><code>secretVariable : String</code> (optional)
</li>
<li><code>usernameVariable : String</code> (optional)
</li>
</ul></div></li>
<li><code>dockerCert</code><div>
<ul><li><code>variable : String</code>
<div><div>
 Name of an environment variable to be set during the build.
 <br>
  Its value will be the absolute path of the directory where the <code>{ca,cert,key}.pem</code> files will be created.
 <br>
  You probably want to call this variable <code>DOCKER_CERT_PATH</code>, which will be understood by the docker client binary.
 <br>
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>file</code><div>
<div><div>
 Copies the file given in the credentials to a temporary location, then sets the variable to that location. (The file is deleted when the build completes.)
</div>
<div>
 <strong>Warning</strong>: if the Jenkins controller or agent node has multiple executors, any other build running concurrently on the same node will be able to read the contents of this file.
</div></div>
<ul><li><code>variable : String</code>
<div><div>
 Name of an environment variable to be set during the build. The contents of this location are not masked.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>gitUsernamePassword</code><div>
<ul><li><code>gitToolName : String</code>
<div><div>
 <p>Specify the Git tool installation name</p>
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Set the git username / password credential for <strong>HTTP</strong> and <strong>HTTPS</strong> protocols. 
 <p><strong>Shell example</strong></p>
 <pre>withCredentials([gitUsernamePassword(credentialsId: 'my-credentials-id',
                 gitToolName: 'git-tool')]) {
  sh 'git fetch --all'
}
</pre>
 <p></p>
 <p><strong>Batch example</strong></p>
 <pre>withCredentials([gitUsernamePassword(credentialsId: 'my-credentials-id',
                 gitToolName: 'git-tool')]) {
  bat 'git submodule update --init --recursive'
}
</pre>
 <p></p>
 <p><strong>Powershell example</strong></p>
 <pre>withCredentials([gitUsernamePassword(credentialsId: 'my-credentials-id',
                 gitToolName: 'git-tool')]) {
  powershell 'git push'
}
</pre>
 <p></p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'KeychainPasswordAndPathBinding'</code><div>
<ul><li><code>keychainPathVariable : String</code>
<div><div>
 Name of a variable that contains information about the keychain path stored in the 'Credentials'.
 <br>
  Because values are stored in the environment variable of the name specified here, you can use the information stored in the 'Credentials' by shell script etc.
</div></div>

</li>
<li><code>passwordVariable : String</code>
<div><div>
 Name of a variable that contains information about the keychain password stored in the 'Credentials'.
 <br>
  Because values are stored in the environment variable of the name specified here, you can use the information stored in the 'Credentials' by shell script etc.
</div></div>

</li>
<li><code>inSearchPathVariable : String</code>
<div><div>
 Name of a variable that stores information on whether to set the keychain stored in the 'Credentials' to the search path.
 <br>
  Because values are stored in the environment variable of the name specified here, you can use the information stored in the 'Credentials' by shell script etc.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>OSFBuilderSuiteOpenCommerceAPICredentials</code><div>
<ul><li><code>clientIdVariable : String</code>
</li>
<li><code>clientPasswordVariable : String</code>
</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>sshUserPrivateKey</code><div>
<div><div>
 Copies the SSH key file given in the credentials to a temporary location, then sets a variable to that location. (The file is deleted when the build completes.) Also optionally sets variables for the SSH key's username and passphrase.
</div>
<div>
 <strong>Warning</strong>: if the Jenkins controller or agent node has multiple executors, any other build running concurrently on the same node will be able to read the contents of this file.
</div></div>
<ul><li><code>keyFileVariable : String</code>
<div><div>
 Name of an environment variable to be set to the temporary path of the SSH key file during the build. The contents of this file are not masked.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
<li><code>passphraseVariable : String</code> (optional)
<div><div>
 Name of an environment variable to be set to the password during the build. (optional)
</div></div>

</li>
<li><code>usernameVariable : String</code> (optional)
<div><div>
 Name of an environment variable to be set to the username during the build. (optional)
</div></div>

</li>
</ul></div></li>
<li><code>string</code><div>
<div><div>
 Sets a variable to the text given in the credentials.
</div>
<div>
 <strong>Warning</strong>: if the Jenkins controller or agent node has multiple executors, any other build running concurrently on the same node will be able to read the text of the secret, for example on Linux using <code>ps e</code>.
</div></div>
<ul><li><code>variable : String</code>
<div><div>
 Name of an environment variable to be set during the build. The contents of this location are not masked.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>OSFBuilderSuiteTwoFactorAuthCredentials</code><div>
<ul><li><code>serverCertificateVariable : String</code>
</li>
<li><code>clientCertificateVariable : String</code>
</li>
<li><code>clientPrivateKeyVariable : String</code>
</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>usernameColonPassword</code><div>
<div><div>
 Sets a variable to the username and password given in the credentials, separated by a colon (<code>:</code>).
</div>
<div>
 <strong>Warning</strong>: if the Jenkins controller or agent node has multiple executors, any other build running concurrently on the same node will be able to read the text of the secret, for example on Linux using <code>ps e</code>.
</div></div>
<ul><li><code>variable : String</code>
<div><div>
 Name of an environment variable to be set during the build. The contents of this location are not masked.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>usernamePassword</code><div>
<div><div>
 Sets one variable to the username and one variable to the password given in the credentials.
</div>
<div>
 <strong>Warning</strong>: if the Jenkins controller or agent node has multiple executors, any other build running concurrently on the same node will be able to read the text of the secret, for example on Linux using <code>ps e</code>.
</div></div>
<ul><li><code>usernameVariable : String</code>
<div><div>
 Name of an environment variable to be set to the username during the build.
</div></div>

</li>
<li><code>passwordVariable : String</code>
<div><div>
 Name of an environment variable to be set to the password during the build.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'VaultCertificateCredentialsBinding'</code><div>
<div><div>
 Certificate Jenkins credential backed by a Hashicorp Vault secret
</div></div>
<ul><li><code>keyStoreVariable : String</code>
</li>
<li><code>passwordVariable : String</code>
</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>vaultFile</code><div>
<div><div>
 Secret File Jenkins credential backed by a Hashicorp Vault secret
</div></div>
<ul><li><code>variable : String</code>
<div><div>
 Name of an environment variable to be set during the build. The contents of this location are not masked.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'VaultSSHUserPrivateKeyBinding'</code><div>
<div><div>
 SSH Username with private key credential backed by a Hashicorp Vault secret
</div></div>
<ul><li><code>usernameVariable : String</code>
</li>
<li><code>privateKeyVariable : String</code>
</li>
<li><code>passphraseVariable : String</code>
</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>vaultString</code><div>
<div><div>
 Secret Text Jenkins credential backed by a Hashicorp Vault secret
</div></div>
<ul><li><code>variable : String</code>
<div><div>
 Name of an environment variable to be set during the build. The contents of this location are not masked.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'VaultTokenCredentialBinding'</code><div>
<ul><li><code>addrVariable : String</code>
<div><div>
 The environment variable to set with the vault address.
</div></div>

</li>
<li><code>tokenVariable : String</code>
<div><div>
 The environment variable to set with the vault token.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
<li><code>vaultAddr : String</code>
<div><div>
 The vault address where the credentials are to be used.
</div></div>

</li>
<li><code>namespaceVariable : String</code> (optional)
</li>
<li><code>vaultNamespace : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'VaultUsernamePasswordCredentialBinding'</code><div>
<div><div>
 Username/ Password Jenkins credential backed by a Hashicorp Vault secret
</div></div>
<ul><li><code>usernameVariable : String</code>
</li>
<li><code>passwordVariable : String</code>
</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>zip</code><div>
<div><div>
 Unpacks the ZIP file given in the credentials to a temporary directory, then sets the variable to that location. (The directory is deleted when the build completes.)
</div>
<div>
 <strong>Warning</strong>: if the Jenkins controller or agent node has multiple executors, any other build running concurrently on the same node will be able to read the contents of this directory.
</div></div>
<ul><li><code>variable : String</code>
<div><div>
 Name of an environment variable to be set during the build. The contents of this location are not masked.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
</ul></div></li>
<li><code>azureServicePrincipal</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
<li><code>clientIdVariable : String</code> (optional)
</li>
<li><code>clientSecretVariable : String</code> (optional)
</li>
<li><code>subscriptionIdVariable : String</code> (optional)
</li>
<li><code>tenantIdVariable : String</code> (optional)
</li>
</ul></div></li>
<li><code>azureStorage</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Credentials of an appropriate type to be set to the variable.
</div></div>

</li>
<li><code>blobEndpointUrlVariable : String</code> (optional)
</li>
<li><code>cdnEndpointUrlVariable : String</code> (optional)
</li>
<li><code>storageAccountKeyVariable : String</code> (optional)
</li>
<li><code>storageAccountNameVariable : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
</ul>


++++
