= Cucumber reports
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/cucumber-reports">Visit the Jenkins Plugins site</a>
++++


=== `cucumber`: Cucumber reports
++++
<div><p><b>Publishes Cucumber results</b></p>
<p>This plugin requires that you use <b>cucumber</b> library to generate a <b>json</b> report. The plugin uses the json report to produce html reports that are available from jenkins on the build page after a build has run.</p>
<pre>
	import cucumber.junit.Cucumber;
	import org.junit.runner.RunWith;

	@RunWith(Cucumber.class)
	@Cucumber.Options(format = {"pretty", "html:target/cucumber", "json:target/cucumber.json"})
	public class MyTest {

	}
</pre></div>
<ul><li><code>fileIncludePattern : String</code>
<div><p>Filter for the files that should be processed. Leave empty to use default pattern <code>**/*.json</code>.</p></div>

</li>
<li><code>buildStatus : String</code> (optional)
<div><p>Build <a href="http://javadoc.jenkins-ci.org/hudson/model/Result.html" rel="nofollow">result</a> to which the build should be set when the report is marked as failed or unstable.</p></div>

</li>
<li><code>classifications</code> (optional)
<div><p>Configure additional information as key-value displayed on main page of the report.</p></div>

<ul><b>Array / List of Nested Object</b>
<div><p>Pairs key-value which are passed to the report to be displayed.</p></div>
<li><code>key : String</code>
<div><p>Name of the classification.</p></div>

</li>
<li><code>value : String</code>
<div><p>Value of the classification. Hyperlink, HTML code and Jenkins variable can be used for values, check <a href="https://wiki.jenkins-ci.org/display/JENKINS/Token+Macro+Plugin" rel="nofollow">Token Macro Plugin</a> for details.</p></div>

</li>
</ul></li>
<li><code>classificationsFilePattern : String</code> (optional)
<div><p>Filter for the properties files that should be processed as classifications. Leave empty to use default pattern <code>**/*.properties</code>. The pattern is evaluated relative to <code>jsonReportDirectory</code></p></div>

</li>
<li><code>customCssFiles : String</code> (optional)
<div><p>Comma separated list of CSS files or patterns (relative to workspace) to include into all report pages.</p></div>

</li>
<li><code>customJsFiles : String</code> (optional)
<div><p>Comma separated list of JS files or patterns (relative to workspace) to include into all report pages.</p></div>

</li>
<li><code>expandAllSteps : boolean</code> (optional)
</li>
<li><code>failedAsNotFailingStatus : boolean</code> (optional)
<div><p>Failed statuses for the step is counted as not failing status and does not fail scenario.</p></div>

</li>
<li><code>failedFeaturesNumber : int</code> (optional)
<div><p>Maximum number of failed features above which build result is triggered. Provide value -1 if the rule should be skipped.</p></div>

</li>
<li><code>failedFeaturesPercentage : double</code> (optional)
<div><p>Maximum percentage of failed features above which build result is changed.</p></div>

</li>
<li><code>failedScenariosNumber : int</code> (optional)
<div><p>Maximum number of failed scenarios above which build result is triggered. Provide value -1 if the rule should be skipped.</p></div>

</li>
<li><code>failedScenariosPercentage : double</code> (optional)
<div><p>Maximum percentage of failed scenarios above which build result is changed.</p></div>

</li>
<li><code>failedStepsNumber : int</code> (optional)
<div><p>Maximum number of failed steps above which build result is triggered. Provide value -1 if the rule should be skipped.</p></div>

</li>
<li><code>failedStepsPercentage : double</code> (optional)
<div><p>Maximum percentage of failed steps above which build result is changed.</p></div>

</li>
<li><code>fileExcludePattern : String</code> (optional)
<div><p>Filter for the files that should be excluded from the report.</p></div>

</li>
<li><code>hideEmptyHooks : boolean</code> (optional)
</li>
<li><code>jsonReportDirectory : String</code> (optional)
<div><p>Directory where the JSON cucumber reports are located. By default and for empty value whole workspace is scanned.</p></div>

</li>
<li><code>mergeFeaturesById : boolean</code> (optional)
<div><p>Merge features with different JSON files that have same ID so scenarios are be stored in single feature.</p></div>

</li>
<li><code>mergeFeaturesWithRetest : boolean</code> (optional)
<div><p>Merge features and scenarios from different JSON files of different runs into a single report by features and scenarios ids.</p>
<p><b>Example:</b><br>
  Original cucumber report is "cucumber.json". Let's look a situation when couple of tests failed there. Cucumber runner generates a new report, for example, cucumber-rerun.json as a result of rerun the failed tests. <br>
  In that case you will have a merged report where all failed tests from the original cucumber.json file are overridden with the results from the cucumber-rerun.json.</p></div>

</li>
<li><code>pendingAsNotFailingStatus : boolean</code> (optional)
<div><p>Pending statuses for the step is counted as not failing status and does not fail scenario.</p></div>

</li>
<li><code>pendingStepsNumber : int</code> (optional)
<div><p>Maximum number of pending steps above which build result is triggered. Provide value -1 if the rule should be skipped.</p></div>

</li>
<li><code>pendingStepsPercentage : double</code> (optional)
<div><p>Maximum percentage of pending steps above which build result is changed.</p></div>

</li>
<li><code>reportTitle : String</code> (optional)
</li>
<li><code>skipEmptyJSONFiles : boolean</code> (optional)
<div><p>Skip empty JSON reports. If this flag is not selected then report generation fails on empty file.</p></div>

</li>
<li><code>skippedAsNotFailingStatus : boolean</code> (optional)
<div><p>Skipped statuses for the step is counted as not failing status and does not fail scenario.</p></div>

</li>
<li><code>skippedStepsNumber : int</code> (optional)
<div><p>Maximum number of skipped steps above which build result is triggered. Provide value -1 if the rule should be skipped.</p></div>

</li>
<li><code>skippedStepsPercentage : double</code> (optional)
<div><p>Maximum percentage of skipped steps above which build result is changed.</p></div>

</li>
<li><code>sortingMethod : String</code> (optional)
<div><p>This section allows to configure what is default sorting method for features:</p>
<ul>
 <li>NATURAL - keeps same order as it was in JSON file</li>
 <li>ALPHABETICAL - sorts rows alphabetically</li>
</ul></div>

</li>
<li><code>stopBuildOnFailedReport : boolean</code> (optional)
<div><p>The default behaviour is to carry on with the build even if the cucumber report contains failures. This option stops the build. Particularly useful when for example there is a need for all tests to pass before deploying to production. Note that this overrides the Build Status option, and it always marks the build as failed.</p></div>

</li>
<li><code>trendsLimit : int</code> (optional)
<div><p>Number of historical reports that should be presented.</p>
<ul>
 <li>set to -1 so trends won't be displayed and history won't be stored</li>
 <li>set to 0 then all historical reports will be stored and displayed</li>
 <li>set to other positive value to decide how many historical reports should be presented by trends.</li>
</ul></div>

</li>
<li><code>undefinedAsNotFailingStatus : boolean</code> (optional)
<div><p>Undefined statuses for the step is counted as not failing status and does not fail scenario.</p></div>

</li>
<li><code>undefinedStepsNumber : int</code> (optional)
<div><p>Maximum number of undefined steps above which build result is triggered. Provide value -1 if the rule should be skipped.</p></div>

</li>
<li><code>undefinedStepsPercentage : double</code> (optional)
<div><p>Maximum percentage of undefined steps above which build result is changed.</p></div>

</li>
</ul>


++++
