= Cucumber json test reporting.
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/cucumber-testresult-plugin">Visit the Jenkins Plugins site</a>
++++


=== `cucumber`: Publish Cucumber test result report
++++
<div><div>
 Cucumber test results report in JSON format. When this option is configured, Jenkins can provide useful information about test results, such as historical test result trends, a web UI for viewing test reports, tracking failures, and so on. 
 <p>To use this feature, first set up your build to run tests, then specify the path to Cucumber JSON files in the <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">Ant glob syntax</a>, such as **/build/test-reports/*.json. Be sure not to include any non-report files into this pattern. You can specify only one file pattern.</p>
 <p>Once there are a few builds running with test results, you should start seeing something like <a href="https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Test+Result+Plugin" rel="nofollow">this</a>.</p>
</div></div>
<ul><li><code>testResults : String</code>
<div><div>
 ANT Glob set.
</div></div>

</li>
<li><code>ignoreBadSteps : boolean</code> (optional)
<div><div>
 Ignore not closed steps in broken JSON for GherkinParser. See: <a href="https://issues.jenkins-ci.org/browse/JENKINS-21835" rel="nofollow">#JENKINS-21835</a>
</div></div>

</li>
</ul>


++++
