= Data Theorem Mobile Security: CI/CD Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/datatheorem-mobile-app-security">Visit the Jenkins Plugins site</a>
++++


=== `sendBuildToDataTheorem`: Upload build to Data Theorem
++++
<ul><li><code>buildToUpload : String</code> (optional)
<div><div>
 <p>The build file name that you want to send to Data Theorem. The build has to be generated either in the workspace or in the archive directory</p>
 <p>If the name of the target is variable, you can use a glob pattern to specify the file for example **/release/app-*.apk</p>
</div></div>

</li>
<li><code>applicationCredentialComments : String</code> (optional)
</li>
<li><code>applicationCredentialPassword : String</code> (optional)
<div><div>
 <p>In order to run a full dynamic scan with an application with a login page, Data Theorem needs a test account. Please Provide us the password for this account here</p>
</div></div>

</li>
<li><code>applicationCredentialUsername : String</code> (optional)
<div><div>
 <p>In order to run a full dynamic scan with an application with a login pagen Data Theorem needs a test account. Please Provide us the username for this account here</p>
</div></div>

</li>
<li><code>dataTheoremUploadApiKey : String</code> (optional)
</li>
<li><code>dontUpload : boolean</code> (optional)
<div><div>
 <p>Check this option to print the path of the build output without uploading anything</p>
 <p>You can use this option to simulate the plugin features without sending anything to Data Theorem</p>
</div></div>

</li>
<li><code>externalId : String</code> (optional)
<div><div>
 <p>Set the external ID of the application. The `external_id` field represents your organization's custom identifier for the app, if any.</p>
</div></div>

</li>
<li><code>mappingFileToUpload : String</code> (optional)
<div><div>
 <p>If your Android application is obfuscated using Proguard, you can upload a mapping file to have scan results deobfuscated. This is not required for scans to be completed. However, once a mapping file has been uploaded once, all subsequent uploads will require the corresponding mapping file unless the requirement is disabled via the Results API v2.</p>
 <p></p>
</div></div>

</li>
<li><code>proxyHostname : String</code> (optional)
</li>
<li><code>proxyPassword : String</code> (optional)
</li>
<li><code>proxyPort : int</code> (optional)
</li>
<li><code>proxyUnsecuredConnection : boolean</code> (optional)
<div><div>
 <p>This option will disable SSL Certificate Validation for each data theorem endpoint request.</p>
</div></div>

</li>
<li><code>proxyUsername : String</code> (optional)
</li>
<li><code>releaseType : String</code> (optional)
<div><div>
 <p>Set the release type of the application. The allowed values are:</p>
 <ul>
  <li>Pre Production: The application is not used in production and intended for pre-production testing</li>
  <li>Enterprise: The application is used in production but not distributed via app stores</li>
 </ul>
 <p></p>
</div></div>

</li>
<li><code>sendBuildDirectlyFromRemote : boolean</code> (optional)
<div><div>
 <p>By default the build is stream to the main node before being sent to Data Theorem. Checking this option will allow the building node to directly send the build to Data Theorem.</p>
</div></div>

</li>
</ul>


++++
