= OWASP Dependency-Check Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/dependency-check-jenkins-plugin">Visit the Jenkins Plugins site</a>
++++


=== `dependencyCheckPublisher`: Publish Dependency-Check results
++++
<ul><li><code>failedNewCritical : int</code> (optional)
</li>
<li><code>failedNewHigh : int</code> (optional)
</li>
<li><code>failedNewLow : int</code> (optional)
</li>
<li><code>failedNewMedium : int</code> (optional)
</li>
<li><code>failedTotalCritical : int</code> (optional)
</li>
<li><code>failedTotalHigh : int</code> (optional)
</li>
<li><code>failedTotalLow : int</code> (optional)
</li>
<li><code>failedTotalMedium : int</code> (optional)
</li>
<li><code>newThresholdAnalysisExploitable : boolean</code> (optional)
</li>
<li><code>pattern : String</code> (optional)
</li>
<li><code>stopBuild : boolean</code> (optional)
</li>
<li><code>totalThresholdAnalysisExploitable : boolean</code> (optional)
</li>
<li><code>unstableNewCritical : int</code> (optional)
</li>
<li><code>unstableNewHigh : int</code> (optional)
</li>
<li><code>unstableNewLow : int</code> (optional)
</li>
<li><code>unstableNewMedium : int</code> (optional)
</li>
<li><code>unstableTotalCritical : int</code> (optional)
</li>
<li><code>unstableTotalHigh : int</code> (optional)
</li>
<li><code>unstableTotalLow : int</code> (optional)
</li>
<li><code>unstableTotalMedium : int</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'DependencyCheckPublisher'])`: Publish Dependency-Check results
++++
<ul><li><code>failedNewCritical : int</code> (optional)
</li>
<li><code>failedNewHigh : int</code> (optional)
</li>
<li><code>failedNewLow : int</code> (optional)
</li>
<li><code>failedNewMedium : int</code> (optional)
</li>
<li><code>failedTotalCritical : int</code> (optional)
</li>
<li><code>failedTotalHigh : int</code> (optional)
</li>
<li><code>failedTotalLow : int</code> (optional)
</li>
<li><code>failedTotalMedium : int</code> (optional)
</li>
<li><code>newThresholdAnalysisExploitable : boolean</code> (optional)
</li>
<li><code>pattern : String</code> (optional)
<div><div>
 Specifies the Dependency-Check XML report to parse. If not specified, the value will default to **/dependency-check-report.xml.
</div></div>

</li>
<li><code>stopBuild : boolean</code> (optional)
<div><div>
 If enabled, it stops the build when one of failed threshold is violated. It does not on unstable threshold.
</div></div>

</li>
<li><code>totalThresholdAnalysisExploitable : boolean</code> (optional)
</li>
<li><code>unstableNewCritical : int</code> (optional)
</li>
<li><code>unstableNewHigh : int</code> (optional)
</li>
<li><code>unstableNewLow : int</code> (optional)
</li>
<li><code>unstableNewMedium : int</code> (optional)
</li>
<li><code>unstableTotalCritical : int</code> (optional)
</li>
<li><code>unstableTotalHigh : int</code> (optional)
</li>
<li><code>unstableTotalLow : int</code> (optional)
</li>
<li><code>unstableTotalMedium : int</code> (optional)
</li>
</ul>


++++
=== `dependencyCheck`: Invoke Dependency-Check
++++
<ul><li><code>odcInstallation : String</code>
</li>
<li><code>additionalArguments : String</code> (optional)
<div><div>
 Defines the arguments to pass to the command-line tool. By default, the following options will be passed if not specified: 
 <br>
 <br>
 <table>
  <tbody>
   <tr>
    <td>--project</td>
    <td>The name of the Jenkins job</td>
   </tr>
   <tr>
    <td>--scan</td>
    <td>The build workspace</td>
   </tr>
   <tr>
    <td>--format</td>
    <td>XML</td>
   </tr>
  </tbody>
 </table>
</div></div>

</li>
<li><code>nvdCredentialsId : String</code> (optional)
<div><div>
 <p>With 9.0.0 dependency-check has moved from using the NVD data-feed to the NVD API.<br>
   Users of dependency-check are <b>highly</b> encouraged to obtain an NVD API Key; see https://nvd.nist.gov/developers/request-an-api-key<br>
   Without an NVD API Key dependency-check's updates will be <b>extremely slow</b>.</p>
 <p><b>The NVD API Key, CI, and Rate Limiting</b><br>
   The NVD API has enforced rate limits. If you are using a single API KEY and multiple builds occur you could hit the rate limit and receive 403 errors.<br><u>In a CI environment one must use a caching strategy or use a set API KEY to use for different jobs.</u></p>
</div></div>

</li>
<li><code>skipOnScmChange : boolean</code> (optional)
<div><div>
 If enabled, a Dependency-Check analysis will not be performed if the job was triggered by an SCM change.
</div></div>

</li>
<li><code>skipOnUpstreamChange : boolean</code> (optional)
<div><div>
 If enabled, a Dependency-Check analysis will not be performed if the job was triggered by an upstream change.
</div></div>

</li>
<li><code>stopBuild : boolean</code> (optional)
<div><div>
 If enabled, it stops the build when the Dependency-Check analysis exit with code different than 0.
</div></div>

</li>
</ul>


++++
