= XebiaLabs XL Deploy Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/deployit-plugin">Visit the Jenkins Plugins site</a>
++++


=== `xldCreatePackage`: Create a deployment package
++++
<div><div>
 Adds a step to package a DAR file.
</div></div>
<ul><li><code>artifactsPath : String</code>
<div><div>
 Path to the artifact directory, relative to the workspace. Jenkins environment variables can be used to specify this value. For example: build/distribution
</div></div>

</li>
<li><code>manifestPath : String</code>
<div><div>
 Path of the deployit-manifest.xml file, relative to the workspace. Jenkin's environment variables can be used to specify values in the manifest file.
</div></div>

</li>
<li><code>darPath : String</code>
<div><div>
 Path for the newly created DAR file, relative to the workspace. Jenkins environment variables can be used to specify this value. For example: $JOB_NAME-$BUILD_NUMBER.0.dar
</div></div>

</li>
</ul>


++++
=== `xldDeploy`: Deploy a package to a environment
++++
<div><div>
 Adds a step to deploy artifacts on environments in the XL Deploy server using Jenkins.
</div></div>
<ul><li><code>serverCredentials : String</code>
</li>
<li><code>packageId : String</code>
</li>
<li><code>environmentId : String</code>
<div><div>
 ID of the environment in XL Deploy to which the artifact should be deployed. Jenkins environment variables can be used to specify this value. For example: Environments/Dev
</div></div>

</li>
<li><code>failOnArchiveFailure : boolean</code> (optional)
</li>
<li><code>overrideCredentialId : String</code> (optional)
</li>
<li><code>rollbackOnError : boolean</code> (optional)
</li>
</ul>


++++
=== `xldPublishPackage`: Publish a deployment package to XLDeploy
++++
<div><div>
 Adds a step to publish the DAR file to the XL Deploy server using Jenkins.
</div></div>
<ul><li><code>darPath : String</code>
<div><div>
 Path to the DAR file (relative to the workspace) that should be published on the XL Deploy server. For example: $JOB_NAME-$BUILD_NUMBER.0.dar
</div></div>

</li>
<li><code>serverCredentials : String</code>
<div><div>
 XL Deploy server credentials used to connect to the XL Deploy server. This must be configured under Manage Jenkins &gt;&gt; Configure System &gt;&gt; XL Deploy.
</div></div>

</li>
<li><code>overrideCredentialId : String</code> (optional)
</li>
</ul>


++++
