= DevOps Portal
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/devops-portal">Visit the Jenkins Plugins site</a>
++++


=== `reportArtifactRelease`: Record an artifact release
++++
<ul><li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationVersion : String</code> (optional)
</li>
<li><code>applicationComponent : String</code> (optional)
</li>
<li><code>artifactName : String</code> (optional)
</li>
<li><code>artifactURL : String</code> (optional)
</li>
<li><code>repositoryName : String</code> (optional)
</li>
<li><code>tags : String</code> (optional)
</li>
</ul>


++++
=== `reportBuild`: Record a build report
++++
<ul><li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationVersion : String</code> (optional)
</li>
<li><code>applicationComponent : String</code> (optional)
</li>
<li><code>artifactFileName : String</code> (optional)
</li>
<li><code>artifactFileSizeLimit : int</code> (optional)
</li>
</ul>


++++
=== `reportDeployOperation`: Record a Deployment operation
++++
<ul><li><code>targetService : String</code> (optional)
</li>
<li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationVersion : String</code> (optional)
</li>
<li><code>tags : String</code> (optional)
</li>
</ul>


++++
=== `reportJMeterPerformanceTest`: Record a performance test with JMeter
++++
<ul><li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationVersion : String</code> (optional)
</li>
<li><code>applicationComponent : String</code> (optional)
</li>
<li><code>jmeterReportPath : String</code> (optional)
</li>
</ul>


++++
=== `reportMavenDependenciesAnalysis`: Record a dependencies analysis
++++
<ul><li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationVersion : String</code> (optional)
</li>
<li><code>applicationComponent : String</code> (optional)
</li>
<li><code>reportPath : String</code> (optional)
</li>
</ul>


++++
=== `reportPerformanceTest`: Record a performance test
++++
<ul><li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationVersion : String</code> (optional)
</li>
<li><code>applicationComponent : String</code> (optional)
</li>
<li><code>errorCount : long</code> (optional)
</li>
<li><code>sampleCount : long</code> (optional)
</li>
<li><code>testCount : long</code> (optional)
</li>
</ul>


++++
=== `reportQualityAudit`: Record a quality audit manually
++++
<ul><li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationVersion : String</code> (optional)
</li>
<li><code>applicationComponent : String</code> (optional)
</li>
<li><code>bugCount : int</code> (optional)
</li>
<li><code>bugScore : <code>Object</code></code> (optional)
</li>
<li><code>duplicationRate : float</code> (optional)
</li>
<li><code>hotspotCount : int</code> (optional)
</li>
<li><code>hotspotScore : <code>Object</code></code> (optional)
</li>
<li><code>linesCount : long</code> (optional)
</li>
<li><code>qualityGatePassed : boolean</code> (optional)
</li>
<li><code>testCoverage : float</code> (optional)
</li>
<li><code>vulnerabilityCount : int</code> (optional)
</li>
<li><code>vulnerabilityScore : <code>Object</code></code> (optional)
</li>
</ul>


++++
=== `reportSonarQubeAudit`: Record a SonarQube quality audit
++++
<ul><li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationVersion : String</code> (optional)
</li>
<li><code>applicationComponent : String</code> (optional)
</li>
<li><code>acceptInvalidCertificate : boolean</code> (optional)
</li>
<li><code>projectKey : String</code> (optional)
</li>
</ul>


++++
=== `reportSurefireTest`: Record a Surefire UT report
++++
<ul><li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationVersion : String</code> (optional)
</li>
<li><code>applicationComponent : String</code> (optional)
</li>
<li><code>surefireReportPath : String</code> (optional)
</li>
</ul>


++++
=== `reportUnitTest`: Record a UT report manually
++++
<ul><li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationVersion : String</code> (optional)
</li>
<li><code>applicationComponent : String</code> (optional)
</li>
<li><code>testCoverage : float</code> (optional)
</li>
<li><code>testsFailed : int</code> (optional)
</li>
<li><code>testsIgnored : int</code> (optional)
</li>
<li><code>testsPassed : int</code> (optional)
</li>
</ul>


++++
