= Dimensions Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/dimensionsscm">Visit the Jenkins Plugins site</a>
++++


=== `dimensionsscm`: Dimensions
++++
<ul><li><code>project : String</code>
</li>
<li><code>credentialsType : String</code>
</li>
<li><code>canJobDelete : boolean</code> (optional)
</li>
<li><code>canJobExpand : boolean</code> (optional)
</li>
<li><code>canJobForce : boolean</code> (optional)
</li>
<li><code>canJobNoMetadata : boolean</code> (optional)
</li>
<li><code>canJobNoTouch : boolean</code> (optional)
</li>
<li><code>canJobRevert : boolean</code> (optional)
</li>
<li><code>canJobUpdate : boolean</code> (optional)
</li>
<li><code>certificateAlias : String</code> (optional)
</li>
<li><code>certificatePassword : String</code> (optional)
</li>
<li><code>certificatePath : String</code> (optional)
</li>
<li><code>changelog : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in changelog': 
 <p>If 'Include in changelog' is enabled for an SCM source, then when a build occurs, the changes from that SCM source will be included in the changelog.</p>
 <p>If 'Include in changelog' is disabled, then when a build occurs, the changes from this SCM source will not be included in the changelog.</p>
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>eol : String</code> (optional)
</li>
<li><code>folders</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>keystoreDatabase : String</code> (optional)
</li>
<li><code>keystorePassword : String</code> (optional)
</li>
<li><code>keystorePath : String</code> (optional)
</li>
<li><code>keystoreServer : String</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>pathsToExclude</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>permissions : String</code> (optional)
</li>
<li><code>pluginDatabase : String</code> (optional)
</li>
<li><code>pluginServer : String</code> (optional)
</li>
<li><code>poll : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in polling' 
 <p>If 'Include in polling' is enabled or 'Include in changelog' is enabled, then when polling occurs, the job will be started if changes are detected from this SCM source.</p>
 <p>If 'Include in polling' is disabled and 'Include in changelog' is disabled, then when polling occurs, changes that are detected from this repository will be ignored.</p>
</div></div>

</li>
<li><code>remoteCertificatePassword : String</code> (optional)
</li>
<li><code>secureAgentAuth : boolean</code> (optional)
</li>
<li><code>timeZone : String</code> (optional)
</li>
<li><code>userDatabase : String</code> (optional)
</li>
<li><code>userName : String</code> (optional)
</li>
<li><code>userServer : String</code> (optional)
</li>
<li><code>webUrl : String</code> (optional)
</li>
</ul>


++++
