= Discord Notifier
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/discord-notifier">Visit the Jenkins Plugins site</a>
++++


=== `discordSend`: Send an embed message to Webhook URL
++++
<ul><li><code>webhookURL : String</code>
<div><div>
 If you don't have a webhook url take a look at <a href="https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks" rel="nofollow">this intro to Discord Webhooks</a>. 
 <br>
 Paste the entire url in the textbox.
</div></div>

</li>
<li><code>customAvatarUrl : String</code> (optional)
</li>
<li><code>customUsername : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
<div><div>
 Message text which supports limited markdown. 
 <br>
 <br>
 See <a href="https://support.discordapp.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-" rel="nofollow">Markdown Text 101 (Chat Formatting: Bold, Italic, Underline)</a> for more info on markdown support.
</div></div>

</li>
<li><code>dynamicFieldContainer : String</code> (optional)
</li>
<li><code>enableArtifactsList : boolean</code> (optional)
</li>
<li><code>footer : String</code> (optional)
<div><div>
 Text in footer of message
</div></div>

</li>
<li><code>image : String</code> (optional)
<div><div>
 URL of the image under everything
</div></div>

</li>
<li><code>link : String</code> (optional)
<div><div>
 When set the title of the message comes clickable and leads to this url. 
 <br>
 <br>
 To link the executed job use <code>env.BUILD_URL</code>. 
 <br>
 This requires Jenkins URL to be set in Global Settings.
</div></div>

</li>
<li><code>notes : String</code> (optional)
</li>
<li><code>result : String</code> (optional)
<div><div>
 Enum to set the build result. Accepts values <code>SUCCESS|UNSTABLE|FAILURE|ABORTED</code>. This field is preferred over success and unstable.
</div></div>

</li>
<li><code>scmWebUrl : String</code> (optional)
</li>
<li><code>showChangeset : boolean</code> (optional)
</li>
<li><code>successful : boolean</code> (optional)
<div><div>
 Either colors the message as green or red depending on success. 
 <br>
 Use <code>currentBuild.resultIsBetterOrEqualTo('SUCCESS')</code> to color the message green on success or red otherwise.
</div></div>

</li>
<li><code>thumbnail : String</code> (optional)
<div><div>
 URL to image displayed on the right.
</div></div>

</li>
<li><code>title : String</code> (optional)
<div><div>
 Message title 
 <br>
 To set title to job name, use <code>env.JOB_NAME</code>.
</div></div>

</li>
<li><code>unstable : boolean</code> (optional)
<div><div>
 Set to true to set the color to yellow (only when the build was successful, else this is omitted).
</div></div>

</li>
</ul>


++++
