= Docker Pipeline
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/docker-workflow">Visit the Jenkins Plugins site</a>
++++


=== `dockerFingerprintFrom`: Record trace of a Docker image used in FROM
++++
<div><div>
 Records the fact that a Docker image was built from another. <strong>Deprecated:</strong> Fingerprints produced by this step are not used anywhere, and the parsing code has major limitations. See https://github.com/jenkinsci/docker-workflow-plugin/pull/149#issuecomment-451305522 and https://groups.google.com/d/msg/jenkinsci-dev/k13SfZcBWVg/iQghmCQrEAAJ If are a user of the Docker Traceability plugin you need to call this Step manually during the build. The mentioned limitations will limit the useability of this step for this purpose.
</div></div>
<ul><li><code>dockerfile : String</code>
<div><div>
 Workspace-relative path of a <code>Dockerfile</code> which will be parsed for its <code>FROM</code> instruction.
</div></div>

</li>
<li><code>image : String</code>
<div><div>
 ID or tag of the image which was just built, like <code>--tag</code> of <code>docker build</code>.
</div></div>

</li>
<li><code>commandLine : String</code> (optional)
</li>
<li><code>toolName : String</code> (optional)
</li>
</ul>


++++
=== `dockerFingerprintRun`: Record trace of a Docker image run in a container
++++
<div><div>
 Records the fact that a Docker image was used by this build. <strong>Deprecated:</strong> Fingerprints produced by this step are not used anywhere, and the parsing code has major limitations. See https://github.com/jenkinsci/docker-workflow-plugin/pull/149#issuecomment-451305522 and https://groups.google.com/d/msg/jenkinsci-dev/k13SfZcBWVg/iQghmCQrEAAJ If are a user of the Docker Traceability plugin you need to call this Step manually during the build. The mentioned limitations will limit the useability of this step for this purpose.
</div></div>
<ul><li><code>containerId : String</code>
</li>
<li><code>toolName : String</code> (optional)
</li>
</ul>


++++
=== `withDockerContainer`: Run build steps inside a Docker container
++++
<div><div>
 Normally used implicitly by method calls on the <code>docker</code> global variable. Takes an image ID or symbolic name <em>which must already have been pulled locally</em> and starts a container based on that image. Runs all nested <code>sh</code> steps inside that container. The workspace is mounted read-write into the container.
</div></div>
<ul><li><code>image : String</code>
</li>
<li><code>args : String</code> (optional)
<div><div>
 Any other arguments to pass to <code>docker run</code>.
</div></div>

</li>
<li><code>toolName : String</code> (optional)
</li>
</ul>


++++
=== `withDockerRegistry`: Sets up Docker registry endpoint
++++
<div><div>
 Normally used implicitly by method calls on the <code>docker</code> global variable. Sets up connection details for a Docker registry.
</div></div>
<ul><li><code>registry</code>
<ul><b>Nested Object</b>
<li><code>url : String</code>
<div><div>
 URL to the Docker registry you are using. May be left blank to use the public DockerHub registry (currently <code>https://index.docker.io/v1/</code>).
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
</ul></li>
<li><code>toolName : String</code> (optional)
</li>
</ul>


++++
=== `withDockerServer`: Sets up Docker server endpoint
++++
<div><div>
 Normally used implicitly by method calls on the <code>docker</code> global variable. Sets up connection details for a Docker server.
</div></div>
<ul><li><code>server</code>
<ul><b>Nested Object</b>
<li><code>uri : String</code>
<div><div>
 URI to the Docker Host you are using. May be left blank to use the Docker default (defined by DOCKER_HOST environment variable) (typically <code>unix:///var/run/docker.sock</code> or <code>tcp://127.0.0.1:2376</code>).
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
</ul></li>
</ul>


++++
