= DotCover
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/dotcoverrunner">Visit the Jenkins Plugins site</a>
++++


=== `dotcover`: Generate code coverage data and report(s)
++++
<div><div>
 Executes tests and generates code coverage data and reports. The coverage data and reports are not archived for you. You need to do this as a separate step.
</div>
<br></div>
<ul><li><code>NDependXmlReportPath : String</code> (optional)
</li>
<li><code>coverageAssemblyInclude : String</code> (optional)
</li>
<li><code>coverageClassInclude : String</code> (optional)
<div><div>
 <p>Includes the specified classes for which coverage data will be generated.</p>
 <p>For an in-depth explanation of how filtering is applied, please see the <a href="https://www.jetbrains.com/help/dotcover/Running_Coverage_Analysis_from_the_Command_LIne.html" rel="nofollow">DotCover documentation</a></p>
</div></div>

</li>
<li><code>coverageExclude : String</code> (optional)
<div><div>
 <p>Excludes the specified assemblies from coverage data. Note, that in addition to this exclusion definition, the assemblies matched by the glob in the global tool configuration for DotCover (named mandatory excludes) will ALWAYS be appended.</p>
 <p>For an in-depth explanation of how filtering is applied, please see the <a href="https://www.jetbrains.com/help/dotcover/Running_Coverage_Analysis_from_the_Command_LIne.html" rel="nofollow">DotCover documentation</a></p>
</div></div>

</li>
<li><code>coverageFunctionInclude : String</code> (optional)
<div><div>
 <p>Semicolon-separated list of names of methods to include in the coverage.</p>
 <p>For an in-depth explanation of how filtering is applied, please see the <a href="https://www.jetbrains.com/help/dotcover/Running_Coverage_Analysis_from_the_Command_LIne.html" rel="nofollow">DotCover documentation</a></p>
</div></div>

</li>
<li><code>detailedXMLReportPath : String</code> (optional)
<div><div>
 <p>Set the path to the detailed XML report with coverage data that DotCover will generate. The default is unset in which case DotCover will not generate this report.</p>
</div></div>

</li>
<li><code>htmlReportPath : String</code> (optional)
<div><div>
 <p>Path to the HTML report with coverage data that DotCover will generate. The default path is 'index.html'. This setting will have DotCover produce an index.html in the workspace + a subfolder with the data used in this webpage.</p>
</div></div>

</li>
<li><code>outputDir : String</code> (optional)
</li>
<li><code>processExclude : String</code> (optional)
<div><div>
 <p>Semicolon-separated list of process names. These processes will be disregarded in the test execution when DotCover is gathering coverage data. This can be helpful in scenarios where it is necessary to strictly define the scope of executables that are part of a test. For instance, DotCover sometimes (mistakenly) detects a database server as part of the the code being exercised in the test run, which can case problems with the coverage data because it tries to include the DB server in the scope of the test. For an in-depth explanation of how filtering is applied, please see the <a href="https://www.jetbrains.com/help/dotcover/Running_Coverage_Analysis_from_the_Command_LIne.html" rel="nofollow">DotCover documentation</a></p>
</div></div>

</li>
<li><code>processInclude : String</code> (optional)
<div><div>
 <p>Semicolon-separated list of process names. These processes will be considered in scope for the test execution when DotCover is gathering coverage data. This is helpful when it is necessary to restrict what executables are part of a test. For an in-depth explanation of how filtering is applied, please see the <a href="https://www.jetbrains.com/help/dotcover/Running_Coverage_Analysis_from_the_Command_LIne.html" rel="nofollow">DotCover documentation</a></p>
</div></div>

</li>
<li><code>vsTestArgs : String</code> (optional)
<div><div>
 <p>Additional arguments to pass to the VsTest test runner. These are simply passed through to the runner, so take care to quote them properly!</p>
</div></div>

</li>
<li><code>vsTestAssemblyFilter : String</code> (optional)
<div><div>
 <p>A glob that picks the test assemblies to include when gathering coverage data. The default value is **/*Test/bin/**/Release/*Test.dll</p>
</div></div>

</li>
<li><code>vsTestCaseFilter : String</code> (optional)
<div><div>
 <p>The testcase filter to pass to vstest. See <a href="https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?irgwc=1&amp;OCID=AID2000142_aff_7593_1375745&amp;tduid=(ir__vbyjjphsywkfr1ve0hnrewwq9n2xjlp6grxrzewx00)(7593)(1375745)()()&amp;irclickid=_vbyjjphsywkfr1ve0hnrewwq9n2xjlp6grxrzewx00&amp;view=vs-2019" rel="nofollow">this page</a> for in-depth explanation of vstest parameters.</p>
</div></div>

</li>
<li><code>vsTestPlatform : String</code> (optional)
<div><div>
 <p>The platform that is targeted by the tests when run through the test runner. Currently x86, x64 and ARM are supported.</p>
</div></div>

</li>
</ul>


++++
