= Digital.ai App Management Publisher
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/ease-plugin">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'ApperianRecorder'])`: Digital.ai App Management Publisher
++++
<ul><li><code>uploads</code>
<ul><b>Array / List of Nested Object</b>
<li><code>prodEnv : String</code>
<div><div>
 <p>Choose the production environment to which the plugin will connect. If you aren’t sure which environment to choose, contact Customer Support at <a href="mailto:support@arxan.com" rel="nofollow">support@arxan.com</a>.</p>
</div></div>

</li>
<li><code>customApperianUrl : String</code>
</li>
<li><code>apiTokenId : String</code>
<div><div>
 <p>Choose an API token to use for authenticating your Apperian organization.</p>
 <p>To include additional tokens in this list, go to <strong>Jenkins &gt; Credentials </strong> and add a new Global Credential. In the <strong>Kind</strong> field, choose Secret Text, set <strong>Scope</strong> to Global, and add your API token in the <strong>Secret</strong> field.</p>
 <p>The user associated with the API token must have valid permissions for adding apps in Apperian. For more information on user permissions, see <a href="https://help.apperian.com/display/pub/Managing+Users" rel="nofollow">Managing Users</a>.</p>
</div></div>

</li>
<li><code>appId : String</code>
<div><div>
 <p>To update an existing app, choose it from this list of native apps currently stored in your Apperian organization.</p>
</div></div>

</li>
<li><code>filename : String</code>
<div><div>
 <p>Specify the filename pattern that this plugin will use to search for and upload the app file from your workspace.</p>
 <p>If your project builds multiple versions of the app binary (for example, signed and unsigned), use this field to explicitly specify the correct file in the workspace. For example: target/android-app-v*.apk.</p>
</div></div>

</li>
<li><code>appName : String</code>
</li>
<li><code>shortDescription : String</code>
</li>
<li><code>longDescription : String</code>
</li>
<li><code>author : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>versionNotes : String</code>
</li>
<li><code>signApp : boolean</code>
</li>
<li><code>credential : String</code>
<div><div>
 <p>Choose the credentials you want to use to sign the app. If no credentials are listed, or if you need to add different credentials, see <a href="https://help.apperian.com/display/pub/Manage+Signing+Credentials" rel="nofollow">Managing Signing Credentials</a>.</p>
 <p>Remember, when you re-sign an iOS or Android app that was already installed on any of your users' devices, it is important that you sign it with the same signing credentials used to previously sign it.</p>
</div></div>

</li>
<li><code>enableApp : boolean</code>
</li>
<li><code>reapplyPolicies : boolean</code>
</li>
</ul></li>
</ul>


++++
