= tracetronic ecu.test Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/ecutest">Visit the Jenkins Plugins site</a>
++++


=== `publishATX`: [TT] Publish ATX Reports
++++
<div><div>
 <p>Publishes the ATX reports of all configured ecu.test packages or projects in this job.<br>
   These ATX reports are generated automatically in this post-build step and uploaded to test.guide.</p><strong>Pipeline usage</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
publishATX(String atxName, boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
publishATX(ATXInstallation installation, boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
ATXServer.publish(boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
ATXServer.publish(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
publishATX('test.guide', false, false, true, true)
            </pre>
   <pre>
def server = ATX.server('test.guide')
publishATX atxInstallation: server.installation
            </pre>
   <pre>
def server = ATX.newServer('test.guide', 'ecu.test')
server.publish()
            </pre>
   <pre>
def server = ATX.newServer atxName: 'test.guide', toolName: 'ecu.test'
server.publish allowMissing: true, runOnFailed: true, archiving: true, keepAll: true
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>atxName : String</code>
</li>
<li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>atxInstallation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>toolName : String</code>
</li>
<li><code>config</code>
<ul><b>Nested Object</b>
<li><code>settings</code>
<ul><li><b>Type:</b> <code>de.tracetronic.jenkins.plugins.ecutest.report.atx.installation.ATXSetting&lt;?&gt;</code></li>
</ul></li>
<li><code>customSettings</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>atxCustomBooleanSetting</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>checked : boolean</code>
</li>
</ul></div></li>
<li><code>atxCustomTextSetting</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
</ul></li>
</ul></li>
</ul></li>
<li><code>failOnOffline : boolean</code> (optional)
</li>
<li><code>injectBuildVars : boolean</code> (optional)
</li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
<li><code>usePersistedSettings : boolean</code> (optional)
</li>
</ul>


++++
=== `generateCache`: [TT] Generate Caches
++++
<div><div>
 Generate ecu.test file caches (A2L, ELF, Bus, Model and Service caches are supported).
</div></div>
<ul><li><code>caches</code>
<ul><b>Array / List of Nested Object</b>
<li><code>type</code>
<ul><li><b>Values:</b> <code>A2L</code>, <code>ELF</code>, <code>BUS</code>, <code>MODEL</code>, <code>SERVICE</code></li></ul></li>
<li><code>filePath : String</code>
</li>
<li><code>dbChannel : String</code>
</li>
<li><code>clear : boolean</code>
</li>
</ul></li>
</ul>


++++
=== `downstreamPublisher`: [TT] Downstream Report Generation
++++
<div><div>
 Generates report downstream-based on another Jenkins node. In order to work the ecu.test workspace has to be copied to that node with all relevant data (i.e. report directory) to generate reports. This can be achieved for free-style projects with the <a href="https://plugins.jenkins.io/copyartifact" rel="nofollow">Copy Artifact Plugin</a> or in pipelines with the stash/unstash commands.
</div></div>
<ul><li><code>workspace : String</code>
</li>
<li><code>reportDir : String</code>
</li>
<li><code>publishers</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>publishATX</code><div>
<div><div>
 <p>Publishes the ATX reports of all configured ecu.test packages or projects in this job.<br>
   These ATX reports are generated automatically in this post-build step and uploaded to test.guide.</p><strong>Pipeline usage</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
publishATX(String atxName, boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
publishATX(ATXInstallation installation, boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
ATXServer.publish(boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
ATXServer.publish(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
publishATX('test.guide', false, false, true, true)
            </pre>
   <pre>
def server = ATX.server('test.guide')
publishATX atxInstallation: server.installation
            </pre>
   <pre>
def server = ATX.newServer('test.guide', 'ecu.test')
server.publish()
            </pre>
   <pre>
def server = ATX.newServer atxName: 'test.guide', toolName: 'ecu.test'
server.publish allowMissing: true, runOnFailed: true, archiving: true, keepAll: true
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>atxName : String</code>
</li>
<li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>atxInstallation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>toolName : String</code>
</li>
<li><code>config</code>
<ul><b>Nested Object</b>
<li><code>settings</code>
<ul><li><b>Type:</b> <code>de.tracetronic.jenkins.plugins.ecutest.report.atx.installation.ATXSetting&lt;?&gt;</code></li>
</ul></li>
<li><code>customSettings</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>atxCustomBooleanSetting</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>checked : boolean</code>
</li>
</ul></div></li>
<li><code>atxCustomTextSetting</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
</ul></li>
</ul></li>
</ul></li>
<li><code>failOnOffline : boolean</code> (optional)
</li>
<li><code>injectBuildVars : boolean</code> (optional)
</li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
<li><code>usePersistedSettings : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>publishETLogs</code><div>
<div><div>
 Publishes the ecu.test log files (ECU_TEST_OUT.log and ECU_TEST_ERR.log) and parses them for warning and errors.
</div></div>
<ul><li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>failedOnError : boolean</code> (optional)
</li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
<li><code>testSpecific : boolean</code> (optional)
</li>
<li><code>unstableOnWarning : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>publishUNIT</code><div>
<div><div>
 <p>Publishes the UNIT reports of all configured ecu.test packages or projects in this job.<br>
   These UNIT reports are generated automatically in this post-build step.</p><strong>Pipeline usage</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
publishUNIT(String toolName, double unstableThreshold, double failedThreshold) : void
            </pre>
   <pre>
publishUNIT(ETInstallation installation, double unstableThreshold, double failedThreshold, boolean allowMissing, boolean runOnFailed) : void
            </pre>
   <pre>
ETInstance.publishUNIT(double unstableThreshold, double failedThreshold, boolean allowMissing, boolean runOnFailed) : void
            </pre>
   <pre>
ETInstance.publishUNIT(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
publishUNIT('ecu.test', 10, 20)
            </pre>
   <pre>
def instance = ET.installation('ecu.test')
publishUNIT installation: instance.installation, unstableThreshold: 10, failedThreshold: 20
            </pre>
   <pre>
def instance = ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0')
instance.publishUNIT()
            </pre>
   <pre>
def instance = ET.newInstallation toolName: 'ecu.test', installPath: C:\\Program Files\\ECU-TEST 8.0'
instance.publishUNIT unstableThreshold: 10, failedThreshold: 20, allowMissing: true, runOnFailed: true
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>failedThreshold : double</code> (optional)
</li>
<li><code>installation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>home : String</code>
</li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>? extends hudson.tools.ToolProperty&lt;?&gt;</code></li>
</ul></li>
</ul></li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
<li><code>unstableThreshold : double</code> (optional)
</li>
</ul></div></li>
<li><code>publishGenerators</code><div>
<div><div>
 <p>Publishes and generates reports by configuration of predefined and/or custom report generators.<br>
   These reports will be generated for all configured ecu.test packages or projects in this job.</p><strong>Pipeline usage</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
publishGenerators(String toolName, List&lt;ReportGeneratorConfig&gt; generators, List&lt;ReportGeneratorConfig&gt; customGenerators) : void
            </pre>
   <pre>
publishGenerators(ETInstallation installation, List&lt;ReportGeneratorConfig&gt; generators, List&lt;ReportGeneratorConfig&gt; customGenerators,
                  boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
ETInstance.publishGenerators(List&lt;ReportGeneratorConfig&gt; generators, List&lt;ReportGeneratorConfig&gt; customGenerators,
                             boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
ETInstance.publishGenerators(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
publishGenerators toolName: 'ecu.test', generators: [[name: 'JSON']]
            </pre>
   <pre>
def instance = ET.installation('ecu.test')
publishGenerators installation: instance.installation, generators: [[name: 'JSON']]
            </pre>
   <pre>
def instance = ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0')
instance.publishGenerators([[name: 'JSON']], [[name: 'Custom-JSON']])
            </pre>
   <pre>
def instance = ET.newInstallation toolName: 'ecu.test', installPath: C:\\Program Files\\ECU-TEST 8.0'
instance.publishGenerators generators: [[name: 'JSON']], customGenerators: [[name: 'Custom-JSON']], allowMissing: true, runOnFailed: true, archiving: true, keepAll: true
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>customGenerators</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>settings</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>usePersistedSettings : boolean</code>
</li>
</ul></li>
<li><code>generators</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>settings</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>usePersistedSettings : boolean</code>
</li>
</ul></li>
<li><code>installation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>home : String</code>
</li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>? extends hudson.tools.ToolProperty&lt;?&gt;</code></li>
</ul></li>
</ul></li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>publishTMS</code><div>
<div><div>
 <p>Publishes the test results of all configured ecu.test projects in this job to a preconfigured test management system like RQM or ALM.</p><strong>Pipeline usage</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
publishTMS(String toolName, String credentialsId, int timeout) : void
            </pre>
   <pre>
publishTMS(ETInstallation installation, String credentialsId, int timeout,
           boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
ETInstance.publishTMS(String credentialsId, int timeout) : void
            </pre>
   <pre>
ETInstance.publishTMS(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
publishTMS('ecu.test')
            </pre>
   <pre>
def instance = ET.installation('ecu.test')
publishTMS installation: instance.installation, credentialsId: 'id', timeout: 120
            </pre>
   <pre>
def instance = ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0')
instance.publishTMS('id')
            </pre>
   <pre>
def instance = ET.newInstallation toolName: 'ecu.test', installPath: C:\\Program Files\\ECU-TEST 8.0'
instance.publishTMS credentialsId: 'id', timeout: 120, allowMissing: true, runOnFailed: true, archiving: true, keepAll: true
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>installation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>home : String</code>
</li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>? extends hudson.tools.ToolProperty&lt;?&gt;</code></li>
</ul></li>
</ul></li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
</li>
</ul></div></li>
<li><code>publishTRF</code><div>
<div><div>
 Publishes the TRF reports of all configured ecu.test packages or projects in this job.
</div></div>
<ul><li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>publishTraceAnalysis</code><div>
<div><div>
 <p>Publishes the results of the trace analysis of all configured ecu.test packages or projects in this job.</p><strong>Pipeline usage</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
publishTraceAnalysis(String toolName, boolean mergeReports, boolean createReportDir, int timeout) : void
            </pre>
   <pre>
publishTraceAnalysis(ETInstallation installation, boolean mergeReports, boolean createReportDir, int timeout,
                     boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
ETInstance.publishTraceAnalysis(boolean mergeReports, boolean createReportDir, int timeout) : void
            </pre>
   <pre>
ETInstance.publishTraceAnalysis(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
publishTraceAnalysis('ecu.test')
            </pre>
   <pre>
def instance = ET.installation('ecu.test')
publishTraceAnalysis installation: instance.installation, mergeReports: true, createReportDir: false
            </pre>
   <pre>
def instance = ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0')
instance.publishTraceAnalysis()
            </pre>
   <pre>
def instance = ET.newInstallation toolName: 'ecu.test', installPath: C:\\Program Files\\ECU-TEST 8.0'
instance.publishTraceAnalysis mergeReports: true, createReportDir: false, timeout: 120, allowMissing: true, runOnFailed: true, archiving: true, keepAll: true
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>createReportDir : boolean</code> (optional)
</li>
<li><code>installation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>home : String</code>
</li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>? extends hudson.tools.ToolProperty&lt;?&gt;</code></li>
</ul></li>
</ul></li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>mergeReports : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
</ul>


++++
=== `publishETLogs`: [TT] Publish ecu.test Logs
++++
<div><div>
 Publishes the ecu.test log files (ECU_TEST_OUT.log and ECU_TEST_ERR.log) and parses them for warning and errors.
</div></div>
<ul><li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>failedOnError : boolean</code> (optional)
</li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
<li><code>testSpecific : boolean</code> (optional)
</li>
<li><code>unstableOnWarning : boolean</code> (optional)
</li>
</ul>


++++
=== `exportPackages`: [TT] Export Packages
++++
<div><div>
 Exports ecu.test packages and their attributes to a test management system like RQM or ALM.
</div></div>
<ul><li><code>exportConfigs</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'ExportPackageAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ExportPackageConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>exportPath : String</code>
</li>
<li><code>createNewPath : boolean</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ExportProjectAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ExportProjectConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>exportPath : String</code>
</li>
<li><code>createNewPath : boolean</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportPackageAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportPackageConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportPackageDirConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectArchiveConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>importConfigPath : String</code>
</li>
<li><code>replaceFiles : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>importMissingPackages : boolean</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
<li><code>tmProjectId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectDirConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
</ul></li>
</ul>


++++
=== `exportProjects`: [TT] Export Projects
++++
<div><div>
 Exports ecu.test projects and their attributes to a test management system like RQM or ALM.
</div></div>
<ul><li><code>exportConfigs</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'ExportPackageAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ExportPackageConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>exportPath : String</code>
</li>
<li><code>createNewPath : boolean</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ExportProjectAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ExportProjectConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>exportPath : String</code>
</li>
<li><code>createNewPath : boolean</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportPackageAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportPackageConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportPackageDirConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectArchiveConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>importConfigPath : String</code>
</li>
<li><code>replaceFiles : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>importMissingPackages : boolean</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
<li><code>tmProjectId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectDirConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
</ul></li>
</ul>


++++
=== `importPackages`: [TT] Import Packages
++++
<div><div>
 Imports ecu.test packages and their attributes from a test management system like RQM or ALM.
</div></div>
<ul><li><code>importConfigs</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'ExportPackageAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ExportPackageConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>exportPath : String</code>
</li>
<li><code>createNewPath : boolean</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ExportProjectAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ExportProjectConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>exportPath : String</code>
</li>
<li><code>createNewPath : boolean</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportPackageAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportPackageConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportPackageDirConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectArchiveConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>importConfigPath : String</code>
</li>
<li><code>replaceFiles : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>importMissingPackages : boolean</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
<li><code>tmProjectId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectDirConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
</ul></li>
</ul>


++++
=== `importProjects`: [TT] Import Projects
++++
<div><div>
 Imports ecu.test projects and their attributes from an archive or a test management system like RQM or ALM.
</div></div>
<ul><li><code>importConfigs</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'ExportPackageAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ExportPackageConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>exportPath : String</code>
</li>
<li><code>createNewPath : boolean</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ExportProjectAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ExportProjectConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>exportPath : String</code>
</li>
<li><code>createNewPath : boolean</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportPackageAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportPackageConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportPackageDirConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectArchiveConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>importConfigPath : String</code>
</li>
<li><code>replaceFiles : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectAttributeConfig'</code><div>
<ul><li><code>filePath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>importMissingPackages : boolean</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
<li><code>tmProjectId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ImportProjectDirConfig'</code><div>
<ul><li><code>tmsPath : String</code>
</li>
<li><code>importPath : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>timeout : String</code>
</li>
</ul></div></li>
</ul></li>
</ul>


++++
=== `publishUNIT`: [TT] Publish UNIT Reports
++++
<div><div>
 <p>Publishes the UNIT reports of all configured ecu.test packages or projects in this job.<br>
   These UNIT reports are generated automatically in this post-build step.</p><strong>Pipeline usage</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
publishUNIT(String toolName, double unstableThreshold, double failedThreshold) : void
            </pre>
   <pre>
publishUNIT(ETInstallation installation, double unstableThreshold, double failedThreshold, boolean allowMissing, boolean runOnFailed) : void
            </pre>
   <pre>
ETInstance.publishUNIT(double unstableThreshold, double failedThreshold, boolean allowMissing, boolean runOnFailed) : void
            </pre>
   <pre>
ETInstance.publishUNIT(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
publishUNIT('ecu.test', 10, 20)
            </pre>
   <pre>
def instance = ET.installation('ecu.test')
publishUNIT installation: instance.installation, unstableThreshold: 10, failedThreshold: 20
            </pre>
   <pre>
def instance = ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0')
instance.publishUNIT()
            </pre>
   <pre>
def instance = ET.newInstallation toolName: 'ecu.test', installPath: C:\\Program Files\\ECU-TEST 8.0'
instance.publishUNIT unstableThreshold: 10, failedThreshold: 20, allowMissing: true, runOnFailed: true
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>failedThreshold : double</code> (optional)
</li>
<li><code>installation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>home : String</code>
</li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>? extends hudson.tools.ToolProperty&lt;?&gt;</code></li>
</ul></li>
</ul></li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
<li><code>unstableThreshold : double</code> (optional)
</li>
</ul>


++++
=== `checkETLicense`: [TT] Check ecu.test License
++++
<div><div>
 <p>Check ecu.test license.</p><strong>Pipelines usage:</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
checkETLicense(String toolName) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
checkETLicense('ecu.test')
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>installation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>home : String</code>
</li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>? extends hudson.tools.ToolProperty&lt;?&gt;</code></li>
</ul></li>
</ul></li>
<li><code>timeout : String</code> (optional)
</li>
</ul>


++++
=== `publishGenerators`: [TT] Publish Generator Reports
++++
<div><div>
 <p>Publishes and generates reports by configuration of predefined and/or custom report generators.<br>
   These reports will be generated for all configured ecu.test packages or projects in this job.</p><strong>Pipeline usage</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
publishGenerators(String toolName, List&lt;ReportGeneratorConfig&gt; generators, List&lt;ReportGeneratorConfig&gt; customGenerators) : void
            </pre>
   <pre>
publishGenerators(ETInstallation installation, List&lt;ReportGeneratorConfig&gt; generators, List&lt;ReportGeneratorConfig&gt; customGenerators,
                  boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
ETInstance.publishGenerators(List&lt;ReportGeneratorConfig&gt; generators, List&lt;ReportGeneratorConfig&gt; customGenerators,
                             boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
ETInstance.publishGenerators(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
publishGenerators toolName: 'ecu.test', generators: [[name: 'JSON']]
            </pre>
   <pre>
def instance = ET.installation('ecu.test')
publishGenerators installation: instance.installation, generators: [[name: 'JSON']]
            </pre>
   <pre>
def instance = ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0')
instance.publishGenerators([[name: 'JSON']], [[name: 'Custom-JSON']])
            </pre>
   <pre>
def instance = ET.newInstallation toolName: 'ecu.test', installPath: C:\\Program Files\\ECU-TEST 8.0'
instance.publishGenerators generators: [[name: 'JSON']], customGenerators: [[name: 'Custom-JSON']], allowMissing: true, runOnFailed: true, archiving: true, keepAll: true
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>customGenerators</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>settings</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>usePersistedSettings : boolean</code>
</li>
</ul></li>
<li><code>generators</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>settings</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>usePersistedSettings : boolean</code>
</li>
</ul></li>
<li><code>installation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>home : String</code>
</li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>? extends hudson.tools.ToolProperty&lt;?&gt;</code></li>
</ul></li>
</ul></li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
</ul>


++++
=== `startET`: [TT] Start ecu.test
++++
<div><div>
 <p>Configure and start a preconfigured ecu.test installation.</p><strong>Pipeline usage</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
startET(String toolName) : void
            </pre>
   <pre>
startET(String toolName, String workspaceDir, String settingsDir, int timeout,
        boolean debugMode, boolean keepInstance, boolean updateUserLibs) : void
            </pre>
   <pre>
ETInstance.start() : void
            </pre>
   <pre>
ETInstance.start(String workspaceDir, String settingsDir, int timeout,
         boolean debugMode, boolean keepInstance, boolean updateUserLibs) : void
            </pre>
   <pre>
ETInstance.start(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
startET('ecu.test')
            </pre>
   <pre>
def instance = ET.installation('ecu.test')
startET installation: instance.installation, workspaceDir: 'C:\\Data'
            </pre>
   <pre>
def instance = ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0')
instance.start()
            </pre>
   <pre>
def instance = ET.newInstallation toolName: 'ecu.test', installPath: C:\\Program Files\\ECU-TEST 8.0'
instance.start workspaceDir: 'C:\\Data', settingsDir: 'C:\\Data', timeout: 120, debugMode: true, keepInstance: false, updateUserLibs: true
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>debugMode : boolean</code> (optional)
</li>
<li><code>installation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>home : String</code>
</li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>? extends hudson.tools.ToolProperty&lt;?&gt;</code></li>
</ul></li>
</ul></li>
<li><code>keepInstance : boolean</code> (optional)
</li>
<li><code>settingsDir : String</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
</li>
<li><code>updateUserLibs : boolean</code> (optional)
</li>
<li><code>workspaceDir : String</code> (optional)
</li>
</ul>


++++
=== `startTS`: [TT] Start Tool-Server
++++
<div><div>
 <p>Configure and start Tool-Server.</p><strong>Pipeline usage</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
startTS(String toolName) : void
            </pre>
   <pre>
startTS(String toolName, String toolLibsIniPath, int tcpPort, int timeout, boolean keepInstance) : void
            </pre>
   <pre>
ETInstance.startTS() : void
            </pre>
   <pre>
ETInstance.startTS(String toolLibsIniPath, int tcpPort, int timeout, boolean keepInstance) : void
            </pre>
   <pre>
ETInstance.startTS(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
startTS('ecu.test')
            </pre>
   <pre>
def instance = ET.installation('ecu.test')
startTS installation: instance.installation
            </pre>
   <pre>
def instance = ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0')
instance.startTS()
            </pre>
   <pre>
def instance = ET.newInstallation toolName: 'ecu.test', installPath: C:\\Program Files\\ECU-TEST 8.0'
instance.startTS toolLibsIniPath: C:\\ToolLibs.ini, tcpPort: 5017, timeout: 60, keepInstance: false
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>installation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>home : String</code>
</li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>? extends hudson.tools.ToolProperty&lt;?&gt;</code></li>
</ul></li>
</ul></li>
<li><code>keepInstance : boolean</code> (optional)
</li>
<li><code>tcpPort : String</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
</li>
<li><code>toolLibsIni : String</code> (optional)
</li>
</ul>


++++
=== `stopET`: [TT] Stop ecu.test
++++
<div><div>
 <p>Shutdown ecu.test.</p><strong>Pipelines usage:</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
stopET(String toolName) : void
            </pre>
   <pre>
stopET(String toolName, int timeout) : void
            </pre>
   <pre>
ETInstance.stop() : void
            </pre>
   <pre>
ETInstance.stop(int timeout) : void
            </pre>
   <pre>
ETInstance.stop(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
stopET('ecu.test')
            </pre>
   <pre>
def instance = ET.installation('ecu.test')
stopET installation: instance.installation
            </pre>
   <pre>
def instance = ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0')
instance.stop()
            </pre>
   <pre>
def instance = ET.newInstallation toolName: 'ecu.test', installPath: C:\\Program Files\\ECU-TEST 8.0'
instance.stop timeout: 60
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>installation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>home : String</code>
</li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>? extends hudson.tools.ToolProperty&lt;?&gt;</code></li>
</ul></li>
</ul></li>
<li><code>timeout : String</code> (optional)
</li>
</ul>


++++
=== `stopTS`: [TT] Stop Tool-Server
++++
<div><div>
 <p>Shutdown Tool-Server.</p><strong>Pipelines usage:</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
stopTS(String toolName) : void
            </pre>
   <pre>
stopTS(String toolName, int timeout) : void
            </pre>
   <pre>
ETInstance.stopTS() : void
            </pre>
   <pre>
ETInstance.stopTS(int timeout) : void
            </pre>
   <pre>
ETInstance.stopTS(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
stopTS('ecu.test')
            </pre>
   <pre>
def instance = ET.installation('ecu.test')
stopTS installation: instance.installation
            </pre>
   <pre>
def instance = ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0')
instance.stopTS()
            </pre>
   <pre>
def instance = ET.newInstallation toolName: 'ecu.test', installPath: C:\\Program Files\\ECU-TEST 8.0'
instance.stopTS timeout: 60
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>installation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>home : String</code>
</li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>? extends hudson.tools.ToolProperty&lt;?&gt;</code></li>
</ul></li>
</ul></li>
<li><code>timeout : String</code> (optional)
</li>
</ul>


++++
=== `publishTMS`: [TT] Publish to Test Management System
++++
<div><div>
 <p>Publishes the test results of all configured ecu.test projects in this job to a preconfigured test management system like RQM or ALM.</p><strong>Pipeline usage</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
publishTMS(String toolName, String credentialsId, int timeout) : void
            </pre>
   <pre>
publishTMS(ETInstallation installation, String credentialsId, int timeout,
           boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
ETInstance.publishTMS(String credentialsId, int timeout) : void
            </pre>
   <pre>
ETInstance.publishTMS(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
publishTMS('ecu.test')
            </pre>
   <pre>
def instance = ET.installation('ecu.test')
publishTMS installation: instance.installation, credentialsId: 'id', timeout: 120
            </pre>
   <pre>
def instance = ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0')
instance.publishTMS('id')
            </pre>
   <pre>
def instance = ET.newInstallation toolName: 'ecu.test', installPath: C:\\Program Files\\ECU-TEST 8.0'
instance.publishTMS credentialsId: 'id', timeout: 120, allowMissing: true, runOnFailed: true, archiving: true, keepAll: true
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>installation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>home : String</code>
</li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>? extends hudson.tools.ToolProperty&lt;?&gt;</code></li>
</ul></li>
</ul></li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
</li>
</ul>


++++
=== `publishTRF`: [TT] Publish TRF Reports
++++
<div><div>
 Publishes the TRF reports of all configured ecu.test packages or projects in this job.
</div></div>
<ul><li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
</ul>


++++
=== `testFolder`: [TT] Run Test Folder
++++
<div><div>
 Execute a test folder.
</div></div>
<ul><li><code>testFile : String</code>
</li>
<li><code>executionConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>timeout : String</code>
</li>
<li><code>stopOnError : boolean</code>
</li>
<li><code>checkTestFile : boolean</code>
</li>
<li><code>recordWarnings : boolean</code>
</li>
</ul></li>
<li><code>failFast : boolean</code> (optional)
</li>
<li><code>packageConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>runTest : boolean</code>
</li>
<li><code>runTraceAnalysis : boolean</code>
</li>
<li><code>parameters</code>
<div><div>
 Definition of ecu.test package parameters consisting of a unique name and a value.
 <br>
  Numeric value entries will be automatically converted to <i>Numeric</i> type in ecu.test.
 <br>
  For now only <i>Numeric</i> and <i>String</i> types are supported. 
 <br><b>Note:</b> From <b>ecu.test Version 2022.3</b> on, no invalid control characters are recognized anymore! In particular, this means that backslashes in Windows paths need to be escaped (<i>C:\\my\\path</i> instead of <i>C:\my\path</i>), such that 'Backslash - next character' is not interpreted as escape sequence, avoiding an error in ecu.test.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>outputParameters</code>
<div><div>
 Definition of ecu.test package output parameter consisting of a unique name.
 <br>
  Defined package output parameters are written to related environment variables after test execution has finished. 
 <br>
 The environment variable has the following syntax: <i>TT_TEST_RETVAL_&lt;VARIABLE NAME&gt;_&lt;INDEX&gt;</i>
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
</ul></li>
</ul></li>
<li><code>projectConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>execInCurrentPkgDir : boolean</code>
</li>
<li><code>filterExpression : String</code>
</li>
<li><code>jobExecMode</code>
<ul><li><b>Values:</b> <code>NO_EXECUTION</code>, <code>SEQUENTIAL_EXECUTION</code>, <code>PARALLEL_EXECUTION</code>, <code>SEPARATE_SEQUENTIAL_EXECUTION</code>, <code>SEPARATE_PARALLEL_EXECUTION</code>, <code>NO_TESTCASE_EXECUTION</code>, <code>TEST_GUIDE_EXECUTION</code></li></ul></li>
</ul></li>
<li><code>recursiveScan : boolean</code> (optional)
</li>
<li><code>scanMode</code> (optional)
<ul><li><b>Values:</b> <code>PACKAGES_ONLY</code>, <code>PROJECTS_ONLY</code>, <code>PACKAGES_AND_PROJECTS</code></li></ul></li>
<li><code>testConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>tbcFile : String</code>
</li>
<li><code>tcfFile : String</code>
</li>
<li><code>forceReload : boolean</code>
</li>
<li><code>loadOnly : boolean</code>
</li>
<li><code>keepConfig : boolean</code>
</li>
<li><code>constants</code>
<div><div>
 Definition of global constants consisting of an unique name and a value. Numeric value entries will be automatically converted to a <i>Python integer literal</i>, or to a <i>Python string literal</i>.
 <br>
  If the global constant does not exist it is created and saved instantly in the current test configuration.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
</ul></li>
</ul>


++++
=== `testPackage`: [TT] Run Package
++++
<div><div>
 Execute a ecu.test package.
</div></div>
<ul><li><code>testFile : String</code>
</li>
<li><code>executionConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>timeout : String</code>
</li>
<li><code>stopOnError : boolean</code>
</li>
<li><code>checkTestFile : boolean</code>
</li>
<li><code>recordWarnings : boolean</code>
</li>
</ul></li>
<li><code>packageConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>runTest : boolean</code>
</li>
<li><code>runTraceAnalysis : boolean</code>
</li>
<li><code>parameters</code>
<div><div>
 Definition of ecu.test package parameters consisting of a unique name and a value.
 <br>
  Numeric value entries will be automatically converted to <i>Numeric</i> type in ecu.test.
 <br>
  For now only <i>Numeric</i> and <i>String</i> types are supported. 
 <br><b>Note:</b> From <b>ecu.test Version 2022.3</b> on, no invalid control characters are recognized anymore! In particular, this means that backslashes in Windows paths need to be escaped (<i>C:\\my\\path</i> instead of <i>C:\my\path</i>), such that 'Backslash - next character' is not interpreted as escape sequence, avoiding an error in ecu.test.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>outputParameters</code>
<div><div>
 Definition of ecu.test package output parameter consisting of a unique name.
 <br>
  Defined package output parameters are written to related environment variables after test execution has finished. 
 <br>
 The environment variable has the following syntax: <i>TT_TEST_RETVAL_&lt;VARIABLE NAME&gt;_&lt;INDEX&gt;</i>
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
</ul></li>
</ul></li>
<li><code>testConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>tbcFile : String</code>
</li>
<li><code>tcfFile : String</code>
</li>
<li><code>forceReload : boolean</code>
</li>
<li><code>loadOnly : boolean</code>
</li>
<li><code>keepConfig : boolean</code>
</li>
<li><code>constants</code>
<div><div>
 Definition of global constants consisting of an unique name and a value. Numeric value entries will be automatically converted to a <i>Python integer literal</i>, or to a <i>Python string literal</i>.
 <br>
  If the global constant does not exist it is created and saved instantly in the current test configuration.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
</ul></li>
</ul>


++++
=== `testProject`: [TT] Run Project
++++
<div><div>
 Execute a ecu.test project.
</div></div>
<ul><li><code>testFile : String</code>
</li>
<li><code>executionConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>timeout : String</code>
</li>
<li><code>stopOnError : boolean</code>
</li>
<li><code>checkTestFile : boolean</code>
</li>
<li><code>recordWarnings : boolean</code>
</li>
</ul></li>
<li><code>projectConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>execInCurrentPkgDir : boolean</code>
</li>
<li><code>filterExpression : String</code>
</li>
<li><code>jobExecMode</code>
<ul><li><b>Values:</b> <code>NO_EXECUTION</code>, <code>SEQUENTIAL_EXECUTION</code>, <code>PARALLEL_EXECUTION</code>, <code>SEPARATE_SEQUENTIAL_EXECUTION</code>, <code>SEPARATE_PARALLEL_EXECUTION</code>, <code>NO_TESTCASE_EXECUTION</code>, <code>TEST_GUIDE_EXECUTION</code></li></ul></li>
</ul></li>
<li><code>testConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>tbcFile : String</code>
</li>
<li><code>tcfFile : String</code>
</li>
<li><code>forceReload : boolean</code>
</li>
<li><code>loadOnly : boolean</code>
</li>
<li><code>keepConfig : boolean</code>
</li>
<li><code>constants</code>
<div><div>
 Definition of global constants consisting of an unique name and a value. Numeric value entries will be automatically converted to a <i>Python integer literal</i>, or to a <i>Python string literal</i>.
 <br>
  If the global constant does not exist it is created and saved instantly in the current test configuration.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
</ul></li>
</ul>


++++
=== `publishTraceAnalysis`: [TT] Publish Trace Analysis
++++
<div><div>
 <p>Publishes the results of the trace analysis of all configured ecu.test packages or projects in this job.</p><strong>Pipeline usage</strong>
 <dl>
  Signatures: 
  <dd>
   <pre>
publishTraceAnalysis(String toolName, boolean mergeReports, boolean createReportDir, int timeout) : void
            </pre>
   <pre>
publishTraceAnalysis(ETInstallation installation, boolean mergeReports, boolean createReportDir, int timeout,
                     boolean allowMissing, boolean runOnFailed, boolean archiving, boolean keepAll) : void
            </pre>
   <pre>
ETInstance.publishTraceAnalysis(boolean mergeReports, boolean createReportDir, int timeout) : void
            </pre>
   <pre>
ETInstance.publishTraceAnalysis(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
publishTraceAnalysis('ecu.test')
            </pre>
   <pre>
def instance = ET.installation('ecu.test')
publishTraceAnalysis installation: instance.installation, mergeReports: true, createReportDir: false
            </pre>
   <pre>
def instance = ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0')
instance.publishTraceAnalysis()
            </pre>
   <pre>
def instance = ET.newInstallation toolName: 'ecu.test', installPath: C:\\Program Files\\ECU-TEST 8.0'
instance.publishTraceAnalysis mergeReports: true, createReportDir: false, timeout: 120, allowMissing: true, runOnFailed: true, archiving: true, keepAll: true
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>allowMissing : boolean</code> (optional)
</li>
<li><code>archiving : boolean</code> (optional)
</li>
<li><code>createReportDir : boolean</code> (optional)
</li>
<li><code>installation</code> (optional)
<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>home : String</code>
</li>
<li><code>properties</code>
<ul><li><b>Type:</b> <code>? extends hudson.tools.ToolProperty&lt;?&gt;</code></li>
</ul></li>
</ul></li>
<li><code>keepAll : boolean</code> (optional)
</li>
<li><code>mergeReports : boolean</code> (optional)
</li>
<li><code>runOnFailed : boolean</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
</li>
</ul>


++++
=== `getATXServer`: Get test.guide server by name
++++
<div><div>
 <p>Gets a test.guide server instance by name which must be present in the test.guide installations. Existing settings can be discovered and overridden afterwards.</p>
 <p>For providing secrets like upload authentication key or proxy settings utilize <a href="https://plugins.jenkins.io/credentials-binding/" rel="nofollow">credentials binding</a> and pass as masked environment variables.</p>
 <dl>
  Signatures: 
  <dd>
   <pre>
ATX.server(String atxName) : ATXServer
            </pre>
   <pre>
ATXServer.getSetting(String settingName) : ATXSetting
            </pre>
   <pre>
ATXServer.getSettings() : Map&lt;String, Object&gt;
            </pre>
   <pre>
ATXServer.overrideSetting(String settingName, Object settingValue) : void
            </pre>
   <pre>
ATXServer.overrideSettings(Map&lt;String, Object&gt; settings) : void
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
ATX.server('test.guide')
            </pre>
   <pre>
ATX.server atxName: 'test.guide'
            </pre>
   <pre>
def server ATX.server atxName: 'test.guide'
server.getSetting('serverURL')
server.getSettings()
server.overrideSetting('uploadToServer', true)
server.overrideSettings([serverURL: 'localhost', useHttpsConnection: true])
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>atxName : String</code>
</li>
</ul>


++++
=== `getETInstallation`: Get ecu.test installation by name
++++
<div><div>
 <p>Gets an ecu.test installation instance by name which must be present in Jenkins global tool configuration.</p>
 <dl>
  Signatures: 
  <dd>
   <pre>
ET.installation(String toolName) : ETInstance
            </pre>
   <pre>
ET.installation(Map&lt;String, Object&gt; installArgs) : ETInstance
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
ET.installation('ecu.test')
            </pre>
   <pre>
ET.installation toolName: 'ecu.test'
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
</ul>


++++
=== `isConfigStarted`: Check ecu.test configuration status
++++
<div><div>
 <p>Checks whether the currently selected ecu.test configurations are started.</p>
 <dl>
  Signatures: 
  <dd>
   <pre>
ETInstance.isConfigStarted() : boolean
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
def instance = ET.installation('ecu.test')
boolean isConfigStarted = instance.isConfigStarted()
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
</ul>


++++
=== `newATXServer`: Return new test.guide server
++++
<div><div>
 <p>Creates a new dynamic test.guide server instance which is only accessible during pipeline execution. test.guide name (<i>atxName</i>) and used ecu.test installation (<i>toolName</i>) are required whereas missing optional settings will be initialized to their default values.</p>
 <p>For providing secrets like upload authentication key or proxy settings utilize <a href="https://plugins.jenkins.io/credentials-binding/" rel="nofollow">credentials binding</a> and pass as masked environment variables.</p>
 <dl>
  Signatures: 
  <dd>
   <pre>
ATX.newServer(String atxName, String toolName) : ATXServer
            </pre>
   <pre>
ATX.newServer(String atxName, String toolName, String fullServerURL, boolean uploadToServer, String authKey, String projectId) : ATXServer
            </pre>
   <pre>
ATXServer.newServer(Map&lt;String, Object&gt; serverArgs) : ATXServer
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
ATX.newServer('test.guide', 'ecu.test')
            </pre>
   <pre>
ATX.newServer('test.guide', 'ecu.test', 'http://localhost:8085', false, '', '1')
            </pre>
   <pre>
ATX.newServer atxName: 'test.guide', toolName: 'ecu.test', fullServerURL: 'https://127.0.0.1:8086/context', uploadToServer: true
            </pre>
   <p>is equivalent to:</p>
   <pre>
def server =  ATX.newServer atxName: 'test.guide', toolName: 'ecu.test'
server.overrideSetting('serverURL', '127.0.0.1')
server.overrideSetting('serverPort', '8086')
server.overrideSetting('serverContextPath', 'context')
server.overrideSetting('useHttpsConnection', true)
server.overrideSetting('uploadToServer', true)
            </pre>
   <pre>
ATX.newServer atxName: 'test.guide', toolName: 'ecu.test', enableArchive: false
            </pre>
   <p>is equivalent to:</p>
   <pre>
def server =  ATX.newServer atxName: 'test.guide', toolName: 'ecu.test'
server.overrideSetting('enableArchive', false)
            </pre>
   <pre>
newATXServer atxName: 'test.guide', toolName: 'ecu.test',
    config: atxConfig(
        settings: [
            atxTextSetting(group: 'CONNECTION', name: 'serverURL', value: '127.0.0.1'),
            atxTextSetting(group: 'CONNECTION', name: 'serverLabel', value: ''),
            atxBooleanSetting(group: 'CONNECTION', name: 'useHttpsConnection', value: false),
            atxBooleanSetting(group: 'CONNECTION', name: 'ignoreSSL', value: false),
            atxTextSetting(group: 'CONNECTION', name: 'serverPort', value: '8085'),
            atxTextSetting(group: 'CONNECTION', name: 'serverContextPath', value: ''),
            atxSecretSetting(group: 'CONNECTION', name: 'httpProxy', value: ''),
            atxSecretSetting(group: 'CONNECTION', name: 'httpsProxy', value: ''),
            atxTextSetting(group: 'CONNECTION', name: 'projectId', value: '1'),
            atxSecretSetting(group: 'CONNECTION', name: 'uploadAuthenticationKey', value: ''),
            atxBooleanSetting(group: 'CONNECTION', name: 'useSettingsFromServer', value: false),
            atxBooleanSetting(group: 'UPLOAD', name: 'uploadAsync', value: true),
            atxBooleanSetting(group: 'UPLOAD', name: 'uploadToServer', value: false),
            atxBooleanSetting(group: 'UPLOAD', name: 'compressUpload', value: false),
            atxBooleanSetting(group: 'UPLOAD', name: 'cleanAfterSuccessUpload', value: true),
            atxBooleanSetting(group: 'UPLOAD', name: 'uploadOnlyProjectReport', value: false),
            atxBooleanSetting(group: 'ARCHIVE', name: 'enableArchive', value: true),
            atxBooleanSetting(group: 'ARCHIVE', name: 'archiveTrf', value: true),
            atxBooleanSetting(group: 'ARCHIVE', name: 'archivePkg', value: false),
            atxBooleanSetting(group: 'ARCHIVE', name: 'archiveTcf', value: false),
            atxBooleanSetting(group: 'ARCHIVE', name: 'archiveTbc', value: false),
            atxBooleanSetting(group: 'ARCHIVE', name: 'archiveMapping', value: false),
            atxTextSetting(group: 'ARCHIVE', name: 'archiveRecordings', value: 'False'),
            atxTextSetting(group: 'ARCHIVE', name: 'archiveRecordingsByAttributes', value: ''),
            atxBooleanSetting(group: 'ARCHIVE', name: 'archiveRecordingMetadata', value: true),
            atxBooleanSetting(group: 'ARCHIVE', name: 'archivePlots', value: true),
            atxTextSetting(group: 'ARCHIVE', name: 'archiveMiscFiles', value: ''),
            atxTextSetting(group: 'ARCHIVE', name: 'archiveMiscFilePrefix', value: ''),
            atxBooleanSetting(group: 'ARCHIVE', name: 'archiveMiscFilesOnlyInTestReportDir', value: true),
            atxTextSetting(group: 'ARCHIVE', name: 'archiveBy', value: 'NONE;SUCCESS;INCONCLUSIVE;FAILED;ERROR'),
            atxTextSetting(group: 'ATTRIBUTE', name: 'coveredAttributes', value: 'Testlevel;Designer;Execution Priority;Estimated Duration [min];'),
            atxTextSetting(group: 'ATTRIBUTE', name: 'attributeDelimiter', value: ''),
            atxBooleanSetting(group: 'ATTRIBUTE', name: 'mapIsTestCaseAsAttribute', value: true),
            atxBooleanSetting(group: 'ATTRIBUTE', name: 'mapTestCaseVersionAsAttribute', value: true),
            atxBooleanSetting(group: 'ATTRIBUTE', name: 'mapRootPrjAttrToPkgAttr', value: true),
            atxBooleanSetting(group: 'ATTRIBUTE', name: 'includePkgSVNRevision', value: true),
            atxBooleanSetting(group: 'ATTRIBUTE', name: 'mapSwkIdsAsAttribute', value: true),
            atxBooleanSetting(group: 'TBC_CONSTANTS', name: 'mapTbcToolAsConstant', value: true),
            atxBooleanSetting(group: 'TCF_CONSTANTS', name: 'mapTcfTesterAsConstant', value: false),
            atxBooleanSetting(group: 'TCF_CONSTANTS', name: 'mapTCFPropertyAsConstant', value: true),
            atxBooleanSetting(group: 'TCF_CONSTANTS', name: 'mapUserDefinedReportDataAsConstant', value: true),
            atxTextSetting(group: 'TCF_CONSTANTS', name: 'setConstants', value: ''),
            atxTextSetting(group: 'TCF_CONSTANTS', name: 'setAttributes', value: ''),
            atxBooleanSetting(group: 'SPECIAL', name: 'autoATXGeneratorUpdate', value: true),
            atxBooleanSetting(group: 'SPECIAL', name: 'includeToolIdentifier', value: false),
            atxBooleanSetting(group: 'SPECIAL', name: 'onlyIncludePkgTestCases', value: false),
            atxBooleanSetting(group: 'SPECIAL', name: 'overrideParamSetNameMapping', value: false),
            atxBooleanSetting(group: 'SPECIAL', name: 'mapProjectElementNameAsTestCaseName', value: false),
            atxTextSetting(group: 'SPECIAL', name: 'mapSubPackageAsTestCaseLevel', value: '0'),
            atxTextSetting(group: 'SPECIAL', name: 'captureSubPackageOnVerdict', value: ''),
            atxBooleanSetting(group: 'SPECIAL', name: 'mapSeparateProjectExecutionAsSingleTestplan', value: false),
            atxTextSetting(group: 'SPECIAL', name: 'mapAttributeAsConstant', value: ''),
            atxBooleanSetting(group: 'SPECIAL', name: 'mapTestReportPathAsConstant', value: false),
            atxBooleanSetting(group: 'SPECIAL', name: 'includeResourceAdapterInfo', value: true)],
        customSettings: [
            atxCustomBooleanSetting(name: 'customOption', checked: true),
            atxCustomTextSetting(name: 'customLabel', value: 'test')])
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>atxName : String</code>
</li>
<li><code>toolName : String</code>
</li>
<li><code>config</code>
<ul><b>Nested Object</b>
<li><code>settings</code>
<ul><li><b>Type:</b> <code>de.tracetronic.jenkins.plugins.ecutest.report.atx.installation.ATXSetting&lt;?&gt;</code></li>
</ul></li>
<li><code>customSettings</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>atxCustomBooleanSetting</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>checked : boolean</code>
</li>
</ul></div></li>
<li><code>atxCustomTextSetting</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
</ul></li>
</ul></li>
</ul>


++++
=== `newETInstallation`: Return new ecu.test installation
++++
<div><div>
 <p>Creates a new dynamic ecu.test installation instance which is only accessible during pipeline execution.</p>
 <dl>
  Signatures: 
  <dd>
   <pre>
ET.newInstallation(String toolName, String installPath) : ETInstance
            </pre>
   <pre>
ET.newInstallation(String toolName, String installPath, String progId, int timeout) : ETInstance
            </pre>
   <pre>
ET.newInstallation(Map&lt;String, Object&gt; installArgs) : ETInstance
            </pre>
  </dd>
 </dl>
 <dl>
  Examples: 
  <dd>
   <pre>
ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0')
            </pre>
   <pre>
ET.newInstallation('ecu.test', 'C:\\Program Files\\ECU-TEST 8.0', 'ECU-TEST.Application', 120)
            </pre>
   <pre>
ET.newInstallation toolName: 'ecu.test', installPath: 'C:\\Program Files\\ECU-TEST 8.0', progId: 'ECU-TEST.Application', timeout: 120
            </pre>
  </dd>
 </dl>
</div></div>
<ul><li><code>toolName : String</code>
</li>
<li><code>installPath : String</code>
</li>
<li><code>property</code>
<ul><b>Nested Object</b>
<li><code>progId : String</code>
</li>
<li><code>timeout : int</code>
</li>
<li><code>registerComServer : boolean</code>
</li>
</ul></li>
</ul>


++++
