= Eggplant Runner Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/eggplant-runner">Visit the Jenkins Plugins site</a>
++++


=== `eggplantRunner`: Eggplant Runner
++++
<ul><li><code>CACertPath : String</code> (optional)
</li>
<li><code>backoffFactor : String</code> (optional)
</li>
<li><code>clientId : String</code> (optional)
</li>
<li><code>clientSecret</code> (optional)
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>dryRun : boolean</code> (optional)
</li>
<li><code>eggplantRunnerPath : String</code> (optional)
</li>
<li><code>logLevel</code> (optional)
<ul><li><b>Values:</b> <code>INFO</code>, <code>DEBUG</code>, <code>WARNING</code>, <code>ERROR</code></li></ul></li>
<li><code>modelName : String</code> (optional)
</li>
<li><code>pollInterval : String</code> (optional)
</li>
<li><code>requestRetries : String</code> (optional)
</li>
<li><code>requestTimeout : String</code> (optional)
</li>
<li><code>serverURL : String</code> (optional)
</li>
<li><code>suiteName : String</code> (optional)
</li>
<li><code>testConfig</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'ModelBased'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>model : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ScriptBased'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>suite : String</code>
</li>
</ul></div></li>
<li><code>$class: 'TestConfigId'</code><div>
<ul><li><code>id : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>testConfigId : String</code> (optional)
</li>
<li><code>testConfigName : String</code> (optional)
</li>
<li><code>testEnvironmentTimeout : String</code> (optional)
</li>
<li><code>testResultPath : String</code> (optional)
</li>
</ul>


++++
