= Eiffel Broadcaster Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/eiffel-broadcaster">Visit the Jenkins Plugins site</a>
++++


=== `build`: Build a job
++++
<div><div>
 <p>Trigger a new build for a given job.</p>
 <p>Use the <a href="https://www.jenkins.io/redirect/pipeline-snippet-generator" rel="nofollow">Pipeline Snippet Generator</a> to generate a sample pipeline script for the build step.</p>
</div></div>
<ul><li><code>job : String</code>
<div><div>
 Name of a downstream job to build. May be another Pipeline job, but more commonly a freestyle or other project. Use a simple name if the job is in the same folder as this upstream Pipeline job; otherwise can use relative paths like <code>../sister-folder/downstream</code> or absolute paths like <code>/top-level-folder/nested-folder/downstream</code>.
</div></div>

</li>
<li><code>parameters</code> (optional)
<div><div>
 A list of parameters to pass to the downstream job. When passing secrets to downstream jobs, prefer credentials parameters over password parameters. See <a href="https://plugins.jenkins.io/pipeline-build-step/" rel="nofollow">the documentation</a> for details.
</div></div>

<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>agentParameter</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>base64File</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>base64 : String</code> (optional)
</li>
<li><code>file</code> (optional)
<ul><b>Nested Choice of Objects</b>
</ul></li>
</ul></div></li>
<li><code>booleanParam</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : boolean</code>
</li>
</ul></div></li>
<li><code>buildMasterRelease</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>applicationId : String</code>
</li>
<li><code>releaseNumber : String</code>
</li>
<li><code>showApplicationId : boolean</code>
</li>
<li><code>description : String</code>
</li>
</ul></div></li>
<li><code>checkboxParameter</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ClearCaseUcmBaselineParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>baseline : String</code>
</li>
<li><code>forceRmview : boolean</code>
</li>
</ul></div></li>
<li><code>credentials</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
<li><code>description : String</code>
</li>
</ul></div></li>
<li><code>$class: 'CvsTagsParamValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>tagName : String</code>
</li>
</ul></div></li>
<li><code>$class: 'DateParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
<li><code>description : String</code>
</li>
</ul></div></li>
<li><code>$class: 'DeployMetaDataParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>environmentKey : String</code>
</li>
<li><code>buildVersion : String</code>
</li>
<li><code>applicationName : String</code>
</li>
</ul></div></li>
<li><code>file</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>file</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
</ul></div></li>
<li><code>fileSystemList</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'GeneratorKeyValueParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>gitParameter</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>imageTag</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>imageName : String</code>
</li>
<li><code>imageTag : String</code>
</li>
</ul></div></li>
<li><code>$class: 'InheritableStringParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'JavaParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>description : String</code>
</li>
<li><code>selectedJDK : String</code>
</li>
</ul></div></li>
<li><code>$class: 'JiraIssueParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'JiraVersionParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>version : String</code>
</li>
</ul></div></li>
<li><code>jsonEditor</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'LabelParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>label : String</code>
</li>
<li><code>allNodesMatchingLabel : boolean</code>
</li>
<li><code>nodeEligibility</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'AllNodeEligibility'</code><div>
<ul></ul></div></li>
<li><code>$class: 'IgnoreOfflineNodeEligibility'</code><div>
<ul></ul></div></li>
<li><code>$class: 'IgnoreTempOfflineNodeEligibility'</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>listGitBranches</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ListSubversionTagsParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>tagsDir : String</code>
</li>
<li><code>tag : String</code>
</li>
</ul></div></li>
<li><code>$class: 'MatrixCombinationsParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>description : String</code>
</li>
<li><code>combinations : Array / List of String</code>
<ul></ul></li>
</ul></div></li>
<li><code>mavenMetadataVersions</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>description : String</code>
</li>
<li><code>groupId : String</code>
</li>
<li><code>artifactId : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>packaging : String</code>
</li>
<li><code>classifier : String</code>
</li>
<li><code>artifactUrl : String</code>
</li>
</ul></div></li>
<li><code>multiselect</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>selectedValues</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'NodeParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>labels : Array / List of String</code>
<ul></ul></li>
<li><code>nodeEligibility</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'AllNodeEligibility'</code><div>
<ul></ul></div></li>
<li><code>$class: 'IgnoreOfflineNodeEligibility'</code><div>
<ul></ul></div></li>
<li><code>$class: 'IgnoreTempOfflineNodeEligibility'</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'PackageChoiceParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>separator</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>separatorStyle : String</code>
</li>
<li><code>sectionHeader : String</code>
</li>
<li><code>sectionHeaderStyle : String</code>
</li>
</ul></div></li>
<li><code>$class: 'PatchParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>file</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
</ul></div></li>
<li><code>$class: 'PromotedBuildParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>runId : String</code>
</li>
<li><code>description : String</code>
</li>
</ul></div></li>
<li><code>$class: 'RandomStringParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>RESTList</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ReviewboardParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>run</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>runId : String</code>
</li>
<li><code>description : String</code>
</li>
</ul></div></li>
<li><code>$class: 'SauceParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>selectedBrowsers : String</code>
</li>
</ul></div></li>
<li><code>stashedFile</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>file</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
</ul></div></li>
<li><code>string</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>text</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'VBoxParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>nodes : Array / List of String</code>
<ul></ul></li>
<li><code>nodeDelimiter : String</code>
</li>
</ul></div></li>
<li><code>email</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>validatingString</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>validatingYamlParameter</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
<li><code>failedValidationMessage : String</code> (optional)
</li>
</ul></div></li>
<li><code>hidden</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'WReadonlyStringParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'WReadonlyTextParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>extendedChoice</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'com.michelin.cio.hudson.plugins.passwordparam.PasswordParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
<li><code>description : String</code>
</li>
</ul></div></li>
<li><code>$class: 'com.moded.extendedchoiceparameter.ExtendedChoiceParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>password</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>description : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>propagate : boolean</code> (optional)
<div><p>If enabled (default state), then the result of this step is that of the downstream build (e.g., success, unstable, failure, not built, or aborted). If disabled, then this step succeeds even if the downstream build is unstable, failed, etc.; use the <code>result</code> property of the return value as needed.</p></div>

</li>
<li><code>quietPeriod : int</code> (optional)
<div><div>
 Optional alternate quiet period (in seconds) before building. If unset, defaults to the quiet period defined by the downstream project (or finally to the system-wide default quiet period).
</div></div>

</li>
<li><code>wait : boolean</code> (optional)
<div><div>
 If true, the pipeline will wait for the result of the build step before jumping to the next step. Defaults to true.
</div></div>

</li>
<li><code>waitForStart : boolean</code> (optional)
<div><div>
 If true, the pipeline will wait for the downstream build to start before jumping to the next step. Defaults to false. Overrides the value of <code>wait</code>.
</div></div>

</li>
</ul>


++++
=== `buildWithEiffel`: Build a job with custom Eiffel activity name
++++
<div><div>
 <p>Extension step of <a href="https://www.jenkins.io/doc/pipeline/steps/pipeline-build-step/" rel="nofollow">Build Step</a> to build a job with a custom Eiffel activity name.</p>
</div></div>
<ul><li><code>job : String</code>
<div><div>
 Name of a downstream job to build. May be another Pipeline job, but more commonly a freestyle or other project. Use a simple name if the job is in the same folder as this upstream Pipeline job; otherwise can use relative paths like <code>../sister-folder/downstream</code> or absolute paths like <code>/top-level-folder/nested-folder/downstream</code>.
</div></div>

</li>
<li><code>activityName : String</code> (optional)
<div><div>
 The name of the Eiffel activity of the started build, expressed in the data.name field of the <a href="https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelActivityTriggeredEvent.md" rel="nofollow"> EiffelActivityTriggeredEvent </a> that's sent when the build is queued.
</div></div>

</li>
<li><code>parameters</code> (optional)
<div><div>
 A list of parameters to pass to the downstream job. When passing secrets to downstream jobs, prefer credentials parameters over password parameters. See <a href="https://plugins.jenkins.io/pipeline-build-step/" rel="nofollow">the documentation</a> for details.
</div></div>

<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>agentParameter</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>base64File</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>base64 : String</code> (optional)
</li>
<li><code>file</code> (optional)
<ul><b>Nested Choice of Objects</b>
</ul></li>
</ul></div></li>
<li><code>booleanParam</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : boolean</code>
</li>
</ul></div></li>
<li><code>buildMasterRelease</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>applicationId : String</code>
</li>
<li><code>releaseNumber : String</code>
</li>
<li><code>showApplicationId : boolean</code>
</li>
<li><code>description : String</code>
</li>
</ul></div></li>
<li><code>checkboxParameter</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ClearCaseUcmBaselineParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>baseline : String</code>
</li>
<li><code>forceRmview : boolean</code>
</li>
</ul></div></li>
<li><code>credentials</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
<li><code>description : String</code>
</li>
</ul></div></li>
<li><code>$class: 'CvsTagsParamValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>tagName : String</code>
</li>
</ul></div></li>
<li><code>$class: 'DateParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
<li><code>description : String</code>
</li>
</ul></div></li>
<li><code>$class: 'DeployMetaDataParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>environmentKey : String</code>
</li>
<li><code>buildVersion : String</code>
</li>
<li><code>applicationName : String</code>
</li>
</ul></div></li>
<li><code>file</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>file</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
</ul></div></li>
<li><code>fileSystemList</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'GeneratorKeyValueParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>gitParameter</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>imageTag</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>imageName : String</code>
</li>
<li><code>imageTag : String</code>
</li>
</ul></div></li>
<li><code>$class: 'InheritableStringParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'JavaParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>description : String</code>
</li>
<li><code>selectedJDK : String</code>
</li>
</ul></div></li>
<li><code>$class: 'JiraIssueParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'JiraVersionParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>version : String</code>
</li>
</ul></div></li>
<li><code>jsonEditor</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'LabelParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>label : String</code>
</li>
<li><code>allNodesMatchingLabel : boolean</code>
</li>
<li><code>nodeEligibility</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'AllNodeEligibility'</code><div>
<ul></ul></div></li>
<li><code>$class: 'IgnoreOfflineNodeEligibility'</code><div>
<ul></ul></div></li>
<li><code>$class: 'IgnoreTempOfflineNodeEligibility'</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>listGitBranches</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ListSubversionTagsParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>tagsDir : String</code>
</li>
<li><code>tag : String</code>
</li>
</ul></div></li>
<li><code>$class: 'MatrixCombinationsParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>description : String</code>
</li>
<li><code>combinations : Array / List of String</code>
<ul></ul></li>
</ul></div></li>
<li><code>mavenMetadataVersions</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>description : String</code>
</li>
<li><code>groupId : String</code>
</li>
<li><code>artifactId : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>packaging : String</code>
</li>
<li><code>classifier : String</code>
</li>
<li><code>artifactUrl : String</code>
</li>
</ul></div></li>
<li><code>multiselect</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>selectedValues</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'NodeParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>labels : Array / List of String</code>
<ul></ul></li>
<li><code>nodeEligibility</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'AllNodeEligibility'</code><div>
<ul></ul></div></li>
<li><code>$class: 'IgnoreOfflineNodeEligibility'</code><div>
<ul></ul></div></li>
<li><code>$class: 'IgnoreTempOfflineNodeEligibility'</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'PackageChoiceParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>separator</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>separatorStyle : String</code>
</li>
<li><code>sectionHeader : String</code>
</li>
<li><code>sectionHeaderStyle : String</code>
</li>
</ul></div></li>
<li><code>$class: 'PatchParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>file</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
</ul></div></li>
<li><code>$class: 'PromotedBuildParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>runId : String</code>
</li>
<li><code>description : String</code>
</li>
</ul></div></li>
<li><code>$class: 'RandomStringParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>RESTList</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ReviewboardParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>run</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>runId : String</code>
</li>
<li><code>description : String</code>
</li>
</ul></div></li>
<li><code>$class: 'SauceParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>selectedBrowsers : String</code>
</li>
</ul></div></li>
<li><code>stashedFile</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>file</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
</ul></div></li>
<li><code>string</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>text</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'VBoxParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>nodes : Array / List of String</code>
<ul></ul></li>
<li><code>nodeDelimiter : String</code>
</li>
</ul></div></li>
<li><code>email</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>validatingString</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>validatingYamlParameter</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
<li><code>failedValidationMessage : String</code> (optional)
</li>
</ul></div></li>
<li><code>hidden</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'WReadonlyStringParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'WReadonlyTextParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>extendedChoice</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'com.michelin.cio.hudson.plugins.passwordparam.PasswordParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
<li><code>description : String</code>
</li>
</ul></div></li>
<li><code>$class: 'com.moded.extendedchoiceparameter.ExtendedChoiceParameterValue'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>password</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>value</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>description : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>propagate : boolean</code> (optional)
<div><p>If enabled (default state), then the result of this step is that of the downstream build (e.g., success, unstable, failure, not built, or aborted). If disabled, then this step succeeds even if the downstream build is unstable, failed, etc.; use the <code>result</code> property of the return value as needed.</p></div>

</li>
<li><code>quietPeriod : int</code> (optional)
<div><div>
 Optional alternate quiet period (in seconds) before building. If unset, defaults to the quiet period defined by the downstream project (or finally to the system-wide default quiet period).
</div></div>

</li>
<li><code>wait : boolean</code> (optional)
<div><div>
 If true, the pipeline will wait for the result of the build step before jumping to the next step. Defaults to true.
</div></div>

</li>
<li><code>waitForStart : boolean</code> (optional)
<div><div>
 If true, the pipeline will wait for the downstream build to start before jumping to the next step. Defaults to false. Overrides the value of <code>wait</code>.
</div></div>

</li>
</ul>


++++
=== `createPackageURL`: Construct a package URL and return it as a string
++++
<div><div>
 Create a well-formed <a href="https://github.com/package-url/purl-spec" rel="nofollow">Package URL</a> (purl) based on a set of discrete input strings and return the result as a string. Package URLs are for example used in the data.identity member of <a href="https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelArtifactCreatedEvent.md" rel="nofollow"> EiffelArtifactCreatedEvent </a>.
</div></div>
<ul><li><code>name : String</code> (optional)
<div><div>
 The name of the package. Required. See the full <a href="https://github.com/package-url/purl-spec" rel="nofollow">Package URL specification</a> for all details and examples.
</div></div>

</li>
<li><code>namespace : String</code> (optional)
<div><div>
 A name prefix such as a Maven groupid, a Docker image owner, a GitHub user or organization. Optional and type-specific. See the full <a href="https://github.com/package-url/purl-spec" rel="nofollow">Package URL specification</a> for all details and examples.
</div></div>

</li>
<li><code>qualifiers</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>subpath : String</code> (optional)
<div><div>
 Extra subpath within a package, relative to the package root. Optional. See the full <a href="https://github.com/package-url/purl-spec" rel="nofollow">Package URL specification</a> for all details and examples.
</div></div>

</li>
<li><code>type : String</code> (optional)
<div><div>
 The package "type" or package "protocol" such as maven, npm, nuget, gem, pypi, etc. Required. See the full <a href="https://github.com/package-url/purl-spec" rel="nofollow">Package URL specification</a> for all details and examples.
</div></div>

</li>
<li><code>version : String</code> (optional)
<div><div>
 The version of the package. Optional. See the full <a href="https://github.com/package-url/purl-spec" rel="nofollow">Package URL specification</a> for all details and examples.
</div></div>

</li>
</ul>


++++
=== `publishEiffelArtifacts`: Publishes previously announced Eiffel artifacts
++++
<div><div>
 <p>Sends an <a href="https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelArtifactPublishedEvent.md" rel="nofollow"> EiffelArtifactPublishedEvent </a> for each <a href="https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelArtifactCreatedEvent.md" rel="nofollow"> EiffelArtifactCreatedEvent </a> that has been recorded in the build using a sendEiffelEvent step with the publishArtifact argument enabled. Optionally also EiffelArtifactCreatedEvent events recorded in a file in the workspace.</p>
 <p>This requires that each EiffelArtifactPublishedEvent has at least one file defined in its data.fileInformation array and that each relative file path in data.fileInformation.name matches a Jenkins artifact in the build. Because of the latter requirement it's normally used after an <a href="https://www.jenkins.io/doc/pipeline/steps/core/#code-archiveartifacts-code-archive-the-artifacts" rel="nofollow"> archiveArtifacts </a> step.</p>
 <p>The EiffelArtifactPublishedEvent will have two links; one ARTIFACT link to the EiffelArtifactCreatedEvent and one CONTEXT link to the parent build's EiffelActivityTriggeredEvent.</p>
</div></div>
<ul><li><code>artifactEventFiles : String</code> (optional)
<div><div>
 If non-empty, specifies an Ant-style filename pattern that selects one or more files containing <a href="https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelArtifactCreatedEvent.md" rel="nofollow"> EiffelArtifactCreatedEvent </a> JSON objects (one per line). Each such event will result in an <a href="https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelArtifactPublishedEvent.md" rel="nofollow"> EiffelArtifactPublishedEvent </a>.
</div></div>

</li>
</ul>


++++
=== `sendEiffelEvent`: Send an Eiffel event
++++
<div><div>
 <p>Sends an Eiffel event expressed as a Groovy map. This map is passed in the event argument.</p>
 <p>By default the event passed by the user will be decorated with a CONTEXT link to the current build's <a href="https://github.com/eiffel-community/eiffel/blob/master/eiffel-vocabulary/EiffelActivityTriggeredEvent.md" rel="nofollow"> EiffelActivityTriggeredEvent </a>. Optionally a CAUSE link can be created instead or the link can be omitted entirely.</p>
 <p>This step returns immediately as soon as the event has been validated and put on the internal outbound queue. The actual delivery of the event to the broker might not have happened at the time of the return.</p>
</div></div>
<ul><li><code>event</code>
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>activityLinkType</code> (optional)
<ul><li><b>Values:</b> <code>ACTIVITY_EXECUTION</code>, <code>ARTIFACT</code>, <code>BASE</code>, <code>CAUSE</code>, <code>CHANGE</code>, <code>COMPOSITION</code>, <code>CONFIGURATION</code>, <code>CONTEXT</code>, <code>DERESOLVED_ISSUE</code>, <code>ELEMENT</code>, <code>ENVIRONMENT</code>, <code>FAILED_ISSUE</code>, <code>FLOW_CONTEXT</code>, <code>INCONCLUSIVE_ISSUE</code>, <code>IUT</code>, <code>MODIFIED_ANNOUNCEMENT</code>, <code>ORIGINAL_TRIGGER</code>, <code>PARTIALLY_RESOLVED_ISSUE</code>, <code>PRECURSOR</code>, <code>PREVIOUS_ACTIVITY_EXECUTION</code>, <code>PREVIOUS_VERSION</code>, <code>RESOLVED_ISSUE</code>, <code>REUSED_ARTIFACT</code>, <code>RUNTIME_ENVIRONMENT</code>, <code>SUB_CONFIDENCE_LEVEL</code>, <code>SUBJECT</code>, <code>SUCCESSFUL_ISSUE</code>, <code>TERC</code>, <code>TEST_CASE_EXECUTION</code>, <code>TEST_SUITE_EXECUTION</code>, <code>VERIFICATION_BASIS</code></li></ul></li>
<li><code>linkToActivity : boolean</code> (optional)
</li>
<li><code>publishArtifact : boolean</code> (optional)
</li>
<li><code>signatureCredentialsId : String</code> (optional)
</li>
<li><code>signatureHashAlgorithm : String</code> (optional)
</li>
</ul>


++++
