= Embeddable Build Status Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/embeddable-build-status">Visit the Jenkins Plugins site</a>
++++


=== `addEmbeddableBadgeConfiguration`: Add an Embeddable Badge Configuration
++++
<div><p>Additional embeddable build status configurations can be created for a Jenkins Pipeline. Those embeddable build status configurations can be displayed in the same locations as the default embeddable build status configuration. For example, if a Pipeline defined a build status configuration named <code>win32build</code>, that configuration can be accessed by appending <code>config=win32build</code> as one of the embeddable build status URL parameters.</p>
<p>Refer to the <a href="https://plugins.jenkins.io/embeddable-build-status/#plugin-content-pipeline-dsl" rel="nofollow">Embeddable build status</a> documentation for more details.</p></div>
<ul><li><code>id : String</code>
<div>The identifier that will be assigned to this embeddable build status configuration. The identifier is passed as the value of <code>config</code> in the embeddable build status URL parameter. For example, if the identifier value was <code>win32build</code> then the URL parameter would be <code>config=win32build</code>.</div>

</li>
<li><code>animatedOverlayColor : String</code> (optional)
<div>You can override the color using the following valid color values: 
<ul>
 <li>one of the values: red, brightgreen, green, yellowgreen, yellow, orange, lightgrey, blue</li>
 <li>a valid hexadecimal HTML RGB color without the hashtag (e.g. FFAABB).</li>
 <li>any valid <a href="https://www.december.com/html/spec/colorsvg.html" rel="nofollow">SVG color name</a></li>
</ul></div>

</li>
<li><code>color : String</code> (optional)
<div>You can override the color using the following valid color values: 
<ul>
 <li>one of the values: red, brightgreen, green, yellowgreen, yellow, orange, lightgrey, blue</li>
 <li>a valid hexadecimal HTML RGB color without the hashtag (e.g. FFAABB).</li>
 <li>any valid <a href="https://www.december.com/html/spec/colorsvg.html" rel="nofollow">SVG color name</a></li>
</ul></div>

</li>
<li><code>link : String</code> (optional)
<div>The link that will be opened when the embeddable build status badge is clicked.</div>

</li>
<li><code>status : String</code> (optional)
<div>Text that describes the build status, usually the result of the build.</div>

</li>
<li><code>subject : String</code> (optional)
<div>The text placed on the left side of the embeddable build status. The subject is "build" by default.</div>

</li>
</ul>


++++
