= Snow Commander Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/embotics-vcommander">Visit the Jenkins Plugins site</a>
++++


=== `vCommander`: Commander Services
++++
<ul><li><code>action</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'VCommanderRequestNewServiceAction'</code><div>
<ul><li><code>payload : String</code>
<div><div>
 When you lookup a service that exists in the Commander Service Catalog, the request configured for that service is displayed in this field as a JSON payload. For some service requests you may edit configuration parameters. If you edit a service request's configuration parameters, you must use valid values for each configuration parameter and proper JSON formatting. Parameter validation is not performed. 
 <br>
 <br>
  You may also use environment variables in the text. Regular Jenkins syntax will be used to resolve the variables - either $xyz, ${xyz} or ${a.b} but not $a.b, while ignoring "$".
</div></div>

</li>
<li><code>sync : boolean</code>
<div><div>
 Commander actions may take a few minutes to complete. If you want Jenkins to wait for the service to complete (that is, perform the action synchronously), you can add timeout and checking intervals in the current build step. You can also add them in a separate, following wait step.
</div></div>

</li>
<li><code>timeout : long</code>
</li>
<li><code>polling : long</code>
</li>
</ul></div></li>
<li><code>$class: 'VCommanderRunWorkflowAction'</code><div>
<ul><li><code>targetType : String</code>
<div><div>
 Select the target type to run the workflow on. The target type and name must be a unique in Commander. 
 <br>
 <br>
  You may also use environment variables in the text. Variables must resolve to valid target types. Regular Jenkins syntax will be used to resolve the variables - either $xyz, ${xyz} or ${a.b} but not $a.b, while ignoring "$".
</div></div>

</li>
<li><code>targetName : String</code>
<div><div>
 Enter the name of the target to run the workflow on. The target type and name must be a unique in Commander. 
 <br>
 <br>
  You may also use environment variables in the text. Regular Jenkins syntax will be used to resolve the variables - either $xyz, ${xyz} or ${a.b} but not $a.b, while ignoring "$".
</div></div>

</li>
<li><code>workflowName : String</code>
</li>
<li><code>sync : boolean</code>
<div><div>
 Commander actions may take a few minutes to complete. If you want Jenkins to wait for the action to complete (that is, perform the action synchronously), you can add timeout and checking intervals in the current build step or you add them a separate wait step.
</div></div>

</li>
<li><code>timeout : long</code>
</li>
<li><code>polling : long</code>
</li>
</ul></div></li>
<li><code>$class: 'VCommanderWaitForRequestNewServiceAction'</code><div>
<ul><li><code>requestId : String</code>
<div><div>
 If you want the build job to wait for the completion of a service request, enter the service request's ID. Typically the wait will be for an asynchronous request made earlier in the same build. In that case, the build step will generate the environment variable VCOMMANDER_REQUESTED_SERVICE_ID, which can be used here. 
 <br>
 <br>
  You may also use environment variables in the text. Regular Jenkins syntax will be used to resolve the variables - either $xyz, ${xyz} or ${a.b} but not $a.b, while ignoring "$".
</div></div>

</li>
<li><code>timeout : long</code>
</li>
<li><code>polling : long</code>
</li>
</ul></div></li>
<li><code>$class: 'VCommanderWaitForRunWorkflowAction'</code><div>
<ul><li><code>taskId : String</code>
<div><div>
 If you want the build job to wait for the completion of a command workflow task, enter that task's ID. Typically the wait will be for an asynchronous command workflow task made earlier in the same build. In that case, the build step will generate the environment variable VCOMMANDER_WORKFLOW_TASK_ID, which can be used here. 
 <br>
 <br>
  You may also use environment variables in the text. Regular Jenkins syntax will be used to resolve the variables - either $xyz, ${xyz} or ${a.b} but not $a.b, while ignoring "$".
</div></div>

</li>
<li><code>timeout : long</code>
</li>
<li><code>polling : long</code>
</li>
</ul></div></li>
</ul></li>
</ul>


++++
