= File Parameter Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/file-parameters">Visit the Jenkins Plugins site</a>
++++


=== `withFileParameter`: Bind file parameter
++++
<div><div>
 Binds an (alternative) file parameter to a local file near the workspace for convenience. Parameters can be retrieved in other ways, depending on the specific parameter type.
</div>
<div>
 <p>How to use it in a declarative pipeline:</p>
 <pre>pipeline {
  agent any
  parameters {
    base64File 'THEFILE'
  }
  stages {
    stage('Example') {
      steps {
        withFileParameter('THEFILE') {
          sh 'cat $THEFILE'
        }
      }
    }
  }
}
  </pre>
</div>
<div>
 By default, there will be an error if there is no parameter for the build but you can ignore this error using the parameter attribute <code>allowNoFile</code>. In this case your Pipeline must take into account the possibility that the file does not exist: 
 <pre>pipeline {
  agent any
  parameters {
    base64File 'THEFILE'
  }
  stages {
    stage('Example') {
      steps {
        withFileParameter(name:'THEFILE', allowNoFile: true) {
          sh 'if [ -f "$THEFILE" ]; then cat $THEFILE; fi'
        }
      }
    }
  }
}
  </pre>
</div></div>
<ul><li><code>name : String</code>
<div><div>
 Name of the parameter. Within the wrapper, this environment variable will be bound to the path of a temporary file.
</div></div>

</li>
<li><code>allowNoFile : boolean</code> (optional)
<div><div>
 By default, an error will be thrown if there is no file uploaded to the build. With this option, the build will proceed, and the environment variable will simply not be defined.
</div></div>

</li>
</ul>


++++
