= File Operations Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/file-operations">Visit the Jenkins Plugins site</a>
++++


=== `fileOperations`: File Operations
++++
<ul><li><code>fileOperations</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>fileCopyOperation</code><div>
<ul><li><code>includes : String</code>
<div><div>
 Files included to copy, this supports ant-style file pattern ex: target/*/final*.xml
</div></div>

</li>
<li><code>excludes : String</code>
<div><div>
 Files excluded from copying, this supports ant-style file pattern ex: target/*/final*.xml
</div></div>

</li>
<li><code>targetLocation : String</code>
<div><div>
 Destination folder location to copy the files. Base directory is workspace.
</div></div>

</li>
<li><code>flattenFiles : boolean</code>
<div><div>
 If selected, files are copied directly to the target location without preserving source file sub-directory structure.
</div></div>

</li>
<li><code>renameFiles : boolean</code>
<div><div>
 By default, the file name of the source file is preserved. When flattening files, this can cause problems if files of the same name exist in multiple source sub-directories. Selecting this option allows the output file name to be manipulated to avoid file name clashes.
</div></div>

</li>
<li><code>sourceCaptureExpression : String</code>
<div><div>
 Java-style regular expression that is run against the full path of each matching source file. This should be used to capture parts of the path that will be used in the target name expression to make each file name unique across all subdirectories.
</div></div>

</li>
<li><code>targetNameExpression : String</code>
<div><div>
 An expression that provides the desired target file name. This can reference variables captured in the source capture expression by using $1, $2 etc.
</div></div>

</li>
</ul></div></li>
<li><code>fileCreateOperation</code><div>
<ul><li><code>fileName : String</code>
<div><div>
 Path and Name of the file to be created in workspace.
</div></div>

</li>
<li><code>fileContent : String</code>
<div><div>
 File content to be created, use environment variables where needed.
</div></div>

</li>
</ul></div></li>
<li><code>fileDeleteOperation</code><div>
<ul><li><code>includes : String</code>
<div><div>
 Files included to delete, this supports ant-style file pattern ex: target/*/final*.xml
</div></div>

</li>
<li><code>excludes : String</code>
<div><div>
 Files excluded from deleting, this supports ant-style file pattern ex: target/*/final*.xml
</div></div>

</li>
</ul></div></li>
<li><code>fileDownloadOperation</code><div>
<ul><li><code>url : String</code>
<div><div>
 Url of the file to download.
</div></div>

</li>
<li><code>userName : String</code>
</li>
<li><code>password : String</code>
</li>
<li><code>targetLocation : String</code>
<div><div>
 Destination location to download the file. Base directory is workspace.
</div></div>

</li>
<li><code>targetFileName : String</code>
</li>
<li><code>proxyHost : String</code>
</li>
<li><code>proxyPort : String</code>
</li>
</ul></div></li>
<li><code>fileJoinOperation</code><div>
<ul><li><code>sourceFile : String</code>
<div><div>
 Source file path to copy the content.
</div></div>

</li>
<li><code>targetFile : String</code>
<div><div>
 Target file path to append the content from source file.
</div></div>

</li>
</ul></div></li>
<li><code>filePropertiesToJsonOperation</code><div>
<ul><li><code>sourceFile : String</code>
<div><div>
 Source file path of properties.
</div></div>

</li>
<li><code>targetFile : String</code>
<div><div>
 Target file path to create or update with json data.
</div></div>

</li>
</ul></div></li>
<li><code>fileRenameOperation</code><div>
<ul><li><code>source : String</code>
<div><div>
 File to be renamed.
</div></div>

</li>
<li><code>destination : String</code>
<div><div>
 Destination file location to rename. Base directory is workspace.
</div></div>

</li>
</ul></div></li>
<li><code>fileTransformOperation</code><div>
<ul><li><code>includes : String</code>
<div><div>
 Files included to copy, this supports ant-style file pattern ex: target/*/final*.xml
</div></div>

</li>
<li><code>excludes : String</code>
<div><div>
 Files excluded from copying, this supports ant-style file pattern ex: target/*/final*.xml
</div></div>

</li>
</ul></div></li>
<li><code>fileUnTarOperation</code><div>
<ul><li><code>filePath : String</code>
<div><div>
 Source tar file location.
</div></div>

</li>
<li><code>targetLocation : String</code>
<div><div>
 Destination folder location to untar the files. Base directory is workspace.
</div></div>

</li>
<li><code>isGZIP : boolean</code>
</li>
</ul></div></li>
<li><code>fileUnZipOperation</code><div>
<ul><li><code>filePath : String</code>
<div><div>
 Source zip file location.
</div></div>

</li>
<li><code>targetLocation : String</code>
<div><div>
 Destination folder location to unzip the files. Base directory is workspace.
</div></div>

</li>
</ul></div></li>
<li><code>fileZipOperation</code><div>
<ul><li><code>folderPath : String</code>
<div><div>
 Path of the file or folder to create a zip file for, relative to the workspace directory.
</div></div>

</li>
<li><code>outputFolderPath : String</code>
<div><div>
 Path to a target directory for the zip file, relative to the workspace directory. Defaults to workspace directory if not defined.
</div></div>

</li>
</ul></div></li>
<li><code>folderCopyOperation</code><div>
<ul><li><code>sourceFolderPath : String</code>
<div><div>
 Folder to be copied.
</div></div>

</li>
<li><code>destinationFolderPath : String</code>
<div><div>
 Destination folder location to copy the files. Base directory is workspace.
</div></div>

</li>
</ul></div></li>
<li><code>folderCreateOperation</code><div>
<ul><li><code>folderPath : String</code>
<div><div>
 Path and Name of the folder to be created in workspace.
</div></div>

</li>
</ul></div></li>
<li><code>folderDeleteOperation</code><div>
<ul><li><code>folderPath : String</code>
<div><div>
 Path and Name of the folder to be deleted in workspace.
</div></div>

</li>
</ul></div></li>
<li><code>folderRenameOperation</code><div>
<ul><li><code>source : String</code>
<div><div>
 Folder to be renamed.
</div></div>

</li>
<li><code>destination : String</code>
<div><div>
 Destination folder name to rename. Base directory is workspace.
</div></div>

</li>
</ul></div></li>
</ul></li>
</ul>


++++
