= Fortify
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/fortify">Visit the Jenkins Plugins site</a>
++++


=== `fortifyClean`: Run Fortify SCA clean
++++
<ul><li><code>buildID : String</code>
</li>
<li><code>addJVMOptions : String</code> (optional)
</li>
<li><code>debug : boolean</code> (optional)
</li>
<li><code>logFile : String</code> (optional)
</li>
<li><code>maxHeap : String</code> (optional)
</li>
<li><code>verbose : boolean</code> (optional)
</li>
</ul>


++++
=== `fortifyRemoteAnalysis`: Upload a project for remote Fortify SCA analysis
++++
<ul><li><code>remoteAnalysisProjectType</code>
<ul><b>Nested Choice of Objects</b>
<li><code>fortifyGradle</code><div>
<ul><li><code>buildFile : String</code> (optional)
</li>
<li><code>includeTests : boolean</code> (optional)
</li>
<li><code>skipBuild : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyMSBuild</code><div>
<ul><li><code>dotnetProject : String</code> (optional)
</li>
<li><code>excludeDisabledProjects : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyMaven</code><div>
<ul><li><code>buildFile : String</code> (optional)
</li>
<li><code>includeTests : boolean</code> (optional)
</li>
<li><code>skipBuild : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyOther</code><div>
<ul></ul></div></li>
<li><code>fortifyPHP</code><div>
<ul><li><code>phpVersion : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyPython</code><div>
<ul><li><code>pythonRequirementsFile : String</code> (optional)
</li>
<li><code>pythonVersion : String</code> (optional)
</li>
<li><code>pythonVirtualEnv : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>remoteOptionalConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>customRulepacks : String</code> (optional)
</li>
<li><code>filterFile : String</code> (optional)
</li>
<li><code>notifyEmail : String</code> (optional)
</li>
<li><code>scanOptions : String</code> (optional)
</li>
<li><code>sensorPoolUUID : String</code> (optional)
</li>
</ul></li>
<li><code>scanOptions : String</code> (optional)
</li>
<li><code>uploadSSC</code> (optional)
<ul><b>Nested Object</b>
<li><code>appName : String</code>
</li>
<li><code>appVersion : String</code>
</li>
<li><code>filterSet : String</code> (optional)
</li>
<li><code>pollingInterval : String</code> (optional)
</li>
<li><code>searchCondition : String</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
</li>
</ul></li>
</ul>


++++
=== `fortifyRemoteArguments`: Set options for remote Fortify SCA analysis
++++
<ul><li><code>scanOptions : String</code> (optional)
</li>
<li><code>transOptions : String</code> (optional)
</li>
</ul>


++++
=== `fortifyRemoteScan`: Upload a translated project for remote scan
++++
<ul><li><code>buildID : String</code>
</li>
<li><code>remoteOptionalConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>customRulepacks : String</code> (optional)
</li>
<li><code>filterFile : String</code> (optional)
</li>
<li><code>notifyEmail : String</code> (optional)
</li>
<li><code>scanOptions : String</code> (optional)
</li>
<li><code>sensorPoolUUID : String</code> (optional)
</li>
</ul></li>
<li><code>scanOptions : String</code> (optional)
</li>
<li><code>uploadSSC</code> (optional)
<ul><b>Nested Object</b>
<li><code>appName : String</code>
</li>
<li><code>appVersion : String</code>
</li>
<li><code>filterSet : String</code> (optional)
</li>
<li><code>pollingInterval : String</code> (optional)
</li>
<li><code>searchCondition : String</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
</li>
</ul></li>
</ul>


++++
=== `fortifyScan`: Run Fortify SCA scan
++++
<ul><li><code>buildID : String</code>
</li>
<li><code>addJVMOptions : String</code> (optional)
</li>
<li><code>addOptions : String</code> (optional)
</li>
<li><code>customRulepacks : String</code> (optional)
</li>
<li><code>debug : boolean</code> (optional)
</li>
<li><code>logFile : String</code> (optional)
</li>
<li><code>maxHeap : String</code> (optional)
</li>
<li><code>resultsFile : String</code> (optional)
</li>
<li><code>verbose : boolean</code> (optional)
</li>
</ul>


++++
=== `fortifyTranslate`: Run Fortify SCA translation
++++
<ul><li><code>buildID : String</code>
</li>
<li><code>projectScanType</code>
<ul><b>Nested Choice of Objects</b>
<li><code>fortifyAdvanced</code><div>
<ul><li><code>advOptions : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyDevenv</code><div>
<ul><li><code>dotnetAddOptions : String</code> (optional)
</li>
<li><code>dotnetProject : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyDotnetSrc</code><div>
<ul><li><code>dotnetAddOptions : String</code> (optional)
</li>
<li><code>dotnetFrameworkVersion : String</code> (optional)
</li>
<li><code>dotnetLibdirs : String</code> (optional)
</li>
<li><code>dotnetSrcFiles : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyGradle</code><div>
<ul><li><code>gradleInstallationName : String</code> (optional)
</li>
<li><code>gradleOptions : String</code> (optional)
</li>
<li><code>gradleTasks : String</code> (optional)
</li>
<li><code>useWrapper : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyJava</code><div>
<ul><li><code>javaAddOptions : String</code> (optional)
</li>
<li><code>javaClasspath : String</code> (optional)
</li>
<li><code>javaSrcFiles : String</code> (optional)
</li>
<li><code>javaVersion : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyMaven3</code><div>
<ul><li><code>mavenInstallationName : String</code> (optional)
</li>
<li><code>mavenOptions : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyMSBuild</code><div>
<ul><li><code>dotnetAddOptions : String</code> (optional)
</li>
<li><code>dotnetProject : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyOther</code><div>
<ul><li><code>otherIncludesList : String</code> (optional)
</li>
<li><code>otherOptions : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>addJVMOptions : String</code> (optional)
</li>
<li><code>debug : boolean</code> (optional)
</li>
<li><code>excludeList : String</code> (optional)
</li>
<li><code>logFile : String</code> (optional)
</li>
<li><code>maxHeap : String</code> (optional)
</li>
<li><code>verbose : boolean</code> (optional)
</li>
</ul>


++++
=== `fortifyUpdate`: Update Fortify Security Content
++++
<ul><li><code>updateServerURL : String</code> (optional)
</li>
<li><code>locale : String</code> (optional)
</li>
<li><code>acceptKey : boolean</code> (optional)
</li>
<li><code>proxyPassword : String</code> (optional)
</li>
<li><code>proxyURL : String</code> (optional)
</li>
<li><code>proxyUsername : String</code> (optional)
</li>
<li><code>useProxy : boolean</code> (optional)
</li>
</ul>


++++
=== `fortifyUpload`: Upload Fortify scan results to SSC
++++
<ul><li><code>appName : String</code>
</li>
<li><code>appVersion : String</code>
</li>
<li><code>failureCriteria : String</code> (optional)
</li>
<li><code>filterSet : String</code> (optional)
</li>
<li><code>pollingInterval : String</code> (optional)
</li>
<li><code>resultsFile : String</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
</li>
</ul>


++++
=== `fortifyRemoteArguments`: Set options for remote Fortify SCA analysis
++++
<ul><li><code>scanOptions : String</code> (optional)
</li>
<li><code>transOptions : String</code> (optional)
</li>
</ul>


++++
=== `fortifyRemoteScan`: Upload a translated project for remote scan
++++
<ul><li><code>buildID : String</code>
</li>
<li><code>remoteOptionalConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>customRulepacks : String</code> (optional)
</li>
<li><code>filterFile : String</code> (optional)
</li>
<li><code>notifyEmail : String</code> (optional)
</li>
<li><code>scanOptions : String</code> (optional)
</li>
<li><code>sensorPoolUUID : String</code> (optional)
</li>
</ul></li>
<li><code>scanOptions : String</code> (optional)
</li>
<li><code>uploadSSC</code> (optional)
<ul><b>Nested Object</b>
<li><code>appName : String</code>
</li>
<li><code>appVersion : String</code>
</li>
<li><code>filterSet : String</code> (optional)
</li>
<li><code>pollingInterval : String</code> (optional)
</li>
<li><code>searchCondition : String</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
</li>
</ul></li>
</ul>


++++
=== `fortifyRemoteAnalysis`: Upload a project for remote Fortify SCA analysis
++++
<ul><li><code>remoteAnalysisProjectType</code>
<ul><b>Nested Choice of Objects</b>
<li><code>fortifyGradle</code><div>
<ul><li><code>buildFile : String</code> (optional)
</li>
<li><code>includeTests : boolean</code> (optional)
</li>
<li><code>skipBuild : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyMSBuild</code><div>
<ul><li><code>dotnetProject : String</code> (optional)
</li>
<li><code>excludeDisabledProjects : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyMaven</code><div>
<ul><li><code>buildFile : String</code> (optional)
</li>
<li><code>includeTests : boolean</code> (optional)
</li>
<li><code>skipBuild : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyOther</code><div>
<ul></ul></div></li>
<li><code>fortifyPHP</code><div>
<ul><li><code>phpVersion : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyPython</code><div>
<ul><li><code>pythonRequirementsFile : String</code> (optional)
</li>
<li><code>pythonVersion : String</code> (optional)
</li>
<li><code>pythonVirtualEnv : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>remoteOptionalConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>customRulepacks : String</code> (optional)
</li>
<li><code>filterFile : String</code> (optional)
</li>
<li><code>notifyEmail : String</code> (optional)
</li>
<li><code>scanOptions : String</code> (optional)
</li>
<li><code>sensorPoolUUID : String</code> (optional)
</li>
</ul></li>
<li><code>scanOptions : String</code> (optional)
</li>
<li><code>uploadSSC</code> (optional)
<ul><b>Nested Object</b>
<li><code>appName : String</code>
</li>
<li><code>appVersion : String</code>
</li>
<li><code>filterSet : String</code> (optional)
</li>
<li><code>pollingInterval : String</code> (optional)
</li>
<li><code>searchCondition : String</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
</li>
</ul></li>
</ul>


++++
=== `fortifyClean`: Run Fortify SCA clean
++++
<ul><li><code>buildID : String</code>
</li>
<li><code>addJVMOptions : String</code> (optional)
</li>
<li><code>debug : boolean</code> (optional)
</li>
<li><code>logFile : String</code> (optional)
</li>
<li><code>maxHeap : String</code> (optional)
</li>
<li><code>verbose : boolean</code> (optional)
</li>
</ul>


++++
=== `fortifyScan`: Run Fortify SCA scan
++++
<ul><li><code>buildID : String</code>
</li>
<li><code>addJVMOptions : String</code> (optional)
</li>
<li><code>addOptions : String</code> (optional)
</li>
<li><code>customRulepacks : String</code> (optional)
</li>
<li><code>debug : boolean</code> (optional)
</li>
<li><code>logFile : String</code> (optional)
</li>
<li><code>maxHeap : String</code> (optional)
</li>
<li><code>resultsFile : String</code> (optional)
</li>
<li><code>verbose : boolean</code> (optional)
</li>
</ul>


++++
=== `fortifyTranslate`: Run Fortify SCA translation
++++
<ul><li><code>buildID : String</code>
</li>
<li><code>projectScanType</code>
<ul><b>Nested Choice of Objects</b>
<li><code>fortifyAdvanced</code><div>
<ul><li><code>advOptions : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyDevenv</code><div>
<ul><li><code>dotnetAddOptions : String</code> (optional)
</li>
<li><code>dotnetProject : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyDotnetSrc</code><div>
<ul><li><code>dotnetAddOptions : String</code> (optional)
</li>
<li><code>dotnetFrameworkVersion : String</code> (optional)
</li>
<li><code>dotnetLibdirs : String</code> (optional)
</li>
<li><code>dotnetSrcFiles : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyGradle</code><div>
<ul><li><code>gradleInstallationName : String</code> (optional)
</li>
<li><code>gradleOptions : String</code> (optional)
</li>
<li><code>gradleTasks : String</code> (optional)
</li>
<li><code>useWrapper : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyJava</code><div>
<ul><li><code>javaAddOptions : String</code> (optional)
</li>
<li><code>javaClasspath : String</code> (optional)
</li>
<li><code>javaSrcFiles : String</code> (optional)
</li>
<li><code>javaVersion : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyMaven3</code><div>
<ul><li><code>mavenInstallationName : String</code> (optional)
</li>
<li><code>mavenOptions : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyMSBuild</code><div>
<ul><li><code>dotnetAddOptions : String</code> (optional)
</li>
<li><code>dotnetProject : String</code> (optional)
</li>
</ul></div></li>
<li><code>fortifyOther</code><div>
<ul><li><code>otherIncludesList : String</code> (optional)
</li>
<li><code>otherOptions : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>addJVMOptions : String</code> (optional)
</li>
<li><code>debug : boolean</code> (optional)
</li>
<li><code>excludeList : String</code> (optional)
</li>
<li><code>logFile : String</code> (optional)
</li>
<li><code>maxHeap : String</code> (optional)
</li>
<li><code>verbose : boolean</code> (optional)
</li>
</ul>


++++
=== `fortifyUpdate`: Update Fortify Security Content
++++
<ul><li><code>updateServerURL : String</code> (optional)
</li>
<li><code>locale : String</code> (optional)
</li>
<li><code>acceptKey : boolean</code> (optional)
</li>
<li><code>proxyPassword : String</code> (optional)
</li>
<li><code>proxyURL : String</code> (optional)
</li>
<li><code>proxyUsername : String</code> (optional)
</li>
<li><code>useProxy : boolean</code> (optional)
</li>
</ul>


++++
=== `fortifyUpload`: Upload Fortify scan results to SSC
++++
<ul><li><code>appName : String</code>
</li>
<li><code>appVersion : String</code>
</li>
<li><code>failureCriteria : String</code> (optional)
</li>
<li><code>filterSet : String</code> (optional)
</li>
<li><code>pollingInterval : String</code> (optional)
</li>
<li><code>resultsFile : String</code> (optional)
</li>
<li><code>timeout : String</code> (optional)
</li>
</ul>


++++
