= Fortify on Demand
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/fortify-on-demand-uploader">Visit the Jenkins Plugins site</a>
++++


=== `fodDynamicAssessment`: Run Fortify on Demand Upload
++++
<ul><li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationType : String</code> (optional)
</li>
<li><code>assessmentType : String</code> (optional)
</li>
<li><code>assessmentTypeId : String</code> (optional)
</li>
<li><code>attributes : String</code> (optional)
</li>
<li><code>auditPreference : String</code> (optional)
</li>
<li><code>businessCriticality : String</code> (optional)
</li>
<li><code>enableRedundantPageDetection : boolean</code> (optional)
</li>
<li><code>entitlementFrequency : String</code> (optional)
</li>
<li><code>entitlementId : String</code> (optional)
</li>
<li><code>envFacing : String</code> (optional)
</li>
<li><code>excludedUrls : String</code> (optional)
</li>
<li><code>graphQLFileId : String</code> (optional)
</li>
<li><code>graphQLFilePath : String</code> (optional)
</li>
<li><code>graphQLSchemeType : String</code> (optional)
</li>
<li><code>graphQLUrl : String</code> (optional)
</li>
<li><code>graphQlApiHost : String</code> (optional)
</li>
<li><code>graphQlApiServicePath : String</code> (optional)
</li>
<li><code>graphQlRadioSource : String</code> (optional)
</li>
<li><code>grpcApiHost : String</code> (optional)
</li>
<li><code>grpcApiServicePath : String</code> (optional)
</li>
<li><code>grpcFileId : String</code> (optional)
</li>
<li><code>grpcFilePath : String</code> (optional)
</li>
<li><code>grpcSchemeType : String</code> (optional)
</li>
<li><code>inProgressBuildResultType : String</code> (optional)
</li>
<li><code>inProgressScanActionType : String</code> (optional)
</li>
<li><code>loginMacroFileId : String</code> (optional)
</li>
<li><code>loginMacroFilePath : String</code> (optional)
</li>
<li><code>loginMacroPrimaryPassword : String</code> (optional)
</li>
<li><code>loginMacroPrimaryUserName : String</code> (optional)
</li>
<li><code>loginMacroSecondaryPassword : String</code> (optional)
</li>
<li><code>loginMacroSecondaryUsername : String</code> (optional)
</li>
<li><code>networkAuthPassword : String</code> (optional)
</li>
<li><code>networkAuthType : String</code> (optional)
</li>
<li><code>networkAuthUserName : String</code> (optional)
</li>
<li><code>openApiFileId : String</code> (optional)
</li>
<li><code>openApiFilePath : String</code> (optional)
</li>
<li><code>openApiKey : String</code> (optional)
</li>
<li><code>openApiRadioSource : String</code> (optional)
</li>
<li><code>openApiUrl : String</code> (optional)
</li>
<li><code>overrideGlobalConfig : boolean</code> (optional)
</li>
<li><code>owner : int</code> (optional)
</li>
<li><code>personalAccessToken : String</code> (optional)
</li>
<li><code>postmanFileId : String</code> (optional)
</li>
<li><code>postmanFilePath : String</code> (optional)
</li>
<li><code>purchaseEntitlements : boolean</code> (optional)
</li>
<li><code>releaseId : String</code> (optional)
</li>
<li><code>releaseName : String</code> (optional)
</li>
<li><code>remediationScanPreferenceType : String</code> (optional)
</li>
<li><code>requestFalsePositiveRemoval : boolean</code> (optional)
</li>
<li><code>requestLoginMacroFileCreation : boolean</code> (optional)
</li>
<li><code>scanPolicy : String</code> (optional)
</li>
<li><code>scanScope : boolean</code> (optional)
</li>
<li><code>scanTimeBox : String</code> (optional)
</li>
<li><code>scanType : String</code> (optional)
</li>
<li><code>sdlcStatus : String</code> (optional)
</li>
<li><code>selectedApiType : String</code> (optional)
</li>
<li><code>selectedDynamicTimeZone : String</code> (optional)
</li>
<li><code>tenantId : String</code> (optional)
</li>
<li><code>timeBoxChecked : boolean</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
<li><code>webSiteUrl : String</code> (optional)
</li>
<li><code>workflowMacroFilePath : String</code> (optional)
</li>
<li><code>workflowMacroHosts : String</code> (optional)
</li>
<li><code>workflowMacroId : String</code> (optional)
</li>
</ul>


++++
=== `fodPollResults`: Poll Fortify on Demand for Results
++++
<ul><li><code>releaseId : String</code>
</li>
<li><code>bsiToken : String</code>
</li>
<li><code>pollingInterval : int</code>
</li>
<li><code>clientId : String</code> (optional)
</li>
<li><code>clientSecret : String</code> (optional)
</li>
<li><code>overrideGlobalConfig : boolean</code> (optional)
</li>
<li><code>personalAccessToken : String</code> (optional)
</li>
<li><code>policyFailureBuildResultPreference : int</code> (optional)
</li>
<li><code>tenantId : String</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
</ul>


++++
=== `fodStaticAssessment`: Run Fortify on Demand Upload
++++
<ul><li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationType : String</code> (optional)
</li>
<li><code>assessmentType : String</code> (optional)
</li>
<li><code>attributes : String</code> (optional)
</li>
<li><code>auditPreference : String</code> (optional)
</li>
<li><code>bsiToken : String</code> (optional)
</li>
<li><code>businessCriticality : String</code> (optional)
</li>
<li><code>entitlementId : String</code> (optional)
</li>
<li><code>entitlementPreference : String</code> (optional)
</li>
<li><code>frequencyId : String</code> (optional)
</li>
<li><code>inProgressBuildResultType : String</code> (optional)
</li>
<li><code>inProgressScanActionType : String</code> (optional)
</li>
<li><code>isMicroservice : boolean</code> (optional)
</li>
<li><code>languageLevel : String</code> (optional)
</li>
<li><code>microserviceName : String</code> (optional)
</li>
<li><code>openSourceScan : String</code> (optional)
</li>
<li><code>overrideGlobalConfig : boolean</code> (optional)
</li>
<li><code>owner : int</code> (optional)
</li>
<li><code>personalAccessToken : String</code> (optional)
</li>
<li><code>purchaseEntitlements : boolean</code> (optional)
</li>
<li><code>releaseId : String</code> (optional)
</li>
<li><code>releaseName : String</code> (optional)
</li>
<li><code>remediationScanPreferenceType : String</code> (optional)
</li>
<li><code>scanCentral : String</code> (optional)
</li>
<li><code>scanCentralBuildCommand : String</code> (optional)
</li>
<li><code>scanCentralBuildFile : String</code> (optional)
</li>
<li><code>scanCentralBuildToolVersion : String</code> (optional)
</li>
<li><code>scanCentralExcludeFiles : String</code> (optional)
</li>
<li><code>scanCentralIncludeTests : String</code> (optional)
</li>
<li><code>scanCentralRequirementFile : String</code> (optional)
</li>
<li><code>scanCentralSkipBuild : String</code> (optional)
</li>
<li><code>scanCentralVirtualEnv : String</code> (optional)
</li>
<li><code>sdlcStatus : String</code> (optional)
</li>
<li><code>srcLocation : String</code> (optional)
</li>
<li><code>technologyStack : String</code> (optional)
</li>
<li><code>tenantId : String</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'FortifyDastFreeStyleBuildStep'])`: Fortify on Demand Dynamic Assessment
++++
<ul><li><code>overrideGlobalConfig : boolean</code>
</li>
<li><code>username : String</code>
</li>
<li><code>personalAccessToken : String</code>
</li>
<li><code>tenantId : String</code>
</li>
<li><code>webSiteUrl : String</code>
</li>
<li><code>dastEnv : String</code>
</li>
<li><code>scanTimeBox : String</code>
</li>
<li><code>excludedUrls : String</code>
</li>
<li><code>scanPolicy : String</code>
</li>
<li><code>scanScope : boolean</code>
</li>
<li><code>selectedScanType : String</code>
</li>
<li><code>selectedDynamicTimeZone : String</code>
</li>
<li><code>webSiteNetworkAuthSettingEnabled : boolean</code>
</li>
<li><code>enableRedundantPageDetection : boolean</code>
</li>
<li><code>networkAuthUserName : String</code>
</li>
<li><code>loginMacroId : String</code>
</li>
<li><code>workflowMacroId : String</code>
</li>
<li><code>workflowMacroHosts : String</code>
</li>
<li><code>networkAuthPassword : String</code>
</li>
<li><code>userSelectedApplication : String</code>
</li>
<li><code>userSelectedRelease : String</code>
</li>
<li><code>assessmentTypeId : String</code>
</li>
<li><code>entitlementId : String</code>
</li>
<li><code>entitlementFrequencyType : String</code>
</li>
<li><code>userSelectedEntitlement : String</code>
</li>
<li><code>selectedNetworkAuthType : String</code>
</li>
<li><code>timeBoxChecked : boolean</code>
</li>
<li><code>selectedApiType : String</code>
</li>
<li><code>openApiRadioSource : String</code>
</li>
<li><code>openApiFileId : String</code>
</li>
<li><code>openApiUrl : String</code>
</li>
<li><code>openApiKey : String</code>
</li>
<li><code>postmanFileId : String</code>
</li>
<li><code>graphQlRadioSource : String</code>
</li>
<li><code>graphQLFileId : String</code>
</li>
<li><code>graphQLUrl : String</code>
</li>
<li><code>graphQLSchemeType : String</code>
</li>
<li><code>graphQlApiHost : String</code>
</li>
<li><code>graphQlApiServicePath : String</code>
</li>
<li><code>grpcFileId : String</code>
</li>
<li><code>grpcSchemeType : String</code>
</li>
<li><code>grpcApiHost : String</code>
</li>
<li><code>grpcApiServicePath : String</code>
</li>
<li><code>openApiFilePath : String</code>
</li>
<li><code>postmanFilePath : String</code>
</li>
<li><code>graphQlFilePath : String</code>
</li>
<li><code>grpcFilePath : String</code>
</li>
<li><code>requestLoginMacroFileCreation : boolean</code>
</li>
<li><code>loginMacroPrimaryUserName : String</code>
</li>
<li><code>loginMacroPrimaryPassword : String</code>
</li>
<li><code>loginMacroSecondaryUsername : String</code>
</li>
<li><code>loginMacroSecondaryPassword : String</code>
</li>
<li><code>requestFalsePositiveRemoval : boolean</code>
</li>
</ul>


++++
=== `fodDynamicAssessment`: Run Fortify on Demand Upload
++++
<ul><li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationType : String</code> (optional)
</li>
<li><code>assessmentType : String</code> (optional)
</li>
<li><code>assessmentTypeId : String</code> (optional)
</li>
<li><code>attributes : String</code> (optional)
</li>
<li><code>auditPreference : String</code> (optional)
</li>
<li><code>businessCriticality : String</code> (optional)
</li>
<li><code>enableRedundantPageDetection : boolean</code> (optional)
</li>
<li><code>entitlementFrequency : String</code> (optional)
</li>
<li><code>entitlementId : String</code> (optional)
</li>
<li><code>envFacing : String</code> (optional)
</li>
<li><code>excludedUrls : String</code> (optional)
</li>
<li><code>graphQLFileId : String</code> (optional)
</li>
<li><code>graphQLFilePath : String</code> (optional)
</li>
<li><code>graphQLSchemeType : String</code> (optional)
</li>
<li><code>graphQLUrl : String</code> (optional)
</li>
<li><code>graphQlApiHost : String</code> (optional)
</li>
<li><code>graphQlApiServicePath : String</code> (optional)
</li>
<li><code>graphQlRadioSource : String</code> (optional)
</li>
<li><code>grpcApiHost : String</code> (optional)
</li>
<li><code>grpcApiServicePath : String</code> (optional)
</li>
<li><code>grpcFileId : String</code> (optional)
</li>
<li><code>grpcFilePath : String</code> (optional)
</li>
<li><code>grpcSchemeType : String</code> (optional)
</li>
<li><code>inProgressBuildResultType : String</code> (optional)
</li>
<li><code>inProgressScanActionType : String</code> (optional)
</li>
<li><code>loginMacroFileId : String</code> (optional)
</li>
<li><code>loginMacroFilePath : String</code> (optional)
</li>
<li><code>loginMacroPrimaryPassword : String</code> (optional)
</li>
<li><code>loginMacroPrimaryUserName : String</code> (optional)
</li>
<li><code>loginMacroSecondaryPassword : String</code> (optional)
</li>
<li><code>loginMacroSecondaryUsername : String</code> (optional)
</li>
<li><code>networkAuthPassword : String</code> (optional)
</li>
<li><code>networkAuthType : String</code> (optional)
</li>
<li><code>networkAuthUserName : String</code> (optional)
</li>
<li><code>openApiFileId : String</code> (optional)
</li>
<li><code>openApiFilePath : String</code> (optional)
</li>
<li><code>openApiKey : String</code> (optional)
</li>
<li><code>openApiRadioSource : String</code> (optional)
</li>
<li><code>openApiUrl : String</code> (optional)
</li>
<li><code>overrideGlobalConfig : boolean</code> (optional)
</li>
<li><code>owner : int</code> (optional)
</li>
<li><code>personalAccessToken : String</code> (optional)
</li>
<li><code>postmanFileId : String</code> (optional)
</li>
<li><code>postmanFilePath : String</code> (optional)
</li>
<li><code>purchaseEntitlements : boolean</code> (optional)
</li>
<li><code>releaseId : String</code> (optional)
</li>
<li><code>releaseName : String</code> (optional)
</li>
<li><code>remediationScanPreferenceType : String</code> (optional)
</li>
<li><code>requestFalsePositiveRemoval : boolean</code> (optional)
</li>
<li><code>requestLoginMacroFileCreation : boolean</code> (optional)
</li>
<li><code>scanPolicy : String</code> (optional)
</li>
<li><code>scanScope : boolean</code> (optional)
</li>
<li><code>scanTimeBox : String</code> (optional)
</li>
<li><code>scanType : String</code> (optional)
</li>
<li><code>sdlcStatus : String</code> (optional)
</li>
<li><code>selectedApiType : String</code> (optional)
</li>
<li><code>selectedDynamicTimeZone : String</code> (optional)
</li>
<li><code>tenantId : String</code> (optional)
</li>
<li><code>timeBoxChecked : boolean</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
<li><code>webSiteUrl : String</code> (optional)
</li>
<li><code>workflowMacroFilePath : String</code> (optional)
</li>
<li><code>workflowMacroHosts : String</code> (optional)
</li>
<li><code>workflowMacroId : String</code> (optional)
</li>
</ul>


++++
=== `fodPollResults`: Poll Fortify on Demand for Results
++++
<ul><li><code>releaseId : String</code>
</li>
<li><code>bsiToken : String</code>
</li>
<li><code>pollingInterval : int</code>
</li>
<li><code>clientId : String</code> (optional)
</li>
<li><code>clientSecret : String</code> (optional)
</li>
<li><code>overrideGlobalConfig : boolean</code> (optional)
</li>
<li><code>personalAccessToken : String</code> (optional)
</li>
<li><code>policyFailureBuildResultPreference : int</code> (optional)
</li>
<li><code>tenantId : String</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
</ul>


++++
=== `fodStaticAssessment`: Run Fortify on Demand Upload
++++
<ul><li><code>applicationName : String</code> (optional)
</li>
<li><code>applicationType : String</code> (optional)
</li>
<li><code>assessmentType : String</code> (optional)
</li>
<li><code>attributes : String</code> (optional)
</li>
<li><code>auditPreference : String</code> (optional)
</li>
<li><code>bsiToken : String</code> (optional)
</li>
<li><code>businessCriticality : String</code> (optional)
</li>
<li><code>entitlementId : String</code> (optional)
</li>
<li><code>entitlementPreference : String</code> (optional)
</li>
<li><code>frequencyId : String</code> (optional)
</li>
<li><code>inProgressBuildResultType : String</code> (optional)
</li>
<li><code>inProgressScanActionType : String</code> (optional)
</li>
<li><code>isMicroservice : boolean</code> (optional)
</li>
<li><code>languageLevel : String</code> (optional)
</li>
<li><code>microserviceName : String</code> (optional)
</li>
<li><code>openSourceScan : String</code> (optional)
</li>
<li><code>overrideGlobalConfig : boolean</code> (optional)
</li>
<li><code>owner : int</code> (optional)
</li>
<li><code>personalAccessToken : String</code> (optional)
</li>
<li><code>purchaseEntitlements : boolean</code> (optional)
</li>
<li><code>releaseId : String</code> (optional)
</li>
<li><code>releaseName : String</code> (optional)
</li>
<li><code>remediationScanPreferenceType : String</code> (optional)
</li>
<li><code>scanCentral : String</code> (optional)
</li>
<li><code>scanCentralBuildCommand : String</code> (optional)
</li>
<li><code>scanCentralBuildFile : String</code> (optional)
</li>
<li><code>scanCentralBuildToolVersion : String</code> (optional)
</li>
<li><code>scanCentralExcludeFiles : String</code> (optional)
</li>
<li><code>scanCentralIncludeTests : String</code> (optional)
</li>
<li><code>scanCentralRequirementFile : String</code> (optional)
</li>
<li><code>scanCentralSkipBuild : String</code> (optional)
</li>
<li><code>scanCentralVirtualEnv : String</code> (optional)
</li>
<li><code>sdlcStatus : String</code> (optional)
</li>
<li><code>srcLocation : String</code> (optional)
</li>
<li><code>technologyStack : String</code> (optional)
</li>
<li><code>tenantId : String</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'PollingBuildStep'])`: Poll Fortify on Demand for Results
++++
<ul><li><code>releaseId : String</code>
</li>
<li><code>bsiToken : String</code>
</li>
<li><code>overrideGlobalConfig : boolean</code>
</li>
<li><code>pollingInterval : int</code>
</li>
<li><code>policyFailureBuildResultPreference : int</code>
</li>
<li><code>clientId : String</code>
</li>
<li><code>clientSecret : String</code>
</li>
<li><code>username : String</code>
</li>
<li><code>personalAccessToken : String</code>
</li>
<li><code>tenantId : String</code>
</li>
</ul>


++++
=== `step([$class: 'StaticAssessmentBuildStep'])`: Fortify on Demand Static Assessment
++++
<ul><li><code>releaseId : String</code>
</li>
<li><code>bsiToken : String</code>
</li>
<li><code>overrideGlobalConfig : boolean</code>
</li>
<li><code>username : String</code>
</li>
<li><code>personalAccessToken : String</code>
</li>
<li><code>tenantId : String</code>
</li>
<li><code>purchaseEntitlements : boolean</code>
</li>
<li><code>entitlementPreference : String</code>
</li>
<li><code>userSelectedAssessmentType : String</code>
</li>
<li><code>userSelectedEntitlementId : String</code>
</li>
<li><code>userSelectedFrequencyType : String</code>
</li>
<li><code>userSelectedTechnologyStack : String</code>
</li>
<li><code>userSelectedLanguageLevel : String</code>
</li>
<li><code>sonatypeEnabled : boolean</code>
</li>
<li><code>userSelectedAuditPreference : String</code>
</li>
<li><code>srcLocation : String</code>
</li>
<li><code>remediationScanPreferenceType : String</code>
</li>
<li><code>inProgressScanActionType : String</code>
</li>
<li><code>inProgressBuildResultType : String</code>
</li>
<li><code>selectedReleaseType : String</code>
</li>
<li><code>userSelectedApplication : String</code>
</li>
<li><code>userSelectedMicroservice : String</code>
</li>
<li><code>userSelectedRelease : String</code>
</li>
<li><code>selectedScanCentralBuildType : String</code>
</li>
<li><code>scanCentralIncludeTests : boolean</code>
</li>
<li><code>scanCentralSkipBuild : boolean</code>
</li>
<li><code>scanCentralBuildCommand : String</code>
</li>
<li><code>scanCentralBuildFile : String</code>
</li>
<li><code>scanCentralExcludeFiles : String</code>
</li>
<li><code>scanCentralBuildToolVersion : String</code>
</li>
<li><code>scanCentralVirtualEnv : String</code>
</li>
<li><code>scanCentralRequirementFile : String</code>
</li>
</ul>


++++
