= Gatling Check Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/gatling-check">Visit the Jenkins Plugins site</a>
++++


=== `gatlingCheck`: GatlingCheckStep
++++
<ul><li><code>metrics : Array / List of String</code>
<ul></ul></li>
</ul>


++++
=== `step([$class: 'GatlingChecker'])`: Gatling Checker
++++
<ul><li><code>metrics</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'GlobalOKRateMetric'</code><div>
<ul><li><code>rate : String</code>
</li>
</ul></div></li>
<li><code>$class: 'GlobalQpsMetric'</code><div>
<ul><li><code>qps : String</code>
</li>
</ul></div></li>
<li><code>$class: 'GlobalResponseTime95Metric'</code><div>
<ul><li><code>responseTime : String</code>
</li>
</ul></div></li>
<li><code>$class: 'GlobalResponseTime99Metric'</code><div>
<ul><li><code>responseTime : String</code>
</li>
</ul></div></li>
<li><code>$class: 'GlobalResponseTimeAvgMetric'</code><div>
<ul><li><code>responseTime : String</code>
</li>
</ul></div></li>
<li><code>$class: 'RequestOKRateMetric'</code><div>
<ul><li><code>requestName : String</code>
</li>
<li><code>rate : String</code>
</li>
</ul></div></li>
<li><code>$class: 'RequestQpsMetric'</code><div>
<ul><li><code>requestName : String</code>
</li>
<li><code>qps : String</code>
</li>
</ul></div></li>
<li><code>$class: 'RequestResponseTime95Metric'</code><div>
<ul><li><code>requestName : String</code>
</li>
<li><code>responseTime : String</code>
</li>
</ul></div></li>
<li><code>$class: 'RequestResponseTime99Metric'</code><div>
<ul><li><code>requestName : String</code>
</li>
<li><code>responseTime : String</code>
</li>
</ul></div></li>
<li><code>$class: 'RequestResponseTimeAvgMetric'</code><div>
<ul><li><code>requestName : String</code>
</li>
<li><code>responseTime : String</code>
</li>
</ul></div></li>
</ul></li>
</ul>


++++
