= Gerrit Trigger
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/gerrit-trigger">Visit the Jenkins Plugins site</a>
++++


=== `setGerritReview`: Set Gerrit review
++++
<div><div>
 <p>Allows influencing how the build results are reported back to Gerrit when the build finishes. All input values are optional. If the step occurs multiple times in a workflow, the last value set for each parameter is used.</p>
 <p>If the build is not triggered by Gerrit Trigger, or if the trigger is configured to not report back to Gerrit when the build finishes, this step does nothing.</p>
</div></div>
<ul><li><code>customUrl : String</code> (optional)
<div><div>
 Custom URL for a message to send back to Gerrit. If empty, URL to post from Gerrit Trigger configuration will be used. Same expansion is done as for the URL to post configuration option.
</div></div>

</li>
<li><code>unsuccessfulMessage : String</code> (optional)
<div><div>
 Additional details to post back to Gerrit if the build is not successful.
</div></div>

</li>
</ul>


++++
