= Git Changelog
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/git-changelog">Visit the Jenkins Plugins site</a>
++++


=== `getHighestSemanticVersion`: Get the highest version, determined by tags in repo. Also tag available as '.findTag().orElse("")'.
++++
<ul><li><code>from</code> (optional)
<ul><b>Nested Object</b>
<li><code>type</code>
<ul><li><b>Values:</b> <code>REF</code>, <code>COMMIT</code></li></ul></li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>repo : String</code> (optional)
</li>
<li><code>to</code> (optional)
<ul><b>Nested Object</b>
<li><code>type</code>
<ul><li><b>Values:</b> <code>REF</code>, <code>COMMIT</code></li></ul></li>
<li><code>value : String</code>
</li>
</ul></li>
</ul>


++++
=== `getNextSemanticVersion`: Next semantic version based on tags and conventional commits in Git repository
++++
<ul><li><code>from</code> (optional)
<ul><b>Nested Object</b>
<li><code>type</code>
<ul><li><b>Values:</b> <code>REF</code>, <code>COMMIT</code></li></ul></li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>majorPattern : String</code> (optional)
</li>
<li><code>minorPattern : String</code> (optional)
</li>
<li><code>patchPattern : String</code> (optional)
</li>
<li><code>repo : String</code> (optional)
</li>
<li><code>to</code> (optional)
<ul><b>Nested Object</b>
<li><code>type</code>
<ul><li><b>Values:</b> <code>REF</code>, <code>COMMIT</code></li></ul></li>
<li><code>value : String</code>
</li>
</ul></li>
</ul>


++++
=== `gitChangelog`: Changelog from Git repository
++++
<ul><li><code>customIssues</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>issuePattern : String</code>
</li>
<li><code>link : String</code> (optional)
</li>
<li><code>title : String</code> (optional)
</li>
</ul></li>
<li><code>dateFormat : String</code> (optional)
</li>
<li><code>extendedVariables</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>from</code> (optional)
<ul><b>Nested Object</b>
<li><code>type</code>
<ul><li><b>Values:</b> <code>REF</code>, <code>COMMIT</code></li></ul></li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>gitHub</code> (optional)
<ul><b>Nested Object</b>
<li><code>api : String</code>
</li>
<li><code>token : String</code>
</li>
<li><code>issuePattern : String</code>
</li>
</ul></li>
<li><code>gitLab</code> (optional)
<ul><b>Nested Object</b>
<li><code>server : String</code>
</li>
<li><code>token : String</code>
</li>
<li><code>issuePattern : String</code>
</li>
<li><code>projectName : String</code>
</li>
</ul></li>
<li><code>ignoreCommitsIfMessageMatches : String</code> (optional)
</li>
<li><code>ignoreCommitsIfOlderThan : String</code> (optional)
</li>
<li><code>ignoreCommitsWithoutIssue : boolean</code> (optional)
</li>
<li><code>ignoreTagsIfNameMatches : String</code> (optional)
</li>
<li><code>javascriptHelper : String</code> (optional)
</li>
<li><code>jira</code> (optional)
<ul><b>Nested Object</b>
<li><code>server : String</code>
</li>
<li><code>issuePattern : String</code>
</li>
<li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
<li><code>basicAuthString : String</code>
</li>
<li><code>bearer : String</code>
</li>
</ul></li>
<li><code>noIssueName : String</code> (optional)
</li>
<li><code>readableTagName : String</code> (optional)
</li>
<li><code>redmine</code> (optional)
<ul><b>Nested Object</b>
<li><code>server : String</code>
</li>
<li><code>issuePattern : String</code>
</li>
<li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
<li><code>token : String</code>
</li>
</ul></li>
<li><code>removeIssueFromMessage : boolean</code> (optional)
</li>
<li><code>repo : String</code> (optional)
</li>
<li><code>returnType</code> (optional)
<ul><li><b>Values:</b> <code>STRING</code>, <code>CONTEXT</code></li></ul></li>
<li><code>template : String</code> (optional)
</li>
<li><code>timeZone : String</code> (optional)
</li>
<li><code>to</code> (optional)
<ul><b>Nested Object</b>
<li><code>type</code>
<ul><li><b>Values:</b> <code>REF</code>, <code>COMMIT</code></li></ul></li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>untaggedName : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'GitChangelogRecorder'])`: Git Changelog
++++
<div><div>
 <p>See <a href="https://github.com/jenkinsci/git-changelog-plugin" rel="nofollow">Git Changelog Plugin</a> for details on how to configure and use this plugin.</p>
</div></div>
<ul><li><code>config</code>
<ul><b>Nested Object</b>
<li><code>configFile : String</code> (optional)
</li>
<li><code>createFileTemplateContent : String</code> (optional)
</li>
<li><code>createFileTemplateFile : String</code> (optional)
</li>
<li><code>createFileUseTemplateContent : boolean</code> (optional)
</li>
<li><code>createFileUseTemplateFile : boolean</code> (optional)
</li>
<li><code>customIssues</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>pattern : String</code>
</li>
<li><code>link : String</code>
</li>
<li><code>title : String</code>
</li>
</ul></li>
<li><code>dateFormat : String</code> (optional)
</li>
<li><code>file : String</code> (optional)
</li>
<li><code>fromReference : String</code> (optional)
</li>
<li><code>fromType : String</code> (optional)
</li>
<li><code>gitHubApi : String</code> (optional)
</li>
<li><code>gitHubApiTokenCredentialsId : String</code> (optional)
</li>
<li><code>gitHubIssuePattern : String</code> (optional)
</li>
<li><code>gitHubToken : String</code> (optional)
</li>
<li><code>gitLabApiTokenCredentialsId : String</code> (optional)
</li>
<li><code>gitLabProjectName : String</code> (optional)
</li>
<li><code>gitLabServer : String</code> (optional)
</li>
<li><code>gitLabToken : String</code> (optional)
</li>
<li><code>ignoreCommitsIfMessageMatches : String</code> (optional)
</li>
<li><code>ignoreCommitsWithoutIssue : boolean</code> (optional)
</li>
<li><code>ignoreTagsIfNameMatches : String</code> (optional)
</li>
<li><code>jiraBasicAuthString : String</code> (optional)
</li>
<li><code>jiraBasicAuthStringCredentialsId : String</code> (optional)
</li>
<li><code>jiraBearer : String</code> (optional)
</li>
<li><code>jiraBearerCredentialsId : String</code> (optional)
</li>
<li><code>jiraIssuePattern : String</code> (optional)
</li>
<li><code>jiraPassword : String</code> (optional)
</li>
<li><code>jiraServer : String</code> (optional)
</li>
<li><code>jiraUsername : String</code> (optional)
</li>
<li><code>jiraUsernamePasswordCredentialsId : String</code> (optional)
</li>
<li><code>noIssueName : String</code> (optional)
</li>
<li><code>readableTagName : String</code> (optional)
</li>
<li><code>redmineIssuePattern : String</code> (optional)
</li>
<li><code>redminePassword : String</code> (optional)
</li>
<li><code>redmineServer : String</code> (optional)
</li>
<li><code>redmineToken : String</code> (optional)
</li>
<li><code>redmineTokenCredentialsId : String</code> (optional)
</li>
<li><code>redmineUserNamePasswordCredentialsId : String</code> (optional)
</li>
<li><code>redmineUsername : String</code> (optional)
</li>
<li><code>showSummary : boolean</code> (optional)
</li>
<li><code>showSummaryTemplateContent : String</code> (optional)
</li>
<li><code>showSummaryTemplateFile : String</code> (optional)
</li>
<li><code>showSummaryUseTemplateContent : boolean</code> (optional)
</li>
<li><code>showSummaryUseTemplateFile : boolean</code> (optional)
</li>
<li><code>subDirectory : String</code> (optional)
</li>
<li><code>timeZone : String</code> (optional)
</li>
<li><code>toReference : String</code> (optional)
</li>
<li><code>toType : String</code> (optional)
</li>
<li><code>untaggedName : String</code> (optional)
</li>
<li><code>useConfigFile : boolean</code> (optional)
</li>
<li><code>useFile : boolean</code> (optional)
</li>
<li><code>useGitHub : boolean</code> (optional)
</li>
<li><code>useGitLab : boolean</code> (optional)
</li>
<li><code>useIgnoreTagsIfNameMatches : boolean</code> (optional)
</li>
<li><code>useJira : boolean</code> (optional)
</li>
<li><code>useReadableTagName : boolean</code> (optional)
</li>
<li><code>useRedmine : boolean</code> (optional)
</li>
<li><code>useSubDirectory : boolean</code> (optional)
</li>
</ul></li>
</ul>


++++
