= Git plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/git">Visit the Jenkins Plugins site</a>
++++


=== `git`: Git
++++
<div><div>
 <p>Git step. It performs a clone from the specified repository.</p>
 <p>Use the <a href="https://www.jenkins.io/redirect/pipeline-snippet-generator" rel="nofollow">Pipeline Syntax Snippet Generator</a> to generate a sample pipeline script for the git step. More advanced checkout operations require the <code>checkout</code> step rather than the <code>git</code> step. Examples of the <code>git</code> step include:</p>
 <ul>
  <li><a rel="nofollow">Git step with defaults</a></li>
  <li><a rel="nofollow">Git step with https and a specific branch</a></li>
  <li><a rel="nofollow">Git step with ssh and a private key credential</a></li>
  <li><a rel="nofollow">Git step with https and changelog disabled</a></li>
  <li><a rel="nofollow">Git step with git protocol and polling disabled</a></li>
 </ul> See the <a rel="nofollow">argument descriptions</a> for more details. 
 <p></p>
 <p>The <code>git</code> step is a simplified shorthand for a subset of the more powerful <code>checkout</code> step:</p>
 <pre>checkout([$class: 'GitSCM', branches: [[name: '*/master']],
    userRemoteConfigs: [[url: 'https://git-server/user/repository.git']]])
</pre>
 <p></p>
 <p><strong>NOTE:</strong> The <code>checkout</code> step is the <strong>preferred SCM checkout method</strong>. It provides significantly more functionality than the <code>git</code> step.</p>
 <p>Use the <a href="https://www.jenkins.io/redirect/pipeline-snippet-generator" rel="nofollow">Pipeline Syntax Snippet Generator</a> to generate a sample pipeline script for the checkout step.</p>
 <p>The <code>checkout</code> step can be used in many cases where the <code>git</code> step cannot be used. Refer to the <a href="https://plugins.jenkins.io/git#extensions" rel="nofollow">git plugin documentation</a> for detailed descriptions of options available to the checkout step. For example, the <code>git</code> step does <strong>not</strong> support:</p>
 <ul>
  <li>SHA-1 checkout</li>
  <li>Tag checkout</li>
  <li>Submodule checkout</li>
  <li>Sparse checkout</li>
  <li>Large file checkout (LFS)</li>
  <li>Reference repositories</li>
  <li>Branch merges</li>
  <li>Repository tagging</li>
  <li>Custom refspecs</li>
  <li>Timeout configuration</li>
  <li>Changelog calculation against a non-default reference</li>
  <li>Stale branch pruning</li>
 </ul>
 <p></p> <strong><a rel="nofollow">Example: Git step with defaults</a></strong>
 <p>Checkout from the git plugin source repository using https protocol, no credentials, and the master branch.</p>
 <p>The <a href="https://www.jenkins.io/redirect/pipeline-snippet-generator" rel="nofollow">Pipeline Syntax Snippet Generator</a> generates this example:</p>
 <pre>git 'https://github.com/jenkinsci/git-plugin'
</pre>
 <p></p><strong><a rel="nofollow">Example: Git step with https and a specific branch</a></strong>
 <p>Checkout from the Jenkins source repository using https protocol, no credentials, and a specific branch (stable-2.204). Note that this must be a local branch name like 'master' or 'develop'.</p>
 <p><strong>Branch names that are not supported by the <code>git</code> step</strong></p>
 <ul>
  <li>Remote branch names like 'origin/master' and 'origin/develop' are <strong>not supported</strong> as the branch argument</li>
  <li>SHA-1 hashes are <strong>not supported</strong> as the branch argument</li>
  <li>Tag names are <strong>not supported</strong> as the branch argument</li>
 </ul>
 <p>Remote branch names, SHA-1 hashes, and tag names <strong>are supported</strong> by the general purpose <code>checkout</code> step.</p>
 <p>The <a href="https://www.jenkins.io/redirect/pipeline-snippet-generator" rel="nofollow">Pipeline Syntax Snippet Generator</a> generates this example:</p>
 <pre>git branch: 'stable-2.204',
    url: 'https://github.com/jenkinsci/jenkins.git'
</pre>
 <p></p><strong><a rel="nofollow">Example: Git step with ssh and a private key credential</a></strong>
 <p>Checkout from the git client plugin source repository using ssh protocol, private key credentials, and the master branch. The credential must be a private key credential if the remote git repository is accessed with the ssh protocol. The credential must be a username / password credential if the remote git repository is accessed with http or https protocol.</p>
 <p>The <a href="https://www.jenkins.io/redirect/pipeline-snippet-generator" rel="nofollow">Pipeline Syntax Snippet Generator</a> generates this example:</p>
 <pre>git credentialsId: 'my-private-key-credential-id',
    url: 'git@github.com:jenkinsci/git-client-plugin.git'
</pre>
 <p></p><strong><a rel="nofollow">Example: Git step with https and changelog disabled</a></strong>
 <p>Checkout from the Jenkins source repository using https protocol, no credentials, the master branch, and changelog calculation disabled. If changelog is <code>false</code>, then the changelog will not be computed for this job. If changelog is <code>true</code> or is not set, then the changelog will be computed. See the <a href="https://github.com/jenkinsci/workflow-scm-step-plugin/blob/master/README.md#changelogs" rel="nofollow">workflow scm step documentation</a> for more changelog details.</p>
 <p>The <a href="https://www.jenkins.io/redirect/pipeline-snippet-generator" rel="nofollow">Pipeline Syntax Snippet Generator</a> generates this example:</p>
 <pre>git changelog: false,
    url: 'https://github.com/jenkinsci/credentials-plugin.git'
</pre>
 <p></p><strong><a rel="nofollow">Example: Git step with https protocol and polling disabled</a></strong>
 <p>Checkout from the Jenkins platform labeler repository using https protocol, no credentials, the master branch, and no polling for changes. If poll is <code>false</code>, then the remote repository will not be polled for changes. If poll is <code>true</code> or is not set, then the remote repository will be polled for changes. See the <a href="https://github.com/jenkinsci/workflow-scm-step-plugin/blob/master/README.md#polling" rel="nofollow">workflow scm step documentation</a> for more polling details.</p>
 <p>The <a href="https://www.jenkins.io/redirect/pipeline-snippet-generator" rel="nofollow">Pipeline Syntax Snippet Generator</a> generates this example:</p>
 <pre>git poll: false,
    url: 'https://github.com/jenkinsci/platformlabeler-plugin.git'
</pre>
 <p></p> <strong><a rel="nofollow">Argument Descriptions</a></strong>
</div></div>
<ul><li><code>url : String</code>
<div><div>
 <p>URL of the repository to be checked out in the workspace. Required parameter.</p>
 <p>Repository URL's should follow the <a href="https://git-scm.com/docs/git-clone#_git_urls_a_id_urls_a" rel="nofollow">git URL guidelines</a>. Git steps to access a secured repository should provide a Jenkins credential with the <code>credentialsId</code> argument rather than embedding credentials in the URL. Credentials embedded in a repository URL may be visible in console logs or in other log files.</p>
</div></div>

</li>
<li><code>branch : String</code> (optional)
<div><div>
 <p>Branch to be checked out in the workspace. Default is '<code>master</code>'.</p>
 <p>Note that this must be a local branch name like 'master' or 'develop'. Remote branch names like 'origin/master' and 'origin/develop' are <strong>not supported</strong> as the branch argument. Tag names are <strong>not supported</strong> as the branch argument. SHA-1 hashes are <strong>not supported</strong> as the branch argument. Remote branch names, tag names, and SHA-1 hashes are supported by the general purpose <code>checkout</code> step.</p>
</div></div>

</li>
<li><code>changelog : boolean</code> (optional)
<div><div>
 <p>Compute changelog for this job. Default is '<code>true</code>'.</p>
 <p>If <code>changelog</code> is false, then the changelog will not be computed for this job. If <code>changelog</code> is true or is not set, then the changelog will be computed.</p>
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 <p>Identifier of the credential used to access the remote git repository. Default is '&lt;empty&gt;'.</p>
 <p>The credential must be a private key credential if the remote git repository is accessed with the ssh protocol. The credential must be a username / password credential if the remote git repository is accessed with http or https protocol.</p>
</div></div>

</li>
<li><code>poll : boolean</code> (optional)
<div><div>
 <p>Poll remote repository for changes. Default is '<code>true</code>'.</p>
 <p>If <code>poll</code> is false, then the remote repository will not be polled for changes. If <code>poll</code> is true or is not set, then the remote repository will be polled for changes.</p>
</div></div>

</li>
</ul>


++++
