= GitHub Issues Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/github-issues">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'GitHubIssueNotifier'])`: Create GitHub issue on failure
++++
<ul><li><code>issueAppend : boolean</code> (optional)
<div><div>
 If checked, and a job is continuously failing, every additional failure adds a new comment.
</div></div>

</li>
<li><code>issueBody : String</code> (optional)
<div><div>
 Body text to use for the GitHub issues created when builds start to fail. Use the "Content Token Reference" help below to see all the available tokens.
</div></div>

</li>
<li><code>issueLabel : String</code> (optional)
<div><div>
 If specified, this label will be applied to all tasks created through this plugin. Optional.
</div></div>

</li>
<li><code>issueReopen : boolean</code> (optional)
<div><div>
 Check this to change the behavior when a job fails a second time and previously created issue exists, if checked, this issue get reopened instead of creating a new one.
</div></div>

</li>
<li><code>issueRepo : String</code> (optional)
<div><div>
 Repo to use for the GitHub issues to create when builds start to fail. If kept blank the project attribute of the GitHub plugin will be used.
</div></div>

</li>
<li><code>issueTitle : String</code> (optional)
<div><div>
 Title to use for the GitHub issues created when builds start to fail. Use the "Content Token Reference" help below to see all the available tokens.
</div></div>

</li>
</ul>


++++
