= GitHub Integration Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/github-pullrequest">Visit the Jenkins Plugins site</a>
++++


=== `setGitHubPullRequestStatus`: Set GitHub PullRequest Commit Status
++++
<div><div>
 Sets the commit status of the commit that triggered a pull request build. Note that this step can only be used by builds that were triggered by a pull request.
</div></div>
<ul><li><code>context : String</code> (optional)
<div><div>
 A string label to differentiate this status from the status of other systems.
</div></div>

</li>
<li><code>message : String</code> (optional)
<div><div>
 A short detail message to add to the status
</div></div>

</li>
<li><code>state</code> (optional)
<div><div>
 State of the status indicating the progress or completion of the check.
</div></div>

<ul><li><b>Values:</b> <code>PENDING</code>, <code>SUCCESS</code>, <code>ERROR</code>, <code>FAILURE</code></li></ul></li>
</ul>


++++
=== `githubPRStatusPublisher`: GitHub PR: set PR status
++++
<ul><li><code>statusMsg</code>
<div><div>
 Description message for GitHub status.
</div></div>

<ul><b>Nested Object</b>
<li><code>content : String</code>
<div><div>
 Message content that will be posted. Support core variable expansion i.e. ${WORKSPACE}.
 <br>
  If token-macro plugin enabled, then support token expansion.
 <br>
  If email-ext plugin enabled, then support expanding groovy templates with ${SCRIPT, path="template.groovy"}.
</div></div>

</li>
</ul></li>
<li><code>unstableAs</code>
<ul><li><b>Values:</b> <code>PENDING</code>, <code>SUCCESS</code>, <code>ERROR</code>, <code>FAILURE</code></li></ul></li>
<li><code>buildMessage</code>
<ul><b>Nested Object</b>
<li><code>successMsg</code>
<ul><b>Nested Object</b>
<li><code>content : String</code>
<div><div>
 Message content that will be posted. Support core variable expansion i.e. ${WORKSPACE}.
 <br>
  If token-macro plugin enabled, then support token expansion.
 <br>
  If email-ext plugin enabled, then support expanding groovy templates with ${SCRIPT, path="template.groovy"}.
</div></div>

</li>
</ul></li>
<li><code>failureMsg</code>
<ul><b>Nested Object</b>
<li><code>content : String</code>
<div><div>
 Message content that will be posted. Support core variable expansion i.e. ${WORKSPACE}.
 <br>
  If token-macro plugin enabled, then support token expansion.
 <br>
  If email-ext plugin enabled, then support expanding groovy templates with ${SCRIPT, path="template.groovy"}.
</div></div>

</li>
</ul></li>
</ul></li>
<li><code>statusVerifier</code>
<ul><b>Nested Object</b>
<li><code>buildStatus : String</code>
</li>
</ul></li>
<li><code>errorHandler</code>
<ul><b>Nested Object</b>
<li><code>buildStatus : String</code>
</li>
</ul></li>
</ul>


++++
=== `githubPRClosePublisher`: GitHub PR: close PR
++++
<ul><li><code>statusVerifier</code>
<ul><b>Nested Object</b>
<li><code>buildStatus : String</code>
</li>
</ul></li>
<li><code>errorHandler</code>
<ul><b>Nested Object</b>
<li><code>buildStatus : String</code>
</li>
</ul></li>
</ul>


++++
=== `githubPRComment`: GitHub PR: post comment
++++
<ul><li><code>comment</code>
<ul><b>Nested Object</b>
<li><code>content : String</code>
<div><div>
 Message content that will be posted. Support core variable expansion i.e. ${WORKSPACE}.
 <br>
  If token-macro plugin enabled, then support token expansion.
 <br>
  If email-ext plugin enabled, then support expanding groovy templates with ${SCRIPT, path="template.groovy"}.
</div></div>

</li>
</ul></li>
<li><code>statusVerifier</code>
<ul><b>Nested Object</b>
<li><code>buildStatus : String</code>
</li>
</ul></li>
<li><code>errorHandler</code>
<ul><b>Nested Object</b>
<li><code>buildStatus : String</code>
</li>
</ul></li>
</ul>


++++
=== `githubPRAddLabels`: GitHub PR: add labels
++++
<ul><li><code>labelProperty</code>
<ul><b>Nested Object</b>
<div><div>
 Help page for GitHubPRLabel class. Not used anywhere?
</div></div>
<li><code>labels : String</code>
<div><p>Every new label on new line</p></div>

</li>
</ul></li>
<li><code>statusVerifier</code>
<ul><b>Nested Object</b>
<li><code>buildStatus : String</code>
</li>
</ul></li>
<li><code>errorHandler</code>
<ul><b>Nested Object</b>
<li><code>buildStatus : String</code>
</li>
</ul></li>
</ul>


++++
=== `githubPRRemoveLabels`: GitHub PR: remove labels
++++
<ul><li><code>labelProperty</code>
<ul><b>Nested Object</b>
<div><div>
 Help page for GitHubPRLabel class. Not used anywhere?
</div></div>
<li><code>labels : String</code>
<div><p>Every new label on new line</p></div>

</li>
</ul></li>
<li><code>statusVerifier</code>
<ul><b>Nested Object</b>
<li><code>buildStatus : String</code>
</li>
</ul></li>
<li><code>errorHandler</code>
<ul><b>Nested Object</b>
<li><code>buildStatus : String</code>
</li>
</ul></li>
</ul>


++++
=== `gitHubPRStatus`: GitHub PR: set 'pending' status
++++
<ul><li><code>statusMessage</code>
<ul><b>Nested Object</b>
<li><code>content : String</code>
<div><div>
 Message content that will be posted. Support core variable expansion i.e. ${WORKSPACE}.
 <br>
  If token-macro plugin enabled, then support token expansion.
 <br>
  If email-ext plugin enabled, then support expanding groovy templates with ${SCRIPT, path="template.groovy"}.
</div></div>

</li>
</ul></li>
</ul>


++++
