= GitHub Pull Request Coverage Status
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/github-pr-coverage-status">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'CompareCoverageAction'])`: Publish coverage to GitHub
++++
<div><div>
 This step could be used only for Jenkins jobs triggered by <a href="https://plugins.jenkins.io/ghprb/" rel="nofollow">GitHub pull request builder plugin</a>
 <p></p> Step will get code coverage from build. Get collected previously coverage for master. Then post status to GitHub pull request as comment. 
 <p></p> To record master coverage add post build step <b>Record Master Coverage</b> to any job which you think should be master. Ensure that coverage report is present in a build. 
 <p></p> Step get test coverage from Cobertura or Jacoco reports (XML) if they present in build. They could be created by any tool. Otherwise coverage will be 0.
</div></div>
<ul><li><code>jacocoCoverageCounter : String</code> (optional)
<div><div>
 The coverage metric should be the same as in "Record Master Coverage" action in order to have accurate results
</div></div>

</li>
<li><code>publishResultAs : String</code> (optional)
</li>
<li><code>scmVars</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>sonarLogin : String</code> (optional)
</li>
<li><code>sonarPassword : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'MasterCoverageAction'])`: Record Master Coverage
++++
<div><div>
 This step get test coverage for repository as master coverage. When you run another build to check pull request. Master coverage will be used co compare vs pull request and post information to pull request comments. 
 <p></p> Step get test coverage from Cobertura or Jacoco reports (XML) if they present in build. They could be created by any tool. Otherwise coverage will be 0.
</div></div>
<ul><li><code>jacocoCounterType : String</code> (optional)
</li>
<li><code>scmVars</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
</ul>


++++
