= Google Cloud Build Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/google-cloudbuild">Visit the Jenkins Plugins site</a>
++++


=== `googleCloudBuild`: Execute Google Cloud Build
++++
<div><div>
 This build step invokes Google Cloud Build.
</div></div>
<ul><li><code>input</code>
<ul><b>Nested Object</b>
<li><code>credentialsId : String</code>
</li>
<li><code>request</code>
<ul><b>Nested Choice of Objects</b>
<li><code>file</code><div>
<ul><li><code>filename : String</code>
<div><div>
 The path to the YAML build request file to pass to Google Cloud Build.
</div></div>

</li>
</ul></div></li>
<li><code>inline</code><div>
<ul><li><code>request : String</code>
<div><div>
 The YAML Build Request to pass to Google Cloud Build.
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>source</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>local</code><div>
<ul><li><code>path : String</code>
<div><div>
 The source to use in the build request. This may be either: 
 <ul>
  <li><b>A path to a file within the workspace.</b> The file must be a compressed gzipped tarball (<code>.tgz</code> or <code>.tar.gz</code>) or zip file (<code>.zip</code>), or</li>
  <li><b>A path to a directory within the workspace.</b> The contents of the directory will be archived as a gzipped tarball (<code>.tgz</code>) and uploaded to a temporary Cloud Storage bucket.</li>
 </ul>
</div></div>

</li>
</ul></div></li>
<li><code>repo</code><div>
<ul><li><code>branch : String</code> (optional)
</li>
<li><code>commit : String</code> (optional)
</li>
<li><code>projectId : String</code> (optional)
<div><div>
 ID of the project that owns the repo. If omitted, the project ID requesting the build is assumed.
</div></div>

</li>
<li><code>repoName : String</code> (optional)
<div><div>
 Name of the repo. If omitted, the name "default" is assumed.
</div></div>

</li>
<li><code>tag : String</code> (optional)
</li>
</ul></div></li>
<li><code>storage</code><div>
<ul><li><code>bucket : String</code>
</li>
<li><code>object : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>substitutionList</code> (optional)
<ul><b>Nested Object</b>
<li><code>items</code>
<div><div>
 User-defined substitutions to be added to the build request. The set of user-defined substitutions referenced in the build request must exactly match the set of substitutions defined here. For details, see <a href="https://cloud.google.com/cloud-build/docs/concepts/build-requests#substitutions" rel="nofollow"> Build Requests - User-defined substitutions</a>.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>key : String</code>
<div><div>
 The name of the user-defined substitution. This must begin with an underscore (<code>_</code>) and use only numbers, uppercase letters, and underscores (respecting the regular expression <code>_[A-Z0-9_]+</code>). The key may not be longer than 100 characters. For details, see <a href="https://cloud.google.com/cloud-build/docs/concepts/build-requests#substitutions" rel="nofollow"> Build Requests - User-defined substitutions</a>.
</div></div>

</li>
<li><code>value : String</code>
<div><div>
 The value of the user-defined substitution. This must not expand to longer than 100 characters. For details, see <a href="https://cloud.google.com/cloud-build/docs/concepts/build-requests#substitutions" rel="nofollow"> Build Requests - User-defined substitutions</a>.
</div></div>

</li>
</ul></li>
</ul></li>
<li><code>substitutions</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
</ul></li>
</ul>


++++
