= Google Play Android Publisher Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/google-play-android-publisher">Visit the Jenkins Plugins site</a>
++++


=== `androidApkUpload`: Upload Android AAB/APKs to Google Play
++++
<ul><li><code>additionalVersionCodes : String</code> (optional)
<div><div>
 Specifies the version codes of app files from a previous release which should be included in the release to be created by this build step. 
 <p></p> For example, if you have a Wear OS app file already released, but in this build step you only need to upload new mobile app files, you can enter the version code of the Wear OS app file to retain it for this new release, rather than having to upload it again here. 
 <p></p> Similarly, if you're using Multiple APK Support, you may have a situation where you only need to release an update to a single APK, and so you can use this functionality to retain the other APKs for this new release by entering their version codes. 
 <p></p> If you don't need this functionality, you can leave this field blank. Note that multiple entries must be comma-separated.  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>apkFilesPattern : String</code> (optional)
</li>
<li><code>deobfuscationFilesPattern : String</code> (optional)
<div><div>
 Specifies filenames or patterns matching one or more ProGuard mapping files that should be uploaded to Google Play, so that it can automatically deobfuscate stacktraces from crash reports. 
 <p></p> Note that if you build an Android App Bundle (AAB file) with ProGuard enabled, the mapping file should already be embedded in the app bundle (typically as BUNDLE-METADATA/com.android.tools.build.obfuscation/proguard.map.
 <br>
  In such cases, you shouldn't use this option since Google Play will reject any attempt to upload a mapping file when the app bundle has one embedded. 
 <p></p> You can use wildcards like "**/build/**/mapping.txt".
 <br>
  See <a href="https://ant.apache.org/manual/Types/fileset.html" rel="nofollow"> the 'includes' attribute of Ant's FileSet</a> for the exact format.
 <br>
  Note that multiple entries must be comma-separated. 
 <p></p> The base directory is <a rel="nofollow">the build's workspace</a>. You can only upload mapping files that are located in your workspace. 
 <p></p> If there are multiple AAB/APK files being uploaded, and only one mapping file is found in the workspace, then that mapping file will be associated with each of the app files being uploaded. If there are multiple mapping files found, a basic attempt will be made to automatically associate each mapping file with its corresponding app file.
 <br>
  Otherwise, if the number of mapping files found is <em>not</em> equal to the number of app files being uploaded, the build will fail, as this situation is not supported. 
 <p></p> For more information on deobfuscating crash stacktraces, see the Google Play documentation:
 <br><a href="https://support.google.com/googleplay/android-developer/answer/6295281" rel="nofollow"> https://support.google.com/googleplay/android-developer/answer/6295281 </a>  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>expansionFilesPattern : String</code> (optional)
<div><p>Specifies filenames or patterns matching zero or more <a href="https://developer.android.com/google/play/expansion-files.html" rel="nofollow"> expansion files</a> that should be associated with the APK files being uploaded to Google Play.</p>
<p></p> You can list as many or as few expansion files as you like — you have the option of associating previously-uploaded expansion files with the new APKs being uploading here. 
<h2>Naming</h2> Files <b>must</b> be named in the format [main|patch].&lt;apk-version&gt;.&lt;application-id&gt;.obb
<p></p> For example: 
<ul>
 <li>main.1000.com.example.mygame.obb</li>
 <li>patch.1002.com.example.mygame.obb</li>
</ul>
<h2>Patterns</h2> You can use wildcards like "**/build/**/*.obb".
<br>
 See <a href="https://ant.apache.org/manual/Types/fileset.html" rel="nofollow"> the 'includes' attribute of Ant's FileSet</a> for the exact format.
<br>
 Note that multiple entries must be comma-separated. 
<p></p> The base directory is <a rel="nofollow">the build's workspace</a>. You can only upload OBB files that are located in your workspace. 
<h2>Re-using existing expansion files</h2> If you don't provide a main or patch expansion file for every APK that you want to upload, enabling the "Re-use expansion files from existing APKs where necessary" option will automatically associate existing expansion file(s) with the APK(s) being uploaded. 
<p></p> With this option enabled, if not enough expansion files are provided for all of the APK(s) being uploaded, this plugin will search for the <i>newest</i>, APKs on Google Play with main or patch expansion files — whether previously uploaded, or uploaded via the current build — and will associate those files with the new APK(s) being uploaded here. 
<p></p> For example: If you want to upload a new APK, but the expansion files have not changed at all, you should leave the "Expansion files" field blank, but enable the checkbox.
<br>
 At build time, the latest existing main (and patch, if available) expansion files will be associated with the newly-uploaded APK. 
<p></p> Similarly, if you have a new build, but only want to change the patch file, then just provide the patch expansion file and make sure this option is checked. The uploaded APK will have the existing main expansion file associated with it, along with the newly-uploaded patch file. 
<p></p> Or, if you have a new main or patch expansion file, and want to apply that same file to multiple APKs being uploaded, name the expansion file according to the <i>lowest</i> versionCode that you're uploading. That expansion file will then be uploaded, and applied to the APKs with higher versionCodes that were uploaded in the same build.  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.</div>

</li>
<li><code>filesPattern : String</code> (optional)
<div><div>
 Specifies filenames or patterns matching one or more AABs or APKs that should be uploaded to Google Play. 
 <p></p> You can use wildcards like "**/build/outputs/*/*-release.apk".
 <br>
  See <a href="https://ant.apache.org/manual/Types/fileset.html" rel="nofollow"> the 'includes' attribute of Ant's FileSet</a> for the exact format.
 <br>
  Note that multiple entries must be comma-separated. 
 <p></p> The base directory is <a rel="nofollow">the build's workspace</a>. You can only upload AAB or APK files that are located in your workspace. 
 <p></p> Applications which have several files per release, taking advantage of <a href="https://developer.android.com/google/play/publishing/multiple-apks.html" rel="nofollow"> Multiple APK Support</a>, must have all of their APKs uploaded together, and all APKs must have the same application identifier (APK package name).
 <br>
 <p></p> If no value is provided, the default is **/build/outputs/**/*.aab, **/build/outputs/**/*.apk.  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>googleCredentialsId : String</code> (optional)
<div><div>
 Specifies which credential to use in order to connect to Google Play. 
 <p></p> The selected credential must be a "Google Service Account from private key" — if you have not added one already, refer to the documentation on <a href="https://plugins.jenkins.io/google-play-android-publisher" rel="nofollow">this plugin's page</a>. 
 <p></p> By choosing the "Parameter expression" option, you can also provide a credential at build time, either from an environment variable, or from a build parameter, e.g. the Credentials Parameter type.
 <br>
  But you can use any type of expression, so long as it expands to the name of a "Google Service Account from private key" credential at build time.  This field supports substituting environment variables in the form ${SOME_VARIABLE} at build time.
 <br>
  Note that variables in the form $SOME_VARIABLE are <em>not</em> accepted by the Credentials Plugin.
</div></div>

</li>
<li><code>inAppUpdatePriority : String</code> (optional)
<div><div>
 Specifies the priority of this app release for the in-app update feature of the Google Play Core Library. 
 <p></p> If you don't use this feature, or don't need to set a priority, you can leave this field blank; it will default to 0. Otherwise the value must be a whole number between 0 (lowest priority) and 5 (highest priority). 
 <p></p> For more information on using in-app updates, see the documentation:
 <br><a href="https://developer.android.com/guide/playcore/in-app-updates" rel="nofollow"> https://developer.android.com/guide/playcore/in-app-updates </a>  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>nativeDebugSymbolFilesPattern : String</code> (optional)
<div><div>
 Specifies filenames or patterns matching one or more zip files containing native library symbols that should be uploaded to Google Play, so that it can automatically deobfuscate native crash dumps. 
 <p></p> Note that if you build an Android App Bundle (AAB file) with native libraries, using Android Gradle Plugin version 4.1 or newer, you can choose to <a href="https://developer.android.com/studio/build/shrink-code#native-crash-support" rel="nofollow"> automatically embed</a> the native symbols into the app bundle file.
 <br>
  Therefore you don't need to use this option to upload the symbols separately. But if you do, the contents of this symbols file will supersede those embedded in the bundle. 
 <p></p> You can use wildcards like "**/build/**/native-debug-symbols.zip".
 <br>
  See <a href="https://ant.apache.org/manual/Types/fileset.html" rel="nofollow"> the 'includes' attribute of Ant's FileSet</a> for the exact format.
 <br>
  Note that multiple entries must be comma-separated. 
 <p></p> The base directory is <a rel="nofollow">the build's workspace</a>. You can only upload symbols files that are located in your workspace. 
 <p></p> If there are multiple AAB/APK files being uploaded, and only one symbols file is found in the workspace, then that symbols file will be associated with each of the app files being uploaded. If there are multiple symbols files found, a basic attempt will be made to automatically associate each symbols file with its corresponding app file.
 <br>
  Otherwise, if the number of symbols files found is <em>not</em> equal to the number of app files being uploaded, the build will fail, as this situation is not supported. 
 <p></p> For more information on deobfuscating crash stacktraces, see the Google Play documentation:
 <br><a href="https://support.google.com/googleplay/android-developer/answer/6295281" rel="nofollow"> https://support.google.com/googleplay/android-developer/answer/6295281 </a>  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>recentChangeList</code> (optional)
<div><div>
 You can optionally apply "What's new" text to the uploaded file(s), in order to inform your user of changes contained in the new app version. 
 <p></p> You add entries for as many or as few of your supported language as you wish, but each language must already have been added to your app, under the "Store Listing" section in the Google Play Developer Console. 
 <p></p> The language must match the language code shown in the Developer Console, e.g. "en-GB" for British English, or "ar" for Arabic. 
 <p></p> The text may be between zero and 500 characters. 
 <p></p> For more information on describing what's new in your app, see the Google Play documentation:
 <br><a href="https://support.google.com/googleplay/android-developer/answer/189724" rel="nofollow"> https://support.google.com/googleplay/android-developer/answer/189724 </a>  Both fields support substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>language : String</code>
</li>
<li><code>text : String</code>
</li>
</ul></li>
<li><code>releaseName : String</code> (optional)
<div><div>
 The release name, used to identify this release in the Google Play Console UI. Not required to be unique among releases. If no value is entered, Google Play will set the release name to the versionName of the app file being uploaded. 
 <p></p> Any instances of {versionCode} or {versionName} in the value will be replaced by the respective value from the app file being uploaded. If multiple files are uploaded, the one with the lowest versionCode will be used. 
 <p></p> For example, entering Version {versionName}-${GIT_COMMIT} as release name could yield a release name on Google Play something like Version 1.2.3-b2c3d3e4.  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>rolloutPercent : double</code> (optional)
</li>
<li><code>rolloutPercentage : String</code> (optional)
<div><div>
 The percentage of users in the given track to which the uploaded file(s) should be rolled out. 
 <p></p> If you enter 100%, the app will be rolled out to all users, and the release will be considered complete, i.e. you will be unable to reduce the rollout percentage for this release. 
 <p></p> If you enter 0%, a draft release will be created, meaning that users will not yet see it; the existing file(s) released in the given track, if any, will remain in place. 
 <p></p> For more information on staged rollouts, see the Google Play documentation:
 <br><a href="https://support.google.com/googleplay/android-developer/answer/6346149" rel="nofollow"> https://support.google.com/googleplay/android-developer/answer/6346149 </a>  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>trackName : String</code> (optional)
<div><div>
 Specifies the release track to which the given app file(s) will be assigned, or uploaded. 
 <h2>Regular release tracks</h2> You can enter the name of a <a href="https://support.google.com/googleplay/android-developer/answer/3131213#create_additional_track" rel="nofollow">custom track</a>, or one of the built-in tracks: 
 <ul>
  <li>internal</li>
  <li>alpha</li>
  <li>beta</li>
  <li>production</li>
 </ul> For these tracks, you have the choice of rolling out the uploaded app files to all existing users immediately, or doing a staged rollout so that only a percentage of your existing userbase will be able to download the new version. Alternatively, you can set the rollout percentage to zero to create a draft release. 
 <p></p> For more information on using the internal, alpha, beta or custom testing tracks, see the Google Play documentation:
 <br><a href="https://support.google.com/googleplay/android-developer/answer/3131213" rel="nofollow"> https://support.google.com/googleplay/android-developer/answer/3131213 </a>
 <h2>Internal App Sharing</h2> Alternatively, you can use the special track name internal-app-sharing, which will upload the app file — either an AAB or APK file — directly to <a href="https://support.google.com/googleplay/android-developer/answer/9844679" rel="nofollow"> Internal App Sharing</a>. In this case, no other build step configuration is required, other than the Google Play credentials. 
 <p></p> Upon successful upload, the download URL for the uploaded file will be output to the build log.  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>usePreviousExpansionFilesIfMissing : boolean</code> (optional)
</li>
</ul>


++++
=== `androidApkMove`: Move Android apps to a different release track
++++
<div><div>
 If you have already uploaded files to Google Play, whether manually, via the "Upload Android AAB/APK to Google Play" post-build action, or by other means, this build step allows you to change the release track for specific versions. 
 <p></p> For example, you can use this to promote an app currently in alpha testing to the beta release track, once you've decided it's ready for a wider audience. 
 <p></p> Similarly, once you're ready for release, you can move from beta to a staged rollout, or directly to production. 
 <p></p> Note that "downgrading" release tracks, e.g. from production to alpha is not possible.
</div></div>
<ul><li><code>apkFilesPattern : String</code> (optional)
</li>
<li><code>applicationId : String</code> (optional)
<div><div>
 Application ID (i.e. APK package name) of the app being assigned to a new release track.  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>filesPattern : String</code> (optional)
<div><div>
 Specifies filenames or patterns matching one or more AAB or APK files from which the version codes should be read, in order to determine which app versions should be re-assigned to a new release track. 
 <p></p> Note that these files should have already been uploaded — this build step will not do any uploading; it will only move existing app versions from one release track to another. To upload app files, use the "Upload Android AAB/APK to Google Play" post-build action. 
 <p></p> You can use wildcards like "**/build/outputs/*/*-release.apk".
 <br>
  See <a href="https://ant.apache.org/manual/Types/fileset.html" rel="nofollow"> the 'includes' attribute of Ant's FileSet</a> for the exact format.
 <br>
  Note that multiple entries must be comma-separated. 
 <p></p> The base directory is <a rel="nofollow">the build's workspace</a>. You can only reference AAB or APK files that are located in your workspace. 
 <p></p> If no value is provided, the default is **/build/outputs/**/*.aab, **/build/outputs/**/*.apk.  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>fromVersionCode : boolean</code> (optional)
</li>
<li><code>googleCredentialsId : String</code> (optional)
<div><div>
 Specifies which credential to use in order to connect to Google Play. 
 <p></p> The selected credential must be a "Google Service Account from private key" — if you have not added one already, refer to the documentation on <a href="https://plugins.jenkins.io/google-play-android-publisher" rel="nofollow">this plugin's page</a>. 
 <p></p> By choosing the "Parameter expression" option, you can also provide a credential at build time, either from an environment variable, or from a build parameter, e.g. the Credentials Parameter type.
 <br>
  But you can use any type of expression, so long as it expands to the name of a "Google Service Account from private key" credential at build time.  This field supports substituting environment variables in the form ${SOME_VARIABLE} at build time.
 <br>
  Note that variables in the form $SOME_VARIABLE are <em>not</em> accepted by the Credentials Plugin.
</div></div>

</li>
<li><code>inAppUpdatePriority : String</code> (optional)
<div><div>
 Specifies the priority of this app release for the in-app update feature of the Google Play Core Library. 
 <p></p> If you don't use this feature, or don't need to set a priority, you can leave this field blank; it will default to 0. Otherwise the value must be a whole number between 0 (lowest priority) and 5 (highest priority). 
 <p></p> For more information on using in-app updates, see the documentation:
 <br><a href="https://developer.android.com/guide/playcore/in-app-updates" rel="nofollow"> https://developer.android.com/guide/playcore/in-app-updates </a>  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>releaseName : String</code> (optional)
<div><div>
 The release name, used to identify this release in the Google Play Console UI. Not required to be unique among releases. If no value is entered, Google Play will set the release name to the versionName of the app file being moved.  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>rolloutPercent : double</code> (optional)
</li>
<li><code>rolloutPercentage : String</code> (optional)
<div><div>
 The percentage of users in the given track to which the uploaded file(s) should be rolled out. 
 <p></p> If you enter 100%, the app will be rolled out to all users, and the release will be considered complete, i.e. you will be unable to reduce the rollout percentage for this release. 
 <p></p> If you enter 0%, a draft release will be created, meaning that users will not yet see it; the existing file(s) released in the given track, if any, will remain in place. 
 <p></p> For more information on staged rollouts, see the Google Play documentation:
 <br><a href="https://support.google.com/googleplay/android-developer/answer/6346149" rel="nofollow"> https://support.google.com/googleplay/android-developer/answer/6346149 </a>  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>trackName : String</code> (optional)
<div><div>
 Specifies the release track to which the given app file(s) will be re-assigned. 
 <p></p> You can enter the name of a <a href="https://support.google.com/googleplay/android-developer/answer/3131213#create_additional_track" rel="nofollow">custom track</a>, or one of the built-in tracks: 
 <ul>
  <li>internal</li>
  <li>alpha</li>
  <li>beta</li>
  <li>production</li>
 </ul> For these tracks, you have the choice of rolling out the uploaded app files to all existing users immediately, or doing a staged rollout so that only a percentage of your existing userbase will be able to download the new version. 
 <p></p> For more information on using the internal, alpha, beta or custom testing tracks, see the Google Play documentation:
 <br><a href="https://support.google.com/googleplay/android-developer/answer/3131213" rel="nofollow"> https://support.google.com/googleplay/android-developer/answer/3131213 </a>  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
<li><code>versionCodes : String</code> (optional)
<div><div>
 This specifies which version codes should be assigned to a new release track. 
 <br>
  Note that multiple entries must be comma-separated.  This field supports substituting environment variables in the form ${SOME_VARIABLE} or $SOME_VARIABLE at build time.
</div></div>

</li>
</ul>


++++
