= Groovy
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/groovy">Visit the Jenkins Plugins site</a>
++++


=== `withGroovy`: Execute Groovy script
++++
<ul><li><code>input : <code>Object</code></code> (optional)
<div><p>Allows the Pipeline script to pass structured objects to the external Groovy script and receive structured return values. The values must be <code>Serializable</code> and may only refer to types defined in the Java Platform or Groovy language. If set to any non-null value, the external script may call the following methods:</p>
<dl>
 <dt>
  <code>Pipeline.input()</code>
 </dt>
 <dd>
  Returns the object passed in this parameter.
 </dd>
 <dt>
  <code>Pipeline.output(object)</code>
 </dt>
 <dd>
  Saves an object to be used as the return value of this step.
 </dd>
</dl>
<p>(If your script passes <code>-cp</code> / <code>-classpath</code>, be sure to append/prepend <code>$CLASSPATH</code> / <code>%CLASSPATH%</code>.)</p></div>

</li>
<li><code>jdk : String</code> (optional)
<div><div>
 Selects a version of Java to use when running Groovy. If you leave this at <b>(Default)</b> then <code>groovy</code> will use whatever <code>java</code> is in your system path, typically that which launched the agent (<code>slave.jar</code>).
</div></div>

</li>
<li><code>tool : String</code> (optional)
<div><div>
 Selects a version of Groovy to add to the system path. If you leave this at <b>(Default)</b> then <code>groovy</code> will just run the CLI (<code>groovy.ui.GroovyMain</code>) from the version of Groovy currently bundled in Jenkins. This is enough for simple scripts, but does not support specific command-line options of the full Groovy launcher.
</div></div>

</li>
</ul>


++++
