= HashiCorp Vault Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/hashicorp-vault-plugin">Visit the Jenkins Plugins site</a>
++++


=== `withVault`: Vault Plugin
++++
<ul><li><code>vaultSecrets</code>
<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
<div><div>
 The path of the secret in the vault server as described <a href="https://www.vaultproject.io/docs/commands/help.html" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>secretValues</code>
<ul><b>Array / List of Nested Object</b>
<li><code>vaultKey : String</code>
<div><div>
 The vault key whose value will populate the environment variable.
</div></div>

</li>
<li><code>envVar : String</code> (optional)
<div><div>
 The environment variable to set with the value of the vault key.
 <br>
  If field is left empty. The value from vault key will be used for environment variable.
</div></div>

</li>
<li><code>isRequired : boolean</code> (optional)
<div><div>
 A toggle to determine if the given Vault secret value must be present in your secret
 <br>
  If checked, the value is required; the plugin will throw an error if the value is not found in the secret.
</div></div>

</li>
</ul></li>
<li><code>engineVersion : int</code> (optional)
<div><div>
 The vault K/V engine version. Currently supports versions 1 or 2. (Only applicable when using vaults Key/Value secrets engine. See <a href="https://www.vaultproject.io/docs/secrets/kv/" rel="nofollow">here</a>)
 <br>
  If set to default it will use what is configured on folder or global configuration.
</div></div>

</li>
</ul></li>
<li><code>configuration</code> (optional)
<ul><b>Nested Object</b>
<li><code>disableChildPoliciesOverride : boolean</code> (optional)
<div><div>
 If set, this will disable any child folder or job from overriding the job policies. This prevents the escalation of privileges by subfolders or jobs.
</div></div>

</li>
<li><code>engineVersion : int</code> (optional)
<div><div>
 The vault K/V engine version. Currently supports versions 1 or 2. (Only applicable when using vaults Key/Value secrets engine. See <a href="https://www.vaultproject.io/docs/secrets/kv/" rel="nofollow">here</a>)
 <br>
  If set to default it will use what is configured on folder or global configuration.
</div></div>

</li>
<li><code>failIfNotFound : boolean</code> (optional)
</li>
<li><code>policies : String</code> (optional)
<div><div>
 The Vault policies to use when requesting a token for a job, separated by newlines. If left empty, this will use all policies from the configured authentication. This is useful for AppRole authentication where the AppRole can have many policies attached it and divide up the policies per job based on the job folder or name. This allows you to restrict access on specific jobs or folders. Each policy can use the following tokens to templatize the policies: 
 <ul>
  <li>${job_base_name} - equal to the JOB_BASE_NAME env var</li>
  <li>${job_name} - equal to the JOB_NAME env var</li>
  <li>${job_name_us} - same as ${job_name} with slashes converted to underscores</li>
  <li>${job_folder} - the folder of the job (JOB_NAME - JOB_BASE_NAME without the trailing slash)</li>
  <li>${job_folder_us} - same as ${job_folder} with slashes converted to underscores</li>
  <li>${node_name} - equal to the NODE_NAME env var</li>
 </ul> For example, a policy list such as: 
 <ul>
  <li>pol_jenkins_base</li>
  <li>pol_jenkins_job_base_${job_base_name}</li>
  <li>pol_jenkins_folder_us_${job_name_folder_us}</li>
  <li>pol_jenkins/folder/${job_folder}</li>
  <li>pol_jenkins_job_us_${job_name_us}</li>
  <li>pol_jenkins/job/${job_name}</li>
 </ul> Would result in six policies being applied to each job run. If the JOB_NAME was "folder1/folder2/job1" and the JOB_BASE_NAME was "job1", the policies applied would be: 
 <ul>
  <li>pol_jenkins_base</li>
  <li>pol_jenkins_job_base_job1</li>
  <li>pol_jenkins_folder_us_folder1_folder2</li>
  <li>pol_jenkins/folder/folder1/folder2</li>
  <li>pol_jenkins_job_us_folder1_folder2_job1</li>
  <li>pol_jenkins/job/folder1/folder2/job1</li>
 </ul> Please note that the AppRole should have all policies configured as token_policies and not identity_policies, as job-specific tokens inherit all identity_policies automatically.
</div></div>

</li>
<li><code>prefixPath : String</code> (optional)
</li>
<li><code>skipSslVerification : boolean</code> (optional)
</li>
<li><code>timeout : int</code> (optional)
</li>
<li><code>vaultCredential</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'VaultAppRoleCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>roleId : String</code>
</li>
<li><code>secretId</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>path : String</code>
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the mount path is located. If the auth mount path is on the root namespace use "<code>/</code>", if namespace is empty the global namespace or credential namespace will be used if specified. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>usePolicies : boolean</code> (optional)
<div><div>
 If checked and policies are defined in the Vault plugin configuration, a child token will be provisioned after authenticating with Vault with only the configured policies. See the Vault plugin configuration policies for more information.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'VaultAwsIamCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>mountPath : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the mount path is located. If the auth mount path is on the root namespace use "<code>/</code>", if namespace is empty the global namespace or credential namespace will be used if specified. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>role : String</code> (optional)
<div><div>
 The IAM role to authenticate with. If this is left blank, Vault will use the role in the <a href="https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html" rel="nofollow">sts:GetCallerIdentity</a> response.
</div></div>

</li>
<li><code>serverId : String</code> (optional)
<div><div>
 The value to supply in the <code>X-Vault-AWS-IAM-Server-ID</code> header of the <a href="https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html" rel="nofollow">sts:GetCallerIdentity</a> request. This must match the value configured in the Vault AWS IAM auth method if the header is required.
</div></div>

</li>
<li><code>usePolicies : boolean</code> (optional)
<div><div>
 If checked and policies are defined in the Vault plugin configuration, a child token will be provisioned after authenticating with Vault with only the configured policies. See the Vault plugin configuration policies for more information.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'VaultGCPCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>role : String</code>
</li>
<li><code>audience : String</code>
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the mount path is located. If the auth mount path is on the root namespace use "<code>/</code>", if namespace is empty the global namespace or credential namespace will be used if specified. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>usePolicies : boolean</code> (optional)
<div><div>
 If checked and policies are defined in the Vault plugin configuration, a child token will be provisioned after authenticating with Vault with only the configured policies. See the Vault plugin configuration policies for more information.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'VaultGithubTokenCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>accessToken</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>mountPath : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the mount path is located. If the auth mount path is on the root namespace use "<code>/</code>", if namespace is empty the global namespace or credential namespace will be used if specified. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>usePolicies : boolean</code> (optional)
<div><div>
 If checked and policies are defined in the Vault plugin configuration, a child token will be provisioned after authenticating with Vault with only the configured policies. See the Vault plugin configuration policies for more information.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'VaultKubernetesCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>role : String</code>
</li>
<li><code>mountPath : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the mount path is located. If the auth mount path is on the root namespace use "<code>/</code>", if namespace is empty the global namespace or credential namespace will be used if specified. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>usePolicies : boolean</code> (optional)
<div><div>
 If checked and policies are defined in the Vault plugin configuration, a child token will be provisioned after authenticating with Vault with only the configured policies. See the Vault plugin configuration policies for more information.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'VaultTokenCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>token</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'VaultTokenFileCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>filepath : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>vaultCredentialId : String</code> (optional)
</li>
<li><code>vaultNamespace : String</code> (optional)
</li>
<li><code>vaultUrl : String</code> (optional)
</li>
</ul></li>
</ul>


++++
=== `wrap([$class: 'VaultBuildWrapper'])`: Vault Plugin
++++
<ul><li><code>vaultSecrets</code>
<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
<div><div>
 The path of the secret in the vault server as described <a href="https://www.vaultproject.io/docs/commands/help.html" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>secretValues</code>
<ul><b>Array / List of Nested Object</b>
<li><code>vaultKey : String</code>
<div><div>
 The vault key whose value will populate the environment variable.
</div></div>

</li>
<li><code>envVar : String</code> (optional)
<div><div>
 The environment variable to set with the value of the vault key.
 <br>
  If field is left empty. The value from vault key will be used for environment variable.
</div></div>

</li>
<li><code>isRequired : boolean</code> (optional)
<div><div>
 A toggle to determine if the given Vault secret value must be present in your secret
 <br>
  If checked, the value is required; the plugin will throw an error if the value is not found in the secret.
</div></div>

</li>
</ul></li>
<li><code>engineVersion : int</code> (optional)
<div><div>
 The vault K/V engine version. Currently supports versions 1 or 2. (Only applicable when using vaults Key/Value secrets engine. See <a href="https://www.vaultproject.io/docs/secrets/kv/" rel="nofollow">here</a>)
 <br>
  If set to default it will use what is configured on folder or global configuration.
</div></div>

</li>
</ul></li>
<li><code>configuration</code> (optional)
<ul><b>Nested Object</b>
<li><code>disableChildPoliciesOverride : boolean</code> (optional)
<div><div>
 If set, this will disable any child folder or job from overriding the job policies. This prevents the escalation of privileges by subfolders or jobs.
</div></div>

</li>
<li><code>engineVersion : int</code> (optional)
<div><div>
 The vault K/V engine version. Currently supports versions 1 or 2. (Only applicable when using vaults Key/Value secrets engine. See <a href="https://www.vaultproject.io/docs/secrets/kv/" rel="nofollow">here</a>)
 <br>
  If set to default it will use what is configured on folder or global configuration.
</div></div>

</li>
<li><code>failIfNotFound : boolean</code> (optional)
</li>
<li><code>policies : String</code> (optional)
<div><div>
 The Vault policies to use when requesting a token for a job, separated by newlines. If left empty, this will use all policies from the configured authentication. This is useful for AppRole authentication where the AppRole can have many policies attached it and divide up the policies per job based on the job folder or name. This allows you to restrict access on specific jobs or folders. Each policy can use the following tokens to templatize the policies: 
 <ul>
  <li>${job_base_name} - equal to the JOB_BASE_NAME env var</li>
  <li>${job_name} - equal to the JOB_NAME env var</li>
  <li>${job_name_us} - same as ${job_name} with slashes converted to underscores</li>
  <li>${job_folder} - the folder of the job (JOB_NAME - JOB_BASE_NAME without the trailing slash)</li>
  <li>${job_folder_us} - same as ${job_folder} with slashes converted to underscores</li>
  <li>${node_name} - equal to the NODE_NAME env var</li>
 </ul> For example, a policy list such as: 
 <ul>
  <li>pol_jenkins_base</li>
  <li>pol_jenkins_job_base_${job_base_name}</li>
  <li>pol_jenkins_folder_us_${job_name_folder_us}</li>
  <li>pol_jenkins/folder/${job_folder}</li>
  <li>pol_jenkins_job_us_${job_name_us}</li>
  <li>pol_jenkins/job/${job_name}</li>
 </ul> Would result in six policies being applied to each job run. If the JOB_NAME was "folder1/folder2/job1" and the JOB_BASE_NAME was "job1", the policies applied would be: 
 <ul>
  <li>pol_jenkins_base</li>
  <li>pol_jenkins_job_base_job1</li>
  <li>pol_jenkins_folder_us_folder1_folder2</li>
  <li>pol_jenkins/folder/folder1/folder2</li>
  <li>pol_jenkins_job_us_folder1_folder2_job1</li>
  <li>pol_jenkins/job/folder1/folder2/job1</li>
 </ul> Please note that the AppRole should have all policies configured as token_policies and not identity_policies, as job-specific tokens inherit all identity_policies automatically.
</div></div>

</li>
<li><code>prefixPath : String</code> (optional)
</li>
<li><code>skipSslVerification : boolean</code> (optional)
</li>
<li><code>timeout : int</code> (optional)
</li>
<li><code>vaultCredential</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'VaultAppRoleCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>roleId : String</code>
</li>
<li><code>secretId</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>path : String</code>
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the mount path is located. If the auth mount path is on the root namespace use "<code>/</code>", if namespace is empty the global namespace or credential namespace will be used if specified. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>usePolicies : boolean</code> (optional)
<div><div>
 If checked and policies are defined in the Vault plugin configuration, a child token will be provisioned after authenticating with Vault with only the configured policies. See the Vault plugin configuration policies for more information.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'VaultAwsIamCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>mountPath : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the mount path is located. If the auth mount path is on the root namespace use "<code>/</code>", if namespace is empty the global namespace or credential namespace will be used if specified. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>role : String</code> (optional)
<div><div>
 The IAM role to authenticate with. If this is left blank, Vault will use the role in the <a href="https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html" rel="nofollow">sts:GetCallerIdentity</a> response.
</div></div>

</li>
<li><code>serverId : String</code> (optional)
<div><div>
 The value to supply in the <code>X-Vault-AWS-IAM-Server-ID</code> header of the <a href="https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html" rel="nofollow">sts:GetCallerIdentity</a> request. This must match the value configured in the Vault AWS IAM auth method if the header is required.
</div></div>

</li>
<li><code>usePolicies : boolean</code> (optional)
<div><div>
 If checked and policies are defined in the Vault plugin configuration, a child token will be provisioned after authenticating with Vault with only the configured policies. See the Vault plugin configuration policies for more information.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'VaultGCPCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>role : String</code>
</li>
<li><code>audience : String</code>
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the mount path is located. If the auth mount path is on the root namespace use "<code>/</code>", if namespace is empty the global namespace or credential namespace will be used if specified. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>usePolicies : boolean</code> (optional)
<div><div>
 If checked and policies are defined in the Vault plugin configuration, a child token will be provisioned after authenticating with Vault with only the configured policies. See the Vault plugin configuration policies for more information.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'VaultGithubTokenCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>accessToken</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>mountPath : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the mount path is located. If the auth mount path is on the root namespace use "<code>/</code>", if namespace is empty the global namespace or credential namespace will be used if specified. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>usePolicies : boolean</code> (optional)
<div><div>
 If checked and policies are defined in the Vault plugin configuration, a child token will be provisioned after authenticating with Vault with only the configured policies. See the Vault plugin configuration policies for more information.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'VaultKubernetesCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>role : String</code>
</li>
<li><code>mountPath : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the mount path is located. If the auth mount path is on the root namespace use "<code>/</code>", if namespace is empty the global namespace or credential namespace will be used if specified. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>usePolicies : boolean</code> (optional)
<div><div>
 If checked and policies are defined in the Vault plugin configuration, a child token will be provisioned after authenticating with Vault with only the configured policies. See the Vault plugin configuration policies for more information.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'VaultTokenCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>token</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'VaultTokenFileCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>filepath : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>vaultCredentialId : String</code> (optional)
</li>
<li><code>vaultNamespace : String</code> (optional)
</li>
<li><code>vaultUrl : String</code> (optional)
</li>
</ul></li>
</ul>


++++
