= OpenText Application Automation Tools
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/hp-application-automation-tools-plugin">Visit the Jenkins Plugins site</a>
++++


=== `loadRunnerTest`: Run LoadRunner performance scenario tests
++++
<ul><li><code>testPaths : String</code>
</li>
<li><code>archiveTestResultsMode : String</code>
<div><div>
 To view the run results, do one of the following:
 <br>
  1) In the left pane, click the <b>Report and Summary</b> link to display the report link and the link to the report folder. From this link, you can open the run results directly in your browser or open the artifacts
 <br>
  2) From the <b>Build Artifacts:</b>
 <br>
  • Open the run_results.html to view the run results.
 <br>
  • Download the zipped report to your desired location and unzip it. In the <b>Run Results Viewer</b>, select the Results.xml file found inside the unzipped folder.
 <br>
  Note that this option is valid only when using the “Execute test from file system” build step.
</div></div>

</li>
<li><code>analysisTemplate : String</code> (optional)
<div><div>
 Apply a template for the build (path to a .tem file). Leave blank in order to use the default template.
</div></div>

</li>
<li><code>controllerPollingInterval : String</code> (optional)
<div><div>
 Polling interval for checking the scenario status, in seconds. The default is 30 seconds.
</div></div>

</li>
<li><code>displayController : String</code> (optional)
<div><div>
 Display the controller while the scenario is running.
</div></div>

</li>
<li><code>fsTimeout : String</code> (optional)
<div><div>
 Timeout value in seconds. If left empty, there is no timeout.
</div></div>

</li>
<li><code>ignoreErrorStrings : String</code> (optional)
<div><div>
 Ignore errors during the scenario run containing any of the strings listed below. For example: "Error: CPU usage for this load generator has exceeded 80%"
</div></div>

</li>
<li><code>perScenarioTimeOut : String</code> (optional)
<div><div>
 The maximum time allotted for scenario execution, in minutes.
</div></div>

</li>
<li><code>scriptRTSSetModel</code> (optional)
<ul><b>Nested Object</b>
<li><code>scripts</code>
<ul><b>Array / List of Nested Object</b>
<li><code>scriptName : String</code>
<div><div>
 The script name is found in Controller's Script Information dialog (Percentage Mode scenario) or Group Information dialog (Vuser Group Mode scenario).
</div></div>

</li>
<li><code>additionalAttributes</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
<li><code>description : String</code>
</li>
</ul></li>
</ul></li>
</ul></li>
<li><code>summaryDataLogModel</code> (optional)
<ul><b>Nested Object</b>
<li><code>logVusersStates : boolean</code>
<div><div>
 Display the number of virtual users in each state.
</div></div>

</li>
<li><code>logErrorCount : boolean</code>
<div><div>
 Display the number of controller errors.
</div></div>

</li>
<li><code>logTransactionStatistics : boolean</code>
<div><div>
 Display the number of passed transactions, failed transactions and hits per second.
</div></div>

</li>
<li><code>pollingInterval : String</code>
<div><div>
 The rate at which the messages are displayed (in seconds). Default value is 10 seconds.
</div></div>

</li>
</ul></li>
</ul>


++++
=== `runLoadRunnerScript`: Run LoadRunner script
++++
<ul><li><code>scriptPath : String</code>
</li>
</ul>


++++
=== `sseBuildAndPublish`: Execute tests using ALM Lab Management and Publish tests result
++++
<ul><li><code>almServerName : String</code>
</li>
<li><code>almProject : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>clientType : String</code>
<div><div>
 Client type is required for some ALM above 12.60 in authentication.
</div></div>

</li>
<li><code>almDomain : String</code>
</li>
<li><code>runType : String</code>
</li>
<li><code>almEntityId : String</code>
</li>
<li><code>timeslotDuration : String</code>
</li>
<li><code>archiveTestResultsMode : String</code>
<div><div>
 To view the run results, do one of the following:
 <br>
  1) In the left pane, click the <b>Report and Summary</b> link to display the report link and the link to the report folder. From this link, you can open the run results directly in your browser or open the artifacts
 <br>
  2) From the <b>Build Artifacts:</b>
 <br>
  • Open the run_results.html to view the run results.
 <br>
  • Download the zipped report to your desired location and unzip it. In the <b>Run Results Viewer</b>, select the Results.xml file found inside the unzipped folder.
 <br>
  Note that this option is valid only when using the “Execute test from file system” build step.
</div></div>

</li>
<li><code>cdaDetails</code> (optional)
<ul><b>Nested Object</b>
<li><code>deploymentAction : String</code>
</li>
<li><code>deployedEnvironmentName : String</code>
</li>
<li><code>deprovisioningAction : String</code>
</li>
</ul></li>
<li><code>description : String</code> (optional)
</li>
<li><code>environmentConfigurationId : String</code> (optional)
<div><div>
 To find the ID of your environment configuration, right-click the entity, copy the URL, and paste it to a text editor. Use the number associated with the EntityID at the end of the URL.
</div></div>

</li>
<li><code>postRunAction : String</code> (optional)
</li>
</ul>


++++
=== `collectBranchesToAlmOctane`: ALM Octane branch collector
++++
<div><div>
 This step is responsible for collecting branches from the SCM tool and injecting them into ALM Octane. 
 <br>
 <br>
  In addition, this step is used to define the SCM repository templates that are used by ALM Octane to link to your repository viewer. To configure templates in ALM Octane, access Settings &gt; Spaces. Select a workspace and click DevOps &gt; SCM Repositories. Follow the on-screen instructions. 
 <br>
 <br>
 <br>
  Supported version of ALM Octane: 15.1.90 and later. 
 <br>
 <br>
  You can change the behaviour of this step by adding the following parameters to the job: 
 <ul>
  <li><b>branches_active_branch_days</b>: Only active branches can be added/updated to ALM Octane. Default is 60 days.</li>
  <br>
  <li><b>branches_max_branches_to_fill</b>: Relevant for GitHub repository only. Max branches to collect data. If data is not collected from a branch, it cannot be added to ALM Octane. Default is 1000.</li>
  <br>
 </ul>
 <br>
 <br><b>Supported SCM Tools: </b>
 <br>
 <table width="100%">
  <thead>
   <tr>
    <td>SCM Tool</td>
    <td>Supported types of authentication</td>
    <td>How to create PAT (Personal access token)</td>
   </tr>
  </thead>
  <tbody>
   <tr>
    <td>Bitbucket Server</td>
    <td>User/password and PAT</td>
    <td>Click on your profile icon -&gt; Manage account -&gt; Personal access tokens -&gt; Create a token (Assign Read permissions for both Projects and Repositories)</td>
   </tr>
   <tr>
    <td>Github Cloud</td>
    <td>PAT only</td>
    <td rowspan="2">Click on your profile icon -&gt; Settings -&gt; Developer settings -&gt; Personal access tokens -&gt; Generate new token (Uncheck all scopes to grants read-only access)</td>
   </tr>
   <tr>
    <td>Github Server</td>
    <td>User/password and PAT</td>
   </tr>
  </tbody>
 </table>
 <br>
  Note : To create PAT credentials in Jenkins , use "Secret text" kind of credentials in "Add Credentials" dialog
</div></div>
<ul><li><code>configurationId : String</code>
</li>
<li><code>workspaceId : String</code>
</li>
<li><code>scmTool : String</code>
</li>
<li><code>repositoryUrl : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>filter : String</code>
</li>
<li><code>useSSHFormat : boolean</code> (optional)
<div><div>
 Select this if all other jobs that use this repository and are connected to ALM Octane pipelines use SSH format. It is important to be consistent with other jobs that use this repository. 
 <br>
  This will ensure that ALM Octane correctly identifies the SCM repository associated with commits, branches and pull requests.
</div></div>

</li>
</ul>


++++
=== `commonResultUploadBuilder`: Upload test result to ALM using field mapping
++++
<ul><li><code>almServerName : String</code>
<div><div>
 The name of the ALM Server.
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
<li><code>almDomain : String</code>
<div><div>
 The Domain of the project to be used.
</div></div>

</li>
<li><code>clientType : String</code>
<div><div>
 Client type is required for some ALM above 12.60 in authentication.
</div></div>

</li>
<li><code>almProject : String</code>
<div><div>
 The project to be used.
</div></div>

</li>
<li><code>almTestFolder : String</code>
<div><div>
 The path of the test folder that will contain the uploaded test. The path doesn't include the Root test folder (Subject). 
 <br>
  For example, sampletestfolder\subfolder means, the tests will be uploaded to test folder named 'subfolder', which is under the test folder named 'sampletestfolder', 
 <br>
  and 'sampletestfolder' is under the root test folder 'Subject'.
</div></div>

</li>
<li><code>almTestSetFolder : String</code>
<div><div>
 The path of the testset folder that will contain the uploaded testset. The path doesn't include the Root testset folder. 
 <br>
  For example, sampletestsetfolder\subfolder means, the testsets will be uploaded to testset folder named 'subfolder', which is under the testset folder named 'sampletestsetfolder', 
 <br>
  and 'sampletestsetfolder' is under the root testset folder 'Root'.
</div></div>

</li>
<li><code>testingResultFile : String</code>
<div><div>
 setting that specifies the generated raw XML report files, such as **/junitResult.xml. Basedir of the fileset is the root path of current job and workspace.
</div></div>

</li>
<li><code>runStatusMapping : String</code>
<div><div>
 <p>Run status mapping field is for mapping the test result's status values to ALM run status value. Yaml key represents the ALM run status values. Only one of the following status can be set here:<br>
   Passed<br>
   Failed<br>
   Yaml value represents the condition that sustains the status. Ten kinds of conditions can be set here:<br>
   ==StringValue<br>
   !=StringValue<br>
   ==0 (Or any numeric value)<br>
   !=0 (Or any numeric value)<br>
   &gt;&gt;0 (Or any numeric value)<br>
   &lt;&lt;0 (Or any numeric value)<br>
   &lt;=0 (Or any numeric value)<br>
   &gt;=0 (Or any numeric value)<br>
   ==NULL<br>
   !=NULL<br>
   You should first set the status field in field mapping.<br></p> Take following test result as example: &lt;test-case name="ExampleTestOfNUnit.TestMultiplicationFail" executed="True" result="Failure" success="False" time="0.122" asserts="1"&gt;  <b>Sample field mapping:</b> run: status: "x: success"  <b>Sample status mapping:</b> status: Passed: "==true"   Take following test result as example: &lt;case&gt; &lt;duration&gt;0.041&lt;/duration&gt; &lt;className&gt;SomeClass&lt;/className&gt; &lt;testName&gt;SomeTest-1&lt;/testName&gt; &lt;skipped&gt;false&lt;/skipped&gt; &lt;failedSince&gt;0&lt;/failedSince&gt; &lt;/case&gt;  <b>Sample field mapping:</b> run: status: "x: failedSince" <b>Sample status mapping:</b> status: Failed: "&gt;=0" 
</div></div>

</li>
<li><code>fieldMapping : String</code>
<div><div>
 <p>Field mapping content is a yaml format configuration. Three sections are required. They are 'testset', 'test' and 'run'. Each section should has a 'root' property indicates the root node of the testset or test or run. Please note that test's root is based on testset's root. Run's root is based on test's root.</p>
 <p>Beside root, you can define any field you want to upload as an ALM entity. Yaml key represents the entity's field name. Yaml value represents the entity's field value.</p>
 <p>If you want to upload a value to a User defined field, you could use a key starts with 'udf|' follows by the UDF label. Such as 'udf-duration' would upload value to a UDF field which has label as 'duration'.</p>
 <p>For the yaml value part, there're two types of value. Value starts with 'x:' means the following value represents the xpath in the test result file. Value starts with 'v:' means the following value is a string value which would be applied to every entity.</p>
 <p>You can use '|' in yame value for combining several parts together.</p><b>Sample test result:</b> &lt;?xml version='1.0' encoding='UTF-8'?&gt; &lt;result&gt; &lt;suites&gt; &lt;suite&gt; &lt;file&gt;Changes file&lt;/file&gt; &lt;name&gt;Changes Test Set 1&lt;/name&gt; &lt;duration&gt;2.293&lt;/duration&gt; &lt;cases&gt; &lt;case&gt; &lt;duration&gt;8.293&lt;/duration&gt; &lt;className&gt;ChangesManagement&lt;/className&gt; &lt;testName&gt;test1&lt;/testName&gt; &lt;testVersion&gt;4.0&lt;/testVersion&gt; &lt;skipped&gt;false&lt;/skipped&gt; &lt;failedSince&gt;0&lt;/failedSince&gt; &lt;/case&gt; &lt;case&gt; &lt;duration&gt;8.293&lt;/duration&gt; &lt;className&gt;ChangesManagement&lt;/className&gt; &lt;testName&gt;List changes 2&lt;/testName&gt; &lt;testVersion&gt;4.0&lt;/testVersion&gt; &lt;skipped&gt;false&lt;/skipped&gt; &lt;failedSince&gt;0&lt;/failedSince&gt; &lt;/case&gt; &lt;/cases&gt; &lt;/suite&gt; &lt;duration&gt;0.576&lt;/duration&gt; &lt;/result&gt; <b>Sample field mapping:</b>  testset: root: "x:/result/suites/suite" name: "x:file|v:_|x:name" udf|duration: "x:duration" subtype-id: "v:hp.qc.test-set.external" test: root: "x:cases/case" name: "x:testName" subtype-id: "v:EXTERNAL-TEST" udf|duration: "x:duration" udf|test version: "x:testVersion" run: root: "x:." duration: "x:duration" status: "x:failedSince" 
</div></div>

</li>
<li><code>createNewTest : boolean</code>
<div><div>
 <b>Check:</b> Create tests and related test-instances and runs when no test is found by the specified fields(name by default or can be specified as id). 
 <br><b>Uncheck:</b> Don't create test and related test-instances and runs when no test is found by the specified fields. 
 <br><b>Note:</b> Tests will not be updated when they're found by the specified fields.
</div></div>

</li>
</ul>


++++
=== `publishGherkinResults`: ALM Octane Cucumber test reporter
++++
<div><div>
 When using this action, Jenkins understands and reads the Cucumber test report XML structure. After reading the structure, Jenkins can provide useful information about Cucumber tests results to ALM Octane. 
 <p>To use the feature, ensure that you have added a Publish JUnit test results post-build action to your build. Then, specify the path to the Cucumber report XML files in the <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">Ant glob syntax</a>. <br>
  You can specify multiple patterns by separating them with commas. <br>
  This path should only contain Cucumber report files. Note that no other test types will be reported from this job.</p>
</div></div>
<ul><li><code>cucumberResultsGlob : String</code>
</li>
</ul>


++++
=== `executeTestsFromAlmOctane`: Execute tests from ALM Octane (Tech Preview)
++++
<div><div>
 This build step is intended to support execution of automated tests from ALM Octane.
 <br>
  There are several modes of execution : 
 <table width="100%">
  <thead>
   <tr>
    <td width="30%">Mode</td>
    <td>Explanation</td>
   </tr>
  </thead>
  <tbody>
   <tr>
    <td>Execute suite runs in ALM Octane</td>
    <td>Execute suites according to specified suite IDs. New suite runs will be created and executed in ALM Octane. Jenkins job is finished after triggering the suite runs. The job does not wait until the suite runs are finished. This method is useful if you want to schedule suite execution in ALM Octane. <br>
      By default, newly created suite runs will have name of suite and will be assigned to default release. In order to override this default behaviour, add following parameters (one or more) to job with your desired values: 
     <ul>
      <li>octane_release_id</li>
      <li>octane_new_suite_run_name</li>
     </ul></td>
   </tr>
   <tr>
    <td>Get tests from suites and trigger execution jobs</td>
    <td>Get tests from suites and trigger execution jobs : Get tests from specified suite IDs. (This method assumes that tests are assigned to test runner jobs from the current Jenkins.) Tests are send to execution by their assigned test runner jobs. The main job is finished after the test runner jobs are finished. This method is useful if you intend to add your job to the ALM Octane Pipeline module.</td>
   </tr>
  </tbody>
 </table>
</div></div>
<ul><li><code>configurationId : String</code>
</li>
<li><code>workspaceId : String</code>
</li>
<li><code>executionMode : String</code>
</li>
<li><code>ids : String</code>
</li>
</ul>


++++
=== `healthAnalyzer`: OpenText Health Analyzer
++++
<ul><li><code>products</code>
<div><div>
 Choose the products that you would like to test that correspond to the relevant build step.
</div></div>

<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'HealthAnalyzerLrStep'</code><div>
<ul><li><code>checkLrInstallation : boolean</code>
</li>
<li><code>checkOsVersion : boolean</code>
</li>
<li><code>checkFiles</code>
<ul><b>Nested Object</b>
<li><code>filesList</code>
<ul><b>Array / List of Nested Object</b>
<li><code>field : String</code>
</li>
</ul></li>
</ul></li>
</ul></div></li>
</ul></li>
</ul>


++++
=== `step([$class: 'JobConfigRebrander'])`: Fix old OpenText Jenkins builds
++++
<ul></ul>


++++
=== `step([$class: 'MigrateAlmCredentialsBuilder'])`: Migrate ALM Credentials
++++
<ul></ul>


++++
=== `pcBuild`: Execute performance test using LoadRunner Enterprise
++++
<ul><li><code>serverAndPort : String</code>
</li>
<li><code>pcServerName : String</code>
<div><div>
 Hostname or IP address The LoadRunner Enterprise Hostname or IP address. If the port of the LRE server is different than the default one, mention it by adding a collon (:) and then the port number
 <br><b>Example</b>: mypcserver.mycompany.net or 182.138.255.1 or mypcserver.mycompany.net:81
 <br>
 <br>
  If the LRE server requires to be accessed via a tenant, you can specify it by adding the tenant details to the LRE Server field.
 <br><b>Example</b>: mypcserver.mycompany.net/?tenant=fa128c06-5436-413d-9cfa-9f04bb738df3 or 182.138.255.1/?tenant=fa128c06-5436-413d-9cfa-9f04bb738df3 or mypcserver.mycompany.net:81/?tenant=fa128c06-5436-413d-9cfa-9f04bb738df3
 <br>
 <br><b>Important</b>: Do not use the full URL of LoadRunner Enterprise server. 
 <br>
  For example, using https://mypcserver/LoadTest will fail. Instead, just specify 'mypcserver' value in 'LRE Server' field and switch on the 'Use HTTPS Protocol' if secured protocol is required.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 LoadRunner Enterprise User / Token's Credentials or parameter pointing to such credentials.
</div></div>

</li>
<li><code>almDomain : String</code>
</li>
<li><code>almProject : String</code>
</li>
<li><code>testId : String</code>
</li>
<li><code>testInstanceId : String</code>
<div><div>
 Represents an instance of a performance test within an ALM Test Set. In order to find the test instance id go to: <b>LRE Web UI &gt; Testing &gt; Select the relevant test &gt; Test Details tab &gt; Assigned Test Set drop down list &gt; Edit the Test Set </b> and look for the Test Instance ID column
</div></div>

</li>
<li><code>autoTestInstanceID : String</code>
</li>
<li><code>timeslotDurationHours : String</code>
</li>
<li><code>timeslotDurationMinutes : String</code>
</li>
<li><code>postRunAction</code>
<ul><li><b>Values:</b> <code>COLLATE</code>, <code>COLLATE_AND_ANALYZE</code>, <code>DO_NOTHING</code></li></ul></li>
<li><code>vudsMode : boolean</code>
<div><div>
 A <b>Virtual User Day (VUD)</b> license provides you with a specified number of Vusers (VUDs) that you can run an unlimited number of times within a 24 hour period. Before using this option, make sure that VUDs licenses are applied in your Micro Focus LoadRunner Enterprise environment.
</div></div>

</li>
<li><code>statusBySLA : boolean</code>
<div><div>
 Check this option in order to set the build-step status according to a pre-defined <b>SLA (Service Level Agreement)</b> configured within your performance test. Unless checked, the build-step will be labeled as <i>Passed</i> as long as no failures occurred.
</div></div>

</li>
<li><code>description : String</code>
</li>
<li><code>addRunToTrendReport : String</code>
</li>
<li><code>trendReportId : String</code>
</li>
<li><code>HTTPSProtocol : boolean</code>
</li>
<li><code>proxyOutURL : String</code>
<div><div>
 Add your local proxy as following: <b>http(s)://host:port</b>
 <br>
  or Leave empty if not using a local proxy. The following proxy configurations are not supported: 
 <ul>
  <li>PAC (proxy auto-config).</li>
  <li>Automatic configuration script.</li>
 </ul>
</div></div>

</li>
<li><code>credentialsProxyId : String</code>
</li>
<li><code>retry : String</code>
</li>
<li><code>retryDelay : String</code>
</li>
<li><code>retryOccurrences : String</code>
</li>
<li><code>authenticateWithToken : boolean</code>
<div><div>
 <div>
  From LRE 2021 R1, you can use a token associated with your user for authentication.
 </div>
 <div>
  If LRE is defined to use SSO, this will be the only way for this plugin to authenticate to LRE.
 </div>
 <div>
  To use it, have a token issued to your user in LRE.
 </div>
 <div>
  In Jenkins, create new Jenkins credentials based on the LRE token you received: use the ClientIdKey in the Username and the ClientSecretKey key in the password.
 </div>
 <div>
  Then use the new Jenkins credentials with this checkbox switched on.
 </div>
</div></div>

</li>
</ul>


++++
=== `collectPullRequestsToAlmOctane`: ALM Octane pull-request collector
++++
<div><div>
 This step is responsible for collecting pull requests from the SCM tool and injecting them to ALM Octane. See help information in <a href="https://admhelp.microfocus.com/octane/en/latest/Online/Content/UserGuide/articles-pull-requests.htm" rel="nofollow">ALM Octane Help Center</a>. 
 <br>
 <br>
  In addition, this step is used to define the scm repositories templates that are used by ALM Octane to link to your repository viewer. To configure templates in ALM Octane, access Settings &gt; Spaces. Select a workspace and click DevOps &gt; SCM Repositories. Follow the on-screen instructions. 
 <br>
 <br>
  Every time pull requests are sent to ALM Octane the last update time is saved. The next time, only pull requests and commits that were updated after this time will be sent to ALM Octane. 
 <br>
 <br>
  Supported version of ALM Octane: 15.0.49 and later. 
 <br>
 <br>
  You can change the behaviour of this step by adding the following parameters to the job: 
 <ul>
  <li><b>pullrequests_min_update_time</b>: Use this parameter to override the last update time that is updated after each successful injection to ALM Octane.</li>
  <br>
  <li><b>pullrequests_max_pr_to_collect</b>: Max number of pull requests to collect. Default is 100.</li>
  <br>
  <li><b>pullrequests_max_commits_to_collect</b>: Max number of commits to collect for each pull request. Default is 100.</li>
  <br>
 </ul>
 <br>
 <br><b>Supported SCM Tools: </b>
 <br>
 <table width="100%">
  <thead>
   <tr>
    <td>SCM Tool</td>
    <td>Supported types of authentication</td>
    <td>How to create PAT (Personal access token)</td>
   </tr>
  </thead>
  <tbody>
   <tr>
    <td>Bitbucket Server</td>
    <td>User/password and PAT</td>
    <td>Click on your profile icon -&gt; Manage account -&gt; Personal access tokens -&gt; Create a token (Assign Read permissions for both Projects and Repositories)</td>
   </tr>
   <tr>
    <td>Github Cloud</td>
    <td>PAT only</td>
    <td rowspan="2">Click on your profile icon -&gt; Settings -&gt; Developer settings -&gt; Personal access tokens -&gt; Generate new token (Uncheck all scopes to grants read-only access)</td>
   </tr>
   <tr>
    <td>Github Server</td>
    <td>User/password and PAT</td>
   </tr>
  </tbody>
 </table>
 <br>
  Note : To create PAT credentials in Jenkins , use "Secret text" kind of credentials in "Add Credentials" dialog
</div></div>
<ul><li><code>configurationId : String</code>
</li>
<li><code>workspaceId : String</code>
</li>
<li><code>scmTool : String</code>
</li>
<li><code>repositoryUrl : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>sourceBranchFilter : String</code>
</li>
<li><code>targetBranchFilter : String</code>
</li>
<li><code>useSSHFormat : boolean</code> (optional)
<div><div>
 Select this if all other jobs that use this repository and are connected to ALM Octane pipelines use SSH format. It is important to be consistent with other jobs that use this repository. 
 <br>
  This will ensure that ALM Octane correctly identifies the SCM repository associated with commits, branches and pull requests.
</div></div>

</li>
</ul>


++++
=== `runFromAlmBuilder`: Execute OpenText functional tests from OpenText ALM
++++
<ul><li><code>almServerName : String</code>
</li>
<li><code>almCredentialsScope : String</code>
<div><div>
 Select the scope of the credentials used for connecting to the specified ALM Server: 
 <ul>
  <li><b>Job (local) credentials</b>: This option requires to provide the credentials right here at job level.</li>
  <li><b>System (global) credentials</b>: This option allows the selection of UserName or ClientID from a dropdown list with global credentials.</li>
 </ul>
</div></div>

</li>
<li><code>almUserName : String</code>
</li>
<li><code>almPassword : String</code>
</li>
<li><code>almDomain : String</code>
</li>
<li><code>almProject : String</code>
</li>
<li><code>almTestSets : String</code>
<div><div>
 List of test sets to run. Each line contains a path to a test set or a test set folder.
 <br>
  For example: Root\subFolder1\subFolder2\testSetToRun . 
 <br>
  In case you want to parameterize the tests please specify the parameters and their values like:
 <br>
  Root\subFolder1\subFolder2\testSetToRun "Parameter1":"&amp;ltstringvalue&gt;",..., "ParameterN":&amp;ltnumbervalue&gt; 
 <br>
  Also, for better specification of parameters you may use the "Specify test parameters" section below.
</div></div>

</li>
<li><code>almRunResultsMode : String</code>
</li>
<li><code>almTimeout : String</code>
<div><div>
 Number of seconds before timeout. If left empty timeout is unlimited.
</div></div>

</li>
<li><code>almRunMode : String</code>
<div><div>
 Defines how the test set is executed: 
 <ul>
  <li><b>Run locally</b>: The test set is run on the machine that performs the build.</li>
  <li><b>Run remotely</b>: The test set is run on the host defined in the <b>Testing Tool host</b> field.</li>
  <li><b>Run on planned host</b>: The test set is run on the host defined in ALM.</li>
 </ul>
</div></div>

</li>
<li><code>almRunHost : String</code>
<div><div>
 If the <b>Run mode</b> field is set to <b>Run remotely</b>, use this field to specify the name of the host that runs the test set.
</div></div>

</li>
<li><code>almClientID : String</code>
</li>
<li><code>almApiKey : String</code>
</li>
<li><code>isSSOEnabled : boolean</code>
<div><div>
 Obtain the Client ID and API key secret from your ALM site administrator.
</div></div>

</li>
<li><code>areParametersEnabled : boolean</code>
</li>
<li><code>specifyParametersModel</code>
<ul><b>Nested Object</b>
<li><code>parameterJson : String</code>
</li>
</ul></li>
<li><code>isFilterTestsEnabled : boolean</code> (optional)
</li>
<li><code>filterTestsModel</code> (optional)
<ul><b>Nested Object</b>
<li><code>blockedCheckbox : boolean</code>
</li>
<li><code>failedCheckbox : boolean</code>
</li>
<li><code>notCompletedCheckbox : boolean</code>
</li>
<li><code>noRunCheckbox : boolean</code>
</li>
<li><code>passedCheckbox : boolean</code>
</li>
<li><code>testName : String</code> (optional)
</li>
</ul></li>
<li><code>almServerSettingsModel</code> (optional)
<ul><b>Nested Object</b>
<li><code>almServerName : String</code>
</li>
<li><code>almServerUrl : String</code>
</li>
<li><code>almCredentials</code>
<ul><b>Array / List of Nested Object</b>
<li><code>almUsername : String</code>
</li>
<li><code>almPassword : String</code>
</li>
</ul></li>
<li><code>almSSOCredentials</code>
<ul><b>Array / List of Nested Object</b>
<li><code>almClientID : String</code>
</li>
<li><code>almApiKeySecret : String</code>
</li>
</ul></li>
</ul></li>
</ul>


++++
=== `runFromCodelessBuilder`: Execute OpenText codeless tests
++++
<ul></ul>


++++
=== `runFromFSBuilder`: Execute OpenText tests from file system
++++
<ul><li><code>fsTests : String</code>
<div><div>
 List of tests or folders that contain tests, to run. Each line should contain a single test, folder, or MTB file. 
 <br>
  In case you want to parameterize the tests please specify the parameters and their values like:
 <br>
  &amp;ltTestPath&gt; "Parameter1":"&amp;ltstringvalue&gt;",..., "ParameterN":&amp;ltnumbervalue&gt; 
 <br>
  Also, for better specification of parameters you may use the "Specify test parameters" section below.
</div></div>

</li>
<li><code>areParametersEnabled : boolean</code>
</li>
<li><code>specifyParametersModel</code>
<ul><b>Nested Object</b>
<li><code>parameterJson : String</code>
</li>
</ul></li>
<li><code>fileSystemTestSetModel</code>
<ul><b>Nested Object</b>
<li><code>fileSystemTestSet</code>
<div><div>
 File system test set help.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>tests : String</code>
<div><div>
 List of tests or folders that contain tests, to run. Each line should contain a single test, folder, or MTB file.
</div></div>

</li>
<li><code>parallelRunnerEnvironments</code>
<ul><b>Array / List of Nested Object</b>
<li><code>environment : String</code>
<div><div>
 Environment help string.
</div></div>

</li>
<li><code>environmentType : String</code>
</li>
</ul></li>
</ul></li>
</ul></li>
<li><code>summaryDataLogModel</code>
<ul><b>Nested Object</b>
<li><code>logVusersStates : boolean</code>
<div><div>
 Display the number of virtual users in each state.
</div></div>

</li>
<li><code>logErrorCount : boolean</code>
<div><div>
 Display the number of controller errors.
</div></div>

</li>
<li><code>logTransactionStatistics : boolean</code>
<div><div>
 Display the number of passed transactions, failed transactions and hits per second.
</div></div>

</li>
<li><code>pollingInterval : String</code>
<div><div>
 The rate at which the messages are displayed (in seconds). Default value is 10 seconds.
</div></div>

</li>
</ul></li>
<li><code>scriptRTSSetModel</code>
<ul><b>Nested Object</b>
<li><code>scripts</code>
<ul><b>Array / List of Nested Object</b>
<li><code>scriptName : String</code>
<div><div>
 The script name is found in Controller's Script Information dialog (Percentage Mode scenario) or Group Information dialog (Vuser Group Mode scenario).
</div></div>

</li>
<li><code>additionalAttributes</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
<li><code>description : String</code>
</li>
</ul></li>
</ul></li>
</ul></li>
<li><code>isParallelRunnerEnabled : boolean</code> (optional)
<div><div>
 <strong>Note</strong>: This mode is for UFT GUI test only.With it enabled, you can define multiple tests and the environments to run with.
 <br>
 <br>
  UFT will run on those environments in parallel(<strong>at most 4 environments</strong> simultaneously) for each test.
 <br>
 <br>
  Disabling this option will switch back to the normal view with the tests kept.
</div></div>

</li>
<li><code>uftSettingsModel</code> (optional)
<ul><b>Nested Object</b>
<li><code>selectedNode : String</code> (optional)
<div><div>
 Please select the corresponding slave machine setup in the main job configuration.
</div></div>

</li>
<li><code>numberOfReruns : String</code> (optional)
<div><div>
 Defines the maximum amount of test set reruns.
</div></div>

</li>
<li><code>cleanupTest : String</code> (optional)
<div><div>
 Test executed before the re-run process of the failed tests.
</div></div>

</li>
<li><code>onCheckFailedTest : String</code> (optional)
</li>
<li><code>fsTestType : String</code> (optional)
<div><div>
 Select which test category will run again when build fails. The user can rerun the entire set of tests or only the failed tests from the suite. If just certain tests fail, then only the selected tests will rerun.
</div></div>

</li>
<li><code>rerunSettingsModels</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>test : String</code> (optional)
</li>
<li><code>checked : boolean</code> (optional)
</li>
<li><code>numberOfReruns : int</code> (optional)
</li>
<li><code>cleanupTest : String</code> (optional)
</li>
</ul></li>
</ul></li>
<li><code>analysisTemplate : String</code> (optional)
<div><div>
 Apply a template for the build (path to a .tem file). Leave blank in order to use the default template.
</div></div>

</li>
<li><code>authModel</code> (optional)
<ul><b>Nested Object</b>
<li><code>mcUserName : String</code>
</li>
<li><code>mcPassword : String</code>
</li>
<li><code>mcTenantId : String</code>
</li>
<li><code>mcExecToken : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>cloudBrowserModel</code> (optional)
<ul><b>Nested Object</b>
<li><code>cloudBrowserUrl : String</code>
</li>
<li><code>cloudBrowserType : String</code>
</li>
<li><code>cloudBrowserVersion : String</code>
</li>
<li><code>cloudBrowserRegion : String</code>
</li>
<li><code>cloudBrowserOs : String</code>
</li>
</ul></li>
<li><code>controllerPollingInterval : String</code> (optional)
<div><div>
 Polling interval for checking the scenario status, in seconds. The default is 30 seconds.
</div></div>

</li>
<li><code>displayController : String</code> (optional)
<div><div>
 Display the controller while the scenario is running.
</div></div>

</li>
<li><code>fsAutActions : String</code> (optional)
</li>
<li><code>fsDeviceId : String</code> (optional)
</li>
<li><code>fsDevicesMetrics : String</code> (optional)
</li>
<li><code>fsExtraApps : String</code> (optional)
</li>
<li><code>fsInstrumented : String</code> (optional)
</li>
<li><code>fsJobId : String</code> (optional)
</li>
<li><code>fsLaunchAppName : String</code> (optional)
</li>
<li><code>fsManufacturerAndModel : String</code> (optional)
</li>
<li><code>fsOs : String</code> (optional)
</li>
<li><code>fsReportPath : String</code> (optional)
<div><div>
 The directory where the test results will be saved. If this is left empty the default directory will be used.
</div></div>

</li>
<li><code>fsTargetLab : String</code> (optional)
</li>
<li><code>fsTimeout : String</code> (optional)
<div><div>
 Timeout value in seconds. If left empty, there is no timeout.
</div></div>

</li>
<li><code>fsUftRunMode : String</code> (optional)
</li>
<li><code>ignoreErrorStrings : String</code> (optional)
<div><div>
 Ignore errors during the scenario run containing any of the strings listed below. For example: "Error: CPU usage for this load generator has exceeded 80%"
</div></div>

</li>
<li><code>mcServerName : String</code> (optional)
<div><div>
 Select the Digital Lab server. To add a server, go to Manage Jenkins &gt; Configure System &gt; Digital Lab.
</div></div>

</li>
<li><code>outEncoding : String</code> (optional)
<div><div>
 The encoding charset to be used when printing the text in the Console Output. The field is optional and the default value is UTF-8. The type UTF-16 is equivalent to Unicode.
</div></div>

</li>
<li><code>perScenarioTimeOut : String</code> (optional)
<div><div>
 The maximum time allotted for scenario execution, in minutes.
</div></div>

</li>
<li><code>proxySettings</code> (optional)
<ul><b>Nested Object</b>
<li><code>fsUseAuthentication : boolean</code>
</li>
<li><code>fsProxyAddress : String</code>
</li>
<li><code>fsProxyUserName : String</code>
</li>
<li><code>fsProxyPassword : String</code>
</li>
</ul></li>
<li><code>resultFileNames</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.Long, java.lang.String&gt;</code></li>
</ul></li>
<li><code>useSSL : boolean</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'RunLoadRunnerScript'])`: Run LoadRunner script
++++
<ul><li><code>scriptsPath : String</code>
</li>
</ul>


++++
=== `publishMicroFocusTestResults`: Publish OpenText tests result
++++
<ul><li><code>archiveTestResultsMode : String</code>
<div><div>
 To view the run results, do one of the following:
 <br>
  1) In the left pane, click the <b>Report and Summary</b> link to display the report link and the link to the report folder. From this link, you can open the run results directly in your browser or open the artifacts
 <br>
  2) From the <b>Build Artifacts:</b>
 <br>
  • Open the run_results.html to view the run results.
 <br>
  • Download the zipped report to your desired location and unzip it. In the <b>Run Results Viewer</b>, select the Results.xml file found inside the unzipped folder.
 <br>
  Note that this option is valid only when using the “Execute test from file system” build step.
</div></div>

</li>
</ul>


++++
=== `addALMOctaneSonarQubeListener`: ALM Octane SonarQube listener
++++
<div><div>
 See help information in <a href="https://admhelp.microfocus.com/octane/en/latest/Online/Content/AdminGuide/how-setup-Sonar-integration.htm" rel="nofollow">ALM Octane Help Center</a>
</div></div>
<ul><li><code>pushCoverage : boolean</code> (optional)
</li>
<li><code>pushVulnerabilities : boolean</code> (optional)
</li>
<li><code>skipWebhookCreation : boolean</code> (optional)
<div><div>
 The integration with SonarQube works by using Sonar’s webhook mechanism, and contains several phases: 
 <ol>
  <li>The plugin automatically configures a webhook in Sonar before the job runs (this requires an access token with global 'Administer' permission).</li>
  <li>When the Sonar analysis is ready, the SonarQube server calls the configured webhook.</li>
  <li>Results are then submitted to ALM Octane for further analysis (this requires an access token with 'Read' permissions).</li>
 </ol> If you cannot assign global 'Administer' permissions to the Sonar token (for the first phase), select "Skip webhook creation", and define a webhook manually in the Sonar server (either at the global level or project level) to the following URL: {jenkins_url}/webhooks/notify
</div></div>

</li>
<li><code>sonarServerUrl : String</code> (optional)
</li>
<li><code>sonarToken : String</code> (optional)
</li>
</ul>


++++
=== `sseBuild`: Execute OpenText tests using OpenText ALM Lab Management
++++
<ul><li><code>almServerName : String</code>
</li>
<li><code>almProject : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>clientType : String</code>
<div><div>
 Client type is required for some ALM above 12.60 in authentication.
</div></div>

</li>
<li><code>almDomain : String</code>
</li>
<li><code>runType : String</code>
</li>
<li><code>almEntityId : String</code>
</li>
<li><code>timeslotDuration : String</code>
</li>
<li><code>cdaDetails</code> (optional)
<ul><b>Nested Object</b>
<li><code>deploymentAction : String</code>
</li>
<li><code>deployedEnvironmentName : String</code>
</li>
<li><code>deprovisioningAction : String</code>
</li>
</ul></li>
<li><code>description : String</code> (optional)
</li>
<li><code>environmentConfigurationId : String</code> (optional)
<div><div>
 To find the ID of your environment configuration, right-click the entity, copy the URL, and paste it to a text editor. Use the number associated with the EntityID at the end of the URL.
</div></div>

</li>
<li><code>postRunAction : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'SvChangeModeBuilder'])`: SV: Change Mode of Virtual Service
++++
<ul><li><code>serverName : String</code>
</li>
<li><code>force : boolean</code>
<div><div>
 If set, service will be modified regardless it is locked by another user.
</div></div>

</li>
<li><code>mode</code>
<ul><li><b>Values:</b> <code>OFFLINE</code>, <code>SIMULATING</code>, <code>STAND_BY</code>, <code>LEARNING</code></li></ul></li>
<li><code>dataModel</code>
<ul><b>Nested Object</b>
<li><code>selectionType</code>
<ul><li><b>Values:</b> <code>BY_NAME</code>, <code>NONE</code>, <code>DEFAULT</code></li></ul></li>
<li><code>dataModel : String</code>
</li>
</ul></li>
<li><code>performanceModel</code>
<ul><b>Nested Object</b>
<li><code>selectionType</code>
<ul><li><b>Values:</b> <code>BY_NAME</code>, <code>NONE</code>, <code>OFFLINE</code>, <code>DEFAULT</code></li></ul></li>
<li><code>performanceModel : String</code>
</li>
</ul></li>
<li><code>serviceSelection</code>
<ul><b>Nested Object</b>
<li><code>selectionType</code>
<ul><li><b>Values:</b> <code>SERVICE</code>, <code>PROJECT</code>, <code>ALL_DEPLOYED</code>, <code>DEPLOY</code></li></ul></li>
<li><code>service : String</code>
</li>
<li><code>projectPath : String</code>
</li>
<li><code>projectPassword : String</code>
</li>
</ul></li>
</ul>


++++
=== `step([$class: 'SvDeployBuilder'])`: SV: Deploy Virtual Service
++++
<ul><li><code>serverName : String</code>
</li>
<li><code>force : boolean</code>
<div><div>
 If set, service will be redeployed regardless it is locked by another user.
</div></div>

</li>
<li><code>service : String</code>
<div><div>
 Name or ID of service to be deployed. All services from project are deployed if no service is specified.
</div></div>

</li>
<li><code>projectPath : String</code>
</li>
<li><code>projectPassword : String</code>
</li>
<li><code>firstAgentFallback : boolean</code>
<div><div>
 Use first agent of the same type if no agent with id referenced from virtual service exists on target server.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'SvExportBuilder'])`: SV: Export Virtual Service
++++
<ul><li><code>serverName : String</code>
</li>
<li><code>force : boolean</code>
<div><div>
 If set, service will be modified regardless it is locked by another user.
</div></div>

</li>
<li><code>targetDirectory : String</code>
<div><div>
 Directory where exported services will be written.
</div></div>

</li>
<li><code>cleanTargetDirectory : boolean</code>
<div><div>
 If checked, all direct subfolders of target directory containing a project file (*.vproj) will be deleted before export.
</div></div>

</li>
<li><code>serviceSelection</code>
<ul><b>Nested Object</b>
<li><code>selectionType</code>
<ul><li><b>Values:</b> <code>SERVICE</code>, <code>PROJECT</code>, <code>ALL_DEPLOYED</code>, <code>DEPLOY</code></li></ul></li>
<li><code>service : String</code>
</li>
<li><code>projectPath : String</code>
</li>
<li><code>projectPassword : String</code>
</li>
</ul></li>
<li><code>switchToStandByFirst : boolean</code>
<div><div>
 Switch service to Stand-By mode to finish current learning before exporting learned data.
</div></div>

</li>
<li><code>archive : boolean</code>
<div><div>
 If set, Export service(s) as project archive(s) (.vproja).
</div></div>

</li>
</ul>


++++
=== `step([$class: 'SvUndeployBuilder'])`: SV: Undeploy Virtual Service
++++
<ul><li><code>serverName : String</code>
</li>
<li><code>continueIfNotDeployed : boolean</code>
<div><div>
 Don't fail if any service marked to be undeployed is not deployed on server.
</div></div>

</li>
<li><code>force : boolean</code>
<div><div>
 If set, service will be undeployed regardless it is locked by another user.
</div></div>

</li>
<li><code>serviceSelection</code>
<ul><b>Nested Object</b>
<li><code>selectionType</code>
<ul><li><b>Values:</b> <code>SERVICE</code>, <code>PROJECT</code>, <code>ALL_DEPLOYED</code>, <code>DEPLOY</code></li></ul></li>
<li><code>service : String</code>
</li>
<li><code>projectPath : String</code>
</li>
<li><code>projectPassword : String</code>
</li>
</ul></li>
</ul>


++++
=== `uploadResultToALM`: Upload test result to ALM
++++
<ul><li><code>almServerName : String</code>
<div><div>
 The name of the ALM Server.
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
<li><code>almDomain : String</code>
<div><div>
 The Domain of the project to be used.
</div></div>

</li>
<li><code>clientType : String</code>
<div><div>
 Client type is required for some ALM above 12.60 in authentication.
</div></div>

</li>
<li><code>almProject : String</code>
<div><div>
 The project to be used.
</div></div>

</li>
<li><code>testingFramework : String</code>
<div><div>
 The testing framework that is used when generate the testing result file.
</div></div>

</li>
<li><code>testingTool : String</code>
<div><div>
 The testing tool that is used when generate the testing result file.
</div></div>

</li>
<li><code>almTestFolder : String</code>
<div><div>
 The path of the test folder that will contain the uploaded test. The path doesn't include the Root test folder (Subject). 
 <br>
  For example, sampletestfolder\subfolder means, the tests will be uploaded to test folder named 'subfolder', which is under the test folder named 'sampletestfolder', 
 <br>
  and 'sampletestfolder' is under the root test folder 'Subject'.
</div></div>

</li>
<li><code>almTestSetFolder : String</code>
<div><div>
 The path of the testset folder that will contain the uploaded testset. The path doesn't include the Root testset folder. 
 <br>
  For example, sampletestsetfolder\subfolder means, the testsets will be uploaded to testset folder named 'subfolder', which is under the testset folder named 'sampletestsetfolder', 
 <br>
  and 'sampletestsetfolder' is under the root testset folder 'Root'.
</div></div>

</li>
<li><code>almTimeout : String</code>
<div><div>
 Number of seconds before timeout. If left empty timeout is unlimited.
</div></div>

</li>
<li><code>testingResultFile : String</code>
<div><div>
 The condition to find the testing result file, start from the root path of the job. For example, **/junitResult.xml to find testing result file for Junit Plugin, **/testng-results.xml to find testing result file for TestNG plugin.
</div></div>

</li>
<li><code>testingAttachments : String</code>
</li>
<li><code>jenkinsServerUrl : String</code>
<div><div>
 The HTTP URL of the Jenkins Server, form example, http://myjenkinsserver.test.com:8080 .
</div></div>

</li>
</ul>


++++
=== `convertTestsToRun`: ALM Octane testing framework converter
++++
<div><div>
 This build step is intended to support execution of automated tests from ALM Octane.
 <br>
  The builder searches for the "testsToRun" parameter which is sent from ALM Octane as part of the execution framework.
 <br>
  Once it is found, its value is converted to the format of the selected testing framework, and injected to the "testsToRunConverted" environment parameter.
 <br>
  Later, the new parameter can be used in the appropriate execution builder. 
 <ul>
  <li>To use in parameter <i>textboxes</i>, use the following syntax: <b>${testsToRunConverted}</b></li>
  <br>
  <li>To use in the <i>scripts</i>, use the following syntax: 
   <ul>
    <li>Linux shell: $testsToRunConverted</li>
    <li>Windows batch command: %testsToRunConverted%</li>
    <li>Pipeline script (workflow job): "${params.testsToRunConverted}"</li>
   </ul><br>
    See examples in the tables below: 
   <table width="100%">
    <thead>
     <tr>
      <td width="20%">Framework</td>
      <td>Linux shell</td>
     </tr>
    </thead>
    <tbody>
     <tr>
      <td>Maven Surefire</td>
      <td>mvn clean -Dtest=$testsToRunConverted test</td>
     </tr>
     <tr>
      <td>Maven Failsafe</td>
      <td>mvn clean -Dit.test=$testsToRunConverted verify</td>
     </tr>
     <tr>
      <td>Gradle</td>
      <td>gradle test $testsToRunConverted</td>
     </tr>
     <tr>
      <td>Protractor</td>
      <td>protractor conf.js --grep="$testsToRunConverted"</td>
     </tr>
     <tr>
      <td>Cucumber-JVM over Maven/<br>
        BDD Scenario</td>
      <td>mvn clean -Dcucumber.options="$testsToRunConverted" test</td>
     </tr>
     <tr>
      <td>JBehave over Maven</td>
      <td>mvn clean -Dfeatures="$testsToRunConverted" test</td>
     </tr>
    </tbody>
   </table><br>
   <table width="100%">
    <thead>
     <tr>
      <td width="20%">Framework</td>
      <td>Windows batch command</td>
     </tr>
    </thead>
    <tbody>
     <tr>
      <td>Maven Surefire</td>
      <td>mvn clean -Dtest=%testsToRunConverted% test</td>
     </tr>
     <tr>
      <td>Maven Failsafe</td>
      <td>mvn clean -Dit.test=%testsToRunConverted% verify</td>
     </tr>
     <tr>
      <td>Gradle</td>
      <td>gradle test %testsToRunConverted%</td>
     </tr>
     <tr>
      <td>Protractor</td>
      <td>protractor conf.js --grep="%testsToRunConverted%"</td>
     </tr>
     <tr>
      <td>Cucumber-JVM over Maven/<br>
        BDD Scenario</td>
      <td>mvn clean -Dcucumber.options="%testsToRunConverted%" test</td>
     </tr>
     <tr>
      <td>JBehave over Maven</td>
      <td>mvn clean -Dfeatures="%testsToRunConverted%" test</td>
     </tr>
    </tbody>
   </table><br>
   <table width="100%">
    <thead>
     <tr>
      <td width="20%">Framework</td>
      <td>Pipeline script</td>
     </tr>
    </thead>
    <tbody>
     <tr>
      <td>Maven Surefire</td>
      <td>bat 'mvn clean -Dtest=${params.testsToRunConverted} test'</td>
     </tr>
     <tr>
      <td>Maven Failsafe</td>
      <td>bat 'mvn clean -Dit.test=${params.testsToRunConverted} verify'</td>
     </tr>
     <tr>
      <td>Gradle</td>
      <td>bat 'gradle test ${params.testsToRunConverted}'</td>
     </tr>
     <tr>
      <td>Protractor</td>
      <td>bat(/protractor conf.js --grep="${params.testsToRunConverted}"/)</td>
     </tr>
     <tr>
      <td>Cucumber-JVM over Maven/<br>
        BDD Scenario</td>
      <td>bat(/mvn clean -Dcucumber.options="${params.testsToRunConverted}" test/)</td>
     </tr>
     <tr>
      <td>JBehave over Maven</td>
      <td>bat(/mvn clean -Dfeatures="${testsToRunConverted}" test/)</td>
     </tr>
    </tbody>
   </table><br></li>
 </ul>
 <br>
  Notes/Limitations : 
 <br>
 <ul>
  <li><b>UFT</b>: In order to build a UFT MTBX file, this builder needs to know the test check-out directory. By default this is the job workspace directory. If tests are checked out in another directory, define in the job a String parameter "testsToRunCheckoutDirectory" with the correct directory.</li>
  <li><b>JUnit/TestNG</b>: Supported for JUnit 4.7+, Surefire Plugin 2.19+, Failsafe Plugin 2.12.1+.</li>
  <li><b>Cucumber-JVM over Maven</b>: If your project contains several run classes, specify a run class that will be used, otherwise all run classes will be executed by Cucumber. You can specify test runner by adding: '-Dtest=[runner class name]' to the Maven command</li>
  <li><b>JBehave over Maven</b>: read more about integration with JBehave <a href="https://github.com/MicroFocus/octane-jbehave-gherkin-reporter/blob/main/README.md" rel="nofollow">here</a></li>
 </ul>
 <br>
 <br>
  See more help information in <a href="https://admhelp.microfocus.com/octane/en/latest/Online/Content/AdminGuide/how-setup-testing-integration.htm" rel="nofollow">ALM Octane Help Center</a>
</div></div>
<ul><li><code>framework : String</code>
<div><div>
 Select the testing framework whose format you want to convert to.
</div></div>

</li>
<li><code>format : String</code>
<div><div>
 In the 'Custom conversion format' field, enter json that describes how to convert tests from raw format to the format of your testing framework. After conversion, the result is injected to the "testsToRunConverted" parameter. 
 <br>
 <br><i><b>Note</b>: Click "Validate" to check the correctness of the inserted configuration.</i>
 <br>
 <br>
  The following are the components that you can use in the "Custom conversion format" : 
 <ul>
  <li><b>testPattern</b> - describes the pattern for converting single test. All parameters that needs to be replaced be real test data, should start with $, for example <b>$package</b>, <b>$class</b>, <b>$testName</b>, <b>$externalRunId</b>, <b>$myCustomParam</b>. All other characters in the pattern will appear in the final result as is.</li>
  <li><b>testDelimiter</b> - the delimiter used to separate different tests.</li>
  <li><b>prefix</b> - a prefix for the whole conversion result.</li>
  <li><b>suffix</b> - a suffix for the whole conversion result.</li>
  <li><b>allowDuplication</b> - indicate whether duplications are allowed in final result. Default is true.</li>
  <li><b>testsToRunConvertedParameter</b> - the parameter name that will contain the conversion result. Default value is "testsToRunConverted".</li>
  <li><b>replacements</b> - the array of replace methods.</li>
 </ul> The minimal configuration is: 
 <br>
 <br>
 <pre>
{
    "testPattern": "$package.$class#$testName",
    "testDelimiter": ","
}
    </pre>
 <br>
 For example:
 <br>
 <br>
  The <i>testsToRun</i> parameter received 2 tests separated by a semicolon: <b>v1:myPackage1|myClass1|myTest1<i>;</i>myPackage2|myClass2|myTest2</b>
 <br>
  The defined <i>testPattern</i> is: <b>$package.$class#$testName</b>
 <br>
  The defined <i>testDelimiter</i> is: <b> , </b>
 <ul>
  <li><b>$package</b> variable will get a value of <i>myPackage1</i> for the first test and <i>myPackage2</i> for the second test.</li>
  <li><b>$class</b> variable will get a value of <i>myClass1</i> for the first test and <i>myClass2</i> for the second test.</li>
  <li><b>$testName</b> variable will get a value of <i>myTest1</i> for the first test and <i>myTest2</i> for the second test.</li>
 </ul>
 <br>
 The <i>testsToRunConverted</i> parameter will be equal: <b>myPackage1.myClass1#myTest1,myPackage2.myClass2#myTest2</b>
 <br>
 <br>
  Optional: 
 <br>
  There is a possibility to alter values received from ALM Octane, for example to set lowercase to the testName, replace spaces by '_', and so on. 
 <br>
  Here are examples of available replace methods. Each replace method contains "target" property that define what parts of the test pattern are affected by replace method, available values are $package,$class,$testName. Its possible to put several values separated by '|'. The replacements are executed in the order they appear in the 'Custom conversion format' json. 
 <pre>
"replacements": [
{
    "type": "<b>replaceRegex</b>",
    "target": "$package|$class|$testName",
    "regex": "aaa",
    "replacement": "bbb",
    "description": "Replaces all the sequence of characters matching the regex with a replacement string."
},{
    "type": "<b>replaceRegexFirst</b>",
    "target": "$package|$class|$testName",
    "regex": "aaa",
    "replacement": "bbb",
    "description": "Replaces the first substring that matches the given regex with the given replacement. For example, given regex '@(.*)@.*' , replacement '$1', and test name '@myTag@ my test name' - will replace test name by the content located between @, that is - 'myTag'."
},{
    "type": "<b>replaceString</b>",
    "target": "$package|$class|$testName",
    "string": "xxx",
    "replacement": "yyy",
    "description": "Replaces all occurrences of ‘string’ with ‘replacement’."
},{
    "type": "<b>joinString</b>",
    "target": "$package|$class|$testName",
    "prefix": "xxx",
    "suffix": "yyy",
    "description": "Add prefix and suffix to the test template."
},{
    "type": "<b>toLowerCase</b>",
    "target": "$package|$class|$testName",
    "description": "Convert test template to lower case."
},{
    "type": "<b>toUpperCase</b>",
    "target": "$package|$class|$testName",
    "description": "Convert test template to upper  case."
},{
    "type": "<b>notLatinAndDigitToOctal</b>",
    "target": "$package|$class|$testName",
    "description": "Replaces all non-latin characters and digits ^[a-zA-Z0-9] to their ASCII octal value."
}]
</pre>
</div></div>

</li>
</ul>


++++
=== `publishCodeCoverage`: ALM Octane code coverage publisher
++++
<div><div>
 See help information in <a href="https://admhelp.microfocus.com/octane/en/latest/Online/Content/UserGuide/pipelines-code-coverage.htm" rel="nofollow">ALM Octane Help Center</a>
</div></div>
<ul><li><code>jacocoPathPattern : String</code>
</li>
<li><code>lcovPathPattern : String</code>
</li>
</ul>


++++
=== `svChangeModeStep`: SV: Change Mode of Virtual Service
++++
<ul><li><code>serverName : String</code>
</li>
<li><code>force : boolean</code>
</li>
<li><code>mode</code>
<ul><li><b>Values:</b> <code>OFFLINE</code>, <code>SIMULATING</code>, <code>STAND_BY</code>, <code>LEARNING</code></li></ul></li>
<li><code>dataModel</code>
<ul><b>Nested Object</b>
<li><code>selectionType</code>
<ul><li><b>Values:</b> <code>BY_NAME</code>, <code>NONE</code>, <code>DEFAULT</code></li></ul></li>
<li><code>dataModel : String</code>
</li>
</ul></li>
<li><code>performanceModel</code>
<ul><b>Nested Object</b>
<li><code>selectionType</code>
<ul><li><b>Values:</b> <code>BY_NAME</code>, <code>NONE</code>, <code>OFFLINE</code>, <code>DEFAULT</code></li></ul></li>
<li><code>performanceModel : String</code>
</li>
</ul></li>
<li><code>serviceSelection</code>
<ul><b>Nested Object</b>
<li><code>selectionType</code>
<ul><li><b>Values:</b> <code>SERVICE</code>, <code>PROJECT</code>, <code>ALL_DEPLOYED</code>, <code>DEPLOY</code></li></ul></li>
<li><code>service : String</code>
</li>
<li><code>projectPath : String</code>
</li>
<li><code>projectPassword : String</code>
</li>
</ul></li>
</ul>


++++
=== `svDeployStep`: SV: Deploy Virtual Service
++++
<ul><li><code>serverName : String</code>
</li>
<li><code>force : boolean</code>
</li>
<li><code>service : String</code>
</li>
<li><code>projectPath : String</code>
</li>
<li><code>projectPassword : String</code>
</li>
<li><code>firstAgentFallback : boolean</code>
</li>
</ul>


++++
=== `svExportStep`: SV: Export Virtual Service
++++
<ul><li><code>serverName : String</code>
</li>
<li><code>force : boolean</code>
</li>
<li><code>targetDirectory : String</code>
</li>
<li><code>cleanTargetDirectory : boolean</code>
</li>
<li><code>serviceSelection</code>
<ul><b>Nested Object</b>
<li><code>selectionType</code>
<ul><li><b>Values:</b> <code>SERVICE</code>, <code>PROJECT</code>, <code>ALL_DEPLOYED</code>, <code>DEPLOY</code></li></ul></li>
<li><code>service : String</code>
</li>
<li><code>projectPath : String</code>
</li>
<li><code>projectPassword : String</code>
</li>
</ul></li>
<li><code>switchToStandByFirst : boolean</code>
</li>
<li><code>archive : boolean</code>
</li>
</ul>


++++
=== `svUndeployStep`: SV: Undeploy Virtual Service
++++
<ul><li><code>serverName : String</code>
</li>
<li><code>continueIfNotDeployed : boolean</code>
</li>
<li><code>force : boolean</code>
</li>
<li><code>serviceSelection</code>
<ul><b>Nested Object</b>
<li><code>selectionType</code>
<ul><li><b>Values:</b> <code>SERVICE</code>, <code>PROJECT</code>, <code>ALL_DEPLOYED</code>, <code>DEPLOY</code></li></ul></li>
<li><code>service : String</code>
</li>
<li><code>projectPath : String</code>
</li>
<li><code>projectPassword : String</code>
</li>
</ul></li>
</ul>


++++
=== `uftScenarioLoad`: Run UFT scenario
++++
<ul><li><code>testPaths : String</code>
</li>
<li><code>archiveTestResultsMode : String</code>
<div><div>
 To view the run results, do one of the following:
 <br>
  1) In the left pane, click the <b>Report and Summary</b> link to display the report link and the link to the report folder. From this link, you can open the run results directly in your browser or open the artifacts
 <br>
  2) From the <b>Build Artifacts:</b>
 <br>
  • Open the run_results.html to view the run results.
 <br>
  • Download the zipped report to your desired location and unzip it. In the <b>Run Results Viewer</b>, select the Results.xml file found inside the unzipped folder.
 <br>
  Note that this option is valid only when using the “Execute test from file system” build step.
</div></div>

</li>
<li><code>fsReportPath : String</code> (optional)
</li>
<li><code>fsTimeout : String</code> (optional)
</li>
<li><code>fsUftRunMode : String</code> (optional)
</li>
<li><code>runFromFileBuilder</code> (optional)
<ul><b>Nested Object</b>
<li><code>fsTests : String</code>
<div><div>
 List of tests or folders that contain tests, to run. Each line should contain a single test, folder, or MTB file. 
 <br>
  In case you want to parameterize the tests please specify the parameters and their values like:
 <br>
  &amp;ltTestPath&gt; "Parameter1":"&amp;ltstringvalue&gt;",..., "ParameterN":&amp;ltnumbervalue&gt; 
 <br>
  Also, for better specification of parameters you may use the "Specify test parameters" section below.
</div></div>

</li>
<li><code>areParametersEnabled : boolean</code>
</li>
<li><code>specifyParametersModel</code>
<ul><b>Nested Object</b>
<li><code>parameterJson : String</code>
</li>
</ul></li>
<li><code>fileSystemTestSetModel</code>
<ul><b>Nested Object</b>
<li><code>fileSystemTestSet</code>
<div><div>
 File system test set help.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>tests : String</code>
<div><div>
 List of tests or folders that contain tests, to run. Each line should contain a single test, folder, or MTB file.
</div></div>

</li>
<li><code>parallelRunnerEnvironments</code>
<ul><b>Array / List of Nested Object</b>
<li><code>environment : String</code>
<div><div>
 Environment help string.
</div></div>

</li>
<li><code>environmentType : String</code>
</li>
</ul></li>
</ul></li>
</ul></li>
<li><code>summaryDataLogModel</code>
<ul><b>Nested Object</b>
<li><code>logVusersStates : boolean</code>
<div><div>
 Display the number of virtual users in each state.
</div></div>

</li>
<li><code>logErrorCount : boolean</code>
<div><div>
 Display the number of controller errors.
</div></div>

</li>
<li><code>logTransactionStatistics : boolean</code>
<div><div>
 Display the number of passed transactions, failed transactions and hits per second.
</div></div>

</li>
<li><code>pollingInterval : String</code>
<div><div>
 The rate at which the messages are displayed (in seconds). Default value is 10 seconds.
</div></div>

</li>
</ul></li>
<li><code>scriptRTSSetModel</code>
<ul><b>Nested Object</b>
<li><code>scripts</code>
<ul><b>Array / List of Nested Object</b>
<li><code>scriptName : String</code>
<div><div>
 The script name is found in Controller's Script Information dialog (Percentage Mode scenario) or Group Information dialog (Vuser Group Mode scenario).
</div></div>

</li>
<li><code>additionalAttributes</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
<li><code>description : String</code>
</li>
</ul></li>
</ul></li>
</ul></li>
<li><code>isParallelRunnerEnabled : boolean</code> (optional)
<div><div>
 <strong>Note</strong>: This mode is for UFT GUI test only.With it enabled, you can define multiple tests and the environments to run with.
 <br>
 <br>
  UFT will run on those environments in parallel(<strong>at most 4 environments</strong> simultaneously) for each test.
 <br>
 <br>
  Disabling this option will switch back to the normal view with the tests kept.
</div></div>

</li>
<li><code>uftSettingsModel</code> (optional)
<ul><b>Nested Object</b>
<li><code>selectedNode : String</code> (optional)
<div><div>
 Please select the corresponding slave machine setup in the main job configuration.
</div></div>

</li>
<li><code>numberOfReruns : String</code> (optional)
<div><div>
 Defines the maximum amount of test set reruns.
</div></div>

</li>
<li><code>cleanupTest : String</code> (optional)
<div><div>
 Test executed before the re-run process of the failed tests.
</div></div>

</li>
<li><code>onCheckFailedTest : String</code> (optional)
</li>
<li><code>fsTestType : String</code> (optional)
<div><div>
 Select which test category will run again when build fails. The user can rerun the entire set of tests or only the failed tests from the suite. If just certain tests fail, then only the selected tests will rerun.
</div></div>

</li>
<li><code>rerunSettingsModels</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>test : String</code> (optional)
</li>
<li><code>checked : boolean</code> (optional)
</li>
<li><code>numberOfReruns : int</code> (optional)
</li>
<li><code>cleanupTest : String</code> (optional)
</li>
</ul></li>
</ul></li>
<li><code>analysisTemplate : String</code> (optional)
<div><div>
 Apply a template for the build (path to a .tem file). Leave blank in order to use the default template.
</div></div>

</li>
<li><code>authModel</code> (optional)
<ul><b>Nested Object</b>
<li><code>mcUserName : String</code>
</li>
<li><code>mcPassword : String</code>
</li>
<li><code>mcTenantId : String</code>
</li>
<li><code>mcExecToken : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>cloudBrowserModel</code> (optional)
<ul><b>Nested Object</b>
<li><code>cloudBrowserUrl : String</code>
</li>
<li><code>cloudBrowserType : String</code>
</li>
<li><code>cloudBrowserVersion : String</code>
</li>
<li><code>cloudBrowserRegion : String</code>
</li>
<li><code>cloudBrowserOs : String</code>
</li>
</ul></li>
<li><code>controllerPollingInterval : String</code> (optional)
<div><div>
 Polling interval for checking the scenario status, in seconds. The default is 30 seconds.
</div></div>

</li>
<li><code>displayController : String</code> (optional)
<div><div>
 Display the controller while the scenario is running.
</div></div>

</li>
<li><code>fsAutActions : String</code> (optional)
</li>
<li><code>fsDeviceId : String</code> (optional)
</li>
<li><code>fsDevicesMetrics : String</code> (optional)
</li>
<li><code>fsExtraApps : String</code> (optional)
</li>
<li><code>fsInstrumented : String</code> (optional)
</li>
<li><code>fsJobId : String</code> (optional)
</li>
<li><code>fsLaunchAppName : String</code> (optional)
</li>
<li><code>fsManufacturerAndModel : String</code> (optional)
</li>
<li><code>fsOs : String</code> (optional)
</li>
<li><code>fsReportPath : String</code> (optional)
<div><div>
 The directory where the test results will be saved. If this is left empty the default directory will be used.
</div></div>

</li>
<li><code>fsTargetLab : String</code> (optional)
</li>
<li><code>fsTimeout : String</code> (optional)
<div><div>
 Timeout value in seconds. If left empty, there is no timeout.
</div></div>

</li>
<li><code>fsUftRunMode : String</code> (optional)
</li>
<li><code>ignoreErrorStrings : String</code> (optional)
<div><div>
 Ignore errors during the scenario run containing any of the strings listed below. For example: "Error: CPU usage for this load generator has exceeded 80%"
</div></div>

</li>
<li><code>mcServerName : String</code> (optional)
<div><div>
 Select the Digital Lab server. To add a server, go to Manage Jenkins &gt; Configure System &gt; Digital Lab.
</div></div>

</li>
<li><code>outEncoding : String</code> (optional)
<div><div>
 The encoding charset to be used when printing the text in the Console Output. The field is optional and the default value is UTF-8. The type UTF-16 is equivalent to Unicode.
</div></div>

</li>
<li><code>perScenarioTimeOut : String</code> (optional)
<div><div>
 The maximum time allotted for scenario execution, in minutes.
</div></div>

</li>
<li><code>proxySettings</code> (optional)
<ul><b>Nested Object</b>
<li><code>fsUseAuthentication : boolean</code>
</li>
<li><code>fsProxyAddress : String</code>
</li>
<li><code>fsProxyUserName : String</code>
</li>
<li><code>fsProxyPassword : String</code>
</li>
</ul></li>
<li><code>resultFileNames</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.Long, java.lang.String&gt;</code></li>
</ul></li>
<li><code>useSSL : boolean</code> (optional)
</li>
</ul></li>
<li><code>runResultRecorder</code> (optional)
<ul><b>Nested Object</b>
<li><code>archiveTestResultsMode : String</code>
<div><div>
 To view the run results, do one of the following:
 <br>
  1) In the left pane, click the <b>Report and Summary</b> link to display the report link and the link to the report folder. From this link, you can open the run results directly in your browser or open the artifacts
 <br>
  2) From the <b>Build Artifacts:</b>
 <br>
  • Open the run_results.html to view the run results.
 <br>
  • Download the zipped report to your desired location and unzip it. In the <b>Run Results Viewer</b>, select the Results.xml file found inside the unzipped folder.
 <br>
  Note that this option is valid only when using the “Execute test from file system” build step.
</div></div>

</li>
</ul></li>
</ul>


++++
