= IBM Security AppScan Standard Scanner
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/ibm-security-appscanstandard-scanner">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'AppScanStandardBuilder'])`: Run AppScan Standard
++++
<ul><li><code>startingURL : String</code>
<div><div>
 Insert the URL that you want AppScan Standard to start scanning from. 
 <p>Spiders will find the remaining URLs in the domain to be included for scanning.</p>
</div></div>

</li>
<li><code>installation : String</code>
</li>
<li><code>additionalCommands : String</code> (optional)
<div><div>
 Provide additional and optional commands to run on AppScan Standard CLI. 
 <pre>
AppScanCMD exec|ex|e

        Parameters:
        [ /dest_scan|/dest|/d  ]
        [ /base_scan|/base|/b  ]
        [ /old_host|/ohost|/oh  ]
        [ /new_host|/nhost|/nh  ]
        [ /scan_template|/stemplate|/st  ]
        [ /login_file|/lfile|/lf  ]
        [ /multi_step_file|/mstepfile|/mf  ]
        [ /manual_explore_file|/mexplorefile|/mef  ]
        [ /policy_file|/pfile|/pf  ]
        [ /additional_domains|/adomains|/ad  ]
        [ /report_file|/rf  ]
        [ /report_type|/rt  {xml} ]
        [ /min_severity|/msev  {informational} ]
        [ /test_type|/tt  ]
        [ /report_template|/rtemplate|/rtm  {CliDefault} ]

        Flags:
        [ /verbose|/v {false} ]
        [ /scan_log|/sl {false} ]
        [ /explore_only|/eo {false} ]
        [ /test_only|/to {false} ]
        [ /multi_step|/mstep|/ms {false} ]
        [ /continue|/c {false} ]
        [ /merge_manual_explore_requests|/mmer {false} ]
        [ /include_responses|/ir {false} ]
        [ /open_proxy|/oprxy|/opr /listening_port|/lport|/lp  ]

        Creates new scan with base_scan's configuration
    saving dest_scan and creating report, if configured.

AppScanCMD report|rep|r

        Parametrs:
        /base_scan|/base|/b 
        /report_file|/rf 
        /report_type|/rt 
        [ /min_severity|/msev  {informational} ]
        [ /test_type|/tt  ]
        [ /report_template|/rtemplate|/rtm  {CliDefault} ]

        Flags:
        [ /verbose|/v {false} ]

        Creates a report for base_scan.

AppScanCMD close_proxy|cprxy|cpr

        Closes AppScan proxy if was previously opened.
        
More info. at:
(9.0.3.2 User Guide) CLI - Chapter 15 - CLI - Page 315
http://www-01.ibm.com/support/docview.wss?uid=swg27048015#2
        
</pre>
</div></div>

</li>
<li><code>authScan : boolean</code> (optional)
<div><div>
 Checking this option will allow AppScan Stardard to spider and scan a website using authentication, optimizing the results obtained in the report. 
 <p>If the website contains private information accessed only by logging in this option should be checked and credentials provided to increase dynamic security coverage.</p>
</div></div>

</li>
<li><code>authScanPw : String</code> (optional)
<div><div>
 Provide the password corresponding to the account's user name inserted above. 
 <p>Providing an account with higher authorization (such as Administrator) will increase the attack surface and therefore the scan coverage.</p>
</div></div>

</li>
<li><code>authScanRadio : boolean</code> (optional)
<div><div>
 Check "Recorded Login Sequence" if you have one for the website, this is, for the majority of the cases, the most reliable option for authenticated scanning. 
 <p>A login sequence may be recorded using AppScan Standard's GUI by following these steps:</p>
 <p>"Scan" &gt; "Scan Configuration" &gt; "Login Management" &gt; "Record" &gt; [ record your login...] &gt; "I am logged in to the site" &gt; "Details" (Tab) &gt; "Export" (small icon on the right side).</p>
 <p></p>
 <p>Check "Form Based Authentication" if you do not have a recorded login sequence, this option will require an user name and password combination and is not guaranteed to work for all scenarios.</p>
</div></div>

</li>
<li><code>authScanUser : String</code> (optional)
<div><div>
 Provide the user name of an account with access to the private functionalities of the website. 
 <p>Providing an account with higher authorization (such as Administrator) will increase the attack surface and therefore the scan coverage.</p>
</div></div>

</li>
<li><code>generateReport : boolean</code> (optional)
<div><div>
 Check this option if you want AppScan Standard to generate a report after scannning. 
 <p>The report is available in HTML and PDF.</p>
 <p>The HTML report generated is ready to be integrated with the HTML Publisher Plugin.</p>
</div></div>

</li>
<li><code>htmlReport : boolean</code> (optional)
<div><div>
 This report can be integrated with the <a href="https://wiki.jenkins-ci.org/display/JENKINS/HTML+Publisher+Plugin" rel="nofollow">HTML Publisher Plugin</a>.
</div></div>

</li>
<li><code>includeURLS : String</code> (optional)
<div><div>
 This is used to include URLs for scanning, 
 <p>Some URLs might not be found by AppScan Standard's spiders, include them to get the best possible coverage.</p>
</div></div>

</li>
<li><code>pathRecordedLoginSequence : String</code> (optional)
<div><div>
 Provide the full path to the recorded login sequence file (.login). More info. at: (9.0.3.2 User Guide) Login Management view - Chapter 4 - Configuring - Page 45 http://www-01.ibm.com/support/docview.wss?uid=swg27048015#2
</div></div>

</li>
<li><code>pdfReport : boolean</code> (optional)
<div><div>
 A PDF report is generated.
</div></div>

</li>
<li><code>policyFile : String</code> (optional)
<div><div>
 Provide the Path to a Test Policy File (.policy) to determine which type of flaws to scan for. 
 <p>A Test Policy File can be created following these steps:</p>
 <p>"Scan" &gt; "Scan Configuration" &gt; "Test Policy" &gt; "Export".</p>
</div></div>

</li>
<li><code>reportName : String</code> (optional)
<div><div>
 Provide the name to save the report with. 
 <p>To configure HTML Publisher Plugin properly, the names in the configuration must match.</p>
</div></div>

</li>
<li><code>verbose : boolean</code> (optional)
<div><div>
 Selecting this option will enable AppScan Standards' verbose, printing the full scan output in Jenkins log.
</div></div>

</li>
</ul>


++++
