= InfluxDB Query Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/influxdb-query">Visit the Jenkins Plugins site</a>
++++


=== `influxDbQuery`: Query InfluxDB
++++
<ul><li><code>checkName : String</code>
<div><div>
 Logical name for the check.
</div></div>

</li>
<li><code>influxQuery : String</code>
<div><div>
 InfluxDB select query supposed to return 1 value. It can be a sum, count or function returning only one value. May use Jenkins tokens such as build number in the query. e.g.
</div></div>

</li>
<li><code>expectedThreshold : double</code>
<div><div>
 Threshold for the value returned by query result. If exceeded and if Mark Build Unstable is selected, the build will be marked unstable.
</div></div>

</li>
<li><code>markUnstable : boolean</code> (optional)
<div><div>
 Check if we should mark the build unstable if the threshold is exceeded.
</div></div>

</li>
<li><code>retryCount : int</code> (optional)
<div><div>
 Max number of times to execute the query as a single post-build step.
</div></div>

</li>
<li><code>retryInterval : int</code> (optional)
<div><div>
 Time to wait in between each query in seconds, default to 30s.
</div></div>

</li>
<li><code>showResults : boolean</code> (optional)
<div><div>
 Check if we should should display the query results in the Jenkins console.
</div></div>

</li>
</ul>


++++
