= Rapid7 InsightAppSec
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/insightappsec">Visit the Jenkins Plugins site</a>
++++


=== `insightAppSec`: Scan using InsightAppSec
++++
<ul><li><code>region : String</code>
<div><div>
 The data storage region of the target InsightAppSec instance.
</div></div>

</li>
<li><code>insightCredentialsId : String</code>
</li>
<li><code>appId : String</code>
<div><div>
 The App containing the Scan Config you wish to scan.
</div></div>

</li>
<li><code>scanConfigId : String</code>
<div><div>
 The Scan Config you wish to scan.
</div></div>

</li>
<li><code>buildAdvanceIndicator : String</code>
<div><div>
 <div>
  This configuration option can be used to augment how the build advances based on the status of the scan submitted
 </div>
 <ul>
  <li><b>Scan has been submitted</b> - Advance the build when the scan has been <i>submitted</i> successfully</li>
  <p></p>
  <li><b>Scan has been started</b> - Advance the build when the scan has been <i>started</i> successfully</li>
  <p></p>
  <li><b>Scan has been completed</b> - Advance the build when the scan has been <i>completed</i> successfully</li>
  <p></p>
  <li><b>Vulnerability results query has returned no vulnerabilities</b> - Advance the build when the scan has been <i>completed</i> and the vulnerability search query has returned no vulnerabilities</li>
 </ul>
</div></div>

</li>
<li><code>vulnerabilityQuery : String</code>
<div><div>
 <ul>
  <li>
   <div>
    An InsightAppSec search query may be supplied to search vulnerabilities found by the scan.
   </div></li>
  <li>
   <div>
    For example, if you wish to fail the build when <i>high</i> severity vulnerabilities have been found, use:
   </div>
   <pre>                       <code>vulnerability.severity='HIGH'</code>
            </pre></li>
  <li>
   <div>
    The query supplied will automatically be scoped to the scan
   </div></li>
  <li>
   <div>
    For more information on vulnerability search queries, consult the InsightAppSec API search documentation here:
   </div><a href="https://help.rapid7.com/insightappsec/en-us/api/v1/docs.html#tag/Search" rel="nofollow">https://help.rapid7.com/insightappsec/en-us/api/v1/docs.html#tag/Search</a></li>
  <li>
   <div>
    If left blank, the build will fail when <b>any</b> vulnerabilities have been found in the scan
   </div></li>
 </ul>
</div></div>

</li>
<li><code>maxScanPendingDuration : String</code>
<div><div>
 <div>
  A max scan pending duration may be provided so that the length of time the CI process takes to provide feedback can be controlled.
 </div>
 <ul>
  <li>This option is ignored if 'Scan has been submitted' has been selected as the build advance indicator</li>
  <li>The duration will take affect when the scan has been submitted</li>
  <li>Upon reaching the duration, the scan will be cancelled and the build will fail</li>
 </ul>
</div>
<p></p>
<div>
 <div>
  The following format must be used for defining a duration: 
  <pre>       <code>0d 5h 30m</code>
    </pre>
 </div>
 <div>
  <ul>
   <li>(d) - Days</li>
   <li>(h) - Hours</li>
   <li>(m) - Minutes</li>
  </ul>
  <div>
   A quantity must be supplied for each of the above. e.g.
  </div>
  <ul>
   <li>1 day: 1d 0h 0m</li>
   <li>5 hours: 0d 5h 0m</li>
   <li>3 hours, 30 minutes: 0d 3h 30m</li>
  </ul>
 </div>
</div></div>

</li>
<li><code>maxScanExecutionDuration : String</code>
<div><div>
 <div>
  A max scan execution duration may be provided so that the length of time the CI process takes to provide feedback can be controlled.
 </div>
 <ul>
  <li>This option is ignored if 'Scan has been submitted' has been selected as the build advance indicator</li>
  <li>This option is ignored if 'Scan has been started' has been selected as the build advance indicator</li>
  <li>The duration will take affect when the scan moves into scanning state</li>
  <li>Upon reaching the duration, the in-progress scan will be stopped and the build will advance as normal</li>
 </ul>
</div>
<p></p>
<div>
 <div>
  The following format must be used for defining a duration: 
  <pre>       <code>0d 5h 30m</code>
    </pre>
 </div>
 <div>
  <ul>
   <li>(d) - Days</li>
   <li>(h) - Hours</li>
   <li>(m) - Minutes</li>
  </ul>
  <div>
   A quantity must be supplied for each of the above. e.g.
  </div>
  <ul>
   <li>1 day: 1d 0h 0m</li>
   <li>5 hours: 0d 5h 0m</li>
   <li>3 hours, 30 minutes: 0d 3h 30m</li>
  </ul>
 </div>
</div></div>

</li>
<li><code>enableScanResults : boolean</code>
<div><div>
 <div>
  Flag to indicate if scan results should be viewable when a build has finished.
 </div>
 <div>
  When enabled, a new action will be provided to view scan results, labeled 'InsightAppSec Scan Results'.
 </div>
 <p></p>
 <div>
  <b>Note: All users with access to view the build job history will be able to view InsightAppSec scan results</b>
 </div>
</div></div>

</li>
</ul>


++++
