= PTC Windchill RV&S CM - Jenkins Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/integrity-plugin">Visit the Jenkins Plugins site</a>
++++


=== `siaddprojectlabel`: Windchill RV&S SCM Label
++++
<ul><li><code>serverConfig : String</code>
</li>
<li><code>checkpointLabel : String</code> (optional)
<div><div>
 A valid Windchill RV&amp;S Checkpoint label string. No groovy pre-processing is applied.
</div></div>

</li>
<li><code>configPath : String</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>userName : String</code> (optional)
</li>
</ul>


++++
=== `sicheckpoint`: Windchill RV&S SCM Checkpoint
++++
<ul><li><code>serverConfig : String</code>
</li>
<li><code>checkpointDesc : String</code> (optional)
</li>
<li><code>checkpointLabel : String</code> (optional)
<div><div>
 A valid Windchill RV&amp;S Checkpoint label string. No groovy pre-processing is applied.
</div></div>

</li>
<li><code>configPath : String</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>userName : String</code> (optional)
</li>
</ul>


++++
=== `sici`: Windchill RV&S SCM Checkin
++++
<ul><li><code>serverConfig : String</code>
</li>
<li><code>configPath : String</code> (optional)
</li>
<li><code>excludes : String</code> (optional)
<div><div>
 Ant-style filter for an excludes pattern. Example: **/*.class
</div></div>

</li>
<li><code>includes : String</code> (optional)
<div><div>
 Ant-style filter for an includes pattern. Example: **/*.java
</div></div>

</li>
<li><code>itemID : String</code> (optional)
<div><div>
 Windchill RV&amp;S Item ID designation. Acceptable values include: 
 <br>
 &nbsp;&nbsp;:none // <i>Indicates no change packages are used for check in</i>
 <br>
 &nbsp;&nbsp;:bypass // <i>Assumes that the user has administrative privileges to bypass change package policies configured for the Windchill RV&amp;S Project</i>
 <br>
 &nbsp;&nbsp;0 // <i>Same as :none above</i>
 <br>
 &nbsp;&nbsp;12345 // <i>An actual valid Windchill RV&amp;S Item ID that the plugin will use to create a change package</i>
</div></div>

</li>
<li><code>password : String</code> (optional)
</li>
<li><code>userName : String</code> (optional)
</li>
</ul>


++++
