= Jabber (XMPP) notifier and control plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/jabber">Visit the Jenkins Plugins site</a>
++++


=== `jabberNotify`: Jabber Notification
++++
<div><div>
 When used in Pipelines, this plugin will act somewhat differently than in AbstractBuild subclasses. Specifically, notification strategy relies on a build result being set, but in pipelines it is not (yet) set. Here are some ways to use it: 
 <ul>
  <li><b>Set result yourself</b> (and use a single jabberNotify step) 
   <pre>                <code>
try {
    //main build here.

    currentBuild.result = Result.SUCCESS.toString() //otherwise message will say "NOT_BUILT"
} catch(e) {
    currentBuild.result = Result.FAILURE.toString()
    throw e
} finally {
    jabberNotify notificationStrategy: 'failure and fixed', notifyCulprits: true, notifySuspects: true, targets: '...'
}
                </code>
            </pre></li>
  <li><b>Decide when to notify</b> (and author your own messages) 
   <pre>                <code>
jabberNotify buildToChatNotifier: [$class: 'ExtraMessageOnlyBuildToChatNotifier'], extraMessage: 'Build Started', targets: '...'
try {
    //main build here

    jabberNotify buildToChatNotifier: [$class: 'ExtraMessageOnlyBuildToChatNotifier'], extraMessage: 'Build Succeeded', targets: '...'
} catch (e) {
    jabberNotify buildToChatNotifier: [$class: 'ExtraMessageOnlyBuildToChatNotifier'], extraMessage: 'Build Failed', targets: '...'
    throw e
}

                </code>
            </pre></li>
 </ul>
</div></div>
<ul><li><code>targets : String</code>
</li>
<li><code>buildToChatNotifier</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'BuildParametersBuildToChatNotifier'</code><div>
<ul></ul></div></li>
<li><code>$class: 'DefaultBuildToChatNotifier'</code><div>
<ul></ul></div></li>
<li><code>$class: 'ExtraMessageOnlyBuildToChatNotifier'</code><div>
<ul></ul></div></li>
<li><code>$class: 'PrintFailingTestsBuildToChatNotifier'</code><div>
<ul></ul></div></li>
<li><code>$class: 'SummaryOnlyBuildToChatNotifier'</code><div>
<ul></ul></div></li>
</ul></li>
<li><code>extraMessage : String</code> (optional)
</li>
<li><code>matrixNotifier</code> (optional)
<ul><li><b>Values:</b> <code>ONLY_PARENT</code>, <code>ONLY_CONFIGURATIONS</code>, <code>ALL</code></li></ul></li>
<li><code>notificationStrategy : String</code> (optional)
<div><div>
 This only makes sense if the build result has been set, either because this step is in a catch or finally block and the job already failed, or because it was manually set in the DSL (eg: <b>currentBuild.result = Result.FAILURE.toString()</b>) If it was not set, then only "all" will make sense.
</div></div>

</li>
<li><code>notifyCulprits : boolean</code> (optional)
</li>
<li><code>notifyFixers : boolean</code> (optional)
</li>
<li><code>notifySuspects : boolean</code> (optional)
</li>
<li><code>notifyUpstreamCommitters : boolean</code> (optional)
</li>
</ul>


++++
