= Jacked
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/jacked">Visit the Jenkins Plugins site</a>
++++


=== `jacked`: Vulnerability scan with jacked
++++
<ul><li><code>scanDest : String</code>
</li>
<li><code>scanName : String</code>
<div><div>
 Input Image name, Directory path, tar file path, or sbom file path.
</div></div>

</li>
<li><code>severityType : String</code>
<div><div>
 Select a threshold that will fail the build when equal to or above the severity found in the results.
</div></div>

</li>
<li><code>scanType : String</code>
<div><div>
 <b>Scan Type:</b> Image, Directory, Tar File and SBOM File. 
 <ul>
  <li><b>Image:</b> Provide the image to be scanned.</li>
  <li><b>Directory:</b> Provide the target directory path to be scanned.</li>
  <li><b>Tar File:</b> Provide the target tar file path to be scanned.</li>
  <li><b>SBOM File:</b> Provide the target <a href="https://github.com/carbonetes/diggity" rel="nofollow">Diggity</a> JSON Format SBOM file path to be scanned.</li>
 </ul>
</div></div>

</li>
<li><code>skipFail : boolean</code>
<div><div>
 <ul>
  <li><b>Warning:</b> If the value is checked, it will restrict the plugin from failing the build based on the assessment result.</li>
  <li><b>Default:</b> false / unchecked.</li>
 </ul>
</div></div>

</li>
<li><code>skipDbUpdate : boolean</code>
<div><div>
 <ul>
  <li><b>Warning:</b> If the value is checked, it will skip check database update while scanning.</li>
  <li><b>Default:</b> false / unchecked.</li>
 </ul>
</div></div>

</li>
<li><code>ignorePackageNames : String</code>
<div><div>
 <b>Usage:</b> Ignore the following package names when scanning. Leave blank if not using. 
 <ul>
  <li>Example Input Format: dpkg,tar,gzip</li>
 </ul>
</div></div>

</li>
<li><code>ignoreCves : String</code>
<div><div>
 <b>Usage:</b> Ignore the following CVEs when scanning. Leave blank if not using. 
 <ul>
  <li>Example Input Format: CVE-2022-24775,CVE-2022-1304,TEMP-0000000-6F6CD4</li>
 </ul>
</div></div>

</li>
<li><code>content</code>
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>jackedConfig</code>
<ul><li><b>Type:</b> <code>class io.jenkins.plugins.jacked.model.JackedConfig</code></li>
</ul></li>
</ul>


++++
