= JaCoCo plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/jacoco">Visit the Jenkins Plugins site</a>
++++


=== `jacoco`: Record JaCoCo coverage report
++++
<div><div>
 Allows to configure various aspects of the JaCoCo code coverage report. The paths define where the various types of files can be found in the workspace, inclusions and exclusions allow to exclude certain class files. And the coverage thresholds allow to configure how much coverage is necessary to make the build green (if changing the build status is enabled).
</div></div>
<ul><li><code>buildOverBuild : boolean</code> (optional)
<div><div>
 Check this to set the build status to failure if the delta coverage thresholds are violated. Delta coverage is the difference between coverage of last successful and current build.
</div></div>

</li>
<li><code>changeBuildStatus : boolean</code> (optional)
<div><div>
 Check this to set the build status to unstable if coverage thresholds are violated.
</div></div>

</li>
<li><code>classPattern : String</code> (optional)
<div><div>
 Path to the Java class directories that should be included in coverage reporting. Ant path wildcards are understood.
</div></div>

</li>
<li><code>deltaBranchCoverage : String</code> (optional)
<div><div>
 Change build status if coverage degrades. The build status degrades to unstable (or failed) if <strong>branch coverage</strong> decreases by more than this delta threshold compared to the previous build.
</div></div>

</li>
<li><code>deltaClassCoverage : String</code> (optional)
<div><div>
 Change build status if coverage degrades. The build status degrades to unstable (or failed) if <strong>class coverage</strong> decreases by more than this delta threshold compared to the previous build.
</div></div>

</li>
<li><code>deltaComplexityCoverage : String</code> (optional)
<div><div>
 Change build status if coverage degrades. The build status degrades to unstable (or failed) if <strong>complexity coverage</strong> decreases by more than this delta threshold compared to the previous build.
</div></div>

</li>
<li><code>deltaInstructionCoverage : String</code> (optional)
<div><div>
 Change build status if coverage degrades. The build status degrades to unstable (or failed) if <strong>instruction coverage</strong> decreases by more than this delta threshold compared to the previous build.
</div></div>

</li>
<li><code>deltaLineCoverage : String</code> (optional)
<div><div>
 Change build status if coverage degrades. The build status degrades to unstable (or failed) if <strong>line coverage</strong> decreases by more than this delta threshold compared to the previous build.
</div></div>

</li>
<li><code>deltaMethodCoverage : String</code> (optional)
<div><div>
 Change build status if coverage degrades. The build status degrades to unstable (or failed) if <strong>method coverage</strong> decreases by more than this delta threshold compared to the previous build.
</div></div>

</li>
<li><code>exclusionPattern : String</code> (optional)
<div><div>
 Path to the Java class files that should be excluded from coverage reporting. Ant path wildcards are understood.
</div></div>

</li>
<li><code>execPattern : String</code> (optional)
<div><div>
 Path to the exec files generated by JaCoCo. Ant path wildcards are understood.
</div></div>

</li>
<li><code>inclusionPattern : String</code> (optional)
<div><div>
 Path to the Java class files that should be included in coverage reporting. Ant path wildcards are understood.
</div></div>

</li>
<li><code>maximumBranchCoverage : String</code> (optional)
<div><div>
 Change build status based on coverage results. 
 <ul>
  <li>The build fails if the <strong>branch coverage</strong> is below <code>minimumBranchCoverage</code></li>
  <li>The build is unstable if the <strong>branch coverage</strong> is above <code>minimumBranchCoverage</code> and below <code>maximumBranchCoverage</code></li>
  <li>The build succeeds if the <strong>branch coverage</strong> is above <code>maximumBranchCoverage</code></li>
 </ul>
</div></div>

</li>
<li><code>maximumClassCoverage : String</code> (optional)
<div><div>
 Change build status based on coverage results. 
 <ul>
  <li>The build fails if the <strong>class coverage</strong> is below <code>minimumClassCoverage</code></li>
  <li>The build is unstable if the <strong>class coverage</strong> is above <code>minimumClassCoverage</code> and below <code>maximumClassCoverage</code></li>
  <li>The build succeeds if the <strong>class coverage</strong> is above <code>maximumClassCoverage</code></li>
 </ul>
</div></div>

</li>
<li><code>maximumComplexityCoverage : String</code> (optional)
<div><div>
 Change build status based on coverage results. 
 <ul>
  <li>The build fails if the <strong>complexity coverage</strong> is below <code>minimumComplexityCoverage</code></li>
  <li>The build is unstable if the <strong>complexity coverage</strong> is above <code>minimumComplexityCoverage</code> and below <code>maximumComplexityCoverage</code></li>
  <li>The build succeeds if the <strong>complexity coverage</strong> is above <code>maximumComplexityCoverage</code></li>
 </ul>
</div></div>

</li>
<li><code>maximumInstructionCoverage : String</code> (optional)
<div><div>
 Change build status based on coverage results. 
 <ul>
  <li>The build fails if the <strong>instruction coverage</strong> is below <code>minimumInstructionCoverage</code></li>
  <li>The build is unstable if the <strong>instruction coverage</strong> is above <code>minimumInstructionCoverage</code> and below <code>maximumInstructionCoverage</code></li>
  <li>The build succeeds if the <strong>instruction coverage</strong> is above <code>maximumInstructionCoverage</code></li>
 </ul>
</div></div>

</li>
<li><code>maximumLineCoverage : String</code> (optional)
<div><div>
 Change build status based on coverage results. 
 <ul>
  <li>The build fails if the <strong>line coverage</strong> is below <code>minimumLineCoverage</code></li>
  <li>The build is unstable if the <strong>line coverage</strong> is above <code>minimumLineCoverage</code> and below <code>maximumLineCoverage</code></li>
  <li>The build succeeds if the <strong>line coverage</strong> is above <code>maximumLineCoverage</code></li>
 </ul>
</div></div>

</li>
<li><code>maximumMethodCoverage : String</code> (optional)
<div><div>
 Change build status based on coverage results. 
 <ul>
  <li>The build fails if the <strong>method coverage</strong> is below <code>minimumMethodCoverage</code></li>
  <li>The build is unstable if the <strong>method coverage</strong> is above <code>minimumMethodCoverage</code> and below <code>maximumMethodCoverage</code></li>
  <li>The build succeeds if the <strong>method coverage</strong> is above <code>maximumMethodCoverage</code></li>
 </ul>
</div></div>

</li>
<li><code>minimumBranchCoverage : String</code> (optional)
<div><div>
 Change build status based on coverage results. 
 <ul>
  <li>The build fails if the <strong>branch coverage</strong> is below <code>minimumBranchCoverage</code></li>
  <li>The build is unstable if the <strong>branch coverage</strong> is above <code>minimumBranchCoverage</code> and below <code>maximumBranchCoverage</code></li>
  <li>The build succeeds if the <strong>branch coverage</strong> is above <code>maximumBranchCoverage</code></li>
 </ul>
</div></div>

</li>
<li><code>minimumClassCoverage : String</code> (optional)
<div><div>
 Change build status based on coverage results. 
 <ul>
  <li>The build fails if the <strong>class coverage</strong> is below <code>minimumClassCoverage</code></li>
  <li>The build is unstable if the <strong>class coverage</strong> is above <code>minimumClassCoverage</code> and below <code>maximumClassCoverage</code></li>
  <li>The build succeeds if the <strong>class coverage</strong> is above <code>maximumClassCoverage</code></li>
 </ul>
</div></div>

</li>
<li><code>minimumComplexityCoverage : String</code> (optional)
<div><div>
 Change build status based on coverage results. 
 <ul>
  <li>The build fails if the <strong>complexity coverage</strong> is below <code>minimumComplexityCoverage</code></li>
  <li>The build is unstable if the <strong>complexity coverage</strong> is above <code>minimumComplexityCoverage</code> and below <code>maximumComplexityCoverage</code></li>
  <li>The build succeeds if the <strong>complexity coverage</strong> is above <code>maximumComplexityCoverage</code></li>
 </ul>
</div></div>

</li>
<li><code>minimumInstructionCoverage : String</code> (optional)
<div><div>
 Change build status based on coverage results. 
 <ul>
  <li>The build fails if the <strong>instruction coverage</strong> is below <code>minimumInstructionCoverage</code></li>
  <li>The build is unstable if the <strong>instruction coverage</strong> is above <code>minimumInstructionCoverage</code> and below <code>maximumInstructionCoverage</code></li>
  <li>The build succeeds if the <strong>instruction coverage</strong> is above <code>maximumInstructionCoverage</code></li>
 </ul>
</div></div>

</li>
<li><code>minimumLineCoverage : String</code> (optional)
<div><div>
 Change build status based on coverage results. 
 <ul>
  <li>The build fails if the <strong>line coverage</strong> is below <code>minimumLineCoverage</code></li>
  <li>The build is unstable if the <strong>line coverage</strong> is above <code>minimumLineCoverage</code> and below <code>maximumLineCoverage</code></li>
  <li>The build succeeds if the <strong>line coverage</strong> is above <code>maximumLineCoverage</code></li>
 </ul>
</div></div>

</li>
<li><code>minimumMethodCoverage : String</code> (optional)
<div><div>
 Change build status based on coverage results. 
 <ul>
  <li>The build fails if the <strong>method coverage</strong> is below <code>minimumMethodCoverage</code></li>
  <li>The build is unstable if the <strong>method coverage</strong> is above <code>minimumMethodCoverage</code> and below <code>maximumMethodCoverage</code></li>
  <li>The build succeeds if the <strong>method coverage</strong> is above <code>maximumMethodCoverage</code></li>
 </ul>
</div></div>

</li>
<li><code>runAlways : boolean</code> (optional)
<div><div>
 Run coverage collection even if the build fails or is aborted.
</div></div>

</li>
<li><code>skipCopyOfSrcFiles : boolean</code> (optional)
<div><div>
 Check this to disable display of source files for each line coverage
</div></div>

</li>
<li><code>sourceExclusionPattern : String</code> (optional)
<div><div>
 Path to the Java source files that should be excluded from coverage reporting. Ant path wildcards are understood.
</div></div>

</li>
<li><code>sourceInclusionPattern : String</code> (optional)
<div><div>
 Path to the Java source files that should be included in coverage reporting. Ant path wildcards are understood.
</div></div>

</li>
<li><code>sourcePattern : String</code> (optional)
<div><div>
 Path to the Java source directories that should be included in coverage reporting. Ant path wildcards are understood.
</div></div>

</li>
</ul>


++++
