= JDCloud CodeDeploy Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/jdcloud-codedeploy">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'JDCodeDeployPublisher'])`: Deploy to JDCloud CodeDeploy
++++
<ul><li><code>ossBucket : String</code>
<div><div>
 The bucket in Object Storage Service where new JDCloud CodeDeploy revisions will be uploaded.
</div></div>

</li>
<li><code>ossObject : String</code>
<div><div>
 The Object in the Object Storage Service Bucket to prepend to the JDCloud CodeDeploy revision.
</div></div>

</li>
<li><code>applicationName : String</code>
<div><div>
 The name of the JDCloud CodeDeploy application you wish to deploy to. This plugin assumes that you've already created the application and deployment group.
</div></div>

</li>
<li><code>deploymentGroupName : String</code>
<div><div>
 The name of the JDCloud CodeDeploy deployment group attached to your application that you want to deploy to.
</div></div>

</li>
<li><code>regionId : String</code>
</li>
<li><code>waitForCompletion : boolean</code>
<div><div>
 <p>If checked, this build will wait for the JDCloud CodeDeploy deployment to finish (with either success or failure). Polling Timeout, below, sets the maximum amount of time to wait.<br><br>
  If unchecked, the deployment will be handed off to JDCloud CodeDeploy and the build will move on to the next step.</p>
 <p>The build will be marked a failure if <em>either</em> the timeout is reached or the deployment fails. The build log will indicate which.</p>
</div></div>

</li>
<li><code>pollingTimeoutSec : long</code>
</li>
<li><code>pollingFreqSec : long</code>
</li>
<li><code>doDeploy : boolean</code>
</li>
<li><code>accessKey : String</code>
<div><div>
 <p>JDCloud Access and Secret keys to use for this deployment.</p>
</div></div>

</li>
<li><code>secretKey</code>
<div><div>
 <p>JDCloud Access and Secret keys to use for this deployment.</p>
</div></div>

<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>includes : String</code>
<div><div>
 <strong>Includes</strong> and <strong>Excludes</strong> together define the file(s) that will be contained in the application revision that is uploaded to Object Storage Service.
</div></div>

</li>
<li><code>downloadUrl : String</code>
</li>
<li><code>deploySource : String</code>
</li>
<li><code>excludes : String</code>
<div><div>
 <strong>Includes</strong> and <strong>Excludes</strong> together define the file(s) that will be contained in the application revision that is uploaded to Object Storage Service.
</div></div>

</li>
<li><code>subdirectory : String</code>
<div><div>
 A subdirectory inside the workspace to be packed instead of the whole workspace. Remember that the <i>jdcloud-codedeploy.yml</i> must be placed at the top of the .tar.gz archive. The <i>excludes</i> and <i>includes</i> will be applied based on this path.
</div></div>

</li>
</ul>


++++
