= JGiven Jenkins Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/jgiven">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'JgivenReportGenerator'])`: Generate JGiven Reports
++++
<ul><li><code>reportConfigs</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'AsciiDocReportConfig'</code><div>
<ul></ul></div></li>
<li><code>$class: 'HtmlReportConfig'</code><div>
<ul><li><code>customCssFile : String</code> (optional)
<div><div>
 Custom Css File which will be referenced from the JGiven Reports. This path is relative to the workspace. The file will be copied to the JGiven report directory.
</div></div>

</li>
<li><code>customJsFile : String</code> (optional)
<div><div>
 Custom Js File which will be referenced from the JGiven Reports. This path is relative to the workspace. The file will be copied to the JGiven report directory.
</div></div>

</li>
<li><code>title : String</code> (optional)
<div><div>
 The title of the JGiven report.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'TextReportConfig'</code><div>
<ul></ul></div></li>
</ul></li>
<li><code>excludeEmptyScenarios : boolean</code> (optional)
</li>
<li><code>jgivenResults : String</code> (optional)
<div><div>
 <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">Fileset 'includes'</a> setting that specifies the generated raw json JGiven report files, such as 'myproject/target/jgiven-reports/json/*.json'. Basedir of the fileset is <a rel="nofollow">the workspace root</a>. 
 <br>
  If not set then '**/json/*.json' is used.
</div></div>

</li>
</ul>


++++
