= Job DSL
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/job-dsl">Visit the Jenkins Plugins site</a>
++++


=== `jobDsl`: Process Job DSLs
++++
<ul><li><code>additionalClasspath : String</code> (optional)
<div><div>
 Newline separated list of additional classpath entries for the Job DSL scripts. All entries must be relative to the workspace root, e.g. <em>build/classes/main</em>. Supports Ant-style patterns like <em>lib/*.jar</em>.
</div></div>

</li>
<li><code>additionalParameters</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.Object&gt;</code></li>
</ul></li>
<li><code>failOnMissingPlugin : boolean</code> (optional)
<div><div>
 If checked, the build will be marked as failed if a plugin must be installed or updated to support all features used in the DSL scripts. If not checked, the build will be marked as unstable instead.
</div></div>

</li>
<li><code>failOnSeedCollision : boolean</code> (optional)
<div><div>
 Fail build if generated item(s) have the same name as existing items already managed by another seed job. By default, this plugin will always regenerate all jobs and views, thus updating previously generated jobs and views even if managed by another seed job. Check this box if you wish to fail the job if a generated item name collision is detected.
</div></div>

</li>
<li><code>ignoreExisting : boolean</code> (optional)
<div><div>
 Ignore previously generated jobs and views. By default, this plugin will always regenerate all jobs and views, thus updating previously generated jobs and views. Check this box if you wish to leave previous jobs and views as is.
</div></div>

</li>
<li><code>ignoreMissingFiles : boolean</code> (optional)
<div><div>
 Ignore missing DSL scripts. If not checked, the build step will fail if a configured script is missing or if a wildcard does not match any files.
</div></div>

</li>
<li><code>lookupStrategy</code> (optional)
<div><div>
 Determines how relative job names in DSL scripts are interpreted. You will only see a difference when the seed job is located in a <a href="https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Folders+Plugin" rel="nofollow">folder</a>. 
 <ul>
  <li><b>Jenkins Root</b> When this option is selected relative job names are always interpreted relative to the Jenkins root.</li>
  <li><b>Seed Job</b> If you choose this option relative job names in DSL scripts will be interpreted relative to the folder in which the seed job is located. Suppose you have a seed job which is located in a folder named <em>seedJobFolder</em> and a DSL script which creates a job named <em>subfolder2/job</em>. The job that is created by the seed job will be at the location <em>/seedJobFolder/subfolder2/job</em>.</li>
 </ul>
</div></div>

<ul><li><b>Values:</b> <code>JENKINS_ROOT</code>, <code>SEED_JOB</code></li></ul></li>
<li><code>removedConfigFilesAction</code> (optional)
<div><div>
 Specifies what to do when previously generated config files are not referenced anymore. 
 <p><b>Note:</b> when using multiple Job DSL build steps in a single job, set this to "Delete" only for the last Job DSL build step. Otherwise config files may be deleted and re-created. See <a href="https://issues.jenkins-ci.org/browse/JENKINS-44142" rel="nofollow">JENKINS-44142</a> for details.</p>
</div></div>

<ul><li><b>Values:</b> <code>IGNORE</code>, <code>DELETE</code></li></ul></li>
<li><code>removedJobAction</code> (optional)
<div><div>
 Specifies what to do when a previously generated job is not referenced anymore. 
 <p><b>Note:</b> when using multiple Job DSL build steps in a single job, set this to "Delete" or "Disable" only for the last Job DSL build step. Otherwise jobs will be deleted and re-created or disabled and re-enabled and you may lose the job history of generated jobs. See <a href="https://issues.jenkins-ci.org/browse/JENKINS-44142" rel="nofollow">JENKINS-44142</a> for details.</p>
</div></div>

<ul><li><b>Values:</b> <code>IGNORE</code>, <code>DISABLE</code>, <code>DELETE</code></li></ul></li>
<li><code>removedViewAction</code> (optional)
<div><div>
 Specifies what to do when a previously generated view is not referenced anymore. 
 <p><b>Note:</b> when using multiple Job DSL build steps in a single job, set this to "Delete" only for the last Job DSL build step. Otherwise views may be deleted and re-created. See <a href="https://issues.jenkins-ci.org/browse/JENKINS-44142" rel="nofollow">JENKINS-44142</a> for details.</p>
</div></div>

<ul><li><b>Values:</b> <code>IGNORE</code>, <code>DELETE</code></li></ul></li>
<li><code>sandbox : boolean</code> (optional)
<div><div>
 If checked, runs the DSL scripts in a sandbox with limited abilities. You will also need to configure this job to run with the identity of a particular user. If unchecked, and you are not a Jenkins administrator, you will need to wait for an administrator to approve the scripts.
</div></div>

</li>
<li><code>scriptText : String</code> (optional)
<div><div>
 DSL Script, which is groovy code. Look at <a href="https://github.com/jenkinsci/job-dsl-plugin" rel="nofollow">documentation</a> for details on the syntax.
</div></div>

</li>
<li><code>targets : String</code> (optional)
<div><div>
 Newline separated list of DSL scripts, located in <a rel="nofollow">the Workspace</a>. Can use wildcards like 'jobs/**/*.groovy'. See <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">the @includes of Ant fileset</a> for the exact format. 
 <p>Scripts are executed in the same order as specified. The execution order of expanded wildcards is unspecified.</p>
</div></div>

</li>
<li><code>unstableOnDeprecation : boolean</code> (optional)
<div><div>
 If checked, marks the build as unstable when using deprecated features. If not checked, a warning will be printed to the build log only.
</div></div>

</li>
<li><code>useScriptText : boolean</code> (optional)
</li>
</ul>


++++
