= JUnit Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/junit">Visit the Jenkins Plugins site</a>
++++


=== `junit`: Archive JUnit-formatted test results
++++
<div><div>
 Jenkins understands the JUnit test report XML format (which is also used by TestNG). When this option is configured, Jenkins can provide useful information about test results, such as historical test result trends, a web UI for viewing test reports, tracking failures, and so on. 
 <p>To use this feature, first set up your build to run tests, then specify the path to JUnit XML files in the <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">Ant glob syntax</a>, such as **/build/test-reports/*.xml. Be sure not to include any non-report files into this pattern. You can specify multiple patterns of files separated by commas.</p>
</div></div>
<ul><li><code>testResults : String</code>
</li>
<li><code>allowEmptyResults : boolean</code> (optional)
<div><div>
 If checked, the default behavior of failing a build on missing test result files or empty test results is changed to not affect the status of the build. Please note that this setting make it harder to spot misconfigured jobs or build failures where the test tool does not exit with an error code when not producing test report files.
</div></div>

</li>
<li><code>checksName : String</code> (optional)
<div><div>
 If provided, and publishing checks enabled, the plugin will use this name when publishing results to corresponding SCM hosting platforms. If not, a default including the current stage / branch names will be used.
</div></div>

</li>
<li><code>healthScaleFactor : double</code> (optional)
<div><div>
 The amplification factor to apply to test failures when computing the test result contribution to the build health score. 
 <br>
  The default factor is <code>1.0</code>
 <ul>
  <li>A factor of <code>0.0</code> will disable the test result contribution to build health score.</li>
  <li>A factor of <code>0.1</code> means that 10% of tests failing will score 99% health</li>
  <li>A factor of <code>0.5</code> means that 10% of tests failing will score 95% health</li>
  <li>A factor of <code>1.0</code> means that 10% of tests failing will score 90% health</li>
  <li>A factor of <code>2.0</code> means that 10% of tests failing will score 80% health</li>
  <li>A factor of <code>2.5</code> means that 10% of tests failing will score 75% health</li>
  <li>A factor of <code>5.0</code> means that 10% of tests failing will score 50% health</li>
  <li>A factor of <code>10.0</code> means that 10% of tests failing will score 0% health</li>
 </ul> The factor is persisted with the build results, so changes will only be reflected in new builds.
</div></div>

</li>
<li><code>keepLongStdio : boolean</code> (optional)
<div><div>
 If checked, any standard output or error from a test suite will be retained in the test results after the build completes. (This refers only to additional messages printed to console, not to a failure stack trace.) Such output is always kept if the test failed, but by default lengthy output from passing tests is truncated to save space. Check this option if you need to see every log message from even passing tests, but beware that Jenkins's memory consumption can substantially increase as a result, even if you never look at the test results!
</div></div>

</li>
<li><code>keepProperties : boolean</code> (optional)
</li>
<li><code>skipMarkingBuildUnstable : boolean</code> (optional)
<div><div>
 If this option is unchecked, then the plugin will mark the build as unstable when it finds at least 1 test failure. If this option is checked, then the build will still be successful even if there are test failures reported. In any case, the corresponding pipeline node (and stage) will be marked as unstable in case of test failure.
</div></div>

</li>
<li><code>skipOldReports : boolean</code> (optional)
</li>
<li><code>skipPublishingChecks : boolean</code> (optional)
<div><div>
 If this option is unchecked, then the plugin automatically publishes the test results to corresponding SCM hosting platforms. For example, if you are using this feature for a GitHub organization project, the warnings will be published to GitHub through the Checks API. If this operation slows down your build, or you don't want to publish the warnings to SCM platforms, you can use this option to deactivate this feature.
</div></div>

</li>
<li><code>stdioRetention : String</code> (optional)
</li>
<li><code>testDataPublishers</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>attachments</code><div>
<ul></ul></div></li>
<li><code>$class: 'AutomateTestDataPublisher'</code><div>
<ul></ul></div></li>
<li><code>$class: 'ClaimTestDataPublisher'</code><div>
<ul></ul></div></li>
<li><code>$class: 'JUnitFlakyTestDataPublisher'</code><div>
<ul></ul></div></li>
<li><code>jiraTestResultReporter</code><div>
<ul><li><code>configs</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>jiraSelectableArrayField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>values</code>
<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>jiraSelectableField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>jiraStringArrayField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>values</code>
<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>jiraStringField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>value : String</code>
<div><div>
 <p>Insert a string value.</p>
 <p>You can include Jenkins Environment variables (see <a href="https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project" rel="nofollow">link</a>), or the following variables defined by this plugin:</p>
 <p></p>Variable usage: <b>${VAR_NAME}</b>
 <p></p>
 <p>CRFL - new line</p>
 <p>DEFAULT_SUMMARY - configured in the global configuration page</p>
 <p>DEFAULT_DESCRIPTION - configured in the global configuration page</p>
 <p>TEST_RESULT</p>
 <p>TEST_NAME</p>
 <p>TEST_FULL_NAME</p>
 <p>TEST_STACK_TRACE</p>
 <p>TEST_ERROR_DETAILS</p>
 <p>TEST_DURATION</p>
 <p>TEST_PACKAGE_NAME</p>
 <p>TEST_PACKAGE_CLASS_METHOD_NAME</p>
 <p>TEST_STDERR</p>
 <p>TEST_STDOUT</p>
 <p>TEST_OVERVIEW</p>
 <p>TEST_AGE</p>
 <p>TEST_PASS_COUNT</p>
 <p>TEST_SKIPPED_COUNT</p>
 <p>TEST_FAIL_SINCE</p>
 <p>TEST_IS_REGRESSION - expands to true/false</p>
 <p>BUILD_RESULT</p>
 <h3>WARNING: Your input will not be validated against the server's metadata. Check Jira to make sure you insert a valid value for this field and use the Validate Fields button bellow, otherwise the plugin will fail to create your issue.</h3>
</div></div>

</li>
</ul></div></li>
<li><code>jiraUserField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>value : String</code>
<div><div>
 <p>Insert the <b>username</b>.</p>
 <p>For example if you have a user with: <br><br>
  Display Name: <b>John Doe</b>, Username: <b>johndoe</b>, Email: <b>johndoe@email.com</b>,<br><br>
   you need to write <b>johndoe</b> in this field. Any other value (like display name, or email) will not work.</p>
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>projectKey : String</code>
</li>
<li><code>issueType : String</code>
</li>
<li><code>autoRaiseIssue : boolean</code>
<div><div>
 Create issues automatically for failing tests that don't yet have one linked.
</div></div>

</li>
<li><code>autoResolveIssue : boolean</code>
<div><div>
 Automatically apply transition to resolve issues linked to tests, if the test passes.
 <br><b>Experimental feature:</b> For now it only looks for the first transition that contains in its name "resolve". If it is found, it will be applied, if not, the status of the issue will not change. In future releases this will be parametrized.
</div></div>

</li>
<li><code>autoUnlinkIssue : boolean</code>
</li>
<li><code>overrideResolvedIssues : boolean</code>
<div><div>
 Create issues automatically for failing tests that are linked to resolved issues in JiraIssueKeyToTestMap.json.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'JunitResultPublisher'</code><div>
<div><div>
 If checked, each JUnit test result XML file will be examined to see if it represents a SOASTA CloudTest composition. For applicable tests, a hyperlink to the SOASTA CloudTest dashboard will be inserted into the test report.
</div></div>
<ul><li><code>urlOverride : String</code>
<div><div>
 Specify the CloudTest URL to use when creating hyperlinks to CloudTest dashboards. Normally, this can be left blank, and the URL will be extracted from the test result file.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PerfSigTestDataPublisher'</code><div>
<ul><li><code>dynatraceProfile : String</code>
</li>
</ul></div></li>
<li><code>$class: 'SahaginTestDataPublishser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'SauceOnDemandReportPublisher'</code><div>
<div><div>
 Show embedded Sauce OnDemand reports, including video and logs. Your test should use <a href="http://selenium-client-factory.infradna.com/" rel="nofollow">Selenium client factory</a> (at least <a href="http://maven.jenkins-ci.org/content/repositories/releases/com/saucelabs/selenium/selenium-client-factory/1.3/" rel="nofollow">version 1.3</a> to match test cases to individual Sauce OnDemand jobs).
</div></div>
<ul><li><code>jobVisibility : String</code> (optional)
<div>Set your test results visibility permissions. The <a href="https://wiki.saucelabs.com/display/DOCS/Sharing+the+Results+of+Sauce+Labs+Tests" rel="nofollow">Sauce Documentation</a> has all the various levels described in detail.</div>

</li>
</ul></div></li>
<li><code>$class: 'StabilityTestDataPublisher'</code><div>
<ul></ul></div></li>
<li><code>$class: 'TestCafePublisher'</code><div>
<ul></ul></div></li>
<li><code>$class: 'TestReporter'</code><div>
<ul></ul></div></li>
<li><code>$class: 'YoutrackTestDataPublisher'</code><div>
<ul></ul></div></li>
</ul></li>
</ul>


++++
=== `step([$class: 'JUnitResultArchiver'])`: Publish JUnit test result report
++++
<div><div>
 Jenkins understands the JUnit test report XML format (which is also used by TestNG). When this option is configured, Jenkins can provide useful information about test results, such as historical test result trends, a web UI for viewing test reports, tracking failures, and so on. 
 <p>To use this feature, first set up your build to run tests, then specify the path to JUnit XML files in the <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">Ant glob syntax</a>, such as **/build/test-reports/*.xml. Be sure not to include any non-report files into this pattern. You can specify multiple patterns of files separated by commas.</p>
</div></div>
<ul><li><code>testResults : String</code>
</li>
<li><code>allowEmptyResults : boolean</code> (optional)
<div><div>
 If checked, the default behavior of failing a build on missing test result files or empty test results is changed to not affect the status of the build. Please note that this setting make it harder to spot misconfigured jobs or build failures where the test tool does not exit with an error code when not producing test report files.
</div></div>

</li>
<li><code>checksName : String</code> (optional)
<div><div>
 If provided, and publishing checks enabled, the plugin will use this name when publishing results to corresponding SCM hosting platforms. If not, a default of "Tests" will be used.
</div></div>

</li>
<li><code>healthScaleFactor : double</code> (optional)
<div><div>
 The amplification factor to apply to test failures when computing the test result contribution to the build health score. 
 <br>
  The default factor is <code>1.0</code>
 <ul>
  <li>A factor of <code>0.0</code> will disable the test result contribution to build health score.</li>
  <li>A factor of <code>0.1</code> means that 10% of tests failing will score 99% health</li>
  <li>A factor of <code>0.5</code> means that 10% of tests failing will score 95% health</li>
  <li>A factor of <code>1.0</code> means that 10% of tests failing will score 90% health</li>
  <li>A factor of <code>2.0</code> means that 10% of tests failing will score 80% health</li>
  <li>A factor of <code>2.5</code> means that 10% of tests failing will score 75% health</li>
  <li>A factor of <code>5.0</code> means that 10% of tests failing will score 50% health</li>
  <li>A factor of <code>10.0</code> means that 10% of tests failing will score 0% health</li>
 </ul> The factor is persisted with the build results, so changes will only be reflected in new builds.
</div></div>

</li>
<li><code>keepLongStdio : boolean</code> (optional)
<div><div>
 <strong>Deprecated, use stdioRetention instead.</strong>
 <p>If checked, any standard output or error from a test suite will be retained in the test results after the build completes. (This refers only to additional messages printed to console, not to a failure stack trace.) Such output is always kept if the test failed, but by default lengthy output from passing tests is truncated to save space. Check this option if you need to see every log message from even passing tests, but beware that Jenkins's memory consumption can substantially increase as a result, even if you never look at the test results!</p>
</div></div>

</li>
<li><code>keepProperties : boolean</code> (optional)
</li>
<li><code>skipMarkingBuildUnstable : boolean</code> (optional)
<div><div>
 If this option is unchecked, then the plugin will mark the build as unstable when it finds at least 1 test failure. If this option is checked, then the build will still be successful even if there are test failures reported.
</div></div>

</li>
<li><code>skipOldReports : boolean</code> (optional)
</li>
<li><code>skipPublishingChecks : boolean</code> (optional)
<div><div>
 If this option is unchecked, then the plugin automatically publishes the test results to corresponding SCM hosting platforms. For example, if you are using this feature for a GitHub organization project, the warnings will be published to GitHub through the Checks API. If this operation slows down your build, or you don't want to publish the warnings to SCM platforms, you can use this option to deactivate this feature.
</div></div>

</li>
<li><code>stdioRetention : String</code> (optional)
<div><div>
 Controls how standard output or error from a test suite will be retained in the test results after the build completes. (This refers only to additional messages printed to console, not to a failure stack trace.) Some output is always retained for tests, but by default, excessively long output is truncated to save disk space. This property can be used to control whether that truncation takes place: 
 <ul>
  <li>If set to 'all', then no truncation will take place and the complete output from every test will be stored.</li>
  <li>If set to 'failed', then the complete output from all failed tests will be stored, but long output from passing tests will be truncated.</li>
  <li>If set to 'none', then long output from every test will be truncated, regardless of whether they passed or failed.</li>
 </ul> Beware that storing large output can cause Jenkins's memory consumption to substantially increase, even if you never look at the test results.
</div></div>

</li>
<li><code>testDataPublishers</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>attachments</code><div>
<ul></ul></div></li>
<li><code>$class: 'AutomateTestDataPublisher'</code><div>
<ul></ul></div></li>
<li><code>$class: 'ClaimTestDataPublisher'</code><div>
<ul></ul></div></li>
<li><code>$class: 'JUnitFlakyTestDataPublisher'</code><div>
<ul></ul></div></li>
<li><code>jiraTestResultReporter</code><div>
<ul><li><code>configs</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>jiraSelectableArrayField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>values</code>
<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>jiraSelectableField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>jiraStringArrayField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>values</code>
<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>jiraStringField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>value : String</code>
<div><div>
 <p>Insert a string value.</p>
 <p>You can include Jenkins Environment variables (see <a href="https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project" rel="nofollow">link</a>), or the following variables defined by this plugin:</p>
 <p></p>Variable usage: <b>${VAR_NAME}</b>
 <p></p>
 <p>CRFL - new line</p>
 <p>DEFAULT_SUMMARY - configured in the global configuration page</p>
 <p>DEFAULT_DESCRIPTION - configured in the global configuration page</p>
 <p>TEST_RESULT</p>
 <p>TEST_NAME</p>
 <p>TEST_FULL_NAME</p>
 <p>TEST_STACK_TRACE</p>
 <p>TEST_ERROR_DETAILS</p>
 <p>TEST_DURATION</p>
 <p>TEST_PACKAGE_NAME</p>
 <p>TEST_PACKAGE_CLASS_METHOD_NAME</p>
 <p>TEST_STDERR</p>
 <p>TEST_STDOUT</p>
 <p>TEST_OVERVIEW</p>
 <p>TEST_AGE</p>
 <p>TEST_PASS_COUNT</p>
 <p>TEST_SKIPPED_COUNT</p>
 <p>TEST_FAIL_SINCE</p>
 <p>TEST_IS_REGRESSION - expands to true/false</p>
 <p>BUILD_RESULT</p>
 <h3>WARNING: Your input will not be validated against the server's metadata. Check Jira to make sure you insert a valid value for this field and use the Validate Fields button bellow, otherwise the plugin will fail to create your issue.</h3>
</div></div>

</li>
</ul></div></li>
<li><code>jiraUserField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>value : String</code>
<div><div>
 <p>Insert the <b>username</b>.</p>
 <p>For example if you have a user with: <br><br>
  Display Name: <b>John Doe</b>, Username: <b>johndoe</b>, Email: <b>johndoe@email.com</b>,<br><br>
   you need to write <b>johndoe</b> in this field. Any other value (like display name, or email) will not work.</p>
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>projectKey : String</code>
</li>
<li><code>issueType : String</code>
</li>
<li><code>autoRaiseIssue : boolean</code>
<div><div>
 Create issues automatically for failing tests that don't yet have one linked.
</div></div>

</li>
<li><code>autoResolveIssue : boolean</code>
<div><div>
 Automatically apply transition to resolve issues linked to tests, if the test passes.
 <br><b>Experimental feature:</b> For now it only looks for the first transition that contains in its name "resolve". If it is found, it will be applied, if not, the status of the issue will not change. In future releases this will be parametrized.
</div></div>

</li>
<li><code>autoUnlinkIssue : boolean</code>
</li>
<li><code>overrideResolvedIssues : boolean</code>
<div><div>
 Create issues automatically for failing tests that are linked to resolved issues in JiraIssueKeyToTestMap.json.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'JunitResultPublisher'</code><div>
<div><div>
 If checked, each JUnit test result XML file will be examined to see if it represents a SOASTA CloudTest composition. For applicable tests, a hyperlink to the SOASTA CloudTest dashboard will be inserted into the test report.
</div></div>
<ul><li><code>urlOverride : String</code>
<div><div>
 Specify the CloudTest URL to use when creating hyperlinks to CloudTest dashboards. Normally, this can be left blank, and the URL will be extracted from the test result file.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PerfSigTestDataPublisher'</code><div>
<ul><li><code>dynatraceProfile : String</code>
</li>
</ul></div></li>
<li><code>$class: 'SahaginTestDataPublishser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'SauceOnDemandReportPublisher'</code><div>
<div><div>
 Show embedded Sauce OnDemand reports, including video and logs. Your test should use <a href="http://selenium-client-factory.infradna.com/" rel="nofollow">Selenium client factory</a> (at least <a href="http://maven.jenkins-ci.org/content/repositories/releases/com/saucelabs/selenium/selenium-client-factory/1.3/" rel="nofollow">version 1.3</a> to match test cases to individual Sauce OnDemand jobs).
</div></div>
<ul><li><code>jobVisibility : String</code> (optional)
<div>Set your test results visibility permissions. The <a href="https://wiki.saucelabs.com/display/DOCS/Sharing+the+Results+of+Sauce+Labs+Tests" rel="nofollow">Sauce Documentation</a> has all the various levels described in detail.</div>

</li>
</ul></div></li>
<li><code>$class: 'StabilityTestDataPublisher'</code><div>
<ul></ul></div></li>
<li><code>$class: 'TestCafePublisher'</code><div>
<ul></ul></div></li>
<li><code>$class: 'TestReporter'</code><div>
<ul></ul></div></li>
<li><code>$class: 'YoutrackTestDataPublisher'</code><div>
<ul></ul></div></li>
</ul></li>
</ul>


++++
