= Karaf Build Step Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/karaf-build-step">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'KarafBuildStepBuilder'])`: Execute Karaf command
++++
<ul><li><code>useCustomKaraf : boolean</code>
</li>
<li><code>karafHome : String</code>
</li>
<li><code>flags : String</code>
<div><div>
 <b>-a [port]</b>
 <p>specify the port to connect to</p><b>-h [host]</b>
 <p>specify the host to connect to</p><b>-u [user]</b>
 <p>specify the user name</p><b>-p [password]</b>
 <p>specify the password (optional, if not provided, the password is prompted)</p><b>-v</b>
 <p>raise verbosity</p><b>-l</b>
 <p>set client logging level. Set to 0 for ERROR logging and up to 4 for TRACE</p><b>-r [attempts]</b>
 <p>retry connection establishment (up to attempts times)</p><b>-d [delay]</b>
 <p>intra-retry delay (defaults to 2 seconds)</p><b>-f [file]</b>
 <p>read commands from the specified file</p><b>-k [keyFile]</b>
 <p>specify the private keyFile location when using key login, need have BouncyCastle registered as security provider using this flag</p><b>-t [timeout]</b>
 <p>define the client idle timeout</p>
</div></div>

</li>
<li><code>option</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'KarafCommandFileOption'</code><div>
<ul><li><code>file : String</code>
</li>
</ul></div></li>
<li><code>$class: 'KarafCommandScriptOption'</code><div>
<ul><li><code>script : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
</ul>


++++
