= Keeper Secrets Manager
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/keeper-secrets-manager">Visit the Jenkins Plugins site</a>
++++


=== `withKsm`: Inject secrets with Keeper Secrets Manager
++++
<ul><li><code>application</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>secrets</code> (optional)
<ul><b>Array / List of Nested Object</b>
<div><div>
 Setting up Keeper Notation to environmental variables.
</div></div>
<li><code>notation : String</code> (optional)
<div><h3>Overview</h3>
<p>Notation is used to pull a value from a secret record. Notation is prefixed with <b>keeper://</b>. The prefix is used to designate that environmental variable contains notation.</p>
<p>The notation is divided into three parts separated by a forward slash.</p><code> Record UID / &lt;field|custom_field|file&gt; / Label, Type, or File Name </code>
<p>The first part is the UID of the record.</p>
<p>The second is an enumeration for the three places a value can be stored in a secret.</p>
<ul>
 <li><b>field</b> - Standard field of the record, which are based on the record type. Examples of these are <i>login</i> and <i>password</i>. The field is referenced by its <i>type</i>.</li>
 <li><b>custom_field</b> - Custom fields a user can attach to a secret. The field is referenced by its <i>label</i> or its <i>type</i>.</li>
 <li><b>file</b> - Attached files on a record. The field is referenced by its file name.</li>
</ul>
<p></p>
<p>The third part is how the field is referenced. This is either the field type, label or name of the file. Some fields are complex. They can include multiple values and also dictionaries for the values.</p>
<h3>Examples</h3>
<p>Below is a record that contains the structure found in a record. The examples will reference this structure.</p>
<pre>    $ ksm secret get --title "My Record" --json

    {
        "uid": "Atu8tVgMxpB-iO4xT-Vu3Q",
        "title": "My Database",
        "type": "databaseCredentials",
        "fields": [
            {
                "type": "text",
                "value": [
                    "postgresql"
                ]
            },
            {
                "type": "host",
                "value": [
                    {
                        "hostName": "db.hostname",
                        "port": "5432"
                    }
                ]
            },
            {
                "type": "login",
                "value": [
                    "root"
                ]
            },
            {
                "type": "password",
                "value": [
                    "abc123"
                ]
            },
        ],
        "custom_fields": [
            {
                "label": "Admin Template",
                "type": "text",
                "value": [
                    "template1"
                ]
            },
            {
                "label": "Admin Contact",
                "type": "name",
                "value": [
                    {
                        "first": "John",
                        "middle": "X",
                        "last": "Smith"
                    }
                ]
            },
            {
                "label": "phone",
                "type": "phone",
                "value": [
                    {
                        "number": "555-5555555",
                        "ext": "55",
                        "type": "Work"
                    },
                    {
                        "number": "777-7777777",
                        "ext": "77",
                        "type": "Home"
                    }
                ]
            }
        ],
        "files": [
            {
                "name": "orm.svg",
                "title": "orm.svg",
                "type": "mage/svg+xml",
                "last_modified": 1622044028400,
                "size": 30744
            },
        ]
    }
</pre>
<h4>Example 1 - Simple Values</h4>
<p>A simple values is where there is only one literal value for the field. It looks like an array with only one string value. For our Database record type sample, the following will return a single value.</p><code> keeper://Atu8tVgMxpB-iO4xT-Vu3Q/field/text<br>
  keeper://Atu8tVgMxpB-iO4xT-Vu3Q/field/login<br>
  keeper://Atu8tVgMxpB-iO4xT-Vu3Q/field/password<br>
  keeper://Atu8tVgMxpB-iO4xT-Vu3Q/custom_field/Admin Template<br></code>
<p>If you attempt to retrieve a simple value of the field that contains a complex, you will get a JSON value. The notation <b>keeper://Atu8tVgMxpB-iO4xT-Vu3Q/field/host</b> would return <b>{"hostName": "db.hostname", "port": "5432"}</b>.</p>
<p>Also if retrieving a simple value of a field that has multiple values in array will result in only the first item being returned.</p>
<h4>Example 2 - Arrays and Dictionaries</h4>
<h5>Arrays</h5>
<p>Some fields contain multiple values. The additional values can be accessed using a index that starts at 0. This means the first value has an index of 0, the second has an index of 1, and so on. The following notation ..</p><code> keeper://Atu8tVgMxpB-iO4xT-Vu3Q/custom_field/phone[1] </code>
<p>would return the second item in the array.</p><code> {"number": "777-7777777", "ext": "77", "type": "Home"} </code>
<h5>Dictionaries</h5>
<p>Some values are dictionaries. For example the phone and host fields.</p><code> keeper://Atu8tVgMxpB-iO4xT-Vu3Q/custom_field/phone[1][number]<br>
  keeper://Atu8tVgMxpB-iO4xT-Vu3Q/custom_field/host[hostName]<br></code>
<p>To get the specific value in the dictionary, add the key to the notation.</p>
<h4>Example 3 - The Full Value</h4>
<p>To get the full value, the entire array returned in a JSON format, just use an empty <b>[]</b>. The following notation</p><code> keeper://Atu8tVgMxpB-iO4xT-Vu3Q/custom_field/phone[] </code>
<p>would return the entire value in a JSON format.</p><code> [{"number": "555-5555555", "ext": "55", "type": "Work"}, {"number": "777-7777777", "ext": "77", type": "Home"}] </code>
<h4>Example 4 - Files</h4>
<p>With notation, you can download files into an environmental variables. This works well with text based files, however mileage may var with binary files. Binary files may cause exceptions to be thrown. Also, there is a limit on the size of the file based on your OS's handling of environmental variables.</p><code> keeper://Atu8tVgMxpB-iO4xT-Vu3Q/file/orm.svg </code></div>

</li>
<li><code>destination : String</code> (optional)
</li>
<li><code>envVar : String</code> (optional)
<div><p>The environmental variable the secret will be placed.</p>
<p>Environmental variables can only contain letters, numbers, and underscores (_). Spaces are not allowed. The environmental variable also cannot start with a number.</p></div>

</li>
<li><code>filePath : String</code> (optional)
<div><p>The optional directories and file name, in the workspace, where the secret file will be created. If the directories in the path do not exist, they will be created.</p>
<p>The file will be removed when the path is done. Any directories created will not be removed. If you copy the secret file in your script, the copy will not be removed.</p></div>

</li>
</ul></li>
</ul></li>
</ul>


++++
