= Klocwork Analysis Plug-in
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/klocwork">Visit the Jenkins Plugins site</a>
++++


=== `klocworkBuildSpecGeneration`: Klocwork - Step 1 (CI/Full) - Capture Build Information
++++
<ul><li><code>buildSpecConfig</code>
<ul><b>Nested Object</b>
<li><code>buildCommand : String</code>
<div><div>
 Specify your project's build command. This command is used to compile the project and capture information about the build in a build specification file that Klocwork will use for the analysis.
</div></div>

</li>
<li><code>tool : String</code>
<div><div>
 The Klocwork tool used to generate the build specification, by default this is set to kwinject. 
 <table></table> Tools Available: kwinject monitors your C/C++ build to create a build specification kwmaven creates a Java build specification based on the information in your maven build file kwmavenw creates a Java build specification based on the information in your maven wrapper file kwjsspec creates a Javascript build specification file kwpyspec creates a Python build specification file kwktspec creates a Kotlin build specification file kwant creates a Java build specification based on the information in your ant build file create tracefile uses kwinject to create a trace file, mainly used for debugging kwgradle creates a Java build specification based on the information in your Gradle build file kwgradlew creates a Java build specification based on the information in your Gradle wrapper file
</div></div>

</li>
<li><code>output : String</code>
<div><div>
 Specify the build specification output filename and, optionally, its file path. By default, the build specification is written to kwinject.out in the current working directory. The specified file path can be absolute or relative to the current working directory. By default, the current working directory is the workspace directory.
</div></div>

</li>
<li><code>additionalOpts : String</code>
<div><div>
 Specify other tool options here. Separate the options with whitespace; surround any arguments with whitespace in double quotes.
</div></div>

</li>
<li><code>ignoreErrors : boolean</code>
<div><div>
 Ignore any error return codes from this step and continue.
</div></div>

</li>
<li><code>workDir : String</code> (optional)
<div><div>
 Specify the working directory path from where the Klocwork Build Spec Generation command will be executed. This path must both exist and be relative to the workspace directory. If no value is specified in this field then the Klocwork Build Spec Generation command will be executed from the workspace directory.
</div></div>

</li>
</ul></li>
</ul>


++++
=== `klocworkFailureCondition`: Klocwork - Post Analysis (Full/CI) - Build Failure Conditions (Optional)
++++
<ul><li><code>failureConditionConfig</code>
<ul><b>Nested Object</b>
<li><code>enableServerFailureCondition : boolean</code> (optional)
<div><div>
 <h2>Full integration analysis build failure conditions (Full)</h2>
 <p>Create multiple build failure conditions by using queries that are sent to the Klocwork Server through the Web API.</p>
 <p>Filter issues based on the search query, then provide the status to set the build to, along with the threshold (the number of issues to meet this criteria).</p>
 <p>Note: unless specified, the query runs with issue grouping turned off (grouping:off).</p>
</div></div>

</li>
<li><code>failureConditionServerConfigs</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>jobResult : String</code>
</li>
<li><code>query : String</code>
</li>
<li><code>threshold : String</code>
</li>
<li><code>conditionName : String</code>
</li>
<li><code>stopBuild : boolean</code>
</li>
<li><code>enableHTMLReporting : boolean</code>
</li>
</ul></li>
<li><code>enableCiFailureCondition : boolean</code> (optional)
<div><div>
 <h2>Differential analysis build failure conditions (CI)</h2>
 <p>Set a threshold for the differential analysis build failure conditions. Pass the build if the threshold is not exceeded; fail otherwise.</p>
 <p>This step checks the XML report generated by the differential analysis build step. You can filter which issues appear in this report by providing additional options to the differential analysis build step.</p>
 <p>This step counts the total number of issues in the XML report.</p>
</div></div>

</li>
<li><code>enableDesktopFailureCondition : boolean</code> (optional)
</li>
<li><code>failureConditionCiConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>withDiffList : boolean</code>
</li>
<li><code>diffFileList : String</code>
</li>
<li><code>threshold : String</code> (optional)
</li>
<li><code>reportFile : String</code> (optional)
</li>
<li><code>enableHTMLReporting : boolean</code> (optional)
</li>
<li><code>enabledSeverites</code> (optional)
<ul><b>Nested Object</b>
<li><code>critical : boolean</code>
</li>
<li><code>error : boolean</code>
</li>
<li><code>warning : boolean</code>
</li>
<li><code>review : boolean</code>
</li>
<li><code>fiveToTen : boolean</code>
</li>
</ul></li>
<li><code>enabledStatuses</code> (optional)
<ul><b>Nested Object</b>
<li><code>analyze : boolean</code>
</li>
<li><code>ignore : boolean</code>
</li>
<li><code>notAProblem : boolean</code>
</li>
<li><code>fix : boolean</code>
</li>
<li><code>fixInNextRelease : boolean</code>
</li>
<li><code>fixInLaterRelease : boolean</code>
</li>
<li><code>defer : boolean</code>
</li>
<li><code>filter : boolean</code>
</li>
</ul></li>
<li><code>failUnstable : boolean</code> (optional)
</li>
<li><code>name : String</code> (optional)
</li>
<li><code>stopBuild : boolean</code> (optional)
</li>
</ul></li>
<li><code>failureConditionCiConfigs</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>withDiffList : boolean</code>
</li>
<li><code>diffFileList : String</code>
</li>
<li><code>threshold : String</code> (optional)
</li>
<li><code>reportFile : String</code> (optional)
</li>
<li><code>enableHTMLReporting : boolean</code> (optional)
</li>
<li><code>enabledSeverites</code> (optional)
<ul><b>Nested Object</b>
<li><code>critical : boolean</code>
</li>
<li><code>error : boolean</code>
</li>
<li><code>warning : boolean</code>
</li>
<li><code>review : boolean</code>
</li>
<li><code>fiveToTen : boolean</code>
</li>
</ul></li>
<li><code>enabledStatuses</code> (optional)
<ul><b>Nested Object</b>
<li><code>analyze : boolean</code>
</li>
<li><code>ignore : boolean</code>
</li>
<li><code>notAProblem : boolean</code>
</li>
<li><code>fix : boolean</code>
</li>
<li><code>fixInNextRelease : boolean</code>
</li>
<li><code>fixInLaterRelease : boolean</code>
</li>
<li><code>defer : boolean</code>
</li>
<li><code>filter : boolean</code>
</li>
</ul></li>
<li><code>failUnstable : boolean</code> (optional)
</li>
<li><code>name : String</code> (optional)
</li>
<li><code>stopBuild : boolean</code> (optional)
</li>
</ul></li>
<li><code>failureConditionDesktopConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>withDiffList : boolean</code>
</li>
<li><code>diffFileList : String</code>
</li>
<li><code>threshold : String</code> (optional)
</li>
<li><code>reportFile : String</code> (optional)
</li>
<li><code>enableHTMLReporting : boolean</code> (optional)
</li>
<li><code>enabledSeverites</code> (optional)
<ul><b>Nested Object</b>
<li><code>critical : boolean</code>
</li>
<li><code>error : boolean</code>
</li>
<li><code>warning : boolean</code>
</li>
<li><code>review : boolean</code>
</li>
<li><code>fiveToTen : boolean</code>
</li>
</ul></li>
<li><code>enabledStatuses</code> (optional)
<ul><b>Nested Object</b>
<li><code>analyze : boolean</code>
</li>
<li><code>ignore : boolean</code>
</li>
<li><code>notAProblem : boolean</code>
</li>
<li><code>fix : boolean</code>
</li>
<li><code>fixInNextRelease : boolean</code>
</li>
<li><code>fixInLaterRelease : boolean</code>
</li>
<li><code>defer : boolean</code>
</li>
<li><code>filter : boolean</code>
</li>
</ul></li>
<li><code>failUnstable : boolean</code> (optional)
</li>
<li><code>name : String</code> (optional)
</li>
<li><code>stopBuild : boolean</code> (optional)
</li>
</ul></li>
</ul></li>
</ul>


++++
=== `klocworkIncremental`: Klocwork - Step 2 (CI) - Run Differential Analysis
++++
<ul><li><code>ciConfig</code>
<ul><b>Nested Object</b>
<li><code>buildSpec : String</code>
<div><div>
 Build specification to use for analysis. Path is relative to the workspace
</div></div>

</li>
<li><code>projectDir : String</code>
</li>
<li><code>cleanupProject : boolean</code>
</li>
<li><code>reportFile : String</code>
<div><div>
 XML report file in which to store Klocwork results. Optional, in case you want to use the XML report for something custom; otherwise, a default file is created for the post-build step.
</div></div>

</li>
<li><code>additionalOpts : String</code>
<div><div>
 Additional options added to the kwciagent run command. For example, specify the number of jobs/threads to use (--jobs-num) or which filters to apply (--severity  --taxonomy  --system)
</div>
<div>
 See the Klocwork documentation for more information.
</div></div>

</li>
<li><code>incrementalAnalysis : boolean</code>
<div><div>
 <h3>Analyze changed files only</h3>
 <p>This feature allows for quick, incremental analyses of changed source files to enable pre/post-checkin/commit-like behavior . The goal is that only changed files are analyzed by the Klocwork kwciagent tool to replicate the local analysis developers would perform by using our supported IDE plugins or the command line utility. To enable this behavior, the plugin takes a list of the changed files from the SCM; this enables the system to analyze only the changed files when the workspace isn’t kept. Leave this cleared to analyze the whole project, or, if the workspace is kept, to perform a standard incremental analysis.</p>
 <h4>Diff file list</h4>
 <p>The diff file list is the file that contains the changed source files for Klocwork to analyze. All analyzed files must exist in the build specification generated by kwinject.</p>
 <p>Note: All files to be analyzed must exist in the build specification.</p>
 <h5>Using Git</h5>
 <p>If using Git, provide the previous commit that Git should perform a "diff" against. The change list between the current commit and the specified previous commit will be added to the diff file list for Klocwork to process by automatically calling "git diff &lt;previous_commit&gt;" during the build. Note: If you are using Git jenkins plugin to obtain source files for you pipeline job be sure to use 'Pipeline script from SCM' and specify the previous commit with the environment variable, 'GIT_PREVIOUS_COMMIT'. Also be aware that the first build in the job won't be able to access GIT_PREVIOUS_COMMIT and the first build will run full CI analysis.</p>
 <h5>Manual</h5>
 <p>If you are not using Git, or want to manually generate the change list by using Git, select this option. You will need to generate the diff file list by using a custom build-step (or similar). List one changed source file on each line of the file.</p>
</div></div>

</li>
<li><code>differentialAnalysisConfig</code>
<ul><b>Nested Object</b>
<li><code>diffType : String</code>
</li>
<li><code>gitPreviousCommit : String</code>
</li>
<li><code>diffFileList : String</code>
</li>
</ul></li>
</ul></li>
</ul>


++++
=== `klocworkIntegrationStep1`: Klocwork - Step 2 (Full) - Run Analysis
++++
<ul><li><code>serverConfig</code>
<ul><b>Nested Object</b>
<li><code>buildSpec : String</code>
<div><div>
 Build specification to use for analysis. Path is relative to the workspace.
</div></div>

</li>
<li><code>tablesDir : String</code>
<div><div>
 Specify the location of the tables directory, for example, ${MY_VAR}/kwtables.
</div></div>

</li>
<li><code>incrementalAnalysis : boolean</code>
</li>
<li><code>ignoreCompileErrors : boolean</code>
<div><div>
 Ignore compile errors encountered by kwbuildproject. This setting will not ignore a return code that indicates that kwbuildproject failed to the extent that no results are generated.
</div></div>

</li>
<li><code>importConfig : String</code>
<div><div>
 Optionally, provide configuration files to import to the project before running the analysis. If the checker configuration (for example, analysis_profile.pconf) is under version control, you can provide the file here and it will be automatically imported for each build.
</div>
<div>
 Specify multiple files by separating them with commas (",").
</div></div>

</li>
<li><code>additionalOpts : String</code>
</li>
<li><code>disableKwdeploy : boolean</code>
<div><div>
 By default, kwdeploy runs before the analysis, to ensure the checkers are up-to-date. Enable this setting if you don't want kwdeploy to run before the analysis.
</div></div>

</li>
<li><code>duplicateFrom : String</code> (optional)
<div><div>
 Optional setting to specify the name of an existing Klocwork project. Klocwork will duplicate that project's configuration settings.
</div></div>

</li>
<li><code>enabledCreateProject : boolean</code> (optional)
<div><div>
 Enable to create a new Klocwork project on the server if one does not exist with the name specified. This can be useful when using multi-branch pipeline jobs.
</div></div>

</li>
</ul></li>
</ul>


++++
=== `klocworkIntegrationStep2`: Klocwork - Step 3 (Full) - Load Analysis Results
++++
<ul><li><code>serverConfig</code>
<ul><b>Nested Object</b>
<li><code>tablesDir : String</code> (optional)
</li>
<li><code>buildName : String</code> (optional)
<div><div>
 Specify the name of the build for the Klocwork server, for example, ${MY_VAR}-${GIT_COMMIT}. If empty, Klocwork uses an auto increment to name the builds.
</div></div>

</li>
<li><code>additionalOpts : String</code> (optional)
</li>
</ul></li>
<li><code>reportConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>displayChart : boolean</code>
</li>
<li><code>chartHeight : String</code> (optional)
</li>
<li><code>chartWidth : String</code> (optional)
</li>
<li><code>query : String</code> (optional)
</li>
</ul></li>
</ul>


++++
=== `klocworkIssueSync`: Klocwork - Post Analysis (Full) - Cross-Project Issue Sync (Optional)
++++
<ul><li><code>syncConfig</code>
<ul><b>Nested Object</b>
<li><code>dryRun : boolean</code>
<div><div>
 Cross synchronisation reads and writes to the Klocwork database. Therefore, we strongly recommend that you first try a Dry Run of the command (which skips the writing) and verify that the command works as expected.
</div></div>

</li>
<li><code>lastSync : String</code>
<div><div>
 Specify the "last synchronisation" date (how far back Klocwork should go when synchronising issue citations).
</div>
<div>
 Format is "DD-MM-YYYY hh:mm:ss".
</div>
<div>
 For example, "03-00-0000 00:00:00" will go back 3 days in time.
</div></div>

</li>
<li><code>projectRegexp : String</code>
<div><div>
 A regular expression that is used to retrieve Klocwork projects that should be processed during synchronisation. If you want to process all projects, leave empty.
</div>
<div>
 For example, if you prepend projects with "DEPT-" to indicate a particular department the regular expression "^DEPT-" will match all these projects
</div></div>

</li>
<li><code>statusAnalyze : boolean</code>
</li>
<li><code>statusIgnore : boolean</code>
</li>
<li><code>statusNotAProblem : boolean</code>
</li>
<li><code>statusFix : boolean</code>
</li>
<li><code>statusFixInNextRelease : boolean</code>
</li>
<li><code>statusFixInLaterRelease : boolean</code>
</li>
<li><code>statusDefer : boolean</code>
</li>
<li><code>statusFilter : boolean</code>
</li>
<li><code>additionalOpts : String</code>
<div><div>
 Additional options added to the kwxsync command.
</div>
<div>
 See the Klocwork documentation for more information.
</div></div>

</li>
</ul></li>
</ul>


++++
=== `step([$class: 'KlocworkBuildSpecBuilder'])`: Klocwork - Step 1 (CI/Full) - Capture Build Information
++++
<div><div>
 <b>Integration analysis (Full)</b>
</div>
<br>
<div>
 Use the following steps to perform a Klocwork integration analysis and load the results to the Klocwork Server:
</div>
<br>
<div>
 <table></table> Klocwork - Step 1 (CI/Full) - Capture Build Information runs a Klocwork build specification generation tool to capture compilation information about the project Klocwork - Step 2 (Full) - Run Analysis runs the Klocwork Server analysis engine against the data captured within the build specification Klocwork - Step 3 (Full) - Load Analysis Results runs the Klocwork Server load tool, which imports analysis data into the Klocwork Server database
</div>
<br>
<div>
 <b>Differential Analysis (CI)</b>
</div>
<br>
<div>
 Use the following steps to perform a differential analysis, which does not publish the results to the Klocwork Server and only reports the new issues detected since the previous integration analysis. Differential analysis can be used as a quality measure to reduce new issues being added to the Klocwork Server, and can also be configured to only analyze the changed files from the checkin, making the process much quicker:
</div>
<br>
<div>
 <table></table> Klocwork - Step 1 (CI/Full) - Capture Build Information runs a Klocwork build specification generation tool to capture compilation information about the project Klocwork - Step 2 (CI) - Run Differential Analysis runs an analysis only on the changed files by using the Klocwork command line user tool
</div></div>
<ul><li><code>buildSpecConfig</code>
<ul><b>Nested Object</b>
<li><code>buildCommand : String</code>
<div><div>
 Specify your project's build command. This command is used to compile the project and capture information about the build in a build specification file that Klocwork will use for the analysis.
</div></div>

</li>
<li><code>tool : String</code>
<div><div>
 The Klocwork tool used to generate the build specification, by default this is set to kwinject. 
 <table></table> Tools Available: kwinject monitors your C/C++ build to create a build specification kwmaven creates a Java build specification based on the information in your maven build file kwmavenw creates a Java build specification based on the information in your maven wrapper file kwjsspec creates a Javascript build specification file kwpyspec creates a Python build specification file kwktspec creates a Kotlin build specification file kwant creates a Java build specification based on the information in your ant build file create tracefile uses kwinject to create a trace file, mainly used for debugging kwgradle creates a Java build specification based on the information in your Gradle build file kwgradlew creates a Java build specification based on the information in your Gradle wrapper file
</div></div>

</li>
<li><code>output : String</code>
<div><div>
 Specify the build specification output filename and, optionally, its file path. By default, the build specification is written to kwinject.out in the current working directory. The specified file path can be absolute or relative to the current working directory. By default, the current working directory is the workspace directory.
</div></div>

</li>
<li><code>additionalOpts : String</code>
<div><div>
 Specify other tool options here. Separate the options with whitespace; surround any arguments with whitespace in double quotes.
</div></div>

</li>
<li><code>ignoreErrors : boolean</code>
<div><div>
 Ignore any error return codes from this step and continue.
</div></div>

</li>
<li><code>workDir : String</code> (optional)
<div><div>
 Specify the working directory path from where the Klocwork Build Spec Generation command will be executed. This path must both exist and be relative to the workspace directory. If no value is specified in this field then the Klocwork Build Spec Generation command will be executed from the workspace directory.
</div></div>

</li>
</ul></li>
</ul>


++++
=== `step([$class: 'KlocworkCiBuilder'])`: Klocwork - Step 2 (CI) - Run Differential Analysis
++++
<ul><li><code>ciConfig</code>
<ul><b>Nested Object</b>
<li><code>buildSpec : String</code>
<div><div>
 Build specification to use for analysis. Path is relative to the workspace
</div></div>

</li>
<li><code>projectDir : String</code>
</li>
<li><code>cleanupProject : boolean</code>
</li>
<li><code>reportFile : String</code>
<div><div>
 XML report file in which to store Klocwork results. Optional, in case you want to use the XML report for something custom; otherwise, a default file is created for the post-build step.
</div></div>

</li>
<li><code>additionalOpts : String</code>
<div><div>
 Additional options added to the kwciagent run command. For example, specify the number of jobs/threads to use (--jobs-num) or which filters to apply (--severity  --taxonomy  --system)
</div>
<div>
 See the Klocwork documentation for more information.
</div></div>

</li>
<li><code>incrementalAnalysis : boolean</code>
<div><div>
 <h3>Analyze changed files only</h3>
 <p>This feature allows for quick, incremental analyses of changed source files to enable pre/post-checkin/commit-like behavior . The goal is that only changed files are analyzed by the Klocwork kwciagent tool to replicate the local analysis developers would perform by using our supported IDE plugins or the command line utility. To enable this behavior, the plugin takes a list of the changed files from the SCM; this enables the system to analyze only the changed files when the workspace isn’t kept. Leave this cleared to analyze the whole project, or, if the workspace is kept, to perform a standard incremental analysis.</p>
 <h4>Diff file list</h4>
 <p>The diff file list is the file that contains the changed source files for Klocwork to analyze. All analyzed files must exist in the build specification generated by kwinject.</p>
 <p>Note: All files to be analyzed must exist in the build specification.</p>
 <h5>Using Git</h5>
 <p>If using Git, provide the previous commit that Git should perform a "diff" against. The change list between the current commit and the specified previous commit will be added to the diff file list for Klocwork to process by automatically calling "git diff &lt;previous_commit&gt;" during the build. Note: If you are using Git jenkins plugin to obtain source files for you pipeline job be sure to use 'Pipeline script from SCM' and specify the previous commit with the environment variable, 'GIT_PREVIOUS_COMMIT'. Also be aware that the first build in the job won't be able to access GIT_PREVIOUS_COMMIT and the first build will run full CI analysis.</p>
 <h5>Manual</h5>
 <p>If you are not using Git, or want to manually generate the change list by using Git, select this option. You will need to generate the diff file list by using a custom build-step (or similar). List one changed source file on each line of the file.</p>
</div></div>

</li>
<li><code>differentialAnalysisConfig</code>
<ul><b>Nested Object</b>
<li><code>diffType : String</code>
</li>
<li><code>gitPreviousCommit : String</code>
</li>
<li><code>diffFileList : String</code>
</li>
</ul></li>
</ul></li>
</ul>


++++
=== `step([$class: 'KlocworkFailureConditionPublisher'])`: Klocwork - Post Analysis (Full/CI) - Build Failure Conditions (Optional)
++++
<ul><li><code>failureConditionConfig</code>
<ul><b>Nested Object</b>
<li><code>enableServerFailureCondition : boolean</code> (optional)
<div><div>
 <h2>Full integration analysis build failure conditions (Full)</h2>
 <p>Create multiple build failure conditions by using queries that are sent to the Klocwork Server through the Web API.</p>
 <p>Filter issues based on the search query, then provide the status to set the build to, along with the threshold (the number of issues to meet this criteria).</p>
 <p>Note: unless specified, the query runs with issue grouping turned off (grouping:off).</p>
</div></div>

</li>
<li><code>failureConditionServerConfigs</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>jobResult : String</code>
</li>
<li><code>query : String</code>
</li>
<li><code>threshold : String</code>
</li>
<li><code>conditionName : String</code>
</li>
<li><code>stopBuild : boolean</code>
</li>
<li><code>enableHTMLReporting : boolean</code>
</li>
</ul></li>
<li><code>enableCiFailureCondition : boolean</code> (optional)
<div><div>
 <h2>Differential analysis build failure conditions (CI)</h2>
 <p>Set a threshold for the differential analysis build failure conditions. Pass the build if the threshold is not exceeded; fail otherwise.</p>
 <p>This step checks the XML report generated by the differential analysis build step. You can filter which issues appear in this report by providing additional options to the differential analysis build step.</p>
 <p>This step counts the total number of issues in the XML report.</p>
</div></div>

</li>
<li><code>enableDesktopFailureCondition : boolean</code> (optional)
</li>
<li><code>failureConditionCiConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>withDiffList : boolean</code>
</li>
<li><code>diffFileList : String</code>
</li>
<li><code>threshold : String</code> (optional)
</li>
<li><code>reportFile : String</code> (optional)
</li>
<li><code>enableHTMLReporting : boolean</code> (optional)
</li>
<li><code>enabledSeverites</code> (optional)
<ul><b>Nested Object</b>
<li><code>critical : boolean</code>
</li>
<li><code>error : boolean</code>
</li>
<li><code>warning : boolean</code>
</li>
<li><code>review : boolean</code>
</li>
<li><code>fiveToTen : boolean</code>
</li>
</ul></li>
<li><code>enabledStatuses</code> (optional)
<ul><b>Nested Object</b>
<li><code>analyze : boolean</code>
</li>
<li><code>ignore : boolean</code>
</li>
<li><code>notAProblem : boolean</code>
</li>
<li><code>fix : boolean</code>
</li>
<li><code>fixInNextRelease : boolean</code>
</li>
<li><code>fixInLaterRelease : boolean</code>
</li>
<li><code>defer : boolean</code>
</li>
<li><code>filter : boolean</code>
</li>
</ul></li>
<li><code>failUnstable : boolean</code> (optional)
</li>
<li><code>name : String</code> (optional)
</li>
<li><code>stopBuild : boolean</code> (optional)
</li>
</ul></li>
<li><code>failureConditionCiConfigs</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>withDiffList : boolean</code>
</li>
<li><code>diffFileList : String</code>
</li>
<li><code>threshold : String</code> (optional)
</li>
<li><code>reportFile : String</code> (optional)
</li>
<li><code>enableHTMLReporting : boolean</code> (optional)
</li>
<li><code>enabledSeverites</code> (optional)
<ul><b>Nested Object</b>
<li><code>critical : boolean</code>
</li>
<li><code>error : boolean</code>
</li>
<li><code>warning : boolean</code>
</li>
<li><code>review : boolean</code>
</li>
<li><code>fiveToTen : boolean</code>
</li>
</ul></li>
<li><code>enabledStatuses</code> (optional)
<ul><b>Nested Object</b>
<li><code>analyze : boolean</code>
</li>
<li><code>ignore : boolean</code>
</li>
<li><code>notAProblem : boolean</code>
</li>
<li><code>fix : boolean</code>
</li>
<li><code>fixInNextRelease : boolean</code>
</li>
<li><code>fixInLaterRelease : boolean</code>
</li>
<li><code>defer : boolean</code>
</li>
<li><code>filter : boolean</code>
</li>
</ul></li>
<li><code>failUnstable : boolean</code> (optional)
</li>
<li><code>name : String</code> (optional)
</li>
<li><code>stopBuild : boolean</code> (optional)
</li>
</ul></li>
<li><code>failureConditionDesktopConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>withDiffList : boolean</code>
</li>
<li><code>diffFileList : String</code>
</li>
<li><code>threshold : String</code> (optional)
</li>
<li><code>reportFile : String</code> (optional)
</li>
<li><code>enableHTMLReporting : boolean</code> (optional)
</li>
<li><code>enabledSeverites</code> (optional)
<ul><b>Nested Object</b>
<li><code>critical : boolean</code>
</li>
<li><code>error : boolean</code>
</li>
<li><code>warning : boolean</code>
</li>
<li><code>review : boolean</code>
</li>
<li><code>fiveToTen : boolean</code>
</li>
</ul></li>
<li><code>enabledStatuses</code> (optional)
<ul><b>Nested Object</b>
<li><code>analyze : boolean</code>
</li>
<li><code>ignore : boolean</code>
</li>
<li><code>notAProblem : boolean</code>
</li>
<li><code>fix : boolean</code>
</li>
<li><code>fixInNextRelease : boolean</code>
</li>
<li><code>fixInLaterRelease : boolean</code>
</li>
<li><code>defer : boolean</code>
</li>
<li><code>filter : boolean</code>
</li>
</ul></li>
<li><code>failUnstable : boolean</code> (optional)
</li>
<li><code>name : String</code> (optional)
</li>
<li><code>stopBuild : boolean</code> (optional)
</li>
</ul></li>
</ul></li>
</ul>


++++
=== `step([$class: 'KlocworkServerAnalysisBuilder'])`: Klocwork - Step 2 (Full) - Run Analysis
++++
<ul><li><code>serverConfig</code>
<ul><b>Nested Object</b>
<li><code>buildSpec : String</code>
<div><div>
 Build specification to use for analysis. Path is relative to the workspace.
</div></div>

</li>
<li><code>tablesDir : String</code>
<div><div>
 Specify the location of the tables directory, for example, ${MY_VAR}/kwtables.
</div></div>

</li>
<li><code>incrementalAnalysis : boolean</code>
</li>
<li><code>ignoreCompileErrors : boolean</code>
<div><div>
 Ignore compile errors encountered by kwbuildproject. This setting will not ignore a return code that indicates that kwbuildproject failed to the extent that no results are generated.
</div></div>

</li>
<li><code>importConfig : String</code>
<div><div>
 Optionally, provide configuration files to import to the project before running the analysis. If the checker configuration (for example, analysis_profile.pconf) is under version control, you can provide the file here and it will be automatically imported for each build.
</div>
<div>
 Specify multiple files by separating them with commas (",").
</div></div>

</li>
<li><code>additionalOpts : String</code>
</li>
<li><code>disableKwdeploy : boolean</code>
<div><div>
 By default, kwdeploy runs before the analysis, to ensure the checkers are up-to-date. Enable this setting if you don't want kwdeploy to run before the analysis.
</div></div>

</li>
<li><code>duplicateFrom : String</code> (optional)
<div><div>
 Optional setting to specify the name of an existing Klocwork project. Klocwork will duplicate that project's configuration settings.
</div></div>

</li>
<li><code>enabledCreateProject : boolean</code> (optional)
<div><div>
 Enable to create a new Klocwork project on the server if one does not exist with the name specified. This can be useful when using multi-branch pipeline jobs.
</div></div>

</li>
</ul></li>
</ul>


++++
=== `step([$class: 'KlocworkServerLoadBuilder'])`: Klocwork - Step 3 (Full) - Load Analysis Results
++++
<ul><li><code>serverConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>tablesDir : String</code> (optional)
</li>
<li><code>buildName : String</code> (optional)
<div><div>
 Specify the name of the build for the Klocwork server, for example, ${MY_VAR}-${GIT_COMMIT}. If empty, Klocwork uses an auto increment to name the builds.
</div></div>

</li>
<li><code>additionalOpts : String</code> (optional)
</li>
</ul></li>
<li><code>reportConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>displayChart : boolean</code>
</li>
<li><code>chartHeight : String</code> (optional)
</li>
<li><code>chartWidth : String</code> (optional)
</li>
<li><code>query : String</code> (optional)
</li>
</ul></li>
</ul>


++++
=== `step([$class: 'KlocworkXSyncBuilder'])`: Klocwork - Post Analysis (Full) - Cross-Project Issue Sync (Optional)
++++
<ul><li><code>syncConfig</code>
<ul><b>Nested Object</b>
<li><code>dryRun : boolean</code>
<div><div>
 Cross synchronisation reads and writes to the Klocwork database. Therefore, we strongly recommend that you first try a Dry Run of the command (which skips the writing) and verify that the command works as expected.
</div></div>

</li>
<li><code>lastSync : String</code>
<div><div>
 Specify the "last synchronisation" date (how far back Klocwork should go when synchronising issue citations).
</div>
<div>
 Format is "DD-MM-YYYY hh:mm:ss".
</div>
<div>
 For example, "03-00-0000 00:00:00" will go back 3 days in time.
</div></div>

</li>
<li><code>projectRegexp : String</code>
<div><div>
 A regular expression that is used to retrieve Klocwork projects that should be processed during synchronisation. If you want to process all projects, leave empty.
</div>
<div>
 For example, if you prepend projects with "DEPT-" to indicate a particular department the regular expression "^DEPT-" will match all these projects
</div></div>

</li>
<li><code>statusAnalyze : boolean</code>
</li>
<li><code>statusIgnore : boolean</code>
</li>
<li><code>statusNotAProblem : boolean</code>
</li>
<li><code>statusFix : boolean</code>
</li>
<li><code>statusFixInNextRelease : boolean</code>
</li>
<li><code>statusFixInLaterRelease : boolean</code>
</li>
<li><code>statusDefer : boolean</code>
</li>
<li><code>statusFilter : boolean</code>
</li>
<li><code>additionalOpts : String</code>
<div><div>
 Additional options added to the kwxsync command.
</div>
<div>
 See the Klocwork documentation for more information.
</div></div>

</li>
</ul></li>
</ul>


++++
=== `klocworkWrapper`: Klocwork - Build Environment Settings
++++
<ul><li><code>serverConfig : String</code>
<div><div>
 Create server configurations on the <a rel="nofollow">Configure System</a> page.
</div></div>

</li>
<li><code>installConfig : String</code>
<div><div>
 You can create install configurations on the <a rel="nofollow">Configure System</a> page. When used, the system updates the build environment's PATH variable to include the Klocwork installation PATH provided by the selected configuration.
</div></div>

</li>
<li><code>serverProject : String</code>
<div><div>
 The Klocwork Server project or stream to run a server build against or to connect to for CI analysis.
</div></div>

</li>
<li><code>ltoken : String</code>
<div><div>
 Optionally, specify a custom ltoken location. The Klocwork ltoken is used to authenticate with the Klocwork Server. The default ltoken location is in the .klocwork directory which is located in the home directory of the user running the process, for example: C:\Users\user_name\.klocwork\ltoken. See the Klocwork documentation for more information.
</div></div>

</li>
</ul>


++++
