= Kobiton
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/kobiton-integration">Visit the Jenkins Plugins site</a>
++++


=== `appUploaderBuilder`: Upload application to Kobiton Apps Repository
++++
<ul><li><code>uploadPath : String</code>
<div><div>
 The path to your application (.apk or .ipa) in your machine
</div></div>

</li>
<li><code>isUpdateVersion : boolean</code>
<div><p>The Kobiton Apps Repository helps users manage different versions of their application.</p></div>

</li>
<li><code>appId : int</code>
<div><div>
 ID of existing application
</div></div>

</li>
</ul>


++++
=== `credentialsBuildWrapper`: Kobiton
++++
<ul><li><code>username : String</code>
<div><div>
 <b>(Required)</b> Your Kobiton username. It can be found in the Kobiton Portal under <a href="https://portal.kobiton.com/profile/account" rel="nofollow">Profile</a>.
</div></div>

</li>
<li><code>apiKey</code>
<div><div>
 <b>(Required)</b> Your Kobiton API key. It can be found in the Kobiton Portal under <a href="https://portal.kobiton.com/settings/keys" rel="nofollow">Settings</a>.
</div></div>

<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>standaloneUrl : String</code>
<div><div>
 <i>(Optional)</i> URL for your Kobiton standalone environment (leaving this field blank will result in using the default Kobiton Production URL)
</div></div>

</li>
</ul>


++++
