= Kubernetes plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/kubernetes">Visit the Jenkins Plugins site</a>
++++


=== `container`: Run build steps in a container
++++
<div><div>
 Selects a container of the agent pod so that all shell steps are executed in that container.
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>shell : String</code> (optional)
<div><p>Specifies a shell which will run inside the container and process requests from Jenkins to run executables, set environment variables, and similar infrastructure.</p>
<p>This does <strong>not</strong> affect the shell used to run user code, such as <code>sh</code> steps. To run your scripts with a specific shell on Linux, use an interpreter line:</p>
<pre><code>sh '''#!/bin/bash
for x in {0..9}; do echo x; done
'''</code></pre>
<p>or just use a subprocess and an externally versioned script:</p>
<pre><code>sh 'bash ci.sh'</code></pre>
<p>On Windows, choose between the <code>bat</code> or <code>powershell</code> steps.</p>
<p>For a pod running on Linux, defaults to <code>sh</code>, which should be in <code>$PATH</code>; for a pod running on Windows, defaults to <code>cmd</code>, which should be in <code>%Path%</code>. Should not generally be overridden.</p></div>

</li>
</ul>


++++
=== `podTemplate`: Define a podTemplate to use in the kubernetes plugin
++++
<div><p>Defines a Kubernetes pod template that can be used to create nodes.</p>
<p></p>
<p>Example:</p>
<pre>podTemplate(...) {
    node(POD_LABEL) {
        // some steps
    }
}
</pre></div>
<ul><li><code>activeDeadlineSeconds : int</code> (optional)
</li>
<li><code>annotations</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>key : String</code>
<div>The annotation key.</div>

</li>
<li><code>value : String</code>
<div>The annotation value.</div>

</li>
</ul></li>
<li><code>cloud : String</code> (optional)
<div>The Kubernetes cloud to use to schedule the pod.
<br>
 If unset, the first available Kubernetes cloud will be used.</div>

</li>
<li><code>containers</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
<div>The name for the container to be run. One container is automatically created with the name <code>jnlp</code>, and runs the Jenkins agent. In order to replace the default agent image, the container with the agent must be named <code>jnlp</code>.</div>

</li>
<li><code>image : String</code>
<div>Container image (repository, name, and tag) for a Jenkins inbound agent. Connection details will be passed as environment variables as per <a href="https://github.com/jenkinsci/docker-inbound-agent/#running-this-container" rel="nofollow">documentation</a>.</div>

</li>
<li><code>alwaysPullImage : boolean</code> (optional)
<div>If ticked, the latest version of the image will be pulled every time it is used. See <a href="https://kubernetes.io/docs/concepts/containers/images/#updating-images" rel="nofollow">Images - Kubernetes</a> for the default Kubernetes behaviour.</div>

</li>
<li><code>args : String</code> (optional)
<div><p>Arguments to pass to the command.</p>
<p><code>${computer.jnlpmac}</code> and <code>${computer.name}</code> are replaced with the agent secret and name respectively.</p>
<p>For Windows containers the args <code>Start-Sleep 999999</code> are reasonable choices to go with <code>powershell</code>.</p></div>

</li>
<li><code>command : String</code> (optional)
<div><p>Override the image entrypoint with a different one.</p>
<p>For Windows containers <code>powershell</code> is a good default.</p></div>

</li>
<li><code>envVars</code> (optional)
<div>The environment variables to pass to the container.</div>

<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>containerEnvVar</code><div>
<ul><li><code>key : String</code>
<div>The environment variable key.</div>

</li>
<li><code>value : String</code>
<div>The environment variable value.</div>

</li>
</ul></div></li>
<li><code>envVar</code><div>
<ul><li><code>key : String</code>
<div>The environment variable key.</div>

</li>
<li><code>value : String</code>
<div>The environment variable value.</div>

</li>
</ul></div></li>
<li><code>podEnvVar</code><div>
<ul><li><code>key : String</code>
<div>The environment variable key.</div>

</li>
<li><code>value : String</code>
<div>The environment variable value.</div>

</li>
</ul></div></li>
<li><code>secretEnvVar</code><div>
<ul><li><code>key : String</code>
<div>The environment variable key.</div>

</li>
<li><code>secretName : String</code>
<div>Name of secret to lookup from Kubernetes.</div>

</li>
<li><code>secretKey : String</code>
<div>Key of secret to lookup from Kubernetes.</div>

</li>
<li><code>optional : boolean</code>
<div>Whether this secret is optional.</div>

</li>
</ul></div></li>
</ul></li>
<li><code>livenessProbe</code> (optional)
<ul><b>Nested Object</b>
<li><code>execArgs : String</code>
<div>Command executed by the liveness probe.</div>

</li>
<li><code>timeoutSeconds : int</code>
<div>Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1.</div>

</li>
<li><code>initialDelaySeconds : int</code>
<div>Number of seconds after the container has started before liveness or readiness probes are initiated. Defaults to 0 seconds. Minimum value is 0.</div>

</li>
<li><code>failureThreshold : int</code>
<div><p>When a Pod starts and the probe fails, Kubernetes will try <em>failureThreshold</em> times before giving up.<br>
  Giving up in case of liveness probe means restarting the container.<br>
  In case of readiness probe the Pod will be marked Unready. Defaults to 3. Minimum value is 1.</p></div>

</li>
<li><code>periodSeconds : int</code>
<div><p>How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.</p></div>

</li>
<li><code>successThreshold : int</code>
<div>Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness. Minimum value is 1.</div>

</li>
</ul></li>
<li><code>ports</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code> (optional)
<div>The name of the port</div>

</li>
<li><code>containerPort : int</code> (optional)
<div>Port to expose into the pod</div>

</li>
<li><code>hostPort : int</code> (optional)
<div>Port to expose onto the host</div>

</li>
</ul></li>
<li><code>privileged : boolean</code> (optional)
<div>Flag to mark the container as privileged.</div>

</li>
<li><code>resourceLimitCpu : String</code> (optional)
<div>Kubernetes Resources Limit of CPU This value can be set to control the CPU resource limit passed when creating the Jenkins agent Docker container in Kubernetes. Unlike a resource request, this is the upper limit of resources used by your Jenkins Agent container. When left blank, the defaults of your Kubernetes cluster will be used. For more info, see the <a href="http://kubernetes.io/docs/user-guide/compute-resources/" rel="nofollow">Kubernetes docs.</a> e.g. `500m`.</div>

</li>
<li><code>resourceLimitEphemeralStorage : String</code> (optional)
</li>
<li><code>resourceLimitMemory : String</code> (optional)
<div>Kubernetes Resources Limit of Memory This value can be set to control the memory resource limit passed when creating the Jenkins agent Docker container in Kubernetes. Unlike a resource request, this is the upper limit of resources used by your Jenkins Agent container. When left blank, the defaults of your Kubernetes cluster will be used. For more info, see the <a href="http://kubernetes.io/docs/user-guide/compute-resources/" rel="nofollow">Kubernetes docs.</a> e.g. `250Mi`.</div>

</li>
<li><code>resourceRequestCpu : String</code> (optional)
<div>Kubernetes Resources Request of CPU This value can be set to control the CPU resources requested when creating the Jenkins agent Docker container in Kubernetes. When left blank, the defaults of your Kubernetes cluster will be used. For more info, see the <a href="http://kubernetes.io/docs/user-guide/compute-resources/" rel="nofollow">Kubernetes docs.</a> e.g. `500m`.</div>

</li>
<li><code>resourceRequestEphemeralStorage : String</code> (optional)
</li>
<li><code>resourceRequestMemory : String</code> (optional)
<div>Kubernetes Resources Request of Memory This value can be set to control the memory resources requested when creating the Jenkins agent Docker container in Kubernetes. When left blank, the defaults of your Kubernetes cluster will be used. For more info, see the <a href="http://kubernetes.io/docs/user-guide/compute-resources/" rel="nofollow">Kubernetes docs.</a> e.g. `250Mi`.</div>

</li>
<li><code>runAsGroup : String</code> (optional)
<div>Specify the gid to run as.</div>

</li>
<li><code>runAsUser : String</code> (optional)
<div>Specify the uid to run as.</div>

</li>
<li><code>shell : String</code> (optional)
</li>
<li><code>ttyEnabled : boolean</code> (optional)
<div>Whether this container should allocate a TTY for itself.</div>

</li>
<li><code>workingDir : String</code> (optional)
<div>Path to the root of the workspace from the view point of this container, such as <em>/home/jenkins/agent</em>.</div>

</li>
</ul></li>
<li><code>envVars</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>containerEnvVar</code><div>
<ul><li><code>key : String</code>
<div>The environment variable key.</div>

</li>
<li><code>value : String</code>
<div>The environment variable value.</div>

</li>
</ul></div></li>
<li><code>envVar</code><div>
<ul><li><code>key : String</code>
<div>The environment variable key.</div>

</li>
<li><code>value : String</code>
<div>The environment variable value.</div>

</li>
</ul></div></li>
<li><code>podEnvVar</code><div>
<ul><li><code>key : String</code>
<div>The environment variable key.</div>

</li>
<li><code>value : String</code>
<div>The environment variable value.</div>

</li>
</ul></div></li>
<li><code>secretEnvVar</code><div>
<ul><li><code>key : String</code>
<div>The environment variable key.</div>

</li>
<li><code>secretName : String</code>
<div>Name of secret to lookup from Kubernetes.</div>

</li>
<li><code>secretKey : String</code>
<div>Key of secret to lookup from Kubernetes.</div>

</li>
<li><code>optional : boolean</code>
<div>Whether this secret is optional.</div>

</li>
</ul></div></li>
</ul></li>
<li><code>hostNetwork : boolean</code> (optional)
</li>
<li><code>idleMinutes : int</code> (optional)
</li>
<li><code>imagePullSecrets : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>inheritFrom : String</code> (optional)
</li>
<li><code>inheritYamlMergeStrategy : boolean</code> (optional)
</li>
<li><code>instanceCap : int</code> (optional)
</li>
<li><code>label : String</code> (optional)
<div><div>
 Jenkins node label to bind. If left blank, one will be generated for you, and inside the step it will be bound to the variable <code>POD_LABEL</code> so you can use this as the argument to the <code>node</code> step.
 <br>
  Example: 
 <pre>        podTemplate(...) {
            node(POD_LABEL) {
                // some steps
            }
        }
    </pre>
</div></div>

</li>
<li><code>name : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>nodeSelector : String</code> (optional)
</li>
<li><code>nodeUsageMode : String</code> (optional)
</li>
<li><code>podRetention</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>always</code><div>
<ul></ul></div></li>
<li><code>default</code><div>
<ul></ul></div></li>
<li><code>never</code><div>
<ul></ul></div></li>
<li><code>onFailure</code><div>
<ul></ul></div></li>
</ul></li>
<li><code>runAsGroup : String</code> (optional)
</li>
<li><code>runAsUser : String</code> (optional)
</li>
<li><code>schedulerName : String</code> (optional)
</li>
<li><code>serviceAccount : String</code> (optional)
</li>
<li><code>showRawYaml : boolean</code> (optional)
</li>
<li><code>slaveConnectTimeout : int</code> (optional)
</li>
<li><code>supplementalGroups : String</code> (optional)
</li>
<li><code>volumes</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>configMapVolume</code><div>
<ul><li><code>mountPath : String</code>
<div>Path to mount this volume inside the pod.</div>

</li>
<li><code>configMapName : String</code>
<div>The name of the Kubernetes Config Map to mount into the pod.</div>

</li>
<li><code>optional : boolean</code>
<div>Whether this configmap needs to exist.</div>

</li>
<li><code>subPath : String</code> (optional)
<div>SubPath to mount this volume inside the pod.</div>

</li>
</ul></div></li>
<li><code>dynamicPVC</code><div>
<ul><li><code>accessModes : String</code> (optional)
<div>A PersistentVolume can be mounted on a host in any way supported by the resource provider. Providers will have different capabilities and each PV’s access modes are set to the specific modes supported by that particular volume. For example, NFS can support multiple read/write clients, but a specific NFS PV might be exported on the server as read-only. Each PV gets its own set of access modes describing that specific PV’s capabilities. Defaults to ReadWriteOnce.</div>

</li>
<li><code>mountPath : String</code> (optional)
<div>Path to mount this volume inside the pod.</div>

</li>
<li><code>requestsSize : String</code> (optional)
<div>Claims, like pods, can request specific quantities of a resource. In this case, the request is for storage. The same resource model applies to both volumes and claims. Defaults to 10Gi.</div>

</li>
<li><code>storageClassName : String</code> (optional)
<div>A StorageClass provides a way for administrators to describe the “classes” of storage they offer. Different classes might map to quality-of-service levels, or to backup policies, or to arbitrary policies determined by the cluster administrators. Kubernetes itself is unopinionated about what classes represent. This concept is sometimes called “profiles” in other storage systems.</div>

</li>
</ul></div></li>
<li><code>emptyDirVolume</code><div>
<ul><li><code>mountPath : String</code>
<div>Path to mount this volume inside the pod.</div>

</li>
<li><code>memory : boolean</code>
<div>Flag for in-memory volume.</div>

</li>
</ul></div></li>
<li><code>genericEphemeralVolume</code><div>
<ul><li><code>accessModes : String</code> (optional)
<div>A PersistentVolume can be mounted on a host in any way supported by the resource provider. Providers will have different capabilities and each PV’s access modes are set to the specific modes supported by that particular volume. For example, NFS can support multiple read/write clients, but a specific NFS PV might be exported on the server as read-only. Each PV gets its own set of access modes describing that specific PV’s capabilities. Defaults to ReadWriteOnce.</div>

</li>
<li><code>mountPath : String</code> (optional)
<div>Path to mount this volume inside the pod.</div>

</li>
<li><code>requestsSize : String</code> (optional)
<div>Claims, like pods, can request specific quantities of a resource. In this case, the request is for storage. The same resource model applies to both volumes and claims. Defaults to 10Gi.</div>

</li>
<li><code>storageClassName : String</code> (optional)
<div>A StorageClass provides a way for administrators to describe the “classes” of storage they offer. Different classes might map to quality-of-service levels, or to backup policies, or to arbitrary policies determined by the cluster administrators. Kubernetes itself is unopinionated about what classes represent. This concept is sometimes called “profiles” in other storage systems.</div>

</li>
</ul></div></li>
<li><code>hostPathVolume</code><div>
<ul><li><code>hostPath : String</code>
<div>File or directory on the host node's filesystem to mount into the pod.</div>

</li>
<li><code>mountPath : String</code>
<div>Path to mount this volume inside the pod.</div>

</li>
<li><code>readOnly : boolean</code>
<div>Flag for read-only mount, set hostPath mount to readOnly is considered best-practice.</div>

</li>
</ul></div></li>
<li><code>nfsVolume</code><div>
<ul><li><code>serverAddress : String</code>
<div>NFS Server Address.</div>

</li>
<li><code>serverPath : String</code>
<div>NFS Server Path.</div>

</li>
<li><code>readOnly : boolean</code>
</li>
<li><code>mountPath : String</code>
<div>Path to mount this volume inside the pod.</div>

</li>
</ul></div></li>
<li><code>persistentVolumeClaim</code><div>
<ul><li><code>mountPath : String</code>
<div>Path to mount this volume inside the pod.</div>

</li>
<li><code>claimName : String</code>
<div>The claim name.</div>

</li>
<li><code>readOnly : boolean</code>
<div>Flag for read-only volume.</div>

</li>
</ul></div></li>
<li><code>secretVolume</code><div>
<ul><li><code>mountPath : String</code>
<div>Path to mount this volume inside the pod.</div>

</li>
<li><code>secretName : String</code>
<div>The name of the Kubernetes Secret to mount into the pod.</div>

</li>
<li><code>defaultMode : String</code>
<div>The file permissions for the secret volume. Does not support Octal notation.</div>

</li>
<li><code>optional : boolean</code>
<div>Whether the secret needs to exist.</div>

</li>
</ul></div></li>
</ul></li>
<li><code>workingDir : String</code> (optional)
</li>
<li><code>workspaceVolume</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>dynamicPVC</code><div>
<ul><li><code>accessModes : String</code> (optional)
<div>A PersistentVolume can be mounted on a host in any way supported by the resource provider. Providers will have different capabilities and each PV’s access modes are set to the specific modes supported by that particular volume. For example, NFS can support multiple read/write clients, but a specific NFS PV might be exported on the server as read-only. Each PV gets its own set of access modes describing that specific PV’s capabilities. Defaults to ReadWriteOnce.</div>

</li>
<li><code>requestsSize : String</code> (optional)
<div>Claims, like pods, can request specific quantities of a resource. In this case, the request is for storage. The same resource model applies to both volumes and claims. Defaults to 10Gi.</div>

</li>
<li><code>storageClassName : String</code> (optional)
<div>A StorageClass provides a way for administrators to describe the “classes” of storage they offer. Different classes might map to quality-of-service levels, or to backup policies, or to arbitrary policies determined by the cluster administrators. Kubernetes itself is unopinionated about what classes represent. This concept is sometimes called “profiles” in other storage systems.</div>

</li>
</ul></div></li>
<li><code>emptyDirWorkspaceVolume</code><div>
<ul><li><code>memory : boolean</code>
<div>Flag for in-memory volume.</div>

</li>
</ul></div></li>
<li><code>genericEphemeralVolume</code><div>
<ul><li><code>accessModes : String</code> (optional)
<div>A PersistentVolume can be mounted on a host in any way supported by the resource provider. Providers will have different capabilities and each PV’s access modes are set to the specific modes supported by that particular volume. For example, NFS can support multiple read/write clients, but a specific NFS PV might be exported on the server as read-only. Each PV gets its own set of access modes describing that specific PV’s capabilities. Defaults to ReadWriteOnce.</div>

</li>
<li><code>requestsSize : String</code> (optional)
<div>Claims, like pods, can request specific quantities of a resource. In this case, the request is for storage. The same resource model applies to both volumes and claims. Defaults to 10Gi.</div>

</li>
<li><code>storageClassName : String</code> (optional)
<div>A StorageClass provides a way for administrators to describe the “classes” of storage they offer. Different classes might map to quality-of-service levels, or to backup policies, or to arbitrary policies determined by the cluster administrators. Kubernetes itself is unopinionated about what classes represent. This concept is sometimes called “profiles” in other storage systems.</div>

</li>
</ul></div></li>
<li><code>hostPathWorkspaceVolume</code><div>
<ul><li><code>hostPath : String</code>
<div>File or directory on the host node's filesystem to mount into the pod.</div>

</li>
</ul></div></li>
<li><code>nfsWorkspaceVolume</code><div>
<ul><li><code>serverAddress : String</code>
<div>NFS Server Address.</div>

</li>
<li><code>serverPath : String</code>
<div>NFS Server Path.</div>

</li>
<li><code>readOnly : boolean</code>
</li>
</ul></div></li>
<li><code>persistentVolumeClaimWorkspaceVolume</code><div>
<ul><li><code>claimName : String</code>
<div>The claim name.</div>

</li>
<li><code>readOnly : boolean</code>
<div>Flag for read-only volume.</div>

</li>
</ul></div></li>
</ul></li>
<li><code>yaml : String</code> (optional)
</li>
<li><code>yamlMergeStrategy</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>merge</code><div>
<ul></ul></div></li>
<li><code>override</code><div>
<ul></ul></div></li>
</ul></li>
</ul>


++++
=== `kubeconfig`: Setup Kubernetes CLI (kubectl)
++++
<div><div>
 Configure Kubernetes client (kubectl) so it can be used in the build to run Kubernetes commands
</div></div>
<ul><li><code>serverUrl : String</code>
<div><div>
 URL of the Kubernetes API endpoint. If not set the connection options will be autoconfigured from service account or kube config file.
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
<li><code>caCertificate : String</code>
<div><div>
 The base64 encoded certificate of the certificate authority (CA). It is used to verify the server certificate. 
 <p>Leaving this field empty will skip the certificate verification.</p>
</div></div>

</li>
</ul>


++++
=== `containerLog`: Get container log from Kubernetes
++++
<ul><li><code>name : String</code>
<div><div>
 Name of the container, as specified in <code>containerTemplate</code>.
</div></div>

</li>
<li><code>limitBytes : int</code> (optional)
<div><div>
 If set, the number of bytes to read from the server before terminating the log output. This may not display a complete final line of logging, and may return slightly more or slightly less than the specified limit.
</div></div>

</li>
<li><code>returnLog : boolean</code> (optional)
<div><div>
 Return the container log. If not checked, the log will be printed to the build log.
</div></div>

</li>
<li><code>sinceSeconds : int</code> (optional)
<div><div>
 A relative time in seconds before the current time from which to show logs. If this value precedes the time a pod was started, only logs since the pod start will be returned. If this value is in the future, no logs will be returned.
</div></div>

</li>
<li><code>tailingLines : int</code> (optional)
<div><div>
 If set, the number of lines from the end of the log to show. If not specified, log is shown from the creation of the container or limited by "sinceSeconds".
</div></div>

</li>
</ul>


++++
