= Kubernetes CLI Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/kubernetes-cli">Visit the Jenkins Plugins site</a>
++++


=== `withKubeConfig`: Configure Kubernetes CLI (kubectl)
++++
<div><div>
 Configure Kubernetes client (kubectl) so it can be used in the build to run Kubernetes commands
</div></div>
<ul><li><code>caCertificate : String</code> (optional)
<div><div>
 The certificate of the certificate authority (CA). It's used to validate the API server certificate. 
 <p>Leaving this field empty will skip the certificate verification.</p>
</div></div>

</li>
<li><code>clusterName : String</code> (optional)
<div><div>
 Cluster name to use or to switch to.
</div></div>

</li>
<li><code>contextName : String</code> (optional)
<div><div>
 Context name to use or to switch to.
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 Default namespace.
</div></div>

</li>
<li><code>restrictKubeConfigAccess : boolean</code> (optional)
<div><div>
 Restrict access to kubeconfig file to the Jenkins Agent's user.
</div></div>

</li>
<li><code>serverUrl : String</code> (optional)
<div><div>
 URL of the Kubernetes API endpoint.
</div></div>

</li>
</ul>


++++
=== `withKubeCredentials`: Configure Kubernetes CLI (kubectl) with multiple credentials
++++
<ul><li><code>kubectlCredentials</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>caCertificate : String</code> (optional)
</li>
<li><code>clusterName : String</code> (optional)
</li>
<li><code>contextName : String</code> (optional)
</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>serverUrl : String</code> (optional)
</li>
</ul></li>
</ul>


++++
=== `wrap([$class: 'MultiKubectlBuildWrapper'])`: Configure Kubernetes CLI (kubectl) with multiple credentials
++++
<ul><li><code>kubectlCredentials</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>caCertificate : String</code> (optional)
</li>
<li><code>clusterName : String</code> (optional)
</li>
<li><code>contextName : String</code> (optional)
</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>serverUrl : String</code> (optional)
</li>
</ul></li>
<li><code>restrictKubeConfigAccess : boolean</code> (optional)
</li>
</ul>


++++
=== `wrap([$class: 'KubectlBuildWrapper'])`: Configure Kubernetes CLI (kubectl) (deprecated, use the multi credentials one instead)
++++
<div><div>
 Configure Kubernetes client (kubectl) so it can be used in the build to run Kubernetes commands
</div></div>
<ul><li><code>caCertificate : String</code> (optional)
<div><div>
 The certificate of the certificate authority (CA). It's used to validate the API server certificate. 
 <p>Leaving this field empty will skip the certificate verification.</p>
</div></div>

</li>
<li><code>clusterName : String</code> (optional)
<div><div>
 Cluster name to use or to switch to.
</div></div>

</li>
<li><code>contextName : String</code> (optional)
<div><div>
 Context name to use or to switch to.
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 Default namespace.
</div></div>

</li>
<li><code>restrictKubeConfigAccess : boolean</code> (optional)
<div><div>
 Restrict access to kubeconfig file to the Jenkins Agent's user.
</div></div>

</li>
<li><code>serverUrl : String</code> (optional)
<div><div>
 URL of the Kubernetes API endpoint.
</div></div>

</li>
</ul>


++++
