= Labelled Pipeline Steps Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/labelled-steps">Visit the Jenkins Plugins site</a>
++++


=== `labelledShell`: Shell Script
++++
<ul><li><code>script : String</code>
</li>
<li><code>encoding : String</code> (optional)
<div><div>
 Encoding of process output. In the case of <code>returnStdout</code>, applies to the return value of this step; otherwise, or always for standard error, controls how text is copied to the build log. If unspecified, uses the system default encoding of the node on which the step is run. If there is any expectation that process output might include non-ASCII characters, it is best to specify the encoding explicitly. For example, if you have specific knowledge that a given process is going to be producing UTF-8 yet will be running on a node with a different system encoding (typically Windows, since every Linux distribution has defaulted to UTF-8 for a long time), you can ensure correct output by specifying: <code>encoding: 'UTF-8'</code>
</div></div>

</li>
<li><code>label : String</code> (optional)
<div><div>
 Label to be displayed in the pipeline step view and blue ocean details for the step instead of the step type. So the view is more meaningful and domain specific instead of technical.
</div></div>

</li>
<li><code>returnStatus : boolean</code> (optional)
<div><div>
 Normally, a script which exits with a nonzero status code will cause the step to fail with an exception. If this option is checked, the return value of the step will instead be the status code. You may then compare it to zero, for example.
</div></div>

</li>
<li><code>returnStdout : boolean</code> (optional)
<div><div>
 If checked, standard output from the task is returned as the step value as a <code>String</code>, rather than being printed to the build log. (Standard error, if any, will still be printed to the log.) You will often want to call <code>.trim()</code> on the result to strip off a trailing newline.
</div></div>

</li>
</ul>


++++
