= Lacework Security Scanner
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/lacework-security-scanner">Visit the Jenkins Plugins site</a>
++++


=== `lacework`: Lacework Security
++++
<ul><li><code>customFlags : String</code>
<div><div>
 <p>Specify any desired command-line flags to be passed to the Lacework scanner.</p>
</div></div>

</li>
<li><code>fixableOnly : boolean</code>
<div><div>
 <p>Whether the build step should only return information for fixable vulnerabilities.</p>
</div></div>

</li>
<li><code>imageName : String</code>
</li>
<li><code>imageTag : String</code>
</li>
<li><code>noPull : boolean</code>
<div><div>
 <p>Whether the build step should attempt to pull container images that don't exist locally.</p>
</div></div>

</li>
<li><code>evaluatePolicies : boolean</code>
<div><div>
 <p>Whether the build step should evaluate against policies which are assigned in the Lacework platform.</p>
</div></div>

</li>
<li><code>saveToLacework : boolean</code>
<div><div>
 <p>Whether the build step should save assessment results to the Lacework platform.</p>
</div></div>

</li>
<li><code>disableLibraryPackageScanning : boolean</code>
<div><div>
 <p>Whether the build step should disable scanning of programming language libraries.</p>
</div></div>

</li>
<li><code>showEvaluationExceptions : boolean</code>
<div><div>
 <p>Whether the build step should display evaluation exceptions.</p>
</div></div>

</li>
<li><code>tags : String</code>
<div><div>
 <p>Specify any desired tags, in JSON key/value format, to be assigned to the Lacework scanner assessment.</p>
</div></div>

</li>
</ul>


++++
