= AWS Lambda Test Runner
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/lambda-test-runner">Visit the Jenkins Plugins site</a>
++++


=== `lambdaTestRunner`: Trigger execution of AWS Lambda Test Runner
++++
<ul><li><code>functionName : String</code>
<div><div>
 <p><a href="https://github.com/automatictester/lambda-test-runner" rel="nofollow">AWS Lambda Test Runner</a> function to execute.</p>
</div></div>

</li>
<li><code>region : String</code>
<div><div>
 <p>AWS region where your Lambda function is deployed. Example: <b>eu-west-1</b></p>
</div></div>

</li>
<li><code>s3Bucket : String</code>
<div><div>
 <p>AWS S3 bucket containing build outputs.</p>
</div></div>

</li>
<li><code>repoUri : String</code>
<div><div>
 <p>HTTPS or SSH Git repository URL. Examples:</p>
 <p><b>https://github.com/username/repo.git</b><br><b>git@github.com:username/repo.git</b></p>
</div></div>

</li>
<li><code>command : String</code>
<div><div>
 <p>Command to run the tests. Examples:</p>
 <p><b>./mvnw test -Dmaven.repo.local=${MAVEN_USER_HOME}</b><br><b>./sbt -Dsbt.global.base=${SBT_GLOBAL_BASE} -Dsbt.ivy.home=${SBT_IVY_HOME} test</b></p>
</div></div>

</li>
<li><code>branch : String</code> (optional)
<div><div>
 <p>Git branch to checkout. Example: <b>develop</b></p>
 <p>If not specified, <b>HEAD</b> will be used, which points to the default branch configured in your Git repo.</p>
</div></div>

</li>
<li><code>storeToS3 : String</code> (optional)
<div><div>
 <p>Comma-separated list of directories to store to S3. Examples:</p>
 <p><b>target/surefire-reports</b><br><b>target/surefire-reports,target/failsafe-reports</b></p>
</div></div>

</li>
</ul>


++++
