= Liquibase Runner
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/liquibase-runner">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'DropAllBuilder'])`: Liquibase: Drop everything in database
++++
<ul><li><code>changeLogFile : String</code> (optional)
</li>
<li><code>changeLogParameters : String</code> (optional)
</li>
<li><code>contexts : String</code> (optional)
<div><div>
 Liquibase contexts to execute under.
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>installationName : String</code> (optional)
</li>
<li><code>labels : String</code> (optional)
<div><div>
 Liquibase labels to execute
</div></div>

</li>
<li><code>liquibasePropertiesPath : String</code> (optional)
<div><div>
 A liquibase.properties file can be used for default values. Any of the below settings will override what is in this file. This file should be relative to a directory listed in the "Resource directories" section.
</div></div>

</li>
<li><code>password : String</code> (optional)
</li>
<li><code>resourceDirectories : String</code> (optional)
<div><div>
 Leave blank for workspace root. May be relative to workspace or an absolute path.
</div></div>

</li>
<li><code>url : String</code> (optional)
<div>example: jdbc:mysql://localhost:3306/sampledb. The JDBC driver must be available in the "lib" directory of your Liquibase installation</div>

</li>
<li><code>username : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'RawCliBuilder'])`: Liquibase: CLI Command
++++
<ul><li><code>changeLogFile : String</code> (optional)
</li>
<li><code>changeLogParameters : String</code> (optional)
</li>
<li><code>commandArguments : String</code> (optional)
</li>
<li><code>contexts : String</code> (optional)
<div><div>
 Liquibase contexts to execute under.
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>installationName : String</code> (optional)
</li>
<li><code>labels : String</code> (optional)
<div><div>
 Liquibase labels to execute
</div></div>

</li>
<li><code>liquibasePropertiesPath : String</code> (optional)
<div><div>
 A liquibase.properties file can be used for default values. Any of the below settings will override what is in this file. This file should be relative to a directory listed in the "Resource directories" section.
</div></div>

</li>
<li><code>password : String</code> (optional)
</li>
<li><code>resourceDirectories : String</code> (optional)
<div><div>
 Leave blank for workspace root. May be relative to workspace or an absolute path.
</div></div>

</li>
<li><code>url : String</code> (optional)
<div>example: jdbc:mysql://localhost:3306/sampledb. The JDBC driver must be available in the "lib" directory of your Liquibase installation</div>

</li>
<li><code>username : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'RollbackBuilder'])`: Liquibase: Roll Back Changes
++++
<ul><li><code>changeLogFile : String</code> (optional)
</li>
<li><code>changeLogParameters : String</code> (optional)
</li>
<li><code>contexts : String</code> (optional)
<div><div>
 Liquibase contexts to execute under.
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>installationName : String</code> (optional)
</li>
<li><code>labels : String</code> (optional)
<div><div>
 Liquibase labels to execute
</div></div>

</li>
<li><code>liquibasePropertiesPath : String</code> (optional)
<div><div>
 A liquibase.properties file can be used for default values. Any of the below settings will override what is in this file. This file should be relative to a directory listed in the "Resource directories" section.
</div></div>

</li>
<li><code>numberOfChangesetsToRollback : String</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>resourceDirectories : String</code> (optional)
<div><div>
 Leave blank for workspace root. May be relative to workspace or an absolute path.
</div></div>

</li>
<li><code>rollbackLastHours : String</code> (optional)
</li>
<li><code>rollbackToDate : String</code> (optional)
</li>
<li><code>rollbackToTag : String</code> (optional)
</li>
<li><code>rollbackType : String</code> (optional)
</li>
<li><code>url : String</code> (optional)
<div>example: jdbc:mysql://localhost:3306/sampledb. The JDBC driver must be available in the "lib" directory of your Liquibase installation</div>

</li>
<li><code>username : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'TagBuilder'])`: Liquibase: Tag Database
++++
<ul><li><code>changeLogFile : String</code> (optional)
</li>
<li><code>changeLogParameters : String</code> (optional)
</li>
<li><code>contexts : String</code> (optional)
<div><div>
 Liquibase contexts to execute under.
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>installationName : String</code> (optional)
</li>
<li><code>labels : String</code> (optional)
<div><div>
 Liquibase labels to execute
</div></div>

</li>
<li><code>liquibasePropertiesPath : String</code> (optional)
<div><div>
 A liquibase.properties file can be used for default values. Any of the below settings will override what is in this file. This file should be relative to a directory listed in the "Resource directories" section.
</div></div>

</li>
<li><code>password : String</code> (optional)
</li>
<li><code>resourceDirectories : String</code> (optional)
<div><div>
 Leave blank for workspace root. May be relative to workspace or an absolute path.
</div></div>

</li>
<li><code>tag : String</code> (optional)
<div>The tag to apply to the database. If the tag already exists, it will be moved the current datatabase state. 
<br>
<br>
 If left empty, an auto-generated tag based on the build number will be applied</div>

</li>
<li><code>url : String</code> (optional)
<div>example: jdbc:mysql://localhost:3306/sampledb. The JDBC driver must be available in the "lib" directory of your Liquibase installation</div>

</li>
<li><code>username : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'UpdateBuilder'])`: Liquibase: Update Database
++++
<ul><li><code>changeLogFile : String</code> (optional)
</li>
<li><code>changeLogParameters : String</code> (optional)
</li>
<li><code>contexts : String</code> (optional)
<div><div>
 Liquibase contexts to execute under.
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>installationName : String</code> (optional)
</li>
<li><code>labels : String</code> (optional)
<div><div>
 Liquibase labels to execute
</div></div>

</li>
<li><code>liquibasePropertiesPath : String</code> (optional)
<div><div>
 A liquibase.properties file can be used for default values. Any of the below settings will override what is in this file. This file should be relative to a directory listed in the "Resource directories" section.
</div></div>

</li>
<li><code>password : String</code> (optional)
</li>
<li><code>resourceDirectories : String</code> (optional)
<div><div>
 Leave blank for workspace root. May be relative to workspace or an absolute path.
</div></div>

</li>
<li><code>url : String</code> (optional)
<div>example: jdbc:mysql://localhost:3306/sampledb. The JDBC driver must be available in the "lib" directory of your Liquibase installation</div>

</li>
<li><code>username : String</code> (optional)
</li>
</ul>


++++
