= Lockable Resources plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/lockable-resources">Visit the Jenkins Plugins site</a>
++++


=== `lock`: Lock shared resource
++++
<ul><li><code>resource : String</code>
<div><div>
 <p>The resource name to lock as defined in Global settings.</p>
 <p>If the resource does not exist in Global Settings it will be automatically created on build execution. Either a resource or a label need to be specified.</p>
</div></div>

</li>
<li><code>extra</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>resource : String</code>
<div><div>
 <p>The resource name to lock as defined in Global settings.</p>
 <p>If the resource does not exist in Global Settings it will be automatically created on build execution. Either a resource or a label need to be specified.</p>
</div></div>

</li>
<li><code>label : String</code> (optional)
<div><div>
 <p>The label of the resources to be locked as defined in Global settings.</p>
 <p>Either a resource or a label need to be specified.</p>
 <p>See also <a href="https://github.com/jenkinsci/lockable-resources-plugin#multiple-resource-lock" rel="nofollow">examples</a> and <a href="https://github.com/jenkinsci/lockable-resources-plugin/blob/master/src/doc/examples/scripted-vs-declarative-pipeline.md" rel="nofollow">Scripted vs declarative pipeline</a> .</p>
</div></div>

</li>
<li><code>quantity : int</code> (optional)
<div><div>
 <p>The quantity of resources with the specified label to be locked as defined in Global settings.</p>
 <p>Either a resource or a label need to be specified. Empty value or 0 means lock all matching resources.</p>
</div></div>

</li>
</ul></li>
<li><code>inversePrecedence : boolean</code> (optional)
<div><div>
 <p>By default waiting builds get the lock in the same order they requested to acquire it.</p>
 <p>By checking this option the newest build in the waiting queue will get the lock first.</p>
 <p>See also <a href="https://github.com/jenkinsci/lockable-resources-plugin#take-first-position-in-queue" rel="nofollow">examples</a> .</p>
</div></div>

</li>
<li><code>label : String</code> (optional)
<div><div>
 <p>The label of the resources to be locked as defined in Global settings.</p>
 <p>Either a resource or a label need to be specified.</p>
 <p>See also <a href="https://github.com/jenkinsci/lockable-resources-plugin#multiple-resource-lock" rel="nofollow">examples</a> and <a href="https://github.com/jenkinsci/lockable-resources-plugin/blob/master/src/doc/examples/scripted-vs-declarative-pipeline.md" rel="nofollow">Scripted vs declarative pipeline</a> .</p>
</div></div>

</li>
<li><code>priority : int</code> (optional)
<div><div>
 <p>The priority of the lock,</p>
 <p>which takes an integer number that defines the order in which concurrent jobs waiting for the same resource are served. The job with the highest number would get the resource first. If the priority is equal, the current precedence (first comes first) would be applied.</p>
 <p>See also <a href="https://github.com/jenkinsci/lockable-resources-plugin#lock-(queue)-priority" rel="nofollow">examples</a> .</p>
</div></div>

</li>
<li><code>quantity : int</code> (optional)
<div><div>
 <p>The quantity of resources with the specified label to be locked as defined in Global settings.</p>
 <p>Either a resource or a label need to be specified. Empty value or 0 means lock all matching resources.</p>
</div></div>

</li>
<li><code>resourceSelectStrategy : String</code> (optional)
<div><div>
 <p>The strategy used to chose which available resources get locked. By default, the strategy will be "sequential" and resources are locked following the order in the lockable resources list. Set the strategy to "random" to randomize the order in which resources are locked.</p>
</div></div>

</li>
<li><code>skipIfLocked : boolean</code> (optional)
<div><div>
 <p>By default waiting builds get the lock.</p>
 <p>By checking this option the body will not be executed if there is a queue. It will only take the lock if it can be taken immediately.</p>
 <p>See also <a href="https://github.com/jenkinsci/lockable-resources-plugin#skip-executing-the-block-if-there-is-a-queue" rel="nofollow">examples</a> .</p>
</div></div>

</li>
<li><code>variable : String</code> (optional)
<div><div>
 <p>Name of an environment variable that will receive the comma separated list of the names of the locked resources while the block executes.</p>
 <p>See also <a href="https://github.com/jenkinsci/lockable-resources-plugin#resolve-a-variable-configured-with-the-resource-name" rel="nofollow">examples</a> and <a href="https://github.com/jenkinsci/lockable-resources-plugin/blob/master/src/doc/examples/scripted-vs-declarative-pipeline.md" rel="nofollow">Scripted vs declarative pipeline</a> .</p>
</div></div>

</li>
</ul>


++++
