= Mailer Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/mailer">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'Mailer'])`: E-mail Notification
++++
<div><div>
 If configured, Jenkins will send out an e-mail to the specified recipients when a certain important event occurs. 
 <ol>
  <li>Every failed build triggers a new e-mail.</li>
  <li>A successful build after a failed (or unstable) build triggers a new e-mail, indicating that a crisis is over.</li>
  <li>An unstable build after a successful build triggers a new e-mail, indicating that there's a regression.</li>
  <li>Unless configured, every unstable build triggers a new e-mail, indicating that regression is still there.</li>
 </ol> For lazy projects where unstable builds are the norm, Uncheck "Send e-mail for every unstable build".
</div></div>
<ul><li><code>recipients : String</code>
</li>
<li><code>notifyEveryUnstableBuild : boolean</code>
</li>
<li><code>sendToIndividuals : boolean</code>
<div><div>
 If this option is checked, the notification e-mail will be sent to individuals who have committed changes for the broken build (by assuming that those changes broke the build). 
 <p>If e-mail addresses are also specified in the recipient list, then both the individuals as well as the specified addresses get the notification e-mail. If the recipient list is empty, then only the individuals will receive e-mails.</p>
</div></div>

</li>
</ul>


++++
