= Mask Passwords Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/mask-passwords">Visit the Jenkins Plugins site</a>
++++


=== `maskPasswords`: Mask passwords and regexes (and enable global passwords)
++++
<div><div>
 <p>When enabled, allows masking passwords that may appear in the console.</p>
 <p>Passwords or regexes to be masked can be defined at three levels.</p>
 <p>First, it is possible to select in Jenkins configuration screen the build parameters whose value must be masked. For example, selecting the <b>Password Parameter</b> type is a good idea.</p>
 <p>Second, still in Jenkins' configuration screen, it is possible to define passwords to be masked as global <b>Name</b>/<b>Password</b> pairs, or regexes to be masked.</p>
 <p>Third, on a per job basis (that is, in the current configuration screen), passwords to be masked can be defined as local <b>Name</b>/<b>Password</b> pairs, or regexes can be masked:</p>
 <ul>
  <li><b>Password</b> is aimed at containing a password to be masked from the console. Empty and blank values are not allowed (e.g. "&nbsp;", etc.). This field is ciphered. This field can not contain variables, they won't be expanded.</li>
  <li>If <b>Name</b> is set, then a build variable will be defined accordingly. This allows accessing the password by using the variable rather than hard-coding it in a field which is not ciphered (e.g. the ones of the <b>Invoke Ant</b> or <b>Execute shell</b> build steps).</li>
  <li>If <b>Regex</b> is set, then any text matching that regex will be masked in the console output. The regex should not contain start- or end-of-string markers and will be internally and-ed (piped) together with all other regexes and regexes matching the specified names and passwords.</li>
 </ul>
</div></div>
<ul><li><code>varPasswordPairs</code>
<ul><b>Array / List of Nested Object</b>
<li><code>var : String</code>
</li>
<li><code>password</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
</ul></li>
<li><code>varMaskRegexes</code>
<ul><b>Array / List of Nested Object</b>
<li><code>key : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
</ul>


++++
