= MATLAB Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/matlab">Visit the Jenkins Plugins site</a>
++++


=== `runMATLABBuild`: Run a MATLAB build using the MATLAB build tool
++++
<ul><li><code>buildOptions : String</code> (optional)
<div><div>
 Specify a space-separated list of MATLAB build options. The plugin supports the build options that you can pass to the <b>buildtool</b> command.
 <br><b>Example: </b>-continueOnFailure
 <br><b>Example: </b>-continueOnFailure -skip test
</div></div>

</li>
<li><code>startupOptions : String</code> (optional)
<div><div>
 Specify a space-separated list of MATLAB startup options.
 <br><b>Example: </b>-nojvm
 <br><b>Example: </b>-nojvm -logfile output.log 
 <br>
 &nbsp;
 <br><b>Note: </b>Specifying the <b>-batch</b> or <b>-r</b> option is not supported.
</div></div>

</li>
<li><code>tasks : String</code> (optional)
<div><div>
 Insert a space-separated list of tasks to run in the <b>Tasks</b> box. If not specified, the action runs the default tasks in buildfile.m as well as all the tasks on which they depend.
 <br><b>Example: </b>test
 <br><b>Example: </b>compile test 
 <br>
 &nbsp;
 <br><b>Note:</b>
 <ul>
  <li>MATLAB exits with exit code 0 if the tasks run without error. Otherwise, MATLAB terminates with a nonzero exit code, which causes the step to fail.</li>
  <li>To use the Run MATLAB Build step, you need MATLAB R2022b or a later release.</li>
 </ul>
</div></div>

</li>
</ul>


++++
=== `runMATLABCommand`: Run MATLAB commands, scripts, or functions
++++
<ul><li><code>command : String</code>
<div><div>
 Insert the MATLAB commands you want to execute in the <b>Command</b> box. If you need to specify more than one command, use a comma or semicolon to separate the commands.
 <br><b>Example: </b>results = runtests, assertSuccess(results);
 <br>
 <br>
  If you need to specify several MATLAB commands, consider writing a MATLAB script or function and executing this script or function instead. (To run a script or function, do not specify the file extension.)
 <br><b>Example: </b>myscript
 <br>
 <br>
 &nbsp;
 <br><b>Note:</b>
 <ul>
  <li>The build fails if the execution of any command results in an error.</li>
  <li>If the build uses a MATLAB version prior to R2020a, MATLAB might display non-ASCII characters, specified in the <b>Command</b> box, as garbled text. If you specify non-ASCII characters in your commands, consider running your commands as a .m or .mlx file created in the same locale that MATLAB uses on the build agent</li>
 </ul>
</div></div>

</li>
<li><code>startupOptions : String</code> (optional)
<div><div>
 A space-separated list of MATLAB startup options.
</div></div>

</li>
</ul>


++++
=== `runMATLABTests`: Run MATLAB tests and generate artifacts
++++
<ul><li><code>codeCoverageCobertura : String</code> (optional)
<div><div>
 <br>
  Generate a code coverage report in Cobertura XML format. By default, MATLAB names the artifact <b>cobertura.xml</b> and stores it in the <b>matlabTestArtifacts</b> folder of the project workspace. To override the default artifact name and location, specify a path relative to the project folder in the <b>File path</b> box. If the text box is empty, MATLAB does not generate an artifact. 
 <br>
</div></div>

</li>
<li><code>loggingLevel : String</code> (optional)
<div><div>
 <p>Maximum verbosity level for logged diagnostics included for the test run.</p>
</div></div>

</li>
<li><code>modelCoverageCobertura : String</code> (optional)
<div><div>
 <br>
  Generate a model coverage report in Cobertura XML format. This artifact includes coverage results for Simulink® models that are tested using Simulink Test™. By default, MATLAB names the artifact <b>coberturamodelcoverage.xml</b> and stores it in the <b>matlabTestArtifacts</b> folder of the project workspace. 
 <br>
 <br><b>Note:</b> This feature requires a <b>Simulink Coverage™</b> license and is supported only in MATLAB R2018b or a newer release.
 <br>
 <br>
</div></div>

</li>
<li><code>outputDetail : String</code> (optional)
<div><div>
 <p>Display level for event details output by the test run.</p>
</div></div>

</li>
<li><code>selectByFolder : Array / List of String</code> (optional)
<div><div>
 <p>Specify the locations of folders containing tests, relative to the project root folder, as a list of strings. To generate a test suite, MATLAB uses only the tests in the specified folders and their subfolders.</p>
 <p><b>Example:</b> ["test/folderA", "test/folderB"]</p>
</div></div>

<ul></ul></li>
<li><code>selectByTag : String</code> (optional)
<div><div>
 <p>Specify the test tag used to select test suite elements. To generate a test suite, MATLAB uses only the test elements with the specified tag.</p>
 <p><b>Example:</b> 'FeatureA'</p>
</div></div>

</li>
<li><code>sourceFolder : Array / List of String</code> (optional)
<div><div>
 <p>Specify the location of folders containing source code, relative to the project root folder, as a string array. The specified folders and their subfolders are added to the top of the MATLAB search path. To generate a coverage report, MATLAB uses only the source code in the specified folders and their subfolders.</p>
 <p><b>Example:</b> ["src/folderA", "src/folderB"]</p>
</div></div>

<ul></ul></li>
<li><code>startupOptions : String</code> (optional)
<div><div>
 A space-separated list of MATLAB startup options.
</div></div>

</li>
<li><code>strict : boolean</code> (optional)
<div><div>
 <p>Whether to apply strict checks when running the tests. For example, the framework generates a qualification failure if a test issues a warning.</p>
</div></div>

</li>
<li><code>testResultsJUnit : String</code> (optional)
<div><div>
 <br>
  Generate a test report in JUnit XML format. By default, MATLAB names the artifact <b>junittestresults.xml</b> and stores it in the <b>matlabTestArtifacts</b> folder of the project workspace. To override the default artifact name and location, specify a path relative to the project folder in the <b>File path</b> box. If the text box is empty, MATLAB does not generate an artifact. 
 <br>
</div></div>

</li>
<li><code>testResultsPDF : String</code> (optional)
<div><div>
 <br>
  Generate a test report in PDF format. By default, MATLAB names the artifact <b>testreport.pdf</b> and stores it in the <b>matlabTestArtifacts</b> folder of the project workspace. To override the default artifact name and location, specify a path relative to the project folder in the <b>File path</b> box. If the text box is empty, MATLAB does not generate an artifact. 
 <br>
 <br>
  Due to Jenkins Content Security Policy rules, the generated report might not open properly from within the Jenkins workspace. Consider copying the report to a location outside the workspace and opening it from there. For more information, see <a href="http://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy" rel="nofollow">Configuring Jenkins Content Security Policy</a>. 
 <br>
 <br><b>Note:</b> On macOS platforms, this feature is supported in MATLAB R2020b and later.
</div></div>

</li>
<li><code>testResultsSimulinkTest : String</code> (optional)
<div><div>
 <br>
 Export Simulink Test™ Manager results in MLDATX format. By default, MATLAB names the artifact <b>simulinktestresults.mldatx</b> and stores it in the <b>matlabTestArtifacts</b> folder of the project workspace. To override the default artifact name and location, specify a path relative to the project folder in the <b>File path</b> box. If the text box is empty, MATLAB does not generate an artifact. 
 <br>
 <br><b>Note:</b> This feature requires a <b>Simulink Test</b> license and is supported only in MATLAB R2019a or a newer release.
</div></div>

</li>
<li><code>testResultsTAP : String</code> (optional)
<div><div>
 <br>
  Generate a test report in TAP format. By default, MATLAB names the artifact <b>taptestresults.tap</b> and stores it in the <b>matlabTestArtifacts</b> folder of the project workspace. To override the default artifact name and location, specify a path relative to the project folder in the <b>File path</b> box. If the text box is empty, MATLAB does not generate an artifact. 
 <br>
</div></div>

</li>
<li><code>useParallel : boolean</code> (optional)
<div><div>
 <p>Whether to run tests in parallel. This feature requires a Parallel Computing Toolbox license, and might not be compatible with other options. If incompatible, testing occurs in serial regardless of the value of this feature.</p>
</div></div>

</li>
</ul>


++++
=== `step([$class: 'RunMatlabBuildBuilder'])`: Run MATLAB Build
++++
<ul><li><code>buildOptions</code> (optional)
<div><div>
 Specify a space-separated list of MATLAB build options. The plugin supports the build options that you can pass to the <b>buildtool</b> command.
 <br><b>Example: </b>-continueOnFailure
 <br><b>Example: </b>-continueOnFailure -skip test
</div></div>

<ul><b>Nested Object</b>
<li><code>options : String</code>
</li>
</ul></li>
<li><code>startupOptions</code> (optional)
<div><div>
 Specify a space-separated list of MATLAB startup options.
 <br><b>Example: </b>-nojvm
 <br><b>Example: </b>-nojvm -logfile output.log 
 <br>
 &nbsp;
 <br><b>Note: </b>Specifying the <b>-batch</b> or <b>-r</b> option is not supported.
</div></div>

<ul><b>Nested Object</b>
<li><code>options : String</code>
</li>
</ul></li>
<li><code>tasks : String</code> (optional)
<div><div>
 Insert a space-separated list of tasks to run in the <b>Tasks</b> box. If not specified, the action runs the default tasks in buildfile.m as well as all the tasks on which they depend.
 <br><b>Example: </b>test
 <br><b>Example: </b>compile test 
 <br>
 &nbsp;
 <br><b>Note:</b>
 <ul>
  <li>MATLAB exits with exit code 0 if the tasks run without error. Otherwise, MATLAB terminates with a nonzero exit code, which causes the step to fail.</li>
  <li>To use the Run MATLAB Build step, you need MATLAB R2022b or a later release.</li>
 </ul>
</div></div>

</li>
</ul>


++++
=== `step([$class: 'RunMatlabCommandBuilder'])`: Run MATLAB Command
++++
<ul><li><code>matlabCommand : String</code> (optional)
<div><div>
 Insert the MATLAB commands you want to execute in the <b>Command</b> box. If you need to specify more than one command, use a comma or semicolon to separate the commands.
 <br><b>Example: </b>results = runtests, assertSuccess(results);
 <br>
 <br>
  If you need to specify several MATLAB commands, consider writing a MATLAB script or function and executing this script or function instead. (To run a script or function, do not specify the file extension.)
 <br><b>Example: </b>myscript
 <br>
 <br>
 &nbsp;
 <br><b>Note:</b>
 <ul>
  <li>The build fails if the execution of any command results in an error.</li>
  <li>If the build uses a MATLAB version prior to R2020a, MATLAB might display non-ASCII characters, specified in the <b>Command</b> box, as garbled text. If you specify non-ASCII characters in your commands, consider running your commands as a .m or .mlx file created in the same locale that MATLAB uses on the build agent</li>
 </ul>
</div></div>

</li>
<li><code>startupOptions</code> (optional)
<div><div>
 A space-separated list of MATLAB startup options.
</div></div>

<ul><b>Nested Object</b>
<li><code>options : String</code>
</li>
</ul></li>
</ul>


++++
=== `step([$class: 'RunMatlabTestsBuilder'])`: Run MATLAB Tests
++++
<ul><li><code>coberturaArtifact</code> (optional)
<div><div>
 <br>
  Generate a code coverage report in Cobertura XML format. By default, MATLAB names the artifact <b>cobertura.xml</b> and stores it in the <b>matlabTestArtifacts</b> folder of the project workspace. To override the default artifact name and location, specify a path relative to the project folder in the <b>File path</b> box. If the text box is empty, MATLAB does not generate an artifact. 
 <br>
</div></div>

<ul><b>Nested Object</b>
<li><code>coberturaReportFilePath : String</code>
</li>
</ul></li>
<li><code>junitArtifact</code> (optional)
<div><div>
 <br>
  Generate a test report in JUnit XML format. By default, MATLAB names the artifact <b>junittestresults.xml</b> and stores it in the <b>matlabTestArtifacts</b> folder of the project workspace. To override the default artifact name and location, specify a path relative to the project folder in the <b>File path</b> box. If the text box is empty, MATLAB does not generate an artifact. 
 <br>
</div></div>

<ul><b>Nested Object</b>
<li><code>junitReportFilePath : String</code>
</li>
</ul></li>
<li><code>loggingLevel : String</code> (optional)
<div><div>
 <p>Maximum verbosity level for logged diagnostics included for the test run.</p>
</div></div>

</li>
<li><code>modelCoverageArtifact</code> (optional)
<div><div>
 <br>
  Generate a model coverage report in Cobertura XML format. This artifact includes coverage results for Simulink® models that are tested using Simulink Test™. By default, MATLAB names the artifact <b>coberturamodelcoverage.xml</b> and stores it in the <b>matlabTestArtifacts</b> folder of the project workspace. 
 <br>
 <br><b>Note:</b> This feature requires a <b>Simulink Coverage™</b> license and is supported only in MATLAB R2018b or a newer release.
 <br>
 <br>
</div></div>

<ul><b>Nested Object</b>
<li><code>modelCoverageFilePath : String</code>
</li>
</ul></li>
<li><code>outputDetail : String</code> (optional)
<div><div>
 <p>Display level for event details output by the test run.</p>
</div></div>

</li>
<li><code>pdfReportArtifact</code> (optional)
<div><div>
 <br>
  Generate a test report in PDF format. By default, MATLAB names the artifact <b>testreport.pdf</b> and stores it in the <b>matlabTestArtifacts</b> folder of the project workspace. To override the default artifact name and location, specify a path relative to the project folder in the <b>File path</b> box. If the text box is empty, MATLAB does not generate an artifact. 
 <br>
 <br>
  Due to Jenkins Content Security Policy rules, the generated report might not open properly from within the Jenkins workspace. Consider copying the report to a location outside the workspace and opening it from there. For more information, see <a href="http://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy" rel="nofollow">Configuring Jenkins Content Security Policy</a>. 
 <br>
 <br><b>Note:</b> On macOS platforms, this feature is supported in MATLAB R2020b and later.
</div></div>

<ul><b>Nested Object</b>
<li><code>pdfReportFilePath : String</code>
</li>
</ul></li>
<li><code>selectByFolder</code> (optional)
<div><div>
 <br>
  Specify the location of folders used to select test suite elements, relative to the project root folder. To generate a test suite, the plugin uses only the tests in the specified folders and their subfolders. 
 <br>
  Paste the test folder path in the text box. To add more folders, click <b>Add folder.</b>
 <br>
</div></div>

<ul><b>Nested Object</b>
<li><code>testFolderPaths</code>
<ul><b>Array / List of Nested Object</b>
<li><code>testFolders : String</code>
</li>
</ul></li>
</ul></li>
<li><code>selectByTag</code> (optional)
<div><div>
 <br>
  Specify the test tag used to select test suite elements. To generate a suite, the plugin uses only the test elements with the specified tag. 
 <br>
</div></div>

<ul><b>Nested Object</b>
<li><code>testTag : String</code>
</li>
</ul></li>
<li><code>sourceFolder</code> (optional)
<div><div>
 <p>Specify the location of folders containing source code, relative to the project root folder. The specified folders and their subfolders are added to the top of the MATLAB search path. To generate a coverage report, MATLAB uses only the source code in the specified folders and their subfolders.</p>
 <p>Paste the source folder path in the <b>Folder path</b> box. To add more folders, click <b>Add folder</b>.</p>
</div></div>

<ul><b>Nested Object</b>
<li><code>sourceFolderPaths</code>
<ul><b>Array / List of Nested Object</b>
<li><code>srcFolderPath : String</code>
</li>
</ul></li>
</ul></li>
<li><code>startupOptions</code> (optional)
<div><div>
 A space-separated list of MATLAB startup options.
</div></div>

<ul><b>Nested Object</b>
<li><code>options : String</code>
</li>
</ul></li>
<li><code>stmResultsArtifact</code> (optional)
<div><div>
 <br>
 Export Simulink Test™ Manager results in MLDATX format. By default, MATLAB names the artifact <b>simulinktestresults.mldatx</b> and stores it in the <b>matlabTestArtifacts</b> folder of the project workspace. To override the default artifact name and location, specify a path relative to the project folder in the <b>File path</b> box. If the text box is empty, MATLAB does not generate an artifact. 
 <br>
 <br><b>Note:</b> This feature requires a <b>Simulink Test</b> license and is supported only in MATLAB R2019a or a newer release.
</div></div>

<ul><b>Nested Object</b>
<li><code>stmResultsFilePath : String</code>
</li>
</ul></li>
<li><code>strict : boolean</code> (optional)
<div><div>
 <p>Whether to apply strict checks when running the tests. For example, the framework generates a qualification failure if a test issues a warning.</p>
</div></div>

</li>
<li><code>tapArtifact</code> (optional)
<div><div>
 <br>
  Generate a test report in TAP format. By default, MATLAB names the artifact <b>taptestresults.tap</b> and stores it in the <b>matlabTestArtifacts</b> folder of the project workspace. To override the default artifact name and location, specify a path relative to the project folder in the <b>File path</b> box. If the text box is empty, MATLAB does not generate an artifact. 
 <br>
</div></div>

<ul><b>Nested Object</b>
<li><code>tapReportFilePath : String</code>
</li>
</ul></li>
<li><code>useParallel : boolean</code> (optional)
<div><div>
 <p>Whether to run tests in parallel. This feature requires a Parallel Computing Toolbox license, and might not be compatible with other options. If incompatible, testing occurs in serial regardless of the value of this feature.</p>
</div></div>

</li>
</ul>


++++
=== `wrap([$class: 'UseMatlabVersionBuildWrapper'])`: Use MATLAB version
++++
<div><div>
 <p>Use this list to specify the MATLAB version for the build. The plugin prepends your specified MATLAB to the PATH environment variable and uses it to perform the build. <br>
   The list includes the names of all MATLAB versions that have been registered as a tool in Jenkins. Select one of the tools, or select <b>Custom</b> if you want to specify a different version. When you select <b>Custom</b>, you must enter the full path to the desired MATLAB root folder in the <b>MATLAB root</b> box.</p>
 <p><br><b>Note:</b> In multi-configuration projects, the value specified by <b>Use MATLAB version</b> takes precedence over the values specified by the <b>MATLAB</b> axis.</p>
</div></div>
<ul><li><code>matlabBuildWrapperContent</code> (optional)
<ul><b>Nested Object</b>
<li><code>matlabInstallationName : String</code>
</li>
<li><code>matlabRootFolder : String</code>
</li>
</ul></li>
</ul>


++++
