= Mattermost Notification Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/mattermost">Visit the Jenkins Plugins site</a>
++++


=== `mattermostSend`: Send Mattermost message
++++
<div><div>
 Simple step for sending a Mattermost message to specified channel.
 <br>
  Use the advanced settings to override the Mattermost Plugin global configuration to include: <code>endpoint</code>, <code>channel</code> and <code>icon</code>.
 <br>
  Please see the Mattermost Plugin global configuration for more details on the fields. Usage Example:
 <br><code> mattermostSend "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (&lt;${env.BUILD_URL}|Open&gt;)" </code>
</div></div>
<ul><li><code>message : String</code>
<div><div>
 This is the main text in a message attachment, and can contain standard message markup. The content will automatically collapse if it contains 700+ characters or 5+ linebreaks, and will display a "Show more..." link to expand the content. Message may include global variables, for example environment and currentBuild variables:
 <br><code> mattermostSend "started ${env.JOB_NAME} ${env.BUILD_NUMBER} (&lt;${env.BUILD_URL}|Open&gt;)" </code>
</div></div>

</li>
<li><code>channel : String</code> (optional)
<div><div>
 Allows overriding the Mattermost Plugin channel specified in the global configuration.
 <br><code>mattermostSend channel: "#channel-name", message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"</code>
</div></div>

</li>
<li><code>color : String</code> (optional)
<div><div>
 An <b>optional</b> value that can either be one of <b>good</b>, <b>warning</b>, <b>danger</b>, or any <b>hex color code</b> (eg. #439FE0). This value is used to color the border along the left side of the message attachment.
 <br><code>mattermostSend color: "#439FE0", message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"</code>
</div></div>

</li>
<li><code>endpoint : String</code> (optional)
<div><div>
 Allows overriding the Mattermost Plugin endpoint (url?token) specified in the global configuration.
</div></div>

</li>
<li><code>failOnError : boolean</code> (optional)
<div><div>
 If set to true, then the step will abort the Workflow run if there is an error sending message.
 <br><code>mattermostSend failOnError: true, message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"</code>
</div></div>

</li>
<li><code>icon : String</code> (optional)
<div><div>
 Allows overriding the Mattermost Plugin Integration icon specified in the global configuration.
</div></div>

</li>
<li><code>text : String</code> (optional)
<div><div>
 This text is the main message after the message attachment, and can contain standard message markup. The content may contain user "mentions" and highlights.
 <br><code> mattermostSend prext: "@foo @bar" color: "#439FE0", message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}" </code>
</div></div>

</li>
</ul>


++++
