= meliora-testlab
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/meliora-testlab">Visit the Jenkins Plugins site</a>
++++


=== `melioraTestlab`: Publish test results to Testlab
++++
<ul><li><code>projectKey : String</code>
<div><div>
 <p>The key of the Testlab project you want to publish the results to.</p>
</div></div>

</li>
<li><code>ruleset : String</code> (optional)
<div><div>
 <p>A "source" is a set of settings and mapping rules defined in Testlab. Enter a name of the source you wish to use for processing the pushed results. If you wish to override a setting (or settings) in your job, choose the "Override source settings" option and set the preferred values.</p>
 <p><i>If not set, the default source in your Testlab will be used.</i></p>
</div></div>

</li>
<li><code>rulesetSettings</code> (optional)
<ul><b>Nested Object</b>
<li><code>testRunTitle : String</code> (optional)
</li>
<li><code>milestone : String</code> (optional)
</li>
<li><code>testTargetTitle : String</code> (optional)
</li>
<li><code>testEnvironmentTitle : String</code> (optional)
</li>
<li><code>addIssueStrategy</code> (optional)
<ul><li><b>Values:</b> <code>DONOTADD</code>, <code>ADDPERTESTRUN</code>, <code>ADDPERTESTCASE</code>, <code>ADDPERRESULT</code>, <code>RULESET_DEFAULT</code></li></ul></li>
<li><code>reopenExisting : boolean</code> (optional)
</li>
<li><code>assignToUser : String</code> (optional)
</li>
<li><code>importTestCases : boolean</code> (optional)
</li>
<li><code>importTestCasesRootCategory : String</code> (optional)
</li>
<li><code>robotCatenateParentKeywords : boolean</code> (optional)
</li>
<li><code>testCaseMappingField : String</code> (optional)
</li>
<li><code>tags : String</code> (optional)
</li>
</ul></li>
<li><code>description : String</code> (optional)
<div><div>
 <p>The description to be set for the Testlab test run to create or update.</p>
 <p>In this field the build time environmental variables of Jenkins are handy. In addition to the <a href="https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables" rel="nofollow">by default set environment variables</a> this plugin registers the following variables that can be used for configuration values:</p>
 <table width="100%">
  <tbody>
   <tr>
    <td><b>Variable</b></td>
    <td><b>Description</b></td>
   </tr>
   <tr>
    <td>${BUILD_FULL_DISPLAY_NAME}</td>
    <td>Combined full display name of the build with job name and build number. For example 'my jenkins job #133'</td>
   </tr>
   <tr>
    <td>${BUILD_RESULT}</td>
    <td>Result of the build. For example 'SUCCESS' or 'UNSTABLE'.</td>
   </tr>
   <tr>
    <td>${BUILD_STATUS}</td>
    <td>Summary of the overall build. For example 'broken for a long time'.</td>
   </tr>
  </tbody>
 </table>
 <p>To use variables in your configuration values make sure to enter tags as <i>${VARIABLE}</i>.</p>
</div></div>

</li>
<li><code>parameters : String</code> (optional)
<div><div>
 <p>Environment variables to sent to Testlab as test case parameters.</p>
 <p>Test cases in Testlab can include parameters in the content as ${PARAM1} formatted tags. Normally, these tags are set and replaced with values set during the test case execution or execution planning phase. By listing variables to this setting makes it possible to send values of environmental variables from Jenkins as test case parameters to Testlab.</p>
 <p>For example, test case(s) in your Testlab project might have a parameter titled ${BROWSER}. When running automated UI tests in your Jenkins, enter a value "BROWSER" to this setting and ensure that your job sets an environmental variable BROWSER to some sensible value. This way running the job sends and sets the ${BROWSER} test case parameter value to all run tests to a value matching to the environmental variable.</p>
 <p>Probably the easiest way to set environment variables is to use a <a href="https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin" rel="nofollow">fitting plugin</a>.</p>
</div></div>

</li>
<li><code>publishRobot</code> (optional)
<div><div>
 <p>The plugin supports publishing the results directly from <i><a href="http://robotframework.org/" rel="nofollow">Robot Framework</a></i> output files found in the build.</p>
 <p><strong> Note: This option publishes results directly from Robot's output.xml file. This produces a more detailed result in Testlab compared to the junit-format based output of Robot Framework. </strong></p>
</div></div>

<ul><b>Nested Object</b>
<li><code>robotCatenateParentKeywords : boolean</code>
</li>
<li><code>robotOutput : String</code> (optional)
</li>
</ul></li>
<li><code>publishTap</code> (optional)
<div><div>
 <p>The plugin supports publishing the results from TAP (<i><a href="https://testanything.org/tap-specification.html" rel="nofollow">Test Anything Protocol</a></i>) files found in the build. If not checked, the possible TAP results produced by the job are ignored.</p>
 <p><strong> To publish TAP results the <a href="https://wiki.jenkins-ci.org/display/JENKINS/TAP+Plugin" rel="nofollow">TAP-Plugin</a> must be installed to your Jenkins. In addition to this, the job must be configured with "Publish TAP Results" Post-build Action to make the results available for publishing. </strong></p>
</div></div>

<ul><b>Nested Object</b>
<li><code>tapFileNameInIdentifier : boolean</code> (optional)
</li>
<li><code>tapTestNumberInIdentifier : boolean</code> (optional)
</li>
<li><code>tapTestsAsSteps : boolean</code> (optional)
</li>
<li><code>tapMappingPrefix : String</code> (optional)
</li>
</ul></li>
<li><code>advancedSettings</code> (optional)
<ul><b>Nested Object</b>
<li><code>testCaseMappingField : String</code>
</li>
<li><code>companyId : String</code> (optional)
</li>
<li><code>apiKey</code> (optional)
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>usingonpremise</code> (optional)
<ul><b>Nested Object</b>
<li><code>onpremiseurl : String</code> (optional)
</li>
</ul></li>
</ul></li>
<li><code>automationSource : String</code> (optional)
<div><div>
 <p>Source is used to identify results, so that two test runs with the same source name should contain results for same, or similar tests. The default {JOB_NAME} - value uses the Jenkins job's name as automation source name.</p>
</div></div>

</li>
</ul>


++++
