= Memory Map Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/memory-map">Visit the Jenkins Plugins site</a>
++++


=== `memoryMap`: Memory Map Publisher
++++
<ul><li><code>chosenParsers</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>gccParser</code><div>
<ul><li><code>parserUniqueName : String</code>
<div><p>A unique parser name. This has to be unique among the parsers chosen in this job otherwise results will get mixed together, renaming this invalidates previous results.</p></div>

</li>
<li><code>mapFile : String</code>
<div><p>An Ant file pattern, pointing to a map file, which describes the location of code in the specified memory layout</p></div>

</li>
<li><code>configurationFile : String</code>
<div><p>An Ant file pattern, pointing to a command file, which describes the memory layout of the target device</p></div>

</li>
<li><code>wordSize : int</code>
</li>
<li><code>bytesOnGraph : boolean</code>
</li>
<li><code>graphConfiguration</code>
<ul><b>Array / List of Nested Object</b>
<li><code>graphDataList : String</code>
<div><h1>Graph data settings</h1>
<h3>The <em>data</em> to be harvested</h3>
<p>You can add several data values to one graph, with a comma separator, i.e <em>DATA,CONST</em></p>
<p>This will create a graph with two datapoints</p>
<p>You can also ADD the values of the sections together like so: <em>DATA+CONST</em> this will generate one combined dataset with the combined value of CONST and DATA</p></div>

</li>
<li><code>graphCaption : String</code>
<div><p>The <em>title</em> of the graph</p></div>

</li>
</ul></li>
<li><code>parserTitle : String</code> (optional)
</li>
</ul></div></li>
<li><code>tiParser</code><div>
<ul><li><code>parserUniqueName : String</code>
<div><p>A unique parser name. This has to be unique among the parsers chosen in this job otherwise results will get mixed together, renaming this invalidates previous results.</p></div>

</li>
<li><code>mapFile : String</code>
<div><p>An Ant file pattern, pointing to a map file, which describes the location of code in the specified memory layout</p></div>

</li>
<li><code>configurationFile : String</code>
<div><p>An Ant file pattern, pointing to a command file, which describes the memory layout of the target device</p></div>

</li>
<li><code>wordSize : int</code>
</li>
<li><code>graphConfiguration</code>
<ul><b>Array / List of Nested Object</b>
<li><code>graphDataList : String</code>
<div><h1>Graph data settings</h1>
<h3>The <em>data</em> to be harvested</h3>
<p>You can add several data values to one graph, with a comma separator, i.e <em>DATA,CONST</em></p>
<p>This will create a graph with two datapoints</p>
<p>You can also ADD the values of the sections together like so: <em>DATA+CONST</em> this will generate one combined dataset with the combined value of CONST and DATA</p></div>

</li>
<li><code>graphCaption : String</code>
<div><p>The <em>title</em> of the graph</p></div>

</li>
</ul></li>
<li><code>bytesOnGraph : boolean</code>
</li>
<li><code>parserTitle : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>scale : String</code> (optional)
<div><p>Scale for y-axis</p></div>

</li>
<li><code>showBytesOnGraph : boolean</code> (optional)
<div><p>Show "Bytes" on y-axis rather than "Words"</p></div>

</li>
<li><code>wordSize : int</code> (optional)
<div><p>The word size of the processor</p>
<p><em>Default value is 8</em></p></div>

</li>
</ul>


++++
