= Metrics Aggregation
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/metrics-aggregation">Visit the Jenkins Plugins site</a>
++++


=== `metrics`: Record Metrics
++++
<ul><li><code>classPathFile : String</code> (optional)
<div><div>
 In order to use Type resolution during the analysis, PMD has to have access to the classpath of the project. 
 <p>In case of a <b>maven</b> build, a file containing the classpath can be generated with: <code>mvn dependency:build-classpath -Dmdep.outputFile=cp.txt</code> Alternatively it is also possible include this in your pom.xml so it is generated as part of the build. See <a href="https://maven.apache.org/plugins/maven-dependency-plugin/usage.html" rel="nofollow"> https://maven.apache.org/plugins/maven-dependency-plugin/usage.html</a> for more information.</p>
 <p>When using <b>gradle</b>, a file containing the classpath can be generated by adding <code> task removecp(type: Delete) { delete "cp.txt" } subprojects { task printcp { new File(rootDir, "cp.txt").append(":" + sourceSets.main.runtimeClasspath.join(':')) } } </code> to the end of your build.gradle and executing <code>gradlew removecp printcp</code>.</p>
</div></div>

</li>
<li><code>filePattern : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'MetricsRecorder'])`: Record Metrics
++++
<ul><li><code>classPathFile : String</code> (optional)
</li>
<li><code>filePattern : String</code> (optional)
</li>
</ul>


++++
