= OpenText LoadRunner Enterprise integration With Git
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/micro-focus-performance-center-integration">Visit the Jenkins Plugins site</a>
++++


=== `pcGitBuild`: Synchronize LoadRunner Enterprise With Git
++++
<div><div>
 The plugin allows to synchronize scripts from Git repository to OpenText LoadRunner Enterprise project.
 <br>
  The plugin respects the subfolders structure defined in Git when synchronizing LoadRunner scripts to Performance Center 12.60 and above. For previous versions, all scripts will be uploaded to the same root folder in the Test Plan tree of the LoadRunner Enterprise project (scripts with duplicated named will be overwritten).
 <br>
</div></div>
<ul><li><code>description : String</code>
</li>
<li><code>pcServerName : String</code>
<div><div>
 Hostname or IP address The LoadRunner Enterprise Hostname or IP address. If the port of the LRE server is different than the default one, mention it by adding a collon (:) and then the port number
 <br><b>Example</b>: mypcserver.mycompany.net or 182.138.255.1 or mypcserver.mycompany.net:81
 <br>
 <br>
  If the LRE server requires to be accessed via a tenant, you can specify it by adding the tenant details to the LRE Server field.
 <br><b>Example</b>: mypcserver.mycompany.net/?tenant=fa128c06-5436-413d-9cfa-9f04bb738df3 or 182.138.255.1/?tenant=fa128c06-5436-413d-9cfa-9f04bb738df3 or mypcserver.mycompany.net:81/?tenant=fa128c06-5436-413d-9cfa-9f04bb738df3
 <br>
 <br><b>Important</b>: Do not use the full URL of LoadRunner Enterprise server. 
 <br>
  For example, using https://mypcserver/LoadTest will fail. Instead, just specify 'mypcserver' value in 'LRE Server' field and switch on the 'Use HTTPS Protocol' if secured protocol is required.
</div></div>

</li>
<li><code>httpsProtocol : boolean</code>
</li>
<li><code>credentialsId : String</code>
<div><div>
 LoadRunner Enterprise User / Token's Credentials or parameter pointing to such credentials.
</div></div>

</li>
<li><code>almDomain : String</code>
</li>
<li><code>almProject : String</code>
</li>
<li><code>serverAndPort : String</code>
</li>
<li><code>proxyOutURL : String</code>
<div><div>
 Add your local proxy as following: 
 <br><b>http(s)://host:port</b>
 <br>
  or Leave empty if not using a local proxy.
 <br>
  The following proxy configurations are not supported: 
 <ul>
  <li>PAC (proxy auto-config).</li>
  <li>Automatic configuration script.</li>
 </ul>
</div></div>

</li>
<li><code>credentialsProxyId : String</code>
</li>
<li><code>subjectTestPlan : String</code>
<div><div>
 <b>This field is obsolete and remains for backward compatibility. It can be ignored</b> The Test Plan folder path in LoadRunner Enterprise where the scripts will be loaded.
 <br>
  Available paths can be found in the LoadRunner Enterprise interface: <b>Test Management</b> -&gt; <b>Test Plan</b>
 <br>
  The path must begin with "<b>Subject</b>" and be separated with backslashes (<b>\</b>).
 <br>
  The path is case-sensitive!
 <br><b>Important</b>: For Performance Center Server below version 12.60: 
 <ul>
  <li>the specified folder must exist at the time of the build (the plugin can not create folders independently).</li>
  <li>Scripts saved in Git subfolders will be synchronized to the specified subject and in case of duplicated script names in Git, the last uploaded script to LRE will overwrite the previously uploaded script(s) with the same name.</li>
 </ul>
</div></div>

</li>
<li><code>uploadScriptMode</code>
<div><div>
 This corresponds to the similar option existing in LoadRunner Enterprise / VuGen: 
 <ul>
  <li><b>All Files</b>: All script files are uploaded (this takes longer to load).</li>
  <li><b>Runtime Files</b>: Only the required files are uploaded (script files, Runtime Settings, parameter files, etc.)</li>
 </ul><b>Recommended value</b>: "<b>Runtime Files</b>".
 <br>
</div></div>

<ul><li><b>Values:</b> <code>RUNTIME_FILES</code>, <code>ALL_FILES</code></li></ul></li>
<li><code>removeScriptFromPC</code>
<div><div>
 This option will allow you to synchronize scripts deletion from Git to LoadRunner Enterprise.
 <br>
 <br>
  The recommended value is "<b> Yes</b>".
 <br>
</div></div>

<ul><li><b>Values:</b> <code>YES</code>, <code>NO</code></li></ul></li>
<li><code>importTests</code>
<div><p></p>
<h1>How to import tests from YAML files saved in the Git repository</h1>
<div>
 Copy your YAML files to a folder in your Git repository (YAML files under the root of the Git repository will be ignored). The plugin will create the test in the LoadRunner Enterprise project according to: 
 <ul>
  <li>The file name (without extension) which will be used as test name.</li>
  <li>The location of the file in the Git repository which will be the location of the test under the root folder ('Subject') in the <strong>Test Management</strong> tree.</li>
  <li>The content of the YAML file which must be composed according to the parameters described in the tables below.</li>
 </ul>
</div>
<p></p>
<p><strong>Note:</strong></p>
<ul>
 <li>All parameters must be in lowercase.</li>
 <li>When a backslash (\) occurs in a value provided to a parameter (for example, a folder separator in a file path), a double backslash (\\) must be used instead.</li>
 <li>This feature is supported with Performance Center 12.61 and later versions.</li>
</ul>
<p></p>
<p></p>
<div>
 Root parameters of the YAML file: 
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>controller</td>
    <td>
     <div>
      Defines the Controller to be used during the test run (it must be an available host in the LoadRunner Enterprise project). If not specified, a Controller will be chosen from the different controllers available in the LoadRunner Enterprise project.
     </div>
     <div>
      From Performance Center 12.62 and plugin version 1.1.1, the option to provision a Controller as a Docker image is available by specifying the value "Elastic" and providing a value for the 'controller_elastic_configuration' parameter (see 'controller_elastic_configuration' table below).
     </div></td>
    <td>No</td>
   </tr>
   <tr>
    <td>lg_amount</td>
    <td>Number of load generators to allocate to the test (every group in the test will be run by the same load generators).</td>
    <td>Not required if each group defined in the 'group' parameter defines the load generators it will be using via the 'lg_name' parameter (see 'group' table below).</td>
   </tr>
   <tr>
    <td>group</td>
    <td>Lists all groups or scripts defined in the test. The parameter to be used in each group are specified in the 'group' table below.</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>scheduler</td>
    <td>Defines the duration of a test, and determines whether virtual users are started simultaneously or gradually. See the 'scheduler' table below.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>lg_elastic_configuration</td>
    <td>Defines the image to be used in order to provision load generators. See the 'lg_elastic_configuration' table below. Available from Performance Center 12.62 and plugin version 1.1.1.</td>
    <td>Yes, if a load generator is defined to be provisioned from a Docker image.</td>
   </tr>
   <tr>
    <td>controller_elastic_configuration</td>
    <td>Defines the image to be used in order to provision the Controller. See the 'controller_elastic_configuration' table below. Available from Performance Center 12.62 and plugin version 1.1.1.</td>
    <td>Yes, if the Controller is defined to be provisioned from a Docker image.</td>
   </tr>
   <tr>
    <td>automatic_trending</td>
    <td>Defines association to existing trend report.</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>group:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>group_name</td>
    <td>Name of the group (it must be a unique name if several groups are defined).</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>vusers</td>
    <td>Number of virtual users to allocate to the group for running the script.</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>script_id</td>
    <td>ID of the script in the LoadRunner Enterprise project.</td>
    <td>Not required if the 'script_path' parameter is specified.</td>
   </tr>
   <tr>
    <td>script_path</td>
    <td>Path and name of the script to be added to the group, separated by double backslashes (\\). For example "MyMainFolder\\MySubFolder\\MyScriptName'. Do not include the LoadRunner Enterprise root folder (named "Subject").</td>
    <td>Not required if 'script_id' parameter is specified</td>
   </tr>
   <tr>
    <td>lg_name</td>
    <td>List of load generators to allocate to the group for running the script. The supported values are: 
     <ul>
      <li>The hostname, as defined in LoadRunner Enterprise, of an existing load generator in LoadRunner Enterprise allocated as a host.</li>
      <li><strong>"LG"</strong> followed by a number, to use an automatically matched load generator (recommended).</li>
      <li><strong>"DOCKER"</strong> followed by a number, to use a dynamic load generator (available from Performance Center 12.62, if your project is set to work with Docker). This option requires the 'lg_elastic_configuration' parameter to be defined (see the 'lg_elastic_configuration' table below).</li>
     </ul></td>
    <td>No</td>
   </tr>
   <tr>
    <td>command_line</td>
    <td>The command line applied to the group.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>rts</td>
    <td>Object defining the runtime settings of the script. See the 'rts' table below.</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>rts:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>pacing</td>
    <td>Can be used to define the number of iterations the script will run and the required delay between iterations (see the 'pacing' table below).</td>
    <td>No</td>
   </tr>
   <tr>
    <td>thinktime</td>
    <td>Can be used to define think time (see the 'thinktime' table below).</td>
    <td>No</td>
   </tr>
   <tr>
    <td>java_vm</td>
    <td>Can be used when defining Java environment runtime settings (see the 'java_vm' table below).</td>
    <td>No</td>
   </tr>
   <tr>
    <td>jmeter</td>
    <td>Can be used to define JMeter environment runtime settings (see the 'jmeter' table below).</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>pacing:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>number_of_iterations</td>
    <td>Specifies the number of iterations to run; this must be a positive number.</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>type</td>
    <td>Possible values for type attribute are: 
     <ul>
      <li><strong>"immediately"</strong>: ignores 'delay' and 'delay_random_range' parameters. This is the default value when no type is specified.</li>
      <li><strong>"fixed delay"</strong>: 'delay' parameter is mandatory.</li>
      <li><strong>"random delay"</strong>: 'delay' and 'delay_random_range' parameters are mandatory.</li>
      <li><strong>"fixed interval"</strong>: 'delay' parameter is mandatory.</li>
      <li><strong>"random interval"</strong>: 'delay' and 'delay_random_range' parameters are mandatory.</li>
     </ul></td>
    <td>No</td>
   </tr>
   <tr>
    <td>delay</td>
    <td>Non-negative number (less than 'delay_at_range_to_seconds' when specified).</td>
    <td>Depends on the value provided for the 'type' parameter.</td>
   </tr>
   <tr>
    <td>delay_random_range</td>
    <td>Non-negative number. It will be added to the value given to the 'delay' parameter (the value will be randomly chosen between the value given to 'delay' parameter and the same value to which is added the value of this parameter).</td>
    <td>Depends on the value provided for the 'type' parameter.</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>thinktime:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>type</td>
    <td>The ThinkTime Type attribute is one of: 
     <ul>
      <li><strong>"ignore"</strong>: This is the default value when no type is specified.</li>
      <li><strong>"replay"</strong>: Provide 'limit_seconds' parameter with value.</li>
      <li><strong>"modify"</strong>: Provide 'limit_seconds' and 'multiply_factor' parameters with values.</li>
      <li><strong>"random"</strong>: Provide 'limit_seconds', 'min_percentage' and 'max_percentage' parameters with values.</li>
     </ul></td>
    <td>No</td>
   </tr>
   <tr>
    <td>min_percentage</td>
    <td>This must be a positive number.</td>
    <td>Depends on the value provided for the 'type' parameter.</td>
   </tr>
   <tr>
    <td>max_percentage</td>
    <td>This must be a positive number (it must be larger than the value provided for the 'min_percentage' parameter).</td>
    <td>Depends on the value provided for the 'type' parameter.</td>
   </tr>
   <tr>
    <td>limit_seconds</td>
    <td>This must be a positive number.</td>
    <td>Depends on the value provided for the 'type' parameter.</td>
   </tr>
   <tr>
    <td>multiply_factor</td>
    <td>The recorded think time is multiplied by this factor at runtime.</td>
    <td>Depends on the value provided for the 'type' parameter.</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>java_vm:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>jdk_home</td>
    <td>The JDK installation path.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>java_vm_parameters</td>
    <td>List the Java command line parameters. These parameters can be any JVM argument. The common arguments are the debug flag (-verbose) or memory settings (-ms, -mx). In additional, you can also pass properties to Java applications in the form of a -D flag.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>use_xboot</td>
    <td>Boolean: Instructs VuGen to add the Classpath before the Xbootclasspath (prepend the string).</td>
    <td>No</td>
   </tr>
   <tr>
    <td>enable_classloader_per_vuser</td>
    <td>Boolean: Loads each Virtual User using a dedicated class loader (runs Vusers as threads).</td>
    <td>No</td>
   </tr>
   <tr>
    <td>java_env_class_paths</td>
    <td>A list of classpath entries. Use a double backslash (\\) for folder separators.</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>jmeter:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>start_measurements</td>
    <td>Boolean value to enable JMX measurements during performance test execution.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>jmeter_home_path</td>
    <td>Path to JMeter home. If not defined, the path from the %JMETER_HOME% environment variable is used.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>jmeter_min_port</td>
    <td>This number must be lower than the value provided in the 'jmeter_max_port' parameter. Both 'jmeter_min_port' and 'jmeter_max_port' parameters must be specified otherwise the default port values is used.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>jmeter_max_port</td>
    <td>This number must be higher than the value provided in the 'jmeter_min_port' parameter. Both 'jmeter_min_port' and 'jmeter_max_port' parameters must be specified otherwise the default port values is used.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>jmeter_additional_properties</td>
    <td>JMeter additional properties file. Use double slash (\\) for folder separator.</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>scheduler:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>rampup</td>
    <td>Time, in seconds, to gradually start all virtual users. Additional virtual users are added every 15 seconds until the time specified in the parameter ends. If no value is specified, all virtual users are started simultaneously at the beginning of the test.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>duration</td>
    <td>Time, in seconds, that it will take to run the test after all virtual users are started. After this time, the test run ends. If not specified, the test will run until completion.</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>automatic_trending:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>report_id</td>
    <td>Id of the trend report to associate the test run analysis with.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>max_runs_in_report</td>
    <td>Maximum trends in a report (default is 10 if not specified).</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>lg_elastic_configuration:</strong> (available from Performance Center 12.62 and plugin version 1.1.1)
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>image_id</td>
    <td>This number can be retrieved from: 
     <ul>
      <li>The Administration page of LoadRunner Enterprise (you might need to turn to your LoadRunner Enterprise administrator as accessing this page requires admin privileges): select the <strong>Orchestration</strong> section -&gt; switch to <strong>Docker Images</strong> tab -&gt; you will have the list of all available Docker images for Load Generator purposes with their ID. You can make sure the images are available to your project from the <strong>Orchestrators</strong> tab.</li>
      <li>A LoadRunner Enterprise Rest API command applied on the project (replace the bracketed values): GET - <a rel="nofollow">http(s)://(PCServer):(PortNumber)/LoadTest/rest/domains/(DomainName)/projects/(ProjectName)/dockerimages/</a> and select any valid image not having the value 'controller' for purpose.</li>
     </ul></td>
    <td>Yes if one of the load generator is defined to be provisioned from Docker image.</td>
   </tr>
   <tr>
    <td>memory_limit</td>
    <td>This parameter can be retrieved from <strong>LoadRunner Enterprise Application</strong> -&gt; <strong>Test Management</strong> -&gt; edit a test -&gt; Press <strong>Assign LG</strong> button -&gt; in the <strong>Elastic</strong> section, select <strong>DOCKER1</strong> -&gt; select the relevant image (based on the image name) -&gt; use the values provided in the 'Memory(GB)' dropdown list (if not specified, this parameter should be ignored).</td>
    <td>Yes, if the image is defined with resource limits</td>
   </tr>
   <tr>
    <td>cpu_limit</td>
    <td>This parameter can be retrieved from <strong>LoadRunner Enterprise Application</strong> -&gt; <strong>Test Management</strong> -&gt; edit a test -&gt; Press <strong>Assign LG</strong> button -&gt; in the <strong>Elastic</strong> section, select <strong>DOCKER1</strong> -&gt; select the relevant image (based on the image name) -&gt; use the values provided in the 'CUPs' dropdown list (if not specified, this parameter should be ignored).</td>
    <td>Yes, if the image is defined with resource limits</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>controller_elastic_configuration:</strong> (available from Performance Center 12.62 and plugin version 1.1.1)
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>image_id</td>
    <td>This number can be retrieved from: 
     <ul>
      <li>The Administration page of LoadRunner Enterprise (you might need to turn to your LoadRunner Enterprise administrator as accessing this page requires admin privileges): select the <strong>Orchestration</strong> section -&gt; switch to <strong>Docker Images</strong> tab -&gt; you will have the list of all available Docker images for Controller purposes with their ID. You can make sure the images are available to your project from the <strong>Orchestrators</strong> tab.</li>
      <li>A LoadRunner Enterprise Rest API command applied on the project (replace the bracketed values): GET - <a rel="nofollow">http(s)://(PCServer):(PortNumber)/LoadTest/rest/domains/(DomainName)/projects/(ProjectName)/dockerimages/</a> and select any valid image having the value 'controller' for purpose.</li>
     </ul></td>
    <td>Yes if the Controller is defined to be provisioned from Docker image.</td>
   </tr>
   <tr>
    <td>memory_limit</td>
    <td>This parameter can be retrieved from <strong>LoadRunner Enterprise Application</strong> -&gt; <strong>Test Management</strong> -&gt; edit a test -&gt; select the Controller -&gt; choose <strong>Elastic</strong> option -&gt; select the relevant image -&gt; Under the <strong>Resource Limits</strong> label, find and use the values provided in the 'Memory(GB)' dropdown list (if not specified, this parameter should be ignored).</td>
    <td>Yes, if the image is defined with resource limits</td>
   </tr>
   <tr>
    <td>cpu_limit</td>
    <td>This parameter can be retrieved from <strong>LoadRunner Enterprise Application</strong> -&gt; <strong>Test Management</strong> -&gt; edit a test -&gt; select the Controller -&gt; choose <strong>Elastic</strong> option -&gt; select the relevant image -&gt; Under the <strong>Resource Limits</strong> label, find and use the values provided in the 'CUPs' dropdown list (if not specified, this parameter should be ignored).</td>
    <td>Yes, if the image is defined with resource limits</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 In the example below: 
 <ul>
  <li>The plugin automatically assigns the file name as the test name, and the folder path of the file in the Git repository is used to create the location of the test under the root folder ('Subject') in the LoadRunner Enterprise project.</li>
  <li>In the content: 
   <ul>
    <li>Since no Controller and no load generator amount were specified, a random available Controller will be allocated to the test just before it is run and the 'lg_name' parameter specified in each group will be used.</li>
    <li>In the 'group' parameter: 
     <ul>
      <li>We added two scripts. For each, we provided a unique value in the 'group_name' parameter, and the number of virtual users to run the group.</li>
      <li>Since we did not know the ID of the scripts, we used the 'script_path' parameter in which we entered the script path (without "Subject") followed by the script name, and used double backslashes for separators.</li>
      <li>We specified the load generators that will be used by each group (in this case, load generators will automatically be matched as we use the 'LG' prefix).</li>
     </ul></li>
   </ul></li>
  <li>In the scheduler: 
   <ul>
    <li>We want all Virtual Users to be initialized gradually (45 seconds).</li>
    <li>We want the test to stop after 5 minutes (300 seconds).</li>
   </ul></li>
 </ul>
</div>
<pre>
<code>
##################################################
group:
- group_name: "TEstInt"
  vusers: '20'
  script_path: "plugin\\TEstInt"
  lg_name:
  - "LG1"
  - "LG2"
- group_name: "Mtours"
  vusers: '20'
  script_path: "plugin\\mtours"
  lg_name:
  - "LG3"
  - "LG4"
scheduler:
  rampup: '45'
  Duration: '300'
##################################################
</code>
</pre>
<p></p>
<p></p>
<div>
 In the example below: 
 <ul>
  <li>The plugin automatically assigns the file name as the test name, and the folder path of the file in the Git repository is used to create the location of the test under the root folder ('Subject') in the LoadRunner Enterprise project.</li>
  <li>Since the 'controller' and the 'lg_amount' parameters are specified, the specified Controller will be used to run the test and three automatch load generators will be used and shared by all groups.</li>
  <li>The content of the file is defined with seven groups, all being set with the “rts” parameter: 
   <ul>
    <li>The “pacing” parameter is used with different options for all groups.</li>
    <li>The “java_vm” parameter is used for five scripts with JavaVM for protocol.</li>
    <li>The “thinktime” parameter is used with different options for four groups.</li>
    <li>The “jmeter” parameter is used for two scripts with JMeter for protocol.</li>
   </ul></li>
  <li>In the scheduler: 
   <ul>
    <li>We want all Virtual Users to be initialized gradually (120 seconds).</li>
    <li>We want the test to stop after 10 minutes (600 seconds).</li>
   </ul></li>
 </ul>
</div>
<pre>
<code>
##################################################
controller: "mycontroller"
lg_amount: 3
group:
  - group_name: "JavaVuser_LR_Information_pacing_immediately_thinktime_ignore"
    vusers: 50
    script_id: 394
    rts:
      pacing:
        number_of_iterations: 2
        type: "immediately"
      java_vm:
        jdk_home: "C:\\Program Files\\Java\\jdk1.8.0_191"
        java_vm_parameters: "java_vm_parameters"
        enable_classloader_per_vuser: true
        use_xboot: true
        java_env_class_paths:
          - "java_env_class_path1"
          - "java_env_class_path2"
      thinktime:
        type: "ignore"

  - group_name: "JavaHTTP_BigXML_pacing_fixed_delay_thinktime_replay"
    vusers: 50
    script_path: "scripts\\java_protocols\\JavaHTTP_BigXML"
    rts:
      pacing:
        number_of_iterations: 2
        type: "fixed delay"
        delay: 10
      java_vm:
        jdk_home: "C:\\Program Files\\Java\\jdk1.8.0_191"
        java_vm_parameters: "java_vm_parameters"
        enable_classloader_per_vuser: true
      thinktime:
        type: "replay"
        limit_seconds: 30

  - group_name: "JavaVuser_LR_Information_immediately_pacing_random_delay_thinktime_modify"
    vusers: 50
    script_id: 394
    rts:
      pacing:
        number_of_iterations: 2
        type: "random delay"
        delay: 10
        delay_random_range: 20
      java_vm:
        jdk_home: "C:\\Program Files\\Java\\jdk1.8.0_191"
        java_vm_parameters: "java_vm_parameters"
        enable_classloader_per_vuser: true
        java_env_class_paths:
          - "java_env_class_path1"
          - "java_env_class_path2"
      thinktime:
        type: "modify"
        limit_seconds: 30
        multiply_factor: 2

  - group_name: "JavaHTTP_BigXML_pacing_fixed_interval_thinktime_random"
    vusers: 50
    #script_id: 392
    script_path: "scripts\\java_protocols\\JavaHTTP_BigXML"
    rts:
      pacing:
        number_of_iterations: 2
        type: "fixed interval"
        delay: 10
      java_vm:
        jdk_home: "C:\\Program Files\\Java\\jdk1.8.0_191"
        java_vm_parameters: "java_vm_parameters"
        enable_classloader_per_vuser: true
        java_env_class_paths:
          - "java_env_class_path1"
          - "java_env_class_path2"
      thinktime:
        type: "random"
        limit_seconds: 30
        min_percentage: 2
        max_percentage: 3

  - group_name: "JavaHTTP_BigXML_pacing_random_interval"
    vusers: 50
    script_path: "scripts\\java_protocols\\JavaHTTP_BigXML"
    rts:
      pacing:
        number_of_iterations: 2
        type: "random interval"
        delay: 10
        delay_random_range: 20
      java_vm:
        jdk_home: "C:\\Program Files\\Java\\jdk1.8.0_191"
        java_vm_parameters: "java_vm_parameters"
        enable_classloader_per_vuser: true
        java_env_class_paths:
          - "java_env_class_path1"
          - "java_env_class_path2"

  - group_name: "Mtours_pacing_random_interval"
    vusers: 50
    script_path: "scripts\\Mtours"
    rts:
      pacing:
        number_of_iterations: 2
        type: "random interval"
        delay: 10
        delay_random_range: 20
      jmeter:
        start_measurements: true
        jmeter_home_path: "c:\\jmeter"
        jmeter_min_port: 2001
        jmeter_max_port: 3001
        jmeter_additional_properties: "jmeter_additional_properties"
  - group_name: "Mtours_pacing_random_interval_Jmeter_default_port"
    vusers: 50
    script_path: "scripts\\Mtours"
    rts:
      pacing:
        number_of_iterations: 2
        type: "random interval"
        delay: 10
        delay_random_range: 20
      jmeter:
        start_measurements: true

scheduler:
  rampup: 120
  duration: 600
##################################################
</code>
</pre>
<p></p></div>

<ul><li><b>Values:</b> <code>YES</code>, <code>NO</code></li></ul></li>
<li><code>authenticateWithToken : boolean</code>
<div><div>
 <div>
  From LRE 2021 R1, you can use a token associated with your user for authentication.
 </div>
 <div>
  If LRE is defined to use SSO, this will be the only way for this plugin to authenticate to LRE.
 </div>
 <div>
  To use it, have a token issued to your user in LRE.
 </div>
 <div>
  In Jenkins, create new Jenkins credentials based on the LRE token you received: use the ClientIdKey in the Username and the ClientSecretKey key in the password.
 </div>
 <div>
  Then use the new Jenkins credentials with this checkbox switched on.
 </div>
</div></div>

</li>
</ul>


++++
=== `pcRunBuild`: Run Performance Test Using LoadRunner Enterprise
++++
<ul><li><code>serverAndPort : String</code>
</li>
<li><code>pcServerName : String</code>
<div><div>
 Hostname or IP address The LoadRunner Enterprise Hostname or IP address. If the port of the LRE server is different than the default one, mention it by adding a collon (:) and then the port number
 <br><b>Example</b>: mypcserver.mycompany.net or 182.138.255.1 or mypcserver.mycompany.net:81
 <br>
 <br>
  If the LRE server requires to be accessed via a tenant, you can specify it by adding the tenant details to the LRE Server field.
 <br><b>Example</b>: mypcserver.mycompany.net/?tenant=fa128c06-5436-413d-9cfa-9f04bb738df3 or 182.138.255.1/?tenant=fa128c06-5436-413d-9cfa-9f04bb738df3 or mypcserver.mycompany.net:81/?tenant=fa128c06-5436-413d-9cfa-9f04bb738df3
 <br>
 <br><b>Important</b>: Do not use the full URL of LoadRunner Enterprise server. 
 <br>
  For example, using https://mypcserver/LoadTest will fail. Instead, just specify 'mypcserver' value in 'LRE Server' field and switch on the 'Use HTTPS Protocol' if secured protocol is required.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 LoadRunner Enterprise User / Token's Credentials or parameter pointing to such credentials.
</div></div>

</li>
<li><code>almDomain : String</code>
</li>
<li><code>almProject : String</code>
</li>
<li><code>testToRun : String</code>
</li>
<li><code>testId : String</code>
</li>
<li><code>testContentToCreate : String</code>
<div><p></p>
<h1>How to create a test from YAML input</h1>
<p>The content of the field must either be:</p>
<ul>
 <li>Text in YAML syntax composed according to the parameters described in the tables below. You must set values to the 'test_name' and 'test_folder_path' parameters and continue with the'test_content' parameter and its sub-parameters.</li>
 <li>As opposed to the previous option, you can also specify as value a relative path to a YAML file within the workspace (or within your Git repository cloned within the workspace). In the YAML file, only specify the parameters defined in the 'test_content' table. The following logic will be used to create the LoadRunner Enterprise test: 
  <ul>
   <li>The file name (without extension) will be used as the test name.</li>
   <li>The location of the file in the Git repository will be the location of the test under the root folder ('Subject') in the <strong>Test Management</strong> tree.</li>
   <li>The content of the YAML file must consist of the parameters, and their sub-parameters, listed in the 'test_content' table below.</li>
  </ul></li>
</ul>
<p></p>
<p><strong>Note:</strong></p>
<ul>
 <li>All parameters must be in lowercase.</li>
 <li>When a backslash (\) occurs in a value provided to a parameter (for example, a folder separator in a file path), a double backslash (\\) must be used instead.</li>
 <li>This feature is supported with Performance Center 12.61 and later versions.</li>
</ul>
<p></p>
<p></p>
<div>
 Root parameters of the field 
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>test_name</td>
    <td>The test name.</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>test_folder_path</td>
    <td>The location of the test in the <strong>Test Management</strong> folder tree of the LoadRunner Enterprise project. The folders should be separated by double backslashes (\\). For example, "MyMainFolder\\MySubfolder\\MySubSubFolder". Do not include the LoadRunner Enterprise root folder (named "Subject")</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>test_content</td>
    <td>The content of the test that requires additional parameters specified in the 'test_content' table below.</td>
    <td>Yes</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>test_content (if a YAML file is specified in the field, those are the root parameter to be used in the file content):</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>controller</td>
    <td>
     <div>
      Defines the Controller to be used during the test run (it must be an available host in the LoadRunner Enterprise project). If not specified, a Controller will be chosen from the different controllers available in the LoadRunner Enterprise project.
     </div>
     <div>
      From Performance Center 12.62 and plugin version 1.1.1, the option to provision a Controller as a Docker image is available by specifying the value "Elastic" and providing a value for the 'controller_elastic_configuration' parameter (see 'controller_elastic_configuration' table below).
     </div></td>
    <td>No</td>
   </tr>
   <tr>
    <td>lg_amount</td>
    <td>Number of load generators to allocate to the test (every group in the test will be run by the same load generators).</td>
    <td>Not required if each group defined in the 'group' parameter defines the load generators it will be using via the 'lg_name' parameter (see 'group' table below).</td>
   </tr>
   <tr>
    <td>group</td>
    <td>Lists all groups or scripts defined in the test. The parameter to be used in each group are specified in the 'group' table below.</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>scheduler</td>
    <td>Defines the duration of a test, and determines whether virtual users are started simultaneously or gradually. See the 'scheduler' table below.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>lg_elastic_configuration</td>
    <td>Defines the image to be used in order to provision load generators. See the 'lg_elastic_configuration' table below. Available from Performance Center 12.62 and plugin version 1.1.1.</td>
    <td>Yes, if a load generator is defined to be provisioned from a Docker image.</td>
   </tr>
   <tr>
    <td>controller_elastic_configuration</td>
    <td>Defines the image to be used in order to provision the Controller. See the 'controller_elastic_configuration' table below. Available from Performance Center 12.62 and plugin version 1.1.1.</td>
    <td>Yes, if the Controller is defined to be provisioned from a Docker image.</td>
   </tr>
   <tr>
    <td>automatic_trending</td>
    <td>Defines association to existing trend report. If the parameter is not defined, the test will not be associated to any trend report.</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>group:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>group_name</td>
    <td>Name of the group (it must be a unique name if several groups are defined).</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>vusers</td>
    <td>Number of virtual users to allocate to the group for running the script.</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>script_id</td>
    <td>ID of the script in the LoadRunner Enterprise project.</td>
    <td>Not required if the 'script_path' parameter is specified.</td>
   </tr>
   <tr>
    <td>script_path</td>
    <td>Path and name of the script to be added to the group, separated by double backslashes (\\). For example "MyMainFolder\\MySubFolder\\MyScriptName'. Do not include the LoadRunner Enterprise root folder (named "Subject").</td>
    <td>Not required if 'script_id' parameter is specified</td>
   </tr>
   <tr>
    <td>lg_name</td>
    <td>List of load generators to allocate to the group for running the script. The supported values are: 
     <ul>
      <li>The hostname, as defined in LoadRunner Enterprise, of an existing load generator in LoadRunner Enterprise allocated as a host.</li>
      <li><strong>"LG"</strong> followed by a number, to use an automatically matched load generator (recommended).</li>
      <li><strong>"DOCKER"</strong> followed by a number, to use a dynamic load generator. Available from Performance Center 12.62, if your project is set to work with Docker. This option requires the 'lg_elastic_configuration' parameter to be defined (see the 'lg_elastic_configuration' table below).</li>
     </ul></td>
    <td>No</td>
   </tr>
   <tr>
    <td>command_line</td>
    <td>The command line applied to the group.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>rts</td>
    <td>Object defining the runtime settings of the script. See the 'rts' table below.</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>rts:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>pacing</td>
    <td>Can be used to define the number of iterations the script will run and the required delay between iterations (see the 'pacing' table below).</td>
    <td>No</td>
   </tr>
   <tr>
    <td>thinktime</td>
    <td>Can be used to define think time (see the 'thinktime' table below).</td>
    <td>No</td>
   </tr>
   <tr>
    <td>java_vm</td>
    <td>Can be used when defining Java environment runtime settings (see the 'java_vm' table below).</td>
    <td>No</td>
   </tr>
   <tr>
    <td>jmeter</td>
    <td>Can be used to define JMeter environment runtime settings (see the 'jmeter' table below).</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>pacing:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>number_of_iterations</td>
    <td>Specifies the number of iterations to run; this must be a positive number.</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>type</td>
    <td>Possible values for type attribute are: 
     <ul>
      <li><strong>"immediately"</strong>: ignores 'delay' and 'delay_random_range' parameters. This is the default value when no type is specified.</li>
      <li><strong>"fixed delay"</strong>: 'delay' parameter is mandatory.</li>
      <li><strong>"random delay"</strong>: 'delay' and 'delay_random_range' parameters are mandatory.</li>
      <li><strong>"fixed interval"</strong>: 'delay' parameter is mandatory.</li>
      <li><strong>"random interval"</strong>: 'delay' and 'delay_random_range' parameters are mandatory.</li>
     </ul></td>
    <td>No</td>
   </tr>
   <tr>
    <td>delay</td>
    <td>Non-negative number (less than 'delay_at_range_to_seconds' when specified).</td>
    <td>Depends on the value provided for the 'type' parameter.</td>
   </tr>
   <tr>
    <td>delay_random_range</td>
    <td>Non-negative number. It will be added to the value given to the 'delay' parameter (the value will be randomly chosen between the value given to 'delay' parameter and the same value to which is added the value of this parameter).</td>
    <td>Depends on the value provided for the 'type' parameter.</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>thinktime:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>type</td>
    <td>The ThinkTime Type attribute is one of: 
     <ul>
      <li><strong>"ignore"</strong>: This is the default value when no type is specified.</li>
      <li><strong>"replay"</strong>: Provide 'limit_seconds' parameter with value.</li>
      <li><strong>"modify"</strong>: Provide 'limit_seconds' and 'multiply_factor' parameters with values.</li>
      <li><strong>"random"</strong>: Provide 'limit_seconds', 'min_percentage' and 'max_percentage' parameters with values.</li>
     </ul></td>
    <td>No</td>
   </tr>
   <tr>
    <td>min_percentage</td>
    <td>This must be a positive number.</td>
    <td>Depends on the value provided for the 'type' parameter.</td>
   </tr>
   <tr>
    <td>max_percentage</td>
    <td>This must be a positive number (it must be larger than the value provided for the 'min_percentage' parameter).</td>
    <td>Depends on the value provided for the 'type' parameter.</td>
   </tr>
   <tr>
    <td>limit_seconds</td>
    <td>This must be a positive number.</td>
    <td>Depends on the value provided for the 'type' parameter.</td>
   </tr>
   <tr>
    <td>multiply_factor</td>
    <td>The recorded think time is multiplied by this factor at runtime.</td>
    <td>Depends on the value provided for the 'type' parameter.</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>java_vm:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>jdk_home</td>
    <td>The JDK installation path.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>java_vm_parameters</td>
    <td>List the Java command line parameters. These parameters can be any JVM argument. The common arguments are the debug flag (-verbose) or memory settings (-ms, -mx). In additional, you can also pass properties to Java applications in the form of a -D flag.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>use_xboot</td>
    <td>Boolean: Instructs VuGen to add the Classpath before the Xbootclasspath (prepend the string).</td>
    <td>No</td>
   </tr>
   <tr>
    <td>enable_classloader_per_vuser</td>
    <td>Boolean: Loads each Virtual User using a dedicated class loader (runs Vusers as threads).</td>
    <td>No</td>
   </tr>
   <tr>
    <td>java_env_class_paths</td>
    <td>A list of classpath entries. Use a double backslash (\\) for folder separators.</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>jmeter:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>start_measurements</td>
    <td>Boolean value to enable JMX measurements during performance test execution.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>jmeter_home_path</td>
    <td>Path to JMeter home. If not defined, the path from the %JMETER_HOME% environment variable is used.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>jmeter_min_port</td>
    <td>This number must be lower than the value provided in the 'jmeter_max_port' parameter. Both 'jmeter_min_port' and 'jmeter_max_port' parameters must be specified otherwise the default port values is used.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>jmeter_max_port</td>
    <td>This number must be higher than the value provided in the 'jmeter_min_port' parameter. Both 'jmeter_min_port' and 'jmeter_max_port' parameters must be specified otherwise the default port values is used.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>jmeter_additional_properties</td>
    <td>JMeter additional properties file. Use double slash (\\) for folder separator.</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>scheduler:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>rampup</td>
    <td>Time, in seconds, to gradually start all virtual users. Additional virtual users are added every 15 seconds until the time specified in the parameter ends. If no value is specified, all virtual users are started simultaneously at the beginning of the test.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>duration</td>
    <td>Time, in seconds, that it will take to run the test after all virtual users are started. After this time, the test run ends. If not specified, the test will run until completion.</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>automatic_trending:</strong>
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>report_id</td>
    <td>Id of the trend report to associate the test run analysis with.</td>
    <td>No</td>
   </tr>
   <tr>
    <td>max_runs_in_report</td>
    <td>Maximum trends in a report (default is 10 if not specified).</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>lg_elastic_configuration:</strong> (available from Performance Center 12.62 and plugin version 1.1.1)
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>image_id</td>
    <td>This number can be retrieved from: 
     <ul>
      <li>The Administration page of LoadRunner Enterprise (you might need to turn to your LoadRunner Enterprise administrator as accessing this page requires admin privileges): select the <strong>Orchestration</strong> section -&gt; switch to <strong>Docker Images</strong> tab -&gt; you will have the list of all available Docker images for Load Generator purposes with their ID. You can make sure the images are available to your project from the <strong>Orchestrators</strong> tab.</li>
      <li>A LoadRunner Enterprise Rest API command applied on the project (replace the bracketed values): GET - <a rel="nofollow">http(s)://(PCServer):(PortNumber)/LoadTest/rest/domains/(DomainName)/projects/(ProjectName)/dockerimages/</a> and select any valid image not having the value 'controller' for purpose.</li>
     </ul></td>
    <td>Yes if one of the load generator is defined to be provisioned from Docker image.</td>
   </tr>
   <tr>
    <td>memory_limit</td>
    <td>This parameter can be retrieved from <strong>LoadRunner Enterprise Application</strong> -&gt; <strong>Test Management</strong> -&gt; edit a test -&gt; Press <strong>Assign LG</strong> button -&gt; in the <strong>Elastic</strong> section, select <strong>DOCKER1<strong> -&gt; select the relevant image (based on the image name) -&gt; use the values provided in the 'Memory(GB)' dropdown list (if not specified, this parameter should be ignored).</strong></strong></td>
    <td>Yes, if the image is defined with resource limits</td>
   </tr>
   <tr>
    <td>cpu_limit</td>
    <td>This parameter can be retrieved from <strong>LoadRunner Enterprise Application</strong> -&gt; <strong>Test Management</strong> -&gt; edit a test -&gt; Press <strong>Assign LG</strong> button -&gt; in the <strong>Elastic</strong> section, select <strong>DOCKER1<strong> -&gt; select the relevant image (based on the image name) -&gt; use the values provided in the 'CUPs' dropdown list (if not specified, this parameter should be ignored).</strong></strong></td>
    <td>Yes, if the image is defined with resource limits</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 <strong>controller_elastic_configuration:</strong> (available from Performance Center 12.62 and plugin version 1.1.1)
</div>
<div>
 <table>
  <tbody>
   <tr>
    <th>Parameter</th>
    <th>Description</th>
    <th>Required</th>
   </tr>
   <tr>
    <td>image_id</td>
    <td>This number can be retrieved from: 
     <ul>
      <li>The Administration page of LoadRunner Enterprise (you might need to turn to your LoadRunner Enterprise administrator as accessing this page requires admin privileges): select the <strong>Orchestration</strong> section -&gt; switch to <strong>Docker Images</strong> tab -&gt; you will have the list of all available Docker images for Controller purposes with their ID. You can make sure the images are available to your project from the <strong>Orchestrators</strong> tab.</li>
      <li>A LoadRunner Enterprise Rest API command applied on the project (replace the bracketed values): GET - <a rel="nofollow">http(s)://(PCServer):(PortNumber)/LoadTest/rest/domains/(DomainName)/projects/(ProjectName)/dockerimages/</a> and select any valid image having the value 'controller' for purpose.</li>
     </ul></td>
    <td>Yes if the Controller is defined to be provisioned from Docker image.</td>
   </tr>
   <tr>
    <td>memory_limit</td>
    <td>This parameter can be retrieved from <strong>LoadRunner Enterprise Application</strong> -&gt; <strong>Test Management</strong> -&gt; edit a test -&gt; select the Controller -&gt; choose <strong>Elastic</strong> option -&gt; select the relevant image -&gt; Under the <strong>Resource Limits</strong> label, find and use the values provided in the 'Memory(GB)' dropdown list (if not specified, this parameter should be ignored).</td>
    <td>Yes, if the image is defined with resource limits</td>
   </tr>
   <tr>
    <td>cpu_limit</td>
    <td>This parameter can be retrieved from <strong>LoadRunner Enterprise Application</strong> -&gt; <strong>Test Management</strong> -&gt; edit a test -&gt; select the Controller -&gt; choose <strong>Elastic</strong> option -&gt; select the relevant image -&gt; Under the <strong>Resource Limits</strong> label, find and use the values provided in the 'CUPs' dropdown list (if not specified, this parameter should be ignored).</td>
    <td>Yes, if the image is defined with resource limits</td>
   </tr>
  </tbody>
 </table>
</div>
<p></p>
<p></p>
<div>
 In the next example, the value of the field is set with the code below: 
 <ul>
  <li>The test name is "mytestname" and it will be placed in the LoadRunner Enterprise project under the folder path "Subject\\Tests\\mytests" (the root folder of the folders, which is "Subject", should not be specified in the parameter). The folder separator is a double backslash (\\).</li>
  <li>In the content: 
   <ul>
    <li>Since no Controller or load generator amount were specified, a random available Controller will be used to run the test, and the 'lg_name' parameter specified in each group will be used.</li>
    <li>In the 'group' parameter: 
     <ul>
      <li>We added two scripts. For each, we provided a unique value in the 'group_name' parameter, and the number of virtual users to run the group.</li>
      <li>Since we did not know the ID of the scripts, we used the 'script_path' parameter in which we entered the script path (without "Subject") followed by the script name, and used double backslashes for separators.</li>
      <li>We specified the load generators that will be used by each group (in this case, load generators will automatically be matched as we use the 'LG' prefix).</li>
     </ul></li>
   </ul></li>
  <li>In the scheduler: 
   <ul>
    <li>We want all Virtual Users to be initialized gradually (45 seconds).</li>
    <li>We want the test to stop after 5 minutes (300 seconds).</li>
   </ul></li>
 </ul>
</div>
<pre>
<code>
##################################################
test_name: mytestname
test_folder_path: "Tests\\mytests"
test_content:
  group:
    - group_name: "TEstInt"
      vusers: '20'
      script_path: "plugin\\TEstInt"
      lg_name:
        - "LG1"
        - "LG2"
    - group_name: "Mtours"
      vusers: '20'
      script_path: "plugin\\mtours"
      lg_name:
        - "LG3"
        - "LG4"
  scheduler:
    rampup: '45'
    duration: '300'
##################################################
</code>
</pre>
<p></p>
<p></p>
<div>
 In the next example, a YAML file location is specified as value and the content of the file contains the code below: 
 <ul>
  <li>The plugin automatically assigns the file name as the test name, and the folder path of the file in the Git repository is used to create the location of the test under the root folder ('Subject') in the LoadRunner Enterprise project.</li>
  <li>In the content: 
   <ul>
    <li>Since no Controller or load generator amount were specified, a random available Controller will be used to run the test, and the 'lg_name' parameter specified in each group will be used.</li>
    <li>In the 'group' parameter: 
     <ul>
      <li>We added two scripts. For each, we provided a unique value in the 'group_name' parameter, and the number of virtual users to run the group.</li>
      <li>Since we did not know the ID of the scripts, we used the 'script_path' parameter in which we entered the script path (without "Subject") followed by the script name, and used double backslashes for separators.</li>
      <li>We specified the load generators that will be used by each group (in this case, load generators will automatically be matched as we use the 'LG' prefix).</li>
     </ul></li>
   </ul></li>
  <li>In the scheduler: 
   <ul>
    <li>We want all Virtual Users to be initialized gradually (45 seconds).</li>
    <li>We want the test to stop after 5 minutes (300 seconds).</li>
   </ul></li>
 </ul>
</div>
<pre>
<code>
##################################################
group:
  - group_name: "TEstInt"
    vusers: '20'
    script_path: "plugin\\TEstInt"
    lg_name:
      - "LG1"
      - "LG2"
  - group_name: "Mtours"
    vusers: '20'
    script_path: "plugin\\mtours"
    lg_name:
      - "LG3"
      - "LG4"
scheduler:
  rampup: '45'
  duration: '300'
##################################################
</code>
</pre>
<p></p>
<p></p>
<div>
 In the next example, a YAML file location is specified as value and the content of the file contains the code below: 
 <ul>
  <li>The plugin automatically assigns the file name as the test name, and the folder path of the file in the Git repository is used to create the location of the test under the root folder ('Subject') in the LoadRunner Enterprise project.</li>
  <li>Since the 'controller' parameter and the 'lg_amount' parameter are specified, the specified controller will be used to run the test and three automatch load generators will be used and shared by all groups.</li>
  <li>The content of the file is defined with seven groups, all being set with the “rts” parameter: 
   <ul>
    <li>The “pacing” parameter is used with different options for all groups.</li>
    <li>The “java_vm” parameter is used for five scripts with JavaVM for protocol.</li>
    <li>The “thinktime” parameter is used with different options for four groups.</li>
    <li>The “jmeter” parameter is used for two scripts with JMeter for protocol.</li>
   </ul></li>
  <li>In the scheduler: 
   <ul>
    <li>We want all Virtual Users to be initialized gradually (120 seconds).</li>
    <li>We want the test to stop after 10 minutes (600 seconds).</li>
   </ul></li>
 </ul>
</div>
<pre>
<code>
##################################################
controller: "mycontroller"
lg_amount: 3
group:
  - group_name: "JavaVuser_LR_Information_pacing_immediately_thinktime_ignore"
    vusers: 50
    script_id: 394
    rts:
      pacing:
        number_of_iterations: 2
        type: "immediately"
      java_vm:
        jdk_home: "C:\\Program Files\\Java\\jdk1.8.0_191"
        java_vm_parameters: "java_vm_parameters"
        enable_classloader_per_vuser: true
        use_xboot: true
        java_env_class_paths:
          - "java_env_class_path1"
          - "java_env_class_path2"
      thinktime:
        type: "ignore"

  - group_name: "JavaHTTP_BigXML_pacing_fixed_delay_thinktime_replay"
    vusers: 50
    script_path: "scripts\\java_protocols\\JavaHTTP_BigXML"
    rts:
      pacing:
        number_of_iterations: 2
        type: "fixed delay"
        delay: 10
      java_vm:
        jdk_home: "C:\\Program Files\\Java\\jdk1.8.0_191"
        java_vm_parameters: "java_vm_parameters"
        enable_classloader_per_vuser: true
      thinktime:
        type: "replay"
        limit_seconds: 30

  - group_name: "JavaVuser_LR_Information_immediately_pacing_random_delay_thinktime_modify"
    vusers: 50
    script_id: 394
    rts:
      pacing:
        number_of_iterations: 2
        type: "random delay"
        delay: 10
        delay_random_range: 20
      java_vm:
        jdk_home: "C:\\Program Files\\Java\\jdk1.8.0_191"
        java_vm_parameters: "java_vm_parameters"
        enable_classloader_per_vuser: true
        java_env_class_paths:
          - "java_env_class_path1"
          - "java_env_class_path2"
      thinktime:
        type: "modify"
        limit_seconds: 30
        multiply_factor: 2

  - group_name: "JavaHTTP_BigXML_pacing_fixed_interval_thinktime_random"
    vusers: 50
    #script_id: 392
    script_path: "scripts\\java_protocols\\JavaHTTP_BigXML"
    rts:
      pacing:
        number_of_iterations: 2
        type: "fixed interval"
        delay: 10
      java_vm:
        jdk_home: "C:\\Program Files\\Java\\jdk1.8.0_191"
        java_vm_parameters: "java_vm_parameters"
        enable_classloader_per_vuser: true
        java_env_class_paths:
          - "java_env_class_path1"
          - "java_env_class_path2"
      thinktime:
        type: "random"
        limit_seconds: 30
        min_percentage: 2
        max_percentage: 3

  - group_name: "JavaHTTP_BigXML_pacing_random_interval"
    vusers: 50
    script_path: "scripts\\java_protocols\\JavaHTTP_BigXML"
    rts:
      pacing:
        number_of_iterations: 2
        type: "random interval"
        delay: 10
        delay_random_range: 20
      java_vm:
        jdk_home: "C:\\Program Files\\Java\\jdk1.8.0_191"
        java_vm_parameters: "java_vm_parameters"
        enable_classloader_per_vuser: true
        java_env_class_paths:
          - "java_env_class_path1"
          - "java_env_class_path2"

  - group_name: "Mtours_pacing_random_interval"
    vusers: 50
    script_path: "scripts\\Mtours"
    rts:
      pacing:
        number_of_iterations: 2
        type: "random interval"
        delay: 10
        delay_random_range: 20
      jmeter:
        start_measurements: true
        jmeter_home_path: "c:\\jmeter"
        jmeter_min_port: 2001
        jmeter_max_port: 3001
        jmeter_additional_properties: "jmeter_additional_properties"
  - group_name: "Mtours_pacing_random_interval_Jmeter_default_port"
    vusers: 50
    script_path: "scripts\\Mtours"
    rts:
      pacing:
        number_of_iterations: 2
        type: "random interval"
        delay: 10
        delay_random_range: 20
      jmeter:
        start_measurements: true

scheduler:
  rampup: 120
  duration: 600
##################################################
</code>
</pre>
<p></p></div>

</li>
<li><code>testInstanceId : String</code>
<div><div>
 Represents an instance of a performance test within an ALM Test Set. In order to find the test instance id go to: <b>LoadRunner Enterprise Application &gt; Test Lab perspective &gt; Performance Test Set table</b> and look for the ID column
</div></div>

</li>
<li><code>autoTestInstanceID : String</code>
</li>
<li><code>timeslotDurationHours : String</code>
</li>
<li><code>timeslotDurationMinutes : String</code>
</li>
<li><code>postRunAction</code>
<ul><li><b>Values:</b> <code>COLLATE</code>, <code>COLLATE_AND_ANALYZE</code>, <code>DO_NOTHING</code></li></ul></li>
<li><code>vudsMode : boolean</code>
<div><div>
 A <b>Virtual User Day (VUD)</b> license provides you with a specified number of Vusers (VUDs) that you can run an unlimited number of times within a 24 hour period. Before using this option, make sure that VUDs licenses are applied in your OpenText LoadRunner Enterprise environment.
</div></div>

</li>
<li><code>statusBySLA : boolean</code>
<div><div>
 Check this option in order to set the build-step status according to a pre-defined <b>SLA (Service Level Agreement)</b> configured within your performance test. Unless checked, the build-step will be labeled as <i>Passed</i> as long as no failures occurred.
</div></div>

</li>
<li><code>description : String</code>
</li>
<li><code>addRunToTrendReport : String</code>
</li>
<li><code>trendReportId : String</code>
</li>
<li><code>HTTPSProtocol : boolean</code>
</li>
<li><code>proxyOutURL : String</code>
<div><div>
 Add your local proxy as following: <b>http(s)://host:port</b>
 <br>
  or Leave empty if not using a local proxy. The following proxy configurations are not supported: 
 <ul>
  <li>PAC (proxy auto-config).</li>
  <li>Automatic configuration script.</li>
 </ul>
</div></div>

</li>
<li><code>credentialsProxyId : String</code>
</li>
<li><code>retry : String</code>
</li>
<li><code>retryDelay : String</code>
</li>
<li><code>retryOccurrences : String</code>
</li>
<li><code>trendReportWaitTime : String</code>
<div><div>
 Even though the trend report is shown in LoadRunner Enterprise as ready for download, additional wait time might be required until the report is complete. You can set a wait time between 0 and 300 seconds. <b>Tip</b>: We recommend using '0' (the default setting) which means no wait time. If the trend report displays partial data only, increase to 10 seconds, and wait for the next build. Repeat as necessary until the report contains all the transaction information.
</div></div>

</li>
<li><code>authenticateWithToken : boolean</code>
<div><div>
 <div>
  From LRE 2021 R1, you can use a token associated with your user for authentication.
 </div>
 <div>
  If LRE is defined to use SSO, this will be the only way for this plugin to authenticate to LRE.
 </div>
 <div>
  To use it, have a token issued to your user in LRE.
 </div>
 <div>
  In Jenkins, create new Jenkins credentials based on the LRE token you received: use the ClientIdKey in the Username and the ClientSecretKey key in the password.
 </div>
 <div>
  Then use the new Jenkins credentials with this checkbox switched on.
 </div>
</div></div>

</li>
<li><code>searchTimeslot : boolean</code>
<div><div>
 <div>
  Use this option to search for an opened timeslot related to the test and use it to execute the test.
 </div>
</div></div>

</li>
</ul>


++++
