= Minio Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/minio">Visit the Jenkins Plugins site</a>
++++


=== `minio`: Upload build artifacts to Minio
++++
<ul><li><code>bucket : String</code>
<div><div>
 The bucket to upload the files to. This bucket will be created if it does not yet exist. Please note the <a href="https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html" rel="nofollow">restrictions in bucket naming</a>
</div></div>

</li>
<li><code>includes : String</code>
<div><div>
 File pattern to indicate which files will be uploaded. Multiple entries can be used when separated by a ","
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 Credentials to use when authenticating to Minio. If host is left blank the global configured credentials will be used
</div></div>

</li>
<li><code>excludes : String</code> (optional)
</li>
<li><code>host : String</code> (optional)
<div><div>
 URL where Minio is reachable by Jenkins. Leave this blank to use global configuration
</div></div>

</li>
<li><code>targetFolder : String</code> (optional)
<div><div>
 If you want to store the artifacts in a specific folder in Minio you can specify it with this parameter. Environment variables can be used with the ${...} syntax.
</div></div>

</li>
</ul>


++++
=== `minioDelete`: Delete build artifacts from Minio
++++
<ul><li><code>bucket : String</code>
<div><div>
 The bucket to download the files from. An error will be thrown if this bucket does not exist.
</div></div>

</li>
<li><code>files : String</code>
<div><div>
 Indicates what files should be deleted in Minio. Environment variables can be used with the ${...} syntax. Multiple files can be separated using ",".
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 Credentials to use when authenticating to Minio. If host is left blank the global configured credentials will be used
</div></div>

</li>
<li><code>failOnNonExisting : boolean</code> (optional)
<div><div>
 By default the plugin will not error out if it tries to delete a file that doesn't exist.
</div></div>

</li>
<li><code>host : String</code> (optional)
<div><div>
 URL where Minio is reachable by Jenkins. Leave this blank to use global configuration
</div></div>

</li>
</ul>


++++
=== `minioDownload`: Download files from Minio
++++
<ul><li><code>bucket : String</code>
<div><div>
 The bucket to download the files from. An error will be thrown if this bucket does not exist.
</div></div>

</li>
<li><code>file : String</code>
<div><div>
 Indicates what file should be downloaded. Environment variables can be used with the ${...} syntax.
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 Credentials to use when authenticating to Minio. If host is left blank the global configured credentials will be used
</div></div>

</li>
<li><code>excludes : String</code> (optional)
</li>
<li><code>failOnNonExisting : boolean</code> (optional)
<div><div>
 Uncheck this if you want the build to continue when a non-existing file is encountered.
</div></div>

</li>
<li><code>host : String</code> (optional)
<div><div>
 URL where Minio is reachable by Jenkins. Leave this blank to use global configuration
</div></div>

</li>
<li><code>targetFolder : String</code> (optional)
<div><div>
 Optionally indicate what directory in your workspace the objects should be downloaded to. Environment variables can be used with the ${...} syntax.
</div></div>

</li>
</ul>


++++
