= MISRA Compliance Report Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/misra-compliance-report-generator">Visit the Jenkins Plugins site</a>
++++


=== `misraReport`: Build MISRA Guideline Compliance Summary (GCS)
++++
<ul><li><code>doFailOnError : boolean</code> (optional)
<div>Fail the build if the plugin could not create a valid MISRA Guideline Compliance Summary.</div>

</li>
<li><code>doFailOnIncompliance : boolean</code> (optional)
<div>Fail the build if the result of the Guideline Compliance Report is that the code is not MISRA-compliant.</div>

</li>
<li><code>grpFile : String</code> (optional)
<div><p>A simple text file containing the guideline re-categorization plan (GRP) - see "MISRA Compliance 2016". Leave empty to not re-categorize any rules. Rules that are not recategorized do not need to appear in this listing.</p>
<p>The format of the text file should be: <br>
  [Guideline], [New compliance level] <br>
  Example: <br>
  Directive 1.1, Mandatory<br>
  Rule 11.2, Mandatory<br>
  Rule 12.1, Required<br>
  Rule 12.2, Disapplied</p></div>

</li>
<li><code>logFile : String</code> (optional)
<div>The log file will list all the tags discovered in the code. The file can be parsed by a warning parser. A typical use would be to automatically add comments or review tasks to a pull request. The output format is the same as the clang compiler.</div>

</li>
<li><code>nonMisraTagPattern : String</code> (optional)
</li>
<li><code>projectName : String</code> (optional)
<div>Project name to be shown in the report</div>

</li>
<li><code>ruleSet : String</code> (optional)
<div>Select the version of MISRA guidelines to be applied</div>

</li>
<li><code>softwareVersion : String</code> (optional)
<div>The software version to show in the report. Usually you would use an environment variable which has been set by one of the earlier build steps here, e. g. ${SOFTWARE_VERSION}</div>

</li>
<li><code>sourceListFile : String</code> (optional)
<div>A file containing a list of source code and header files separated by newlines. These files will be checked for suppressing comments and tags.</div>

</li>
<li><code>warningParser : String</code> (optional)
<div>Select the tool used to check for code compliance.</div>

</li>
<li><code>warningsFile : String</code> (optional)
<div>File that contains warnings produced by the warning parser.</div>

</li>
</ul>


++++
