= NeoLoad Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/neoload-jenkins-plugin">Visit the Jenkins Plugins site</a>
++++


=== `neoloadRefreshTrends`: Refresh NeoLoad Trends
++++
<ul><li><code>graphOptionsInfo</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>curve</code>
<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
</li>
</ul></li>
<li><code>statistic : String</code>
</li>
</ul></li>
<li><code>maxTrends : int</code> (optional)
</li>
<li><code>showTrendAverageResponse : boolean</code> (optional)
</li>
<li><code>showTrendErrorRate : boolean</code> (optional)
</li>
</ul>


++++
=== `neoloadRun`: Run a NeoLoad scenario
++++
<div><div>
 This build step executes a NeoLoad scenario and adds trend result graphs to the job page.
</div></div>
<ul><li><code>scenarioName : String</code> (optional)
<div><div>
 The name of the Scenario to launch.
</div></div>

</li>
<li><code>autoArchive : boolean</code> (optional)
</li>
<li><code>customCommandLineOptions : String</code> (optional)
<div><div>
 Include any additional Command Line options here.
</div></div>

</li>
<li><code>displayGUI : boolean</code> (optional)
</li>
<li><code>executable : String</code> (optional)
<div><div>
 This is the absolute path to the NeoLoad executable file. 
 <br>
  For example,<code>/opt/NeoLoad 6.5/bin/NeoLoadCmd</code>, <code>C:\Program Files\NeoLoad 6.5\bin\NeoLoadCmd.exe</code> or <code>/Applications/NeoLoad 6.5/bin/NeoLoadCmd</code>.
</div></div>

</li>
<li><code>graphOptionsInfo</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>curve</code>
<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
</li>
</ul></li>
<li><code>statistic : String</code>
</li>
</ul></li>
<li><code>htmlReport : String</code> (optional)
<div><div>
 This is the path where the HTLM report file is created by NeoLoad. 
 <br>
  For example, <code>${WORKSPACE}/neoload-report/report.html</code>.
</div></div>

</li>
<li><code>junitReport : String</code> (optional)
<div><div>
 This is the path where the JUnit results file (based on an SLA in NeoLoad) is created. 
 <br>
  For example, <code>${WORKSPACE}/neoload-report/junit-sla-results.xml</code>.
</div></div>

</li>
<li><code>licenseDuration : String</code> (optional)
<div><div>
 This is the number of hours to reserve the license. This must be at least as long as the test will last.
</div></div>

</li>
<li><code>licenseServer</code> (optional)
<div><div>
 Choose which server to use to lease the license. If no servers appear, please configure one in the System Configuration screen of Jenkins.
</div></div>

<ul><b>Nested Object</b>
<li><code>uniqueID : String</code>
</li>
<li><code>url : String</code>
</li>
<li><code>loginUser : String</code>
</li>
<li><code>loginPassword</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>label : String</code>
</li>
<li><code>collabPath : String</code>
</li>
<li><code>licenseID : String</code>
</li>
</ul></li>
<li><code>licenseType : String</code> (optional)
</li>
<li><code>licenseVUCount : String</code> (optional)
<div><div>
 This is the number of Virtual Users (User Paths) to reserve with the license.
</div></div>

</li>
<li><code>licenseVUSAPCount : String</code> (optional)
<div><div>
 This is the number of SAP Virtual Users (User Paths for SAP) to reserve with the license.
</div></div>

</li>
<li><code>localProjectFile : String</code> (optional)
<div><div>
 This is the local project file path. 
 <br>
  For example,<code>/home/ajohnson/neoload_projects/JenkinsExample/JenkinsExample.nlp</code>, <code>C:\neoload_projects\JenkinsExample\JenkinsExample.nlp</code> or <code>/Users/ajohnson/neoload_projects/JenkinsExample/JenkinsExample.nlp</code> or <code>/Users/ajohnson/neoload_projects/JenkinsExample/JenkinsExample.yaml</code>.
</div></div>

</li>
<li><code>maxTrends : int</code> (optional)
<div><div>
 Limit the number of points in trend charts. You can use 0 value to have unlimited charts
</div></div>

</li>
<li><code>pdfReport : String</code> (optional)
<div><div>
 This is the path where the PDF report file is created. 
 <br>
  For example, <code>${WORKSPACE}/neoload-report/report.pdf</code>.
</div></div>

</li>
<li><code>projectType : String</code> (optional)
</li>
<li><code>publishTestResults : boolean</code> (optional)
<div><div>
 When selected, test results are published after the scenario is run.
</div></div>

</li>
<li><code>reportType : String</code> (optional)
</li>
<li><code>sharedProjectName : String</code> (optional)
<div><div>
 This is the name of the shared project to checkout and load. 
 <br>
  For example, <code>MyProjectName</code>.
</div></div>

</li>
<li><code>sharedProjectServer</code> (optional)
<div><div>
 Choose which server to use. If no servers appear, please configure one in the System Configuration screen of Jenkins.
</div></div>

<ul><b>Nested Object</b>
<li><code>uniqueID : String</code>
</li>
<li><code>url : String</code>
</li>
<li><code>loginUser : String</code>
</li>
<li><code>loginPassword</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>label : String</code>
</li>
</ul></li>
<li><code>showTrendAverageResponse : boolean</code> (optional)
<div><div>
 When selected, a trend graph of the average response time for all pages is displayed. Note that the build artifacts must include XML results from NeoLoad for the graph to be displayed.
</div></div>

</li>
<li><code>showTrendErrorRate : boolean</code> (optional)
<div><div>
 When selected, a trend graph of the error rate of the most recent runs is included on the job page. Note that the build artifacts must include XML results from NeoLoad for the graph to be displayed.
</div></div>

</li>
<li><code>testDescription : String</code> (optional)
<div><div>
 The test description entered here appears in the report file.
</div></div>

</li>
<li><code>testResultName : String</code> (optional)
<div><div>
 This is the name of the test results. The value <code>$Date{hh:mm - dd MMM yyyy}</code> is replaced by the current date by NeoLoad and the value <code>${BUILD_NUMBER}</code> is replaced by the current build number by Jenkins.
 <br>
  For example, <code>$Date{hh:mm - dd MMM yyyy} (build $${BUILD_NUMBER})</code>.
</div></div>

</li>
<li><code>xmlReport : String</code> (optional)
<div><div>
 This is the path where the XML report file is created. 
 <br>
  For example, <code>${WORKSPACE}/neoload-report/report.xml</code>.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'NeoBuildAction'])`: Execute a NeoLoad Scenario
++++
<div><div>
 This build step executes a NeoLoad scenario and adds trend result graphs to the job page.
</div></div>
<ul><li><code>executable : String</code>
<div><div>
 This is the absolute path to the NeoLoad executable file. 
 <br>
  For example,<code>/opt/NeoLoad 6.5/bin/NeoLoadCmd</code>, <code>C:\Program Files\NeoLoad 6.5\bin\NeoLoadCmd.exe</code> or <code>/Applications/NeoLoad 6.5/bin/NeoLoadCmd</code>.
</div></div>

</li>
<li><code>projectType : String</code>
</li>
<li><code>reportType : String</code>
</li>
<li><code>localProjectFile : String</code>
<div><div>
 This is the local project file path. 
 <br>
  For example,<code>/home/ajohnson/neoload_projects/JenkinsExample/JenkinsExample.nlp</code>, <code>C:\neoload_projects\JenkinsExample\JenkinsExample.nlp</code> or <code>/Users/ajohnson/neoload_projects/JenkinsExample/JenkinsExample.nlp</code> or <code>C:\neoload_projects\JenkinsExample\JenkinsExample.yaml</code>.
</div></div>

</li>
<li><code>sharedProjectName : String</code>
<div><div>
 This is the name of the shared project to checkout and load. 
 <br>
  For example, <code>MyProjectName</code>.
</div></div>

</li>
<li><code>scenarioName : String</code>
<div><div>
 The name of the Scenario to launch.
</div></div>

</li>
<li><code>htmlReport : String</code>
<div><div>
 This is the path where the HTLM report file is created by NeoLoad. 
 <br>
  For example, <code>${WORKSPACE}/neoload-report/report.html</code>.
</div></div>

</li>
<li><code>xmlReport : String</code>
<div><div>
 This is the path where the XML report file is created. 
 <br>
  For example, <code>${WORKSPACE}/neoload-report/report.xml</code>.
</div></div>

</li>
<li><code>pdfReport : String</code>
<div><div>
 This is the path where the PDF report file is created. 
 <br>
  For example, <code>${WORKSPACE}/neoload-report/report.pdf</code>.
</div></div>

</li>
<li><code>junitReport : String</code>
<div><div>
 This is the path where the JUnit results file (based on an SLA in NeoLoad) is created. 
 <br>
  For example, <code>${WORKSPACE}/neoload-report/junit-sla-results.xml</code>.
</div></div>

</li>
<li><code>scanAllBuilds : boolean</code>
</li>
<li><code>displayTheGUI : boolean</code>
<div><div>
 When selected, then the NeoLoad GUI is displayed during the test. Note that the user launching the process must be able to display a user interface (which is not always the case for the Jenkins user). Note also that some errors or warning messages may prevent NeoLoad from closing automatically at the end of a test run. Thus this should only be used for testing purposes.
</div></div>

</li>
<li><code>testResultName : String</code>
<div><div>
 This is the name of the test results. The value <code>$Date{hh:mm - dd MMM yyyy}</code> is replaced by the current date by NeoLoad and the value <code>${BUILD_NUMBER}</code> is replaced by the current build number by Jenkins.
 <br>
  For example, <code>$Date{hh:mm - dd MMM yyyy} (build $${BUILD_NUMBER})</code>.
</div></div>

</li>
<li><code>testDescription : String</code>
<div><div>
 The test description entered here appears in the report file.
</div></div>

</li>
<li><code>licenseType : String</code>
</li>
<li><code>licenseVUCount : String</code>
<div><div>
 This is the number of Virtual Users (User Paths) to reserve with the license.
</div></div>

</li>
<li><code>licenseVUSAPCount : String</code>
<div><div>
 This is the number of SAP Virtual Users (User Paths for SAP) to reserve with the license.
</div></div>

</li>
<li><code>licenseDuration : String</code>
<div><div>
 This is the number of hours to reserve the license. This must be at least as long as the test will last.
</div></div>

</li>
<li><code>customCommandLineOptions : String</code>
<div><div>
 Include any additional Command Line options here.
</div></div>

</li>
<li><code>publishTestResults : boolean</code>
<div><div>
 When selected, test results are published after the scenario is run.
</div></div>

</li>
<li><code>sharedProjectServer</code>
<div><div>
 Choose which server to use. If no servers appear, please configure one in the System Configuration screen of Jenkins.
</div></div>

<ul><b>Nested Object</b>
<li><code>uniqueID : String</code>
</li>
<li><code>url : String</code>
</li>
<li><code>loginUser : String</code>
</li>
<li><code>loginPassword</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>label : String</code>
</li>
</ul></li>
<li><code>licenseServer</code>
<div><div>
 Choose which server to use to lease the license. If no servers appear, please configure one in the System Configuration screen of Jenkins.
</div></div>

<ul><b>Nested Object</b>
<li><code>uniqueID : String</code>
</li>
<li><code>url : String</code>
</li>
<li><code>loginUser : String</code>
</li>
<li><code>loginPassword</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>label : String</code>
</li>
<li><code>collabPath : String</code>
</li>
<li><code>licenseID : String</code>
</li>
</ul></li>
<li><code>showTrendAverageResponse : boolean</code>
<div><div>
 When selected, a trend graph of the average response time for all pages is displayed. Note that the build artifacts must include XML results from NeoLoad for the graph to be displayed.
</div></div>

</li>
<li><code>showTrendErrorRate : boolean</code>
<div><div>
 When selected, a trend graph of the error rate of the most recent runs is included on the job page. Note that the build artifacts must include XML results from NeoLoad for the graph to be displayed.
</div></div>

</li>
<li><code>graphOptionsInfo</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>curve</code>
<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
</li>
</ul></li>
<li><code>statistic : String</code>
</li>
</ul></li>
<li><code>maxTrends : int</code>
<div><div>
 Limit the number of points in trend charts. You can use 0 value to have unlimited charts
</div></div>

</li>
</ul>


++++
