= Nexus Artifact Uploader
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/nexus-artifact-uploader">Visit the Jenkins Plugins site</a>
++++


=== `nexusArtifactUploader`: Nexus Artifact Uploader
++++
<ul><li><code>nexusVersion : String</code>
</li>
<li><code>protocol : String</code>
</li>
<li><code>nexusUrl : String</code>
<div><div>
 If Nexus Url is <em>http://mynexusrepo:8081/nexus</em> the value for this field is <em>mynexusrepo:8081/nexus</em>
</div></div>

</li>
<li><code>groupId : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>repository : String</code>
<div><div>
 RepositoryId of the Repository in Nexus to which this artifact to be uploaded.
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
<li><code>artifacts</code>
<ul><b>Array / List of Nested Object</b>
<li><code>artifactId : String</code>
</li>
<li><code>type : String</code>
<div><div>
 Extension of the artifact for ex: artifact file name is <em>artifact.zip</em> the extension is <em>zip</em>.
</div></div>

</li>
<li><code>classifier : String</code>
<div><div>
 Classifier of the artifact.
</div></div>

</li>
<li><code>file : String</code>
<div><div>
 File path in the workspace. ex:<em>artifact.zip or artifact.jar</em>
</div></div>

</li>
</ul></li>
</ul>


++++
=== `step([$class: 'NexusArtifactUploader'])`: Nexus artifact uploader
++++
<ul><li><code>nexusVersion : String</code>
</li>
<li><code>protocol : String</code>
</li>
<li><code>nexusUrl : String</code>
<div><div>
 If Nexus Url is <em>http://mynexusrepo:8081/nexus</em> the value for this field is <em>mynexusrepo:8081/nexus</em>
</div></div>

</li>
<li><code>groupId : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>repository : String</code>
<div><div>
 RepositoryId of the Repository in Nexus to which this artifact to be uploaded.
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
<li><code>artifacts</code>
<ul><b>Array / List of Nested Object</b>
<li><code>artifactId : String</code>
</li>
<li><code>type : String</code>
<div><div>
 Extension of the artifact for ex: artifact file name is <em>artifact.zip</em> the extension is <em>zip</em>.
</div></div>

</li>
<li><code>classifier : String</code>
<div><div>
 Classifier of the artifact.
</div></div>

</li>
<li><code>file : String</code>
<div><div>
 File path in the workspace. ex:<em>artifact.zip or artifact.jar</em>
</div></div>

</li>
</ul></li>
</ul>


++++
