= NowSecure Auto Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/nowsecure-auto-security-test">Visit the Jenkins Plugins site</a>
++++


=== `apiKey`: NowSecure Auto Security Test
++++
<ul><li><code>validateDnsUrlConnection : boolean</code>
</li>
<li><code>apiUrl : String</code> (optional)
<div><div>
 The Base URL of the NowSecure API, by default this is https://lab-api.nowsecure.com. For Enterprise installs, this URL will differ.
</div></div>

</li>
<li><code>group : String</code> (optional)
<div><div>
 Specify group-id where the app belongs
</div></div>

</li>
<li><code>binaryName : String</code> (optional)
<div><div>
 Specify the filename of Android or iOS application, only apk and ipa formats are supported respectively. You can specify filename if it was generated by a previous step and is stored under the artifacts directory or the full path of the file.
</div></div>

</li>
<li><code>description : String</code> (optional)
<div><div>
 Specify description of this step
</div></div>

</li>
<li><code>waitForResults : boolean</code> (optional)
<div><div>
 Check this option if you would like to wait until security analysis is completed. This step would fail if any critical errors are found.
</div></div>

</li>
<li><code>waitMinutes : int</code> (optional)
<div><div>
 Specify, in minutes, how long this step should wait for results. If analysis takes longer than this limit, the step would timeout.
</div></div>

</li>
<li><code>breakBuildOnScore : boolean</code> (optional)
<div><div>
 Break the build when the application's security score is lower then the defined threshold.
</div></div>

</li>
<li><code>scoreThreshold : int</code> (optional)
<div><div>
 Specify a number between 1 and 100, 1 being the lower and 100 being the highest, to act as a threshold for breaking builds.
</div></div>

</li>
<li><code>apiKey : String</code> (optional)
<div><div>
 The API Key is used to authenticate against the NowSecure Auto API. See https://docs.nowsecure.com/auto/integration-services/jenkins-integration/ for instructions on generating an API Key.
</div></div>

</li>
<li><code>useBuildEndpoint : boolean</code> (optional)
</li>
<li><code>artifactsDir : String</code> (optional)
</li>
<li><code>debug : boolean</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>proxyEnabled : boolean</code> (optional)
</li>
<li><code>showStatusMessages : boolean</code> (optional)
<div><div>
 Specify if status messages for automation testing should be displayed
</div></div>

</li>
<li><code>stopTestsForStatusMessage : String</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
<li><code>validateDnsUrlConnectionEnabled : boolean</code> (optional)
<div><div>
 Check this option if you would like to validate DNS and URL access for NowSecure API
</div></div>

</li>
</ul>


++++
