= 1Password Secrets
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/onepassword-secrets">Visit the Jenkins Plugins site</a>
++++


=== `withSecrets`: 1Password Secrets
++++
<ul><li><code>config</code> (optional)
<ul><b>Nested Object</b>
<li><code>connectCredential</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'EksTokenCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>clusterName : String</code>
</li>
<li><code>region : String</code>
</li>
<li><code>awsCredentialsId : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'FileSystemServiceAccountCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
</ul></div></li>
<li><code>idToken</code><div>
<div><div>
 Supplies an OpenID Connect id token (JWT) with claims about the current build.
</div></div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>audience : String</code> (optional)
<div><div>
 Optional audience claim for the id token.
</div></div>

</li>
<li><code>issuer : String</code> (optional)
<div><div>
 Alternate issuer URL. If specified, you must be prepared to serve <code>.well-known/openid-configuration</code> and <code>jwks</code> from that location as <code>application/json</code> documents. Jenkins will continue to maintain the private key, but beware that unauthorized modification of either document could allow id tokens to be forged.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretPersonalAccessTokenCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as plain text.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretSSHUserPrivateKeyCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as yaml. The following is an example</p>
 <pre>        username: jenkins
        passphrase:
        privateKey: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEAnWLC5QGdQNii4oDosvY5hXEGOGQXFsw1YFMkyG+xY5kUIxc3
          :
          :
          BZC5SbkVLUxtoPubf2op4lJoxbBX4p0qcA8Iu6HVJFDkWhPvuH7O5g==
          -----END RSA PRIVATE KEY-----
    </pre>
 <p>The following example uses the az-cli to load a yaml file as a secret into an Azure Keyvault</p>
 <pre>    az keyvault secret --vault-name jenkins --name ssh-cred --file ssh-cred.yaml
    </pre>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretStringCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as plain text.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretUsernamePasswordCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as yaml. The following is an example</p>
 <pre>        username: jenkins
        password: P@ssword
    </pre>
 <p>The following example uses the az-cli to load a yaml file as a secret into an Azure Keyvault</p>
 <pre>    az keyvault secret --vault-name jenkins --name jenkins-cred --file jenkins-cred.yaml
    </pre>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'StringCredentialsImpl'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>secret</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'VaultStringCredentialImpl'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>engineVersion : int</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the secret resides in. Leave blank if namespaces are not enabled or the secret is part of the root namespace. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>path : String</code> (optional)
<div><div>
 The Vault secret path. Example "<code>kv/eng/apikey/google</code>".
</div></div>

</li>
<li><code>prefixPath : String</code> (optional)
<div><div>
 The secret engine prefix path. Use this to identify the path the secret engine (i.e. <code>kv</code>) is mounted to if it is not mounted at the root. 
 <p>For example if the secret path is "<code>team1/kv/database</code>" the prefix path would be "<code>team1/kv</code>". If the secret path is "<code>kv/database</code>" the prefix path can be left blank.</p>
</div></div>

</li>
<li><code>vaultKey : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>connectCredentialId : String</code> (optional)
<div><div>
 A secret text credential that contains the 1Password Connect Token
</div></div>

</li>
<li><code>connectHost : String</code> (optional)
<div><div>
 Host where Connect is deployed
</div></div>

</li>
<li><code>opCLIPath : String</code> (optional)
<div><div>
 Path to the 1Password CLI
</div></div>

</li>
<li><code>serviceAccountCredential</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'EksTokenCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>clusterName : String</code>
</li>
<li><code>region : String</code>
</li>
<li><code>awsCredentialsId : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'FileSystemServiceAccountCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
</ul></div></li>
<li><code>idToken</code><div>
<div><div>
 Supplies an OpenID Connect id token (JWT) with claims about the current build.
</div></div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>audience : String</code> (optional)
<div><div>
 Optional audience claim for the id token.
</div></div>

</li>
<li><code>issuer : String</code> (optional)
<div><div>
 Alternate issuer URL. If specified, you must be prepared to serve <code>.well-known/openid-configuration</code> and <code>jwks</code> from that location as <code>application/json</code> documents. Jenkins will continue to maintain the private key, but beware that unauthorized modification of either document could allow id tokens to be forged.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretPersonalAccessTokenCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as plain text.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretSSHUserPrivateKeyCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as yaml. The following is an example</p>
 <pre>        username: jenkins
        passphrase:
        privateKey: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEAnWLC5QGdQNii4oDosvY5hXEGOGQXFsw1YFMkyG+xY5kUIxc3
          :
          :
          BZC5SbkVLUxtoPubf2op4lJoxbBX4p0qcA8Iu6HVJFDkWhPvuH7O5g==
          -----END RSA PRIVATE KEY-----
    </pre>
 <p>The following example uses the az-cli to load a yaml file as a secret into an Azure Keyvault</p>
 <pre>    az keyvault secret --vault-name jenkins --name ssh-cred --file ssh-cred.yaml
    </pre>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretStringCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as plain text.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretUsernamePasswordCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as yaml. The following is an example</p>
 <pre>        username: jenkins
        password: P@ssword
    </pre>
 <p>The following example uses the az-cli to load a yaml file as a secret into an Azure Keyvault</p>
 <pre>    az keyvault secret --vault-name jenkins --name jenkins-cred --file jenkins-cred.yaml
    </pre>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'StringCredentialsImpl'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>secret</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'VaultStringCredentialImpl'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>engineVersion : int</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the secret resides in. Leave blank if namespaces are not enabled or the secret is part of the root namespace. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>path : String</code> (optional)
<div><div>
 The Vault secret path. Example "<code>kv/eng/apikey/google</code>".
</div></div>

</li>
<li><code>prefixPath : String</code> (optional)
<div><div>
 The secret engine prefix path. Use this to identify the path the secret engine (i.e. <code>kv</code>) is mounted to if it is not mounted at the root. 
 <p>For example if the secret path is "<code>team1/kv/database</code>" the prefix path would be "<code>team1/kv</code>". If the secret path is "<code>kv/database</code>" the prefix path can be left blank.</p>
</div></div>

</li>
<li><code>vaultKey : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>serviceAccountCredentialId : String</code> (optional)
<div><div>
 A secret text credential that contains the Service Account Authorization Token.
</div></div>

</li>
</ul></li>
<li><code>secrets</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>envVar : String</code>
<div><div>
 The environment variable that will contain the loaded secret
</div></div>

</li>
<li><code>secretRef : String</code>
<div><div>
 The reference to the secret (has the format "op://vault/item/[section/]field")
</div></div>

</li>
</ul></li>
</ul>


++++
=== `wrap([$class: 'OnePasswordBuildWrapper'])`: 1Password Secrets
++++
<ul><li><code>config</code> (optional)
<ul><b>Nested Object</b>
<li><code>connectCredential</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'EksTokenCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>clusterName : String</code>
</li>
<li><code>region : String</code>
</li>
<li><code>awsCredentialsId : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'FileSystemServiceAccountCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
</ul></div></li>
<li><code>idToken</code><div>
<div><div>
 Supplies an OpenID Connect id token (JWT) with claims about the current build.
</div></div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>audience : String</code> (optional)
<div><div>
 Optional audience claim for the id token.
</div></div>

</li>
<li><code>issuer : String</code> (optional)
<div><div>
 Alternate issuer URL. If specified, you must be prepared to serve <code>.well-known/openid-configuration</code> and <code>jwks</code> from that location as <code>application/json</code> documents. Jenkins will continue to maintain the private key, but beware that unauthorized modification of either document could allow id tokens to be forged.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretPersonalAccessTokenCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as plain text.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretSSHUserPrivateKeyCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as yaml. The following is an example</p>
 <pre>        username: jenkins
        passphrase:
        privateKey: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEAnWLC5QGdQNii4oDosvY5hXEGOGQXFsw1YFMkyG+xY5kUIxc3
          :
          :
          BZC5SbkVLUxtoPubf2op4lJoxbBX4p0qcA8Iu6HVJFDkWhPvuH7O5g==
          -----END RSA PRIVATE KEY-----
    </pre>
 <p>The following example uses the az-cli to load a yaml file as a secret into an Azure Keyvault</p>
 <pre>    az keyvault secret --vault-name jenkins --name ssh-cred --file ssh-cred.yaml
    </pre>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretStringCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as plain text.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretUsernamePasswordCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as yaml. The following is an example</p>
 <pre>        username: jenkins
        password: P@ssword
    </pre>
 <p>The following example uses the az-cli to load a yaml file as a secret into an Azure Keyvault</p>
 <pre>    az keyvault secret --vault-name jenkins --name jenkins-cred --file jenkins-cred.yaml
    </pre>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'StringCredentialsImpl'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>secret</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'VaultStringCredentialImpl'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>engineVersion : int</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the secret resides in. Leave blank if namespaces are not enabled or the secret is part of the root namespace. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>path : String</code> (optional)
<div><div>
 The Vault secret path. Example "<code>kv/eng/apikey/google</code>".
</div></div>

</li>
<li><code>prefixPath : String</code> (optional)
<div><div>
 The secret engine prefix path. Use this to identify the path the secret engine (i.e. <code>kv</code>) is mounted to if it is not mounted at the root. 
 <p>For example if the secret path is "<code>team1/kv/database</code>" the prefix path would be "<code>team1/kv</code>". If the secret path is "<code>kv/database</code>" the prefix path can be left blank.</p>
</div></div>

</li>
<li><code>vaultKey : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>connectCredentialId : String</code> (optional)
<div><div>
 A secret text credential that contains the 1Password Connect Token
</div></div>

</li>
<li><code>connectHost : String</code> (optional)
<div><div>
 Host where Connect is deployed
</div></div>

</li>
<li><code>opCLIPath : String</code> (optional)
<div><div>
 Path to the 1Password CLI
</div></div>

</li>
<li><code>serviceAccountCredential</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'EksTokenCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>clusterName : String</code>
</li>
<li><code>region : String</code>
</li>
<li><code>awsCredentialsId : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'FileSystemServiceAccountCredential'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
</ul></div></li>
<li><code>idToken</code><div>
<div><div>
 Supplies an OpenID Connect id token (JWT) with claims about the current build.
</div></div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>audience : String</code> (optional)
<div><div>
 Optional audience claim for the id token.
</div></div>

</li>
<li><code>issuer : String</code> (optional)
<div><div>
 Alternate issuer URL. If specified, you must be prepared to serve <code>.well-known/openid-configuration</code> and <code>jwks</code> from that location as <code>application/json</code> documents. Jenkins will continue to maintain the private key, but beware that unauthorized modification of either document could allow id tokens to be forged.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretPersonalAccessTokenCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as plain text.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretSSHUserPrivateKeyCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as yaml. The following is an example</p>
 <pre>        username: jenkins
        passphrase:
        privateKey: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEAnWLC5QGdQNii4oDosvY5hXEGOGQXFsw1YFMkyG+xY5kUIxc3
          :
          :
          BZC5SbkVLUxtoPubf2op4lJoxbBX4p0qcA8Iu6HVJFDkWhPvuH7O5g==
          -----END RSA PRIVATE KEY-----
    </pre>
 <p>The following example uses the az-cli to load a yaml file as a secret into an Azure Keyvault</p>
 <pre>    az keyvault secret --vault-name jenkins --name ssh-cred --file ssh-cred.yaml
    </pre>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretStringCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as plain text.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SecretUsernamePasswordCredentials'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>servicePrincipalId : String</code>
<div><div>
 The Azure Service Principal credentials used to communicate with the Azure services. Check the following documentation for more information about the service principal: 
 <ul>
  <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal" rel="nofollow"> Use portal to create an Azure Active Directory application and service principal that can access resources </a></li>
 </ul>
</div></div>

</li>
<li><code>secretIdentifier : String</code>
<div><div>
 <p>Secret identifier can be found on Azure Portal.</p>
 <p>Secret value will be interpreted as yaml. The following is an example</p>
 <pre>        username: jenkins
        password: P@ssword
    </pre>
 <p>The following example uses the az-cli to load a yaml file as a secret into an Azure Keyvault</p>
 <pre>    az keyvault secret --vault-name jenkins --name jenkins-cred --file jenkins-cred.yaml
    </pre>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'StringCredentialsImpl'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>secret</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'VaultStringCredentialImpl'</code><div>
<ul><li><code>scope</code>
<div><div>
 Determines where this credential can be used. 
 <dl>
  <dt>
   System
  </dt>
  <dd>
   This credential is only available to the object on which the credential is associated. Typically you would use system-scoped credentials for things like email auth, agent connection, etc, i.e. where the Jenkins instance itself is using the credential. Unlike the global scope, this significantly restricts where the credential can be used, thereby providing a higher degree of confidentiality to the credential.
  </dd>
  <dt>
   Global
  </dt>
  <dd>
   This credential is available to the object on which the credential is associated and all objects that are children of that object. Typically you would use global-scoped credentials for things that are needed by jobs.
  </dd>
 </dl>
 <p>In general, a credential is defined in one place (e.g., the credentials configuration page under "Manage Jenkins") and then used in another place (e.g., when connecting to a new SSH build agent). The scope allows you to say "this credential is only used by these places" by looking at the relationship between the two locations.</p>
</div></div>

<ul><li><b>Values:</b> <code>SYSTEM</code>, <code>GLOBAL</code>, <code>USER</code></li></ul></li>
<li><code>id : String</code>
<div><div>
 An internal unique ID by which these credentials are identified from jobs and other configuration. Normally left blank, in which case an ID will be generated, which is fine for jobs created using visual forms. Useful to specify explicitly when using credentials from scripted configuration.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 An optional description to help tell similar credentials apart.
</div></div>

</li>
<li><code>engineVersion : int</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
<div><div>
 The <a href="https://www.vaultproject.io/docs/enterprise/namespaces" rel="nofollow">Vault Namespace</a> the secret resides in. Leave blank if namespaces are not enabled or the secret is part of the root namespace. 
 <p><strong>Note:</strong> Namespaces are a feature of Vault Enterprise.</p>
</div></div>

</li>
<li><code>path : String</code> (optional)
<div><div>
 The Vault secret path. Example "<code>kv/eng/apikey/google</code>".
</div></div>

</li>
<li><code>prefixPath : String</code> (optional)
<div><div>
 The secret engine prefix path. Use this to identify the path the secret engine (i.e. <code>kv</code>) is mounted to if it is not mounted at the root. 
 <p>For example if the secret path is "<code>team1/kv/database</code>" the prefix path would be "<code>team1/kv</code>". If the secret path is "<code>kv/database</code>" the prefix path can be left blank.</p>
</div></div>

</li>
<li><code>vaultKey : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>serviceAccountCredentialId : String</code> (optional)
<div><div>
 A secret text credential that contains the Service Account Authorization Token.
</div></div>

</li>
</ul></li>
<li><code>secrets</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>envVar : String</code>
<div><div>
 The environment variable that will contain the loaded secret
</div></div>

</li>
<li><code>secretRef : String</code>
<div><div>
 The reference to the secret (has the format "op://vault/item/[section/]field")
</div></div>

</li>
</ul></li>
</ul>


++++
