= ontrack Jenkins plug-in
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/ontrack">Visit the Jenkins Plugins site</a>
++++


=== `ontrackBranchName`: Transforms a branch name, as provided by the pipeline for example, into a name suitable for a branch in Ontrack.
++++
<ul><li><code>branch : String</code>
</li>
<li><code>branchReplacement : String</code> (optional)
</li>
</ul>


++++
=== `ontrackBranchSetup`: Setup an Ontrack branch, and creates it if it does not exist.
++++
<ul><li><code>project : String</code>
</li>
<li><code>branch : String</code>
</li>
<li><code>script : String</code>
</li>
<li><code>bindings</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.Object&gt;</code></li>
</ul></li>
<li><code>logging : boolean</code> (optional)
</li>
</ul>


++++
=== `ontrackBuild`: Creates an Ontrack build
++++
<ul><li><code>project : String</code>
</li>
<li><code>branch : String</code>
</li>
<li><code>build : String</code>
</li>
<li><code>gitCommit : String</code> (optional)
</li>
</ul>


++++
=== `ontrackGraphQL`: Runs some Ontrack GraphQL script
++++
<ul><li><code>script : String</code>
</li>
<li><code>bindings</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.Object&gt;</code></li>
</ul></li>
</ul>


++++
=== `ontrackProjectSetup`: Setup an Ontrack project, and creates it if it does not exist.
++++
<ul><li><code>project : String</code>
</li>
<li><code>script : String</code>
</li>
<li><code>bindings</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.Object&gt;</code></li>
</ul></li>
<li><code>logging : boolean</code> (optional)
</li>
</ul>


++++
=== `ontrackPromote`: Promotes an Ontrack build
++++
<ul><li><code>project : String</code>
</li>
<li><code>branch : String</code>
</li>
<li><code>build : String</code>
</li>
<li><code>promotionLevel : String</code>
</li>
</ul>


++++
=== `ontrackScript`: Runs some Ontrack DSL script
++++
<ul><li><code>script : String</code>
</li>
<li><code>bindings</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.Object&gt;</code></li>
</ul></li>
<li><code>logging : boolean</code> (optional)
</li>
</ul>


++++
=== `ontrackValidate`: Validates an Ontrack build
++++
<ul><li><code>project : String</code>
</li>
<li><code>branch : String</code>
</li>
<li><code>build : String</code>
</li>
<li><code>validationStamp : String</code>
</li>
<li><code>buildResult : String</code> (optional)
</li>
<li><code>data</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, ?&gt;</code></li>
</ul></li>
<li><code>dataType : String</code> (optional)
</li>
<li><code>dataValidation : boolean</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>testResults</code> (optional)
<ul><li><b>Type:</b> <code>class hudson.tasks.junit.TestResultSummary</code></li>
</ul></li>
<li><code>testResultsAsFraction : boolean</code> (optional)
</li>
<li><code>validationStatus : String</code> (optional)
</li>
</ul>


++++
