= OpenShift Pipeline Jenkins Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/openshift-pipeline">Visit the Jenkins Plugins site</a>
++++


=== `openshiftBuild`: Trigger OpenShift Build
++++
<ul><li><code>bldCfg : String</code>
<div><div>
 If you run `oc get bc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>buildName : String</code> (optional)
<div><div>
 The value here is what you supply with the --from-build option when invoking the OpenShift `oc start-build` command. It allows you to point to OpenShift build to a previously run build, and run another build with exactly the same source and destination metadata. If you do not supply a value, the plugin will generate a new OpenShift build based on the Build Configuration referenced.
</div></div>

</li>
<li><code>checkForTriggeredDeployments : String</code> (optional)
<div><div>
 This flag is the toggle for turning on or off the verification that any deployments triggered by this build's output fired.
</div></div>

</li>
<li><code>commitID : String</code> (optional)
<div><div>
 The value here is what you supply with the --commit option when invoking the OpenShift `oc start-build` command. It allows you to point the OpenShift build to a specific commit hash from the git-log of the source repository. If you do not supply a value, the plugin assumes the latest version from the source repository should be used.
</div></div>

</li>
<li><code>env</code> (optional)
<div><div>
 Specify a list of environment variables to include in the build (see `oc start-build -e ...`).
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
<div><div>
 The name of the environment variable to set.
</div></div>

</li>
<li><code>value : String</code>
<div><div>
 The value for the environment variable.
</div></div>

</li>
</ul></li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>showBuildLogs : String</code> (optional)
<div><div>
 Indicates whether the build logs get dumped to the console of the Jenkins build.
</div></div>

</li>
<li><code>verbose : String</code> (optional)
</li>
<li><code>waitTime : String</code> (optional)
</li>
<li><code>waitUnit : String</code> (optional)
</li>
</ul>


++++
=== `openshiftCreateResource`: Create OpenShift Resource(s)
++++
<ul><li><code>jsonyaml : String</code>
<div><div>
 The JSON or YAML formatted text that conforms to the schema for defining the various OpenShift resources.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
</ul>


++++
=== `openshiftDeleteResourceByJsonYaml`: Delete OpenShift Resource(s) from JSON or YAML
++++
<ul><li><code>jsonyaml : String</code>
<div><div>
 The JSON or YAML formatted text that conforms to the schema for defining the various OpenShift resources.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
</ul>


++++
=== `openshiftDeleteResourceByKey`: Delete OpenShift Resource(s) by Key
++++
<ul><li><code>types : String</code>
<div><div>
 The comma separated list of types of API objects to delete. See https://docs.openshift.org/latest/rest_api/index.html for the supported types.
</div></div>

</li>
<li><code>keys : String</code>
<div><div>
 The comma separated list of keys of the API objects to delete.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
</ul>


++++
=== `openshiftDeleteResourceByLabels`: Delete OpenShift Resource(s) using Labels
++++
<ul><li><code>types : String</code>
<div><div>
 The comma separated list of types of API objects to delete, where those objects have labels corresponding to the specified key/value pairs. See https://docs.openshift.org/latest/rest_api/index.html for the supported types.
</div></div>

</li>
<li><code>keys : String</code>
<div><div>
 The comma separated list of keys of the labels in the API objects to delete.
</div></div>

</li>
<li><code>values : String</code>
<div><div>
 The comma separated list of values of the labels in the API objects to delete.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
</ul>


++++
=== `openshiftDeploy`: Trigger OpenShift Deployment
++++
<ul><li><code>depCfg : String</code>
<div><div>
 If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
<li><code>waitTime : String</code> (optional)
</li>
<li><code>waitUnit : String</code> (optional)
</li>
</ul>


++++
=== `openshiftExec`: OpenShift Exec
++++
<ul><li><code>pod : String</code>
<div><div>
 The pod in which to execute a command.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>arguments</code> (optional)
<div><div>
 Specify a list of arguments to pass to the command.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
<div><div>
 The value for the environment variable.
</div></div>

</li>
</ul></li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>command : String</code> (optional)
<div><div>
 The name of the command to execute.
</div></div>

</li>
<li><code>container : String</code> (optional)
<div><div>
 The container in which to execute a command. If not specified, the first container in the pod will be used.
</div></div>

</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
<li><code>waitTime : String</code> (optional)
</li>
<li><code>waitUnit : String</code> (optional)
</li>
</ul>


++++
=== `openshiftImageStream`: OpenShift ImageStreams
++++
<ul><li><code>name : String</code> (optional)
<div><div>
 The name of the ImageStream is what shows up in the NAME column if you dump all the ImageStream's with the `oc get is` command invocation.
</div></div>

</li>
<li><code>tag : String</code> (optional)
<div><div>
 The specific image tag within the ImageStream to monitor.
</div></div>

</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>changelog : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in changelog': 
 <p>If 'Include in changelog' is enabled for an SCM source, then when a build occurs, the changes from that SCM source will be included in the changelog.</p>
 <p>If 'Include in changelog' is disabled, then when a build occurs, the changes from this SCM source will not be included in the changelog.</p>
</div></div>

</li>
<li><code>poll : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in polling' 
 <p>If 'Include in polling' is enabled or 'Include in changelog' is enabled, then when polling occurs, the job will be started if changes are detected from this SCM source.</p>
 <p>If 'Include in polling' is disabled and 'Include in changelog' is disabled, then when polling occurs, changes that are detected from this repository will be ignored.</p>
</div></div>

</li>
<li><code>verbose : String</code> (optional)
</li>
</ul>


++++
=== `openshiftScale`: Scale OpenShift Deployment
++++
<ul><li><code>depCfg : String</code>
<div><div>
 If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>replicaCount : String</code>
<div><div>
 The value here should be the number of started pods desired for the deployment specified. It is the equivalent of the value supplied to --replicas with an `oc scale` command invocation. This is a required parameter. If an integer is not specified here, this build step can not be added to the job. Note: specifying a 0 is allowed, and means you do not want any pods for the specified deployment config running.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
<li><code>verifyReplicaCount : String</code> (optional)
<div><div>
 This flag is the toggle for turning on or off the verification that the specified replica count for the deployment has been reached.
</div></div>

</li>
<li><code>waitTime : String</code> (optional)
</li>
<li><code>waitUnit : String</code> (optional)
</li>
</ul>


++++
=== `openshiftTag`: Tag OpenShift Image
++++
<ul><li><code>srcStream : String</code>
<div><div>
 The name of the ImageStream for the existing tag.
</div></div>

</li>
<li><code>srcTag : String</code>
<div><div>
 The name of the existing tag, or an actual, existing image ID. The image referenced will have the new tag applied to it.
</div></div>

</li>
<li><code>destStream : String</code>
<div><div>
 One or more ImageStream names in a comma delimited list. If multiple streams and multiple destination tags are specified, the two lists must contain the same number of elements.
</div></div>

</li>
<li><code>destTag : String</code>
<div><div>
 One or more tag names in a comma delimited list. If multiple streams and multiple destination tags are specified, the two lists must contain the same number of elements.
</div></div>

</li>
<li><code>alias : String</code> (optional)
<div><div>
 This flag is the equivalent of the `--alias` option for the `oc tag` command. When false, the destination tag type is "ImageStreamImage", and when true, the destination tag type is "ImageStreamTag".
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>destinationAuthToken : String</code> (optional)
<div><div>
 The value here is what you supply with the --token option when invoking the OpenShift `oc` command. If you do not supply a value, the plugin will assume it is running in the OpenShift Jenkins image and attempt to load the kubernetes service account token stored in that image.
</div></div>

</li>
<li><code>destinationNamespace : String</code> (optional)
<div><div>
 The value here should match the value from the output from `oc project` if you created the resources related to this task from the command line. If nothing is specified, the plugin will inspect the PROJECT_NAME environment variable.
</div></div>

</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
</ul>


++++
=== `openshiftVerifyBuild`: Verify OpenShift Build
++++
<ul><li><code>bldCfg : String</code>
<div><div>
 If you run `oc get bc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>checkForTriggeredDeployments : String</code> (optional)
<div><div>
 This flag is the toggle for turning on or off the verification that any deployments triggered by this build's output fired.
</div></div>

</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
<li><code>waitTime : String</code> (optional)
</li>
<li><code>waitUnit : String</code> (optional)
</li>
</ul>


++++
=== `openshiftVerifyDeployment`: Verify OpenShift Deployment
++++
<ul><li><code>depCfg : String</code>
<div><div>
 If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>replicaCount : String</code> (optional)
<div><div>
 This optional field's value represents the number expected running pods for the deployment for the DeploymentConfig specified. If no value is specified it will work the number of running pods against the desired replica count in the DeploymentConfig.
</div></div>

</li>
<li><code>verbose : String</code> (optional)
</li>
<li><code>verifyReplicaCount : String</code> (optional)
<div><div>
 This flag is the toggle for turning on or off the verification that the specified replica count for the deployment has been reached.
</div></div>

</li>
<li><code>waitTime : String</code> (optional)
</li>
<li><code>waitUnit : String</code> (optional)
</li>
</ul>


++++
=== `openshiftVerifyService`: Verify OpenShift Service
++++
<ul><li><code>svcName : String</code>
<div><div>
 The equivalent to the name supplied to a `oc get service` command line invocation.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>retryCount : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'OpenShiftBuildCanceller'])`: Cancel OpenShift Builds
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>namespace : String</code>
</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>bldCfg : String</code>
<div><div>
 If you run `oc get bc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'OpenShiftDeployCanceller'])`: Cancel OpenShift Deployment
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>depCfg : String</code>
<div><div>
 If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>namespace : String</code>
</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
</ul>


++++
=== `step([$class: 'OpenShiftScalerPostAction'])`: Scale OpenShift Deployment
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>depCfg : String</code>
<div><div>
 If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>namespace : String</code>
</li>
<li><code>replicaCount : String</code>
<div><div>
 The value here should be the number of started pods desired for the deployment specified. It is the equivalent of the value supplied to --replicas with an `oc scale` command invocation. This is a required parameter. If an integer is not specified here, this build step can not be added to the job. Note: specifying a 0 is allowed, and means you do not want any pods for the specified deployment config running.
</div></div>

</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>verifyReplicaCount : String</code>
<div><div>
 This flag is the toggle for turning on or off the verification that the specified replica count for the deployment has been reached.
</div></div>

</li>
<li><code>waitTime : String</code>
</li>
<li><code>waitUnit : String</code>
</li>
</ul>


++++
=== `step([$class: 'OpenShiftBuildVerifier'])`: Verify OpenShift Build
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>bldCfg : String</code>
<div><div>
 If you run `oc get bc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>namespace : String</code>
</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>checkForTriggeredDeployments : String</code>
<div><div>
 This flag is the toggle for turning on or off the verification that any deployments triggered by this build's output fired.
</div></div>

</li>
<li><code>waitTime : String</code>
</li>
<li><code>waitUnit : String</code>
</li>
</ul>


++++
=== `step([$class: 'OpenShiftBuilder'])`: Trigger OpenShift Build
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>bldCfg : String</code>
<div><div>
 If you run `oc get bc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>namespace : String</code>
</li>
<li><code>env</code>
<div><div>
 Specify a list of environment variables to include in the build (see `oc start-build -e ...`).
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
<div><div>
 The name of the environment variable to set.
</div></div>

</li>
<li><code>value : String</code>
<div><div>
 The value for the environment variable.
</div></div>

</li>
</ul></li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>commitID : String</code>
<div><div>
 The value here is what you supply with the --commit option when invoking the OpenShift `oc start-build` command. It allows you to point the OpenShift build to a specific commit hash from the git-log of the source repository. If you do not supply a value, the plugin assumes the latest version from the source repository should be used.
</div></div>

</li>
<li><code>buildName : String</code>
<div><div>
 The value here is what you supply with the --from-build option when invoking the OpenShift `oc start-build` command. It allows you to point to OpenShift build to a previously run build, and run another build with exactly the same source and destination metadata. If you do not supply a value, the plugin will generate a new OpenShift build based on the Build Configuration referenced.
</div></div>

</li>
<li><code>showBuildLogs : String</code>
<div><div>
 Indicates whether the build logs get dumped to the console of the Jenkins build.
</div></div>

</li>
<li><code>checkForTriggeredDeployments : String</code>
<div><div>
 This flag is the toggle for turning on or off the verification that any deployments triggered by this build's output fired.
</div></div>

</li>
<li><code>waitTime : String</code>
</li>
<li><code>waitUnit : String</code>
</li>
</ul>


++++
=== `step([$class: 'OpenShiftCreator'])`: Create OpenShift Resource(s)
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>namespace : String</code>
</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>jsonyaml : String</code>
<div><div>
 The JSON or YAML formatted text that conforms to the schema for defining the various OpenShift resources.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'OpenShiftDeleterJsonYaml'])`: Delete OpenShift Resource(s) from JSON or YAML
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>namespace : String</code>
</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>jsonyaml : String</code>
<div><div>
 The JSON or YAML formatted text that conforms to the schema for defining the various OpenShift resources.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'OpenShiftDeleterLabels'])`: Delete OpenShift Resource(s) using Labels
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>namespace : String</code>
</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>types : String</code>
<div><div>
 The comma separated list of types of API objects to delete, where those objects have labels corresponding to the specified key/value pairs. See https://docs.openshift.org/latest/rest_api/index.html for the supported types.
</div></div>

</li>
<li><code>keys : String</code>
<div><div>
 The comma separated list of keys of the labels in the API objects to delete.
</div></div>

</li>
<li><code>values : String</code>
<div><div>
 The comma separated list of values of the labels in the API objects to delete.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'OpenShiftDeleterList'])`: Delete OpenShift Resource(s) by Key
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>namespace : String</code>
</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>types : String</code>
<div><div>
 The comma separated list of types of API objects to delete. See https://docs.openshift.org/latest/rest_api/index.html for the supported types.
</div></div>

</li>
<li><code>keys : String</code>
<div><div>
 The comma separated list of keys of the API objects to delete.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'OpenShiftDeployer'])`: Trigger OpenShift Deployment
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>depCfg : String</code>
<div><div>
 If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>namespace : String</code>
</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>waitTime : String</code>
</li>
<li><code>waitUnit : String</code>
</li>
</ul>


++++
=== `step([$class: 'OpenShiftDeploymentVerifier'])`: Verify OpenShift Deployment
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>depCfg : String</code>
<div><div>
 If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>namespace : String</code>
</li>
<li><code>replicaCount : String</code>
<div><div>
 This optional field's value represents the number expected running pods for the deployment for the DeploymentConfig specified. If no value is specified it will work the number of running pods against the desired replica count in the DeploymentConfig.
</div></div>

</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>verifyReplicaCount : String</code>
<div><div>
 This flag is the toggle for turning on or off the verification that the specified replica count for the deployment has been reached.
</div></div>

</li>
<li><code>waitTime : String</code>
</li>
<li><code>waitUnit : String</code>
</li>
</ul>


++++
=== `step([$class: 'OpenShiftExec'])`: OpenShift Exec
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>namespace : String</code>
</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>pod : String</code>
<div><div>
 The pod in which to execute a command.
</div></div>

</li>
<li><code>container : String</code>
<div><div>
 The container in which to execute a command. If not specified, the first container in the pod will be used.
</div></div>

</li>
<li><code>command : String</code>
<div><div>
 The name of the command to execute.
</div></div>

</li>
<li><code>arguments</code>
<div><div>
 Specify a list of arguments to pass to the command.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
<div><div>
 The value for the environment variable.
</div></div>

</li>
</ul></li>
<li><code>waitTime : String</code>
</li>
<li><code>waitUnit : String</code>
</li>
</ul>


++++
=== `step([$class: 'OpenShiftImageTagger'])`: Tag OpenShift Image
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>testTag : String</code>
<div><div>
 The name of the existing tag, or an actual, existing image ID. The image referenced will have the new tag applied to it.
</div></div>

</li>
<li><code>prodTag : String</code>
<div><div>
 One or more tag names in a comma delimited list. If multiple streams and multiple destination tags are specified, the two lists must contain the same number of elements.
</div></div>

</li>
<li><code>namespace : String</code>
</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>testStream : String</code>
<div><div>
 The name of the ImageStream for the existing tag.
</div></div>

</li>
<li><code>prodStream : String</code>
<div><div>
 One or more ImageStream names in a comma delimited list. If multiple streams and multiple destination tags are specified, the two lists must contain the same number of elements.
</div></div>

</li>
<li><code>destinationNamespace : String</code>
<div><div>
 The value here should match the value from the output from `oc project` if you created the resources related to this task from the command line. If nothing is specified, the plugin will inspect the PROJECT_NAME environment variable.
</div></div>

</li>
<li><code>destinationAuthToken : String</code>
<div><div>
 The value here is what you supply with the --token option when invoking the OpenShift `oc` command. If you do not supply a value, the plugin will assume it is running in the OpenShift Jenkins image and attempt to load the kubernetes service account token stored in that image.
</div></div>

</li>
<li><code>alias : String</code>
<div><div>
 This flag is the equivalent of the `--alias` option for the `oc tag` command. When false, the destination tag type is "ImageStreamImage", and when true, the destination tag type is "ImageStreamTag".
</div></div>

</li>
</ul>


++++
=== `step([$class: 'OpenShiftScaler'])`: Scale OpenShift Deployment
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>depCfg : String</code>
<div><div>
 If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>namespace : String</code>
</li>
<li><code>replicaCount : String</code>
<div><div>
 The value here should be the number of started pods desired for the deployment specified. It is the equivalent of the value supplied to --replicas with an `oc scale` command invocation. This is a required parameter. If an integer is not specified here, this build step can not be added to the job. Note: specifying a 0 is allowed, and means you do not want any pods for the specified deployment config running.
</div></div>

</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
<li><code>verifyReplicaCount : String</code>
<div><div>
 This flag is the toggle for turning on or off the verification that the specified replica count for the deployment has been reached.
</div></div>

</li>
<li><code>waitTime : String</code>
</li>
<li><code>waitUnit : String</code>
</li>
</ul>


++++
=== `step([$class: 'OpenShiftServiceVerifier'])`: Verify OpenShift Service
++++
<ul><li><code>apiURL : String</code>
</li>
<li><code>svcName : String</code>
<div><div>
 The equivalent to the name supplied to a `oc get service` command line invocation.
</div></div>

</li>
<li><code>namespace : String</code>
</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
</ul>


++++
=== `openshiftVerifyBuild`: Verify OpenShift Build
++++
<ul><li><code>bldCfg : String</code>
<div><div>
 If you run `oc get bc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>checkForTriggeredDeployments : String</code> (optional)
<div><div>
 This flag is the toggle for turning on or off the verification that any deployments triggered by this build's output fired.
</div></div>

</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
<li><code>waitTime : String</code> (optional)
</li>
<li><code>waitUnit : String</code> (optional)
</li>
</ul>


++++
=== `openshiftBuild`: Trigger OpenShift Build
++++
<ul><li><code>bldCfg : String</code>
<div><div>
 If you run `oc get bc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>buildName : String</code> (optional)
<div><div>
 The value here is what you supply with the --from-build option when invoking the OpenShift `oc start-build` command. It allows you to point to OpenShift build to a previously run build, and run another build with exactly the same source and destination metadata. If you do not supply a value, the plugin will generate a new OpenShift build based on the Build Configuration referenced.
</div></div>

</li>
<li><code>checkForTriggeredDeployments : String</code> (optional)
<div><div>
 This flag is the toggle for turning on or off the verification that any deployments triggered by this build's output fired.
</div></div>

</li>
<li><code>commitID : String</code> (optional)
<div><div>
 The value here is what you supply with the --commit option when invoking the OpenShift `oc start-build` command. It allows you to point the OpenShift build to a specific commit hash from the git-log of the source repository. If you do not supply a value, the plugin assumes the latest version from the source repository should be used.
</div></div>

</li>
<li><code>env</code> (optional)
<div><div>
 Specify a list of environment variables to include in the build (see `oc start-build -e ...`).
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
<div><div>
 The name of the environment variable to set.
</div></div>

</li>
<li><code>value : String</code>
<div><div>
 The value for the environment variable.
</div></div>

</li>
</ul></li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>showBuildLogs : String</code> (optional)
<div><div>
 Indicates whether the build logs get dumped to the console of the Jenkins build.
</div></div>

</li>
<li><code>verbose : String</code> (optional)
</li>
<li><code>waitTime : String</code> (optional)
</li>
<li><code>waitUnit : String</code> (optional)
</li>
</ul>


++++
=== `openshiftCreateResource`: Create OpenShift Resource(s)
++++
<ul><li><code>jsonyaml : String</code>
<div><div>
 The JSON or YAML formatted text that conforms to the schema for defining the various OpenShift resources.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
</ul>


++++
=== `openshiftDeleteResourceByJsonYaml`: Delete OpenShift Resource(s) from JSON or YAML
++++
<ul><li><code>jsonyaml : String</code>
<div><div>
 The JSON or YAML formatted text that conforms to the schema for defining the various OpenShift resources.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
</ul>


++++
=== `openshiftDeleteResourceByLabels`: Delete OpenShift Resource(s) using Labels
++++
<ul><li><code>types : String</code>
<div><div>
 The comma separated list of types of API objects to delete, where those objects have labels corresponding to the specified key/value pairs. See https://docs.openshift.org/latest/rest_api/index.html for the supported types.
</div></div>

</li>
<li><code>keys : String</code>
<div><div>
 The comma separated list of keys of the labels in the API objects to delete.
</div></div>

</li>
<li><code>values : String</code>
<div><div>
 The comma separated list of values of the labels in the API objects to delete.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
</ul>


++++
=== `openshiftDeleteResourceByKey`: Delete OpenShift Resource(s) by Key
++++
<ul><li><code>types : String</code>
<div><div>
 The comma separated list of types of API objects to delete. See https://docs.openshift.org/latest/rest_api/index.html for the supported types.
</div></div>

</li>
<li><code>keys : String</code>
<div><div>
 The comma separated list of keys of the API objects to delete.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
</ul>


++++
=== `openshiftDeploy`: Trigger OpenShift Deployment
++++
<ul><li><code>depCfg : String</code>
<div><div>
 If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
<li><code>waitTime : String</code> (optional)
</li>
<li><code>waitUnit : String</code> (optional)
</li>
</ul>


++++
=== `openshiftVerifyDeployment`: Verify OpenShift Deployment
++++
<ul><li><code>depCfg : String</code>
<div><div>
 If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>replicaCount : String</code> (optional)
<div><div>
 This optional field's value represents the number expected running pods for the deployment for the DeploymentConfig specified. If no value is specified it will work the number of running pods against the desired replica count in the DeploymentConfig.
</div></div>

</li>
<li><code>verbose : String</code> (optional)
</li>
<li><code>verifyReplicaCount : String</code> (optional)
<div><div>
 This flag is the toggle for turning on or off the verification that the specified replica count for the deployment has been reached.
</div></div>

</li>
<li><code>waitTime : String</code> (optional)
</li>
<li><code>waitUnit : String</code> (optional)
</li>
</ul>


++++
=== `openshiftExec`: OpenShift Exec
++++
<ul><li><code>pod : String</code>
<div><div>
 The pod in which to execute a command.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>arguments</code> (optional)
<div><div>
 Specify a list of arguments to pass to the command.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
<div><div>
 The value for the environment variable.
</div></div>

</li>
</ul></li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>command : String</code> (optional)
<div><div>
 The name of the command to execute.
</div></div>

</li>
<li><code>container : String</code> (optional)
<div><div>
 The container in which to execute a command. If not specified, the first container in the pod will be used.
</div></div>

</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
<li><code>waitTime : String</code> (optional)
</li>
<li><code>waitUnit : String</code> (optional)
</li>
</ul>


++++
=== `openshiftTag`: Tag OpenShift Image
++++
<ul><li><code>srcStream : String</code>
<div><div>
 The name of the ImageStream for the existing tag.
</div></div>

</li>
<li><code>srcTag : String</code>
<div><div>
 The name of the existing tag, or an actual, existing image ID. The image referenced will have the new tag applied to it.
</div></div>

</li>
<li><code>destStream : String</code>
<div><div>
 One or more ImageStream names in a comma delimited list. If multiple streams and multiple destination tags are specified, the two lists must contain the same number of elements.
</div></div>

</li>
<li><code>destTag : String</code>
<div><div>
 One or more tag names in a comma delimited list. If multiple streams and multiple destination tags are specified, the two lists must contain the same number of elements.
</div></div>

</li>
<li><code>alias : String</code> (optional)
<div><div>
 This flag is the equivalent of the `--alias` option for the `oc tag` command. When false, the destination tag type is "ImageStreamImage", and when true, the destination tag type is "ImageStreamTag".
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>destinationAuthToken : String</code> (optional)
<div><div>
 The value here is what you supply with the --token option when invoking the OpenShift `oc` command. If you do not supply a value, the plugin will assume it is running in the OpenShift Jenkins image and attempt to load the kubernetes service account token stored in that image.
</div></div>

</li>
<li><code>destinationNamespace : String</code> (optional)
<div><div>
 The value here should match the value from the output from `oc project` if you created the resources related to this task from the command line. If nothing is specified, the plugin will inspect the PROJECT_NAME environment variable.
</div></div>

</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
</ul>


++++
=== `openshiftScale`: Scale OpenShift Deployment
++++
<ul><li><code>depCfg : String</code>
<div><div>
 If you run `oc get dc` for the project listed in "nameSpace", that is the value you want to put here.
</div></div>

</li>
<li><code>replicaCount : String</code>
<div><div>
 The value here should be the number of started pods desired for the deployment specified. It is the equivalent of the value supplied to --replicas with an `oc scale` command invocation. This is a required parameter. If an integer is not specified here, this build step can not be added to the job. Note: specifying a 0 is allowed, and means you do not want any pods for the specified deployment config running.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
<li><code>verifyReplicaCount : String</code> (optional)
<div><div>
 This flag is the toggle for turning on or off the verification that the specified replica count for the deployment has been reached.
</div></div>

</li>
<li><code>waitTime : String</code> (optional)
</li>
<li><code>waitUnit : String</code> (optional)
</li>
</ul>


++++
=== `openshiftVerifyService`: Verify OpenShift Service
++++
<ul><li><code>svcName : String</code>
<div><div>
 The equivalent to the name supplied to a `oc get service` command line invocation.
</div></div>

</li>
<li><code>apiURL : String</code> (optional)
</li>
<li><code>authToken : String</code> (optional)
</li>
<li><code>namespace : String</code> (optional)
</li>
<li><code>retryCount : String</code> (optional)
</li>
<li><code>verbose : String</code> (optional)
</li>
</ul>


++++
