= Package Drone Deployer
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/package-drone">Visit the Jenkins Plugins site</a>
++++


=== `pdrone`: Package Drone Deployer
++++
<ul><li><code>serverUrl : String</code>
<div><div>
 The main URL of the server. Not to any channel or artifact but to the server only.
</div></div>

</li>
<li><code>channel : String</code>
</li>
<li><code>credentialsId : String</code>
<div><div>
 A <a href="https://wiki.jenkins.io/display/JENKINS/Plain+Credentials+Plugin" rel="nofollow">secrect text</a> credential stored in Jenkins to be used as deploy key.
</div></div>

</li>
<li><code>artifacts : String</code>
<div><div>
 You can use wildcards like 'module/dist/**/*.zip'. See <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow"> the includes attribute of Ant fileset</a> for the exact format. The base directory is <a rel="nofollow">the workspace</a>. You can only archive files that are located in your workspace.
</div></div>

</li>
<li><code>allowEmptyArchive : boolean</code> (optional)
<div><div>
 Normally, a build fails if archiving returns zero artifacts. This option allows the archiving process to return nothing without failing the build. Instead, the build will simply throw a warning.
</div></div>

</li>
<li><code>defaultExcludes : boolean</code> (optional)
<div><div>
 Package Drone uses the Ant glob pattern which excludes by default some patterns. Refer <a href="http://ant.apache.org/manual/dirtasks.html#defaultexcludes" rel="nofollow">here</a> for the complete list of patterns. 
 <p>This option allows to enable or disable the default Ant exclusions.</p>
</div></div>

</li>
<li><code>deployKey : String</code> (optional)
</li>
<li><code>excludes : String</code> (optional)
<div><div>
 Optionally specify <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">the 'excludes' pattern</a>, such as "foo/bar/**/*". A file that matches this mask will not be archived even if it matches the mask specified in 'files to archive' section.
</div></div>

</li>
<li><code>failsAsUpload : boolean</code> (optional)
</li>
<li><code>stripPath : boolean</code> (optional)
<div><div>
 This will strip the leading directories from the uploaded file name. For example the file <code>foo/bar/file</code> will get uploaded as <code>file</code> instead.
</div></div>

</li>
<li><code>uploadV3 : boolean</code> (optional)
<div><div>
 This will upload all artifacts in a single transfer archive, which is faster but requires the Upload API V3, which is only present in Eclipse Package Drone™ since version 0.14.0.
</div></div>

</li>
</ul>


++++
