= Parallel Test Executor Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/parallel-test-executor">Visit the Jenkins Plugins site</a>
++++


=== `splitTests`: Split Test Runs
++++
<div><div>
 Asks Jenkins to analyze the timing of tests from the last build and divide the tests for this build into roughly equal subsets for <code>parallel</code> execution. <a href="https://github.com/jenkinsci/parallel-test-executor-plugin/blob/master/demo/repo/Jenkinsfile" rel="nofollow">example <code>Jenkinsfile</code></a>
</div></div>
<ul><li><code>parallelism</code>
<ul><b>Nested Choice of Objects</b>
<li><code>count</code><div>
<div><div>
 Always divide the tests into N parallel sub-tasks of about equal size. This mode is useful if your build slaves are not elastic to control the resource consumption by this task.
</div></div>
<ul><li><code>size : int</code>
</li>
</ul></div></li>
<li><code>time</code><div>
<div><div>
 Divide the tests into parallel sub-tasks each no bigger than N minutes. Combined with elastic slaves, such as EC2, the turn-around time of the tests will remain the same no matter how many tests you add. 
 <p>This value counts just the time spent on executing tests, and not including other time such as checking out the code, building the test, etc. For example, if your test job spends 50 minutes in tests and 60 minutes total from start to finish, then you have 10 minutes "fixed" overhead regardless of the number of tests it executes. If you use this mode and set the value to "10 minutes", then you'll have 5 parallel sub-tasks that all ends in roughly 20 minutes (20 mins = 10 mins tests time + 10 mins overhead.)</p>
 <p>"N minutes per a sub-task" is a goal, not a hard constraint. So a sub-task can take longer (for example if you have a single test that takes more than N minutes.)</p>
</div></div>
<ul><li><code>mins : int</code>
</li>
</ul></div></li>
</ul></li>
<li><code>estimateTestsFromFiles : boolean</code> (optional)
</li>
<li><code>generateInclusions : boolean</code> (optional)
<div><p>If disabled, the splitStep call will return a <i>List&lt;List&lt;String&gt;&gt;</i> containing the exclusion patterns for the different buckets.</p>
<p>If enabled, the splitStep call won't return a <i>List&lt;List&lt;String&gt;&gt;</i>.<br>
  Instead it will return a <i>List</i> of a structure with :</p>
<ul>
 <li><i>boolean includes</i> whether the following list is an inclusion or an exclusion list</li>
 <li><i>List&lt;String&gt; list</i> the list of patterns</li>
</ul>
<p></p></div>

</li>
<li><code>stage : String</code> (optional)
<div><div>
 If defined, only consider tests recorded in the previous build in the named stage.
</div></div>

</li>
<li><code>testMode</code> (optional)
<div><p>Configure how exclusions and inclusions are formed from the JUnit result XML. The test job receiving the exclusion/inclusion files must be able to handle the format produced by the selected mode.</p></div>

<ul><b>Nested Choice of Objects</b>
<li><code>javaClass</code><div>
<div><div>
 This mode works best with java projects. 
 <p>Each exclusion/inclusion generates two lines by replacing "." with "/" in the fully qualified test class name and appending ".java" to one line and ".class" to the second line.</p>
</div></div>
<ul></ul></div></li>
<li><code>javaTestCase</code><div>
<div><div>
 This mode works best with Java projects. 
 <p>Parallelize per Java test case.</p>
 <p>It is also able to estimate tests (per class) to run from the workspace content if no historical context could be found.</p>
</div></div>
<ul></ul></div></li>
<li><code>testCase</code><div>
<div><div>
 Each exclusion/inclusion generates one line consisting of the test case name only. 
 <p>This is useful where a tool produces JUnit result XML containing unique test case names without any class prefix.</p>
</div></div>
<ul></ul></div></li>
<li><code>qualifiedTestCase</code><div>
<div><div>
 If checked, each exclusion/inclusion generates one line consisting of the class and test case name on a <em>className.testName</em> format.
</div></div>
<ul></ul></div></li>
</ul></li>
</ul>


++++
