= Parameterized Remote Trigger Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/Parameterized-Remote-Trigger">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'RemoteBuildConfiguration'])`: Trigger a remote parameterized job
++++
<ul><li><code>abortTriggeredJob : boolean</code> (optional)
</li>
<li><code>auth2</code> (optional)
<div><div>
 Using this parameter you can override the authentication used to connect to the selected remote Jenkins. 
 <ul>
  <li><b>Don't Override</b><br>
    The authentication configured in the (global) settings of the selected 'remote host' is used.</li>
  <li><b>Token Authentication</b><br>
    The specified user id and Jenkins API token is used.</li>
  <li><b>Credentials Authentication</b><br>
    The specified Jenkins Credentials are used. This can be either user/password or user/API Token.</li>
  <li><b>No Authentication</b><br>
    No Authorization header will be sent, independent of the global 'remote host' settings.</li>
  <li><b>Bearer Authentication</b><br>
    The bearer token is used.</li>
 </ul><b>Note:</b> <i>Jenkins API Tokens</i> are recommended since, if stolen, they allow access only to a specific Jenkins while user and password typically provide access to many systems.
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>BearerTokenAuth</code><div>
<ul><li><code>token</code> (optional)
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
</ul></div></li>
<li><code>CredentialsAuth</code><div>
<ul><li><code>credentials : String</code> (optional)
</li>
</ul></div></li>
<li><code>NoneAuth</code><div>
<ul></ul></div></li>
<li><code>NullAuth</code><div>
<ul></ul></div></li>
<li><code>TokenAuth</code><div>
<ul><li><code>apiToken</code> (optional)
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>userName : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>blockBuildUntilComplete : boolean</code> (optional)
</li>
<li><code>disabled : boolean</code> (optional)
<div><div>
 Set this field to disable the job step instead of removing it from job configuration.
</div></div>

</li>
<li><code>enhancedLogging : boolean</code> (optional)
<div><div>
 <div>
  Enable Enhanced Logging
 </div> If this option is enabled, the console output of the remote job is also logged.
</div></div>

</li>
<li><code>httpGetReadTimeout : int</code> (optional)
</li>
<li><code>httpPostReadTimeout : int</code> (optional)
</li>
<li><code>job : String</code> (optional)
<div><div>
 <div>
  Remote Job Name or full URL.
 </div> The name or URL of the job on the remote Jenkins host which you would like to trigger. If the full job URL is specified the URL of the remote Jenkins host configured above will be ignored.
</div></div>

</li>
<li><code>maxConn : int</code> (optional)
<div><div>
 The max concurrent connections to the remote host, default is 1, max is 5. It'll be 5 even if you set it greater than 5. <b>Note:</b> Set this field with caution, too many concurrent requests will not only fail your local jobs,
 <br>
  but also block the remote server.
</div></div>

</li>
<li><code>overrideTrustAllCertificates : boolean</code> (optional)
</li>
<li><code>parameters : String</code> (optional)
</li>
<li><code>parameters2</code> (optional)
<div><div>
 <div>
  Job Parameters
 </div> Parameters which will be used when triggering the remote job. 
 <br>
  If no parameters are needed, then just leave this blank. 
 <ul>
  <li><b>Map parameters</b><br>
    This is the recommended type. It allows you to provide parameters with key/value and supports multi-line parameters.</li>
  <li><b>String parameters (legacy)</b><br>
    This type allows to describe parameters within a big string like in versions 3.1.5 and lower. It does not support multi-line parameters.</li>
  <li><b>File parameters (legacy)</b><br>
    This type allows to describe parameters within a file like in versions 3.1.5 and lower. It does not support multi-line parameters.</li>
 </ul>
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>FileParameters</code><div>
<ul><li><code>filePath : String</code> (optional)
</li>
</ul></div></li>
<li><code>MapParameters</code><div>
<ul><li><code>parameters</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code> (optional)
</li>
<li><code>value : String</code> (optional)
</li>
</ul></li>
</ul></div></li>
<li><code>StringParameters</code><div>
<ul><li><code>parameters : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>pollInterval : int</code> (optional)
</li>
<li><code>preventRemoteBuildQueue : boolean</code> (optional)
</li>
<li><code>remoteJenkinsName : String</code> (optional)
</li>
<li><code>remoteJenkinsUrl : String</code> (optional)
<div><div>
 It is possible to override the Remote Jenkins URL for each Job separately.
</div></div>

</li>
<li><code>shouldNotFailBuild : boolean</code> (optional)
<div><div>
 <div>
  Do Not Fail If Remote Fails
 </div> If this option is enabled, the build will not fail even if the remote build fails.
</div></div>

</li>
<li><code>token : String</code> (optional)
<div><div>
 <div>
  Remote Job Token
 </div> Security token which is defined on the job of the remote Jenkins host. 
 <br>
  If no job token is needed to trigger this job, then just leave it blank
</div></div>

</li>
<li><code>trustAllCertificates : boolean</code> (optional)
<div><div>
 <div>
  Trust all certificates
 </div>
 <p>It is possible to override/rewrite the 'Trust all certificate'-setting for each Job separately. Setting this checkbox to 'true' will result in accepting all certificates for the given Job.</p>
 <div>
  If your remote Jenkins host has a <a href="https://en.wikipedia.org/wiki/Self-signed_certificate" rel="nofollow"> self-signed certificate </a> or its certificate is not trusted, you may want to enable this option. It will accept untrusted certificates for the given host.
 </div>
 <p><strong>This is unsafe and should only be used for testing or if you trust the host.</strong></p>
</div></div>

</li>
<li><code>useCrumbCache : boolean</code> (optional)
<div><div>
 Set this field to enable cache of the crumb of remote server. 
 <br>
  It'll be more efficient for the local job execution &amp; more stable for remote server when massive concurrent jobs are triggered.
 <br>
  This cache will be cleared every 10 minutes.
</div></div>

</li>
<li><code>useJobInfoCache : boolean</code> (optional)
<div><div>
 Set this field to enable cache of the job info of remote server. 
 <br>
  It'll be more efficient for the local job execution &amp; more stable for remote server when massive concurrent jobs are triggered.
 <br>
  This cache will be cleared every 10 minutes.
</div></div>

</li>
</ul>


++++
=== `triggerRemoteJob`: Trigger Remote Job
++++
<div><div>
 The `triggerRemoteJob` pipeline step triggers a job on a remote Jenkins.
 <br><b>The full documentation is <a href="https://github.com/jenkinsci/parameterized-remote-trigger-plugin" rel="nofollow">available in GitHub</a>.</b>
 <br>
 <br>
  Example: 
 <pre>//Trigger remote job
def handle = triggerRemoteJob(remoteJenkinsName: 'remoteJenkins', job: 'RemoteJob')

//Get information from the handle
def status = handle.getBuildStatus()
def buildUrl = handle.getBuildUrl()
echo buildUrl.toString() + " finished with " + status.toString()

//Download and parse the archived "build-results.json" (if generated and archived by remote build)
def results = handle.readJsonFileFromBuildArchive('build-results.json')
echo results.urlToTestResults //only example


//List other available methods
echo handle.help()
</pre>
</div></div>
<ul><li><code>job : String</code>
<div><div>
 <div>
  Remote Job Name or full URL.
 </div> The name or URL of the job on the remote Jenkins host which you would like to trigger. If the full job URL is specified the URL of the remote Jenkins host configured above will be ignored. 
 <p>mandatory: yes<br></p>
</div></div>

</li>
<li><code>abortTriggeredJob : boolean</code> (optional)
</li>
<li><code>auth</code> (optional)
<div><div>
 Using this parameter you can override the authentication used to connect to the selected remote Jenkins.
 <br>
 <ul>
  <li><b>Don't Override</b><br>
    The authentication configured in the (global) settings of the selected 'remote host' is used.</li>
  <li><b>Token Authentication</b><br>
    The specified user id and Jenkins API token is used.</li>
  <li><b>Credentials Authentication</b><br>
    The specified Jenkins Credentials are used. This can be either user/password or user/API Token.</li>
  <li><b>No Authentication</b><br>
    No Authorization header will be sent, independent of the global 'remote host' settings.</li>
 </ul><b>Note:</b> <i>Jenkins API Tokens</i> are recommended since, if stolen, they allow access only to a specific Jenkins while user and password typically provide access to many systems.
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>BearerTokenAuth</code><div>
<ul><li><code>token</code> (optional)
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
</ul></div></li>
<li><code>CredentialsAuth</code><div>
<ul><li><code>credentials : String</code> (optional)
</li>
</ul></div></li>
<li><code>NoneAuth</code><div>
<ul></ul></div></li>
<li><code>NullAuth</code><div>
<ul></ul></div></li>
<li><code>TokenAuth</code><div>
<ul><li><code>apiToken</code> (optional)
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>userName : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>blockBuildUntilComplete : boolean</code> (optional)
<div><div>
 <div>
  Wait/Block Until Remote Build Complete
 </div> If enabled the remote job is called synchronously and the plugin waits until the remote job finished.
 <br>
  If disabled the plugin triggers the remote job and returns.
 <br>
 <br>
  In both cases a <code>handle</code> is returned for further tracking the remote job or getting the results (see plugin main help page). 
 <p>mandatory: no<br>
   default: true</p>
</div></div>

</li>
<li><code>disabled : boolean</code> (optional)
<div><div>
 Set this field to disable the job step instead of removing it from job configuration.
</div></div>

</li>
<li><code>enhancedLogging : boolean</code> (optional)
<div><div>
 <div>
  Enable Enhanced Logging
 </div> If this option is enabled, the console output of the remote job is also logged. 
 <p>mandatory: no<br>
   default: false</p>
</div></div>

</li>
<li><code>httpGetReadTimeout : int</code> (optional)
</li>
<li><code>httpPostReadTimeout : int</code> (optional)
</li>
<li><code>maxConn : int</code> (optional)
<div><div>
 The max concurrent connections to the remote host, default is 1, max is 5. It'll be 5 even if you set it greater than 5. <b>Note:</b> Set this field with caution, too many concurrent requests will not only fail your local jobs, 
 <br>
  but also block the remote server.
</div></div>

</li>
<li><code>overrideTrustAllCertificates : boolean</code> (optional)
</li>
<li><code>parameterFile : String</code> (optional)
</li>
<li><code>parameters : <code>Object</code></code> (optional)
<div><div>
 <div>
  Job Parameters
 </div> Parameters which will be used when triggering the remote job. 
 <br>
  If no parameters are needed, then just leave this blank. 
 <br>
  In case of a String, the plugin uses String/File parameters depending on the parameter's content. 
 <ul>
  <li><b>Map parameters</b><br>
   <p><code>Map&lt;String, Object&gt;</code></p>
   <p>This is the recommended type. It allows you to provide parameters with key/value and supports multi-line parameters.</p></li>
  <li><b>String parameters (legacy)</b><br>
   <p><code>String</code></p>
   <p>This type allows to describe parameters within a big string like in versions 3.1.5 and lower. It does not support multi-line parameters.</p></li>
  <li><b>File parameters (legacy)</b><br>
   <p><code>String</code></p> This type allows to describe parameters within a file like in versions 3.1.5 and lower. It does not support multi-line parameters.</li>
 </ul>
</div></div>

</li>
<li><code>pollInterval : int</code> (optional)
<div><div>
 <div>
  Polling Interval
 </div> The plugin identifies the status of the remote build by polling. Here you can specify how often the plugin shall poll the remote status.
 <br>
  Be aware that polling too often might cause an increased load on the remote Jenkins. 
 <p>mandatory: no<br>
   default: 10</p>
</div></div>

</li>
<li><code>preventRemoteBuildQueue : boolean</code> (optional)
<div><div>
 <div>
  Prevent Remote Build Queue
 </div> Wait to trigger remote builds until no other builds are running. 
 <p>mandatory: no<br>
   default: false</p>
</div></div>

</li>
<li><code>remoteJenkinsName : String</code> (optional)
<div><div>
 <div>
  Remote Jenkins Name
 </div> The name of the remote Jenkins as configured in the Jenkins global configuration (Manage Jenkins &gt; Configure System &gt; Parameterized Remote Trigger Configuration &gt; Remote Hosts). 
 <p>mandatory: yes</p>
</div></div>

</li>
<li><code>remoteJenkinsUrl : String</code> (optional)
<div><div>
 It is possible to override the Remote Jenkins URL for each Pipeline separately. 
 <p>mandatory: no</p>
</div></div>

</li>
<li><code>shouldNotFailBuild : boolean</code> (optional)
<div><div>
 <div>
  Do Not Fail If Remote Fails
 </div> If this option is enabled, the build will not fail even if the remote build fails. 
 <p>mandatory: no<br>
   default: false</p>
</div></div>

</li>
<li><code>token : String</code> (optional)
<div><div>
 <div>
  Remote Job Token
 </div> Security token which is defined on the job of the remote Jenkins host. 
 <br>
  If no job token is needed to trigger this job, then just leave it blank 
 <p>mandatory: no<br>
   default: ""</p>
</div></div>

</li>
<li><code>trustAllCertificates : boolean</code> (optional)
<div><div>
 <div>
  Trust all certificates
 </div>
 <p>It is possible to override/rewrite the 'Trust all certificate'-setting for each Job separately. Setting this checkbox to 'true' will result in accepting all certificates for the given Job.</p>
 <div>
  If your remote Jenkins host has a <a href="https://en.wikipedia.org/wiki/Self-signed_certificate" rel="nofollow"> self-signed certificate </a> or its certificate is not trusted, you may want to enable this option. It will accept untrusted certificates for the given host.
 </div>
 <p><strong>This is unsafe and should only be used for testing or if you trust the host.</strong></p>
</div></div>

</li>
<li><code>useCrumbCache : boolean</code> (optional)
<div><div>
 Set this field to enable cache of the crumb of remote server. 
 <br>
  It'll be more efficient for the local job execution &amp; more stable for remote server when massive concurrent jobs are triggered.
 <br>
  This cache will be cleared every 10 minutes.
</div></div>

</li>
<li><code>useJobInfoCache : boolean</code> (optional)
<div><div>
 Set this field to enable cache of the job info of remote server. 
 <br>
  It'll be more efficient for the local job execution &amp; more stable for remote server when massive concurrent jobs are triggered.
 <br>
  This cache will be cleared every 10 minutes.
</div></div>

</li>
</ul>


++++
