= Peass-CI
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/peass-ci">Visit the Jenkins Plugins site</a>
++++


=== `cleanPerformanceMeasurement`: Clean Peass-CI Cache
++++
<ul><li><code>cleanMeasurement : boolean</code> (optional)
</li>
<li><code>cleanRCA : boolean</code> (optional)
</li>
<li><code>cleanRTS : boolean</code> (optional)
</li>
</ul>


++++
=== `measure`: Measure Version Performance
++++
<ul><li><code>VMs : int</code> (optional)
</li>
<li><code>androidCompileSdkVersion : String</code> (optional)
</li>
<li><code>androidGradleTasks : String</code> (optional)
</li>
<li><code>androidGradleVersion : String</code> (optional)
</li>
<li><code>androidManifest : String</code> (optional)
</li>
<li><code>androidMinSdkVersion : String</code> (optional)
</li>
<li><code>androidTargetSdkVersion : String</code> (optional)
</li>
<li><code>androidTestPackageName : String</code> (optional)
</li>
<li><code>clazzFolders : String</code> (optional)
</li>
<li><code>cleanGoal : String</code> (optional)
</li>
<li><code>clearMockitoCaches : boolean</code> (optional)
</li>
<li><code>commitDiff : int</code> (optional)
</li>
<li><code>createDefaultConstructor : boolean</code> (optional)
</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>directlyMeasureKieker : boolean</code> (optional)
</li>
<li><code>displayLogs : boolean</code> (optional)
</li>
<li><code>displayRCALogs : boolean</code> (optional)
</li>
<li><code>displayRTSLogs : boolean</code> (optional)
</li>
<li><code>excludeByRule : String</code> (optional)
</li>
<li><code>excludeForTracing : String</code> (optional)
</li>
<li><code>excludeLog4jSlf4jImpl : boolean</code> (optional)
</li>
<li><code>excludeLog4jToSlf4j : boolean</code> (optional)
</li>
<li><code>excludes : String</code> (optional)
</li>
<li><code>executeBeforeClassInMeasurement : boolean</code> (optional)
</li>
<li><code>executeParallel : boolean</code> (optional)
</li>
<li><code>executeRCA : boolean</code> (optional)
</li>
<li><code>failOnRtsError : boolean</code> (optional)
</li>
<li><code>generateCoverageSelection : boolean</code> (optional)
</li>
<li><code>generateTwiceExecutability : boolean</code> (optional)
</li>
<li><code>importLogSizeInMb : int</code> (optional)
</li>
<li><code>includeByRule : String</code> (optional)
</li>
<li><code>includes : String</code> (optional)
</li>
<li><code>iterations : int</code> (optional)
</li>
<li><code>kiekerQueueSize : long</code> (optional)
</li>
<li><code>kiekerWaitTime : int</code> (optional)
</li>
<li><code>linearizeHistory : boolean</code> (optional)
</li>
<li><code>measureJMH : boolean</code> (optional)
</li>
<li><code>measurementMode</code> (optional)
<ul><li><b>Values:</b> <code>LEVELWISE</code>, <code>COMPLETE</code>, <code>UNTIL_STRUCTURE_CHANGE</code>, <code>UNTIL_SOURCE_CHANGE</code></li></ul></li>
<li><code>nightlyBuild : boolean</code> (optional)
</li>
<li><code>onlyMeasureWorkload : boolean</code> (optional)
</li>
<li><code>onlyOneCallRecording : boolean</code> (optional)
</li>
<li><code>pl : String</code> (optional)
</li>
<li><code>properties : String</code> (optional)
</li>
<li><code>redirectSubprocessOutputToFile : boolean</code> (optional)
</li>
<li><code>redirectToNull : boolean</code> (optional)
</li>
<li><code>removeSnapshots : boolean</code> (optional)
</li>
<li><code>repetitions : int</code> (optional)
</li>
<li><code>showStart : boolean</code> (optional)
</li>
<li><code>significanceLevel : double</code> (optional)
</li>
<li><code>statisticalTest</code> (optional)
<ul><li><b>Values:</b> <code>T_TEST</code>, <code>BIMODAL_T_TEST</code>, <code>AGNOSTIC_T_TEST</code>, <code>MANN_WHITNEY_TEST</code>, <code>CONFIDENCE_INTERVAL</code>, <code>ANY</code>, <code>ANY_NO_AGNOSTIC</code></li></ul></li>
<li><code>testClazzFolders : String</code> (optional)
</li>
<li><code>testExecutor : String</code> (optional)
</li>
<li><code>testGoal : String</code> (optional)
</li>
<li><code>testTransformer : String</code> (optional)
</li>
<li><code>timeout : long</code> (optional)
</li>
<li><code>traceSizeInMb : int</code> (optional)
</li>
<li><code>updateSnapshotDependencies : boolean</code> (optional)
</li>
<li><code>useAggregation : boolean</code> (optional)
</li>
<li><code>useAlternativeBuildfile : boolean</code> (optional)
</li>
<li><code>useAnbox : boolean</code> (optional)
</li>
<li><code>useGC : boolean</code> (optional)
</li>
<li><code>useSourceInstrumentation : boolean</code> (optional)
</li>
<li><code>warmup : int</code> (optional)
</li>
<li><code>writeAsZip : boolean</code> (optional)
</li>
<li><code>xmx : String</code> (optional)
</li>
</ul>


++++
=== `peassOverview`: Peass Overview
++++
<ul><li><code>changeClassifications : String</code> (optional)
</li>
<li><code>projects</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>project : String</code> (optional)
</li>
</ul></li>
<li><code>timespan : String</code> (optional)
</li>
<li><code>unmeasuredClassifications : String</code> (optional)
</li>
</ul>


++++
