= Performance Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/performance">Visit the Jenkins Plugins site</a>
++++


=== `perfReport`: Publish Performance test result report
++++
<ul><li><code>sourceDataFiles : String</code>
<div><div>
 <p>Specify the path to the Performance report files, relative to the <a rel="nofollow">workspace root</a>. Plugin will be automatically detect parser for each report file.</p>
 <ul>
  <li>You can specify multiple files and directories separated by semicolon.</li>
  <li>You use an Ant 'fileset' pattern.</li>
 </ul>
 <p>Default Values are:</p>
 <ul>
  <li>JMeter reports: "**/*.jtl"</li>
  <li>JMeter csv reports: "**/*.csv"</li>
  <li>JMeter Summariser reports: "**/*.log"</li>
  <li>Taurus reports: "**/*.xml"</li>
  <li>JUnit report: "**/TEST-*.xml"</li>
  <li>wrk report: "**/*.wrk"</li>
  <li>Locust report: "**/*_stats.csv"</li>
 </ul>
 <p>* By default jmeter writes summariser statistics to jmeter.log. To enable logging summariser statistics to separate log file add the property to jmeter.properties file to #Logging Configuration block : "log_file.jmeter.reporters.Summariser=filename.log"</p>
 <p>** Default time format, that JMeter used for logging is "yyyy/mm/dd HH:mm:ss". See "log_format" property in jmeter.properties file in #Logging Configuration block.</p>
 <p>*** By default wrk does not write output files. You'll need to redirect the STDOUT output for a file as in</p>
 <pre>wrk [options] [url] &gt; results.wrk</pre>
</div></div>

</li>
<li><code>baselineBuild : int</code> (optional)
</li>
<li><code>compareBuildPrevious : boolean</code> (optional)
</li>
<li><code>configType : String</code> (optional)
</li>
<li><code>constraints</code> (optional)
<ul><li><b>Type:</b> <code>? extends hudson.plugins.performance.constraints.AbstractConstraint</code></li>
</ul></li>
<li><code>errorFailedThreshold : int</code> (optional)
</li>
<li><code>errorUnstableResponseTimeThreshold : String</code> (optional)
<div><div>
 The thresholds settings should be delimited by a new line character "\n".
</div>
<div>
 The actual threshold number should be seperated from the test file name by a colon ":"
</div>
<pre>Example:
-------------------------------------
JMeterResultsOrders.jtl:2000
JMeterResultsGetCustomer.jtl:500
JMeterResultsCreateCustomer.jtl:700
-------------------------------------
</pre></div>

</li>
<li><code>errorUnstableThreshold : int</code> (optional)
</li>
<li><code>excludeResponseTime : boolean</code> (optional)
</li>
<li><code>failBuildIfNoResultFile : boolean</code> (optional)
</li>
<li><code>filterRegex : String</code> (optional)
<div><div>
 <p>If this field is not empty, its content will be considered as a regular expression to only take into account URI matching it.</p>
 <p>Example : ^(HP|Scenario|Search)(-success|-failure)?$</p>
</div></div>

</li>
<li><code>graphType : String</code> (optional)
</li>
<li><code>ignoreFailedBuilds : boolean</code> (optional)
</li>
<li><code>ignoreUnstableBuilds : boolean</code> (optional)
</li>
<li><code>junitOutput : String</code> (optional)
</li>
<li><code>modeEvaluation : boolean</code> (optional)
<div><div>
 <p>Standard Mode activates upper box and ignores lower box.</p>
 <p>Expert Mode activates lower box and ignores upper box.</p>
</div></div>

</li>
<li><code>modeOfThreshold : boolean</code> (optional)
</li>
<li><code>modePerformancePerTestCase : boolean</code> (optional)
</li>
<li><code>modeThroughput : boolean</code> (optional)
</li>
<li><code>nthBuildNumber : int</code> (optional)
</li>
<li><code>parsers</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'IagoParser'</code><div>
<ul><li><code>glob : String</code>
</li>
<li><code>percentiles : String</code>
</li>
<li><code>filterRegex : String</code>
</li>
</ul></div></li>
<li><code>$class: 'JMeterCsvParser'</code><div>
<ul><li><code>glob : String</code>
</li>
<li><code>percentiles : String</code>
</li>
<li><code>filterRegex : String</code>
</li>
</ul></div></li>
<li><code>$class: 'JMeterParser'</code><div>
<ul><li><code>glob : String</code>
</li>
<li><code>percentiles : String</code>
</li>
<li><code>filterRegex : String</code>
</li>
</ul></div></li>
<li><code>$class: 'JUnitParser'</code><div>
<ul><li><code>glob : String</code>
</li>
<li><code>percentiles : String</code>
</li>
<li><code>filterRegex : String</code>
</li>
</ul></div></li>
<li><code>$class: 'JmeterSummarizerParser'</code><div>
<ul><li><code>glob : String</code>
</li>
<li><code>percentiles : String</code>
</li>
<li><code>filterRegex : String</code>
</li>
</ul></div></li>
<li><code>$class: 'LoadRunnerParser'</code><div>
<ul><li><code>glob : String</code>
</li>
<li><code>percentiles : String</code>
</li>
<li><code>filterRegex : String</code>
</li>
</ul></div></li>
<li><code>$class: 'LocustParser'</code><div>
<ul><li><code>glob : String</code>
</li>
<li><code>percentiles : String</code>
</li>
<li><code>filterRegex : String</code>
</li>
</ul></div></li>
<li><code>$class: 'TaurusParser'</code><div>
<ul><li><code>glob : String</code>
</li>
<li><code>percentiles : String</code>
</li>
<li><code>filterRegex : String</code>
</li>
</ul></div></li>
<li><code>$class: 'WrkSummarizerParser'</code><div>
<ul><li><code>glob : String</code>
</li>
<li><code>percentiles : String</code>
</li>
<li><code>filterRegex : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>percentiles : String</code> (optional)
</li>
<li><code>persistConstraintLog : boolean</code> (optional)
</li>
<li><code>relativeFailedThresholdNegative : double</code> (optional)
</li>
<li><code>relativeFailedThresholdPositive : double</code> (optional)
</li>
<li><code>relativeUnstableThresholdNegative : double</code> (optional)
</li>
<li><code>relativeUnstableThresholdPositive : double</code> (optional)
</li>
<li><code>showTrendGraphs : boolean</code> (optional)
</li>
</ul>


++++
=== `bzt`: Run Performance Test
++++
<div><div>
 Execute <a href="http://gettaurus.org/?utm_source=jenkins&amp;utm_medium=link&amp;utm_campaign=build_step_help" rel="nofollow">Taurus</a> with configuration files and options. You can simply specify JMX file to run, or give list of Taurus config files and options to execute.
</div></div>
<ul><li><code>params : String</code>
</li>
<li><code>alwaysUseVirtualenv : boolean</code> (optional)
</li>
<li><code>bztVersion : String</code> (optional)
</li>
<li><code>generatePerformanceTrend : boolean</code> (optional)
</li>
<li><code>printDebugOutput : boolean</code> (optional)
</li>
<li><code>useBztExitCode : boolean</code> (optional)
</li>
<li><code>useSystemSitePackages : boolean</code> (optional)
</li>
<li><code>virtualEnvCommand : String</code> (optional)
</li>
<li><code>workingDirectory : String</code> (optional)
</li>
<li><code>workspace : String</code> (optional)
</li>
</ul>


++++
