= Performance Signature: Dynatrace
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/performance-signature-dynatracesaas">Visit the Jenkins Plugins site</a>
++++


=== `createDynatraceDeploymentEvent`: create Dynatrace Deployment event
++++
<ul><li><code>envId : String</code>
</li>
<li><code>customProperties</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>key : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>entityIds</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'Application'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'Host'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'Process'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ProcessGroup'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'Service'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>tagMatchRules</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>meTypes</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>meType : String</code>
</li>
</ul></li>
<li><code>tags</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>context : String</code> (optional)
</li>
<li><code>key : String</code> (optional)
</li>
<li><code>value : String</code> (optional)
</li>
</ul></li>
</ul></li>
</ul>


++++
=== `perfSigDynatraceReports`: Performance Signature Dynatrace reports
++++
<ul><li><code>envId : String</code>
</li>
<li><code>metrics</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>metricId : String</code>
</li>
</ul></li>
<li><code>nonFunctionalFailure : int</code> (optional)
</li>
<li><code>specFile : String</code> (optional)
</li>
</ul>


++++
=== `recordDynatraceSession`: record Dynatrace Saas/Managed session
++++
<ul><li><code>envId : String</code>
</li>
<li><code>testCase : String</code>
</li>
<li><code>entityIds</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'Application'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'Host'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'Process'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ProcessGroup'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'Service'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>tagMatchRules</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>meTypes</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>meType : String</code>
</li>
</ul></li>
<li><code>tags</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>context : String</code> (optional)
</li>
<li><code>key : String</code> (optional)
</li>
<li><code>value : String</code> (optional)
</li>
</ul></li>
</ul></li>
</ul>


++++
=== `recordDynatraceCustomSession`: record Dynatrace Saas/Managed custom session
++++
<ul><li><code>envId : String</code>
</li>
<li><code>testCase : String</code>
</li>
<li><code>entityIds</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'Application'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'Host'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'Process'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ProcessGroup'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'Service'</code><div>
<ul><li><code>entityId : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>tagMatchRules</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>meTypes</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>meType : String</code>
</li>
</ul></li>
<li><code>tags</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>context : String</code> (optional)
</li>
<li><code>key : String</code> (optional)
</li>
<li><code>value : String</code> (optional)
</li>
</ul></li>
</ul></li>
<li><code>timeframeStart : long</code> (optional)
</li>
<li><code>timeframeStop : long</code> (optional)
</li>
</ul>


++++
