= piketec-tpt
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/piketec-tpt">Visit the Jenkins Plugins site</a>
++++


=== `tptReport`: TPT Report
++++
<ul></ul>


++++
=== `tptExecute`: Execute TPT test cases
++++
<div><div>
 The "Execute TPT test cases" build step can run in two modes. 
 <ul>
  <li>Just execute the tests within this Job. The given values will be used to create a command that will be executed. This command could be typed into the command line and would work.</li>
  <li>Use this Job as a Master. In this mode the TPT RMI API is used to read the test cases that must be executed. For every test case a slave job is started and parameters are provided that can be used by the "Execute TPT tests slave" build step. The slaves copy their reults back to the master and the master will aggregate the test results.</li>
 </ul> The master mode can be activated and configured by clicking on the "Advanced" button.
</div></div>
<ul><li><code>exePaths : String</code>
</li>
<li><code>executionConfiguration</code>
<ul><b>Array / List of Nested Object</b>
<li><code>tptFile : String</code>
</li>
<li><code>configuration : String</code>
</li>
<li><code>id : String</code>
</li>
<li><code>enableTest : boolean</code> (optional)
</li>
<li><code>reportDir : String</code> (optional)
</li>
<li><code>testSet : String</code> (optional)
</li>
<li><code>testdataDir : String</code> (optional)
</li>
<li><code>timeout : long</code> (optional)
</li>
</ul></li>
<li><code>arguments : String</code> (optional)
</li>
<li><code>enableJunit : boolean</code> (optional)
</li>
<li><code>isTptMaster : boolean</code> (optional)
</li>
<li><code>jUnitLogLevel</code> (optional)
<ul><li><b>Values:</b> <code>NONE</code>, <code>ERROR</code>, <code>WARNING</code>, <code>INFO</code>, <code>ALL</code></li></ul></li>
<li><code>jUnitreport : String</code> (optional)
</li>
<li><code>slaveJob : String</code> (optional)
</li>
<li><code>slaveJobCount : String</code> (optional)
</li>
<li><code>slaveJobTries : String</code> (optional)
</li>
<li><code>tptBindingName : String</code> (optional)
</li>
<li><code>tptPort : String</code> (optional)
</li>
<li><code>tptStartUpWaitTime : String</code> (optional)
</li>
</ul>


++++
=== `tptAgent`: Execute TPT tests as a worker for a TPT master job
++++
<div><div>
 This build step expects to be executed in a job started by an "Execute TPT test cases" build step in master mode. The master job will provide some parameters used by this build step. It will execute excatly one test case and copies the result back to the master node. To execute a single test case the build step uses the TPT RMI API. The Job should be only run once on every Computer. You can achive that e.g. by <a href="https://wiki.jenkins-ci.org/display/JENKINS/Throttle+Concurrent+Builds+Plugin" rel="nofollow">Throttle Concurrent Builds Plugin</a>
</div></div>
<ul><li><code>exePaths : String</code>
</li>
<li><code>arguments : String</code> (optional)
</li>
<li><code>tptBindingName : String</code> (optional)
</li>
<li><code>tptPort : String</code> (optional)
</li>
<li><code>tptStartUpWaitTime : String</code> (optional)
</li>
</ul>


++++
