= Pipeline: Input Step
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/pipeline-input-step">Visit the Jenkins Plugins site</a>
++++


=== `input`: Wait for interactive input
++++
<div><div>
 <p>This step pauses Pipeline execution and allows the user to interact and control the flow of the build. Only a basic "proceed" or "abort" option is provided in the stage view.</p>
 <p>You can optionally request information back, hence the name of the step. The parameter entry screen can be accessed via a link at the bottom of the build console log or via link in the sidebar for a build.</p>
</div></div>
<ul><li><code>message : String</code>
<div><p>This parameter gives a prompt which will be shown to a human:</p>
<pre>    Ready to go?
    Proceed or Abort
    </pre>
<p></p>
<p>If you click "Proceed" the build will proceed to the next step, if you click "Abort" the build will be aborted.</p></div>

</li>
<li><code>id : String</code> (optional)
<div><p>Every <code>input</code> step has an unique identifier. It is used in the generated URL to proceed or abort.</p>
<p>A specific identifier could be used, for example, to mechanically respond to the input from some external process/tool.</p></div>

</li>
<li><code>ok : String</code> (optional)
</li>
<li><code>parameters</code> (optional)
<div><p>Request that the submitter specify one or more parameter values when approving. If just one parameter is listed, its value will become the value of the <code>input</code> step. If multiple parameters are listed, the return value will be a map keyed by the parameter names. If parameters are not requested, the step returns nothing if approved.</p>
<p>On the parameter entry screen you are able to enter values for parameters that are defined in this field.</p></div>

<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>agentParameter</code><div>
<ul><li><code>name : String</code>
<div><div>
 Parameter name,required.
</div></div>

</li>
<li><code>defaultValue : String</code> (optional)
<div><div>
 Default agent server name,Not required.
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'AppDetectorParamaterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>appName : String</code>
</li>
<li><code>defaultValue : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'ArtifactRepoParamDefinition'</code><div>
<div><div>
 Define an artifact repository from which to pull information and make it available as build parameters.
</div></div>
<ul><li><code>name : String</code>
<div><div>
 The name (and label) displayed to the user when selecting settings prior to running a build.
</div></div>

</li>
<li><code>serverType : String</code>
<div><div>
 Select the type of the artifact repository. 
 <ul>
  <li>Sonatype Nexus 3</li>
  <li>JFrog Artifactory 7 / Cloud</li>
 </ul>
</div></div>

</li>
<li><code>serverUrl : String</code>
<div><div>
 <p>Define the URL of the repository instance.</p><span>Example URLs</span>
 <ul>
  <li>Artifactory OSS - <code>http://localhost:8082/artifactory/</code></li>
  <li>Artifactory Cloud - <code>https://tenant.jfrog.io/artifactory/</code></li>
  <li>Nexus - <code>http://localhost:8081/</code></li>
 </ul>
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 <p>Select the credentials to use to connect to the artifact repository instance.</p>
 <p>Please be aware that currently only username/password credentials are supported.</p>
</div></div>

</li>
<li><code>ignoreCertificate : boolean</code>
<div><div>
 <p>When checked the HTTP connection will ignore invalid certificates while trying to connect to the repository instance. This is useful when using an internal service with self-signed certificates.</p>
 <p><em>Use this feature with caution as it can introduce potential security risks.</em></p>
</div></div>

</li>
<li><code>proxy</code>
<div><div>
 <p>When checked it allows to define an HTTP proxy to be used for the outgoing connections.</p><i> Please note that when this option is unchecked but a global proxy is defined the connection will make use of the global proxy settings. If both the local and global proxy settings are set the local proxy settings take precedence. </i>
</div></div>

<ul><b>Nested Object</b>
<li><code>proxyProtocol : String</code>
</li>
<li><code>proxyHost : String</code>
</li>
<li><code>proxyPort : String</code>
</li>
<li><code>proxyCredentialsId : String</code>
</li>
</ul></li>
<li><code>paramType : String</code>
<div><div>
 <p>Select the type of information to display as a build parameter.</p><strong>Artifact Path</strong> displays the name of deployed artifacts and makes the full path available. 
 <br><strong>Artifact Version</strong> displays the version of deployed artifacts.
 <br><strong>Repositories</strong> displays all available artifact repositories.
</div></div>

</li>
<li><code>artifactName : String</code>
<div><div>
 Define a name pattern for the artifact to be found. An asterisk (*) can be used as a wildcard. 
 <p><i> Unfortunately the REST APIs do not allow for more powerful filter possibilities in regards to the artifact name. If more advanced filter possibilities are required please refer to the <code>Filter Regex</code> option within the <code>Display Options</code> section below. </i></p>
</div></div>

</li>
<li><code>repoName : String</code>
<div><div>
 Allows to define a repository name. Only artifacts that exist in this repository will be listed in the result set. 
 <p><i> The REST API of Nexus only allows to define a single repository. To harmonize the UI it was decided to limit the possibility to define repositories for Artifactory to a single entry as well. </i></p>
</div></div>

</li>
<li><code>versionRegex : String</code>
<div><div>
 <p>This field allows to define a <a href="https://docs.oracle.com/javase/tutorial/essential/regex/groups.html" rel="nofollow"> Java capturing groups</a> to extract version information from the full artifact path. In a nutshell define a regex and define a part of a string as a group by surrounding it with ( ) brackets to define a group. The first outer group found is used to extract the version information. Following is an example for a Maven artifact with the regex <code>.+/(\d+\.\d+(\.\d+((-CANDIDATE)?-SNAPSHOT)?)?)/.+</code>.</p>
 <table>
  <tbody>
   <tr>
    <th>Path</th>
    <th>Version</th>
   </tr>
   <tr>
    <td>http://localhost:8081/maven-releases/org/example/test/<span>1.0</span>/test-1.0.jar</td>
    <td>1.0</td>
   </tr>
   <tr>
    <td>http://localhost:8081/maven-releases/org/example/test/<span>1.0.5</span>/test-1.0.5.jar</td>
    <td>1.0.5</td>
   </tr>
   <tr>
    <td>http://localhost:8081/maven-releases/org/example/test/<span>1.0.5-CANDIDATE-SNAPSHOT</span>/test-1.0.5-CANDIDATE-SNAPSHOT.jar</td>
    <td>1.0.5-CANDIDATE-SNAPSHOT</td>
   </tr>
  </tbody>
 </table>
</div></div>

</li>
<li><code>repoType : Array / List of String</code>
<ul></ul></li>
<li><code>formatType : Array / List of String</code>
<ul></ul></li>
<li><code>multiSelection : boolean</code>
<div><div>
 Check to allow multiple entries to be selectable.
</div></div>

</li>
<li><code>resultsCount : String</code>
<div><div>
 The number of results to be displayed on the parameter view. The number must be between 1 and 100.
</div></div>

</li>
<li><code>filterRegex : String</code>
<div><div>
 <p>This allows to filter the results returned from the repository before displaying it to the user for selection. Any entry matching the regular expression will be displayed. <br>
   To display all entries either leave the field empty or use the regular expression <code>.+</code>.</p>
 <p>A typical regex for Maven-based artifacts would for example look like <code>.+/(\d+\.\d+(\.\d+(-SNAPSHOT)?)?)/.+</code></p>
</div></div>

</li>
<li><code>sortOrder : String</code>
</li>
<li><code>selectEntry : String</code>
<div><div>
 This option allows to define whether the first or last or any entry matching a regex should get preselected automatically. When regex is selected and the display option is a single value selection (e.g. dropdown, radio button) then the first entry matching the regex wins.
</div></div>

</li>
<li><code>selectRegex : String</code>
<div><div>
 Define a regex to match any of the entries. 
 <br>
 <br>
 <p>Please note that when a regex matches multiple entries but the display style is set to either radio button or dropdown then only the first match wins as those types do not allow for multiple entries to be selected. Furthermore, the regex is always checked against the full path and not just the displayed value.</p>
 <p>Example: <br><br>
   Displayed Value: <code>artifact-1.0.0-SNAPSHOT.jar</code> <br>
   Full Path: <code>http://localhost:8081/foo/bar/com.example.group/artifact/artifact-1.0.0-SNAPSHOT.jar</code></p>
</div></div>

</li>
<li><code>submitValue : String</code>
<div><div>
 <p>By default the plugin will not only submit the label but also some hidden value containing the path of the item represented by the label. Sometimes however one only wants to get the value visible in the label. This option will allow you to choose what information will get passed along to the build script.</p>
 <ul>
  <li>Label + Path (default) - This will send both the label and the hidden path to the build pipeline. Both information are split by a ; (semi-colon).</li>
  <li>Label Only - This will only send the visible label text to the build pipeline.</li>
  <li>Path Only - This will only send a non-visible path of the artifact/repository to the build pipeline.</li>
 </ul>
 <p></p>
 <h3>Example</h3>
 <pre>
Label + Path  = commons-lang3-3.12.0.jar;http://localhost:8082/repository/.../commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
Label Only    = commons-lang3-3.12.0.jar
Path Only     = http://localhost:8082/repository/.../commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
        </pre>
 <p></p>
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>base64File</code><div>
<div><p>Simple file parameter compatible with Pipeline. Transmits file contents as an environment variable in Base64 encoding, so it is best used with fairly small files. Example usage from Declarative Pipeline:</p>
<pre>pipeline {
  agent any
  parameters {
    base64File 'FILE'
  }
  stages {
    stage('Example') {
      steps {
        sh 'echo $FILE | base64 -d &gt; config.yaml'
      }
    }
  }
}
</pre></div>
<ul><li><code>name : String</code>
<div><p>The name of the parameter. Depending on the type of parameter, this may or may not be bound as an environment variable during the build.</p>
<p>If a local filename was given, an environment variable <code><i>paramname</i>_FILENAME</code> will also be set. If the build is triggered via the CLI, the variable will not be set.</p></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>booleanParam</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : boolean</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>buildMasterRelease</code><div>
<div><div>
 <p>Defines a parameter where users can pick an active release from a BuildMaster application. The following environment variables will be injected into the build job:</p>
 <ul>
  <li>BUILDMASTER_APPLICATION_ID</li>
  <li>BUILDMASTER_APPLICATION_NAME</li>
  <li>BUILDMASTER_RELEASE_NUMBER</li>
  <li>BUILDMASTER_LATEST_BUILD_NUMBER</li>
  <li>BUILDMASTER_NEXT_BUILD_NUMBER</li>
 </ul>
 <p>When used within pipeline script the applicationId parameter can contain either the id or name of a BuildMaster application.</p>
 <pre>
parameters {
  buildMasterRelease applicationId: 'TestApplication', description: '', name: 'BuildMaster Release'
}
</pre>
</div></div>
<ul><li><code>name : String</code>
<div><div>
 <p>The name of the parameter.</p>
 <p>This value is used for display purposes only - it is not exposed as an environment variable.</p>
</div></div>

</li>
<li><code>applicationId : String</code>
<div><div>
 The BuildMaster application to obtain the releases for.
</div></div>

</li>
<li><code>showApplicationId : boolean</code>
<div><div>
 Allows a user to select both the Application and Release at build time. 
 <p><b>Triggering a build from an external source</b><br>
   As the two fields are still presented to Jenkins as a single parameter, a slightly different approach is required to to pass in both the application id and release number from other jobs or via a build api request. This is supported by separating the two values using the pipe character '|'. The applicationId is optional, can contain either an Id or applicaton name, and is only supported if this field is checked.</p>
 <p></p><b>Examples</b>
 <ul>
  <li><b>ReleaseNumber:</b> 0.0.0</li>
  <li><b>ApplicationId and ReleaseNumber:</b> 1|0.0.0</li>
  <li><b>ApplicationName and ReleaseNumber:</b> BuildMaster%20Application|0.0.0</li>
 </ul>
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>buildSelector</code><div>
<div><div>
 <p>Defines a parameter that specifies how a Copy Artifact build step should select which build to copy from. Note that this parameter type is easier to use when starting the build from a browser; to specify a value via direct HTTP POST or the CLI, valid XML must be given.</p>
 <p>Be aware that this string value is encoded selector configuration, and not compatible with different plugin versions.</p>
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultSelector</code>
<ul><b>Nested Choice of Objects</b>
<li><code>downstream</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggered from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downstream build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>lastWithArtifacts</code><div>
<ul></ul></div></li>
<li><code>lastCompleted</code><div>
<ul></ul></div></li>
<li><code>$class: 'MultiJobBuildSelector'</code><div>
<ul></ul></div></li>
<li><code>buildParameter</code><div>
<ul><li><code>parameterName : String</code>
<div><div>
 Name of the "build selector" parameter. A parameter with this name should be added in the build parameters section above. There is a special parameter type for choosing the build selector. 
 <p>You can pass not only the parameter name, but also the parameter value itself. This is useful especially used with workflow-plugin.</p>
</div></div>

</li>
</ul></div></li>
<li><code>permalink</code><div>
<ul><li><code>id : String</code>
</li>
</ul></div></li>
<li><code>$class: 'PromotedBuildSelector'</code><div>
<ul><li><code>level : int</code>
</li>
</ul></div></li>
<li><code>latestSavedBuild</code><div>
<ul></ul></div></li>
<li><code>specific</code><div>
<ul><li><code>buildNumber : String</code>
<div><div>
 While this selector is for build numbers (e.g. "22" for build #22), you can also resolve build parameters or environment variables (e.g. "${PARAM}"). The display name of a build and permalinks (e.g. "lastSuccessfulBuild", "lastBuild"...) can be used as well.
</div></div>

</li>
</ul></div></li>
<li><code>lastSuccessful</code><div>
<ul><li><code>stable : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>upstream</code><div>
<ul><li><code>allowUpstreamDependencies : boolean</code> (optional)
</li>
<li><code>fallbackToLastSuccessful : boolean</code> (optional)
</li>
<li><code>upstreamFilterStrategy</code> (optional)
<div><div>
 Jenkins launches only one build when multiple upstreams triggered the same project at the same time. This field specifies from which upstream build to copy artifacts in those cases. "Use the oldest" copies artifacts from the upstream build with the smallest build number (that is, oldest). "Use the newest" copies artifacts from the upstream build with the largest build number (that is, newest). The default value is "Use global setting", which behaves as configured in "Manage Jenkins" &gt; "Configure System".
</div></div>

<ul><li><b>Values:</b> <code>UseGlobalSetting</code>, <code>UseOldest</code>, <code>UseNewest</code></li></ul></li>
</ul></div></li>
<li><code>workspace</code><div>
<ul></ul></div></li>
</ul></li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>reactiveChoice</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>randomName : String</code>
</li>
<li><code>script</code>
<ul><b>Nested Choice of Objects</b>
<li><code>groovyScript</code><div>
<div><div>
 <p>Use a Groovy script to define the parameter.</p>
 <p>The <strong>Script</strong> will be evaluated first, and if it fails (e.g. throws an exception), the <strong>Fallback Script</strong> will be used as a fallback.</p>
 <p>This script integrates with <a href="https://plugins.jenkins.io/script-security" rel="nofollow">Script Security plugin</a> to allow regular Jenkins users to configure this parameter, while limiting what they can do for security.</p>
 <p>If this script is used for any of the <em>HTML</em> choice types of an <em>Active Choices Reactive Reference Parameter</em>, the resulting HTML output will be sanitized to remove everything but basic formatting, like <code>script</code> tags, unless the script runs outside the sandbox. This mode requires approval from a Jenkins administrator to prevent cross-site scripting (HTML) and arbitrary code execution (Groovy).</p>
</div></div>
<ul><li><code>script</code>
<ul><b>Nested Object</b>
<li><code>script : String</code>
</li>
<li><code>sandbox : boolean</code>
<div><div>
 If checked, run this Groovy script in a sandbox with limited abilities. If unchecked, and you are not a Jenkins administrator, you will need to wait for an administrator to approve the script.
</div></div>

</li>
<li><code>classpath</code>
<div><div>
 Additional classpath entries accessible from the script.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
<div><div>
 A path or URL to a JAR file. This path should be approved by an administrator or a user with the RUN_SCRIPT permission, or the script fails. If the file or files are once approved, they are treated approved even located in another path.
</div></div>

</li>
<li><code>oldPath : String</code> (optional)
</li>
<li><code>shouldBeApproved : boolean</code> (optional)
</li>
</ul></li>
<li><code>oldScript : String</code> (optional)
</li>
</ul></li>
<li><code>fallbackScript</code>
<ul><b>Nested Object</b>
<li><code>script : String</code>
</li>
<li><code>sandbox : boolean</code>
<div><div>
 If checked, run this Groovy script in a sandbox with limited abilities. If unchecked, and you are not a Jenkins administrator, you will need to wait for an administrator to approve the script.
</div></div>

</li>
<li><code>classpath</code>
<div><div>
 Additional classpath entries accessible from the script.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
<div><div>
 A path or URL to a JAR file. This path should be approved by an administrator or a user with the RUN_SCRIPT permission, or the script fails. If the file or files are once approved, they are treated approved even located in another path.
</div></div>

</li>
<li><code>oldPath : String</code> (optional)
</li>
<li><code>shouldBeApproved : boolean</code> (optional)
</li>
</ul></li>
<li><code>oldScript : String</code> (optional)
</li>
</ul></li>
</ul></div></li>
<li><code>scriptlerScript</code><div>
<ul><li><code>scriptlerBuilder</code>
<ul><b>Nested Object</b>
<div><div>
 Execute a scriptler script with a job, this allows the automation of many administration tasks or to provide prepared scripts for privileged users.
 <br>
  Select the script you want to execute during the build. The scripts available are the ones marked by the admin as 'allow for users with RunScripts permission'. 
 <p>The parameters can be passed via job params or by creating these in this builder config.</p>
</div></div>
<li><code>builderId : String</code>
</li>
<li><code>scriptId : String</code>
</li>
<li><code>propagateParams : boolean</code>
</li>
<li><code>parameters</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
</ul></li>
<li><code>isSandboxed : boolean</code>
</li>
<li><code>parameters</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>scriptlerScriptId : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>choiceType : String</code>
</li>
<li><code>referencedParameters : String</code>
</li>
<li><code>filterable : boolean</code>
</li>
<li><code>filterLength : int</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>checkboxParameter</code><div>
<ul><li><code>name : String</code>
<div><div>
 The parameter name, which can be used to read the selected value in the build script. Multiple selected values are separated by ",", such as: value1, value2, value3...
</div></div>

</li>
<li><code>pipelineSubmitContent : String</code>
</li>
<li><code>description : String</code> (optional)
<div><div>
 Parameter Description.
</div></div>

</li>
<li><code>protocol</code> (optional)
<div><div>
 Use Protocol: HTTP_HTTPS, FILE_PATH, FILE_PATH stands for file system path, HTTP_HTTPS refers to HTTP or HTTPS protocol.
 <br>
  If you choose HTTP_HTTPS, please fill in the URL of the file in the URI, for example: https://raw.githubusercontent.com/sunweisheng/Jenkins/master/xxx.yaml
 <br>
  If you choose FILE_PATH, please fill in the file path in the URI such as: /opt/xxx.yaml or C:\xxx.yaml
</div></div>

<ul><li><b>Values:</b> <code>HTTP_HTTPS</code>, <code>FILE_PATH</code></li></ul></li>
<li><code>format</code> (optional)
<div><div>
 Select the file format, such as YAML file or JSON file.
</div></div>

<ul><li><b>Values:</b> <code>YAML</code>, <code>JSON</code>, <code>Empty</code></li></ul></li>
<li><code>uri : String</code> (optional)
<div><div>
 Select HTTP_HTTPS, URI, please fill in the URL address. 
 <br>
  Select FILE_PATH, URI, please fill in the file path.
</div></div>

</li>
<li><code>displayNodePath : String</code> (optional)
<div><div>
 Specify the node path used for the check box display content (this format is common to different formats), the root in the file is represented by "//", and the nodes are separated by "/", such as YAML file content:
 <br>
 <br>
  CheckboxParameter:
 <br>
  - key: key-1
 <br>
  value: value-1
 <br>
  - key: key-2
 <br>
  value: value-2
 <br>
  - key: key-3
 <br>
  value: value-3
 <br>
 <br>
  Display node path:
 <br>
  //CheckboxParameter/key
 <br>
  Value node path:
 <br>
  //CheckboxParameter/value
 <br>
  Then, there will be three check boxes, of which the display contents of the check boxes are: key-1, key-2, key-3, and the values obtained after checking the check boxes are: value-1, value-2 , Value-3
 <br>
</div></div>

</li>
<li><code>valueNodePath : String</code> (optional)
<div><div>
 Specify the node path used for the check box selection value (this path format is common to different formats). The root in the file is represented by "//", and the nodes are separated by "/", such as the content of the YAML file:
 <br>
 <br>
  CheckboxParameter:
 <br>
  - key: key-1
 <br>
  value: value-1
 <br>
  - key: key-2
 <br>
  value: value-2
 <br>
  - key: key-3
 <br>
  value: value-3
 <br>
 <br>
  Display node path:
 <br>
  //CheckboxParameter/key
 <br>
  Value node path:
 <br>
  //CheckboxParameter/value
 <br>
  Then, there will be three check boxes, of which the display contents of the check boxes are: key-1, key-2, key-3, and the values obtained after checking the check boxes are: value-1, value-2 , Value-3
 <br>
</div></div>

</li>
<li><code>useInput : boolean</code> (optional)
<div><div>
 Ignore the URI setting of the remote file acquisition or the local file URI setting, and use the input file content as the file content to be read.
</div></div>

</li>
<li><code>submitContent : String</code> (optional)
<div><div>
 After selecting the "Use only the input as the document content" check box, you can directly enter the YAML format or JSON format content of the configuration check box. The content format is set by the "document format" option, and the URI will be ignored after directly entering the configuration content Settings.
</div></div>

</li>
</ul></div></li>
<li><code>activeChoice</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>randomName : String</code>
</li>
<li><code>script</code>
<ul><b>Nested Choice of Objects</b>
<li><code>groovyScript</code><div>
<div><div>
 <p>Use a Groovy script to define the parameter.</p>
 <p>The <strong>Script</strong> will be evaluated first, and if it fails (e.g. throws an exception), the <strong>Fallback Script</strong> will be used as a fallback.</p>
 <p>This script integrates with <a href="https://plugins.jenkins.io/script-security" rel="nofollow">Script Security plugin</a> to allow regular Jenkins users to configure this parameter, while limiting what they can do for security.</p>
 <p>If this script is used for any of the <em>HTML</em> choice types of an <em>Active Choices Reactive Reference Parameter</em>, the resulting HTML output will be sanitized to remove everything but basic formatting, like <code>script</code> tags, unless the script runs outside the sandbox. This mode requires approval from a Jenkins administrator to prevent cross-site scripting (HTML) and arbitrary code execution (Groovy).</p>
</div></div>
<ul><li><code>script</code>
<ul><b>Nested Object</b>
<li><code>script : String</code>
</li>
<li><code>sandbox : boolean</code>
<div><div>
 If checked, run this Groovy script in a sandbox with limited abilities. If unchecked, and you are not a Jenkins administrator, you will need to wait for an administrator to approve the script.
</div></div>

</li>
<li><code>classpath</code>
<div><div>
 Additional classpath entries accessible from the script.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
<div><div>
 A path or URL to a JAR file. This path should be approved by an administrator or a user with the RUN_SCRIPT permission, or the script fails. If the file or files are once approved, they are treated approved even located in another path.
</div></div>

</li>
<li><code>oldPath : String</code> (optional)
</li>
<li><code>shouldBeApproved : boolean</code> (optional)
</li>
</ul></li>
<li><code>oldScript : String</code> (optional)
</li>
</ul></li>
<li><code>fallbackScript</code>
<ul><b>Nested Object</b>
<li><code>script : String</code>
</li>
<li><code>sandbox : boolean</code>
<div><div>
 If checked, run this Groovy script in a sandbox with limited abilities. If unchecked, and you are not a Jenkins administrator, you will need to wait for an administrator to approve the script.
</div></div>

</li>
<li><code>classpath</code>
<div><div>
 Additional classpath entries accessible from the script.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
<div><div>
 A path or URL to a JAR file. This path should be approved by an administrator or a user with the RUN_SCRIPT permission, or the script fails. If the file or files are once approved, they are treated approved even located in another path.
</div></div>

</li>
<li><code>oldPath : String</code> (optional)
</li>
<li><code>shouldBeApproved : boolean</code> (optional)
</li>
</ul></li>
<li><code>oldScript : String</code> (optional)
</li>
</ul></li>
</ul></div></li>
<li><code>scriptlerScript</code><div>
<ul><li><code>scriptlerBuilder</code>
<ul><b>Nested Object</b>
<div><div>
 Execute a scriptler script with a job, this allows the automation of many administration tasks or to provide prepared scripts for privileged users.
 <br>
  Select the script you want to execute during the build. The scripts available are the ones marked by the admin as 'allow for users with RunScripts permission'. 
 <p>The parameters can be passed via job params or by creating these in this builder config.</p>
</div></div>
<li><code>builderId : String</code>
</li>
<li><code>scriptId : String</code>
</li>
<li><code>propagateParams : boolean</code>
</li>
<li><code>parameters</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
</ul></li>
<li><code>isSandboxed : boolean</code>
</li>
<li><code>parameters</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>scriptlerScriptId : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>choiceType : String</code>
</li>
<li><code>filterable : boolean</code>
</li>
<li><code>filterLength : int</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>choice</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>choices : <code>Object</code></code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'ClearCaseUcmBaselineParameterDefinition'</code><div>
<div><div>
 When used, this parameter will display a field at build-time so that the user is able to select the ClearCase UCM baseline from which to download the content to be worked with by this project.
 <br>
  To use this parameter, you MUST also set the SCM to be the ClearCase UCM baseline one, otherwise the build will fail.
 <br>
  The name of the selected ClearCase UCM baseline is available through the <code>CLEARCASE_BASELINE</code> environment variable.
</div></div>
<ul><li><code>pvob : String</code>
<div><div>
 <b>Mandatory</b> — Name of the ClearCase UCM PVOB.
</div></div>

</li>
<li><code>component : String</code>
<div><div>
 <b>Mandatory</b> — Name of the ClearCase UCM component which owns the ClearCase UCM baseline to download at build-time.
 <br>
  At build-time, the user will be able to select one of the ClearCase UCM baselines defined for this component.
</div></div>

</li>
<li><code>promotionLevel : String</code>
<div><div>
 <b>Optional</b> — Promotion level of the ClearCase UCM baseline to be downloaded at build-time.
 <br>
  If no promotion level is set (blank field), then the user will be presented with all the ClearCase UCM baselines belonging to the ClearCase UCM component defined above. If a promotion level is set, then, at build-time, the user will be presented with only the ClearCase UCM baselines which have been promoted to the specified level.
</div></div>

</li>
<li><code>stream : String</code>
<div><div>
 <b>Optional</b> — Stream of the ClearCase UCM baseline to be downloaded at build-time.
 <br>
  If no stream is set (blank field), then the user will be presented with all the ClearCase UCM baselines belonging to the ClearCase UCM component defined above. If a stream is set, then, at build-time, the user will be presented with only the ClearCase UCM baselines which have been defined on this stream.
</div></div>

</li>
<li><code>restrictions : String</code>
<div><div>
 <b>Optional</b> — List of folders (one folder per line) to be actually downloaded from ClearCase.
 <br>
  For this field to be taken into account, you need to check the <b>Use snapshot view</b> field.
 <br>
  If no restrictions are defined, then all the data for the selected ClearCase UCM baseline will be downloaded. If restrictions are defined, then only these folders will be downloaded.
 <br>
  For each folder to download, don't forget to prefix them with the VOB name and the component root dir (usually identical to the component name) this folder belongs to. For example, if you want to download the folder <code>05_impl/0_src</code> which is in the <code>fa4_web</code> component of the <code>fa4</code> VOB, set the value to <code>/fa/fa4_web/05_impl/0_src</code>.
</div></div>

</li>
<li><code>viewName : String</code>
<div><div>
 <b>Mandatory</b> — Name of the ClearCase UCM view which will be created to download the content of the baseline selected at build-time.
 <br>
  You can use several variables within the view name, such as:
 <ul>
  <li><code>CLEARCASE_BASELINE</code>, which is replaced with the name of the ClearCase UCM baseline which is selected at build-time;</li>
  <li><code>JOB_NAME</code>, which is replaced with the name of the job;</li>
  <li><code>USER_NAME</code>, which is replaced with the name of the user running Hudson.</li>
 </ul> The ClearCase UCM view is available as two environment variables:
 <ul>
  <li>The name of the ClearCase UCM view is available as <code>CLEARCASE_VIEWNAME</code>;</li>
  <li>The absolute path to the ClearCase UCM view is available as <code>CLEARCASE_VIEWPATH</code>.</li>
 </ul>
</div></div>

</li>
<li><code>mkviewOptionalParam : String</code>
<div><div>
 <b>Optional</b> — If your build requires additional <code>cleartool </code> arguments when creating a view using <code>mkview</code>, specify them here.
 <br>
  Note that all other arguments (that is, <code>-snapshot</code> —if applicable— and <code>-tag ${CLEARCASE_VIEWNAME}</code> will be appended before these additional arguments.
 <br>
  For documentation on the <code>mkview</code> command, take a look at the <a href="http://publib.boulder.ibm.com/infocenter/cchelp/v7r0m0/index.jsp?topic=/com.ibm.rational.clearcase.cc_ref.doc/topics/ct_mkview.htm" rel="nofollow"> ClearCase 7.0 Information Center</a>.
</div></div>

</li>
<li><code>snapshotView : boolean</code>
</li>
<li><code>useUpdate : boolean</code>
<div><div>
 Check this option to avoid recreating the Clearcase UCM view each time a build is triggered and the baseline has changed. Instead, the view config spec will be updated so that only files that have changed are loaded.
</div></div>

</li>
<li><code>forceRmview : boolean</code>
<div><div>
 Check this option to force the recreation of the ClearCase UCM view each time a build is triggered. If this option is not set and if the baseline which is selected when a new build is triggered is the same as for the previous build, then the ClearCase UCM view won't be recreated.
 <br>
  This setting can be overriden at run-time.
</div></div>

</li>
<li><code>excludeElementCheckedout : boolean</code>
<div><div>
 Check this option to exclude the <code>element * CHECKEDOUT</code> rule from the config spec.
 <br>
  Note that the <code>element * CHECKEDOUT</code> rule is mandatory when using snapshot views.
</div></div>

</li>
<li><code>moreRecentThan : String</code>
<div><div>
 <b>Optional</b> — Use this field to display, when triggering a new build, only the ClearCase UCM baselines which are more recent than a given number of years, or months, or weeks, or days.
 <br>
  Examples: <code>1 year</code>, <code>6 months</code>, <code>1 week</code>, <code>10 days</code>
</div></div>

</li>
<li><code>uuid : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'CloudSelectorParameter'</code><div>
<ul><li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>credentials</code><div>
<div><div>
 Defines a credentials parameter, which you can use during a build. 
 <p><i>For security reasons</i>, the credential is <i>NOT</i> directly exposed, the ID of the credential is exposed.</p> However, the selected credential is available through variable substitution in some other parts of the configuration. The string value will be the ID of the credential. A supporting plugin can thus use the ID to retrieve the selected credential and expose it to the build in an appropriate way.
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code>
<div><div>
 The default credentials to use.
</div></div>

</li>
<li><code>credentialType : String</code>
</li>
<li><code>required : boolean</code>
<div><div>
 When this option is selected, the credentials selection drop down will not provide the empty selection as one of the options. This will not prevent a build without a value if there are no credentials available, for example if the job does not have access to any credentials of the correct type or there is no default value and the user starting the build either does not have any credentials of the correct type in their personal credentials store or they do not have permissions on the job to use credentials from their personal store.
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'CvsTagsParamDefinition'</code><div>
<ul><li><code>name : String</code>
<div><div>
 The name this parameter will be referred to as during any builds.
</div></div>

</li>
<li><code>cvsRoot : String</code>
</li>
<li><code>passwordRequired : boolean</code>
</li>
<li><code>password : String</code>
</li>
<li><code>moduleName : String</code>
<div><div>
 The name of the item to retrieve a list of symbolic names for. This could be a module root (e.g. moduleName), subdirectory (e.g. moduleName/sub/directory/) or individual file (e.g. moduleName/sub/directory/file.name).
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'DateParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>dateFormat : String</code>
<div>This is the Java date format. Like 'yyyyMMdd'.</div>

</li>
<li><code>defaultValue : String</code>
<div>You can create a 'default value' in one of two forms. 
<p>1. Java LocalDate or LocalDateTime code style</p>
<ul>
 <li>LocalDate.now();</li>
 <li>LocalDate.now().plusDays(1);</li>
 <li>LocalDate.now().plusDays(1).plusYears(2);</li>
 <li>LocalDate.now().minusDays(5).minusMonths(3).minusYears(2);</li>
 <li>LocalDateTime.now()</li>
 <li>LocalDateTime.now().minusHours(5).plusMinutes(10).minusSeconds(20);</li>
 <li>LocalDateTime.now().minusDays(5).plusYears(5).plusSeconds(50);</li>
</ul>
<p>2. LocalDate String (This case should match the format of 'dateFormat')</p>
<ul>
 <li>20170501</li>
 <li>2017-05-01</li>
</ul></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'DeployMetaDataParameterDefinition'</code><div>
<div>A deployment meta data parameter allows you to specify environment and build version to deploy that will be used in "Collect deploy metadata" plugin.</div>
<ul><li><code>name : String</code>
</li>
<li><code>environmentKey : String</code>
</li>
<li><code>buildVersion : String</code>
</li>
<li><code>applicationName : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>activeChoiceHtml</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>randomName : String</code>
</li>
<li><code>script</code>
<ul><b>Nested Choice of Objects</b>
<li><code>groovyScript</code><div>
<div><div>
 <p>Use a Groovy script to define the parameter.</p>
 <p>The <strong>Script</strong> will be evaluated first, and if it fails (e.g. throws an exception), the <strong>Fallback Script</strong> will be used as a fallback.</p>
 <p>This script integrates with <a href="https://plugins.jenkins.io/script-security" rel="nofollow">Script Security plugin</a> to allow regular Jenkins users to configure this parameter, while limiting what they can do for security.</p>
 <p>If this script is used for any of the <em>HTML</em> choice types of an <em>Active Choices Reactive Reference Parameter</em>, the resulting HTML output will be sanitized to remove everything but basic formatting, like <code>script</code> tags, unless the script runs outside the sandbox. This mode requires approval from a Jenkins administrator to prevent cross-site scripting (HTML) and arbitrary code execution (Groovy).</p>
</div></div>
<ul><li><code>script</code>
<ul><b>Nested Object</b>
<li><code>script : String</code>
</li>
<li><code>sandbox : boolean</code>
<div><div>
 If checked, run this Groovy script in a sandbox with limited abilities. If unchecked, and you are not a Jenkins administrator, you will need to wait for an administrator to approve the script.
</div></div>

</li>
<li><code>classpath</code>
<div><div>
 Additional classpath entries accessible from the script.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
<div><div>
 A path or URL to a JAR file. This path should be approved by an administrator or a user with the RUN_SCRIPT permission, or the script fails. If the file or files are once approved, they are treated approved even located in another path.
</div></div>

</li>
<li><code>oldPath : String</code> (optional)
</li>
<li><code>shouldBeApproved : boolean</code> (optional)
</li>
</ul></li>
<li><code>oldScript : String</code> (optional)
</li>
</ul></li>
<li><code>fallbackScript</code>
<ul><b>Nested Object</b>
<li><code>script : String</code>
</li>
<li><code>sandbox : boolean</code>
<div><div>
 If checked, run this Groovy script in a sandbox with limited abilities. If unchecked, and you are not a Jenkins administrator, you will need to wait for an administrator to approve the script.
</div></div>

</li>
<li><code>classpath</code>
<div><div>
 Additional classpath entries accessible from the script.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
<div><div>
 A path or URL to a JAR file. This path should be approved by an administrator or a user with the RUN_SCRIPT permission, or the script fails. If the file or files are once approved, they are treated approved even located in another path.
</div></div>

</li>
<li><code>oldPath : String</code> (optional)
</li>
<li><code>shouldBeApproved : boolean</code> (optional)
</li>
</ul></li>
<li><code>oldScript : String</code> (optional)
</li>
</ul></li>
</ul></div></li>
<li><code>scriptlerScript</code><div>
<ul><li><code>scriptlerBuilder</code>
<ul><b>Nested Object</b>
<div><div>
 Execute a scriptler script with a job, this allows the automation of many administration tasks or to provide prepared scripts for privileged users.
 <br>
  Select the script you want to execute during the build. The scripts available are the ones marked by the admin as 'allow for users with RunScripts permission'. 
 <p>The parameters can be passed via job params or by creating these in this builder config.</p>
</div></div>
<li><code>builderId : String</code>
</li>
<li><code>scriptId : String</code>
</li>
<li><code>propagateParams : boolean</code>
</li>
<li><code>parameters</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
</ul></li>
<li><code>isSandboxed : boolean</code>
</li>
<li><code>parameters</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>scriptlerScriptId : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>choiceType : String</code>
</li>
<li><code>referencedParameters : String</code>
</li>
<li><code>omitValueField : boolean</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>editableChoice</code><div>
<div><div>
 <p>Display choices but allows inputting any values even not in choices. Works just like suggestion.</p>
 <p>To use in pipeline: <code></code></p>
 <pre><code>editableChoice(
  name: 'PARAM1',
  choices: ['Apple', 'Grape', 'Orange'],
  // belows are optional paramters
  defaultValue: 'Grape',
  restrict: true,
  filterConfig: filterConfig(
    prefix: true,
    caseInsensitive: true,
  ),
)
</code></pre>
 <p></p>
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>choices : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>choicesWithText : String</code> (optional)
<div><div>
 Choices delimited with new line letters like: 
 <pre>choice1
choice2
choice3
</pre>
</div></div>

</li>
<li><code>defaultValue : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>filterConfig</code> (optional)
<div><div>
 Filter choices with input value. It works just like suggestion.
</div></div>

<ul><b>Nested Object</b>
<li><code>caseInsensitive : boolean</code> (optional)
</li>
<li><code>prefix : boolean</code> (optional)
<div><div>
 <p>Display values when their prefix matches the input. Otherwise, display values when they contains the input.</p>
 <p>Example:</p>
 <dl>
  <dt>
   Choices
  </dt>
  <dd>
   <code>
    <pre>apple
orange
grape
</pre></code>
  </dd>
  <dt>
   Current input
  </dt>
  <dd>
   ap
  </dd>
  <dt>
   values displayed when "Filter only with prefix" is enabled
  </dt>
  <dd>
   <code>
    <pre>apple</pre></code>
  </dd>
  <dt>
   values displayed when "Filter only with prefix" is disabled
  </dt>
  <dd>
   <code>
    <pre>apple
grape</pre></code>
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
</ul></li>
<li><code>restrict : boolean</code> (optional)
<div><div>
 Restrict input values to be a value in choices.
</div></div>

</li>
<li><code>withDefaultValue</code> (optional)
<div><div>
 The top most value will be the default value if not specified.
</div></div>

<ul><b>Nested Object</b>
<li><code>defaultValue : String</code>
</li>
</ul></li>
</ul></div></li>
<li><span><a href="/doc/pipeline/steps/params/extensiblechoiceparameterdefinition"><code>$class: 'ExtensibleChoiceParameterDefinition'</code></a></span></li>
<li><code>file</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>fileSystemList</code><div>
<div><div>
 The <strong>filesystem-list-parameter-plugin</strong> lists file system object names of a directory. One of the object names can be selected as build parameter. In addition the objects can be filtered: <code>ALL, DIRECTORY, FILE, SYMLINK</code>. The order of the list can be reversed.
</div></div>
<ul><li><code>name : String</code>
<div><div>
 The name of the parameter.
</div></div>

</li>
<li><code>nodeName : String</code>
</li>
<li><code>path : String</code>
<div><div>
 The path of the directory containing the file system objects.
</div></div>

</li>
<li><code>defaultValue : String</code>
<div><div>
 Only one value can be pre-selected as default when the value is contained in object list. (Multi select default is not supported for now!)
</div></div>

</li>
<li><code>selectedType : String</code>
<div><div>
 Objects in "Path" can be filtered: <code>ALL, DIRECTORY, FILE, SYMLINK</code>.
</div></div>

</li>
<li><code>formSelectType : String</code>
</li>
<li><code>regexIncludePattern : String</code>
<div><div>
 The regular expression matching the file system objects to be excluded in parameter selection. (Will be ignored if empty) See Standard <a href="http://download.oracle.com/javase/1.4.2/docs/api/java/util/regex/Pattern.html" rel="nofollow">Java regular expression</a>.
</div></div>

</li>
<li><code>regexExcludePattern : String</code>
<div><div>
 The regular expression matching the file system objects to be included in parameter selection. (Will be ignored if empty) See Standard <a href="http://download.oracle.com/javase/1.4.2/docs/api/java/util/regex/Pattern.html" rel="nofollow">Java regular expression</a>.
</div></div>

</li>
<li><code>sortByLastModified : boolean</code>
<div><div>
 If true, the list of the parameter values will be sorted by last modified file attribute. Default order is sort by parameter value.
</div></div>

</li>
<li><code>sortReverseOrder : boolean</code>
<div><div>
 If true, the list of the parameter values will be sorted in reverse order.
</div></div>

</li>
<li><code>includePathInValue : boolean</code>
<div><div>
 If true, the path will be concatenated with the selected value.
</div></div>

</li>
<li><code>description : String</code> (optional)
<div><div>
 The type of the file system objects that will be filtered from path.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GeneratorChoiceParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>choices : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'GeneratorKeyValueParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>trim : boolean</code> (optional)
<div><div>
 Strip whitespace from the beginning and end of the string.
</div></div>

</li>
</ul></div></li>
<li><code>gitParameter</code><div>
<div><div>
 <p>When used, this parameter will present at build-time a choice to select a Git tag (or revision number) which set a parameter for parametrized build.</p>
 <p>Be aware that git does not allow us get additional information (like author/commmit date) from a remote URL this plugin will silently clone the project when your workspace is empty. This may take a long time when we have a slow connection and/or the checkout is big.</p>
 <p>Often the parameter defined in the "Name" field is used to specify the branch of the git checkout.</p>
</div></div>
<ul><li><code>name : String</code>
<div><div>
 The name of the parameter.
</div></div>

</li>
<li><code>type : String</code>
<div><div>
 The type of the list of parameters: 
 <ul>
  <li>Tag - list of all commit tags in repository - returns Tag Name</li>
  <li>Branch - list of all branch in repository - returns Branch Name</li>
  <li>Revision - list of all revision sha1 in repository followed by its author and date - returns Tag SHA1</li>
 </ul>
</div></div>

</li>
<li><code>defaultValue : String</code>
<div><div>
 This value is returned when the list is empty or if an error occurs while retrieving data.
</div></div>

</li>
<li><code>branch : String</code>
<div><div>
 Name of branch to look in. Used only if listing revisions.
</div></div>

</li>
<li><code>branchFilter : String</code>
<div><div>
 Regex used to filter displayed branches. If blank, the filter will default to ".*".
 <br>
  Remote branches will be listed with the remote name first. E.g., "origin/master"
</div></div>

</li>
<li><code>tagFilter : String</code>
<div><div>
 This parameter is used to get tag from git.
 <br>
  If is blank, parameter is set to "*".
 <br>
  Properly is executed command: git ls-remote -t &lt;repository&gt; "*" or git ls-remote -t &lt;repository&gt; "$tagFilter".
 <br><a href="https://git-scm.com/docs/git-ls-remote.html" rel="nofollow">git-ls-remote</a> documentation.
</div></div>

</li>
<li><code>sortMode</code>
<div><div>
 Select how to sort the downloaded parameters. Only applies to a branch or a tag. 
 <ul>
  <li>none</li>
  <li>ascending smart</li>
  <li>descending smart</li>
  <li>ascending</li>
  <li>descending</li>
 </ul> When smart sorting is chosen, the compare treats a sequence of digits as a single character.
</div></div>

<ul><li><b>Values:</b> <code>NONE</code>, <code>ASCENDING_SMART</code>, <code>DESCENDING_SMART</code>, <code>ASCENDING</code>, <code>DESCENDING</code></li></ul></li>
<li><code>selectedValue</code>
<div><div>
 Which value is selected, after loaded parameters.
 <br>
  If you choose 'default', but default value is not present on the list, nothing is selected.
</div></div>

<ul><li><b>Values:</b> <code>NONE</code>, <code>TOP</code>, <code>DEFAULT</code></li></ul></li>
<li><code>useRepository : String</code>
<div><div>
 If in the task are defined multiple repositories, this option specifies which the repository is taken into account on getting data.
 <br>
  If the option is not defined, is taken a first defined repository.
 <br>
  This option is a regular expression, which is compared to the 'Repository URL'.
</div></div>

</li>
<li><code>quickFilterEnabled : boolean</code>
<div><div>
 When this option is enabled will show a text field.
 <br>
  Parameter is filtered on the fly.
</div></div>

</li>
<li><code>description : String</code> (optional)
<div><div>
 A description that will be shown to the user later.
</div></div>

</li>
<li><code>listSize : String</code> (optional)
<div><div>
 Specify the number of items the list will display. A value of 0 will display as a DropDown list.
</div></div>

</li>
<li><code>requiredParameter : boolean</code> (optional)
<div><div>
 When this option is selected the user must select an option or an error will be thrown(default values are ignored)
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GlobalVariableStringParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>trim : boolean</code> (optional)
<div><div>
 Strip whitespace from the beginning and end of the string.
</div></div>

</li>
</ul></div></li>
<li><code>imageTag</code><div>
<div><div>
 This parameter lets the user specity image tag to be used at the start of each build.
</div></div>
<ul><li><code>name : String</code>
<div><div>
 The name of the parameter
 <br>
  These parameters are exposed to build as environment variables.
</div></div>

</li>
<li><code>image : String</code>
<div><div>
 Full Image name for tags to be listed. One Docker Hub offical most used image (e.g ubuntu) are usualy in library namespace: library/ubuntu
</div></div>

</li>
<li><code>filter : String</code>
<div><div>
 Regular expression to filter image tag e.g. v(\d+\.)*\d+ for tags like v23.3.2
</div></div>

</li>
<li><code>registry : String</code>
<div><div>
 A Docker V2 API registry where to locate images and tags.
 <br>
  You can change the default value in Jenkins Configuration Page.
</div></div>

</li>
<li><code>credentialId : String</code>
<div><div>
 Credential (username with password) to authenticate against the registry
</div></div>

</li>
<li><code>description : String</code> (optional)
<div><div>
 A description that will be shown to the user later.
</div></div>

</li>
<li><code>defaultTag : String</code> (optional)
<div><div>
 Specify a tag value that should get preselected selected as default (e.g.: v1.0 for the image myImage:v1.0)
 <br>
  NOTE: the defaultTag will get string compared to the fetched tags and if no equal exists will get ignored
</div></div>

</li>
<li><code>tagOrder</code> (optional)
<div><div>
 <div>
  Allows the user to alter the ordering of the ImageTags in the build parameter.
 </div>
 <br>
 <div>
  <strong>Natural Ordering</strong> ... same Ordering as the tags had in prior versions
  <br><strong>Reverse Natural Ordering</strong> ... the reversed original ordering
  <br><strong>Descending Versions</strong> ... attempts to pars the tags to a version and order them descending
  <br><strong>Ascending Versions</strong> ... attempts to pars the tags to a version and order them ascending
  <br>
 </div>
 <br>
 <div>
  <strong>WARNING:</strong>
  <br>
   Careful with Versioned sorting, this works best with <a href="https://semver.org/" rel="nofollow">semver</a> or maven version compliant ImageTags, but won't work at all under certain circumstances!
  <br>
   The conversion from tags to versions can fail in certain cases and cause the sorting to fail, which will result in an empty selection list.
  <br>
   In such a case the user will get notified about a parameter misconfiguration.
 </div>
</div></div>

<ul><li><b>Values:</b> <code>NATURAL</code>, <code>REV_NATURAL</code>, <code>DSC_VERSION</code>, <code>ASC_VERSION</code></li></ul></li>
<li><code>verifySsl : boolean</code> (optional)
<div><div>
 Specify if Certificate validation will be performed
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'InheritableStringParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>inheritanceMode : String</code>
<div><div>
 This field selects, how this parameter is altered, when a child project overrides its value. For example, you may provide a variable "A" here with the value "Foo", while a child also defines "A", but with the value "Bar". 
 <p>The mode that you select here will influence the final value of the parameter, when you build the child:</p>
 <ul>
  <li>If you select "Overwritable", the build will just get the value "Bar"</li>
  <li>If you select "Extensible", the build will get the value "FooBar" (or "Foo Bar", depending on the "Whitespace Mode" below)</li>
  <li>If you select "Fixed", then the build will fail, since this project prohibited changing the value.</li>
 </ul> Do note, that this field only has an effect on the <b>child</b> parameter — not the other way around. In other words, this mode decides what will happen in the future, not what happens "now" to the current or earlier overrides.
</div></div>

</li>
<li><code>mustHaveDefaultValue : boolean</code>
</li>
<li><code>mustBeAssigned : boolean</code>
</li>
<li><code>whitespaceMode : String</code>
<div><div>
 This field allows you to select, how whitespaces at the start/end of the parameter should be handled, when a build is started: 
 <ol>
  <li>Trim all leading/trailing whitespace from the entered value.</li>
  <li>Keep the whitespace intact, exactly as the user entered it.</li>
  <li>Keep the whitespace, but make sure that at least a single space is added to the front of the value, in case it <b>extends</b> a parameter with the same name from a parent.</li>
 </ol> Select the first option, if you know the parameter should not have leading or trailing spaces.
 <br>
  Select the third option, if you are constructing a parameter that is used in flag- or command-construction. For example Compiler Flags.
 <br>
  Otherwise, or if in doubt, just select the second option. 
 <p>Do note that, if trimming is selected, this has an effect on both the default value used for automatically started builds, as well as user-initiated builds where the user had a chance to alter the parameter value.</p>
</div></div>

</li>
<li><code>isHidden : boolean</code>
<div><div>
 If this is checked, the parameter will be hidden behind an "advanced" button on the screen for starting a build. For sanity's sake, you should set this for all mandatory variables that are rarely changed.
</div></div>

</li>
<li><code>defaultValue : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>trim : boolean</code> (optional)
<div><div>
 Strip whitespace from the beginning and end of the string.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'InheritableStringParameterReferenceDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>trim : boolean</code> (optional)
<div><div>
 Strip whitespace from the beginning and end of the string.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'JFrogPipelinesParameter'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>trim : boolean</code> (optional)
<div><div>
 Strip whitespace from the beginning and end of the string.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'JavaParameterDefinition'</code><div>
<div><div>
 This parameter lets the user specify JDK to be used at the star of each build.
</div></div>
<ul><li><code>name : String</code>
<div><div>
 The name to be displayed on the build parameters page.
</div></div>

</li>
<li><code>defaultJDK : String</code>
<div><div>
 The JDK that will be used if the user does not specify one.
</div></div>

</li>
<li><code>allowedJDKs : Array / List of String</code>
<div><div>
 The JDKs that can be chosen from on the build parameters page.
</div></div>

<ul></ul></li>
<li><code>description : String</code> (optional)
<div><div>
 The description to be shown on the build parameters page.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'JiraIssueParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>jiraIssueFilter : String</code>
<div><div>
 Specify the JQL search on Jira instance. For a build, Jenkins will run this query, populate a drop-down list box, then ask the user to select one.
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
<li><code>altSummaryFields : String</code> (optional)
<div><div>
 <p>Optionally, specify a comma-delimited list of fields to use instead of the issue summary as the title in the dropdown. Fields will be concatenated with spaces.</p>
 <p>Example:</p><strong>Field1,Field2</strong>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'JiraVersionParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>jiraProjectKey : String</code>
<div><div>
 <p>Specify the project key. A project key is the all capitals part before the issue number in Jira.</p>
 <p>(<strong>EXAMPLE</strong>-100)</p>
</div></div>

</li>
<li><code>jiraReleasePattern : String</code>
<div><div>
 <p>Specify a regular expression which release names have to match to be listed. Leave this blank to match all issues.</p>
 <p>Example:</p><strong>v[0-9]+([.][0-9]+)+</strong> will match v1.0.1, v123, v12.0.1
</div></div>

</li>
<li><code>jiraShowReleased : String</code>
</li>
<li><code>jiraShowArchived : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>jsonEditor</code><div>
<ul><li><code>name : String</code>
<div><div>
 The name of the JsonEditor parameter. This name must be unique within a set of parameters added to a single choice (InputStep). The name must start with a Latin alphabet character and may contain 1-63 more Latin alphabet characters, Latin digits, hyphens ('-'), or underscores ('_').
</div></div>

</li>
<li><code>description : String</code> (optional)
<div><div>
 The description for the JsonEditor parameter.
</div></div>

</li>
<li><code>options : String</code> (optional)
<div><div>
 Extra options for the JsonEditor form. See <a href="https://github.com/json-editor/json-editor#options" rel="nofollow">options</a> for details.
</div></div>

</li>
<li><code>schema : String</code> (optional)
<div><div>
 The scheme for the JsonEditor form. See <a href="https://github.com/json-editor/json-editor#json-schema-support" rel="nofollow">json-schema-support</a> for details.
</div></div>

</li>
<li><code>startval : String</code> (optional)
<div><div>
 The initial values for the JsonEditor form. This value should be valid against the schema.
 <br>
  Leave empty to use the defaults from the schema.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'LabelParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code>
</li>
<li><code>allNodesMatchingLabel : boolean</code>
</li>
<li><code>nodeEligibility</code>
<div><div>
 Defines how selected offline nodes should be handled. 
 <ul>
  <li><b>All Nodes</b> - trigger the job on all selected nodes, regardless of their online/offline state</li>
  <li><b>Ignore Offline Nodes</b> - trigger the job only on nodes being online and having an executor</li>
  <li><b>Ignore Temp Offline Nodes</b> - trigger the job on all selected nodes except on the ones currently manually marked as offline</li>
 </ul>
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'AllNodeEligibility'</code><div>
<ul></ul></div></li>
<li><code>$class: 'IgnoreOfflineNodeEligibility'</code><div>
<ul></ul></div></li>
<li><code>$class: 'IgnoreTempOfflineNodeEligibility'</code><div>
<ul></ul></div></li>
</ul></li>
<li><code>triggerIfResult : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>listGitBranches</code><div>
<div><div>
 <p>When used, this parameter will display a field at build-time so that user is able to select a git branch or tag as a parameter for parametrized build..</p>
 <p>Note that this plugin is specifically designed for pipeline jobs that do not configure SCM but still want to see remote repository branches or tags before build begins.</p>
 <p>The plugin is highly motivated by <a href="https://wiki.jenkins.io/display/JENKINS/Git+Parameter+Plugin" rel="nofollow">Git Parameter Plugin</a>.</p>
 <p>But unlike <a href="https://wiki.jenkins.io/display/JENKINS/Git+Parameter+Plugin" rel="nofollow">Git Parameter Plugin</a>, this plugin will not change working space at all at build-time</p>
</div></div>
<ul><li><code>name : String</code>
<div><div>
 The name of the parameter.
</div></div>

</li>
<li><code>remoteURL : String</code>
<div><div>
 Specify the Git repository URL.
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
<li><code>defaultValue : String</code>
<div><div>
 This value is returned when list is empty.
</div></div>

</li>
<li><code>sortMode</code>
<div><div>
 Select how to sort the downloaded parameters. Only applies to a branch or a tag. 
 <ul>
  <li>none</li>
  <li>ascending smart</li>
  <li>descending smart</li>
  <li>ascending</li>
  <li>descending</li>
 </ul> When smart sorting is chosen, the compare treats a sequence of digits as a single character.
</div></div>

<ul><li><b>Values:</b> <code>NONE</code>, <code>ASCENDING_SMART</code>, <code>DESCENDING_SMART</code>, <code>ASCENDING</code>, <code>DESCENDING</code></li></ul></li>
<li><code>selectedValue</code>
<div><div>
 When this option is enabled will show a text field.
 <br>
  Parameter is filtered on the fly.
</div></div>

<ul><li><b>Values:</b> <code>NONE</code>, <code>TOP</code>, <code>DEFAULT</code></li></ul></li>
<li><code>quickFilterEnabled : boolean</code>
<div><div>
 When this option is enabled will show a text field.
 <br>
  Parameter is filtered on the fly.
</div></div>

</li>
<li><code>type : String</code>
<div><div>
 The type of the list of parameters: 
 <ul>
  <li>Tag - list of all commit tags in repository - returns Tag Name</li>
  <li>Branch - list of all branch in repository - returns Branch Name</li>
 </ul>
</div></div>

</li>
<li><code>tagFilter : String</code>
<div><div>
 This parameter is used to get tag from git.
 <br>
  If is blank, parameter is set to "*".
 <br>
  Properly is executed command: git tag -l "*" or git tag -l "$tagFilter".
</div></div>

</li>
<li><code>branchFilter : String</code>
<div><div>
 Specify a <a href="http://download.oracle.com/javase/1.5.0/docs/api/java/util/regex/Pattern.html" rel="nofollow">regular expression</a> which will be used to filter the branches which are actually displayed when triggering a new build.
</div></div>

</li>
<li><code>listSize : String</code>
<div><div>
 Specify the number of items the list will display. A value of 0 will display as a DropDown list.
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'ListSubversionTagsParameterDefinition'</code><div>
<div><div>
 When used, this parameter will display a field at build-time so that the user is able to select a Subversion tag from which to create the working copy for this project. 
 <p>Once the two fields <strong>Name</strong> and <strong>Repository URL</strong> are set, you must</p>
 <ol>
  <li>ensure the job uses <strong>Subversion</strong> and</li>
  <li>set the <strong>Repository URL</strong> field of <strong>Subversion</strong> by concatenating the two fields of this parameter.</li>
 </ol> For instance, if <strong> Name</strong> is set to <code>SVN_TAG</code> and <strong>Repository URL</strong> is set to <code>https://svn.jenkins-ci.org/tags</code>, then <strong>Subversion</strong>'s <strong>Repository URL</strong> must be set to <code>https://svn.jenkins-ci.org/tags/$SVN_TAG</code>. 
 <p>Notice that you can set the <strong>Repository URL</strong> field to a Subversion repository root rather than just pointing to a <code>tags</code> dir (ie, you can set it to <code>https://svn.jenkins-ci.org</code> rather than <code>https://svn.jenkins-ci.org/tags</code>). In that case, if this repository root contains the <code>trunk</code>, <code>branches</code> and <code>tags</code> folders, then the dropdown will allow the user to pick the trunk, or a branch, or a tag.</p>
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>tagsDir : String</code>
<div><div>
 Specify the Subversion repository URL which contains the tags to be listed when triggering a new build. 
 <p>You can also specify the root of a Subversion repository: If this root contains the <code>trunk</code>, <code>branches</code> and <code>tags</code> folders, then the dropdown will display <code>trunk</code>, all the branches and all the tags. If the root does not contain these three folders, then all its subfolders are listed in the dropdown.</p>
 <p>When you enter the URL, Jenkins automatically checks if it can connect to it. If access requires authentication, you'll be prompted for the necessary credential. If you already have a working credential but would like to change it for some other reasons, you can <a rel="nofollow">manage credentials</a> and specify a different credential.</p>
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
<li><code>tagsFilter : String</code>
<div><div>
 Specify a <a href="http://download.oracle.com/javase/1.5.0/docs/api/java/util/regex/Pattern.html" rel="nofollow"> regular expression</a> which will be used to filter the tags which are actually displayed when triggering a new build.
</div></div>

</li>
<li><code>defaultValue : String</code>
<div><div>
 For features such as SVN polling a default value is required. If job will only be started manually, this field is not necessary.
</div></div>

</li>
<li><code>maxTags : String</code>
<div><div>
 The maximum number of tags to display in the dropdown. Any non-number value will default to all.
</div></div>

</li>
<li><code>reverseByDate : boolean</code>
<div><div>
 Check this option so that tags are sorted from the newest to the oldest. 
 <p>If this option is checked, the <b>Sort Z to A</b> one won't be taken into account.</p>
</div></div>

</li>
<li><code>reverseByName : boolean</code>
<div><div>
 Check this option so that tags are displayed in reverse order (sorted Z to A). 
 <p>Notice that if <b>Sort newest first</b> is checked, this option won't be taken into account.</p>
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'MatrixCombinationsParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultCombinationFilter : String</code>
<div><div>
 <p>A Groovy expression to specify which combinations are checked by default. They are also combinations which is built in a scheduled build. If not specified, the combination filter of this multi-configuration project is used. Also see <a rel="nofollow">help of the combination filter</a>.</p>
 <p>Note that you cannot enable combinations which disabled by the combination filter of the project.</p>
</div></div>

</li>
<li><code>shortcutList</code>
<div><div>
 Links to check a set of combinations. Combinations to check are calculated with the last build in the build page or with the build to rebuild in the rebuild page (when <a href="https://wiki.jenkins-ci.org/display/JENKINS/Rebuild+Plugin" rel="nofollow">Rebuild plugin</a> is installed).
</div></div>

<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'All'</code><div>
<div><div>
 Check all enable combinations.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'CombinationFilterShortcut'</code><div>
<div><div>
 Decide combinations to check with a combinations filter.
</div></div>
<ul><li><code>name : String</code>
<div><div>
 The name displayed as the shortcut link.
</div></div>

</li>
<li><code>combinationFilter : String</code>
<div><div>
 A Groovy expression to decide combinations to check.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'None'</code><div>
<div><div>
 Uncheck all combinations.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'PreviousShortcut'</code><div>
<div><div>
 Check combinations built in the previous build.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'ResultShortcut'</code><div>
<div><div>
 Check combinations with specific results in the previous build.
</div></div>
<ul><li><code>name : String</code>
<div><div>
 The name displayed as the shortcut link.
</div></div>

</li>
<li><code>exact : boolean</code>
<div><div>
 Only checks child builds running exactly in the previous build.
</div></div>

</li>
<li><code>resultsToCheck : Array / List of String</code>
<div><div>
 Results of child builds to check.
</div></div>

<ul></ul></li>
</ul></div></li>
</ul></li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>mavenMetadataVersions</code><div>
<div><div>
 This parameter allows the resolution of maven artifact versions by contacting the repository and reading the <a href="http://docs.codehaus.org/display/MAVEN/Repository+Metadata" rel="nofollow">maven-metadata.xml</a>. 
 <p></p> If you named your parameter "MY_JAR" and have configured all values correctly. Then the following parameters will be set for the build step: 
 <ul>
  <li>MY_JAR_VERSION - the version you selected in the dropdown or that was selected as part of an automated build</li>
  <li>MY_JAR_ARTIFACT_URL - the full URL to the actual artifact selected. You can use something like "wget" to download that artifact and do something with it.</li>
  <li>MY_JAR_GROUP_ID - echoes back your configuration</li>
  <li>MY_JAR_ARTIFACT_ID - echoes back your configuration</li>
  <li>MY_JAR_CLASSIFIER - echoes back your configuration</li>
  <li>MY_JAR_PACKAGING - echoes back your configuration</li>
 </ul>
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>repoBaseUrl : String</code>
</li>
<li><code>groupId : String</code>
</li>
<li><code>artifactId : String</code>
</li>
<li><code>packaging : String</code>
</li>
<li><code>classifier : String</code>
</li>
<li><code>versionFilter : String</code>
<div><div>
 Specify a <a href="http://docs.oracle.com/javase/6/docs/api/java/util/regex/Pattern.html" rel="nofollow"> regular expression</a> which will be used to filter the versions which are actually displayed when triggering a new build.
</div></div>

</li>
<li><code>sortOrder : String</code>
</li>
<li><code>defaultValue : String</code>
<div><div>
 For features such as SVN polling a default value is required. If job will only be started manually, this field is not necessary.
 <br>
  There are 4 special default values which will be evaluated at runtime: 
 <ul>
  <li>FIRST - will evaluate to the first item in the drop-down that would have been presented had the build been executed manually.</li>
  <li>LAST - will evaluate to the last item in the drop-down that would have been presented had the build been executed manually.</li>
  <li>RELEASE - will evaluate to the version marked as RELEASE in the <a href="http://docs.codehaus.org/display/MAVEN/Repository+Metadata" rel="nofollow">repository metadata</a> for the configured artifact. The versionFilter even if defined is ignored for this default value.</li>
  <li>LATEST - will evaluate to the version marked as LATEST in the <a href="http://docs.codehaus.org/display/MAVEN/Repository+Metadata" rel="nofollow">repository metadata</a> for the configured artifact. The versionFilter even if defined is ignored for this default value.</li>
 </ul>
</div></div>

</li>
<li><code>maxVersions : String</code>
<div><div>
 The maximum number of versions to display in the drop-down. Any non-number value as well as 0 or negative values will default to all.
</div></div>

</li>
<li><code>currentArtifactInfoUrl : String</code>
<div><div>
 The URL where an information resource about the currently used artifact can be requested. If the URL is provided and valid, the information will be displayed next to the drop-down. Otherwise not artifact information will be displayed.
</div></div>

</li>
<li><code>currentArtifactInfoLabel : String</code>
<div><div>
 An informational label that will be displayed in front of the aritfact information. When no label is specified, the default label <i>Currently used artifact</i> will be displayed. Any label will only be displayed when a valid <i>Current Artifact Info URL</i> is configured.
</div></div>

</li>
<li><code>currentArtifactInfoPattern : String</code>
<div><div>
 A pattern that describes the part of the artifact information resources' content to be displayed: 
 <ul>
  When no pattern is specified, the whole content will be displayed.
 </ul>
 <ul>
  When a standard pattern is specified, only its first match in the content will be displayed.
 </ul>
 <ul>
  When a pattern with a capturing group is specified, only the first group of its first match in the content will be displayed.
 </ul>
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>multiselect</code><div>
<ul><li><code>name : String</code>
<div><div>
 Name of the parameter displayed in forms.
</div></div>

</li>
<li><code>description : String</code> (optional)
<div><div>
 Description that is displayed as a help for users running a parameterized build, as to what the parameter is used for.
</div></div>

</li>
<li><code>decisionTree</code> (optional)
<ul><b>Nested Object</b>
<li><code>itemList</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>label : String</code> (optional)
</li>
<li><code>value : String</code> (optional)
</li>
<li><code>children</code> (optional)
<ul><b>Array / List of Nested Object</b>
</ul></li>
</ul></li>
<li><code>variableDescriptions</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>label : String</code> (optional)
</li>
<li><code>variableName : String</code> (optional)
</li>
</ul></li>
</ul></li>
<li><code>format</code> (optional)
<ul><li><b>Values:</b> <code>CSV</code></li></ul></li>
</ul></div></li>
<li><code>$class: 'NetstormTestParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>keyword : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'NodeParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultSlaves : Array / List of String</code>
<ul></ul></li>
<li><code>allowedSlaves : Array / List of String</code>
<ul></ul></li>
<li><code>triggerIfResult : String</code>
</li>
<li><code>nodeEligibility</code>
<div><div>
 Defines how selected offline nodes should be handled. 
 <ul>
  <li><b>All Nodes</b> - trigger the job on all selected nodes, regardless of their online/offline state</li>
  <li><b>Ignore Offline Nodes</b> - trigger the job only on nodes being online and having an executor</li>
  <li><b>Ignore Temp Offline Nodes</b> - trigger the job on all selected nodes except on the ones currently manually marked as offline</li>
 </ul>
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'AllNodeEligibility'</code><div>
<ul></ul></div></li>
<li><code>$class: 'IgnoreOfflineNodeEligibility'</code><div>
<ul></ul></div></li>
<li><code>$class: 'IgnoreTempOfflineNodeEligibility'</code><div>
<ul></ul></div></li>
</ul></li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>ontrackChoiceParam</code><div>
<div><div>
 <p>Gets a list of parameter value to choose from, using the execution of a <a href="https://github.com/nemerosa/ontrack/wiki/DSL" rel="nofollow">Ontrack DSL</a> script.</p>
 <p>The script is expected to return a list of objects (a single object will be converted into a singleton list) and the parameter value of each item will be extracted from this object using the property defined in the <i>Value property</i> field.</p>
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>dsl : String</code>
</li>
<li><code>sandbox : boolean</code>
</li>
<li><code>valueProperty : String</code>
</li>
<li><code>injectProperties : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>ontrackMultiChoiceParam</code><div>
<div><div>
 <p>Gets a list of parameter value to choose from, using the execution of a <a href="https://github.com/nemerosa/ontrack/wiki/DSL" rel="nofollow">Ontrack DSL</a> script.</p>
 <p>The script is expected to return a list of objects (a single object will be converted into a singleton list) and the parameter value of each item will be extracted from this object using the property defined in the <i>Value property</i> field.</p>
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>dsl : String</code>
</li>
<li><code>sandbox : boolean</code>
</li>
<li><code>valueProperty : String</code>
</li>
<li><code>injectProperties : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>ontrackSingleParam</code><div>
<div><div>
 <p>Gets a parameter value from the execution of a <a href="https://github.com/nemerosa/ontrack/wiki/DSL" rel="nofollow">Ontrack DSL</a> script.</p>
 <p>The script is expected to return a single object and the value of the parameter will be extracted from this object using the property defined in the <i>Value property</i> field.</p>
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>dsl : String</code>
</li>
<li><code>sandbox : boolean</code>
</li>
<li><code>valueProperty : String</code>
</li>
<li><code>injectProperties : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'PackageChoiceParameterDefinition'</code><div>
<div><div>
 List Content Packages available for download from a configured Adobe CRX repository.
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>baseUrl : String</code>
<div><div>
 Specify the base URL of the Adobe Granite server, including hostname and port. The CRX Package Manager service path will be appended to this value for all requests. For example, <strong>http://localhost:4502</strong> or <strong>https://author.mycorp.com</strong>, etc.
 <br>
 <br>
  If login credentials for the server are different than those configured in the Connection Options section, you may override them in the Base URL by inserting <code>username[:password]@</code> between the scheme and the hostname.
 <br>
 <br>
  For example, to override the Username without changing the associated password or private key, you may use the following form:
 <br>
 <br>
  http://<strong>deployer@</strong>localhost:4502
 <br>
 <br>
  To override the credentials completely, provide a username and password (which may be provided by an encrypted parameter) by separating them with a colon, as shown below:
 <br>
 <br>
  http://<strong>deployer:Password123@</strong>localhost:4502
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Select the login credentials with which content packages will be listed from the CRX server.
 <br>
 <br><strong>[Signature]</strong> credentials may be used if the target server supports HTTP Signature Authentication using the keyId format, <code>/$username/keys/$fingerprint</code>.
 <br>
 <br>
  Select "-none-" to use the default credentials set in the global <strong>CRX Content Package Deployer - HTTP Client</strong> configuration.
</div></div>

</li>
<li><code>requestTimeout : long</code>
<div><div>
 Specify the timeout in milliseconds to wait for a response for each individual request. Specify a value of 0 to use default behavior.
</div></div>

</li>
<li><code>serviceTimeout : long</code>
<div><div>
 Specify the timeout in milliseconds to wait for PackageManager service availability between sending POST requests. Specify a value of 0 to use default behavior.
</div></div>

</li>
<li><code>multiselect : boolean</code>
</li>
<li><code>excludeNotInstalled : boolean</code>
<div><div>
 Filter the list to exclude packages which have been uploaded to the server, but which are not installed.
</div></div>

</li>
<li><code>excludeModified : boolean</code>
<div><div>
 Filter the list to exclude packages whose metadata have been modified after upload to the server, e.g. which need to be re-wrapped.
</div></div>

</li>
<li><code>visibleItemCount : long</code>
<div><div>
 Set the number of visible items displayed when multiselect is enabled. The default is 10.
</div></div>

</li>
<li><code>query : String</code>
<div><div>
 Specify a full-text search query to filter the list of packages, such as "Adobe".
</div></div>

</li>
<li><code>packageIdFilter : String</code>
<div><div>
 Specify a package ID filter to match against the list of packages returned from the configured Granite server.
 <br>
 <br>
  A Package ID consists of the group, the name, and the version of a package, separated by colons (':').
 <br>
 <br>
  Package ID filters must follow one of three patterns:
 <br>
 <ul>
  <li>group:name:version</li>
  <li>group:name</li>
  <li>name</li>
 </ul> Each segment in the filter may be either ommitted or replaced with an asterisk ('*') to represent a wildcard.
</div></div>

</li>
<li><code>value : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'PackageParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>rep : String</code>
</li>
<li><code>pkg : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>separator</code><div>
<div><div>
 Inserts a visual separator for build parameters: horizontal rule (&lt;hr/&gt; element) with an optional "Section Header" below it.
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>separatorStyle : String</code>
<div><div>
 Defines a custom CSS style for the Separator (i.e. the &lt;hr/&gt; tag). If empty, "Global separator style" is used, as configured by an administrator in Jenkins global configuaration.
</div></div>

</li>
<li><code>sectionHeader : String</code>
<div><div>
 Inserts a section header below the horizontal rule. Can be empty.
</div></div>

</li>
<li><code>sectionHeaderStyle : String</code>
<div><div>
 Defines a custom CSS style for the Section Header. If empty, "Global section header style" is used, as configured by an administrator in Jenkins global configuaration.
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'PatchParameterDefinition'</code><div>
<div><div>
 Accepts a patch file to be submitted. This patch will be applied to the workspace after the source code is checked out, then the build will proceed.
</div></div>
<ul><li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>persistentBoolean</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : boolean</code>
</li>
<li><code>successfulOnly : boolean</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>persistentChoice</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>choices : <code>Object</code></code> (optional)
</li>
<li><code>successfulOnly : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'PersistentPackageParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>useAwsKeys : boolean</code>
<div><div>
 <p>If you need to access the repository outside of the repository, you will need grant access to the S3 bucket.</p>
 <p>When accessing it from within AWS, it's probable that the server itself provides the necessary access rights.</p>
 <p>When accessing it from outside, you need to provide a key pair. These are set up in the AWS admin console. If you don't have access, please ask operations to create a new key pair with access to the specified bucket.</p>
</div></div>

</li>
<li><code>awsAccessKeyId : String</code>
<div><div>
 <p>This is the AWS secret key setup in the AWS console. It will resemble the form: ‘<em>AAAAAAAAAA2AAA2AAAAA</em>’</p>
 <p>If you don't have access to the AWS console, and you need an access key pair, please contact someone in operations.</p>
</div></div>

</li>
<li><code>awsSecretAccessKey : String</code>
<div><div>
 <p>This is the AWS secret key setup in the AWS console. It will resemble the form: ‘<em>XxXXXxx/1ZZz1zZZZ11zzZ1zz/YyYyYyyYyyyyYY</em>’</p>
 <p>If you don't have access to the AWS console, and you need an access key pair, please contact someone in operations.</p>
</div></div>

</li>
<li><code>bucketName : String</code>
<div><div>
 <p>This should be set to a valid bucket name that you can access using the key value pair, or if within AWS, that the server has access to.</p>
 <p>Ensure that the bucket specified contains the repo. It might sound obvious, but I just wanted to point that out.</p>
</div></div>

</li>
<li><code>repoPath : String</code>
<div><div>
 <p>This is the path to the actual repo containing the artifacts, relative to the AWS S3 bucket.</p>
 <p>For example, given the S3 bucket ‘<em>vhols-common-test-yumrepo</em>’, the path to the locations-public-api repo is repos/locations-public-api</p>
</div></div>

</li>
<li><code>repositoryType : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>persistentString</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code>
</li>
<li><code>successfulOnly : boolean</code>
</li>
<li><code>trim : boolean</code>
<div><div>
 Strip whitespace from the beginning and end of the string.
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>persistentText</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code>
</li>
<li><code>successfulOnly : boolean</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'PersistentYumParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>useAwsKeys : boolean</code>
<div><div>
 <p>If you need to access the repository outside of the repository, you will need grant access to the S3 bucket.</p>
 <p>When accessing it from within AWS, it's probable that the server itself provides the necessary access rights.</p>
 <p>When accessing it from outside, you need to provide a key pair. These are set up in the AWS admin console. If you don't have access, please ask operations to create a new key pair with access to the specified bucket.</p>
</div></div>

</li>
<li><code>awsAccessKeyId : String</code>
<div><div>
 <p>This is the AWS secret key setup in the AWS console. It will resemble the form: ‘<em>AAAAAAAAAA2AAA2AAAAA</em>’</p>
 <p>If you don't have access to the AWS console, and you need an access key pair, please contact someone in operations.</p>
</div></div>

</li>
<li><code>awsSecretAccessKey : String</code>
<div><div>
 <p>This is the AWS secret key setup in the AWS console. It will resemble the form: ‘<em>XxXXXxx/1ZZz1zZZZ11zzZ1zz/YyYyYyyYyyyyYY</em>’</p>
 <p>If you don't have access to the AWS console, and you need an access key pair, please contact someone in operations.</p>
</div></div>

</li>
<li><code>bucketName : String</code>
<div><div>
 <p>This should be set to a valid bucket name that you can access using the key value pair, or if within AWS, that the server has access to.</p>
 <p>Ensure that the bucket specified contains the repo. It might sound obvious, but I just wanted to point that out.</p>
</div></div>

</li>
<li><code>repoPath : String</code>
<div><div>
 <p>This is the path to the actual repo containing the artifacts, relative to the AWS S3 bucket.</p>
 <p>For example, given the S3 bucket ‘<em>vhols-common-test-yumrepo</em>’, the path to the locations-public-api repo is repos/locations-public-api</p>
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'PromotedBuildParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>jobName : String</code>
</li>
<li><code>process : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'PromotionLevelParameter'</code><div>
<div><div>
 Defines a parameter selected from the configured promotion levels. Note that the parameter provided to builds has the <b>numeric</b> value of the promotion level, i.e. its index in the list below, starting with one. 
 <br>
  If used with the Copy Artifact plugin to copy artifacts of a particular promotion level, the name of the parameter should be COPY_PROMOTION_LEVEL.
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultLevel : int</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'RandomStringParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>failedValidationMessage : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>RESTList</code><div>
<ul><li><code>name : String</code>
<div><div>
 The name of the parameter
 <br>
  These parameters are exposed to build as environment variables.
</div></div>

</li>
<li><code>restEndpoint : String</code>
<div><div>
 The URL address for to the REST endpoint.
 <br>
 <br>
  e.g. List GitLab repository releases <a href="https://docs.gitlab.com/ee/api/releases/#list-releases" rel="nofollow">https://gitlab.example.com/api/v4/projects/:id/releases</a>
</div></div>

</li>
<li><code>credentialId : String</code>
<div><div>
 Depending on the authentication requirement for the REST/Web endpoint there are three supported methods:
 <br>
 <ul>
  <li>`NONE` if there is no authentication requirement simply don't select any _Credential ID_</li>
  <li>`BASIC` if this authentication type is required, then simply select any Username and Password credential in the _Credential ID_ field</li>
  <li>`BEARER` if this authentication type is required, then simply select any Secret Text credential in the _Credential ID_ field</li>
 </ul><strong>NOTE:</strong> The Authentication header will be build and added based on the type of the selected credential type.
</div></div>

</li>
<li><code>mimeType</code>
<div><div>
 The MIME type that gets requested from the REST endpoint (i.e. Accepts: application/json)
 <br>
 <br><b>NOTE</b> This setting also define which kind of <i>Value Expression</i> gets applied to select the values in the end.
 <br>
 <ul>
  <li><b><i>APPLICATION_JSON</i></b> - Json-Path syntax is expected in the <i>Value Expression</i><br></li>
  <li><b><i>APPLICATION_XML</i></b> - xPath syntax is expected in the <i>Value Expression</i></li>
 </ul>
</div></div>

<ul><li><b>Values:</b> <code>APPLICATION_JSON</code>, <code>APPLICATION_XML</code></li></ul></li>
<li><code>valueExpression : String</code>
<div><div>
 The Value Expression dictates how the values get pares out of the REST response.
 <br>
  Depending on the selected MIME type the syntax expects is either Json-Path or xPath:
 <br>
 <ul>
  <li><b>Json-Path</b> <a href="https://github.com/json-path/JsonPath" rel="nofollow">Syntax</a> <a href="https://restfulapi.net/json-jsonpath/" rel="nofollow">Cheatsheet</a> <a href="https://jsonpath.com/" rel="nofollow">Playground</a></li>
  <li><b>xPath</b> <a href="https://www.w3schools.com/xml/xpath_syntax.asp" rel="nofollow">Syntax</a> <a href="https://devhints.io/xpath" rel="nofollow">Cheatsheet</a> <a href="http://xpather.com/" rel="nofollow">Playground</a></li>
 </ul>
</div></div>

</li>
<li><code>description : String</code> (optional)
<div><div>
 A description that will be shown to the user later.
</div></div>

</li>
<li><code>displayExpression : String</code> (optional)
<div><div>
 The Display Expression dictates how the values get displayed based on the object parsed from value expression.
 <br>
  Depending on the selected MIME type the syntax expects is either Json-Path or xPath:
 <br>
 <ul>
  <li><b>Json-Path</b> <a href="https://github.com/json-path/JsonPath" rel="nofollow">Syntax</a> <a href="https://restfulapi.net/json-jsonpath/" rel="nofollow">Cheatsheet</a> <a href="https://jsonpath.com/" rel="nofollow">Playground</a></li>
  <li><b>xPath</b> <strong>UNSUPPORTED</strong> Due to the limitation of the XML parser.</li>
 </ul>
</div></div>

</li>
<li><code>cacheTime : int</code> (optional)
<div><div>
 Allows the user to cache values returned from a HTTP endpoint.
 <br>
  The unit of this value is <strong>MINUTES</strong>. If the value is set to <strong><em>0</em></strong>, a web request is forced.
 <br><strong>NOTE:</strong> The cache can globally hold up to 50 MiB per default, which <em>should</em> be enough for most use-cases.
 <br>
  (The maximum size of the cache can be adjusted in the global Jenkins settings)
</div></div>

</li>
<li><code>defaultValue : String</code> (optional)
<div>The <i>Default Value</i> allows the user to predetermine the value selected for this parameter.
<br><b>NOTE</b> This has to be the exact same value as the value to be preselected, because it gets string compared.</div>

</li>
<li><code>filter : String</code> (optional)
<div><div>
 A simple <a href="https://regexr.com/" rel="nofollow">regex</a> filter applied on the values list generated by the <i>Value Expression</i>
 <br>
  This filter is useful for longer value lists (e.g. version lists) to filter for only relevant values.
</div></div>

</li>
<li><code>valueOrder</code> (optional)
<div><div>
 This setting provides tha ability to sort the received values from the endpoint set above.
 <br>
  Can be useful if your endpoint returns a lot of values and does not return them in order nor provides the option to.
 <br>
 <ul>
  <li>NONE - Do not apply any post ordering on the received values</li>
  <li>ASC - "Ascending" order gets applied on the received values</li>
  <li>DSC - "Descending" order gets applied on the received values</li>
 </ul>
</div></div>

<ul><li><b>Values:</b> <code>NONE</code>, <code>ASC</code>, <code>DSC</code>, <code>REV</code></li></ul></li>
</ul></div></li>
<li><code>$class: 'ReviewboardParameterDefinition'</code><div>
<div><div>
 Accepts a patch url or number of review request. This patch will be applied to the workspace after the source code is checked out, then the build will proceed.
</div></div>
<ul><li><code>defaultValue : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>trim : boolean</code> (optional)
<div><div>
 Strip whitespace from the beginning and end of the string.
</div></div>

</li>
</ul></div></li>
<li><span><a href="/doc/pipeline/steps/params/runfilterparameter"><code>$class: 'RunFilterParameter'</code></a></span></li>
<li><code>run</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>projectName : String</code>
</li>
<li><code>filter</code>
<ul><li><b>Values:</b> <code>ALL</code>, <code>STABLE</code>, <code>SUCCESSFUL</code>, <code>COMPLETED</code></li></ul></li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><span><a href="/doc/pipeline/steps/params/runselectorparameter"><code>$class: 'RunSelectorParameter'</code></a></span></li>
<li><code>$class: 'SauceParameterDefinition'</code><div>
<ul><li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'ScriptSelectionTaskDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>path : String</code>
</li>
<li><code>arrayCheckBox</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>variableName : String</code>
</li>
<li><code>check : boolean</code>
</li>
<li><code>type : String</code>
</li>
<li><code>parent : String</code>
</li>
</ul></li>
<li><code>testDelimSymbol : String</code>
</li>
<li><code>nodeDelimSymbol : String</code>
</li>
<li><code>countDelimiterSymbol : int</code>
</li>
<li><code>delimiter : String</code>
</li>
<li><code>defaultValue : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>snParam</code><div>
<ul><li><code>credentialsForPublishedApp : String</code>
<div><div>
 User name and password defined in global credentials (credentials ID is required here) used for the instance where the application will be published.
</div></div>

</li>
<li><code>instanceForPublishedAppUrl : String</code>
<div><div>
 ServiceNow instance url where the application will be published to.
</div></div>

</li>
<li><code>credentialsForInstalledApp : String</code>
<div><div>
 User name and password defined in global credentials (credentials ID is required here) used for the instance where the application will be installed.
</div></div>

</li>
<li><code>instanceForInstalledAppUrl : String</code>
<div><div>
 ServiceNow instance url where the application will be installed.
</div></div>

</li>
<li><code>sysId : String</code>
<div><div>
 Required if <code>application scope</code> is not specified. The system id of the application for which to apply the changes. You can locate this value in the Sys ID field in the Custom Application [sys_app] table.
</div></div>

</li>
<li><code>appScope : String</code>
<div><div>
 Required if <code>application system ID</code> is not specified. The scope name of the application for which to apply the changes, such as x_aah_custom_app. You can locate this value in the scope field in the Custom Application [sys_app] table.
</div></div>

</li>
<li><code>publishedAppVersion : String</code>
<div><div>
 Version number of published application (that will be also installed if appropriate build step will be used). Do not fill the field up if you want to get the number automatically (depends on the build step 'Publish application').
</div></div>

</li>
<li><code>rollbackAppVersion : String</code>
<div><div>
 Version number of the application used by the step 'Roll back application'.
 <br>
 Do not fill this field up if the version should be obtained automatically.
</div></div>

</li>
<li><code>batchRollbackId : String</code>
</li>
<li><code>progressCheckInterval : int</code>
<div><div>
 Time in milliseconds between one and another progress check set up for all build steps of ServiceNow. 
 <br>
 Leave it empty to use default value.
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'SpringBootLibrariesListParameterDefinition'</code><div>
<ul><li><code>springBootVersion : String</code>
</li>
<li><code>defaultValue : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>trim : boolean</code> (optional)
<div><div>
 Strip whitespace from the beginning and end of the string.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'StashBranchParameterDefinition'</code><div>
<ul><li><code>name : String</code>
<div><div>
 The name of the parameter.
</div></div>

</li>
<li><code>repository : String</code>
</li>
<li><code>defaultValue : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>branchNameRegex : String</code> (optional)
</li>
<li><code>tagNameRegex : String</code> (optional)
</li>
</ul></div></li>
<li><code>stashedFile</code><div>
<div><p>File parameter compatible with Pipeline but using the stash system, better suited to large files. The file will be saved to a stash named like the parameter containing one entry, also named like the parameter. Example usage from Declarative Pipeline:</p>
<pre>pipeline {
  agent any
  parameters {
    stashedFile 'assets.zip'
  }
  stages {
    stage('Example') {
      steps {
        unstash 'assets.zip'
        sh 'unzip assets.zip'
      }
    }
  }
}
 </pre></div>
<ul><li><code>name : String</code>
<div><p>The name of the parameter. Depending on the type of parameter, this may or may not be bound as an environment variable during the build.</p>
<p>If a local filename was given, an environment variable <code><i>paramname</i>_FILENAME</code> will also be set. If the build is triggered via the CLI, the variable will not be set.</p></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>string</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>trim : boolean</code> (optional)
<div><div>
 Strip whitespace from the beginning and end of the string.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'TestExecuter'</code><div>
<div><div>
 This plugin allows you to choose specific tests you want to run.
 <br>
  First, you need to specify the name of the environment variable in which you want your selected tests to be saved in (after build the selected tests will be in this environment variable as a JSON array).
 <br>
  Second, you need to enter the properties file path. This file will contain all your tests and maybe some extra fields for the plugin (more details about the properties file are in the appropriate help field).
 <br>
  After that, your tests will be shown in a tree diagram, allowing you to select some of them.
</div></div>
<ul><li><code>name : String</code>
<div><div>
 Enter the name of the <b>environment variable</b> in which you want your selected tests to be saved in (after build the selected tests will be in this environment variable as a JSON array).
 <br>
</div></div>

</li>
<li><code>propertiesFilePath : String</code>
<div><div>
 <div>
  The properties file you enter <b>must</b> have a property called <b>tests</b>.
 </div>
 <div>
  The <b>tests</b> property value is a JSON array that contains a JSON object for each test. 
  <br>
   In each test object you need to specify it's attributes by a key/value pairs.
 </div>
 <br>
 <div>
  The following properties will allow you to select specific fields which have a special meaning:
 </div>
 <div>
  1.<span>&nbsp; </span><b>enableField</b> - the name of the field that will imply if the test is enabled or not. 
  <br>
   if the value in the specified field, for some test(s), will be false then the test will not be shown at all.
 </div>
 <div>
  2.<span>&nbsp; </span><b>groupBy</b> - the field that the plugin will group the tests by. 
  <br>
   if 2 tests have the same value in this field, they will be in the same group.
 </div>
 <div>
  3.<span>&nbsp; </span><b>showFields - </b>the field(s) that will be shown in the tests tree.
 </div>
 <div>
  4.<span>&nbsp; </span><b>multiplicityField - </b>the field that will be set to the amount of times the test should run.
 </div>
 <div>
  5.<span>&nbsp; </span><b>fieldSeparator - </b>the character that will separate between the fields in the tests tree.
 </div>
 <div>
  <b>Each property must</b> be defined either in the properties file or in the override section bellow. 
  <br>
   If you want to change the properties you defined In the file, you can override them in the section bellow.
 </div>
 <br>
 <div>
  <u>This is an <b>example</b> for a properties file which contains all above properties: </u>
 </div>
 <div>
  tests=[{"enabled":true,"owner":"shushu","testgroup":"A","testcase":"single"},{"enabled":false,"owner":"shushu","testgroup":"B","setuptype":"basic","testcase":"triple"}]
 </div>
 <div>
  enableField=enabled
 </div>
 <div>
  groupBy=testgroup
 </div>
 <div>
  fieldSeparator=.
 </div>
 <div>
  showFields=testsuite,testcase
 </div>
 <div>
  multiplicityField=multiplicity
 </div>
</div></div>

</li>
<li><code>enableField</code>
<div><div>
 Setting <b>Enable Field</b> property. 
 <br><b>Enable Field</b> - the name of the field that will imply if the test is enabled or not. If the value in the specified field, for some test(s), will be false then the test will not be shown at all.
</div></div>

<ul><b>Nested Object</b>
<li><code>text : String</code>
</li>
</ul></li>
<li><code>groupBy</code>
<div><div>
 Setting <b>Group By</b> property. 
 <br><b>Group By</b> - the field that the plugin will group the tests by. If 2 tests have the same value in this field, they will be in the same group.
</div></div>

<ul><b>Nested Object</b>
<li><code>text : String</code>
</li>
</ul></li>
<li><code>fieldSeparator</code>
<div><div>
 Setting <b>Field Separator</b> property. 
 <br><b>Field Separator </b>- the character that will separate between the fields in the tests tree.
</div></div>

<ul><b>Nested Object</b>
<li><code>text : String</code>
</li>
</ul></li>
<li><code>showFields</code>
<div><div>
 Setting <b>Show Fields</b> property. 
 <br><b>Show Fields</b> - the field(s) that will be shown in the tests tree.
 <br>
  If you click on "Show/Hide Available Fields" button then next to each available field appears (howManyTestsHasThisField/amountOfTests).
</div></div>

<ul><b>Nested Object</b>
<li><code>text : String</code>
</li>
</ul></li>
<li><code>multiplicityField</code>
<div><div>
 Setting <b>Multiplicity Field</b> property. 
 <br><b>Multiplicity Field</b> - the field that will be set to the amount of times the test should run.
</div></div>

<ul><b>Nested Object</b>
<li><code>text : String</code>
</li>
</ul></li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>text</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code> (optional)
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>trim : boolean</code> (optional)
<div><div>
 Strip whitespace from the beginning and end of the string.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ToolVersionParameterDefinition'</code><div>
<ul><li><code>toolName : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'VBoxParameterDefinition'</code><div>
<div><div>
 Build parameter with virtual node names. Parameter <i>name</i> is exported to the build from virtual node names joined by node name delimiter.
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>nodeDelimiter : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>email</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code>
</li>
<li><code>domain : String</code>
</li>
<li><code>externalEmail : boolean</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>validatingString</code><div>
<div><div>
 Defines a simple text parameter, where users can enter a string value, which you can use during a build, either as an environment variable, or through variable substitution in some other parts of the configuration. 
 <p></p> Additionally, this parameter supports a regular expression based validation of the user entered parameter to ensure it meets the build's requirements.
</div></div>
<ul><li><code>name : String</code>
<div><div>
 The name of the parameter 
 <p>These parameters are exposed to build as environment variables.</p>
</div></div>

</li>
<li><code>defaultValue : String</code>
<div><div>
 Specifies the default value of the field, which allows the user to save typing the actual value.
</div></div>

</li>
<li><code>regex : String</code>
<div><div>
 <p>Standard <a href="https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html" rel="nofollow">Java regular expression</a> that will be used to validate the entered string parameter value.</p>
</div></div>

</li>
<li><code>failedValidationMessage : String</code>
<div><div>
 <p>This message is displayed to the user if they enter a value that does not match the configured regular expression.</p>
</div></div>

</li>
<li><code>description : String</code> (optional)
<div><div>
 A description that will be shown to the user later.
</div></div>

</li>
</ul></div></li>
<li><code>validatingYamlParameter</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code>
</li>
<li><code>failedValidationMessage : String</code>
<div><div>
 <p>This message is displayed to the user if they enter a value that is not a syntactical correct YAML</p>
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'VersionParameterDefinition'</code><div>
<div><div>
 Defines a build parameter for the selecting a version of the artifact to use at job runtime.
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>groupId : String</code>
</li>
<li><code>artifactId : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
<li><code>includeReleases : boolean</code> (optional)
</li>
<li><code>includeSnapshots : boolean</code> (optional)
</li>
<li><code>limit : String</code> (optional)
</li>
<li><code>oldestFirst : boolean</code> (optional)
</li>
<li><code>repositoryId : String</code> (optional)
</li>
<li><code>useLatest : boolean</code> (optional)
</li>
<li><code>useRelease : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>hidden</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'WReadonlyStringParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'WReadonlyTextParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValue : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>extendedChoice</code><div>
<div><div>
 <p>This parameter adds various types of choice fields to the Pipeline Input Step.</p>
</div></div>
<ul><li><code>name : String</code>
<div><div>
 The name of the parameter.
</div></div>

</li>
<li><code>type : String</code>
<div><div>
 The type of parameter: 
 <ul>
  <li>Single Select: user chooses a single selection from a drop down menu, populated by either explicit values (see Value field below) or a property file (see Property File and Property Key fields below)<br><br></li>
  <li>Multi Select: a user can choose multiple selections from a multi-line box, populated by either explicit values (see Value field below) or a property file (see Property File and Property Key fields below)<br><br></li>
  <li>Check Boxes: user can check off zero or more check boxes, labeled by either explicit values (see Value field below) or a property file (see Property File and Property Key fields below)<br><br></li>
  <li>Multi-Level Single Select: user chooses a selection from a drop down, and then a another drop down appears with selections that depend on the first value, and upon second selection a third drop down may appear depending on the first two selections, and so on.<br><br>
    The property file is a tab delimited file, with levels defined in columns and choices defined in rows. For example, to have a 2 level selection where you first select a country and then a city, you could specify a file such as the following:<br><br>
   <pre>Country	City
United States	San Francisco
United States	Chicago
Mexico	Mexico City
Mexico	Cancun
            </pre> This would result in a first drop down with the options "Select a country...", "United States", and "Mexico" (the initial selection is "Select a country...", which serves as a label for the drop down). After the user selects a country, a "City" drop down would appear. If United States was chosen first, then San Francisco and Chicago would be options, but if Mexico was selected then instead Mexico City and Cancun would be options. <br><br>
    The columns that should represent levels must be specified in the value field. For example "Country,City" could be valid values. <br><br>
    Note that default values are not supported for multi-level selects.<br><br></li>
  <li>Multi-Level Multi Select: same as single select, but after all levels are chosen, a button appears to "Select another..." and an additional multi-level selection is presented.</li>
 </ul>
</div></div>

</li>
<li><code>value : String</code>
<div><div>
 Comma separated list of values for the single select or multi-select box. 
 <br>
 <br>
 This field can be left blank if the comma separated values need to be picked up from a properties file (set via 'Property File' and 'Property Key'). 
 <br>
 <br>
  This value has different meaning for multi-level select -- see the parameter type help for more info.
</div></div>

</li>
<li><code>projectName : String</code>
<div><div>
 If specified, this adds a <b>currentProject</b> entry to the groovy script context. The entry's value is set to the specified Jenkins project.
</div></div>

</li>
<li><code>propertyFile : String</code>
<div><div>
 The <a href="https://en.wikipedia.org/wiki/.properties" rel="nofollow">properties file</a> is a collection of key,value pairs of the form key=value1,value2,... 
 <br>
 <br>
  Properties may reference other properties. For example: 
 <blockquote>
  prop1=a,b,c,d,e
  <br>
   prop2=${prop1},f,g,h
 </blockquote> The properties file can be placed anywhere on the file-system that Jenkins can access. 
 <br>
 <br>
  This property file has different meaning for multi-level select -- see the parameter type help for more info.
</div></div>

</li>
<li><code>groovyScript : String</code>
</li>
<li><code>groovyScriptFile : String</code>
</li>
<li><code>bindings : String</code>
</li>
<li><code>groovyClasspath : String</code>
</li>
<li><code>propertyKey : String</code>
<div><div>
 The property of the property file to use. 
 <br>
 <br>
  For example, if the property file was the following: 
 <blockquote>
  prop1=a,b,c,d,e
  <br>
   prop2=1,2,3,4
 </blockquote> Then you could specify the property as either prop1 or prop2.
</div></div>

</li>
<li><code>defaultValue : String</code>
<div><div>
 Initial selection of the single-select or mult-select box. 
 <br>
 <br>
 In case of the multi-select box, default value can be a comma separated string.
</div></div>

</li>
<li><code>defaultPropertyFile : String</code>
<div><div>
 Absolute path (specified without using environment variables).
</div></div>

</li>
<li><code>defaultGroovyScript : String</code>
</li>
<li><code>defaultGroovyScriptFile : String</code>
</li>
<li><code>defaultBindings : String</code>
</li>
<li><code>defaultGroovyClasspath : String</code>
</li>
<li><code>defaultPropertyKey : String</code>
</li>
<li><code>descriptionPropertyValue : String</code>
</li>
<li><code>descriptionPropertyFile : String</code>
</li>
<li><code>descriptionGroovyScript : String</code>
</li>
<li><code>descriptionGroovyScriptFile : String</code>
</li>
<li><code>descriptionBindings : String</code>
</li>
<li><code>descriptionGroovyClasspath : String</code>
</li>
<li><code>descriptionPropertyKey : String</code>
</li>
<li><code>javascriptFile : String</code>
</li>
<li><code>javascript : String</code>
</li>
<li><code>saveJSONParameterToFile : boolean</code>
</li>
<li><code>quoteValue : boolean</code>
</li>
<li><code>visibleItemCount : int</code>
</li>
<li><code>multiSelectDelimiter : String</code>
<div><div>
 <p>Inserts this value between selections when the parameter is a multi-select.</p>
 <p>The default when empty is ','</p>
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'com.michelin.cio.hudson.plugins.passwordparam.PasswordParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'com.moded.extendedchoiceparameter.ExtendedChoiceParameterDefinition'</code><div>
<ul><li><code>name : String</code>
<div><div>
 The name of the parameter.
</div></div>

</li>
<li><code>type : String</code>
<div><div>
 The type of parameter: 
 <ul>
  <li>Single Select: user chooses a single selection from a drop down menu, populated by either explicit values (see Value field below) or a property file (see Property File and Property Key fields below)<br><br></li>
  <li>Multi Select: a user can choose multiple selections from a multi-line box, populated by either explicit values (see Value field below) or a property file (see Property File and Property Key fields below)<br><br></li>
  <li>Check Boxes: user can check off zero or more check boxes, labeled by either explicit values (see Value field below) or a property file (see Property File and Property Key fields below)<br><br></li>
  <li>Multi-Level Single Select: user chooses a selection from a drop down, and then a another drop down appears with selections that depend on the first value, and upon second selection a third drop down may appear depending on the first two selections, and so on.<br><br>
    The property file is a tab delimited file, with levels defined in columns and choices defined in rows. For example, to have a 2 level selection where you first select a country and then a city, you could specify a file such as the following:<br><br>
   <pre>
Country	City
United States	San Francisco
United States	Chicago
Mexico	Mexico City
Mexico	Cancun
            </pre> This would result in a first drop down with the options "Select a country...", "United States", and "Mexico" (the initial selection is "Select a country...", which serves as a label for the drop down). After the user selects a country, a "City" drop down would appear. If United States was chosen first, then San Francisco and Chicago would be options, but if Mexico was selected then instead Mexico City and Cancun would be options. <br><br>
    The columns that should represent levels must be specified in the value field. For example "Country,City" could be valid values. <br><br>
    Note that default values are not supported for multi-level selects.<br><br></li>
  <li>Multi-Level Multi Select: same as single select, but after all levels are chosen, a button appears to "Select another..." and an additional multi-level selection is presented.</li>
 </ul>
</div></div>

</li>
<li><code>value : String</code>
<div><div>
 Comma separated list of values for the single select or multi-select box. 
 <br>
 <br>
 This field can be left blank if the comma separated values need to be picked up from a properties file (set via 'Property File' and 'Property Key'). 
 <br>
 <br>
  This value has different meaning for multi-level select -- see the parameter type help for more info.
</div></div>

</li>
<li><code>propertyFile : String</code>
<div><div>
 The <a href="http://download.oracle.com/javase/6/docs/api/java/util/Properties.html" rel="nofollow">properties file</a> is a collection of key,value pairs of the form key=value1,value2,... 
 <br>
 <br>
  Property files may reference other properties. For example: 
 <blockquote>
  prop1=a,b,c,d,e
  <br>
   prop2=${prop1},f,g,h
 </blockquote> The properties file can be placed anywhere on the file-system that Jenkins can access. 
 <br>
 <br>
  This property file has different meaning for multi-level select -- see the parameter type help for more info.
</div></div>

</li>
<li><code>propertyKey : String</code>
<div><div>
 The property of the property file to use. 
 <br>
 <br>
  For example, if the property file was the following: 
 <blockquote>
  prop1=a,b,c,d,e
  <br>
   prop2=1,2,3,4
 </blockquote> Then you could specify the property as either prop1 or prop2.
</div></div>

</li>
<li><code>defaultValue : String</code>
<div><div>
 Initial selection of the single-select or mult-select box. 
 <br>
 <br>
 In case of the multi-select box, default value can be a comma separated string.
</div></div>

</li>
<li><code>defaultPropertyFile : String</code>
<div><div>
 Absolute path (specified without using environment variables).
</div></div>

</li>
<li><code>defaultPropertyKey : String</code>
</li>
<li><code>quoteValue : boolean</code>
</li>
<li><code>visibleItemCount : int</code>
</li>
<li><code>multiSelectDelimiter : String</code>
<div><div>
 <p>Inserts this value between selections when the parameter is a multi-select.</p>
 <p>The default when empty is ','</p>
</div></div>

</li>
<li><code>bindFieldName : String</code>
</li>
<li><code>svnPath : boolean</code>
</li>
<li><code>svnUrl : String</code>
</li>
<li><code>svnUserName : String</code>
</li>
<li><code>svnPassword : String</code>
</li>
<li><code>projectName : String</code>
</li>
<li><code>roleBasedFilter : boolean</code>
</li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
<li><code>password</code><div>
<div><div>
 Pass a password to your build. The password entered here is made available to the build in plain text as an environment variable like a string parameter would be. The value will be stored encrypted on the Jenkins controller, similar to passwords in Jenkins configuration.
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultValueAsSecret</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>submitter : String</code> (optional)
<div><div>
 User IDs and/or <em>external</em> group names of person or people permitted to respond to the input, separated by ','. Spaces will be trimmed. This means that "alice, bob, blah " is the same as "alice,bob,blah".
 <br><strong>Note: Jenkins administrators are able to respond to the input regardless of the value of this parameter.</strong>
</div></div>

</li>
<li><code>submitterParameter : String</code> (optional)
<div><div>
 If specified, this is the name of the return value that will contain the ID of the user that approves this input. The return value will be handled in a fashion similar to the <code>parameters</code> value.
</div></div>

</li>
</ul>


++++
