= Pipeline: Keep Environment Step Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/pipeline-keepenv-step">Visit the Jenkins Plugins site</a>
++++


=== `keepEnv`: Keep only specified environment variables
++++
<div><div>
 Filters out for the scope of the block, the environment variables proposed by Jenkins except the ones listed. These are available to any external processes spawned within that scope. For example: 
 <p></p>
 <pre>node {
  env.CUSTOM=test
  env.INFO=useful
  keepEnv(['INFO']) {
    // at this point the CUSTOM will not be available
    bat 'echo %INFO%'
  }
}
</pre>
 <p>See the documentation for the <code>env</code> singleton for more information on environment variables.</p>
</div></div>
<ul><li><code>variables : Array / List of String</code>
<div><div>
 A list of environment variables to retain. Specify one variable name per line. All other environment variables added to the Pipeline by Jenkins will be removed from the block. System-contributed environment variables like <code>PATH</code> will be reset to their default value.
</div></div>

<ul></ul></li>
</ul>


++++
