= Pipeline: HuaweiCloud Steps
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/pipeline-huaweicloud-plugin">Visit the Jenkins Plugins site</a>
++++


=== `invokeFunction`: Invoke a given function
++++
<ul><li><code>functionName : String</code>
</li>
<li><code>payload : <code>Object</code></code> (optional)
</li>
<li><code>payloadAsString : String</code> (optional)
</li>
<li><code>returnValueAsString : boolean</code> (optional)
</li>
</ul>


++++
=== `obsUpload`: Copy file to obs
++++
<div><div>
 <p>Upload a file/folder from the workspace to an S3 bucket. If the file parameter denotes a directory, then the complete directory (including all subfolders) will be uploaded. If text is provided, upload the text as the provided filename in the remote S3 bucket.</p>
</div></div>
<ul><li><code>bucket : String</code>
<div><div>
 This is the bucket to use.
</div></div>

</li>
<li><code>excludePathPattern : String</code> (optional)
<div><div>
 This is the pattern to use to exclude files <i>Sample : "*.svg"</i>
</div></div>

</li>
<li><code>file : String</code> (optional)
<div><div>
 This is the local file to upload from the workspace.
</div></div>

</li>
<li><code>includePathPattern : String</code> (optional)
<div><div>
 This is the pattern to use to find files to push to S3 <i>Sample : "dist/**"</i>
</div></div>

</li>
<li><code>metadatas : Array / List of String</code> (optional)
<div><div>
 Metadatas to add to push file. Multiple metadatas must be separated with a ';' and name and value separated by a ':'. <i>Sample : "Content-Type:image/svg+xml;Another:AnotherValue"</i>
</div></div>

<ul></ul></li>
<li><code>path : String</code> (optional)
<div><div>
 This is the path inside the bucket to use. <i>Do not begin with a leading "/".</i>
</div></div>

</li>
<li><code>text : String</code> (optional)
<div><div>
 This is the text to be copied up to S3.
</div></div>

</li>
<li><code>workingDir : String</code> (optional)
<div><div>
 Working directories for obsUpload plugin <i>Sample : "dist"</i>
</div></div>

</li>
</ul>


++++
=== `withOBS`: set OBS settings for nested block
++++
<div><div>
 <p>The <code>withOBS</code> step provides authorization for the nested steps. You can provide region. <code>withOBS</code> block.</p>
</div></div>
<ul><li><code>credentials : String</code> (optional)
<div><div>
 Use standard Jenkins UsernamePassword credentials. Note: the username should be your Access Key ID, and the password should be the Secret Access Key.
</div></div>

</li>
<li><code>endpointUrl : String</code> (optional)
<div><div>
 The OBS endpoint-url.
</div></div>

</li>
<li><code>region : String</code> (optional)
<div><div>
 The OBS region.
</div></div>

</li>
</ul>


++++
