= Pipeline GitHub Notify Step Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/pipeline-githubnotify-step">Visit the Jenkins Plugins site</a>
++++


=== `githubNotify`: Notifies GitHub of the status of a Pull Request
++++
<div><div>
 <p>The <code>githubNotify</code> step gives full controll to pipelines about the commit status</p>
 <p>You can check the oficial GitHub's documentation about statutes <a href="https://developer.github.com/v3/repos/statuses/" rel="nofollow">here</a></p>
</div></div>
<ul><li><code>status</code>
<ul><li><b>Values:</b> <code>PENDING</code>, <code>SUCCESS</code>, <code>ERROR</code>, <code>FAILURE</code></li></ul></li>
<li><code>description : String</code>
<div><div>
 <p>The notification description, it will be displayed by GitHub</p>
 <p>You can check the oficial GitHub's documentation <a href="https://developer.github.com/v3/repos/statuses/#create-a-status" rel="nofollow">here</a></p>
</div></div>

</li>
<li><code>account : String</code> (optional)
<div><div>
 <p>The GitHub account that owns the repos that contains the commit to notify</p>
 <p>You can check the oficial GitHub's documentation <a href="https://developer.github.com/v3/repos/statuses/#create-a-status" rel="nofollow">here</a></p>
</div></div>

</li>
<li><code>context : String</code> (optional)
<div><div>
 <p>The Notification key, keys are used by GitHub to diferentiate between notifications, two notification with the same key are meant to be the same</p>
 <p>You can check the oficial GitHub's documentation <a href="https://developer.github.com/v3/repos/statuses/#create-a-status" rel="nofollow">here</a></p>
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 <p>The GitHub credentials, username/password or username/accessToken</p>
</div></div>

</li>
<li><code>gitApiUrl : String</code> (optional)
<div><div>
 <p>If you are a user of GitHub Enterprise use this field to set your custom API endpoint</p>
</div></div>

</li>
<li><code>repo : String</code> (optional)
<div><div>
 <p>The GitHub repository that contains the commit to validate, must be owned by the user specified in the account field</p>
 <p>You can check the oficial GitHub's documentation <a href="https://developer.github.com/v3/repos/statuses/#create-a-status" rel="nofollow">here</a></p>
</div></div>

</li>
<li><code>sha : String</code> (optional)
<div><div>
 <p>The SHA that identifies the commit to notify</p>
 <p>You can check the oficial GitHub's documentation <a href="https://developer.github.com/v3/repos/statuses/#create-a-status" rel="nofollow">here</a></p>
</div></div>

</li>
<li><code>targetUrl : String</code> (optional)
<div><div>
 <p>Use this field to specify a custom target URL for the notification, if not specified the build's URL will be used</p>
 <p>You can check the oficial GitHub's documentation <a href="https://developer.github.com/v3/repos/statuses/#create-a-status" rel="nofollow">here</a></p>
</div></div>

</li>
</ul>


++++
