= Pipeline: Bamboo Step
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/pipeline-bamboo">Visit the Jenkins Plugins site</a>
++++


=== `buildBamboo`: Build Bamboo
++++
<div><div>
 <p>The <b>buildBamboo</b> step provides a way to invoke Bamboo plans from within a Jenkinsfile.</p>
</div></div>
<ul><li><code>projectKey : String</code>
<div><div>
 (required) The project key of your build plan. For example, if the build plan is "MYPROJECT-MYPLAN", this would be "MYPROJECT".
</div></div>

</li>
<li><code>planKey : String</code>
<div><div>
 (required) The plan key of your build plan. For example, if the build plan is "MYPROJECT-MYPLAN", this would be "MYPLAN".
</div></div>

</li>
<li><code>serverAddress : String</code>
<div><div>
 (required) The hostname or IP of the Bamboo server.
</div></div>

</li>
<li><code>username : String</code>
<div><div>
 (required) The username to use to authenticate to Bamboo.
</div></div>

</li>
<li><code>password : String</code>
<div><div>
 (required) The Bamboo server password.
</div></div>

</li>
<li><code>checkInterval : int</code> (optional)
</li>
<li><code>params</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.Object&gt;</code></li>
</ul></li>
<li><code>propagate : boolean</code> (optional)
<div><div>
 (optional) Boolean. Whether or not failures halt the pipeline. Default: True
</div></div>

</li>
</ul>


++++
