= PlasticSCM Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/plasticscm-plugin">Visit the Jenkins Plugins site</a>
++++


=== `cm`: Plastic SCM
++++
<ul><li><code>branch : String</code> (optional)
</li>
<li><code>changelog : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in changelog': 
 <p>If 'Include in changelog' is enabled for an SCM source, then when a build occurs, the changes from that SCM source will be included in the changelog.</p>
 <p>If 'Include in changelog' is disabled, then when a build occurs, the changes from this SCM source will not be included in the changelog.</p>
</div></div>

</li>
<li><code>changeset : String</code> (optional)
</li>
<li><code>cleanup</code> (optional)
<ul><li><b>Values:</b> <code>MINIMAL</code>, <code>STANDARD</code>, <code>FULL</code>, <code>DELETE</code></li></ul></li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>directory : String</code> (optional)
</li>
<li><code>label : String</code> (optional)
</li>
<li><code>poll : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in polling' 
 <p>If 'Include in polling' is enabled or 'Include in changelog' is enabled, then when polling occurs, the job will be started if changes are detected from this SCM source.</p>
 <p>If 'Include in polling' is disabled and 'Include in changelog' is disabled, then when polling occurs, changes that are detected from this repository will be ignored.</p>
</div></div>

</li>
<li><code>repository : String</code> (optional)
</li>
<li><code>server : String</code> (optional)
</li>
<li><code>shelveset : String</code> (optional)
</li>
<li><code>workingMode</code> (optional)
<ul><li><b>Values:</b> <code>NONE</code>, <code>UP</code>, <code>LDAP</code></li></ul></li>
</ul>


++++
=== `mergebotCheckout`: Plastic SCM Mergebot Checkout
++++
<ul><li><code>changelog : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in changelog': 
 <p>If 'Include in changelog' is enabled for an SCM source, then when a build occurs, the changes from that SCM source will be included in the changelog.</p>
 <p>If 'Include in changelog' is disabled, then when a build occurs, the changes from this SCM source will not be included in the changelog.</p>
</div></div>

</li>
<li><code>cleanup</code> (optional)
<ul><li><b>Values:</b> <code>MINIMAL</code>, <code>STANDARD</code>, <code>FULL</code>, <code>DELETE</code></li></ul></li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>poll : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in polling' 
 <p>If 'Include in polling' is enabled or 'Include in changelog' is enabled, then when polling occurs, the job will be started if changes are detected from this SCM source.</p>
 <p>If 'Include in polling' is disabled and 'Include in changelog' is disabled, then when polling occurs, changes that are detected from this repository will be ignored.</p>
</div></div>

</li>
<li><code>specAttributeName : String</code> (optional)
</li>
<li><code>workingMode</code> (optional)
<ul><li><b>Values:</b> <code>NONE</code>, <code>UP</code>, <code>LDAP</code></li></ul></li>
</ul>


++++
