= Plot plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/plot">Visit the Jenkins Plugins site</a>
++++


=== `plot`: Plot build data
++++
<ul><li><code>group : String</code>
</li>
<li><code>style : String</code>
</li>
<li><code>csvFileName : String</code>
</li>
<li><code>csvSeries</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>file : String</code>
</li>
<li><code>url : String</code>
</li>
<li><code>inclusionFlag : String</code>
</li>
<li><code>exclusionValues : String</code>
</li>
<li><code>displayTableFlag : boolean</code>
</li>
</ul></li>
<li><code>description : String</code> (optional)
</li>
<li><code>exclZero : boolean</code> (optional)
</li>
<li><code>keepRecords : boolean</code> (optional)
</li>
<li><code>logarithmic : boolean</code> (optional)
</li>
<li><code>numBuilds : String</code> (optional)
</li>
<li><code>propertiesSeries</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>file : String</code>
</li>
<li><code>label : String</code>
</li>
</ul></li>
<li><code>title : String</code> (optional)
</li>
<li><code>useDescr : boolean</code> (optional)
</li>
<li><code>xmlSeries</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>file : String</code>
</li>
<li><code>xpath : String</code>
</li>
<li><code>nodeType : String</code>
</li>
<li><code>url : String</code>
</li>
</ul></li>
<li><code>yaxis : String</code> (optional)
</li>
<li><code>yaxisMaximum : String</code> (optional)
</li>
<li><code>yaxisMinimum : String</code> (optional)
</li>
</ul>


++++
