= PreFlight
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/preflight-integration">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'PreflightBuilder'])`: Run PreFlight Test
++++
<ul><li><code>clientId : String</code>
<div><div>
 (required) Client Id for PreFlight API. You can generate client id and client secret from <a href="https://app.preflight.com/account/api" rel="nofollow">Account Settings&gt;API</a> under your Preflight account.
</div></div>

</li>
<li><code>clientSecret : String</code>
<div><div>
 (required) Client Secret for PreFlight API. You can generate client id and client secret from <a href="https://app.preflight.com/account/api" rel="nofollow">Account Settings&gt;API</a> under your Preflight account.
</div></div>

</li>
<li><code>testId : String</code>
<div><div>
 (optional) Pass the Test Id to run. If test id or group id are not passed all the tests will be run.
</div></div>

</li>
<li><code>groupId : String</code>
<div><div>
 (optional) Pass the Group Id to run. If test id or group id are not passed all the tests will be run. You can get it from <a href="https://app.preflight.com/tests/settings/groups" rel="nofollow"> Test Settings&gt;Groups</a> under your Preflight account.
</div></div>

</li>
<li><code>environmentId : String</code>
<div><div>
 (optional) Environment ID for your test group. You can get it from <a href="https://app.preflight.com/tests/settings/environments" rel="nofollow">Test Settings&gt;Environments</a> under your Preflight account.
</div></div>

</li>
<li><code>platforms : String</code>
<div><div>
 (optional) Platforms and browsers you want to run your PreFlight tests. 
 <ul>
  <li>Example usage <code>win-chrome</code>.</li>
  <li>You can pass more than one browser option. Ex. <code>win-chrome,win-firefox</code></li>
  <li>Platform options : <code>win</code></li>
  <li>Browser options : <code>chrome, ie, edge, firefox</code></li>
 </ul>
</div></div>

</li>
<li><code>sizes : String</code>
<div><div>
 (optional) Sizes you want to run your PreFlight tests. 
 <ul>
  <li>Example usage. (WidthxHeight) <code>1440x900</code>.</li>
  <li>You can pass more than one size option. Ex. <code>1920x1080, 1440x900</code></li>
  <li>Size options : <code>1920x1080, 1440x900, 1024x768, 480x640</code></li>
 </ul>
</div></div>

</li>
<li><code>captureScreenshots : boolean</code>
<div><div>
 Capture screenshots enables taking screenshots of the each step.
</div></div>

</li>
<li><code>waitResults : boolean</code>
<div><div>
 Wait PreFlight test result(s). If you set it as true, your Jenkins build waits your PreFlight test result(s).
</div></div>

</li>
</ul>


++++
