= Helix QAC Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/prqa-plugin">Visit the Jenkins Plugins site</a>
++++


=== `qacReport`: Helix QAC Report
++++
<ul><li><code>runWhenSuccess : boolean</code>
</li>
<li><code>sourceQAFramework</code>
<ul><b>Nested Object</b>
<li><code>qaInstallation : String</code>
</li>
<li><code>qaProject : String</code>
</li>
<li><code>useCustomLicenseServer : boolean</code>
</li>
<li><code>customLicenseServerAddress : String</code>
</li>
<li><code>downloadUnifiedProjectDefinition : boolean</code>
</li>
<li><code>unifiedProjectName : String</code>
</li>
<li><code>performCrossModuleAnalysis : boolean</code>
</li>
<li><code>cmaProjectName : String</code>
</li>
<li><code>enableDependencyMode : boolean</code>
</li>
<li><code>generateReport : boolean</code>
</li>
<li><code>publishToQAV : boolean</code>
</li>
<li><code>loginToQAV : boolean</code>
</li>
<li><code>chosenServers : Array / List of String</code>
<ul></ul></li>
<li><code>uploadWhenStable : boolean</code>
</li>
<li><code>qaVerifyProjectName : String</code>
</li>
<li><code>uploadSnapshotName : String</code>
</li>
<li><code>buildNumber : String</code>
</li>
<li><code>uploadSourceCode : String</code>
</li>
<li><code>generateCrr : boolean</code>
</li>
<li><code>generateMdr : boolean</code>
</li>
<li><code>generateHis : boolean</code>
</li>
<li><code>generateSup : boolean</code>
</li>
<li><code>analysisSettings : boolean</code>
</li>
<li><code>stopWhenFail : boolean</code>
</li>
<li><code>customCpuThreads : boolean</code>
</li>
<li><code>maxNumThreads : String</code>
</li>
<li><code>generatePreprocess : boolean</code>
</li>
<li><code>assembleSupportAnalytics : boolean</code>
</li>
<li><code>generateReportOnAnalysisError : boolean</code>
</li>
<li><code>addBuildNumber : boolean</code>
</li>
<li><code>projectConfiguration : String</code>
</li>
</ul></li>
<li><code>thresholdsDesc</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'FileComplianceThreshold'</code><div>
<ul><li><code>value : double</code>
</li>
<li><code>improvement : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'MessageComplianceThreshold'</code><div>
<ul><li><code>value : int</code>
</li>
<li><code>thresholdLevel : int</code>
</li>
<li><code>improvement : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'ProjectComplianceThreshold'</code><div>
<ul><li><code>value : double</code>
</li>
<li><code>improvement : boolean</code>
</li>
</ul></div></li>
</ul></li>
</ul>


++++
