= Publish Over Dropbox
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/publish-over-dropbox">Visit the Jenkins Plugins site</a>
++++


=== `dropbox`: Publish to Dropbox folder
++++
<ul><li><code>sourceFiles : String</code>
<div><div>
 <p>Files to upload to the Dropbox location.</p>
 <p>The string is a comma separated list of includes for an Ant fileset eg. '**/*.jar' (see <a href="http://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Patterns</a> in the Ant manual).<br>
   The base directory for this fileset is the workspace.</p>
</div></div>

</li>
<li><code>remoteDirectory : String</code>
<div><div>
 <p>Destination folder.</p>
 <p>This folder will be below the one in the global configuration. The folder will be created if does not exist.</p>
</div></div>

</li>
<li><code>configName : String</code>
<div><div>
 <p>Select an Dropbox location from the list configured in the global configuration of this Jenkins.</p>
 <p>The configuration defines the account properties and base directory of the Dropbox location.</p>
</div></div>

</li>
<li><code>cleanRemote : boolean</code> (optional)
<div><div>
 <p>Select to delete all files and directories within the remote directory before transferring files.</p>
</div></div>

</li>
<li><code>excludes : String</code> (optional)
</li>
<li><code>flatten : boolean</code> (optional)
<div><div>
 <p>Only create files on the server, do not create directories (except for the remote directory).</p>
 <p>All files that have been selected to transfer must have unique filenames. Publishing will stop and fail as soon as a duplicate filename is found when using the flatten option.</p>
</div></div>

</li>
<li><code>pruneDays : int</code> (optional)
<div><div>
 <p>Directory created more then this number of days ago are considered old for pruning of root.</p>
</div></div>

</li>
<li><code>pruneRoot : boolean</code> (optional)
<div><div>
 <p>Directories older then the max days will be deleted.</p>
 <p>A date format directory format can lead to a long list of directories. Removing old directories in the remote root will allow you to prune that list.</p>
</div></div>

</li>
<li><code>remoteDirectorySDF : boolean</code> (optional)
<div><div>
 <p>Select this to include the timestamp in the remote directory.</p>
 <p>The timestamp is the date of build. This setting turns the remote directory option into a java SimpleDateFormat. The SimpleDateFormat(SDF) uses letters to represent components of the date, like the month, year, or day of the week. The <a href="http://download.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html" rel="nofollow">SimpleDateFormat documentation</a> has more information about the date patterns. As the SDF reserves all of the letters [A-Z][a-z], any that you want to appear literally in the directory that is created will need to be quoted.</p>
</div></div>

</li>
<li><code>removePrefix : String</code> (optional)
<div><div>
 <p>First part of the file path that should not be created on the remote server.</p>
 <p>Directory structures are created relative to the base directory, which is usually the workspace.You normally do not want the full path to these files to be created on the server. For example if Source files were target/deployment/images/**/ then you may want Remove prefix to be target/deployment This would create the images folder under the remote directory, and not target/deployment If you use remove prefix, then ALL source file paths MUST start with the prefix.</p>
</div></div>

</li>
</ul>


++++
=== `step([$class: 'DropboxPublisherPlugin'])`: Send build artifacts over Dropbox
++++
<div><div>
 Send build artifacts to a Dropbox account
</div></div>
<ul><li><code>publishers</code>
<ul><b>Array / List of Nested Object</b>
<li><code>configName : String</code>
<div><div>
 <p>Select an Dropbox account from the list configured in the global configuration of this Jenkins.</p>
 <p>The configuration defines the connection properties and base directory of the Dropbox publication.</p>
</div></div>

</li>
<li><code>verbose : boolean</code>
<div><div>
 Select to enable logging of all commands sent to, and responses received from the Dropbox server in the Jenkins console.
</div></div>

</li>
<li><code>transfers</code>
<ul><b>Array / List of Nested Object</b>
<li><code>sourceFiles : String</code>
<div><div>
 <p>Files to upload to a server.</p>
 <p>The string is a comma separated list of includes for an Ant fileset eg. '**/*.jar' (see <a href="http://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Patterns</a> in the Ant manual).<br>
   The base directory for this fileset is the workspace.</p>
</div></div>

</li>
<li><code>excludes : String</code>
<div><div>
 <p>Exclude files from the Transfer set.</p>
 <p>The string is a comma separated list of excludes for an Ant fileset eg. '**/*.log,**/*.tmp,.git/' (see <a href="http://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Patterns</a> in the Ant manual)</p>
</div></div>

</li>
<li><code>remoteDirectory : String</code>
<div><div>
 <p>Optional destination folder.</p>
 <p>This folder will be below the one in the global configuration, if present.<br>
   The folder will be created if does not exist.</p>
</div></div>

</li>
<li><code>removePrefix : String</code>
<div><div>
 <p>First part of the file path that should not be created on the remote server.</p>
 <p>Directory structures are created relative to the base directory, which is usually the workspace.<br>
   You normally do not want the full path to these files to be created on the server.<br>
   For example if Source files were <code>target/deployment/images/**/</code> then you may want Remove prefix to be <code>target/deployment</code> This would create the images folder under the remote directory, and not target/deployment<br>
   Jenkins environment variables can be used in this path.</p>
 <p><strong>If you use remove prefix, then ALL source file paths MUST start with the prefix.</strong></p>
</div></div>

</li>
<li><code>remoteDirectorySDF : boolean</code>
<div><div>
 <p>Select this to include the timestamp in the remote directory.</p>
 <p>The timestamp is the date of build. If this publisher is being used during a promotion, then the timestamp is that of the build that is being promoted. <br>
  This setting turns the remote directory option into a java SimpleDateFormat. <br>
  The SimpleDateFormat(SDF) uses letters to represent components of the date, like the month, year, or day of the week. <a href="http://download.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html" rel="nofollow">Click here for more information about the date patterns.</a> <br>
  As the SDF reserves all of the letters [A-Z][a-z], any that you want to appear literally in the directory that is created will need to be quoted.</p>
 <p>Some examples follow - all examples are based on a build with a timestamp of 3:45 pm and 55 seconds on the 7th November 2010. <br></p>
 <table>
  <tbody>
   <tr>
    <th>Remote directory</th>
    <th>Directories created</th>
   </tr>
   <tr>
    <td><code>'qa-approved/'yyyyMMddHHmmss</code></td>
    <td><code>qa-approved/20101107154555</code></td>
   </tr>
   <tr>
    <td><code>'builds/'yyyy/MM/dd/'build-${BUILD_NUMBER}'</code></td>
    <td><code>builds/2010/11/07/build-456</code> (if the build was number 456)</td>
   </tr>
   <tr>
    <td><code>yyyy_MM/'build'-EEE-d-HHmmss</code></td>
    <td><code>2010_11/build-Sun-7-154555</code></td>
   </tr>
   <tr>
    <td><code>yyyy-MM-dd_HH-mm-ss</code></td>
    <td><code>2010-11-07_15-45-55</code></td>
   </tr>
  </tbody>
 </table>
 <p></p>
</div></div>

</li>
<li><code>flatten : boolean</code>
<div><div>
 <p>Only create files on the server, don't create directories (except for the remote directory, if present)</p>
 <p><strong>All files that have been selected to transfer must have unique filenames.</strong> The publisher will stop and fail as soon as a duplicate filename is found when using the flatten option.</p>
</div></div>

</li>
<li><code>cleanRemote : boolean</code>
<div><div>
 <p>Select to delete all files and directories within the remote directory before transferring files.</p>
</div></div>

</li>
<li><code>pruneRoot : boolean</code>
<div><div>
 <p>A date format directory format can lead to a long list of directories. Removing old directories in the remote root will allow you to prune that list.</p>
 <p>Directories older then the max days will be deleted.</p>
</div></div>

</li>
<li><code>pruneRootDays : int</code>
</li>
</ul></li>
<li><code>useWorkspaceInPromotion : boolean</code>
<div><div>
 <p>Set the root directory for the Source files to the workspace</p>
 <p>By default this plugin uses the artifacts directory (where archived artifacts are stored). This allows the artifacts from the build number that you are promoting to be sent somewhere else.</p>
 <p>If you run tasks that produce files in the workspace during the promotion and you want to publish them, then set this option.</p>
 <p>If you need to send files from both the workspace and the archive directory, then you need to add a second server, even if you want to send the files to the same place. This is due to the fact that the workspace is not necessarily on the same host as the archive directory</p>
</div></div>

</li>
<li><code>usePromotionTimestamp : boolean</code>
<div><div>
 <p>Use the build time of the promotion when the remote directory is a date format</p>
 <p>By default this plugin uses the time of the original build (the one that is being promoted) when formatting the remote directory. Setting this option will mean that if you use the remote directory is a date format option, it will use the time that the promotion process runs, instead of the original build.</p>
</div></div>

</li>
<li><code>dropboxRetry</code>
<div><div>
 <p>If publishing to this server fails, try again.</p>
 <p>Files that were successfully transferred will not be re-sent.<br>
   If the <em>Clean remote</em> option is selected, and succeeds, it will not be attempted again.</p>
</div></div>

<ul><b>Nested Object</b>
<li><code>retries : int</code>
<div><div>
 The number of times to retry this server in the event of failure
</div></div>

</li>
<li><code>retryDelay : long</code>
<div><div>
 The time to wait, in milliseconds, before attempting another transfer
</div></div>

</li>
</ul></li>
<li><code>dropboxLabel</code>
<div><div>
 <p>Set the label for this Server instance - for use with Parameterized publishing</p>
 <p>Expand the help for Parameterized publishing for more details</p>
</div></div>

<ul><b>Nested Object</b>
<li><code>label : String</code>
<div><div>
 <p>Set the label for this Server instance - for use with Parameterized publishing</p>
 <p>Expand the help for Parameterized publishing for more details</p>
</div></div>

</li>
</ul></li>
</ul></li>
<li><code>continueOnError : boolean</code>
<div><div>
 Select to continue publishing to the other Dropbox accounts after a problem with a previous account
</div></div>

</li>
<li><code>failOnError : boolean</code>
<div><div>
 Select to mark the build as a failure if there is a problem publishing to an account. The default is to mark the build as unstable
</div></div>

</li>
<li><code>alwaysPublishFromMaster : boolean</code>
<div><div>
 <p>Select to publish from the Jenkins master.</p>
 <p>The default is to publish from the server that holds the files to transfer (workspace on the slave, or artifacts directory on the master)<br>
   Enabling this option could help dealing with strict network configurations and firewall rules.<br>
   This option will cause the files to be transferred through the master before being sent to the remote server, this may increase network traffic, and could increase the build time.</p>
</div></div>

</li>
<li><code>masterNodeName : String</code>
<div><div>
 <p>Set the NODE_NAME for the master Jenkins.</p>
 <p>Set this option to give a value to the NODE_NAME environment variable when the value is missing (the Jenkins master).<br>
   This is useful if you use the $NODE_NAME variable in the remoteDirectory option and the build may occur on the master.</p>
</div></div>

</li>
</ul>


++++
