= Qiniu
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/qiniu">Visit the Jenkins Plugins site</a>
++++


=== `archiveArtifactsToQiniu`: Archive the artifacts to Qiniu
++++
<ul><li><code>includeFilesGlob : String</code>
<div><div>
 You can use wildcards like 'module/dist/**/*.zip'. See <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow"> the includes attribute of Ant fileset</a> for the exact format. The base directory is <a rel="nofollow">the workspace</a>. You can only archive files that are located in your workspace.
</div></div>

</li>
<li><code>excludeFilesGlob : String</code>
<div><div>
 Optionally specify <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">the 'excludes' pattern</a>, such as "foo/bar/**/*". A file that matches this mask will not be archived even if it matches the mask specified in 'files to archive' section.
</div></div>

</li>
<li><code>allowEmptyArchive : boolean</code>
</li>
<li><code>onlyIfSuccessful : boolean</code>
</li>
<li><code>useDefaultExcludes : boolean</code>
<div><div>
 <p>Artifact archiver uses Ant <code>org.apache.tools.ant.DirectoryScanner</code> which excludes by default the following patterns:<br><code>**/%*%,**/.git/**,**/SCCS,**/.bzr,**/.hg/**,**/.bzrignore,**/.git,**/SCCS/**,**/.hg,**/.#*,**/vssver.scc,**/.bzr/**,**/._*,**/#*#,**/*~,**/CVS,**/.hgtags,**/.svn/**,**/.hgignore,**/.svn,**/.gitignore,**/.gitmodules,**/.hgsubstate,**/.gitattributes,**/CVS/**,**/.hgsub,**/.DS_Store,**/.cvsignore</code></p>
 <p>This option allows to enable or disable the default Ant exclusions.</p>
</div></div>

</li>
<li><code>caseSensitive : boolean</code>
<div><div>
 Artifact archiver uses Ant <code>org.apache.tools.ant.DirectoryScanner</code> which by default is case sensitive. For instance, if the job produces *.hpi files, pattern "**/*.HPI" will fail to find them.
 <br>
 <br>
  This option can be used to disable case sensitivity. When it's unchecked, pattern "**/*.HPI" will match any *.hpi files, or pattern "**/cAsEsEnSiTiVe.jar" will match a file called caseSensitive.jar.
</div></div>

</li>
</ul>


++++
