= QMetry for JIRA - Test Management Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/qmetry-for-jira-test-management">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'QTM4JResultPublisher'])`: Publish test result to QMetry for JIRA Old
++++
<ul><li><code>name : String</code>
</li>
<li><code>apikey : String</code>
</li>
<li><code>file : String</code>
</li>
<li><code>attachFile : boolean</code>
</li>
<li><code>testrunname : String</code>
</li>
<li><code>labels : String</code>
</li>
<li><code>sprint : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>component : String</code>
</li>
<li><code>format : String</code>
</li>
<li><code>platform : String</code>
</li>
<li><code>comment : String</code>
</li>
<li><code>apikeyserver : String</code>
</li>
<li><code>jiraurlserver : String</code>
</li>
<li><code>proxyUrl : String</code>
</li>
<li><code>password</code>
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>testrunnameserver : String</code>
</li>
<li><code>labelsserver : String</code>
</li>
<li><code>sprintserver : String</code>
</li>
<li><code>versionserver : String</code>
</li>
<li><code>componentserver : String</code>
</li>
<li><code>username : String</code>
</li>
<li><code>fileserver : String</code>
</li>
<li><code>attachFileServer : boolean</code>
</li>
<li><code>formatserver : String</code>
</li>
<li><code>platformserver : String</code>
</li>
<li><code>commentserver : String</code>
</li>
<li><code>testToRun : String</code>
</li>
<li><code>testrunkey : String</code>
</li>
<li><code>testassethierarchy : String</code>
</li>
<li><code>testCaseUpdateLevel : String</code>
</li>
<li><code>jirafields : String</code>
</li>
<li><code>testrunkeyserver : String</code>
</li>
<li><code>testassethierarchyserver : String</code>
</li>
<li><code>testCaseUpdateLevelServer : String</code>
</li>
<li><code>jirafieldsserver : String</code>
</li>
<li><code>disableaction : boolean</code>
</li>
<li><code>serverAuthenticationType : String</code>
</li>
<li><code>personalAccessToken : String</code>
</li>
</ul>


++++
=== `step([$class: 'TestReportDeployPublisher'])`: Publish results to QMetry for Jira version 3.X below
++++
<ul><li><code>name : String</code>
</li>
<li><code>apikey : String</code>
<div><div>
 <strong> API Key is unique for a specific user in a single project </strong>. The result will be imported for the project associated with the given API Key.
</div></div>

</li>
<li><code>file : String</code>
<div><div>
 <strong>Path of the result file/directory relative to build directory.</strong>
</div></div>

</li>
<li><code>attachFile : boolean</code>
<div><div>
 Check for upload attachments in execution. Default value: false.
</div></div>

</li>
<li><code>testrunname : String</code>
<div><div>
 Name of the test run to be created. For example:<strong> Test Run </strong>
</div></div>

</li>
<li><code>labels : String</code>
<div><div>
 Comma separated names of Labels to be added to the test run. For example: <strong> label1, label2 </strong>
</div></div>

</li>
<li><code>sprint : String</code>
<div><div>
 Name of Sprint to be added to the test run. For example: <strong>Final sprint</strong>
</div></div>

</li>
<li><code>version : String</code>
<div><div>
 Comma separated names of versions to be added to the test run. For example: <strong>version1, version2</strong>
</div></div>

</li>
<li><code>component : String</code>
<div><div>
 Comma separated names of Components to be added to the test run. For example: <strong>component1, component2</strong>
</div></div>

</li>
<li><code>format : String</code>
</li>
<li><code>platform : String</code>
<div><div>
 Name of Platform on which test run to be executed. For example: <strong>IOS</strong>
</div></div>

</li>
<li><code>comment : String</code>
<div><div>
 Comment to be added to the test run.
</div></div>

</li>
<li><code>apikeyserver : String</code>
<div><div>
 <strong> API Key is unique for a specific user in a single project </strong>. The result will be imported for the project associated with the given API Key.
</div></div>

</li>
<li><code>jiraurlserver : String</code>
<div><div>
 Your JIRA url. Example:https://qmetryjiraeval.qmetry.com/rest/qtm/latest/automation/importresults
</div></div>

</li>
<li><code>proxyUrl : String</code>
</li>
<li><code>password</code>
<div><div>
 <strong> Password for your account.</strong>
</div></div>

<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>testrunnameserver : String</code>
<div><div>
 Name of the test run to be created. For example:<strong> Test Run </strong>
</div></div>

</li>
<li><code>labelsserver : String</code>
<div><div>
 Comma separated names of Labels to be added to the test run. For example: <strong> label1, label2 </strong>
</div></div>

</li>
<li><code>sprintserver : String</code>
<div><div>
 Name of Sprint to be added to the test run. For example: <strong>Final sprint</strong>
</div></div>

</li>
<li><code>versionserver : String</code>
<div><div>
 Comma separated names of versions to be added to the test run. For example: <strong>version1, version2</strong>
</div></div>

</li>
<li><code>componentserver : String</code>
<div><div>
 Comma separated names of Components to be added to the test run. For example: <strong>component1, component2</strong>
</div></div>

</li>
<li><code>username : String</code>
<div><div>
 <strong>Username for your account.</strong>
</div></div>

</li>
<li><code>fileserver : String</code>
<div><div>
 <strong>Path of the result file/directory relative to build directory</strong>
</div></div>

</li>
<li><code>attachFileServer : boolean</code>
<div><div>
 Check for upload attachments in execution. Default value: false.
</div></div>

</li>
<li><code>formatserver : String</code>
</li>
<li><code>platformserver : String</code>
<div><div>
 Name of Platform on which test run to be executed. For example: <strong>IOS</strong>
</div></div>

</li>
<li><code>commentserver : String</code>
<div><div>
 Comment to be added to the test run.
</div></div>

</li>
<li><code>testToRun : String</code>
</li>
<li><code>testrunkey : String</code>
<div><div>
 Provide Test Run key to append new results to existing Test Run.
</div></div>

</li>
<li><code>testassethierarchy : String</code>
</li>
<li><code>testCaseUpdateLevel : String</code>
<div><div>
 Test Case update level while reusing test case, starts from 0 to 2. (This is only applicable when you use TestCase-TestStep Hierarchy option) Default :- No change in test steps while reusing Test Case.
</div></div>

</li>
<li><code>jirafields : String</code>
<div><div>
 Provide JSON array of custom jirafields.
</div></div>

</li>
<li><code>testrunkeyserver : String</code>
<div><div>
 Provide Test Run key to append new results to existing Test Run.
</div></div>

</li>
<li><code>testassethierarchyserver : String</code>
</li>
<li><code>testCaseUpdateLevelServer : String</code>
<div><div>
 Test Case update level while reusing test case, starts from 0 to 2. (This is only applicable when you use TestCase-TestStep Hierarchy option) Default :- No change in test steps while reusing Test Case.
</div></div>

</li>
<li><code>jirafieldsserver : String</code>
<div><div>
 Provide JSON array of custom jirafields.
</div></div>

</li>
<li><code>disableaction : boolean</code>
</li>
<li><code>serverAuthenticationType : String</code>
</li>
<li><code>personalAccessToken : String</code>
<div><div>
 <strong>Enter Personal Access Token of your account.</strong>
</div></div>

</li>
</ul>


++++
=== `step([$class: 'TestReportDeployPublisherCloudV4'])`: Publish results to QMetry for Jira version 4.X above
++++
<ul><li><code>testToRun : String</code>
</li>
<li><code>apikey : String</code>
<div><div>
 <strong> API Key is unique for a specific user in a single project </strong>. The result will be imported for the project associated with the given API Key.
</div></div>

</li>
<li><code>file : String</code>
<div><div>
 <strong>Path of the result file/directory relative to build directory.</strong>
</div></div>

</li>
<li><code>attachFile : boolean</code>
<div><div>
 Pass true to upload attachments in execution. Default value: false. For more details, Refer automation help documents.
</div></div>

</li>
<li><code>matchTestSteps : boolean</code>
<div><div>
 <strong> Match Test Steps - True/False, True is the default. </strong>
 <br>
  True - Create/Reuse a test case with a summary and test steps that exactly match the automated test case uploaded through the result file. The execution results and other execution details of the test case and steps will be imported from the automation result file. 
 <br>
  False - Create/Reuse a test case with a summary or test case key that exactly matches the automated test case uploaded through the result file, and exclude matching of test steps. The execution results of the test case will be imported or calculated based on the test case/step results from the automation result file. The execution result of the test case will be propagated to the test steps in the case of test case reuse/creation. Individual test case steps will not be matched and their execution results/details will not be picked from the result file. 
 <br>
</div></div>

</li>
<li><code>format : String</code>
</li>
<li><code>disableaction : boolean</code>
</li>
<li><code>testCycleToReuse : String</code>
<div><div>
 Issue Key of the test cycle to be reused. If issue key of test cycle is not provided it will create new Cycle.
</div></div>

</li>
<li><code>environment : String</code>
<div><div>
 Name of the environment on which test cycle has to be executed. Default Value is "No Environment".
</div></div>

</li>
<li><code>build : String</code>
<div><div>
 Name of the build for test cycle execution
</div></div>

</li>
<li><code>testCycleLabels : String</code>
<div><div>
 Comma separated names of Labels to be added to the test cycle. For example: <strong> label1, label2 </strong> To get values check under: Qmetry &gt; Configuration &gt; Labels
</div></div>

</li>
<li><code>testCycleComponents : String</code>
<div><div>
 Comma separated names of Components to be added to the test cycle. For example: <strong>component1, component2</strong> To get values check under: Qmetry &gt; Configuration &gt; Component
</div></div>

</li>
<li><code>testCyclePriority : String</code>
<div><div>
 Default value for Priority [High,Blocker,Low,Medium]. To get other values check under Qmetry &gt; Configuration &gt; Priority
</div></div>

</li>
<li><code>testCycleStatus : String</code>
<div><div>
 Default value for Priority [Done,In Progress,To Do]. To get other values check under Qmetry &gt; Configuration &gt; Statuses &gt; Test Cycle
</div></div>

</li>
<li><code>testCycleSprintId : String</code>
</li>
<li><code>testCycleFixVersionId : String</code>
</li>
<li><code>testCycleSummary : String</code>
</li>
<li><code>testCycleCustomFields : String</code>
<div><div>
 Enter Test Cycle Custom Fields in Json Array Format. 
 <br>
  For example: <strong>[{"name": "custom field 1", "value": "high,medium,low"}, {"name": "custom field 2", "value": "29/May/2020"}] </strong>
 <br>
  To get more information check under: Qmetry &gt; Configuration &gt; Custom Fields &gt; Test Cycle
</div></div>

</li>
<li><code>testCycleStartDate : String</code>
<div><div>
 Pass date in 'dd/MMM/yyyy HH:mm' format
</div></div>

</li>
<li><code>testCycleEndDate : String</code>
<div><div>
 Pass date in 'dd/MMM/yyyy HH:mm' format
</div></div>

</li>
<li><code>testCycleReporter : String</code>
<div><div>
 Enter Valid User Account Id
</div></div>

</li>
<li><code>testCycleAssignee : String</code>
<div><div>
 Enter Valid User Account Id
</div></div>

</li>
<li><code>testCycleDescription : String</code>
</li>
<li><code>testCycleFolderId : String</code>
<div><div>
 Enter folder id for Test Cycle. 
 <br>
  To get it, Go to QTM4J Test Cycle panel &gt; Right click on any folder &gt; select 'Copy Folder Id' option &gt; Paste it here.
</div></div>

</li>
<li><code>testCaseLabels : String</code>
<div><div>
 Comma separated names of Labels to be added to the test case. For example: <strong> label1, label2 </strong> To get values check under: Qmetry &gt; Configuration &gt; Labels
</div></div>

</li>
<li><code>testCaseEstimatedTime : String</code>
<div><div>
 Pass time in 'HH:mm' format
</div></div>

</li>
<li><code>testCaseReporter : String</code>
<div><div>
 Enter Valid User Account Id
</div></div>

</li>
<li><code>testCaseAssignee : String</code>
<div><div>
 Enter Valid User Account Id
</div></div>

</li>
<li><code>testCaseDescription : String</code>
</li>
<li><code>testCasePrecondition : String</code>
</li>
<li><code>testCaseComponents : String</code>
<div><div>
 Comma separated names of Components to be added to the test case. For example: <strong>component1, component2</strong> To get values check under: Qmetry &gt; Configuration &gt; Component
</div></div>

</li>
<li><code>testCasePriority : String</code>
<div><div>
 Default value for Priority [High,Blocker,Low,Medium]. To get other values check under Qmetry &gt; Configuration &gt; Priority
</div></div>

</li>
<li><code>testCaseStatus : String</code>
<div><div>
 Default value for Status [Done,In Progress,To Do]. To get other values check under Qmetry &gt; Configuration &gt; Statuses &gt; Test Case
</div></div>

</li>
<li><code>testCaseSprintId : String</code>
</li>
<li><code>testCaseFixVersionId : String</code>
</li>
<li><code>testCaseCustomFields : String</code>
<div><div>
 Enter Test Case Custom Fields in Json Array Format. 
 <br>
  For example: <strong>[{"name": "custom field 1", "value": "high,medium,low"}, {"name": "custom field 2", "value": "29/May/2020"}] </strong>
 <br>
  To get more information check under: Qmetry &gt; Configuration &gt; Custom Fields &gt; Test Case
</div></div>

</li>
<li><code>testCaseFolderId : String</code>
<div><div>
 Enter folder id for Test Case. 
 <br>
  To get it, Go to QTM4J Test Case panel &gt; Right click on any folder &gt; select 'Copy Folder Id' option &gt; Paste it here.
</div></div>

</li>
<li><code>jiraUrlServer : String</code>
<div><div>
 Your JIRA url. Example:http://qtm4j.qmetry.com:8080/rest/qtm4j/automation/latest/importresult
</div></div>

</li>
<li><code>proxyUrl : String</code>
</li>
<li><code>username : String</code>
<div><div>
 <strong>Username for your account.</strong>
</div></div>

</li>
<li><code>password</code>
<div><div>
 <strong> Password for your account.</strong>
</div></div>

<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>apikeyServer : String</code>
<div><div>
 <strong> API Key is unique for a specific user in a single project </strong>. The result will be imported for the project associated with the given API Key.
</div></div>

</li>
<li><code>formatServer : String</code>
</li>
<li><code>fileServer : String</code>
<div><div>
 <strong>Path of the result file/directory relative to build directory.</strong>
</div></div>

</li>
<li><code>testCycleToReuseServer : String</code>
<div><div>
 Issue Key of the test cycle to be reused. If issue key of test cycle is not provided it will create new Cycle.
</div></div>

</li>
<li><code>environmentServer : String</code>
<div><div>
 Name of the environment on which test cycle has to be executed. Default Value is "No Environment".
</div></div>

</li>
<li><code>buildServer : String</code>
<div><div>
 Name of the build for test cycle execution
</div></div>

</li>
<li><code>attachFileServer : boolean</code>
<div><div>
 Pass true to upload attachments in execution. Default value: false. For more details, Refer automation help documents.
</div></div>

</li>
<li><code>matchTestStepsServer : boolean</code>
<div><div>
 <strong> Match Test Steps - True/False, True is the default. </strong>
 <br>
  True - Create/Reuse a test case with a summary and test steps that exactly match the automated test case uploaded through the result file. The execution results and other execution details of the test case and steps will be imported from the automation result file. 
 <br>
  False - Create/Reuse a test case with a summary or test case key that exactly matches the automated test case uploaded through the result file, and exclude matching of test steps. The execution results of the test case will be imported or calculated based on the test case/step results from the automation result file. The execution result of the test case will be propagated to the test steps in the case of test case reuse/creation. Individual test case steps will not be matched and their execution results/details will not be picked from the result file. 
 <br>
</div></div>

</li>
<li><code>testCycleLabelsServer : String</code>
<div><div>
 Comma separated names of Labels to be added to the test cycle. For example: <strong> label1, label2 </strong> To get values check under: Qmetry &gt; Configuration &gt; Labels
</div></div>

</li>
<li><code>testCycleComponentsServer : String</code>
<div><div>
 Comma separated names of Components to be added to the test cycle. For example: <strong>component1, component2</strong> To get values check under: Qmetry &gt; Configuration &gt; Component
</div></div>

</li>
<li><code>testCyclePriorityServer : String</code>
<div><div>
 Default value for Priority [High,Blocker,Low,Medium]. To get other values check under Qmetry &gt; Configuration &gt; Priority
</div></div>

</li>
<li><code>testCycleStatusServer : String</code>
<div><div>
 Default value for Priority [Done,In Progress,To Do]. To get other values check under Qmetry &gt; Configuration &gt; Statuses &gt; Test Cycle
</div></div>

</li>
<li><code>testCycleSprintIdServer : String</code>
</li>
<li><code>testCycleFixVersionIdServer : String</code>
</li>
<li><code>testCycleSummaryServer : String</code>
</li>
<li><code>testCycleStartDateServer : String</code>
<div><div>
 Pass date in 'dd/MMM/yyyy HH:mm' format
</div></div>

</li>
<li><code>testCycleEndDateServer : String</code>
<div><div>
 Pass date in 'dd/MMM/yyyy HH:mm' format
</div></div>

</li>
<li><code>testCycleAssigneeServer : String</code>
<div><div>
 Enter Valid User Account Id
</div></div>

</li>
<li><code>testCycleReporterServer : String</code>
<div><div>
 Enter Valid User Account Id
</div></div>

</li>
<li><code>testCycleDescriptionServer : String</code>
</li>
<li><code>testCycleCustomFieldsServer : String</code>
<div><div>
 Enter Test Cycle Custom Fields in Json Array Format. 
 <br>
  For example: <strong>[{"name": "custom field 1", "value": "high,medium,low"}, {"name": "custom field 2", "value": "29/May/2020"}] </strong>
 <br>
  To get more information check under: Qmetry &gt; Configuration &gt; Custom Fields &gt; Test Cycle
</div></div>

</li>
<li><code>testCaseEstimatedTimeServer : String</code>
<div><div>
 Pass time in 'HH:mm' format
</div></div>

</li>
<li><code>testCaseAssigneeServer : String</code>
<div><div>
 Enter Valid User Account Id
</div></div>

</li>
<li><code>testCaseReporterServer : String</code>
<div><div>
 Enter Valid User Account Id
</div></div>

</li>
<li><code>testCaseDescriptionServer : String</code>
</li>
<li><code>testCaseCustomFieldsServer : String</code>
<div><div>
 Enter Test Case Custom Fields in Json Array Format. 
 <br>
  For example: <strong>[{"name": "custom field 1", "value": "high,medium,low"}, {"name": "custom field 2", "value": "29/May/2020"}] </strong>
 <br>
  To get more information check under: Qmetry &gt; Configuration &gt; Custom Fields &gt; Test Case
</div></div>

</li>
<li><code>testCaseLabelsServer : String</code>
<div><div>
 Comma separated names of Labels to be added to the test case. For example: <strong> label1, label2 </strong> To get values check under: Qmetry &gt; Configuration &gt; Labels
</div></div>

</li>
<li><code>testCaseComponentsServer : String</code>
<div><div>
 Comma separated names of Components to be added to the test case. For example: <strong>component1, component2</strong> To get values check under: Qmetry &gt; Configuration &gt; Component
</div></div>

</li>
<li><code>testCasePriorityServer : String</code>
<div><div>
 Default value for Priority [High,Blocker,Low,Medium]. To get other values check under Qmetry &gt; Configuration &gt; Priority
</div></div>

</li>
<li><code>testCaseStatusServer : String</code>
<div><div>
 Default value for Status [Done,In Progress,To Do]. To get other values check under Qmetry &gt; Configuration &gt; Statuses &gt; Test Case
</div></div>

</li>
<li><code>testCaseSprintIdServer : String</code>
</li>
<li><code>testCaseFixVersionIdServer : String</code>
</li>
<li><code>serverAuthenticationType : String</code>
</li>
<li><code>personalAccessToken : String</code>
<div><div>
 <strong>Enter Personal Access Token of your account.</strong>
</div></div>

</li>
<li><code>testCycleFolderPathServer : String</code>
<div><div>
 Enter folder path for Test Cycle. For example: <strong>F1/F2/F3</strong>
</div></div>

</li>
<li><code>testCaseFolderPathServer : String</code>
<div><div>
 Enter folder path for Test Case. For example: <strong>F1/F2/F3</strong>
</div></div>

</li>
<li><code>testCasePreconditionServer : String</code>
</li>
<li><code>testCaseExecutionCommentServer : String</code>
<div><div>
 Enter comment to be added to the Test Case Executions.
</div></div>

</li>
<li><code>testCaseExecutionActualTimeServer : String</code>
<div><div>
 Pass time in 'HH:mm' format.
</div></div>

</li>
<li><code>testCaseExecutionAssigneeServer : String</code>
<div><div>
 Enter Valid User Account Id.
</div></div>

</li>
<li><code>testCaseExecutionCustomFieldsServer : String</code>
<div><div>
 Enter Test Case Execution Custom Fields in Json Array Format. 
 <br>
  For example: <strong>[{"name": "custom field 1", "value": "high,medium,low"}, {"name": "custom field 2", "value": "29/May/2020"}] </strong>
 <br>
  To get more information check under: Qmetry &gt; Configuration &gt; Custom Fields &gt; Test Execution
</div></div>

</li>
<li><code>testCaseExecutionPlannedDateServer : String</code>
<div><div>
 Pass date in 'dd/MMM/yyyy' format
</div></div>

</li>
<li><code>automationHierarchyServer : String</code>
<div><div>
 Set Hierarchy for Automation Uploads “Test Cycle - Test Case - Test Step Hierarchy” as Default, 1, 2 or 3 :-
</div>
<ul>
 <li>JUnit 
  <ul>
   <li>Default Settings - Will refer to QMetry &gt; Automation &gt; Automation API &gt; Settings.</li>
   <li>1 - Test Suite Name Tag is created as Test Case &amp; Test Case Name Tag is created as Test Step.</li>
   <li>2 - Test Suite Name Tag is created as Test Cycle &amp; Test Case Name Tag is created as Test Case.</li>
   <li>3 - Test Cycle Summary will be auto-generated &amp; Test Case Name Tag is created as Test Case.</li>
  </ul></li>
 <li>TestNG 
  <ul>
   <li>Default Settings - Will refer to QMetry &gt; Automation &gt; Automation API &gt; Settings.</li>
   <li>1 - Test Name Tag is created as Test Case &amp; Test Method Name Tag is created as Test Step.</li>
   <li>2 - Test Name Tag is created as Test Cycle &amp; Test Method Name Tag is created as Test Case.</li>
   <li>3 - Suite Name Tag is created as Test Cycle &amp; Test Method Name Tag is created as Test Case.</li>
  </ul></li>
</ul></div>

</li>
<li><code>appendTestNameServer : String</code>
<div><div>
 Applicable only for JUnit or TestNG frameworks automation result uploads with Automation Hierarchy 2 or 3 :-
</div>
<ul>
 <li>JUnit 
  <ul>
   <li>Default Settings - Will refer to QMetry &gt; Automation &gt; Automation API &gt; Settings.</li>
   <li>Yes - Append Test Suite Name to Test Case Name while creating the Test Case Summary.</li>
   <li>No - Create the Test Case Summary as per the Test Case Name present in the result file.</li>
  </ul></li>
 <li>TestNG 
  <ul>
   <li>Default Settings - Will refer to QMetry &gt; Automation &gt; Automation API &gt; Settings.</li>
   <li>Yes - Append Test Name to Test Method Name while creating the Test Case Summary.</li>
   <li>No - Create the Test Case Summary as per the Test Method Name in the result file.</li>
  </ul></li>
</ul></div>

</li>
<li><code>automationHierarchy : String</code>
<div><div>
 Set Hierarchy for Automation Uploads “Test Cycle - Test Case - Test Step Hierarchy” as Default, 1, 2 or 3 :-
</div>
<ul>
 <li>JUnit 
  <ul>
   <li>Default Settings - Will refer to QMetry &gt; Automation &gt; Automation API &gt; Settings.</li>
   <li>1 - Test Suite Name Tag is created as Test Case &amp; Test Case Name Tag is created as Test Step.</li>
   <li>2 - Test Suite Name Tag is created as Test Cycle &amp; Test Case Name Tag is created as Test Case.</li>
   <li>3 - Test Cycle Summary will be auto-generated &amp; Test Case Name Tag is created as Test Case.</li>
  </ul></li>
 <li>TestNG 
  <ul>
   <li>Default Settings - Will refer to QMetry &gt; Automation &gt; Automation API &gt; Settings.</li>
   <li>1 - Test Name Tag is created as Test Case &amp; Test Method Name Tag is created as Test Step.</li>
   <li>2 - Test Name Tag is created as Test Cycle &amp; Test Method Name Tag is created as Test Case.</li>
   <li>3 - Suite Name Tag is created as Test Cycle &amp; Test Method Name Tag is created as Test Case.</li>
  </ul></li>
</ul></div>

</li>
<li><code>appendTestName : String</code>
<div><div>
 Applicable only for JUnit or TestNG frameworks automation result uploads with Automation Hierarchy 2 or 3 :-
</div>
<ul>
 <li>JUnit 
  <ul>
   <li>Default Settings - Will refer to QMetry &gt; Automation &gt; Automation API &gt; Settings.</li>
   <li>Yes - Append Test Suite Name to Test Case Name while creating the Test Case Summary.</li>
   <li>No - Create the Test Case Summary as per the Test Case Name present in the result file.</li>
  </ul></li>
 <li>TestNG 
  <ul>
   <li>Default Settings - Will refer to QMetry &gt; Automation &gt; Automation API &gt; Settings.</li>
   <li>Yes - Append Test Name to Test Method Name while creating the Test Case Summary.</li>
   <li>No - Create the Test Case Summary as per the Test Method Name in the result file.</li>
  </ul></li>
</ul></div>

</li>
</ul>


++++
