= QMetry Test Management Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/qmetry-test-management">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'QTMReportPublisher'])`: Publish Build Result(s) to QMetry Test Management
++++
<ul><li><code>qtmUrl : String</code>
<div><div>
 URL to your QTM application
</div></div>

</li>
<li><code>qtmAutomationApiKey : String</code>
<div><div>
 Get your Automation API Key from QTM interface.
</div>
<ol>
 <li>Login to QTM</li>
 <li>Go to Integration &gt; Automation API</li>
 <li>Copy 'Key'</li>
</ol></div>

</li>
<li><code>proxyUrl : String</code>
<div><div>
 Enter Proxy URL
</div></div>

</li>
<li><code>automationFramework : String</code>
<div><div>
 Test Automation framework used in your project to produce Test Result File(s) to be uploaded to QTM. supported formats are :-
</div>
<ul>
 <li>Json file(s) from Cucumber Tests</li>
 <li>Xml file(s) from Junit Tests</li>
 <li>Xml file(s) from TestNG Tests</li>
 <li>Json file(s) from QAS Tests</li>
 <li>XML file(s) from HP-UFT Tests</li>
 <li>XML file(s) from Robot Tests</li>
</ul></div>

</li>
<li><code>automationHierarchy : String</code>
<div><div>
 Hierarchy which will be used to parse test result files on QTM. supported formats are :-
</div>
<ul>
 <li>JUnit 
  <ul>
   <li>1 - Use current Hierarchy in which JUnit  is treated as TestStep and  is treated as Testcase</li>
   <li>2 - Use Junit  as Testcase and link all those (from all testsuites and all files of Junit) to one Testsuite</li>
   <li>3 - Create Multiple Testsuites and then link their respective testcases in corresponding Testsuites</li>
  </ul></li>
 <li>TestNG 
  <ul>
   <li>1 - Use  as Testcase and  as TestStep</li>
   <li>2 - Use  as Testcase</li>
   <li>3 - Use  as TestCase and  as TestStep</li>
  </ul></li>
</ul></div>

</li>
<li><code>testResultFilePath : String</code>
<div><div>
 Path to result files to be uploaded to QTM relative to your Build directory. 
 <br>
  Provide a path to directory to upload multiple files at once.
</div></div>

</li>
<li><code>buildName : String</code>
<div><div>
 Cycle name attached to your test suite in QTM.
</div></div>

</li>
<li><code>testSuiteName : String</code>
<div><div>
 Test suite Key or Id (This will upload results to existing test suite with given Id or Key)
</div></div>

</li>
<li><code>testSName : String</code>
<div><div>
 Test Suite Name (This will create a new test suite with given name. It will be ignored if automation framework is JUnit and automation hierarchy is 3)
</div></div>

</li>
<li><code>tsFolderPath : String</code>
<div><div>
 Test Suite Folder Path (This will upload results to the mentioned Test Suite Folder. It will be ignored if the QMetry instance type is Server.)
</div></div>

</li>
<li><code>platformName : String</code>
<div><div>
 Name of platform linked with Test Suite
</div></div>

</li>
<li><code>project : String</code>
<div><div>
 Target Project ID or project Key or project name
</div></div>

</li>
<li><code>release : String</code>
<div><div>
 Target Release ID or Release name
</div></div>

</li>
<li><code>cycle : String</code>
<div><div>
 Target Cycle Id or Cycle Name
</div></div>

</li>
<li><code>disableaction : boolean</code>
</li>
<li><code>testcaseFields : String</code>
<div><div>
 Enter Test Case Fields in Json Format (add "Field Name" as json key in JSON object.) System defined fields supported by test-case module are description, testCaseType, testCaseState, component, priority, testcaseOwner, estimatedTime. User can also add User defined fields. Ex. testcaseFields: {"description":"Automated Test case", "testCaseType":"Security", "testCaseState":"Rejected", "component":["x"], "priority":"Blocker", "testcaseOwner":"john.deo", "estimatedTime":"143", "userDefinedFields" : {"Integrate" : "Custom Field Test case"}}
</div></div>

</li>
<li><code>testsuiteFields : String</code>
<div><div>
 Enter Test Suite Fields in Json Format (add "Field Name" as json key in JSON object.) System defined fields supported by test-suite module are description, testsuiteOwner, testSuiteState. User can also add Userdefined fields. Ex. testsuiteFields: {"description":"Automated Test suite", "testsuiteOwner": "John.deo", "testSuiteState": "New", "userDefinedFields": {"Integrate" : "Custom Field Test suite"}}
</div></div>

</li>
<li><code>skipWarning : String</code>
<div><div>
 Skip Warning while uploading Test Result File(s) to QTM. supported values are :-
</div>
<ul>
 <li>0 - Test Case Import will be failed if the Test Case summary is more than 255 characters</li>
 <li>1 - Test Case will be imported by truncating the Test Case summary to 255 characters</li>
</ul></div>

</li>
<li><code>isMatchingRequired : String</code>
<div><div>
 Create a new Test Case version or reuse the already created version while uploading Test Result File(s) to QTM. supported values are :-
</div>
<ul>
 <li>1 - Create a new Test Case or Test Case Version if no version matches with the one being uploaded</li>
 <li>0 - Reuse already linked Test Case version on Test Suite OR auto link the existing latest version of Test Case, if the Test Case entity key OR Test Case summary is found matching</li>
</ul></div>

</li>
</ul>


++++
