= qTest Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/qtest">Visit the Jenkins Plugins site</a>
++++


=== `submitJUnitTestResultsToqTest`: Submit jUnit test result to qTest
++++
<ul><li><code>pipeConfiguration</code>
<ul><b>Nested Object</b>
<li><code>qtestURL : String</code>
</li>
<li><code>apiKey : String</code>
</li>
<li><code>projectID : long</code>
</li>
<li><code>containerID : long</code>
</li>
<li><code>containerType : String</code>
</li>
<li><code>overwriteExistingTestSteps : boolean</code>
</li>
<li><code>parseTestResultsFromTestingTools : boolean</code>
</li>
<li><code>createTestCaseForEachJUnitTestClass : boolean</code>
</li>
<li><code>submitToExistingContainer : boolean</code>
</li>
<li><code>submitToAReleaseAsSettingFromQtest : boolean</code>
</li>
<li><code>utilizeTestResultsFromCITool : boolean</code>
</li>
<li><code>createTestCaseForEachJUnitTestMethod : boolean</code>
</li>
<li><code>createNewTestRunsEveryBuildDate : boolean</code> (optional)
</li>
<li><code>environmentID : long</code> (optional)
</li>
<li><code>executeExternalTool</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>executeToscaTests</code><div>
<ul><li><code>command : String</code>
</li>
<li><code>arguments : String</code>
</li>
<li><code>pathToResults : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>parseTestResultsPattern : String</code> (optional)
</li>
</ul></li>
</ul>


++++
