= Qualys Container Scanning Connector
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/qualys-cs">Visit the Jenkins Plugins site</a>
++++


=== `getImageVulnsFromQualys`: Scan container images with Qualys CS
++++
<ul><li><code>useGlobalConfig : boolean</code> (optional)
</li>
<li><code>useLocalConfig : boolean</code> (optional)
</li>
<li><code>apiServer : String</code> (optional)
</li>
<li><code>apiUser : String</code> (optional)
</li>
<li><code>apiPass : String</code> (optional)
</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>pollingInterval : String</code> (optional)
</li>
<li><code>vulnsTimeout : String</code> (optional)
</li>
<li><code>isFailOnSevereVulns : boolean</code> (optional)
</li>
<li><code>severity1Limit : int</code> (optional)
</li>
<li><code>severity2Limit : int</code> (optional)
</li>
<li><code>severity3Limit : int</code> (optional)
</li>
<li><code>severity4Limit : int</code> (optional)
</li>
<li><code>severity5Limit : int</code> (optional)
</li>
<li><code>isSev1Vulns : boolean</code> (optional)
</li>
<li><code>isSev2Vulns : boolean</code> (optional)
</li>
<li><code>isSev3Vulns : boolean</code> (optional)
</li>
<li><code>isSev4Vulns : boolean</code> (optional)
</li>
<li><code>isSev5Vulns : boolean</code> (optional)
</li>
<li><code>proxyServer : String</code> (optional)
</li>
<li><code>proxyPort : int</code> (optional)
</li>
<li><code>proxyUsername : String</code> (optional)
</li>
<li><code>proxyPassword : String</code> (optional)
</li>
<li><code>useProxy : boolean</code> (optional)
</li>
<li><code>proxyCredentialsId : String</code> (optional)
</li>
<li><code>isFailOnQidFound : boolean</code> (optional)
</li>
<li><code>qidList : String</code> (optional)
</li>
<li><code>isFailOnCVEs : boolean</code> (optional)
</li>
<li><code>cveList : String</code> (optional)
</li>
<li><code>isFailOnSoftware : boolean</code> (optional)
</li>
<li><code>softwareList : String</code> (optional)
</li>
<li><code>isPotentialVulnsToBeChecked : boolean</code> (optional)
</li>
<li><code>imageIds : String</code> (optional)
</li>
<li><code>webhookUrl : String</code> (optional)
</li>
<li><code>isExcludeConditions : boolean</code> (optional)
</li>
<li><code>excludeBy : String</code> (optional)
</li>
<li><code>excludeList : String</code> (optional)
</li>
<li><code>failByCvss : boolean</code> (optional)
</li>
<li><code>cvssVersion : String</code> (optional)
</li>
<li><code>cvssThreshold : String</code> (optional)
</li>
<li><code>platform : String</code> (optional)
</li>
<li><code>dockerUrl : String</code> (optional)
</li>
<li><code>dockerCert : String</code> (optional)
</li>
</ul>


++++
