= Qualys Web App Scanning Connector
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/qualys-was">Visit the Jenkins Plugins site</a>
++++


=== `qualysWASScan`: Scan web applications with Qualys WAS
++++
<ul><li><code>platform : String</code>
</li>
<li><code>apiServer : String</code> (optional)
</li>
<li><code>credsId : String</code> (optional)
</li>
<li><code>webAppId : String</code> (optional)
</li>
<li><code>scanName : String</code> (optional)
</li>
<li><code>scanType : String</code> (optional)
</li>
<li><code>authRecord : String</code> (optional)
</li>
<li><code>optionProfile : String</code> (optional)
</li>
<li><code>cancelOptions : String</code> (optional)
</li>
<li><code>cancelHours : String</code> (optional)
</li>
<li><code>optionProfileId : String</code> (optional)
</li>
<li><code>authRecordId : String</code> (optional)
</li>
<li><code>proxyServer : String</code> (optional)
</li>
<li><code>proxyPort : int</code> (optional)
</li>
<li><code>proxyCredentialsId : String</code> (optional)
</li>
<li><code>useProxy : boolean</code> (optional)
</li>
<li><code>pollingInterval : String</code> (optional)
</li>
<li><code>vulnsTimeout : String</code> (optional)
</li>
<li><code>severity1Limit : int</code> (optional)
</li>
<li><code>severity2Limit : int</code> (optional)
</li>
<li><code>severity3Limit : int</code> (optional)
</li>
<li><code>severity4Limit : int</code> (optional)
</li>
<li><code>severity5Limit : int</code> (optional)
</li>
<li><code>isSev1Vulns : boolean</code> (optional)
</li>
<li><code>isSev2Vulns : boolean</code> (optional)
</li>
<li><code>isSev3Vulns : boolean</code> (optional)
</li>
<li><code>isSev4Vulns : boolean</code> (optional)
</li>
<li><code>isSev5Vulns : boolean</code> (optional)
</li>
<li><code>isFailOnQidFound : boolean</code> (optional)
</li>
<li><code>qidList : String</code> (optional)
</li>
<li><code>failOnScanError : boolean</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'WASScanNotifier'])`: Scan web applications with Qualys WAS
++++
<ul><li><code>apiServer : String</code> (optional)
</li>
<li><code>credsId : String</code> (optional)
</li>
<li><code>authRecord : String</code> (optional)
</li>
<li><code>authRecordId : String</code> (optional)
</li>
<li><code>cancelHours : String</code> (optional)
</li>
<li><code>cancelOptions : String</code> (optional)
</li>
<li><code>failOnScanError : boolean</code> (optional)
</li>
<li><code>isFailOnQidFound : boolean</code> (optional)
</li>
<li><code>isSev1Vulns : boolean</code> (optional)
</li>
<li><code>isSev2Vulns : boolean</code> (optional)
</li>
<li><code>isSev3Vulns : boolean</code> (optional)
</li>
<li><code>isSev4Vulns : boolean</code> (optional)
</li>
<li><code>isSev5Vulns : boolean</code> (optional)
</li>
<li><code>optionProfile : String</code> (optional)
</li>
<li><code>optionProfileId : String</code> (optional)
</li>
<li><code>platform : String</code> (optional)
</li>
<li><code>pollingInterval : String</code> (optional)
</li>
<li><code>proxyCredentialsId : String</code> (optional)
</li>
<li><code>proxyPort : int</code> (optional)
</li>
<li><code>proxyServer : String</code> (optional)
</li>
<li><code>qidList : String</code> (optional)
</li>
<li><code>scanName : String</code> (optional)
</li>
<li><code>scanType : String</code> (optional)
</li>
<li><code>severity1Limit : int</code> (optional)
</li>
<li><code>severity2Limit : int</code> (optional)
</li>
<li><code>severity3Limit : int</code> (optional)
</li>
<li><code>severity4Limit : int</code> (optional)
</li>
<li><code>severity5Limit : int</code> (optional)
</li>
<li><code>useProxy : boolean</code> (optional)
</li>
<li><code>vulnsTimeout : String</code> (optional)
</li>
<li><code>webAppId : String</code> (optional)
</li>
</ul>


++++
