= Qualys Policy Compliance Scanning Connector
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/qualys-pc">Visit the Jenkins Plugins site</a>
++++


=== `qualysPolicyComplianceScanner`: Scan host/instances with Qualys PC
++++
<ul><li><code>apiServer : String</code> (optional)
</li>
<li><code>credsId : String</code> (optional)
</li>
<li><code>useProxy : boolean</code> (optional)
</li>
<li><code>createAuthRecord : boolean</code> (optional)
</li>
<li><code>proxyServer : String</code> (optional)
</li>
<li><code>proxyPort : int</code> (optional)
</li>
<li><code>proxyCredentialsId : String</code> (optional)
</li>
<li><code>unixAndWindowsCredentialsId : String</code> (optional)
</li>
<li><code>scanName : String</code> (optional)
</li>
<li><code>useHost : boolean</code> (optional)
</li>
<li><code>hostIp : String</code> (optional)
</li>
<li><code>useEc2 : boolean</code> (optional)
</li>
<li><code>ec2Id : String</code> (optional)
</li>
<li><code>ec2ConnDetails : String</code> (optional)
</li>
<li><code>runConnector : boolean</code> (optional)
</li>
<li><code>optionProfile : String</code> (optional)
</li>
<li><code>scannerName : String</code> (optional)
</li>
<li><code>selectedPolicies : String</code> (optional)
</li>
<li><code>stateFail : boolean</code> (optional)
</li>
<li><code>stateError : boolean</code> (optional)
</li>
<li><code>stateExceptions : boolean</code> (optional)
</li>
<li><code>criticalitySerious : boolean</code> (optional)
</li>
<li><code>criticalityUrgent : boolean</code> (optional)
</li>
<li><code>criticalityCritical : boolean</code> (optional)
</li>
<li><code>criticalityMedium : boolean</code> (optional)
</li>
<li><code>criticalityMinimal : boolean</code> (optional)
</li>
<li><code>failByAuth : boolean</code> (optional)
</li>
<li><code>excludedCids : String</code> (optional)
</li>
<li><code>pollingInterval : String</code> (optional)
</li>
<li><code>vulnsTimeout : String</code> (optional)
</li>
<li><code>unixAndWindowsCredentials : String</code> (optional)
</li>
<li><code>failByStateAndCriticality : boolean</code> (optional)
</li>
<li><code>excludedCriteria : boolean</code> (optional)
</li>
<li><code>platform : String</code> (optional)
</li>
<li><code>ec2ConnAccountId : String</code> (optional)
</li>
<li><code>ec2ConnId : String</code> (optional)
</li>
<li><code>ec2ConnName : String</code> (optional)
</li>
</ul>


++++
