= InsightVM Container Image Scanner
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/rapid7-insightvm-container-assessment">Visit the Jenkins Plugins site</a>
++++


=== `assessContainerImage`: Assess Container Image with Rapid7 InsightVM
++++
<ul><li><code>failOnPluginError : boolean</code> (optional)
<div>Enable this option to fail the build if the plugin encountered any errors.</div>

</li>
<li><code>imageId : String</code> (optional)
<div>Provide a Docker image ID or name which can be referenced by the Docker daemon (e.g. my-repo/my-image:my-tag).</div>

</li>
<li><code>nameRules</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>packageName</code><div>
<ul><li><code>action : String</code>
<div>Select Fail to set the build status to Fail. Select Mark Unstable to set the build status to Unstable.</div>

</li>
<li><code>contains : String</code>
<div>Set the name that will trigger the selected action.</div>

</li>
</ul></div></li>
<li><code>vulnerabilityCategory</code><div>
<ul><li><code>action : String</code>
<div>Select Fail to set the build status to Fail. Select Mark Unstable to set the build status to Unstable.</div>

</li>
<li><code>contains : String</code>
<div>Set the name that will trigger the selected action.</div>

</li>
</ul></div></li>
<li><code>vulnerabilityTitle</code><div>
<ul><li><code>action : String</code>
<div>Select Fail to set the build status to Fail. Select Mark Unstable to set the build status to Unstable.</div>

</li>
<li><code>contains : String</code>
<div>Set the name that will trigger the selected action.</div>

</li>
</ul></div></li>
<li><code>vulnerablePackageName</code><div>
<ul><li><code>action : String</code>
<div>Select Fail to set the build status to Fail. Select Mark Unstable to set the build status to Unstable.</div>

</li>
<li><code>contains : String</code>
<div>Set the name that will trigger the selected action.</div>

</li>
</ul></div></li>
</ul></li>
<li><code>thresholdRules</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>criticalVulnerabilities</code><div>
<ul><li><code>action : String</code>
<div>Select Fail to set the build status to Fail. Select Mark Unstable to set the build status to Unstable.</div>

</li>
<li><code>threshold : String</code>
<div>Set the numeric threshold value that will trigger the selected action.</div>

</li>
</ul></div></li>
<li><code>cvssV2Score</code><div>
<ul><li><code>action : String</code>
<div>Select Fail to set the build status to Fail. Select Mark Unstable to set the build status to Unstable.</div>

</li>
<li><code>threshold : String</code>
<div>Set the numeric threshold value that will trigger the selected action.</div>

</li>
</ul></div></li>
<li><code>exploitableVulnerabilities</code><div>
<ul><li><code>action : String</code>
<div>Select Fail to set the build status to Fail. Select Mark Unstable to set the build status to Unstable.</div>

</li>
<li><code>threshold : String</code>
<div>Set the numeric threshold value that will trigger the selected action.</div>

</li>
</ul></div></li>
<li><code>vulnerabilitiesWithMalwareKits</code><div>
<ul><li><code>action : String</code>
<div>Select Fail to set the build status to Fail. Select Mark Unstable to set the build status to Unstable.</div>

</li>
<li><code>threshold : String</code>
<div>Set the numeric threshold value that will trigger the selected action.</div>

</li>
</ul></div></li>
<li><code>moderateVulnerabilities</code><div>
<ul><li><code>action : String</code>
<div>Select Fail to set the build status to Fail. Select Mark Unstable to set the build status to Unstable.</div>

</li>
<li><code>threshold : String</code>
<div>Set the numeric threshold value that will trigger the selected action.</div>

</li>
</ul></div></li>
<li><code>packageRiskScore</code><div>
<ul><li><code>action : String</code>
<div>Select Fail to set the build status to Fail. Select Mark Unstable to set the build status to Unstable.</div>

</li>
<li><code>threshold : String</code>
<div>Set the numeric threshold value that will trigger the selected action.</div>

</li>
</ul></div></li>
<li><code>riskScore</code><div>
<ul><li><code>action : String</code>
<div>Select Fail to set the build status to Fail. Select Mark Unstable to set the build status to Unstable.</div>

</li>
<li><code>threshold : String</code>
<div>Set the numeric threshold value that will trigger the selected action.</div>

</li>
</ul></div></li>
<li><code>severeVulnerabilities</code><div>
<ul><li><code>action : String</code>
<div>Select Fail to set the build status to Fail. Select Mark Unstable to set the build status to Unstable.</div>

</li>
<li><code>threshold : String</code>
<div>Set the numeric threshold value that will trigger the selected action.</div>

</li>
</ul></div></li>
<li><code>totalVulnerabilities</code><div>
<ul><li><code>action : String</code>
<div>Select Fail to set the build status to Fail. Select Mark Unstable to set the build status to Unstable.</div>

</li>
<li><code>threshold : String</code>
<div>Set the numeric threshold value that will trigger the selected action.</div>

</li>
</ul></div></li>
</ul></li>
<li><code>treatWarningsAsErrors : boolean</code> (optional)
<div>Enable this option to treat warnings as errors, which will fail the build.</div>

</li>
<li><code>workspaceDir : String</code> (optional)
</li>
</ul>


++++
