= Maven Repository Server Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/repository">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'UpdaterPublisher'])`: Publish Maven Artifacts
++++
<ul></ul>


++++
=== `wrap([$class: 'RepositoryDefinitionProperty'])`: Define Upstream Maven Repository
++++
<div><div>
 If selected, this allows you to define a variable - Jenkins.Repository - that will be present in the Maven environment that points to the specified repository. 
 <br>
  The best way of using this is to create a profile in the Jenkins settings.xml: 
 <br>
 <pre>

        &lt;profile&gt;
            &lt;id&gt;jenkins&lt;/id&gt;
            &lt;repositories&gt;
                &lt;repository&gt;
                    &lt;id&gt;jenkins&lt;/id&gt;
                    &lt;url&gt;${env.Jenkins.Repository}&lt;/url&gt;
                    &lt;releases&gt;
                        &lt;enabled&gt;true&lt;/enabled&gt;
                    &lt;/releases&gt;
                    &lt;snapshots&gt;
                        &lt;enabled&gt;true&lt;/enabled&gt;
                    &lt;/snapshots&gt;
                &lt;/repository&gt;
            &lt;/repositories&gt;
            &lt;pluginRepositories&gt;
                &lt;pluginRepository&gt;
                    &lt;id&gt;jenkins&lt;/id&gt;
                    &lt;url&gt;${env.Jenkins.Repository}&lt;/url&gt;
                    &lt;releases&gt;
                        &lt;enabled&gt;true&lt;/enabled&gt;
                    &lt;/releases&gt;
                    &lt;snapshots&gt;
                        &lt;enabled&gt;true&lt;/enabled&gt;
                    &lt;/snapshots&gt;
                &lt;/pluginRepository&gt;
            &lt;/pluginRepositories&gt;
        &lt;/profile&gt;

    </pre>
 <br>
  This profile is then enabled by adding "-Pjenkins" to your maven build options.
</div></div>
<ul><li><code>upstream</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'SelectionTypeProject'</code><div>
<ul><li><code>project : String</code>
</li>
<li><code>build : String</code>
</li>
<li><code>promoted : String</code>
</li>
</ul></div></li>
<li><code>$class: 'SelectionTypeSpecified'</code><div>
<ul><li><code>path : String</code>
</li>
</ul></div></li>
<li><code>$class: 'SelectionTypeUpstream'</code><div>
<ul><li><code>build : String</code>
</li>
</ul></div></li>
</ul></li>
</ul>


++++
