= Repository Connector
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/repository-connector">Visit the Jenkins Plugins site</a>
++++


=== `artifactDeployer`: Maven Artifact Deployer
++++
<div><div>
 Deploy one or more artifacts to a maven repository.
</div></div>
<ul><li><code>artifacts</code>
<ul><b>Array / List of Nested Object</b>
<li><code>groupId : String</code>
</li>
<li><code>artifactId : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>classifier : String</code> (optional)
</li>
<li><code>deployToLocal : boolean</code> (optional)
</li>
<li><code>deployToRemote : boolean</code> (optional)
</li>
<li><code>extension : String</code> (optional)
</li>
<li><code>failOnError : boolean</code> (optional)
</li>
<li><code>pomFile : String</code> (optional)
</li>
<li><code>targetFileName : String</code> (optional)
</li>
</ul></li>
<li><code>enableRepositoryLogging : boolean</code> (optional)
</li>
<li><code>enableTransferLogging : boolean</code> (optional)
</li>
<li><code>repositoryId : String</code> (optional)
</li>
</ul>


++++
=== `artifactResolver`: Maven Artifact Resolver
++++
<div><div>
 Resolves artifacts against one or more remote maven repositories. 
 <div>
 </div>
</div></div>
<ul><li><code>artifacts</code>
<ul><b>Array / List of Nested Object</b>
<li><code>groupId : String</code>
</li>
<li><code>artifactId : String</code>
</li>
<li><code>version : String</code>
</li>
<li><code>classifier : String</code> (optional)
</li>
<li><code>deployToLocal : boolean</code> (optional)
</li>
<li><code>deployToRemote : boolean</code> (optional)
</li>
<li><code>extension : String</code> (optional)
</li>
<li><code>failOnError : boolean</code> (optional)
</li>
<li><code>pomFile : String</code> (optional)
</li>
<li><code>targetFileName : String</code> (optional)
</li>
</ul></li>
<li><code>enableRepositoryLogging : boolean</code> (optional)
</li>
<li><code>enableTransferLogging : boolean</code> (optional)
</li>
<li><code>repositoryId : String</code> (optional)
</li>
<li><code>targetDirectory : String</code> (optional)
</li>
</ul>


++++
