= Reqtify Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/reqtify">Visit the Jenkins Plugins site</a>
++++


=== `reqtifyFunction`: Reqtify: Call Function
++++
<div><div>
 Call a function You can choose: 
 <ul>
  <li>Function name</li>
  <li>Function Arguments</li>
 </ul>
</div></div>
<ul><li><code>functionName : String</code> (optional)
</li>
<li><code>argumentList : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>argument : String</code> (optional)
</li>
</ul>


++++
=== `reqtifyReport`: Reqtify: Generate Report
++++
<div><div>
 Creation of a report. The plugin will find a .rqtf file in the workspace and make a report. You can choose: 
 <ul>
  <li>The name of report</li>
  <li>The model of report</li>
  <li>The template of report</li>
 </ul>
</div></div>
<ul><li><code>reportArgumentList : Array / List of String</code>
<ul></ul></li>
<li><code>nameReport : String</code> (optional)
</li>
<li><code>modelReport : String</code> (optional)
</li>
<li><code>templateReport : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'CallFunction'])`: Reqtify: Call Function
++++
<div><div>
 Call a function You can choose: 
 <ul>
  <li>Function name</li>
  <li>Function Arguments</li>
 </ul>
</div></div>
<ul><li><code>functionName : String</code> (optional)
</li>
<li><code>argumentList : Array / List of String</code> (optional)
<ul></ul></li>
<li><code>argument : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'ReqtifyGenerateReport'])`: Reqtify: Generate Report
++++
<div><div>
 Creation of a report. The plugin will find a .rqtf file in the workspace and make a report. You can choose: 
 <ul>
  <li>The name of report</li>
  <li>The model of report</li>
  <li>The template of report</li>
 </ul>
</div></div>
<ul><li><code>reportArgumentList : Array / List of String</code>
<ul></ul></li>
<li><code>nameReport : String</code> (optional)
</li>
<li><code>modelReport : String</code> (optional)
</li>
<li><code>templateReport : String</code> (optional)
</li>
</ul>


++++
