= Robot Framework plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/robot">Visit the Jenkins Plugins site</a>
++++


=== `robot`: Configure robot framework report collection
++++
<div><div>
 <p>Publishes <a href="http://code.google.com/p/robotframework/" rel="nofollow">Robot Framework</a> test reports into Hudson user interface.</p>
 <p>Note that you must configure your build to produce these reports before you can publish them with this plugin.</p>
 <p>All text fields support the use of environment variables available during build (e.g. ${BUILD_NUMBER}).</p>
</div></div>
<ul><li><code>outputPath : String</code>
</li>
<li><code>archiveDirName : String</code> (optional)
</li>
<li><code>disableArchiveOutput : boolean</code> (optional)
<div><div>
 <p>output xml files are not needed by Jenkins once the publishing step of the build is finished.</p>
 <p>They are archived for traceability or reuse in some other context.</p>
 <p>You might want to disable archiving of those output xml files to save disk space on the Jenkins server.</p>
</div></div>

</li>
<li><code>enableCache : boolean</code> (optional)
<div><div>
 <p>Enable cache for test results (produces memory pressure)</p>
</div></div>

</li>
<li><code>logFileName : String</code> (optional)
<div><div>
 <p>File name relative to output path. Supports <a href="http://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant GLOB</a> style wildcards (e.g. **/log*.html).</p>
 <p>Splitted files will be copied automatically. If file name is specified log.html then all log-xxx.html will be saved.</p>
</div></div>

</li>
<li><code>onlyCritical : boolean</code> (optional)
</li>
<li><code>otherFiles : String</code> (optional)
<div><div>
 <p>Comma separated list of file names relative to output path. Supports <a href="http://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant GLOB</a> style wildcards (e.g. **/screenshot*.jpg).</p>
 <p>You can save any artifacts related to tests (e.g. Selenium screenshots) in the robot directory by configuring the filenames here. Items that are linked to the robot log files - like screenshots - have to be explicitly saved here in order to view them in the stored logs.</p>
</div></div>

</li>
<li><code>outputFileName : String</code> (optional)
<div><div>
 <p>File name relative to output path. Supports <a href="http://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant GLOB</a> style wildcards (e.g. **/output*.xml).</p>
 <p>Splitted files will be copied automatically. If file name is specified output.xml then all output-xxx.xml will be saved.</p>
</div></div>

</li>
<li><code>overwriteXAxisLabel : String</code> (optional)
<div><div>
 <p>Pattern to format x axis label in trend graphs. You can use $build for build number and $display_name for build display name beside all letters from java class DateTimeFormatter (e.g. MM-dd HH:mm). Already created and cached images are not affected.</p>
</div></div>

</li>
<li><code>passThreshold : double</code> (optional)
</li>
<li><code>reportFileName : String</code> (optional)
<div><div>
 <p>File name relative to output path. Supports <a href="http://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant GLOB</a> style wildcards (e.g. **/report*.html).</p>
 <p>Splitted files will be copied automatically. If file name is specified report.html then all report-xxx.html will be saved.</p>
</div></div>

</li>
<li><code>unstableThreshold : double</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'RobotPublisher'])`: Publish Robot Framework test results
++++
<div><div>
 <p>Publishes <a href="http://code.google.com/p/robotframework/" rel="nofollow">Robot Framework</a> test reports into Hudson user interface.</p>
 <p>Note that you must configure your build to produce these reports before you can publish them with this plugin.</p>
 <p>All text fields support the use of environment variables available during build (e.g. ${BUILD_NUMBER}).</p>
</div></div>
<ul><li><code>archiveDirName : String</code>
</li>
<li><code>outputPath : String</code>
</li>
<li><code>outputFileName : String</code>
<div><div>
 <p>File name relative to output path. Supports <a href="http://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant GLOB</a> style wildcards (e.g. **/output*.xml).</p>
 <p>Splitted files will be copied automatically. If file name is specified output.xml then all output-xxx.xml will be saved.</p>
</div></div>

</li>
<li><code>disableArchiveOutput : boolean</code>
<div><div>
 <p>output xml files are not needed by Jenkins once the publishing step of the build is finished.</p>
 <p>They are archived for traceability or reuse in some other context.</p>
 <p>You might want to disable archiving of those output xml files to save disk space on the Jenkins server.</p>
</div></div>

</li>
<li><code>reportFileName : String</code>
<div><div>
 <p>File name relative to output path. Supports <a href="http://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant GLOB</a> style wildcards (e.g. **/report*.html).</p>
 <p>Splitted files will be copied automatically. If file name is specified report.html then all report-xxx.html will be saved.</p>
</div></div>

</li>
<li><code>logFileName : String</code>
<div><div>
 <p>File name relative to output path. Supports <a href="http://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant GLOB</a> style wildcards (e.g. **/log*.html).</p>
 <p>Splitted files will be copied automatically. If file name is specified log.html then all log-xxx.html will be saved.</p>
</div></div>

</li>
<li><code>passThreshold : double</code>
</li>
<li><code>unstableThreshold : double</code>
</li>
<li><code>onlyCritical : boolean</code>
</li>
<li><code>otherFiles : String</code>
<div><div>
 <p>Comma separated list of file names relative to output path. Supports <a href="http://ant.apache.org/manual/dirtasks.html#patterns" rel="nofollow">Ant GLOB</a> style wildcards (e.g. **/screenshot*.jpg).</p>
 <p>You can save any artifacts related to tests (e.g. Selenium screenshots) in the robot directory by configuring the filenames here. Items that are linked to the robot log files - like screenshots - have to be explicitly saved here in order to view them in the stored logs.</p>
</div></div>

</li>
<li><code>enableCache : boolean</code>
<div><div>
 <p>Enable cache for test results (produces memory pressure)</p>
</div></div>

</li>
<li><code>overwriteXAxisLabel : String</code>
<div><div>
 <p>Pattern to format x axis label in trend graphs. You can use $build for build number and $display_name for build display name beside all letters from java class DateTimeFormatter (e.g. MM-dd HH:mm). Already created and cached images are not affected.</p>
</div></div>

</li>
</ul>


++++
