= Role-based Authorization Strategy
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/role-strategy">Visit the Jenkins Plugins site</a>
++++


=== `currentUserGlobalRoles`: Current Users Global Roles
++++
<div><div>
 Returns a list of all global roles of the user that started the build. This includes roles assigned via groups. When the run is triggered by an SCM event or by the timer, the build usually runs as the <em>System</em> user. This user is considered as having all roles.
 <br>
  You can use the <a href="https://plugins.jenkins.io/authorize-project/" rel="nofollow">Authorize Project</a> plugin to run the builds as a different user. When running as <em>anonymous</em>, an empty list is returned.
</div></div>
<ul></ul>


++++
=== `currentUserItemRoles`: Current Users Item Roles
++++
<div><div>
 Returns a list of all item roles of the user that started the build. This includes roles assigned via groups. When the run is triggered by an SCM event or by the timer, the build usually runs as the <em>System</em> user. This user is considered as having all roles.
 <br>
  You can use the <a href="https://plugins.jenkins.io/authorize-project/" rel="nofollow">Authorize Project</a> plugin to run the builds as a different user. When running as <em>anonymous</em>, an empty list is returned.
</div></div>
<ul><li><code>showAllRoles : boolean</code> (optional)
<div><div>
 If checked, all item roles of the user are returned. Otherwise only roles matching the pipeline job are returned.
</div></div>

</li>
</ul>


++++
