= S3 publisher plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/s3">Visit the Jenkins Plugins site</a>
++++


=== `s3Upload`: Publish artifacts to S3 Bucket
++++
<ul><li><code>profileName : String</code>
</li>
<li><code>entries</code>
<ul><b>Array / List of Nested Object</b>
<li><code>bucket : String</code>
<div><div>
 Destination bucket. It will be created if doesn't exist. Environment variable can be used, for example my-artifact-bucket/${JOB_NAME}-${BUILD_NUMBER}.
</div></div>

</li>
<li><code>sourceFile : String</code>
<div><div>
 Files to be uploaded. This field follows <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">the Ant glob syntax</a>, such as **/build/test-reports/*.xml. The base directory is <a rel="nofollow">the workspace</a>.
</div></div>

</li>
<li><code>excludedFile : String</code>
</li>
<li><code>storageClass : String</code>
</li>
<li><code>selectedRegion : String</code>
<div><div>
 Region location of the Bucket. By default plugin uses value provided by system property "hudson.plugins.s3.DEFAULT_AMAZON_S3_REGION"
</div></div>

</li>
<li><code>noUploadOnFailure : boolean</code>
<div><div>
 If Enabled, the artifacts won't be published if the build failed.
</div></div>

</li>
<li><code>uploadFromSlave : boolean</code>
<div><div>
 Upload directly from the slave, instead of proxying the upload to the master.
</div></div>

</li>
<li><code>managedArtifacts : boolean</code>
<div><div>
 When enabled, this lets Jenkins fully manage the artifacts, exactly like it does when the artifacts are published to the master. 
 <br>
  In this case, the artifacts are stored in the "jobs/[job]/[build-number]/" path in the selected bucket and prefix path. This means the following features are enabled: 
 <ul>
  <li>artifacts are finger printed and linked to the build</li>
  <li>artifacts can be downloaded directly from the build page in the S3 Artifact section</li>
  <li>artifacts are automatically deleted when the build is deleted</li>
  <li>the <em>S3 Copy Artifact</em> build step can be used to download artifacts from S3 automatically, helping build complex pipelines</li>
 </ul>
</div></div>

</li>
<li><code>useServerSideEncryption : boolean</code>
<div><div>
 Use S3 AES-256 server side encryption support.
</div></div>

</li>
<li><code>flatten : boolean</code>
<div><div>
 When enabled, Jenkins will ignore the directory structure of the artifacts in the source project and copy all matching artifacts directly into the specified bucket. By default the artifacts are copied in the same directory structure as the source project.
</div></div>

</li>
<li><code>gzipFiles : boolean</code>
<div><div>
 When enabled, files will be compressed with GZIP and "Content-Encoding" header will be set to "gzip".
</div></div>

</li>
<li><code>keepForever : boolean</code>
<div><div>
 By default, artifacts will be cleaned up as part of job history rotation policy. If you want to keep artifacts after removing job history, you need to enable this option.
</div></div>

</li>
<li><code>showDirectlyInBrowser : boolean</code>
<div><div>
 If option is enabled, content of artifact would be displayed directly in browser. Otherwise, it would be attached and user could download it.
</div></div>

</li>
<li><code>userMetadata</code>
<ul><b>Array / List of Nested Object</b>
<li><code>key : String</code>
<div><div>
 Metadata key for the files from this build. It will be prefixed by "x-amz-meta-" when uploaded to S3. Can contain macros (e.g. environment variables).
</div></div>

</li>
<li><code>value : String</code>
<div><div>
 Metadata value for the files from this build. Can contain macros (e.g. environment variables).
</div></div>

</li>
</ul></li>
</ul></li>
<li><code>userMetadata</code>
<ul><b>Array / List of Nested Object</b>
<li><code>key : String</code>
<div><div>
 Metadata key for the files from this build. It will be prefixed by "x-amz-meta-" when uploaded to S3. Can contain macros (e.g. environment variables).
</div></div>

</li>
<li><code>value : String</code>
<div><div>
 Metadata value for the files from this build. Can contain macros (e.g. environment variables).
</div></div>

</li>
</ul></li>
<li><code>dontWaitForConcurrentBuildCompletion : boolean</code>
<div><div>
 When disabled, only publish to S3 after completion of concurrent builds to prevent overriding published artifact. You can enable this to publish to S3 at the end of each concurrent build. Published artifact should then have a different name for each build to prevent unnecessary uploads.
</div></div>

</li>
<li><code>consoleLogLevel : String</code>
<div><div>
 Allows filtering log messages by level of severity: INFO, WARNING and SEVERE.
</div></div>

</li>
<li><code>pluginFailureResultConstraint : String</code>
</li>
<li><code>dontSetBuildResultOnFailure : boolean</code>
<div><div>
 When checked or selected, the build status will not get updated when a failure occurs. This is primarily useful when using this step in a pipeline. A failure would manifest itself as an exception thrown as opposed to a change in build status. Therefore, the pipeline author can choose to decide to handle the exception with a retry(), etc.
</div></div>

</li>
</ul>


++++
=== `s3CopyArtifact`: S3 Copy Artifact
++++
<ul><li><code>projectName : String</code>
</li>
<li><code>buildSelector</code>
<ul><b>Nested Choice of Objects</b>
<li><code>downstream</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggered from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downstream build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>lastWithArtifacts</code><div>
<ul></ul></div></li>
<li><code>lastCompleted</code><div>
<ul></ul></div></li>
<li><code>$class: 'MultiJobBuildSelector'</code><div>
<ul></ul></div></li>
<li><code>buildParameter</code><div>
<ul><li><code>parameterName : String</code>
<div><div>
 Name of the "build selector" parameter. A parameter with this name should be added in the build parameters section above. There is a special parameter type for choosing the build selector. 
 <p>You can pass not only the parameter name, but also the parameter value itself. This is useful especially used with workflow-plugin.</p>
</div></div>

</li>
</ul></div></li>
<li><code>permalink</code><div>
<ul><li><code>id : String</code>
</li>
</ul></div></li>
<li><code>$class: 'PromotedBuildSelector'</code><div>
<ul><li><code>level : int</code>
</li>
</ul></div></li>
<li><code>latestSavedBuild</code><div>
<ul></ul></div></li>
<li><code>specific</code><div>
<ul><li><code>buildNumber : String</code>
<div><div>
 While this selector is for build numbers (e.g. "22" for build #22), you can also resolve build parameters or environment variables (e.g. "${PARAM}"). The display name of a build and permalinks (e.g. "lastSuccessfulBuild", "lastBuild"...) can be used as well.
</div></div>

</li>
</ul></div></li>
<li><code>lastSuccessful</code><div>
<ul><li><code>stable : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>upstream</code><div>
<ul><li><code>allowUpstreamDependencies : boolean</code> (optional)
</li>
<li><code>fallbackToLastSuccessful : boolean</code> (optional)
</li>
<li><code>upstreamFilterStrategy</code> (optional)
<div><div>
 Jenkins launches only one build when multiple upstreams triggered the same project at the same time. This field specifies from which upstream build to copy artifacts in those cases. "Use the oldest" copies artifacts from the upstream build with the smallest build number (that is, oldest). "Use the newest" copies artifacts from the upstream build with the largest build number (that is, newest). The default value is "Use global setting", which behaves as configured in "Manage Jenkins" &gt; "Configure System".
</div></div>

<ul><li><b>Values:</b> <code>UseGlobalSetting</code>, <code>UseOldest</code>, <code>UseNewest</code></li></ul></li>
</ul></div></li>
<li><code>workspace</code><div>
<ul></ul></div></li>
</ul></li>
<li><code>filter : String</code>
</li>
<li><code>excludeFilter : String</code>
</li>
<li><code>target : String</code>
</li>
<li><code>flatten : boolean</code>
</li>
<li><code>optional : boolean</code>
</li>
</ul>


++++
