= SaltStack plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/saltstack">Visit the Jenkins Plugins site</a>
++++


=== `salt`: Send a message to Salt API
++++
<ul><li><code>servername : String</code>
<div><div>
 Salt servername. In the form: https://host.domain:8000
 <br>
  The Test Connection process is run from the Jenkins master. If the build is localized to an agent, and the servername is specific to that agent, then Test Connection will likely fail, while the actual build may succeed.
</div></div>

</li>
<li><code>authtype : String</code>
</li>
<li><code>clientInterface</code>
<ul><b>Nested Choice of Objects</b>
<li><code>hook</code><div>
<ul><li><code>post : String</code>
<div><div>
 Publish JSON object as 'post' data, see <a href="https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#salt.netapi.rest_cherrypy.app.Webhook.POST" rel="nofollow">upstream documentation</a>. . Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>tag : String</code>
<div><div>
 Specify salt event tag for message. The event tag is prefixed with salt/netapi/hook, see <a href="https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#salt.netapi.rest_cherrypy.app.Webhook" rel="nofollow">upstream documentation</a>. Paramaterized variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
</ul></div></li>
<li><code>batch</code><div>
<ul><li><code>function : String</code>
<div><div>
 Specify salt function such as test.ping or cmd.run. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>arguments : String</code>
<div><div>
 Specify salt function arguments space separated. Paramaterized Build variables should be specified in the format {{VARNAME}}. Python lists should be quoted: pkgs="[package1, package2]".
 <br>
  Pillar values should be passed in as an argument, with the pillar string surrounded in double or single quotes, and the values single or double quoted: "pillar={artifact: 'somevalue3', repo: 'othervalue:4'}"
</div></div>

</li>
<li><code>batchSize : String</code>
<div><div>
 Specify salt batch size. Example: 10 or 10%
</div></div>

</li>
<li><code>batchWait : String</code>
<div><div>
 Optionally specify time to wait between batches of minions.
</div></div>

</li>
<li><code>target : String</code>
<div><div>
 Specify salt target as defined in the <a href="http://docs.saltstack.com/en/latest/topics/targeting/" rel="nofollow">salt documentation</a>. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>targettype : String</code>
</li>
</ul></div></li>
<li><code>local</code><div>
<ul><li><code>function : String</code>
<div><div>
 Specify salt function such as test.ping or cmd.run. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>arguments : String</code>
<div><div>
 Specify salt function arguments space separated. Paramaterized Build variables should be specified in the format {{VARNAME}}. Python lists should be quoted: pkgs="[package1, package2]".
 <br>
  Pillar values should be passed in as an argument, with the pillar string surrounded in double or single quotes, and the values single or double quoted: "pillar={artifact: 'somevalue3', repo: 'othervalue:4'}"
</div></div>

</li>
<li><code>target : String</code>
<div><div>
 Specify salt target as defined in the <a href="http://docs.saltstack.com/en/latest/topics/targeting/" rel="nofollow">salt documentation</a>. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>targettype : String</code>
</li>
<li><code>blockbuild : boolean</code> (optional)
</li>
<li><code>jobPollTime : int</code> (optional)
</li>
<li><code>minionTimeout : int</code> (optional)
</li>
</ul></div></li>
<li><code>subset</code><div>
<ul><li><code>function : String</code>
<div><div>
 Specify salt function such as test.ping or cmd.run. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>arguments : String</code>
<div><div>
 Specify salt function arguments space separated. Paramaterized Build variables should be specified in the format {{VARNAME}}. Python lists should be quoted: pkgs="[package1, package2]".
 <br>
  Pillar values should be passed in as an argument, with the pillar string surrounded in double or single quotes, and the values single or double quoted: "pillar={artifact: 'somevalue3', repo: 'othervalue:4'}"
</div></div>

</li>
<li><code>subset : String</code>
<div><div>
 Execute the routine on a random subset of the targeted minions. Paramaterized variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>target : String</code>
<div><div>
 Specify salt target as defined in the <a href="http://docs.saltstack.com/en/latest/topics/targeting/" rel="nofollow">salt documentation</a>. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>targettype : String</code>
</li>
</ul></div></li>
<li><code>runner</code><div>
<ul><li><code>function : String</code>
<div><div>
 Specify salt function such as test.ping or cmd.run. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>arguments : String</code>
<div><div>
 Specify salt function arguments space separated. Paramaterized Build variables should be specified in the format {{VARNAME}}. Python lists should be quoted: pkgs="[package1, package2]".
 <br>
</div></div>

</li>
<li><code>mods : String</code>
<div><div>
 Specify runner mods value. Used in state.orchestrate function to specify the name of the orchestrate module
 <br>
  Paramaterized Build variables should be specified in the format {{VARNAME}}
</div></div>

</li>
<li><code>pillarvalue : String</code>
<div><div>
 Specify runner pillar value. Used in state.orchestrate functions. Ex: {"key": "value"}
 <br>
  Paramaterized Build variables should be specified in the format {{VARNAME}}
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>credentialsId : String</code>
</li>
<li><code>saveEnvVar : boolean</code> (optional)
</li>
<li><code>saveFile : boolean</code> (optional)
</li>
<li><code>skipValidation : boolean</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'SaltAPIBuilder'])`: Send a message to Salt API
++++
<ul><li><code>authtype : String</code>
</li>
<li><code>clientInterface</code>
<ul><b>Nested Choice of Objects</b>
<li><code>hook</code><div>
<ul><li><code>post : String</code>
<div><div>
 Publish JSON object as 'post' data, see <a href="https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#salt.netapi.rest_cherrypy.app.Webhook.POST" rel="nofollow">upstream documentation</a>. . Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>tag : String</code>
<div><div>
 Specify salt event tag for message. The event tag is prefixed with salt/netapi/hook, see <a href="https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#salt.netapi.rest_cherrypy.app.Webhook" rel="nofollow">upstream documentation</a>. Paramaterized variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
</ul></div></li>
<li><code>batch</code><div>
<ul><li><code>function : String</code>
<div><div>
 Specify salt function such as test.ping or cmd.run. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>arguments : String</code>
<div><div>
 Specify salt function arguments space separated. Paramaterized Build variables should be specified in the format {{VARNAME}}. Python lists should be quoted: pkgs="[package1, package2]".
 <br>
  Pillar values should be passed in as an argument, with the pillar string surrounded in double or single quotes, and the values single or double quoted: "pillar={artifact: 'somevalue3', repo: 'othervalue:4'}"
</div></div>

</li>
<li><code>batchSize : String</code>
<div><div>
 Specify salt batch size. Example: 10 or 10%
</div></div>

</li>
<li><code>batchWait : String</code>
<div><div>
 Optionally specify time to wait between batches of minions.
</div></div>

</li>
<li><code>target : String</code>
<div><div>
 Specify salt target as defined in the <a href="http://docs.saltstack.com/en/latest/topics/targeting/" rel="nofollow">salt documentation</a>. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>targettype : String</code>
</li>
</ul></div></li>
<li><code>local</code><div>
<ul><li><code>function : String</code>
<div><div>
 Specify salt function such as test.ping or cmd.run. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>arguments : String</code>
<div><div>
 Specify salt function arguments space separated. Paramaterized Build variables should be specified in the format {{VARNAME}}. Python lists should be quoted: pkgs="[package1, package2]".
 <br>
  Pillar values should be passed in as an argument, with the pillar string surrounded in double or single quotes, and the values single or double quoted: "pillar={artifact: 'somevalue3', repo: 'othervalue:4'}"
</div></div>

</li>
<li><code>target : String</code>
<div><div>
 Specify salt target as defined in the <a href="http://docs.saltstack.com/en/latest/topics/targeting/" rel="nofollow">salt documentation</a>. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>targettype : String</code>
</li>
<li><code>blockbuild : boolean</code> (optional)
</li>
<li><code>jobPollTime : int</code> (optional)
</li>
<li><code>minionTimeout : int</code> (optional)
</li>
</ul></div></li>
<li><code>subset</code><div>
<ul><li><code>function : String</code>
<div><div>
 Specify salt function such as test.ping or cmd.run. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>arguments : String</code>
<div><div>
 Specify salt function arguments space separated. Paramaterized Build variables should be specified in the format {{VARNAME}}. Python lists should be quoted: pkgs="[package1, package2]".
 <br>
  Pillar values should be passed in as an argument, with the pillar string surrounded in double or single quotes, and the values single or double quoted: "pillar={artifact: 'somevalue3', repo: 'othervalue:4'}"
</div></div>

</li>
<li><code>subset : String</code>
<div><div>
 Execute the routine on a random subset of the targeted minions. Paramaterized variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>target : String</code>
<div><div>
 Specify salt target as defined in the <a href="http://docs.saltstack.com/en/latest/topics/targeting/" rel="nofollow">salt documentation</a>. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>targettype : String</code>
</li>
</ul></div></li>
<li><code>runner</code><div>
<ul><li><code>function : String</code>
<div><div>
 Specify salt function such as test.ping or cmd.run. Paramaterized Build variables should be specified in the format {{VARNAME}}.
</div></div>

</li>
<li><code>arguments : String</code>
<div><div>
 Specify salt function arguments space separated. Paramaterized Build variables should be specified in the format {{VARNAME}}. Python lists should be quoted: pkgs="[package1, package2]".
 <br>
</div></div>

</li>
<li><code>mods : String</code>
<div><div>
 Specify runner mods value. Used in state.orchestrate function to specify the name of the orchestrate module
 <br>
  Paramaterized Build variables should be specified in the format {{VARNAME}}
</div></div>

</li>
<li><code>pillarvalue : String</code>
<div><div>
 Specify runner pillar value. Used in state.orchestrate functions. Ex: {"key": "value"}
 <br>
  Paramaterized Build variables should be specified in the format {{VARNAME}}
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>credentialsId : String</code>
</li>
<li><code>servername : String</code> (optional)
<div><div>
 Salt servername. In the form: https://host.domain:8000
 <br>
  The Test Connection process is run from the Jenkins master. If the build is localized to an agent, and the servername is specific to that agent, then Test Connection will likely fail, while the actual build may succeed.
</div></div>

</li>
<li><code>saveEnvVar : boolean</code> (optional)
</li>
<li><code>saveFile : boolean</code> (optional)
</li>
<li><code>skipValidation : boolean</code> (optional)
</li>
</ul>


++++
