= Sauce OnDemand plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/sauce-ondemand">Visit the Jenkins Plugins site</a>
++++


=== `sauce`: Sauce
++++
<ul><li><code>credentialsId : String</code>
</li>
</ul>


++++
=== `sauceconnect`: Sauce Connect
++++
<ul><li><code>options : String</code> (optional)
</li>
<li><code>sauceConnectPath : String</code> (optional)
</li>
<li><code>useGeneratedTunnelIdentifier : boolean</code> (optional)
</li>
<li><code>useLatestSauceConnect : boolean</code> (optional)
</li>
<li><code>verboseLogging : boolean</code> (optional)
</li>
</ul>


++++
=== `saucePublisher`: Run Sauce Labs Test Publisher
++++
<div><div>
 This step will trigger jenkins to parse the output of your build for <code>SauceOnDemandSessionID</code> lines and will attempt to update the job on sauce labs with the proper status. See <a href="https://wiki.saucelabs.com/display/DOCS/Setting+Up+Reporting+between+Sauce+Labs+and+Jenkins" rel="nofollow">the Sauce Labs wiki</a> for more information
</div></div>
<ul><li><code>testDataPublishers</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>attachments</code><div>
<ul></ul></div></li>
<li><code>$class: 'AutomateTestDataPublisher'</code><div>
<ul></ul></div></li>
<li><code>$class: 'ClaimTestDataPublisher'</code><div>
<ul></ul></div></li>
<li><code>$class: 'JUnitFlakyTestDataPublisher'</code><div>
<ul></ul></div></li>
<li><code>jiraTestResultReporter</code><div>
<ul><li><code>configs</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>jiraSelectableArrayField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>values</code>
<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>jiraSelectableField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>jiraStringArrayField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>values</code>
<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>jiraStringField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>value : String</code>
<div><div>
 <p>Insert a string value.</p>
 <p>You can include Jenkins Environment variables (see <a href="https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project" rel="nofollow">link</a>), or the following variables defined by this plugin:</p>
 <p></p>Variable usage: <b>${VAR_NAME}</b>
 <p></p>
 <p>CRFL - new line</p>
 <p>DEFAULT_SUMMARY - configured in the global configuration page</p>
 <p>DEFAULT_DESCRIPTION - configured in the global configuration page</p>
 <p>TEST_RESULT</p>
 <p>TEST_NAME</p>
 <p>TEST_FULL_NAME</p>
 <p>TEST_STACK_TRACE</p>
 <p>TEST_ERROR_DETAILS</p>
 <p>TEST_DURATION</p>
 <p>TEST_PACKAGE_NAME</p>
 <p>TEST_PACKAGE_CLASS_METHOD_NAME</p>
 <p>TEST_STDERR</p>
 <p>TEST_STDOUT</p>
 <p>TEST_OVERVIEW</p>
 <p>TEST_AGE</p>
 <p>TEST_PASS_COUNT</p>
 <p>TEST_SKIPPED_COUNT</p>
 <p>TEST_FAIL_SINCE</p>
 <p>TEST_IS_REGRESSION - expands to true/false</p>
 <p>BUILD_RESULT</p>
 <h3>WARNING: Your input will not be validated against the server's metadata. Check Jira to make sure you insert a valid value for this field and use the Validate Fields button bellow, otherwise the plugin will fail to create your issue.</h3>
</div></div>

</li>
</ul></div></li>
<li><code>jiraUserField</code><div>
<ul><li><code>fieldKey : String</code>
</li>
<li><code>value : String</code>
<div><div>
 <p>Insert the <b>username</b>.</p>
 <p>For example if you have a user with: <br><br>
  Display Name: <b>John Doe</b>, Username: <b>johndoe</b>, Email: <b>johndoe@email.com</b>,<br><br>
   you need to write <b>johndoe</b> in this field. Any other value (like display name, or email) will not work.</p>
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>projectKey : String</code>
</li>
<li><code>issueType : String</code>
</li>
<li><code>autoRaiseIssue : boolean</code>
<div><div>
 Create issues automatically for failing tests that don't yet have one linked.
</div></div>

</li>
<li><code>autoResolveIssue : boolean</code>
<div><div>
 Automatically apply transition to resolve issues linked to tests, if the test passes.
 <br><b>Experimental feature:</b> For now it only looks for the first transition that contains in its name "resolve". If it is found, it will be applied, if not, the status of the issue will not change. In future releases this will be parametrized.
</div></div>

</li>
<li><code>autoUnlinkIssue : boolean</code>
</li>
<li><code>overrideResolvedIssues : boolean</code>
<div><div>
 Create issues automatically for failing tests that are linked to resolved issues in JiraIssueKeyToTestMap.json.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'JunitResultPublisher'</code><div>
<div><div>
 If checked, each JUnit test result XML file will be examined to see if it represents a SOASTA CloudTest composition. For applicable tests, a hyperlink to the SOASTA CloudTest dashboard will be inserted into the test report.
</div></div>
<ul><li><code>urlOverride : String</code>
<div><div>
 Specify the CloudTest URL to use when creating hyperlinks to CloudTest dashboards. Normally, this can be left blank, and the URL will be extracted from the test result file.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PerfSigTestDataPublisher'</code><div>
<ul><li><code>dynatraceProfile : String</code>
</li>
</ul></div></li>
<li><code>$class: 'SahaginTestDataPublishser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'SauceOnDemandReportPublisher'</code><div>
<div><div>
 Show embedded Sauce OnDemand reports, including video and logs. Your test should use <a href="http://selenium-client-factory.infradna.com/" rel="nofollow">Selenium client factory</a> (at least <a href="http://maven.jenkins-ci.org/content/repositories/releases/com/saucelabs/selenium/selenium-client-factory/1.3/" rel="nofollow">version 1.3</a> to match test cases to individual Sauce OnDemand jobs).
</div></div>
<ul><li><code>jobVisibility : String</code> (optional)
<div>Set your test results visibility permissions. The <a href="https://wiki.saucelabs.com/display/DOCS/Sharing+the+Results+of+Sauce+Labs+Tests" rel="nofollow">Sauce Documentation</a> has all the various levels described in detail.</div>

</li>
</ul></div></li>
<li><code>$class: 'StabilityTestDataPublisher'</code><div>
<ul></ul></div></li>
<li><code>$class: 'TestCafePublisher'</code><div>
<ul></ul></div></li>
<li><code>$class: 'TestReporter'</code><div>
<ul></ul></div></li>
<li><code>$class: 'YoutrackTestDataPublisher'</code><div>
<ul></ul></div></li>
</ul></li>
</ul>


++++
