= ServiceNow CI/CD Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/servicenow-cicd">Visit the Jenkins Plugins site</a>
++++


=== `snActivatePlugin`: SN: Activate plugin
++++
<ul><li><code>credentialsId : String</code> (optional)
<div><div>
 User name and password defined in global credentials (credentials ID is required here). 
 <br>
  This field cannot be empty. It doesn't use global settings from ServiceNow Parameters.
</div></div>

</li>
<li><code>apiVersion : String</code> (optional)
<div><div>
 Optional. Version of the endpoint to access. For example, v1 or v2. Only specify this value to use an endpoint version other than the latest.
</div></div>

</li>
<li><code>pluginId : String</code> (optional)
<div><div>
 Unique identifier of the plugin. You can locate this identifier on the Plugins page within the card of the desired plugin; identified with the name "ID".
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 ServiceNow instance url. This field cannot be empty. It doesn't use global settings from ServiceNow Parameters.
</div></div>

</li>
</ul>


++++
=== `snApplyChanges`: SN: Apply changes
++++
<ul><li><code>credentialsId : String</code> (optional)
<div><div>
 User name and password defined in global credentials (credentials ID is required here) used for the instance (usually where the application will be published).
</div></div>

</li>
<li><code>apiVersion : String</code> (optional)
<div><div>
 Optional. Version of the endpoint to access. For example, v1 or v2. Only specify this value to use an endpoint version other than the latest.
</div></div>

</li>
<li><code>appScope : String</code> (optional)
<div><div>
 Required if <code>application system ID</code> is not specified. The scope name of the application for which to apply the changes, such as x_aah_custom_app. You can locate this value in the scope field in the Custom Application [sys_app] table.
</div></div>

</li>
<li><code>appSysId : String</code> (optional)
<div><div>
 Required if <code>application scope</code> is not specified. The system id of the application for which to apply the changes. You can locate this value in the Sys ID field in the Custom Application [sys_app] table.
</div></div>

</li>
<li><code>branchName : String</code> (optional)
<div><div>
 Name of the branch in the source control system from which to acquire the application.
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 ServiceNow instance url (usually where the application will be published to).
</div></div>

</li>
</ul>


++++
=== `snBatchInstall`: SN: Batch install
++++
<ul><li><code>credentialsId : String</code> (optional)
<div><div>
 User name and password defined in global credentials (credentials ID is required here) used for the instance where the application will be installed.
</div></div>

</li>
<li><code>apiVersion : String</code> (optional)
<div><div>
 Optional. Version of the endpoint to access. For example, v1 or v2. Only specify this value to use an endpoint version other than the latest.
</div></div>

</li>
<li><code>batchName : String</code> (optional)
<div><div>
 Required. User specified descriptive name for this batch request.
</div></div>

</li>
<li><code>file : String</code> (optional)
<div><div>
 Name of the batch file with json manifest. If only a name is given or relative path then the file will be searched in WORKSPACE directory of the build. 
 <p>The field is required if <strong>Use file</strong> is checked. If the field is not changed default value will be used: <code>now_batch_manifest.json</code>.</p>
</div></div>

</li>
<li><code>notes : String</code> (optional)
<div><div>
 User specified additional notes about the batch install plan. 
 <p>Default: <code>null</code></p>
</div></div>

</li>
<li><code>packages : String</code> (optional)
<div><div>
 Required. JSON array, where each object specifies details of a package to install. 
 <pre>        <code>
    [{
        "id": "String",
        "load_demo_data": Boolean,
        "notes": "String",
        "requested_customized_version": "String",
        "requested_version": "String",
        "type": "String"
    }]
        </code>
    </pre>
 <table>
  <tbody>
   <tr>
    <th>id</th>
    <td>Required. Sys_id of the application or identifier of the plugin to install.</td>
   </tr>
   <tr>
    <th>load_demo_data</th>
    <td>Flag that indicates whether demo data is loaded when installing the package. <br>
     Valid values: <br>
     &nbsp;<code>true</code>: Demo data should be loaded. <br>
     &nbsp;<code>false</code>: Demo data should not be loaded. <br>
     Default: <code>false</code></td>
   </tr>
   <tr>
    <th>notes</th>
    <td>User specified notes about the package. <br>
     Default: <code>null</code></td>
   </tr>
   <tr>
    <th>requested_customized_version</th>
    <td>Only applicable when packages.type is set to application. Version of the store application customization package to install, such as 1.0.2 or 2.3.</td>
   </tr>
   <tr>
    <th>requested_customized_version</th>
    <td>Only applicable when packages.type is set to application. Version of the store application customization package to install, such as 1.0.2 or 2.3. 
     <p></p>Default: None. If this is not set, then the system does not look for customizations for the application.</td>
   </tr>
   <tr>
    <th>requested_version</th>
    <td>Required if <code>type</code> is set to application; ignored if set to plugin. Version of the package to install, such as 1.0.2 or 2.3.</td>
   </tr>
   <tr>
    <th>type</th>
    <td>Required. Type of package. <br>
     Valid values: 
     <ul>
      <li><code>application</code></li>
      <li><code>plugin</code></li>
     </ul></td>
   </tr>
  </tbody>
 </table>
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 ServiceNow instance url where the application will be installed.
</div></div>

</li>
<li><code>useFile : boolean</code> (optional)
<div><div>
 Specifies if manifest json file will be used to define the batch. The file can be stored in git repository (in this case SCM should be configured). 
 <p>Default: <code>false</code></p>
</div></div>

</li>
</ul>


++++
=== `snBatchRollback`: SN: Batch rollback
++++
<ul><li><code>credentialsId : String</code> (optional)
<div><div>
 User name and password defined in global credentials (credentials ID is required here). 
 <br>
  If ServiceNow Parameters are used, then credentials for installation instance will be used.
</div></div>

</li>
<li><code>apiVersion : String</code> (optional)
<div><div>
 Optional. Version of the endpoint to access. For example, v1 or v2. Only specify this value to use an endpoint version other than the latest.
</div></div>

</li>
<li><code>rollbackId : String</code> (optional)
<div><div>
 Unique identifier (<code>sys_id</code>) of the rollback installed before.
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 ServiceNow instance url where the batch of packages was installed. 
 <p>If ServiceNow Parameters are used, then the URL of installation instance will be used.</p>
</div></div>

</li>
</ul>


++++
=== `snInstallApp`: SN: Install application
++++
<ul><li><code>credentialsId : String</code> (optional)
<div><div>
 User name and password defined in global credentials (credentials ID is required here) used for the instance where the application will be installed.
</div></div>

</li>
<li><code>apiVersion : String</code> (optional)
<div><div>
 Optional. Version of the endpoint to access. For example, v1 or v2. Only specify this value to use an endpoint version other than the latest.
</div></div>

</li>
<li><code>appScope : String</code> (optional)
<div><div>
 Required if <code>application system ID</code> is not specified. The scope name of the application for which to apply the changes, such as x_aah_custom_app. You can locate this value in the scope field in the Custom Application [sys_app] table.
</div></div>

</li>
<li><code>appSysId : String</code> (optional)
<div><div>
 Required if <code>application scope</code> is not specified. The system id of the application for which to apply the changes. You can locate this value in the Sys ID field in the Custom Application [sys_app] table.
</div></div>

</li>
<li><code>appVersion : String</code> (optional)
<div><div>
 Version of the application to install. If empty, the published version will be used.
</div></div>

</li>
<li><code>baseAppAutoUpgrade : boolean</code> (optional)
<div><div>
 Only applicable if Application Customization is active and the associated application is a higher version than the currently installed version. Flag that indicates whether the associated base application should be automatically upgraded to a newer version. 
 <p></p>Valid values: 
 <ul>
  <li>true: Automatically upgrade the associated application when a newer version becomes available.</li>
  <li>false: Upgrades need to be explicitly installed.</li>
 </ul>
 <p></p>Data type: Boolean 
 <p></p>Default: false
</div></div>

</li>
<li><code>baseAppVersion : String</code> (optional)
<div><div>
 Only applicable if Application Customization is active. Version of the base application on which to apply the customizations. A base application is any third-party application that comes in the ServiceNow Store. 
 <p></p>Data type: String 
 <p></p>Default: If the version field in the associated Custom Application [sys_app] or Store Application [sys_store_app] table is set, then that value is used. If the version field is not set.
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 ServiceNow instance url where the application will be installed.
</div></div>

</li>
</ul>


++++
=== `snInstanceScan`: SN: Instance scan
++++
<ul><li><code>credentialsId : String</code> (optional)
<div><div>
 User name and password defined in global credentials (credentials ID is required here) used for the instance (usually where the application will be published).
</div></div>

</li>
<li><code>apiVersion : String</code> (optional)
</li>
<li><code>comboSysId : String</code> (optional)
</li>
<li><code>requestBody : String</code> (optional)
</li>
<li><code>scanType : String</code> (optional)
</li>
<li><code>suiteSysId : String</code> (optional)
</li>
<li><code>targetRecordSysId : String</code> (optional)
</li>
<li><code>targetTable : String</code> (optional)
</li>
<li><code>url : String</code> (optional)
<div><div>
 ServiceNow instance url (usually where the application will be published to).
</div></div>

</li>
</ul>


++++
=== `snPublishApp`: SN: Publish application
++++
<ul><li><code>credentialsId : String</code> (optional)
<div><div>
 User name and password defined in global credentials (credentials ID is required here) used for the instance where the application will be published.
</div></div>

</li>
<li><code>apiVersion : String</code> (optional)
<div><div>
 Optional. Version of the endpoint to access. For example, v1 or v2. Only specify this value to use an endpoint version other than the latest.
</div></div>

</li>
<li><code>appScope : String</code> (optional)
<div><div>
 Required if <code>application system ID</code> is not specified. The scope name of the application for which to apply the changes, such as x_aah_custom_app. You can locate this value in the scope field in the Custom Application [sys_app] table.
</div></div>

</li>
<li><code>appSysId : String</code> (optional)
<div><div>
 Required if <code>application scope</code> is not specified. The system id of the application for which to apply the changes. You can locate this value in the Sys ID field in the Custom Application [sys_app] table.
</div></div>

</li>
<li><code>appVersion : String</code> (optional)
<div><div>
 Version under which to store the application. Provide 2 significant numbers separated by '.' eg. 1.0 (the third number will be automatically added with build number, what gives eg. 1.0.106).
 <br>
 If the version number is passed, the publish process uses that version and updates the local application version if different. If the version number is not passed, the publish process uses the current version of the local application.
</div></div>

</li>
<li><code>devNotes : String</code> (optional)
<div><div>
 Developer notes to store with the application.
</div></div>

</li>
<li><code>incrementBy : int</code> (optional)
</li>
<li><code>isAppCustomization : boolean</code> (optional)
</li>
<li><code>obtainVersionAutomatically : boolean</code> (optional)
<div><div>
 Calculate next application version that will be published. Retrieve it in smart way using API or source control (if SCM is configured for the build). API has the highest priority, then SCM will be used.
 <br><strong>The value from ''Application version'' will be ignored.</strong>
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 ServiceNow instance url where the application will be published to.
</div></div>

</li>
</ul>


++++
=== `snRollbackApp`: SN: Roll back application
++++
<ul><li><code>credentialsId : String</code> (optional)
<div><div>
 User name and password defined in global credentials (credentials ID is required here) used for the instance where the application is installed.
</div></div>

</li>
<li><code>apiVersion : String</code> (optional)
<div><div>
 Optional. Version of the endpoint to access. For example, v1 or v2. Only specify this value to use an endpoint version other than the latest.
</div></div>

</li>
<li><code>appScope : String</code> (optional)
<div><div>
 Required if <code>application system ID</code> is not specified. The scope name of the application for which to apply the changes, such as x_aah_custom_app. You can locate this value in the scope field in the Custom Application [sys_app] table.
</div></div>

</li>
<li><code>appSysId : String</code> (optional)
<div><div>
 Required if <code>application scope</code> is not specified. The system id of the application for which to apply the changes. You can locate this value in the Sys ID field in the Custom Application [sys_app] table.
</div></div>

</li>
<li><code>rollbackAppVersion : String</code> (optional)
<div><div>
 Expected rollback version. This version is compared to the version that is included in the last rollback context, if they don't match, the build step fails.
 <br>
 If empty, installed version from previous step will be taken.
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 ServiceNow instance url where the application was installed.
</div></div>

</li>
</ul>


++++
=== `snRollbackPlugin`: SN: Roll back plugin
++++
<ul><li><code>credentialsId : String</code> (optional)
<div><div>
 User name and password defined in global credentials (credentials ID is required here). 
 <br>
  This field cannot be empty. It doesn't use global settings from ServiceNow Parameters.
</div></div>

</li>
<li><code>apiVersion : String</code> (optional)
<div><div>
 Optional. Version of the endpoint to access. For example, v1 or v2. Only specify this value to use an endpoint version other than the latest.
</div></div>

</li>
<li><code>pluginId : String</code> (optional)
<div><div>
 Unique identifier of the plugin. You can locate this identifier on the Plugins page within the card of the desired plugin; identified with the name "ID".
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 ServiceNow instance url. This field cannot be empty. It doesn't use global settings from ServiceNow Parameters.
</div></div>

</li>
</ul>


++++
=== `snRunTestSuite`: SN: Run test suite with results
++++
<ul><li><code>credentialsId : String</code> (optional)
<div><div>
 User name and password defined in global credentials (credentials ID is required here) used for the instance where the application will be installed.
</div></div>

</li>
<li><code>apiVersion : String</code> (optional)
<div><div>
 Optional. Version of the endpoint to access. For example, v1 or v2. Only specify this value to use an endpoint version other than the latest.
</div></div>

</li>
<li><code>browserName : String</code> (optional)
<div><div>
 Name of the browser to use to run the client test. This value must match what is specified in the scheduled client test runner. For additional information on scheduled client test runners, see <a href="https://developer.servicenow.com/app.do#!/training/article/app_store_learnv2_atf_newyork_using_the_automated_test_framework/app_store_learnv2_atf_newyork_scheduled_client_test_runners?v=orlando" rel="nofollow">Scheduled Client Test Runners</a>.
 <p>Valid values:</p>
 <ul>
  <li>Any</li>
  <li>Chrome</li>
  <li>Firefox</li>
  <li>Edge</li>
  <li>IE</li>
  <li>Safari</li>
 </ul>
</div></div>

</li>
<li><code>browserVersion : String</code> (optional)
<div><div>
 Starting value of the version of the browser specified in browser_name to use to run the test. For example, if you enter "9", that would enable all 9.x.x.x versions. This value must match what is specified in the scheduled client test runner.
</div></div>

</li>
<li><code>osName : String</code> (optional)
<div><div>
 Name of the operating system under which to run the test suite. This value must match what is specified in the scheduled client test runner.
</div></div>

</li>
<li><code>osVersion : String</code> (optional)
<div><div>
 Starting value of the version of the operating system under which to run the test suite. For example, if you enter "8", that would enable all 8.x.x.x versions. This value must match what is specified in the scheduled client test. runner.
</div></div>

</li>
<li><code>responseBodyFormat : String</code> (optional)
</li>
<li><code>testSuiteName : String</code> (optional)
<div><div>
 Required if <i>Test suite sys_id</i> is not specified. The name of the test suite to run. This value is located in the Test [sys_atf_test_suite] table.
</div></div>

</li>
<li><code>testSuiteSysId : String</code> (optional)
<div><div>
 Required if <i>Test suite name</i> is not specified. The <code>sys_id</code> of the test suite to run. This value is located in the Test [sys_atf_test_suite] table.
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 ServiceNow instance url where the application will be installed.
</div></div>

</li>
<li><code>withResults : boolean</code> (optional)
<div><div>
 If the checkbox is checked, then results from ServiceNow will be visible in Output Console, together with the link to the visualization on the NOW platform.
</div></div>

</li>
</ul>


++++
