= ServiceNow DevOps Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/servicenow-devops">Visit the Jenkins Plugins site</a>
++++


=== `snDevOpsArtifact`: ServiceNow DevOps - Register Artifact step
++++
<div><div>
 <p><b> Artifact registration</b> <br>
   Configure artifact registration in a scripted pipeline or freestyle job using th DevOps API/artifact/registration endpoint. Multiple artifact versions are supported. <br></p>
</div></div>
<ul><li><code>artifactsPayload : String</code> (optional)
<div><div>
 ArtifactPayload 
 <br>
  "name" --&gt; Artifact name for which different builds (artifact versions) are generated. 
 <br>
  "version" --&gt; Specific version of the artifact. Deployable component of an application generated by a CI build. When provided, semantic version is used.
 <br>
  "semanticVersion" --&gt; Optional attribute of an artifact version that, when provided, is used to determine commits for a change. Semantic version format is (MAJOR.MINOR.PATCH).
 <br>
  "repository" --&gt; Target for artifacts generated in a build, and also a source of artifacts required by a build.
 <br>
 <br>
 <br>
  Example:
 <br>
  {"artifacts":[{"name": "sa-web.jar", "version": "1.9", "repositoryName": "services-1031"}, {"name": "sa-db.jar", "version": "1.3.2", "repositoryName": "services-1032"}], "branchName": "master"}
</div></div>

</li>
<li><code>enabled : boolean</code> (optional)
<div><div>
 Enabled specifies the setting for build notifications property (true/false)
</div></div>

</li>
<li><code>ignoreErrors : boolean</code> (optional)
<div><div>
 ignoreErrors specifies the setting to prevent job failure if there is an error (true/false)
</div></div>

</li>
</ul>


++++
=== `snDevOpsChange`: ServiceNow DevOps - Change Control step
++++
<div><div>
 <p><b>snDevOpsChange</b> <br>
   Enables change control for each root-level stage that is mapped to a DevOps step. <br></p>
</div></div>
<ul><li><code>abortOnChangeCreationFailure : boolean</code> (optional)
<div><div>
 Abort or Resume pipeline if the change is not created till the change creation timeout. 
 <br>
  Checked: Abort (default, when change creation timeout specified). 
 <br>
  Unchecked: Resume
</div></div>

</li>
<li><code>abortOnChangeStepTimeOut : boolean</code> (optional)
<div><div>
 Abort or Resume pipeline if the change step is still in progress on change step timeout. 
 <br>
  Checked: Abort (default, when change creation timeout specified) 
 <br>
  Unchecked: Resume
</div></div>

</li>
<li><code>applicationName : String</code> (optional)
<div><div>
 Specifies the application to where config data will be uploaded.
</div></div>

</li>
<li><code>changeCreationTimeOut : <code>Object</code></code> (optional)
<div><div>
 <p>Timeout value in seconds. Upon timeout, Jenkins checks the Change creation status in ServiceNow and if it failed to create the CHG, it resumes or aborts the pipeline based on the flag abortOnChangeCreationFailure. By default it aborts, when timeout is specified.</p>
</div></div>

</li>
<li><code>changeRequestDetails : String</code> (optional)
<div><div>
 changeRequestDetails specifies closure code and change request fields from within the pipeline (starting with version 1.24).
 <br>
 <br>
  Example: 
 <br>
 <p>{ "attributes": { "short_description": "Test description", "priority": "1", "start_date": "2021-02-05 08:00:00", "end_date": "2022-04-05 08:00:00", "justification": "test justification", "description": "test description", "cab_required": &lt;true/false&gt;, "comments": "This update for work notes is from jenkins file", "work_notes": "test work notes", "assignment_group": "&lt;SYS_ID&gt;" }, "setCloseCode": &lt;true/false&gt; }</p>
</div></div>

</li>
<li><code>changeStepTimeOut : <code>Object</code></code> (optional)
<div><div>
 <p>Timeout value in seconds. Upon timeout, if the Change step is still in progress, it resumes or aborts the pipeline based on the flag abortOnChangeStepTimeout. By default it aborts, when timeout is specified.</p>
</div></div>

</li>
<li><code>enabled : boolean</code> (optional)
<div><div>
 Enabled specifies the setting for build notifications property (true/false)
</div></div>

</li>
<li><code>ignoreErrors : boolean</code> (optional)
<div><div>
 ignoreErrors specifies the setting to prevent job failure if there is an error (true/false)
</div></div>

</li>
<li><code>pollingInterval : <code>Object</code></code> (optional)
<div><div>
 Frequency at which Jenkins polls ServiceNow for the Change status and update the console logs only on Change state transitions, Asssignment Group updates, Approval updates, Planned Start/End date updates. Specify time in seconds.
</div></div>

</li>
<li><code>snapshotName : String</code> (optional)
<div><div>
 Specifies snapshot from which to export data.
</div></div>

</li>
</ul>


++++
=== `snDevOpsConfig`: ServiceNow DevOps - DevOps Configuration Pipeline
++++
<div><div>
 This action streamlines and enhances the functionality of DevOps Config by integrating multiple operations into a single action. 
 <br>
  The revamped process follows these steps:
 <br><b>Upload</b>: The action begins by uploading files specified in a regex format.
 <br><b>Validation and Publishing</b>: Config data validation and publishing can be customized through arguments provided for this action.
 <br><b>Snapshot Retrieval</b>: After the upload, the action retrieves the created snapshots and waits for the validation process to complete. It generates test results based on user input.
 <br><b>Changeset Registration</b>: The action registers the changeset with the pipeline execution.
 <br>
  Finally, the action returns a list of snapshot objects.
</div></div>
<ul><li><code>applicationName : String</code>
<div><div>
 Specifies the application to where config data will be uploaded.
</div></div>

</li>
<li><code>target : String</code>
<div><div>
 Specifies the data model target to where config data will be uploaded (for example, component, collection, deployable).
</div></div>

</li>
<li><code>namePath : String</code>
<div><div>
 Specifies the name path in the data model to where config data will be uploaded. 
 <br><b>Note:</b> When uploading to a vars folder, you must start the name path with "vars/" to specifiy the variable folder path.
</div></div>

</li>
<li><code>configFile : String</code>
<div><div>
 Specifies the configuration data file to upload to the component or deployable path in the data model.
</div></div>

</li>
<li><code>autoCommit : String</code> (optional)
<div><div>
 Specifies whether to commit configuration data after upload (true/false). Default is false.
</div></div>

</li>
<li><code>autoDelete : String</code> (optional)
</li>
<li><code>autoPublish : String</code> (optional)
<div><div>
 Specifies whether to auto publish for a snapshot for the given application and deployable (true/false). Default is false.
</div></div>

</li>
<li><code>autoValidate : String</code> (optional)
<div><div>
 Specifies whether to validate configuration data during commit (true/false). Default is false.
</div></div>

</li>
<li><code>changesetNumber : String</code> (optional)
<div><div>
 <b>Output variable</b>
 <br>
  Specifies the (open) changeset to which this upload activity is associated.
</div></div>

</li>
<li><code>collectionName : String</code> (optional)
<div><div>
 Name of the collection to upload to (required if target is collection).
</div></div>

</li>
<li><code>continueWithLatest : boolean</code> (optional)
</li>
<li><code>convertPath : boolean</code> (optional)
<div><div>
 Specifies whether to preserve the directory structure of configuration files (with respect to the workspace) and convert the directory to paths within the data model.
</div></div>

</li>
<li><code>dataFormat : String</code> (optional)
<div><div>
 Specifies the data format of the config file (for example, JSON, YAML, XML, etc.)
</div></div>

</li>
<li><code>deployableName : String</code> (optional)
<div><div>
 Name of the deployable to upload to (required if target is deployable).
</div></div>

</li>
<li><code>enabled : boolean</code> (optional)
<div><div>
 Enabled specifies the setting for build notifications property (true/false)
</div></div>

</li>
<li><code>ignoreErrors : boolean</code> (optional)
<div><div>
 Specifies the setting to prevent job failure if there is an error
</div></div>

</li>
<li><code>isValidated : boolean</code> (optional)
<div><div>
 Specifies to only retrieve the latest validated snapshots, with or without exceptions.
</div></div>

</li>
<li><code>markFailed : boolean</code> (optional)
<div><div>
 Fail the pipeline in the event that the validation attempt failed (due to a backend issue).
</div></div>

</li>
<li><code>showResults : boolean</code> (optional)
<div><div>
 Specifies the expected data format of the returned configuration data.
</div></div>

</li>
<li><code>testResultFormat : String</code> (optional)
<div><div>
 Specifies the format of the test results(xml or json).
</div></div>

</li>
</ul>


++++
=== `snDevOpsConfigExport`: ServiceNow DevOps - DevOps Configuration Export
++++
<div><div>
 This action exports a snapshot for the given application and deployable. 
 <br>
  The user should specify the exporter, relevant exporter arguments, the export format (for example, YAML, JSON, etc.), and output location for the exported config data. 
 <br>
  From here, the config data can be used directly as an input for a deployment or provisioning tool downstream in the pipeline. 
 <br><b>Example:</b>
 <br>
 <div>
  <pre>        <span>snDevOpsConfigExport</span>(
             <span>applicationName</span>: <span>'PaymentDemo'</span>,
             <span>deployableName</span>: <span>'Production'</span>,
             <span>snapshotName</span>: <span>'Production-v23.dpl'</span>,
             <span>exporterFormat</span>: <span>'yaml'</span>,
             <span>exporterName</span>: <span>'returnAllData-now'</span>,
             <span>exporterArgs</span>: <span>''</span>,
             <span>fileName</span>: <span>'exported_file-Production-20220302.yml'</span>
        )</pre>
 </div>
</div></div>
<ul><li><code>applicationName : String</code>
<div><div>
 Specifies the application to where config data will be uploaded.
</div></div>

</li>
<li><code>deployableName : String</code>
<div><div>
 Name of the deployable to upload to (required if target is deployable).
</div></div>

</li>
<li><code>exporterName : String</code>
<div><div>
 Specifies the exporter to apply to the snapshot (for example, UniqueCDIs).
</div></div>

</li>
<li><code>exporterFormat : String</code>
<div><div>
 Specifies the format to export the snapshot data (For example, INI, YAML, PROPS).
</div></div>

</li>
<li><code>fileName : String</code>
<div><div>
 Specifies the file to be used from the workspace to store the exported config data. (Example: stagingConfig.json)
</div></div>

</li>
<li><code>enabled : boolean</code> (optional)
<div><div>
 Enabled specifies the setting for build notifications property (true/false)
</div></div>

</li>
<li><code>exporterArgs : String</code> (optional)
<div><div>
 Specifies arguments to be used along with the exporter.
</div></div>

</li>
<li><code>ignoreErrors : boolean</code> (optional)
<div><div>
 Specifies the setting to prevent job failure if there is an error
</div></div>

</li>
<li><code>markFailed : boolean</code> (optional)
<div><div>
 Fail the pipeline in the event that the validation attempt failed (due to a backend issue).
</div></div>

</li>
<li><code>showResults : boolean</code> (optional)
<div><div>
 Specifies the expected data format of the returned configuration data.
</div></div>

</li>
<li><code>snapshotName : String</code> (optional)
<div><div>
 Specifies snapshot from which to export data.
</div></div>

</li>
</ul>


++++
=== `snDevOpsConfigGetSnapshots`: ServiceNow DevOps - Get latest and validated snapshots
++++
<div><ul>
 <li>Retrieve all snapshots for any impacted deployables.
  <p>When config files are uploaded to an application data model, the system will create snapshots for any deployables determined to be impacted by the upload. Following along the CI flow, assuming the last Upload call had validation enabled, the next step would be to iterate through the list of snapshots and ensure they all passed validation.</p></li>
 <li>Retrieve a specific snapshot.
  <p>Following the CD flow, a specific snapshot is retrieved so it can be published and then exported to be consumed downstream (for example, to provision out infrastructure or application).</p></li>
 <li>Show policy validation results in a pipeline execution.
  <p>View policy validation results as test results on the Jenkins build tests results page, including compliant with exception, when getting a snapshot.</p></li><b>Example:</b>
 <br>
 <ul>
  <li>Specific snapshot (specified):
   <div>
    <div>
     <pre><span>$snapshots</span> = <span>snDevOpsConfigGetSnapshots</span>(
<span>applicationName</span>: <span>'PaymentDemo'</span>,
<span>deployableName</span>: <span>'Production'</span>,
<span>changesetNumber</span>: <span>'Chset-16'</span>
)</pre>
    </div>
   </div></li>
  <li>Latest validated snapshot (returns the latest snapshot for application and deployable combination):
   <div>
    <div>
     <pre><span>$snapshots</span> = <span>snDevOpsConfigGetSnapshots</span>(
<span>applicationName</span>: <span>'PaymentDemo'</span>,
<span>deployableName</span>: <span>'Production'</span>,
<span>isValidated</span>: <span>'true'</span>
)</pre>
    </div>
   </div></li>
  <li>All changeset snapshots (returns all snapshots for application and deployable combination):
   <div>
    <div>
     <pre><span>$snapshots</span> = <span>snDevOpsConfigGetSnapshots</span>(
<span>applicationName</span>: <span>'PaymentDemo'</span>,
<span>changesetNumber</span>: <span>'Chset-16'</span>,
)</pre>
    </div>
   </div></li>
  <li>Show policy validation results in a pipeline execution.
   <div>
    <ol>
     <li>Assign a variable to the path of the file that contains the snapshot validation results generated during the snDevOpsConfigGetSnapshots action.</li>
     <li>Call the <a href="https://plugins.jenkins.io/junit/" rel="nofollow">JUnit action</a> to load the snapshot validation results into the pipeline execution test section.</li>
    </ol>
    <div>
     <pre>stage(<span>'Validate'</span>) {
steps {
script {
changeSetResults = snDevOpsConfigGetSnapshots( … )
<span>if</span> (!changeSetResults) {
 echo <span>"No snapshots were created"</span>
} <span>else</span> {
def changeSetResultsObject = readJSON text: changeSetResults

changeSetResultsObject.each {
     snapshotName = it.name
     snapshotObject = it
}
<span>// STEP 1</span>
validationResultsPath = <span>"<span>${snapshotName}</span>_<span>${currentBuild.projectName}</span>_<span>${currentBuild.number}</span>.xml"</span>
}
}
}
}

post {
always {
<span>// STEP 2</span>
junit testResults: <span>"<span>${validationResultsPath}</span>"</span>, skipPublishingChecks: <span>true</span>
}
}
</pre>
    </div>
   </div></li>
 </ul>
</ul></div>
<ul><li><code>applicationName : String</code>
<div><div>
 Specifies the application to where config data will be uploaded.
</div></div>

</li>
<li><code>deployableName : String</code> (optional)
<div><div>
 Name of the deployable to upload to (required if target is deployable).
</div></div>

</li>
<li><code>changesetNumber : String</code> (optional)
<div><div>
 <b>Output variable</b>
 <br>
  Specifies the (open) changeset to which this upload activity is associated.
</div></div>

</li>
<li><code>continueWithLatest : boolean</code> (optional)
</li>
<li><code>enabled : boolean</code> (optional)
<div><div>
 Enabled specifies the setting for build notifications property (true/false)
</div></div>

</li>
<li><code>ignoreErrors : boolean</code> (optional)
<div><div>
 Specifies the setting to prevent job failure if there is an error
</div></div>

</li>
<li><code>isValidated : boolean</code> (optional)
<div><div>
 Specifies to only retrieve the latest validated snapshots, with or without exceptions.
</div></div>

</li>
<li><code>markFailed : boolean</code> (optional)
<div><div>
 Fail the pipeline in the event that the validation attempt failed (due to a backend issue).
</div></div>

</li>
<li><code>outputFormat : String</code> (optional)
<div><div>
 Specifies the format of the test results(xml or json).
</div></div>

</li>
<li><code>showResults : boolean</code> (optional)
<div><div>
 Specifies the expected data format of the returned configuration data.
</div></div>

</li>
</ul>


++++
=== `snDevOpsConfigPublish`: ServiceNow DevOps - DevOps Configuration Publish
++++
<div><div>
 This action publishes a snapshot for the given application and deployable. From here, the snapshot can be consumed through the Export process.
 <br><b>Example:</b>
 <div>
  <pre>        <span>snDevOpsConfigPublish</span>(
             <span>applicationName</span>: <span>'PaymentDemo'</span>,
             <span>deployableName</span>: <span>'Production'</span>,
             <span>snapshotName</span>: <span>'Production-v23.dpl'</span>,
        )</pre>
 </div>
</div></div>
<ul><li><code>applicationName : String</code>
<div><div>
 Specifies the application to where config data will be uploaded.
</div></div>

</li>
<li><code>deployableName : String</code>
<div><div>
 Name of the deployable to upload to (required if target is deployable).
</div></div>

</li>
<li><code>snapshotName : String</code>
<div><div>
 Specifies snapshot from which to export data.
</div></div>

</li>
<li><code>enabled : boolean</code> (optional)
<div><div>
 Enabled specifies the setting for build notifications property (true/false)
</div></div>

</li>
<li><code>ignoreErrors : boolean</code> (optional)
<div><div>
 Specifies the setting to prevent job failure if there is an error
</div></div>

</li>
<li><code>markFailed : boolean</code> (optional)
<div><div>
 Fail the pipeline in the event that the validation attempt failed (due to a backend issue).
</div></div>

</li>
<li><code>showResults : boolean</code> (optional)
<div><div>
 Specifies the expected data format of the returned configuration data.
</div></div>

</li>
</ul>


++++
=== `snDevOpsConfigRegisterPipeline`: ServiceNow DevOps - DevOps Configuration Register Pipeline
++++
<div><div>
 <p>This action ties a changeset and/or snapshot to the pipeline so that it can be tracked during the pipeline execution. In <span>DevOps Change Velocity</span>, this is shown in the Pipeline UI.</p>
 <p>See <a href="https://docs.servicenow.com/bundle/utah-devops/bundle/utah-devops/page/product/devops-config/concept/../../enterprise-dev-ops/concept/dev-ops-change-acceleration.html" title="Enable the Change Acceleration feature of DevOps for automatic change request creation in your pipeline, and use change approval policies to automate approval under certain conditions." rel="nofollow">Accelerating your DevOps change process</a> for more information regarding the <span>DevOps</span> Change Acceleration feature.</p><b>Example:</b>
 <ul>
  <li>Input:
   <p>Here is an example of the snDevOpsConfigRegisterPipeline action. For the sake of illustration, we’ll assign the response to a variable, changeSetRegResult, which could be echoed out to our console log for debugging scenarios.</p>
   <div>
    <div>
     <pre>changeSetRegResult = <span>snDevOpsConfigRegisterPipeline</span>(
<span>applicationName</span>: <span>"PaymentDemo"</span>,
<span>changesetNumber</span>: <span>"Chset-122"</span>
)

<span>echo</span> <span>"Pipeline registration result: ${changeSetRegResult}"</span></pre>
    </div>
   </div></li>
 </ul>
</div></div>
<ul><li><code>applicationName : String</code> (optional)
<div><div>
 Specifies the application to where config data will be uploaded.
</div></div>

</li>
<li><code>changesetNumber : String</code> (optional)
<div><div>
 <b>Output variable</b>
 <br>
  Specifies the (open) changeset to which this upload activity is associated.
</div></div>

</li>
<li><code>enabled : boolean</code> (optional)
<div><div>
 Enabled specifies the setting for build notifications property (true/false)
</div></div>

</li>
<li><code>ignoreErrors : boolean</code> (optional)
<div><div>
 Specifies the setting to prevent job failure if there is an error
</div></div>

</li>
<li><code>markFailed : boolean</code> (optional)
<div><div>
 Fail the pipeline in the event that the validation attempt failed (due to a backend issue).
</div></div>

</li>
<li><code>showResults : boolean</code> (optional)
<div><div>
 Specifies the expected data format of the returned configuration data.
</div></div>

</li>
<li><code>snapshotName : String</code> (optional)
<div><div>
 Specifies snapshot from which to export data.
</div></div>

</li>
</ul>


++++
=== `snDevOpsConfigUpload`: ServiceNow DevOps - DevOps Configuration Upload
++++
<div><div>
 <p>This action uploads a configuration file to a given location within an application data model. <br>
   It is meant to be used in an iterative nature for all config files to upload to the application data model during the pipeline run. <br></p>
 <div>
  Supports:
  <ul>
   <li>Upload to:
    <ul>
     <li>A component, collection, or deployable.</li>
     <li>The variable (vars) folder of a component, collection, or deployable.</li>
    </ul></li>
   <li>Regex pattern for config file input.</li>
   <li>Ability to be called multiple times in the same pipeline.</li>
  </ul>
 </div>
 <ul>
  <li>Input:
   <p>Here is an example of the snDevOpsConfigUpload action. For the sake of illustration, we’ll assign the response to a variable, changeSetId, which could be echoed out to our console log for debugging scenarios.</p>
   <div>
    <div>
     <pre>        changeSetId = <span>snDevOpsConfigUpload</span>(
            <span>applicationName</span>: <span>"PaymentDemo"</span>,
            <span>target</span>: <span>'component'</span>,
            <span>namePath</span>: <span>"web-api-v1.0"</span>,
            <span>configFile</span>: <span>"k8s/helm/values.yml"</span>,
            <span>dataFormat</span>: <span>"json"</span>,
            <span>autoCommit</span>: <span>'true'</span>,
            <span>autoDelete</span>: <span>'true'</span>,
            <span>autoValidate</span>: <span>'true'</span>
        )

<span>echo</span> <span>"Changeset: <span>$changeSetId</span> created"</span></pre>
    </div>
   </div></li>
 </ul><b> Example - Multiple uploads (component) </b>
 <div>
  You can call the upload action more than once to upload configuration data in different file formats from different locations, while still keeping the uploads part of one changeset.
  <ul>
   <li>In the first upload, name the action so the changesetNumber output variable can be reused in subsequent uploads.
    <div>
     YAML file upload:
     <div>
      <pre> <span>$changeset</span> = <span>snDevOpsConfigUpload</span>(
      <span>applicationName</span>: <span>'PaymentDemo'</span>,
      <span>target</span>: <span>'component'</span>,
      <span>namePath</span>: <span>'wep-api-v1.0'</span>,
      <span>configFile</span>: <span>'k8s/helm/values.yml'</span>,
      <span>dataFormat</span>: <span>'yaml'</span>,
      <span>autoCommit</span>: <span>'false'</span>,
      <span>autoDelete</span>: <span>'false'</span>,
      <span>autoValidate</span>: <span>'false'</span>
 )</pre>
     </div>
    </div></li>
   <li>In subsequent uploads, reference the changesetNumber output variable from the first upload as an input variable.
    <div>
     3 JSON files upload:
     <div>
      <pre> <span>snDevOpsConfigUpload</span>(
      <span>applicationName</span>: <span>'PaymentDemo'</span>,
      <span>target</span>: <span>'component'</span>,
      <span>namePath</span>: <span>'wep-api-v1.0'</span>,
      <span>configFile</span>: <span>'infra/*.json'</span>,
      <span>dataFormat</span>: <span>'json'</span>,
      <span>autoCommit</span>: <span>'false'</span>,
      <span>autoDelete</span>: <span>'false'</span>,
      <span>autoValidate</span>: <span>'false'</span>,
      <span>changesetNumber</span>: ”${<span>changeset</span>}”
 )</pre>
     </div>
    </div></li>
   <li>In the final call, in addition to referencing the changesetNumber output variable from the first upload as an input variable, set autoCommit, autoDelete, and autoValidate to true.
    <div>
     INI file upload:
     <div>
      <pre> <span>snDevOpsConfigUpload</span>(
      <span>applicationName</span>: <span>'PaymentDemo'</span>,
      <span>target</span>: <span>'component'</span>,
      <span>namePath</span>: <span>'wep-api-v1.0'</span>,
      <span>configFile</span>: <span>'featureToggles/set1.ini'</span>,
      <span>dataFormat</span>: <span>'ini'</span>,
      <span>autoCommit</span>: <span>'true'</span>,
      <span>autoDelete</span>: <span>'true'</span>,
      <span>autoValidate</span>: <span>'true'</span>,
      <span>changesetNumber</span>: ”${<span>changeset</span>}”
 )</pre>
     </div>
    </div></li>
  </ul>
 </div><b> Example - Multiple uploads (collection and vars) </b>
 <div>
  You can call the upload action more than once to upload configuration data in different file formats from different locations, while still keeping the uploads part of one changeset.
  <ul>
   <li>In the first upload, create a variable (for example, $changeset), and assign the return value of the step to it so it can be reused in subsequent uploads.
    <div>
     XML file upload:
     <div>
      <pre> <span>$changeset</span> = <span>snDevOpsConfigUpload</span>(
      <span>applicationName</span>: <span>'PaymentDemo'</span>,
      <span>target</span>: <span>'collection'</span>,
      <span>collectionName</span>: <span>'release-v1.0'</span>,
      <span>namePath</span>: <span>'v1-common-configs'</span>,
      <span>configFile</span>: <span>'infra/v1/config.xml'</span>,
      <span>dataFormat</span>: <span>'xml'</span>,
      <span>autoCommit</span>: <span>'false'</span>,
      <span>autoDelete</span>: <span>'false'</span>,
      <span>autoValidate</span>: <span>'false'</span>
 )</pre>
     </div>
    </div></li>
   <li>In subsequent uploads, use the variable as an input.
    <div>
     JSON file upload: 
     <div>
      <pre> <span>snDevOpsConfigUpload</span>(
      <span>applicationName</span>: <span>'PaymentDemo'</span>,
      <span>target</span>: <span>'deployable'</span>,
      <span>deployableName</span>: <span>'Production'</span>,
      <span>namePath</span>: <span>'vars/dbSettings'</span>,
      <span>configFile</span>: <span>'infra/prod/dbConfig.json'</span>,
      <span>dataFormat</span>: <span>'json'</span>,
      <span>autoCommit</span>: <span>'true'</span>,
      <span>autoDelete</span>: <span>'true'</span>,
      <span>autoValidate</span>: <span>'true'</span>,
      <span>changesetNumber</span>: ”${<span>changeset</span>}”
 )</pre>
     </div>
    </div></li>
  </ul>
 </div>
 <div>
  <span>Note:</span> To upload to a variable folder, uploadTarget must be set to deployable, and the correct values must be set for deployableName and changesetNumber.
 </div>
</div></div>
<ul><li><code>applicationName : String</code>
<div><div>
 Specifies the application to where config data will be uploaded.
</div></div>

</li>
<li><code>target : String</code>
<div><div>
 Specifies the data model target to where config data will be uploaded (for example, component, collection, deployable).
</div></div>

</li>
<li><code>namePath : String</code>
<div><div>
 Specifies the name path in the data model to where config data will be uploaded. 
 <br><b>Note:</b> When uploading to a vars folder, you must start the name path with "vars/" to specifiy the variable folder path.
</div></div>

</li>
<li><code>configFile : String</code>
<div><div>
 Specifies the configuration data file to upload to the component or deployable path in the data model.
</div></div>

</li>
<li><code>autoCommit : boolean</code>
<div><div>
 Specifies whether to commit configuration data after upload (true/false). Default is false.
</div></div>

</li>
<li><code>autoDelete : boolean</code>
</li>
<li><code>autoValidate : boolean</code>
<div><div>
 Specifies whether to validate configuration data during commit (true/false). Default is false.
</div></div>

</li>
<li><code>autoPublish : boolean</code>
<div><div>
 Specifies whether to auto publish for a snapshot for the given application and deployable (true/false). Default is false.
</div></div>

</li>
<li><code>changesetNumber : String</code> (optional)
<div><div>
 <b>Output variable</b>
 <br>
  Specifies the (open) changeset to which this upload activity is associated.
</div></div>

</li>
<li><code>collectionName : String</code> (optional)
<div><div>
 Name of the collection to upload to (required if target is collection).
</div></div>

</li>
<li><code>convertPath : boolean</code> (optional)
<div><div>
 Specifies whether to preserve the directory structure of configuration files (with respect to the workspace) and convert the directory to paths within the data model.
</div></div>

</li>
<li><code>dataFormat : String</code> (optional)
<div><div>
 Specifies the data format of the config file (for example, JSON, YAML, XML, etc.)
</div></div>

</li>
<li><code>deployableName : String</code> (optional)
<div><div>
 Name of the deployable to upload to (required if target is deployable).
</div></div>

</li>
<li><code>enabled : boolean</code> (optional)
<div><div>
 Enabled specifies the setting for build notifications property (true/false)
</div></div>

</li>
<li><code>ignoreErrors : boolean</code> (optional)
<div><div>
 Specifies the setting to prevent job failure if there is an error
</div></div>

</li>
<li><code>markFailed : boolean</code> (optional)
<div><div>
 Fail the pipeline in the event that the validation attempt failed (due to a backend issue).
</div></div>

</li>
<li><code>showResults : boolean</code> (optional)
<div><div>
 Specifies the expected data format of the returned configuration data.
</div></div>

</li>
</ul>


++++
=== `snDevOpsConfigValidate`: ServiceNow DevOps - DevOps Configuration Validate
++++
<div><div>
 Validate config data against your organization policies.
 <br><b>Example:</b>
 <br>
 <ul>
  <li>Specific snapshot (specified):
   <div>
    <div>
     <pre><span>snDevOpsConfigValidate</span>(
<span>applicationName</span>: <span>'PaymentDemo'</span>,
<span>deployableName</span>: <span>'Production'</span>,
<span>snapshotName</span>: <span>'Production-v23.dpl'</span>,
)</pre>
    </div>
   </div></li>
  <li>Latest snapshot (retrieves and validates the latest snapshot for application and deployable combination):
   <div>
    <div>
     <pre><span>$changeset</span> = <span>snDevOpsConfigValidate</span>(
<span>applicationName</span>: <span>'PaymentDemo'</span>,
<span>deployableName</span>: <span>'Production'</span>
)</pre>
    </div>
   </div></li>
 </ul>
</div></div>
<ul><li><code>applicationName : String</code>
<div><div>
 Specifies the application to where config data will be uploaded.
</div></div>

</li>
<li><code>deployableName : String</code>
<div><div>
 Name of the deployable to upload to (required if target is deployable).
</div></div>

</li>
<li><code>enabled : boolean</code> (optional)
<div><div>
 Enabled specifies the setting for build notifications property (true/false)
</div></div>

</li>
<li><code>ignoreErrors : boolean</code> (optional)
<div><div>
 Specifies the setting to prevent job failure if there is an error
</div></div>

</li>
<li><code>markFailed : boolean</code> (optional)
<div><div>
 Fail the pipeline in the event that the validation attempt failed (due to a backend issue).
</div></div>

</li>
<li><code>showResults : boolean</code> (optional)
<div><div>
 Specifies the expected data format of the returned configuration data.
</div></div>

</li>
<li><code>snapshotName : String</code> (optional)
<div><div>
 Specifies snapshot from which to export data.
</div></div>

</li>
</ul>


++++
=== `snDevOpsGetChangeNumber`: ServiceNow DevOps - get Change Number step
++++
<div><div>
 <p><b>snDevOpsGetChangeNumber</b> <br>
   Returns the DevOps change request number based on the inputs provided. <br>
   For more information, see <a href="https://docs.servicenow.com/bundle/tokyo-devops/page/product/enterprise-dev-ops/concept/devops-change-number-notify-jenkins.html" rel="nofollow">click here</a></p>
</div></div>
<ul><li><code>changeDetails : String</code> (optional)
<div><div>
 Pipeline Name, Build Number, Stage Name are mandatory input parameters to retrieve the change request number. If these input field parameters are not provided, the change request number for the current Pipeline Name, Build Number, Stage Name will be retrieved. For multi-branch pipelines, you must provide the Branch Name as an input parameter as well. (starting with version 1.37).
 <br>
 <br>
  Example: 
 <br>
 <p>{ "pipeline_name": "Test Pipeline", "build_number": "1", "stage_name": "ChangeStage", "branch_name": "master" }</p>
</div></div>

</li>
</ul>


++++
=== `snDevOpsPackage`: ServiceNow DevOps - Register Package step
++++
<div><div>
 <p><b>Artifact package creation</b> <br>
   Configure artifact package creation in a scripted pipeline or freestyle job using the DevOps API /package/registration endpoint. <br></p>
</div></div>
<ul><li><code>name : String</code> (optional)
<div><div>
 Collection of artifact versions used as input to a CD pipeline, or for associating test results.
</div></div>

</li>
<li><code>artifactsPayload : String</code> (optional)
<div><div>
 ArtifactPayload 
 <br>
  "name" --&gt; Artifact name for which different builds (artifact versions) are generated. 
 <br>
  "version" --&gt; Specific version of the artifact. Deployable component of an application generated by a CI build. When provided, semantic version is used.
 <br>
  "semanticVersion" --&gt; Optional attribute of an artifact version that, when provided, is used to determine commits for a change. Semantic version format is (MAJOR.MINOR.PATCH).
 <br>
  "repository" --&gt; Target for artifacts generated in a build, and also a source of artifacts required by a build.
 <br>
 <br>
 <br>
  Example:
 <br>
  {"artifacts":[{"name": "sa-web.jar", "version": "1.9", "repositoryName": "services-1031"}, {"name": "sa-db.jar", "version": "1.3.2", "repositoryName": "services-1032"}], "branchName": "master"}
</div></div>

</li>
</ul>


++++
=== `snDevOpsSecurityResult`: Servicenow Register Security Step
++++
<div><div>
 <p><br><b>snDevOpsSecurityResults</b> - Retrieves and stores the security scan results <br></p>
</div></div>
<ul><li><code>securityResultAttributes : String</code> (optional)
<div><div>
 <h3>Enter the security result attributes.</h3>
 <h4>Jenkins-Veracode:</h4> '{"scanner": "Veracode", "applicationName": "", "buildVersion": "", "securityToolId": ""}' 
 <br>
 <br>
  scanner: Scanning tool and is required e.g. Veracode.
 <br>
  applicationName: Name of your Veracode application and is required. This attribute is applicable only for Veracode.
 <br>
  buildVersion: Veracode Scan name / build version and is optional. This attribute is applicable only for Veracode.
 <br>
  securityToolId: Security tool onboarded in ServiceNow (sys_id of the onboarded security tool) and is optional.
 <br>
 <br>
 <h4>Jenkins-Checkmarx One:</h4> '{"scanner": "Checkmarx One", "projectName": "", "projectId": "", "scanId": "", "securityToolId": ""}' 
 <br>
 <br>
  scanner: Scanning tool and is required e.g. Checkmarx One.
 <br>
  projectName/ProjectId: Name/Id of your Checkmarx One project and is required. This attribute is applicable only for Checkmarx One.
 <br>
  scanId: Checkmarx One scan id and is optional. This attribute is applicable only for Checkmarx One.
 <br>
  securityToolId: Security tool onboarded in ServiceNow (sys_id of the onboarded security tool) and is optional.
 <br>
 <br>
 <h4>Jenkins-CheckMarx SAST:</h4> '{"scanner": "Checkmarx SAST", "projectId": "", "securityToolId": ""}' 
 <br>
 <br>
  scanner: Scanning tool and is required e.g. Checkmarx SAST.
 <br>
  ProjectId: Id of your Checkmarx SAST project and is required. This attribute is applicable only for Checkmarx SAST.
 <br>
  securityToolId: Security tool onboarded in ServiceNow (sys_id of the onboarded security tool) and is optional.
 <br>
 <br>
 <h4>Jenkins-Others:</h4> You can use this snippet if you are using any other security tool that ServiceNow doesn't support in the base system. In addition to "scanner" and "securityToolId" you must provide the required project information (e.g. scanId or ProjectId or ProjectName or any other attribute that is applicable) for us to retrieve the security scan results from your custom security tool. 
 <br>
 <br>
  '{"scanner": "", "securityToolId": ""}' 
 <br>
 <br>
  scanner: Scanning tool and is required e.g. Custom security tool.
 <br>
  securityToolId: Security tool onboarded in ServiceNow (sys_id of the onboarded security tool) and is optional.
 <br>
</div></div>

</li>
</ul>


++++
=== `snDevOpsStep`: ServiceNow DevOps - Mapping step
++++
<ul><li><code>enabled : boolean</code> (optional)
</li>
<li><code>ignoreErrors : boolean</code> (optional)
</li>
</ul>


++++
=== `snDevOpsUpdateChangeInfo`: ServiceNow DevOps - Update Change Request Info
++++
<div><div>
 <p><b>snDevOpsUpdateChangeInfo</b> <br>
   Updates the details of the DevOps change request number provided. Returns true/false based on the status of Update (true if update is successful, else false). <br>
   For more information, see <a href="https://docs.servicenow.com/bundle/tokyo-devops/page/product/enterprise-dev-ops/concept/devops-change-number-notify-jenkins.html" rel="nofollow">click here</a></p>
</div></div>
<ul><li><code>changeRequestDetails : String</code> (optional)
<div><div>
 Change request details to be updated must be provided as Key:Value pairs in the following format: 
 <br>
  Example: 
 <br>
 <p>{ "short_description": "Test description", "priority": "1", "start_date": "2021-02-05 08:00:00", "end_date": "2022-04-05 08:00:00", "justification": "test justification", "description": "test description", "cab_required": &lt;true/false&gt;, "comments": "This update for work notes is from jenkins file", "work_notes": "test work notes", "assignment_group": "&lt;SYS_ID&gt;", "state":"&lt;STATE_CODE&gt;", "close_code":"&lt;successful/successful_issues/unsuccessful&gt;", "reason":"&lt;As per Choice List&gt;" }</p>
 <p></p>
 <ul>
  <li>Key:Value pairs provided as input parameters must match with the Change_request table's field column values.</li>
  <li>For choice type of fields, the field value must match with the appropriate choice value (Ex: close_code)</li>
  <li>For State Transition to 'Close' of Change, 'close_code' and 'close_notes' are mandatory, and to 'Cancel' of Change, 'reason' is mandatory.</li>
 </ul>
 <p></p>
</div></div>

</li>
<li><code>changeRequestNumber : String</code> (optional)
<div><div>
 Change request number to be updated.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'DevOpsCreateArtifactPackageBuildStep'])`: ServiceNow DevOps - Register Package step
++++
<ul><li><code>name : String</code> (optional)
<div><div>
 Collection of artifact versions used as input to a CD pipeline, or for associating test results.
</div></div>

</li>
<li><code>artifactsPayload : String</code> (optional)
<div><div>
 ArtifactPayload 
 <br>
  "name" --&gt; Artifact name for which different builds (artifact versions) are generated. 
 <br>
  "version" --&gt; Specific version of the artifact. Deployable component of an application generated by a CI build. When provided, semantic version is used.
 <br>
  "semanticVersion" --&gt; Optional attribute of an artifact version that, when provided, is used to determine commits for a change. Semantic version format is (MAJOR.MINOR.PATCH).
 <br>
  "repository" --&gt; Target for artifacts generated in a build, and also a source of artifacts required by a build.
 <br>
 <br>
 <br>
  Example:
 <br>
  {"artifacts":[{"name": "sa-web.jar", "version": "1.9", "repositoryName": "services-1031"}, {"name": "sa-db.jar", "version": "1.3.2", "repositoryName": "services-1032"}], "branchName": "master"}
</div></div>

</li>
</ul>


++++
=== `step([$class: 'DevOpsFreestyleRegisterSecurityStep'])`: snDevOpsSecurityResult
++++
<ul><li><code>securityResultAttributes : String</code> (optional)
<div><div>
 <h3>Enter the security result attributes.</h3>
 <h4>Jenkins-Veracode:</h4> '{"scanner": "Veracode", "applicationName": "", "buildVersion": "", "securityToolId": ""}' 
 <br>
 <br>
  scanner: Scanning tool and is required e.g. Veracode.
 <br>
  applicationName: Name of your Veracode application and is required. This attribute is applicable only for Veracode.
 <br>
  buildVersion: Veracode Scan name / build version and is optional. This attribute is applicable only for Veracode.
 <br>
  securityToolId: Security tool onboarded in ServiceNow (sys_id of the onboarded security tool) and is optional.
 <br>
 <br>
 <h4>Jenkins-Checkmarx One:</h4> '{"scanner": "Checkmarx One", "projectName": "", "projectId": "", "scanId": "", "securityToolId": ""}' 
 <br>
 <br>
  scanner: Scanning tool and is required e.g. Checkmarx One.
 <br>
  projectName/ProjectId: Name/Id of your Checkmarx One project and is required. This attribute is applicable only for Checkmarx One.
 <br>
  scanId: Checkmarx One scan id and is optional. This attribute is applicable only for Checkmarx One.
 <br>
  securityToolId: Security tool onboarded in ServiceNow (sys_id of the onboarded security tool) and is optional.
 <br>
 <br>
 <h4>Jenkins-CheckMarx SAST:</h4> '{"scanner": "Checkmarx SAST", "projectId": "", "securityToolId": ""}' 
 <br>
 <br>
  scanner: Scanning tool and is required e.g. Checkmarx SAST.
 <br>
  ProjectId: Id of your Checkmarx SAST project and is required. This attribute is applicable only for Checkmarx SAST.
 <br>
  securityToolId: Security tool onboarded in ServiceNow (sys_id of the onboarded security tool) and is optional.
 <br>
 <br>
 <h4>Jenkins-Others:</h4> You can use this snippet if you are using any other security tool that ServiceNow doesn't support in the base system. In addition to "scanner" and "securityToolId" you must provide the required project information (e.g. scanId or ProjectId or ProjectName or any other attribute that is applicable) for us to retrieve the security scan results from your custom security tool. 
 <br>
 <br>
  '{"scanner": "", "securityToolId": ""}' 
 <br>
 <br>
  scanner: Scanning tool and is required e.g. Custom security tool.
 <br>
  securityToolId: Security tool onboarded in ServiceNow (sys_id of the onboarded security tool) and is optional.
 <br>
</div></div>

</li>
<li><code>securityToolId : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'DevOpsRegisterArtifactBuildStep'])`: ServiceNow DevOps - Register Artifact step
++++
<ul><li><code>artifactsPayload : String</code> (optional)
<div><div>
 ArtifactPayload 
 <br>
  "name" --&gt; Artifact name for which different builds (artifact versions) are generated. 
 <br>
  "version" --&gt; Specific version of the artifact. Deployable component of an application generated by a CI build. When provided, semantic version is used.
 <br>
  "semanticVersion" --&gt; Optional attribute of an artifact version that, when provided, is used to determine commits for a change. Semantic version format is (MAJOR.MINOR.PATCH).
 <br>
  "repository" --&gt; Target for artifacts generated in a build, and also a source of artifacts required by a build.
 <br>
 <br>
 <br>
  Example:
 <br>
  {"artifacts":[{"name": "sa-web.jar", "version": "1.9", "repositoryName": "services-1031"}, {"name": "sa-db.jar", "version": "1.3.2", "repositoryName": "services-1032"}], "branchName": "master"}
</div></div>

</li>
</ul>


++++
