= SLOCCount Plug-in
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/sloccount">Visit the Jenkins Plugins site</a>
++++


=== `sloccountPublish`: Publish Sloccount reports
++++
<ul><li><code>pattern : String</code> (optional)
</li>
<li><code>encoding : String</code> (optional)
</li>
<li><code>commentIsCode : boolean</code> (optional)
</li>
<li><code>numBuildsInGraph : int</code> (optional)
</li>
<li><code>ignoreBuildFailure : boolean</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'SloccountPublisher'])`: Publish SLOCCount analysis results
++++
<ul><li><code>pattern : String</code>
<div><p><a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">Fileset 'includes'</a> setting that specifies the generated raw <a href="http://www.dwheeler.com/sloccount/" rel="nofollow">SLOCCount</a> or <a href="http://cloc.sourceforge.net/" rel="nofollow">cloc</a> report files, such as '**/sloccount.sc' or '**/cloc.xml'. Basedir of the fileset is <a rel="nofollow">the workspace root</a>. If no value is set, then the default '**/sloccount.sc' is used. Be sure not to include any non-report files into this pattern.</p>
<p>The report files must have been generated by sloccount tool using the "--wide --details" options, e.g.</p>
<pre>    sloccount --duplicates --wide --details SOURCE_DIRECTORY &gt; sloccount.sc
</pre>
<p>or by cloc tool using the "--by-file --xml" options, e.g.</p>
<pre>    cloc --by-file --xml --out=cloc.xml SOURCE_DIRECTORY
</pre>
<p>If you are not sure which type to use, prefer <em>cloc</em>. It is able to detect more programming languages than SLOCCount (Scala, Ant, CSS, ...) and is able to count also lines with comments that often contain Javadoc or Doxygen documentation. Cloc is also better portable, SLOCCount requires <a href="https://www.cygwin.com/" rel="nofollow">cygwin</a> or similar environment under MS Windows.</p>
<p><strong>Never switch between SLOCCount and cloc inside one job.</strong> You would end up with messy trend graph because they name programming languages differently. Delete all affected builds and rebuild the job in such case to fix the issue.</p></div>

</li>
<li><code>encoding : String</code>
<div>The character encoding of SLOCCount result files. If no value is set, default 'UTF-8' will be used. This option is considered only in the SLOCCount report parser and is ignored in the cloc one.</div>

</li>
<li><code>commentIsCode : boolean</code>
</li>
<li><code>numBuildsInGraph : int</code>
<div>Maximal number of last successful builds, that are displayed in the trend graphs. Use 1 or less for unlimited.</div>

</li>
<li><code>ignoreBuildFailure : boolean</code>
</li>
</ul>


++++
