= SmileHub Notifier
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/smilehubnotifier">Visit the Jenkins Plugins site</a>
++++


=== `smilehubSend`: Send SmileHub Message
++++
<div><div>
 Simple step for sending a SmileHub message to specified channel.
 <br>
  Use the advanced settings to override the SmileHub Plugin global configuration to include: <code>channel</code>.
 <br>
  Please see the SmileHub Plugin global configuration for more details on the fields. Usage Example:
 <br><code> rocketSend "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (&lt;${env.BUILD_URL}|Open&gt;)" </code>
</div></div>
<ul><li><code>message : String</code>
</li>
<li><code>attachments</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>title : String</code>
</li>
<li><code>audioUrl : String</code> (optional)
</li>
<li><code>authorIcon : String</code> (optional)
</li>
<li><code>authorName : String</code> (optional)
</li>
<li><code>collapsed : boolean</code> (optional)
</li>
<li><code>color : String</code> (optional)
</li>
<li><code>imageUrl : String</code> (optional)
</li>
<li><code>messageLink : String</code> (optional)
</li>
<li><code>text : String</code> (optional)
</li>
<li><code>thumbUrl : String</code> (optional)
</li>
<li><code>titleLink : String</code> (optional)
</li>
<li><code>titleLinkDownload : boolean</code> (optional)
</li>
<li><code>ts : String</code> (optional)
</li>
<li><code>videoUrl : String</code> (optional)
</li>
</ul></li>
<li><code>avatar : String</code> (optional)
</li>
<li><code>channel : String</code> (optional)
</li>
<li><code>color : String</code> (optional)
</li>
<li><code>emoji : String</code> (optional)
</li>
<li><code>failOnError : boolean</code> (optional)
</li>
<li><code>rawMessage : boolean</code> (optional)
</li>
<li><code>serverUrl : String</code> (optional)
</li>
<li><code>trustSSL : boolean</code> (optional)
</li>
<li><code>webhookToken : String</code> (optional)
</li>
<li><code>webhookTokenCredentialId : String</code> (optional)
</li>
</ul>


++++
