= Snyk Security Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/snyk-security-scanner">Visit the Jenkins Plugins site</a>
++++


=== `snykSecurity`: Invoke Snyk Security task
++++
<ul><li><code>additionalArguments : String</code> (optional)
</li>
<li><code>failOnError : boolean</code> (optional)
</li>
<li><code>failOnIssues : boolean</code> (optional)
</li>
<li><code>monitorProjectOnBuild : boolean</code> (optional)
</li>
<li><code>organisation : String</code> (optional)
</li>
<li><code>projectName : String</code> (optional)
</li>
<li><code>severity : String</code> (optional)
</li>
<li><code>snykInstallation : String</code> (optional)
</li>
<li><code>snykTokenId : String</code> (optional)
</li>
<li><code>targetFile : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'SnykStepBuilder'])`: Invoke Snyk Security task
++++
<ul><li><code>additionalArguments : String</code> (optional)
<div><div>
 <p>Additional runtime arguments that will be used to invoke the Snyk CLI. See the <a href="https://snyk.io/docs/using-snyk/" rel="nofollow">Snyk CLI help page</a> for more details.</p>
 <p>Use the standalone double-dash <code>--</code> to pass arguments to the build tool invoked by the Snyk CLI. For example:</p>
 <ul>
  <li><code>-- -Pprofile -Dkey=value</code> for <code>Maven</code> projects.</li>
  <li><code>-- --configuration runtime</code> for <code>Gradle</code> projects.</li>
  <li><code>-- -Dkey=value</code> for <code>SBT</code> projects.</li>
 </ul>
</div></div>

</li>
<li><code>failOnError : boolean</code> (optional)
<div><div>
 <p>Whether the step should fail if Snyk fails to scan the project due to an error. Errors include scenarios like: failing to download Snyk's binaries, improper Jenkins setup, bad configuration and server errors.</p>
</div></div>

</li>
<li><code>failOnIssues : boolean</code> (optional)
<div><div>
 <p>The "When issues are found" selection specifies if builds should be failed or continued based on issues found by Snyk.</p>
 <ul>
  <li>if "Fail the build, if severity at or above" is selected, the Jenkins build will <strong>fail</strong> if Snyk detects issues of provided level or higher.</li>
  <li>if "Let the build continue" is selected, the Jenkins build will <strong>continue</strong> even if Snyk detects issues in the project.</li>
 </ul>
 <p>The corresponding CLI option for severity parameter: <strong>--severity-threshold</strong></p>
</div></div>

</li>
<li><code>monitorProjectOnBuild : boolean</code> (optional)
<div><div>
 <p>Monitor the project on every build by taking a snapshot of its current dependencies on Snyk.io. Selecting this option will keep you notified about newly disclosed vulnerabilities and remediation options in the project.</p>
</div></div>

</li>
<li><code>organisation : String</code> (optional)
<div><div>
 <p>The Snyk organisation in which this project should be tested and monitored. Leave empty to use your default organisation.</p>
 <p>The corresponding CLI option for this parameter: <strong>--org</strong></p>
</div></div>

</li>
<li><code>projectName : String</code> (optional)
<div><div>
 <p>A custom name for the Snyk project created for this Jenkins project on every build. Leave empty for the project's name to be detected in the manifest file.</p>
 <p>The corresponding CLI option for this parameter: <strong>--project-name</strong></p>
</div></div>

</li>
<li><code>severity : String</code> (optional)
</li>
<li><code>snykInstallation : String</code> (optional)
<div><div>
 <p>Ensures that the selected version of Snyk tools are installed. In addition, the Snyk tools will be added at the start of the <code>PATH</code> environment variable during builds.</p>
 <p>If no Snyk installations have been defined in the Jenkins system config, then none of the above steps will take place.</p>
</div></div>

</li>
<li><code>snykTokenId : String</code> (optional)
<div><div>
 <p>This needs to be the ID of an existing "Snyk API Token" credential. The token will be used to authenticate with Snyk.</p>
 <p>If you prefer to provide the Snyk API Token another way, such using alternative credential bindings, you'll need to provide a <code>SNYK_TOKEN</code> build environment variable.</p>
</div></div>

</li>
<li><code>targetFile : String</code> (optional)
<div><div>
 <p>The path to the manifest file to be used by Snyk. Leave empty for Snyk to auto-detect the manifest file in the project's root folder.</p>
 <p>The corresponding CLI option for this parameter: <strong>--file</strong></p>
</div></div>

</li>
</ul>


++++
