= Sonar Gerrit Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/sonar-gerrit">Visit the Jenkins Plugins site</a>
++++


=== `sonarToGerrit`: Post SonarQube issues as Gerrit comments
++++
<ul><li><code>authConfig</code> (optional)
<div><div>
 <b>Override</b> HTTP credentials specified in Gerrit Trigger settings to be used for review posting
</div></div>

<ul><b>Nested Object</b>
<li><code>httpCredentialsId : String</code> (optional)
</li>
<li><code>password : String</code> (optional)
<div><div>
 This field will <b>override</b> the HTTP password from Gerrit Trigger settings and will be used for plugin purposes only.
</div></div>

</li>
<li><code>secretPassword</code> (optional)
<ul><li><b>Type:</b> <code>class hudson.util.Secret</code></li>
</ul></li>
<li><code>username : String</code> (optional)
<div><div>
 This field will <b>override</b> the HTTP username from Gerrit Trigger settings and will be used for plugin purposes only.
</div></div>

</li>
</ul></li>
<li><code>category : String</code> (optional)
</li>
<li><code>changedLinesOnly : boolean</code> (optional)
</li>
<li><code>httpPassword : String</code> (optional)
</li>
<li><code>httpUsername : String</code> (optional)
</li>
<li><code>inspectionConfig</code> (optional)
<div><div>
 Configure accordance of SonarQube report(s) and project or module(s) path(s)
</div></div>

<ul><b>Nested Object</b>
<li><code>analysisStrategy</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>previewMode</code><div>
<ul><li><code>autoMatch : boolean</code> (optional)
<div><div>
 Allow plugin to match inspection and review system file names automatically (useful for projects with several nested modules)
</div></div>

</li>
<li><code>baseConfig</code> (optional)
<div><div>
 Provides settings for the whole project
</div></div>

<ul><b>Nested Object</b>
<li><code>autoMatch : boolean</code> (optional)
</li>
<li><code>projectPath : String</code> (optional)
<div><div>
 Provides module prefix for a file path for multi-module projects
</div></div>

</li>
<li><code>sonarReportPath : String</code> (optional)
<div><div>
 Path to SonarQube report on Jenkins server. Default value is "target/sonar/sonar-report.json"
</div></div>

</li>
</ul></li>
<li><code>sonarQubeInstallationName : String</code> (optional)
<div><div>
 The <a href="https://plugins.jenkins.io/sonar/" rel="nofollow">SonarQube installation</a> to use.
</div></div>

</li>
<li><code>subJobConfigs</code> (optional)
<div><div>
 Provides separate settings for each module
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>autoMatch : boolean</code> (optional)
</li>
<li><code>projectPath : String</code> (optional)
<div><div>
 Provides module prefix for a file path for multi-module projects
</div></div>

</li>
<li><code>sonarReportPath : String</code> (optional)
<div><div>
 Path to SonarQube report on Jenkins server. Default value is "target/sonar/sonar-report.json"
</div></div>

</li>
</ul></li>
<li><code>type : String</code> (optional)
</li>
</ul></div></li>
<li><code>pullRequest</code><div>
<ul></ul></div></li>
</ul></li>
<li><code>autoMatch : boolean</code> (optional)
</li>
<li><code>baseConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>autoMatch : boolean</code> (optional)
</li>
<li><code>projectPath : String</code> (optional)
<div><div>
 Provides module prefix for a file path for multi-module projects
</div></div>

</li>
<li><code>sonarReportPath : String</code> (optional)
<div><div>
 Path to SonarQube report on Jenkins server. Default value is "target/sonar/sonar-report.json"
</div></div>

</li>
</ul></li>
<li><code>serverURL : String</code> (optional)
</li>
<li><code>sonarQubeInstallationName : String</code> (optional)
</li>
<li><code>subJobConfigs</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>autoMatch : boolean</code> (optional)
</li>
<li><code>projectPath : String</code> (optional)
<div><div>
 Provides module prefix for a file path for multi-module projects
</div></div>

</li>
<li><code>sonarReportPath : String</code> (optional)
<div><div>
 Path to SonarQube report on Jenkins server. Default value is "target/sonar/sonar-report.json"
</div></div>

</li>
</ul></li>
<li><code>type : String</code> (optional)
</li>
</ul></li>
<li><code>issueComment : String</code> (optional)
</li>
<li><code>issuesNotification : String</code> (optional)
</li>
<li><code>issuesScore : String</code> (optional)
</li>
<li><code>newIssuesOnly : boolean</code> (optional)
</li>
<li><code>noIssuesNotification : String</code> (optional)
</li>
<li><code>noIssuesScore : String</code> (optional)
</li>
<li><code>noIssuesToPostText : String</code> (optional)
</li>
<li><code>notificationConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>commentedIssuesNotificationRecipient : String</code> (optional)
<div><div>
 This setting allow to determine who will be notified in case there are <b>several SonarQube issues matching filter settings</b> found in particular commit. 
 <br>
  An e-mails sent to recipients will contain review information: title of review and list of comments (issues). Recipient settings: 
 <br>
 <br>
  * None - No one;
 <br>
  * Owner - Owner (i.e. author of the commit);
 <br>
  * Owner and Reviewers - Owner (i.e. author of the commit) and all Reviewers (people who was added to reviewer list of the commit);
 <br>
  * All - everyone in the project list. 
 <br>
 <br>
</div></div>

</li>
<li><code>negativeScoreNotificationRecipient : String</code> (optional)
<div><div>
 This setting allow to determine who will be notified in case if the build got a negative score due to issues matching score filter settings are found. An e-mails sent to recipients will contain review information: title of review and list of comments (issues). Recipient settings: 
 <br>
 <br>
  * None - No one;
 <br>
  * Owner - Owner (i.e. author of the commit);
 <br>
  * Owner and Reviewers - Owner (i.e. author of the commit) and all Reviewers (people who was added to reviewer list of the commit);
 <br>
  * All - everyone in the project list. 
 <br>
 <br>
</div></div>

</li>
<li><code>noIssuesNotificationRecipient : String</code> (optional)
<div><div>
 This setting allow to determine who will be notified in case there are <b>no SonarQube issues matching filter settings</b> found in particular commit. 
 <br>
  An e-mails sent to recipients will contain review information: title of review. Recipient settings: 
 <br>
 <br>
  * None - No one;
 <br>
  * Owner - Owner (i.e. author of the commit);
 <br>
  * Owner and Reviewers - Owner (i.e. author of the commit) and all Reviewers (people who was added to reviewer list of the commit);
 <br>
  * All - everyone in the project list. 
 <br>
 <br>
</div></div>

</li>
</ul></li>
<li><code>overrideCredentials : boolean</code> (optional)
</li>
<li><code>path : String</code> (optional)
</li>
<li><code>postScore : boolean</code> (optional)
</li>
<li><code>projectPath : String</code> (optional)
</li>
<li><code>reviewConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>commentType</code> (optional)
<div><div>
 Posted review comments can be of one of the following types : 
 <ul>
  <li>Standard - The usual review comment that everyone use.</li>
  <li>Robot - Available since Gerrit 2.14. Review comment type to be used by robots. See <a href="https://gerrit-review.googlesource.com/Documentation/config-robot-comments.html" rel="nofollow">robot comment documentation</a> for more details.</li>
 </ul>
</div></div>

<ul><li><b>Values:</b> <code>STANDARD</code>, <code>ROBOT</code></li></ul></li>
<li><code>issueCommentTemplate : String</code> (optional)
<div><div>
 This text will appear as comment for a line with SonarQube issue in Gerrit review. 
 <br>
  There are some tags available: 
 <br>
 <br>
  * &lt;key&gt; - will be replaced with <b>issue key</b>; 
 <br>
  * &lt;component&gt; - will be replaced with <b>issue component info</b>; 
 <br>
  * &lt;message&gt; - will be replaced with <b>issue message</b>; 
 <br>
  * &lt;severity&gt; - will be replaced with <b>issue severity</b>; 
 <br>
  * &lt;rule&gt; - will be replaced with <b>issue rule name</b>; 
 <br>
  * &lt;rule_url&gt; - will be replaced with link to <b>rule description on SonarQube</b> if SonarQube URL is provided in SonarQube settings section or <b>rule name</b> if URL is not provided; 
 <br>
  * &lt;status&gt; - will be replaced with <b>issue status</b>; 
 <br>
  * &lt;creation_date&gt; - will be replaced with <b>issue creation date</b>. 
 <br>
 <br>
  Please note that only <b>filtered</b> by severity level issues and their counts will be shown in report.
</div></div>

</li>
<li><code>issueFilterConfig</code> (optional)
<div><div>
 Issue filter to specify issues to be <b>commented</b> in Gerrit
</div></div>

<ul><b>Nested Object</b>
<li><code>changedLinesOnly : boolean</code> (optional)
<div><div>
 Only <b>changed in current commit</b> lines to be commented by Gerrit when checked. Modified files to be commented with <b>all issues</b> if this control unchecked.
</div></div>

</li>
<li><code>excludedPathsGlobPattern : String</code> (optional)
</li>
<li><code>includedPathsGlobPattern : String</code> (optional)
</li>
<li><code>newIssuesOnly : boolean</code> (optional)
<div><div>
 Only <b>new</b> SonarQube issues to be commented in Gerrit when checked. Modified files to be commented with <b>all</b> corresponding issues when unchecked.
</div></div>

</li>
<li><code>severity : String</code> (optional)
<div><div>
 Minimum level of SonarQube severity to be reported to Gerrit.
</div></div>

</li>
</ul></li>
<li><code>noIssuesTitleTemplate : String</code> (optional)
<div><div>
 This text will appear as title of Gerrit review in case when <b>no issues matching filter settings</b> found. 
 <br>
  There are some tags available: 
 <br>
 <br>
  * &lt;info_count&gt; - will be replaced with count of issues having <b>INFO</b> severity level; 
 <br>
  * &lt;minor_count&gt; - will be replaced with count of issues having <b>MINOR</b> severity level; 
 <br>
  * &lt;major_count&gt; - will be replaced with count of issues having <b>MAJOR</b> severity level; 
 <br>
  * &lt;critical_count&gt; - will be replaced with count of issues having <b>CRITICAL</b> severity level; 
 <br>
  * &lt;blocker_count&gt; - will be replaced with count of issues having <b>BLOCKER</b> severity level; 
 <br>
  * &lt;min_minor_count&gt; - will be replaced with count of issues having <b>MINOR</b> severity level <b>or higher</b>; 
 <br>
  * &lt;min_major_count&gt; - will be replaced with count of issues having <b>MAJOR</b> severity level <b>or higher</b>; 
 <br>
  * &lt;min_critical_count&gt; - will be replaced with count of issues having <b>CRITICAL</b> severity level <b>or higher</b>; 
 <br>
  * &lt;total_count&gt; - will be replaced with <b>total count</b> of issues. 
 <br>
  Please note that only <b>filtered</b> by severity level issues and their counts will be shown in report.
</div></div>

</li>
<li><code>omitDuplicateComments : boolean</code> (optional)
</li>
<li><code>someIssuesTitleTemplate : String</code> (optional)
<div><div>
 This text will appear as title of Gerrit review in case when there are several issues matching filter settings found. 
 <br>
  There are some tags available: 
 <br>
 <br>
  * &lt;info_count&gt; - will be replaced with count of issues having <b>INFO</b> severity level; 
 <br>
  * &lt;minor_count&gt; - will be replaced with count of issues having <b>MINOR</b> severity level; 
 <br>
  * &lt;major_count&gt; - will be replaced with count of issues having <b>MAJOR</b> severity level; 
 <br>
  * &lt;critical_count&gt; - will be replaced with count of issues having <b>CRITICAL</b> severity level; 
 <br>
  * &lt;blocker_count&gt; - will be replaced with count of issues having <b>BLOCKER</b> severity level; 
 <br>
  * &lt;min_minor_count&gt; - will be replaced with count of issues having <b>MINOR</b> severity level <b>or higher</b>; 
 <br>
  * &lt;min_major_count&gt; - will be replaced with count of issues having <b>MAJOR</b> severity level <b>or higher</b>; 
 <br>
  * &lt;min_critical_count&gt; - will be replaced with count of issues having <b>CRITICAL</b> severity level <b>or higher</b>; 
 <br>
  * &lt;total_count&gt; - will be replaced with <b>total count</b> of issues. 
 <br>
  Please note that only <b>filtered</b> by severity level issues and their counts will be shown in report.
</div></div>

</li>
</ul></li>
<li><code>scoreConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>category : String</code> (optional)
<div><div>
 This field describes under what category score will appear in Gerrit. This category should match one of existent Gerrit categories.
</div></div>

</li>
<li><code>issueFilterConfig</code> (optional)
<div><div>
 Issue filter to specify issues to affect <b>score</b> in Gerrit
</div></div>

<ul><b>Nested Object</b>
<li><code>changedLinesOnly : boolean</code> (optional)
<div><div>
 Only <b>changed in current commit</b> lines to be commented by Gerrit when checked. Modified files to be commented with <b>all issues</b> if this control unchecked.
</div></div>

</li>
<li><code>excludedPathsGlobPattern : String</code> (optional)
</li>
<li><code>includedPathsGlobPattern : String</code> (optional)
</li>
<li><code>newIssuesOnly : boolean</code> (optional)
<div><div>
 Only <b>new</b> SonarQube issues to be commented in Gerrit when checked. Modified files to be commented with <b>all</b> corresponding issues when unchecked.
</div></div>

</li>
<li><code>severity : String</code> (optional)
<div><div>
 Minimum level of SonarQube severity to be reported to Gerrit.
</div></div>

</li>
</ul></li>
<li><code>issuesScore : int</code> (optional)
<div><div>
 Score to be posted to Gerrit in case when there are SonarQube violations found
</div></div>

</li>
<li><code>noIssuesScore : int</code> (optional)
<div><div>
 Score to be posted to Gerrit in case when there are no SonarQube violations found
</div></div>

</li>
</ul></li>
<li><code>severity : String</code> (optional)
</li>
<li><code>someIssuesToPostText : String</code> (optional)
</li>
<li><code>sonarURL : String</code> (optional)
</li>
<li><code>subJobConfigs</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>autoMatch : boolean</code> (optional)
</li>
<li><code>projectPath : String</code> (optional)
<div><div>
 Provides module prefix for a file path for multi-module projects
</div></div>

</li>
<li><code>sonarReportPath : String</code> (optional)
<div><div>
 Path to SonarQube report on Jenkins server. Default value is "target/sonar/sonar-report.json"
</div></div>

</li>
</ul></li>
</ul>


++++
