= Sonargraph Integration Jenkins Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/sonargraph-integration">Visit the Jenkins Plugins site</a>
++++


=== `SonargraphReport`: Sonargraph Integration Report Generation & Analysis
++++
<ul><li><code>activationCode : String</code> (optional)
<div><div>
 Sonargraph license activation code. If this parameter is not specified, you must specify a license file parameter.
</div></div>

</li>
<li><code>architectureViolationsAction : String</code> (optional)
</li>
<li><code>architectureWarningsAction : String</code> (optional)
</li>
<li><code>baselineReportPath : String</code> (optional)
<div><div>
 Optional: Enter the path to the baseline Sonargraph XML report file (without extension ".xml"). This path must be relative to the workspace.
</div></div>

</li>
<li><code>chartConfiguration : String</code> (optional)
</li>
<li><code>cyclicElementsAction : String</code> (optional)
</li>
<li><code>emptyWorkspaceAction : String</code> (optional)
</li>
<li><code>languageCPlusPlus : boolean</code> (optional)
<div><div>
 Select if your Sonargraph system uses C++.
</div></div>

</li>
<li><code>languageCSharp : boolean</code> (optional)
<div><div>
 Select if your Sonargraph system uses C#.
</div></div>

</li>
<li><code>languageJava : boolean</code> (optional)
<div><div>
 Select if your Sonargraph system uses Java.
</div></div>

</li>
<li><code>languagePython : boolean</code> (optional)
<div><div>
 Select if your Sonargraph system uses Python.
</div></div>

</li>
<li><code>licenseFile : String</code> (optional)
<div><div>
 Sonargraph license file location. If this parameter is not specified, you must specify the activation code parameter.
</div></div>

</li>
<li><code>logFile : String</code> (optional)
<div><div>
 Path of the log file to be used for SonargraphBuild (relative to the workspace). Default: sonargraph_build.log.
</div></div>

</li>
<li><code>logLevel : String</code> (optional)
<div><div>
 Level of logging detail. One of: off, error, warn, info, debug, trace, all. Default: info.
</div></div>

</li>
<li><code>metaDataFile : String</code> (optional)
</li>
<li><code>metrics</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>metricName : String</code>
</li>
<li><code>metricCategory : String</code>
</li>
</ul></li>
<li><code>qualityGateAction : String</code> (optional)
</li>
<li><code>qualityModelFile : String</code> (optional)
<div><div>
 Optional: Use a built-in Quality Model, or an external Quality Model instead of the Quality Model included in Sonargraph Software System. Must be either a file within workspace with extension "sgqm", or one of the built-in Quality Models 
 <ul>
  <li>Sonargraph:Default.sgqm (language-independent)</li>
  <li>Sonargraph:Java.sgqm (language-specific)</li>
  <li>Sonargraph:CSharp.sgqm (language-specific)</li>
  <li>Sonargraph:CPlusPlus.sgqm (language-specific)</li>
 </ul>
</div></div>

</li>
<li><code>reportGeneration : String</code> (optional)
</li>
<li><code>reportPath : String</code> (optional)
<div><div>
 Enter the path to the pre-generated Sonargraph XML report file (without extension ".xml"). This path must be relative to the workspace.
</div></div>

</li>
<li><code>skip : boolean</code> (optional)
<div><div>
 Skip Sonargraph Jenkins Plugin.
</div></div>

</li>
<li><code>snapshotDirectory : String</code> (optional)
<div><div>
 Target directory for the created snapshot. Only if either this parameter or snapshotFileName is provided, a snapshot will be generated. Parameter can only be used with Sonargraph Architect license.
</div></div>

</li>
<li><code>snapshotFileName : String</code> (optional)
<div><div>
 The target file name (without extension). Only if either this parameter or snapshotDirectory is provided, a snapshot will be generated. Parameter can only be used with Sonargraph Architect license.
</div></div>

</li>
<li><code>sonargraphBuildJDK : String</code> (optional)
</li>
<li><code>sonargraphBuildVersion : String</code> (optional)
</li>
<li><code>systemDirectory : String</code> (optional)
<div><div>
 Enter the path to the Sonargraph system (*.sonargraph) directory. This path must be relative to the workspace.
</div></div>

</li>
<li><code>thresholdViolationsAction : String</code> (optional)
</li>
<li><code>unassignedTypesAction : String</code> (optional)
</li>
<li><code>useHttpProxy : boolean</code> (optional)
<div><div>
 Use Jenkins proxy configuration when connecting to Sonargraph license server.
</div></div>

</li>
<li><code>virtualModel : String</code> (optional)
<div><div>
 The virtual model to be used when checking for issues. This parameter overrides the default virtual model that is set when the system is opened.
</div>
<div>
 <h3>Licensing</h3>
 <table>
  <tbody>
   <tr>
    <td>Sonargraph Explorer</td>
    <td>Changing virtual models is not supported, "Parser" model is taken.</td>
   </tr>
   <tr>
    <td>Sonargraph Architect</td>
    <td>Changing virtual models is supported, "Modifiable.vm" is taken by default.</td>
   </tr>
  </tbody>
 </table>
</div></div>

</li>
<li><code>workItemsAction : String</code> (optional)
</li>
<li><code>workspaceProfile : String</code> (optional)
<div><div>
 The profile file name (e.g. "BuildProfile.xml") for transforming the workspace paths to match the build environment.
</div></div>

</li>
<li><code>workspaceWarningsAction : String</code> (optional)
</li>
</ul>


++++
