= SSH Pipeline Steps
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/ssh-steps">Visit the Jenkins Plugins site</a>
++++


=== `sshCommand`: SSH Steps: sshCommand - Execute command on remote node.
++++
<div><div>
 <p>Takes a remote (map) of settings and <code>command</code> to execute it on the remote node and returns output. See docs on the <a href="https://github.com/jenkinsci/ssh-steps-plugin" rel="nofollow">README</a> for more information.</p>
 <p></p>
 <pre>    def remote = [:]
    remote.name = 'test'
    remote.host = 'test.domain.com'
    remote.user = 'root'
    remote.password = 'password'
    remote.allowAnyHosts = true
    stage('Remote SSH') {
      sshCommand remote: remote, command: "ls -lrt"
      sshCommand remote: remote, command: "for i in {1..5}; do echo -n \"Loop \$i \"; date ; sleep 1; done"
    }
  </pre>
</div></div>
<ul><li><code>command : String</code>
</li>
<li><code>dryRun : boolean</code> (optional)
</li>
<li><code>failOnError : boolean</code> (optional)
</li>
<li><code>remote</code> (optional)
<ul><b>Nested Choice of Objects</b>
</ul></li>
<li><code>sudo : boolean</code> (optional)
</li>
</ul>


++++
=== `sshGet`: SSH Steps: sshGet - Get a file/directory from remote node.
++++
<div><div>
 <p>Takes a remote (map) of settings, local file/directory <code>into</code> to get the given file/directory <code>from</code> remote node. See docs on the <a href="https://github.com/jenkinsci/ssh-steps-plugin" rel="nofollow">README</a> for more information.</p>
 <p></p>
 <pre>    def remote = [:]
    remote.name = 'test'
    remote.host = 'test.domain.com'
    remote.user = 'root'
    remote.password = 'password'
    remote.allowAnyHosts = true
    stage('Remote SSH') {
      sshGet remote: remote, from: 'abc.sh', into: 'abc_get.sh', override: true
    }
  </pre>
</div></div>
<ul><li><code>from : String</code>
</li>
<li><code>into : String</code>
</li>
<li><code>dryRun : boolean</code> (optional)
</li>
<li><code>failOnError : boolean</code> (optional)
</li>
<li><code>filterBy : String</code> (optional)
</li>
<li><code>filterRegex : String</code> (optional)
</li>
<li><code>override : boolean</code> (optional)
</li>
<li><code>remote</code> (optional)
<ul><b>Nested Choice of Objects</b>
</ul></li>
</ul>


++++
=== `sshPut`: SSH Steps: sshPut - Put a file/directory on remote node.
++++
<div><div>
 <p>Takes a remote (map) of settings, local file/directory <code>from</code> workspace and path to put this <code>into</code> remote node. See docs on the <a href="https://github.com/jenkinsci/ssh-steps-plugin" rel="nofollow">README</a> for more information.</p>
 <p></p>
 <pre>    def remote = [:]
    remote.name = 'test'
    remote.host = 'test.domain.com'
    remote.user = 'root'
    remote.password = 'password'
    remote.allowAnyHosts = true
    stage('Remote SSH') {
      writeFile file: 'abc.sh', text: 'ls -lrt'
      sshPut remote: remote, from: 'abc.sh', into: '.'
    }
  </pre>
</div></div>
<ul><li><code>from : String</code>
</li>
<li><code>into : String</code>
</li>
<li><code>dryRun : boolean</code> (optional)
</li>
<li><code>failOnError : boolean</code> (optional)
</li>
<li><code>filterBy : String</code> (optional)
</li>
<li><code>filterRegex : String</code> (optional)
</li>
<li><code>remote</code> (optional)
<ul><b>Nested Choice of Objects</b>
</ul></li>
</ul>


++++
=== `sshRemove`: SSH Steps: sshRemove - Remove a file/directory from remote node.
++++
<div><div>
 <p>Takes a remote (map) of settings and <code>path</code> (file/directory) to remove from remote node. See docs on the <a href="https://github.com/jenkinsci/ssh-steps-plugin" rel="nofollow">README</a> for more information.</p>
 <p></p>
 <pre>    def remote = [:]
    remote.name = 'test'
    remote.host = 'test.domain.com'
    remote.user = 'root'
    remote.password = 'password'
    remote.allowAnyHosts = true
    stage('Remote SSH') {
      sshRemove remote: remote, path: "abc.sh"
    }
  </pre>
</div></div>
<ul><li><code>path : String</code>
</li>
<li><code>dryRun : boolean</code> (optional)
</li>
<li><code>failOnError : boolean</code> (optional)
</li>
<li><code>remote</code> (optional)
<ul><b>Nested Choice of Objects</b>
</ul></li>
</ul>


++++
=== `sshScript`: SSH Steps: sshScript - Execute script(file) on remote node.
++++
<div><div>
 <p>Takes a remote (map) of settings and script a shell script file to execute it on the remote node and returns output. See docs on the <a href="https://github.com/jenkinsci/ssh-steps-plugin" rel="nofollow">README</a> for more information.</p>
 <p></p>
 <pre>    def remote = [:]
    remote.name = 'test'
    remote.host = 'test.domain.com'
    remote.user = 'root'
    remote.password = 'password'
    remote.allowAnyHosts = true
    stage('Remote SSH') {
      writeFile file: 'abc.sh', text: 'ls -lrt'
      sshScript remote: remote, script: "abc.sh"
    }
  </pre>
</div></div>
<ul><li><code>script : String</code>
</li>
<li><code>dryRun : boolean</code> (optional)
</li>
<li><code>failOnError : boolean</code> (optional)
</li>
<li><code>remote</code> (optional)
<ul><b>Nested Choice of Objects</b>
</ul></li>
</ul>


++++
