= SSH Agent Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/ssh-agent">Visit the Jenkins Plugins site</a>
++++


=== `sshagent`: SSH Agent
++++
<div><pre><code>
node {
  sshagent (credentials: ['deploy-dev']) {
    sh 'ssh -o StrictHostKeyChecking=no -l cloudbees 192.168.1.106 uname -a'
  }
}
</code></pre>
<p>Multiple credentials could be passed in the array but it is not supported using Snippet Generator.</p></div>
<ul><li><code>credentials : Array / List of String</code>
<div><div>
 List of credentials to be used by the <code>sshagent</code> step. The Pipeline Syntax Snippet Generator will guide the user to select a single credential from the list of available, like this: 
 <pre>sshagent(credentials: ['my-credential-id']) {
    // some block
}
</pre> The step also accepts a list of credentials, like this: 
 <pre>sshagent(credentials: ['my-credential-id', 'my-alternate-credential', 'another-credential']) {
    // some block
}
</pre>
</div></div>

<ul></ul></li>
<li><code>ignoreMissing : boolean</code> (optional)
<div><div>
 When set to <code>true</code>, any missing credentials will be ignored. When set to <code>false</code>, then the build fails if any of the required credentials cannot be resolved. Defaults to <code>false</code>.
</div></div>

</li>
</ul>


++++
