= Bitbucket Server Notifier
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/stashNotifier">Visit the Jenkins Plugins site</a>
++++


=== `notifyBitbucket`: Notify Bitbucket Instance
++++
<ul><li><code>buildName : String</code> (optional)
<div><div>
 If not empty, this will overwrite the default build name sent to Bitbucket.
</div></div>

</li>
<li><code>buildStatus : <code>Object</code></code> (optional)
<div><div>
 If not empty, this status will be sent to Bitbucket instead of the <code>currentBuild.result</code>.
</div></div>

</li>
<li><code>buildUrl : String</code> (optional)
</li>
<li><code>commitSha1 : String</code> (optional)
<div><div>
 Enter a 40-digit SHA1 commit id or a Jenkins variable prefixed with '$' (e. g. <em>$GIT_COMMIT</em>) when you want the notification to be attached to a specific commit in Bitbucket. If left empty, Jenkins will use the commit that was built by the Git plugin.
</div></div>

</li>
<li><code>considerUnstableAsSuccess : boolean</code> (optional)
<div><div>
 Consider unstable builds as success, besides the test errors.
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>disableInprogressNotification : boolean</code> (optional)
<div><div>
 Disable sending pre-build notification to Bitbucket
</div></div>

</li>
<li><code>ignoreUnverifiedSSLPeer : boolean</code> (optional)
<div>Check this if you need to connect by HTTPS to a Bitbucket server that uses an invalid or self-signed SSL certificate</div>

</li>
<li><code>includeBuildNumberInKey : boolean</code> (optional)
<div><div>
 <p>Check this if you want results of repeated builds of the same commit to show up in Bitbucket as a list of builds. If unchecked, Bitbucket will only display the latest build result.</p>
</div></div>

</li>
<li><code>prependParentProjectKey : boolean</code> (optional)
<div><div>
 Whether to prepend parent project while forming notify key
</div></div>

</li>
<li><code>projectKey : String</code> (optional)
<div><div>
 If not empty, this key will be used instead of automatically configured project key
</div></div>

</li>
<li><code>stashServerBaseUrl : String</code> (optional)
<div><div>
 The base URL of the Bitbucket server to notify. Examples are: 
 <ul>
  <li>http://localhost:7990, or</li>
  <li>http://my.company.intranet/bitbucket.</li>
 </ul>
</div></div>

</li>
</ul>


++++
