= StepCounter Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/stepcounter">Visit the Jenkins Plugins site</a>
++++


=== `stepcounter`: Count steps
++++
<div><div>
 Specify the file which measures the number of steps.
 <br>
  And specify these encoding and the category of a total unit.
 <br>
  If result output to file, specify file path and file format.
</div></div>
<ul><li><code>outputFile : String</code> (optional)
<div><div>
 If result output to file, specify file path and file format. (example 'dist/result.xls')。
 <br>
  The directory used as root is <a rel="nofollow">work space</a>.
</div></div>

</li>
<li><code>outputFormat : String</code> (optional)
</li>
<li><code>settings</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>encoding : String</code>
</li>
<li><code>filePattern : String</code>
<div><div>
 A wild card can be used for the candidate for a count (example 'module/dist/**/*.zip'). About an exact form, they are <a href="http://www.jajakarta.org/ant/ant-1.6.1/docs/en/manual/CoreTypes/fileset.html" rel="nofollow">. Please refer to an includes attribute (file set of Ant) </a>. The directory used as root is <a rel="nofollow">work space</a>.
</div></div>

</li>
<li><code>filePatternExclude : String</code>
<div><div>
 A wild card can be used for the object excepted from a count (example 'module/dist/**/*.zip'). About an exact form, they are <a href="http://www.jajakarta.org/ant/ant-1.6.1/docs/en/manual/CoreTypes/fileset.html" rel="nofollow"> Please refer to an excludes attribute (file set of Ant) </a>. The directory used as a standard is <a rel="nofollow">work space</a>.
</div></div>

</li>
<li><code>key : String</code>
<div><div>
 Specify the file type. It will be the counting unit of results. 
 <br>
  Please be configured in a range of [A-z][A-Z][0-9][-_].
</div></div>

</li>
</ul></li>
</ul>


++++
