= Sumologic Publisher
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/sumologic-publisher">Visit the Jenkins Plugins site</a>
++++


=== `SumoPipelineLogCollection`: SumoPipelineLogCollection
++++
<ul></ul>


++++
=== `SumoSDOEvent`: Upload Events specific to Software Delivery Optimization Solution to Sumo Logic.
++++
<ul><li><code>eventType : String</code> (optional)
</li>
<li><code>fields</code> (optional)
<ul><li><b>Type:</b> <code>java.util.HashMap&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>keyValueMap</code> (optional)
<ul><li><b>Type:</b> <code>java.util.HashMap&lt;java.lang.String, java.lang.Object&gt;</code></li>
</ul></li>
</ul>


++++
=== `SumoUpload`: Upload files or Text to Sumo Logic HTTP source as provided in Sumo Logic Publisher Configuration.
++++
<ul><li><code>excludePathPattern : String</code> (optional)
</li>
<li><code>fields</code> (optional)
<ul><li><b>Type:</b> <code>java.util.HashMap&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>file : String</code> (optional)
</li>
<li><code>includePathPattern : String</code> (optional)
</li>
<li><code>keyValueMap</code> (optional)
<ul><li><b>Type:</b> <code>java.util.HashMap&lt;java.lang.String, java.lang.Object&gt;</code></li>
</ul></li>
<li><code>text : String</code> (optional)
</li>
<li><code>workingDir : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'SumoBuildNotifier'])`: Sumo Logic build logger
++++
<ul></ul>


++++
