= Seapine Surround SCM Plug-in
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/Surround-SCM-plugin">Visit the Jenkins Plugins site</a>
++++


=== `sscm`: Surround SCM
++++
<ul><li><code>url : String</code>
<div><div>
 Enter the Surround SCM URL for the repository to retrieve.
 <br>
  Example: sscm://ServerAddress:4900//BranchName//Mainline/Path/To/Repository
</div></div>

</li>
<li><code>credentialsId : String</code>
</li>
<li><code>changelog : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in changelog': 
 <p>If 'Include in changelog' is enabled for an SCM source, then when a build occurs, the changes from that SCM source will be included in the changelog.</p>
 <p>If 'Include in changelog' is disabled, then when a build occurs, the changes from this SCM source will not be included in the changelog.</p>
</div></div>

</li>
<li><code>poll : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in polling' 
 <p>If 'Include in polling' is enabled or 'Include in changelog' is enabled, then when polling occurs, the job will be started if changes are detected from this SCM source.</p>
 <p>If 'Include in polling' is disabled and 'Include in changelog' is disabled, then when polling occurs, changes that are detected from this repository will be ignored.</p>
</div></div>

</li>
<li><code>rsaKey</code> (optional)
<ul><b>Nested Object</b>
<li><code>rsaKeyFileId : String</code> (optional)
</li>
<li><code>rsaKeyFilePath : String</code> (optional)
</li>
<li><code>rsaKeyType</code> (optional)
<ul><li><b>Values:</b> <code>NoKey</code>, <code>Path</code>, <code>ID</code></li></ul></li>
<li><code>rsaKeyValue : String</code> (optional)
</li>
</ul></li>
<li><code>rsaKeyFileId : String</code> (optional)
</li>
<li><code>rsaKeyFilePath : String</code> (optional)
<div><div>
 Enter the full path to the RSA key file for the Surround SCM connection. Example: C:\SurroundRSAKeyFile.xml
</div></div>

</li>
</ul>


++++
