= Synopsys Security Scan
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/synopsys-security-scan">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'SecurityScanFreestyle'])`: Synopsys Security Scan
++++
<ul><li><code>bitbucket_token : String</code> (optional)
</li>
<li><code>blackduck_automation_prcomment : boolean</code> (optional)
<div><div>
 Add automatic pull request comment based on Black Duck scan result. Supported values: <code>true</code> or <code>false</code>
</div></div>

</li>
<li><code>blackduck_download_url : String</code> (optional)
<div><div>
 Specify Black Duck download URL
</div></div>

</li>
<li><code>blackduck_install_directory : String</code> (optional)
</li>
<li><code>blackduck_reports_sarif_create : boolean</code> (optional)
<div><div>
 SARIF report will be uploaded as a Jenkins Archive Artifact.
</div></div>

</li>
<li><code>blackduck_reports_sarif_file_path : String</code> (optional)
<div><div>
 File path (including file name) where SARIF report is created.
</div></div>

</li>
<li><code>blackduck_reports_sarif_groupSCAIssues : boolean</code> (optional)
<div><div>
 Uncheck this to disable grouping by component and list SCA issues by vulnerability.
</div></div>

</li>
<li><code>blackduck_reports_sarif_severities : String</code> (optional)
<div><div>
 Comma separated list of issue severities to include in SARIF report. Supported values: <code>CRITICAL,HIGH,MEDIUM,LOW</code>
</div></div>

</li>
<li><code>blackduck_scan_failure_severities : String</code> (optional)
<div><div>
 Specify scan failure severities of Black Duck. Supported values: <code>ALL</code>, <code>NONE</code>, <code>BLOCKER</code>, <code>CRITICAL</code>, <code>MAJOR</code>, <code>MINOR</code>, <code>OK</code>, <code>TRIVIAL</code>, <code>UNSPECIFIED</code>
</div></div>

</li>
<li><code>blackduck_scan_full : boolean</code> (optional)
<div><div>
 Specifies whether full scan is required or not. Supported values: <code>true</code> or <code>false</code>
</div></div>

</li>
<li><code>blackduck_token : String</code> (optional)
</li>
<li><code>blackduck_url : String</code> (optional)
</li>
<li><code>coverity_automation_prcomment : boolean</code> (optional)
<div><div>
 Coverity security testing as pull request comment. Supported values: <code>true</code> or <code>false</code>
</div></div>

</li>
<li><code>coverity_install_directory : String</code> (optional)
</li>
<li><code>coverity_local : boolean</code> (optional)
<div><div>
 Coverity Local Analysis. Supported values: <code>true</code> or <code>false</code>
</div></div>

</li>
<li><code>coverity_passphrase : String</code> (optional)
</li>
<li><code>coverity_policy_view : String</code> (optional)
<div><div>
 ID number/Name of a saved view to apply as a <b>'break the build'</b> policy
</div></div>

</li>
<li><code>coverity_project_name : String</code> (optional)
<div><div>
 The project name in Coverity is optional for <b>multi-branch pipeline</b> jobs, but it is mandatory for <b>freestyle</b> and <b>pipeline</b> jobs.
</div></div>

</li>
<li><code>coverity_stream_name : String</code> (optional)
<div><div>
 The stream name in Coverity is optional for <b>multi-branch pipeline</b> jobs, but it is mandatory for <b>freestyle</b> and <b>pipeline</b> jobs.
</div></div>

</li>
<li><code>coverity_url : String</code> (optional)
</li>
<li><code>coverity_user : String</code> (optional)
</li>
<li><code>coverity_version : String</code> (optional)
<div><div>
 Specific Coverity version to download, rather than opting for the latest version
</div></div>

</li>
<li><code>github_token : String</code> (optional)
</li>
<li><code>gitlab_token : String</code> (optional)
</li>
<li><code>include_diagnostics : boolean</code> (optional)
<div><div>
 Bridge diagnostics will be uploaded in Jenkins Archive Artifact. Supported values: <code>true</code> or <code>false</code>
</div></div>

</li>
<li><code>network_airgap : boolean</code> (optional)
<div><div>
 Network airgap. Supported values: <code>true</code> or <code>false</code>
</div></div>

</li>
<li><code>polaris_access_token : String</code> (optional)
</li>
<li><code>polaris_application_name : String</code> (optional)
<div><div>
 Application name created in the Polaris server
</div></div>

</li>
<li><code>polaris_assessment_types : String</code> (optional)
<div><div>
 Polaris assessment types. Supported values: <code>SCA</code> or <code>SAST</code> or both <code>SCA, SAST</code>
</div></div>

</li>
<li><code>polaris_branch_name : String</code> (optional)
<div><div>
 Branch name in the Polaris Server
</div></div>

</li>
<li><code>polaris_project_name : String</code> (optional)
<div><div>
 Project name created in the Polaris server
</div></div>

</li>
<li><code>polaris_reports_sarif_create : boolean</code> (optional)
<div><div>
 SARIF report will be uploaded as a Jenkins Archive Artifact.
</div></div>

</li>
<li><code>polaris_reports_sarif_file_path : String</code> (optional)
<div><div>
 File path (including file name) where SARIF report is created.
</div></div>

</li>
<li><code>polaris_reports_sarif_groupSCAIssues : boolean</code> (optional)
<div><div>
 Uncheck this to disable grouping by component and list SCA issues by vulnerability.
</div></div>

</li>
<li><code>polaris_reports_sarif_issue_types : String</code> (optional)
<div><div>
 Comma separated list of issues types to include in SARIF report. Supported values: <code>SAST</code>, <code>SCA</code>
</div></div>

</li>
<li><code>polaris_reports_sarif_severities : String</code> (optional)
<div><div>
 Comma separated list of issue severities to include in SARIF report. Supported values: <code>CRITICAL,HIGH,MEDIUM,LOW</code>
</div></div>

</li>
<li><code>polaris_server_url : String</code> (optional)
</li>
<li><code>polaris_triage : String</code> (optional)
<div><div>
 Polaris Triage. Supported values: <code>REQUIRED</code> or <code>NOT_REQUIRED</code> or <code>NOT_ENTITLED</code>
</div></div>

</li>
<li><code>product : String</code> (optional)
<div><div>
 Please select the synopsys security product. Supported products are <b>Black Duck</b>, <b>Coverity</b> and <b>Polaris</b>
</div></div>

</li>
<li><code>return_status : boolean</code> (optional)
</li>
<li><code>synopsys_bridge_download_url : String</code> (optional)
</li>
<li><code>synopsys_bridge_download_version : String</code> (optional)
</li>
<li><code>synopsys_bridge_install_directory : String</code> (optional)
</li>
</ul>


++++
=== `synopsys_scan`: Synopsys Security Scan
++++
<ul><li><code>bitbucket_token : String</code> (optional)
</li>
<li><code>blackduck_automation_prcomment : boolean</code> (optional)
<div><div>
 Add automatic pull request comment based on Black Duck scan result. Supported values: <code>true</code> or <code>false</code>
</div></div>

</li>
<li><code>blackduck_download_url : String</code> (optional)
<div><div>
 Specify Black Duck download URL
</div></div>

</li>
<li><code>blackduck_install_directory : String</code> (optional)
</li>
<li><code>blackduck_reports_sarif_create : boolean</code> (optional)
<div><div>
 SARIF report will be uploaded as a Jenkins Archive Artifact.
</div></div>

</li>
<li><code>blackduck_reports_sarif_file_path : String</code> (optional)
<div><div>
 File path (including file name) where SARIF report is created.
</div></div>

</li>
<li><code>blackduck_reports_sarif_groupSCAIssues : boolean</code> (optional)
<div><div>
 Uncheck this to disable grouping by component and list SCA issues by vulnerability.
</div></div>

</li>
<li><code>blackduck_reports_sarif_severities : String</code> (optional)
<div><div>
 Comma separated list of issue severities to include in SARIF report. Supported values: <code>CRITICAL,HIGH,MEDIUM,LOW</code>
</div></div>

</li>
<li><code>blackduck_scan_failure_severities : String</code> (optional)
<div><div>
 Specify scan failure severities of Black Duck. Supported values: <code>ALL</code>, <code>NONE</code>, <code>BLOCKER</code>, <code>CRITICAL</code>, <code>MAJOR</code>, <code>MINOR</code>, <code>OK</code>, <code>TRIVIAL</code>, <code>UNSPECIFIED</code>
</div></div>

</li>
<li><code>blackduck_scan_full : boolean</code> (optional)
<div><div>
 Specifies whether full scan is required or not. Supported values: <code>true</code> or <code>false</code>
</div></div>

</li>
<li><code>blackduck_token : String</code> (optional)
</li>
<li><code>blackduck_url : String</code> (optional)
</li>
<li><code>coverity_automation_prcomment : boolean</code> (optional)
<div><div>
 Coverity security testing as pull request comment. Supported values: <code>true</code> or <code>false</code>
</div></div>

</li>
<li><code>coverity_install_directory : String</code> (optional)
</li>
<li><code>coverity_local : boolean</code> (optional)
<div><div>
 Coverity Local Analysis. Supported values: <code>true</code> or <code>false</code>
</div></div>

</li>
<li><code>coverity_passphrase : String</code> (optional)
</li>
<li><code>coverity_policy_view : String</code> (optional)
<div><div>
 ID number/Name of a saved view to apply as a <b>'break the build'</b> policy
</div></div>

</li>
<li><code>coverity_project_name : String</code> (optional)
<div><div>
 The project name in Coverity is optional for <b>multi-branch pipeline</b> jobs, but it is mandatory for <b>freestyle</b> and <b>pipeline</b> jobs.
</div></div>

</li>
<li><code>coverity_stream_name : String</code> (optional)
<div><div>
 The stream name in Coverity is optional for <b>multi-branch pipeline</b> jobs, but it is mandatory for <b>freestyle</b> and <b>pipeline</b> jobs.
</div></div>

</li>
<li><code>coverity_url : String</code> (optional)
</li>
<li><code>coverity_user : String</code> (optional)
</li>
<li><code>coverity_version : String</code> (optional)
<div><div>
 Specific Coverity version to download, rather than opting for the latest version
</div></div>

</li>
<li><code>github_token : String</code> (optional)
</li>
<li><code>gitlab_token : String</code> (optional)
</li>
<li><code>include_diagnostics : boolean</code> (optional)
<div><div>
 Bridge diagnostics will be uploaded in Jenkins Archive Artifact. Supported values: <code>true</code> or <code>false</code>
</div></div>

</li>
<li><code>network_airgap : boolean</code> (optional)
<div><div>
 Network airgap. Supported values: <code>true</code> or <code>false</code>
</div></div>

</li>
<li><code>polaris_access_token : String</code> (optional)
</li>
<li><code>polaris_application_name : String</code> (optional)
<div><div>
 Application name created in the Polaris server
</div></div>

</li>
<li><code>polaris_assessment_types : String</code> (optional)
<div><div>
 Polaris assessment types. Supported values: <code>SCA</code> or <code>SAST</code> or both <code>SCA, SAST</code>
</div></div>

</li>
<li><code>polaris_branch_name : String</code> (optional)
<div><div>
 Branch name in the Polaris Server
</div></div>

</li>
<li><code>polaris_project_name : String</code> (optional)
<div><div>
 Project name created in the Polaris server
</div></div>

</li>
<li><code>polaris_reports_sarif_create : boolean</code> (optional)
<div><div>
 SARIF report will be uploaded as a Jenkins Archive Artifact.
</div></div>

</li>
<li><code>polaris_reports_sarif_file_path : String</code> (optional)
<div><div>
 File path (including file name) where SARIF report is created.
</div></div>

</li>
<li><code>polaris_reports_sarif_groupSCAIssues : boolean</code> (optional)
<div><div>
 Uncheck this to disable grouping by component and list SCA issues by vulnerability.
</div></div>

</li>
<li><code>polaris_reports_sarif_issue_types : String</code> (optional)
<div><div>
 Comma separated list of issues types to include in SARIF report. Supported values: <code>SAST</code>, <code>SCA</code>
</div></div>

</li>
<li><code>polaris_reports_sarif_severities : String</code> (optional)
<div><div>
 Comma separated list of issue severities to include in SARIF report. Supported values: <code>CRITICAL,HIGH,MEDIUM,LOW</code>
</div></div>

</li>
<li><code>polaris_server_url : String</code> (optional)
</li>
<li><code>polaris_triage : String</code> (optional)
<div><div>
 Polaris Triage. Supported values: <code>REQUIRED</code> or <code>NOT_REQUIRED</code> or <code>NOT_ENTITLED</code>
</div></div>

</li>
<li><code>product : String</code> (optional)
<div><div>
 Please select the synopsys security product. Supported products are <b>Black Duck</b>, <b>Coverity</b> and <b>Polaris</b>
</div></div>

</li>
<li><code>return_status : boolean</code> (optional)
<div><div>
 If true (checked), returns the status code of the Synopsys Security Scan instead of failing the workflow. Supported values: <code>true</code> or <code>false</code>
</div></div>

</li>
<li><code>synopsys_bridge_download_url : String</code> (optional)
</li>
<li><code>synopsys_bridge_download_version : String</code> (optional)
</li>
<li><code>synopsys_bridge_install_directory : String</code> (optional)
</li>
</ul>


++++
