= Synopsys Coverity on Polaris
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/synopsys-polaris">Visit the Jenkins Plugins site</a>
++++


=== `polaris`: Execute Coverity on Polaris CLI
++++
<ul><li><code>arguments : String</code>
<div><div>
 <p>The command line arguments to pass to the Polaris CLI</p>
</div></div>

</li>
<li><code>createChangeSetFile</code> (optional)
<div><div>
 <p>Creates a file at $CHANGE_SET_FILE_PATH (by default, the workspace directory) containing a list of files generated from the Jenkins-provided SCM changeset.<br>
   Used for Incremental analysis (--incremental) as the file containing the list of changed files for analysis.</p>
</div></div>

<ul><b>Nested Object</b>
<li><code>excluding : String</code> (optional)
<div><div>
 <p>Specify a comma separated list of filename patterns that you would like to explicitly excluded from the Jenkins-provided SCM changeset.<br>
   The pattern is applied to determine which files will be populated in the changeset file, stored at $CHANGE_SET_FILE_PATH.<br>
   If blank, will exclude none.<br>
   Examples:</p>
 <table>
  <thead>
   <tr>
    <th>File Name</th>
    <th>Pattern</th>
    <th>Will be excluded</th>
   </tr>
  </thead>
  <tbody>
   <tr>
    <td>test.java</td>
    <td>*.java</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>test.java</td>
    <td>*.jpg</td>
    <td>No</td>
   </tr>
   <tr>
    <td>test.java</td>
    <td>test.*</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>test.java</td>
    <td>test.????</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>test.java</td>
    <td>test.?????</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div></div>

</li>
<li><code>including : String</code> (optional)
<div><div>
 <p>Specify a comma separated list of filename patterns that you would like to explicitly included from the Jenkins-provided SCM changeset.<br>
   The pattern is applied to determine which files will be populated in the changeset file, stored at $CHANGE_SET_FILE_PATH.<br>
   If blank, will include all. Examples:</p>
 <table>
  <thead>
   <tr>
    <th>File Name</th>
    <th>Pattern</th>
    <th>Will be included</th>
   </tr>
  </thead>
  <tbody>
   <tr>
    <td>test.java</td>
    <td>*.java</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>test.java</td>
    <td>*.jpg</td>
    <td>No</td>
   </tr>
   <tr>
    <td>test.java</td>
    <td>test.*</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>test.java</td>
    <td>test.????</td>
    <td>Yes</td>
   </tr>
   <tr>
    <td>test.java</td>
    <td>test.?????</td>
    <td>No</td>
   </tr>
  </tbody>
 </table>
</div></div>

</li>
<li><code>returnSkipCode : boolean</code> (optional)
<div><div>
 <p>If true (checked), returns -1 instead of throwing a IntegrationAbortException when static analysis is skipped because the changeset contained no files to analyze.</p>
</div></div>

</li>
</ul></li>
<li><code>polarisCli : String</code> (optional)
<div><div>
 <p>The Coverity on Polaris CLI installation to execute</p>
</div></div>

</li>
<li><code>returnStatus : boolean</code> (optional)
<div><div>
 <p>If true (checked), returns the status code of the Coverity on Polaris CLI run instead of throwing an exception</p>
</div></div>

</li>
</ul>


++++
=== `polarisIssueCheck`: Check for issues in the Coverity on Polaris found by a previous execution of the CLI
++++
<ul><li><code>jobTimeoutInMinutes : int</code> (optional)
<div><div>
 <p>The maximum number of minutes to wait for jobs started by the Coverity on Polaris CLI to complete when executed without -w (nonblocking mode). Must be a positive integer, defaults to 30 minutes.</p>
</div></div>

</li>
<li><code>returnIssueCount : boolean</code> (optional)
<div><div>
 <p>Check this box to return the issue count as an integer instead of throwing an exception</p>
</div></div>

</li>
</ul>


++++
