= Sysdig Secure Container Image Scanner Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/sysdig-secure">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'NewEngineBuilder'])`: Sysdig Image Scanning
++++
<ul><li><code>imageName : String</code>
</li>
<li><code>bailOnFail : boolean</code> (optional)
</li>
<li><code>bailOnPluginFail : boolean</code> (optional)
</li>
<li><code>cliVersionToApply : String</code> (optional)
</li>
<li><code>customCliVersion : String</code> (optional)
</li>
<li><code>engineCredentialsId : String</code> (optional)
</li>
<li><code>engineURL : String</code> (optional)
</li>
<li><code>engineVerify : boolean</code> (optional)
</li>
<li><code>inlineScanExtraParams : String</code> (optional)
</li>
<li><code>policiesToApply : String</code> (optional)
</li>
<li><code>scannerBinaryPath : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'SysdigBuilder'])`: Sysdig Secure Container Image Scanner (Legacy)
++++
<ul><li><code>name : String</code>
</li>
<li><code>bailOnFail : boolean</code> (optional)
</li>
<li><code>bailOnPluginFail : boolean</code> (optional)
</li>
<li><code>engineCredentialsId : String</code> (optional)
</li>
<li><code>engineurl : String</code> (optional)
</li>
<li><code>engineverify : boolean</code> (optional)
</li>
<li><code>forceScan : boolean</code> (optional)
</li>
<li><code>inlineScanExtraParams : String</code> (optional)
</li>
<li><code>inlineScanning : boolean</code> (optional)
</li>
<li><code>runAsUser : String</code> (optional)
</li>
</ul>


++++
=== `sysdig`: Sysdig Secure Container Image Scanner pipeline step (Legacy)
++++
<ul><li><code>name : String</code>
</li>
<li><code>bailOnFail : boolean</code> (optional)
</li>
<li><code>bailOnPluginFail : boolean</code> (optional)
</li>
<li><code>engineCredentialsId : String</code> (optional)
</li>
<li><code>engineurl : String</code> (optional)
</li>
<li><code>engineverify : boolean</code> (optional)
</li>
<li><code>forceScan : boolean</code> (optional)
</li>
<li><code>inlineScanExtraParams : String</code> (optional)
</li>
<li><code>inlineScanning : boolean</code> (optional)
</li>
<li><code>runAsUser : String</code> (optional)
</li>
</ul>


++++
=== `sysdigImageScan`: Sysdig Image Scanning pipeline step
++++
<ul><li><code>imageName : String</code>
</li>
<li><code>bailOnFail : boolean</code> (optional)
</li>
<li><code>bailOnPluginFail : boolean</code> (optional)
</li>
<li><code>cliVersionToApply : String</code> (optional)
</li>
<li><code>customCliVersion : String</code> (optional)
</li>
<li><code>engineCredentialsId : String</code> (optional)
</li>
<li><code>engineURL : String</code> (optional)
</li>
<li><code>engineVerify : boolean</code> (optional)
</li>
<li><code>inlineScanExtraParams : String</code> (optional)
</li>
<li><code>policiesToApply : String</code> (optional)
</li>
<li><code>scannerBinaryPath : String</code> (optional)
</li>
</ul>


++++
