= Team Concert Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/teamconcert">Visit the Jenkins Plugins site</a>
++++


=== `rtcBuild`: Step for interacting with EWM (RTC) Build
++++
<ul><li><code>task</code>
<div><div>
 <h3>Request Build</h3>
 <p>Request a EWM (RTC) build from the Jenkins pipeline. When a request is successfully created, the step returns the build result UUID in the property "buildResultUUID".</p>
 <br>
</div>
<div>
 <h3>Wait for Build</h3>
 <p>Wait for a EWM (RTC) build result to attain a specific state. Default states to wait for are COMPLETED and INCOMPLETE. If a timeout period is provided, then the task does not return until the specified state is reached or the time period expires. By default, the task will wait indefinitely till the build result reaches the specified states.</p>
 <br>
</div>
<div>
 <h3>List Logs</h3>
 <p>Retrieve the details of the one or more logs from an EWM (RTC) build result. Logs appear in the "Logs" tab of the EWM build result. This task will retrieve the details of the logs whose content is stored in the EWM repository.</p>
 <br>
</div>
<div>
 <h3>List Artifacts</h3>
 <p>Retrieve the details of the artifacts from an EWM (RTC) build result. Artifacts appear in the "Downloads" tab of the EWM build result. This task will retrieve the details of the artifacts whose content is stored in the EWM repository.</p>
 <br>
</div>
<div>
 <h3>Download Log</h3>
 <p>Download a log from an EWM (RTC) build result. You can download a log using the log’s name or content ID. To retrieve the name or contentId of the log, use the "List Logs" task.</p>
 <br>
</div>
<div>
 <h3>Download Artifact</h3>
 <p>Download an artifact from an EWM (RTC) build result. You can download an artifact using the artifact's name or content ID. To retrieve the name or contentId of the artifact, use the "List Artifacts" task.</p>
 <br>
</div>
<div>
 <h3>Get SCM Snapshot from Build</h3>
 <p>Retrieve the Jazz SCM snapshot details for a given EWM (RTC) build result. If the build result has a Jazz SCM snapshot contribution, then the task returns the snapshot's name and UUID. If the build result does not have such a contribution, then the task returns empty values for snapshot name and UUID.</p>
</div></div>

<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>addOrOverrideProperties : boolean</code> (optional)
</li>
<li><code>buildDefinitionId : String</code> (optional)
</li>
<li><code>buildResultUUID : String</code> (optional)
</li>
<li><code>buildStates : String</code> (optional)
</li>
<li><code>componentName : String</code> (optional)
</li>
<li><code>contentId : String</code> (optional)
</li>
<li><code>deleteProperties : boolean</code> (optional)
</li>
<li><code>destinationFileName : String</code> (optional)
</li>
<li><code>fileName : String</code> (optional)
</li>
<li><code>fileNameOrPattern : String</code> (optional)
</li>
<li><code>linkEWMBuild : boolean</code> (optional)
</li>
<li><code>maxResults : int</code> (optional)
</li>
<li><code>propertiesToAddOrOverride</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>propertyName : String</code> (optional)
</li>
<li><code>propertyValue : String</code> (optional)
</li>
</ul></li>
<li><code>propertiesToDelete</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>propertyName : String</code> (optional)
</li>
<li><code>propertyValue : String</code> (optional)
</li>
</ul></li>
<li><code>waitBuildInterval : long</code> (optional)
</li>
<li><code>waitBuildTimeout : int</code> (optional)
</li>
</ul></li>
<li><code>taskName : String</code>
</li>
<li><code>buildTool : String</code> (optional)
<div><div>
 <p>The RTC build toolkit to use when running the tasks. The toolkits available are defined in the system configuration (with the other tools like Ant and Java). If the task is run in an agent, then the build toolkit should be available in the agent, either at the same location as the master build toolkit or an overridden location of your choice.</p>
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 <p>Credentials for the build user. Make sure a name and password credential for the Jazz Repository should be configured.</p>
</div></div>

</li>
<li><code>serverURI : String</code> (optional)
<div><div>
 <p>The Jazz Repository connection URI for the EWM (RTC) server.</p>
</div></div>

</li>
<li><code>timeout : int</code> (optional)
<div><div>
 <p>The timeout period in seconds for establishing a connection to the Jazz repository when running this step. Default value is 120 seconds.</p>
</div></div>

</li>
</ul>


++++
=== `step([$class: 'RTCPostBuildDeliverPublisher'])`: RTC Post Build Deliver 
++++
<div><div>
 <p>Perform post build deliver for Rational Team Concert(RTC) SCM configuration in the Jenkins build.</p>
 <p>In a Pipeline job where RTC SCM can be called multiple times, post build deliver will be attempted for each invocation of RTC SCM.</p>
 <p>Currently, post build deliver is performed only if a build definition is used as the build configuration. The step uses the post build deliver configuration information from the build definition.</p>
</div></div>
<ul><li><code>failOnError : boolean</code>
<div><div>
 <p>If post build deliver operation fails, set the build's status to FAILURE.</p>
</div></div>

</li>
</ul>


++++
=== `teamconcert`: Team Concert
++++
<ul><li><code>buildType</code>
<ul><b>Nested Object</b>
<li><code>value : String</code>
</li>
<li><code>buildDefinition : String</code>
</li>
<li><code>buildWorkspace : String</code>
</li>
<li><code>buildSnapshot : String</code>
</li>
<li><code>buildStream : String</code>
</li>
<li><code>acceptBeforeLoad : boolean</code> (optional)
</li>
<li><code>addLinksToWorkItems : boolean</code> (optional)
</li>
<li><code>buildSnapshotContext</code> (optional)
<ul><b>Nested Object</b>
<li><code>snapshotOwnerType : String</code>
</li>
<li><code>processAreaOfOwningStream : String</code>
</li>
<li><code>owningStream : String</code>
</li>
<li><code>owningWorkspace : String</code>
</li>
</ul></li>
<li><code>clearLoadDirectory : boolean</code> (optional)
</li>
<li><code>componentLoadConfig : String</code> (optional)
</li>
<li><code>componentsToExclude : String</code> (optional)
</li>
<li><code>createFoldersForComponents : boolean</code> (optional)
</li>
<li><code>currentSnapshotOwnerType : String</code> (optional)
</li>
<li><code>customizedSnapshotName : String</code> (optional)
</li>
<li><code>generateChangelogWithGoodBuild : boolean</code> (optional)
</li>
<li><code>loadDirectory : String</code> (optional)
</li>
<li><code>loadPolicy : String</code> (optional)
</li>
<li><code>overrideDefaultSnapshotName : boolean</code> (optional)
</li>
<li><code>pathToLoadRuleFile : String</code> (optional)
</li>
<li><code>pollingOnly : boolean</code> (optional)
</li>
<li><code>pollingOnlyData</code> (optional)
<ul><b>Nested Object</b>
<li><code>snapshotUUID : String</code>
</li>
</ul></li>
<li><code>processArea : String</code> (optional)
</li>
<li><code>useDynamicLoadRules : boolean</code> (optional)
</li>
</ul></li>
<li><code>changelog : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in changelog': 
 <p>If 'Include in changelog' is enabled for an SCM source, then when a build occurs, the changes from that SCM source will be included in the changelog.</p>
 <p>If 'Include in changelog' is disabled, then when a build occurs, the changes from this SCM source will not be included in the changelog.</p>
</div></div>

</li>
<li><code>overrideConfig</code> (optional)
<ul><b>Nested Object</b>
<li><code>serverURI : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>buildTool : String</code>
</li>
<li><code>avoidUsingToolkit : boolean</code> (optional)
</li>
<li><code>serverUri : String</code> (optional)
</li>
<li><code>timeout : int</code> (optional)
</li>
</ul></li>
<li><code>poll : boolean</code> (optional)
<div><div>
 Enable or Disable 'Include in polling' 
 <p>If 'Include in polling' is enabled or 'Include in changelog' is enabled, then when polling occurs, the job will be started if changes are detected from this SCM source.</p>
 <p>If 'Include in polling' is disabled and 'Include in changelog' is disabled, then when polling occurs, changes that are detected from this repository will be ignored.</p>
</div></div>

</li>
</ul>


++++
