= Test Results Aggregator Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/test-results-aggregator">Visit the Jenkins Plugins site</a>
++++


=== `testResultsAggregator`: Aggregate Test Results
++++
<ul><li><code>jobs</code>
<ul><b>Array / List of Nested Object</b>
<li><code>groupName : String</code> (optional)
</li>
<li><code>jobFriendlyName : String</code> (optional)
</li>
<li><code>jobName : String</code> (optional)
</li>
</ul></li>
<li><code>influxdbUrl : String</code>
</li>
<li><code>influxdbToken : String</code>
</li>
<li><code>influxdbBucket : String</code>
</li>
<li><code>influxdbOrg : String</code>
</li>
<li><code>subject : String</code> (optional)
<div><div>
 Mail Subject prefix. Supports also job &amp; env variables.
</div></div>

</li>
<li><code>recipientsList : String</code> (optional)
<div><div>
 Comma separated recipients list , ex : nick@some.com,mairy@some.com
 <br>
  If empty or blank no email will be triggered. Supports also job variables.
</div></div>

</li>
<li><code>recipientsListCC : String</code> (optional)
</li>
<li><code>recipientsListBCC : String</code> (optional)
</li>
<li><code>recipientsListIgnored : String</code> (optional)
</li>
<li><code>outOfDateResults : String</code> (optional)
<div><div>
 Completed Jenkins Jobs with results more than X hours ago will be marked with 'red' color under 'Last Run' column report.
 <br>
  Otherwise if blank or empty then column 'Last Run' will just have the timestamp of job completion.
</div></div>

</li>
<li><code>data</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>groupName : String</code> (optional)
</li>
<li><code>jobs</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>jobFriendlyName : String</code> (optional)
</li>
<li><code>jobName : String</code> (optional)
</li>
</ul></li>
<li><code>reportGroup</code> (optional)
<ul><li><b>Type:</b> <code>class com.jenkins.testresultsaggregator.data.ReportGroup</code></li>
</ul></li>
</ul></li>
<li><code>beforebody : String</code> (optional)
<div><div>
 Text Before mail body. Static text or HTML code. Supports also job &amp; env variables , for example ${WORKSPACE} or ${myVariable}
</div></div>

</li>
<li><code>afterbody : String</code> (optional)
<div><div>
 Text Before mail body. Static text or HTML code. Supports also job &amp; env variables , for example ${WORKSPACE} or ${myVariable}
</div></div>

</li>
<li><code>theme : String</code> (optional)
<div><div>
 Mail theme
</div></div>

</li>
<li><code>sortresults : String</code> (optional)
<div><div>
 Sort Results using one of the following available options. If there are Groups then sorting refers to jobs inside a group.
</div></div>

</li>
<li><code>columns : String</code> (optional)
<div><div>
 Specify HTML &amp; email report columns and the order of them, comma separated.
 <br>
  Column Group/Team is standard if at least one group has been configured.
 <br>
  Other possible column values are : 
 <br>
  Health, Job, Status, Percentage, Total, Pass, Fail, Skip, Commits, LastRun, Duration, Description, Packages, Files, Classes, Methods, Lines, Conditions, Sonar, Build
 <br>
</div></div>

</li>
<li><code>compareWithPreviousRun : boolean</code> (optional)
<div><div>
 Compare with previous run. Default its true.
</div></div>

</li>
<li><code>ignoreNotFoundJobs : boolean</code> (optional)
<div><div>
 Ignore not found jobs from report.
</div></div>

</li>
<li><code>ignoreDisabledJobs : boolean</code> (optional)
<div><div>
 Ignore Disabled jobs from report.
</div></div>

</li>
<li><code>ignoreAbortedJobs : boolean</code> (optional)
<div><div>
 Ignore Aborted jobs from report.
</div></div>

</li>
<li><code>ignoreRunningJobs : boolean</code> (optional)
<div><div>
 Ignore Running jobs from report.
 <br>
  If false then jobs are reported with status RUNNING
 <br>
  If true then jobs are reported with the previous status and results. Moreover an asterisk at the side of status declares that the job is still running.
 <br>
</div></div>

</li>
</ul>


++++
