= Text Finder
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/text-finder">Visit the Jenkins Plugins site</a>
++++


=== `findText`: Search files or the console log for regular expression(s)
++++
<ul><li><code>alsoCheckConsoleOutput : boolean</code> (optional)
</li>
<li><code>buildResult : String</code> (optional)
</li>
<li><code>fileSet : String</code> (optional)
</li>
<li><code>notBuiltIfFound : boolean</code> (optional)
</li>
<li><code>regexp : String</code> (optional)
</li>
<li><code>succeedIfFound : boolean</code> (optional)
</li>
<li><code>textFinders</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>regexp : String</code>
<div><div>
 Specify a regular expression using the syntax supported by the Java <a href="https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html" rel="nofollow"><code>Pattern</code></a> class.
</div></div>

</li>
<li><code>alsoCheckConsoleOutput : boolean</code> (optional)
</li>
<li><code>buildResult : String</code> (optional)
<div><div>
 Based on the change condition, the build result will be set to this value. Note that the build result can only get worse, so you cannot change the result to <code>SUCCESS</code> if the current result is <code>UNSTABLE</code> or worse. Use <code>SUCCESS</code> to keep the build result from being set.
</div></div>

</li>
<li><code>changeCondition</code> (optional)
<div><div>
 If the change condition is <code>MATCH_FOUND</code>, then the build result will be set if a match is found. If the change condition is <code>MATCH_NOT_FOUND</code>, then the build result will be set if a match is not found.
</div></div>

<ul><li><b>Values:</b> <code>MATCH_FOUND</code>, <code>MATCH_NOT_FOUND</code></li></ul></li>
<li><code>fileSet : String</code> (optional)
<div><div>
 Specify the path to the files to search, relative to the workspace root. This can use wildcards like <code>logs/**/*/*.txt</code>. See the documentation for the <code>@includes</code> attribute of the Ant <a href="https://ant.apache.org/manual/Types/fileset.html" rel="nofollow"><code>FileSet</code></a> type for details. Leave this empty if you do not want to scan any files (usually combined with checking <i>Also search the console output</i>).
</div></div>

</li>
</ul></li>
<li><code>unstableIfFound : boolean</code> (optional)
</li>
</ul>


++++
