= Thycotic DevOps Secrets Vault Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/thycotic-devops-secrets-vault">Visit the Jenkins Plugins site</a>
++++


=== `dsvSecret`: VaultSecretStep
++++
<ul><li><code>config</code>
<ul><b>Nested Object</b>
<li><code>credentialsId : String</code>
</li>
<li><code>tenant : String</code> (optional)
</li>
<li><code>tld : String</code> (optional)
</li>
<li><code>credentialId : String</code> (optional)
</li>
</ul></li>
<li><code>secretPath : String</code> (optional)
</li>
<li><code>secretDataKey : String</code> (optional)
</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>tenant : String</code> (optional)
</li>
<li><code>tld : String</code> (optional)
</li>
</ul>


++++
=== `wrap([$class: 'VaultBuildWrapper'])`: Use Thycotic DevOps Secrets Vault Secrets
++++
<ul><li><code>secrets</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
<div><div>
 The path (URL) of the secret e.g. <code>/aws/us-east-1/server1</code>
</div></div>

</li>
<li><code>mappings</code>
<div><div>
 A list of mappings from Secret data fields to environment variables
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>dataField : String</code>
</li>
<li><code>environmentVariable : String</code>
</li>
</ul></li>
<li><code>credentialId : String</code> (optional)
</li>
<li><code>tenant : String</code> (optional)
<div><div>
 The DevOps Secrets vault tenant is used to create the base URL i.e. <code><i>tenant</i>.secretservercloud.com</code>
</div></div>

</li>
<li><code>tld : String</code> (optional)
<div><div>
 The DevOps Secrets vault top-level domain (TLD) is used to create the base URL i.e. <code>mytenant.secretservercloud.<i>tld</i></code>
</div></div>

</li>
</ul></li>
</ul>


++++
