= UiPath Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/uipath-automation-package">Visit the Jenkins Plugins site</a>
++++


=== `UiPathAssets`: UiPath Manage Assets
++++
<ul><li><code>assetsAction</code>
<ul><b>Nested Choice of Objects</b>
<li><code>AutoVersion</code><div>
<ul></ul></div></li>
<li><code>CurrentVersion</code><div>
<ul></ul></div></li>
<li><code>DeleteAssets</code><div>
<ul></ul></div></li>
<li><code>DeployAssets</code><div>
<ul></ul></div></li>
<li><code>Dynamically</code><div>
<ul><li><code>jobsCount : int</code>
</li>
<li><code>user : String</code>
<div><div>
 The name of the user. This feature is available only on modern folders. This should be a machine user, not an orchestrator user. For local users, the format should be MachineName\\UserName".
</div></div>

</li>
<li><code>machine : String</code>
<div><div>
 The name of the machine. This feature is available only on modern folders.
</div></div>

</li>
</ul></div></li>
<li><code>ExternalApp</code><div>
<ul><li><code>accountForApp : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
<li><code>applicationId : String</code>
<div><div>
 Specify the confidential external application id. Learn more about how to add an external application by following the steps outlined <a href="https://docs.uipath.com/automation-cloud/docs/managing-external-applications" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>applicationSecret : String</code>
<div><div>
 Specify the confidential external application secret.
</div></div>

</li>
<li><code>applicationScope : String</code>
<div><div>
 Specify the confidential external application scope(s). It is mandatory to use only Application Scope(s).
</div></div>

</li>
<li><code>identityUrl : String</code>
</li>
</ul></div></li>
<li><code>CustomVersion</code><div>
<ul><li><code>version : String</code>
</li>
</ul></div></li>
<li><code>NonProduction</code><div>
<ul></ul></div></li>
<li><code>Robot</code><div>
<ul><li><code>robotsIds : String</code>
</li>
</ul></div></li>
<li><code>Test</code><div>
<ul></ul></div></li>
<li><code>TestProject</code><div>
<ul><li><code>testProjectPath : String</code>
<div><div>
 Specify the location of a test project to be deployed in Orchestrator and executed as part of a transient test set.
</div></div>

</li>
<li><code>environments : String</code>
<div><div>
 Specify the environment onto which the package will be deployed as a process. For the project and environment with existing processes, the processes will be updated to use the latest project version. Required when using a classic folder, otherwise not applicable.
</div></div>

</li>
</ul></div></li>
<li><code>TestSet</code><div>
<ul><li><code>testSet : String</code>
<div><div>
 Specify the test set name of a pre-existing test set on the Orchestrator which will be executed. If the test set does not belong to the default folder (organization unit) it must be prefixed with the folder name, e.g. AccountingTeam\\TestSet
</div></div>

</li>
</ul></div></li>
<li><code>Token</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Specify the refresh token using which to authenticate to the Cloud Orchestrator instance. Learn more about how to generate this token by following the steps outlined <a href="https://docs.uipath.com/orchestrator/v2019/reference#consuming-cloud-api" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>accountName : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
</ul></div></li>
<li><code>Unattended</code><div>
<ul></ul></div></li>
<li><code>UserPass</code><div>
<ul><li><code>credentialsId : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>orchestratorAddress : String</code>
<div><div>
 Specify the address of the Orchestrator instance onto which the assets will be deployed or updated.
</div></div>

</li>
<li><code>orchestratorTenant : String</code>
<div><div>
 Specify the Orchestrator tenant onto which the assets will be deployed or updated.
</div></div>

</li>
<li><code>folderName : String</code>
<div><div>
 Specify the folder where assets will deploy or update.
</div></div>

</li>
<li><code>credentials</code>
<ul><b>Nested Choice of Objects</b>
<li><code>AutoVersion</code><div>
<ul></ul></div></li>
<li><code>CurrentVersion</code><div>
<ul></ul></div></li>
<li><code>DeleteAssets</code><div>
<ul></ul></div></li>
<li><code>DeployAssets</code><div>
<ul></ul></div></li>
<li><code>Dynamically</code><div>
<ul><li><code>jobsCount : int</code>
</li>
<li><code>user : String</code>
<div><div>
 The name of the user. This feature is available only on modern folders. This should be a machine user, not an orchestrator user. For local users, the format should be MachineName\\UserName".
</div></div>

</li>
<li><code>machine : String</code>
<div><div>
 The name of the machine. This feature is available only on modern folders.
</div></div>

</li>
</ul></div></li>
<li><code>ExternalApp</code><div>
<ul><li><code>accountForApp : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
<li><code>applicationId : String</code>
<div><div>
 Specify the confidential external application id. Learn more about how to add an external application by following the steps outlined <a href="https://docs.uipath.com/automation-cloud/docs/managing-external-applications" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>applicationSecret : String</code>
<div><div>
 Specify the confidential external application secret.
</div></div>

</li>
<li><code>applicationScope : String</code>
<div><div>
 Specify the confidential external application scope(s). It is mandatory to use only Application Scope(s).
</div></div>

</li>
<li><code>identityUrl : String</code>
</li>
</ul></div></li>
<li><code>CustomVersion</code><div>
<ul><li><code>version : String</code>
</li>
</ul></div></li>
<li><code>NonProduction</code><div>
<ul></ul></div></li>
<li><code>Robot</code><div>
<ul><li><code>robotsIds : String</code>
</li>
</ul></div></li>
<li><code>Test</code><div>
<ul></ul></div></li>
<li><code>TestProject</code><div>
<ul><li><code>testProjectPath : String</code>
<div><div>
 Specify the location of a test project to be deployed in Orchestrator and executed as part of a transient test set.
</div></div>

</li>
<li><code>environments : String</code>
<div><div>
 Specify the environment onto which the package will be deployed as a process. For the project and environment with existing processes, the processes will be updated to use the latest project version. Required when using a classic folder, otherwise not applicable.
</div></div>

</li>
</ul></div></li>
<li><code>TestSet</code><div>
<ul><li><code>testSet : String</code>
<div><div>
 Specify the test set name of a pre-existing test set on the Orchestrator which will be executed. If the test set does not belong to the default folder (organization unit) it must be prefixed with the folder name, e.g. AccountingTeam\\TestSet
</div></div>

</li>
</ul></div></li>
<li><code>Token</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Specify the refresh token using which to authenticate to the Cloud Orchestrator instance. Learn more about how to generate this token by following the steps outlined <a href="https://docs.uipath.com/orchestrator/v2019/reference#consuming-cloud-api" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>accountName : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
</ul></div></li>
<li><code>Unattended</code><div>
<ul></ul></div></li>
<li><code>UserPass</code><div>
<ul><li><code>credentialsId : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>filePath : String</code>
<div><div>
 Specify the path for the csv files used to describe the assets that will be deployed or updated. Please use the following file format: 
 <pre> name,type,value</pre>
 <pre> asset_1_name,text,asset_value   # we can have comments</pre>
 <pre> asset_2_name,integer,123</pre>
 <pre> asset_3_name,boolean,false </pre>
 <pre> asset_4_name,credential,"username::password"</pre> For the update, the type column isn't used, so it can be empty but still present.
</div></div>

</li>
<li><code>traceLevel</code>
<div><div>
 The trace logging level. One of the following values: None, Critical, Error, Warning, Information, Verbose. (default None)
</div></div>

<ul><li><b>Values:</b> <code>None</code>, <code>Critical</code>, <code>Error</code>, <code>Warning</code>, <code>Information</code>, <code>Verbose</code></li></ul></li>
</ul>


++++
=== `UiPathDeploy`: UiPath Deploy
++++
<ul><li><code>packagePath : String</code>
<div><div>
 Specify the location of the package(s) to be deployed in Orchestrator. The paths are local to the workspace of the build.
</div></div>

</li>
<li><code>orchestratorAddress : String</code>
<div><div>
 Specify the address of the Orchestrator instance onto which the package(s) will be deployed.
</div></div>

</li>
<li><code>orchestratorTenant : String</code>
<div><div>
 Specify the Orchestrator tenant onto which the package(s) will be deployed.
</div></div>

</li>
<li><code>folderName : String</code>
<div><div>
 Specify the folder to deploy to. If the folder is a classic folder, you will also need to set the environments field. For modern folders, setting the environments is not required.
</div></div>

</li>
<li><code>environments : String</code>
<div><div>
 Specify the environment onto which the package will be deployed as a process. For the project and environment with existing processes, the processes will be updated to use the latest project version. Required when using a classic folder, otherwise not applicable.
</div></div>

</li>
<li><code>credentials</code>
<ul><b>Nested Choice of Objects</b>
<li><code>AutoVersion</code><div>
<ul></ul></div></li>
<li><code>CurrentVersion</code><div>
<ul></ul></div></li>
<li><code>DeleteAssets</code><div>
<ul></ul></div></li>
<li><code>DeployAssets</code><div>
<ul></ul></div></li>
<li><code>Dynamically</code><div>
<ul><li><code>jobsCount : int</code>
</li>
<li><code>user : String</code>
<div><div>
 The name of the user. This feature is available only on modern folders. This should be a machine user, not an orchestrator user. For local users, the format should be MachineName\\UserName".
</div></div>

</li>
<li><code>machine : String</code>
<div><div>
 The name of the machine. This feature is available only on modern folders.
</div></div>

</li>
</ul></div></li>
<li><code>ExternalApp</code><div>
<ul><li><code>accountForApp : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
<li><code>applicationId : String</code>
<div><div>
 Specify the confidential external application id. Learn more about how to add an external application by following the steps outlined <a href="https://docs.uipath.com/automation-cloud/docs/managing-external-applications" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>applicationSecret : String</code>
<div><div>
 Specify the confidential external application secret.
</div></div>

</li>
<li><code>applicationScope : String</code>
<div><div>
 Specify the confidential external application scope(s). It is mandatory to use only Application Scope(s).
</div></div>

</li>
<li><code>identityUrl : String</code>
</li>
</ul></div></li>
<li><code>CustomVersion</code><div>
<ul><li><code>version : String</code>
</li>
</ul></div></li>
<li><code>NonProduction</code><div>
<ul></ul></div></li>
<li><code>Robot</code><div>
<ul><li><code>robotsIds : String</code>
</li>
</ul></div></li>
<li><code>Test</code><div>
<ul></ul></div></li>
<li><code>TestProject</code><div>
<ul><li><code>testProjectPath : String</code>
<div><div>
 Specify the location of a test project to be deployed in Orchestrator and executed as part of a transient test set.
</div></div>

</li>
<li><code>environments : String</code>
<div><div>
 Specify the environment onto which the package will be deployed as a process. For the project and environment with existing processes, the processes will be updated to use the latest project version. Required when using a classic folder, otherwise not applicable.
</div></div>

</li>
</ul></div></li>
<li><code>TestSet</code><div>
<ul><li><code>testSet : String</code>
<div><div>
 Specify the test set name of a pre-existing test set on the Orchestrator which will be executed. If the test set does not belong to the default folder (organization unit) it must be prefixed with the folder name, e.g. AccountingTeam\\TestSet
</div></div>

</li>
</ul></div></li>
<li><code>Token</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Specify the refresh token using which to authenticate to the Cloud Orchestrator instance. Learn more about how to generate this token by following the steps outlined <a href="https://docs.uipath.com/orchestrator/v2019/reference#consuming-cloud-api" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>accountName : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
</ul></div></li>
<li><code>Unattended</code><div>
<ul></ul></div></li>
<li><code>UserPass</code><div>
<ul><li><code>credentialsId : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>traceLevel</code>
<div><div>
 The trace logging level. One of the following values: None, Critical, Error, Warning, Information, Verbose. (default None)
</div></div>

<ul><li><b>Values:</b> <code>None</code>, <code>Critical</code>, <code>Error</code>, <code>Warning</code>, <code>Information</code>, <code>Verbose</code></li></ul></li>
<li><code>entryPointPaths : String</code>
<div><div>
 Define the specific entry points to create or update a process. This is the filePath of the entry point starting from the root of the project. 
 <pre> e.g. "Folder1/Main.xaml, Folder1/Folder2/AdditionalEntrypoint.xaml" (without quotes) </pre> For classic folders only one entry point can be specified, for each environment a process will be created or updated with the specified entry point. Works only for Orchestrator ≥ 21.4.
</div></div>

</li>
<li><code>createProcess : boolean</code>
<div><div>
 When selected, a process will be created in the specified folder respective to entry point path(s) input. (default true)
</div></div>

</li>
</ul>


++++
=== `UiPathInstallPlatform`: UiPath InstallPlatform
++++
<ul><li><code>traceLevel</code>
<ul><li><b>Values:</b> <code>None</code>, <code>Critical</code>, <code>Error</code>, <code>Warning</code>, <code>Information</code>, <code>Verbose</code></li></ul></li>
<li><code>cliNupkgPath : String</code> (optional)
</li>
<li><code>cliVersion : String</code> (optional)
</li>
<li><code>forceInstall : boolean</code> (optional)
</li>
</ul>


++++
=== `UiPathPack`: UiPath Pack
++++
<ul><li><code>version</code>
<ul><b>Nested Choice of Objects</b>
<li><code>AutoVersion</code><div>
<ul></ul></div></li>
<li><code>CurrentVersion</code><div>
<ul></ul></div></li>
<li><code>DeleteAssets</code><div>
<ul></ul></div></li>
<li><code>DeployAssets</code><div>
<ul></ul></div></li>
<li><code>Dynamically</code><div>
<ul><li><code>jobsCount : int</code>
</li>
<li><code>user : String</code>
<div><div>
 The name of the user. This feature is available only on modern folders. This should be a machine user, not an orchestrator user. For local users, the format should be MachineName\\UserName".
</div></div>

</li>
<li><code>machine : String</code>
<div><div>
 The name of the machine. This feature is available only on modern folders.
</div></div>

</li>
</ul></div></li>
<li><code>ExternalApp</code><div>
<ul><li><code>accountForApp : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
<li><code>applicationId : String</code>
<div><div>
 Specify the confidential external application id. Learn more about how to add an external application by following the steps outlined <a href="https://docs.uipath.com/automation-cloud/docs/managing-external-applications" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>applicationSecret : String</code>
<div><div>
 Specify the confidential external application secret.
</div></div>

</li>
<li><code>applicationScope : String</code>
<div><div>
 Specify the confidential external application scope(s). It is mandatory to use only Application Scope(s).
</div></div>

</li>
<li><code>identityUrl : String</code>
</li>
</ul></div></li>
<li><code>CustomVersion</code><div>
<ul><li><code>version : String</code>
</li>
</ul></div></li>
<li><code>NonProduction</code><div>
<ul></ul></div></li>
<li><code>Robot</code><div>
<ul><li><code>robotsIds : String</code>
</li>
</ul></div></li>
<li><code>Test</code><div>
<ul></ul></div></li>
<li><code>TestProject</code><div>
<ul><li><code>testProjectPath : String</code>
<div><div>
 Specify the location of a test project to be deployed in Orchestrator and executed as part of a transient test set.
</div></div>

</li>
<li><code>environments : String</code>
<div><div>
 Specify the environment onto which the package will be deployed as a process. For the project and environment with existing processes, the processes will be updated to use the latest project version. Required when using a classic folder, otherwise not applicable.
</div></div>

</li>
</ul></div></li>
<li><code>TestSet</code><div>
<ul><li><code>testSet : String</code>
<div><div>
 Specify the test set name of a pre-existing test set on the Orchestrator which will be executed. If the test set does not belong to the default folder (organization unit) it must be prefixed with the folder name, e.g. AccountingTeam\\TestSet
</div></div>

</li>
</ul></div></li>
<li><code>Token</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Specify the refresh token using which to authenticate to the Cloud Orchestrator instance. Learn more about how to generate this token by following the steps outlined <a href="https://docs.uipath.com/orchestrator/v2019/reference#consuming-cloud-api" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>accountName : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
</ul></div></li>
<li><code>Unattended</code><div>
<ul></ul></div></li>
<li><code>UserPass</code><div>
<ul><li><code>credentialsId : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>projectJsonPath : String</code>
<div><div>
 The location of the project(s) to be packaged. It can be a direct path to a project.json file or a directory with one or multiple projects. In the latter case, each level one project is packaged individually
</div></div>

</li>
<li><code>outputPath : String</code>
<div><div>
 Specify the location where you want to output the NuGet package(s). The paths are local to the workspace of the build.
</div></div>

</li>
<li><code>traceLevel</code>
<div><div>
 The trace logging level. One of the following values: None, Critical, Error, Warning, Information, Verbose. (default None)
</div></div>

<ul><li><b>Values:</b> <code>None</code>, <code>Critical</code>, <code>Error</code>, <code>Warning</code>, <code>Information</code>, <code>Verbose</code></li></ul></li>
<li><code>credentials</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>AutoVersion</code><div>
<ul></ul></div></li>
<li><code>CurrentVersion</code><div>
<ul></ul></div></li>
<li><code>DeleteAssets</code><div>
<ul></ul></div></li>
<li><code>DeployAssets</code><div>
<ul></ul></div></li>
<li><code>Dynamically</code><div>
<ul><li><code>jobsCount : int</code>
</li>
<li><code>user : String</code>
<div><div>
 The name of the user. This feature is available only on modern folders. This should be a machine user, not an orchestrator user. For local users, the format should be MachineName\\UserName".
</div></div>

</li>
<li><code>machine : String</code>
<div><div>
 The name of the machine. This feature is available only on modern folders.
</div></div>

</li>
</ul></div></li>
<li><code>ExternalApp</code><div>
<ul><li><code>accountForApp : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
<li><code>applicationId : String</code>
<div><div>
 Specify the confidential external application id. Learn more about how to add an external application by following the steps outlined <a href="https://docs.uipath.com/automation-cloud/docs/managing-external-applications" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>applicationSecret : String</code>
<div><div>
 Specify the confidential external application secret.
</div></div>

</li>
<li><code>applicationScope : String</code>
<div><div>
 Specify the confidential external application scope(s). It is mandatory to use only Application Scope(s).
</div></div>

</li>
<li><code>identityUrl : String</code>
</li>
</ul></div></li>
<li><code>CustomVersion</code><div>
<ul><li><code>version : String</code>
</li>
</ul></div></li>
<li><code>NonProduction</code><div>
<ul></ul></div></li>
<li><code>Robot</code><div>
<ul><li><code>robotsIds : String</code>
</li>
</ul></div></li>
<li><code>Test</code><div>
<ul></ul></div></li>
<li><code>TestProject</code><div>
<ul><li><code>testProjectPath : String</code>
<div><div>
 Specify the location of a test project to be deployed in Orchestrator and executed as part of a transient test set.
</div></div>

</li>
<li><code>environments : String</code>
<div><div>
 Specify the environment onto which the package will be deployed as a process. For the project and environment with existing processes, the processes will be updated to use the latest project version. Required when using a classic folder, otherwise not applicable.
</div></div>

</li>
</ul></div></li>
<li><code>TestSet</code><div>
<ul><li><code>testSet : String</code>
<div><div>
 Specify the test set name of a pre-existing test set on the Orchestrator which will be executed. If the test set does not belong to the default folder (organization unit) it must be prefixed with the folder name, e.g. AccountingTeam\\TestSet
</div></div>

</li>
</ul></div></li>
<li><code>Token</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Specify the refresh token using which to authenticate to the Cloud Orchestrator instance. Learn more about how to generate this token by following the steps outlined <a href="https://docs.uipath.com/orchestrator/v2019/reference#consuming-cloud-api" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>accountName : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
</ul></div></li>
<li><code>Unattended</code><div>
<ul></ul></div></li>
<li><code>UserPass</code><div>
<ul><li><code>credentialsId : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>orchestratorAddress : String</code> (optional)
<div><div>
 Specify the address of the Orchestrator instance from which library dependencies should be restored.
</div></div>

</li>
<li><code>orchestratorTenant : String</code> (optional)
<div><div>
 Specify the tenant of the Orchestrator instance from which library dependencies should be restored.
</div></div>

</li>
<li><code>outputType : String</code> (optional)
<div><div>
 Force the output to a specific type.
</div></div>

</li>
<li><code>projectUrl : String</code> (optional)
</li>
<li><code>repositoryBranch : String</code> (optional)
</li>
<li><code>repositoryCommit : String</code> (optional)
</li>
<li><code>repositoryType : String</code> (optional)
</li>
<li><code>repositoryUrl : String</code> (optional)
</li>
<li><code>runWorkflowAnalysis : boolean</code> (optional)
<div><div>
 Run the workflow analysis before packing and fail in case of errors. (default false)
</div></div>

</li>
<li><code>splitOutput : boolean</code> (optional)
</li>
<li><code>useOrchestrator : boolean</code> (optional)
</li>
</ul>


++++
=== `UiPathRunJob`: UiPath Run Job
++++
<ul><li><code>jobType</code>
<ul><b>Nested Choice of Objects</b>
<li><code>AutoVersion</code><div>
<ul></ul></div></li>
<li><code>CurrentVersion</code><div>
<ul></ul></div></li>
<li><code>DeleteAssets</code><div>
<ul></ul></div></li>
<li><code>DeployAssets</code><div>
<ul></ul></div></li>
<li><code>Dynamically</code><div>
<ul><li><code>jobsCount : int</code>
</li>
<li><code>user : String</code>
<div><div>
 The name of the user. This feature is available only on modern folders. This should be a machine user, not an orchestrator user. For local users, the format should be MachineName\\UserName".
</div></div>

</li>
<li><code>machine : String</code>
<div><div>
 The name of the machine. This feature is available only on modern folders.
</div></div>

</li>
</ul></div></li>
<li><code>ExternalApp</code><div>
<ul><li><code>accountForApp : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
<li><code>applicationId : String</code>
<div><div>
 Specify the confidential external application id. Learn more about how to add an external application by following the steps outlined <a href="https://docs.uipath.com/automation-cloud/docs/managing-external-applications" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>applicationSecret : String</code>
<div><div>
 Specify the confidential external application secret.
</div></div>

</li>
<li><code>applicationScope : String</code>
<div><div>
 Specify the confidential external application scope(s). It is mandatory to use only Application Scope(s).
</div></div>

</li>
<li><code>identityUrl : String</code>
</li>
</ul></div></li>
<li><code>CustomVersion</code><div>
<ul><li><code>version : String</code>
</li>
</ul></div></li>
<li><code>NonProduction</code><div>
<ul></ul></div></li>
<li><code>Robot</code><div>
<ul><li><code>robotsIds : String</code>
</li>
</ul></div></li>
<li><code>Test</code><div>
<ul></ul></div></li>
<li><code>TestProject</code><div>
<ul><li><code>testProjectPath : String</code>
<div><div>
 Specify the location of a test project to be deployed in Orchestrator and executed as part of a transient test set.
</div></div>

</li>
<li><code>environments : String</code>
<div><div>
 Specify the environment onto which the package will be deployed as a process. For the project and environment with existing processes, the processes will be updated to use the latest project version. Required when using a classic folder, otherwise not applicable.
</div></div>

</li>
</ul></div></li>
<li><code>TestSet</code><div>
<ul><li><code>testSet : String</code>
<div><div>
 Specify the test set name of a pre-existing test set on the Orchestrator which will be executed. If the test set does not belong to the default folder (organization unit) it must be prefixed with the folder name, e.g. AccountingTeam\\TestSet
</div></div>

</li>
</ul></div></li>
<li><code>Token</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Specify the refresh token using which to authenticate to the Cloud Orchestrator instance. Learn more about how to generate this token by following the steps outlined <a href="https://docs.uipath.com/orchestrator/v2019/reference#consuming-cloud-api" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>accountName : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
</ul></div></li>
<li><code>Unattended</code><div>
<ul></ul></div></li>
<li><code>UserPass</code><div>
<ul><li><code>credentialsId : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>orchestratorAddress : String</code>
<div><div>
 Specify the address of the Orchestrator instance onto which the job(s) will be ran.
</div></div>

</li>
<li><code>orchestratorTenant : String</code>
<div><div>
 Specify the Orchestrator tenant onto which the job(s) will be ran.
</div></div>

</li>
<li><code>folderName : String</code>
<div><div>
 Specify the folder to run to. If the folder is a modern folder, you can also target a specific user and/or a specific machine.
</div></div>

</li>
<li><code>credentials</code>
<ul><b>Nested Choice of Objects</b>
<li><code>AutoVersion</code><div>
<ul></ul></div></li>
<li><code>CurrentVersion</code><div>
<ul></ul></div></li>
<li><code>DeleteAssets</code><div>
<ul></ul></div></li>
<li><code>DeployAssets</code><div>
<ul></ul></div></li>
<li><code>Dynamically</code><div>
<ul><li><code>jobsCount : int</code>
</li>
<li><code>user : String</code>
<div><div>
 The name of the user. This feature is available only on modern folders. This should be a machine user, not an orchestrator user. For local users, the format should be MachineName\\UserName".
</div></div>

</li>
<li><code>machine : String</code>
<div><div>
 The name of the machine. This feature is available only on modern folders.
</div></div>

</li>
</ul></div></li>
<li><code>ExternalApp</code><div>
<ul><li><code>accountForApp : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
<li><code>applicationId : String</code>
<div><div>
 Specify the confidential external application id. Learn more about how to add an external application by following the steps outlined <a href="https://docs.uipath.com/automation-cloud/docs/managing-external-applications" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>applicationSecret : String</code>
<div><div>
 Specify the confidential external application secret.
</div></div>

</li>
<li><code>applicationScope : String</code>
<div><div>
 Specify the confidential external application scope(s). It is mandatory to use only Application Scope(s).
</div></div>

</li>
<li><code>identityUrl : String</code>
</li>
</ul></div></li>
<li><code>CustomVersion</code><div>
<ul><li><code>version : String</code>
</li>
</ul></div></li>
<li><code>NonProduction</code><div>
<ul></ul></div></li>
<li><code>Robot</code><div>
<ul><li><code>robotsIds : String</code>
</li>
</ul></div></li>
<li><code>Test</code><div>
<ul></ul></div></li>
<li><code>TestProject</code><div>
<ul><li><code>testProjectPath : String</code>
<div><div>
 Specify the location of a test project to be deployed in Orchestrator and executed as part of a transient test set.
</div></div>

</li>
<li><code>environments : String</code>
<div><div>
 Specify the environment onto which the package will be deployed as a process. For the project and environment with existing processes, the processes will be updated to use the latest project version. Required when using a classic folder, otherwise not applicable.
</div></div>

</li>
</ul></div></li>
<li><code>TestSet</code><div>
<ul><li><code>testSet : String</code>
<div><div>
 Specify the test set name of a pre-existing test set on the Orchestrator which will be executed. If the test set does not belong to the default folder (organization unit) it must be prefixed with the folder name, e.g. AccountingTeam\\TestSet
</div></div>

</li>
</ul></div></li>
<li><code>Token</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Specify the refresh token using which to authenticate to the Cloud Orchestrator instance. Learn more about how to generate this token by following the steps outlined <a href="https://docs.uipath.com/orchestrator/v2019/reference#consuming-cloud-api" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>accountName : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
</ul></div></li>
<li><code>Unattended</code><div>
<ul></ul></div></li>
<li><code>UserPass</code><div>
<ul><li><code>credentialsId : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>processName : String</code> (optional)
<div><div>
 Process name.
</div></div>

</li>
<li><code>parametersFilePath : String</code> (optional)
<div><div>
 The full path to a json input file.
</div></div>

</li>
<li><code>priority</code> (optional)
<ul><li><b>Values:</b> <code>Low</code>, <code>Normal</code>, <code>High</code></li></ul></li>
<li><code>strategy</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>AutoVersion</code><div>
<ul></ul></div></li>
<li><code>CurrentVersion</code><div>
<ul></ul></div></li>
<li><code>DeleteAssets</code><div>
<ul></ul></div></li>
<li><code>DeployAssets</code><div>
<ul></ul></div></li>
<li><code>Dynamically</code><div>
<ul><li><code>jobsCount : int</code>
</li>
<li><code>user : String</code>
<div><div>
 The name of the user. This feature is available only on modern folders. This should be a machine user, not an orchestrator user. For local users, the format should be MachineName\\UserName".
</div></div>

</li>
<li><code>machine : String</code>
<div><div>
 The name of the machine. This feature is available only on modern folders.
</div></div>

</li>
</ul></div></li>
<li><code>ExternalApp</code><div>
<ul><li><code>accountForApp : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
<li><code>applicationId : String</code>
<div><div>
 Specify the confidential external application id. Learn more about how to add an external application by following the steps outlined <a href="https://docs.uipath.com/automation-cloud/docs/managing-external-applications" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>applicationSecret : String</code>
<div><div>
 Specify the confidential external application secret.
</div></div>

</li>
<li><code>applicationScope : String</code>
<div><div>
 Specify the confidential external application scope(s). It is mandatory to use only Application Scope(s).
</div></div>

</li>
<li><code>identityUrl : String</code>
</li>
</ul></div></li>
<li><code>CustomVersion</code><div>
<ul><li><code>version : String</code>
</li>
</ul></div></li>
<li><code>NonProduction</code><div>
<ul></ul></div></li>
<li><code>Robot</code><div>
<ul><li><code>robotsIds : String</code>
</li>
</ul></div></li>
<li><code>Test</code><div>
<ul></ul></div></li>
<li><code>TestProject</code><div>
<ul><li><code>testProjectPath : String</code>
<div><div>
 Specify the location of a test project to be deployed in Orchestrator and executed as part of a transient test set.
</div></div>

</li>
<li><code>environments : String</code>
<div><div>
 Specify the environment onto which the package will be deployed as a process. For the project and environment with existing processes, the processes will be updated to use the latest project version. Required when using a classic folder, otherwise not applicable.
</div></div>

</li>
</ul></div></li>
<li><code>TestSet</code><div>
<ul><li><code>testSet : String</code>
<div><div>
 Specify the test set name of a pre-existing test set on the Orchestrator which will be executed. If the test set does not belong to the default folder (organization unit) it must be prefixed with the folder name, e.g. AccountingTeam\\TestSet
</div></div>

</li>
</ul></div></li>
<li><code>Token</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Specify the refresh token using which to authenticate to the Cloud Orchestrator instance. Learn more about how to generate this token by following the steps outlined <a href="https://docs.uipath.com/orchestrator/v2019/reference#consuming-cloud-api" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>accountName : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
</ul></div></li>
<li><code>Unattended</code><div>
<ul></ul></div></li>
<li><code>UserPass</code><div>
<ul><li><code>credentialsId : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>resultFilePath : String</code> (optional)
<div><div>
 The full path to a json file or a folder where the result json file will be created.
</div></div>

</li>
<li><code>timeout : int</code> (optional)
<div><div>
 The timeout for job(s) runs in seconds. (default 1800)
</div></div>

</li>
<li><code>failWhenJobFails : boolean</code> (optional)
<div><div>
 The command fails when at least one job fails. (default true)
</div></div>

</li>
<li><code>waitForJobCompletion : boolean</code> (optional)
<div><div>
 Wait for job runs completion. (default true)
</div></div>

</li>
<li><code>traceLevel</code> (optional)
<div><div>
 The trace logging level. One of the following values: None, Critical, Error, Warning, Information, Verbose. (default None)
</div></div>

<ul><li><b>Values:</b> <code>None</code>, <code>Critical</code>, <code>Error</code>, <code>Warning</code>, <code>Information</code>, <code>Verbose</code></li></ul></li>
</ul>


++++
=== `UiPathTest`: UiPath Run tests
++++
<ul><li><code>orchestratorAddress : String</code>
<div><div>
 Specify the address of the Orchestrator instance onto which the package(s) will be deployed.
</div></div>

</li>
<li><code>orchestratorTenant : String</code>
<div><div>
 Specify the Orchestrator tenant onto which the package(s) will be deployed.
</div></div>

</li>
<li><code>folderName : String</code>
<div><div>
 Specify the folder to deploy to. If the folder is a classic folder and you would like to execute a transient test set, you will also need to set the environment. For modern folders, the environment is not required.
</div></div>

</li>
<li><code>testTarget</code>
<div><div>
 Specify the test execution target, a pre-existing test set on the Orchestrator or the tests in a package at a given path, which will be executed as part of a transient test set.
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>AutoVersion</code><div>
<ul></ul></div></li>
<li><code>CurrentVersion</code><div>
<ul></ul></div></li>
<li><code>DeleteAssets</code><div>
<ul></ul></div></li>
<li><code>DeployAssets</code><div>
<ul></ul></div></li>
<li><code>Dynamically</code><div>
<ul><li><code>jobsCount : int</code>
</li>
<li><code>user : String</code>
<div><div>
 The name of the user. This feature is available only on modern folders. This should be a machine user, not an orchestrator user. For local users, the format should be MachineName\\UserName".
</div></div>

</li>
<li><code>machine : String</code>
<div><div>
 The name of the machine. This feature is available only on modern folders.
</div></div>

</li>
</ul></div></li>
<li><code>ExternalApp</code><div>
<ul><li><code>accountForApp : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
<li><code>applicationId : String</code>
<div><div>
 Specify the confidential external application id. Learn more about how to add an external application by following the steps outlined <a href="https://docs.uipath.com/automation-cloud/docs/managing-external-applications" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>applicationSecret : String</code>
<div><div>
 Specify the confidential external application secret.
</div></div>

</li>
<li><code>applicationScope : String</code>
<div><div>
 Specify the confidential external application scope(s). It is mandatory to use only Application Scope(s).
</div></div>

</li>
<li><code>identityUrl : String</code>
</li>
</ul></div></li>
<li><code>CustomVersion</code><div>
<ul><li><code>version : String</code>
</li>
</ul></div></li>
<li><code>NonProduction</code><div>
<ul></ul></div></li>
<li><code>Robot</code><div>
<ul><li><code>robotsIds : String</code>
</li>
</ul></div></li>
<li><code>Test</code><div>
<ul></ul></div></li>
<li><code>TestProject</code><div>
<ul><li><code>testProjectPath : String</code>
<div><div>
 Specify the location of a test project to be deployed in Orchestrator and executed as part of a transient test set.
</div></div>

</li>
<li><code>environments : String</code>
<div><div>
 Specify the environment onto which the package will be deployed as a process. For the project and environment with existing processes, the processes will be updated to use the latest project version. Required when using a classic folder, otherwise not applicable.
</div></div>

</li>
</ul></div></li>
<li><code>TestSet</code><div>
<ul><li><code>testSet : String</code>
<div><div>
 Specify the test set name of a pre-existing test set on the Orchestrator which will be executed. If the test set does not belong to the default folder (organization unit) it must be prefixed with the folder name, e.g. AccountingTeam\\TestSet
</div></div>

</li>
</ul></div></li>
<li><code>Token</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Specify the refresh token using which to authenticate to the Cloud Orchestrator instance. Learn more about how to generate this token by following the steps outlined <a href="https://docs.uipath.com/orchestrator/v2019/reference#consuming-cloud-api" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>accountName : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
</ul></div></li>
<li><code>Unattended</code><div>
<ul></ul></div></li>
<li><code>UserPass</code><div>
<ul><li><code>credentialsId : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>credentials</code>
<ul><b>Nested Choice of Objects</b>
<li><code>AutoVersion</code><div>
<ul></ul></div></li>
<li><code>CurrentVersion</code><div>
<ul></ul></div></li>
<li><code>DeleteAssets</code><div>
<ul></ul></div></li>
<li><code>DeployAssets</code><div>
<ul></ul></div></li>
<li><code>Dynamically</code><div>
<ul><li><code>jobsCount : int</code>
</li>
<li><code>user : String</code>
<div><div>
 The name of the user. This feature is available only on modern folders. This should be a machine user, not an orchestrator user. For local users, the format should be MachineName\\UserName".
</div></div>

</li>
<li><code>machine : String</code>
<div><div>
 The name of the machine. This feature is available only on modern folders.
</div></div>

</li>
</ul></div></li>
<li><code>ExternalApp</code><div>
<ul><li><code>accountForApp : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
<li><code>applicationId : String</code>
<div><div>
 Specify the confidential external application id. Learn more about how to add an external application by following the steps outlined <a href="https://docs.uipath.com/automation-cloud/docs/managing-external-applications" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>applicationSecret : String</code>
<div><div>
 Specify the confidential external application secret.
</div></div>

</li>
<li><code>applicationScope : String</code>
<div><div>
 Specify the confidential external application scope(s). It is mandatory to use only Application Scope(s).
</div></div>

</li>
<li><code>identityUrl : String</code>
</li>
</ul></div></li>
<li><code>CustomVersion</code><div>
<ul><li><code>version : String</code>
</li>
</ul></div></li>
<li><code>NonProduction</code><div>
<ul></ul></div></li>
<li><code>Robot</code><div>
<ul><li><code>robotsIds : String</code>
</li>
</ul></div></li>
<li><code>Test</code><div>
<ul></ul></div></li>
<li><code>TestProject</code><div>
<ul><li><code>testProjectPath : String</code>
<div><div>
 Specify the location of a test project to be deployed in Orchestrator and executed as part of a transient test set.
</div></div>

</li>
<li><code>environments : String</code>
<div><div>
 Specify the environment onto which the package will be deployed as a process. For the project and environment with existing processes, the processes will be updated to use the latest project version. Required when using a classic folder, otherwise not applicable.
</div></div>

</li>
</ul></div></li>
<li><code>TestSet</code><div>
<ul><li><code>testSet : String</code>
<div><div>
 Specify the test set name of a pre-existing test set on the Orchestrator which will be executed. If the test set does not belong to the default folder (organization unit) it must be prefixed with the folder name, e.g. AccountingTeam\\TestSet
</div></div>

</li>
</ul></div></li>
<li><code>Token</code><div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Specify the refresh token using which to authenticate to the Cloud Orchestrator instance. Learn more about how to generate this token by following the steps outlined <a href="https://docs.uipath.com/orchestrator/v2019/reference#consuming-cloud-api" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>accountName : String</code>
<div><div>
 Specify the Cloud Orchestrator account name.
</div></div>

</li>
</ul></div></li>
<li><code>Unattended</code><div>
<ul></ul></div></li>
<li><code>UserPass</code><div>
<ul><li><code>credentialsId : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>testResultsOutputPath : String</code>
<div><div>
 Specify the output path of the test results, e.g. Output\testResults.xml. The results are output in JUnit format. If not specified, the results are output to the workspace as UiPathResults.xml.
</div></div>

</li>
<li><code>timeout : int</code>
<div><div>
 Specify the timeout of a test project to be deployed in Orchestrator and executed as part of a transient test set. The default value is 7200 seconds.
</div></div>

</li>
<li><code>traceLevel</code>
<div><div>
 The trace logging level. One of the following values: None, Critical, Error, Warning, Information, Verbose. (default None)
</div></div>

<ul><li><b>Values:</b> <code>None</code>, <code>Critical</code>, <code>Error</code>, <code>Warning</code>, <code>Information</code>, <code>Verbose</code></li></ul></li>
<li><code>parametersFilePath : String</code>
<div><div>
 Specify the location of a input parameters json file to override input arguments for a transient test set.
</div></div>

</li>
<li><code>attachRobotLogs : boolean</code> (optional)
</li>
<li><code>projectUrl : String</code> (optional)
</li>
<li><code>repositoryBranch : String</code> (optional)
</li>
<li><code>repositoryCommit : String</code> (optional)
</li>
<li><code>repositoryType : String</code> (optional)
</li>
<li><code>repositoryUrl : String</code> (optional)
</li>
</ul>


++++
