= UrbanCode Velocity Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/urbancode-velocity">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'CheckGate'])`: UCV - Check Gate in UrbanCode Velocity
++++
<ul><li><code>pipelineId : String</code>
</li>
<li><code>stageName : String</code>
</li>
<li><code>versionId : String</code>
</li>
<li><code>fatal : String</code>
</li>
</ul>


++++
=== `step([$class: 'UploadBuild'])`: UCV - Upload Build to UrbanCode Velocity
++++
<ul><li><code>tenantId : String</code>
</li>
<li><code>id : String</code>
</li>
<li><code>name : String</code>
</li>
<li><code>versionName : String</code>
</li>
<li><code>revision : String</code>
</li>
<li><code>requestor : String</code>
</li>
<li><code>status : String</code>
<div><div>
 One of start, in_progress, success, or failure.
</div></div>

</li>
<li><code>startTime : String</code>
</li>
<li><code>endTime : String</code>
</li>
<li><code>appName : String</code>
</li>
<li><code>appId : String</code>
</li>
<li><code>appExtId : String</code>
</li>
<li><code>debug : boolean</code>
</li>
<li><code>fatal : boolean</code>
<div><div>
 Fail build on failed upload (rather than just making build unstable).
</div></div>

</li>
</ul>


++++
=== `step([$class: 'UploadDeployment'])`: UCV - Upload Deployment to UrbanCode Velocity
++++
<ul><li><code>id : String</code>
</li>
<li><code>tenantId : String</code>
</li>
<li><code>name : String</code>
</li>
<li><code>result : String</code>
<div><div>
 One of start, in_progress, success, or failure.
</div></div>

</li>
<li><code>initiator : String</code>
</li>
<li><code>versionName : String</code>
</li>
<li><code>versionExtId : String</code>
</li>
<li><code>type : String</code>
</li>
<li><code>environmentId : String</code>
</li>
<li><code>environmentName : String</code>
</li>
<li><code>description : String</code>
</li>
<li><code>startTime : String</code>
</li>
<li><code>endTime : String</code>
</li>
<li><code>appName : String</code>
</li>
<li><code>appId : String</code>
</li>
<li><code>appExtId : String</code>
</li>
<li><code>debug : boolean</code>
</li>
<li><code>fatal : boolean</code>
<div><div>
 Fail build on failed upload (rather than just making build unstable).
</div></div>

</li>
</ul>


++++
=== `step([$class: 'UploadJUnitTestResult'])`: UCV - Upload JUnit Results to UrbanCode Velocity
++++
<ul><li><code>properties</code>
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
</ul>


++++
=== `step([$class: 'UploadMetricsFile'])`: UCV - Upload Metrics File to UrbanCode Velocity
++++
<ul><li><code>tenantId : String</code>
</li>
<li><code>name : String</code>
</li>
<li><code>filePath : String</code>
</li>
<li><code>testSetName : String</code>
</li>
<li><code>environment : String</code>
</li>
<li><code>combineTestSuites : boolean</code>
</li>
<li><code>fatal : boolean</code>
<div><div>
 Fail build on failed test upload (rather than just making build unstable).
</div></div>

</li>
<li><code>debug : boolean</code>
</li>
<li><code>pluginType : String</code>
</li>
<li><code>dataFormat : String</code>
</li>
<li><code>recordName : String</code>
</li>
<li><code>metricDefinitionId : String</code>
</li>
<li><code>metricsRecordUrl : String</code>
</li>
<li><code>description : String</code>
</li>
<li><code>executionDate : String</code>
<div><div>
 Time of execution that produced test results. Should be in Epoch milliseconds. Defaults to current time.
</div></div>

</li>
<li><code>buildId : String</code>
</li>
<li><code>buildUrl : String</code>
</li>
<li><code>appId : String</code>
</li>
<li><code>appName : String</code>
</li>
<li><code>appExtId : String</code>
</li>
</ul>


++++
