= Cadence vManager Plugin for Jenkins
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/vmanager-plugin">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'DSLPublisher'])`: vManager Post Build Actions
++++
<ul><li><code>vAPIUrl : String</code>
<div><div>
 Verisium Manager expose a REST API interface for API. The REST API is a dedicated process for serving remote http requests - vAPI.
 <br>
  Starting 14.1 s005 The vAPI process is served automatically by the Verisium Manager Server process, and as such you need to supply the following url:
 <br><strong>https://[VMANAGER_HOST:VMANAGER_PORT]/vmgr/vapi</strong>
 <br>
</div></div>

</li>
<li><code>vAPIUser : String</code>
<div><div>
 In case of a secure mode, the userId will be shown as the user who perform the operation within Verisium Manager tool.
 <br>
  In case of open mode, the default userid that will be used is "vapi".
 <br>
</div></div>

</li>
<li><code>vAPIPassword : String</code>
<div><div>
 In case of a secure mode, a password is needed
 <br>
  Please contact Verisium Manager documentation for further info.
 <br>
</div></div>

</li>
<li><code>authRequired : boolean</code>
<div><div>
 Verisium Manager vAPI can operate in one of two modes:
 <br>
 <li>Secured by user/secret key</li>
 <li>Open</li> In case of a secure mode, the userId (vAPI User) will be shown as the user who perform the operation within Verisium Manager tool.
 <br>
  In case of open mode, the default userid that will be used is "vapi".
 <br>
</div></div>

</li>
<li><code>advConfig : boolean</code>
</li>
<li><code>dynamicUserId : boolean</code>
<div><div>
 In case of a need in dynamically selecting the user name per job, the pre-job should place into the workspace directory a file with single line that contains the userid to be used.
 <br>
  The file name should be: ${BUILD_NUMBER}.${BUILD_ID}.user.input"
 <br>
  The job will pick the userid which is in the file, and connect to vAPI using this userid and the vAPI secret key.
</div></div>

</li>
<li><code>connTimeout : int</code>
<div><div>
 Connection Timeout is the time (in minutes) for the Jenkins executor to wait till it establish a connection with the Verisium Manager server. It is usually very fast, so no need to change the default (1 minute).
 <br>
  Setting the time to 0 means an unlimited time. In case it is taking too long to establish a connection, and the time passed is more than the Connection Timeout set, the connection to the Verisium Manager server will be closed, and the Jenkins executor will be able to continue. The vAPI operation will fail (it will not start), and the build will be marked as failed.
 <br>
  If no Connection timeout is set, the default is 1 minutes.
</div></div>

</li>
<li><code>readTimeout : int</code>
<div><div>
 Read Timeout is the time (in minutes) for the Jenkins executor to wait for Verisium Manager server to end the current operation. In heavy operations such as collect compact or ranking, the time to response back can vary, and might even take an hour or so depends on the load the Verisium Manager server is experiencing. 
 <br>
  Setting the time to 0 means an unlimited time. In case the vAPI call is taking too long, and is more than the Read Timeout set, the connection to the Verisium Manager server will be closed, and the Jenkins executor will be able to continue. The vAPI operation will not fail, but the build will be marked as failed.
 <br>
  If no Read timeout is set, the default is 30 minutes.
</div></div>

</li>
<li><code>advancedFunctions : boolean</code>
</li>
<li><code>retrieveSummaryReport : boolean</code>
</li>
<li><code>runReport : boolean</code>
</li>
<li><code>metricsReport : boolean</code>
</li>
<li><code>vPlanReport : boolean</code>
</li>
<li><code>testsViewName : String</code>
</li>
<li><code>metricsViewName : String</code>
</li>
<li><code>vplanViewName : String</code>
</li>
<li><code>testsDepth : int</code>
</li>
<li><code>metricsDepth : int</code>
</li>
<li><code>vPlanDepth : int</code>
</li>
<li><code>metricsInputType : String</code>
</li>
<li><code>metricsAdvanceInput : String</code>
<div><div>
 In case of a need to take advantage of the full summary report flags, you can use a json structure to define the rest of the flags the vAPI supports.
 <br>
  The following structure addresses the flags relevant for the metrics part only (for more information, check the full vAPI electronic docs on the web):
 <br>
  {
 <br>
  "depth": 4,
 <br>
  "instances": true,
 <br>
  "types": true,
 <br>
  "extended": true,
 <br>
  "path": "string",
 <br>
  "scope": "string"
 <br>
  }
 <br>
 <br>
  depth: integer ($int32) (Metrics tree level depth. Default value is the whole tree)
 <br>
  scope: string (Metrics verification scope)
 <br>
  path: string (Full Path to entity in Metrics tree.)
 <br>
  instances: boolean (Specify if vPlan entity is in the instances hierarchy)
 <br>
  types: boolean (Specify if vPlan entity is in the types hierarchy)
 <br>
  extended: boolean (Enables or disables extended metrics report, if not specified the report would be extended according to metrics configuration)
 <br>
 <br>
  None of the fields are mandatory to exclude "depth".
</div></div>

</li>
<li><code>vPlanInputType : String</code>
</li>
<li><code>vPlanAdvanceInput : String</code>
<div><div>
 In case of a need to take advantage of the full summary report flags, you can use a json structure to define the rest of the flags the vAPI supports.
 <br>
  The following structure addresses the flags relevant for the vPlan part only (for more information, check the full vAPI electronic docs on the web):
 <br>
  {
 <br>
  "depth": 4,
 <br>
  "perspective": "string",
 <br>
  "multiPerspectives": [array - look for more information within the documentation] "instances": true,
 <br>
  "types": true,
 <br>
  "extended": true,
 <br>
  "path": "string",
 <br>
  "vplanNode": "string"
 <br>
  }
 <br>
 <br>
  { "depth": 20, "perspective": "APB_UART", "instances": true, "types": true, "extended": true } depth: integer ($int32) (vPlan tree level depth. Default value is the whole tree)
 <br>
  perspective: string (Perspective to report. if not specified the default plan perspective would be used)
 <br>
  multiPerspectives: [...]
 <br>
  vplanNode: string (Full Path to perspective/section/port in vPlan tree.)
 <br>
  path: string (specify if to use vplanNode, instances or types for vPlan entity. If not specified the perspective is used)
 <br>
  instances: boolean (Specify if vPlan entity is in the instances hierarchy)
 <br>
  types: boolean (Specify if vPlan entity is in the types hierarchy)
 <br>
  extended: boolean (Enables or disables extended vplan report. if not specified the report would be extended according to vplan configuration)
 <br>
 <br>
  None of the fields are mandatory to exclude "depth".
</div></div>

</li>
<li><code>vPlanxFileName : String</code>
</li>
<li><code>summaryType : String</code>
</li>
<li><code>ctxInput : boolean</code>
</li>
<li><code>ctxAdvanceInput : String</code>
<div><div>
 In case of a need to take advantage of the full summary report flags, you can use a json structure to define the rest of the flags the vAPI supports.
 <br>
  The following structure addresses the flags relevant for the vPlan and Metrics parts and gives you more control over refinements (for more information, check the full vAPI electronic docs on the web):
 <br>
  {
 <br>
  "depth": 4,
 <br>
  "refinementFile": "string",
 <br>
  "vplanFile": "string",
 <br>
  "vplanRefinementFile": "string",
 <br>
  "environment": "string",
 <br>
  "multiPerspectives": [array - look for more information within the documentation],
 <br>
  "multiPerspectives": [array - look for more information within the documentation],
 <br>
  "multiPerspectives": [array - look for more information within the documentation]
 <br>
  }
 <br>
 <br>
  None of the fields are mandatory, however - please note that adding "vplanFile" here, will overwrite anything you placed within "vPlanx file name".
 <br>
  ("vPlanx file name" field is not mandatory in case you choose to use the advanced context input)
</div></div>

</li>
<li><code>freeVAPISyntax : String</code>
<div><div>
 In case of a need in taking full control over the vAPI parameters of the summary report, the pre-job should place into the workspace directory a file with the json input for the /reports/generate-summary-report vAPI.
 <br>
  The input file should be place into the working directory. In case this field is empty, The file name need to be: ${BUILD_NUMBER}.${BUILD_ID}.summary_report.input
 <br>
  Please fill this field only in case, you want to hard code the input file name, to be consist across all builds. 
 <br>
  Please exclude the "rs" section from this json. This plugin will automatically fill in the "rs" based on the sessions launched during the build process.
 <br>
</div></div>

</li>
<li><code>deleteReportSyntaxInputFile : boolean</code>
</li>
<li><code>vManagerVersion : String</code>
</li>
<li><code>sendEmail : boolean</code>
</li>
<li><code>emailList : String</code>
</li>
<li><code>emailType : String</code>
</li>
<li><code>emailInputFile : String</code>
<div><div>
 In case of a need in providing a dynamic list of email addresses, the pre-job should place into the workspace directory a file with the relevant emails, one email address per line (without a comma between).
 <br>
  The input file should be place into the working directory. In case this field is empty, The file name need to be: ${BUILD_NUMBER}.${BUILD_ID}.emails.input
 <br>
  Please fill this field only in case, you want to hard code the input file name, to be consist across all builds. 
 <br>
  Disclaimer: In case you choose to work with the "free vAPI syntax" option, you have the option to supply the list of emails as part of the free vAPI json structure (optionally) - in such cases, this field will be ignored.
 <br>
</div></div>

</li>
<li><code>deleteEmailInputFile : boolean</code>
</li>
<li><code>summaryMode : String</code>
</li>
<li><code>ignoreSSLError : boolean</code>
<div><div>
 This option is only relevant if you choose Verisium Manager Version &lt; 19.09.
 <br>
  If the Verisium Manager version is smaller than 19.09, the report is being retrieved by parsing the html web page of the report generated using http connection.
 <br>
  Since Verisium Manager Web Server is having by default a self-signed certificate, normal http connection will fail to get validated and the connection will get rejected. 
 <br>
  If you replaced the server certificate with a signed one of your own, you can leave it as default. Unless, if you are using the default Verisium Manager installed self-signed certificate - the only way to overcome its SSL validation is to allow the connection from the Jenkins to the Verisium Manager server at the time of the report retrieval only to skip validation.
</div></div>

</li>
<li><code>vAPICredentials : String</code>
</li>
<li><code>credentialType : String</code>
</li>
</ul>


++++
=== `vmanagerLaunch`: Cadence vManager Session Launcher
++++
<ul><li><code>vAPIUrl : String</code>
<div><div>
 Verisium Manager expose a REST API interface for API. The REST API is a dedicated process for serving remote http requests - vAPI.
 <br>
  Starting 14.1 s005 The vAPI process is served automatically by the Verisium Manager Server process, and as such you need to supply the following url:
 <br><strong>https://[VMANAGER_HOST:VMANAGER_PORT]/vmgr/vapi</strong>
 <br>
</div></div>

</li>
<li><code>vAPIUser : String</code>
<div><div>
 In case of a secure mode, the userId will be shown as the user who perform the operation within Verisium Manager tool.
 <br>
  In case of open mode, the default userid that will be used is "vapi".
 <br>
</div></div>

</li>
<li><code>vAPIPassword : String</code>
<div><div>
 In case of a secure mode, a password is needed
 <br>
  Please contact Verisium Manager documentation for further info.
 <br>
</div></div>

</li>
<li><code>executionType : String</code>
</li>
<li><code>vMGRBuildArchive : boolean</code>
</li>
<li><code>vSIFName : String</code>
</li>
<li><code>vSIFInputFile : String</code>
<div><div>
 In case of a need in dynamically selecting the vsif files to get launched per job, the pre-job should place into the workspace directory a file with the full paths of the relevant vsif files to be launched, new line for each additional vsif file.
 <br>
  The input file should be place into the working directory. In case this field is empty, The file name need to be: ${BUILD_NUMBER}.${BUILD_ID}.vsif.input
 <br>
  Please fill this field only in case, you want to hard code the input file name, to be consist across all builds. 
 <br>
  The output of all IDs of the launched sessions can be found at: ${BUILD_NUMBER}.${BUILD_ID}.session_launch.output
 <br>
</div></div>

</li>
<li><code>advConfig : boolean</code> (optional)
</li>
<li><code>archivePassword : String</code> (optional)
</li>
<li><code>archiveUser : String</code> (optional)
</li>
<li><code>attrValues : boolean</code> (optional)
</li>
<li><code>attrValuesFile : String</code> (optional)
<div><div>
 <strong>Supported by Verisium Manager 17.1 and above only</strong>
 <br>
  In case of a need in setting the vsif attribute values, the pre-job should place into the workspace directory a file with a list of relevant attributes and their values (one line per each attribute) in the following format.
 <br>
  Line 1: attribute_name,attribute_value,attribute_type
 <br>
  Line 2: attribute_name,attribute_value,attribute_type
 <br>
 <br>
  attribute type can be 1 of 3:
 <br>
  P_SESSION for session type attributes
 <br>
  P_TEST for test type attributes
 <br>
  P_GROUP for group type attributes
 <br>
  Example:
 <br><strong> home_location,/home/dan/regression,P_SESSION<br>
   owner,dan,P_TEST<br></strong> (Note the comma seperator within the lines. <strong>Do not</strong> place comma at the end of the lines.) 
 <br>
  The input file should be place into the working directory. In case this field is empty, The file name need to be: ${BUILD_NUMBER}.${BUILD_ID}.attr.values.input
 <br>
  Please fill this field only in case, you want to hard code the input file name, to be consist across all builds.
</div></div>

</li>
<li><code>authRequired : boolean</code> (optional)
<div><div>
 Verisium Manager vAPI can operate in one of two modes:
 <br>
 <li>Secured by user/secret key</li>
 <li>Open</li> In case of a secure mode, the userId (vAPI User) will be shown as the user who perform the operation within Verisium Manager tool.
 <br>
  In case of open mode, the default userid that will be used is "vapi".
 <br>
</div></div>

</li>
<li><code>connTimeout : int</code> (optional)
<div><div>
 Connection Timeout is the time (in minutes) for the Jenkins executor to wait till it establish a connection with the Verisium Manager server. It is usually very fast, so no need to change the default (1 minute).
 <br>
  Setting the time to 0 means an unlimited time. In case it is taking too long to establish a connection, and the time passed is more than the Connection Timeout set, the connection to the Verisium Manager server will be closed, and the Jenkins executor will be able to continue. The vAPI operation will fail (it will not start), and the build will be marked as failed.
 <br>
  If no Connection timeout is set, the default is 1 minutes.
</div></div>

</li>
<li><code>credentialInputFile : String</code> (optional)
<div><div>
 Supported only from 16.1 and above.
 <br>
  Verisium Manager can execute jobs in one of two modes:
 <br>
 <li>Same user permissions (the account permission where the Verisium Manager server is installed) for all jobs launched by the vAPI/Jenkins.</li>
 <li>Use the Linux account permissions of the actual user who is doing the launch operation.</li>
 <br>
  Default (unchecked above) is for the Verisium Manager to launch job by using the account permissions where the server is installed.
 <br>
  When this box is checked, user can choose between using the same credentials used within the authentication section above, or supply a file with user/password in plain text containing only two lines:
 <br><strong> username<br>
   password<br></strong>
 <br>
  For this (dynamic user/password), a pre-job should place any file into its working directory, and supply the full path to it.
 <br>
  In case this field is empty, The file name need to be: ${BUILD_NUMBER}.${BUILD_ID}.credential.input, and should be place in the working directory of the current running build.
 <br>
  Please fill this field only in case you want to hard code the input file name, to be consist across all builds.
</div></div>

</li>
<li><code>defineVariableText : String</code> (optional)
</li>
<li><code>defineVariableType : String</code> (optional)
</li>
<li><code>defineVarible : boolean</code> (optional)
</li>
<li><code>defineVaribleFile : String</code> (optional)
<div><div>
 In case of a need in setting the vsif define values, the pre-job should place into the workspace directory a file with a list of relevant defines and their values (one line per each definition) in the following format.
 <br>
  Line 1: define_name,define_value
 <br>
  Line 2: define_name,define_value
 <br>
 <br>
  Example:
 <br><strong> REG_MODE,sanity<br>
   SESSION_NAME,my_session<br></strong> (Note the comma separator within the lines. <strong>Do not</strong> place comma at the end of the lines.) 
 <br>
  The input file should be place into the working directory. In case this field is empty, The file name need to be: ${BUILD_NUMBER}.${BUILD_ID}.define.input
 <br>
  Please fill this field only in case, you want to hard code the input file name, to be consist across all builds.
</div></div>

</li>
<li><code>deleteAlsoSessionDirectory : boolean</code> (optional)
<div><div>
 Choosing to delete Verisium Manager session during build removal, will trigger an operation during manual/automatic deletion of a build, to deal with the remote session/sessions that were created during that build on the Verisium Manager DB.
 <br>
  When this option is enabled the build will place an instruction file (sdi.properties) within the job directory that specify the sessions to get deleted, as well as other parameters - that will be used during the delete operation.
 <br>
 <br>
  Builds that runs while this option is turned off, will not get effected during removal, and will keep their sessions.
 <br>
 <br>
  You can choose between two methodologies: 
 <br>
 <br><strong>Sync Delete Methodology (built-in)</strong>
 <br>
  In case you select the sync methodology, the plugin will call Verisium Manager vAPI during the build removal process for deleting the sessions that were created during that same build.
 <br>
  With this option you can also supply a generic user/password to be used for the delete operation, otherwise, the same user that was used during the build will be picked automatically. 
 <br>
  Please note that the sync methodology is lacking two main aspects:
 <br>
  1. Since Jenkins ignores any exception thrown within the callback functions of RunListener, the build will get deleted even if the session failed to get deleted from Verisium Manager DB.
 <br>
  2. When the vAPI is down, it can take up to 20 seconds to finish the operation (as it needs to wait till vAPI will be available) - the UX at that time, might appear sluggish to the end user.
 <br>
 <br><strong>Async Delete Methodology (externally)</strong>
 <br>
  In case you want to introduce a more robust approach (promise session deletion even if Verisium Manager Server is down, as well as faster UX), you should use the async methodology.
 <br>
  When Async Methodology is used, the callback function will not try to delete the session, but instead will copy the sdi.properties file into an external location of your choice. 
 <br>
  You should create an additional job, one that is triggered every 1 minute for scanning that directory (and trying to delete the relevant sessions within these sdi files). To exclude the copy of the sdi files during build removal, this flow is not managed by the plugin.
 <br>
  Please note - defining an external directory location (in windows) requires the use of forward slash instead of backslash.
 <br>
</div></div>

</li>
<li><code>deleteCredentialInputFile : boolean</code> (optional)
</li>
<li><code>deleteInputFile : boolean</code> (optional)
</li>
<li><code>deleteSessionInputFile : boolean</code> (optional)
</li>
<li><code>doneResolver : String</code> (optional)
</li>
<li><code>dynamicUserId : boolean</code> (optional)
<div><div>
 In case of a need in dynamically selecting the user name per job, the pre-job should place into the workspace directory a file with single line that contains the userid to be used.
 <br>
  The file name should be: ${BUILD_NUMBER}.${BUILD_ID}.user.input"
 <br>
  The job will pick the userid which is in the file, and connect to vAPI using this userid and the vAPI secret key.
</div></div>

</li>
<li><code>envSourceInputFile : String</code> (optional)
<div><div>
 <strong>Supported by Verisium Manager 17.10 and above only</strong>
 <br>
  In case of a need in adding the vsif environment variables, users can create a list of aliases and store them within a file. The job will 'source' that file prior of reading the vsif.
 <br>
  Note that this can also serve for any pre stage execution, not just for aliases. 
 <br>
  Relative path is also supported (aka ~/doSomething.sh). 
 <br>
  Script must be in bash or csh. 
 <br>
 <br>
  The file should be place into a directory with a read permission for the user who launches the regression.
 <br>
  In case this field is empty, this field is ignored
 <br>
</div></div>

</li>
<li><code>envSourceInputFileType : String</code> (optional)
</li>
<li><code>envVarible : boolean</code> (optional)
</li>
<li><code>envVaribleFile : String</code> (optional)
<div><div>
 <strong>Supported by Verisium Manager 15.1 and above only</strong>
 <br>
  In case of a need in adding the vsif environment variables, the pre-job should place into the workspace directory a file with a list of relevant environment variables in json keys format.
 <br>
  Example:
 <br><strong> "MY_REGRESSION_AREA": "/home/dan/regression",<br>
   "MY_DUT" : "top"<br></strong> (Note the comma seperator at the end of each line, to exclude the last line.) 
 <br>
  The input file should be place into the working directory. In case this field is empty, The file name need to be: ${BUILD_NUMBER}.${BUILD_ID}.environment.input
 <br>
  Please fill this field only in case, you want to hard code the input file name, to be consist across all builds.
</div></div>

</li>
<li><code>executionScript : String</code> (optional)
<div><div>
 <strong>Start your session from shell using batch, and continue monitoring from vAPI</strong>
 <br>
  In case you need to launch your session using batch first, please create a wrapper script that gets as an input the vSIF full path.
 <br>
  The plugin will execute your script on the selective agent (Jenkins) and will extract the session name out of it.
 <br>
  The plugin will then use that session_name to keep monitor your execution.
 <br>
 <br>
  Example for such script file can be:
 <br>
  ---------------------------
 <br>
  #!/bin/csh
 <br>
 <br>
  source ~/.cshrc
 <br>
 <br>
  setenv VMGR_REGION default
 <br>
  setenv VMGR_REGION_ROUTE_POLICY LOCAL
 <br>
  setenv VMGR_USER some_user_id
 <br>
  setenv VMGR_PASSWORD XXXXXX
 <br>
 <br>
  vmanager -execcmd "launch $1"
 <br>
  ---------------------------
 <br>
 <br>
  Please also make sure that
 <br>
  1) The path to the script is a full path. No shortcuts or relative paths are allowed.
 <br>
  2) The shell type (bash, csh, sh) is supplied with full path as well.
 <br>
  3) This mode can only be used with an Agent that runs on Linux.
 <br>
</div></div>

</li>
<li><code>executionShellLocation : String</code> (optional)
</li>
<li><code>executionVsifFile : String</code> (optional)
</li>
<li><code>extraAttributesForFailures : boolean</code> (optional)
</li>
<li><code>failJobIfAllRunFailed : boolean</code> (optional)
</li>
<li><code>failJobUnlessAllRunPassed : boolean</code> (optional)
</li>
<li><code>failedResolver : String</code> (optional)
</li>
<li><code>famMode : String</code> (optional)
</li>
<li><code>famModeLocation : String</code> (optional)
</li>
<li><code>generateJUnitXML : boolean</code> (optional)
</li>
<li><code>genericCredentialForSessionDelete : boolean</code> (optional)
</li>
<li><code>inaccessibleResolver : String</code> (optional)
<div><div>
 The following setup allow you to select how the build will behave in each of the state where the session stop from running.
 <br>
 <br><strong>Continue</strong>
 <br>
  In case you select to continue, the build will assume (on the chosen state) for a given session that it can continue and finish the wait on this specific session.
 <br>
  Please note that in case there are multiple sessions that are being executed by this step, the build will wait till all sessions got into a state that allow it to continue. 
 <br>
 <br><strong>Ignore</strong>
 <br>
  In case you select to continue, the build will assume (on the chosen state) for a given session that it can ignore the chosen state and keep waiting for other state (until get the 'completed' state). 
 <br>
 <br><strong>Fail</strong>
 <br>
  In case you select to fail, the build will assume (on the chosen state) for a given session that it should mark this build as a failure build. <strong>Note: </strong>If you have multiple sessions on this build step, it is enough for one single session to be marked as 'failed' in order to mark the entire build as a failed build. 
 <br>
 <br><strong>Other Waiting Considerations</strong>
 <br>
  1. When all sessions on this build step are having the state 'completed' the build will be marked as success.
 <br>
  2. When the Verisium Manager server goes down, the build step will keep waiting till the server will go back up. The build step will only change its state based on sessions state changes.
 <br>
  3. If the session was manually deleted on the Verisium Manager server, before reaching into final state, the build will be marked as a failure build.
 <br>
  4. In any case, if the number of minutes waiting is bigger than the timeout set here, the build will marked as a failed build.
 <br>
</div></div>

</li>
<li><code>markBuildAsFailedIfAllRunFailed : boolean</code> (optional)
</li>
<li><code>markBuildAsPassedIfAllRunPassed : boolean</code> (optional)
</li>
<li><code>masterWorkspaceLocation : String</code> (optional)
<div><div>
 In case of master/nodes setup, in which the job is running on the nodes, the workspace location is of the nodes, not the master.
 <br>
  The Verisium Manager plugins stores run's data at the master location, and as such need to know the full path for the master workspace per build.
 <br>
 <br>
  Example:
 <br><strong> (pipelineNodes: true, masterWorkspaceLocation: c:/jenkins/workspace) <br></strong>
</div></div>

</li>
<li><code>noAppendSeed : boolean</code> (optional)
</li>
<li><code>pauseSessionOnBuildInterruption : boolean</code> (optional)
</li>
<li><code>pipelineNodes : boolean</code> (optional)
</li>
<li><code>readTimeout : int</code> (optional)
<div><div>
 Read Timeout is the time (in minutes) for the Jenkins executor to wait for Verisium Manager server to end the current operation. In heavy operations such as collect compact or ranking, the time to response back can vary, and might even take an hour or so depends on the load the Verisium Manager server is experiencing. 
 <br>
  Setting the time to 0 means an unlimited time. In case the vAPI call is taking too long, and is more than the Read Timeout set, the connection to the Verisium Manager server will be closed, and the Jenkins executor will be able to continue. The vAPI operation will not fail, but the build will be marked as failed.
 <br>
  If no Read timeout is set, the default is 30 minutes.
</div></div>

</li>
<li><code>sessionsInputFile : String</code> (optional)
<div><div>
 This option is useful for those who wish to take benefit of their own environment and scripts for launching sessions using batch, but still want the benefit of having the Job waiting for the execution to end, generates JUnit report, produce triage link, real time view of the run's progress, summary report, etc'.
 <br>
  This option is also useful for those who wish to take advantage of this plugin, but are not using the Verisium Manager Runner, and uses "collect" mode instead. For such flow they can still benefit from generated JUnit report, triage link, real time view of the run's progress, summary report, etc'.
 <br>
  In this option, there is an assumption that a pre-step (usually from shell type) is taking over the session launch operation (or collect), and as such, in order for this plugin to continue monitoring those sessions - the session names need to be exchange between the shell step and this step.
 <br>
 <br>
  In case of a need to launch the sessions using batch as a pre-step to this one (or collect), the pre-step should place into the workspace directory a file with the session or session names that were launched/collected - new line for each session name.
 <br>
  The input file should be place into the working directory. In case this field is empty, The file name need to be: ${BUILD_NUMBER}.${BUILD_ID}.sessions.input
 <br>
  Please fill this field only in case, you want to hard code the input file name, to be consist across all builds. 
 <br>
 <br>
  the Verisium Manager plugin will look for any of the input files mentioned above, and query the server for their respective id automatically. From that point and on, the flow continues as if the sessions were launched/collected by this plugin.
 <br>
 <br>
  The output of all IDs of the launched/collected sessions can be found at: ${BUILD_NUMBER}.${BUILD_ID}.session_launch.output
 <br>
</div></div>

</li>
<li><code>staticAttributeList : String</code> (optional)
</li>
<li><code>stepSessionTimeout : int</code> (optional)
</li>
<li><code>stoppedResolver : String</code> (optional)
</li>
<li><code>suspendedResolver : String</code> (optional)
</li>
<li><code>useUserOnFarm : boolean</code> (optional)
</li>
<li><code>userFarmType : String</code> (optional)
</li>
<li><code>userPrivateSSHKey : boolean</code> (optional)
</li>
<li><code>vsifType : String</code> (optional)
</li>
<li><code>waitTillSessionEnds : boolean</code> (optional)
</li>
</ul>


++++
=== `vmanagerPostBuildActions`: vManager Post Build Actions
++++
<ul><li><code>vAPIUrl : String</code>
<div><div>
 Verisium Manager expose a REST API interface for API. The REST API is a dedicated process for serving remote http requests - vAPI.
 <br>
  Starting 14.1 s005 The vAPI process is served automatically by the Verisium Manager Server process, and as such you need to supply the following url:
 <br><strong>https://[VMANAGER_HOST:VMANAGER_PORT]/vmgr/vapi</strong>
 <br>
</div></div>

</li>
<li><code>vAPIUser : String</code>
<div><div>
 In case of a secure mode, the userId will be shown as the user who perform the operation within Verisium Manager tool.
 <br>
  In case of open mode, the default userid that will be used is "vapi".
 <br>
</div></div>

</li>
<li><code>vAPIPassword : String</code>
<div><div>
 In case of a secure mode, a password is needed
 <br>
  Please contact Verisium Manager documentation for further info.
 <br>
</div></div>

</li>
<li><code>authRequired : boolean</code>
<div><div>
 Verisium Manager vAPI can operate in one of two modes:
 <br>
 <li>Secured by user/secret key</li>
 <li>Open</li> In case of a secure mode, the userId (vAPI User) will be shown as the user who perform the operation within Verisium Manager tool.
 <br>
  In case of open mode, the default userid that will be used is "vapi".
 <br>
</div></div>

</li>
<li><code>advConfig : boolean</code>
</li>
<li><code>dynamicUserId : boolean</code>
<div><div>
 In case of a need in dynamically selecting the user name per job, the pre-job should place into the workspace directory a file with single line that contains the userid to be used.
 <br>
  The file name should be: ${BUILD_NUMBER}.${BUILD_ID}.user.input"
 <br>
  The job will pick the userid which is in the file, and connect to vAPI using this userid and the vAPI secret key.
</div></div>

</li>
<li><code>connTimeout : int</code>
<div><div>
 Connection Timeout is the time (in minutes) for the Jenkins executor to wait till it establish a connection with the Verisium Manager server. It is usually very fast, so no need to change the default (1 minute).
 <br>
  Setting the time to 0 means an unlimited time. In case it is taking too long to establish a connection, and the time passed is more than the Connection Timeout set, the connection to the Verisium Manager server will be closed, and the Jenkins executor will be able to continue. The vAPI operation will fail (it will not start), and the build will be marked as failed.
 <br>
  If no Connection timeout is set, the default is 1 minutes.
</div></div>

</li>
<li><code>readTimeout : int</code>
<div><div>
 Read Timeout is the time (in minutes) for the Jenkins executor to wait for Verisium Manager server to end the current operation. In heavy operations such as collect compact or ranking, the time to response back can vary, and might even take an hour or so depends on the load the Verisium Manager server is experiencing. 
 <br>
  Setting the time to 0 means an unlimited time. In case the vAPI call is taking too long, and is more than the Read Timeout set, the connection to the Verisium Manager server will be closed, and the Jenkins executor will be able to continue. The vAPI operation will not fail, but the build will be marked as failed.
 <br>
  If no Read timeout is set, the default is 30 minutes.
</div></div>

</li>
<li><code>advancedFunctions : boolean</code>
</li>
<li><code>retrieveSummaryReport : boolean</code>
</li>
<li><code>runReport : boolean</code>
</li>
<li><code>metricsReport : boolean</code>
</li>
<li><code>vPlanReport : boolean</code>
</li>
<li><code>testsViewName : String</code>
</li>
<li><code>metricsViewName : String</code>
</li>
<li><code>vplanViewName : String</code>
</li>
<li><code>testsDepth : int</code>
</li>
<li><code>metricsDepth : int</code>
</li>
<li><code>vPlanDepth : int</code>
</li>
<li><code>metricsInputType : String</code>
</li>
<li><code>metricsAdvanceInput : String</code>
<div><div>
 In case of a need to take advantage of the full summary report flags, you can use a json structure to define the rest of the flags the vAPI supports.
 <br>
  The following structure addresses the flags relevant for the metrics part only (for more information, check the full vAPI electronic docs on the web):
 <br>
  {
 <br>
  "depth": 4,
 <br>
  "instances": true,
 <br>
  "types": true,
 <br>
  "extended": true,
 <br>
  "path": "string",
 <br>
  "scope": "string"
 <br>
  }
 <br>
 <br>
  depth: integer ($int32) (Metrics tree level depth. Default value is the whole tree)
 <br>
  scope: string (Metrics verification scope)
 <br>
  path: string (Full Path to entity in Metrics tree.)
 <br>
  instances: boolean (Specify if vPlan entity is in the instances hierarchy)
 <br>
  types: boolean (Specify if vPlan entity is in the types hierarchy)
 <br>
  extended: boolean (Enables or disables extended metrics report, if not specified the report would be extended according to metrics configuration)
 <br>
 <br>
  None of the fields are mandatory to exclude "depth".
</div></div>

</li>
<li><code>vPlanInputType : String</code>
</li>
<li><code>vPlanAdvanceInput : String</code>
<div><div>
 In case of a need to take advantage of the full summary report flags, you can use a json structure to define the rest of the flags the vAPI supports.
 <br>
  The following structure addresses the flags relevant for the vPlan part only (for more information, check the full vAPI electronic docs on the web):
 <br>
  {
 <br>
  "depth": 4,
 <br>
  "perspective": "string",
 <br>
  "multiPerspectives": [array - look for more information within the documentation] "instances": true,
 <br>
  "types": true,
 <br>
  "extended": true,
 <br>
  "path": "string",
 <br>
  "vplanNode": "string"
 <br>
  }
 <br>
 <br>
  { "depth": 20, "perspective": "APB_UART", "instances": true, "types": true, "extended": true } depth: integer ($int32) (vPlan tree level depth. Default value is the whole tree)
 <br>
  perspective: string (Perspective to report. if not specified the default plan perspective would be used)
 <br>
  multiPerspectives: [...]
 <br>
  vplanNode: string (Full Path to perspective/section/port in vPlan tree.)
 <br>
  path: string (specify if to use vplanNode, instances or types for vPlan entity. If not specified the perspective is used)
 <br>
  instances: boolean (Specify if vPlan entity is in the instances hierarchy)
 <br>
  types: boolean (Specify if vPlan entity is in the types hierarchy)
 <br>
  extended: boolean (Enables or disables extended vplan report. if not specified the report would be extended according to vplan configuration)
 <br>
 <br>
  None of the fields are mandatory to exclude "depth".
</div></div>

</li>
<li><code>vPlanxFileName : String</code>
</li>
<li><code>summaryType : String</code>
</li>
<li><code>ctxInput : boolean</code>
</li>
<li><code>ctxAdvanceInput : String</code>
<div><div>
 In case of a need to take advantage of the full summary report flags, you can use a json structure to define the rest of the flags the vAPI supports.
 <br>
  The following structure addresses the flags relevant for the vPlan and Metrics parts and gives you more control over refinements (for more information, check the full vAPI electronic docs on the web):
 <br>
  {
 <br>
  "depth": 4,
 <br>
  "refinementFile": "string",
 <br>
  "vplanFile": "string",
 <br>
  "vplanRefinementFile": "string",
 <br>
  "environment": "string",
 <br>
  "multiPerspectives": [array - look for more information within the documentation],
 <br>
  "multiPerspectives": [array - look for more information within the documentation],
 <br>
  "multiPerspectives": [array - look for more information within the documentation]
 <br>
  }
 <br>
 <br>
  None of the fields are mandatory, however - please note that adding "vplanFile" here, will overwrite anything you placed within "vPlanx file name".
 <br>
  ("vPlanx file name" field is not mandatory in case you choose to use the advanced context input)
</div></div>

</li>
<li><code>freeVAPISyntax : String</code>
<div><div>
 In case of a need in taking full control over the vAPI parameters of the summary report, the pre-job should place into the workspace directory a file with the json input for the /reports/generate-summary-report vAPI.
 <br>
  The input file should be place into the working directory. In case this field is empty, The file name need to be: ${BUILD_NUMBER}.${BUILD_ID}.summary_report.input
 <br>
  Please fill this field only in case, you want to hard code the input file name, to be consist across all builds. 
 <br>
  Please exclude the "rs" section from this json. This plugin will automatically fill in the "rs" based on the sessions launched during the build process.
 <br>
</div></div>

</li>
<li><code>deleteReportSyntaxInputFile : boolean</code>
</li>
<li><code>vManagerVersion : String</code>
</li>
<li><code>sendEmail : boolean</code>
</li>
<li><code>emailList : String</code>
</li>
<li><code>emailType : String</code>
</li>
<li><code>emailInputFile : String</code>
<div><div>
 In case of a need in providing a dynamic list of email addresses, the pre-job should place into the workspace directory a file with the relevant emails, one email address per line (without a comma between).
 <br>
  The input file should be place into the working directory. In case this field is empty, The file name need to be: ${BUILD_NUMBER}.${BUILD_ID}.emails.input
 <br>
  Please fill this field only in case, you want to hard code the input file name, to be consist across all builds. 
 <br>
  Disclaimer: In case you choose to work with the "free vAPI syntax" option, you have the option to supply the list of emails as part of the free vAPI json structure (optionally) - in such cases, this field will be ignored.
 <br>
</div></div>

</li>
<li><code>deleteEmailInputFile : boolean</code>
</li>
<li><code>summaryMode : String</code>
</li>
<li><code>ignoreSSLError : boolean</code>
<div><div>
 This option is only relevant if you choose Verisium Manager Version &lt; 19.09.
 <br>
  If the Verisium Manager version is smaller than 19.09, the report is being retrieved by parsing the html web page of the report generated using http connection.
 <br>
  Since Verisium Manager Web Server is having by default a self-signed certificate, normal http connection will fail to get validated and the connection will get rejected. 
 <br>
  If you replaced the server certificate with a signed one of your own, you can leave it as default. Unless, if you are using the default Verisium Manager installed self-signed certificate - the only way to overcome its SSL validation is to allow the connection from the Jenkins to the Verisium Manager server at the time of the report retrieval only to skip validation.
</div></div>

</li>
</ul>


++++
