= vRealize Automation 8.x Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/vrealize-automation-8">Visit the Jenkins Plugins site</a>
++++


=== `vraDeleteDeployment`: vRA - Delete Deployment
++++
<div><div>
 Requests the deletion of a deployment and waits for it to complete.
</div></div>
<ul><li><code>deploymentId : String</code> (optional)
</li>
<li><code>deploymentName : String</code> (optional)
</li>
<li><code>domain : String</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>timeout : long</code> (optional)
</li>
<li><code>token : String</code> (optional)
</li>
<li><code>trustSelfSignedCert : boolean</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
<li><code>vraURL : String</code> (optional)
</li>
</ul>


++++
=== `vraDeployFromCatalog`: vRA - Deploy from catalog
++++
<div><div>
 Creates a new deployment from a vRealize Automation catalog item
</div></div>
<ul><li><code>catalogItemName : String</code> (optional)
</li>
<li><code>config : String</code> (optional)
</li>
<li><code>configFormat : String</code> (optional)
</li>
<li><code>count : int</code> (optional)
</li>
<li><code>deploymentName : String</code> (optional)
</li>
<li><code>domain : String</code> (optional)
</li>
<li><code>inputMap</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.Object&gt;</code></li>
</ul></li>
<li><code>inputs : String</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>projectName : String</code> (optional)
</li>
<li><code>reason : String</code> (optional)
</li>
<li><code>timeout : int</code> (optional)
</li>
<li><code>token : String</code> (optional)
</li>
<li><code>trustSelfSignedCert : boolean</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
<li><code>version : String</code> (optional)
</li>
<li><code>vraURL : String</code> (optional)
</li>
</ul>


++++
=== `vraGetDeployment`: vRA - Get Deployment
++++
<div><div>
 Returns the details of a resource action.
</div></div>
<ul><li><code>deploymentId : String</code> (optional)
</li>
<li><code>deploymentName : String</code> (optional)
</li>
<li><code>domain : String</code> (optional)
</li>
<li><code>expandResources : boolean</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>token : String</code> (optional)
</li>
<li><code>trustSelfSignedCert : boolean</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
<li><code>vraURL : String</code> (optional)
</li>
</ul>


++++
=== `vraGetResourceActionDetails`: vRA - Get Resource Action Details
++++
<div><div>
 Returns details of a specific resource action.
</div></div>
<ul><li><code>actionId : String</code> (optional)
</li>
<li><code>deploymentId : String</code> (optional)
</li>
<li><code>deploymentName : String</code> (optional)
</li>
<li><code>domain : String</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>resourceName : String</code> (optional)
</li>
<li><code>token : String</code> (optional)
</li>
<li><code>trustSelfSignedCert : boolean</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
<li><code>vraURL : String</code> (optional)
</li>
</ul>


++++
=== `vraGetResourceActions`: vRA - Get Resource Actions
++++
<div><div>
 Returns the actions available for a resource.
</div></div>
<ul><li><code>deploymentId : String</code> (optional)
</li>
<li><code>deploymentName : String</code> (optional)
</li>
<li><code>domain : String</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>resourceName : String</code> (optional)
</li>
<li><code>token : String</code> (optional)
</li>
<li><code>trustSelfSignedCert : boolean</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
<li><code>vraURL : String</code> (optional)
</li>
</ul>


++++
=== `vraRunAction`: vRA - Run Action
++++
<div><div>
 Runs a day two action against a deployment or a resource within a deployment.
</div></div>
<ul><li><code>actionId : String</code> (optional)
</li>
<li><code>deploymentId : String</code> (optional)
</li>
<li><code>deploymentName : String</code> (optional)
</li>
<li><code>domain : String</code> (optional)
</li>
<li><code>inputMap</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.Object&gt;</code></li>
</ul></li>
<li><code>inputs : String</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>reason : String</code> (optional)
</li>
<li><code>resourceName : String</code> (optional)
</li>
<li><code>timeout : long</code> (optional)
</li>
<li><code>token : String</code> (optional)
</li>
<li><code>trustSelfSignedCert : boolean</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
<li><code>vraURL : String</code> (optional)
</li>
</ul>


++++
=== `vraWaitForAddress`: vRA - Wait for Address
++++
<div><div>
 Waits until a machine within a deployment has obtained an IP address and returns it.
</div></div>
<ul><li><code>deploymentId : String</code> (optional)
</li>
<li><code>deploymentName : String</code> (optional)
</li>
<li><code>domain : String</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>resourceName : String</code> (optional)
</li>
<li><code>timeout : long</code> (optional)
</li>
<li><code>token : String</code> (optional)
</li>
<li><code>trustSelfSignedCert : boolean</code> (optional)
</li>
<li><code>username : String</code> (optional)
</li>
<li><code>vraURL : String</code> (optional)
</li>
</ul>


++++
