= vSphere Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/vsphere-cloud">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'DeleteSnapshot'])`: Delete a Snapshot
++++
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM.
</div></div>

</li>
<li><code>snapshotName : String</code>
<div><div>
 The name of the snapshot.
</div></div>

</li>
<li><code>consolidate : boolean</code>
<div><div>
 Consolidate all redundant redo logs for this VM?
</div></div>

</li>
<li><code>failOnNoExist : boolean</code>
<div><div>
 If the snapshot you are trying to delete doesnt exist, fail this build step. Sometimes, the job doesnt care if deletion was successful and only wants it gone---if this is the case, leave unchecked.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'Deploy'])`: Deploy VM from template
++++
<ul><li><code>template : String</code>
<div><div>
 The name of the vSphere template to clone.
</div></div>

</li>
<li><code>clone : String</code>
<div><div>
 The name of the cloned VM.
</div></div>

</li>
<li><code>linkedClone : boolean</code>
<div><div>
 Linked clones will re-use any read-only disk backings (like snapshots) and create new children for your clone. This will drastically save time, but the disk backings will be shared.
</div></div>

</li>
<li><code>resourcePool : String</code>
<div><div>
 The Resource Pool to be used by the VM. If no resource pool is being used, then leave blank.
</div></div>

</li>
<li><code>cluster : String</code>
<div><div>
 The vCenter cluster to be used by the VM.
</div></div>

</li>
<li><code>datastore : String</code>
<div><div>
 The data store to be used by the VM.
</div></div>

</li>
<li><code>folder : String</code>
<div><div>
 (Optional) VSphere folder path or unique folder name where VM is going to be created. 
 <br>
  If blank, it will be created in the same folder as the original VM. 
 <br>
</div></div>

</li>
<li><code>customizationSpec : String</code>
</li>
<li><code>timeoutInSeconds : int</code>
<div><div>
 The length of time, in seconds, to wait for the new VirtualMachine to be assigned an IP address after it has been powered on. If this value is zero, no attempt will be made to determine the IP address.
</div></div>

</li>
<li><code>powerOn : boolean</code>
<div><div>
 Specifies whether or not the new VirtualMachine should be powered on after creation.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'ExposeGuestInfo'])`: Expose Guest Info
++++
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to expose guest info for.
 <br>
  Variables IpAddress, Hostname, ToolsStatus, ToolsRunningStatus, ToolsVersion, ToolsVersionStatus, GuestState, GuestId, GuestFamily, GuestFullName, AppHeartbeatStatus, GuestOperationsReady, InteractiveGuestOperationsReady are exposed.
</div></div>

</li>
<li><code>envVariablePrefix : String</code>
<div><div>
 Prefix for guest info environmental variables. E.g. for prefix VM1, variables would be VM1_IpAddress, VM1_HostName etc.
</div></div>

</li>
<li><code>waitForIp4 : boolean</code>
</li>
</ul>


++++
=== `step([$class: 'PowerOff'])`: Power-Off VM
++++
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to shut down.
</div></div>

</li>
<li><code>evenIfSuspended : boolean</code>
<div><div>
 If the VM is currently suspended, it will still be shutdown.
</div></div>

</li>
<li><code>shutdownGracefully : boolean</code>
<div><div>
 If the VM is powered on and VMware Tools is running, a graceful shutdown will be attempted by performing a Guest Shutdown. If the VM is still running after the timeout has been reached, a hard power off will be performed.
</div></div>

</li>
<li><code>ignoreIfNotExists : boolean</code>
</li>
<li><code>gracefulShutdownTimeout : int</code> (optional)
<div><div>
 The number of seconds after which the graceful shutdown attempt is abandoned, and hard power off is performed.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'Reconfigure'])`: Reconfigure VM
++++
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM or template to reconfigure.
</div></div>

</li>
<li><code>reconfigureSteps</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'ReconfigureAnnotation'</code><div>
<ul><li><code>annotation : String</code> (optional)
<div><div>
 The text that will be written into the "annotations" field on the VM. This typically shows up in the vSphere UI as the "Notes" for a VM.
</div></div>

</li>
<li><code>append : boolean</code> (optional)
<div><div>
 If set then the text specified in this build step will be appended to the end of any existing text. If not set then the text specified will replace any existing text.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ReconfigureCpu'</code><div>
<ul><li><code>cpuCores : String</code>
<div><div>
 The number of CPU Cores.
</div></div>

</li>
<li><code>coresPerSocket : String</code>
<div><div>
 The number of CPU Cores per Socket.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ReconfigureDisk'</code><div>
<ul><li><code>diskSize : String</code>
</li>
<li><code>datastore : String</code>
<div><div>
 The data store to be used by the disk.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ReconfigureMemory'</code><div>
<ul><li><code>memorySize : String</code>
<div><div>
 The amount of memory (RAM) in megabytes.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ReconfigureNetworkAdapters'</code><div>
<ul><li><code>deviceAction</code>
<ul><li><b>Values:</b> <code>ADD</code>, <code>EDIT</code>, <code>REMOVE</code></li></ul></li>
<li><code>deviceLabel : String</code>
<div><div>
 The name of the network device, such as "Network adapter 1". If blank, the first network adapter will be used.
</div></div>

</li>
<li><code>macAddress : String</code>
<div><div>
 The new MAC address for this network adapter. Leave blank to keep existing or default value.
</div></div>

</li>
<li><code>standardSwitch : boolean</code>
</li>
<li><code>portGroup : String</code>
<div><div>
 The name of the network port group to use. Leave blank to keep existing or default value.
</div></div>

</li>
<li><code>distributedSwitch : boolean</code>
</li>
<li><code>distributedPortGroup : String</code>
<div><div>
 Specifies the Distributed Switch Port Group.
</div></div>

</li>
<li><code>distributedPortId : String</code>
<div><div>
 Port Id to be used from the specified Distributed Switch Port Group.
</div></div>

</li>
</ul></div></li>
</ul></li>
</ul>


++++
=== `step([$class: 'Rename'])`: Rename VM
++++
<ul><li><code>oldName : String</code>
<div><div>
 The old name of the VM or template to be renamed.
</div></div>

</li>
<li><code>newName : String</code>
<div><div>
 The new name of the VM or template.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'RenameSnapshot'])`: Rename Snapshot
++++
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM or template.
</div></div>

</li>
<li><code>oldName : String</code>
<div><div>
 The old name of the snapshot to be renamed.
</div></div>

</li>
<li><code>newName : String</code>
<div><div>
 The new name of the snapshot.
</div></div>

</li>
<li><code>newDescription : String</code>
<div><div>
 The new description of the snapshot.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'RevertToSnapshot'])`: Revert to Snapshot
++++
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM.
</div></div>

</li>
<li><code>snapshotName : String</code>
<div><div>
 The name of the snapshot.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'SuspendVm'])`: Suspend VM
++++
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to suspend.
</div></div>

</li>
</ul>


++++
=== `step([$class: 'TakeSnapshot'])`: Take Snapshot
++++
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM you'd like to take a snapshot of.
</div></div>

</li>
<li><code>snapshotName : String</code>
<div><div>
 The name of the snapshot.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 The description to be saved with the snapshot.
</div></div>

</li>
<li><code>includeMemory : boolean</code>
<div><div>
 Would you like to save the active memory in the snapshot?
</div></div>

</li>
</ul>


++++
=== `step([$class: 'VSphereBuildStepContainer'])`: vSphere Build Step
++++
<ul><li><code>buildStep</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'Clone'</code><div>
<ul><li><code>sourceName : String</code>
<div><div>
 The name of the vSphere VM or template to clone.
</div></div>

</li>
<li><code>clone : String</code>
<div><div>
 The name of the cloned VM.
</div></div>

</li>
<li><code>linkedClone : boolean</code>
<div><div>
 Linked clones will re-use any read-only disk backings (like snapshots) and create new children for your clone. This will drastically save time, but the disk backings will be shared.
</div></div>

</li>
<li><code>resourcePool : String</code>
<div><div>
 The Resource Pool to be used by the VM. Leave it blank to use the same resource pool as the source VM. Must be specified if source VM is a template.
</div></div>

</li>
<li><code>cluster : String</code>
<div><div>
 The vCenter cluster to be used by the VM.
</div></div>

</li>
<li><code>datastore : String</code>
<div><div>
 The data store to be used by the VM.
</div></div>

</li>
<li><code>folder : String</code>
<div><div>
 (Optional) VSphere folder path or unique folder name where VM is going to be created. 
 <br>
  If blank, it will be created in the same folder as the original VM. 
 <br>
</div></div>

</li>
<li><code>powerOn : boolean</code>
<div><div>
 Specifies whether or not the new VirtualMachine should be powered on after creation.
</div></div>

</li>
<li><code>timeoutInSeconds : int</code>
<div><div>
 The length of time, in seconds, to wait for the new VirtualMachine to be assigned an IP address after it has been powered on. If this value is zero, no attempt will be made to determine the IP address.
</div></div>

</li>
<li><code>customizationSpec : String</code>
<div><div>
 The customization specification name, as defined under 'Policies and Profiles'
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ConvertToTemplate'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to be converted to a template.
</div></div>

</li>
<li><code>force : boolean</code>
<div><div>
 Check this if you want to force the conversion in the case where the VM is not already powered down.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ConvertToVm'</code><div>
<ul><li><code>template : String</code>
<div><div>
 The name of the template to be converted to a Virtual Machine.
</div></div>

</li>
<li><code>resourcePool : String</code>
<div><div>
 The Resource Pool to be used by the VM.
</div></div>

</li>
<li><code>cluster : String</code>
<div><div>
 The vCenter cluster to be used by the VM.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'Delete'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to be destroyed. This is a destructive operation that cannot be undone!
</div></div>

</li>
<li><code>failOnNoExist : boolean</code>
<div><div>
 If the VM you are trying to delete doesnt exist, fail this build step. Sometimes, the job doesnt care if deletion was successful and only wants it gone---if this is the case, leave unchecked.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DeleteSnapshot'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM.
</div></div>

</li>
<li><code>snapshotName : String</code>
<div><div>
 The name of the snapshot.
</div></div>

</li>
<li><code>consolidate : boolean</code>
<div><div>
 Consolidate all redundant redo logs for this VM?
</div></div>

</li>
<li><code>failOnNoExist : boolean</code>
<div><div>
 If the snapshot you are trying to delete doesnt exist, fail this build step. Sometimes, the job doesnt care if deletion was successful and only wants it gone---if this is the case, leave unchecked.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'Deploy'</code><div>
<ul><li><code>template : String</code>
<div><div>
 The name of the vSphere template to clone.
</div></div>

</li>
<li><code>clone : String</code>
<div><div>
 The name of the cloned VM.
</div></div>

</li>
<li><code>linkedClone : boolean</code>
<div><div>
 Linked clones will re-use any read-only disk backings (like snapshots) and create new children for your clone. This will drastically save time, but the disk backings will be shared.
</div></div>

</li>
<li><code>resourcePool : String</code>
<div><div>
 The Resource Pool to be used by the VM. If no resource pool is being used, then leave blank.
</div></div>

</li>
<li><code>cluster : String</code>
<div><div>
 The vCenter cluster to be used by the VM.
</div></div>

</li>
<li><code>datastore : String</code>
<div><div>
 The data store to be used by the VM.
</div></div>

</li>
<li><code>folder : String</code>
<div><div>
 (Optional) VSphere folder path or unique folder name where VM is going to be created. 
 <br>
  If blank, it will be created in the same folder as the original VM. 
 <br>
</div></div>

</li>
<li><code>customizationSpec : String</code>
</li>
<li><code>timeoutInSeconds : int</code>
<div><div>
 The length of time, in seconds, to wait for the new VirtualMachine to be assigned an IP address after it has been powered on. If this value is zero, no attempt will be made to determine the IP address.
</div></div>

</li>
<li><code>powerOn : boolean</code>
<div><div>
 Specifies whether or not the new VirtualMachine should be powered on after creation.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ExposeGuestInfo'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to expose guest info for.
 <br>
  Variables IpAddress, Hostname, ToolsStatus, ToolsRunningStatus, ToolsVersion, ToolsVersionStatus, GuestState, GuestId, GuestFamily, GuestFullName, AppHeartbeatStatus, GuestOperationsReady, InteractiveGuestOperationsReady are exposed.
</div></div>

</li>
<li><code>envVariablePrefix : String</code>
<div><div>
 Prefix for guest info environmental variables. E.g. for prefix VM1, variables would be VM1_IpAddress, VM1_HostName etc.
</div></div>

</li>
<li><code>waitForIp4 : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'PowerOff'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to shut down.
</div></div>

</li>
<li><code>evenIfSuspended : boolean</code>
<div><div>
 If the VM is currently suspended, it will still be shutdown.
</div></div>

</li>
<li><code>shutdownGracefully : boolean</code>
<div><div>
 If the VM is powered on and VMware Tools is running, a graceful shutdown will be attempted by performing a Guest Shutdown. If the VM is still running after the timeout has been reached, a hard power off will be performed.
</div></div>

</li>
<li><code>ignoreIfNotExists : boolean</code>
</li>
<li><code>gracefulShutdownTimeout : int</code> (optional)
<div><div>
 The number of seconds after which the graceful shutdown attempt is abandoned, and hard power off is performed.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PowerOn'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to power on.
</div></div>

</li>
<li><code>timeoutInSeconds : int</code>
<div><div>
 The maximum number of seconds to wait for the IP.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'Reconfigure'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM or template to reconfigure.
</div></div>

</li>
<li><code>reconfigureSteps</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'ReconfigureAnnotation'</code><div>
<ul><li><code>annotation : String</code> (optional)
<div><div>
 The text that will be written into the "annotations" field on the VM. This typically shows up in the vSphere UI as the "Notes" for a VM.
</div></div>

</li>
<li><code>append : boolean</code> (optional)
<div><div>
 If set then the text specified in this build step will be appended to the end of any existing text. If not set then the text specified will replace any existing text.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ReconfigureCpu'</code><div>
<ul><li><code>cpuCores : String</code>
<div><div>
 The number of CPU Cores.
</div></div>

</li>
<li><code>coresPerSocket : String</code>
<div><div>
 The number of CPU Cores per Socket.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ReconfigureDisk'</code><div>
<ul><li><code>diskSize : String</code>
</li>
<li><code>datastore : String</code>
<div><div>
 The data store to be used by the disk.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ReconfigureMemory'</code><div>
<ul><li><code>memorySize : String</code>
<div><div>
 The amount of memory (RAM) in megabytes.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ReconfigureNetworkAdapters'</code><div>
<ul><li><code>deviceAction</code>
<ul><li><b>Values:</b> <code>ADD</code>, <code>EDIT</code>, <code>REMOVE</code></li></ul></li>
<li><code>deviceLabel : String</code>
<div><div>
 The name of the network device, such as "Network adapter 1". If blank, the first network adapter will be used.
</div></div>

</li>
<li><code>macAddress : String</code>
<div><div>
 The new MAC address for this network adapter. Leave blank to keep existing or default value.
</div></div>

</li>
<li><code>standardSwitch : boolean</code>
</li>
<li><code>portGroup : String</code>
<div><div>
 The name of the network port group to use. Leave blank to keep existing or default value.
</div></div>

</li>
<li><code>distributedSwitch : boolean</code>
</li>
<li><code>distributedPortGroup : String</code>
<div><div>
 Specifies the Distributed Switch Port Group.
</div></div>

</li>
<li><code>distributedPortId : String</code>
<div><div>
 Port Id to be used from the specified Distributed Switch Port Group.
</div></div>

</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'Rename'</code><div>
<ul><li><code>oldName : String</code>
<div><div>
 The old name of the VM or template to be renamed.
</div></div>

</li>
<li><code>newName : String</code>
<div><div>
 The new name of the VM or template.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'RenameSnapshot'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM or template.
</div></div>

</li>
<li><code>oldName : String</code>
<div><div>
 The old name of the snapshot to be renamed.
</div></div>

</li>
<li><code>newName : String</code>
<div><div>
 The new name of the snapshot.
</div></div>

</li>
<li><code>newDescription : String</code>
<div><div>
 The new description of the snapshot.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'RevertToSnapshot'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM.
</div></div>

</li>
<li><code>snapshotName : String</code>
<div><div>
 The name of the snapshot.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SuspendVm'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to suspend.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'TakeSnapshot'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM you'd like to take a snapshot of.
</div></div>

</li>
<li><code>snapshotName : String</code>
<div><div>
 The name of the snapshot.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 The description to be saved with the snapshot.
</div></div>

</li>
<li><code>includeMemory : boolean</code>
<div><div>
 Would you like to save the active memory in the snapshot?
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>serverName : String</code>
<div><div>
 The vSphere configuration to use. Use ${VSPHERE_CLOUD_NAME} and create a vsphere selection parameter if you want to dynamically select the vSphere configuration.
 <br>
  A vsphere selection parameter is the same as a string parameter named VSPHERE_CLOUD_NAME but allows easy selection of a vsphere cloud.
</div></div>

</li>
</ul>


++++
=== `vSphere`: Invoke an vSphere action, exposing the VM IP under some actions
++++
<div><div>
 Execute vCenter actions. Reusing vSphereBuildStep forms, cut properly exposing VSPHERE_IP for PowerOn, Deploy and Clone options.
</div></div>
<ul><li><code>buildStep</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'Clone'</code><div>
<ul><li><code>sourceName : String</code>
<div><div>
 The name of the vSphere VM or template to clone.
</div></div>

</li>
<li><code>clone : String</code>
<div><div>
 The name of the cloned VM.
</div></div>

</li>
<li><code>linkedClone : boolean</code>
<div><div>
 Linked clones will re-use any read-only disk backings (like snapshots) and create new children for your clone. This will drastically save time, but the disk backings will be shared.
</div></div>

</li>
<li><code>resourcePool : String</code>
<div><div>
 The Resource Pool to be used by the VM. Leave it blank to use the same resource pool as the source VM. Must be specified if source VM is a template.
</div></div>

</li>
<li><code>cluster : String</code>
<div><div>
 The vCenter cluster to be used by the VM.
</div></div>

</li>
<li><code>datastore : String</code>
<div><div>
 The data store to be used by the VM.
</div></div>

</li>
<li><code>folder : String</code>
<div><div>
 (Optional) VSphere folder path or unique folder name where VM is going to be created. 
 <br>
  If blank, it will be created in the same folder as the original VM. 
 <br>
</div></div>

</li>
<li><code>powerOn : boolean</code>
<div><div>
 Specifies whether or not the new VirtualMachine should be powered on after creation.
</div></div>

</li>
<li><code>timeoutInSeconds : int</code>
<div><div>
 The length of time, in seconds, to wait for the new VirtualMachine to be assigned an IP address after it has been powered on. If this value is zero, no attempt will be made to determine the IP address.
</div></div>

</li>
<li><code>customizationSpec : String</code>
<div><div>
 The customization specification name, as defined under 'Policies and Profiles'
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ConvertToTemplate'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to be converted to a template.
</div></div>

</li>
<li><code>force : boolean</code>
<div><div>
 Check this if you want to force the conversion in the case where the VM is not already powered down.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ConvertToVm'</code><div>
<ul><li><code>template : String</code>
<div><div>
 The name of the template to be converted to a Virtual Machine.
</div></div>

</li>
<li><code>resourcePool : String</code>
<div><div>
 The Resource Pool to be used by the VM.
</div></div>

</li>
<li><code>cluster : String</code>
<div><div>
 The vCenter cluster to be used by the VM.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'Delete'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to be destroyed. This is a destructive operation that cannot be undone!
</div></div>

</li>
<li><code>failOnNoExist : boolean</code>
<div><div>
 If the VM you are trying to delete doesnt exist, fail this build step. Sometimes, the job doesnt care if deletion was successful and only wants it gone---if this is the case, leave unchecked.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DeleteSnapshot'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM.
</div></div>

</li>
<li><code>snapshotName : String</code>
<div><div>
 The name of the snapshot.
</div></div>

</li>
<li><code>consolidate : boolean</code>
<div><div>
 Consolidate all redundant redo logs for this VM?
</div></div>

</li>
<li><code>failOnNoExist : boolean</code>
<div><div>
 If the snapshot you are trying to delete doesnt exist, fail this build step. Sometimes, the job doesnt care if deletion was successful and only wants it gone---if this is the case, leave unchecked.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'Deploy'</code><div>
<ul><li><code>template : String</code>
<div><div>
 The name of the vSphere template to clone.
</div></div>

</li>
<li><code>clone : String</code>
<div><div>
 The name of the cloned VM.
</div></div>

</li>
<li><code>linkedClone : boolean</code>
<div><div>
 Linked clones will re-use any read-only disk backings (like snapshots) and create new children for your clone. This will drastically save time, but the disk backings will be shared.
</div></div>

</li>
<li><code>resourcePool : String</code>
<div><div>
 The Resource Pool to be used by the VM. If no resource pool is being used, then leave blank.
</div></div>

</li>
<li><code>cluster : String</code>
<div><div>
 The vCenter cluster to be used by the VM.
</div></div>

</li>
<li><code>datastore : String</code>
<div><div>
 The data store to be used by the VM.
</div></div>

</li>
<li><code>folder : String</code>
<div><div>
 (Optional) VSphere folder path or unique folder name where VM is going to be created. 
 <br>
  If blank, it will be created in the same folder as the original VM. 
 <br>
</div></div>

</li>
<li><code>customizationSpec : String</code>
</li>
<li><code>timeoutInSeconds : int</code>
<div><div>
 The length of time, in seconds, to wait for the new VirtualMachine to be assigned an IP address after it has been powered on. If this value is zero, no attempt will be made to determine the IP address.
</div></div>

</li>
<li><code>powerOn : boolean</code>
<div><div>
 Specifies whether or not the new VirtualMachine should be powered on after creation.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ExposeGuestInfo'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to expose guest info for.
 <br>
  Variables IpAddress, Hostname, ToolsStatus, ToolsRunningStatus, ToolsVersion, ToolsVersionStatus, GuestState, GuestId, GuestFamily, GuestFullName, AppHeartbeatStatus, GuestOperationsReady, InteractiveGuestOperationsReady are exposed.
</div></div>

</li>
<li><code>envVariablePrefix : String</code>
<div><div>
 Prefix for guest info environmental variables. E.g. for prefix VM1, variables would be VM1_IpAddress, VM1_HostName etc.
</div></div>

</li>
<li><code>waitForIp4 : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'PowerOff'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to shut down.
</div></div>

</li>
<li><code>evenIfSuspended : boolean</code>
<div><div>
 If the VM is currently suspended, it will still be shutdown.
</div></div>

</li>
<li><code>shutdownGracefully : boolean</code>
<div><div>
 If the VM is powered on and VMware Tools is running, a graceful shutdown will be attempted by performing a Guest Shutdown. If the VM is still running after the timeout has been reached, a hard power off will be performed.
</div></div>

</li>
<li><code>ignoreIfNotExists : boolean</code>
</li>
<li><code>gracefulShutdownTimeout : int</code> (optional)
<div><div>
 The number of seconds after which the graceful shutdown attempt is abandoned, and hard power off is performed.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PowerOn'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to power on.
</div></div>

</li>
<li><code>timeoutInSeconds : int</code>
<div><div>
 The maximum number of seconds to wait for the IP.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'Reconfigure'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM or template to reconfigure.
</div></div>

</li>
<li><code>reconfigureSteps</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'ReconfigureAnnotation'</code><div>
<ul><li><code>annotation : String</code> (optional)
<div><div>
 The text that will be written into the "annotations" field on the VM. This typically shows up in the vSphere UI as the "Notes" for a VM.
</div></div>

</li>
<li><code>append : boolean</code> (optional)
<div><div>
 If set then the text specified in this build step will be appended to the end of any existing text. If not set then the text specified will replace any existing text.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ReconfigureCpu'</code><div>
<ul><li><code>cpuCores : String</code>
<div><div>
 The number of CPU Cores.
</div></div>

</li>
<li><code>coresPerSocket : String</code>
<div><div>
 The number of CPU Cores per Socket.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ReconfigureDisk'</code><div>
<ul><li><code>diskSize : String</code>
</li>
<li><code>datastore : String</code>
<div><div>
 The data store to be used by the disk.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ReconfigureMemory'</code><div>
<ul><li><code>memorySize : String</code>
<div><div>
 The amount of memory (RAM) in megabytes.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ReconfigureNetworkAdapters'</code><div>
<ul><li><code>deviceAction</code>
<ul><li><b>Values:</b> <code>ADD</code>, <code>EDIT</code>, <code>REMOVE</code></li></ul></li>
<li><code>deviceLabel : String</code>
<div><div>
 The name of the network device, such as "Network adapter 1". If blank, the first network adapter will be used.
</div></div>

</li>
<li><code>macAddress : String</code>
<div><div>
 The new MAC address for this network adapter. Leave blank to keep existing or default value.
</div></div>

</li>
<li><code>standardSwitch : boolean</code>
</li>
<li><code>portGroup : String</code>
<div><div>
 The name of the network port group to use. Leave blank to keep existing or default value.
</div></div>

</li>
<li><code>distributedSwitch : boolean</code>
</li>
<li><code>distributedPortGroup : String</code>
<div><div>
 Specifies the Distributed Switch Port Group.
</div></div>

</li>
<li><code>distributedPortId : String</code>
<div><div>
 Port Id to be used from the specified Distributed Switch Port Group.
</div></div>

</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'Rename'</code><div>
<ul><li><code>oldName : String</code>
<div><div>
 The old name of the VM or template to be renamed.
</div></div>

</li>
<li><code>newName : String</code>
<div><div>
 The new name of the VM or template.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'RenameSnapshot'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM or template.
</div></div>

</li>
<li><code>oldName : String</code>
<div><div>
 The old name of the snapshot to be renamed.
</div></div>

</li>
<li><code>newName : String</code>
<div><div>
 The new name of the snapshot.
</div></div>

</li>
<li><code>newDescription : String</code>
<div><div>
 The new description of the snapshot.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'RevertToSnapshot'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM.
</div></div>

</li>
<li><code>snapshotName : String</code>
<div><div>
 The name of the snapshot.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SuspendVm'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM to suspend.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'TakeSnapshot'</code><div>
<ul><li><code>vm : String</code>
<div><div>
 The name of the VM you'd like to take a snapshot of.
</div></div>

</li>
<li><code>snapshotName : String</code>
<div><div>
 The name of the snapshot.
</div></div>

</li>
<li><code>description : String</code>
<div><div>
 The description to be saved with the snapshot.
</div></div>

</li>
<li><code>includeMemory : boolean</code>
<div><div>
 Would you like to save the active memory in the snapshot?
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>serverName : String</code> (optional)
</li>
</ul>


++++
