= Pipeline: Groovy
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/workflow-cps">Visit the Jenkins Plugins site</a>
++++


=== `load`: Evaluate a Groovy source file into the Pipeline script
++++
<div><div>
 Takes a filename in the workspace and runs it as Groovy source text. 
 <p>The loaded file can contain statements at top level or just load and run a closure. For example:</p>
 <pre>    def pipeline
    node('agent') {
        pipeline = load 'pipeline.groovy'
        pipeline.functionA()
    }
    pipeline.functionB()
    </pre>
 <p>Where <code>pipeline.groovy</code> defines functionA and functionB functions (among others) before ending with <code>return this;</code></p>
 <p></p>
</div></div>
<ul><li><code>path : String</code>
<div><p>Current directory (<code>pwd()</code>) relative path to the Groovy file to load.</p></div>

</li>
</ul>


++++
=== `parallel`: Execute in parallel
++++
<div>
    <p>
        Takes a map from branch names to closures and an optional argument <code>failFast</code>
        which will terminate all branches upon a failure in any other branch:
    </p>
    <pre>
    parallel firstBranch: {
        // do something
    }, secondBranch: {
        // do something else
    },
    failFast: true|false
    </pre>
</div>


++++
