= Worksoft Execution Manager Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/ws-execution-manager">Visit the Jenkins Plugins site</a>
++++


=== `execMan`: Run Execution Manager Request
++++
<ul><li><code>requestType : String</code> (optional)
</li>
<li><code>altEMConfig</code> (optional)
<div><div>
 Optional alternative Execution Manager configuration. If provided, these parameters override those specified in Jenkins global configuration.
</div></div>

<ul><b>Nested Object</b>
<li><code>url : String</code>
</li>
<li><code>credentials : String</code>
</li>
</ul></li>
<li><code>bookmark</code> (optional)
<div><div>
 Select this to run a predefined bookmark configured on the Execution Manager via the Management Studio.
</div></div>

<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>folder : String</code> (optional)
</li>
</ul></li>
<li><code>execParams</code> (optional)
<div><div>
 Optional execution request parameters. Both a key and value must be specified. The value can refer to Jenkins environment variables using this syntax - <b>${</b><em>JENKINS_ENV_VAR</em><b>}</b>. For example - <b>${BUILD_ID}</b>.
</div></div>

<ul><b>Nested Object</b>
<li><code>list</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>key : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></li>
</ul></li>
<li><code>postExecute</code> (optional)
<div><div>
 Optional post execution action. To perform any post action, provide action name along with the need parameters.
</div></div>

<ul><b>Nested Object</b>
<li><code>action : String</code>
</li>
<li><code>params : String</code>
</li>
</ul></li>
<li><code>processList</code> (optional)
<div><div>
 Select this to execute a list of Certify processes without creating a request or bookmark first.
</div></div>

<ul><b>Nested Object</b>
<li><code>database : String</code>
<div><div>
 Alias name of the Certify connection saved in Management Studio &gt; Configuration &gt; Certify Configuration.
</div></div>

</li>
<li><code>project : String</code>
<div><div>
 Certify project where processes reside.
</div></div>

</li>
<li><code>processes</code>
<div><div>
 List of the fully qualified path to each process.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>processPath : String</code>
</li>
</ul></li>
<li><code>folder : String</code>
<div><div>
 Folder where Certify Results will be saved. If not specified, results go to the root results folder.
</div></div>

</li>
<li><code>requestName : String</code>
<div><div>
 Name given to the request execution.
</div></div>

</li>
</ul></li>
<li><code>request</code> (optional)
<div><div>
 Select this to run a predefined request configured on the Execution Manager.
</div></div>

<ul><b>Nested Object</b>
<li><code>name : String</code>
</li>
</ul></li>
<li><code>waitConfig</code> (optional)
<div><div>
 Optional execution request wait configuration. Both the polling interval and maximum run time must be specified in seconds.
</div></div>

<ul><b>Nested Object</b>
<li><code>pollInterval : String</code>
</li>
<li><code>maxRunTime : String</code>
</li>
</ul></li>
</ul>


++++
