= Web Security Application Project (WSAP)
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/wsap">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'WsapBuilder'])`: Web Security Application Project (WSAP)
++++
<ul><li><code>wsapLocation : String</code>
</li>
<li><code>envVar : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>targetUrl : String</code>
</li>
<li><code>ipAddress : String</code>
</li>
<li><code>port : int</code>
</li>
<li><code>apiKey : String</code>
</li>
<li><code>sastAnalysis</code>
<ul><b>Nested Object</b>
<li><code>target : String</code>
</li>
</ul></li>
<li><code>dastAnalysis</code>
<ul><b>Nested Object</b>
<li><code>scanMethod</code>
<ul><b>Nested Object</b>
<li><code>scan : String</code>
</li>
<li><code>apiUrl : String</code>
</li>
<li><code>apiDefinition : String</code>
</li>
</ul></li>
<li><code>includeUrls</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'DASTAnalysis'</code><div>
</div></li>
<li><code>$class: 'ExcludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'HeaderEntry'</code><div>
<ul><li><code>header : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'IncludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'LoginProperties'</code><div>
<ul><li><code>useLogin : boolean</code>
</li>
<li><code>loginUrl : String</code>
</li>
<li><code>requestJson : String</code>
</li>
<li><code>usernameField : String</code>
</li>
<li><code>passwordField : String</code>
</li>
<li><code>loggedInRegex : String</code>
</li>
<li><code>loggedOutRegex : String</code>
</li>
<li><code>headers</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'DASTAnalysis'</code><div>
</div></li>
<li><code>$class: 'ExcludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'HeaderEntry'</code><div>
<ul><li><code>header : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'IncludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'LoginProperties'</code><div>
</div></li>
<li><code>$class: 'SASTAnalysis'</code><div>
<ul><li><code>target : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ScanMethod'</code><div>
<ul><li><code>scan : String</code>
</li>
<li><code>apiUrl : String</code>
</li>
<li><code>apiDefinition : String</code>
</li>
</ul></div></li>
<li><code>$class: 'UserEntry'</code><div>
<ul><li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>users</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'DASTAnalysis'</code><div>
</div></li>
<li><code>$class: 'ExcludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'HeaderEntry'</code><div>
<ul><li><code>header : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'IncludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'LoginProperties'</code><div>
</div></li>
<li><code>$class: 'SASTAnalysis'</code><div>
<ul><li><code>target : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ScanMethod'</code><div>
<ul><li><code>scan : String</code>
</li>
<li><code>apiUrl : String</code>
</li>
<li><code>apiDefinition : String</code>
</li>
</ul></div></li>
<li><code>$class: 'UserEntry'</code><div>
<ul><li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'SASTAnalysis'</code><div>
<ul><li><code>target : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ScanMethod'</code><div>
<ul><li><code>scan : String</code>
</li>
<li><code>apiUrl : String</code>
</li>
<li><code>apiDefinition : String</code>
</li>
</ul></div></li>
<li><code>$class: 'UserEntry'</code><div>
<ul><li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>excludeUrls</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'DASTAnalysis'</code><div>
</div></li>
<li><code>$class: 'ExcludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'HeaderEntry'</code><div>
<ul><li><code>header : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'IncludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'LoginProperties'</code><div>
<ul><li><code>useLogin : boolean</code>
</li>
<li><code>loginUrl : String</code>
</li>
<li><code>requestJson : String</code>
</li>
<li><code>usernameField : String</code>
</li>
<li><code>passwordField : String</code>
</li>
<li><code>loggedInRegex : String</code>
</li>
<li><code>loggedOutRegex : String</code>
</li>
<li><code>headers</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'DASTAnalysis'</code><div>
</div></li>
<li><code>$class: 'ExcludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'HeaderEntry'</code><div>
<ul><li><code>header : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'IncludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'LoginProperties'</code><div>
</div></li>
<li><code>$class: 'SASTAnalysis'</code><div>
<ul><li><code>target : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ScanMethod'</code><div>
<ul><li><code>scan : String</code>
</li>
<li><code>apiUrl : String</code>
</li>
<li><code>apiDefinition : String</code>
</li>
</ul></div></li>
<li><code>$class: 'UserEntry'</code><div>
<ul><li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>users</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'DASTAnalysis'</code><div>
</div></li>
<li><code>$class: 'ExcludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'HeaderEntry'</code><div>
<ul><li><code>header : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'IncludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'LoginProperties'</code><div>
</div></li>
<li><code>$class: 'SASTAnalysis'</code><div>
<ul><li><code>target : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ScanMethod'</code><div>
<ul><li><code>scan : String</code>
</li>
<li><code>apiUrl : String</code>
</li>
<li><code>apiDefinition : String</code>
</li>
</ul></div></li>
<li><code>$class: 'UserEntry'</code><div>
<ul><li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'SASTAnalysis'</code><div>
<ul><li><code>target : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ScanMethod'</code><div>
<ul><li><code>scan : String</code>
</li>
<li><code>apiUrl : String</code>
</li>
<li><code>apiDefinition : String</code>
</li>
</ul></div></li>
<li><code>$class: 'UserEntry'</code><div>
<ul><li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>loginProperties</code>
<ul><b>Nested Object</b>
<li><code>useLogin : boolean</code>
</li>
<li><code>loginUrl : String</code>
</li>
<li><code>requestJson : String</code>
</li>
<li><code>usernameField : String</code>
</li>
<li><code>passwordField : String</code>
</li>
<li><code>loggedInRegex : String</code>
</li>
<li><code>loggedOutRegex : String</code>
</li>
<li><code>headers</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'DASTAnalysis'</code><div>
</div></li>
<li><code>$class: 'ExcludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'HeaderEntry'</code><div>
<ul><li><code>header : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'IncludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'LoginProperties'</code><div>
</div></li>
<li><code>$class: 'SASTAnalysis'</code><div>
<ul><li><code>target : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ScanMethod'</code><div>
<ul><li><code>scan : String</code>
</li>
<li><code>apiUrl : String</code>
</li>
<li><code>apiDefinition : String</code>
</li>
</ul></div></li>
<li><code>$class: 'UserEntry'</code><div>
<ul><li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>users</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'DASTAnalysis'</code><div>
</div></li>
<li><code>$class: 'ExcludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'HeaderEntry'</code><div>
<ul><li><code>header : String</code>
</li>
<li><code>value : String</code>
</li>
</ul></div></li>
<li><code>$class: 'IncludeEntry'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'LoginProperties'</code><div>
</div></li>
<li><code>$class: 'SASTAnalysis'</code><div>
<ul><li><code>target : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ScanMethod'</code><div>
<ul><li><code>scan : String</code>
</li>
<li><code>apiUrl : String</code>
</li>
<li><code>apiDefinition : String</code>
</li>
</ul></div></li>
<li><code>$class: 'UserEntry'</code><div>
<ul><li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
</ul></div></li>
</ul></li>
</ul></li>
</ul></li>
</ul>


++++
