= XebiaLabs XL Release Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/xlrelease-plugin">Visit the Jenkins Plugins site</a>
++++


=== `xlrCreateRelease`: Create and invoke a XLR release
++++
<div><div>
 Adds a step to create and start a release on an XL Release server using Jenkins.
</div></div>
<ul><li><code>serverCredentials : String</code>
<div><div>
 XL Release server credentials used to connect to the XL Release server. This must be configured under Manage Jenkins &gt;&gt; Configure System &gt;&gt; XL Release.
</div></div>

</li>
<li><code>template : String</code>
<div><div>
 Template name or path to use when creating a new release in XL Release. For example: Samples &amp; Tutorials/Configure XL Release or Sample Release Template
</div></div>

</li>
<li><code>releaseTitle : String</code>
<div><div>
 Title of the release in XL Release. Jenkins environment variables can be used to specify this value. For example: Release for $BUILD_TAG
</div></div>

</li>
<li><code>version : String</code> (optional)
<div><div>
 Title of the newly created release in XL Release. Jenkins environment variables can be used to specify this value. For example: Release for $BUILD_TAG 
 <br>
 <div>
  <b>Warning:</b> This parameter is deprecated and will be removed in a future release. Use releaseTitle instead.
 </div>
</div></div>

</li>
<li><code>variables</code> (optional)
<div><div>
 If the template has variables, define them using this parameter. For example: variables: [[propertyName: 'QA environment', propertyValue: 'QA'], [propertyName: 'packageId', propertyValue: '1.0']]
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>propertyName : String</code>
</li>
<li><code>propertyValue : String</code>
</li>
</ul></li>
<li><code>startRelease : boolean</code> (optional)
<div><div>
 Set to true to start the release after it is created. Set to false to create the release without starting it.
</div></div>

</li>
<li><code>overrideCredentialId : String</code> (optional)
</li>
</ul>


++++
