= Xray - Test Management for Jira Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/xray-connector">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'XrayExportBuilder'])`: Xray: Cucumber Features Export Task
++++
<ul><li><code>serverInstance : String</code>
</li>
<li><code>issues : String</code>
<div><div>
 Please fill this field with the issue keys separated by ";".
</div></div>

</li>
<li><code>filter : String</code>
<div><div>
 Please fill this field with the filter id.
</div></div>

</li>
<li><code>filePath : String</code>
<div><div>
 The default value is "/features"
</div></div>

</li>
<li><code>credentialId : String</code>
</li>
<li><code>fields</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>xrayInstance</code> (optional)
<ul><b>Nested Object</b>
<li><code>configID : String</code>
</li>
<li><code>alias : String</code>
</li>
<li><code>hosting</code>
<ul><li><b>Values:</b> <code>SERVER</code>, <code>CLOUD</code></li></ul></li>
<li><code>serverAddress : String</code>
</li>
<li><code>credentialId : String</code>
</li>
</ul></li>
</ul>


++++
=== `step([$class: 'XrayImportBuilder'])`: Xray: Results Import Task
++++
<ul><li><code>serverInstance : String</code>
</li>
<li><code>endpointName : String</code>
</li>
<li><code>projectKey : String</code>
</li>
<li><code>testEnvironments : String</code>
</li>
<li><code>testPlanKey : String</code>
</li>
<li><code>fixVersion : String</code>
</li>
<li><code>importFilePath : String</code>
<div><div>
 The default value is "/features/result.json". Either specify the path and name to the new file or rename the json file to "result.json" and move it inside the features folder.
</div></div>

</li>
<li><code>testExecKey : String</code>
</li>
<li><code>revision : String</code>
</li>
<li><code>importInfo : String</code>
</li>
<li><code>testImportInfo : String</code>
</li>
<li><code>inputInfoSwitcher : String</code>
</li>
<li><code>inputTestInfoSwitcher : String</code>
</li>
<li><code>importToSameExecution : String</code>
</li>
<li><code>credentialId : String</code>
</li>
<li><code>importInParallel : String</code>
</li>
<li><code>dynamicFields</code> (optional)
<ul><li><b>Type:</b> <code>java.util.Map&lt;java.lang.String, java.lang.String&gt;</code></li>
</ul></li>
<li><code>endpoint</code> (optional)
<ul><li><b>Values:</b> <code>XRAY</code>, <code>XRAY_MULTIPART</code>, <code>CUCUMBER</code>, <code>CUCUMBER_MULTIPART</code>, <code>BEHAVE</code>, <code>BEHAVE_MULTIPART</code>, <code>JUNIT</code>, <code>JUNIT_MULTIPART</code>, <code>NUNIT</code>, <code>NUNIT_MULTIPART</code>, <code>ROBOT</code>, <code>ROBOT_MULTIPART</code>, <code>BUNDLE</code>, <code>TESTNG</code>, <code>TESTNG_MULTIPART</code>, <code>XUNIT</code>, <code>XUNIT_MULTIPART</code></li></ul></li>
<li><code>xrayInstance</code> (optional)
<ul><b>Nested Object</b>
<li><code>configID : String</code>
</li>
<li><code>alias : String</code>
</li>
<li><code>hosting</code>
<ul><li><b>Values:</b> <code>SERVER</code>, <code>CLOUD</code></li></ul></li>
<li><code>serverAddress : String</code>
</li>
<li><code>credentialId : String</code>
</li>
</ul></li>
</ul>


++++
=== `step([$class: 'XrayImportFeatureBuilder'])`: Xray: Cucumber Features Import Task
++++
<div><div>
 This Build Step can be used to import existing Cucumber Tests into Xray Tests.
</div></div>
<ul><li><code>serverInstance : String</code>
<div><div>
 Select the configured Jira instance where the Tests will be imported.
</div></div>

</li>
<li><code>folderPath : String</code>
<div><div>
 This is the directory containing your feature files or a specific feature file. All the files in this directory and sub directories will be imported.
</div></div>

</li>
<li><code>projectKey : String</code>
<div><div>
 This is the project where the Tests and Pre-Conditions will be created/updated.
</div></div>

</li>
<li><code>testInfo : String</code>
</li>
<li><code>preconditions : String</code>
</li>
<li><code>credentialId : String</code>
</li>
<li><code>lastModified : String</code> (optional)
<div><div>
 By entering an integer <i>n</i> here, only files that where modified in the last <i>n</i> hours will be imported. 
 <br>
 Leave empty if you do not want to use this parameter.
</div></div>

</li>
</ul>


++++
