= Zanata Plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/zanata">Visit the Jenkins Plugins site</a>
++++


=== `step([$class: 'ZanataCliBuilder'])`: Zanata Sync via CLI
++++
<div><div>
 <strong>Experimental feature</strong> - this is experimental and subject to change without notice.
</div></div>
<ul><li><code>projFile : String</code>
</li>
<li><code>syncG2zanata : boolean</code>
</li>
<li><code>syncZ2git : boolean</code>
</li>
<li><code>zanataCredentialsId : String</code>
</li>
<li><code>extraPathEntries : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'ZanataSyncStep'])`: Zanata Sync
++++
<div><div>
 Use this build step to perform standard Zanata push and pull. If you need to use advanced Zanata CLI options, Jenkins admin can configure Zanata CLI installation under global tools. Then select the installation in the job configuration. You can then use it in shell.
</div></div>
<ul><li><code>zanataCredentialsId : String</code>
</li>
<li><code>pullFromZanata : boolean</code> (optional)
<div><div>
 This will pull translation from Zanata server and commit if there is changes in it. Right now it only support commit for Git SCM. If you use other SCM, you will need to use other build step to do the commit. <strong>Note:</strong> You still need to configure a post build step to do git push or equivalent (e.g. git publisher) to push your commit to your remote repo.
</div></div>

</li>
<li><code>pushToZanata : boolean</code> (optional)
</li>
<li><code>syncOption : String</code> (optional)
</li>
<li><code>zanataLocaleIds : String</code> (optional)
</li>
<li><code>zanataProjectConfigs : String</code> (optional)
<div><div>
 If you have multiple zanata.xml in your Git repo and you want to restrict this job to certain ones, use this field and define the relative path to those files separated by comma.
</div></div>

</li>
<li><code>zanataURL : String</code> (optional)
<div><div>
 Leave blank to use the URL defined in your zanata.xml. If you specify a value here, it will override whats in zanata.xml.
</div></div>

</li>
</ul>


++++
