= z/OS DevOps
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/zdevops">Visit the Jenkins Plugins site</a>
++++


=== `allocateDS`: Allocate Dataset Declarative
++++
<ul><li><code>dsn : String</code>
</li>
<li><code>dsOrg</code>
<ul><li><b>Values:</b> <code>PO</code>, <code>POE</code>, <code>PS</code>, <code>VS</code></li></ul></li>
<li><code>primary : int</code>
</li>
<li><code>secondary : int</code>
</li>
<li><code>recFm</code>
<ul><li><b>Values:</b> <code>F</code>, <code>FB</code>, <code>V</code>, <code>VB</code>, <code>U</code>, <code>VSAM</code>, <code>VA</code></li></ul></li>
<li><code>alcUnit</code> (optional)
<ul><li><b>Values:</b> <code>TRK</code>, <code>CYL</code></li></ul></li>
<li><code>avgBlk : int</code> (optional)
</li>
<li><code>blkSize : int</code> (optional)
</li>
<li><code>dataClass : String</code> (optional)
</li>
<li><code>dirBlk : int</code> (optional)
</li>
<li><code>dsModel : String</code> (optional)
</li>
<li><code>dsnType</code> (optional)
<ul><li><b>Values:</b> <code>LIBRARY</code>, <code>HFS</code>, <code>PDS</code>, <code>LARGE</code>, <code>BASIC</code>, <code>EXTREQ</code>, <code>EXTPREF</code></li></ul></li>
<li><code>lrecl : int</code> (optional)
</li>
<li><code>mgntClass : String</code> (optional)
</li>
<li><code>storClass : String</code> (optional)
</li>
<li><code>unit : String</code> (optional)
</li>
<li><code>volser : String</code> (optional)
</li>
</ul>


++++
=== `downloadDS`: Download File Declarative
++++
<ul><li><code>dsn : String</code>
</li>
<li><code>getETag : boolean</code> (optional)
</li>
<li><code>vol : String</code> (optional)
</li>
</ul>


++++
=== `step([$class: 'SubmitJobStep'])`: [z/OS] - Submit job
++++
<ul><li><code>connectionName : String</code>
</li>
<li><code>jobName : String</code>
</li>
</ul>


++++
=== `submitJob`: Submit Job Declarative
++++
<ul><li><code>fileToSubmit : String</code>
</li>
</ul>


++++
=== `submitJobSync`: Submit Job Synchronously Declarative
++++
<ul><li><code>fileToSubmit : String</code>
</li>
</ul>


++++
=== `writeFileToMember`: Write file to Dataset Member Declarative
++++
<ul><li><code>dsn : String</code>
</li>
<li><code>member : String</code>
</li>
<li><code>file : String</code>
</li>
</ul>


++++
=== `writeFileToDS`: Write file to Dataset Declarative
++++
<ul><li><code>dsn : String</code>
</li>
<li><code>file : String</code>
</li>
</ul>


++++
=== `writeToDS`: Write to Dataset Declarative
++++
<ul><li><code>dsn : String</code>
</li>
<li><code>text : String</code>
</li>
</ul>


++++
=== `writeToMember`: Write to Dataset Member Declarative
++++
<ul><li><code>dsn : String</code>
</li>
<li><code>member : String</code>
</li>
<li><code>text : String</code>
</li>
</ul>


++++
=== `zosmf`: ZosmfStepDeclarative
++++
<ul><li><code>connectionName : String</code>
</li>
</ul>


++++
