= Zephyr Enterprise Test Management plugin
:page-layout: pipelinesteps

:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:compat-mode!:


++++
<a href="https://plugins.jenkins.io/zephyr-enterprise-test-management">Visit the Jenkins Plugins site</a>
++++


=== `zeeReporter`: Publish test result to Zephyr Enterprise
++++
<div><div>
 Zephyr Test Result Reporter is a plugin for Jenkins which supports an integration with Zephyr Enterprise/Community Test Management
</div></div>
<ul><li><code>serverAddress : String</code>
<div><div>
 Zephyr Server IP address or hostname
</div></div>

</li>
<li><code>projectKey : String</code>
<div><div>
 Select the name of Zephyr Project
</div></div>

</li>
<li><code>releaseKey : String</code>
<div><div>
 Select the name of Zephyr Release
</div></div>

</li>
<li><code>cycleKey : String</code>
<div><div>
 Select either an existing cycle in Zephyr or create a new cycle
</div></div>

</li>
<li><code>cyclePrefix : String</code>
<div><div>
 The default cycle name has the format Automation_&lt;Date&gt;&lt;Time&gt;. Use Cycle Name Prefix to substitute the prefix "Automation" with custom prefix of your choice for new cycle
</div></div>

</li>
<li><code>cycleDuration : String</code>
<div><div>
 The default cycle duration will be that of the existing cycle in Zephyr. Select Cycle duration when creating a new cycle
</div></div>

</li>
<li><code>createPackage : boolean</code>
<div><div>
 By default all test cases will be created under folder named "Automation" in Zephyr. Select Create Package Structure to create folder hierarchy based on your package
</div></div>

</li>
<li><code>resultXmlFilePath : String</code>
</li>
<li><code>parserTemplateKey : String</code>
</li>
</ul>


++++
