// :modified-files: pom.xml
// :task-identifier: require-newer-core
// :task-description: Require 2.414.3 as minimum Jenkins version

= Update minimum Jenkins version

.Require a newer minimum Jenkins version
video::Fev8KfFsPZE[youtube,width=800,height=420,start=2430]

Jenkins plugins declare a minimum supported Jenkins version.
The minimum Jenkins version is a good way for plugin developers to indicate the range of Jenkins versions they are willing to support and test.
See the xref:plugin-development:choosing-jenkins-baseline.adoc[developer documentation] for the recommended minimum Jenkins version.

// Create the branch
include::dev-docs:tutorial-improve:partial$_create-a-branch.adoc[]

== Update minimum required Jenkins version

Update the minimum required Jenkins version by setting a `jenkins.version` value in the properties section of the `pom.xml` file:

[source,xml,subs="attributes+"]
----
   <properties>
     <jenkins.version>2.440.3</jenkins.version>
   </properties>
----

If the plugin is already using the plugin bill of materials, then the bill of materials also needs to be updated with the matching `artifactId` for the minimum required Jenkins version.
The `version` may also need an upgrade see the xref:plugin-development:dependency-management.adoc#jenkins-plugin-bom[developer documentation].

The `git diff` might look like this:

[source,xml]
----
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.jenkins.tools.bom</groupId>
-        <artifactId>bom-2.361.x</artifactId>
+        <artifactId>bom-2.426.x</artifactId>
-        <version>2102.v854b_fec19c92</version>
+        <version>3080.vfa_b_e4a_a_39b_44</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
----

// Compile the plugin
include::dev-docs:tutorial-improve:partial$_compile-the-plugin.adoc[]

// Create a pull request
include::dev-docs:tutorial-improve:partial$_create-a-pull-request.adoc[]
