= Reverse proxy configuration

[pass]
++++
<!-- Redirect anchor references with Javascript -->
<!-- This is ONLY for anchor references like installing/#windows. -->
<!-- Use redirects as described in the contributing guide for page level redirects. -->
<!-- https://stackoverflow.com/questions/1305211/javascript-to-redirect-from-anchor-to-a-separate-page/21198129#21198129 -->
<script>
(function () {
    var anchorMap = {

        "ji-toolbar" : "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/", /* Algolia search redirect to stay on same page */

        "running-jenkins-behind-apache": "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-apache/",
        "running-jenkins-behind-haproxy": "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-haproxy/",
        "running-jenkins-behind-iis": "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iis/",
        "running-jenkins-behind-iptables": "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iptables/",
        "running-jenkins-behind-nginx": "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx/",
        "running-jenkins-behind-squid": "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-squid/",
    }
    /*
    * Best practice for extracting hashes:
    * https://stackoverflow.com/a/10076097/151365
    */
    var hash = window.location.hash.substring(1);

    if (hash) {
        /*
        * Best practice for javascript redirects:
        * https://stackoverflow.com/a/506004/151365
        */
        window.location.replace(anchorMap[hash]);
    }
})();
</script>
++++

A 'link:https://en.wikipedia.org/wiki/Reverse_proxy[reverse proxy]' allows an alternate HTTP or HTTPS provider to communicate with web browsers on behalf of Jenkins.
The alternate provider may offer additional capabilities, like SSL encryption.
The alternate provider may offload some work from Jenkins, like delivering static images.

== General Guidelines

Jenkins actively monitors reverse proxy configuration.
Jenkins reports xref:user-docs:system-administration:reverse-proxy-configuration-troubleshooting.adoc["`+Your reverse proxy setup is broken+`"] when it detects a reverse proxy configuration problem.
Refer to the xref:user-docs:system-administration:reverse-proxy-configuration-troubleshooting.adoc[troubleshooting] section if Jenkins is reporting that your reverse proxy setup is broken.

=== Background

Reverse proxies receive inbound HTTP requests and forward those requests to Jenkins.
It receives the outbound HTTP response from Jenkins and forwards those requests to the original requester.
A correctly configured reverse proxy rewrites *both* the HTTP request and the HTTP response.

When HTTP request rewriting is misconfigured, pages won't be displayed at all.
Refer to *link:#configuration-examples[Configuration Examples by Server Type]* if your reverse proxy is not displaying any Jenkins pages.

A reverse proxy must handle the HTTP response by either rewriting the response or setting HTTP headers on the forwarded request.
When HTTP response handling is misconfigured, Jenkins may fail to show updated information on a page or it may ignore changes submitted through web pages.
Refer to the xref:user-docs:system-administration:reverse-proxy-configuration-troubleshooting.adoc[troubleshooting] section if Jenkins is reporting that your reverse proxy setup is broken or pages are not behaving as expected.

[#configuration-examples]
== Configuration Examples by Server Type

Jenkins works with many different reverse proxies.
This section provides examples for specific reverse proxies, though much of the information also applies to other reverse proxies.

* xref:reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-apache.adoc[Running Jenkins with Apache]
* xref:reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx.adoc[Running Jenkins with Nginx]
* xref:reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-lighttpd.adoc[Running Jenkins with Lighttpd]
* xref:reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-haproxy.adoc[Running Jenkins with HAProxy]
* xref:reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-pomerium.adoc[Running Jenkins with Pomerium]
* xref:reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-squid.adoc[Running Jenkins with Squid]
* xref:reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iis.adoc[Running Jenkins with IIS]
* xref:reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iptables.adoc[Running Jenkins with iptables]
