= Contributing to docs.jenkins.io

image:https://badges.gitter.im/jenkinsci/docs.svg[link="https://app.gitter.im/#/room/#jenkins/docs:matrix.org"]

== Getting Started

To contribute to this repository, follow these steps:

1. link:https://guides.github.com/activities/forking/[Fork this repository] and ensure that you keep only the `main` branch.
2. Create a new branch from your `main` branch and perform your work on this new branch, avoiding direct changes to the `main` branch.
3. Once your work is completed and committed to your branch, push the changes to your forked repository.
4. link:https://help.github.com/articles/creating-a-pull-request-from-a-fork/[Create a pull request (PR)] from your branch to the `main` branch of this repository.

Forking only needs to be done once. After that, you can keep your fork up to date with the upstream repository thanks to *Sync fork*.
You can make further changes to your forked repository using the GitHub website file editor or by working on a local clone, as described below.

You can also open this project as a https://www.gitpod.io/[Gitpod workspace], which comes pre-configured with all the tools you will need.

[link="https://gitpod.io/#https://github.com/jenkins-infra/docs.jenkins.io"]
image::https://gitpod.io/button/open-in-gitpod.svg[Open in Gitpod]

[[newcomers]]
=== Information for newcomers

The documentation below describes common cases for contributors.
If you have any questions, please do not hesitate to ask in link:https://app.gitter.im/\#/room/#jenkinsci_newcomer-contributors:gitter.im[newcomers] or link:https://app.gitter.im/\#/room/#jenkins/docs:matrix.org[Documentation SIG] Gitter chats.
If you have any feedback about your contributor experience, please also share it with us in these channels so that we can improve our guidelines.

You can also find some newbie-friendly issues in our task tracker:

* link:https://github.com/jenkins-infra/docs.jenkins.io/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22[Good First Issues on GitHub]

If you found an issue that you would like to work on, you are welcome to go ahead and start contributing.
Please don't ask to be assigned to an issue, we don't assign individuals to issues, just go ahead and start working on it.
If you want to avoid having other people work on the same issue, feel free to add a comment to the issue stating that you're working on it.
If the last comment on the issue is older than a week and there is no PR linked to the issue, you can assume nobody is working on it.
If you need any help, please ask in the xref:contacts[].

[[contacts]]
=== Communication channels

The Jenkins website is largely maintained by the link:https://jenkins.io/sigs/docs/[Jenkins documentation] special interest group.
This group has various communication channels which can be used to discuss contributing to the website:

* link:https://app.gitter.im/#/room/#jenkins/docs:matrix.org[Gitter chat]
* link:https://jenkins.io/sigs/docs/#meetings[Regular meetings]

== Structure of docs.jenkins.io

The `docs.jenkins.io` repository contains two distinct parts:

1. **Antora** (Versioned)
   - link: link:/docs[/docs]
   - This part of the site is built using Antora, a static site generator designed for documentation. It is version-controlled, meaning that different versions of Jenkins documentation are maintained.
   - You can find more information in the link:https://github.com/jenkins-infra/docs.jenkins.io/tree/main/docs#readme[Antora README.md].

2. **Gatsby** (Non-Versioned)
   - link: link:/site[/site]
   - The non-versioned part of the site is built using Gatsby, a React-based framework.
   - For more details, you can refer to the link:https://github.com/jenkins-infra/docs.jenkins.io/tree/main/site#readme[Gatsby README.md].

When contributing to this repository, ensure that you are working on the correct section (Antora or Gatsby) based on the type of documentation you are adding or modifying.

[[forking]]
=== Creating a fork

Creating a fork, aka link:https://guides.github.com/activities/forking/[forking], makes a personal copy of another repository.
Changes you make in your fork do not show up in the `docs.jenkins.io` site until they are merged (via PR) to the `main` branch of this repository.
If you are unfamiliar with how to create a fork or how forks work, refer to the link:https://guides.github.com/activities/forking/[GitHub tutorial on forking].

=== Using GitHub to edit files

GitHub makes it easy to add, edit, or delete individual files via their website's link:https://help.github.com/articles/editing-files-in-your-repository/[File Editor].
The advantage of using the file editor is that GitHub will automatically fork (if needed), push the changes to a branch, and open a PR for you.
It also means you don't need to have a local clone of your fork.
The disadvantages are that you can't verify your changes locally before creating the PR, it only works on one file at a time, and your changes are lost if you close or navigate away from the page.

=== Using a local clone

We generally recommend making changes in a link:https://help.github.com/articles/cloning-a-repository-from-github/[local clone] of your fork.
This requires some additional tools and storage on your local machine, and you will need a bit more technical knowledge of how to use those tools.
However, this will allow you to work on multiple files as part of a single set of changes.
You'll save your changes in a local branch and then <<building, build and review>> them locally.
When they are ready, you will push your changes to your fork and submit a PR from there.

== Syncing your fork

You should regularly sync your fork with the upstream repository to keep it up to date with changes in the `main` branch.
To sync your fork, follow these steps:

. Add the upstream repository as a remote:
+
[source, bash]
----
git remote add upstream https://github.com/jenkins-infra/docs.jenkins.io.git
----

. Fetch the latest changes from upstream:
+
[source, bash]
----
git fetch upstream
----

. Check out your `main` branch:
+
[source, bash]
----
git checkout main
----

. Merge the changes from the upstream `main` branch:
+
[source, bash]
----
git merge upstream/main
----

. Push the updated `main` branch to your fork:
+
[source, bash]
----
git push origin main
----

== Building

To make changes to the documentation, it’s important to test them locally by building the appropriate part of the site (Antora or Gatsby). Follow these steps to build and preview the site:

=== Building the Antora documentation

. **Install Node.js and npm**
+
--
Install Node.js and npm preferably using a version manager like nvm:

- https://github.com/nvm-sh/

Alternatively, you can install Node.js directly from the official site:

- https://nodejs.org/

Verify your installation by running the following commands:


[source, bash]
----
node --version
npm --version
----
--

. **Install dependencies**
+
Navigate to the root of the repository and run:
+
[source, bash]
----
npm install
----

. **Build the Antora documentation**
+
--
Run the following command to build and serve the Antora documentation locally:

[source, bash]
----
make all
----

After the site is built, it will be available at: link:http://localhost:5252/[localhost:5252].
--

[[make-targets]]
=== `make` Targets

Run `make` to run a full build, or `make <target>` using one of the targets below to achieve specific results.

You can run `make help` to see a list of all available targets.

* *all* (default target) will run a full build of the site, including `install`, `ui`, and `antora`.
This also downloads and regenerates external resources.
* *clean* will remove all build output and dependencies in preparation for a full rebuild.
* *install* will download external dependencies and resources necessary to build the site.
As an optimization to make iterating on content locally more pleasant, dependencies and resources are not downloaded again unless the `clean` target is called first.
The exception being `all`, which downloads and regenerates external resources (but not download dependencies because they are more bandwidth intensive).
* *ui* will build the site ui.
* *antora* will build the documentation and run a development server on link:http://localhost:5252/[localhost:5252].
* *help* show the help message.

=== Building the Gatsby site

To work on the Gatsby part of the site, navigate to the `site/` directory and follow the instructions in the link:https://github.com/jenkins-infra/docs.jenkins.io/blob/main/site/README.md#installation[Gatsby README.md > Installation].

== Editing content

Most content on this site is written up in the AsciiDoc markup language.

[[why-asciidoc]]
==== Why AsciiDoc?

Generally speaking, all documentation should be written in link:https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc].
While most open source contributors are familiar with link:https://en.wikipedia.org/wiki/Markdown[Markdown], it has limitations that make writing in-depth documentation with it problematic.
Markdown, as opposed to link:https://guides.github.com/features/mastering-markdown/[GitHub flavored Markdown], does not have support for denoting what language source code might be written in.
AsciiDoc supports this natively with the "source code" block:

[source, asciidoc]
-----
[source, asciidoc]
----
This is where I would _cite_ some highlighted AsciiDoc code.
----
-----

AsciiDoc has a number of other features that make authoring documentation easier, such as "link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#admon-bl[admonition blocks]", which help call out specific sections, including:

[source, asciidoc]
----
NOTE: This is a notice that you should pay attention to!

CAUTION: This is a common mistake!
----

Becomes:

NOTE: This is a notice that you should pay attention to!

CAUTION: This is a common mistake!


There are too many other helpful macros and formatting options to list here, so we recommended that you refer to the link:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference[quick reference] to become more familiar with what is available.


== Adding new content

To add or modify content, follow these guidelines based on the specific section of the documentation.

=== Website structure and ownership

The Jenkins website hosts various content: user and developer documentation, blog, governance materials, pages for special interest groups and sub-projects, etc.
This information is maintained by multiple teams.
Ownership domains are also defined in the link:./.github/CODEOWNERS[CODEOWNERS] file.
Note that this file might be out of date or missing some entries, so common sense there applies.

Notable special areas:

* link:https://jenkins.io/project[Governance documents] - Managed by the link:https://www.jenkins.io/project/board/#current-board-members[Governance Board]
* Jenkins core changelogs - Managed by the link:https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#roles[Jenkins core maintainers]
* Security pages and advisories under `jenkins.io/security/` - Managed by the link:https://www.jenkins.io/security/team/[Jenkins Security Team]
* Event pages under `jenkins.io/events/` - Managed by event organizers, link:https://www.jenkins.io/sigs/advocacy-and-outreach/[Advocacy and Outreach SIG] and the link:https://www.jenkins.io/project/team-leads/#events[Jenkins Events Officer]
* SIG and sub-project pages - Managed by teams

Areas not in this file are considered as _common areas_ and maintained by teams listed below.

=== Teams and roles

There are 2 teams which maintain the majority of the website content except special areas:

* link:https://github.com/orgs/jenkins-infra/teams/jenkins-io-triage[Triage] team which performs triage and reviews the submitted issues and PRs.
* link:https://github.com/orgs/jenkins-infra/teams/copy-editors[Copy Editors] team which, in addition to reviews and triage, has permissions to copy-edit and merge submitted changes.

Both teams operate under the umbrella of link:https://www.jenkins.io/sigs/docs/[Jenkins Documentation Special Interest Group] led by the link:https://www.jenkins.io/project/team-leads/#documentation[Documentation Officer].

=== Joining the teams

If you are interested in joining the Triage or Copy Editors team, you can request membership in the link:https://groups.google.com/d/forum/jenkinsci-dev[Jenkins Developer mailing list] or in the link:https://www.jenkins.io/sigs/docs/[Documentation SIG channels].
The request will be processed and discussed by the community, and then the link:https://www.jenkins.io/project/team-leads/#documentation[documentation officer] will make a decision.

Eligibility requirements:

* Membership in both teams requires a track of contributions to the Jenkins website and/or documentation.
_Triage_ team is effectively an onboarding team for contributors interested in becoming copy editors, and this team has a low entry bar.
* Applicants to the _Copy Editors_ team should have a signed link:https://github.com/jenkinsci/infra-cla[Contributor License Agreement].


[[reviewing]]
=== Reviewing changes

There are many PRs being submitted to docs.jenkins.io every week.
Reviews are driven by the community, and any contributions are always welcome.
Reviews may take some time depending on availability of contributors.

Some tips for contributors:

* PRs are open to public, and any GitHub user can review changes and provide feedback.
If you are interested to review changes, please just do so (and thanks in advance!). 
No special permissions are needed.
* If you need help with reviews for documentation changes, you can ask in the link:https://app.gitter.im/#/room/#jenkins/docs:matrix.org[Documentation SIG Gitter channel].

[[merging-common]]
=== Merging changes in common areas

Common area process applies when there is no special ownership or process defined.
PRs to common areas can be merged by any _Copy Editor_ once all of the following apply:

* Conversations in the PR are completed OR it is explicit that a reviewer does not block the change (often indicated by line comments attached to an approving PR review, or by using the term "nit", from "nit-picking")
* There are enough approvals
** For trivial changes (typo fixes, minor improvements) - 1 approval from a _Copy Editor_
** For major changes - at least 2 approvals from reviewers.

[[merging-special-areas]]
=== Merging changes in special areas

Special areas are managed by their owners.
_Copy Editors_ should not merge substantial changes in these areas unless they get explicit sign-off from owners identified in the link:./.github/CODEOWNERS[CODEOWNERS].
Minor changes like typo fixes might be integrated by _Copy Editors_.

== Communication

For any questions or help, feel free to ask in the link:https://app.gitter.im/#/room/#jenkins/docs:matrix.org[Documentation SIG Gitter channel]

We look forward to your contributions!
