= Jenkins Events

There are many online and local Jenkins-related events: including conferences, meetups, webinars, hackathons, etc.

* xref:online-meetup:index.adoc[Jenkins Online Meetup]. Our project has a virtual meetup for users and developers. We organize regular events and webinars there.
* xref:projects:jam:index.adoc[Local meetups]. Jenkins contributors organize many local CI/CD and Jenkins meetups around the world. There might be one in your city!
* xref:contributor-summit:index.adoc[Contributor Summits]. We organize a few contributor summits every year. It brings together current community members and future contributors to learn, meet, and help shape the future of Jenkins.
* xref:devops-world:index.adoc[DevOps World]. CloudBees organizes the DevOps World conference and includes Jenkins topics in the conference agenda.
* xref:hacktoberfest:index.adoc[Hacktoberfest]. Jenkins project is participating to Hacktoberfest.

[#major-events]
== Major Events

There are no upcoming major events registered in the database. If you see that your event is missing, please submit a change to our website.

link:https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#adding-an-event[> How to add an event to the Jenkins website?]

[#event-calendar]
== Event Calendar

We have a calendar which lists events related to Jenkins, including regular SIG and project meetings. This calendar is also available in the https://calendar.google.com/calendar/ical/4ss12f0mqr3tbp1t2fe369slf4%40group.calendar.google.com/public/basic.ics[(.ics format)]

++++
<!-- Using JSTZ time zone detection library -->
<script src="
https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js
"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.7/jstz.min.js"></script>

<style>
iframe {
    max-width: 700px;
}
</style>

<script type="text/javascript">
  const deviceTimeZone = jstz.determine().name();

  const calendarSrc = 'https://calendar.google.com/calendar/b/1/embed'

      + '?showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;mode=WEEK'
      + '&amp;src=4ss12f0mqr3tbp1t2fe369slf4%40group.calendar.google.com&amp;color=%2329527A'
      + '&amp;ctz='
  const calendarSrcPrefix = '<iframe src="' + calendarSrc;

  const calendarSrcSuffix = '" style="border:0;overflow:hidden;" width="1024" height="600" scrolling="no"></iframe>';

  function set_calendar(timezone) {
    timezone = timezone || deviceTimeZone;

    document.getElementById('calendar-container').innerHTML = calendarSrcPrefix + encodeURIComponent(timezone) + calendarSrcSuffix;

  }

  $(function () {
    set_calendar(deviceTimeZone);
  });
</script>

<div class="row">
    <div class="col">
        <!-- The following div's innerHTML will be overwritten with the-->
        <!-- calendar iframe set to the appropriate time zone. -->
        <div id="calendar-container"></div>
        <p>
            View calendar using TimeZone:
            <select id="selected_timezone" onchange="set_calendar(this.value)">
                <option value="">(auto)</option>
                <option value="GMT">GMT</option>
                <option value="CET">CET</option>
                <option value="America/New_York">US Eastern</option>
                <option value="America/Los_Angeles">US Pacific</option>
                <option value="Asia/Tokyo">Tokyo</option>
                <option value="Asia/Shanghai">Shanghai</option>
            </select>
        </p>
    </div>
</div>
++++
