= $class: 'BacklogPullRequestSCMSource'
:page-layout: pipelinesteps
== $class: 'BacklogPullRequestSCMSource'

++++
<li><code>$class: 'BacklogPullRequestSCMSource'</code><div>
<ul><li><code>remote : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>includes : String</code>
</li>
<li><code>excludes : String</code>
</li>
<li><code>ignoreOnPushNotifications : boolean</code>
</li>
<li><code>url : String</code>
<div><div>
 Set the project URL of Backlog used with this repository. Samples of URL are shown below. 
 <ul>
  <li>https://demo.backlog.jp/projects/DORA</li>
 </ul>
</div></div>

</li>
<li><code>apiKey : String</code>
<div><div>
 <p>API key when using <a href="http://developer.nulab-inc.com/docs/backlog" rel="nofollow">Backlog API version 2</a>.</p>
</div></div>

</li>
<li><code>id : String</code> (optional)
</li>
<li><code>browser</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>assembla</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://www.assembla.com/code/PROJECT/git/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'BacklogGitRepositoryBrowser'</code><div>
<ul><li><code>repoName : String</code>
</li>
<li><code>repoUrl : String</code>
</li>
</ul></div></li>
<li><code>bitbucketServer</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the Bitbucket Server root URL for this repository (such as <em>https://bitbucket:7990/OWNER/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>bitbucket</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://bitbucket.org/OWNER/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>cgit</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://cgit.example.com:port/group/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>fisheye</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the URL of this repository in FishEye (such as <em>https://fisheye.example.com/browse/project/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>gitblit</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository.
</div></div>

</li>
<li><code>projectName : String</code>
<div><div>
 Specify the name of the project in GitBlit.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GitBucketBrowser'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>gitLab</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gitlab.com/username/repository/</em>).
</div></div>

</li>
<li><code>version : String</code> (optional)
<div><div>
 Specify the major and minor version of GitLab you use (such as 9.1). If you don't specify a version, a modern version of GitLab (&gt;= 8.0) is assumed.
</div></div>

</li>
</ul></div></li>
<li><code>gitLabBrowser</code><div>
<div><div>
 Specify the HTTP URL for this project's GitLab page so that links to changes can be automatically generated by Jenkins. The URL needs to include the owner and project. If the GitLab server is <code>https://gitLab.example.com</code> then the URL for bob's skunkworks project might be <code>https://gitLab.example.com/bob/skunkworks</code>.
</div></div>
<ul><li><code>projectUrl : String</code>
<div><div>
 Specify the HTTP URL for this project's GitLab page. The URL needs to include the owner and project so, for example, if the GitLab server is <code>https://gitLab.example.com</code> then the URL for bob's skunkworks project might be <code>https://gitLab.example.com/bob/skunkworks</code>
</div></div>

</li>
</ul></div></li>
<li><code>gitList</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gitlist.example.com/repo/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>gitWeb</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://github.com/jenkinsci/jenkins.git</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GiteaBrowser'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the HTTP URL for this repository's Gitea page. The URL needs to include the owner and repository so, for example, if the Gitea server is <code>https://gitea.example.com</code> then the URL for bob's skunkworks project repository might be <code>https://gitea.example.com/bob/skunkworks</code>
</div></div>

</li>
</ul></div></li>
<li><code>github</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the HTTP URL for this repository's GitHub page (such as <em>https://github.com/jquery/jquery</em>).
</div></div>

</li>
</ul></div></li>
<li><code>gitiles</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gwt.googlesource.com/gwt/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GitoriousWeb'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gitorious.org/gitorious/mainline</em>).
</div></div>

</li>
</ul></div></li>
<li><code>gogs</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gogs.example.com/username/some-repo-url.git</em>).
</div></div>

</li>
</ul></div></li>
<li><code>kiln</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://khanacademy.kilnhg.com/Code/Website/Group/webapp</em>).
</div></div>

</li>
</ul></div></li>
<li><code>phabricator</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the phabricator instance root URL (such as <em>https://phabricator.example.com</em>).
</div></div>

</li>
<li><code>repo : String</code>
<div><div>
 Specify the repository name in phabricator (such as the <em>foo</em> part of <em>phabricator.example.com/diffusion/foo/browse</em>).
</div></div>

</li>
</ul></div></li>
<li><code>redmine</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://redmine.example.com/PATH/projects/PROJECT/repository</em>).
</div></div>

</li>
</ul></div></li>
<li><code>rhodeCode</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the HTTP URL for this repository's RhodeCode page (such as <em>https://rhodecode.example.com/projects/PROJECT/repos/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ScmManagerGitRepositoryBrowser'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://scm-manager.org/scm/repo/namespace/name</em>).
</div></div>

</li>
</ul></div></li>
<li><code>jbSpace</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Provide the absolute URL to your repository in JetBrains Space in the following format: https://&lt;your Space instance&gt;/p/&lt;project key&gt;/repositories/&lt;repository name&gt;
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'Stash'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the HTTP URL for this repository's Stash page (such as <em>https://stash.example.com/projects/PROJECT/repos/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>teamFoundation</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Either the name of the remote whose URL should be used, or the URL of this module in TFS (such as <em>https://tfs.example.com/tfs/PROJECT/_git/REPO/</em>). If empty (default), the URL of the "origin" repository is used. 
 <p>If TFS is also used as the repository server, this can usually be left blank.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'TracGitRepositoryBrowser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'TuleapBrowser'</code><div>
<div><div>
 Specify the HTTPS URL for the Tuleap Git repository so that links to changes can be automatically generated by Jenkins.
</div></div>
<ul><li><code>repositoryUrl : String</code>
<div><div>
 The URL is the web URL of the Tuleap Git repository.
</div></div>

</li>
</ul></div></li>
<li><code>viewgit</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://git.example.com/viewgit/</em>).
</div></div>

</li>
<li><code>projectName : String</code>
<div><div>
 Specify the name of the project in ViewGit (e.g. scripts, scuttle etc. from <em>https://code.fealdia.org/viewgit/</em>).
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>extensions</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>authorInChangelog</code><div>
<div><div>
 The default behavior is to use the Git commit's "Committer" value in Jenkins' build changesets. If this option is selected, the Git commit's "Author" value would be used instead.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'BuildChooserSetting'</code><div>
<div><div>
 When you are interested in using a job to build multiple heads (most typically multiple branches), you can choose how Jenkins choose what branches to build in what order. 
 <p>This extension point in Jenkins is used by many other plugins to control the job to build specific commits. When you activate those plugins, you may see them installing a custom strategy here.</p>
</div></div>
<ul><li><code>buildChooser</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'AlternativeBuildChooser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'AncestryBuildChooser'</code><div>
<ul><li><code>maximumAgeInDays : int</code>
</li>
<li><code>ancestorCommitSha1 : String</code>
</li>
</ul></div></li>
<li><code>$class: 'DefaultBuildChooser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'DeflakeGitBuildChooser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'GerritTriggerBuildChooser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'InverseBuildChooser'</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>buildSingleRevisionOnly</code><div>
<div><div>
 Disable scheduling for multiple candidate revisions.
 <br>
  If we have 3 branches:
 <br>
  ----A--.---.--- B
 <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\-----C
 <br>
  jenkins would try to build (B) and (C).
 <br>
  This behaviour disables this and only builds one of them.
 <br>
  It is helpful to reduce the load of the Jenkins infrastructure when the SCM system like Bitbucket or GitHub should decide what commits to build.
</div></div>
<ul></ul></div></li>
<li><code>changelogToBranch</code><div>
<div><div>
 This method calculates the changelog against the specified branch.
</div></div>
<ul><li><code>options</code>
<ul><b>Nested Object</b>
<li><code>compareRemote : String</code>
<div><div>
 Name of the repository, such as <code>origin</code>, that contains the branch you specify below.
</div></div>

</li>
<li><code>compareTarget : String</code>
<div><div>
 The name of the branch within the named repository to compare against.
</div></div>

</li>
</ul></li>
</ul></div></li>
<li><code>checkoutOption</code><div>
<ul><li><code>timeout : int</code>
<div><div>
 Specify a timeout (in minutes) for checkout.
 <br>
  This option overrides the default timeout of 10 minutes. 
 <br>
  You can change the global git timeout via the property org.jenkinsci.plugins.gitclient.Git.timeOut (see <a href="https://issues.jenkins.io/browse/JENKINS-11286" rel="nofollow">JENKINS-11286</a>). Note that property should be set on both controller and agent to have effect (see <a href="https://issues.jenkins.io/browse/JENKINS-22547" rel="nofollow">JENKINS-22547</a>).
</div></div>

</li>
</ul></div></li>
<li><code>cleanBeforeCheckout</code><div>
<div><div>
 Clean up the workspace before every checkout by deleting all untracked files and directories, including those which are specified in <code>.gitignore</code>. It also resets all <em>tracked</em> files to their versioned state. This ensures that the workspace is in the same state as if you cloned and checked out in a brand-new empty directory, and ensures that your build is not affected by the files generated by the previous build.
</div></div>
<ul><li><code>deleteUntrackedNestedRepositories : boolean</code> (optional)
<div><div>
 Deletes untracked submodules and any other subdirectories which contain <code>.git</code> directories.
</div></div>

</li>
</ul></div></li>
<li><code>cleanAfterCheckout</code><div>
<div><div>
 Clean up the workspace after every checkout by deleting all untracked files and directories, including those which are specified in <code>.gitignore</code>. It also resets all <em>tracked</em> files to their versioned state. This ensures that the workspace is in the same state as if you cloned and checked out in a brand-new empty directory, and ensures that your build is not affected by the files generated by the previous build.
</div></div>
<ul><li><code>deleteUntrackedNestedRepositories : boolean</code> (optional)
<div><div>
 Deletes untracked submodules and any other subdirectories which contain <code>.git</code> directories.
</div></div>

</li>
</ul></div></li>
<li><code>cloneOption</code><div>
<ul><li><code>shallow : boolean</code>
<div><div>
 Perform shallow clone, so that git will not download the history of the project, saving time and disk space when you just want to access the latest version of a repository.
</div></div>

</li>
<li><code>noTags : boolean</code>
<div><div>
 Deselect this to perform a clone without tags, saving time and disk space when you just want to access what is specified by the refspec.
</div></div>

</li>
<li><code>reference : String</code>
<div><div>
 Specify a folder containing a repository that will be used by Git as a reference during clone operations.
 <br>
  This option will be ignored if the folder is not available on the controller or agent where the clone is being executed.
</div></div>

</li>
<li><code>timeout : int</code>
<div><div>
 Specify a timeout (in minutes) for clone and fetch operations.
 <br>
  This option overrides the default timeout of 10 minutes. 
 <br>
  You can change the global git timeout via the property org.jenkinsci.plugins.gitclient.Git.timeOut (see <a href="https://issues.jenkins.io/browse/JENKINS-11286" rel="nofollow">JENKINS-11286</a>). Note that property should be set on both controller and agent to have effect (see <a href="https://issues.jenkins.io/browse/JENKINS-22547" rel="nofollow">JENKINS-22547</a>).
</div></div>

</li>
<li><code>depth : int</code> (optional)
<div><div>
 Set shallow clone depth, so that git will only download recent history of the project, saving time and disk space when you just want to access the latest commits of a repository.
</div></div>

</li>
<li><code>honorRefspec : boolean</code> (optional)
<div><div>
 Perform initial clone using the refspec defined for the repository. This can save time, data transfer and disk space when you only need to access the references specified by the refspec.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'CodeCommitURLHelper'</code><div>
<ul><li><code>credentialId : String</code>
<div><div>
 <p>OPTIONAL: Select the credentials to use.<br>
   If not specified, defaults to the <a href="http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html#using-the-default-credential-provider-chain" rel="nofollow"> DefaultAWSCredentialsProviderChain </a> behaviour - <b>*FROM THE JENKINS INSTANCE*</b></p>
 <p>In the latter case, usage of IAM Role Profiles seems not to work, thus relying on environment variables / system properties or the ~/.aws/credentials file, thus not recommended.</p>
</div></div>

</li>
<li><code>repositoryName : String</code>
</li>
</ul></div></li>
<li><code>$class: 'DisableRemotePoll'</code><div>
<div><div>
 Git plugin uses git ls-remote polling mechanism by default when configured with a single branch (no wildcards!). This compare the latest built commit SHA with the remote branch without cloning a local copy of the repo.
 <br>
 <br>
  If you don't want to / can't use this.
 <br>
 <br>
  If this option is selected, polling will require a workspace and might trigger unwanted builds (see <a href="https://issues.jenkins.io/browse/JENKINS-10131" rel="nofollow">JENKINS-10131</a>).
</div></div>
<ul></ul></div></li>
<li><code>$class: 'ExcludeFromChangeSet'</code><div>
<ul></ul></div></li>
<li><code>$class: 'ExcludeFromPoll'</code><div>
<ul></ul></div></li>
<li><code>lfs</code><div>
<div><div>
 Enable <a href="https://git-lfs.github.com/" rel="nofollow">git large file support</a> for the workspace by pulling large files after the checkout completes. Requires that the controller and each agent performing an LFS checkout have installed `git lfs`.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'GitSCMChecksExtension'</code><div>
<ul><li><code>verboseConsoleLog : boolean</code> (optional)
<div><div>
 If this option is checked, verbose log will be output to build console; the verbose log is useful for debugging the publisher creation.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GitSCMStatusChecksExtension'</code><div>
<ul><li><code>name : String</code> (optional)
</li>
<li><code>skip : boolean</code> (optional)
</li>
<li><code>skipProgressUpdates : boolean</code> (optional)
</li>
<li><code>suppressLogs : boolean</code> (optional)
</li>
<li><code>unstableBuildNeutral : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'GitTagMessageExtension'</code><div>
<div><div>
 If the revision checked out has a git tag associated with it, the tag name will be exported during the build as <strong>GIT_TAG_NAME</strong>. 
 <br>
  If a message was specified when creating the tag, then that message will be exported during the build as the <strong>GIT_TAG_MESSAGE</strong> environment variable. 
 <br>
  If no tag message was specified, the commit message will be used. 
 <br>
  If you ticked the <strong>Use most recent tag</strong> option, and the revision checked out has no git tag associated with it, the parent commits will be searched for a git tag, and the rules stated above will apply to the first parent commit with a git tag. 
 <p></p> If the revision has more than one tag associated with it, only the most recent tag will be taken into account, <strong>unless</strong> the refspec contains "refs/tags/" — i.e. builds are only triggered when certain tag names or patterns are matched — in which case the exact tag name that triggered the build will be used, even if it's not the most recent tag for this commit. 
 <br>
  For this reason, if you're not using a tag-specific refspec but you <em>are</em> using the "Create a tag for every build" behaviour, you should make sure that the build-tagging behaviour is configured to run <em>after</em> this "export git tag message" behaviour. 
 <p></p> Tag and commit messages which span multiple lines are no problem, though only the first 10000 lines of a tag's message will be exported.
</div></div>
<ul><li><code>useMostRecentTag : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'IgnoreNotifyCommit'</code><div>
<div><div>
 If checked, this repository will be ignored when the notifyCommit-URL is accessed regardless of if the repository matches or not.
</div></div>
<ul></ul></div></li>
<li><code>localBranch</code><div>
<div><div>
 If given, checkout the revision to build as HEAD on this branch. 
 <p>If selected, and its value is an empty string or "**", then the branch name is computed from the remote branch without the origin. In that case, a remote branch origin/master will be checked out to a local branch named master, and a remote branch origin/develop/new-feature will be checked out to a local branch named develop/newfeature.</p>
 <p>Please note that this has not been tested with submodules.</p>
</div></div>
<ul><li><code>localBranch : String</code>
</li>
</ul></div></li>
<li><code>$class: 'MessageExclusion'</code><div>
<ul><li><code>excludedMessage : String</code>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will ignore any revisions committed with message matched to <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html" rel="nofollow">Pattern</a> when determining if a build needs to be triggered. This can be used to exclude commits done by the build itself from triggering another build, assuming the build server commits the change with a distinct message. 
 <p></p>Exclusion uses <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html" rel="nofollow">Pattern</a> <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Matcher.html#matches()" rel="nofollow">matching</a>
 <p></p>
 <pre>.*\[maven-release-plugin\].*</pre> The example above illustrates that if only revisions with "[maven-release-plugin]" message in first comment line have been committed to the SCM a build will not occur. 
 <p></p> You can create more complex patterns using embedded flag expressions. 
 <pre>(?s).*FOO.*</pre> This example will search FOO message in all comment lines.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PathRestriction'</code><div>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will pay attention to included and/or excluded files and/or folders when determining if a build needs to be triggered. 
 <p></p> Using this behaviour will preclude the faster git ls-remote polling mechanism, forcing polling to require a workspace thus sometimes triggering unwanted builds, as if you had selected the <strong>Force polling using workspace</strong> extension as well.
</div></div>
<ul><li><code>includedRegions : String</code>
<div><div>
 Each inclusion uses <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html" rel="nofollow">java regular expression pattern matching</a>, and must be separated by a new line. An empty list implies that everything is included. 
 <p></p>
 <pre>    myapp/src/main/web/.*\.html
    myapp/src/main/web/.*\.jpeg
    myapp/src/main/web/.*\.gif
  </pre> The example above illustrates that a build will only occur, if html/jpeg/gif files have been committed to the SCM. Exclusions take precedence over inclusions, if there is an overlap between included and excluded regions.
</div></div>

</li>
<li><code>excludedRegions : String</code>
<div><div>
 Each exclusion uses <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html" rel="nofollow">java regular expression pattern matching</a>, and must be separated by a new line. 
 <p></p>
 <pre>    myapp/src/main/web/.*\.html
    myapp/src/main/web/.*\.jpeg
    myapp/src/main/web/.*\.gif
  </pre> The example above illustrates that if only html/jpeg/gif files have been committed to the SCM a build will not occur.
</div></div>

</li>
</ul></div></li>
<li><code>perBuildTag</code><div>
<div><div>
 Create a tag in the workspace for every build to unambiguously mark the commit that was built. You can combine this with Git publisher to push the tags to the remote repository.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'PreBuildMerge'</code><div>
<div><div>
 These options allow you to perform a merge to a particular branch before building. For example, you could specify an integration branch to be built, and to merge to master. In this scenario, on every change of integration, Jenkins will perform a merge with the master branch, and try to perform a build if the merge is successful. It then may push the merge back to the remote repository if the Git Push post-build action is selected.
</div></div>
<ul><li><code>options</code>
<ul><b>Nested Object</b>
<li><code>mergeTarget : String</code>
<div><div>
 The name of the branch within the named repository to merge to, such as <code>master</code>.
</div></div>

</li>
<li><code>fastForwardMode</code> (optional)
<div><div>
 Merge fast-forward mode selection.
 <br>
  The default, --ff, gracefully falls back to a merge commit when required.
 <br>
  For more information, see the <a href="https://git-scm.com/docs/git-merge" rel="nofollow">Git Merge Documentation</a>
</div></div>

<ul><li><b>Values:</b> <code>FF</code>, <code>FF_ONLY</code>, <code>NO_FF</code></li></ul></li>
<li><code>mergeRemote : String</code> (optional)
<div><div>
 Name of the repository, such as <code>origin</code>, that contains the branch you specify below. If left blank, it'll default to the name of the first repository configured above.
</div></div>

</li>
<li><code>mergeStrategy</code> (optional)
<div><div>
 Merge strategy selection. <strong>This feature is not fully implemented in JGIT.</strong>
</div></div>

<ul><li><b>Values:</b> <code>DEFAULT</code>, <code>RESOLVE</code>, <code>RECURSIVE</code>, <code>OCTOPUS</code>, <code>OURS</code>, <code>SUBTREE</code>, <code>RECURSIVE_THEIRS</code></li></ul></li>
</ul></li>
</ul></div></li>
<li><code>pretestedIntegration</code><div>
<ul><li><code>gitIntegrationStrategy</code>
<ul><b>Nested Choice of Objects</b>
<li><code>accumulated</code><div>
<div><h2>Accumulated Commit Strategy</h2>
<div>
 This strategy merges your commits with the --no-ff switch
</div></div>
<ul><li><code>shortCommitMessage : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>ffonly</code><div>
<div><h2>Fast Forward only (--ff-only) Strategy</h2>
<div>
 This strategy fast-forward only using the --ff-only switch - or fails
</div></div>
<ul><li><code>shortCommitMessage : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>squash</code><div>
<div><h2>Squashed Commit Strategy</h2>
<div>
 This strategy squashes all your commit on a given branch with the --squash option
</div></div>
<ul></ul></div></li>
</ul></li>
<li><code>integrationBranch : String</code>
<div><h3>What to specify</h3>
<p>The branch name must match your integration branch name. <b>No trailing slash.</b></p>
<h3>Merge is performed the following way</h3>
<h5>Squash commit</h5>
<pre>            git checkout -B &lt;Branch name&gt; &lt;Repository name&gt;/&lt;Branch name&gt;
            git merge --squash &lt;Branch matched by git&gt;
            git commit -C &lt;Branch matched by git&gt;</pre>
<h5>Accumulated commit</h5>
<pre>            git checkout -B &lt;Branch name&gt; &lt;Repository name&gt;/&lt;Branch name&gt;
            git merge -m &lt;commitMsg&gt; &lt;Branch matched by git&gt; --no-ff</pre>
<h3>When changes are pushed to the integration branch?</h3>
<p>Changes are only ever pushed when the build results is SUCCESS</p>
<pre>            git push &lt;Repository name&gt; &lt;Branch name&gt;</pre></div>

</li>
<li><code>repoName : String</code>
<div><div>
 <h3>What to specify</h3>
 <p>The repository name. In git the repository is always the name of the remote. So if you have specified a repository name in your Git configuration. You need to specify the exact same name here, otherwise no integration will be performed. We do the merge based on this.</p>
 <p><b>No trailing slash on repository name.</b></p>
 <p><span>Remember to specify this when working with NAMED repositories in Git</span></p>
</div></div>

</li>
</ul></div></li>
<li><code>pruneStaleBranch</code><div>
<div><div>
 Run "git remote prune" for each remote, to prune obsolete local branches.
</div></div>
<ul></ul></div></li>
<li><code>pruneTags</code><div>
<ul><li><code>pruneTags : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'RelativeTargetDirectory'</code><div>
<ul><li><code>relativeTargetDir : String</code>
<div><div>
 Specify a local directory (relative to <a rel="nofollow">the workspace root</a>) where the Git repository will be checked out. If left empty, the workspace root itself will be used. 
 <p>This extension should <strong>not</strong> be used in Jenkins Pipeline (either declarative or scripted). Jenkins Pipeline already provides standard techniques for checkout to a subdirectory. Use <a href="https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#ws-allocate-workspace" rel="nofollow">ws</a> and <a href="https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#dir-change-current-directory" rel="nofollow">dir</a> in Jenkins Pipeline rather than this extension.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ScmName'</code><div>
<div><div>
 <p>Unique name for this SCM. Needed when using Git within the Multi SCM plugin.</p>
</div></div>
<ul><li><code>name : String</code>
</li>
</ul></div></li>
<li><code>$class: 'SparseCheckoutPaths'</code><div>
<div><div>
 <p>Specify the paths that you'd like to sparse checkout. This may be used for saving space (Think about a reference repository). Be sure to use a recent version of Git, at least above 1.7.10</p>
</div></div>
<ul><li><code>sparseCheckoutPaths</code>
<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>submodule</code><div>
<ul><li><code>depth : int</code> (optional)
<div><div>
 Set shallow clone depth, so that git will only download recent history of the project, saving time and disk space when you just want to access the latest commits of a repository.
</div></div>

</li>
<li><code>disableSubmodules : boolean</code> (optional)
<div><div>
 By disabling support for submodules you can still keep using basic git plugin functionality and just have Jenkins to ignore submodules completely as if they didn't exist.
</div></div>

</li>
<li><code>parentCredentials : boolean</code> (optional)
<div><div>
 Use credentials from the default remote of the parent project.
</div></div>

</li>
<li><code>recursiveSubmodules : boolean</code> (optional)
<div><div>
 Retrieve all submodules recursively (uses '--recursive' option which requires git&gt;=1.6.5)
</div></div>

</li>
<li><code>reference : String</code> (optional)
<div><div>
 Specify a folder containing a repository that will be used by Git as a reference during clone operations.
 <br>
  This option will be ignored if the folder is not available on the controller or agent where the clone is being executed.
 <br>
  To prepare a reference folder with multiple subprojects, create a bare git repository and add all the remote urls then perform a fetch:
 <br>
 <pre>  git init --bare
  git remote add SubProject1 https://gitrepo.com/subproject1
  git remote add SubProject2 https://gitrepo.com/subproject2
  git fetch --all
  </pre>
</div></div>

</li>
<li><code>shallow : boolean</code> (optional)
<div><div>
 Perform shallow clone, so that git will not download the history of the project, saving time and disk space when you just want to access the latest version of a repository.
</div></div>

</li>
<li><code>threads : int</code> (optional)
<div><div>
 Specify the number of threads that will be used to update submodules.
 <br>
  If unspecified, the command line git default thread count is used.
 <br>
</div></div>

</li>
<li><code>timeout : int</code> (optional)
<div><div>
 Specify a timeout (in minutes) for submodules operations.
 <br>
  This option overrides the default timeout of 10 minutes. 
 <br>
  You can change the global git timeout via the property org.jenkinsci.plugins.gitclient.Git.timeOut (see <a href="https://issues.jenkins.io/browse/JENKINS-11286" rel="nofollow">JENKINS-11286</a>). Note that property should be set on both controller and agent to have effect (see <a href="https://issues.jenkins.io/browse/JENKINS-22547" rel="nofollow">JENKINS-22547</a>).
</div></div>

</li>
<li><code>trackingSubmodules : boolean</code> (optional)
<div><div>
 Retrieve the tip of the configured branch in .gitmodules (Uses '--remote' option which requires git&gt;=1.8.2)
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'UserExclusion'</code><div>
<ul><li><code>excludedUsers : String</code>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will ignore any revisions committed by users in this list when determining if a build needs to be triggered. This can be used to exclude commits done by the build itself from triggering another build, assuming the build server commits the change with a distinct SCM user. 
 <p></p> Using this behaviour will preclude the faster git ls-remote polling mechanism, forcing polling to require a workspace thus sometimes triggering unwanted builds, as if you had selected the <strong>Force polling using workspace</strong> extension as well. 
 <p></p>Each exclusion uses exact string comparison and must be separated by a new line. User names are only excluded if they exactly match one of the names in this list. 
 <p></p>
 <pre>auto_build_user</pre> The example above illustrates that if only revisions by "auto_build_user" have been committed to the SCM a build will not occur.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'UserIdentity'</code><div>
<ul><li><code>name : String</code>
<div><div>
 <p>If given, "GIT_COMMITTER_NAME=[this]" and "GIT_AUTHOR_NAME=[this]" are set for builds. This overrides whatever is in the global settings.</p>
</div></div>

</li>
<li><code>email : String</code>
<div><div>
 <p>If given, "GIT_COMMITTER_EMAIL=[this]" and "GIT_AUTHOR_EMAIL=[this]" are set for builds. This overrides whatever is in the global settings.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'WipeWorkspace'</code><div>
<div><div>
 Delete the contents of the workspace before building, ensuring a fully fresh workspace.
</div></div>
<ul></ul></div></li>
</ul></li>
<li><code>gitTool : String</code> (optional)
</li>
</ul></div></li>


++++