= $class: 'CCUCMScm'
:page-layout: pipelinesteps
== $class: 'CCUCMScm'

++++
<li><code>$class: 'CCUCMScm'</code><div>
<ul><li><code>loadModule : String</code>
</li>
<li><code>newest : boolean</code>
</li>
<li><code>mode</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'PollChildMode'</code><div>
<ul><li><code>levelToPoll : String</code>
</li>
<li><code>component : String</code> (optional)
</li>
<li><code>createBaseline : boolean</code> (optional)
<div><div>
 <p>Check this if you want create a baseline after a completed deliver.</p>
 <p>This is only applicable for child and sibling poll mode.</p>
</div></div>

</li>
<li><code>newest : boolean</code> (optional)
<div><div>
 Selects the newest baseline on the stream. Skipping intermediates.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PollRebaseMode'</code><div>
<ul><li><code>levelToPoll : String</code>
</li>
<li><code>component : String</code> (optional)
<div><div>
 The component used to figure out the correct baseline to recommend due to the following bug: 
 <br><a href="http://www-01.ibm.com/support/docview.wss?uid=swg21269043" rel="nofollow">http://www-01.ibm.com/support/docview.wss?uid=swg21269043</a>
</div></div>

</li>
<li><code>createBaseline : boolean</code> (optional)
</li>
<li><code>excludeList : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'PollSelfMode'</code><div>
<ul><li><code>levelToPoll : String</code>
</li>
<li><code>component : String</code> (optional)
</li>
<li><code>newest : boolean</code> (optional)
<div><div>
 Selects the newest baseline on the stream. Skipping intermediates.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PollSiblingMode'</code><div>
<ul><li><code>levelToPoll : String</code>
</li>
<li><code>component : String</code> (optional)
</li>
<li><code>createBaseline : boolean</code> (optional)
<div><div>
 <p>Check this if you want create a baseline after a completed deliver.</p>
 <p>This is only applicable for child and sibling poll mode.</p>
</div></div>

</li>
<li><code>newest : boolean</code> (optional)
<div><div>
 Selects the newest baseline on the stream. Skipping intermediates.
</div></div>

</li>
<li><code>useHyperLinkForPolling : boolean</code> (optional)
<div><div>
 Instead of using the integration streams default deliver target. Use the value specified in the hyperlink. The hyperlink type to be used can be configured in the global configuration.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PollSubscribeMode'</code><div>
<ul><li><code>levelToPoll : String</code>
</li>
<li><code>componentsToMonitor</code>
<ul><b>Array / List of Nested Object</b>
<li><code>componentSelection : String</code>
</li>
</ul></li>
<li><code>jobsToMonitor</code>
<ul><b>Array / List of Nested Object</b>
<li><code>jobname : String</code>
</li>
<li><code>ignores : String</code>
<div><div>
 A comma seperated list of components which should not be included when checking if the requirements are met. That is to say that not all components are interesting in every job specified.
</div></div>

</li>
<li><code>jobName : String</code> (optional)
<div><div>
 Specifies the name of the job in which all selected baselines must be present.
</div></div>

</li>
</ul></li>
<li><code>cascadePromotion : boolean</code> (optional)
</li>
<li><code>component : String</code> (optional)
</li>
<li><code>newest : boolean</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>stream : String</code>
<div><div>
 Specify the stream you want to poll for with ClearCase UCM SCM. Syntax: [stream]@[PVOB]
</div></div>

</li>
<li><code>treatUnstable : String</code>
</li>
<li><code>nameTemplate : String</code>
</li>
<li><code>forceDeliver : boolean</code>
</li>
<li><code>recommend : boolean</code>
</li>
<li><code>makeTag : boolean</code>
</li>
<li><code>setDescription : boolean</code>
</li>
<li><code>buildProject : String</code>
</li>
<li><code>removeViewPrivateFiles : boolean</code>
</li>
<li><code>trimmedChangeSet : boolean</code>
</li>
<li><code>discard : boolean</code>
</li>
</ul></div></li>


++++