= dagshubScmSource
:page-layout: pipelinesteps
== dagshubScmSource

++++
<li><code>dagshubScmSource</code><div>
<ul><li><code>repositoryUrl : String</code> (optional)
<div><div>
 The URL you would use to clone your repo from DAGsHub. 
 <br>
  e.g. <code>https://DAGsHub.com/myuser/myrepo.git</code> or <code>https://DAGsHub.com/myuser/myrepo</code>
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 Checkout credentials are only needed for private projects. 
 <br>
  If you can't find your credentials in the list, make sure they are scoped to the domain specified in the "Repository URL" field!
</div></div>

</li>
<li><code>traits</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'ApprovedPullRequestTrait'</code><div>
<div><div>
 Sets if approvals are required before building pull requests.
</div></div>
<ul><li><code>strategyId : int</code>
<div><div>
 Sets if approvals are required before building pull requests. 
 <dl>
  <dt>
   No approval necessary.
  </dt>
  <dd>
   No check of approvals will be performed before building.
  </dd>
  <dt>
   Any approval required
  </dt>
  <dd>
   Before building the pull request must be approved. This may be performed by the author or someone else.
  </dd>
  <dt>
   Non-author approval required
  </dt>
  <dd>
   Before building the pull request must be approved and that approval cannot be performed by the author of the pull request.
  </dd>
  <dt>
   Author and Non-author approval required
  </dt>
  <dd>
   Before building the pull request must be approved by the author and a non-author.
  </dd>
 </dl>
</div></div>

</li>
</ul></div></li>
<li><code>authorInChangelog</code><div>
<ul></ul></div></li>
<li><code>bitbucketAgedRefsTrait</code><div>
<div><div>
 Defines the number of days to accept an unmodified git ref as candidate for being built (supposing it contains a Jenkinsfile). In a practical effect it is a ripoff from the Orphaned Item Strategy but on indexing time.
</div></div>
<ul><li><code>retentionDays : String</code>
</li>
</ul></div></li>
<li><code>bitbucketBranchCommitSkipTrait</code><div>
<div><div>
 Branches whose last commit's message contains (case insensitive) the pattern "[ci skip]" or "[skip ci]" will be ignored.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'BitbucketBranchDiscoveryTrait'</code><div>
<div><div>
 Discovers branches in the repository.
</div></div>
<ul></ul></div></li>
<li><code>bitbucketBuildStatusNotifications</code><div>
<div><div>
 Configure the Bitbucket notifications.
</div></div>
<ul><li><code>disableNotificationForNotBuildJobs : boolean</code> (optional)
</li>
<li><code>sendSuccessNotificationForUnstableBuild : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>bitbucketCommitSkipTrait</code><div>
<div><div>
 Pull requests whose last commit's message contains (case insensitive) the pattern "[ci skip]" or "[skip ci]" will be ignored.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'BitbucketGitBrowserSCMSourceTrait'</code><div>
<ul><li><code>browser</code>
<ul><b>Nested Choice of Objects</b>
<li><code>assembla</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://www.assembla.com/code/PROJECT/git/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'BacklogGitRepositoryBrowser'</code><div>
<ul><li><code>repoName : String</code>
</li>
<li><code>repoUrl : String</code>
</li>
</ul></div></li>
<li><code>bitbucketServer</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the Bitbucket Server root URL for this repository (such as <em>https://bitbucket:7990/OWNER/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>bitbucket</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://bitbucket.org/OWNER/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>cgit</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://cgit.example.com:port/group/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>fisheye</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the URL of this repository in FishEye (such as <em>https://fisheye.example.com/browse/project/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>gitblit</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository.
</div></div>

</li>
<li><code>projectName : String</code>
<div><div>
 Specify the name of the project in GitBlit.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GitBucketBrowser'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>gitLab</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gitlab.com/username/repository/</em>).
</div></div>

</li>
<li><code>version : String</code> (optional)
<div><div>
 Specify the major and minor version of GitLab you use (such as 9.1). If you don't specify a version, a modern version of GitLab (&gt;= 8.0) is assumed.
</div></div>

</li>
</ul></div></li>
<li><code>gitLabBrowser</code><div>
<div><div>
 Specify the HTTP URL for this project's GitLab page so that links to changes can be automatically generated by Jenkins. The URL needs to include the owner and project. If the GitLab server is <code>https://gitLab.example.com</code> then the URL for bob's skunkworks project might be <code>https://gitLab.example.com/bob/skunkworks</code>.
</div></div>
<ul><li><code>projectUrl : String</code>
<div><div>
 Specify the HTTP URL for this project's GitLab page. The URL needs to include the owner and project so, for example, if the GitLab server is <code>https://gitLab.example.com</code> then the URL for bob's skunkworks project might be <code>https://gitLab.example.com/bob/skunkworks</code>
</div></div>

</li>
</ul></div></li>
<li><code>gitList</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gitlist.example.com/repo/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>gitWeb</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://github.com/jenkinsci/jenkins.git</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GiteaBrowser'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the HTTP URL for this repository's Gitea page. The URL needs to include the owner and repository so, for example, if the Gitea server is <code>https://gitea.example.com</code> then the URL for bob's skunkworks project repository might be <code>https://gitea.example.com/bob/skunkworks</code>
</div></div>

</li>
</ul></div></li>
<li><code>github</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the HTTP URL for this repository's GitHub page (such as <em>https://github.com/jquery/jquery</em>).
</div></div>

</li>
</ul></div></li>
<li><code>gitiles</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gwt.googlesource.com/gwt/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GitoriousWeb'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gitorious.org/gitorious/mainline</em>).
</div></div>

</li>
</ul></div></li>
<li><code>gogs</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gogs.example.com/username/some-repo-url.git</em>).
</div></div>

</li>
</ul></div></li>
<li><code>kiln</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://khanacademy.kilnhg.com/Code/Website/Group/webapp</em>).
</div></div>

</li>
</ul></div></li>
<li><code>phabricator</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the phabricator instance root URL (such as <em>https://phabricator.example.com</em>).
</div></div>

</li>
<li><code>repo : String</code>
<div><div>
 Specify the repository name in phabricator (such as the <em>foo</em> part of <em>phabricator.example.com/diffusion/foo/browse</em>).
</div></div>

</li>
</ul></div></li>
<li><code>redmine</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://redmine.example.com/PATH/projects/PROJECT/repository</em>).
</div></div>

</li>
</ul></div></li>
<li><code>rhodeCode</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the HTTP URL for this repository's RhodeCode page (such as <em>https://rhodecode.example.com/projects/PROJECT/repos/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ScmManagerGitRepositoryBrowser'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://scm-manager.org/scm/repo/namespace/name</em>).
</div></div>

</li>
</ul></div></li>
<li><code>jbSpace</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Provide the absolute URL to your repository in JetBrains Space in the following format: https://&lt;your Space instance&gt;/p/&lt;project key&gt;/repositories/&lt;repository name&gt;
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'Stash'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the HTTP URL for this repository's Stash page (such as <em>https://stash.example.com/projects/PROJECT/repos/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>teamFoundation</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Either the name of the remote whose URL should be used, or the URL of this module in TFS (such as <em>https://tfs.example.com/tfs/PROJECT/_git/REPO/</em>). If empty (default), the URL of the "origin" repository is used. 
 <p>If TFS is also used as the repository server, this can usually be left blank.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'TracGitRepositoryBrowser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'TuleapBrowser'</code><div>
<div><div>
 Specify the HTTPS URL for the Tuleap Git repository so that links to changes can be automatically generated by Jenkins.
</div></div>
<ul><li><code>repositoryUrl : String</code>
<div><div>
 The URL is the web URL of the Tuleap Git repository.
</div></div>

</li>
</ul></div></li>
<li><code>viewgit</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://git.example.com/viewgit/</em>).
</div></div>

</li>
<li><code>projectName : String</code>
<div><div>
 Specify the name of the project in ViewGit (e.g. scripts, scuttle etc. from <em>https://code.fealdia.org/viewgit/</em>).
</div></div>

</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'BitbucketJiraValidatorTrait'</code><div>
<div><div>
 Enforces a pull request to be filled with a title containing a single and unresolved Jira ticket, formatted as defined at the global config (defaulting matching as JENKINS-1234).
</div></div>
<ul><li><code>jiraServerIdx : int</code>
</li>
</ul></div></li>
<li><code>$class: 'BitbucketPullRequestDiscoveryTrait'</code><div>
<div><div>
 Discovers open pull requests in the repository.
</div></div>
<ul></ul></div></li>
<li><code>buildStatusNameCustomPart</code><div>
<div><div>
 Customize the pipeline status name used by Jenkins
</div></div>
<ul><li><code>buildStatusNameCustomPart : String</code> (optional)
<div><div>
 Enter a string to customize the status/context name for status updates published to GitLab. For a branch build the default name would be 'jenkinsci/branch'. With the buildStatusNameCustomPart 'custom' the name would be 'jenkinsci/custom/branch'. This allows to have multiple GitLab-Branch-Sources for the same GitLab-project configured.
</div></div>

</li>
<li><code>buildStatusNameOverwrite : boolean</code> (optional)
<div><div>
 Overwrites the build status name including the jenkinsci default part.
 <br>
  Instead of 'jenkinsci/custom/branch' just 'custom/branch'.
</div></div>

</li>
<li><code>ignoreTypeInStatusName : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'ChangeDiscoveryTrait'</code><div>
<ul><li><code>queryString : String</code>
<div><div>
 <p>Provide an additional query string to search for open changes. The status:open is implicitly added and does not need to be specified. See <a href="https://gerrit-documentation.storage.googleapis.com/Documentation/3.2.0/user-search.html#search-operators" rel="nofollow">Gerrit search operators documentation</a> for a detailed list of the supported search operators.</p>
 <h2>Examples:</h2>
 <p></p>
 <ul>
  <li>
   <pre>-is:wip</pre> does not include work-in-progress changes</li>
  <li>
   <pre>is:private</pre> includes private changes</li>
 </ul>
 <p></p>
</div></div>

</li>
</ul></div></li>
<li><code>checkoutOption</code><div>
<ul><li><code>extension</code>
<ul><b>Nested Object</b>
<li><code>timeout : int</code>
<div><div>
 Specify a timeout (in minutes) for checkout.
 <br>
  This option overrides the default timeout of 10 minutes. 
 <br>
  You can change the global git timeout via the property org.jenkinsci.plugins.gitclient.Git.timeOut (see <a href="https://issues.jenkins.io/browse/JENKINS-11286" rel="nofollow">JENKINS-11286</a>). Note that property should be set on both controller and agent to have effect (see <a href="https://issues.jenkins.io/browse/JENKINS-22547" rel="nofollow">JENKINS-22547</a>).
</div></div>

</li>
</ul></li>
</ul></div></li>
<li><code>cleanAfterCheckout</code><div>
<ul><li><code>extension</code>
<ul><b>Nested Object</b>
<div><div>
 Clean up the workspace after every checkout by deleting all untracked files and directories, including those which are specified in <code>.gitignore</code>. It also resets all <em>tracked</em> files to their versioned state. This ensures that the workspace is in the same state as if you cloned and checked out in a brand-new empty directory, and ensures that your build is not affected by the files generated by the previous build.
</div></div>
<li><code>deleteUntrackedNestedRepositories : boolean</code> (optional)
<div><div>
 Deletes untracked submodules and any other subdirectories which contain <code>.git</code> directories.
</div></div>

</li>
</ul></li>
</ul></div></li>
<li><code>cleanBeforeCheckout</code><div>
<ul><li><code>extension</code>
<ul><b>Nested Object</b>
<div><div>
 Clean up the workspace before every checkout by deleting all untracked files and directories, including those which are specified in <code>.gitignore</code>. It also resets all <em>tracked</em> files to their versioned state. This ensures that the workspace is in the same state as if you cloned and checked out in a brand-new empty directory, and ensures that your build is not affected by the files generated by the previous build.
</div></div>
<li><code>deleteUntrackedNestedRepositories : boolean</code> (optional)
<div><div>
 Deletes untracked submodules and any other subdirectories which contain <code>.git</code> directories.
</div></div>

</li>
</ul></li>
</ul></div></li>
<li><code>$class: 'CleanMercurialSCMSourceTrait'</code><div>
<div><div>
 When this behaviour is present, each build will wipe any local modifications or untracked files in the repository checkout. This is often a convenient way to ensure that a build is not using any artifacts from earlier builds.
</div></div>
<ul></ul></div></li>
<li><code>cloneOption</code><div>
<ul><li><code>extension</code>
<ul><b>Nested Object</b>
<li><code>shallow : boolean</code>
<div><div>
 Perform shallow clone, so that git will not download the history of the project, saving time and disk space when you just want to access the latest version of a repository.
</div></div>

</li>
<li><code>noTags : boolean</code>
<div><div>
 Deselect this to perform a clone without tags, saving time and disk space when you just want to access what is specified by the refspec.
</div></div>

</li>
<li><code>reference : String</code>
<div><div>
 Specify a folder containing a repository that will be used by Git as a reference during clone operations.
 <br>
  This option will be ignored if the folder is not available on the controller or agent where the clone is being executed.
</div></div>

</li>
<li><code>timeout : int</code>
<div><div>
 Specify a timeout (in minutes) for clone and fetch operations.
 <br>
  This option overrides the default timeout of 10 minutes. 
 <br>
  You can change the global git timeout via the property org.jenkinsci.plugins.gitclient.Git.timeOut (see <a href="https://issues.jenkins.io/browse/JENKINS-11286" rel="nofollow">JENKINS-11286</a>). Note that property should be set on both controller and agent to have effect (see <a href="https://issues.jenkins.io/browse/JENKINS-22547" rel="nofollow">JENKINS-22547</a>).
</div></div>

</li>
<li><code>depth : int</code> (optional)
<div><div>
 Set shallow clone depth, so that git will only download recent history of the project, saving time and disk space when you just want to access the latest commits of a repository.
</div></div>

</li>
<li><code>honorRefspec : boolean</code> (optional)
<div><div>
 Perform initial clone using the refspec defined for the repository. This can save time, data transfer and disk space when you only need to access the references specified by the refspec.
</div></div>

</li>
</ul></li>
</ul></div></li>
<li><code>$class: 'DisableStatusUpdateTrait'</code><div>
<div><div>
 Disables notifications (commit status updates) to GitHub for builds.
</div></div>
<ul></ul></div></li>
<li><code>discoverOtherRefs</code><div>
<div><div>
 Discovers other specified refs on the repository.
</div></div>
<ul><li><code>ref : String</code>
<div><p>The pattern under /refs on the remote repository to discover, can contain a wildcard.<br>
  Example: test/*/merged</p></div>

</li>
<li><code>nameMapping : String</code> (optional)
<div><p>Mapping for how the ref can be named in for example the <code>@Library</code>.<br>
  Example: test-@{1} <br>
  Where @{1} replaces the first wildcard in the ref when discovered.</p>
<p>By default it will be "namespace_before_wildcard-@{1}". E.g. if ref is "test/*/merged" the default mapping would be "test-@{1}".</p></div>

</li>
</ul></div></li>
<li><code>$class: 'FilterChecksTrait'</code><div>
<ul><li><code>queryOperator</code>
<ul><li><b>Values:</b> <code>ID</code>, <code>SCHEME</code></li></ul></li>
<li><code>queryString : String</code>
<div><div>
 Provide a query string to search for pending checks. Depending on which mode was chosen, this either should be a checker-scheme or the UUID of a specific checker.
</div></div>

</li>
</ul></div></li>
<li><code>gitLabForkDiscovery</code><div>
<div><div>
 Discovers merge requests where the origin project is a fork of the target project.
</div></div>
<ul><li><code>strategyId : int</code>
<div><div>
 Determines how merge requests are discovered: 
 <dl>
  <dt>
   Merging the merge request with the current target branch revision
  </dt>
  <dd>
   Discover each merge request once with the discovered revision corresponding to the result of merging with the current revision of the target branch
  </dd>
  <dt>
   The current merge request revision
  </dt>
  <dd>
   Discover each merge request once with the discovered revision corresponding to the merge request head revision without merging
  </dd>
  <dt>
   Both the current merge request revision and the merge request merged with the current target branch revision
  </dt>
  <dd>
   Discover each merge request twice. The first discovered revision corresponds to the result of merging with the current revision of the target branch in each scan. The second parallel discovered revision corresponds to the merge request head revision without merging
  </dd>
 </dl>
</div></div>

</li>
<li><code>trust</code>
<div><div>
 <p>One of the great powers of merge requests is that anyone with read access to a project can fork it, commit some changes to their fork and then create a merge request against the original project with their changes. There are some files stored in source control that are important. For example, a <code>Jenkinsfile</code> may contain configuration details to sandbox merge requests in order to mitigate against malicious merge requests. In order to protect against a malicious merge request itself modifying the <code>Jenkinsfile</code> to remove the protections, you can define the trust policy for merge requests from forks.</p>
 <p>Other plugins can extend the available trust policies. The default policies are:</p>
 <dl>
  <dt>
   Nobody
  </dt>
  <dd>
   Merge requests from forks will all be treated as untrusted. This means that where Jenkins requires a trusted file (e.g. <code>Jenkinsfile</code>) the contents of that file will be retrieved from the target branch on the origin project and not from the merge request branch on the fork project.
  </dd>
  <dt>
   Members
  </dt>
  <dd>
   Merge requests from collaborators to the origin project will be treated as trusted, all other merge requests from fork repositories will be treated as untrusted. Note that if credentials used by Jenkins for scanning the project does not have permission to query the list of contributors to the origin project then only the origin account will be treated as trusted - i.e. this will fall back to <code>Nobody</code>.
  </dd>
  <dt>
   Trusted Members
  </dt>
  <dd>
   Merge requests forks will be treated as trusted if and only if the fork owner has either Developer or Maintainer or Owner Access Level in the origin project. <strong>This is the recommended policy.</strong>
  </dd>
  <dt>
   Everyone
  </dt>
  <dd>
   All merge requests from forks will be treated as trusted. <strong>NOTE:</strong> this option can be dangerous if used on a public project hosted on a GitLab instance.
  </dd>
 </dl>
</div></div>

<ul><li><b>Type:</b> <code>jenkins.scm.api.trait.SCMHeadAuthority&lt;? super io.jenkins.plugins.gitlabbranchsource.GitLabSCMSourceRequest, ? extends jenkins.scm.api.mixin.ChangeRequestSCMHead2, ? extends jenkins.scm.api.SCMRevision&gt;</code></li>
</ul></li>
<li><code>buildMRForksNotMirror : boolean</code> (optional)
<div><div>
 Add discovery of merge requests where the origin project is a fork of a certain project, but the target project is not the original forked project. To be used in case one has a GitLab project which is a fork of another project from another team, in order to isolate artefacts and allow an MR flow. This means using MRs inside that fork from branches in the fork back to the fork's default branch. (Implements https://github.com/jenkinsci/gitlab-branch-source-plugin/issues/167)
</div></div>

</li>
</ul></div></li>
<li><code>browser</code><div>
<ul><li><code>browser</code>
<ul><b>Nested Choice of Objects</b>
<li><code>assembla</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://www.assembla.com/code/PROJECT/git/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'BacklogGitRepositoryBrowser'</code><div>
<ul><li><code>repoName : String</code>
</li>
<li><code>repoUrl : String</code>
</li>
</ul></div></li>
<li><code>bitbucketServer</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the Bitbucket Server root URL for this repository (such as <em>https://bitbucket:7990/OWNER/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>bitbucket</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://bitbucket.org/OWNER/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>cgit</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://cgit.example.com:port/group/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>fisheye</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the URL of this repository in FishEye (such as <em>https://fisheye.example.com/browse/project/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>gitblit</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository.
</div></div>

</li>
<li><code>projectName : String</code>
<div><div>
 Specify the name of the project in GitBlit.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GitBucketBrowser'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>gitLab</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gitlab.com/username/repository/</em>).
</div></div>

</li>
<li><code>version : String</code> (optional)
<div><div>
 Specify the major and minor version of GitLab you use (such as 9.1). If you don't specify a version, a modern version of GitLab (&gt;= 8.0) is assumed.
</div></div>

</li>
</ul></div></li>
<li><code>gitLabBrowser</code><div>
<div><div>
 Specify the HTTP URL for this project's GitLab page so that links to changes can be automatically generated by Jenkins. The URL needs to include the owner and project. If the GitLab server is <code>https://gitLab.example.com</code> then the URL for bob's skunkworks project might be <code>https://gitLab.example.com/bob/skunkworks</code>.
</div></div>
<ul><li><code>projectUrl : String</code>
<div><div>
 Specify the HTTP URL for this project's GitLab page. The URL needs to include the owner and project so, for example, if the GitLab server is <code>https://gitLab.example.com</code> then the URL for bob's skunkworks project might be <code>https://gitLab.example.com/bob/skunkworks</code>
</div></div>

</li>
</ul></div></li>
<li><code>gitList</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gitlist.example.com/repo/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>gitWeb</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://github.com/jenkinsci/jenkins.git</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GiteaBrowser'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the HTTP URL for this repository's Gitea page. The URL needs to include the owner and repository so, for example, if the Gitea server is <code>https://gitea.example.com</code> then the URL for bob's skunkworks project repository might be <code>https://gitea.example.com/bob/skunkworks</code>
</div></div>

</li>
</ul></div></li>
<li><code>github</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the HTTP URL for this repository's GitHub page (such as <em>https://github.com/jquery/jquery</em>).
</div></div>

</li>
</ul></div></li>
<li><code>gitiles</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gwt.googlesource.com/gwt/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GitoriousWeb'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gitorious.org/gitorious/mainline</em>).
</div></div>

</li>
</ul></div></li>
<li><code>gogs</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://gogs.example.com/username/some-repo-url.git</em>).
</div></div>

</li>
</ul></div></li>
<li><code>kiln</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://khanacademy.kilnhg.com/Code/Website/Group/webapp</em>).
</div></div>

</li>
</ul></div></li>
<li><code>phabricator</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the phabricator instance root URL (such as <em>https://phabricator.example.com</em>).
</div></div>

</li>
<li><code>repo : String</code>
<div><div>
 Specify the repository name in phabricator (such as the <em>foo</em> part of <em>phabricator.example.com/diffusion/foo/browse</em>).
</div></div>

</li>
</ul></div></li>
<li><code>redmine</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://redmine.example.com/PATH/projects/PROJECT/repository</em>).
</div></div>

</li>
</ul></div></li>
<li><code>rhodeCode</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the HTTP URL for this repository's RhodeCode page (such as <em>https://rhodecode.example.com/projects/PROJECT/repos/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ScmManagerGitRepositoryBrowser'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://scm-manager.org/scm/repo/namespace/name</em>).
</div></div>

</li>
</ul></div></li>
<li><code>jbSpace</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Provide the absolute URL to your repository in JetBrains Space in the following format: https://&lt;your Space instance&gt;/p/&lt;project key&gt;/repositories/&lt;repository name&gt;
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'Stash'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the HTTP URL for this repository's Stash page (such as <em>https://stash.example.com/projects/PROJECT/repos/REPO/</em>).
</div></div>

</li>
</ul></div></li>
<li><code>teamFoundation</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Either the name of the remote whose URL should be used, or the URL of this module in TFS (such as <em>https://tfs.example.com/tfs/PROJECT/_git/REPO/</em>). If empty (default), the URL of the "origin" repository is used. 
 <p>If TFS is also used as the repository server, this can usually be left blank.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'TracGitRepositoryBrowser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'TuleapBrowser'</code><div>
<div><div>
 Specify the HTTPS URL for the Tuleap Git repository so that links to changes can be automatically generated by Jenkins.
</div></div>
<ul><li><code>repositoryUrl : String</code>
<div><div>
 The URL is the web URL of the Tuleap Git repository.
</div></div>

</li>
</ul></div></li>
<li><code>viewgit</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://git.example.com/viewgit/</em>).
</div></div>

</li>
<li><code>projectName : String</code>
<div><div>
 Specify the name of the project in ViewGit (e.g. scripts, scuttle etc. from <em>https://code.fealdia.org/viewgit/</em>).
</div></div>

</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>gitHubAgedRefsTrait</code><div>
<div><div>
 Defines the number of days to accept an unmodified git ref as candidate for being built (supposing it contains a Jenkinsfile). In a practical effect it is a ripoff from the Orphaned Item Strategy but on indexing time.
</div></div>
<ul><li><code>retentionDays : String</code>
</li>
</ul></div></li>
<li><code>gitHubBranchCommitSkipTrait</code><div>
<div><div>
 Branches whose last commit's message contains (case insensitive) the pattern "[ci skip]" or "[skip ci]" will be ignored.
</div></div>
<ul></ul></div></li>
<li><code>gitHubCommitSkipTrait</code><div>
<div><div>
 Pull requests whose last commit's message contains (case insensitive) the pattern "[ci skip]" or "[skip ci]" will be ignored.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'GitHubJiraValidatorTrait'</code><div>
<div><div>
 Enforces a pull request to be filled with a title containing a single and unresolved Jira ticket, formatted as defined at the global config (defaulting matching as JENKINS-1234).
</div></div>
<ul><li><code>jiraServerIdx : int</code>
</li>
</ul></div></li>
<li><code>gitHubSourceChecks</code><div>
<ul><li><code>verboseConsoleLog : boolean</code> (optional)
<div><div>
 If this option is checked, verbose log will be output to build console; the verbose log is useful for debugging the publisher creation.
</div></div>

</li>
</ul></div></li>
<li><code>gitHubStatusChecks</code><div>
<ul><li><code>name : String</code> (optional)
</li>
<li><code>skip : boolean</code> (optional)
</li>
<li><code>skipNotifications : boolean</code> (optional)
<div><div>
 If this option is checked, the notifications sent by the <a href="https://plugins.jenkins.io/github-branch-source/" rel="nofollow">GitHub Branch Source Plugin</a> will be disabled.
</div></div>

</li>
<li><code>skipProgressUpdates : boolean</code> (optional)
</li>
<li><code>suppressLogs : boolean</code> (optional)
</li>
<li><code>unstableBuildNeutral : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>lfs</code><div>
<ul></ul></div></li>
<li><code>gitlabAvatar</code><div>
<ul><li><code>disableProjectAvatar : boolean</code> (optional)
<div><div>
 Due to a GitLab bug, sometimes it is not possible to GitLab API to fetch GitLab Avatar for private projects or when the api doesn't have token access. You may choose to skip avatar for projects if you want to avoid broken or self generated avatars.
</div></div>

</li>
</ul></div></li>
<li><code>gitlabMarkUnstableAsSuccess</code><div>
<ul><li><code>markUnstableAsSuccess : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>gitlabSkipNotifications</code><div>
<ul></ul></div></li>
<li><code>gitTool</code><div>
<ul><li><code>gitTool : String</code>
</li>
</ul></div></li>
<li><code>gitLabHookRegistration</code><div>
<ul><li><code>webHookMode : String</code>
</li>
<li><code>systemHookMode : String</code>
</li>
</ul></div></li>
<li><code>gitHubIgnoreDraftPullRequestFilter</code><div>
<ul></ul></div></li>
<li><code>ignoreOnPush</code><div>
<ul></ul></div></li>
<li><code>jervisFilter</code><div>
<div><div>
 <p>This will look at the root of a GitHub reference for .jervis.yml for the branches and tags filtering. You can customize the name of the YAML file searched for if you like.</p>
 <p>For Tags:</p>
 <ul>
  <li>It will filter for the tag name.</li>
 </ul>
 <p>For Branches:</p>
 <ul>
  <li>It will filter for the branch name.</li>
  <li>It will filter for pull requests destined for the branch name.</li>
 </ul>
 <h2>Example YAML</h2><code>
  <pre>branches:
  only:
    - main
</pre></code>
 <h1>More on specify branches and tags to build</h1>
 <p>By default Jervis will generate Jenkins jobs for all branches that have a .jervis.yml file. You can control and limit this behavior by specifying the branches or tags key in your .jervis.yml.</p>
 <h3>Allow or block branches and tags</h3>
 <p>You can either create an allow list of branches (only) or a block list of branches (except) to be built.</p><code>
  <pre># block branches from building
branches:
  except:
    - legacy
    - experimental

# allow only these branches
branches:
  only:
    - main
    - stable
</pre></code>
 <p>The same YAML can be applied to tags.</p><code>
  <pre># block tags from building
tags:
  except:
    - .*-rc
    - .*-beta

# allow only these tags
tags:
  only:
    - v[.0-9]+
</pre></code>
 <p>If you specify both only and except, then except will be ignored. .jervis.yml needs to be present on all branches you want to be built. .jervis.yml will be interpreted in the context of that branch so if you specify an allow list in your main branch, then it will not propagate to other branches.</p>
 <h3>Using regular expressions</h3>
 <p>You can use regular expressions to allow or block branches:</p><code>
  <pre>branches:
  only:
    - main
    - /^[.0-9]+-hotfix$/
</pre></code>
 <p>Any name surrounded with / in the list of branches is treated as a regular expression. The expression will use <a href="https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#compile%28java.lang.String%29" rel="nofollow">Pattern.compile</a> to compile the regex string into a <a href="http://docs.groovy-lang.org/latest/html/documentation/index.html#_regular_expression_operators" rel="nofollow">Groovy regular expression</a>.</p>
</div></div>
<ul><li><code>yamlFileName : String</code>
<div><div>
 <p>The filename which will be read from GitHub to determine if a Jenkins branch, tag, or pull request should be built. Provide a comma separated list of paths to YAML files in a repository and it will check each path as a fallback.</p>
 <p>For example, set the value to: .jervis.yml, .ci/jervis.yml and this plugin will first check for valid YAML in .jervis.yml. If no YAML exists, then it will fall back to checking .ci/jervis.yml.</p>
</div></div>

</li>
</ul></div></li>
<li><code>localBranch</code><div>
<ul></ul></div></li>
<li><code>logComment</code><div>
<ul><li><code>logSuccess : boolean</code> (optional)
<div><div>
 Sometimes the user doesn't want to log the builds that succeeded. The trait only enable logging of failed/aborted builds by default. Select this option to include logging of successful builds as well.
</div></div>

</li>
<li><code>sudoUser : String</code> (optional)
<div><div>
 Enter a sudo username of the user you want to comment as on GitLab Server. Remember the token specified should have api and sudo access both (which can only be created by your GitLab Server Admin). It is recommended to create a dummy user in your GitLab Server with an appropriate username like `jenkinsadmin` etc. Leave empty if you want use the owner of the project as the commenter.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'MercurialBrowserSCMSourceTrait'</code><div>
<ul><li><code>browser</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'FishEye'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository, such as: http://www.example.org/browse/hg/
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GoogleCode'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <a href="http://code.google.com/p/PROJECTNAME/source/" rel="nofollow">this</a>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'HgWeb'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <a href="https://www.mercurial-scm.org/repo/hg/" rel="nofollow">this</a>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'Kallithea'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <a href="https://rhodecode.server/repo_name" rel="nofollow">this</a>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'KilnHG'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <a href="https://acme.kilnhg.com/Repo/Repositories/Group/PROJECTNAME" rel="nofollow">this</a>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'RhodeCode'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <a href="https://rhodecode.server/repo_name" rel="nofollow">this</a>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'RhodeCodeLegacy'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <a href="https://rhodecode.server/repo_name" rel="nofollow">this</a>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ScmManager'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <code>http://YOURSCMMANAGER/scm/repo/NAMESPACE/NAME/</code>).
</div></div>

</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'MercurialInstallationSCMSourceTrait'</code><div>
<ul><li><code>installation : String</code>
</li>
</ul></div></li>
<li><code>multiBranchProjectDisplayNaming</code><div>
<div><div>
 Some branch source plugins provide additional information about discovered branches like a title or subject of merge or change requests.
 <br>
  With this trait, that additional information can be used for the job display names.
 <br><b>Note:</b> Job display name changes do not trigger builds.
</div></div>
<ul><li><code>displayNamingStrategy</code>
<div><div>
 The different strategies: 
 <ul>
  <li>
   <p><strong>Job display name with fallback to name:</strong> <br>
     Uses the branch source plugin's display name for the PR instead of the raw name <br>
     Value for configuration-as-code: <code>OBJECT_DISPLAY_NAME</code></p></li>
  <li>
   <p><strong>Name and, if available, display name:</strong> <br>
     Joins the raw name and the branch source plugin's display name <br>
     Value for configuration-as-code: <code>RAW_AND_OBJECT_DISPLAY_NAME</code></p></li>
 </ul>
</div></div>

<ul><li><b>Values:</b> <code>OBJECT_DISPLAY_NAME</code>, <code>RAW_AND_OBJECT_DISPLAY_NAME</code></li></ul></li>
</ul></div></li>
<li><code>gitHubNotificationContextTrait</code><div>
<div><div>
 Defines custom context labels to be sent as part of GitHub Status notifications for this project.
</div></div>
<ul><li><code>contextLabel : String</code>
<div><div>
 The text of the context label(s) for GitHub status notifications. If using multiple statuses, entries are separated by the specified delimiter.
</div></div>

</li>
<li><code>typeSuffix : boolean</code>
<div><div>
 <p>Appends the relevant suffix to the context label(s) based on the build type. '/pr-merge', '/pr-head' or '/branch'</p>
</div></div>

</li>
<li><code>multipleStatusDelimiter : String</code> (optional)
<div><div>
 The separator/delimiter used for splitting the Label field into multiple values.
</div></div>

</li>
<li><code>multipleStatuses : boolean</code> (optional)
<div><div>
 Configure multiple status notifications to be sent to GitHub.
</div></div>

</li>
</ul></div></li>
<li><code>gitLabOriginDiscovery</code><div>
<div><div>
 Discovers merge requests where the origin project is the same as the target project.
</div></div>
<ul><li><code>strategyId : int</code>
<div><div>
 Determines how merge requests are discovered: 
 <dl>
  <dt>
   Merging the merge request with the current target branch revision
  </dt>
  <dd>
   Discover each merge request once with the discovered revision corresponding to the result of merging with the current revision of the target branch
  </dd>
  <dt>
   The current merge request revision
  </dt>
  <dd>
   Discover each merge request once with the discovered revision corresponding to the merge request head revision without merging
  </dd>
  <dt>
   Both the current merge request revision and the merge request merged with the current target branch revision
  </dt>
  <dd>
   Discover each merge request twice. The first discovered revision corresponds to the result of merging with the current revision of the target branch in each scan. The second parallel discovered revision corresponds to the merge request head revision without merging
  </dd>
 </dl>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PathBasedPullRequestFilterTrait'</code><div>
<ul><li><code>inclusionField : String</code>
<div>If any of the changed files in a discovered PR match this regex then it will generate a build (unless excluded by the exclusion regex).</div>

</li>
<li><code>exclusionField : String</code>
<div>Any changed files in a discovered pull request that matches this regex will not be considered for the inclusion regex.</div>

</li>
</ul></div></li>
<li><code>$class: 'PreBuildMergeTrait'</code><div>
<ul><li><code>extension</code>
<ul><b>Nested Object</b>
<div><div>
 These options allow you to perform a merge to a particular branch before building. For example, you could specify an integration branch to be built, and to merge to master. In this scenario, on every change of integration, Jenkins will perform a merge with the master branch, and try to perform a build if the merge is successful. It then may push the merge back to the remote repository if the Git Push post-build action is selected.
</div></div>
<li><code>options</code>
<ul><b>Nested Object</b>
<li><code>mergeTarget : String</code>
<div><div>
 The name of the branch within the named repository to merge to, such as <code>master</code>.
</div></div>

</li>
<li><code>fastForwardMode</code> (optional)
<div><div>
 Merge fast-forward mode selection.
 <br>
  The default, --ff, gracefully falls back to a merge commit when required.
 <br>
  For more information, see the <a href="https://git-scm.com/docs/git-merge" rel="nofollow">Git Merge Documentation</a>
</div></div>

<ul><li><b>Values:</b> <code>FF</code>, <code>FF_ONLY</code>, <code>NO_FF</code></li></ul></li>
<li><code>mergeRemote : String</code> (optional)
<div><div>
 Name of the repository, such as <code>origin</code>, that contains the branch you specify below. If left blank, it'll default to the name of the first repository configured above.
</div></div>

</li>
<li><code>mergeStrategy</code> (optional)
<div><div>
 Merge strategy selection. <strong>This feature is not fully implemented in JGIT.</strong>
</div></div>

<ul><li><b>Values:</b> <code>DEFAULT</code>, <code>RESOLVE</code>, <code>RECURSIVE</code>, <code>OCTOPUS</code>, <code>OURS</code>, <code>SUBTREE</code>, <code>RECURSIVE_THEIRS</code></li></ul></li>
</ul></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'PretestedIntegrationSCMTrait'</code><div>
<ul><li><code>extension</code>
<ul><b>Nested Object</b>
<li><code>gitIntegrationStrategy</code>
<ul><b>Nested Choice of Objects</b>
<li><code>accumulated</code><div>
<div><h2>Accumulated Commit Strategy</h2>
<div>
 This strategy merges your commits with the --no-ff switch
</div></div>
<ul><li><code>shortCommitMessage : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>ffonly</code><div>
<div><h2>Fast Forward only (--ff-only) Strategy</h2>
<div>
 This strategy fast-forward only using the --ff-only switch - or fails
</div></div>
<ul><li><code>shortCommitMessage : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>squash</code><div>
<div><h2>Squashed Commit Strategy</h2>
<div>
 This strategy squashes all your commit on a given branch with the --squash option
</div></div>
<ul></ul></div></li>
</ul></li>
<li><code>integrationBranch : String</code>
<div><h3>What to specify</h3>
<p>The branch name must match your integration branch name. <b>No trailing slash.</b></p>
<h3>Merge is performed the following way</h3>
<h5>Squash commit</h5>
<pre>            git checkout -B &lt;Branch name&gt; &lt;Repository name&gt;/&lt;Branch name&gt;
            git merge --squash &lt;Branch matched by git&gt;
            git commit -C &lt;Branch matched by git&gt;</pre>
<h5>Accumulated commit</h5>
<pre>            git checkout -B &lt;Branch name&gt; &lt;Repository name&gt;/&lt;Branch name&gt;
            git merge -m &lt;commitMsg&gt; &lt;Branch matched by git&gt; --no-ff</pre>
<h3>When changes are pushed to the integration branch?</h3>
<p>Changes are only ever pushed when the build results is SUCCESS</p>
<pre>            git push &lt;Repository name&gt; &lt;Branch name&gt;</pre></div>

</li>
<li><code>repoName : String</code>
<div><div>
 <h3>What to specify</h3>
 <p>The repository name. In git the repository is always the name of the remote. So if you have specified a repository name in your Git configuration. You need to specify the exact same name here, otherwise no integration will be performed. We do the merge based on this.</p>
 <p><b>No trailing slash on repository name.</b></p>
 <p><span>Remember to specify this when working with NAMED repositories in Git</span></p>
</div></div>

</li>
</ul></li>
</ul></div></li>
<li><code>pruneStaleBranch</code><div>
<ul></ul></div></li>
<li><code>pruneStaleTag</code><div>
<ul></ul></div></li>
<li><code>bitbucketPublicRepoPullRequestFilter</code><div>
<div><div>
 If the repository being scanned is a public repository, this behaviour will exclude all pull requests. (Note: This behaviour is not especially useful if scanning a single repository as you could just not include the pull request discovery behaviours in the first place)
</div></div>
<ul></ul></div></li>
<li><code>$class: 'PullRequestDiscoveryTrait'</code><div>
<ul><li><code>excludeBranchesWithPRs : boolean</code>
<div><div>
 Exclude branches for which there is an open pull request
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PullRequestLabelsBlackListFilterTrait'</code><div>
<div><div>
 Filter github pull requests out by labels matching any labels specified.
</div></div>
<ul><li><code>labels : String</code>
<div><div>
 Labels to match a pull request. Use ',' to split multiple labels.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PullRequestLabelsMatchAllFilterTrait'</code><div>
<div><div>
 Filter github pull requests by labels matching all labels specified.
</div></div>
<ul><li><code>labels : String</code>
<div><div>
 Labels to match a pull request. Use ',' to split multiple labels.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PullRequestLabelsMatchAnyFilterTrait'</code><div>
<div><div>
 Filter github pull requests by labels matching any labels specified.
</div></div>
<ul><li><code>labels : String</code>
<div><div>
 Labels to match a pull request. Use ',' to split multiple labels.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PullRequestNameFilterTrait'</code><div>
<div><div>
 Filter Bitbucket Pull Requests by matching in title any phrase specified.
</div></div>
<ul><li><code>strategyId : int</code>
</li>
<li><code>phrase : String</code>
<div><div>
 Phrases to match a title of the pull request. Use ',' to split multiple phrases - only for no regular expression.
</div></div>

</li>
<li><code>ignoreCase : boolean</code>
<div><div>
 Case sensitivity defines whether uppercase and lowercase letters are treated as distinct (unchecked) or equivalent (checked).
</div></div>

</li>
<li><code>regex : boolean</code>
<div><div>
 Treat a phrase as a regular expression. Note, the comma character is part of the expression!
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PullRequestSourceBranchFilterTrait'</code><div>
<div><div>
 Filter Bitbucket Pull Requests by source branch.
</div></div>
<ul><li><code>strategyId : int</code>
</li>
<li><code>phrase : String</code>
<div><div>
 Phrases to match a title of the pull request. Use ',' to split multiple phrases - only for no regular expression.
</div></div>

</li>
<li><code>ignoreCase : boolean</code>
<div><div>
 Case sensitivity defines whether uppercase and lowercase letters are treated as distinct (unchecked) or equivalent (checked).
</div></div>

</li>
<li><code>regex : boolean</code>
<div><div>
 Treat a phrase as a regular expression. Note, the comma character is part of the expression!
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PullRequestTargetBranchFilterTrait'</code><div>
<div><div>
 Filter Bitbucket Pull Requests by target branch.
</div></div>
<ul><li><code>strategyId : int</code>
</li>
<li><code>phrase : String</code>
<div><div>
 Phrases to match a title of the pull request. Use ',' to split multiple phrases - only for no regular expression.
</div></div>

</li>
<li><code>ignoreCase : boolean</code>
<div><div>
 Case sensitivity defines whether uppercase and lowercase letters are treated as distinct (unchecked) or equivalent (checked).
</div></div>

</li>
<li><code>regex : boolean</code>
<div><div>
 Treat a phrase as a regular expression. Note, the comma character is part of the expression!
</div></div>

</li>
</ul></div></li>
<li><code>refSpecs</code><div>
<ul><li><code>templates</code>
<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
<div><div>
 A ref spec to fetch. Any occurrences of <code>@{remote}</code> will be replaced by the remote name (which defaults to <code>origin</code>) before use.
</div></div>

</li>
</ul></li>
</ul></div></li>
<li><code>headRegexFilterWithPRFromOrigin</code><div>
<ul><li><code>regex : String</code>
<div><div>
 A <a href="https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html" rel="nofollow">Java regular expression</a> to restrict the names. Names that do not match the supplied regular expression will be ignored.
</div></div>

</li>
<li><code>tagRegex : String</code>
<div><div>
 A <a href="https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html" rel="nofollow">Java regular expression</a> to restrict the names. Names for tags that do not match the supplied regular expression will be ignored.
</div></div>

</li>
</ul></div></li>
<li><code>giteaReleaseDiscovery</code><div>
<div><div>
 Discovers releases on the repository.
</div></div>
<ul><li><code>includePreReleases : boolean</code> (optional)
<div><div>
 If enabled, releases that are marked as pre-release are also discovered
</div></div>

</li>
<li><code>artifactToAssetMappingEnabled : boolean</code> (optional)
<div><div>
 If enabled, artifacts that where archived (i.e. via <code>archiveArtifacts</code>) will be added as assets in the release, but only if the build was successfull.
</div></div>

</li>
</ul></div></li>
<li><code>remoteName</code><div>
<ul><li><code>remoteName : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ScmManagerBranchDiscoveryTrait'</code><div>
<ul></ul></div></li>
<li><code>sparseCheckoutPaths</code><div>
<ul><li><code>extension</code>
<ul><b>Nested Object</b>
<div><div>
 <p>Specify the paths that you'd like to sparse checkout. This may be used for saving space (Think about a reference repository). Be sure to use a recent version of Git, at least above 1.7.10</p>
</div></div>
<li><code>sparseCheckoutPaths</code>
<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
</li>
</ul></li>
</ul></li>
</ul></div></li>
<li><code>submoduleOption</code><div>
<ul><li><code>extension</code>
<ul><b>Nested Object</b>
<li><code>depth : int</code> (optional)
<div><div>
 Set shallow clone depth, so that git will only download recent history of the project, saving time and disk space when you just want to access the latest commits of a repository.
</div></div>

</li>
<li><code>disableSubmodules : boolean</code> (optional)
<div><div>
 By disabling support for submodules you can still keep using basic git plugin functionality and just have Jenkins to ignore submodules completely as if they didn't exist.
</div></div>

</li>
<li><code>parentCredentials : boolean</code> (optional)
<div><div>
 Use credentials from the default remote of the parent project.
</div></div>

</li>
<li><code>recursiveSubmodules : boolean</code> (optional)
<div><div>
 Retrieve all submodules recursively (uses '--recursive' option which requires git&gt;=1.6.5)
</div></div>

</li>
<li><code>reference : String</code> (optional)
<div><div>
 Specify a folder containing a repository that will be used by Git as a reference during clone operations.
 <br>
  This option will be ignored if the folder is not available on the controller or agent where the clone is being executed.
 <br>
  To prepare a reference folder with multiple subprojects, create a bare git repository and add all the remote urls then perform a fetch:
 <br>
 <pre>  git init --bare
  git remote add SubProject1 https://gitrepo.com/subproject1
  git remote add SubProject2 https://gitrepo.com/subproject2
  git fetch --all
  </pre>
</div></div>

</li>
<li><code>shallow : boolean</code> (optional)
<div><div>
 Perform shallow clone, so that git will not download the history of the project, saving time and disk space when you just want to access the latest version of a repository.
</div></div>

</li>
<li><code>threads : int</code> (optional)
<div><div>
 Specify the number of threads that will be used to update submodules.
 <br>
  If unspecified, the command line git default thread count is used.
 <br>
</div></div>

</li>
<li><code>timeout : int</code> (optional)
<div><div>
 Specify a timeout (in minutes) for submodules operations.
 <br>
  This option overrides the default timeout of 10 minutes. 
 <br>
  You can change the global git timeout via the property org.jenkinsci.plugins.gitclient.Git.timeOut (see <a href="https://issues.jenkins.io/browse/JENKINS-11286" rel="nofollow">JENKINS-11286</a>). Note that property should be set on both controller and agent to have effect (see <a href="https://issues.jenkins.io/browse/JENKINS-22547" rel="nofollow">JENKINS-22547</a>).
</div></div>

</li>
<li><code>trackingSubmodules : boolean</code> (optional)
<div><div>
 Retrieve the tip of the configured branch in .gitmodules (Uses '--remote' option which requires git&gt;=1.8.2)
</div></div>

</li>
</ul></li>
</ul></div></li>
<li><code>mrTriggerComment</code><div>
<ul><li><code>commentBody : String</code>
<div><div>
 Add comment body you want to use to instruct Jenkins CI to rebuild the MR
</div></div>

</li>
<li><code>onlyTrustedMembersCanTrigger : boolean</code>
</li>
</ul></div></li>
<li><code>tuleapBranchDiscovery</code><div>
<ul></ul></div></li>
<li><code>tuleapNotifyPullRequest</code><div>
<ul></ul></div></li>
<li><code>tuleapForkPullRequestDiscovery</code><div>
<ul></ul></div></li>
<li><code>tuleapPullRequestDiscovery</code><div>
<ul></ul></div></li>
<li><code>userIdentity</code><div>
<ul><li><code>extension</code>
<ul><b>Nested Object</b>
<li><code>name : String</code>
<div><div>
 <p>If given, "GIT_COMMITTER_NAME=[this]" and "GIT_AUTHOR_NAME=[this]" are set for builds. This overrides whatever is in the global settings.</p>
</div></div>

</li>
<li><code>email : String</code>
<div><div>
 <p>If given, "GIT_COMMITTER_EMAIL=[this]" and "GIT_AUTHOR_EMAIL=[this]" are set for builds. This overrides whatever is in the global settings.</p>
</div></div>

</li>
</ul></li>
</ul></div></li>
<li><code>bitbucketWebhookConfiguration</code><div>
<div><div>
 <p>Sets the value for committersToIgnore in the Bitbucket Webhook. Value should be a comma separated string.</p>
 <p>committerToIgnore is used to prevent triggering Jenkins builds when commits by certain users are made.</p>
</div></div>
<ul><li><code>committersToIgnore : String</code>
</li>
</ul></div></li>
<li><code>WebhookListenerBuildConditionsTrait</code><div>
<ul><li><code>alwaysBuildMROpen : boolean</code> (optional)
</li>
<li><code>alwaysBuildMRReOpen : boolean</code> (optional)
</li>
<li><code>alwaysIgnoreMRApproval : boolean</code> (optional)
</li>
<li><code>alwaysIgnoreMRApproved : boolean</code> (optional)
</li>
<li><code>alwaysIgnoreMRUnApproval : boolean</code> (optional)
</li>
<li><code>alwaysIgnoreMRUnApproved : boolean</code> (optional)
</li>
<li><code>alwaysIgnoreMRWorkInProgress : boolean</code> (optional)
</li>
<li><code>alwaysIgnoreNonCodeRelatedUpdates : boolean</code> (optional)
<div><div>
 GitLab will send a webhook to Jenkins when there are updates to the MR including title changes, labels removed/added, etc. Enabling this option will prevent a build running if the cause was one of these updates. Note: these settings do not have any impact on build from comment settings.
</div></div>

</li>
</ul></div></li>
<li><code>headWildcardFilterWithPRFromOrigin</code><div>
<ul><li><code>includes : String</code>
<div><div>
 Space-separated list of branch name patterns to consider. You may use <code>*</code> as a wildcard; for example: <code>master release*</code>
</div></div>

</li>
<li><code>excludes : String</code>
<div><div>
 Branch name patterns to ignore even if matched by the includes list. For example: <code>release</code>
</div></div>

</li>
<li><code>tagIncludes : String</code>
<div><div>
 Space-separated list of tag name patterns to consider. You may use <code>*</code> as a wildcard; for example: <code>*-1.*</code> to build only 1.0 tags from the maven release plugin.
</div></div>

</li>
<li><code>tagExcludes : String</code>
<div><div>
 Tag name patterns to ignore even if matched by the tag includes list. For example: <code>*-0.*</code>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'WipeWorkspaceTrait'</code><div>
<ul></ul></div></li>
<li><code>bitbucketBranchDiscovery</code><div>
<div><div>
 Discovers branches on the repository.
</div></div>
<ul><li><code>strategyId : int</code>
<div><div>
 Determines which branches are discovered. 
 <dl>
  <dt>
   Exclude branches that are also filed as PRs
  </dt>
  <dd>
   If you are discovering origin pull requests, it may not make sense to discover the same changes both as a pull request and as a branch.
  </dd>
  <dt>
   Only branches that are also filed as PRs
  </dt>
  <dd>
   Discovers branches that have PR's associated with them. This may make sense if you have a notification sent to the team at the end of a triggered build or limited Jenkins resources.
  </dd>
  <dt>
   All branches
  </dt>
  <dd>
   Ignores whether the branch is also filed as a pull request and instead discovers all branches on the origin repository.
  </dd>
 </dl>
</div></div>

</li>
</ul></div></li>
<li><code>bitbucketForkDiscovery</code><div>
<div><div>
 Discovers pull requests where the origin repository is a fork of the target repository.
</div></div>
<ul><li><code>strategyId : int</code>
<div><div>
 Determines how pull requests are discovered. 
 <dl>
  <dt>
   Merging the pull request with the current target branch revision
  </dt>
  <dd>
   Discover each pull request once with the discovered revision corresponding to the result of merging with the current revision of the target branch
  </dd>
  <dt>
   The current pull request revision
  </dt>
  <dd>
   Discover each pull request once with the discovered revision corresponding to the pull request head revision without merging
  </dd>
  <dt>
   Both the current pull request revision and the pull request merged with the current target branch revision
  </dt>
  <dd>
   Discover each pull request twice. The first discovered revision corresponds to the result of merging with the current revision of the target branch in each scan. The second parallel discovered revision corresponds to the pull request head revision without merging
  </dd>
 </dl>
</div></div>

</li>
<li><code>trust</code>
<div><div>
 <p>One of the great powers of pull requests is that anyone with read access to a repository can fork it, commit some changes to their fork and then create a pull request against the original repository with their changes. There are some files stored in source control that are important. For example, a <code>Jenkinsfile</code> may contain configuration details to sandbox pull requests in order to mitigate against malicious pull requests. In order to protect against a malicious pull request itself modifying the <code>Jenkinsfile</code> to remove the protections, you can define the trust policy for pull requests from forks.</p>
 <p>Other plugins can extend the available trust policies. The default policies are:</p>
 <dl>
  <dt>
   Nobody
  </dt>
  <dd>
   Pull requests from forks will all be treated as untrusted. This means that where Jenkins requires a trusted file (e.g. <code>Jenkinsfile</code>) the contents of that file will be retrieved from the target branch on the origin repository and not from the pull request branch on the fork repository.
  </dd>
  <dt>
   Forks in the same account
  </dt>
  <dd>
   Bitbucket allows for a repository to be forked into a "sibling" repository in the same account but using a different name. This strategy will trust any pull requests from forks that are in the same account as the target repository on the basis that users have to have been granted write permission to account in order create such a fork.
  </dd>
  <dt>
   Everyone
  </dt>
  <dd>
   All pull requests from forks will be treated as trusted. <strong>NOTE:</strong> this option can be dangerous if used on a public repository hosted on Bitbucket Cloud.
  </dd>
 </dl>
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>bitbucketTrustEveryone</code><div>
<ul></ul></div></li>
<li><code>bitbucketTrustNobody</code><div>
<ul></ul></div></li>
<li><code>bitbucketTrustTeam</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>bitbucketPullRequestDiscovery</code><div>
<div><div>
 Discovers pull requests where the origin repository is the same as the target repository.
</div></div>
<ul><li><code>strategyId : int</code>
<div><div>
 Determines how pull requests are discovered. 
 <dl>
  <dt>
   Merging the pull request with the current target branch revision
  </dt>
  <dd>
   Discover each pull request once with the discovered revision corresponding to the result of merging with the current revision of the target branch
  </dd>
  <dt>
   The current pull request revision
  </dt>
  <dd>
   Discover each pull request once with the discovered revision corresponding to the pull request head revision without merging
  </dd>
  <dt>
   Both the current pull request revision and the pull request merged with the current target branch revision
  </dt>
  <dd>
   Discover each pull request twice. The first discovered revision corresponds to the result of merging with the current revision of the target branch in each scan. The second parallel discovered revision corresponds to the pull request head revision without merging
  </dd>
 </dl>
</div></div>

</li>
</ul></div></li>
<li><code>bitbucketSshCheckout</code><div>
<div><div>
 By default the discovered branches / pull requests will all use the same credentials that were used for discovery when checking out sources. This means that the checkout will be using the <code>https://</code> protocol for the Git repository. 
 <p>This behaviour allows you to select the SSH private key to be used for checking out sources, which will consequently force the checkout to use the <code>ssh://</code> protocol.</p>
</div></div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Credentials used to check out sources. 
 <p>It must be a SSH key based credential.</p>
</div></div>

</li>
</ul></div></li>
<li><code>bitbucketTagDiscovery</code><div>
<div><div>
 Discovers tags on the repository.
</div></div>
<ul></ul></div></li>
<li><code>bitbucketWebhookRegistration</code><div>
<div><div>
 <p>Overrides the defaults for webhook management.</p>
 <p>Webhooks are used to inform Jenkins about changes to repositories. There are two ways webhooks can be configured:</p>
 <ul>
  <li>Manual webhook configuration requires the user to configure Bitbucket with the Jenkins URL in order to ensure that Bitbucket will send the events to Jenkins after every change.</li>
  <li>Automatic webhook configuration requires that Jenkins has credentials with sufficient permission to configure webhooks and also that Jenkins knows the URL that Bitbucket can connect to.</li>
 </ul>
 <p>The <strong>Manage Jenkins  Configure Jenkins  Bitbucket Endpoints</strong> allows defining the list of servers. Each server can be associated with credentials. If credentials are defined then the default behaviour is to use those credentials to automatically manage the webhooks of all repositories that Jenkins is interested in. If no credentials are defined then the default behaviour is to require the user to manually configure webhooks.</p>
</div></div>
<ul><li><code>mode : String</code>
<div><div>
 There are two available modes: 
 <dl>
  <dt>
   Disable hook management
  </dt>
  <dd>
   Disables hook management irrespective of the global defaults.
  </dd>
  <dt>
   Use item credentials for hook management
  </dt>
  <dd>
   Enabled hook management but uses the selected credentials to manage the hooks rather than those defined in <strong>Manage Jenkins  Configure Jenkins  Bitbucket Endpoints</strong>
  </dd>
 </dl>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'com.cloudogu.scmmanager.scm.BranchDiscoveryTrait'</code><div>
<ul></ul></div></li>
<li><code>$class: 'com.cloudogu.scmmanager.scm.TagDiscoveryTrait'</code><div>
<ul></ul></div></li>
<li><code>dagshubBranchDiscovery</code><div>
<ul></ul></div></li>
<li><code>$class: 'io.jenkins.plugins.dagshubbranchsource.traits.ForkPullRequestDiscoveryTrait'</code><div>
<ul><li><code>buildOnPullHead : boolean</code> (optional)
<div><div>
 If checked, then the build will run on the commit at the tip of the pull request head, instead of first trying to merge it into the target branch and then running the build on the merged commit.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'io.jenkins.plugins.dagshubbranchsource.traits.OriginPullRequestDiscoveryTrait'</code><div>
<ul><li><code>buildOnPullHead : boolean</code> (optional)
<div><div>
 If checked, then the build will run on the commit at the tip of the pull request head, instead of first trying to merge it into the target branch and then running the build on the merged commit.
</div></div>

</li>
</ul></div></li>
<li><code>dagshubTagDiscovery</code><div>
<ul></ul></div></li>
<li><code>gitLabBranchDiscovery</code><div>
<div><div>
 Discovers branches on the repository.
</div></div>
<ul><li><code>strategyId : int</code>
<div><div>
 Determines which branches are discovered. 
 <dl>
  <dt>
   Only branches that are not also filed as MRs
  </dt>
  <dd>
   If you are discovering origin merge requests, it may not make sense to discover the same changes both as a merge request and as a branch.
  </dd>
  <dt>
   Only branches that are also filed as MRs
  </dt>
  <dd>
   This option exists to preserve legacy behaviour when upgrading from older versions of the plugin. NOTE: If you have an actual use case for this option please file a merge request against this text.
  </dd>
  <dt>
   All branches
  </dt>
  <dd>
   Ignores whether the branch is also filed as a merge request and instead discovers all branches on the origin project.
  </dd>
 </dl>
</div></div>

</li>
<li><code>branchesAlwaysIncludedRegex : String</code> (optional)
<div><div>
 Regular expression of branches that should always be included regardless of whether a merge request exists or not for those branches.
</div></div>

</li>
</ul></div></li>
<li><code>gitLabSshCheckout</code><div>
<div><div>
 By default the discovered branches / merge requests will all use the same username / password credentials that were used for discovery when checking out sources. This means that the checkout will be using the <code>https://</code> protocol for the Git repository. 
 <p>This behaviour allows you to select the SSH private key to be used for checking out sources, which will consequently force the checkout to use the <code>ssh://</code> protocol.</p>
</div></div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Credentials used to check out sources. Must be a SSH key based credential.
</div></div>

</li>
</ul></div></li>
<li><code>gitLabTagDiscovery</code><div>
<ul></ul></div></li>
<li><code>gitBranchDiscovery</code><div>
<div><div>
 Discovers branches on the repository.
</div></div>
<ul></ul></div></li>
<li><code>gitTagDiscovery</code><div>
<div><div>
 Discovers tags on the repository.
</div></div>
<ul></ul></div></li>
<li><code>headRegexFilter</code><div>
<ul><li><code>regex : String</code>
<div><div>
 A <a href="https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html" rel="nofollow">Java regular expression</a> to restrict the names. Names that do not match the supplied regular expression will be ignored.
 <br><strong>NOTE: this filter will be applied to all branch like things, including change requests</strong>
</div></div>

</li>
</ul></div></li>
<li><code>headWildcardFilter</code><div>
<ul><li><code>includes : String</code>
<div><div>
 Space-separated list of name patterns to consider. You may use <code>*</code> as a wildcard; for example: <code>master release*</code>
 <br><strong>NOTE: this filter will be applied to all branch like things, including change requests</strong>
</div></div>

</li>
<li><code>excludes : String</code>
<div><div>
 Space-separated list of name patterns to ignore even if matched by the includes list. For example: <code>release alpha-* beta-*</code>
 <br><strong>NOTE: this filter will be applied to all branch like things, including change requests</strong>
</div></div>

</li>
</ul></div></li>
<li><code>headRegexFilterWithPR</code><div>
<ul><li><code>regex : String</code>
<div><div>
 A <a href="https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html" rel="nofollow">Java regular expression</a> to restrict the names. Names that do not match the supplied regular expression will be ignored.
</div></div>

</li>
<li><code>tagRegex : String</code>
<div><div>
 A <a href="https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html" rel="nofollow">Java regular expression</a> to restrict the names. Names for tags that do not match the supplied regular expression will be ignored.
</div></div>

</li>
</ul></div></li>
<li><code>headWildcardFilterWithPR</code><div>
<ul><li><code>includes : String</code>
<div><div>
 Space-separated list of branch name patterns to consider. You may use <code>*</code> as a wildcard; for example: <code>master release*</code>
</div></div>

</li>
<li><code>excludes : String</code>
<div><div>
 Branch name patterns to ignore even if matched by the includes list. For example: <code>release</code>
</div></div>

</li>
<li><code>tagIncludes : String</code>
<div><div>
 Space-separated list of tag name patterns to consider. You may use <code>*</code> as a wildcard; for example: <code>*-1.*</code> to build only 1.0 tags from the maven release plugin.
</div></div>

</li>
<li><code>tagExcludes : String</code>
<div><div>
 Tag name patterns to ignore even if matched by the tag includes list. For example: <code>*-0.*</code>
</div></div>

</li>
</ul></div></li>
<li><code>giteaBranchDiscovery</code><div>
<div><div>
 Discovers branches on the repository.
</div></div>
<ul><li><code>strategyId : int</code>
<div><div>
 Determines which branches are discovered. 
 <dl>
  <dt>
   Exclude branches that are also filed as PRs
  </dt>
  <dd>
   If you are discovering origin pull requests, it may not make sense to discover the same changes both as a pull request and as a branch.
  </dd>
  <dt>
   Only branches that are also filed as PRs
  </dt>
  <dd>
   This option exists to preserve legacy behaviour when upgrading from older versions of the plugin. NOTE: If you have an actual use case for this option please file a pull request against this text.
  </dd>
  <dt>
   Only branches that are also filed as PRs or main
  </dt>
  <dd>
   Discover branches that are also files as PRs (have open PRs) or that are the master / main branch.
  </dd>
  <dt>
   All branches
  </dt>
  <dd>
   Ignores whether the branch is also filed as a pull request and instead discovers all branches on the origin repository.
  </dd>
 </dl>
</div></div>

</li>
</ul></div></li>
<li><code>giteaForkDiscovery</code><div>
<div><div>
 Discovers pull requests where the origin repository is a fork of the target repository.
</div></div>
<ul><li><code>strategyId : int</code>
<div><div>
 Determines how pull requests are discovered: 
 <dl>
  <dt>
   Merging the pull request with the current target branch revision
  </dt>
  <dd>
   Discover each pull request once with the discovered revision corresponding to the result of merging with the current revision of the target branch
  </dd>
  <dt>
   The current pull request revision
  </dt>
  <dd>
   Discover each pull request once with the discovered revision corresponding to the pull request head revision without merging
  </dd>
  <dt>
   Both the current pull request revision and the pull request merged with the current target branch revision
  </dt>
  <dd>
   Discover each pull request twice. The first discovered revision corresponds to the result of merging with the current revision of the target branch in each scan. The second parallel discovered revision corresponds to the pull request head revision without merging
  </dd>
 </dl>
</div></div>

</li>
<li><code>trust</code>
<div><div>
 <p>One of the great powers of pull requests is that anyone with read access to a repository can fork it, commit some changes to their fork and then create a pull request against the original repository with their changes. There are some files stored in source control that are important. For example, a <code>Jenkinsfile</code> may contain configuration details to sandbox pull requests in order to mitigate against malicious pull requests. In order to protect against a malicious pull request itself modifying the <code>Jenkinsfile</code> to remove the protections, you can define the trust policy for pull requests from forks.</p>
 <p>Other plugins can extend the available trust policies. The default policies are:</p>
 <dl>
  <dt>
   Nobody
  </dt>
  <dd>
   Pull requests from forks will all be treated as untrusted. This means that where Jenkins requires a trusted file (e.g. <code>Jenkinsfile</code>) the contents of that file will be retrieved from the target branch on the origin repository and not from the pull request branch on the fork repository.
  </dd>
  <dt>
   Contributors
  </dt>
  <dd>
   Pull requests from collaborators to the origin repository will be treated as trusted, all other pull requests from fork repositories will be treated as untrusted. Note that if credentials used by Jenkins for scanning the repository does not have permission to query the list of contributors to the origin repository then only the origin account will be treated as trusted - i.e. this will fall back to <code>Nobody</code>.
  </dd>
  <dt>
   Everyone
  </dt>
  <dd>
   All pull requests from forks will be treated as trusted. <strong>NOTE:</strong> this option can be dangerous if used on a public repository hosted on a Gitea instance that allows signup.
  </dd>
 </dl>
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>gitLabTrustMembers</code><div>
<ul></ul></div></li>
<li><code>bitbucketTrustTeam</code><div>
<ul></ul></div></li>
<li><code>bitbucketTrustEveryone</code><div>
<ul></ul></div></li>
<li><code>bitbucketTrustNobody</code><div>
<ul></ul></div></li>
<li><code>gitLabTrustEveryone</code><div>
<ul></ul></div></li>
<li><code>gitLabTrustNobody</code><div>
<ul></ul></div></li>
<li><code>gitLabTrustPermissions</code><div>
<ul></ul></div></li>
<li><code>giteaTrustContributors</code><div>
<ul></ul></div></li>
<li><code>giteaTrustEveryone</code><div>
<ul></ul></div></li>
<li><code>giteaTrustNobody</code><div>
<ul></ul></div></li>
<li><code>gitHubTrustContributors</code><div>
<ul></ul></div></li>
<li><code>gitHubTrustEveryone</code><div>
<ul></ul></div></li>
<li><code>gitHubTrustNobody</code><div>
<ul></ul></div></li>
<li><code>gitHubTrustPermissions</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>giteaPullRequestDiscovery</code><div>
<div><div>
 Discovers pull requests where the origin repository is the same as the target repository.
</div></div>
<ul><li><code>strategyId : int</code>
<div><div>
 Determines how pull requests are discovered: 
 <dl>
  <dt>
   Merging the pull request with the current target branch revision
  </dt>
  <dd>
   Discover each pull request once with the discovered revision corresponding to the result of merging with the current revision of the target branch
  </dd>
  <dt>
   The current pull request revision
  </dt>
  <dd>
   Discover each pull request once with the discovered revision corresponding to the pull request head revision without merging
  </dd>
  <dt>
   Both the current pull request revision and the pull request merged with the current target branch revision
  </dt>
  <dd>
   Discover each pull request twice. The first discovered revision corresponds to the result of merging with the current revision of the target branch in each scan. The second parallel discovered revision corresponds to the pull request head revision without merging
  </dd>
 </dl>
</div></div>

</li>
</ul></div></li>
<li><code>giteaSSHCheckout</code><div>
<div><div>
 By default the discovered branches / pull requests will all use the same username / password credentials that were used for discovery when checking out sources. This means that the checkout will be using the <code>https://</code> protocol for the Git repository. 
 <p>This behaviour allows you to select the SSH private key to be used for checking out sources, which will consequently force the checkout to use the <code>ssh://</code> protocol.</p>
</div></div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Credentials used to check out sources. Must be a SSH key based credential.
</div></div>

</li>
</ul></div></li>
<li><code>giteaTagDiscovery</code><div>
<ul></ul></div></li>
<li><code>giteaWebhookRegistration</code><div>
<div><div>
 <p>Overrides the defaults for webhook management.</p>
 <p>Webhooks are used to inform Jenkins about changes to repositories. There are two ways webhooks can be configured:</p>
 <ul>
  <li>Manual webhook configuration requires the user to configure Gitea with the Jenkins URL in order to ensure that Gitea will send the events to Jenkins after every change.</li>
  <li>Automatic webhook configuration requires that Jenkins has credentials with sufficient permission to configure webhooks and also that Jenkins knows the URL that Gitea can connect to.</li>
 </ul>
 <p>The <strong>Manage Jenkins  Configure System  Gitea Server</strong> allows defining the list of servers. Each server can be associated with credentials. If credentials are defined then the default behaviour is to use those credentials to automatically manage the webhooks of all repositories that Jenkins is interested in. If no credentials are defined then the default behaviour is to require the user to manually configure webhooks.</p>
</div></div>
<ul><li><code>mode : String</code>
<div><div>
 There are two available modes: 
 <dl>
  <dt>
   Disable hook management
  </dt>
  <dd>
   Disables hook management irrespective of the global defaults.
  </dd>
  <dt>
   Use item credentials for hook management
  </dt>
  <dd>
   Enabled hook management but uses the selected credentials to manage the hooks rather than those defined in <strong>Manage Jenkins  Configure System  Gitea Server</strong>
  </dd>
 </dl>
</div></div>

</li>
</ul></div></li>
<li><code>gitHubBranchDiscovery</code><div>
<div><div>
 Discovers branches on the repository.
</div></div>
<ul><li><code>strategyId : int</code>
<div><div>
 Determines which branches are discovered. 
 <dl>
  <dt>
   Exclude branches that are also filed as PRs
  </dt>
  <dd>
   If you are discovering origin pull requests, you may not want to also build the source branches for those pull requests.
  </dd>
  <dt>
   Only branches that are also filed as PRs
  </dt>
  <dd>
   Similar to discovering origin pull requests, but discovers the branch rather than the pull request. This means <code>env.GIT_BRANCH</code> will be set to the branch name rather than <code>PR-#</code>. Also, status notifications for these builds will only be applied to the commit and not to the pull request.
  </dd>
  <dt>
   All branches
  </dt>
  <dd>
   Ignores whether the branch is also filed as a pull request and instead discovers all branches on the origin repository.
  </dd>
 </dl>
</div></div>

</li>
</ul></div></li>
<li><code>gitHubForkDiscovery</code><div>
<div><div>
 Discovers pull requests where the origin repository is a fork of the target repository.
</div></div>
<ul><li><code>strategyId : int</code>
<div><div>
 Determines how pull requests are discovered: 
 <dl>
  <dt>
   Merging the pull request with the current target branch revision
  </dt>
  <dd>
   Discover each pull request once with the discovered revision corresponding to the result of merging with the current revision of the target branch. Note that pushes to the target branch will result in new pull request builds.
  </dd>
  <dt>
   The current pull request revision
  </dt>
  <dd>
   Discover each pull request once with the discovered revision corresponding to the pull request head revision without merging.
  </dd>
  <dt>
   Both the current pull request revision and the pull request merged with the current target branch revision
  </dt>
  <dd>
   Discover each pull request twice. The first discovered revision corresponds to the result of merging with the current revision of the target branch in each scan. The second parallel discovered revision corresponds to the pull request head revision without merging.
  </dd>
 </dl>
</div></div>

</li>
<li><code>trust</code>
<div><div>
 <p>One of the great powers of pull requests is that anyone with read access to a repository can fork it, commit some changes to their fork and then create a pull request against the original repository with their changes. There are some files stored in source control that are important. For example, a <code>Jenkinsfile</code> may contain configuration details to sandbox pull requests in order to mitigate against malicious pull requests. In order to protect against a malicious pull request itself modifying the <code>Jenkinsfile</code> to remove the protections, you can define the trust policy for pull requests from forks.</p>
 <p>Other plugins can extend the available trust policies. The default policies are:</p>
 <dl>
  <dt>
   Nobody
  </dt>
  <dd>
   Pull requests from forks will all be treated as untrusted. This means that where Jenkins requires a trusted file (e.g. <code>Jenkinsfile</code>) the contents of that file will be retrieved from the target branch on the origin repository and not from the pull request branch on the fork repository.
  </dd>
  <dt>
   Collaborators
  </dt>
  <dd>
   Pull requests from <a href="https://developer.github.com/v3/repos/collaborators/" rel="nofollow">collaborators</a> to the origin repository will be treated as trusted, all other pull requests from fork repositories will be treated as untrusted. Note that if credentials used by Jenkins for scanning the repository does not have permission to query the list of collaborators to the origin repository then only the origin account will be treated as trusted - i.e. this will fall back to <code>Nobody</code>. <strong>NOTE:</strong> all collaborators are trusted, even if they are only members of a team with read permission.
  </dd>
  <dt>
   Everyone
  </dt>
  <dd>
   All pull requests from forks will be treated as trusted. <strong>NOTE:</strong> this option can be dangerous if used on a public repository hosted on GitHub.
  </dd>
  <dt>
   From users with Admin or Write permission
  </dt>
  <dd>
   Pull requests forks will be treated as trusted if and only if the fork owner has either Admin or Write permissions on the origin repository. <strong>This is the recommended policy.</strong> Note that this strategy requires the <a href="https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level" rel="nofollow">Review a user's permission level</a> API, as a result on GitHub Enterprise Server versions before 2.12 this is the same as trusting <strong>Nobody</strong>.
  </dd>
 </dl>
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>gitHubTrustContributors</code><div>
<ul></ul></div></li>
<li><code>gitHubTrustEveryone</code><div>
<ul></ul></div></li>
<li><code>gitHubTrustNobody</code><div>
<ul></ul></div></li>
<li><code>gitHubTrustPermissions</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>gitHubPullRequestDiscovery</code><div>
<div><div>
 Discovers pull requests where the origin repository is the same as the target repository.
</div></div>
<ul><li><code>strategyId : int</code>
<div><div>
 Determines how pull requests are discovered: 
 <dl>
  <dt>
   Merging the pull request with the current target branch revision
  </dt>
  <dd>
   Discover each pull request once with the discovered revision corresponding to the result of merging with the current revision of the target branch. Note that pushes to the target branch will result in new pull request builds.
  </dd>
  <dt>
   The current pull request revision
  </dt>
  <dd>
   Discover each pull request once with the discovered revision corresponding to the pull request head revision without merging.
  </dd>
  <dt>
   Both the current pull request revision and the pull request merged with the current target branch revision
  </dt>
  <dd>
   Discover each pull request twice. The first discovered revision corresponds to the result of merging with the current revision of the target branch in each scan. The second parallel discovered revision corresponds to the pull request head revision without merging.
  </dd>
 </dl>
</div></div>

</li>
</ul></div></li>
<li><code>gitHubSshCheckout</code><div>
<div><div>
 By default the discovered branches / pull requests will all use the same username / password credentials that were used for discovery when checking out sources. This means that the checkout will be using the <code>https://</code> protocol for the Git repository. 
 <p>This behaviour allows you to select the SSH private key to be used for checking out sources, which will consequently force the checkout to use the <code>ssh://</code> protocol.</p>
</div></div>
<ul><li><code>credentialsId : String</code>
<div><div>
 Credentials used to check out sources. Must be a SSH key based credential.
</div></div>

</li>
</ul></div></li>
<li><code>gitHubTagDiscovery</code><div>
<div><div>
 Discovers tags on the repository.
</div></div>
<ul></ul></div></li>
</ul></li>
<li><code>id : String</code> (optional)
</li>
</ul></div></li>


++++