= $class: 'ExtensibleChoiceParameterDefinition'
:page-layout: pipelinesteps
== $class: 'ExtensibleChoiceParameterDefinition'

++++
<li><code>$class: 'ExtensibleChoiceParameterDefinition'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>choiceListProvider</code>
<div><div>
 Select a provider that gives choices when build.
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'ArtifactoryChoiceListProvider'</code><div>
<ul><li><code>artifactId : String</code> (optional)
<div><div>
 Mandatory: The artifactId to search for in the repository.
</div></div>

</li>
<li><code>classifier : String</code> (optional)
<div><div>
 The Maven Artifact classifier, i.E. "sources". By default leave empty. You can specifiy a list of valid or invalid classifier separated by Comma, i.E. "sources,!jar"
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 If your repository service requires user authentication, you'll have to configure the username and password here.
</div></div>

</li>
<li><code>filterExpression : String</code> (optional)
<div><div>
 Regular expression which filters the returned artifacts. Applied to the whole url. Allows extended grep syntax.
</div></div>

</li>
<li><code>groupId : String</code> (optional)
<div><div>
 Optional: The GroupId to search the artifact, i.E. "org.jenkins-ci.plugins"
</div></div>

</li>
<li><code>inverseFilter : boolean</code> (optional)
<div><div>
 Show only the results which do not match the regular expression specified in Filter Expression input field.
</div></div>

</li>
<li><code>packaging : String</code> (optional)
<div><div>
 Optional: Filters the matching packaging type from the results, i.E. "jar" or "zip". Use a * to return all the values. If parameter is not set, only the parent folder is returned.
</div></div>

</li>
<li><code>repositoryId : String</code> (optional)
</li>
<li><code>reverseOrder : boolean</code> (optional)
<div><div>
 If the list should be returned in reverse order.
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 Enter the URL of the Artifactory server, i.E. https://repo.jenkins-ci.org/
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'FilenameChoiceListProvider'</code><div>
<ul><li><code>baseDirPath : String</code>
<div><div>
 Specify the path to the directory to scan for files. This path will not be contained in choice list strings. If specified as a relative path, it is considered as relative to ${JENKINS_HOME}.
</div></div>

</li>
<li><code>includePattern : String</code>
<div><div>
 Specify the pattern of files to list. Multiple patterns can be specified with separating with comma(,). Wildcard is available like '**/*.xml'. See <a href="http://ant.apache.org/manual/Types/fileset.html" rel="nofollow">includes attribute of Ant FileSet Type</a> for the exact format.
</div></div>

</li>
<li><code>excludePattern : String</code>
<div><div>
 Specify patterns not to list (even specified in File Name Pattern field). See the help of "File Name Pattern" for the formats of patterns.
</div></div>

</li>
<li><code>scanType</code>
<div><div>
 Specify what type of files to list.
</div></div>

<ul><li><b>Values:</b> <code>File</code>, <code>Directory</code>, <code>FileAndDirectory</code></li></ul></li>
<li><code>reverseOrder : boolean</code>
<div><div>
 check to list files in reverse alphabetical order. If not checked, files are listed in alphabetical order.
</div></div>

</li>
<li><code>emptyChoiceType</code>
<div><div>
 Adds an empty choice to the specified place.
</div></div>

<ul><li><b>Values:</b> <code>None</code>, <code>AtTop</code>, <code>AtEnd</code></li></ul></li>
</ul></div></li>
<li><code>$class: 'GlobalTextareaChoiceListProvider'</code><div>
<ul><li><code>name : String</code>
<div><div>
 Select a name of the choice set, that you have specified in the system configuration.
</div></div>

</li>
<li><code>defaultChoice : String</code>
</li>
<li><code>addEditedValue : boolean</code>
</li>
<li><code>whenToAdd</code>
<ul><li><b>Values:</b> <code>Triggered</code>, <code>Completed</code>, <code>CompletedStable</code>, <code>CompletedUnstable</code></li></ul></li>
</ul></div></li>
<li><code>$class: 'MavenCentralChoiceListProvider'</code><div>
<ul><li><code>artifactId : String</code> (optional)
<div><div>
 Mandatory: The artifactId to search for in the repository.
</div></div>

</li>
<li><code>classifier : String</code> (optional)
<div><div>
 The Maven Artifact classifier, i.E. "sources". By default leave empty. You can specifiy a list of valid or invalid classifier separated by Comma, i.E. "sources,!jar"
</div></div>

</li>
<li><code>filterExpression : String</code> (optional)
<div><div>
 Regular expression which filters the returned artifacts. Applied to the whole url. Allows extended grep syntax.
</div></div>

</li>
<li><code>groupId : String</code> (optional)
<div><div>
 Optional: The GroupId to search the artifact, i.E. "org.jenkins-ci.plugins"
</div></div>

</li>
<li><code>inverseFilter : boolean</code> (optional)
<div><div>
 Show only the results which do not match the regular expression specified in Filter Expression input field.
</div></div>

</li>
<li><code>packaging : String</code> (optional)
<div><div>
 Optional: Filters the matching packaging type from the results, i.E. "jar" or "zip". Use a * to return all the values. If parameter is not set, only the parent folder is returned.
</div></div>

</li>
<li><code>repositoryId : String</code> (optional)
</li>
<li><code>reverseOrder : boolean</code> (optional)
<div><div>
 If the list should be returned in reverse order.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'MavenMetadataChoiceListProvider'</code><div>
<ul><li><code>artifactId : String</code> (optional)
<div><div>
 Mandatory: The exact artifactId to search for in the repository.
</div></div>

</li>
<li><code>classifier : String</code> (optional)
</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 If your repository service requires user authentication, you'll have to configure the username/password or token here.
</div></div>

</li>
<li><code>filterExpression : String</code> (optional)
<div><div>
 The Regular expression allows to apply a filters on the returned artifacts. Applied to the whole version. Allows extended grep syntax.
</div></div>

</li>
<li><code>groupId : String</code> (optional)
<div><div>
 Mandatory: The exact GroupId to search the artifact, i.E. "org.jenkins-ci.plugins".
</div></div>

</li>
<li><code>inverseFilter : boolean</code> (optional)
<div><div>
 Show only the results which do not match the regular expression specified in Filter Expression input field.
</div></div>

</li>
<li><code>packaging : String</code> (optional)
</li>
<li><code>repositoryId : String</code> (optional)
</li>
<li><code>reverseOrder : boolean</code> (optional)
<div><div>
 If the list should be returned in reverse order.
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 Enter the base URL to the maven_metadata.xml for a given repository, groupId, artifact.
 <br>
  It is advised to use virtual repositories which serve all the desired artifacts (snapshots+releases).
 <br>
  Plugin downloads the following url construct:
 <br>
  [base_url]/[repository]/[groupId hierarchy expanded]/[artifactId]/maven-metadata.xml
 <br>
  i.e. base_url: https://maven.mycompany.com/content/repository
 <br>
  repository: myrepository
 <br>
  groupId: my.group.id
 <br>
  artifactId: my-artifactId
 <br>
  https://maven.mycompany.com/content/repository/myrepository/my/group/id/my-artifactId/maven-metadata.xml
 <br>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'Nexus3ChoiceListProvider'</code><div>
<ul><li><code>artifactId : String</code> (optional)
<div><div>
 Mandatory/Optional: The artifactId to search for in the repository. Either provide at least the artifactId or the groupId. ArtifactId can contains *
</div></div>

</li>
<li><code>classifier : String</code> (optional)
<div><div>
 The Maven Artifact classifier, i.E. "sources". By default leave empty to get the default artifact. You can specifiy a list of valid or invalid classifier separated by Comma, i.E. "sources,!jar" or a "*" to retrieve all classifiers.
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 If your repository service requires user authentication, you'll have to configure the username and password here.
</div></div>

</li>
<li><code>filterExpression : String</code> (optional)
<div><div>
 Regular expression which filters the returned artifacts. Applied to the whole url. Allows extended grep syntax.
</div></div>

</li>
<li><code>groupId : String</code> (optional)
<div><div>
 Optional/Mandatory: The GroupId to search the artifact, i.E. "org.jenkins-ci.plugins". If ArtifactId is not defined you have to specify at least the GroupId.
</div></div>

</li>
<li><code>inverseFilter : boolean</code> (optional)
<div><div>
 Show only the results which do not match the regular expression specified in Filter Expression input field.
</div></div>

</li>
<li><code>packaging : String</code> (optional)
<div><div>
 Optional: Filters the matching packaging type from the results, i.E. "jar" or "zip". Use a * to return all the values. If parameter is not set, only the parent folder is returned.
</div></div>

</li>
<li><code>repositoryId : String</code> (optional)
<div><div>
 Optional: The repositoryId which should be searched, i.E. "snapshots" or "releases"
</div></div>

</li>
<li><code>reverseOrder : boolean</code> (optional)
<div><div>
 If the list should be returned in reverse order.
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 Enter the URL of the Nexus server, i.E. http://nexus.mycompany.com/nexus/
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'Nexus3GenericChoiceListProvider'</code><div>
<ul><li><code>name : String</code> (optional)
<div><div>
 Mandatory/Optional: The name to search for in the repository. Name can contain *
</div></div>

</li>
<li><code>artifactId : String</code> (optional)
</li>
<li><code>classifier : String</code> (optional)
</li>
<li><code>credentialsId : String</code> (optional)
</li>
<li><code>filterExpression : String</code> (optional)
<div><div>
 Regular expression which filters the returned artifacts. Applied to the whole url. Allows extended grep syntax.
</div></div>

</li>
<li><code>groupId : String</code> (optional)
</li>
<li><code>inverseFilter : boolean</code> (optional)
<div><div>
 Show only the results which do not match the regular expression specified in Filter Expression input field.
</div></div>

</li>
<li><code>packaging : String</code> (optional)
</li>
<li><code>repositoryId : String</code> (optional)
<div><div>
 Optional: The repositoryId which should be searched, i.E. "snapshots" or "releases"
</div></div>

</li>
<li><code>reverseOrder : boolean</code> (optional)
<div><div>
 If the list should be returned in reverse order.
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 Enter the URL of the Nexus server, i.E. http://nexus.mycompany.com/nexus/
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'NexusChoiceListProvider'</code><div>
<ul><li><code>artifactId : String</code> (optional)
<div><div>
 Mandatory/Optional: The artifactId to search for in the repository. Either provide at least the artifactId or the groupId. ArtifactId can contains *
</div></div>

</li>
<li><code>classifier : String</code> (optional)
<div><div>
 The Maven Artifact classifier, i.E. "sources". By default leave empty. You can specifiy a list of valid or invalid classifier separated by Comma, i.E. "sources,!jar"
</div></div>

</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 If your repository service requires user authentication, you'll have to configure the username and password here.
</div></div>

</li>
<li><code>filterExpression : String</code> (optional)
<div><div>
 Regular expression which filters the returned artifacts. Applied to the whole url. Allows extended grep syntax.
</div></div>

</li>
<li><code>groupId : String</code> (optional)
<div><div>
 Optional/Mandatory: The GroupId to search the artifact, i.E. "org.jenkins-ci.plugins". If ArtifactId is not defined you have to specify at least the GroupId.
</div></div>

</li>
<li><code>inverseFilter : boolean</code> (optional)
<div><div>
 Show only the results which do not match the regular expression specified in Filter Expression input field.
</div></div>

</li>
<li><code>packaging : String</code> (optional)
<div><div>
 Optional: Filters the matching packaging type from the results, i.E. "jar" or "zip". Use a * to return all the values. If parameter is not set, only the parent folder is returned.
</div></div>

</li>
<li><code>repositoryId : String</code> (optional)
<div><div>
 Optional: The repositoryId which should be searched, i.E. "snapshots" or "releases"
</div></div>

</li>
<li><code>reverseOrder : boolean</code> (optional)
<div><div>
 If the list should be returned in reverse order.
</div></div>

</li>
<li><code>url : String</code> (optional)
<div><div>
 Enter the URL of the Nexus server, i.E. http://nexus.mycompany.com/nexus/
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'SystemGroovyChoiceListProvider'</code><div>
<ul><li><code>groovyScript</code>
<ul><b>Nested Object</b>
<li><code>script : String</code>
</li>
<li><code>sandbox : boolean</code>
<div><div>
 If checked, run this Groovy script in a sandbox with limited abilities. If unchecked, and you are not a Jenkins administrator, you will need to wait for an administrator to approve the script.
</div></div>

</li>
<li><code>classpath</code>
<div><div>
 Additional classpath entries accessible from the script.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
<div><div>
 A path or URL to a JAR file. This path should be approved by an administrator or a user with the RUN_SCRIPT permission, or the script fails. If the file or files are once approved, they are treated approved even located in another path.
</div></div>

</li>
<li><code>oldPath : String</code> (optional)
</li>
<li><code>shouldBeApproved : boolean</code> (optional)
</li>
</ul></li>
<li><code>oldScript : String</code> (optional)
</li>
</ul></li>
<li><code>defaultChoice : String</code>
</li>
<li><code>usePredefinedVariables : boolean</code>
<div><div>
 <p>Enable following pre-defined variables:</p>
 <dl>
  <dt>
   project
  </dt>
  <dd>
   The project. An instance of <a href="http://javadoc.jenkins-ci.org/hudson/model/Job.html" rel="nofollow">Job</a>.
  </dd>
 </dl>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'TextareaChoiceListProvider'</code><div>
<ul><li><code>choiceListText : String</code>
</li>
<li><code>defaultChoice : String</code>
</li>
<li><code>addEditedValue : boolean</code>
</li>
<li><code>whenToAdd</code>
<ul><li><b>Values:</b> <code>Triggered</code>, <code>Completed</code>, <code>CompletedStable</code>, <code>CompletedUnstable</code></li></ul></li>
</ul></div></li>
</ul></li>
<li><code>editable : boolean</code>
<div><div>
 With checked, you can specify a parameter other than those in the choice. Of course, you can also select a parameter from the choice.
</div></div>

</li>
<li><code>description : String</code> (optional)
</li>
<li><code>editableType</code> (optional)
<ul><li><b>Values:</b> <code>NoFilter</code>, <code>Filter</code></li></ul></li>
</ul></div></li>


++++