= fromScm
:page-layout: pipelinesteps
== fromScm

++++
<li><code>fromScm</code><div>
<ul><li><code>name : String</code>
<div><div>
 The name of the SCM head/trunk/branch/tag that this source provides.
</div></div>

</li>
<li><code>scm</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'AWSCodePipelineSCM'</code><div>
<ul><li><code>name : String</code>
</li>
<li><code>clearWorkspace : boolean</code>
</li>
<li><code>region : String</code>
<div><div>
 <p>The AWS region must be the same to the region where your action runs in CodePipeline. Examples: "us-east-1", "cn-north-1", "us-gov-west-1". To list all supported regions, see <a href="https://docs.aws.amazon.com/general/latest/gr/codepipeline.html" rel="nofollow">AWS CodePipeline endpoints and quotas</a>.</p>
</div></div>

</li>
<li><code>awsAccessKey : String</code>
<div><div>
 <p>In order to integrate with AWS CodePipeline, you must authorize access to the pipeline and its related artifacts. If you installed Jenkins on a supported Amazon EC2 instance type, such as Amazon Linux, you can install the AWS CLI and configure a profile with the required credentials. This is the preferred method. In all other cases, you can store AWS credentials in these fields. You should securely configure your Jenkins instance to use HTTPS so that these credentials are not sent unencrypted.</p>
</div></div>

</li>
<li><code>awsSecretKey : String</code>
<div><div>
 <p>&gt;In order to integrate with AWS CodePipeline, you must authorize access to the pipeline and its related artifacts. If you installed Jenkins on a supported Amazon EC2 instance type, such as Amazon Linux, you can install the AWS CLI and configure a profile with the required credentials. This is the preferred method. In all other cases, you can store AWS credentials in these fields. You should securely configure your Jenkins instance to use HTTPS so that these credentials are not sent unencrypted.</p>
</div></div>

</li>
<li><code>proxyHost : String</code>
<div><div>
 <p>You might need a proxy host address if you are hosting Jenkins on a private network. The proxy name can be an IP address or DNS address. The AWS CodePipeline Plugin for Jenkins requires internet access. If access is not configured, you might see errors in the AWS CodePipeline Polling Log.</p>
</div></div>

</li>
<li><code>proxyPort : String</code>
<div><div>
 <p>You might need a proxy port for your proxy host address if you are hosting Jenkins on a private network. The proxy port is a number, might be on port 8080, 3128, or 8443, depending on your network protocols and security settings. If access is not configured, you might see errors in the AWS CodePipeline Polling Log.</p>
</div></div>

</li>
<li><code>category : String</code>
<div><div>
 <p>This is the category of the action type in AWS CodePipeline, and is usually either Build or Test. To see an example usage, see <a href="https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-four-stage-pipeline.html" rel="nofollow">Install and Configure the AWS CodePipeline Plugin for Jenkins</a>.</p>
</div></div>

</li>
<li><code>provider : String</code>
<div><div>
 <p>This is the provider name of the action type in AWS CodePipeline. You must provide this exact string when adding an action for Jenkins in AWS CodePipeline. To see an example usage, see <a href="https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-four-stage-pipeline.html" rel="nofollow">Install and Configure the AWS CodePipeline Plugin for Jenkins</a>.</p>
</div></div>

</li>
<li><code>version : String</code>
<div><div>
 <p>Leave the default as 1.</p>
</div></div>

</li>
</ul></div></li>
<li><code>accurev</code><div>
<ul><li><code>depot : String</code>
</li>
<li><code>stream : String</code>
</li>
<li><code>serverName : String</code> (optional)
</li>
<li><code>serverUUID : String</code> (optional)
</li>
<li><code>wspaceORreftree : String</code> (optional)
</li>
<li><code>accurevTool : String</code> (optional)
</li>
<li><code>cleanreftree : boolean</code> (optional)
</li>
<li><code>directoryOffset : String</code> (optional)
</li>
<li><code>dontPopContent : boolean</code> (optional)
</li>
<li><code>filterForPollSCM : String</code> (optional)
</li>
<li><code>ignoreStreamParent : boolean</code> (optional)
</li>
<li><code>reftree : String</code> (optional)
</li>
<li><code>snapshotNameFormat : String</code> (optional)
</li>
<li><code>subPath : String</code> (optional)
</li>
<li><code>subPathOnly : boolean</code> (optional)
</li>
<li><code>synctime : boolean</code> (optional)
</li>
<li><code>useSnapshot : boolean</code> (optional)
</li>
<li><code>workspace : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'BazaarSCM'</code><div>
<ul><li><code>source : String</code>
</li>
<li><code>cleantree : boolean</code>
</li>
<li><code>browser</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'Loggerhead'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Loggerhead is a web-based interface for <a href="http://bazaar-vcs.org" rel="nofollow">Bazaar </a> branches. It is used by <a href="https://launchpad.net" rel="nofollow">Launchpad</a>, so if your code is hosted on Launchpad, you are using Loggerhead.
</div>
<div>
 The repository browser URL for the root of the project. For example, a Launchpad project called myproject would use http://bazaar.launchpad.net/~myteam/myproject/mybranch.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'OpenGrok'</code><div>
<ul><li><code>url : String</code>
<div><div>
 The repository browser URL for the root of the project. For example, the OpenGrok project would use http://src.opensolaris.org/source/.
</div></div>

</li>
<li><code>rootModule : String</code>
<div><div>
 Specify the root Bazaar module that this OpenGrok monitors. For example, for http://src.opensolaris.org/source/xref/opengrok/trunk/, this field would be opengrok/trunk/ because it displays the directory "/opengrok/trunk/".
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>checkout : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'BitKeeperSCM'</code><div>
<ul><li><code>parent : String</code>
</li>
<li><code>localRepository : String</code>
</li>
<li><code>usePull : boolean</code>
</li>
<li><code>quiet : boolean</code>
</li>
</ul></div></li>
<li><code>BbS</code><div>
<ul><li><code>id : String</code>
</li>
<li><code>branches</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
<div><div>
 <p>Specify the branches if you'd like to track a specific branch in a repository. If left blank, all branches will be examined for changes and built.</p>
 <p>The safest way is to use the <code>refs/heads/&lt;branchName&gt;</code> syntax. This way the expected branch is unambiguous.</p>
 <p>If your branch name has a <code>/</code> in it make sure to use the full reference above. When not presented with a full path the plugin will only use the part of the string right of the last slash. Meaning <code>foo/bar</code> will actually match <code>bar</code>.</p>
 <p>If you use a wildcard branch specifier, with a slash (e.g. <code>release/</code>), you'll need to specify the origin repository in the branch names to make sure changes are picked up. So e.g. <code>origin/release/</code></p>
 <p>Possible options:</p>
 <ul>
  <li><strong><code>&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch. If ambiguous the first result is taken, which is not necessarily the expected one. Better use <code>refs/heads/&lt;branchName&gt;</code>.<br>
    E.g. <code>master</code>, <code>feature1</code>, ...</li>
  <li><strong><code>refs/heads/&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch.<br>
    E.g. <code>refs/heads/master</code>, <code>refs/heads/feature1/master</code>, ...</li>
  <li><strong><code>&lt;remoteRepoName&gt;/&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch. If ambiguous the first result is taken, which is not necessarily the expected one.<br>
    Better use <code>refs/heads/&lt;branchName&gt;</code>.<br>
    E.g. <code>origin/master</code></li>
  <li><strong><code>remotes/&lt;remoteRepoName&gt;/&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch.<br>
    E.g. <code>remotes/origin/master</code></li>
  <li><strong><code>refs/remotes/&lt;remoteRepoName&gt;/&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch.<br>
    E.g. <code>refs/remotes/origin/master</code></li>
  <li><strong><code>&lt;tagName&gt;</code></strong><br>
    This does not work since the tag will not be recognized as tag.<br>
    Use <code>refs/tags/&lt;tagName&gt;</code> instead.<br>
    E.g. <code>git-2.3.0</code></li>
  <li><strong><code>refs/tags/&lt;tagName&gt;</code></strong><br>
    Tracks/checks out the specified tag.<br>
    E.g. <code>refs/tags/git-2.3.0</code></li>
  <li><strong><code>&lt;commitId&gt;</code></strong><br>
    Checks out the specified commit.<br>
    E.g. <code>5062ac843f2b947733e6a3b105977056821bd352</code>, <code>5062ac84</code>, ...</li>
  <li><strong><code>${ENV_VARIABLE}</code></strong><br>
    It is also possible to use environment variables. In this case the variables are evaluated and the result is used as described above.<br>
    E.g. <code>${TREEISH}</code>, <code>refs/tags/${TAGNAME}</code>, ...</li>
  <li><strong><code>&lt;Wildcards&gt;</code></strong><br>
    The syntax is of the form: <code>REPOSITORYNAME/BRANCH</code>. In addition, <code>BRANCH</code> is recognized as a shorthand of <code>*/BRANCH</code>, '*' is recognized as a wildcard, and '**' is recognized as wildcard that includes the separator '/'. Therefore, <code>origin/branches*</code> would match <code>origin/branches-foo</code> but not <code>origin/branches/foo</code>, while <code>origin/branches**</code> would match both <code>origin/branches-foo</code> and <code>origin/branches/foo</code>.</li>
  <li><strong><code>:&lt;regular expression&gt;</code></strong><br>
    The syntax is of the form: <code>:regexp</code>. Regular expression syntax in branches to build will only build those branches whose names match the regular expression.<br>
    Examples:<br>
   <ul>
    <li><code>:^(?!(origin/prefix)).*</code>
     <ul>
      <li>matches: <code>origin</code> or <code>origin/master</code> or <code>origin/feature</code></li>
      <li>does not match: <code>origin/prefix</code> or <code>origin/prefix_123</code> or <code>origin/prefix-abc</code></li>
     </ul></li>
    <li><code>:origin/release-\d{8}</code>
     <ul>
      <li>matches: <code>origin/release-20150101</code></li>
      <li>does not match: <code>origin/release-2015010</code> or <code>origin/release-201501011</code> or <code>origin/release-20150101-something</code></li>
     </ul></li>
    <li><code>:^(?!origin/master$|origin/develop$).*</code>
     <ul>
      <li>matches: <code>origin/branch1</code> or <code>origin/branch-2</code> or <code>origin/master123</code> or <code>origin/develop-123</code></li>
      <li>does not match: <code>origin/master</code> or <code>origin/develop</code></li>
     </ul></li>
   </ul></li>
 </ul>
 <p></p>
</div></div>

</li>
</ul></li>
<li><code>credentialsId : String</code>
<div><div>
 <p>When running a job, Jenkins requires credentials to authenticate with Bitbucket Server. For example, to checkout the source code for builds. To do this, it needs credentials with access to the projects and repositories you want it to build from.</p>
 <p>You can provide Jenkins with credentials here by:</p>
 <ul>
  <li>selecting credentials from the list</li>
  <li>adding credentials as a <strong>Username with password</strong> (for the password, you can enter a Bitbucket Server password or a Bitbucket Server <a href="https://confluence.atlassian.com/x/a97-Nw" rel="nofollow">personal access token</a>)</li>
 </ul>
 <p>In addition, you can provide Jenkins with SSH credentials below. If you do, Jenkins will use them for clone operations instead of the credentials you select here.</p>
</div></div>

</li>
<li><code>sshCredentialsId : String</code>
<div><div>
 <p>If specified, Jenkins will use these credentials to check out the source code for builds. If no SSH credentials are specified, Jenkins will use the basic credentials instead.</p>
 <p>To provide Jenkins with SSH credentials, you can:</p>
 <ul>
  <li>choose credentials from the list</li>
  <li>add credentials as a <strong>SSH Username with private key</strong> (the username must be "git")</li>
 </ul>
</div></div>

</li>
<li><code>extensions</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>authorInChangelog</code><div>
<div><div>
 The default behavior is to use the Git commit's "Committer" value in Jenkins' build changesets. If this option is selected, the Git commit's "Author" value would be used instead.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'BuildChooserSetting'</code><div>
<div><div>
 When you are interested in using a job to build multiple heads (most typically multiple branches), you can choose how Jenkins choose what branches to build in what order. 
 <p>This extension point in Jenkins is used by many other plugins to control the job to build specific commits. When you activate those plugins, you may see them installing a custom strategy here.</p>
</div></div>
<ul><li><code>buildChooser</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'AlternativeBuildChooser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'AncestryBuildChooser'</code><div>
<ul><li><code>maximumAgeInDays : int</code>
</li>
<li><code>ancestorCommitSha1 : String</code>
</li>
</ul></div></li>
<li><code>$class: 'DefaultBuildChooser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'DeflakeGitBuildChooser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'GerritTriggerBuildChooser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'InverseBuildChooser'</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>buildSingleRevisionOnly</code><div>
<div><div>
 Disable scheduling for multiple candidate revisions.
 <br>
  If we have 3 branches:
 <br>
  ----A--.---.--- B
 <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\-----C
 <br>
  jenkins would try to build (B) and (C).
 <br>
  This behaviour disables this and only builds one of them.
 <br>
  It is helpful to reduce the load of the Jenkins infrastructure when the SCM system like Bitbucket or GitHub should decide what commits to build.
</div></div>
<ul></ul></div></li>
<li><code>changelogToBranch</code><div>
<div><div>
 This method calculates the changelog against the specified branch.
</div></div>
<ul><li><code>options</code>
<ul><b>Nested Object</b>
<li><code>compareRemote : String</code>
<div><div>
 Name of the repository, such as <code>origin</code>, that contains the branch you specify below.
</div></div>

</li>
<li><code>compareTarget : String</code>
<div><div>
 The name of the branch within the named repository to compare against.
</div></div>

</li>
</ul></li>
</ul></div></li>
<li><code>checkoutOption</code><div>
<ul><li><code>timeout : int</code>
<div><div>
 Specify a timeout (in minutes) for checkout.
 <br>
  This option overrides the default timeout of 10 minutes. 
 <br>
  You can change the global git timeout via the property org.jenkinsci.plugins.gitclient.Git.timeOut (see <a href="https://issues.jenkins.io/browse/JENKINS-11286" rel="nofollow">JENKINS-11286</a>). Note that property should be set on both controller and agent to have effect (see <a href="https://issues.jenkins.io/browse/JENKINS-22547" rel="nofollow">JENKINS-22547</a>).
</div></div>

</li>
</ul></div></li>
<li><code>cleanBeforeCheckout</code><div>
<div><div>
 Clean up the workspace before every checkout by deleting all untracked files and directories, including those which are specified in <code>.gitignore</code>. It also resets all <em>tracked</em> files to their versioned state. This ensures that the workspace is in the same state as if you cloned and checked out in a brand-new empty directory, and ensures that your build is not affected by the files generated by the previous build.
</div></div>
<ul><li><code>deleteUntrackedNestedRepositories : boolean</code> (optional)
<div><div>
 Deletes untracked submodules and any other subdirectories which contain <code>.git</code> directories.
</div></div>

</li>
</ul></div></li>
<li><code>cleanAfterCheckout</code><div>
<div><div>
 Clean up the workspace after every checkout by deleting all untracked files and directories, including those which are specified in <code>.gitignore</code>. It also resets all <em>tracked</em> files to their versioned state. This ensures that the workspace is in the same state as if you cloned and checked out in a brand-new empty directory, and ensures that your build is not affected by the files generated by the previous build.
</div></div>
<ul><li><code>deleteUntrackedNestedRepositories : boolean</code> (optional)
<div><div>
 Deletes untracked submodules and any other subdirectories which contain <code>.git</code> directories.
</div></div>

</li>
</ul></div></li>
<li><code>cloneOption</code><div>
<ul><li><code>shallow : boolean</code>
<div><div>
 Perform shallow clone, so that git will not download the history of the project, saving time and disk space when you just want to access the latest version of a repository.
</div></div>

</li>
<li><code>noTags : boolean</code>
<div><div>
 Deselect this to perform a clone without tags, saving time and disk space when you just want to access what is specified by the refspec.
</div></div>

</li>
<li><code>reference : String</code>
<div><div>
 Specify a folder containing a repository that will be used by Git as a reference during clone operations.
 <br>
  This option will be ignored if the folder is not available on the controller or agent where the clone is being executed.
</div></div>

</li>
<li><code>timeout : int</code>
<div><div>
 Specify a timeout (in minutes) for clone and fetch operations.
 <br>
  This option overrides the default timeout of 10 minutes. 
 <br>
  You can change the global git timeout via the property org.jenkinsci.plugins.gitclient.Git.timeOut (see <a href="https://issues.jenkins.io/browse/JENKINS-11286" rel="nofollow">JENKINS-11286</a>). Note that property should be set on both controller and agent to have effect (see <a href="https://issues.jenkins.io/browse/JENKINS-22547" rel="nofollow">JENKINS-22547</a>).
</div></div>

</li>
<li><code>depth : int</code> (optional)
<div><div>
 Set shallow clone depth, so that git will only download recent history of the project, saving time and disk space when you just want to access the latest commits of a repository.
</div></div>

</li>
<li><code>honorRefspec : boolean</code> (optional)
<div><div>
 Perform initial clone using the refspec defined for the repository. This can save time, data transfer and disk space when you only need to access the references specified by the refspec.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'CodeCommitURLHelper'</code><div>
<ul><li><code>credentialId : String</code>
<div><div>
 <p>OPTIONAL: Select the credentials to use.<br>
   If not specified, defaults to the <a href="http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html#using-the-default-credential-provider-chain" rel="nofollow"> DefaultAWSCredentialsProviderChain </a> behaviour - <b>*FROM THE JENKINS INSTANCE*</b></p>
 <p>In the latter case, usage of IAM Role Profiles seems not to work, thus relying on environment variables / system properties or the ~/.aws/credentials file, thus not recommended.</p>
</div></div>

</li>
<li><code>repositoryName : String</code>
</li>
</ul></div></li>
<li><code>$class: 'DisableRemotePoll'</code><div>
<div><div>
 Git plugin uses git ls-remote polling mechanism by default when configured with a single branch (no wildcards!). This compare the latest built commit SHA with the remote branch without cloning a local copy of the repo.
 <br>
 <br>
  If you don't want to / can't use this.
 <br>
 <br>
  If this option is selected, polling will require a workspace and might trigger unwanted builds (see <a href="https://issues.jenkins.io/browse/JENKINS-10131" rel="nofollow">JENKINS-10131</a>).
</div></div>
<ul></ul></div></li>
<li><code>$class: 'ExcludeFromChangeSet'</code><div>
<ul></ul></div></li>
<li><code>$class: 'ExcludeFromPoll'</code><div>
<ul></ul></div></li>
<li><code>lfs</code><div>
<div><div>
 Enable <a href="https://git-lfs.github.com/" rel="nofollow">git large file support</a> for the workspace by pulling large files after the checkout completes. Requires that the controller and each agent performing an LFS checkout have installed `git lfs`.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'GitSCMChecksExtension'</code><div>
<ul><li><code>verboseConsoleLog : boolean</code> (optional)
<div><div>
 If this option is checked, verbose log will be output to build console; the verbose log is useful for debugging the publisher creation.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GitSCMStatusChecksExtension'</code><div>
<ul><li><code>name : String</code> (optional)
</li>
<li><code>skip : boolean</code> (optional)
</li>
<li><code>skipProgressUpdates : boolean</code> (optional)
</li>
<li><code>suppressLogs : boolean</code> (optional)
</li>
<li><code>unstableBuildNeutral : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'GitTagMessageExtension'</code><div>
<div><div>
 If the revision checked out has a git tag associated with it, the tag name will be exported during the build as <strong>GIT_TAG_NAME</strong>. 
 <br>
  If a message was specified when creating the tag, then that message will be exported during the build as the <strong>GIT_TAG_MESSAGE</strong> environment variable. 
 <br>
  If no tag message was specified, the commit message will be used. 
 <br>
  If you ticked the <strong>Use most recent tag</strong> option, and the revision checked out has no git tag associated with it, the parent commits will be searched for a git tag, and the rules stated above will apply to the first parent commit with a git tag. 
 <p></p> If the revision has more than one tag associated with it, only the most recent tag will be taken into account, <strong>unless</strong> the refspec contains "refs/tags/" — i.e. builds are only triggered when certain tag names or patterns are matched — in which case the exact tag name that triggered the build will be used, even if it's not the most recent tag for this commit. 
 <br>
  For this reason, if you're not using a tag-specific refspec but you <em>are</em> using the "Create a tag for every build" behaviour, you should make sure that the build-tagging behaviour is configured to run <em>after</em> this "export git tag message" behaviour. 
 <p></p> Tag and commit messages which span multiple lines are no problem, though only the first 10000 lines of a tag's message will be exported.
</div></div>
<ul><li><code>useMostRecentTag : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'IgnoreNotifyCommit'</code><div>
<div><div>
 If checked, this repository will be ignored when the notifyCommit-URL is accessed regardless of if the repository matches or not.
</div></div>
<ul></ul></div></li>
<li><code>localBranch</code><div>
<div><div>
 If given, checkout the revision to build as HEAD on this branch. 
 <p>If selected, and its value is an empty string or "**", then the branch name is computed from the remote branch without the origin. In that case, a remote branch origin/master will be checked out to a local branch named master, and a remote branch origin/develop/new-feature will be checked out to a local branch named develop/newfeature.</p>
 <p>Please note that this has not been tested with submodules.</p>
</div></div>
<ul><li><code>localBranch : String</code>
</li>
</ul></div></li>
<li><code>$class: 'MessageExclusion'</code><div>
<ul><li><code>excludedMessage : String</code>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will ignore any revisions committed with message matched to <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html" rel="nofollow">Pattern</a> when determining if a build needs to be triggered. This can be used to exclude commits done by the build itself from triggering another build, assuming the build server commits the change with a distinct message. 
 <p></p>Exclusion uses <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html" rel="nofollow">Pattern</a> <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Matcher.html#matches()" rel="nofollow">matching</a>
 <p></p>
 <pre>.*\[maven-release-plugin\].*</pre> The example above illustrates that if only revisions with "[maven-release-plugin]" message in first comment line have been committed to the SCM a build will not occur. 
 <p></p> You can create more complex patterns using embedded flag expressions. 
 <pre>(?s).*FOO.*</pre> This example will search FOO message in all comment lines.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PathRestriction'</code><div>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will pay attention to included and/or excluded files and/or folders when determining if a build needs to be triggered. 
 <p></p> Using this behaviour will preclude the faster git ls-remote polling mechanism, forcing polling to require a workspace thus sometimes triggering unwanted builds, as if you had selected the <strong>Force polling using workspace</strong> extension as well.
</div></div>
<ul><li><code>includedRegions : String</code>
<div><div>
 Each inclusion uses <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html" rel="nofollow">java regular expression pattern matching</a>, and must be separated by a new line. An empty list implies that everything is included. 
 <p></p>
 <pre>    myapp/src/main/web/.*\.html
    myapp/src/main/web/.*\.jpeg
    myapp/src/main/web/.*\.gif
  </pre> The example above illustrates that a build will only occur, if html/jpeg/gif files have been committed to the SCM. Exclusions take precedence over inclusions, if there is an overlap between included and excluded regions.
</div></div>

</li>
<li><code>excludedRegions : String</code>
<div><div>
 Each exclusion uses <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html" rel="nofollow">java regular expression pattern matching</a>, and must be separated by a new line. 
 <p></p>
 <pre>    myapp/src/main/web/.*\.html
    myapp/src/main/web/.*\.jpeg
    myapp/src/main/web/.*\.gif
  </pre> The example above illustrates that if only html/jpeg/gif files have been committed to the SCM a build will not occur.
</div></div>

</li>
</ul></div></li>
<li><code>perBuildTag</code><div>
<div><div>
 Create a tag in the workspace for every build to unambiguously mark the commit that was built. You can combine this with Git publisher to push the tags to the remote repository.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'PreBuildMerge'</code><div>
<div><div>
 These options allow you to perform a merge to a particular branch before building. For example, you could specify an integration branch to be built, and to merge to master. In this scenario, on every change of integration, Jenkins will perform a merge with the master branch, and try to perform a build if the merge is successful. It then may push the merge back to the remote repository if the Git Push post-build action is selected.
</div></div>
<ul><li><code>options</code>
<ul><b>Nested Object</b>
<li><code>mergeTarget : String</code>
<div><div>
 The name of the branch within the named repository to merge to, such as <code>master</code>.
</div></div>

</li>
<li><code>fastForwardMode</code> (optional)
<div><div>
 Merge fast-forward mode selection.
 <br>
  The default, --ff, gracefully falls back to a merge commit when required.
 <br>
  For more information, see the <a href="https://git-scm.com/docs/git-merge" rel="nofollow">Git Merge Documentation</a>
</div></div>

<ul><li><b>Values:</b> <code>FF</code>, <code>FF_ONLY</code>, <code>NO_FF</code></li></ul></li>
<li><code>mergeRemote : String</code> (optional)
<div><div>
 Name of the repository, such as <code>origin</code>, that contains the branch you specify below. If left blank, it'll default to the name of the first repository configured above.
</div></div>

</li>
<li><code>mergeStrategy</code> (optional)
<div><div>
 Merge strategy selection. <strong>This feature is not fully implemented in JGIT.</strong>
</div></div>

<ul><li><b>Values:</b> <code>DEFAULT</code>, <code>RESOLVE</code>, <code>RECURSIVE</code>, <code>OCTOPUS</code>, <code>OURS</code>, <code>SUBTREE</code>, <code>RECURSIVE_THEIRS</code></li></ul></li>
</ul></li>
</ul></div></li>
<li><code>pretestedIntegration</code><div>
<ul><li><code>gitIntegrationStrategy</code>
<ul><b>Nested Choice of Objects</b>
<li><code>accumulated</code><div>
<div><h2>Accumulated Commit Strategy</h2>
<div>
 This strategy merges your commits with the --no-ff switch
</div></div>
<ul><li><code>shortCommitMessage : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>ffonly</code><div>
<div><h2>Fast Forward only (--ff-only) Strategy</h2>
<div>
 This strategy fast-forward only using the --ff-only switch - or fails
</div></div>
<ul><li><code>shortCommitMessage : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>squash</code><div>
<div><h2>Squashed Commit Strategy</h2>
<div>
 This strategy squashes all your commit on a given branch with the --squash option
</div></div>
<ul></ul></div></li>
</ul></li>
<li><code>integrationBranch : String</code>
<div><h3>What to specify</h3>
<p>The branch name must match your integration branch name. <b>No trailing slash.</b></p>
<h3>Merge is performed the following way</h3>
<h5>Squash commit</h5>
<pre>            git checkout -B &lt;Branch name&gt; &lt;Repository name&gt;/&lt;Branch name&gt;
            git merge --squash &lt;Branch matched by git&gt;
            git commit -C &lt;Branch matched by git&gt;</pre>
<h5>Accumulated commit</h5>
<pre>            git checkout -B &lt;Branch name&gt; &lt;Repository name&gt;/&lt;Branch name&gt;
            git merge -m &lt;commitMsg&gt; &lt;Branch matched by git&gt; --no-ff</pre>
<h3>When changes are pushed to the integration branch?</h3>
<p>Changes are only ever pushed when the build results is SUCCESS</p>
<pre>            git push &lt;Repository name&gt; &lt;Branch name&gt;</pre></div>

</li>
<li><code>repoName : String</code>
<div><div>
 <h3>What to specify</h3>
 <p>The repository name. In git the repository is always the name of the remote. So if you have specified a repository name in your Git configuration. You need to specify the exact same name here, otherwise no integration will be performed. We do the merge based on this.</p>
 <p><b>No trailing slash on repository name.</b></p>
 <p><span>Remember to specify this when working with NAMED repositories in Git</span></p>
</div></div>

</li>
</ul></div></li>
<li><code>pruneStaleBranch</code><div>
<div><div>
 Run "git remote prune" for each remote, to prune obsolete local branches.
</div></div>
<ul></ul></div></li>
<li><code>pruneTags</code><div>
<ul><li><code>pruneTags : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'RelativeTargetDirectory'</code><div>
<ul><li><code>relativeTargetDir : String</code>
<div><div>
 Specify a local directory (relative to <a rel="nofollow">the workspace root</a>) where the Git repository will be checked out. If left empty, the workspace root itself will be used. 
 <p>This extension should <strong>not</strong> be used in Jenkins Pipeline (either declarative or scripted). Jenkins Pipeline already provides standard techniques for checkout to a subdirectory. Use <a href="https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#ws-allocate-workspace" rel="nofollow">ws</a> and <a href="https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#dir-change-current-directory" rel="nofollow">dir</a> in Jenkins Pipeline rather than this extension.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ScmName'</code><div>
<div><div>
 <p>Unique name for this SCM. Needed when using Git within the Multi SCM plugin.</p>
</div></div>
<ul><li><code>name : String</code>
</li>
</ul></div></li>
<li><code>$class: 'SparseCheckoutPaths'</code><div>
<div><div>
 <p>Specify the paths that you'd like to sparse checkout. This may be used for saving space (Think about a reference repository). Be sure to use a recent version of Git, at least above 1.7.10</p>
</div></div>
<ul><li><code>sparseCheckoutPaths</code>
<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>submodule</code><div>
<ul><li><code>depth : int</code> (optional)
<div><div>
 Set shallow clone depth, so that git will only download recent history of the project, saving time and disk space when you just want to access the latest commits of a repository.
</div></div>

</li>
<li><code>disableSubmodules : boolean</code> (optional)
<div><div>
 By disabling support for submodules you can still keep using basic git plugin functionality and just have Jenkins to ignore submodules completely as if they didn't exist.
</div></div>

</li>
<li><code>parentCredentials : boolean</code> (optional)
<div><div>
 Use credentials from the default remote of the parent project.
</div></div>

</li>
<li><code>recursiveSubmodules : boolean</code> (optional)
<div><div>
 Retrieve all submodules recursively (uses '--recursive' option which requires git&gt;=1.6.5)
</div></div>

</li>
<li><code>reference : String</code> (optional)
<div><div>
 Specify a folder containing a repository that will be used by Git as a reference during clone operations.
 <br>
  This option will be ignored if the folder is not available on the controller or agent where the clone is being executed.
 <br>
  To prepare a reference folder with multiple subprojects, create a bare git repository and add all the remote urls then perform a fetch:
 <br>
 <pre>  git init --bare
  git remote add SubProject1 https://gitrepo.com/subproject1
  git remote add SubProject2 https://gitrepo.com/subproject2
  git fetch --all
  </pre>
</div></div>

</li>
<li><code>shallow : boolean</code> (optional)
<div><div>
 Perform shallow clone, so that git will not download the history of the project, saving time and disk space when you just want to access the latest version of a repository.
</div></div>

</li>
<li><code>threads : int</code> (optional)
<div><div>
 Specify the number of threads that will be used to update submodules.
 <br>
  If unspecified, the command line git default thread count is used.
 <br>
</div></div>

</li>
<li><code>timeout : int</code> (optional)
<div><div>
 Specify a timeout (in minutes) for submodules operations.
 <br>
  This option overrides the default timeout of 10 minutes. 
 <br>
  You can change the global git timeout via the property org.jenkinsci.plugins.gitclient.Git.timeOut (see <a href="https://issues.jenkins.io/browse/JENKINS-11286" rel="nofollow">JENKINS-11286</a>). Note that property should be set on both controller and agent to have effect (see <a href="https://issues.jenkins.io/browse/JENKINS-22547" rel="nofollow">JENKINS-22547</a>).
</div></div>

</li>
<li><code>trackingSubmodules : boolean</code> (optional)
<div><div>
 Retrieve the tip of the configured branch in .gitmodules (Uses '--remote' option which requires git&gt;=1.8.2)
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'UserExclusion'</code><div>
<ul><li><code>excludedUsers : String</code>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will ignore any revisions committed by users in this list when determining if a build needs to be triggered. This can be used to exclude commits done by the build itself from triggering another build, assuming the build server commits the change with a distinct SCM user. 
 <p></p> Using this behaviour will preclude the faster git ls-remote polling mechanism, forcing polling to require a workspace thus sometimes triggering unwanted builds, as if you had selected the <strong>Force polling using workspace</strong> extension as well. 
 <p></p>Each exclusion uses exact string comparison and must be separated by a new line. User names are only excluded if they exactly match one of the names in this list. 
 <p></p>
 <pre>auto_build_user</pre> The example above illustrates that if only revisions by "auto_build_user" have been committed to the SCM a build will not occur.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'UserIdentity'</code><div>
<ul><li><code>name : String</code>
<div><div>
 <p>If given, "GIT_COMMITTER_NAME=[this]" and "GIT_AUTHOR_NAME=[this]" are set for builds. This overrides whatever is in the global settings.</p>
</div></div>

</li>
<li><code>email : String</code>
<div><div>
 <p>If given, "GIT_COMMITTER_EMAIL=[this]" and "GIT_AUTHOR_EMAIL=[this]" are set for builds. This overrides whatever is in the global settings.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'WipeWorkspace'</code><div>
<div><div>
 Delete the contents of the workspace before building, ensuring a fully fresh workspace.
</div></div>
<ul></ul></div></li>
</ul></li>
<li><code>gitTool : String</code>
</li>
<li><code>projectName : String</code>
<div><div>
 <p>Enter the name of the Bitbucket Server project containing the repository you want Jenkins to build from. To find a project, start typing. If it doesn't appear in the search results, the credentials that you've chosen may not have read access to it and you'll need to provide different credentials.</p>
 <p>To get Jenkins to build from a personal repository, enter a tilde (<code>~</code>) followed by repository owner's username. For example, <code>~jsmith.</code></p>
</div></div>

</li>
<li><code>repositoryName : String</code>
<div><div>
 <p>Enter the Bitbucket Server repository you want Jenkins to build from. To find a repository, start typing. If it doesn't appear in the search results, the credentials that you've chosen may not have read access to it and you'll need to provide different credentials.</p>
 <p>To get Jenkins to build from a personal repository, enter its slug. This is the URL-friendly version of the repository name. For example, a repository called my example repo will have the slug <em>my-example-repo</em>, and you can see this in its URL, https://bitbucketserver.mycompany.com/myproject/my-example-repo.</p>
</div></div>

</li>
<li><code>serverId : String</code>
<div><div>
 <p>Choose the Bitbucket Server instance containing the repository you want Jenkins to build from. If you can't find your instance, check this plugin's configuration and try again.</p>
</div></div>

</li>
<li><code>mirrorName : String</code>
<div><div>
 <p>Choose the location that Jenkins should clone from when running this build. This can be the primary server or a mirror if one is available. To see available mirrors, first choose a Bitbucket Server project and repository.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'BlameSubversionSCM'</code><div>
<div><div>
 <p>if it is false and the build is not triggered by upstream job,</p>
 <p></p>
 <p>the plugin will not collect any svn info from upstream job.</p>
 <p>else the plugin will collect svn info from latest upstream job</p>
</div></div>
<ul><li><code>alwaysCollectSVNInfo : boolean</code>
</li>
</ul></div></li>
<li><span><a href="/doc/pipeline/steps/params/ccucmscm"><code>$class: 'CCUCMScm'</code></a></span></li>
<li><span><a href="/doc/pipeline/steps/params/cvsscm"><code>$class: 'CVSSCM'</code></a></span></li>
<li><code>$class: 'ClearCaseSCM'</code><div>
<ul><li><code>branch : String</code>
</li>
<li><code>label : String</code>
</li>
<li><code>extractConfigSpec : boolean</code>
</li>
<li><code>configSpecFileName : String</code>
</li>
<li><code>refreshConfigSpec : boolean</code>
</li>
<li><code>refreshConfigSpecCommand : String</code>
</li>
<li><code>configSpec : String</code>
</li>
<li><code>viewTag : String</code>
</li>
<li><code>useupdate : boolean</code>
</li>
<li><code>extractLoadRules : boolean</code>
</li>
<li><code>loadRules : String</code>
</li>
<li><code>useOtherLoadRulesForPolling : boolean</code>
</li>
<li><code>loadRulesForPolling : String</code>
</li>
<li><code>usedynamicview : boolean</code>
</li>
<li><code>viewdrive : String</code>
</li>
<li><code>mkviewoptionalparam : String</code>
</li>
<li><code>filterOutDestroySubBranchEvent : boolean</code>
</li>
<li><code>doNotUpdateConfigSpec : boolean</code>
</li>
<li><code>rmviewonrename : boolean</code>
</li>
<li><code>excludedRegions : String</code>
</li>
<li><code>multiSitePollBuffer : String</code>
</li>
<li><code>useTimeRule : boolean</code>
</li>
<li><code>createDynView : boolean</code>
</li>
<li><code>viewPath : String</code>
</li>
<li><code>changeset</code>
<ul><li><b>Values:</b> <code>ALL</code>, <code>BRANCH</code>, <code>NONE</code>, <code>UPDT</code></li></ul></li>
<li><code>viewStorage</code>
<div><p>Three strategies are currently available to manage view storage location.</p>
<ul>
 <li><b>Default</b>. This entry doesn't generate any additional argument to the <i>cleartool mkview</i> command. The behaviour will change depending on how your clearcase server is configured.</li>
 <li><b>Use server storage location</b>. This entry generates a <i>-stgloc</i> argument to the <i>cleartool mkview</i> command.</li>
 <li><b>Use explicit path</b>. This entry generates a <i>-vws</i> argument to the <i>cleartool mkview</i> command.</li>
</ul>
<p></p></div>

<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'DefaultViewStorage'</code><div>
<ul></ul></div></li>
<li><code>$class: 'ServerViewStorage'</code><div>
<ul><li><code>assignedLabelString : String</code>
<div><p>Label expression used to populate view storage location dropdown.</p></div>

</li>
<li><code>server : String</code>
<div><p>The view storage location that will be passed to the <i>-stgloc</i> option.<br>
  The list of available servers is retrieved using <i>cleartool lsstgloc -view</i><br>
  Note that auto is always available.</p></div>

</li>
</ul></div></li>
<li><code>$class: 'SpecificViewStorage'</code><div>
<ul><li><code>winStorageDir : String</code>
</li>
<li><code>unixStorageDir : String</code>
</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'ClearCaseUcmBaselineSCM'</code><div>
<div><div>
 When used (and fully set up), this option will display a field at build-time so that the user is able to select a ClearCase UCM baseline from which to download the content for this project.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'ClearCaseUcmSCM'</code><div>
<ul><li><code>stream : String</code>
</li>
<li><code>loadrules : String</code>
</li>
<li><code>viewTag : String</code>
</li>
<li><code>usedynamicview : boolean</code>
</li>
<li><code>viewdrive : String</code>
</li>
<li><code>mkviewoptionalparam : String</code>
</li>
<li><code>filterOutDestroySubBranchEvent : boolean</code>
</li>
<li><code>useUpdate : boolean</code>
</li>
<li><code>rmviewonrename : boolean</code>
</li>
<li><code>excludedRegions : String</code>
</li>
<li><code>multiSitePollBuffer : String</code>
</li>
<li><code>overrideBranchName : String</code>
</li>
<li><code>createDynView : boolean</code>
</li>
<li><code>freezeCode : boolean</code>
</li>
<li><code>recreateView : boolean</code>
</li>
<li><code>allocateViewName : boolean</code>
</li>
<li><code>viewPath : String</code>
</li>
<li><code>useManualLoadRules : boolean</code>
</li>
<li><code>changeset</code>
<ul><li><b>Values:</b> <code>ALL</code>, <code>BRANCH</code>, <code>NONE</code>, <code>UPDT</code></li></ul></li>
<li><code>viewStorage</code>
<div><p>Three strategies are currently available to manage view storage location.</p>
<ul>
 <li><b>Default</b>. This entry doesn't generate any additional argument to the <i>cleartool mkview</i> command. The behaviour will change depending on how your clearcase server is configured.</li>
 <li><b>Use server storage location</b>. This entry generates a <i>-stgloc</i> argument to the <i>cleartool mkview</i> command.</li>
 <li><b>Use explicit path</b>. This entry generates a <i>-vws</i> argument to the <i>cleartool mkview</i> command.</li>
</ul>
<p></p></div>

<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'DefaultViewStorage'</code><div>
<ul></ul></div></li>
<li><code>$class: 'ServerViewStorage'</code><div>
<ul><li><code>assignedLabelString : String</code>
<div><p>Label expression used to populate view storage location dropdown.</p></div>

</li>
<li><code>server : String</code>
<div><p>The view storage location that will be passed to the <i>-stgloc</i> option.<br>
  The list of available servers is retrieved using <i>cleartool lsstgloc -view</i><br>
  Note that auto is always available.</p></div>

</li>
</ul></div></li>
<li><code>$class: 'SpecificViewStorage'</code><div>
<ul><li><code>winStorageDir : String</code>
</li>
<li><code>unixStorageDir : String</code>
</li>
</ul></div></li>
</ul></li>
<li><code>buildFoundationBaseline : boolean</code>
<div><p>If checked, instead of creating a view on the current stream, the job will look up the current foundation baselines for the given stream and work in readonly on these baselines. If polling is enabled, the build will be triggered every time a new foundation baseline is detected on the given stream.</p></div>

</li>
</ul></div></li>
<li><code>$class: 'CloneWorkspaceSCM'</code><div>
<ul><li><code>parentJobName : String</code>
</li>
<li><code>criteria : String</code>
</li>
</ul></div></li>
<li><code>$class: 'CmvcSCM'</code><div>
<ul><li><code>family : String</code>
</li>
<li><code>become : String</code>
</li>
<li><code>releases : String</code>
</li>
<li><code>checkoutScript : String</code>
</li>
<li><code>trackViewReportWhereClause : String</code>
</li>
</ul></div></li>
<li><span><a href="/doc/pipeline/steps/params/cvsprojectset"><code>$class: 'CvsProjectset'</code></a></span></li>
<li><code>$class: 'DarcsScm'</code><div>
<ul><li><code>source : String</code>
</li>
<li><code>localDir : String</code>
</li>
<li><code>clean : boolean</code>
</li>
<li><code>browser</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'DarcsWeb'</code><div>
<ul><li><code>url : String</code>
</li>
<li><code>repo : String</code>
</li>
</ul></div></li>
<li><code>$class: 'Darcsden'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'DimensionsSCM'</code><div>
<ul><li><code>project : String</code>
</li>
<li><code>credentialsType : String</code>
</li>
<li><code>userName : String</code>
</li>
<li><code>password : String</code>
</li>
<li><code>pluginServer : String</code>
</li>
<li><code>userServer : String</code>
</li>
<li><code>keystoreServer : String</code>
</li>
<li><code>pluginDatabase : String</code>
</li>
<li><code>userDatabase : String</code>
</li>
<li><code>keystoreDatabase : String</code>
</li>
<li><code>keystorePath : String</code>
</li>
<li><code>certificateAlias : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>certificatePassword : String</code>
</li>
<li><code>keystorePassword : String</code>
</li>
<li><code>certificatePath : String</code>
</li>
<li><code>remoteCertificatePassword : String</code>
</li>
<li><code>secureAgentAuth : boolean</code>
</li>
<li><code>canJobDelete : boolean</code> (optional)
</li>
<li><code>canJobExpand : boolean</code> (optional)
</li>
<li><code>canJobForce : boolean</code> (optional)
</li>
<li><code>canJobNoMetadata : boolean</code> (optional)
</li>
<li><code>canJobNoTouch : boolean</code> (optional)
</li>
<li><code>canJobRevert : boolean</code> (optional)
</li>
<li><code>canJobUpdate : boolean</code> (optional)
</li>
<li><code>eol : String</code> (optional)
</li>
<li><code>folders</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>pathsToExclude</code> (optional)
<ul><b>Array / List of Nested Object</b>
<li><code>value : String</code>
</li>
</ul></li>
<li><code>permissions : String</code> (optional)
</li>
<li><code>timeZone : String</code> (optional)
</li>
<li><code>webUrl : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'DrushMakefileSCM'</code><div>
<ul><li><code>makefile : String</code>
<div><div>
 <p>Specify the content of the <a href="https://www.drupal.org/node/1432374" rel="nofollow">Makefile</a>. Support for YAML Makefiles depends on the version of Drush you have installed.</p>
 <p>This example will generate a vanilla Drupal 7.38:</p>
 <pre>    api=2
    core=7.x
    projects[drupal][version]=7.38
    </pre>
 <p></p>
</div></div>

</li>
<li><code>root : String</code>
<div><div>
 Specify a local directory for the Drupal root (relative to the <a rel="nofollow">workspace root</a>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'EndevorConfiguration'</code><div>
<ul><li><code>connectionId : String</code>
</li>
<li><code>filterPattern : String</code>
</li>
<li><code>fileExtension : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>targetFolder : String</code>
</li>
</ul></div></li>
<li><code>filesystem</code><div>
<ul><li><code>path : String</code>
<div><div>
 <p>The file path for the source code.</p>
 <p>e.g. \\Server1\project1\src or c:\myproject\src</p>
 <p>Note for distributed build environment, please make sure the path is accessible on remote node(s)</p>
</div></div>

</li>
<li><code>clearWorkspace : boolean</code>
<div><div>
 <p>If true, the system will delete all existing files/sub-folders in workspace before checking-out. Poll changes will not be affected by this setting.</p>
</div></div>

</li>
<li><code>copyHidden : boolean</code>
<div><div>
 <p>If true, the system will copy hidden files and folders as well. Default is false.</p>
</div></div>

</li>
<li><code>filterSettings</code>
<ul><b>Nested Object</b>
<li><code>includeFilter : boolean</code>
</li>
<li><code>selectors</code>
<div><div>
 <p>You can apply wildcard filter(s) when detecting changes and copying files. By default, the system will filter out hidden files, on Unix, that means files/folder starting with ".", on Windows, that means files/folders with "hidden" attribute. You may want to filter out, e.g. files with ".tmp" extension.</p>
 <p>Note: filters are applied on both sides, source and destination (i.e. the workspace). E.g. if you filter out ".tmp" files, all ".tmp" files currently in workspace will not be removed.</p>
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>wildcard : String</code>
<div><div>
 <p>ANT style wildcard.</p>
 <p>To include just *.java, set filter type to "Include" and type add "*.java" (without quote) in the wildcard. To exclude *.exe" and all JUnit test cases, set filter type to "Exclude" and add two wildcard, one for "*.dll" and one for "*Test*"</p>
 <p>To exclude a directory, set filter to "**/dir_to_exclude/**"</p>
 <p>Note: (1) the wildcard is case insensitive, (2) all backslashes (\) will be replaced with slashes (/)</p>
</div></div>

</li>
</ul></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'FeatureBranchAwareMercurialSCM'</code><div>
<ul><li><code>installation : String</code>
</li>
<li><code>source : String</code>
<div><div>
 Specify the repository to track. This can be URL or a local file path.
</div></div>

</li>
<li><code>branch : String</code>
<div><div>
 Specify the branch name if you'd like to track a specific branch in a repository. Leave this field empty otherwise, to track the "default" branch.
</div></div>

</li>
<li><code>modules : String</code>
<div><div>
 Reduce unnecessary builds by specifying a comma or space delimited list of "modules" within the repository. A module is a directory name within the repository that this project lives in. If this field is set, changes outside the specified modules will not trigger a build (even though the whole repository is checked out anyway due to the Mercurial limitation.)
</div></div>

</li>
<li><code>subdir : String</code>
<div><div>
 If not empty, check out the Mercurial repository into this subdirectory of the job's workspace. For example: <code>my/sources</code> (use forward slashes). If changing this entry, you probably want to clean the workspace first.
</div></div>

</li>
<li><code>browser</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'FishEye'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository, such as: http://www.example.org/browse/hg/
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GoogleCode'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <a href="http://code.google.com/p/PROJECTNAME/source/" rel="nofollow">this</a>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'HgWeb'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <a href="https://www.mercurial-scm.org/repo/hg/" rel="nofollow">this</a>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'Kallithea'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <a href="https://rhodecode.server/repo_name" rel="nofollow">this</a>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'KilnHG'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <a href="https://acme.kilnhg.com/Repo/Repositories/Group/PROJECTNAME" rel="nofollow">this</a>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'RhodeCode'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <a href="https://rhodecode.server/repo_name" rel="nofollow">this</a>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'RhodeCodeLegacy'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <a href="https://rhodecode.server/repo_name" rel="nofollow">this</a>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ScmManager'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL serving this repository (such as <code>http://YOURSCMMANAGER/scm/repo/NAMESPACE/NAME/</code>).
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>clean : boolean</code>
<div><div>
 When this option is checked, each build will wipe any local modifications or untracked files in the repository checkout. This is often a convenient way to ensure that a build is not using any artifacts from earlier builds.
</div></div>

</li>
<li><code>branchPattern : String</code>
</li>
</ul></div></li>
<li><code>$class: 'GeneXusServerSCM'</code><div>
<div><div>
 Checks out (or updates) a Knowledge Base from a GeneXus&nbsp;Server.
</div></div>
<ul><li><code>gxInstallationId : String</code>
<div><div>
 <p>GeneXus installation to use when creating (or updating) a local copy of a Knowledge&nbsp;Base from a GeneXus&nbsp;Server.</p>
 <p>Select "(Custom)" if you want to specify a custom GeneXus path for this project (see Advanced Options).</p>
 <p>The options that appear here are those you may configure in Jenkins "Global Tool Configuration" for GeneXus.</p>
</div></div>

</li>
<li><code>gxCustomPath : String</code>
<div><div>
 <p>Custom path to a GeneXus installation to use when creating (or updating) a local copy of Knowledge&nbsp;Base from a GeneXus&nbsp;Server. This custom path is used when the "Custom" option is selected for the GeneXus&nbsp;Installation</p>
</div></div>

</li>
<li><code>msbuildCustomPath : String</code>
<div><div>
 <p>Custom path to the MSBuild installation to use when creating (or updating) a local copy of Knowledge&nbsp;Base from a GeneXus&nbsp;Server.</p>
</div></div>

</li>
<li><code>serverURL : String</code>
<div><div>
 URL of the GeneXus&nbsp;Server from which to obtain (or update) a local copy of a Knowledge&nbsp;Base (eg:&nbsp;"https://sandbox.genexusserver.com/v16").
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 <p>Credentials to use when authenticating to the GeneXus&nbsp;Server.</p>
 <p>Select the credentials you want to use or click "Add" to enter a new user/password pair.</p>
</div></div>

</li>
<li><code>kbName : String</code>
<div><div>
 Name of the Knowledge&nbsp;Base in GeneXus&nbsp;Server from which to obtain (or update) a local copy.
</div></div>

</li>
<li><code>kbVersion : String</code>
<div><div>
 <p>Name of the Version that will be selected when creating a local copy of the Knowledge Base.</p>
 <p>If you leave it blank the 'Trunk' version will be selected by default.</p>
</div></div>

</li>
<li><code>localKbPath : String</code>
<div><div>
 <p>Path to the local Knowledge Base to use as working copy.</p>
 <p>If you leave it blank the default <code>${WORKSPACE}\KBname</code> will apply.</p>
</div></div>

</li>
<li><code>localKbVersion : String</code>
<div><div>
 <p>Name of the Version in the local Knowledge Base that is linked to the Version in the server.</p>
 <p>If you leave it blank the 'Trunk' version will be selected by default.</p>
</div></div>

</li>
<li><code>kbDbServerInstance : String</code>
<div><div>
 SQL Server used by GeneXus for the local Knowledge Base.
</div></div>

</li>
<li><code>kbDbCredentialsId : String</code>
<div><div>
 <p>Credentials to use when to connecting to SQL&nbsp;Server.</p>
 <p>Select "none" for Windows Authentication.</p>
</div></div>

</li>
<li><code>kbDbName : String</code>
<div><div>
 <p>Name of the SQL Server database used for the local Knowledge&nbsp;Base.</p>
 <p>Leave it blank to use the default database name.</p>
</div></div>

</li>
<li><code>kbDbInSameFolder : boolean</code>
<div><div>
 <p>Create the database files in the same folder as the Knowledge&nbsp;Base when checking out. Default is '<code>true</code>'.</p>
 <p>If <code>kbDbInSameFolder</code> is true or not set, then the database files will be created in the same folder as the Knowledge&nbsp;Base. If <code>kbDbInSameFolder</code> is false, then the database files will be created in the default folder configured for the SQL Server at <code>kbDbServerInstance (optional)</code>.</p>
</div></div>

</li>
</ul></div></li>
<li><span><a href="/doc/pipeline/steps/params/scmgit"><code>scmGit</code></a></span></li>
<li><code>$class: 'HarvestSCM'</code><div>
<ul><li><code>broker : String</code>
</li>
<li><code>passwordFile : String</code>
</li>
<li><code>userId : String</code>
</li>
<li><code>password : String</code>
</li>
<li><code>projectName : String</code>
</li>
<li><code>state : String</code>
</li>
<li><code>viewPath : String</code>
</li>
<li><code>clientPath : String</code>
</li>
<li><code>processName : String</code>
</li>
<li><code>recursiveSearch : String</code>
</li>
<li><code>useSynchronize : boolean</code>
</li>
<li><code>extraOptions : String</code>
</li>
</ul></div></li>
<li><code>$class: 'IntegritySCM'</code><div>
<div><div>
 Checks out source code from "Windchill RV&amp;S for Configuration Management" repositories
</div></div>
<ul><li><code>serverConfig : String</code>
</li>
<li><code>configPath : String</code>
</li>
<li><code>configurationName : String</code>
</li>
<li><code>CPBasedMode : boolean</code> (optional)
</li>
<li><code>alternateWorkspace : String</code> (optional)
</li>
<li><code>browser</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'IntegrityWebUI'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the URL of the PTC Windchill RV&amp;S Configuration Management server.
 <br>
  For example: http://hostname:7001
 <br>
  This value is optional and is used as an override to the URL detected in the Windchill RV&amp;S Change Log.
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>checkoutThreadPoolSize : int</code> (optional)
</li>
<li><code>checkoutThreadTimeout : int</code> (optional)
</li>
<li><code>checkpointBeforeBuild : boolean</code> (optional)
</li>
<li><code>checkpointLabel : String</code> (optional)
</li>
<li><code>cleanCopy : boolean</code> (optional)
</li>
<li><code>deleteNonMembers : boolean</code> (optional)
</li>
<li><code>excludeList : String</code> (optional)
</li>
<li><code>fetchChangedWorkspaceFiles : boolean</code> (optional)
</li>
<li><code>includeList : String</code> (optional)
</li>
<li><code>lineTerminator : String</code> (optional)
</li>
<li><code>localClient : boolean</code> (optional)
</li>
<li><code>password : String</code> (optional)
</li>
<li><code>restoreTimestamp : boolean</code> (optional)
</li>
<li><code>sandboxScope : String</code> (optional)
</li>
<li><code>skipAuthorInfo : boolean</code> (optional)
</li>
<li><code>userName : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'IspwConfiguration'</code><div>
<ul><li><code>connectionId : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>serverConfig : String</code>
</li>
<li><code>serverStream : String</code>
</li>
<li><code>serverApplication : String</code>
</li>
<li><code>serverSubAppl : String</code>
</li>
<li><code>serverLevel : String</code>
</li>
<li><code>levelOption : String</code>
</li>
<li><code>componentType : String</code>
</li>
<li><code>folderName : String</code>
</li>
<li><code>ispwDownloadAll : boolean</code>
</li>
<li><code>targetFolder : String</code>
</li>
<li><code>ispwDownloadIncl : boolean</code>
</li>
<li><code>ispwDownloadWithCompileOnly : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'IspwContainerConfiguration'</code><div>
<ul><li><code>connectionId : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>serverConfig : String</code>
</li>
<li><code>containerName : String</code>
</li>
<li><code>containerType : String</code>
</li>
<li><code>serverLevel : String</code>
</li>
<li><code>componentType : String</code>
</li>
<li><code>ispwDownloadAll : boolean</code>
</li>
<li><code>targetFolder : String</code>
</li>
<li><code>ispwDownloadIncl : boolean</code>
</li>
</ul></div></li>
<li><span><a href="/doc/pipeline/steps/params/mercurialscm"><code>$class: 'MercurialSCM'</code></a></span></li>
<li><code>$class: 'MergebotScm'</code><div>
<ul><li><code>cleanup</code>
<ul><li><b>Values:</b> <code>MINIMAL</code>, <code>STANDARD</code>, <code>FULL</code>, <code>DELETE</code></li></ul></li>
<li><code>workingMode</code>
<ul><li><b>Values:</b> <code>NONE</code>, <code>UP</code>, <code>LDAP</code></li></ul></li>
<li><code>credentialsId : String</code>
</li>
<li><code>specAttributeName : String</code>
</li>
</ul></div></li>
<li><span><a href="/doc/pipeline/steps/params/multiscm"><code>$class: 'MultiSCM'</code></a></span></li>
<li><code>none</code><div>
<ul></ul></div></li>
<li><code>$class: 'OpenShiftImageStreams'</code><div>
<ul><li><code>imageStreamName : String</code>
<div><div>
 The name of the ImageStream is what shows up in the NAME column if you dump all the ImageStream's with the `oc get is` command invocation.
</div></div>

</li>
<li><code>tag : String</code>
<div><div>
 The specific image tag within the ImageStream to monitor.
</div></div>

</li>
<li><code>apiURL : String</code>
</li>
<li><code>namespace : String</code>
</li>
<li><code>authToken : String</code>
</li>
<li><code>verbose : String</code>
</li>
</ul></div></li>
<li><code>$class: 'PdsConfiguration'</code><div>
<ul><li><code>connectionId : String</code>
</li>
<li><code>filterPattern : String</code>
</li>
<li><code>fileExtension : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>targetFolder : String</code>
</li>
</ul></div></li>
<li><code>perforce</code><div>
<ul><li><code>credential : String</code>
<div><div>
 <b>Perforce Credentials</b>
 <p>Select the appropriate credential for the Perforce connection. Perforce Credentials are defined in the Jenkins Credentials plugin <a rel="nofollow">here</a>.</p>
 <p>There are two types:</p>
 <ul>
  <li>'Perforce Password Credential' for standard username/password authentication</li>
  <li>'Perforce Ticket Credential' for ticket based authentication.</li>
 </ul>
</div></div>

</li>
<li><code>workspace</code>
<div><div>
 <b>Workspace Behaviour</b>
 <p>Select the appropriate Perforce workspace behaviour from the list. Not all modes will suit all Jenkins Job build types.</p>
 <p>There are five types:</p>
 <ul>
  <dt>
   Manual
  </dt>
  <dd>
   Manually define the Workspace view and sync options. Existing workspace will by updated or a new workspace created.
  </dd>
  <dt>
   Spec File
  </dt>
  <dd>
   Use a pre-defined Workspace Spec file versioned in Perforce.
  </dd>
  <dt>
   Static
  </dt>
  <dd>
   Use a pre-defined Workspace; must already exist and have a valid view.
  </dd>
  <dt>
   Streams
  </dt>
  <dd>
   Auto create/update a Streams workspace with a view determined by the chosen stream.
  </dd>
  <dt>
   Template
  </dt>
  <dd>
   Auto create/update a normal workspace with a view determined by the template workspace.
  </dd>
 </ul>
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>manualSpec</code><div>
<ul><li><code>charset : String</code>
<div><div>
 <b>P4CHARSET</b>
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p>
</div></div>

</li>
<li><code>pinHost : boolean</code>
</li>
<li><code>name : String</code>
<div><div>
 <b>Workspace name</b>
 <p>Specify the name of the Perforce workspace to be used as the Jenkins build workspace. If the workspace does not yet exist, the configuration will be saved in Jenkins; the workspace is created only when it is to be used. If the workspace exists and you are connected to a Perforce server the auto-text fill should list suitable workspaces; updates are only applied when the workspace is used.</p>
</div></div>

</li>
<li><code>spec</code>
<ul><b>Nested Object</b>
<li><code>allwrite : boolean</code>
</li>
<li><code>clobber : boolean</code>
</li>
<li><code>compress : boolean</code>
</li>
<li><code>locked : boolean</code>
</li>
<li><code>modtime : boolean</code>
</li>
<li><code>rmdir : boolean</code>
</li>
<li><code>streamName : String</code>
</li>
<li><code>line : String</code>
<div><div>
 <b>Line Endings</b>
 <p>Set line-ending character(s) for client text files.</p>
 <ul>
  <li><b>UNIX</b>
   <p>linefeed: UNIX style.</p></li>
  <li><b>MAC</b>
   <p>carriage return: Macintosh style. (obsolete)</p></li>
  <li><b>WIN</b>
   <p>carriage return-linefeed: Windows style.</p></li>
  <li><b>SHARE</b>
   <p>hybrid: writes UNIX style but reads UNIX, Mac or Windows style.</p></li>
 </ul>
</div></div>

</li>
<li><code>view : String</code>
<div><div>
 <b>View</b>
 <p>Lines to map depot files into the client workspace.</p>
 <p>The variable ${P4_CLIENT} will expand to the client name, for example, a simple mapping:</p>
 <p>//depot/... //${P4_CLIENT}/...</p>
 <p>Maps files in the depot to files in your client workspace. Defines the files that you want in your client workspace and specifies where you want them to reside. The default view maps all depot files onto the client. See 'p4 help views' for view syntax. A new view takes effect on the next 'p4 sync'.</p>
 <p>To support migration from the old Perforce plugin, a View Mapping can be inserted from a file in Perforce. Add the depot path to the "View Mappings" field Prefix "@" (this only applies to the "Manual" Workspace behaviour).</p>
</div></div>

</li>
<li><code>changeView : String</code>
</li>
<li><code>type : String</code>
<div><div>
 <b>Type</b>
 <p>Type of client: writeable/readonly/partitioned/graph</p>
 <p>By default all clients are 'writeable', certain clients are short lived and perform long sync and build cycles. Over time these build clients can fragment the 'db.have' table which is used to track what files a client has synced. Setting a type of 'readonly' gives the client its own personal 'db.have' database table. A 'readonly' client cannot 'edit' or 'submit' files, however for build automation this is not usually a requirement and the performance tradeoff is worth considering if your build automation is causing issues with the 'db.have' table. This option requires that an administrator has first configured the 'client.readonly.dir' setting. If it is necessary to submit changes as part of your build, you may specify a 'partitioned' client: like a 'reaonly' client, this type also has a separate 'db.have' table under the 'client.readonly.dir' directory, but allows journalled 'edit' and 'submit' of files.</p>
</div></div>

</li>
<li><code>serverID : String</code>
</li>
<li><code>backup : boolean</code>
<div><div>
 <b>Backup</b>
 <p>Client's participation in backup enable/disable. If not specified backup of a writable client defaults to enabled.</p>
</div></div>

</li>
<li><code>streamAtChange : String</code> (optional)
<div><div>
 <b>Stream at change</b>
 <p>When specified, the client view is generated from the stream specification version at or before the change number.</p>
</div></div>

</li>
</ul></li>
<li><code>cleanup : boolean</code>
</li>
<li><code>syncID : String</code> (optional)
</li>
</ul></div></li>
<li><code>specFileSpec</code><div>
<ul><li><code>charset : String</code>
<div><div>
 <b>P4CHARSET</b>
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p>
</div></div>

</li>
<li><code>pinHost : boolean</code>
</li>
<li><code>name : String</code>
<div><div>
 <b>An existing workspace</b>
 <p>Specify the name of the Perforce workspace to be used as the Jenkins build workspace. If the workspace does not yet exist, the configuration will be saved in Jenkins; the workspace is created only when it is to be used. If the workspace exists and you are connected to a Perforce server the auto-text fill should list suitable workspaces; updates are only applied when the workspace is used.</p>
</div></div>

</li>
<li><code>specPath : String</code>
</li>
<li><code>syncID : String</code> (optional)
</li>
</ul></div></li>
<li><code>staticSpec</code><div>
<ul><li><code>charset : String</code>
<div><div>
 <b>P4CHARSET</b>
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p>
</div></div>

</li>
<li><code>pinHost : boolean</code>
</li>
<li><code>name : String</code>
<div><div>
 <b>An existing workspace</b>
 <p>Specify the name of an existing workspace in Perforce to be used as the Jenkins build workspace. If connected to a Perforce server the auto-text fill should list suitable workspaces</p>
</div></div>

</li>
<li><code>syncID : String</code> (optional)
</li>
</ul></div></li>
<li><code>streamSpec</code><div>
<ul><li><code>charset : String</code>
<div><div>
 <b>P4CHARSET</b>
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p>
</div></div>

</li>
<li><code>pinHost : boolean</code>
</li>
<li><code>streamName : String</code>
<div><div>
 <b>Stream codeline</b>
 <p>Specify the full Perforce depot path for the given stream. If connected to a Perforce server the auto-text fill should list possible streams.</p><i>For example: //stream-depot/main-stream</i>
</div></div>

</li>
<li><code>format : String</code>
<div><div>
 <b>Workspace name formatter</b>
 <p>Jenklin slave nodes must each use a unique Perforce workspace. The format string configures the workspace name by substituting the specified variables: (at least one variable must be used)</p>
 <p>Variables can be taken from the Jenkins <a rel="nofollow">Environment</a> or Parameterized builds</p>
</div></div>

</li>
<li><code>streamAtChange : String</code> (optional)
<div><div>
 <b>Stream at change</b>
 <p>When specified, the client view is generated from the stream specification version at or before the change number.</p>
</div></div>

</li>
<li><code>syncID : String</code> (optional)
</li>
</ul></div></li>
<li><code>templateSpec</code><div>
<ul><li><code>charset : String</code>
<div><div>
 <b>P4CHARSET</b>
 <p>The character set used by Jenkins when syncing files from the Perforce server. This should be set to 'none' unless connected to a Unicode enabled Perforce server.</p>
</div></div>

</li>
<li><code>pinHost : boolean</code>
</li>
<li><code>templateName : String</code>
<div><div>
 <b>Templace workspace</b>
 <p>Specify the name of an existing workspace in Perforce used to create or update a Jenkins build workspace. If connected to a Perforce server the auto-text fill should list suitable workspaces</p>
</div></div>

</li>
<li><code>format : String</code>
<div><div>
 <b>Workspace name formatter</b>
 <p>Jenklin slave nodes must each use a unique Perforce workspace. The format string configures the workspace name by substituting the specified variables: (at least one variable must be used)</p>
 <p>Variables can be taken from the Jenkins <a rel="nofollow">Environment</a> or Parameterized builds</p>
</div></div>

</li>
<li><code>syncID : String</code> (optional)
</li>
</ul></div></li>
</ul></li>
<li><code>filter</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>latest</code><div>
<ul><li><code>latestChange : boolean</code>
</li>
</ul></div></li>
<li><code>latestWithPin</code><div>
<ul><li><code>latestWithPin : boolean</code>
<div><div>
 <b>Polling latest change with pin</b>
 <p>When enabled, in case of a pinned checkout, polling ignores the pin or the label specified in the checkout step and polls till the latest change.</p>
</div></div>

</li>
</ul></div></li>
<li><code>pathFilter</code><div>
<ul><li><code>path : String</code>
<div><div>
 <b>Depot path filter</b>
 <p>Changes can be filtered to not trigger a build; if all the files within a change match the specified path, the build is filtered.</p>
 <p>For example, with a Filter of " <code>//depot/main/tests</code> ":</p>
 <p><strong>Case A</strong> (change will be filtered):</p>
 <p>Files:</p>
 <ul>
  <li><code>//depot/main/tests/index.xml</code></li>
  <li><code>//depot/main/tests/001/test.xml</code></li>
  <li><code>//depot/main/tests/002/test.xml</code></li>
 </ul>
 <p><strong>Case B</strong> (change will not be filtered, as build.xml is outside of the filter):</p>
 <p>Files:</p>
 <ul>
  <li><code>//depot/main/src/build.xml</code></li>
  <li><code>//depot/main/tests/004/test.xml</code></li>
  <li><code>//depot/main/tests/005/test.xml</code></li>
 </ul>
 <p>This is not Perforce syntax. Use of ... and * patterns are not supported. Only paths to directories are supported.</p>
</div></div>

</li>
</ul></div></li>
<li><code>viewPattern</code><div>
<ul><li><code>patternText : String</code>
<div><div>
 <b>Java Pattern filter</b>
 <p>Changes can be filtered to not trigger a build; if none of the files within a change match a Java pattern (regular expression) listed, the build is filtered.</p>
 <p>For example, with the following regular expressions: <br><code>//depot/main/tests.*</code> <br><code>//depot/main/src/.*\.cpp</code> <br><code>//depot/main/build/.*(?:\.rb|\.py|\.bat|Jenkinsfile)</code> <br><code>//depot/main/lib/(?!Lib1|Lib2).*</code> <br></p>
 <p><strong>Case A</strong> (change will not be filtered, as these files match our first pattern on "tests"):</p>
 <p>Files:</p>
 <ul>
  <li><code>//depot/main/tests/CONTRIUBTING.md</code></li>
  <li><code>//depot/main/tests/001/index.xml</code></li>
 </ul>
 <p><strong>Case B</strong> (Be careful with incomplete file paths! Change will NOT be filtered, <br>
  as this file matches a pattern which was likely intended as describing a <strong>"tests/"</strong> directory.)</p>
 <p>Files:</p>
 <ul>
  <li><code>//depot/main/tests.doc</code></li>
 </ul>
 <p><strong>Case C</strong> (change will NOT be filtered, as all files match our fourth pattern looking for script files in 'build/'):</p>
 <p>Files:</p>
 <ul>
  <li><code>//depot/main/build/rbs/deploy_server.rb</code></li>
  <li><code>//depot/main/build/deploy/deploy.bat</code></li>
  <li><code>//depot/main/build/Jenkinsfile</code></li>
 </ul>
 <p><strong>Case D</strong> (change will be filtered, as no file matches our second pattern for ".cpp" files under "main/src"):</p>
 <p>Files:</p>
 <ul>
  <li><code>//depot/main/src/howto.doc</code></li>
  <li><code>//depot/main/src/oldmain.c</code></li>
  <li><code>//depot/main/src/art/splash.bmp</code></li>
  <li><code>//depot/main/src/bt/funnelcake.php</code></li>
 </ul>
 <p><strong>Case E</strong> (change will be filtered. Lib1 is included in a negative lookahead, and thus is excluded.)</p>
 <p>Files:</p>
 <ul>
  <li><code>//depot/main/lib/Lib1/build.xml</code></li>
 </ul>
</div></div>

</li>
<li><code>caseSensitive : boolean</code>
</li>
</ul></div></li>
<li><code>incremental</code><div>
<ul><li><code>perChange : boolean</code>
<div><div>
 <b>Polling per change</b>
 <p>When enabled, only the one, oldest changelist returned by polling is built.</p>
 <p>If <code>P4_INCREMENTAL</code> environment variable (or build parameter) is set to "false", polling per change is ignored and all changelists are built.</p>
</div></div>

</li>
</ul></div></li>
<li><code>userFilter</code><div>
<ul><li><code>user : String</code>
<div><div>
 <b>User name filter</b>
 <p>Changes can be filtered to not trigger a build; if the owner of a change matches the specified name, the build is filtered.</p>
</div></div>

</li>
</ul></div></li>
<li><code>viewFilter</code><div>
<ul><li><code>viewMask : String</code>
<div><div>
 <b>View Mask filter</b>
 <p>Changes can be filtered to not trigger a build; if none of the files within a change are contained in the view mask, the build is filtered.</p>
 <p>For example, with a View Mask Filter of: <br><code>//depot/main/tests</code> <br><code>-//depot/main/tests/001</code> <br></p>
 <p><strong>Case A</strong> (change will not be filtered, as index.xml is in the view mask):</p>
 <p>Files:</p>
 <ul>
  <li><code>//depot/main/tests/index.xml</code></li>
  <li><code>//depot/main/tests/001/test.xml</code></li>
 </ul>
 <p><strong>Case B</strong> (change will not be filtered, as index.xml is in the view mask):</p>
 <p>Files:</p>
 <ul>
  <li><code>//depot/main/test/index.xml</code></li>
  <li><code>//depot/main/src/build.xml</code></li>
 </ul>
 <p><strong>Case C</strong> (change will be filtered, as no file is in the view mask):</p>
 <p>Files:</p>
 <ul>
  <li><code>//depot/main/src/build.xml</code></li>
 </ul>
 <p><strong>Case D</strong> (change will be filtered, as no file is in the view mask):</p>
 <p>Files:</p>
 <ul>
  <li><code>//depot/main/src/build.xml</code></li>
  <li><code>//depot/main/tests/001/test.xml</code></li>
 </ul>
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>populate</code>
<div><div>
 <b>Populate Options</b>
 <p>Perforce will populate the workspace with the file revisions needed for the build. The different options effect the way the workspace is cleaned and the file revisions are updated.</p>
 <p>There are three options:</p>
 <ul>
  <dt>
   Automatic Cleanup and Sync
  </dt>
  <dd>
   Efficient cleaning and syncing of file revisions. Extra (non versioned files) are removed, missing and modified files re-added. 
   <br>
   Best for clean builds.
  </dd>
  <dt>
   Flush Workspace
  </dt>
  <dd>
   No files Sync or cleanup attempted, but the Workspace's have list is updated. 
   <br>
   Effective command 'p4 sync -k'.
  </dd>
  <dt>
   Force Clean and Sync
  </dt>
  <dd>
   Will remove all files from under the workspace root, then force sync the required files. Inefficient and NOT RECOMENDED.
  </dd>
  <dt>
   Graph Force Clean and Sync/dt&gt;
  </dt>
  <dd>
   For Graph and Hybrid only, will remove all files from under the workspace root, then force sync the required files.
  </dd>
  <dt>
   Preview Check Only
  </dt>
  <dd>
   No files Sync or cleanup attempted; the Workspace's have list is not updated. 
   <br>
   Effective command 'p4 sync -n'.
  </dd>
  <dt>
   Sync Only
  </dt>
  <dd>
   No cleanup attempted; the sync will update all files (as CLOBBER is set) to the required set of revisions. 
   <br>
   Best for incremental builds.
  </dd>
 </ul>
</div></div>

<ul><b>Nested Choice of Objects</b>
<li><code>autoClean</code><div>
<ul><li><code>replace : boolean</code>
<div><div>
 <b>REPLACE missing/modified files</b>
 <p>Perforce will check out and overwrite any depot files which are either missing from workspace, or have been modified locally.</p>
</div></div>

</li>
<li><code>delete : boolean</code>
<div><div>
 <b>DELETE generated files</b>
 <p>Perforce will delete any local files that are not in the depot.</p>
</div></div>

</li>
<li><code>tidy : boolean</code>
</li>
<li><code>modtime : boolean</code>
</li>
<li><code>quiet : boolean</code>
<div><div>
 <b>Suppressing info messages</b>
 <p>Enables the -q flag for all applicable Perforce operations. Summary details will still be displayed.</p>
</div></div>

</li>
<li><code>pin : String</code>
<div><div>
 <b>Pinning a build at Perforce Label</b>
 <p>When a build is triggered by Polling, Build Now or an external Action, the workspace will sync only to the specified label. Any other specified change or label will be ignored.</p>
 <p>Supports variable expansion e.g. ${VAR}. If 'now' is used, or a variable that expands to 'now', then the latest change is used (within the scope of the workspace view).</p>
</div></div>

</li>
<li><code>parallel</code>
<ul><b>Nested Object</b>
<li><code>enable : boolean</code>
</li>
<li><code>path : String</code>
</li>
<li><code>threads : String</code>
</li>
<li><code>minfiles : String</code>
</li>
<li><code>minbytes : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>previewOnly</code><div>
<ul><li><code>quiet : boolean</code>
<div><div>
 <b>Suppressing info messages</b>
 <p>Enables the -q flag for all applicable Perforce operations. Summary details will still be displayed.</p>
</div></div>

</li>
<li><code>pin : String</code>
</li>
</ul></div></li>
<li><code>flushOnly</code><div>
<ul><li><code>quiet : boolean</code>
</li>
<li><code>pin : String</code>
<div><div>
 <b>Pinning a build at Perforce Label</b>
 <p>When a build is triggered by Polling, Build Now or an external Action, the workspace will flush only to the specified label or changelist number. Any other specified change or label will be ignored.</p>
 <p>Supports variable expansion e.g. ${VAR}. If 'now' is used, or a variable that expands to 'now', then the latest change is used (within the scope of the workspace view).</p>
</div></div>

</li>
</ul></div></li>
<li><code>forceClean</code><div>
<ul><li><code>have : boolean</code>
</li>
<li><code>quiet : boolean</code>
<div><div>
 <b>Suppressing info messages</b>
 <p>Enables the -q flag for all applicable Perforce operations. Summary details will still be displayed.</p>
</div></div>

</li>
<li><code>pin : String</code>
<div><div>
 <b>Pinning a build at Perforce Label</b>
 <p>When a build is triggered by Polling, Build Now or an external Action, the workspace will sync only to the specified label. Any other specified change or label will be ignored.</p>
 <p>Supports variable expansion e.g. ${VAR}. If 'now' is used, or a variable that expands to 'now', then the latest change is used (within the scope of the workspace view).</p>
</div></div>

</li>
<li><code>parallel</code>
<ul><b>Nested Object</b>
<li><code>enable : boolean</code>
</li>
<li><code>path : String</code>
</li>
<li><code>threads : String</code>
</li>
<li><code>minfiles : String</code>
</li>
<li><code>minbytes : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>graphClean</code><div>
<ul><li><code>quiet : boolean</code>
<div><div>
 <b>Suppressing info messages</b>
 <p>Enables the -q flag for all applicable Perforce operations. Summary details will still be displayed.</p>
</div></div>

</li>
<li><code>pin : String</code>
<div><div>
 <b>Pinning a build at Perforce Label</b>
 <p>When a build is triggered by Polling, Build Now or an external Action, the workspace will sync only to the specified label. Any other specified change or label will be ignored.</p>
 <p>Supports variable expansion e.g. ${VAR}. If 'now' is used, or a variable that expands to 'now', then the latest change is used (within the scope of the workspace view).</p>
</div></div>

</li>
<li><code>parallel</code>
<ul><b>Nested Object</b>
<li><code>enable : boolean</code>
</li>
<li><code>path : String</code>
</li>
<li><code>threads : String</code>
</li>
<li><code>minfiles : String</code>
</li>
<li><code>minbytes : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>syncOnly</code><div>
<ul><li><code>revert : boolean</code>
</li>
<li><code>have : boolean</code>
</li>
<li><code>force : boolean</code>
</li>
<li><code>modtime : boolean</code>
</li>
<li><code>quiet : boolean</code>
<div><div>
 <b>Suppressing info messages</b>
 <p>Enables the -q flag for all applicable Perforce operations. Summary details will still be displayed.</p>
</div></div>

</li>
<li><code>pin : String</code>
<div><div>
 <b>Pinning a build at Perforce Label</b>
 <p>When a build is triggered by Polling, Build Now or an external Action, the workspace will sync only to the specified label. Any other specified change or label will be ignored.</p>
 <p>Supports variable expansion e.g. ${VAR}. If 'now' is used, or a variable that expands to 'now', then the latest change is used (within the scope of the workspace view).</p>
</div></div>

</li>
<li><code>parallel</code>
<ul><b>Nested Object</b>
<li><code>enable : boolean</code>
</li>
<li><code>path : String</code>
</li>
<li><code>threads : String</code>
</li>
<li><code>minfiles : String</code>
</li>
<li><code>minbytes : String</code>
</li>
</ul></li>
</ul></div></li>
</ul></li>
<li><code>browser</code>
<ul><b>Nested Choice of Objects</b>
<li><code>fishEye</code><div>
<ul><li><code>url : String</code>
</li>
<li><code>rootModule : String</code>
</li>
</ul></div></li>
<li><code>openGrok</code><div>
<ul><li><code>url : String</code>
</li>
<li><code>depotPath : String</code>
</li>
<li><code>projectName : String</code>
</li>
</ul></div></li>
<li><code>p4Web</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>swarm</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'PlasticSCM'</code><div>
<ul><li><code>selector : String</code>
</li>
<li><code>cleanup</code>
<ul><li><b>Values:</b> <code>MINIMAL</code>, <code>STANDARD</code>, <code>FULL</code>, <code>DELETE</code></li></ul></li>
<li><code>workingMode</code>
<ul><li><b>Values:</b> <code>NONE</code>, <code>UP</code>, <code>LDAP</code></li></ul></li>
<li><code>credentialsId : String</code>
</li>
<li><code>useMultipleWorkspaces : boolean</code>
</li>
<li><code>additionalWorkspaces</code>
<ul><b>Array / List of Nested Object</b>
<li><code>selector : String</code>
</li>
<li><code>cleanup</code>
<ul><li><b>Values:</b> <code>MINIMAL</code>, <code>STANDARD</code>, <code>FULL</code>, <code>DELETE</code></li></ul></li>
<li><code>directory : String</code>
</li>
</ul></li>
<li><code>pollOnController : boolean</code>
</li>
<li><code>directory : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ProxySCM'</code><div>
<ul><li><code>projectName : String</code>
</li>
</ul></div></li>
<li><code>$class: 'PvcsScm'</code><div>
<ul><li><code>projectRoot : String</code>
</li>
<li><code>archiveRoot : String</code>
</li>
<li><code>changeLogPrefixFudge : String</code>
</li>
<li><code>moduleDir : String</code>
</li>
<li><code>loginId : String</code>
</li>
<li><code>pvcsWorkspace : String</code>
</li>
<li><code>promotionGroup : String</code>
</li>
<li><code>versionLabel : String</code>
</li>
<li><code>cleanCopy : boolean</code>
</li>
</ul></div></li>
<li><span><a href="/doc/pipeline/steps/params/rtcscm"><code>$class: 'RTCScm'</code></a></span></li>
<li><code>$class: 'SCLMSCM'</code><div>
<ul><li><code>server : String</code>
</li>
<li><code>port : int</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>JESINTERFACELEVEL1 : boolean</code>
</li>
<li><code>FTPActiveMode : boolean</code>
</li>
<li><code>project : String</code>
</li>
<li><code>alternate : String</code>
</li>
<li><code>group : String</code>
</li>
<li><code>types : String</code>
</li>
<li><code>custJobStep : boolean</code>
</li>
<li><code>JobStep : String</code>
</li>
<li><code>custJobHeader : boolean</code>
</li>
<li><code>JobHeader : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ShellScriptSCM'</code><div>
<ul><li><code>checkoutShell : String</code>
</li>
<li><code>pollingShell : String</code>
</li>
<li><code>useCheckoutForPolling : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'SimpleClearCaseSCM'</code><div>
<ul><li><code>loadRules : String</code>
<div><div>
 Specify the paths to the source code inside of ClearCase VOBS. one Path for each line. For instance: 
 <p>/vobs/structure/package/product/subproduct<br>
   /vobs/structure/package/product/anothersubproduct.</p>
</div></div>

</li>
<li><code>viewname : String</code>
<div><div>
 The viewname which has a configured config spec. This is external to the plugin as the way the config spec can be configured in many different ways. From updating the config spec dynamically with fixed intervals to having a constant one throughout a full project life time.
</div></div>

</li>
<li><code>branch : String</code>
<div><div>
 Specify which branch to follow. Not mandatory. If not set then all branches will be followed, i.e you will get notifications about changes in branches which your config specification isn't related to. Example value: main, dev etc.
</div></div>

</li>
<li><code>filter : boolean</code>
<div><div>
 Filters out mkbranch and rmbranch messages in lshistory. These changes isn't relevant if you are tracking source files in a specific branch.
</div></div>

</li>
</ul></div></li>
<li><code>SpaceGit</code><div>
<ul><li><code>customSpaceConnection</code>
<div><div>
 <p>Provide JetBrains Space connection, project and repository.</p>
 <p>This section is optional in case <b>Triggered by JetBrains Space</b> is enabled for a job or pipeline. The Build trigger settings will be used for checking out source code if the JetBrains Space connection parameters are not specified here explicitly.</p>
</div></div>

<ul><b>Nested Object</b>
<li><code>spaceConnection : String</code>
</li>
<li><code>projectKey : String</code>
</li>
<li><code>repository : String</code>
</li>
<li><code>branches</code>
<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
<div><div>
 <p>Specify the branches if you'd like to track a specific branch in a repository. If left blank, all branches will be examined for changes and built.</p>
 <p>The safest way is to use the <code>refs/heads/&lt;branchName&gt;</code> syntax. This way the expected branch is unambiguous.</p>
 <p>If your branch name has a <code>/</code> in it make sure to use the full reference above. When not presented with a full path the plugin will only use the part of the string right of the last slash. Meaning <code>foo/bar</code> will actually match <code>bar</code>.</p>
 <p>If you use a wildcard branch specifier, with a slash (e.g. <code>release/</code>), you'll need to specify the origin repository in the branch names to make sure changes are picked up. So e.g. <code>origin/release/</code></p>
 <p>Possible options:</p>
 <ul>
  <li><strong><code>&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch. If ambiguous the first result is taken, which is not necessarily the expected one. Better use <code>refs/heads/&lt;branchName&gt;</code>.<br>
    E.g. <code>master</code>, <code>feature1</code>, ...</li>
  <li><strong><code>refs/heads/&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch.<br>
    E.g. <code>refs/heads/master</code>, <code>refs/heads/feature1/master</code>, ...</li>
  <li><strong><code>&lt;remoteRepoName&gt;/&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch. If ambiguous the first result is taken, which is not necessarily the expected one.<br>
    Better use <code>refs/heads/&lt;branchName&gt;</code>.<br>
    E.g. <code>origin/master</code></li>
  <li><strong><code>remotes/&lt;remoteRepoName&gt;/&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch.<br>
    E.g. <code>remotes/origin/master</code></li>
  <li><strong><code>refs/remotes/&lt;remoteRepoName&gt;/&lt;branchName&gt;</code></strong><br>
    Tracks/checks out the specified branch.<br>
    E.g. <code>refs/remotes/origin/master</code></li>
  <li><strong><code>&lt;tagName&gt;</code></strong><br>
    This does not work since the tag will not be recognized as tag.<br>
    Use <code>refs/tags/&lt;tagName&gt;</code> instead.<br>
    E.g. <code>git-2.3.0</code></li>
  <li><strong><code>refs/tags/&lt;tagName&gt;</code></strong><br>
    Tracks/checks out the specified tag.<br>
    E.g. <code>refs/tags/git-2.3.0</code></li>
  <li><strong><code>&lt;commitId&gt;</code></strong><br>
    Checks out the specified commit.<br>
    E.g. <code>5062ac843f2b947733e6a3b105977056821bd352</code>, <code>5062ac84</code>, ...</li>
  <li><strong><code>${ENV_VARIABLE}</code></strong><br>
    It is also possible to use environment variables. In this case the variables are evaluated and the result is used as described above.<br>
    E.g. <code>${TREEISH}</code>, <code>refs/tags/${TAGNAME}</code>, ...</li>
  <li><strong><code>&lt;Wildcards&gt;</code></strong><br>
    The syntax is of the form: <code>REPOSITORYNAME/BRANCH</code>. In addition, <code>BRANCH</code> is recognized as a shorthand of <code>*/BRANCH</code>, '*' is recognized as a wildcard, and '**' is recognized as wildcard that includes the separator '/'. Therefore, <code>origin/branches*</code> would match <code>origin/branches-foo</code> but not <code>origin/branches/foo</code>, while <code>origin/branches**</code> would match both <code>origin/branches-foo</code> and <code>origin/branches/foo</code>.</li>
  <li><strong><code>:&lt;regular expression&gt;</code></strong><br>
    The syntax is of the form: <code>:regexp</code>. Regular expression syntax in branches to build will only build those branches whose names match the regular expression.<br>
    Examples:<br>
   <ul>
    <li><code>:^(?!(origin/prefix)).*</code>
     <ul>
      <li>matches: <code>origin</code> or <code>origin/master</code> or <code>origin/feature</code></li>
      <li>does not match: <code>origin/prefix</code> or <code>origin/prefix_123</code> or <code>origin/prefix-abc</code></li>
     </ul></li>
    <li><code>:origin/release-\d{8}</code>
     <ul>
      <li>matches: <code>origin/release-20150101</code></li>
      <li>does not match: <code>origin/release-2015010</code> or <code>origin/release-201501011</code> or <code>origin/release-20150101-something</code></li>
     </ul></li>
    <li><code>:^(?!origin/master$|origin/develop$).*</code>
     <ul>
      <li>matches: <code>origin/branch1</code> or <code>origin/branch-2</code> or <code>origin/master123</code> or <code>origin/develop-123</code></li>
      <li>does not match: <code>origin/master</code> or <code>origin/develop</code></li>
     </ul></li>
   </ul></li>
 </ul>
 <p></p>
</div></div>

</li>
</ul></li>
</ul></li>
<li><code>gitTool : String</code>
<div><p>Name of the git tool to be used for this job. Git tool names are defined in "Global Tool Configuration".</p></div>

</li>
<li><code>extensions</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>authorInChangelog</code><div>
<div><div>
 The default behavior is to use the Git commit's "Committer" value in Jenkins' build changesets. If this option is selected, the Git commit's "Author" value would be used instead.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'BuildChooserSetting'</code><div>
<div><div>
 When you are interested in using a job to build multiple heads (most typically multiple branches), you can choose how Jenkins choose what branches to build in what order. 
 <p>This extension point in Jenkins is used by many other plugins to control the job to build specific commits. When you activate those plugins, you may see them installing a custom strategy here.</p>
</div></div>
<ul><li><code>buildChooser</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'AlternativeBuildChooser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'AncestryBuildChooser'</code><div>
<ul><li><code>maximumAgeInDays : int</code>
</li>
<li><code>ancestorCommitSha1 : String</code>
</li>
</ul></div></li>
<li><code>$class: 'DefaultBuildChooser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'DeflakeGitBuildChooser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'GerritTriggerBuildChooser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'InverseBuildChooser'</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>buildSingleRevisionOnly</code><div>
<div><div>
 Disable scheduling for multiple candidate revisions.
 <br>
  If we have 3 branches:
 <br>
  ----A--.---.--- B
 <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\-----C
 <br>
  jenkins would try to build (B) and (C).
 <br>
  This behaviour disables this and only builds one of them.
 <br>
  It is helpful to reduce the load of the Jenkins infrastructure when the SCM system like Bitbucket or GitHub should decide what commits to build.
</div></div>
<ul></ul></div></li>
<li><code>changelogToBranch</code><div>
<div><div>
 This method calculates the changelog against the specified branch.
</div></div>
<ul><li><code>options</code>
<ul><b>Nested Object</b>
<li><code>compareRemote : String</code>
<div><div>
 Name of the repository, such as <code>origin</code>, that contains the branch you specify below.
</div></div>

</li>
<li><code>compareTarget : String</code>
<div><div>
 The name of the branch within the named repository to compare against.
</div></div>

</li>
</ul></li>
</ul></div></li>
<li><code>checkoutOption</code><div>
<ul><li><code>timeout : int</code>
<div><div>
 Specify a timeout (in minutes) for checkout.
 <br>
  This option overrides the default timeout of 10 minutes. 
 <br>
  You can change the global git timeout via the property org.jenkinsci.plugins.gitclient.Git.timeOut (see <a href="https://issues.jenkins.io/browse/JENKINS-11286" rel="nofollow">JENKINS-11286</a>). Note that property should be set on both controller and agent to have effect (see <a href="https://issues.jenkins.io/browse/JENKINS-22547" rel="nofollow">JENKINS-22547</a>).
</div></div>

</li>
</ul></div></li>
<li><code>cleanBeforeCheckout</code><div>
<div><div>
 Clean up the workspace before every checkout by deleting all untracked files and directories, including those which are specified in <code>.gitignore</code>. It also resets all <em>tracked</em> files to their versioned state. This ensures that the workspace is in the same state as if you cloned and checked out in a brand-new empty directory, and ensures that your build is not affected by the files generated by the previous build.
</div></div>
<ul><li><code>deleteUntrackedNestedRepositories : boolean</code> (optional)
<div><div>
 Deletes untracked submodules and any other subdirectories which contain <code>.git</code> directories.
</div></div>

</li>
</ul></div></li>
<li><code>cleanAfterCheckout</code><div>
<div><div>
 Clean up the workspace after every checkout by deleting all untracked files and directories, including those which are specified in <code>.gitignore</code>. It also resets all <em>tracked</em> files to their versioned state. This ensures that the workspace is in the same state as if you cloned and checked out in a brand-new empty directory, and ensures that your build is not affected by the files generated by the previous build.
</div></div>
<ul><li><code>deleteUntrackedNestedRepositories : boolean</code> (optional)
<div><div>
 Deletes untracked submodules and any other subdirectories which contain <code>.git</code> directories.
</div></div>

</li>
</ul></div></li>
<li><code>cloneOption</code><div>
<ul><li><code>shallow : boolean</code>
<div><div>
 Perform shallow clone, so that git will not download the history of the project, saving time and disk space when you just want to access the latest version of a repository.
</div></div>

</li>
<li><code>noTags : boolean</code>
<div><div>
 Deselect this to perform a clone without tags, saving time and disk space when you just want to access what is specified by the refspec.
</div></div>

</li>
<li><code>reference : String</code>
<div><div>
 Specify a folder containing a repository that will be used by Git as a reference during clone operations.
 <br>
  This option will be ignored if the folder is not available on the controller or agent where the clone is being executed.
</div></div>

</li>
<li><code>timeout : int</code>
<div><div>
 Specify a timeout (in minutes) for clone and fetch operations.
 <br>
  This option overrides the default timeout of 10 minutes. 
 <br>
  You can change the global git timeout via the property org.jenkinsci.plugins.gitclient.Git.timeOut (see <a href="https://issues.jenkins.io/browse/JENKINS-11286" rel="nofollow">JENKINS-11286</a>). Note that property should be set on both controller and agent to have effect (see <a href="https://issues.jenkins.io/browse/JENKINS-22547" rel="nofollow">JENKINS-22547</a>).
</div></div>

</li>
<li><code>depth : int</code> (optional)
<div><div>
 Set shallow clone depth, so that git will only download recent history of the project, saving time and disk space when you just want to access the latest commits of a repository.
</div></div>

</li>
<li><code>honorRefspec : boolean</code> (optional)
<div><div>
 Perform initial clone using the refspec defined for the repository. This can save time, data transfer and disk space when you only need to access the references specified by the refspec.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'CodeCommitURLHelper'</code><div>
<ul><li><code>credentialId : String</code>
<div><div>
 <p>OPTIONAL: Select the credentials to use.<br>
   If not specified, defaults to the <a href="http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html#using-the-default-credential-provider-chain" rel="nofollow"> DefaultAWSCredentialsProviderChain </a> behaviour - <b>*FROM THE JENKINS INSTANCE*</b></p>
 <p>In the latter case, usage of IAM Role Profiles seems not to work, thus relying on environment variables / system properties or the ~/.aws/credentials file, thus not recommended.</p>
</div></div>

</li>
<li><code>repositoryName : String</code>
</li>
</ul></div></li>
<li><code>$class: 'DisableRemotePoll'</code><div>
<div><div>
 Git plugin uses git ls-remote polling mechanism by default when configured with a single branch (no wildcards!). This compare the latest built commit SHA with the remote branch without cloning a local copy of the repo.
 <br>
 <br>
  If you don't want to / can't use this.
 <br>
 <br>
  If this option is selected, polling will require a workspace and might trigger unwanted builds (see <a href="https://issues.jenkins.io/browse/JENKINS-10131" rel="nofollow">JENKINS-10131</a>).
</div></div>
<ul></ul></div></li>
<li><code>$class: 'ExcludeFromChangeSet'</code><div>
<ul></ul></div></li>
<li><code>$class: 'ExcludeFromPoll'</code><div>
<ul></ul></div></li>
<li><code>lfs</code><div>
<div><div>
 Enable <a href="https://git-lfs.github.com/" rel="nofollow">git large file support</a> for the workspace by pulling large files after the checkout completes. Requires that the controller and each agent performing an LFS checkout have installed `git lfs`.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'GitSCMChecksExtension'</code><div>
<ul><li><code>verboseConsoleLog : boolean</code> (optional)
<div><div>
 If this option is checked, verbose log will be output to build console; the verbose log is useful for debugging the publisher creation.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'GitSCMStatusChecksExtension'</code><div>
<ul><li><code>name : String</code> (optional)
</li>
<li><code>skip : boolean</code> (optional)
</li>
<li><code>skipProgressUpdates : boolean</code> (optional)
</li>
<li><code>suppressLogs : boolean</code> (optional)
</li>
<li><code>unstableBuildNeutral : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'GitTagMessageExtension'</code><div>
<div><div>
 If the revision checked out has a git tag associated with it, the tag name will be exported during the build as <strong>GIT_TAG_NAME</strong>. 
 <br>
  If a message was specified when creating the tag, then that message will be exported during the build as the <strong>GIT_TAG_MESSAGE</strong> environment variable. 
 <br>
  If no tag message was specified, the commit message will be used. 
 <br>
  If you ticked the <strong>Use most recent tag</strong> option, and the revision checked out has no git tag associated with it, the parent commits will be searched for a git tag, and the rules stated above will apply to the first parent commit with a git tag. 
 <p></p> If the revision has more than one tag associated with it, only the most recent tag will be taken into account, <strong>unless</strong> the refspec contains "refs/tags/" — i.e. builds are only triggered when certain tag names or patterns are matched — in which case the exact tag name that triggered the build will be used, even if it's not the most recent tag for this commit. 
 <br>
  For this reason, if you're not using a tag-specific refspec but you <em>are</em> using the "Create a tag for every build" behaviour, you should make sure that the build-tagging behaviour is configured to run <em>after</em> this "export git tag message" behaviour. 
 <p></p> Tag and commit messages which span multiple lines are no problem, though only the first 10000 lines of a tag's message will be exported.
</div></div>
<ul><li><code>useMostRecentTag : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'IgnoreNotifyCommit'</code><div>
<div><div>
 If checked, this repository will be ignored when the notifyCommit-URL is accessed regardless of if the repository matches or not.
</div></div>
<ul></ul></div></li>
<li><code>localBranch</code><div>
<div><div>
 If given, checkout the revision to build as HEAD on this branch. 
 <p>If selected, and its value is an empty string or "**", then the branch name is computed from the remote branch without the origin. In that case, a remote branch origin/master will be checked out to a local branch named master, and a remote branch origin/develop/new-feature will be checked out to a local branch named develop/newfeature.</p>
 <p>Please note that this has not been tested with submodules.</p>
</div></div>
<ul><li><code>localBranch : String</code>
</li>
</ul></div></li>
<li><code>$class: 'MessageExclusion'</code><div>
<ul><li><code>excludedMessage : String</code>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will ignore any revisions committed with message matched to <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html" rel="nofollow">Pattern</a> when determining if a build needs to be triggered. This can be used to exclude commits done by the build itself from triggering another build, assuming the build server commits the change with a distinct message. 
 <p></p>Exclusion uses <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html" rel="nofollow">Pattern</a> <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Matcher.html#matches()" rel="nofollow">matching</a>
 <p></p>
 <pre>.*\[maven-release-plugin\].*</pre> The example above illustrates that if only revisions with "[maven-release-plugin]" message in first comment line have been committed to the SCM a build will not occur. 
 <p></p> You can create more complex patterns using embedded flag expressions. 
 <pre>(?s).*FOO.*</pre> This example will search FOO message in all comment lines.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'PathRestriction'</code><div>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will pay attention to included and/or excluded files and/or folders when determining if a build needs to be triggered. 
 <p></p> Using this behaviour will preclude the faster git ls-remote polling mechanism, forcing polling to require a workspace thus sometimes triggering unwanted builds, as if you had selected the <strong>Force polling using workspace</strong> extension as well.
</div></div>
<ul><li><code>includedRegions : String</code>
<div><div>
 Each inclusion uses <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html" rel="nofollow">java regular expression pattern matching</a>, and must be separated by a new line. An empty list implies that everything is included. 
 <p></p>
 <pre>    myapp/src/main/web/.*\.html
    myapp/src/main/web/.*\.jpeg
    myapp/src/main/web/.*\.gif
  </pre> The example above illustrates that a build will only occur, if html/jpeg/gif files have been committed to the SCM. Exclusions take precedence over inclusions, if there is an overlap between included and excluded regions.
</div></div>

</li>
<li><code>excludedRegions : String</code>
<div><div>
 Each exclusion uses <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html" rel="nofollow">java regular expression pattern matching</a>, and must be separated by a new line. 
 <p></p>
 <pre>    myapp/src/main/web/.*\.html
    myapp/src/main/web/.*\.jpeg
    myapp/src/main/web/.*\.gif
  </pre> The example above illustrates that if only html/jpeg/gif files have been committed to the SCM a build will not occur.
</div></div>

</li>
</ul></div></li>
<li><code>perBuildTag</code><div>
<div><div>
 Create a tag in the workspace for every build to unambiguously mark the commit that was built. You can combine this with Git publisher to push the tags to the remote repository.
</div></div>
<ul></ul></div></li>
<li><code>$class: 'PreBuildMerge'</code><div>
<div><div>
 These options allow you to perform a merge to a particular branch before building. For example, you could specify an integration branch to be built, and to merge to master. In this scenario, on every change of integration, Jenkins will perform a merge with the master branch, and try to perform a build if the merge is successful. It then may push the merge back to the remote repository if the Git Push post-build action is selected.
</div></div>
<ul><li><code>options</code>
<ul><b>Nested Object</b>
<li><code>mergeTarget : String</code>
<div><div>
 The name of the branch within the named repository to merge to, such as <code>master</code>.
</div></div>

</li>
<li><code>fastForwardMode</code> (optional)
<div><div>
 Merge fast-forward mode selection.
 <br>
  The default, --ff, gracefully falls back to a merge commit when required.
 <br>
  For more information, see the <a href="https://git-scm.com/docs/git-merge" rel="nofollow">Git Merge Documentation</a>
</div></div>

<ul><li><b>Values:</b> <code>FF</code>, <code>FF_ONLY</code>, <code>NO_FF</code></li></ul></li>
<li><code>mergeRemote : String</code> (optional)
<div><div>
 Name of the repository, such as <code>origin</code>, that contains the branch you specify below. If left blank, it'll default to the name of the first repository configured above.
</div></div>

</li>
<li><code>mergeStrategy</code> (optional)
<div><div>
 Merge strategy selection. <strong>This feature is not fully implemented in JGIT.</strong>
</div></div>

<ul><li><b>Values:</b> <code>DEFAULT</code>, <code>RESOLVE</code>, <code>RECURSIVE</code>, <code>OCTOPUS</code>, <code>OURS</code>, <code>SUBTREE</code>, <code>RECURSIVE_THEIRS</code></li></ul></li>
</ul></li>
</ul></div></li>
<li><code>pretestedIntegration</code><div>
<ul><li><code>gitIntegrationStrategy</code>
<ul><b>Nested Choice of Objects</b>
<li><code>accumulated</code><div>
<div><h2>Accumulated Commit Strategy</h2>
<div>
 This strategy merges your commits with the --no-ff switch
</div></div>
<ul><li><code>shortCommitMessage : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>ffonly</code><div>
<div><h2>Fast Forward only (--ff-only) Strategy</h2>
<div>
 This strategy fast-forward only using the --ff-only switch - or fails
</div></div>
<ul><li><code>shortCommitMessage : boolean</code> (optional)
</li>
</ul></div></li>
<li><code>squash</code><div>
<div><h2>Squashed Commit Strategy</h2>
<div>
 This strategy squashes all your commit on a given branch with the --squash option
</div></div>
<ul></ul></div></li>
</ul></li>
<li><code>integrationBranch : String</code>
<div><h3>What to specify</h3>
<p>The branch name must match your integration branch name. <b>No trailing slash.</b></p>
<h3>Merge is performed the following way</h3>
<h5>Squash commit</h5>
<pre>            git checkout -B &lt;Branch name&gt; &lt;Repository name&gt;/&lt;Branch name&gt;
            git merge --squash &lt;Branch matched by git&gt;
            git commit -C &lt;Branch matched by git&gt;</pre>
<h5>Accumulated commit</h5>
<pre>            git checkout -B &lt;Branch name&gt; &lt;Repository name&gt;/&lt;Branch name&gt;
            git merge -m &lt;commitMsg&gt; &lt;Branch matched by git&gt; --no-ff</pre>
<h3>When changes are pushed to the integration branch?</h3>
<p>Changes are only ever pushed when the build results is SUCCESS</p>
<pre>            git push &lt;Repository name&gt; &lt;Branch name&gt;</pre></div>

</li>
<li><code>repoName : String</code>
<div><div>
 <h3>What to specify</h3>
 <p>The repository name. In git the repository is always the name of the remote. So if you have specified a repository name in your Git configuration. You need to specify the exact same name here, otherwise no integration will be performed. We do the merge based on this.</p>
 <p><b>No trailing slash on repository name.</b></p>
 <p><span>Remember to specify this when working with NAMED repositories in Git</span></p>
</div></div>

</li>
</ul></div></li>
<li><code>pruneStaleBranch</code><div>
<div><div>
 Run "git remote prune" for each remote, to prune obsolete local branches.
</div></div>
<ul></ul></div></li>
<li><code>pruneTags</code><div>
<ul><li><code>pruneTags : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'RelativeTargetDirectory'</code><div>
<ul><li><code>relativeTargetDir : String</code>
<div><div>
 Specify a local directory (relative to <a rel="nofollow">the workspace root</a>) where the Git repository will be checked out. If left empty, the workspace root itself will be used. 
 <p>This extension should <strong>not</strong> be used in Jenkins Pipeline (either declarative or scripted). Jenkins Pipeline already provides standard techniques for checkout to a subdirectory. Use <a href="https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#ws-allocate-workspace" rel="nofollow">ws</a> and <a href="https://www.jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#dir-change-current-directory" rel="nofollow">dir</a> in Jenkins Pipeline rather than this extension.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'ScmName'</code><div>
<div><div>
 <p>Unique name for this SCM. Needed when using Git within the Multi SCM plugin.</p>
</div></div>
<ul><li><code>name : String</code>
</li>
</ul></div></li>
<li><code>$class: 'SparseCheckoutPaths'</code><div>
<div><div>
 <p>Specify the paths that you'd like to sparse checkout. This may be used for saving space (Think about a reference repository). Be sure to use a recent version of Git, at least above 1.7.10</p>
</div></div>
<ul><li><code>sparseCheckoutPaths</code>
<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
</li>
</ul></li>
</ul></div></li>
<li><code>submodule</code><div>
<ul><li><code>depth : int</code> (optional)
<div><div>
 Set shallow clone depth, so that git will only download recent history of the project, saving time and disk space when you just want to access the latest commits of a repository.
</div></div>

</li>
<li><code>disableSubmodules : boolean</code> (optional)
<div><div>
 By disabling support for submodules you can still keep using basic git plugin functionality and just have Jenkins to ignore submodules completely as if they didn't exist.
</div></div>

</li>
<li><code>parentCredentials : boolean</code> (optional)
<div><div>
 Use credentials from the default remote of the parent project.
</div></div>

</li>
<li><code>recursiveSubmodules : boolean</code> (optional)
<div><div>
 Retrieve all submodules recursively (uses '--recursive' option which requires git&gt;=1.6.5)
</div></div>

</li>
<li><code>reference : String</code> (optional)
<div><div>
 Specify a folder containing a repository that will be used by Git as a reference during clone operations.
 <br>
  This option will be ignored if the folder is not available on the controller or agent where the clone is being executed.
 <br>
  To prepare a reference folder with multiple subprojects, create a bare git repository and add all the remote urls then perform a fetch:
 <br>
 <pre>  git init --bare
  git remote add SubProject1 https://gitrepo.com/subproject1
  git remote add SubProject2 https://gitrepo.com/subproject2
  git fetch --all
  </pre>
</div></div>

</li>
<li><code>shallow : boolean</code> (optional)
<div><div>
 Perform shallow clone, so that git will not download the history of the project, saving time and disk space when you just want to access the latest version of a repository.
</div></div>

</li>
<li><code>threads : int</code> (optional)
<div><div>
 Specify the number of threads that will be used to update submodules.
 <br>
  If unspecified, the command line git default thread count is used.
 <br>
</div></div>

</li>
<li><code>timeout : int</code> (optional)
<div><div>
 Specify a timeout (in minutes) for submodules operations.
 <br>
  This option overrides the default timeout of 10 minutes. 
 <br>
  You can change the global git timeout via the property org.jenkinsci.plugins.gitclient.Git.timeOut (see <a href="https://issues.jenkins.io/browse/JENKINS-11286" rel="nofollow">JENKINS-11286</a>). Note that property should be set on both controller and agent to have effect (see <a href="https://issues.jenkins.io/browse/JENKINS-22547" rel="nofollow">JENKINS-22547</a>).
</div></div>

</li>
<li><code>trackingSubmodules : boolean</code> (optional)
<div><div>
 Retrieve the tip of the configured branch in .gitmodules (Uses '--remote' option which requires git&gt;=1.8.2)
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'UserExclusion'</code><div>
<ul><li><code>excludedUsers : String</code>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will ignore any revisions committed by users in this list when determining if a build needs to be triggered. This can be used to exclude commits done by the build itself from triggering another build, assuming the build server commits the change with a distinct SCM user. 
 <p></p> Using this behaviour will preclude the faster git ls-remote polling mechanism, forcing polling to require a workspace thus sometimes triggering unwanted builds, as if you had selected the <strong>Force polling using workspace</strong> extension as well. 
 <p></p>Each exclusion uses exact string comparison and must be separated by a new line. User names are only excluded if they exactly match one of the names in this list. 
 <p></p>
 <pre>auto_build_user</pre> The example above illustrates that if only revisions by "auto_build_user" have been committed to the SCM a build will not occur.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'UserIdentity'</code><div>
<ul><li><code>name : String</code>
<div><div>
 <p>If given, "GIT_COMMITTER_NAME=[this]" and "GIT_AUTHOR_NAME=[this]" are set for builds. This overrides whatever is in the global settings.</p>
</div></div>

</li>
<li><code>email : String</code>
<div><div>
 <p>If given, "GIT_COMMITTER_EMAIL=[this]" and "GIT_AUTHOR_EMAIL=[this]" are set for builds. This overrides whatever is in the global settings.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'WipeWorkspace'</code><div>
<div><div>
 Delete the contents of the workspace before building, ensuring a fully fresh workspace.
</div></div>
<ul></ul></div></li>
</ul></li>
<li><code>postBuildStatusToSpace : boolean</code> (optional)
<div><div>
 <p>If checked, Jenkins will automatically report the build to JetBrains Space. Adding any steps to the job or workflow definition will not be required.</p>
 <p>The build will be reported as running upon its start and as succeeded or failed upon its completion.</p>
 <p>Git commit and branch name for reporting will be taken from the GIT_COMMIT and GIT_BRANCH environment variables. These <a href="https://plugins.jenkins.io/git/#plugin-content-environment-variables" rel="nofollow">environment variables</a> are provided by the standard Jenkins Git plugin when source code is checked out from a git repository.</p>
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'StoreSCM'</code><div>
<ul><li><code>scriptName : String</code>
</li>
<li><code>repositoryName : String</code>
<div><div>
 Specify the name of the Store repository to be checked. It is assumed that the Smalltalk image being run by the "script" property will contain any necessary repository definitions.
</div></div>

</li>
<li><code>pundles</code>
<div><div>
 List the names of the top-level pundles (bundles and/or packages) to check for changes. All listed pundles and their recursive prerequisites will be checked.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>pundleType</code>
<ul><li><b>Values:</b> <code>PACKAGE</code>, <code>BUNDLE</code></li></ul></li>
<li><code>name : String</code>
</li>
</ul></li>
<li><code>versionRegex : String</code>
<div><div>
 Specify a Regex11-style regular expression that specifies which pundle versions to consider when checking for changes. Examples: 
 <ul>
  <li><b>.+</b> (the default) will match any version string</li>
  <li><b>\d+</b> will match any integer version number</li>
  <li><b>(7.9\s*-\s*)?\d+</b> will match any integer version number with an optional "7.9 - " prefix</li>
 </ul>
</div></div>

</li>
<li><code>minimumBlessingLevel : String</code>
<div><div>
 Choose the minimum Store blessing level that should be considered. Pundle versions with a lower blessing level will be ignored.
</div></div>

</li>
<li><code>generateParcelBuilderInputFile : boolean</code>
<div><div>
 Check this if Jenkins should generate an input file for ParcelBuilder or a similar tool. A ParcelBuilder input file specifies the type, name, and version of all of the Pundles that are part of the current build.
</div></div>

</li>
<li><code>parcelBuilderInputFilename : String</code>
<div><div>
 The name of the file, relative to the Jenkins workspace directory, where the input file for ParcelBuilder will be written.
</div></div>

</li>
</ul></div></li>
<li><span><a href="/doc/pipeline/steps/params/subversionscm"><code>$class: 'SubversionSCM'</code></a></span></li>
<li><code>$class: 'SurroundSCM'</code><div>
<ul><li><code>server : String</code>
</li>
<li><code>serverPort : String</code>
</li>
<li><code>branch : String</code>
</li>
<li><code>repository : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>rsaKey</code> (optional)
<ul><b>Nested Object</b>
<li><code>rsaKeyFileId : String</code> (optional)
</li>
<li><code>rsaKeyFilePath : String</code> (optional)
</li>
<li><code>rsaKeyType</code> (optional)
<ul><li><b>Values:</b> <code>NoKey</code>, <code>Path</code>, <code>ID</code></li></ul></li>
<li><code>rsaKeyValue : String</code> (optional)
</li>
</ul></li>
<li><code>rsaKeyFileId : String</code> (optional)
</li>
<li><code>rsaKeyFilePath : String</code> (optional)
<div><div>
 Enter the full path to the RSA key file for the Surround SCM connection. Example: C:\SurroundRSAKeyFile.xml
</div></div>

</li>
<li><code>rsaKeyPath : String</code> (optional)
</li>
</ul></div></li>
<li><code>$class: 'SynergySCM'</code><div>
<ul><li><code>project : String</code>
</li>
<li><code>database : String</code>
</li>
<li><code>release : String</code>
</li>
<li><code>purpose : String</code>
</li>
<li><code>username : String</code>
</li>
<li><code>password : String</code>
</li>
<li><code>engine : String</code>
</li>
<li><code>oldProject : String</code>
</li>
<li><code>baseline : String</code>
</li>
<li><code>oldBaseline : String</code>
</li>
<li><code>ccmHome : String</code>
</li>
<li><code>remoteClient : boolean</code>
</li>
<li><code>detectConflict : boolean</code>
</li>
<li><code>replaceSubprojects : boolean</code>
</li>
<li><code>checkForUpdateWarnings : boolean</code>
</li>
<li><code>leaveSessionOpen : boolean</code>
</li>
<li><code>maintainWorkarea : boolean</code>
</li>
<li><code>checkTaskModifiedObjects : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'VaultSCM'</code><div>
<ul><li><code>serverName : String</code>
<div><div>
 Specify the hostname or IP address of the vault server.
</div></div>

</li>
<li><code>path : String</code>
</li>
<li><code>userName : String</code>
</li>
<li><code>password : String</code>
</li>
<li><code>repositoryName : String</code>
</li>
<li><code>vaultName : String</code>
</li>
<li><code>sslEnabled : boolean</code>
</li>
<li><code>useNonWorkingFolder : boolean</code>
</li>
<li><code>merge : String</code>
</li>
<li><code>fileTime : String</code>
</li>
<li><code>makeWritableEnabled : boolean</code>
</li>
<li><code>verboseEnabled : boolean</code>
</li>
</ul></div></li>
<li><code>$class: 'hudson.plugins.gradle_repo.RepoScm'</code><div>
<ul><li><code>repositoryUrl : String</code>
</li>
<li><code>branch : String</code>
</li>
</ul></div></li>
<li><span><a href="/doc/pipeline/steps/params/hudsonpluginsreporeposcm"><code>$class: 'hudson.plugins.repo.RepoScm'</code></a></span></li>
</ul></li>
<li><code>id : String</code> (optional)
</li>
</ul></div></li>


++++