= $class: 'it.dockins.dockerslaves.spec.ContainerSetDefinition'
:page-layout: pipelinesteps
== $class: 'it.dockins.dockerslaves.spec.ContainerSetDefinition'

++++
<li><code>$class: 'it.dockins.dockerslaves.spec.ContainerSetDefinition'</code><div>
<ul><li><code>buildHostImage</code>
<div>Docker image used to host the build environment and run build steps. Using this option, you have full control on your build environment to make it fully reproducible and isolated from other builds. You can use <i>arbitrary</i> docker images here, setup with the builds tools required by your job. There's <u>no</u> prerequisites on the docker image as the jenkins infrastructure setup is handled transparently.</div>

<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'DockerSocketContainerDefinition'</code><div>
<ul><li><code>hints</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'MemoryHint'</code><div>
<ul><li><code>memory : String</code>
<div>Define Memory requirements for container format: <code>&lt;number&gt;&lt;unit&gt;</code>. Number is a positive integer. Unit can be one of b, k, m, or g. Minimum is 4m.</div>

</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'DockerfileContainerDefinition'</code><div>
<ul><li><code>contextPath : String</code>
</li>
<li><code>dockerfile : String</code>
</li>
<li><code>forcePull : boolean</code>
</li>
<li><code>hints</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'MemoryHint'</code><div>
<ul><li><code>memory : String</code>
<div>Define Memory requirements for container format: <code>&lt;number&gt;&lt;unit&gt;</code>. Number is a positive integer. Unit can be one of b, k, m, or g. Minimum is 4m.</div>

</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'ImageIdContainerDefinition'</code><div>
<ul><li><code>image : String</code>
</li>
<li><code>forcePull : boolean</code>
<div>Always pull the image before launching the container, to ensure the latest is ran during the build. Usefull if you use a <code>latest</code> image. Will slow down the build, but ensure you always run the up-to-date image.</div>

</li>
<li><code>hints</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'MemoryHint'</code><div>
<ul><li><code>memory : String</code>
<div>Define Memory requirements for container format: <code>&lt;number&gt;&lt;unit&gt;</code>. Number is a positive integer. Unit can be one of b, k, m, or g. Minimum is 4m.</div>

</li>
</ul></div></li>
</ul></li>
</ul></div></li>
</ul></li>
<li><code>sideContainers</code>
<div>Your build can rely on side images to host build resources, like a test database or application server to run the application you are building and testing.</div>

<ul><b>Array / List of Nested Object</b>
<li><code>name : String</code>
</li>
<li><code>spec</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'DockerSocketContainerDefinition'</code><div>
<ul><li><code>hints</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'MemoryHint'</code><div>
<ul><li><code>memory : String</code>
<div>Define Memory requirements for container format: <code>&lt;number&gt;&lt;unit&gt;</code>. Number is a positive integer. Unit can be one of b, k, m, or g. Minimum is 4m.</div>

</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'DockerfileContainerDefinition'</code><div>
<ul><li><code>contextPath : String</code>
</li>
<li><code>dockerfile : String</code>
</li>
<li><code>forcePull : boolean</code>
</li>
<li><code>hints</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'MemoryHint'</code><div>
<ul><li><code>memory : String</code>
<div>Define Memory requirements for container format: <code>&lt;number&gt;&lt;unit&gt;</code>. Number is a positive integer. Unit can be one of b, k, m, or g. Minimum is 4m.</div>

</li>
</ul></div></li>
</ul></li>
</ul></div></li>
<li><code>$class: 'ImageIdContainerDefinition'</code><div>
<ul><li><code>image : String</code>
</li>
<li><code>forcePull : boolean</code>
<div>Always pull the image before launching the container, to ensure the latest is ran during the build. Usefull if you use a <code>latest</code> image. Will slow down the build, but ensure you always run the up-to-date image.</div>

</li>
<li><code>hints</code> (optional)
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>$class: 'MemoryHint'</code><div>
<ul><li><code>memory : String</code>
<div>Define Memory requirements for container format: <code>&lt;number&gt;&lt;unit&gt;</code>. Number is a positive integer. Unit can be one of b, k, m, or g. Minimum is 4m.</div>

</li>
</ul></div></li>
</ul></li>
</ul></div></li>
</ul></li>
</ul></li>
</ul></div></li>


++++