= $class: 'RunFilterParameter'
:page-layout: pipelinesteps
== $class: 'RunFilterParameter'

++++
<li><code>$class: 'RunFilterParameter'</code><div>
<div><div>
 Defines a parameter that can be used for a build filter of Copy Artifact.
</div></div>
<ul><li><code>name : String</code>
</li>
<li><code>defaultFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code><div>
<ul><li><code>runFilterList</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>and</code><div>
</div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code><div>
</div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
</div></li>
<li><code>or</code><div>
<ul><li><code>runFilterList</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>and</code><div>
</div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
</div></li>
<li><code>or</code><div>
</div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>or</code><div>
<ul><li><code>runFilterList</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>and</code><div>
</div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code><div>
</div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
</div></li>
<li><code>or</code><div>
</div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>or</code><div>
</div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code><div>
<ul><li><code>runFilterList</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>and</code><div>
</div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
</div></li>
<li><code>or</code><div>
<ul><li><code>runFilterList</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>and</code><div>
</div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
</div></li>
<li><code>or</code><div>
</div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
</div></li>
<li><code>or</code><div>
<ul><li><code>runFilterList</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>and</code><div>
<ul><li><code>runFilterList</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>and</code><div>
</div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
</div></li>
<li><code>or</code><div>
</div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
</div></li>
<li><code>or</code><div>
</div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>or</code><div>
<ul><li><code>runFilterList</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>and</code><div>
<ul><li><code>runFilterList</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>and</code><div>
</div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code><div>
</div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
</div></li>
<li><code>or</code><div>
</div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>or</code><div>
</div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
<ul><li><code>runFilter</code>
<ul><b>Nested Choice of Objects</b>
<li><code>and</code><div>
<ul><li><code>runFilterList</code>
<ul><b>Array / List of Nested Choice of Objects</b>
<li><code>and</code><div>
</div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
</div></li>
<li><code>or</code><div>
</div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>displayName</code><div>
<ul><li><code>runDisplayName : String</code>
<div><div>
 Filter the run based on its display name. It accepts the first run that has the display name matching the given parameter. The iteration is done from newest to oldest run.
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'DownstreamRunFilter'</code><div>
<ul><li><code>upstreamProjectName : String</code>
<div><div>
 <p>Copy artifacts from a build that is a downstream of a build of the specified project. You can use variable expressions.</p>
 <p>Downstream builds are found using fingerprints of files. That is, a build that is triggerd from a build isn't always considered downstream, but you need to fingerprint files used in builds to let Jenkins track them.</p>
 <p>Note: "Downsteram build of" is applicable only to AbstractProject based projects (both upstream and downstream projects).</p>
 <dl>
  <dt>
   AbstractProject based projects:
  </dt>
  <dd>
   Freestyle projects
  </dd>
  <dd>
   Multi-configuration projects
  </dd>
  <dd>
   Maven projects
  </dd>
  <dt>
   Non AbstractProject based projects:
  </dt>
  <dd>
   Pipeline jobs (aka. Workflow jobs)
  </dd>
 </dl>
 <p></p>
</div></div>

</li>
<li><code>upstreamBuildNumber : String</code>
<div><div>
 The number of the build to find its downstream build. You can also specify display names. You can use variable expressions.
</div></div>

</li>
</ul></div></li>
<li><code>not</code><div>
</div></li>
<li><code>or</code><div>
</div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>or</code><div>
</div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>
<li><code>parameterized</code><div>
<ul><li><code>parameter : String</code>
<div><div>
 Specify the value passed via the parameter "Build filter for Copy Artifact". E.g. You specified "Build filter for Copy Artifact" as <code>PARAM</code>, specify <code>${PARAM}</code> here.
</div></div>

</li>
</ul></div></li>
<li><code>parameters</code><div>
<ul><li><code>paramsToMatch : String</code>
<div><div>
 <p>Jobs may be filtered to select only builds matching particular parameters or other build variables. Use PARAM=VALUE,... to list the parameter filter; this is the same syntax as described for multiconfiguration jobs in <i>Project name</i> except with parameters instead of axis values. For example, FOO=bar,BAZ=true examines only builds that ran with parameter FOO set to bar and the checkbox for BAZ was checked.</p>
</div></div>

</li>
</ul></div></li>
<li><code>saved</code><div>
<ul></ul></div></li>
</ul></li>
<li><code>description : String</code> (optional)
</li>
</ul></div></li>


++++