= scmManagerSvn
:page-layout: pipelinesteps
== scmManagerSvn

++++
<li><code>scmManagerSvn</code><div>
<ul><li><code>serverUrl : String</code>
<div><div>
 Specify the root URL of the SCM-Manager instance including the context path (such as <em>https://scm-manager.org/scm/</em>).
</div></div>

</li>
<li><code>repository : String</code>
<div><div>
 Select an existing repository from the SCM-Manager instance.
</div></div>

</li>
<li><code>id : String</code> (optional)
</li>
<li><code>credentialsId : String</code> (optional)
<div><div>
 Select valid credentials for the specified SCM-Manager instance.
</div></div>

</li>
<li><code>browser</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'Assembla'</code><div>
<ul><li><code>spaceName : String</code>
</li>
</ul></div></li>
<li><code>$class: 'BacklogRepositoryBrowser'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Set the project URL of Repository Browser used with this project. Sample of URL are shown below. 
 <ul>
  <li>https://demo.backlog.jp/projects/DORA</li>
 </ul>
 <p>When no value is set, project of "Backlog URL" set above is used.</p>
</div></div>

</li>
</ul></div></li>
<li><code>svnPhabricator</code><div>
<ul><li><code>url : String</code>
</li>
<li><code>repo : String</code>
</li>
</ul></div></li>
<li><code>$class: 'PolarionRepositoryBrowser'</code><div>
<ul><li><code>url : String</code>
</li>
<li><code>location : String</code>
</li>
</ul></div></li>
<li><code>$class: 'RedmineRepositoryBrowser'</code><div>
<ul><li><code>repositoryId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'SVNWeb'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ScmManagerSvnRepositoryBrowser'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://scm-manager.org/scm/repo/namespace/name</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'TeamForge'</code><div>
<ul><li><code>connectionFactory</code>
<ul><b>Nested Object</b>
<li><code>url : String</code>
<div><div>
 <p>This should be the URL of your Digital.ai TeamForge site. It should be of the form 'https://forge.collab.net'.</p>
</div></div>

</li>
<li><code>username : String</code>
<div><div>
 <p>The user who will upload the files.</p>
</div></div>

</li>
<li><code>password : String</code>
<div><div>
 <p>The password for the user specified above. If incorrectly given, the login to the Digital.ai TeamForge server will fail.</p>
</div></div>

</li>
</ul></li>
<li><code>project : String</code>
</li>
<li><code>repo : String</code>
</li>
</ul></div></li>
<li><code>$class: 'TracRepositoryBrowser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'ViewVCRepositoryBrowser'</code><div>
<ul><li><code>url : String</code>
</li>
<li><code>location : String</code>
</li>
</ul></div></li>
<li><code>$class: 'VisualSVN'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL of VisualSVN for this repository (such as <a href="https://demo-server.visualsvn.com/!/#tortoisesvn" rel="nofollow">https://demo-server.visualsvn.com/!/#tortoisesvn</a>).
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>excludes : String</code> (optional)
<div><div>
 Optionally specify branches to be excluded from builds using glob expressions.
</div></div>

</li>
<li><code>includes : String</code> (optional)
<div><div>
 Specify the branches to be build using glob expressions (like <em>trunk,branches/*,tags/*,sandbox/*</em>).
</div></div>

</li>
<li><code>workspaceUpdater</code> (optional)
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'CheckoutUpdater'</code><div>
<ul></ul></div></li>
<li><code>$class: 'NoopUpdater'</code><div>
<ul></ul></div></li>
<li><code>$class: 'UpdateUpdater'</code><div>
<ul></ul></div></li>
<li><code>$class: 'UpdateWithCleanUpdater'</code><div>
<ul></ul></div></li>
<li><code>$class: 'UpdateWithRevertUpdater'</code><div>
<ul></ul></div></li>
</ul></li>
</ul></div></li>


++++