= $class: 'SubversionSCM'
:page-layout: pipelinesteps
== $class: 'SubversionSCM'

++++
<li><code>$class: 'SubversionSCM'</code><div>
<div><div>
 Checks out the source code from Subversion repositories. See <a href="https://wiki.jenkins-ci.org/display/JENKINS/Subversion+Plugin#SubversionPlugin-Postcommithook" rel="nofollow">post-commit</a> hook set up for improved turn-around time and performance in polling.
</div></div>
<ul><li><code>locations</code>
<ul><b>Array / List of Nested Object</b>
<li><code>remote : String</code>
</li>
<li><code>credentialsId : String</code>
</li>
<li><code>local : String</code>
<div><div>
 Specify a local directory (relative to <a rel="nofollow">the workspace root</a>) where this module is checked out. If left empty, the last path component of the URL is used as the default, just like the svn CLI. A single period (<code>.</code>) may be used to check out the project directly into the workspace rather than into a subdirectory.
</div></div>

</li>
<li><code>depthOption : String</code>
<div><div>--depth option for checkout and update commands. Default value is infinity. 
 <ul>
  <li>empty includes only the immediate target of the operation, not any of its file or directory children.</li>
  <li>files includes the immediate target of the operation and any of its immediate file children.</li>
  <li>immediates includes the immediate target of the operation and any of its immediate file or directory children. The directory children will themselves be empty.</li>
  <li>infinity includes the immediate target, its file and directory children, its children's children, and so on to full recursion.</li>
  <li>as-it-is takes the working depth from the current working copy, allows for setting update depth manually using --set-depth option.</li>
 </ul> More information can be found <a href="http://svnbook.red-bean.com/en/1.7/svn.advanced.sparsedirs.html" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>ignoreExternalsOption : boolean</code>
<div><div>
 "--ignore-externals" option will be used with svn checkout, svn update commands to disable externals definition processing. 
 <p></p> More information can be found <a href="http://svnbook.red-bean.com/en/1.7/svn.advanced.externals.html" rel="nofollow">here</a>. 
 <br><b>Note:</b> there is the potential to leverage <code>svn:externals</code> to gain read access to the entire Subversion repository. This can happen if you follow the normal practice of giving Jenkins credentials with read access to the entire Subversion repository. You will also need to provide the credentials to use when checking/polling out the svn:externals using the <i>Additional Credentials</i> option.
</div></div>

</li>
<li><code>cancelProcessOnExternalsFail : boolean</code>
<div><div>
 Determines if the process should be cancelled when checkout/update svn:externals failed. Will work when "Ignore externals" box is not checked. Default choice is to cancelled the process when checkout/update svn:externals failed.
</div></div>

</li>
</ul></li>
<li><code>workspaceUpdater</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'CheckoutUpdater'</code><div>
<ul></ul></div></li>
<li><code>$class: 'NoopUpdater'</code><div>
<ul></ul></div></li>
<li><code>$class: 'UpdateUpdater'</code><div>
<ul></ul></div></li>
<li><code>$class: 'UpdateWithCleanUpdater'</code><div>
<ul></ul></div></li>
<li><code>$class: 'UpdateWithRevertUpdater'</code><div>
<ul></ul></div></li>
</ul></li>
<li><code>browser</code>
<ul><b>Nested Choice of Objects</b>
<li><code>$class: 'Assembla'</code><div>
<ul><li><code>spaceName : String</code>
</li>
</ul></div></li>
<li><code>$class: 'BacklogRepositoryBrowser'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Set the project URL of Repository Browser used with this project. Sample of URL are shown below. 
 <ul>
  <li>https://demo.backlog.jp/projects/DORA</li>
 </ul>
 <p>When no value is set, project of "Backlog URL" set above is used.</p>
</div></div>

</li>
</ul></div></li>
<li><code>svnPhabricator</code><div>
<ul><li><code>url : String</code>
</li>
<li><code>repo : String</code>
</li>
</ul></div></li>
<li><code>$class: 'PolarionRepositoryBrowser'</code><div>
<ul><li><code>url : String</code>
</li>
<li><code>location : String</code>
</li>
</ul></div></li>
<li><code>$class: 'RedmineRepositoryBrowser'</code><div>
<ul><li><code>repositoryId : String</code>
</li>
</ul></div></li>
<li><code>$class: 'SVNWeb'</code><div>
<ul><li><code>url : String</code>
</li>
</ul></div></li>
<li><code>$class: 'ScmManagerSvnRepositoryBrowser'</code><div>
<ul><li><code>repoUrl : String</code>
<div><div>
 Specify the root URL serving this repository (such as <em>https://scm-manager.org/scm/repo/namespace/name</em>).
</div></div>

</li>
</ul></div></li>
<li><code>$class: 'TeamForge'</code><div>
<ul><li><code>connectionFactory</code>
<ul><b>Nested Object</b>
<li><code>url : String</code>
<div><div>
 <p>This should be the URL of your Digital.ai TeamForge site. It should be of the form 'https://forge.collab.net'.</p>
</div></div>

</li>
<li><code>username : String</code>
<div><div>
 <p>The user who will upload the files.</p>
</div></div>

</li>
<li><code>password : String</code>
<div><div>
 <p>The password for the user specified above. If incorrectly given, the login to the Digital.ai TeamForge server will fail.</p>
</div></div>

</li>
</ul></li>
<li><code>project : String</code>
</li>
<li><code>repo : String</code>
</li>
</ul></div></li>
<li><code>$class: 'TracRepositoryBrowser'</code><div>
<ul></ul></div></li>
<li><code>$class: 'ViewVCRepositoryBrowser'</code><div>
<ul><li><code>url : String</code>
</li>
<li><code>location : String</code>
</li>
</ul></div></li>
<li><code>$class: 'VisualSVN'</code><div>
<ul><li><code>url : String</code>
<div><div>
 Specify the root URL of VisualSVN for this repository (such as <a href="https://demo-server.visualsvn.com/!/#tortoisesvn" rel="nofollow">https://demo-server.visualsvn.com/!/#tortoisesvn</a>).
</div></div>

</li>
</ul></div></li>
</ul></li>
<li><code>excludedRegions : String</code>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will ignore any files and/or folders in this list when determining if a build needs to be triggered. 
 <p></p> Each exclusion uses regular expression pattern matching, and must be separated by a new line. 
 <p></p>
 <pre>	/trunk/myapp/src/main/web/.*\.html
	/trunk/myapp/src/main/web/.*\.jpeg
	/trunk/myapp/src/main/web/.*\.gif
  </pre> The example above illustrates that if only html/jpeg/gif files have been committed to the SCM a build will not occur. 
 <p></p> More information on regular expressions can be found <a href="http://www.regular-expressions.info/" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>excludedUsers : String</code>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will ignore any revisions committed by users in this list when determining if a build needs to be triggered. This can be used to exclude commits done by the build itself from triggering another build, assuming the build server commits the change with a distinct SCM user. 
 <p></p>Each exclusion uses literal pattern matching, and must be separated by a new line. 
 <p></p>
 <pre>	 auto_build_user
  </pre> The example above illustrates that if only revisions by "auto_build_user" have been committed to the SCM a build will not occur.
</div></div>

</li>
<li><code>excludedRevprop : String</code>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will ignore any revisions that are marked with the given revision property (revprop) when determining if a build needs to be triggered. This can be used to exclude commits done by the build itself from triggering another build, assuming the build server commits the change with the correct revprop. 
 <p></p>This type of exclusion only works with Subversion 1.5 servers and newer. 
 <p></p>More information on revision properties can be found <a href="http://svnbook.red-bean.com/en/1.5/svn.advanced.props.html" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>excludedCommitMessages : String</code>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will ignore any revisions with commit messages containing any of the given regular expressions when determining if a build needs to be triggered.
</div></div>

</li>
<li><code>includedRegions : String</code>
<div><div>
 If set, and Jenkins is set to poll for changes, Jenkins will ignore any files and/or folders that are <b><i>not</i></b> in this list when determining if a build needs to be triggered. 
 <p></p> Each inclusion uses regular expression pattern matching, and must be separated by a new line. 
 <p></p> This is useful when you need to check out an entire resource for building, but only want to do the build when a subset has changed. 
 <p></p>
 <pre>	/trunk/myapp/c/library1/.*
	/trunk/myapp/c/library2/.*
  </pre> If /trunk/myapp is checked out, the build will only occur when there are changes to either the c/library1 and c/library2 subtrees. 
 <p></p> If there are also excluded regions specified, then a file is not ignored when it is in the included list and <b><i>not</i></b> in the excluded list. 
 <p></p> More information on regular expressions can be found <a href="http://www.regular-expressions.info/" rel="nofollow">here</a>.
</div></div>

</li>
<li><code>ignoreDirPropChanges : boolean</code>
<div><div>
 If set, Jenkins ignores svn-property only changes of directories. These changes are ignored when determining whether a build should be triggered and are removed from a build's changeset. Main usage of this property is to ignore svn:mergeinfo changes (which would otherwise e.g. lead to a complete rebuild of a maven project, in spite of incremental build option).
</div></div>

</li>
<li><code>filterChangelog : boolean</code>
<div><div>
 If set Jenkins will apply the same inclusion and exclusion patterns for displaying changelog entries as it does for polling for changes. If this is disabled, changes which are excluded for polling are still displayed in the changelog.
</div></div>

</li>
<li><code>additionalCredentials</code>
<div><div>
 <p>If there are additional credentials required in order to obtain a complete checkout of the source, they can be provided here.</p>
 <p>The <strong>realm</strong> is how the repository self-identifies to a client. It usually has the following format:</p>
 <p><code>&lt;proto://host:port&gt; Realm Name</code></p>
 <ul>
  <li><code>proto</code> is the protocol, e.g. <code>http</code> or <code>svn</code>.</li>
  <li><code>host</code> is the host how it's accessed by Jenkins, e.g. as IP address <code>192.168.1.100</code>, host name <code>svnserver</code>, or host name and domain <code>svn.example.org</code>.</li>
  <li><code>port</code> is the port, even if not explicitly specified. By default, this is <code>80</code> for HTTP, <code>443</code> for HTTPS, 3690 for the <code>svn</code> protocol.</li>
  <li><code>Realm Name</code> is how the repository self-identifies. Common options include <code>VisualSVN Server</code>, <code>Subversion Authentication</code> or the UUID of the repository.</li>
 </ul>
 <p>To find out the realm, you could do any of the following:</p>
 <ul>
  <li>If you access the repository via HTTP or HTTPS: Open the repo in a web browser without saved credentials. It will use the <code>Realm Name</code> (see above) in the authentication dialog.</li>
  <li>Use the command line <code>svn</code> program. 
   <ul>
    <li>If you don't have stored the credentials, run e.g. <code>svn info https://svnserver/repo</code> and it will tell you the realm when asking you to enter a password, e.g.: <em>Authentication realm: &lt;svn://svnserver:3690&gt; VisualSVN Server</em>.</li>
    <li>If you have already stored the credentials to access the repository, look for the realm name in one of the files in <code>~/.subversion/auth/svn/simple</code>; it will be two lines below the line <code>svn:realmstring</code>.</li>
   </ul></li>
  <li>When accessing a repository via the <code>svn+ssh</code> protocol, the realm has the format <code>username@svn+ssh://host:port</code> – note that the username is <em>before</em> the <code>svn+ssh://</code> (unlike the URL used for normal SVN operations), and that there are no angle brackets and no realm name. For this protocol the default port is 22.</li>
 </ul>
 <p>Make sure to enter the realm <em>exactly</em> as shown, starting with a <code>&lt;</code> (except for repositories accessed via <code>svn+ssh</code> – see above).</p>
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>realm : String</code>
<div><div>
 This is the realm that the SvnKit library associates with a specific checkout. For most Subversion servers this will typically be of the format <code>&lt;<i>scheme</i>://<i>hostname</i>(:<i>port</i>)&gt; <i>name</i></code>, while for servers accessed via <code>svn+ssh</code> it is of the format <code>(<i>username</i>@)svn+ssh://<i>hostname</i>(:<i>port</i>)</code>.
</div></div>

</li>
<li><code>credentialsId : String</code>
<div><div>
 Select the credential from the list of relevant credentials in order to use that credential for checking out the source code.
</div></div>

</li>
</ul></li>
<li><code>quietOperation : boolean</code>
<div><div>
 <p>Mimics subversion command line <code>--quiet</code> parameter for <strong>check out / update</strong> operations to help keep the output shorter. Prints nothing, or only summary information.</p>
</div></div>

</li>
</ul></div></li>


++++