= $class: 'YouTrackProjectProperty'
:page-layout: pipelinesteps
== $class: 'YouTrackProjectProperty'

++++
<li><code>$class: 'YouTrackProjectProperty'</code><div>
<ul><li><code>siteName : String</code>
</li>
<li><code>pluginEnabled : boolean</code>
</li>
<li><code>commentsEnabled : boolean</code>
<div>Adds a link to the build as a comment of all issues mentioned in the commit comment</div>

</li>
<li><code>commandsEnabled : boolean</code>
<div><p>Enabling makes it possible to execute commands from the VCS commit message. It is inspired by how YouTrack integrates with TeamCity, as described <a href="http://confluence.jetbrains.com/display/YTD4/Executing+Commands+from+Comment+to+VCS+Commit" rel="nofollow">here</a>. It does however not support batch commands.</p>
<p>In short after <code>#issue-id</code> the rest of the line is interpreted as a command an sent to YouTrack. If the next line does not contain a # it will be considered as a comment to the command applied.</p>
<p>An extra option in this integration is to write <code>!#issue-id command</code> and the command will be applied, but silently, that is, watchers of the issue will not be notified.</p></div>

</li>
<li><code>runAsEnabled : boolean</code>
<div>Run the command from the commit comments as a YouTrack user with the same e-mail as the commit user. For this feature to work, the user set in the YouTrack configuration should have the "Update project" permission for the projects to run commands in.</div>

</li>
<li><code>annotationsEnabled : boolean</code>
<div>When this setting is on the change log descriptions will be annotation with links to the mentioned YouTrack issues. The tooltip will show the description of the issue in question. The data will be fetched by the user set in the site configuration. This can cause users to see data they would not be able to see in YouTrack.</div>

</li>
<li><code>linkVisibility : String</code>
<div>The link back to this build can be set to be visibile only for a specific YouTrack group. Empty means no specific group will be set.</div>

</li>
<li><code>stateFieldName : String</code>
<div>Here you set the field name of the field containing the issue state</div>

</li>
<li><code>fixedValues : String</code>
<div>Set the values that is considered fixed, this will be used in the Fixed in build buldstep</div>

</li>
<li><code>silentCommands : boolean</code>
<div>Stops YouTrack from notifying users about the changes performed by the commands executed on all commit commands executed from this plugin.</div>

</li>
<li><code>silentLinks : boolean</code>
<div>Checking this stops YouTrack from notifying the users about the comment link being posted to the issue.</div>

</li>
<li><code>executeProjectLimits : String</code>
<div>This field is a comma separated list of project ids in which commands will be applied. When nothing is specified the command will be applied regardless of the project.</div>

</li>
<li><code>trackCommits : boolean</code>
<div><p>Enabling this will globally store the revision ids for the comment and use this to prevent commits being processed multiple times. This is useful if there is a job per branch. The commit ids processed will be stored in Jenkins, so if the jobs for each branch is on different Jenkins intances this will not work.</p>
<p>This option has to be checked for all jobs were the same commit can be in the changelog, i.e. if there is a development job and a production job, then the option has to be checked for both.</p></div>

</li>
<li><code>project : String</code>
</li>
<li><code>commentText : String</code>
<div><p>The text for the comment to send to YouTrack for linking back to this build. It defaults to the URL for the build and the revision id(s) for the change(s). Setting a text here overrides that.</p>
<p>The text is interpreted by the Groovy SimpleTemplateEngine, see <a href="http://groovy.codehaus.org/api/groovy/text/SimpleTemplateEngine.html" rel="nofollow"> http://groovy.codehaus.org/api/groovy/text/SimpleTemplateEngine.html </a>.</p>
<p>There are two variables available: build and entries, where build is an object of type <a href="http://javadoc.jenkins-ci.org/hudson/model/AbstractBuild.html" rel="nofollow"><code>hudson.model.AbstractBuild</code></a> and entries is a list of <a href="http://javadoc.jenkins-ci.org/hudson/scm/ChangeLogSet.Entry.html" rel="nofollow"><code>hudson.scm.ChangeLogSet.Entry</code></a> objects. Therefore a template can be something like:</p>
<pre>    Related build: $build.absoluteUrl&lt;% entries.each { %&gt;
    [Change: ${it.commitId}|http://sourcecodebrowser?change=${it.commitId}]
    &lt;% } %&gt;
</pre></div>

</li>
<li><code>failureMode</code>
<div>This property determines how to fail the build if the commands cannot be applied to YouTrack</div>

<ul><li><b>Values:</b> <code>NONE</code>, <code>UNSTABLE</code>, <code>FAILURE</code></li></ul></li>
<li><code>commentTextSecure</code>
<div><p>The text for the comment to send to YouTrack for linking back to this build. It defaults to the URL for the build and the revision id(s) for the change(s). Setting a text here overrides that.</p>
<p>The text you enter is executed as a Groovy script</p>
<p>There are two variables available: build and entries, where build is an object of type <a href="http://javadoc.jenkins-ci.org/hudson/model/AbstractBuild.html" rel="nofollow"><code>hudson.model.AbstractBuild</code></a> and entries is a list of <a href="http://javadoc.jenkins-ci.org/hudson/scm/ChangeLogSet.Entry.html" rel="nofollow"><code>hudson.scm.ChangeLogSet.Entry</code></a> objects. Therefore a template can be something like:</p>
<pre>    def result = ""
    result += "Related build: $build.absoluteUrl\n"
    entries.each {
        result += "[Change: ${it.commitId}|http://sourcecodebrowser?change=${it.commitId}]\n"
    }
    result
</pre></div>

<ul><b>Nested Object</b>
<li><code>script : String</code>
</li>
<li><code>sandbox : boolean</code>
<div><div>
 If checked, run this Groovy script in a sandbox with limited abilities. If unchecked, and you are not a Jenkins administrator, you will need to wait for an administrator to approve the script.
</div></div>

</li>
<li><code>classpath</code>
<div><div>
 Additional classpath entries accessible from the script.
</div></div>

<ul><b>Array / List of Nested Object</b>
<li><code>path : String</code>
<div><div>
 A path or URL to a JAR file. This path should be approved by an administrator or a user with the RUN_SCRIPT permission, or the script fails. If the file or files are once approved, they are treated approved even located in another path.
</div></div>

</li>
<li><code>oldPath : String</code> (optional)
</li>
<li><code>shouldBeApproved : boolean</code> (optional)
</li>
</ul></li>
<li><code>oldScript : String</code> (optional)
</li>
</ul></li>
</ul></div></li>


++++