= WAR file


The Jenkins Web application ARchive (WAR) file bundles link:https://github.com/jenkinsci/winstone[Winstone],
a link:https://www.eclipse.org/jetty/[Jetty] servlet container wrapper,
and can be started on any operating system or platform with a version of Java supported by Jenkins.
See the xref:platform-information:support-policy-java.adoc[Java Requirements] page for details.

include::user-docs:installing-jenkins:partial$_installation_requirements.adoc[]

== Run the WAR file

The Jenkins Web application ARchive (WAR) file can be started from the command line like this:

. Download the link:https://www.jenkins.io/download[latest Jenkins WAR file] to an appropriate directory on your machine
. Open up a terminal/command prompt window to the download directory
. Run the command `java -jar jenkins.war`
. Browse to `\http://localhost:8080` and wait until the *Unlock Jenkins* page appears
. Continue on with the xref:#setup-wizard[Post-installation setup wizard] below

*Notes:*

* This process does not automatically install any specific plugins.
  They need to installed separately via the
  xref:managing:index.adoc[**Manage Jenkins**] >
  xref:managing:plugins.adoc[**Plugins**] page in Jenkins.
* You can change the port by specifying the `--httpPort` option when you run the
  `java -jar jenkins.war` command. For example, to make Jenkins accessible
  through port 9090, then run Jenkins using the command: +
  `java -jar jenkins.war --httpPort=9090`
* You can change the directory where Jenkins stores its configuration with the `JENKINS_HOME` environment variable.
  For example, to place the Jenkins configuration files in a subdirectory named `my-jenkins-config`, define `JENKINS_HOME=my-jenkins-config` before running the `java -jar jenkins.war` command.
  Use the Windows commands:
+
.Windows
[source]
----
C:\Temp > set JENKINS_HOME=my-jenkins-config
C:\Temp > java -jar jenkins.war
----
+
or the Unix command:
+
.Unix
[source]
----
JENKINS_HOME=my-jenkins-config java -jar jenkins.war
----

For more details of command line arguments that can adjust Jenkins startup, use the command: +
`java -jar jenkins.war --help`

include::user-docs:installing-jenkins:partial$_setup-wizard.adoc[]
