= Security validator for Jenkins Kubernetes Operator

*Project goal:* Improve security aspects of installing Jenkins plugins in Kubernetes environment.

*Skills to study/improve:* Go, Kubernetes, Bash

== Details 
=== Project Details

The link:https://github.com/jenkinsci/kubernetes-operator[Jenkins Operator] is a Kubernetes Native Operator which manages operations for Jenkins on Kubernetes.
It enables  community to run Jenkins in cloud-native environments like Kubernetes, OpenShift and others. Also, supports most of the public cloud providers (AWS, Azure, GCP) in terms of additional capabilities like backups, observability and cloud security.

* Visit the link:https://github.com/jenkinsci/kubernetes-operator[project page]
* Follow link:https://jenkinsci.github.io/kubernetes-operator/docs/developer-guide/[developer guide] and run Jenkins Operator locally

If you are interested in exploring Kubernetes and software-defined operators ecosystem more in-depth, as well as enhance your Go coding skill - this is definitely an interesting opportunity to consider.

== Problem Statement

Some of the plugins have security warnings which are not properly presented to the end users. This may result in introducing security risk in existing CI/CD infrastructure.

As part of reconciliation process of Jenkins, when plugins are already downloaded but not yet installed add a validation step that will check if chosen plugins contain security issues, using link:https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/[Kubernetes Admission Controller].
It can be implemented by taking an advantage of built-in security check mechanism in Jenkins Update Centre - the operator should fetch the data directly from Jenkins Download Center (over REST API) about security warnings for corresponding list of plugins to be installed.

Additionally, in case a security warning is detected, user should be able to choose if Jenkins Operator should continue with installation process.

* link:https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html[Webhook implementation cron tutorial]
* link:https://sdk.operatorframework.io/docs/building-operators/ansible/reference/webhooks/[Operator SDK  Ansible webhooks reference]

== Newbie Friendly Issues

For information about how to contribute to and what to work on, please use the slack channel. Since the project is in active development, these issues could be closed by the time you are looking at them.

== Skills to improve/study

* Go
* Kubernetes
* link:https://sdk.operatorframework.io/[Operator SDK]
* REST API
* JSON
* Bash
* Jenkins Update Centre

== Potential Mentors 
image:images:ROOT:avatars/no_image.svg[,width=30,height=30] Sylwia Brant
image:images:ROOT:avatars/no_image.svg[,width=30,height=30] Jakub Al-Khalili
image:images:ROOT:avatars/no_image.svg[,width=30,height=30] Bartek Antoniak

== Links

* https://github.com/jenkinsci/kubernetes-operator#community[chat]
* xref:gsoc:index.adoc#office-hours[Meetings]

== Organization Links 

* xref:gsoc:index.adoc[Jenkins GSoC page] - documentation, application guidelines
* xref:community:ROOT:index.adoc[Participate and contribute to Jenkins] - landing page for newcomer contributors
* https://issues.jenkins.io/issues/?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20labels%20%3D%20newbie-friendly%20[Newbie-friendly issues] - list of organization-wide newbie-friendly issues (use them if there is no links in the project idea)
> xref:2021/project-ideas.adoc[Go back to other GSoC 2021 project ideas]
