= Get connected with the Jenkins community!

There are many ways to connect to the Jenkins community!

== Follow us on social media

We do our best to spread the word about Jenkins in social media.
It helps us to communicate the Jenkins vision, highlight achievements, and attract new contributors.
Follow us and share the posts with your network!

* **Twitter:** link:https://twitter.com/jenkinsci[@jenkinsci], 
  link:https://twitter.com/jenkins_release[@jenkins_release],
  and other local and language group community channels.
* **LinkedIn:** link:https://www.linkedin.com/company/jenkins-project[Jenkins Project]
* **YouTube:** link:https://www.youtube.com/c/jenkinscicd[Official Jenkins channel]
* **Discourse:** link:https://community.jenkins.io/[community.jenkins.io]
* **Reddit:** link:https://www.reddit.com/r/jenkinsci/[/r/jenkinsci]

Want to help with managing our social media?
Join the xref:sigs:advocacy-and-outreach:index.adoc#social-media[Advocacy and Outreach SIG] that coordinates the effort!

== Join our chats and forums

There are many communication channels in the Jenkins community and its entities.
You are welcome to join these channels and participate in discussions.
Here are the key ones:

* xref:mailing-lists:index.adoc[Mailing lists] - We use mailing lists for async communications and xref:project:ROOT:governance.adoc[open governance].
* xref:community:chat:index.adoc[Chat: Gitter, IRC, Slack, etc.] - Realtime and async communications in the community.
* https://community.jenkins.io/[community.jenkins.io] - our new community forum on Discourse.
  Jenkins end users, developers and contributors are welcome!

Note that language groups and local communities might be using separate channels.
See link:https://community.jenkins.io/c/language-groups/14[Language Groups on Discourse] for some references.

== Join our events!

You can also join our events and xref:meet.adoc[meet Jenkins users and contributors!].
