= Participate and Contribute

++++
<style>
.doc {
  display: flex;
  flex-wrap: wrap;
}

.doc .sidebarblock {
  margin:1rem;
}
</style>
++++

There are many ways to engage with the Jenkins project and community. Here are the most common ways to get you started. Welcome aboard!

[.participate-connect]
.CONNECT
****
Join our communication channels, discuss and help us spread the word!

[.button]
xref:connect.adoc[Read More]
****

[.participate-meet]
.MEET
****
Meet other Jenkins users and share your experiences by organizing and attending events and meetups.

[.button]
xref:meet.adoc[Read More]
****

[.participate-code]
.CODE
****
Do you enjoy writing code? There are numerous plugins and components for you to contribute to.

[.button]
xref:code.adoc[Read More]
****

[.participate-help]
.HELP
****
As an experienced user, you can help others get the most out of Jenkins.

[.button]
xref:help.adoc[Read More]
****

[.participate-translate]
.TRANSLATE
****
If you're fluent in languages other than English, consider improving support for those languages.

[.button]
xref:dev-docs:internationalization:index.adoc[Read More]
****

[.participate-test]
.TEST
****
You can help prevent regressions by contributing automated tests.

[.button]
xref:test.adoc[Read More]
****

[.participate-document]
.DOCUMENT
****
Improve the documentation to make it easier for others to get started.

[.button]
xref:document.adoc[Read More]
****

[.participate-design]
.DESIGN
****
As it is intended for daily use by finicky web developers, design is essential.

[.button]
xref:design.adoc[Read More]
****

[.participate-review]
.REVIEW
****
Help review changes to code or documentation.

[.button]
xref:review-changes.adoc[Read More]
****

[.participate-donate]
.DONATE
****
If you have no time but want to help, we accept money to facilitate project goals.

[.button]
xref:meet.adoc[Read More]
****
