= About the Author
:page-layout: author
:page-author_name: Marky Jackson
:page-github: markyjackson-taulia
:page-authoravatar: ../../images/images/avatars/markyjackson-taulia.png
:page-twitter: markyjackson5

Hi! Super happy you found me here. I’m Marky Jackson and I am a lover of family, friends and a die-hard San Francisco Giants fan. I left my heart in San Francisco in the summer of 2020 and now reside in San Diego, California.
I am a founder and research scientist at [methodair](https://methodair.org) with a focus on [project-julie](https://github.com/methodair/project-julie).
I was previously a Jenkins Goverence Board as well as the Jenkins Events Officer, a Kubernetes Org member, a Kubernetes Release Manager Associate, a Continuous Delivery Foundation Ambassador, a Jenkins core contributor, a Jenkins Google Summer of Code org admin and mentor, a Google Summer of Docs org admin and mentor, and helped with software development and community management on the Ortelius Project.
I have had profiles in the CNCF and other mediums. In the past I have spoken publicly and enjoyed writing blogs on technical topics. Previously, I was named the Most Valuable Jenkins Advocate.
Finally, I was previously a mentoring lead within the Kubernetes project as well as a previous Kubernetes Outreachy coordinator for the Kubernetes project.

You can find me on Twitter @markyjackson5 or on GitHub @markyjackson-taulia.