= Upgrading to Jenkins LTS 2.150.x

Each section covers the upgrade from the previous LTS release, the section on 2.150.1 covers the upgrade from 2.138.4.

== Upgrading to Jenkins 2.150.3

No notable changes requiring upgrade notes.

== Upgrading to Jenkins 2.150.2

=== Possible authentication problems

link:https://www.jenkins.io/security/advisory/2019-01-16/#SECURITY-901[SECURITY-901]

The security fixes in 2.150.2 require that security realms call `SecurityListener#authenticated` or `SecurityListener#loggedIn` after successful authentication.
If a security realm does not do either, sessions will be invalidated immediately, and users logged out again.

To disable this security fix when using a security realm that does not call `SecurityListener`, set the link:/doc/book/managing/system-properties/[Java system property] `jenkins.security.seed.UserSeedProperty.disableUserSeed` to `true`.

Affected plugins and their status is tracked https://wiki.jenkins.io/display/JENKINS/Plugins+affected+by+the+SECURITY-901+fix[on the Jenkins wiki].

== Upgrading to Jenkins 2.150.1

NOTE: 2.150.1 and 2.138.4 were released on the same day. Please note that this upgrade guide only covers the upgrade from 2.138.4. See link:/doc/upgrade-guide/2.138/[it's upgrade guide] for information related to upgrading from 2.138.3.

No notable changes requiring upgrade notes.
