= Upgrading to Jenkins LTS 2.164.x

Each section covers the upgrade from the previous LTS release, the section on 2.164.1 covers the upgrade from 2.150.3.

== Upgrading to Jenkins 2.164.3

No notable changes requiring upgrade notes.

== Upgrading to Jenkins 2.164.2

No notable changes requiring upgrade notes.

== Upgrading to Jenkins 2.164.1

=== Changes related to Java 11 compatibility

Some plugins use JAXB libraries provided by the JDK.
However, the `java.xml.bind` and `javax.activation` modules are no longer included in OpenJDK 11, and plugins might fail if no replacement is offered.

To fix this problem, we've bundled those libraries into a new detached plugin: link:https://plugins.jenkins.io/jaxb[JAXB plugin].
When Jenkins 2.164 or newer is running on Java 11, this plugin is automatically installed.
However, if you manage your plugins outside Jenkins (for example, if you use `plugins.txt` in your Docker images), you might need to explicitly install the plugin.

Many further changes related to Java 11 have been implemented since 2.150.3.
See the changelog for a list, and the following documentation for an overview of Java 11 compatibility:

* link:/doc/administration/requirements/upgrade-java-guidelines/[Upgrading Jenkins Java version from 8 to 11]
* link:/doc/book/installing/[Installing Jenkins]
* https://wiki.jenkins.io/display/JENKINS/Known+Java+11+Compatibility+issues[Known Java 11 Compatibility issues]
* https://wiki.jenkins.io/display/JENKINS/Java+11+Developer+Guidelines[Java 11 Developer Guidelines]
