= Upgrading to Jenkins LTS 2.235.x

Each section covers the upgrade from the previous LTS release, the section on 2.235.1 covers the upgrade from 2.222.4.

== Upgrading to Jenkins 2.235.5

=== Docker Alpine image overhaul

The base images of the Alpine-based Docker images for Jenkins (`jenkins/jenkins:lts-alpine` and similar) and various agent images have been replaced and are now based on images provided by the AdoptOpenJDK project.

For details, see the release notes:

* https://github.com/jenkinsci/docker-agent/releases/tag/4.3-8[https://github.com/jenkinsci/docker-agent/releases/tag/4.3-8]
* https://github.com/jenkinsci/docker-inbound-agent/releases/tag/4.3-9[https://github.com/jenkinsci/docker-inbound-agent/releases/tag/4.3-9]
* https://github.com/jenkinsci/docker-ssh-agent/releases/tag/3.0.0[https://github.com/jenkinsci/docker-ssh-agent/releases/tag/3.0.0]

== Upgrading to Jenkins 2.235.4

=== New Windows Installer

Beginning with Jenkins LTS release link:/changelog-stable/#v2.235.3[2.235.3], the same Windows installer is used in the stable release as has been used since April 2020 in the weekly release.
The new Windows installer was announced in a link:/blog/2019/02/01/windows-installers/[blog post].

Jenkins administrators on Windows may choose to continue using and upgrading their existing installation using the mechanism in the Jenkins UI, or they may choose to migrate to the new Windows installer.

==== Upgrade with existing installation

Jenkins administrators on Windows are offered new Jenkins versions from within the "Manage Jenkins" page of their installation.
After the initial installation of Jenkins on Windows, administrators perform upgrades through the "Manage Jenkins" page.
Administrators generally do not use the Jenkins MSI installer to perform a Jenkins upgrade because the upgrade is simple and easy from within Jenkins itself.

Administrators that choose to continue using their existing installation will continue to be able to upgrade to new Jenkins versions.
Settings in the Jenkins installation can be modified by editing the `jenkins.exe.config` file and other configuration files.

In this configuration, Jenkins will continue to use the 32 bit Java Runtime Environment that was included with the previous installer unless `jenkins.exe.config` has been modified to use a 64 bit Java Runtime Environment.
It will similarly continue to use the default port and service account unless it has been modified locally.

==== Upgrade with new Windows Installer

The new Windows installer provides the following additional features:

* Choose a 64 bit Java 8 or 64 bit Java 11 installation to run Jenkins
* Choose the port that Jenkins will use
* Choose the user account and password that will run the Jenkins service

In addition to those choices, the Jenkins home directory is created in the standard AppData location rather than in `C:\Program Files (x86)\Jenkins`.
You'll find the Jenkins home directory in the `%LocalAppData%` of the user account that runs the Jenkins service.
For example, if the user account running the Jenkins service is named `jservice`, then the Jenkins home directory will be in `C:\Users\jservice\AppData\Local\Jenkins.jenkins`.
Once Jenkins is running, the 'System Information' page within 'Manage Jenkins' displays the properties and variables that describe the Jenkins installation.

Upgrading an existing Windows installation to the new installer requires:

. Stop and disable the existing Jenkins service from the Windows Service Manager
. Run the new installer to create the new installation with desired settings
. Stop the newly installed Jenkins service
. Copy existing Jenkins configuration files to the new Jenkins home directory
. Start the newly installed Jenkins service
. Confirm newly installed Jenkins service is behaving as expected

See the link:/blog/2019/02/01/windows-installers/[Windows installer blog post] for more details.

== Upgrading to Jenkins 2.235.3

=== Repository Signing Key Update

Beginning with Jenkins LTS release link:/changelog-stable/#v2.235.3[2.235.3], stable repositories will be signed with the same GPG keys that sign the weekly repositories.
Administrators of Linux systems must install the new signing keys on their Linux servers before installing Jenkins 2.235.3.

==== Debian/Ubuntu

Update Debian compatible operating systems (Debian, Ubuntu, Linux Mint Debian Edition, etc.) with the command:

.Debian/Ubuntu
[source,bash]
----
# wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -
----

==== Red Hat/CentOS

Update Red Hat compatible operating systems (Red Hat Enterprise Linux, CentOS, Fedora, Oracle Linux, Scientific Linux, etc.) with the command:

.Red Hat/CentOS
[source,bash]
----
# rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
----

See the link:/blog/2020/07/27/repository-signing-keys-changing/[blog post] for more details.

== Upgrading to Jenkins 2.235.2

No notable changes requiring upgrade notes.

== Upgrading to Jenkins 2.235.1

=== Plugin manager improvements

The plugin manager interface includes significant improvements.
Those improvements include a change in the "Available" tab.

The "Available" tab previously listed all available plugins then filtered based on the value in the "search" field.
The "Available" tab now lists no plugins until the user enters a value in the "search" field.
Users who previously scrolled through over 1000 plugins to find their plugin will now need to enter a value in the search field.

=== Auto refresh removed

link:https://issue-redirect.jenkins.io/issue/19828[JENKINS-19828]

The "Enable auto refresh" capability has been removed from Jenkins 2.235.1.
Auto refresh causes serious Jenkins performance issues if a user enables auto refresh on an expensive page and leaves their browser open on that page.
Auto refresh breaks form data entry by requiring that the form must be submitted before the next refresh or entered data will be lost.
Auto refresh breaks expandable list views.

Page refresh extensions are available for popular web browsers like Google Chrome and Mozilla Firefox.
Users that need automatic refresh of a Jenkins page should install one of those extensions.
