= Upgrading to Jenkins LTS 2.401.x

Each section covers the upgrade from the previous LTS release, the section on 2.401.1 covers the upgrade from 2.387.3.

== Upgrading to Jenkins 2.401.3

No notable changes requiring upgrade notes.

== Upgrading to Jenkins 2.401.2

No notable changes requiring upgrade notes.

== Upgrading to Jenkins 2.401.1

=== Simplify loading of JavaScript and CSS

A custom JavaScript library, `jenkins-js-modules` has been removed from Jenkins core.
Users of the https://plugins.jenkins.io/dependency-track[OWASP Dependency Track] plugin must upgrade to 4.3.1 or newer.
Users of the https://plugins.jenkins.io/servicenow-cicd[ServiceNow CI/CD] plugin must upgrade to 2.1 or newer.

=== WebSocket is default command line interface mode

The default connection mode for the Java link:/doc/book/managing/cli/[command line interface] client is now `-webSocket`.

You can specify `-http` to continue to use the former default (for example because you are running Jenkins in a servlet container other than the recommended built-in Jetty, or because you are running an unusual reverse proxy which does not support WebSocket).
You can also continue to specify `-ssh` to use SSH transport (for example because you prefer to authenticate with a private key rather than an API token), or use a native SSH client.

If you use the Jenkins CLI but cannot make WebSocket connections to the Jenkins controller, you will now need to pass the `-http` or `-ssh` option if you were not already doing so.
