= Upgrading to Jenkins LTS 2.440.x

Each section covers the upgrade from the previous LTS release, the section on 2.440.1 covers the upgrade from 2.426.3.

== Upgrading to Jenkins 2.440.3

No notable changes requiring upgrade notes.

== Upgrading to Jenkins 2.440.2

NOTE: These upgrades are not specific to the 2.440.2 release, but are crucial for Jenkins users.

=== OpenJDK Upgrade

Due to a recent change in the upstream OpenJDK, users may encounter a breaking change if they do not upgrade and restart their Java processes.
When upgrading the Java runtime to OpenJDK 11.0.22 and later or 17.0.10 and later, you must restart the Java process.
This practice applies to both controllers and agents: when upgrading the Java runtime on the controller, restart the Java process on the controller; when upgrading the Java runtime on the agent, restart the Java process on the agent.

Details of the issue are available in https://issue-redirect.jenkins.io/issue/72665[JENKINS-72665].

=== Jakarta Plugin Upgrades

Users that have the https://plugins.jenkins.io/jakarta-mail-api[Jakarta Mail API] and https://plugins.jenkins.io/jakarta-activation-api[Jakarta Activation API] plugins installed in their Jenkins instance must update both plugins to the latest version in lockstep.
If the https://github.com/jenkinsci/jakarta-mail-api-plugin/releases/tag/jakarta-mail-api-2.1.3-1[Jakarta Mail] and https://github.com/jenkinsci/jakarta-activation-api-plugin/releases/tag/jakarta-activation-api-2.1.3-1[Activation] API plugins are not updated subsequently this will cause a breaking change.
As with any update or upgrade we advise link:/doc/book/system-administration/backing-up/[backing up] your instance and upgrading all plugins before and after you update Jenkins.

== Upgrading to Jenkins 2.440.1

=== Upgrade to the latest version of Remoting

The `-jnlpUrl pass:c[${JENKINS_URL}]/computer/pass:c[${AGENT_NAME}]/jenkins-agent.jnlp` argument to the agent JAR has been deprecated; use `-url pass:c[${JENKINS_URL}]` and `-name pass:c[${AGENT_NAME}]` instead, potentially also passing in `-webSocket`, `-tunnel`, and/or work directory options as needed.
Make sure you reset all inbound launcher options to defaults, and follow new guidance for command-line options for agent.jar.
The official Docker images are already using the new calling convention.

=== Replace diskSpaceMonitor with diskSpace in configuration as code

Improvements in node monitoring (agents and the controller) include a change in the configuration as code definition for nodeMonitors.
Jenkins LTS 2.426.3 and earlier used `diskSpaceMonitor` to configure the free space threshold for agents.
Jenkins LTS 2.440.1 and later use `diskSpace` to configure the free space threshold for agents.

If `diskSpaceMonitor` is used in Jenkins 2.440.1 and later, a warning message is displayed that says:

[source]
----
Configuration as Code obsolete file format:
    'diskSpaceMonitor' is obsolete, please use 'diskSpace'
----

Replace the `diskSpaceMonitor` entry with `diskSpace` to resolve the warning.
