= Extension Points defined in Display URL API Plugin

https://plugins.jenkins.io/display-url-api[Display URL API Plugin]

== DisplayURLDecorator

`jenkinsdoc:display-url-api:org.jenkinsci.plugins.displayurlapi.DisplayURLDecorator]`

+++ An extension point for decorating the URLs presented to users by the+++ jenkinsdoc:DisplayURLProvider] +++. Use cases include+++ +++ decorating URLs with {@code utm_source} etc tracking parameters in order to measure the usage rate of different URLs+++ +++ generated by Jenkins.+++


**Implementations:**

_(no known implementations)_


== DisplayURLProvider

`jenkinsdoc:display-url-api:org.jenkinsci.plugins.displayurlapi.DisplayURLProvider]`

+++ Generates URLs for well known UI locations for use in notifications (e.g. mailer, HipChat, Slack,+++ +++ IRC, etc) Extensible to allow plugins to override common URLs (e.g. Blue Ocean or another future+++ +++ secondary UI)+++


**Implementations:**

* https://plugins.jenkins.io/display-url-api[Display URL API Plugin]: org.+++<wbr/>+++jenkinsci.+++<wbr/>+++plugins.+++<wbr/>+++displayurlapi.+++<wbr/>+++**ClassicDisplayURLProvider** (link:https://github.com/jenkinsci/display-url-api-plugin/search?q=ClassicDisplayURLProvider&type=Code[view on GitHub])
* https://plugins.jenkins.io/display-url-api[Display URL API Plugin]: org.+++<wbr/>+++jenkinsci.+++<wbr/>+++plugins.+++<wbr/>+++displayurlapi.+++<wbr/>+++**DisplayURLProvider.+++<wbr/>+++DisplayURLProviderImpl** (link:https://github.com/jenkinsci/display-url-api-plugin/search?q=DisplayURLProvider.DisplayURLProviderImpl&type=Code[view on GitHub])

