= Pipeline documentation improvements - Phase 2 and Phase 3

*Project goal:* Improving the navigation and implementation of the Pipeline Steps Reference
*Skills to study/improve:* Documentation, Web development, Jenkins plugins
*Potential Mentors:* 
krisstern
berviantoleo

== Background

Continuing from https://www.jenkins.io/projects/gsoc/2022/projects/pipeline-step-documentation-generator/[the GSoC 2022 Pipeline Step Documentation Generator project] as Phase 2 of that project.
More to do during this Phase 2 and the next Phase 3, as we will need to include both the refinement of the detailing and the navigation design.
The project will involve the adopting of multiple plugins and improving their Pipeline Steps documentation.
The selected contributor is expected to do lots of writing, exploring, testing, but not lots of coding.

== Quick Start

Studying all materials relevant to https://www.jenkins.io/projects/gsoc/2022/projects/pipeline-step-documentation-generator/[the GSoC 2022 Pipeline Step Documentation Generator project] and become familiar with them.

== Skills to Study and Improve

* Jenkins plugin development life cycle
* Documentation
* Web UI/UX design for documentation
* Testing Jenkins plugins

== Project Difficulty Level
Beginner to Intermediate

== Project Size
175 to 350 hours (depending on the scope)

== Expected Outcomes

Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase.