= Improving Jenkinsfile Runner abilities and GitHub Actions

*Project goal:* To investigate the current state of the Jenkinsfile Runner project and to improve its abilities as well as those of GitHub Actions when used in conjunction
*Skills to study/improve:* Java, Jenkinsfile Runner, Docker, GitHub Actions
*Potential Mentors:* 
jonesbusy
krisstern
berviantoleo

== Background

This project idea is a continuation of the xref:gsoc:2022:projects:jenkinsfile-runner-action-for-github-actions.adoc/[GSoC 2022 Jenkinsfile Runner Action for GitHub Actions project].
The current https://github.com/jenkinsci/jenkinsfile-runner[Jenkninsfile Runner project] will need to switch to Spring Security 6, Jetty 12, as well as Jakarta EE 9 as part of its modernization.
We would like to encourage more adoption and compatibility with the latest Jenkins version.
There are many open issues within this project.
We will also need to work on reporting on GitHub checks.

== Skills to Study and Improve

* Java
* To run Jenkinsfile Runner (an incubating project) to create an action inside Docker
* Docker configuration
* GitHub Actions configuration
* Jenkins modernization

== Project Size
175 - 350 hours

== Project Difficulty Level
Intermediate to Advanced

== Expected Outcomes

Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase.