= Antora
// Settings
ifdef::env-gitlab[:outfilesuffix: .adoc]
// Project URLs
:url-project: https://antora.org
:url-docs: https://docs.antora.org
:url-org: https://gitlab.com/antora
:url-repo: {url-org}/antora
:url-demo-repos: {url-org}/demo
:url-ui-repo: {url-org}/antora-ui-default
:url-issues: {url-repo}/issues
:url-ci-pipelines: {url-repo}/pipelines
:url-chat: https://antora.zulipchat.com
:url-twitter: https://twitter.com/antoraproject
:url-twitter-hash: https://twitter.com/hashtag/antora?src=hash
// External URLs
:url-asciidoctor: https://asciidoctor.org
:url-choco: https://chocolatey.org
:url-node-releases: https://nodejs.org/en/about/releases/
:url-nvm: https://github.com/creationix/nvm
:url-nvm-install: {url-nvm}#installation
:url-nvm-windows: https://github.com/coreybutler/nvm-windows
:url-opendevise: https://opendevise.com
:url-git-credential-store: https://git-scm.com/docs/git-credential-store
// Versions:
:version-node-major: 18
:version-node: 18.12.0

{url-project}[Antora] is a modular, multi-repository site generator designed for creating documentation sites from content composed in AsciiDoc(R) and processed with {url-asciidoctor}[Asciidoctor].

Antora's toolchain and workflow help documentation and engineering teams create, manage, collaborate on, remix, and publish documentation sites sourced from multiple versioned git repositories without needing expertise in web technologies, build automation, or system administration.

This project includes a command line interface (CLI) and a site generator so you can quickly start publishing documentation sites with Antora.

== Code of Conduct

The Antora project and its project spaces are governed by our xref:CODE-OF-CONDUCT.adoc[Code of Conduct].
By participating, you're agreeing to honor this code.
Let's work together to make this a welcoming, professional, inclusive, and safe environment for everyone.

== Quickstart

This section offers a basic tutorial for evaluating Antora.
More comprehensive installation instructions are in the {url-docs}[Antora documentation].

=== Prerequisites

Antora is built on Node.js and is verified to work on Linux, macOS, and Windows.
To install Antora, you'll need Node.js (including npm, which is bundled with Node.js) on your system.
You may also find the base build tools for your OS helpful (which includes `git`), though they're not required.
We recommend using the active long term support (LTS) release of Node.js.
While you can use other versions of Node.js, Antora is only tested against {url-node-releases}[LTS releases].

To check whether you have Node.js installed, and which version, open a terminal and type:

 $ node -v

If this command fails with an error, it means you don't yet have Node.js installed.
If the command doesn't report a Node.js LTS version (e.g., v{version-node}), you don't have a suitable version of Node.js installed.

The best way to install Node.js is to use {url-nvm}[nvm] (Node Version Manager).
If your package manager provides Node.js and npm packages, _and you're familiar with using the tools installed system-wide_, you may choose to go that route.
However, we believe you'll be more successful if you choose nvm.

NOTE: Most CI environments use nvm to manage the version of Node.js used in the build job.
By using nvm, you can align your local setup with the environment used to generate and publish your production site.

If you're using Linux or macOS, follow {url-nvm-install}[the nvm installation instructions] to set up nvm on your machine.
If you're using Windows, you can install the {url-nvm-windows}[Windows port of nvm] via the {url-choco}[Chocolatey package manager] using `choco install -y nvm`.
Alternatively, you can install the active LTS release of Node.js directly using `choco install -y nodejs-lts`.

Once you've installed nvm, open a *new* terminal and install the active Node.js LTS release using:

 $ nvm install --lts

IMPORTANT: If you're using nvm for Windows, you must enter the full version of Node.js when running commands (e.g., `nvm install {version-node}`, `nvm use {version-node}`).
Run `nvm list available` to see a list of available Node.js versions.

To make Node.js {version-node-major} the default in new terminals (Linux and macOS only), type:

[subs=attributes+]
 $ nvm alias default {version-node-major}

Switch to this version of Node.js using the following command:

[subs=attributes+]
 $ nvm use {version-node-major}

Now that you have Node.js installed, you can install Antora.

==== Gulp CLI

You'll need the Gulp command-line interface (CLI) to run the build.
The Gulp CLI package provides the `gulp` command which, in turn, executes the version of Gulp declared by the project.

You can install the Gulp CLI globally (which resolves to a location in your user directory if you're using nvm) using the following command:

 $ npm install -g gulp-cli

Verify the Gulp CLI is installed and on your PATH by running:

 $ gulp --version

If you prefer to install global packages using Yarn, run this command instead:

 $ yarn global add gulp-cli

Alternately, you can use the `gulp` command that is installed by the project's dependencies.

 $ npx --offline gulp --version

Now that you have the prerequisites installed, you can fetch and build the UI project.

=== Clone and Initialize the UI Project

Clone the default UI project using git:

[subs=attributes+]
 $ git clone {url-project} &&
   cd "`basename $_`"

The example above clones Antora's default UI project and then switches to the project folder on your filesystem.
Stay in this project folder when executing all subsequent commands.

Use npm to install the project's dependencies inside the project.
In your terminal, execute the following command:

 $ npm install

This command installs the dependencies listed in [.path]_package.json_ into the [.path]_node_modules/_ folder inside the project.
This folder does not get included in the UI bundle and should _not_ be committed to the source control repository.

[TIP]
====
If you prefer to install packages using Yarn, run this command instead:

 $ yarn
====

=== Preview the UI

The default UI project is configured to preview offline.
The files in the [.path]_preview-src/_ folder provide the sample content that allow you to see the UI in action.
In this folder, you'll primarily find pages written in AsciiDoc.
These pages provide a representative sample and kitchen sink of content from the real site.

To build the UI and preview it in a local web server, run the `preview` command:

 $ gulp preview

You'll see a URL listed in the output of this command:

....
[12:00:00] Starting server...
[12:00:00] Server started http://localhost:5252
[12:00:00] Running server
....

Navigate to this URL to preview the site locally.

While this command is running, any changes you make to the source files will be instantly reflected in the browser.
This works by monitoring the project for changes, running the `preview:build` task if a change is detected, and sending the updates to the browser.

Press kbd:[Ctrl+C] to stop the preview server and end the continuous build.

=== Package for Use with Antora

If you need to package the UI so you can use it to generate the documentation site locally, run the following command:

 $ gulp bundle

If any errors are reported by lint, you'll need to fix them.

When the command completes successfully, the UI bundle will be available at [.path]_build/ui-bundle.zip_.
You can point Antora at this bundle using the `--ui-bundle-url` command-line option.

If you have the preview running, and you want to bundle without causing the preview to be clobbered, use:

 $ gulp bundle:pack

The UI bundle will again be available at [.path]_build/ui-bundle.zip_.

==== Source Maps

The build consolidates all the CSS and client-side JavaScript into combined files, [.path]_site.css_ and [.path]_site.js_, respectively, in order to reduce the size of the bundle.
{url-source-maps}[Source maps] correlate these combined files with their original sources.

This "`source mapping`" is accomplished by generating additional map files that make this association.
These map files sit adjacent to the combined files in the build folder.
The mapping they provide allows the debugger to present the original source rather than the obfuscated file, an essential tool for debugging.

In preview mode, source maps are enabled automatically, so there's nothing you have to do to make use of them.
If you need to include source maps in the bundle, you can do so by setting the `SOURCEMAPS` environment variable to `true` when you run the bundle command:

 $ SOURCEMAPS=true gulp bundle

In this case, the bundle will include the source maps, which can be used for debugging your production site.

== Copyright and License

Copyright (C) 2017-present OpenDevise Inc. and the Antora Project.

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.

== Authors

Development of Antora is led and sponsored by {url-opendevise}[OpenDevise Inc].
