= Mailing Lists

The Jenkins project uses https://en.wikipedia.org/wiki/Electronic_mailing_list[mailing lists] to communicate. These mailing lists are organized by topic (see below). Posting to the wrong mailing list will just result in your message being ignored. Please strive to be clear and concise when sending messages. https://www.catb.org/esr/faqs/smart-questions.html[How to ask questions the smart way.]

To subscribe to a mailing list, send an empty email to the "subscribe" email address.

WARNING: Due to heavy spam volume, we have enabled moderation of a user`s first post on some of these lists. This may result in delays in delivering your first email to these lists. For this reason, you should not re-send your email if it doesn`t appear on the list straight away.

== English-language discussion lists

=== mailto:jenkinsci-users@googlegroups.com[jenkinsci-users@googlegroups.com] 

Mailing list for users of Jenkins. Post your questions on how to use Jenkins and Jenkins plugins here.

NOTE: If you`re not sure which list is correct, post here.

https://groups.google.com/group/jenkinsci-users/topics[archive] | mailto:jenkinsci-users+subscribe@googlegroups.com[subscribe] | mailto:jenkinsci-users+unsubscribe@googlegroups.com[unsubscribe]

=== mailto:jenkinsci-board@googlegroups.com[jenkinsci-board@googlegroups.com]

Mailing list to contact https://www.jenkins.io/project/board/[Jenkins board members.]

NOTE: the subscription to this mailing list is reserved to Jenkins board members.

https://groups.google.com/group/jenkinsci-board/topics[archive] | mailto:jenkinsci-board+subscribe@googlegroups.com[subscribe] | mailto:jenkinsci-board+unsubscribe@googlegroups.com[unsubscribe]

[#jenkinsci-dev-googlegroups-com]
=== mailto:jenkinsci-dev@googlegroups.com[jenkinsci-dev@googlegroups.com] 

Mailing list for developers of Jenkins. Post your Jenkins core development and plugin development questions here, as well as topics related to project governance.

Questions that should be asked on the jenkinsci-users list will be ignored. That means your email will be moderated and not posted to the list. Do not cross-post.

https://groups.google.com/group/jenkinsci-dev/topics[archive] | mailto:jenkinsci-dev+subscribe@googlegroups.com[subscribe] | mailto:jenkinsci-dev+unsubscribe@googlegroups.com[unsubscribe]

[#jenkins-advocacy-and-outreach-sig-googlegroups-com]
=== mailto:jenkins-advocacy-and-outreach-sig@googlegroups.com[jenkins-advocacy-and-outreach-sig@googlegroups.com]

Mailing list for events, meet-ups, outreach programs, and fostering local communities.

https://groups.google.com/group/jenkins-advocacy-and-outreach-sig/topics[archive] | mailto:jenkins-advocacy-and-outreach-sig+subscribe@googlegroups.com[subscribe] | mailto:jenkins-advocacy-and-outreach-sig+unsubscribe@googlegroups.com[unsubscribe]

[#jenkins-infra-googlegroups-com]
=== mailto:jenkins-infra@googlegroups.com[jenkins-infra@googlegroups.com]

Mailing list for jenkins.io operations and https://www.jenkins.io/projects/infrastructure/[Jenkins Infrastructure].

https://groups.google.com/group/jenkins-infra/topics[archive] | mailto:jenkins-infra+subscribe@googlegroups.com[subscribe] | mailto:jenkins-infra+unsubscribe@googlegroups.com[unsubscribe]

== Governance board mailing list

=== mailto:jenkinsci-board@googlegroups.com[jenkinsci-board@googlegroups.com]

Mailing list to contact https://www.jenkins.io/project/board/[Jenkins board members.]

The subscription to this mailing list is reserved to Jenkins board members. Do not send messages to this list for support with your Jenkins instance or plugins.

https://groups.google.com/group/jenkinsci-board/topics[archive] | mailto:jenkinsci-board+subscribe@googlegroups.com[subscribe] | mailto:jenkinsci-board+unsubscribe@googlegroups.com[unsubscribe]


== Read-only lists

=== mailto:jenkinsci-advisories@googlegroups.com[jenkinsci-advisories@googlegroups.com]

Security Advisory announcements are sent to this list. xref:security:ROOT:index.adoc[More about security in Jenkins]

https://groups.google.com/group/jenkinsci-advisories/topics[archive] | mailto:jenkinsci-advisories+subscribe@googlegroups.com[subscribe] | mailto:jenkinsci-commits+unsubscribe@googlegroups.com[unsubscribe]

=== mailto:jenkinsci-commits@googlegroups.com[jenkinsci-commits@googlegroups.com]

Automated core and plugin commit notifications.

https://groups.google.com/group/jenkinsci-commits/topics[archive] | mailto:jenkinsci-commits+subscribe@googlegroups.com[subscribe] | mailto:jenkinsci-commits+unsubscribe@googlegroups.com[unsubscribe]

== Special Interest Groups Mailing Lists

=== mailto:jenkins-advocacy-and-outreach-sig@googlegroups.com[jenkins-advocacy-and-outreach-sig@googlegroups.com]

Mailing list for xref:sigs:advocacy-and-outreach:index.adoc[Advocacy and Outreach] group.

https://groups.google.com/group/jenkins-advocacy-and-outreach-sig/topics[archive] | mailto:jenkins-advocacy-and-outreach-sig+subscribe@googlegroups.com[subscribe] | mailto:jenkins-advocacy-and-outreach-sig+unsubscribe@googlegroups.com[unsubscribe]